### ISSUE TITLE
Changing the FlatFloatFromRight shadow color

### ISSUE THREAD

**Issue by iSimar** [aksonov/react-native-router-flux#10]
It seems to be white right now, how can you use a different color?

**Comment by aksonov** [comment]
You could give PR? Actually I'm looking for real 'native-looking' iOS transitions, but still unsuccessfully. Btw, you could use any own animations and set it to Schema or Router directly.

**Comment by iSimar** [comment]
ok I will try to look into it and reopen. Closing for now.

**Comment by RomanTsegelskyi** [comment]
@aksonov Is this still impossible to change?
