### ISSUE TITLE
Tabbar and Modals

### ISSUE THREAD

**Issue by perrosnk** [aksonov/react-native-router-flux#1003]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.0
- react-native v0.3.0

I need some help with the tabbar and Modals.

``` javascript
      <Router>
        <Scene key="root" >
          <Scene    key="initialScreen" component={InitialScreen} title="initialScreen"
            initial={true}
            navigationBarStyle= {{backgroundColor: 'white'}} onRight={() => Actions.signIn()} rightTitle='Sign in'/>
          <Scene key="signIn"        component={SignIn}     title="Sign In" />

          <Scene key= 'mainApp' tabs={true} hideNavBar={true}>
            <Scene key="feeds"       component={Feeds}      title="Feed"       icon= {TabIcon}/>
            <Scene key="home"        component={Home}       title="Home"     icon= {TabIcon} initial={true} />
            <Scene key='searchSend'     title='Send' icon= {TabIcon} >
              <Scene key="search"    component={Search}     title="Search"      hideTabBar onLeft={()=> Actions.home()} leftTitle="Back"/>
              <Scene key="send"      component={Send}       title="Send"      hideTabBar onLeft={()=> Actions.home()} leftTitle="Close"/>
            </Scene>
          </Scene>
        </Scene>
      </Router>
```
1. I want the 'searchSend' tab to open like a Modal window.
   2.On the subsequent screens (Search, Send) I want onLeft,  to close the modal and show the previous screen which could be either 'feeds' or 'home'. The command Actions.pop(), doesn't seem to work.
2. On the 'send' screen I cannot configure the leftTitle. I want to show 'Close', but all it shows is a left arrow < which redirects the user to the previous screen which is 'search'.
3. On the 'send' screen there is an Alert.alert() popover, and onPress 'OK' I want to close the modal and show the previous screen, which is either 'home' or 'feeds'. {Actions} don't seem to work on this screen as it doesn't do anything.

Is it possible to do all these without using redux?
Thank you very much!

**Comment by bhaumikdesai91** [comment]
I want to remove the back button when the scene is presented as modal but, I want to keep the navigation bar. This is also not happening.
