### ISSUE TITLE
Push Scene from a tab

### ISSUE THREAD

**Issue by sarovin** [aksonov/react-native-router-flux#1007]
I have a problem when i try to push a scene from a tab:

Example:

```javascript
<scene key="home" tabs>
	<scene key="a" icon={...} ... />
	<scene key="b" icon={...} initial ... >
		<scene key="1" ... />
	</scene>
	<scene key="c" icon={...} ... />
	<scene key="d" icon={...} ... />
</scene>
```

in the scene with key="b" i have a button:

```javascript
<Button onPress={Actions.search}>
	Complete
</Button>
```

when i press the button i can see this with REDUX:

`action Object {key: "search", type: "REACT_NATIVE_ROUTER_FLUX_PUSH"}`

but the scene not change...

If i change scenarios like this:

```javascript
<scene key="home" tabs>
	<scene key="a" icon={...} ... />
	<scene key="b" icon={...} initial ... />
	<scene key="c" icon={...} ... />
	<scene key="d" icon={...} ... />
        <scene key="1" ... />
</scene>
```

when i press the button i can see this with REDUX:

`action Object {key: "search", type: "REACT_NATIVE_ROUTER_FLUX_JUMP"}`

the render work but i can't see the back button in the navbar.

**Comment by sarovin** [comment]
I want a persistent tabbar ( search, notification, UserProfile ) and push other scene from search or notification or userProfile with a back button in the navbar.

**Comment by andrispraulitis** [comment]
I use clone to achieve this:

`<scene key="search" clone>
<scene key="home" tabs>...`

**Comment by sarovin** [comment]
I have this error:
`is not tab bar, jump action is not valid`

**Comment by andrispraulitis** [comment]
Can you paste full scene setup?

**Comment by sarovin** [comment]
```javascript
<RouterWithRedux>
  <Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar selector={...} unmountScenes tabs >
      <Scene key="auth" >
        <Scene key="welcome" />
        ...
      </Scene>
      <Scene key="search" clone />
      <Scene key="main" tabs >
        <Scene key="list" icon={...} />
        <Scene key="localize" icon={...} tabs initial >
          <Scene key="a" icon={...} />
          <Scene key="b" icon={...} />
        </Scene>
        <Scene key="profile" icon={...} />
      </Scene>
    </Scene>
  </Scene>
</RouterWithRedux>
```

i want push the "search" scene from "a" .

**Comment by andrispraulitis** [comment]
You never said "search" is a tab, so by default type is jump. Not sure how to get this working. Why do you need "root" as tabs?

**Comment by sarovin** [comment]
because the root is a selector component...

**Comment by andrispraulitis** [comment]
Why don't you do it facebook F8App style to do the switch for auth?

**Comment by sarovin** [comment]
There is a limit with the tab?

**Comment by andrispraulitis** [comment]
Probably not, but for me it's too complex if every scene is a tab...

**Comment by sarovin** [comment]
I think so too, i can remove the third tab but i want a persistent tab at the bottom. 
Maybe the tabs is not the right way.

**Comment by andrispraulitis** [comment]
I assume you want to persist main tabs.

From your scene setup "auth, search, main" makes no sense to be a tab because as I see it you are not navigating/jumping between them, are you?

**Comment by sarovin** [comment]
Yes, but i want to show the main tabs ( with list, localize and profile and not with auth, search,main)  after the login action.
So if the user is authenticated then show the main tabs.

**Comment by andrispraulitis** [comment]
Try type replace for auth and main and remove tabs from root

**Comment by andrispraulitis** [comment]
I meant reset not replace, sorry

**Comment by aksonov** [comment]
@sarovin To solve problem what to do - to jump or to push for given actions[key], two keys are actually created actions[key] for jump and actions[key+'_'] for push, maybe you could try to add '_' and check how it works.

**Comment by sarovin** [comment]
The solution is this:

```javascript
<RouterWithRedux>
  <Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar selector={...} unmountScenes tabs >
      <Scene key="auth" >
        <Scene key="welcome" />
        ...
      </Scene>
      <Scene key="main" >
        <Scene key="search" />
        <Scene key="tabs" tabs initial >
          <Scene key="list" icon={...} />
          <Scene key="localize" icon={...} tabs initial >
            <Scene key="a" icon={...} />
            <Scene key="b" icon={...} />
          </Scene>
          <Scene key="profile" icon={...} />
        </Scene>
      </Scene>
    </Scene>
  </Scene>
</RouterWithRedux>
```

**Comment by andrispraulitis** [comment]
That looks about right since you would never navigate to scene in same level as main once logged in
