### ISSUE TITLE
React Warnings

### ISSUE THREAD

**Issue by digitaldavenyc** [aksonov/react-native-router-flux#1009]
Following the [mini-tutorial](https://github.com/aksonov/react-native-router-flux/blob/master/docs/MINI_TUTORIAL.md) and I'm receiving a lot of warning messages from react, it's showing 7 times just on initially loading with a pretty basic config.

```
ExceptionsManager.js:76 Warning: You are manually calling a React.PropTypes validation function for the `initialAction` prop on `NavigationRootContainer`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

Properties warning is thrown on `initialAction`, `linkingActionMap`, `persistenceKey`, `reducer`, `renderNavigation` and `onNavigate`
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v0.30.0
### Expected behaviour

No warnings from react
### Actual behaviour

Warnings from react
### Steps to reproduce

`index.ios.js`

```
<Router>
    <Scene key="root">
        <Scene key="splash" component={Splash} title="Splash" initial={true}></Scene>
    </Scene>
</Router>
```

`splash.js`

```
<View style={{margin: 128}}>
    <Text onPress={Actions.Board}>Splash Logo</Text>
</View>
```

**Comment by shiv86** [comment]
http://stackoverflow.com/questions/38690502/manually-calling-a-react-proptypes-validation-react-native-0-30-0/38715799#38715799

**Comment by markortiz** [comment]
Same here to me on android

- react-native-router-flux v3.32.0
- react-native v0.30.0

**Comment by abakhsh** [comment]
+1

**Comment by steida** [comment]
Upgrade to React Native 0.31 will fix it. You can disable warning as well.

**Comment by itinance** [comment]
Upgrade to 0.31 will not fix it

**Comment by steida** [comment]
@itinance Try update React (but should not be required), it works for me.

**Comment by itinance** [comment]
Unfortunately not here:

    "react": "15.3.0",
    "react-native": "0.31.0",
    "react-native-router-flux": "^3.30.0",

I've fixed it by myself directly in the node_modules folder and have removed all proptypes

**Comment by cwbutler** [comment]
I was able to fix this problem by keeping my react dependency locked at 15.2.1

> "react": "15.2.1",
"react-native": "0.31.0",
"react-native-router-flux": "^3.30.0",

react-native@0.31.0 has a peerDependency for react@15.2.1

[https://github.com/facebook/react-native/blob/0.31-stable/package.json#L124](https://github.com/facebook/react-native/blob/0.31-stable/package.json#L124)

Once I did this the warnings went away.

**Comment by RakanNimer** [comment]
Solved in version 3.35.0

**Comment by OrianeInMoon** [comment]
still appear in v4.0.0-beta.12

**Comment by einomi** [comment]
The problem disappeared for me after upgrading to React 16.0.0
