### ISSUE TITLE
Get current route stack/stack size

### ISSUE THREAD

**Issue by mangogogos** [aksonov/react-native-router-flux#101]
Is there an exposed API for this? Right now Im reading the internal navigator's getCurrentRoutes value but would prefer not to have to dig into the __navigator ref.

**Comment by aksonov** [comment]
Please check latest 2.0 version and Actions.currentRouter property.

**Comment by mangogogos** [comment]
Excellent API redesign, thanks!

**Comment by getnashty** [comment]
what happened to this?
