### ISSUE TITLE
react-native-message-bar usage [Question]

### ISSUE THREAD

**Issue by shiv86** [aksonov/react-native-router-flux#1011]
Is there anyway to setup https://github.com/KBLNY/react-native-message-bar. So that it can be initialized once from a root scene/component and called from any scene ?

**Comment by KBLNY** [comment]
Hey, I'm working on that. Any help/suggestion is appreciated.
I will keep you in touch.

**Comment by shiv86** [comment]
Hey Thanks for looking into it. Ill be able to help in about 2-3 weeks with a PR if no one has looked into it yet. Suggestion in terms of implementation:

1) I think the logic needs to be defined in the Router.js since it is the initial view and there is only a single instance. 
2)Ideally these need to be able to be passed in as props <Router props>

Thanks Kevin!

**Comment by jaisonveneri** [comment]
Hello @shiv86,

Were you able to use `react-native-message-bar` with `react-native-router-flux`?

Thanks!

**Comment by shiv86** [comment]
@jaisonveneri @KBLNY Aplogizes about the delay yes I did get it working:

```
import { MessageBar , MessageBarManager} from 'react-native-message-bar';

class App extends Component {

    componentDidMount() {
    MessageBarManager.registerMessageBar(this.refs.alert);
  }

  componentWillUnmount() {
     MessageBarManager.unregisterMessageBar();
  }  

  _createAlert(message,alertType){
      if(!alertType){
        alertType = 'success';
      }
    MessageBarManager.showAlert({
       // title: 'Your alert title goes here',
        message: message,
        alertType: alertType
      });
  }

  render() {

    return (<View style={{flex: 1}}>
          <Router createReducer={this.reducerCreate.bind(this)}>
              
              <Scene..
              <Scene...
              <Scene key="yourScene" initial createAlert={this._createAlert.bind(this)} />
             </Router>
             **<MessageBar ref="alert" />**
             </View>);
  }

```

and then call the following method from youScene component:

`  this.props.createAlert('Call Alert');`

let me know if you have any problem ...ill be closing this issue in a couple of days
