### ISSUE TITLE
How can we pass props to previous screen in Action.Pop() operation

### ISSUE THREAD

**Issue by vykumar** [aksonov/react-native-router-flux#1014]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.2
- react-native v0.29.0
### Expected behaviour

I am passing props to previous screen like Actions.Pop({variable: value}) on click of back button. I am not able to get the props in previous screen because there is no any component life cycle methods triggered. 

can anyone please tell me which method is triggered on Action.Pop() operation and what is the way to pass props to previous screen on back button press?
### Actual behaviour

In actual only popping is happened and we moved to previous screen.
### Steps to reproduce

1.
2.
3.

**Comment by rturk** [comment]
@vykumar pop(), by definition, will bring back the previous scene with all the context that it was previously set. 
Why can't you just Go to Actions.MyDesiredScene({withMyNewProps...}); .?

**Comment by waqas19921** [comment]
You can pass props like this 
`NavigationActions.pop( {refresh: {variable: value} })`
this prop change will be found in 
`componentWillReceiveProps `callback in previous component

**Comment by afilp** [comment]
@waqas19921 This is nice, but how can the "automatic" pop of the hardware back (on Android) is handled? What should we do in this case, in order for a prop to have a different value there?

Thanks!

**Comment by adarshTS** [comment]
@waqas19921 how can we get the props in CDM
