### ISSUE TITLE
NavigationExperimental.js: __DEV__ is not defined

### ISSUE THREAD

**Issue by parrunset** [aksonov/react-native-router-flux#1015]
### Version
- react-native-router-flux v3.33.0
- react-native v0.26.3

I have updated only react-native-router-flux v3.26.0 and this error appeared...
Any help?

**Comment by patryknowak** [comment]
This is how I manage to fix it with v3.33.2:

```bash
rm -rf node_modules
npm cache clean
npm install
```

Maybe it will help you as well :)

**Comment by tetriscode** [comment]
`npm i -S babel-preset-react-native`

**Comment by parrunset** [comment]
@tetriscode Thank you!

**Comment by arronmabrey** [comment]
`npm i -S babel-preset-react-native` also helped me and I'm on react-native v0.31.0

**Comment by takhil** [comment]
versions:

react-native 0.36.0

still facing the same issue 

<img width="635" alt="screen shot 2016-12-01 at 12 09 33 pm" src="https://cloud.githubusercontent.com/assets/13853900/20803986/2df26d22-b7bf-11e6-8ae6-f741475d3e53.png">
