### ISSUE TITLE
navbar can not transparent

### ISSUE THREAD

**Issue by charlesluo2014** [aksonov/react-native-router-flux#1017]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.3.6
- react-native v0.3.0
### Expected behaviour

`<Scene key="foodDetail" title="Food Detail" component={FootDetailView} navigationBarStyle={styles.transparentNavBar}  />`
Navbar transparent
### Actual behaviour

 no effect

**Comment by parrunset** [comment]
if you want to hide the navbar you have to add the property hideNavBar={true}
Example:
<Scene key="foodDetail" title="Food Detail" component={FootDetailView} **hideNavBar={true}**/>
You can also add transparent background inside styles and borderBottomColor: transparent

**Comment by pewh** [comment]
Hello @parrunset,
can you give me a clue for semi-transparent navbar? I've set opacity on style, but I just got white navbar (not semi-transparent). Thanks

**Comment by leafingio** [comment]
@pewh
With opacity set, you should be able to see a semi-transparent navbar. Maybe the scenario container has paddingTop style and moves the content down the navbar. Please, check the scenario container styles

**Comment by pewh** [comment]
Ah it's work. Thanks :beers:
