### ISSUE TITLE
DefaultRenderer dependency on pure-render-mixin

### ISSUE THREAD

**Issue by kristojorg** [aksonov/react-native-router-flux#1018]
### Version

3.33.0
- react-native-router-flux v3.33.0
- react-native v0.29.0
### Problem

DefaultRenderer depends on react-addons-pure-render-mixin as of [#1006](https://github.com/aksonov/react-native-router-flux/pull/1006) but it is not in package.json.

**Comment by dmueller39** [comment]
https://github.com/aksonov/react-native-experimental-navigation/pull/4

**Comment by FaridSafi** [comment]
+1

**Comment by aksonov** [comment]
@sarovin Could you add it?

Pavel.

**Comment by sarovin** [comment]
#1021
