### ISSUE TITLE
Unmounted scenes after reset

### ISSUE THREAD

**Issue by joshg111** [aksonov/react-native-router-flux#1019]
### Version

"react-native-router-flux": "^3.32.0",
### Steps to reproduce

I'm trying to implement logout and log back in. For initial login things are fine. 
1. Login
2. Go to tabbed component and logout. This bring me back to the login page. 
3. Log back in. 
4. Go back to same tabbed component to logout. While going to this component I get a warning as below:
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`
### Expected behaviour

Tab component can be remounted successfully after reset, or tab component is not unmounted in the first place. 
### Actual behaviour

Tab component is unmounted on call to reset or replace. If I use the default type (w/e that is) I end up getting a back button on the login screen which allows the new user to get into a bad state if they hit the back button.

**Comment by joshg111** [comment]
Update:
I only see this warning once. If I click to other tab and back to the offending tab everything is fine.

**Comment by machei** [comment]
I got same issue as above, any idea for fixing it?

**Comment by sibelius** [comment]
any workaround?

**Comment by joshg111** [comment]
Before I was using "Alt" for state management. There's some mechanism in Alt which allows to listen for state changes from the flux store and propagate those changes to the View component. When the component unmounts there is a call to "unlisten" from the store. I'm guessing there's something wrong with that whole mechanism. 

Now I use Apollo Client (which uses Redux) for state management, and I'm not seeing any issue. 

There's probably some way to fix the Alt related mechanism by using "connectToStores" instead of binding to state with listeners directly. It seems these listeners stay alive even though component has been unmounted.
