### ISSUE TITLE
Unknown plugin "syntax-flow"

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1020]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.32.0
- react v15.1.0
- react-native v0.27.2

### Expected behaviour

Example app runs

### Actual behaviour
Packager starts but getting TransformError:
Unknown plugin "syntax-flow" specified in ".../react-native-experimental-navigation/package.json"

### Steps to reproduce

1. npm install
2. npm start

**Comment by aksonov** [comment]
Please check latest version
