### ISSUE TITLE
Unable to resolve module react-addons-pure-render-mixin

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1022]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.33.0
"react": "^15.1.0",
"react-native": "^0.27.0",

### Expected behaviour

Example app runs

### Actual behaviour

Unable to resolve module react-addons-pure-render-mixin from ".../DefaultRenderer.js"

### Steps to reproduce

1. npm install
2. npm start

**Comment by sarovin** [comment]
#1021
