### ISSUE TITLE
how can i reset 'switch' and pop some pages?

### ISSUE THREAD

**Issue by China1Ai** [aksonov/react-native-router-flux#1023]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.1
- react-native v0.27.0
### Expected behaviour

i want to reset the route when i logout in the page,but it will push the page which i logout when i login.i hope that it will to the homeIndex not the page which i logout.And how can i pop pages more than 2 or more from the history stack which such as:
A->B->C
D->E->C
I want to pop 2 pages from C to A or B use Actions.pop();

**Comment by sarovin** [comment]
@China1Ai It is fixed?
