### ISSUE TITLE
Unable to resolve module fbjs/lib/emptyFunction

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1024]
### Version
Tell us which versions you are using: 

"react": "15.1.0"    
"react-native": "0.27.2"

### Actual behaviour
Unable to resolve module fbjs/lib/emptyFunction from .../react-native-experimental-navigation/NavigationCardStack.js

**Comment by juanluisgv1** [comment]
I had the same error and I copied the fbjs folder from react into the node_modules from react-native-experimental-navigation. That solved the issue... it's a bad solution but somehow the devDependencies from react-native-experimental-navigation where not fully downloaded.

**Comment by aksonov** [comment]
I've just added it as 'dependencies' to RNEN, please check

**Comment by wildQueequeg** [comment]
Works now! Thanks!
