### ISSUE TITLE
unknown module fbjs/lib/invariant

### ISSUE THREAD

**Issue by vairabagni** [aksonov/react-native-router-flux#1026]
### Version

"react": "15.2.1",
"react-native": "0.31.0",
"react-native-router-flux": "^3.33.2"

**Comment by tetriscode** [comment]
`npm i -S fbjs`

**Comment by rturk** [comment]
Hi @vairabagni looks like this is a general React/React native question. Are you sure this question is related to RNRF? Otherwise can you please close this so we can keep the issues thread concise and clean?

**Comment by vairabagni** [comment]
This is an error which was thrown when i tried to integrate this library with latest react-native framework.
And this error is because of your library. It is now incompatible with latest react-native. The version info is given above.

**Comment by savioseb** [comment]
Thanks @tetriscode

**Comment by vairabagni** [comment]
By installing fbjs, it works now. But can you mention this library as a dependency so that I do not have to install it separately.

**Comment by the-simian** [comment]
When i got this error one time, the fix was surprisingly simple. I just stopped and restarted the package manager. embarassingly, this was after a very long time fiddling with various package.json dependencies. If you get this, give that a shot- it worked for me.
