### ISSUE TITLE
Put Image at the navBar

### ISSUE THREAD

**Issue by Talkwondo** [aksonov/react-native-router-flux#1027]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.? - unknown
- react-native v0.?.?- - up to date

### Expected behaviour
I want to put an image where the title place.

### Steps to reproduce

1.
2.
3.

**Comment by Lenin7** [comment]
Which example are you using?

**Comment by Talkwondo** [comment]
there is:
title='somthing'. i want to put an image instead.

**Comment by infacq** [comment]
@Talkwondo how do u do it?

**Comment by Talkwondo** [comment]
What you need to do is to create a function inside and return an image. note that the title has an horizontal animation so it does not so pretty to navigate with this when you have an icon in the left that stay, so i suggest you use const action of jump instead of push.
