### ISSUE TITLE
Block app before loading local data?

### ISSUE THREAD

**Issue by digitaldavenyc** [aksonov/react-native-router-flux#1028]
Is there a way to block the application from loading while retrieving data from `AsyncStorage`? I want to see if a user has ever authenticated before deciding which part of the application to display.  I've seen a similar [ticket](https://github.com/aksonov/react-native-router-flux/issues/953) open but I am not trying to "protect" scenes, I would prefer to block the app entirely before loading this initial data required to start.

**Comment by atlanteh** [comment]
What I do, is render a white screen by default, and when AsyncStorage fires REHYDRATE action, the navigationController middleware (which is responsible for controlling the view navigations) navigates to the right place

**Comment by digitaldavenyc** [comment]
I am doing something similar with a blank white screen but it's creating a flicker effect after loading rather quickly. How would you tie the AsyncStorage to the navigationController middle where RNRF?

**Comment by atlanteh** [comment]
In the Router I have a scene set to initial:
```jsx
<Scene key="white" initial component={WhiteScreen} />
```

Then, I have a navigation middleware:
```javascript
import {Actions, ActionConst} from 'react-native-router-flux';  
    const startInitialRoute = (state) => {
    const initialRoute = {type: ActionConst.RESET};
    if (!state.login || !state.login.uid) {
        Actions.login(initialRoute);
    } else {
        Actions.someOtherScreen(initialRoute);
    }
};
const navigationMiddleware = (/* store */) => next => action => {
    const result = next(action);
    const {type, payload} = action;
    const numOfSteps = 4;
    switch (type) {
    case REHYDRATE:
        startInitialRoute(payload);
        break;
    case ....
    case ....
    default:
        break;
    }
    return result;
};
```
and when I create the store, i plug it as middleware.

**Comment by rturk** [comment]
@digitaldavenyc this strategy from F8 App works pretty well for me: 
https://github.com/fbsamples/f8app/blob/master/js/F8App.js#L80

I'm using redux-persit. I'm my case I wait (actually show a loading view) until the real redux is loaded from disk.

**Comment by jianglinchun** [comment]
I suggest realm for the storage. The api of realm is blocking.
