### ISSUE TITLE
JSX-style comments confused for <Scene> inside <Router>

### ISSUE THREAD

**Issue by ouiliame** [aksonov/react-native-router-flux#1030]
``` javascript
import React, { Component } from 'react';
import { Scene, Router } from 'react-native-router-flux';
import NavigationDrawer from './NavigationDrawer';

// different screens -> scenes
import LoginScreen from '../Containers/LoginScreen';

export default class NavigationRouter extends Component {
  render() {
    return (
      <Router>
        <Scene key="drawer" component={NavigationDrawer}>
          <Scene key="drawerChildrenWrapper">
            <Scene initial key="loginScreen" component={LoginScreen} title={"Driver Login"}/>
            // more scenes ...
          </Scene> {/* drawerChildrenWrapper */}
        </Scene> {/* drawer */}
      </Router>
    )
  }
}

```

The above code will have React Native screaming at you because <Route> does a little parsing of the <Scene> children. It will complain that the element is missing some props. Avoid commenting inside <Route>.

**Comment by dslounge** [comment]
That's not a bug/issue with this package right? It's just incorrect JSX syntax. You're not supposed to put comments inside the children section of the tag. `// more scenes ...` is in the children section of a tag. 

From the docs: `You just need to be careful to put {} around the comments when you are within the children section of a tag.` https://facebook.github.io/react/docs/jsx-in-depth.html#comments

**Comment by hawkrives** [comment]
@dslounge is correct.
