### ISSUE TITLE
How should I put some common components into every scene?

### ISSUE THREAD

**Issue by inetfuture** [aksonov/react-native-router-flux#1034]
For example, I would like to show an ActivityIndicator on every scene whenever an API request starts, I want to do it somewhere just once instead of multiple times on every scene.

What's the preferred way to do this?

Thanks

**Comment by inetfuture** [comment]
Now I'm trying to use a custom root scene container, where contains the common ActivityIndicator and all other scenes are nested below:

```
<Scene key="root" component={Root}>
            {SplashScreen}
            {Login}
</Scene>
```

```
export default class Root extends Component {
  render = () => {
    return (
      <View>
        {this.props.children}
        <ActivityIndicator />
      </View>
    );
  }
}
```

But this doesn't work, it complains as `ExceptionsManager.js:55 Objects are not valid as a React child (found: object with keys {sceneStyle, dispatch, key, name, sceneKey, parent, type, initial, hideNavBar, component, index}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of View`

How a custom container should be written?

**Comment by inetfuture** [comment]
I tried this:

```
export default class Root extends Component {
  render = () => {
    const children = this.props.navigationState.children;
    const state = children[children.length - 1];

    return (
      <View style={{flex: 1}}>
        <DefaultRenderer
          navigationState={state}
          key={state.key}
          {...state}
          onNavigate={this.props.onNavigate}
        />

        <ActivityIndicator />
      </View>
    );
  }
}
```

But navbar is broken

**Comment by tomwalters** [comment]
I've solved this problem by creating a class of `BaseView` which knows how to render a loading view, and having all the components I'm using as Scenes inherit from this base class.

**Comment by vinaynb** [comment]
@tomwalters can you show us a sample of your code ?

**Comment by inetfuture** [comment]
Eventually, I solved this by putting `<Loading />` right after `<Router />` like this:

```
  render = () => {
    return (
      <Provider store={store}>
        <View
          style={styles.container}
          onStartShouldSetResponderCapture={this._onStartShouldSetResponderCapture}
        >
          <Router sceneStyle={styles.scene}>
            <Scene
              key="root"
            >
              ...
            </Scene>
          </Router>
          <Loading />
        </View>
      </Provider>
    );
  }
```

**Comment by tomwalters** [comment]
@inetfuture That's actually what I ended up doing, subclassing in the way I suggested isn't very React-y
