### ISSUE TITLE
How can I do multiple actions with a modal ?

### ISSUE THREAD

**Issue by bberthelemy** [aksonov/react-native-router-flux#1035]
## Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.2
- react-native v15.2.1
### Expected behaviour

I don't know what i'm doing wrong but when i try to call Actions.dialog() multiple times, i got this error.

I thought this fix https://github.com/aksonov/react-native-router-flux/issues/327 fixed it but it should be something else then.

The only time i dont have this, is when i use pop() to close it. Unfortunalty, i dont want to pop (it may break other functionalities in my app).
### Actual behaviour

`1:$dialog_1_dialog`. Child keys must be unique; when two children share a key, only the first child will be used.
    in RCTView (created by View)
    in View (created by Modal)
    in Modal (created by DefaultRenderer)
    in RCTView (created by View)
    in View (created by DefaultRenderer)
    in DefaultRenderer (created by SceneView)
    in SceneView (created by NavigationCard)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by NavigationCard)
    in NavigationCard (created by Container)
    in Container (created by NavigationComponent)
    in NavigationComponent (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in NavigationAnimatedView (created by NavigationComponent)
    in NavigationComponent (created by DefaultRenderer)
    in DefaultRenderer (created by NavigationRootContainer)
    in NavigationRootContainer (created by Router)
    in Router (created by Connect(Router))
    in Connect(Router) (created by CdiscountReact)
    in Provider (created by CdiscountReact)
    in CdiscountReact
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
2016-08-08 14:23:04.269 [warn][tid:com.facebook.react.JavaScript] Warning: flattenChildren(...): Encountered two children with the same key, `1:$dialog_2_dialog`. Child keys must be unique; when two children share a key, only the first child will be used.
    in RCTView (created by View)
    in View (created by Modal)
    in Modal (created by DefaultRenderer)
    in RCTView (created by View)
    in View (created by DefaultRenderer)
    in DefaultRenderer (created by SceneView)
    in SceneView (created by NavigationCard)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by NavigationCard)
    in NavigationCard (created by Container)
    in Container (created by NavigationComponent)
    in NavigationComponent (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in RCTView (created by View)
    in View (created by NavigationAnimatedView)
    in NavigationAnimatedView (created by NavigationComponent)
    in NavigationComponent (created by DefaultRenderer)
    in DefaultRenderer (created by NavigationRootContainer)
    in NavigationRootContainer (created by Router)
    in Router (created by Connect(Router))
    in Connect(Router) (created by CdiscountReact)
    in Provider (created by CdiscountReact)
    in CdiscountReact
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
### Steps to reproduce

```
                  <Scene key="modal" component={Modal} >
                      <Scene key="root">
                          <Scene key="launch" initial={true} component={Launch} />
                          ...
                      </Scene>

                      {/*Modals*/}
                      ...
                      <Modal key="dialog" component={Dialog} direction="vertical"/>
                  </Scene>
```

**Comment by bberthelemy** [comment]
Anyone ?

**Comment by Druux** [comment]
I am facing the exact same warning. Are there solutions available?

**Comment by bberthelemy** [comment]
I finaly find out a hack few minutes ago.

// Dialog
```
class Dialog extends React.Component {
    constructor() {
        super();

        this.state = {
            visible: false
        };

        this.onCloseDialog = this.onCloseDialog.bind(this);
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.visible) {
            this.setState({visible: nextProps.visible});
        }
    }

    onCloseDialog() {
        this.setState({visible: false});
    }

    render() {
        return (this.state.visible) ? (
            <View>
                ...
                <TouchableOpacity onPress={this.onCloseDialog}>
                    <Image source={ require("../Ressources/Images/interface-croix.png") }/>
                </TouchableOpacity>
            </View>
        ) : null;
    }
}

export default connect(null, {})(Dialog);
```

// index.ios.js
```
...
<Router name="root" hideNavBar={true}>
    <Scene key="modal" component={Modal} >
        <Scene key="root">
            <Scene key="launch" initial={true} component={Launch} />
            ...
        </Scene>

        {/*Modales*/}
        <Scene key="dialog" component={Dialog} direction="vertical"/>
        ...
```
// Launch
```
...
// Default visible state of dialog is false, it will not show up this time
Actions.dialog();
```

// Other components where i need to show the dialog
```
...
// We get the new visible value from componentWillReceiveProps, the dialog will show up this time
Actions.refresh(key: "dialog", visible: true, uniqId: new Date().getTime());
```

I show the modal when I get the visible prop (sent when using the refresh action).
I noticed that If I do not send a new prop value (this is why I use the date timestamp), it doesn't go to componentWillReceiveProps and then doesn't re-render.
