### ISSUE TITLE
__DEV__ not defined 

### ISSUE THREAD

**Issue by jcampbell05** [aksonov/react-native-router-flux#1039]
![simulator screen shot aug 9 2016 16 25 08](https://cloud.githubusercontent.com/assets/1484989/17522148/d8037c32-5e4d-11e6-908d-31805efad229.png)

**Comment by vinalys** [comment]
Currently facing the same issue after upgrades (react-native 0.31, react-native-router-flux 3.33.2)

**Comment by vinalys** [comment]
Sorry, it seems the answer is in this ticket:
https://github.com/aksonov/react-native-router-flux/issues/1015

`npm i -S babel-preset-react-native`

Fixed this problem for me, can you try as well and let's close the ticket if it works.

**Comment by jcampbell05** [comment]
@vinalys I will have a go, weird though I would have thought I have the transforms already since I use ES6 and JSX.

**Comment by aaronhma** [comment]
My code is like this:
'use strict';
import React, { Component } from 'react';
import { TextInput, View, Text, StyleSheet, Image, TouchableHighlight, ActivityIndicator } from 'react-native';
import buffer from 'buffer';
import authService from './AuthService';

const styles = StyleSheet.create({
  container: {
        backgroundColor: '#F5FCFF',
        paddingTop: 40,
        padding: 10,
        alignItems: 'center',
        flex: 1
    },
    logo: {
        width: 66,
        height: 55
    },
    heading: {
        fontSize: 30,
        margin: 10,
        marginBottom: 20
    },
    loginInput: {
        height: 50,
        marginTop: 10,
        padding: 4,
        fontSize: 18,
        borderWidth: 1,
        borderColor: '#48BBEC',
        borderRadius: 0,
        color: '#48BBEC'
    },
    button: {
        height: 50,
        backgroundColor: '#48BBEC',
        borderColor: '#48BBEC',
        alignSelf: 'stretch',
        marginTop: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5
    },
    buttonText: {
        color: '#fff',
        fontSize: 24
    },
    loader: {
      marginTop: 20
    },
    error: {
      color: '#ff0000',
      paddingTop: 10
    }
});

export default class Login extends Component {
  constructor(props) {
    super(props);

    this.state = {
      showProgress: false
    }
  }
  render() {
    let errorCtrl = <View />;
    if (!this.state.success && this.state.badCreditials) {
      errorCtrl = <Text style={styles.error}>
        That username and password combination did not work.
      </Text>;
    }
    if (!this.state.success && this.state.unknownError) {
      errorCtrl = <Text style={styles.error}>
        We experienced an unknown issue.
      </Text>;
    }
    return (
      <View style={styles.container}>
        <Image source={require('./Octocat.png')} style={styles.logo} />
        <Text style={styles.heading}>
          Github Browser
        </Text>
        <TextInput
          style={styles.input}
          placeholder="Github Username"
          onChangeText={(text) => this.setState({username: text})}
        />
        <TextInput
        onChangeText={(text) => this.setState({password: text})}
          style={styles.input}
          placeholder="Github Password"
          secureTextEntry="true"
        />
        <TouchableHighlight
          onPress={this.onLoginPressed.bind(this)}
          style={styles.button}>
          <Text style={styles.buttonText}>
            Login
          </Text>
        </TouchableHighlight>

        { errorCtrl }

        <ActivityIndicator
          animating={this.state.showProgress}
          size="large"
          style={styles.loader}
        />
      </View>
    );
  }
      onLoginPressed(){
        console.log('Attempting to log in with username ' + this.state.username);
        this.setState({showProgress: true});

        authService.login({
            username: this.state.username,
            password: this.state.password
        }, (results)=> {
            this.setState(Object.assign({
                showProgress: false
            }, results));

            if(results.success && this.props.onLogin) {
              this.props.onLogin();
            }
        });
    }
}
But when I test it, it keeps giving me this error: authService.login is not defined.I do have a AuthService.js file like this:
import React, { Component } from 'react';
import buffer from 'buffer';

export default class AuthService extends Component {
  login(creds, cb) {
    let b = new buffer.Buffer(creds.username +
        ':' + creds.password);
    let encodedAuth = b.toString('base64');
    fetch('https://api.github.com/user', {
      headers: {
        'Authorization' : 'Basic ' + encodedAuth
      }
    })
    .then((response) => {
      if(response.status >= 200 && response.status < 300) {
        return response;
      }
      throw {
        badCreditials: response.status == 401,
        unknownError: response.status != 401
      }
    .then((response) => {
      return response.json();
    })
    .then((results) => {
      return cb({success: true});
    })
    .catch((err) => {
      return cb(err);
    })
  })
  }
}
Is there any errors?
