### ISSUE TITLE
ExNavigator (Styles) undefined 

### ISSUE THREAD

**Issue by andreasbhansen** [aksonov/react-native-router-flux#104]
With the new release (2.0.3), has something happened to ExNavigator (Styles)? In the previous version I used, I could style the navBar left/right buttons like this:

```
import { ExNavigator } from 'react-native-router-flux';

...

      <TouchableOpacity
        touchRetentionOffset={ExNavigator.Styles.barButtonTouchRetentionOffset}
        style={[ExNavigator.Styles.barRightButton]}>
        <Text style={ExNavigator.Styles.barRightButtonText}>
          ...
        </Text>
      </TouchableOpacity>
```

but now, this is thrown:
```Cannot read property 'Styles' of undefined```

**Comment by aksonov** [comment]
Seems it is breaking changes for 2.* version, please change it to:
import ExNavigator from '@exponent/react-native-navigator';

I want 2.0 version to be UI-agnostic - so it can use exNavigator or anything else to render nav bar.

**Comment by andreasbhansen** [comment]
Superb! Works great, thank you :)
