### ISSUE TITLE
Scene with key considered non-existent despite it rendering successfully

### ISSUE THREAD

**Issue by casenjo** [aksonov/react-native-router-flux#1040]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.33.2
- react-native v0.29.0
### Expected behaviour

The scene key should be found when the state of the app changes
### Actual behaviour

I have the following code for my app:

```
<Router>
  <Scene
    key = "root"
    hideNavBar = {true}
    direction = "vertical"
    component = { connect(state => ({ auth: state.auth, isOnboarding: state.verify.isOnboarding }))(Switch) }
    tabs = {true}
    unmountScenes
    selector = {props => (props.auth.token !== '' && props.isOnboarding == 0) ? "loggedIn" : "loggedOut"}
  >
    <Scene key = "loggedOut" hideNavBar = {true} type = {ActionConst.RESET} direction = "vertical" >
      <Scene key = "login" component = {LoginContainer} passProps = {true} direction = "vertical" />
    </Scene>
    <Scene key = "loggedIn" hideNavBar = {true} type = {ActionConst.RESET} direction = "vertical" >
      <Scene key = "productList" component = {ProductListContainer} passProps = {true} direction = "vertical" type = {ActionConst.RESET} />
    </Scene>
  </Scene>
</Router>
```

When the app is initially installed in the simulator, the loggedOut scene works great. After the login scene is completed (and auth.token and isOnboarding have the relevant values), the transition to loggedIn works great as well. When the token is cleared, however, I get the following screen:

![screen shot 2016-08-09 at 12 38 41 pm](https://cloud.githubusercontent.com/assets/1554289/17530875/4eee79b6-5e2e-11e6-93b5-9d776f83e22e.png)

And when I press Cmd+R, the app refreshes, and only then does it go back to showing the loggedOut scene properly.

I'm not sure what is triggering this error, since the initial render of the loggedOut scene works fine.

**Comment by aksonov** [comment]
Maybe it is bug within umountScenes? Could you check without unmountScenes?

**Comment by casenjo** [comment]
Just checked and unfortunately got the same result :(
Are there any specific things that I could log to help narrow down the issue?

**Comment by steida** [comment]
`connect(state => ({ auth: state.` inside render function a big design smell, try refactore out it.

**Comment by casenjo** [comment]
@steida I agree, I need to clean that up. I want to get it working properly first though ;)

**Comment by steida** [comment]
Properly? It's terribly wrong ;). Please fix it and retest code.

**Comment by casenjo** [comment]
Do you really believe that's the issue, and if so, can you explain why? I'd like to learn because don't really understand why that's the case, and it's the exact example that's provided in the docs.
https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#switch-new-feature

**Comment by mlevkovsky** [comment]
+1 on this

**Comment by casenjo** [comment]
As @steida suggested, I cleaned the code up a little more and turned the component into a full on smart component like this:

```javascript
class App extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
    <Router>
      <Scene
        key = "root"
        hideNavBar = {true}
        direction = "vertical"
        tabs = {true} // Enabled in order to switch between loggedIn/loggedOut
        unmountScenes // Make sure that when we switch between scenes the other ones are unmounted
        selector = {props => (props.auth.token !== '' && props.isOnboarding == 0) ? "loggedIn" : "loggedOut"} // Conditional to decide what to render
      >
        {require("./components/sceneGroups/loggedOut")}
        {require("./components/sceneGroups/loggedIn")}
      </Scene>
    </Router>
    )
  }
}

const mapStateToProps = (state) => {
  const auth = state.auth;
  const isOnboarding = state.verify.isOnboarding;

  return {
    auth,
    isOnboarding,
  };
}

const mapDispatchToProps = (dispatch) => {
  return { };
};

export default connect(mapStateToProps, mapDispatchToProps)(App);
```
And that fixed the issue, though I still don't understand why that fixed it. Thanks @steida!
I still want to understand why the example in the wiki wasn't working but converting it to use mapStateToProps did the trick. @aksonov would you be able to chime in?
