### ISSUE TITLE
how to implements call a function on scene transition end

### ISSUE THREAD

**Issue by flare216** [aksonov/react-native-router-flux#1044]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.33.2
- react-native v0.3.0
### Steps to reproduce

I have searched answers in the issues, someone says that  add  "didFocus" event listener on this.props.route.parent.delegate.refs.nav.navigationContext , but i can't found the "route" in props,
in my scene component's componentWillMount, print this.props.route got undefined. Why?
#161
#183

**Comment by sbefort** [comment]
I think I have the same issue.  I'm showing a spinner during scene transition while data is loaded from an API, and I do not want data to be displayed until the scene transition finishes.  Sometimes the data is displayed during scene transition and it causes frame rates to drop.
