### ISSUE TITLE
Get the current navigator stack

### ISSUE THREAD

**Issue by Druux** [aksonov/react-native-router-flux#1045]
Is there any possibility to print the navigator stack with all the routes which were pushed?

**Comment by Zianwar** [comment]
I kinda have the same question but I wanna print just the current route.

**Comment by sym900728** [comment]
I also have the same problem.

**Comment by ospfranco** [comment]
any ideas on how to access this?

**Comment by aksonov** [comment]
Check docs about ‘redux’ integration. You could see entire stack in your custom reducer.

**Comment by DeDuckProject** [comment]
<img width="343" alt="screenshot 2016-09-02 22 50 21" src="https://cloud.githubusercontent.com/assets/10045034/18216486/a8707d9c-715f-11e6-89a6-907d46792844.png">

I can see that the stack depth is represented inside scene.key
But other than parsing the data myself to determine stack depth, I cannot see anything in the docs about it...

**Comment by DeDuckProject** [comment]
reviewing the code, I think the stack depth should be index, right?
For some reason it stays on 0 for me, even when I push other scenes on top of it... only the number inside the key changes... wierd?

**Comment by DeDuckProject** [comment]
my implementation to detemine stackDepth in my reducer:

`
import { ActionConst } from 'react-native-router-flux';

const initialState = {
    scene: {},
    stackDepth: 0
};

export default function routes(state = initialState, action = {}) {
    switch (action.type) {
        // focus action is dispatched when a new screen comes into focus
        case ActionConst.FOCUS:
            var stackDepth = parseInt(action.scene.key.replace(action.scene.sceneKey,"").replace("_",""));
            return {
                ...state,
                scene: action.scene,
                stackDepth: stackDepth
            };

        // ...other actions

        default:
            return state;
    }
}
`
