### ISSUE TITLE
Can other routes only be accessed by react-native-button?

### ISSUE THREAD

**Issue by hermant2** [aksonov/react-native-router-flux#1046]
I am trying to get my app to change routes based on whether a user is logged in or not. I am using Facebook SDK for my login and it comes with their own button, but when I run `Actions.scene` with in a function after a login success, the app doesn't do anything. I was wondering if there were a way to change the scene without using react-native-button, otherwise I will explore other alternatives.

**Comment by sattaman** [comment]
You just need to make sure you are matching the key defined when creating the scenes so for 

`<Scene key="scene" component={MyScene} >`

The following would trigger navigation 

`Actions.scene()`

**Comment by cridenour** [comment]
We also use FB login and haven't had this issue. Can you post your Router config and FB button code?
