### ISSUE TITLE
example of wiring a create button to a method in a page?

### ISSUE THREAD

**Issue by beebase** [aksonov/react-native-router-flux#1047]
Is there an example some where how to do this?

-Contacts Scene is set up in root.js
-Contacts page has a create method.

How do I link the method to the create button in the nav bar?

**Comment by cridenour** [comment]
in your `componentWillMount` add 

`Actions.refresh({onRight: () => this.create });`

**Comment by onatm** [comment]
@cridenour can you give us a clearer version of the above example?

**Comment by onatm** [comment]
it seems like it is not working inside of Switch

**Comment by cridenour** [comment]
@onatm There's not much more to it than what I posted. If you find it's working outside a switch and not inside, definitely submit a new issue regarding that!

**Comment by onatm** [comment]
@cridenour I wrote the solution on edited post. Should i create another issue and post the solution there?

**Comment by cridenour** [comment]
Ah nope. That looks good - thanks!
