### ISSUE TITLE
navBar to update parent state that is shared with children components

### ISSUE THREAD

**Issue by fgrs** [aksonov/react-native-router-flux#1048]
### Version
- react-native-router-flux v3.34.0
- react-native v0.31.0

I'm trying to build an app similar to what can be achieved in Ionic framework so I have a screen with custom navBar that has left button, title and button on the right, so far the navBar works but I want to use left button to update the value of 123, I'm storing it in a parent component as a state that has been passed in to the Router the same way I do with toggling sideMenu visibility which already works:

```
<Router scenes={scenes} openSideMenu={this.openSideMenu.bind(this)} toggleRecordsDelete={this.toggleRecordsDelete.bind(this)} {...this.state} />
```

The problem is neither navBar or my Records screen doesn't get updated immediately after I press left button in the navBar, I'm expecting it to change the value of 123 to 45434

![image](https://cloud.githubusercontent.com/assets/3940061/17596318/216cd96e-5ff1-11e6-9e87-be68327384a2.png)

if I go back to return to dashboard and back to the Records screen again:

![image](https://cloud.githubusercontent.com/assets/3940061/17596351/4b9681c2-5ff1-11e6-8352-23d1114f2849.png)

...the value gets updated. I tried using componentWillMount in both navBar and Records screen component but had no luck.

Has anybody been working on a similar layout and could point me at what I'm doing wrong here?

**Comment by cridenour** [comment]
Honestly, the navigation of your page shouldn't manage this sort of binding and state. Your best bet is to include a flux implementation so you can keep the app state on a higher order, and bind your components to the state. 

At that point, then it's just a matter of wiring up your buttons to the flux actions.
