### ISSUE TITLE
Setting initial props gives me an route is not defined

### ISSUE THREAD

**Issue by BigPun86** [aksonov/react-native-router-flux#105]
The title says it. If i want to set my initial route i get this error

**Comment by aksonov** [comment]
Please post example here

**Comment by BigPun86** [comment]
my index.android.js

    import {Router, Route, Schema, Animations, TabBar} from 'react-native-router-flux';
    import Launch from './App/Routes/Launch';

    var Test  = React.createClass({
    render: function () {
		return (
			<Router hideNavBar={true}>
				<Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
				<Route name="launch" wrapRouter={true} title="Launch"/>
			</Router>
		);
	}
    });

my index.js: 

    var React = require('react-native');
    var {View, Text}  = React;

    class Launch extends React.Component {
	render() {
		return (
			<View style={{flex:1}}>
				<Text>TEST</Text>
			</View>
		);
	}
    }

    module.exports = Launch;

**Comment by BigPun86** [comment]
The error is now: component or children should be defined for route=launch pointing to Route.js line 36

**Comment by aksonov** [comment]
Where is Launch component passed within index.android.js?

**Comment by BigPun86** [comment]
Upps sorry! Now i fixed it. Error is: route is not defined

**Comment by bradhanebury** [comment]
Also ran into this issue after updating to latest version.

**Comment by ivanfoong** [comment]
I'm having this issue too, with version 2.0.4

**Comment by aksonov** [comment]
Should be fixed for 2.0.5, please check.

**Comment by ivanfoong** [comment]
:+1: v2.0.5 is working for me. Thanks!

**Comment by BigPun86** [comment]
Works perfect thanks @aksonov 
![image](https://cloud.githubusercontent.com/assets/7880624/12172133/4e3eec36-b54f-11e5-943b-91b8f3cf27dc.png)
