### ISSUE TITLE
How can I access the title property if I use a custom renderTitle function

### ISSUE THREAD

**Issue by Manuel83** [aksonov/react-native-router-flux#1053]
- react-native-router-flux v3.34.0
- react-native v0.31

How can I access the title property if I use a custom renderTitle function?
Is it somehow possible to pass this.props.title this function?

```
...
<Router>
     <Scene renderTitle={myTitleFunction} title="HelloWorld" />
</Router>
....
```

**Comment by sheparddw** [comment]
You could do the following:
```
<Router>
     <Scene renderTitle={() => myTitleFunction("myTitleName")} />
</Router>
```
You can even dynamically set the title if you wish via Actions.refresh() within componentWillMount. 
Example:
```
Actions.refresh({
   renderTitle: () => {
      //my title content here
   }
});
```
