### ISSUE TITLE
How can I dynamically go to different initial page by deeplink ?

### ISSUE THREAD

**Issue by markzhai** [aksonov/react-native-router-flux#1060]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.1
- react-native v0.31

How can I dynamically go to different initial page by deeplink ? 
Say like, I have `stayapp://bloc` and `stayapp://card`, and I want to navigate to different page as the initial scene in the same component entry using the link.

Currently,

``` javascript
      var url = Linking.getInitialURL().then((url) => {
        if (url) {
          console.log('Initial url is: ' + url);
        }
      }).catch(err => console.error('An error occurred', err));
```

If I use `Linking`, I can only use Action to navigator in the callback and cannot realize the effect I want (as there was already a page in stack).

**Comment by digitaldavenyc** [comment]
+1 for this question

**Comment by senthilsivanath** [comment]
Have d same prob. How to navigate to diff page in same parent.

<Scene key="drawer" tabs>
<Scene key="artist">
<Scene key="album">
    <Scene key="albumHome" />
    <Scene key="albumDetail" clone={true} tabs={false} />
</Scene>
</Scene>

From albumHome page i navigate to album detail. From drawer when i press album, it loads album detail, how can i go back to albumHome directly though album detail was loaded previously.

**Comment by cjadhav** [comment]
Hi
found any solution for this issue??
I am facing same problem.
I am unable to select other tabs to open when opening tabbar. Always {initial: true} tab loads.

**Comment by digitaldavenyc** [comment]
I have not found a solution to this. @aksonov do you have any recommendations?

**Comment by ihor** [comment]
It is hard to understand what is your problem. I implemented deep linking at work last week, and all I used was ```Actions["<scene key>"].({ props })```.

I prepared an example which uses the same approach [here](https://github.com/ihor/ReactNativeDeepLinkingExample). Here is my [Router](https://github.com/ihor/ReactNativeDeepLinkingExample/blob/master/app/components/LinkedRouter.js) which handles open URL, and here are my [scenes and URLs to scenes mapping](https://github.com/ihor/ReactNativeDeepLinkingExample/blob/master/app/router.js).
