### ISSUE TITLE
Swipe between tabs

### ISSUE THREAD

**Issue by veedeo** [aksonov/react-native-router-flux#1064]
Hello, In my app I need to swipe between tabs, is it posible with this component out of the box, if not what is the easiest way to implement this feature.

-alex

**Comment by andrispraulitis** [comment]
[https://github.com/skv-headless/react-native-scrollable-tab-view](url)

**Comment by veedeo** [comment]
its what Im actually using right now, but I want a better integration with react-native-router-flux

**Comment by sibelius** [comment]
u could try this one as well: https://github.com/react-native-community/react-native-tab-view

Maybe TabBar should be customizable

**Comment by sarthakmis** [comment]
Inside you <Tabs/> component define 
**legacy={true} swipeEnabled={true}** 

It worked for me
