### ISSUE TITLE
Navigate between 2 different tabbars

### ISSUE THREAD

**Issue by joshloo** [aksonov/react-native-router-flux#1066]
Hi,
I am trying to navigate between 2 sets of tabbars. 
For example, 
tabbar 1 has 4 pages, a,b,c,d. 
tabbar 2 has 4 pages, e,f,g,h. 
May I know if it is possible to navigate from page C to page G with different sets of tabbar icons using this router?

Thanks!!

**Comment by amitava82** [comment]
Any update?

**Comment by dragfire** [comment]
Yes you can. But when you press BACK, then it won't go to tabbar 1.
