### ISSUE TITLE
How to remove view from the view stack

### ISSUE THREAD

**Issue by basdvries** [aksonov/react-native-router-flux#1071]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.34.0
- react-native v0.30.0

How do I remove a view from the view stack after for instance navigating? Couldn't find it anywhere in the docs nor in the issues, so asking it here.

**Comment by worldlyjohn** [comment]
`Actions.pop()`

**Comment by basdvries** [comment]
I'm sorry but that's not what I meant. Navigating from let's say a pincode screen (only use once) to some activity screen would allow you to swipe or navigate back right now. PanHandlers={null} is a nice hack if it worked, but in 3.34 it doesn't. Removing it from the view stack would be much cleaner imo.

Get Outlook for iOS




On Wed, Aug 17, 2016 at 10:01 PM +0200, "John Brennan" <notifications@github.com> wrote:












Actions.pop()

**Comment by mlevkovsky** [comment]
Try ActionConst.REPLACE as a parameter like this: Actions.someAction({type: ActionConst.REPLACE})
