### ISSUE TITLE
Cannot read property 'applyAnimation' of undefined when using ActionConst.POP_TO

### ISSUE THREAD

**Issue by ailinykh** [aksonov/react-native-router-flux#1074]
### Version
- react-native-router-flux v3.34.0
- react-native v0.31.0
### Example

``` javascript
import React, { Component } from 'react';
import {Scene, Router, Actions, ActionConst} from 'react-native-router-flux';
import { StyleSheet, View, Text, TouchableOpacity } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <Router>
        <Scene key="root">
          <Scene key="first" component={First} title="First" />
          <Scene key="second" component={Second} title="Second" />
          <Scene key="third" component={Third} title="Third" />
        </Scene>
      </Router>
    );
  }
}

const First = () => {
  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={() => Actions.second()}>
        <Text style={styles.text}>I am First</Text>
      </TouchableOpacity>
    </View>
  );
}

const Second = () => {
  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={() => Actions.third()}>
        <Text style={styles.text}>I am Second</Text>
      </TouchableOpacity>
    </View>
  );
}

const Third = () => {
  return (
    <View style={styles.container}>
      <TouchableOpacity onPress={() => Actions.first({type: ActionConst.POP_TO})}>
        <Text style={styles.text}>I am Third</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    justifyContent:'center',
    flex: 1
  },
  text: {
    textAlign: 'center'
  },
});
```

So when i press _button_ on my **third** scene i assume that it will be _poped_ to **first** scene. But instead i got [an error](http://i.imgur.com/Ft3CS5C.png) **undefined is not an object (evaluating 'selected.applyAnimation')**. That happens because of

``` javascript
<TouchableOpacity onPress={() => Actions.first({type: ActionConst.POP_TO})}>
```
### What is wrong?

To my mind the reason of that is **Reducer.js** that [slices all the children](https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L87) from state if you not pass a **targetIndex** to _action_. So this will works well:

``` javascript
<TouchableOpacity onPress={() => Actions.first({type: ActionConst.POP_TO, targetIndex:0})}>
```
### How it should work

Probably you should get **targetIndex** from **state** as you know an **action.key**. Or could you please include that into docs if **targetIndex** is required in that case. It takes a bit a long time to investigate such kind of things. Thanks!

**Comment by flare216** [comment]
'targetIndex' worked for me! Thanks ! The docs makes me confused .

**Comment by markortiz** [comment]
i also experienced this on 
`Actionc.main({type:'reset'})`
` <Scene key="main" type="replace">`

**Comment by mcavaliere** [comment]
FYI, I was seeing the same on the below setup, but in my case the scene component was undefined and I didn't realize it. So it might be useful to note that this error can happen in cases like this as well. 

* "react-native-router-flux": "^3.40.1"
* "react-native": "^0.45.1"

In my case, I was calling the action directly, as in `Action.signup()` .
