### ISSUE TITLE
Changelog not maintained

### ISSUE THREAD

**Issue by mattvot** [aksonov/react-native-router-flux#1075]
Just a simple issue, maybe the start of a discussion on where changelogs are maintained.

Currently only NPM officially lists the latest version:
<kbd>
![screen shot 2016-08-19 at 16 42 11](https://cloud.githubusercontent.com/assets/723372/17815454/4ceaa3be-662c-11e6-868b-b9af42495727.png)
</kbd>

GitHub releases is out of date:
<kbd>
![screen shot 2016-08-19 at 16 42 30](https://cloud.githubusercontent.com/assets/723372/17815476/5b81e216-662c-11e6-855a-0de280ad3742.png)
</kbd>

Also the CHANGELOG.md file is outdated:
<kbd>
![screen shot 2016-08-19 at 16 42 44](https://cloud.githubusercontent.com/assets/723372/17815481/6632304e-662c-11e6-9d24-90e1028703de.png)
</kbd>
Is there any place we should go to see a definitive changelog between versions, other than looking through the commit history for changes and version increases?

This came apparent today dealing with the new default styles (#1054) that broke one of our implementations.

Many thanks

**Comment by charpeni** [comment]
cc @aksonov @joenoon @philipshurpik @lynndylanhurley @cridenour

**Comment by lynndylanhurley** [comment]
how about something like this?
https://github.com/skywinder/github-changelog-generator

**Comment by aksonov** [comment]
@lynndylanhurley brilliant! will try to use it

**Comment by aksonov** [comment]
@charpeni I'm going to try this tool with latest PRs, but unit tests fail for all of them (i've tried reverted some but they fails for reverted PRs as well).
