### ISSUE TITLE
How to customize drawer button

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1078]
### Version
- react-native-router-flux v3.34.0
- react-native v0.31.0

I'm trying to use an Ionicon from react-native-vector-icons as the menu button.
```
renderMenuButton = () => {
        return (
            <TouchableOpacity style={styles.leftButtonContainer}>
                <Ionicon name="ios-menu" size={30} color="#EF5C30"/>
            </TouchableOpacity>
        );
    };

...

<Scene key="dashboard" component={Dashboard} title="DASHBOARD" type='replace' leftButton={this.menuButton}/>
```

### Actual behaviour
Button renders correctly but does not open drawer.
Using `drawerImage={this.menuButton()}` does not render button though functionality is still there.

**Comment by ailinykh** [comment]
The `drawerImage` property accepts only image path. It [renders that](https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L362) inside an `<Image>` component.
If you want to use custom drawer icon component you need to provide `renderLeftButton` property.
```javascript
```

**Comment by wildQueequeg** [comment]
Yes, that does render the custom button, but how can I attach drawer toggle action?

**Comment by berkayk** [comment]
`renderLeftButton={() => <MenuButton press={() => { Actions.refresh({key: "drawer", open: true})}} />}`

I am not sure if this is the best way to do but it works. "drawer" is the key of the main container that has Drawer as the component. If there is a better way, please share with me :)

**Comment by aksonov** [comment]
Better way is to get reference to drawer directly and call its methods: `Actions.get(‘drawer’).ref.switch()`
and set `Actions.refresh({ref:this.refs.drawer’)` within comonentDidMount of Drawer component.

**Comment by berkayk** [comment]
Can you give a short example?

**Comment by wildQueequeg** [comment]
@aksonov Thanks! It's works now!

@berkayk 
In Drawer component: 
`componentDidMount() {
    Actions.refresh({key: 'drawer', ref: this.refs.navigation});
  }`

In Button component:
`onPress={() => {Actions.get('drawer').ref.toggle()}}`

**Comment by berkayk** [comment]
Thanks @wildQueequeg It worked! I also understood how to use refs in react-native-router-flux.
Cheers :+1:

**Comment by lkag2000** [comment]
My entire screen with header moves down when I add drawer sidemenu. Where could be the issue?

**Comment by bkniya** [comment]
i can't use this :|
get this error: 
_reactNativeRouterFlux.Actions.get is not a function

![screen shot 2017-10-23 at 17 09 56](https://user-images.githubusercontent.com/6282439/31894075-fc0292b2-b815-11e7-9fdc-ee4c8f760e40.png)

**Comment by remoteportal** [comment]
Has Actions.get() been deprecated as a method of Actions?  It's not listed in the API.
When I try it I get:

> _reactNativeRouterFlux.Actions.get is not a function
> ...  .get is undefined
