### ISSUE TITLE
NavBar is not transparent on Android

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1079]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.34.0
- react-native v0.31.0
### Expected behaviour

Navbar background is transparent on both platforms.
### Actual behaviour

Fine on iOS. Inspector says background color is transparent on Android but it's actually a shade of white.

**Comment by charpeni** [comment]
Are you up for a pull request?

**Comment by machei** [comment]
+1 , also here too problem on Android.

**Comment by chuyik** [comment]
Set `backgroundColor: 'transparent'` didn't work on Android, still shows a white background.
Any ideas?

**Comment by sainthardaway** [comment]
Same here, tried to change it in navigationBarStyle and in NavBar.js
https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L65 
and still no luck
+1

**Comment by norbajunior** [comment]
Did you guys solve that? I also have this problem.

**Comment by watadarkstar** [comment]
Same ^

**Comment by robbporto** [comment]
Hey, @aksonov, this is still not working here.
