### ISSUE TITLE
Ghost view during navigation transition

### ISSUE THREAD

**Issue by wildQueequeg** [aksonov/react-native-router-flux#1085]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.34.0
- react-native v0.30.0
### Expected behaviour

Animation is that next view slides over current view as current view fades.
### Actual behaviour

Ghost of previous scenes are visible in the background as current scene fades during transition.

```
<Router>
  <Scene key='launch' type='reset'/>
  <Scene key='login'/>
  <Scene key='createAccount'/>

  <Scene key='drawer'>
      <Scene key='drawerRoot'>
          <Scene key='dashboard1_1' initial type='replace' />
          <Scene key='dashboard1_2' />
          <Scene key='account' type='replace' />
          <Scene key='settings' type='replace'/>
      </Scene>
  </Scene> 
</Router>
```

**Comment by wuxushun** [comment]
i have the same problem, how to solve it?

**Comment by hector** [comment]
Same here

**Comment by wildQueequeg** [comment]
This is a strange issue. I am dually don't think this is a react-native-router-flux issue. Seems more like a weird bug on some iPhone models. I noticed this wasn't happening on all the models. And on the ones where this is an issue, all other apps with dark backgrounds also have this issue.

**Comment by vnshgrg** [comment]
anyone found any solution yet?

**Comment by AdamTyler** [comment]
bump
