### ISSUE TITLE
Long titles are hidden behind the buttons

### ISSUE THREAD

**Issue by lesniakania** [aksonov/react-native-router-flux#1087]
### Version
- react-native-router-flux v3.35.0
- react-native v0.28
### Expected behaviour

Long titles are displayed with dots at the end

![screen shot 2016-08-23 at 06 44 56](https://cloud.githubusercontent.com/assets/193863/17880748/1d13683a-68ff-11e6-91c9-91196d72ad23.png)
### Actual behaviour

Long titles are hidden behind buttons

![screen shot 2016-08-23 at 06 58 51](https://cloud.githubusercontent.com/assets/193863/17880741/10d4d3f6-68ff-11e6-8427-ee91c5e6be95.png)
### Steps to reproduce
1. Set long title for a scene

**Comment by charpeni** [comment]
Thank you for reporting, are you up to do a pull request?

**Comment by lesniakania** [comment]
Actually, I've already done and waiting for being merged  ; )
https://github.com/aksonov/react-native-router-flux/pull/1088
