### ISSUE TITLE
Custom Navbar with Drawer

### ISSUE THREAD

**Issue by redbaron76** [aksonov/react-native-router-flux#1089]
Any chance to use a custom NavBar in conjunction with a Drawer component?
I tried something like the following code but without success.

The `static renderNavigationBar(props)` inside the Scene component of the Drawer seems not to be read. I tried also to move the `static renderNavigationBar(props)` into the `<DefaultRenderer>` component but with no success as well.

Any suggestion?
Thanks

```
class SideMenu extends Component {

    static renderNavigationBar(props) {
        console.log('SideMenu', props);
        return (
            <View style={styles.navigationBarWrapper}>
                <NavigationBar
                    title={{title:props.title}}
                    statusBar={{hideAnimation:'slide', showAnimation:'slide'}}
                    leftButton={<NavbarButton {...props} role="left" icon="ios-menu" onPress={() => alert('Toggle menu')}/>}
                />
            </View>
        )
    }

    render() {
        const state = this.props.navigationState;
        const children = state.children;

        return (
            <Drawer
                ref="navigation"
               ....
```
### Scene schema

```
...
<Scene key="drawer" title="Profile" component={SideMenu}>
     <Scene key="profile" title="Profile" component={Card.Profile}/>
</Scene>
...
```
### Version used
- react-native-router-flux v3.33.2
- react-native v0.31.0

**Comment by idris** [comment]
@charpeni did you ever find a solution to this?  I'm running into the same problem.  Navbar will not render if the Scene is wrapped in a Drawer [because of DefaultRenderer](https://github.com/aksonov/react-native-router-flux/blob/e2fb556b708527165d3a729787e6a7aa8ecdb9b3/src/DefaultRenderer.js#L233-L236)

**Comment by redbaron76** [comment]
well... in order to avoid this, I've been forced to create a new component/npm package called `navbar-native`.
you can find it here: [navbar-native](https://github.com/redbaron76/navbar-native)

**Comment by ssomnoremac** [comment]
@redbaron76 , how are you using this in RNRouterFlux? I substituted the navbar in the package you mentioned but it's still not appearing. @charpeni, why isn't this a bug? The drawer doesn't work with NarBar. I don't see a NavBar. This issue should really be: "Adding a drawer makes NavBar disappear". Is it that drawers only work with tabs?

**Comment by redbaron76** [comment]
@ssomnoremac, you can find an implementation of this in a boilerplate project called MeteorNative.
Check it out: [MeteorNative](https://github.com/redbaron76/MeteorNative)
