### ISSUE TITLE
Searchbox in NavigationBar?

### ISSUE THREAD

**Issue by maluramichael** [aksonov/react-native-router-flux#109]
Is it possible to replace the title with a search bar? 
![screen shot 2016-01-07 at 14 54 50](https://cloud.githubusercontent.com/assets/1489383/12172041/a61def34-b54e-11e5-9295-c608b83dda94.png)

**Comment by aksonov** [comment]
Just set hideNavBar={true} and use your search bar as header

**Comment by aksonov** [comment]
The same issue as #113, check answer there
