### ISSUE TITLE
Initial scene not shown

### ISSUE THREAD

**Issue by anahitsk123** [aksonov/react-native-router-flux#1091]
Here is my simple code

`  class RootApp extends Component {
	  render() {
	    return (
	      <Router>
	        <Scene key="root" hideNavBar>
	          <Scene key="pageOne" component={PageOne} title="PageTwo" initial />
	          <Scene key="pageTwo" component={PageTwo} title="PageTwo" duration={1}/>
	        </Scene>
	      </Router>
	    )
	  }
	} `

And After I run it on simulator I see a blank screen though PageOne is imported and contains simple text that is never shown.

I am quite new to react and react native, could you, please, tell me what can be the problem?

Thanks.

- react-native-router-flux v3.35.0
- react-native v0.31.0
- react 15.2.1

**Comment by anahitsk123** [comment]
Sorry, I fixed it. Seemed to be some unmet dependancy issue.

Thanks anyway

**Comment by charpeni** [comment]
I'll close this issue since it was resolved.

**Comment by YazhouMiao** [comment]
In my app this problem also happened.How do you resolve it?

**Comment by anahitsk123** [comment]
Hi YazhouMiao.

As I mentioned earlier, it was dependancy issues, so, if you still have that problem, use those versions:

"react": "~15.2.1",
"react-native": "0.31.0",
"react-native-router-flux": "3.35.0"

With those versions it works for sure.
Hope this helps.
