### ISSUE TITLE
Dropping Frames 

### ISSUE THREAD

**Issue by ja-ah** [aksonov/react-native-router-flux#1095]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.1
- react-native v0.31

working great on IOS.. but very slow on android and sometimes the app is crashing on startup.
dropping frames..

any solution ?

**Comment by warka0** [comment]
I have the same problem. 

- react-native-router-flux ^3.35.0
- react-native ^0.31.0

Transition on Android are REALLY REALLY slow and it cause a lot of bugs with input touches.
I don't know why, i'm searching. If someone know better how to fix this, it could help a lot :)

**Comment by ja-ah** [comment]
i have checked with a real phone and everything works well. speed is very good.
and now i am using genymotion samsung galaxy note 2.. speed is good. but when i turn perf monitor on. speed drops instantly .. i think there is issue with the debug mode.

**Comment by himanshusoni** [comment]
@ja-ah 

i am also facing similar issue. App is very slow on Android even on a real device.
My versions are :
- react-native-router-flux ^3.35.0
- react-native ^0.31.0

I have built a prod version using
`cd android && ./gradlew assembleRelease`

**Comment by cbrevik** [comment]
I see the same problem on Android. Both on emulator and device.

* react-native-router-flux ^3.35.0
* react-native ^0.37.0

It is dropping a lot of frames, and going down to 30-40 FPS. This is even while completely idle, does not have to be any transitioning, or any touch events.

**Comment by cbrevik** [comment]
Alright, I discovered what my issue was. 

I have a Login-component with an `ActivityIndicator` which is animating while doing some API calls. After the API calls have completed, I navigate to a new scene. I wasn't aware that components does not get unmounted when you navigate forward, and as such the `ActivityIndicator` was still running in the background even after navigating.

It seems like that animation made me drop a lot of frames on the new scene. Navigating to the new scene with something like `Actions.newSceneName({ type: 'reset' })` to reset the stack (and unmount previous components) fixed it. 

If you have the same issue and cannot unmount previous components, then just stopping the animations before navigating might fix it.
