### ISSUE TITLE
Add Features available in Navigator

### ISSUE THREAD

**Issue by waqas19921** [aksonov/react-native-router-flux#1103]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0

Add Features available in [Navigator](https://facebook.github.io/react-native/docs/navigator.html)
### Like
1. `jumpTo`  in case when using drawer.
2. `replacePreviousAndPop`
3. `getCurrentRoutes`
4. `popToTop`
5. `replaceAtIndex`

**Comment by L-Jovi** [comment]
@charpeni  hi, how should I pop to the top level component now,

thanks for your time.
