### ISSUE TITLE
Is it possible to change type of animation for scene-to-scene transition within of a tab?

### ISSUE THREAD

**Issue by alsh76** [aksonov/react-native-router-flux#1105]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v0.31.0
### Actual behaviour

Transitions between scenes inside of a tab have 'card stack' animation.

Is it possible to change this animation? I would prefer to use simple sliding animation there

**Comment by ninjz** [comment]
I too would like to know if this can be done. If you see native iOS applications like Instagram for example the scenes slide to the left on transition and does not have the popping effect

**Comment by kumarpatel** [comment]
Same. I need to know as well.
