### ISSUE TITLE
Option to not move original scene when transitioning to a new one

### ISSUE THREAD

**Issue by tonypeng** [aksonov/react-native-router-flux#1111]
### Version
- react-native-router-flux v3.35.0
- react-native v0.31

When transitioning to a new scene (I'm using float up from bottom, as this seems the closest to native Android transitions), it seems that the original scene "moves away" a bit before the next scene transitions in, creating an unappealing white border:

![image](https://cloud.githubusercontent.com/assets/2261863/18022859/86d60c8c-6ba7-11e6-93a5-555bf61f3c51.png)
(Settings is animating in, the original scene seems to be receding back and creating a white border)

How can I keep the original scene where it is, and simply float the incoming scene up on top of it?

**Comment by DClark5218** [comment]
+1 the docs aren't clear on this. A lot of the issues that are open still have references to routes on them when we are upgraded to '<Scene>' now.

Help would be appreciated!

**Comment by DClark5218** [comment]
Additionally it looks like Navigator.SceneConfigs was a way of doing this, but it has been taken out. Any reason for that @aksonov? Thanks :)

**Comment by agarcia17** [comment]
any update on this?
