### ISSUE TITLE
RN 0.32.0 - "Warning: Component's children should not be mutated. In NavBar..."

### ISSUE THREAD

**Issue by yaronlevi** [aksonov/react-native-router-flux#1112]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.32.0
### Expected behaviour

Using the type="reset/replace" on a scene should not cause the warning to show.
### Actual behaviour

Using the type="reset/replace" on a scene causes the warning to show:

![screen shot 2016-08-27 at 2 14 51 am](https://cloud.githubusercontent.com/assets/5398977/18022925/1d271204-6bfc-11e6-965c-b29a60eac79f.png)
### Steps to reproduce
1. Use this scene structure:

```
          <Scene key="root">
            <Scene key="scene1" component={scene1} />
            <Scene key="scene2" type='reset' component={scene2} />
          </Scene>
```
1. In scene1 put:

```
    componentDidMount() {
        Actions.scene2();
    }
```

3.When scene2 is shown, the warning appears.
1. This happens on the iOS simulator.

**Comment by sym900728** [comment]
The react-native-router-flux is based on RN 0.26

**Comment by sheparddw** [comment]
As sym900728 said, this package currently requires React Native 0.26.
See https://github.com/aksonov/react-native-router-flux/issues/815 for more information.

**Comment by jgkim** [comment]
I think RNRF does not depend on a specific React Native version since it uses a separated fork. It can be used with RN 0.26+.

> While ExperimentalNavigation API is not stable, RNRF uses separated fork of ExperimentalNavigation API to avoid dependency from React Native version. So 3.30 version of RNRF doesn't depend from React Native version, but from that fork (now it is based on 0.26 API). You could use this component with RN0.26+

**Comment by Oblongmana** [comment]
+1

If this has limitations on the react-native version, those should be explicitly called out in the README

**Comment by DeDuckProject** [comment]
I see this is still open. any workarounds for this? or we'll just have to live with the annoying warning?

**Comment by acgourley** [comment]
I too would like a workaround if anyone has one, it's really annoying.

**Comment by selenarakowski** [comment]
I am also looking for a work around for this.
