### ISSUE TITLE
MapView swipe down issue in scene with direction="vertical" 

### ISSUE THREAD

**Issue by veedeo** [aksonov/react-native-router-flux#1116]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.34.0
- react-native v0.30.0

### Expected behaviour
Swiping a MapView down should move its region

### Actual behaviour
MapView is locked and the whole scene moves down

### Steps to reproduce

1. Create a component scene with a MapView and prop direction="vertical" 
2. Show it
3. Move the Map downwards

**Comment by veedeo** [comment]
I came up with quick workaround: create an empty PanResponder with onPanResponderTerminationRequest=>false and add it to MapView container
Same code fixes this issue for all scrollable components placed into Scene
```
componentWillMount() {
    this._panResponder = PanResponder.create({
      onPanResponderTerminationRequest: (evt, gestureState) => false,
      onMoveShouldSetPanResponder: (evt, gestureState) => true,
      onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,
    });
  }
render() {
    return (
       <View {...this._panResponder.panHandlers}>
        <MapView...
```

**Comment by brunolemos** [comment]
@veedeo if I use this, the listview doesn't scroll. Do you know a better solution to that?
cc @asokol 

Created #1253, possibly related but not duplicated.

**Comment by asokol** [comment]
Did `panHandler={null}` on <Scene> work for you here? In my case, I just needed to disable swipe up/down for modal
