### ISSUE TITLE
Jest test support

### ISSUE THREAD

**Issue by maksim-harakhovich-itechart** [aksonov/react-native-router-flux#1120]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.30.0
- jest v14.1.0
### Expected behaviour

Running `Jest` test  shouldn't complain on `react-native-router-flux`.
### Actual behaviour

I have following `Jest` test 

```
import 'react-native';
import React from 'react';
import Component from '../Component'; // RN component
import renderer from 'react-test-renderer';

describe('Component', () => {

  it('renders correctly', () => {
    const tree = renderer.create(
      <Component />
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });

});
```

When RN component has `import { Actions } from 'react-native-router-flux';`, jest gives such error:

```
  Runtime Error
  TypeError: Cannot read property 'source' of undefined
        at Object.<anonymous> (node_modules/react-native-router-flux/src/NavBar.js:155:74)
        at Object.<anonymous> (node_modules/react-native-router-flux/src/DefaultRenderer.js:21:41)
        at Object.<anonymous> (node_modules/react-native-router-flux/index.js:3:50)
```

Without `import { Actions } from 'react-native-router-flux';` all goes fine.
### Steps to reproduce
1. Create  RN component.
2. Add `import { Actions } from 'react-native-router-flux';`.
3. Create `Jest` test.
4. Run `Jest` test.

**Comment by charpeni** [comment]
Hi @maksim-harakhovich-itechart,

When I integrated Jest Snapshot in this repo, I have not had this issue.

Can you compare with the example project : https://github.com/aksonov/react-native-router-flux/tree/master/Example/__tests__

**Comment by maksim-harakhovich-itechart** [comment]
Hi @charpeni, I followed this doc https://facebook.github.io/jest/docs/tutorial-react-native.html#content.
 Comparing with the example - all looks the same.
Forgot to mention: Jest version is 14.0.1

**Comment by sharpred** [comment]
I had the same issue as Maxim, I compared my code with Example and saw that the test has
`jest.unmock('Image');`

which I added and it fixed my issue.  Not quite sure why, but I did see that the error in NavBar.js is thrown at line 155 which is
`backButtonImage: Image.propTypes.source,`

**Comment by rseemann** [comment]
This is due to Jest, in an old version, not having Image mocked. This has been fixed here: https://github.com/facebook/jest/pull/1451. The problem should go away if you update your jest version.
