### ISSUE TITLE
scene(same component. different key) quickly changed but data did not changed

### ISSUE THREAD

**Issue by skyFi** [aksonov/react-native-router-flux#1124]
### Version:
- react-native-router-flux ^3.34.0
- react-native v0.31.0
### Problem:

scene quickly changed but data did not changed
### code:

``` javascript
[...]
<Scene key="schoolDetail" component={SchoolDetail} [...]/>
[...]
```

``` javascript
 Actions.schoolDetail({detail});
```

**Comment by onatm** [comment]
@skyFi have you found any solution? I have same issue.

**Comment by timbielawski** [comment]
I have found that when pushing on the same component no life cycle events are called only render.
So I would check what is coming into render
