### ISSUE TITLE
Display image in navbar

### ISSUE THREAD

**Issue by r6203** [aksonov/react-native-router-flux#113]
Is it possible to display a logo (image) in the navbar?

Before using react-native-router-flux, I used the react-native Navigator component with a Navigator.NavigationBar.
Then I used a routeMapper which returns an image for the 'Title'.

I tried to use the Header prop but using it seems that the Header is not displayed at all...

**Comment by aksonov** [comment]
Please check header prop now or pass render function to renderTitle attribute (like it is supported by exNavigator)

**Comment by luisfuertes** [comment]
On android cant center image on navBar. 

Code of renderTitle:
				
```
<View style={{
					flex: 1,
					alignItems: 'center',
					justifyContent: 'center',
				}}>
					<Image
						source={require('./Resources/logo2.png')}
						style={{ height: 30, width: 76}}
						resizeMode="cover"
					/>
				</View>
```

And navBar style:
```
flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#E12518',
```
