### ISSUE TITLE
Hide leftButtonImage

### ISSUE THREAD

**Issue by manask88** [aksonov/react-native-router-flux#1130]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.26.3

There is a property to hide the back Image using hideBackImage.
I was hoping to do the same for the left Image. However, it seems like the property is not implemented.

Is there any way to hide the back image?
I need this because I am using font icons. So, I ideally, I will just use the text properties (leftButtonTextStyle and leftTitle) to set the icon for Navigation Bar: Left button.

**Comment by AndrewHenderson** [comment]
@manask88 `hideBackImage`. See: https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L182
