### ISSUE TITLE
Navbar 'title' position in IOS 

### ISSUE THREAD

**Issue by kirankalyan5** [aksonov/react-native-router-flux#1131]
Navbar title position in IOS flows to end of the navbar because absolute position , top:20. How can I fix this, Is there a way to ignore the unwnated styles.
My last option si to override these styles..

**Comment by dragfire** [comment]
Could you please attach a screenshot?

**Comment by ryanoboril** [comment]
I have this problem also, it's in version 3.36.0, this works perfectly in 3.35.0

This problem affects both iOS and Android.

<img width="372" alt="screen shot 2016-10-27 at 11 53 02 pm" src="https://cloud.githubusercontent.com/assets/4666759/19794512/c87b797c-9ca0-11e6-9e3e-f9b84f75c56e.png">

<img width="278" alt="screen shot 2016-10-27 at 11 55 32 pm" src="https://cloud.githubusercontent.com/assets/4666759/19794524/e720b7d4-9ca0-11e6-97e4-f0bb49fea9c2.png">

**Comment by jaderYang** [comment]
I meet the same question. @dragfire
![simulator screen shot 2016 11 14 10 12 31](https://cloud.githubusercontent.com/assets/13029870/20251281/23373b70-aa53-11e6-968e-affc2fb5387a.png)
