### ISSUE TITLE
The default NavBar prevents swipe back on Android

### ISSUE THREAD

**Issue by charpeni** [aksonov/react-native-router-flux#1134]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.32.0

If you remove `hideNavBar` from the Example ([here](https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L96)), you won't be able to swipe back to the previous scene on Android, because it will be blocked in transition.

**Comment by charpeni** [comment]
I am currently trying to investigate this issue and it seems caused by `renderTitle`.

**Comment by charpeni** [comment]
The bug is located here : https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L436-L443

<details>
```diff
   renderTitle(childState, index:number) {
     let title = this.props.getTitle ? this.props.getTitle(childState) : childState.title;
     if (title === undefined && childState.component && childState.component.title) {
       title = childState.component.title;
     }
     if (typeof(title) === 'function') {
       title = title(childState);
     }
     return (
       <Animated.Text
         {...this.props.titleProps}
         key={childState.key}
         style={[
           styles.title,
           this.props.titleStyle,
           this.props.navigationState.titleStyle,
           childState.titleStyle,
           {
             opacity: this.props.position.interpolate({
               inputRange: [index - 1, index, index + 1],
               outputRange: [0, this.props.titleOpacity, 0],
             }),
-            left: this.props.position.interpolate({
-              inputRange: [index - 1, index + 1],
-              outputRange: [200, -200],
-            }),
-            right: this.props.position.interpolate({
-              inputRange: [index - 1, index + 1],
-              outputRange: [-200, 200],
-            }),
          },
         ]}
       >
         {title}
       </Animated.Text>
     );
   }
```
</details>

If we removed the previous lines, everything works fine except the removed animations. With this line, the default NavBar is unusable on Android. 

@aksonov can I have some of your time on this? I try to pitch RNFR for an application and it's the only blocker. That would be really appreciated.

**Comment by aksonov** [comment]
@charpeni I would like to help, but unfortunately i don't work with Android at all currently. Could we disable animations for time being?

P.S. My company is hiring now Android+React Native specialist, if you know someone, let me know.

**Comment by charpeni** [comment]
@aksonov  Good, I'll try to fix this. 

Where is your company located?

**Comment by aksonov** [comment]
California, US, but it is remote work (however full-time) and I live in Slovenia.

**Comment by charpeni** [comment]
@aksonov Can you send more information to nicolas.charpentier079@gmail.com, thank you :)

**Comment by luhui** [comment]
Hi @charpeni 
Have you fix this issue?

I just replace the animation style of left/right with translationX, and it works fine.

@aksonov, is this a correct workaround? I am not clearly that you set both left & right style at the same time.  Left style only works fine on iOS, for some compatible maybe?

```
<Animated.Text
          lineBreakMode="tail"
          numberOfLines={1}
          {...this.props.titleProps}
          style={[
            styles.title,
            this.props.titleStyle,
            this.props.navigationState.titleStyle,
            childState.titleStyle,
            {
              opacity: this.props.position.interpolate({
                inputRange: [index - 1, index, index + 1],
                outputRange: [0, this.props.titleOpacity, 0],
              }),
            transform: [{
                translateX: this.props.position.interpolate({
                    inputRange: [index - 1, index + 1],
                    outputRange: [200, -200]
                })
            }]
            },
          ]}
        >
```

**Comment by felipemartim** [comment]
Can confirm that @luhui's solution worked fine for me on Android (RN 0.37.0). The animation is not 100% smooth though, but I only tested on DEV mode.
