### ISSUE TITLE
Scenes don't recognize multiple children

### ISSUE THREAD

**Issue by PranayJuneCS** [aksonov/react-native-router-flux#1136]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0
### Expected behaviour

`<Scene key="drawer" component={Drawer} open={false} type={'replace'}>`
    `<Scene key="feed" component={Feed} />`
    `<Scene key="item" component={Item} />`
`</Scene>`

I'm using `react-native-drawer` and RNRF, and I am integrating the two the way that is specified in the [OTHER_INFO.md](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration) file. I'm trying to add more than one child to the drawer component, so that I can have the drawer span multiple components.
### Actual behaviour

Apparently, when I print out `this.props.children` of the Drawer component, there is only one child, the `Feed` component. Somehow, it is ignoring the `Item` component completely, so when I try to do `<DefaultRenderer navigationState={this.props.children[1]} onNavigate={this.props.onNavigate} />` inside the drawer component, it gives me an error, saying `navigationState and onNavigate` cannot be null (because `this.props.children` is length 1).

Any ideas/answers for what I am doing wrong?

**Comment by zjaml** [comment]
+1, I'm having exactly a same confusion. Would only be natural  to include all child scenes into navigationState prop.  In that way side menu can be built directly from scene configuration. Drawer content switch will be easier too.
