### ISSUE TITLE
How to change route within reducer?

### ISSUE THREAD

**Issue by MikkelSnitker** [aksonov/react-native-router-flux#1139]
Hi. 

I've just started using your router and i really like it.
I do however got a problem understanding how i can change the scene within my route reducer?

I've followed the steps in https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md but i can't see how to change the scene within the route reducer?

it there a example where i can how i can do that?

/Mikkel

**Comment by aksonov** [comment]
FYI, Navigation action is real side effect and MUST NOT BE raised from reducer. You may just call Actions.ROUTE from redux-saga or other side-effect redux library.
