### ISSUE TITLE
How do I pop back to another router?

### ISSUE THREAD

**Issue by wootwoot1234** [aksonov/react-native-router-flux#114]
I have an app where there is a main page and a viewer that shows pages of a book.  Once the viewer reaches the end of the book it needs to return to the main page.  The problem is if I just call ```Actions.Main();``` to go to the main page I notice that code on the viewer keeps running as I change my store.  How do I go back to the main page and remove the viewer from memory so it no longer runs when changes are made to the store?

Here's my layout:

    <Route name="Main" component={connect(mapStateToProps, mapDispatchToProps)(Main)} title="Main"/>

    <Route name="Viewer">
        <Router>
            <Route name="Page" component={connect(mapStateToProps, mapDispatchToProps)(Viewer)} title="Viewer" schema="turnPage"/>
        </Router>
    </Route>

I don't think ```Actions.pop()``` works because I'm trying to go from one router to another.

Any ideas?

**Comment by aksonov** [comment]
pop() is most suitable when you need to remove scene from memory. Or try 'reset' type for Main so Actions.Main() will reset nav stack.

**Comment by wootwoot1234** [comment]
@aksonov, thanks for the response.
