### ISSUE TITLE
Modal outside/on top of drawer height

### ISSUE THREAD

**Issue by juanpasolano** [aksonov/react-native-router-flux#1141]
### Version
- react-native-router-flux v3.35.0
- react-native v0.30.0

### Expected behaviour
I've been trying to make a modal work on top of the drawer with height:100%, so I can call the modal from within the drawer and return afterwards to an open drawer.

### Actual behaviour
The modal comes out but just occupies half of the screen
![screen shot 2016-09-05 at 08 35 50](https://cloud.githubusercontent.com/assets/1621720/18249963/a8289eee-7346-11e6-9b33-5a42c9d8b73a.png)

### Steps to reproduce
This is how my routes are configured
```jsx
      <Router>
        <Scene key="modal" component={Modal} >
          {/* drawer */}
          <Scene key="drawer" component={Drawer} open={false} >
            <Scene key="root" hideNavBar={true}>
              <Scene key="home" component={Home} title="Discussions"/>
            </Scene>
          </Scene>
          {/* modal */}
          <Scene key="myModal" component={MyModal} direction="vertical" title=""/>
        </Scene>
      </Router>
```

I've tried adding `height: Dimensions.get('window').height` to the modal, but the measurement is not accurate.

**Comment by juanpasolano** [comment]
For anyone interested I managed to get the height working by adding styles to the model like so

```
import {
  Dimensions,
  StatusBar,
} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1, 
    position:'absolute', 
    top:0, 
    left:0, 
    height: Dimensions.get('window').height - StatusBar.currentHeight, 
    width: Dimensions.get('window').width
  }
});
```

**Comment by anuragalla** [comment]
@juanpasolano i had similar problem using modal with drawer. I was able to reposition the scene using your solution. Additionally i cannot get the navigation bar to display in my modal. Is there any way to get the navigation bar to display

**Comment by ryancoughlin** [comment]
I am having the same issue. I can't seem to get it to open up as expected including the navigation bar.
