### ISSUE TITLE
Navigation bar backButtonImage - can we use Icon instead if image  

### ISSUE THREAD

**Issue by kirankalyan5** [aksonov/react-native-router-flux#1143]
Hi, 

I wanted to use Icon (react-native-vector-icons) instead of image in Navigation bar backButtonImage , has anyone tried this, or any alternate way to do this with the same behavior.
Thanks in advance.

**Comment by iDay** [comment]
renderBackButton={(nav) => {
                    return nav.navigationState.index ? (
                        <TouchableOpacity onPress={Actions.pop}>
                            <Icon name={ionicon('arrow-back')} size={26} color='#FFFFFF' />
                        </TouchableOpacity>
                    ) : null;
                }}

**Comment by ThaJay** [comment]
https://github.com/oblador/react-native-vector-icons
```
<Icon.ToolbarAndroid />
```

**Comment by haikyuu** [comment]
It didn't work for me when i had the `renderBackButton` in the root Scene.
But when i put it inside individual scenes, it works smoothly.
