### ISSUE TITLE
Question: Scene specific back button behavior [Android]

### ISSUE THREAD

**Issue by sreejithr** [aksonov/react-native-router-flux#1146]
In the current version I've installed (3.35.0), there's provision to assign custom `backButtonHandler` for the `Router`. While this is useful, my app requires custom behavior in certain screens.

In the previous version, I used to have a global `BackAndroid` event listener which gets the component currently in foreground from the navigation stack with `Actions.currentRouter.stack`. In the component's prototype chain, I had a `onBackButton()` method which handles custom behavior.

The new Action API doesn't have currentRouter exposed. I can `addEventListener` in every component and `removeEventListener` on `componentWillUnmount`. But, is there a cleaner way to achieve this?

If not, I propose that we either:
1.  Have `backButtonHandler` prop in `Scene` API.
2. Pass some extra arguments like currentComponent, to the back button handler's call.

What do you guys think?
### Versions
- react-native-router-flux - 3.35.0
- react-native 0.28.0

**Comment by ThaJay** [comment]
+1 probably

I was using
```
BackAndroid.addEventListener('hardwareBackPress', processBackPress)
```
and
```
function processBackPress () {
  if (sceneKey === SETTINGS && !navigate.back()) confirmLogout()
  if (!navigate.back()) {
    if (sceneKey === LOGIN) return false
    else if (sceneKey === DRAWER) return Actions.refresh({key: 'drawer', open: false})
    else if (sceneKey === SCAN || sceneKey === RESULT) navigate.to(SETTINGS)
  }
  return true
}
```
I'm using the following wrapper code so I am able to swap out the navigator without changing my components. It just calls `pop()`.:
```
import {Actions} from 'react-native-router-flux'
const navigate = {
  to: (route, props) => Actions[route](props)
, back: props => Actions.pop(props)
}
export default navigate
```
It worked like a charm but now I get `You are already in the root scene` error on anything that's not default behavior.

**Comment by Cucurrucho** [comment]
Hey, i'm having the same problem and it seems that removing the event handler with the componentWillUnmount method doesnt work with this library, did you find any other solution?

**Comment by Swordsman-Inaction** [comment]
You should upgrade RN to 0.32.

With [this](https://github.com/facebook/react-native/commit/b8576312ca4a950d8bf4a5f4ec3a80c4f55d88b0), you can have the global handler   for most scenes. For those special scenes, you can add `BackAndroid.addEventListener('hardwareBackPress', this.handleAndroidBack)` in them, RN will call the later listener callback first, the global handler would not be called if you `return true` in the later listener callback. I think it's a better solution. Just remember to remove listener callback.
