### ISSUE TITLE
Component from the previous scene when i push a new scene

### ISSUE THREAD

**Issue by sarovin** [aksonov/react-native-router-flux#1149]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.2
- react-native v0.32.0
### Expected behaviour

when i push a new scene, the previous scene must be unmounted.
### Actual behaviour

when i push a new scene, i can see element of the previous scene.
### Steps to reproduce

I have a scene with a Modal component as this.

``` javascript
<View>
  <Modal
    animationType={'fade'}
    transparent
    visible={this.props.isWaiting}
    onRequestClose={() => {
      this.setState({
        modalVisible: false,
      });
    }}
  >
    <ActivityIndicator
      // ...
    />
  </Modal>
  <View>
    // ...
  </View>
</View>
```

P.S. this.props.isWaiting is a REDUX props.

In the second scene i don't have Modal but i see the modal when the REDUX Action set this.props.isWaiting at true because the previous scene is not unmounted, right?

There is a fix for this? I don't want to lost the backButton but i think that is a problem if i see the component of the previous scene.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5980398/18317429/6bb7945e-751e-11e6-82f9-2d96be75281a.gif)

**Comment by yasheshkt** [comment]
@sarovin - Does this seem some issue with Router Flux?

**Comment by sarovin** [comment]
@yasheshkt yes, you use it?

**Comment by yasheshkt** [comment]
@sarovin - Yes. I have issue in map when i use Map with Router Flux. Did you also face such issue? Like overlapping of one map on other? If yes, did you find some workaround that we could use?

**Comment by sarovin** [comment]
@aksonov have any suggestions?

**Comment by hubciorz** [comment]
@sarovin Could you please tell why did you close the issue? It seems that I am having a similar problem. Did you solve that?

**Comment by sarovin** [comment]
@hubciorz Do you use react-native-maps???

**Comment by keenltd** [comment]
@sarovin Hi, im using react native maps along with router flux. I have 4 tabs in my app. The 3rd tab is the map view. When I click on the 3rd tab and then back to the 1st or 2nd tab that map view will always show above the content of the 1st and 2nd tab. However It will never show above the 4th tab. Is this a similar issue to what you are experiencing?

**Comment by susan-github** [comment]
If I don't want to upgrade it to v4, what can I do?
