### ISSUE TITLE
Question: How to set different styles for each selected tab icon 

### ISSUE THREAD

**Issue by bennygenel** [aksonov/react-native-router-flux#1155]
### Version
- react-native-router-flux v3.35.0
- react-native v0.32

I want to set different styles for each tab icon on select. For example giving them a different background-color etc..

Is there a way to set **tabBarSelectedItemStyle** for each individual tab?

Does anyone have any suggestions?

**Comment by ssomnoremac** [comment]
Just create a component for each tab scene and then set it on the scene using `tab={mytabcomponent}` look at the detailed example.
