### ISSUE TITLE
Is the Documentation of "Reactive/Redux/Flux" is correct or working?

### ISSUE THREAD

**Issue by krishbhattacharyya** [aksonov/react-native-router-flux#1156]
### "Reactive/Redux/Flux" setup problem

Have anyone tried to follow "Reactive/Redux/Flux" documentation?

https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md 

Or can anyone provide the working setup?

**Comment by charpeni** [comment]
What is your issue exactly and what are you trying to do ?

**Comment by krishbhattacharyya** [comment]
I got the error:

![error_small](https://cloud.githubusercontent.com/assets/10433734/18400669/8cac6126-76f4-11e6-8947-b08a460e23ac.png)

**Comment by charpeni** [comment]
You're right, the sample contains an error.

```diff
- import React, { PropTypes, Text } from 'react-native';
+ import React, { PropTypes } from 'react';
+ import { Text } from 'react-native';
 import { connect } from 'react-redux';
```

I'll fix this on the documentation, thank you.

Let me know if it doesn't solve your issue.

**Comment by krishbhattacharyya** [comment]
Hi, 

You should add one thing more in app.js.

import { Router, Scene } from 'react-native-router-flux'; // Scene  is missing there 

Though I am getting another error- undefined is not an object ( evaluating 'el.props.component');

**Comment by charpeni** [comment]
Can you send a screenshot of this?

**Comment by krishbhattacharyya** [comment]
![error_small2](https://cloud.githubusercontent.com/assets/10433734/18401385/e90d2632-76f7-11e6-8382-19942ce623ce.png)

**Comment by krishbhattacharyya** [comment]
In the provider section I have import MyComponent

 <Provider store={store}>
        <RouterWithRedux>
            // your scenes here
            <Scene key="MyComponent" component={MyComponent} title="Replace" type="replace"/>
        </RouterWithRedux>
      </Provider>

**Comment by manishtuteja10** [comment]
@krishbhattacharyya - were you able to resolve the above issue ? I am getting the same error. :/

**Comment by aesmon** [comment]
@manishtuteja10 @krishbhattacharyya  - Same issue. Did you guys find any solution yet?

**Comment by krishbhattacharyya** [comment]
@manishtuteja10 , after struggling long days I did not used this . But anyone can close this issue if it's worked.

**Comment by manishtuteja10** [comment]
It worked for me. I followed the documentation below.
https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md
