### ISSUE TITLE
how can I use my user-defined icon in tab bar? Thanks.

### ISSUE THREAD

**Issue by leonardgithub** [aksonov/react-native-router-flux#1158]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.?.?
- react-native v0.?.?

"react": "15.3.0",
"react-native": "0.32.0",
"react-native-router-flux": "3.31.1",
### Expected behaviour

use my user-defined icon in tab bar
### Actual behaviour

I do not how to use my user-defined icon in tab bar

`<Scene key='Main'
                  title={I18n.t('Snowflake.main')}
                  iconName={"home"}
                  icon={TabIcon}
                  hideNavBar
                  component={Main}
                  initial />`

**Comment by ssomnoremac** [comment]
`icon={myIconComponent}`
