### ISSUE TITLE
swipe gesture is hard to trigger

### ISSUE THREAD

**Issue by inetfuture** [aksonov/react-native-router-flux#1162]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.3
- react-native v0.29.0
### Expected behaviour

swipe gesture is easy to trigger like built-in iOS apps
### Actual behaviour

Feels not responsive, must be very slow and steady to trigger it.

Or, is there any params can be tweaked?

**Comment by CasperMunk** [comment]
Under the API there's a function to override the gesture handlers: getPanHandlers 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#gestures

Example: https://github.com/aksonov/react-native-router-flux/issues/1237. In the bottom there's a link to a working example.
