### ISSUE TITLE
You are already in the root scene (on back / pop)

### ISSUE THREAD

**Issue by ThaJay** [aksonov/react-native-router-flux#1165]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.32.0

### Expected behaviour

My back button function works.

### Actual behaviour

It broke in this version. No docs or change report as far as I have seen

### Some code

I was using:
```es6
BackAndroid.addEventListener('hardwareBackPress', processBackPress)
```
with:
```es6
let sceneKey = ''
// I don't like this part either, but it makes things easy.
function routeReducer (state, action) {
  if (action.type === ActionConst.FOCUS) {
    sceneKey = action.scene.sceneKey
    return state
  }
  return state || {}
}
```
and:
```es6
function processBackPress () {
  if (!Actions.pop()) {
    switch (sceneKey) {
      case LOGIN:
        return false
      case DRAWER:
        Actions.refresh({key: 'drawer', open: false}); break
      case SETTINGS:
        confirmLogout(); break
      case SCAN:
      case RESULT:
        Actions.settings()
    }
  }
  return true
}
```
That same function is called onPress of the back button in the nav bar when present.

It worked like a charm but now I get `You are already in the root scene` error on the cases that run some code then return true.

### Some links

https://github.com/aksonov/react-native-router-flux/issues/1146

https://github.com/aksonov/react-native-router-flux/blob/0ef1f7a19ca30d99e1892595da5be67a15c8fc22/src/Router.js#L58-L82

https://github.com/aksonov/react-native-router-flux/issues/1065

I went back to react-native-router-flux v3.34.0 for now.

**Comment by mattvot** [comment]
Had the same issue.

Looks like you no longer need to `pop` on a hardwareBackPress. See https://github.com/aksonov/react-native-router-flux/commit/0ef1f7a19ca30d99e1892595da5be67a15c8fc22

**Comment by Swordsman-Inaction** [comment]
like @mattvot said, RNRF will pop the scene by default. you can also change the default handler. 

But if you are using RN 0.32 and above, according to [this](https://github.com/facebook/react-native/commit/b8576312ca4a950d8bf4a5f4ec3a80c4f55d88b0), the later subscription callback will be call first, if the later one return true, the remaining callbacks would not be called any more. So you might call `Action.pop()` and `return false` at the same time if you got `You are already in the root scene` error.

**Comment by sibelius** [comment]
@charpeni u can also close this

**Comment by afilp** [comment]
Related to this, how can we detect that an action will be the last pop? Through the reducer? Or with another API call?

**Comment by cuitianze** [comment]
I meet this issue when i click back button fast.

**Comment by Micjoyce** [comment]
I have two page, hom  --> detail, home (Actions.detail()) and detail(Actions.pop()) , If I click fast from home to detail and pop detail to home. At developing environment will get
 
> You are already in the root scene. 

when I do release android apk.
Fast click will cause the app quit. 
It is posiable to fixed this problem.

**Comment by Swordsman-Inaction** [comment]
@cuitianze @Micjoyce 
Yes, we should fix this. A little busy recently, but I'll try to fix this as soon as I can.

**Comment by PeterRock** [comment]
I think you should use `onExitApp` for `Router`
Just like sattaman [did:](https://github.com/aksonov/react-native-router-flux/issues/1065)

**Comment by ThaJay** [comment]
@PeterRock I'm still on v3.34.0 where my code works.
I also did not encounter the error on quickly pressing the back button multiple times.
