### ISSUE TITLE
Cannot set renderLoading or renderError for Relay container

### ISSUE THREAD

**Issue by carleryd** [aksonov/react-native-router-flux#1166]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.30.0
- react-relay v0.9.3

I am using router-flux with relay, and I have gotten it working very nicely! However since I no longer use RootContainer, I dunno how to set the `renderLoading` or `renderError` props available on RootContainer. Could this be added on Scene perhaps?

Here is a gist of how I use my containers with router-flux https://gist.github.com/carleryd/d2fabee297ed6781a97e34dbc291f5aa

**Comment by vladar** [comment]
In case if you haven't seen it yet - check out https://github.com/r0b1n/rnrf-relay-renderer
It gives some insights on how to do it.
