### ISSUE TITLE
Scene not unmounting using Switch

### ISSUE THREAD

**Issue by CoteViande** [aksonov/react-native-router-flux#1170]
### Version
- react-native-router-flux v3.35.0
- react-native v0.30.0
### Expected behaviour

I am using a Switch that, depending upon an `isLoggedIn` value in my state selects either the `Auth` group of scenes or the `AppMain` group.
Upon updating `isLoggedIn` in my state, I expect the scenes (or at least the current one) nested in `Auth` to unmount.
### Actual behaviour

The component changes `isLoggedIn` but the `RegisterEmail` actually never triggers `componentWillUnmount`.
#### Here is my Scene config

```
  <Scene key="root" hideNavBar={true}>
    <Scene key="LoginAccessControl" hideNavBar={true} tabs={true}
      component={
        connect(
          state=>({ isLoggedIn: state.auth.user.isLoggedIn })
        )(Switch)
      }
      unmountScenes
      selector={
        props => props.isLoggedIn ? "AppMain" : "Auth"
      }
    >

      <Scene
        key="Auth" default="AuthMain" hideNavBar={true}
      >
        <Scene
          key="AuthMain" component={AuthMain} title="Login" hideNavBar={true}
        />
        <Scene
          key="RegisterEmail" component={RegisterEmail} title="Register" hideNavBar={false}
        />
        <Scene
          key="LoginEmail" component={LoginEmail} title="Login" hideNavBar={false}
        />
      </Scene>

      <Scene
        key="AppMain" default="Home" tabs={true} hideNavBar={true}
      >
        <Scene
          key="Home" component={Home} title="Home" icon={TabIcon} hideNavBar={true} initial={true}
        />
        <Scene
          key="Profile" component={Profile} title="Profile" icon={TabIcon} hideNavBar={true}
        />
      </Scene>

    </Scene>
  </Scene>
```
#### Steps:
1. Navigate to RegisterEmail
2. Fill out form
3. Submit form, thus triggering `isLoggedIn` state to be `true`
4. Automatically navigates to `Home` but the focus is still on a `RegisterEmail TextField`
### Notes
- Is it possible to manually unmount a specific scene?
- Adding a `type="reset"` on `AppMain` does the trick but removes the tabBar, and, I guess, will trigger at each tab change.

**Comment by CoteViande** [comment]
Hey! I used a 'reset' transition upon finishing my action which has the unhealthy side effect to remove (splice) my auth group, meaning that, while doing the next switch use, the auth group is not there anymore.

**Comment by CoteViande** [comment]
I have been experimenting with logs a little and apparently, upon switching to `AppMain`, it resets `AppMain` and not `Auth`.

FYI, I'm logging the elements in `resetHistoryStack` function in `Reducer.js`. Upon switching from Auth to AppMain, it displays:

```
09-16 04:19:11.635  3001 11903 I ReactNativeJS: 'RESET HISTORY STACK: ', '1_AppMain'
09-16 04:19:11.635  3001 11903 I ReactNativeJS: 'RESET HISTORY STACK: ', '0_Home'
09-16 04:19:11.635  3001 11903 I ReactNativeJS: 'RESET HISTORY STACK: ', '1_Profile'
```

**Comment by sarovin** [comment]
#1386 this solve your problem????

**Comment by CoteViande** [comment]
No I do not think so. I can't trigger a `ComponentWillUnmount` on my `RegisterEmail` component after the Switch.

In addition, when I register, then log out and go back to the RegisterEmail scene, I get a `navigationState.children[2].key"scene_RegisterEmail_1_RegisterEmail" conflicts withanother child!`

**Comment by leomar-developer** [comment]
Can anyone explain why when using "unmountScenes" on a tabs scene the TabBar is not rendered? the only way I have been able to make the TabBar appear is to not use the "unmountScenes" attribute. I'm using RNRF v3.35.0 and RN 0.35.0

**Comment by gijoehosaphat** [comment]
Confirming this does not solve the issue. The scenes are either never unmounted, or are over-eagerly unmounted via type={ActionConst.RESET} and cannot be navigated to.

**Comment by ujwal-setlur** [comment]
I am seeing this too. unmountScenes does not seem to unmount when the Switch is activated. Components seem to get unmounted later, almost a lazy unmount.
