### ISSUE TITLE
Remove Back Button For Android

### ISSUE THREAD

**Issue by alexcurtis** [aksonov/react-native-router-flux#1173]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.34.0-rc.0

Since android already has a back button, is it possible to completely remove the leftButton (back etc)?
I've tried `renderBackButton={null}` and `hideBackImage={false}` and they didn't work.

**Comment by markrickert** [comment]
I was going to reply here and ask how you solved this issue, then i realized you had tried `hideBackImage={false}` where it SHOULD be `hideBackImage={true}` or simply: `hideBackImage`.

```js
<Scene key='myScreenWithNoBackButton' component={MyScreenWithNoBackButton} hideBackImage />
```

**Comment by AndrewHenderson** [comment]
@markrickert @alexcurtis I am using `hideBackImage`. While the image does not appear, if I press the spot where the back button would be, it still navigates back. 😕 

Tell us which versions you are using:

- react-native-router-flux v3.36.0
- react-native v0.37.0

**Comment by leocabral** [comment]
@AndrewHenderson hey!

i've hacked this annoying behavior like this:

`<Scene key='myScreenWithNoBackButton' 
component={MyScreenWithNoBackButton} 
hideBackImage  onBack={() => null}/>`

hope it helps you 😃 

have a good one!

**Comment by kazimmusani** [comment]
import { BackAndroid } from 'react-native';

componentWillMount() {
        BackAndroid.addEventListener('hardwareBackPress', () => {return true});
 }

**Comment by hnhm** [comment]
Use:

```js
import { ... BackAndroid } from 'react-native';

componentDidMount() {
  BackAndroid.addEventListener('hardwareBackPress', () => { return true });
  ...
}
componentWillMount() {
  BackAndroid.removeEventListener('hardwareBackPress', () => { return true });
  ...
}
```

**Comment by benvium** [comment]
@vnhnhm A quite note to say that your event handler won't be removed in the code you posted. You're creating a new instance of a closure and passing it to removeEventListener.

We use:
```js
constructor(props) {
  ....
  this.handleBackAndroid = () => true;
}

componentDidMount() {
  BackAndroid.addEventListener('hardwareBackPress', this.handleBackAndroid);
  ...
}
componentWillMount() {
  BackAndroid.removeEventListener('hardwareBackPress', this.handleBackAndroid);
  ...
}
```

**Comment by vnhnhm** [comment]
Thanks @benvium, I haven't noticed it.
