### ISSUE TITLE
Actions.refresh refreshes current scene and tabbar scene when using tabbar

### ISSUE THREAD

**Issue by manask88** [aksonov/react-native-router-flux#1176]
### Version

Tell us which versions you are using: 
    "react-native-router-flux": "^3.35.0",
    "react-native": "^0.33.0",
### Expected behaviour

Actions.refresh() should only refresh the current screen
### Actual behaviour

Actions.refresh() refreshes current screen and others. I have seen this behavior when using Modals and TabBar
### Steps to reproduce
1.  print action.scene.key in the reducer in the example
2. Add   <Button onPress={Actions.refresh}>refresh</Button> to TabView.js
3. go to the tabbar screen
4. Click on Refresh

In the console, the expectation is to get action.scene.key printed once every time you hit refresh. However, it's also printing the tabbar scene key and the modal scene key, which means it's refreshing not only the current scene but others that were mounted previously.

**Comment by compojoom** [comment]
wow! I just ran into something that I think is related, but with the normal Navigation. 
Basically in the parent component I was reacting on componentWillReceiveProps and when the new props are different I was re-rendering the navigation. The issue with that was that my props can change in response of a synchronisation action. 

So out of that scene I'm navigating to a new Scene. Then few seconds later after the sync action completes the parent scene has new properties and it does Actions.refresh and this changes the navigation on the current page.
