### ISSUE TITLE
Is there any available docs for how to use and customize navbar?

### ISSUE THREAD

**Issue by jsdario** [aksonov/react-native-router-flux#1179]
I am looking for plain navigation bar or how to implement my own. If there is out there any alternative best practice I'll welcome it!
### Versions

```
    "react-native": "^0.31.0",
    "react-native-router-flux": "^3.35.0"
```

**Comment by CoteViande** [comment]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#navigation-bar
Is that not enough?

**Comment by jsdario** [comment]
I do appreciate the documentation work – which is nice. And the devoted to maintain this library. However I am missing examples on how to obtain precise navbar configurations. If they are only documented I need to try API methods one by one to see the result. That is which I have eventually done, but specifying a couple of popular use cases (with or without screen captures) I belive would increase library adoption.
