### ISSUE TITLE
How do I make react-native-router-flux work with redux connect?

### ISSUE THREAD

**Issue by gkrinc** [aksonov/react-native-router-flux#1181]
### Version
- react-native-router-flux v3.34.0
- react-native v0.34.0-rc.0
  -react-router-redux v4.0.4
### Expected behaviour

Like the push method from react-router-redux, I expected Actions.<scene> to return an action.
### Actual behaviour

Actions.<scene> dispatches actions itself
### Issue Details

I'm using react and react-native across web, iOS and Android. In my container I have a method that dispatches some actions, then changes the route (web) / scene (mobile). The route/scene change is a method in my actionCreators and is connected to the component through react-redux. When I connect the actionCreator method is wraps the method call in a dispatch() which expects an action as a param.

In the web version, the push() method returns the action, which then gets dispatched by react-redux.

```
export function navigateToRoute(route) {
    return push(route);
}
```

In the native version the Actions.<scene> call returns nothing so the dispatch call fails. In order for this to work I have to call Actions.venue(), then return a dummy action, which seems really asinine.

```
export function navigateToRoute(route) {
    switch(route) {
        case ROUTES.VENUES:
            Actions.venues();

            return {
                type: 'ROUTE.DUMMY.CHANGE'
            };
            break;
    }
}
```

What is the best approach to making this work across web and native? Thanks

**Comment by thienanle** [comment]
+1
