### ISSUE TITLE
Setting status bar component for all scenes

### ISSUE THREAD

**Issue by sadika9** [aksonov/react-native-router-flux#1183]
Is it possible to set [Status Bar](https://facebook.github.io/react-native/docs/statusbar.html) for all scenes?
### Version
- react-native-router-flux v3.35.0
- react-native v0.33.0

**Comment by alexcurtis** [comment]
Yeah. I just add it at the root level (same as `<Router/>`).

```
<View style={styles.application}>
  <StatusBar barStyle="default"/>
  <Router/>
</View>
```

**Comment by sadika9** [comment]
@alexcurtis  I've already tried it. When I wrap Router with a View it does not render at all (white screen)

**Comment by coreyphillips** [comment]
@sadika9 you're not going to want to wrap <Router/>. Notice in @alexcurtis' example the StatusBar component is self-closing: <StatusBar barStyle="default"/>

**Comment by sadika9** [comment]
@alexcurtis @coreyphillips Thank you

**Comment by nonameolsson** [comment]
Thanks, very nice!

But when I use Redux and wrap my Router in a Provider I get an error. I'm not sure if it has to do with react-native-router-flux or Redux. What do you think?
```
      <View>
        <StatusBar
          backgroundColor='#303F9F'
          barStyle='light-content'
        />
        <Provider store={store}>
          <Router />
        </Provider>
      </View>
```

**Comment by nonameolsson** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/1493018/21771022/13859d8e-d686-11e6-8283-c1bdf1db9329.png)

**Comment by coreyphillips** [comment]
@nonameolsson The error does not appear to be related to `react-native-router-flux` or `redux`. The error appears to be reporting that one of your variables is undefined in the `App` component. Based on the code snippet you provided I would check that the `store` variable is indeed defined. If it is, I would check other variables you may have in that component. Finding that rogue variable should fix your error.

Also, to add to my previous comment, you may need to add a `flex: 1` style to the `<View>` wrapper for it to properly render to the view.

**Comment by QiquWong** [comment]
@sadika9 I also encountered this issue about white screen, how do you solve it?

**Comment by sadika9** [comment]
I did what  alexcurtis & coreyphillips said

**Comment by Shu-Ji** [comment]
I also encountered this issue about white screen：
![image](https://user-images.githubusercontent.com/1127594/35904386-e0db04e0-0c1d-11e8-9db2-10902b29a4df.png)
