### ISSUE TITLE
How do i add a right nav bar button?

### ISSUE THREAD

**Issue by jaronoff97** [aksonov/react-native-router-flux#1192]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.32.1
### Expected behaviour

Add right button to nav bar, click and go to a new scene
### Actual behaviour

I'm trying to add a right button in my navigation bar, but it's just rendering as a text, and i added a log for when the text is pressed but thats not happening
### Steps to reproduce
1. <Scene key="list" component={ COMPONENTNAME } direction={ 'horizontal' } onRight={ () => console.log('right pressed') } renderRightButton={ () => <Text onPress={ console.log('right pressed') }>Post</Text> } type={ ActionConst.REPLACE }
           title="APP NAME" />

**Comment by anhtuank7c** [comment]
add following code to your `COMPONENTNAME`
```
import React from 'react';
import { TouchableOpacity, Text } from 'react-native';

class COMPONENTNAME extends React.Component {

    static renderLeftButton = (props) => {
          return (
              <TouchableOpacity onPress={() => console.log('onLeftPressed')}>
                  <Text>Left Button</Text>
              </TouchableOpacity>
          );
    }

    static renderRightButton = (props) => {
          return (
              <TouchableOpacity onPress={() => console.log('onRightPressed')}>
                  <Text>Right Button</Text>
              </TouchableOpacity>
          );
    }
}
```
