### ISSUE TITLE
How to have different navbar and transitions for Android and iOS?

### ISSUE THREAD

**Issue by nbastoWM** [aksonov/react-native-router-flux#1194]
### Version
- react-native-router-flux v3.35.0
- react-native v0.33.

In Android the navbar should only have the title and have no transitions between pages.
How can I do this? 
In the examples there's only a index.js and no difference between android and ios. 
I tried to hide the navbar if Platform.OS is android but then the title also disappears. 
Am I missing something?
Thanks.

**Comment by ttdat89** [comment]
<Scene duration={Utils.isIOS() ? transitonDuration(ms) : 0} />
