### ISSUE TITLE
Example's Redux implementation doesn't trigger in reducer

### ISSUE THREAD

**Issue by redbaron76** [aksonov/react-native-router-flux#1196]
Hello,

Is there any reason why, in my case, the route reducer doesn't get any type from ActionConst when, let's say, a page changes?

From the documentation it seems that any Action should dispatch an action to route reducer in Redux but in my case it does nothing. Any idea?

You can find my Redux implementation in this ReactNative / Meteor boilerplate.
[BOILERPLATE](https://github.com/redbaron76/MeteorNative/tree/master/RNApp/app)

**Comment by kaminskypavel** [comment]
+1
