### ISSUE TITLE
Licensure

### ISSUE THREAD

**Issue by jhabdas** [aksonov/react-native-router-flux#1199]
@aksonov I noticed you're using a [BSD-2-Clause](https://github.com/aksonov/react-native-router-flux/blob/master/LICENSE). One of requirements of the license is:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

This seems to indicate to me that any software using this router and later placed in the App or Play stores must include your copyright notice in their store descriptions. Would you agree or disagree?

**Comment by atlanteh** [comment]
I'm not one of the owners of this project, nor a lawyer, but you can look in facebook & whatsapp "about" screen, there you can see a link to all the open source projects with their licenses, that they use in the app..(there's practically an endless scrolling there..).
 I think this licenses requires exactly that..

**Comment by jhabdas** [comment]
I was afraid of that. Any chance on switching to MIT?  There are probably hundreds of apps going into the store right now which break your licensing policy.

**Comment by atlanteh** [comment]
MIT requires publishing their license as well :)
What we did was just using a module to crawl all our dependencies, make
sure they are permissive, and copy their license content to one big file..
Obviously it's not enough, as there are modules that are MIT without
license file & copyright notices.. But at least we satisfy 90% of our
dependencies tree..

**Comment by jhabdas** [comment]
MIT is _permissive_ and the copyright notice only needs to go on the source code, not necessarily called out in binary distributions. I give credit where credit is due, but trading about page  Nate binary distribution with BSD licenses  doesn't feel professional to end users.

**Comment by atlanteh** [comment]
Ok, so I guess you're right. But how many people do you think are going to press on a "licenses" link inside your "about" page, just to see a long list of project you're using? Facebook does it, Whatsapp does it. Chrome does it. Nobody cares,  but it's there..
I do however agree with you that this license makes many people break its policy.. However, the oweners have put a lot of work in here and they probably want to be acknowledged, even if it's in a dark place in the app..Of course if they decided to change it to MIT, it could be cool :)

**Comment by jhabdas** [comment]
Not to pick apart language, but where fallacies are concerned:

> Facebook does it, Whatsapp does it. Chrome does it.

Argumentum ad populum

> But how many people do you think are going to press on a "licenses" link inside your "about" page, just to see a long list of project you're using

Denying the antecedent

---

Once enough people are using a library, and if they're breaking licensing requirements any savvy attorney could do the work for them IMO.

**Comment by GantMan** [comment]
agreeing with @jhabdas -  For us to promote this library in source code is one thing.  Having to ship a full license with every app we use it on, is a pain.  Let's get a license change on this.  I think their intention was credit where credit is due.  But not to "Nascar" every app that uses it.

**Comment by GantMan** [comment]
competing libraries are MIT licensed.

**Comment by charpeni** [comment]
You're right and his other libraries are MIT licensed too, so I don't think it will bother him.

cc @aksonov I can do the change (BSD-2 to MIT) if you're agree with that.

**Comment by aksonov** [comment]
@charpeni Ok, please do, MIT is fine.

**Comment by zxcpoiu** [comment]
FYI

If we are going to change license to MIT, isn't it better to use ISC
(functionalities equivalent to MIT) License?

It also a default license on npm init

No matter how, we still can't avoid to use tons of modules distributed in
MIT license though, so I'm fine with MIT.

see:

https://en.m.wikipedia.org/wiki/ISC_license

Why you should not use the MIT license:

http://forum.freegamedev.net/viewtopic.php?f=7&t=4328

**Comment by jhabdas** [comment]
@zxcpoiu MIT is the de facto open source license now. It's short and sweet. Use anything else and it only serves to confuse and discourage use.

**Comment by jhabdas** [comment]
@aksonov @charpeni thanks a million!

**Comment by zxcpoiu** [comment]
yep, I'm fine with both since they are all short and sweet.
thank you for fire this issue

**Comment by charpeni** [comment]
[react-native-router-flux](https://github.com/aksonov/react-native-router-flux) is now under MIT license. :tada:
