### ISSUE TITLE
left or right button text not show

### ISSUE THREAD

**Issue by roysG** [aksonov/react-native-router-flux#1200]
I am using last version.

<Scene key="login"
                   component={Login}
                   title="Login"
                   leftTitle ="left side"
                   hideNavBar={false}
                />

**Comment by roysG** [comment]
<Scene key="login"
                   component={Login}
                   title="Login"
                   leftTitle ="left side"
                   hideNavBar={false}
                />

**Comment by charpeni** [comment]
Please reopen another issue with more information.
