### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by atlanteh** [aksonov/react-native-router-flux#1207]
I can see now rnrf passes all tests.. Any reason why you guys dont bump version & publish to npm?

**Comment by atlanteh** [comment]
??

**Comment by aksonov** [comment]
We have some regression after one commit:
https://github.com/aksonov/react-native-router-flux/issues/1151

**Comment by atlanteh** [comment]
@aksonov Do u guys have any estimations as to when the release will be published?
