### ISSUE TITLE
Best Practices for Navigating to a route

### ISSUE THREAD

**Issue by gkrinc** [aksonov/react-native-router-flux#1209]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.34.0
- react-native v0.34.0-rc.0
### Expected behaviour

Memory usage is constant when navigating between the same 3 scenes
### Actual behaviour

Memory usage continually goes up when navigating between the same 3 scenes

When navigating to a route, what is the best practice for reusing existing scenes? If I do Actions.home() does this reuse the "home" scene if it's already been instantiated?

Instead should I be using Actions.popTo('home')? If so, do I have to check if the scene has been instantiated?

Thanks

**Comment by proProbe** [comment]
Any progress on this?
