### ISSUE TITLE
Drawer is showing

### ISSUE THREAD

**Issue by uc-asa** [aksonov/react-native-router-flux#1213]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.32.0
- react-native v0.29.0

### Steps to reproduce

I'm using drawer with react native router flux but when back then drawer showing I need to fix it how plz suggest how can I fix

**Comment by dragfire** [comment]
What do you mean "when back"?

**Comment by uc-asa** [comment]
Suppose I have created 7 scene and I need to print each component name then how to get value of each and current rendered component name

**Comment by dragfire** [comment]
Try ```this.constructor.displayName```

**Comment by uc-asa** [comment]
Thanks its provide current class name.
