### ISSUE TITLE
Swipe back gesture is slow.

### ISSUE THREAD

**Issue by haabnaseem** [aksonov/react-native-router-flux#1214]
Hi, Did anyone notice that flux routers swipe back action is slow ?. trying with latest version. 
When clicked to back button in navigator is fast, but its hard to trigger swipe back action, any suggestions to improve this ?

**Comment by stratospark** [comment]
I am seeing this with version 3.35.0

It works fine in iOS simulator, but very slow in android simulator (qemu).
