### ISSUE TITLE
How to stay in the same scene when Hot Reloading with redux connected Router?

### ISSUE THREAD

**Issue by DenJohX** [aksonov/react-native-router-flux#1217]
### Version

Tell us which versions you are using: 
- "react-native-router-flux": "^3.35.0",
- "react-native": "^0.32.1",
### Expected behaviour

Using Hot Reloading, every time I edit any reducer or action in my app, the router gets re-rendered.
This is as expected, by my inderstanding, as all the scene components are connected to redux.

Every time some code changes, the router shoud re-render but stay at the current selected scene.
### Actual behaviour

When the router gets re-rendered it doesn't honours the current rendered scene and/or route in the store. It dispatches a focus action for the the intial Scene.
### Steps to reproduce
1. Connect the router to redux, as shown in the instructions
2. Add some reducers
3. Navigate to a non initial scene
4. Change some code on any reducer related file

**Comment by sckoh** [comment]
have you found the answer?

**Comment by crisys11** [comment]
+1

**Comment by GeeWee** [comment]
+1

**Comment by JReinhold** [comment]
+1

**Comment by codebymikey** [comment]
+1
