### ISSUE TITLE
Disable transition

### ISSUE THREAD

**Issue by fgrs** [aksonov/react-native-router-flux#1220]
Is there a way to disable transiotion while changing scene etc Actions.someScene?

I have a scene that contains barcode scanner and transition to/from is a bit jerky

**Comment by haibinyu** [comment]
I think you can just set duration={0} in <Scene />

**Comment by HonzaHK** [comment]
as haibinyu mentioned, you can define that by setting prop `<Scene ... duration={0}>`.
Anyways, when i use this in combination with `react-native-maps` package, something goes wrong. When i am on screen containing `<MapView ...>` and i redirect to another scene which has set `duration={0}`, i see only black screen (theres a tiny area of the scene visible in the bottom left corner). After minimizing and maximizing the app, i can see the scene properly. Anyone facing this issue ?

**Comment by charpeni** [comment]
I'll close this issue since it's seem answered, if not please reopen it and let me know.

**Comment by scerelli** [comment]
it works when you navigate to a certain scene but if it's a generic pop? passing `dutation: 0` doesn't work

**Comment by jpsikorra** [comment]
See #1325
