### ISSUE TITLE
As you press back on one step?

### ISSUE THREAD

**Issue by gHashTag** [aksonov/react-native-router-flux#1222]
### Version
Tell us which versions you are using: 

react-native-router-flux v3.35.0
react-native v0.34.0

### Expected behaviour
Clicking a step back

### Actual behaviour
Pressing the condition is not cheating

### Steps to reproduce
`        {/* Z */}
          <TouchableHighlight style={styles.btn} onPress={Actions.onBACK}>
            <Image
              style={styles.xyz}
              source={Z}
            />
          </TouchableHighlight>`

**Comment by dragfire** [comment]
May be you are looking for ```Actions.pop()```

**Comment by charpeni** [comment]
I'll close this issue since it's seem answered, if not please reopen it and let me know.
