### ISSUE TITLE
Get navigator stack

### ISSUE THREAD

**Issue by uc-asa** [aksonov/react-native-router-flux#1223]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v0.29
### Steps to reproduce

I need to get stack of navigator where state set when navigate and after poped value.

Plz suggest

**Comment by dragfire** [comment]
```javascript
this.props.navigationState
```

**Comment by uc-asa** [comment]
Suppose I open 10 scene and these are stored in the any stack array how can I manipulate that array

**Comment by jaisonveneri** [comment]
Hello @uc-asa,

Can you find a way to access the stack?

Thanks!

**Comment by JeroenNelen** [comment]
It indeed seems impossible to find an overview of the current stack. Only if an item has children, you can find the children in the stack, but it seems impossible to just find an array with all the scene's that are on the stack at the current moment. Which makes it very hard, in a dynamic app, to determine how many items you have to pop etc.
