### ISSUE TITLE
Black screen after Actions.SCENE() with no transition

### ISSUE THREAD

**Issue by HonzaHK** [aksonov/react-native-router-flux#1224]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.32.1
- react-native-maps v0.8.2
### Device

Sony Xperia T / Android 4.4.4 / CyanogenMod M12 (11-20141112)
### Expected behaviour

Scene is being rendered properly
### Actual behaviour

Scene screen is black, only little area in bottom left corner is visible
(check http://mss-clan.wbs.cz/black_screen.png)
### Steps to reproduce
1. Go to scene containing `<MapView ...>` (component from react-native-maps package)
2. Now redirect to a scene without transition (`<Scene ... duration={0} key="anotherScene">`

Strange thing is that even i cant see almost anything, im still able to press underlying buttons, so the screen seems to be loaded but not rendered properly - it is like covered by black area.
After minimizing and maximizing the app, i can see whole target scene properly. 
Anyone facing this issue ?

**EDIT:** 
Just found out this is not happening on another (newer) device.

**Comment by monotv** [comment]
I am encountering the same problem with:
UMI Touch / Android 6
- react-native-router-flux v^3.35.0
- react-native v^0.33.0
- react-native-maps v^0.8.2
