### ISSUE TITLE
Controlled from redux

### ISSUE THREAD

**Issue by knapeto** [aksonov/react-native-router-flux#1226]
Hi,

I need switch scenes via Actions something like that:

```
Actions[key]();
```

Any solutions?
Thanks

**Comment by HonzaHK** [comment]
Hello,
im not sure what do you mean by that. but maybe you are searching for this:
`Actions.refresh({key: 'SCENE_KEY', ... })` 
which is an alternative to 
`Actions.SCENE_KEY()`
