### ISSUE TITLE
Testing in appium

### ISSUE THREAD

**Issue by ptah23** [aksonov/react-native-router-flux#1229]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.33.0
When I load the app in Appium inspector, I can't see an id or name I can use for automation of the tabs. Is there an attribute I can set on the corresponding Scene tag?

<img width="243" alt="screen shot 2016-09-28 at 21 30 54" src="https://cloud.githubusercontent.com/assets/2241188/18931167/ee7e847e-85c2-11e6-99c0-66612fd217f0.png">

**Comment by ptah23** [comment]
Nevermind, i got it working with accessiblityLabel

**Comment by mmzoo** [comment]
As far as I can tell there is no accessibility label on the left and right buttons in the navigation bar. How did you manage to click on those?
