### ISSUE TITLE
Issue when passing data to tab scene

### ISSUE THREAD

**Issue by moaxaca** [aksonov/react-native-router-flux#1230]
### Version
Tell us which versions you are using: 

- react-native-router-flux 3.35.0
- react-native 0.33.0

### Expected behaviour

Scene config 
```
<Scene key="modal" component={Modal} >
    <Scene key="root" tabs={true}>
      <Scene key="pageOne" component={PageOne}/>
      <Scene key="PageTwo" component={Drawer} open={false}>
        <Scene key="main" tabs={true}>
          <Scene key="home" component={Home}>
        </Scene>
      </Scene>
    </Scene>
  </Scene>
```

PageOne.js (onPress handler)
```
Actions.drawer({ session: 'some value' })
```

PageTwo.js (in render)
```
console.log(this.props.session) // null
```
### Actual behaviour
Returns null 

I can provide more code if needed.

**Comment by moaxaca** [comment]
Unsure if this is the ideal way to do this but:
```
Actions.drawer({ session: Session })
Actions.refresh({ key: 'drawer', session: Session })
```
Works. Do certain Actions not allow the passing of props or is something more complex happening under the hood?

**Comment by dragfire** [comment]
If you are usng Drawer then I think you can check it in ```javascript this.navigationState.children```

**Comment by alexicum** [comment]
Version 3.35.0 does not support passing props to tab routes.
#1057 and #1236 appends this functionality, but before official release you could test it by installing RNRF with:
npm install --save-dev https://github.com/aksonov/react-native-router-flux.git

**Comment by moaxaca** [comment]
Saved me a headache!
