### ISSUE TITLE
POP_TO not working in android

### ISSUE THREAD

**Issue by uc-asa** [aksonov/react-native-router-flux#1235]
### Version

Tell us which versions you are using: 

-react-native-router-flux v3.32.0
-react-native v0.29
### Steps to reproduce

Hello Team I'm using react native router flux but problem is that POP_TO is not working on android but its work on IOs what can I do.

Code --

<Router createReducer={reducerCreate}  hideNavBar={true}>
    <Route key="signin" component={Signin} initial={true}/>
        <Route key="profile" component={WelcomeUser} title="User" />
        <Route key="home" component={Home} title="My Home" />  
 </Router>
const reducerCreate = params => {
  const defaultReducer = new Reducer(params);
  return (state, action) => {
    if(action.type == 'REACT_NATIVE_ROUTER_FLUX_BACK_ACTION') {
            Actions.home({type: ActionConst.POP_TO, targetIndex:1});
            //return defaultReducer(state, action);
    }
    return defaultReducer(state, action);
  };
};
 // Home is sceneKey

**Comment by ddeanto** [comment]
I am having the same issue
