### ISSUE TITLE
Don't add scene to navigation stack

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#1238]
I'm sorry if this was asked already, but I read the docs 10 times already and searched the issues and I can't figure out the following.

Are we able to somehow exclude a scene from the navigation stack. 

I have the following situation. 
list view -> add button -> form -> on save -> go to single view

Now that works. The problem is that on the single view I have a back button. If I click the back button now I go back to the form, but I want the user to go back to the list view instead. If he wants to edit the entry, he has an edit button in the navbar. 

Am I able to delete the form from the navigation stack? I tried telling the single view to go directly to the list View, by specifying the name of the list view. 

```
static onBack() {
  Actions.listview();
}

```
but the issue here is that when you land on the list view -> the back button now points to the single view. And you end up in an endless loop. 

Any ideas how to properly do that?

**Comment by mahlon-gumbs** [comment]
@compojoom  How are your scenes defined? I think your "single view" scene should be displayed via `ActionConst.REPLACE` so that it replaces the form. At that point, the back button would take the user back to list view.

Hope that helps.

**Comment by compojoom** [comment]
Thanks for the reply. This is how I do it:
```
import React, {Component} from 'react';
import {
	View,
	Navigator,
	StyleSheet,
Text
} from 'react-native';

import Fields from '../components/Fields/Fields';
import Field  from '../components/Field/Field';
import CreateField  from '../components/Field/CreateField';
import Company from '../components/Company/Company';
import FormCrop from '../components/Crop/FormCrop';
import FormCompany from '../components/Company/FormCompany';
import Companies from '../components/Companies/Companies';
import WaitTime from '../components/WaitTime/WaitTime';

import {Actions, Scene, Router, ActionConst} from 'react-native-router-flux';

const styles = StyleSheet.create({
	navigationBarStyle : {
		backgroundColor: '#81c04d'
	},
	titleStyle: {
		color: '#ffffff',
		fontSize: 20
	},
	rightButtonTextStyle: {
		color: '#D2F1AC'

	}
});
export default class FarmerJoeApp extends Component {
	render() {

		return (
			<Router>
				<Scene key="root">
					<Scene key="companies"
						   {...styles} type={ActionConst.BACK} backButton={false} onRight={() => Actions.formCompany()} rightTitle="Neu" component={Companies}  title="Betriebe"  />
					<Scene key="company" {...styles} component={Company}  title=""  />
					<Scene key="formCompany" {...styles} component={FormCompany} />

					<Scene key="fields" {...styles} component={Fields} title="Fields" />
					<Scene key="field" {...styles} component={Field} title="Field" />
					<Scene key="createField" type={ActionConst.REPLACE} {...styles} component={CreateField} title="Create field" />

					<Scene key="waitTime" {...styles} onRight={() => Actions.formCompany()} rightTitle="speichern" component={WaitTime} title="WaitTime" />
					<Scene key="formCrop" {...styles} onRight={() => Actions.formCompany()} rightTitle="speichern" component={FormCrop} title="Kultur hinzufügen" />
				</Scene>
			</Router>
		)
	}
}
```

As you can see with the createField scene I tried it with type={ActionConst.REPLACE}, but this still doesn't work. If I do it with replace then this is what happens.

The navigation in my app works like this.

Companies -> company -> fields -> createField -> on save -> field. 

Now with replace on the field scene the back button works like this:
field -> createField -> company -> companies

If I don't use replace, then the back button works like this
field -> createField -> fields -> company -> companies. 

And all I want to do is this:
field -> fields -> company -> companies

Are my scenes ordered wrong?

**Comment by mahlon-gumbs** [comment]
Hmmm...try one of the following:

- use `type={ActionConst.REPLACE}` on both `createField` and `field`. **Drawback:** _You won't be able to jump back and forth between these two scenes by default._
- OR try using `Actions.popTo("fields")` from within the `field` component. **Drawback:** _It's not in the overall configuration so the default behavior (from a back swipe gesture for example) would still navigate back scene by scene._

I believe either of those will get you what you want.

Hope that helps.

**Comment by mahlon-gumbs** [comment]
Hi @compojoom. Sorry. I think I misunderstood the sequence you are trying to achieve. If you want to go forward

`companies -> company -> fields -> createField -> field`
and then backward
`field -> fields -> company -> companies`

**Then `field` is the only one that needs `type={ActionConst.REPLACE}`.**

This should cause `field` to replace `createField` in the stack. In other words, when you navigate to `field`, your stack should look as follows:

`companies -> company -> fields -> field` (`createField` has been replaced).

You won't need `Actions.popTo(...)` with this approach.

I hope this is less confusing (since I misread your back sequence in the previous message).

**Comment by compojoom** [comment]
I see, now I finally understand what's going on and that won't work in my case. 

The issues is this. I have 2 ways to go to field.
1. fields -> field
2. fields -> createField -> field

If I use replace, then it will work for the second case. But in the first case I'll jump back to company instead of fields as fields has been replaced by field.

Is there any way for my to dynamically determine if I want to have type replace or the default push?


Aaaaah, wait! I have it. So, in my createField scene when I save I can do `Actions.field({type: 'replace'});` Now when save sends me to the field scene the back button sends me back to fields. Awesome! Thanks man! I would not have come to this without your help! Thank you!

**Comment by mahlon-gumbs** [comment]
Awesome! Glad you got it worked out.

**Comment by JeroenNelen** [comment]
@compojoom @mahlon-gumbs I have a similar issue, with just a small variation, maybe any of you can point me in the right direction.
1. sceneA -> sceneB -> sceneC ->... sceneN -> sceneA    --> in this case REFRESH works to show me sceneA but, if I then use the back button it will pop sceneA and I'm back on sceneN, if I then try to proceed again to sceneA, it will try the refresh but sceneA is no longer in the stack, so it won't do anything... so somehow I would have to know, when arriving on sceneN if sceneA is already in the stack (use REFRESH) or not yet in the stack (use PUSH).... another possibility might be that when at sceneN, I pop all the way back to sceneA, the problem however is that the amount of items on the stack will not always be the same and I can't seem to figure out how I can know how many stack items are between sceneA and sceneN...

Anyone any clue?

Thanks,

**Comment by compojoom** [comment]
I couldn't understand what you want to happen from SceneN to SceneA. When you are at sceneA hitting the back button should send you where?

**Comment by JeroenNelen** [comment]
hey @compojoom thank you for your reaction,
in sceneN I select something that will be shown on sceneA
sceneB --> sceneC --> scene... are some kind of browsing screens: you browse through folders until you see items on sceneN, select an item and it will be shown on sceneA, so I have two situations
1) from the dashboardScene --> sceneA, so if we go back at that moment, we want to land on the dashboardScene
2) from the dashboardScene --> sceneA --> start browsing so several scenes are pushed onto the stack --> at sceneN the user selects a new item and that item should be visible on sceneA, so preferably at that moment, we would pop all the way back to sceneA, but since the amount of screens between sceneA and sceneN is not always the same, I would somehow have to be able to calculate or now the amount of screens to pop (assuming that multi-pop works as expected) ?

**Comment by compojoom** [comment]
I asked what should happen when you hit the back button? Should you go back to SceneN, or should you stay at sceneA.

If you stay at scene A, then at sceneN you could send the user to SceneA by using the reset option. This will clear the stack and you'll be at sceneA. Then the user could initiate a new navigation.

**Comment by JeroenNelen** [comment]
hitting the back button at sceneA should send you to the dashboard, so RESET is not an options as it will clear entire stack and you can not go back from sceneA to dashboard anymore, there should be a function like 'pop until sceneA', but as far as I know there is none.

**Comment by compojoom** [comment]
How about overriding the back action on SceneA to always send the user to the dashboard? Then reseting to SceneA shouldt still be able to send you to the dashboard :)
