### ISSUE TITLE
Hiding navbar with route type = switch

### ISSUE THREAD

**Issue by tristangodfrey** [aksonov/react-native-router-flux#124]
Is it intended that the navbar cannot be hidden on switch type routes? My group of routes wrapped inside a router with the prop `showNavigationBar={false}` will not display a navigation bar if route `type="replace"`, but a navigation bar pops up when I set it to `"type="switch"`.

**Comment by aksonov** [comment]
could you try hideNavBar ?

**Comment by maxs15** [comment]
Same for me ``hideNavBar`` doesn't work

**Comment by navels** [comment]
Diito

**Comment by Everhusk** [comment]
+1

**Comment by aksonov** [comment]
Check Example, second tab has hidden nav bar.
