### ISSUE TITLE
Can we have a fade animation similar to that on the Navigation component?

### ISSUE THREAD

**Issue by Mohamed-Abo-El-Soud** [aksonov/react-native-router-flux#1241]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0
### Expected behaviour

when using the typical navigation component. It allows you to have multiple options for transitions. One of them is the `Navigator.SceneConfigs.FadeAndroid` transition which looks good. I expected the fade animation on the `react-native-router-flux` to behave the same.
### Actual behaviour

The animation on the RNRF casts a white box border around the screen that looks funky and detracts from the content of the page. It doesn't look as polished as the `Navigator.SceneConfigs.FadeAndroid` one.
### Steps to reproduce
1. Create two scenes with the `animation={'fade'}` property on both of them
2. try to transition between the two scenes (use a button or something). you should see the apparent white border during the transition between the two pages. (I tested this on an iPhone simulator and on my personal Nexus 5 phone)
   3.

**Comment by woody87** [comment]
Hi Mohamed,

same problem for me, solved in this way (I think was a shadow lag):

const getSceneStyle = ( props, computedProps) => {
      const style = {
          flex: 1,
          backgroundColor: '#000000',
          shadowColor: null,
          shadowOffset: null,
          shadowOpacity: null,
          shadowRadius: null,
      };
      return style;
};
<Router scenes={scenes} getSceneStyle={getSceneStyle}  .......


Hope this works also for you!!!

Woody

**Comment by aditiasap** [comment]
Hi @woody87 
That code didn't work for me. seems scenes function is undefined on me. Hope you please show how scenes function looks like.
And why we need passing (props, computedProps) for getSceneStyle ?

Thanks.
