### ISSUE TITLE
Modal in the tab bar bug

### ISSUE THREAD

**Issue by charlesluo2014** [aksonov/react-native-router-flux#1243]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34.1
### Expected behaviour

 display the modal page
### Actual behaviour

 display half modal page and half tab page
### Steps to reproduce
1. go to tabbar page
2. use the Modal root scene
3. in the tabbar page invoke the Modal page action

**Comment by YuriyUlantsev** [comment]
@charlesluo2014 Please show the code of your router.

**Comment by laeijebor** [comment]
Hi @charlesluo2014 - just stumbled on this. I don't have a fix but have just used a workaround, which was to give my modal absolute position attached to the bottom of the screen.

For example, a modal component and associated styles could look like the below. (NOTICE THE ABSOLUTE POSITIONING IN THE STYLESHEET):

```jsx
const MyModal = (props) => (
  <TouchableOpacity onPress={() => { Actions.pop(); }}>  
    <View style={styles.modalStyle}>
      <Text>modal</Text>
    </View>
  </TouchableOpacity>
);

const styles = StyleSheet.create({
  modalStyle: { 
    position: "absolute",  // LOOK HERE
    bottom: 0, // LOOK HERE
    left: 0, // LOOK HERE
    height: deviceHeight,
    width: deviceWidth,
    backgroundColor: "rgba(0,0,255,0.2)",
  }
})
```



```jsx
<Router>
  <Scene key="modal" component={Modal}>
    <Scene
      key="main"
      tabs
      hideNavBar
      component={MyMainView}
    >
      <Scene key="page1" component={Page1}  title="Page 1" icon={TabIcon} />
      <Scene key="page2" component={Page2} title="Page 2" icon={TabIcon} />
    </Scene>
    <Scene
       key="myModalView"
       component={MyModal}
    />
    .....
  </Scene>
</Router>
```

Not very familiar with the source code for react-native-router-flux, but at first glance I think the issue might have something to do with the special treatment of TabBar Components in the supplied DefaultRenderer.
