### ISSUE TITLE
Question: Using clone={true}

### ISSUE THREAD

**Issue by fostertime** [aksonov/react-native-router-flux#1245]
Is it possible to RESET the router stack, when using a cloned scene? 

I am cloning a scene for a continuous loop of scenes. But when I set the ActionConst to RESET, the cloned scene never transitions to the next scene. I have tried using REPLACE, and POP_AND_REPLACE but the router stack continues to grow larger and larger with those two. 

Any ideas?

**Comment by alizbazar** [comment]
How and in which use cases `clone={true}` should be used? I can't find any examples of this in the documentation. [API CONFIGURATION](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md) page says "see example", but doesn't refer to anything.

**Comment by fostertime** [comment]
@alizbazar You can see in the Examples, EchoView.js (https://github.com/aksonov/react-native-router-flux/blob/master/Example/components/EchoView.js) that is set as `clone` in Example.js (https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js). In the most simplistic terms, a cloned Scene accepts props and is simply cloned each time it is referenced via `Actions.sceneName()` ...

**Comment by fostertime** [comment]
Actually, I forgot to close this ticket. Because the solution was that the Scene that is being cloned needed to be separate from itself. Meaning, don't `clone->clone->clone->clone` ... instead, do `parentScene->clone->parentScene->clone->parentScene->clone` that way the router stack RESETs when setting `type: ActionConst.RESET` when returning to parentScene, which then clones its child. That sounded a lot more clear in my head... :) Let me know if thats confusing!

**Comment by fostertime** [comment]
I think router-flux makes it extremely easy to do what you want to do. Hit me up  if you run into any issues and I'll do my best to help! Going to close this ticket for now.
