### ISSUE TITLE
how to reset nav history when changing tabs?

### ISSUE THREAD

**Issue by sudugo** [aksonov/react-native-router-flux#1246]
This a question!
Tell us which versions you are using: 
- react-native-router-flux v3.?.?
  "react-native-router-flux": "^3.34.0",
- react-native v0.?.?
  "react-native": "0.31.0",

my scene structure is as follows:

Home screen 3 tabs(a,b,c)

a>a1>a2>a3>a4>a5
b>b1>b2>b3>b4>b5
c>c1>c2>c3>c4>c5

each tab has about 5 navigatable scenes within them

if i go to a4 then press b tab and then press a tab again it goes to a4 not a1
how to achieve this.

any help is appreciated.

**Comment by damir-sirola** [comment]
I did this by implementing scene icon component with TouchableWithoutFeedback wrapper.
On press I just did

`Actions.myScreen({ type: 'reset' });`
`setTimeout(() => Actions.refresh({ key: 'myScreen', refresh: false, notification: null }), 10);`

This is kinda hacky with setTimeout, but for some reason it didn't work without it (implemented few versions back).

**Comment by joeferraro** [comment]
@sudugo I'm seeing the opposite behavior. My app is set up with 4 tabs:

a > a1
b > b1
c > c1
d > d1 > d2

If I navigate to `c1`, then tap on `d` tab, then tap the `c` tab again, `c1` pops automatically back to `c`. I'd actually prefer it not pop back to the first scene on `c`. 

@aksonov is this configurable?
