### ISSUE TITLE
Is it possible to hide a particular tab in TabBar from inside a scene?

### ISSUE THREAD

**Issue by dragfire** [aksonov/react-native-router-flux#1247]
I have 5 ```Tabs``` in ```TabBar``` and I would like to manipulate them from inside a ```Scene```.
Is it possible to manipulate them using ```Actions.refresh```?

**Comment by ArtemX9** [comment]
@dragfire You have to write your own action and dispatch it. You also need to add action handling in you custom reducer.

**Comment by dragfire** [comment]
Do I have to use redux/flux for this? https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md#reduxflux

**Comment by ArtemX9** [comment]
You can import Reducer from react-native-router-flux, and implement it like this:
`const reducerCreate = params => {
  const defaultReducer = new Reducer(params);
  return (state, action) => {
    switch (action.type) {
      case '*YOUR_ACTION_NAME*':
        ....manipulations with the state here....
        return state;
      default:
        return defaultReducer(state, action);
    }
  };
};`

and then call it this way: `ACTIONS.*YOUR_SCENE_NAME*({ type: '*YOUR_ACTION_NAME*' });`

**Comment by dragfire** [comment]
Thank you @ArtemX9

**Comment by dragfire** [comment]
@ArtemX9 I've implemented the reducer as you suggested. Everything is working as I want but there is a ```warning: Component's children should not be mutated``` being throw in the console.

Here's my custom reducer:
```javascript

const reducerCreate = params => {
    const defaultReducer = new Reducer(params);
    return (state, action) => {

        switch (action.type) {
            case CustomActions.REMOVE_TWO_TABS:

                let childrens = state.children;
                childrens[1].children.splice(1, 2);
                console.log('CHILDRENS:', childrens);
                return Object.assign({}, state, childrens);
            default:
                return defaultReducer(state, action);
        }
    };
};
```  
Is it a false-positive or am I doing something wrong?

**Comment by ArtemX9** [comment]
@dragfire try to clone `state.children' before splicing, because `splice` mutates the original array. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by dragfire** [comment]
Ok thanks!

**Comment by hoangdoan267** [comment]
@dragfire I always have an error at ` const defaultReducer = new Reducer(params);`
it said `undefined is not an object (evaluating ' _ref3.initialState)` ?
