### ISSUE TITLE
navbar hide when action.name to other page with navbar

### ISSUE THREAD

**Issue by Talkwondo** [aksonov/react-native-router-flux#1248]
### Version
- react-native-router-flux v3.30.6
- react-native v0.31.0
### Expected behaviour

login page: hide navbar
welcomescreen: with navbar

After login the user goes to screen with navbar:
  componentDidMount() {
    firebase.auth().onAuthStateChanged(function(user) {
      if (user) {
        Actions.WelcomeScreen();
      } 
    });
  }
### Actual behaviour

the page is up without navbar

**Comment by Amurmurmur** [comment]
you can either pass hideNavBar to the Scene in the root component where you define all Scenes.
Like so:
```
<Scene key="Login" initial hideNavBar component={LoginPage} title="Login" />
 <Scene key="WelcomeScreen" component={WelcomeContainer} title="Welcome" />
```

Or you can hide the navbar on componentDidMount() in your welcomescreen container like so:
```
import {Actions} from 'react-native-router-flux'
componentDidMount(){
Actions.refresh({ hideNavBar: true })
}
```

Hope this helps :)
