### ISSUE TITLE
panHandlers = { null } raises warning

### ISSUE THREAD

**Issue by acruis** [aksonov/react-native-router-flux#1249]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34.0
### Expected behaviour

Passing `{ null }` into `panHandlers` silently disables swipe-to-go-back.
### Actual behaviour

Passing `{ null }` into `panHandlers` does disable swipe-to-go-back, but there is a warning message:
`Warning: Failed prop type: Required prop panHandlers.onMoveShouldSetResponder was not specified in NavigationCard`.

Not sure if there's a method to deal with this warning, but it doesn't seem to be causing any problems related to business logic.

**Comment by ninjz** [comment]
For me swipe-to-go-back is not working now with null passed to panHandlers

**Comment by acruis** [comment]
Does that mean you can still swipe-to-go-back after passing null to panHandlers?

**Comment by ninjz** [comment]
Yea, and just realized it is occuring on Android as well. this is for v3.35.0, i reverted back to 3.30 and the problem does not occur
