### ISSUE TITLE
Scene transition not animated for type='replace' and type='switch' even when SceneConfig is supplied

### ISSUE THREAD

**Issue by raynehk14** [aksonov/react-native-router-flux#125]
I searched and found this: https://github.com/aksonov/react-native-router-flux/issues/67
but it doesn't work on 2.0.9

**Comment by iheart2code** [comment]
Doesn't work for me either. Using the following:

```
<Router hideNavBar={false}>
  <Schema name="flip" sceneConfig={Navigator.SceneConfigs.ToTheBack} type="replace" />

  <Route name="screen1" component={screen1} initial={true} hideNavBar={true} />
  <Route name="screen2" component={screen2} title="Screen 2" schema="flip" />
</Router>
```

**Comment by aksonov** [comment]
Please check RN Navigator with replace. Looks like it doesn't support animation? This component just reuses standard RN Navigator and passes scene configs to it.

**Comment by iheart2code** [comment]
Looks like there's a thread for this issue already: https://github.com/facebook/react-native/issues/1981

**Comment by aksonov** [comment]
Unfortunately that fix doesn't work for next pop() actions. So will wait until React Native guys fix it.

**Comment by shukerullah** [comment]
any news related to this issue?
