### ISSUE TITLE
Scene with react-native-maps breaks on router-flux 3.36.0

### ISSUE THREAD

**Issue by carleryd** [aksonov/react-native-router-flux#1258]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.34.0
### Expected behaviour

Moving between scenes from tabbar does not break react-native-maps inside of Scene
### Actual behaviour

Moving from Scene with react-native-maps to another Scene via tabbar and then back again makes map not move when dragging on it, however it seems to send the drag event to the map.
### Steps to reproduce

This behavior was introduced in 3.36.0, going back to 3.35.0 fixed it.

I bet it has something to do with render optimizations but I'm really not sure, just thought I'd mention the breaking change.

**Comment by stanleycyang** [comment]
I also noticed the breaking change, and it breaks my left and right button renders. I've managed to fix it for now by locking my version to 3.35.0, but it'd be great not to have to do that
