### ISSUE TITLE
With the master version,there can be double headers

### ISSUE THREAD

**Issue by Daniel-ccx** [aksonov/react-native-router-flux#126]
In ExRouter.js

        ##57: const Header = this.route.header;
        ##58: const header = Header ? <Header {...this.route.props} {...this.props}/> : null;

        ##60: const Footer = this.route.footer;
        ##61: const footer = Footer ? <Footer {...this.route.props} {...this.props}/> : null;

        
this.name can be a 'name' or '_name', so we will get double headers.

I will test the footer.

But thanks for ur nice work

**Comment by aksonov** [comment]
Could you submit PR or atleast code example with double headers? Thanks
