### ISSUE TITLE
AutoUpdate router data via server?

### ISSUE THREAD

**Issue by machei** [aksonov/react-native-router-flux#1260]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.?.?
- react-native v0.?.?
### Expected behaviour

Router should be working with actual data which is always synchronizing with server.
### Actual behaviour and Steps to reproduce
1. Old data with categories is loaded at first time.
2. Every 1 minute router is updating via server.
3. I pressed new category from menu and I get warning message: [react-native-router-flux] missed route data for key=cat35list

How to force reload router data?

**Comment by AndrewHenderson** [comment]
@machei I just hit this issue. Did you make any progress on it?

**Comment by AndrewHenderson** [comment]
@machei Nevermind. I figured out it was a change I made to the custom NavBar I created.

**Comment by machei** [comment]
@AndrewHenderson I still have this issue, and it isnt closed.

**Comment by machei** [comment]
@aksonov please reopen.

need solution for it.
