### ISSUE TITLE
How to disable the navBar animation, especially when from one page with navBar to one page without navBar.

### ISSUE THREAD

**Issue by feyy** [aksonov/react-native-router-flux#1263]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.34.1
### Expected behaviour

When transit from page A(with navBar) to page B(without navBar), only page B float in from right to cover the page A.
### Actual behaviour

Page A and B all have an animation in the navBar. Especially when A(with navBar) to page B(without navBar), the navBar in page A will disappear and left a white block.

I don't want the additional navBar animation, can I disable it?

**Comment by wangzhuwei212003** [comment]
`<RouterWithRedux key="root" animationStyle={animationStyle} duration={0}>`
Setting duration to 0 may be not the best way, but works for me .
If you need more animation , look for this:[https://github.com/aksonov/react-native-router-flux/issues/1202](url) .

**Comment by wangzhuwei212003** [comment]
Setting duration to 0 may be not the best way, but it works.

`<RouterWithRedux key="root" animationStyle={animationStyle} duration={0}>`

And if you need more animation, thanks for the sharing from redbaron76, check this out:
> https://github.com/aksonov/react-native-router-flux/issues/1202

**Comment by MrMatten** [comment]
I tried with duration set to zero, and it removes the transition animation, but the status-bar stops changing from light-content to dark-content. Is there any way to do so that still works?
