### ISSUE TITLE
Displaying compressed sized navigation bar

### ISSUE THREAD

**Issue by tbriscoe** [aksonov/react-native-router-flux#1265]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.33.0
### Expected behaviour

Navigation bar width should fit the size of the screen
### Actual behaviour

Navigation bar width and height are greatly reduced in size, with any containing elements push together.
### Steps to reproduce
1.  Just run react-native-router-flux v3.36.0
   2.
   3.

**Comment by lovato** [comment]
Run into same problem. I upgraded several packages, including RN.
When downgraded to 3.35, navbar become normal again.
