### ISSUE TITLE
Can't test with tape due to unbuilt version

### ISSUE THREAD

**Issue by Rewieer** [aksonov/react-native-router-flux#1269]
I'm working with ReactNative 0.34.1 and ReactNativeRouterFlux 3.35.0. When I Try to launch my test using my own RouterReducer, I get an "unexpected reserved word import". 

This is because the entry point of RNRF isn't transpiled to ES5, and no dist/build folder is shipped with the npm package. As I didn't find any "build" script in package.json I believe this is intended ?

**Comment by Rewieer** [comment]
Any solution for this please ?

**Comment by sibelius** [comment]
`jest` can handle both es6 and es5

I can this question is more suitable for stackoverflow

**Comment by Rewieer** [comment]
Well hopefully i went to jest after that.
Does it mean you have no idea how to solve this, or is ths really intended to be posted on SO ?
If you have the answer I could put it on SO and answer it.
