### ISSUE TITLE
[FR] Allow to explicitly specify backButtonText in Route

### ISSUE THREAD

**Issue by herby** [aksonov/react-native-router-flux#127]
Title says it, instead of existing hardcoded logic of "prevRoute.title unless length > 10" allow to specifiy back button text also explictly if wished.

**Comment by joshuarotenberg** [comment]
:+1:

**Comment by CoericK** [comment]
Any new here?

**Comment by aksonov** [comment]
You could use 'leftTitle' property, what is the problem?

**Comment by herby** [comment]
It does not work unless you specify `onLeft`.

**Comment by aksonov** [comment]
Please check 2.1.3 version

**Comment by herby** [comment]
Cannot check now, still using ver.1 and ver.2 breaks all the navbar styling... will take a while to check if this works.

**Comment by herby** [comment]
Works.

**Comment by CoericK** [comment]
What should we use then? Can we add the functionality on the documentation? What should we use to custom the backButton or de nextButton?

**Comment by herby** [comment]
leftTitle

Erick Arroyo wrote:

**Comment by CoericK** [comment]
the other one should be rightTitle?
