### ISSUE TITLE
The initial tab with scrollable views witch  can not be scrolled when tap between tabs and back to the initial tab

### ISSUE THREAD

**Issue by ksti** [aksonov/react-native-router-flux#1270]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0 
- react-native v0.32.0

I'd update to the latest version 3.36.0, but there comes a problem below. 

We have three tabs. The first one has a view pager witch used [react-native-viewpager](https://github.com/race604/react-native-viewpager) and a ListView witch from react-native.
The view pager is scrollable with horizontal direction while the ListView is scrollable with vertical direction.

The first tab is the initial tab in witch viwpager and ListView can both be scrolled, it works normal.  
But when you tap between tabs and back to the first one, both can be taped but not scrolled. The second tab has a view pager too without ListView, and it can be scrolled.
And I tried that let the second or the third tab be same as the first (initial) one then the other tabs is ok but only not the first (initial) tab. The tabs are all with same views though the initial one cannot be scolled. It seems that the views have not been updated as the content sure has been scrolled but not moved and you would tap the different content. Wish you can resolve this issue.Thanks.

 It's weird because that on react-native-router-flux v3.35.0 it works fine.

### Steps to reproduce
We have three tabs. The first one has a view pager witch used [react-native-viewpager](https://github.com/race604/react-native-viewpager) and a ListView witch from react-native
1.tap between tabs
2.back to the first one
3.neither Viewpager or ListView can be scrolled but can be taped.

**Comment by wrozka** [comment]
I have the same issue, everything worked fine in v3.35.0.

**Comment by aksonov** [comment]
@alexicum Could you please check?

**Comment by Kaishley** [comment]
I have the same issue.

**Comment by proProbe** [comment]
same here

**Comment by alexicum** [comment]
@ksti please test with Viewpager only.
I did next test:
same Viewpager [component](https://github.com/race604/react-native-viewpager/blob/master/Sample/TopScreen.js) on all tabs
and Viewpager is scrolling on all tabs

So may be it is not scrolling only when both Viewpager and ListView are there...

**Comment by ksti** [comment]
@alexicum I did the test but still has the issue, in the initial tab Viewpager can auto scroll but you can not scroll it manually.

**Comment by alexicum** [comment]
@ksti Could you please share your sample?

**Comment by ippy04** [comment]
Am seeing this also with 2 tabs, each with a ListView...

**Comment by brycepavey** [comment]
Also getting this with my first tab with 3.36.0. The view seems to be frozen but I can still see the scroll events in the debugger, just nothing changes on screen

**Comment by huliyou** [comment]
<Scene type={ActionConst.REFRESH}>

fix my issue

**Comment by wrozka** [comment]
@ktsi @aksonov  I've fixed this issue by restoring JUMP handler from `0.35` https://github.com/wrozka/react-native-router-flux/commit/e944fbf39197e2f56ff8dbf86eff6a6f83ae29b7 . Somehow the key of a tabbed scene is different when you navigate to it (PUSH `parent_position_name`) than when you just switch a tab (JUMP `name_position_name`). However this commit breaks passing props to tabs.

**Comment by aksonov** [comment]
@wrozka Great, please submit PR.

**Comment by wrozka** [comment]
@aksonov Sure, but my commit breaks couple of unit tests for passing props to tabs and I don't have time to fix them, does it work for you?

**Comment by masterkrang** [comment]
@wrozka @aksonov confirm this fixes frozen ScrollView for me

`"react-native-router-flux": "github:wrozka/react-native-router-flux#e944fbf39197e2f56ff8dbf86eff6a6f83ae29b7",` 

🎉

**Comment by aksonov** [comment]
@wrozka It is ok, could you comment those tests and introduce some new test for this ticket? This way when guys will fix passing props we could make sure that this functionality is not broken again.

**Comment by alexicum** [comment]
Restoring 0.35 would return #1151 problem:
>When a tab is clicked, the new scene is shown, but now only the selected tab is shown in the tab bar

**Comment by alexicum** [comment]
I can't reproduce problem.
Here is my test.
TestForm contains  `<ListViewForm />`:

After tap between tabs ListView is scrolling:

```
// TestForm.js
const reducerCreate = params => {
  const defaultReducer = new Reducer(params);
  return (state, action) => {
    console.log('ACTION:', action);
    const res = defaultReducer(state, action);
    return res;
  };
};

class MySample extends Component {
  render() {
    return (
      <Router createReducer={reducerCreate}>
        <Scene key="root">
          <Scene key="FirstScreen" component={TestForm} title="FirstScreen" />
          <Scene key="SecondScreen" component={TestForm} title="SecondScreen" />
          <Scene key="main" tabs>
            <Scene key="tab1" component={TestForm} title="Tab #1" icon={TabIcon} />
            <Scene key="tab2" component={TestForm} title="Tab #2" icon={TabIcon} />
            <Scene key="tab3" component={TestForm} title="Tab #3" icon={TabIcon} />
          </Scene>
        </Scene>
      </Router>
    );
  }
}

// ListViewForm.js
export default class ListViewForm extends Component {
  constructor() {
    super();
    const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
    const dataRows = Array.apply(null, { length: 30 }).map(Number.call, Number);
    this.state = { dataSource: ds.cloneWithRows(dataRows) };
  }
  render() {
    return (
      <ListView dataSource={this.state.dataSource} renderRow={rowData => <Text>{rowData}</Text>} />
    );
  }
}
```

**Comment by aksonov** [comment]
@alexicum I agree, we need to find fix that fixes all these issues. @wrozka Could you check #1151 with your code?
