### ISSUE TITLE
Search field inside navigation?

### ISSUE THREAD

**Issue by liesislukas** [aksonov/react-native-router-flux#1273]
Best behaviour would be: 
1. click on right icon, which is search button
2. search field expands and focuses 

all in navigation bar

![image](https://cloud.githubusercontent.com/assets/2733862/19304081/fb8019f6-9073-11e6-80a9-72d8e60c0f43.png)

I'm planning to make my own navigation component for search view to handle this, but i think many applications would benefit from some simple search handler

**Comment by YuriyUlantsev** [comment]
@liesislukas This specific functionality can be implemented using RenderTitle func.

**Comment by liesislukas** [comment]
ok, thanks will play with it

**Comment by infacq** [comment]
do you build your own component?

**Comment by liesislukas** [comment]
haven't done it yet, but will definitely build something, i have to deliver an app. I'm thinking to build same thing in a different way, if nothing works out. Just search input under navigation bar or maybe in another view, like gmail done it.  Haven't decided yet.

If i would maintain such lib, i would think to build some default way for search input, but it's out of my field right now, i wonder if will have enough time to build something for a pull

**Comment by plraphael** [comment]
@liesislukas could you be more specific? I did not understand what you did...if you could provide some example code would be great.

Thanks,

Pedro.

**Comment by liesislukas** [comment]
it just navigates to another view where is no navigation at all and instead of it search field with X icon next to input field, on click X it navigates back. Check out gmail for android, can't check ios version now. It has basically same thing for search

**Comment by marcelmfa** [comment]
@liesislukas could you share your code, please?

**Comment by liesislukas** [comment]
@marcelmfa sorry but this issue is way too old. That code would be out of date anyway. Almost full year passed, many updates pushed to react native and router during that time.

**Comment by marcelmfa** [comment]
The docs probably are outdated. I tried that solution, but didn't work. I found a solution in stackoverflow, if I remember well. Below have my code that works in this last version:
`<Scene key="drawer" drawer contentComponent={SideBar} hideNavBar>
  <Scene key="main">
    <Scene key="showInbox" component={Main} title="System's name" initial/>
  </Scene>
</Scene>`

**Comment by munkhorgil** [comment]
I made this way, unfortunately it can't work as expected. Everytime I write on Text Input it clears automatically.

```javascript
renderTitle = () => {
    return (
      <View style={styles.searchContainer}>
        {
          this.state.toggleSearch
          ? <TextInput
              style={styles.inputStyle}
              placeholder="Search"
              value={this.state.searchValue}
              onChangeText={searchValue => this.onSearch(searchValue)}
            />
          : <Text style={styles.titleNavbar}>CONTACT</Text>
        }
      </View>
    );
  }
```

Any solutions?

**Comment by lewis-yuburi** [comment]
@munkhorgil you need to update the state `this.state.searchValue`, something like this:

```javascript
renderTitle = () => {
    return (
      <View style={styles.searchContainer}>
        {
          this.state.toggleSearch
          ? <TextInput
              style={styles.inputStyle}
              placeholder="Search"
              value={this.state.searchValue}
              onChangeText={searchValue => this.onSearch(searchValue)}
            />
          : <Text style={styles.titleNavbar}>CONTACT</Text>
        }
      </View>
    );
  }

...

onSearch(searchValue) {
  this.setState({ searchValue });
  ...andTheRestOfMethodCode
}

```

**Comment by munkhorgil** [comment]
@lewis-yuburi Of course it updates, I think the problem is it re-renders TextInput.
