### ISSUE TITLE
Sub-Scenes Unexpectedly Popping on Tab Change

### ISSUE THREAD

**Issue by scgough** [aksonov/react-native-router-flux#1275]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34
- node v5.2.0
- osx sierra 10.12
- XCode Version 8.0 (8A218a)
### Expected behaviour

Clicking into a sub-scene (`SceneA-1`) from a tab root scene (`SceneA`) which has been pushed via `Actions.[ActionID]` (this was a cloned scene).

Click onto another tab scene (`SceneB`) then return to the original scene via the tab. I would expect the stack to be maintained and show `SceneA-1`.
### Actual behaviour

Clicking into a sub-scene (`SceneA-1`) from a tab root scene (`SceneA`) which has been pushed via `Actions.[ActionID]` (this was a cloned scene).

Click onto another tab scene (`SceneB`) then return to the original scene via the tab. The stack is visibly popped (I see the animation) to root and `SceneA` shows.
### Steps to reproduce

This is a strange bug. The exact same code base behaves differently on my machine to my colleagues. 
I have tested using XCode iPhone 6 simulator and on my physical iPhone 5s device both running iOS10.0.2

My colleague however _doesn't get the issue_ running on OSX el capitan 10.11.6 using Xcode (same version) iPhone 6 sim and physical iPhone 6 iOS 9.3.5 and physical iPhone 7 iOS 10.0.2.

He has the same version of node, xcode and react native. 

Code:

```
class AppRoot extends Component {
  render() {
    return (
      <Router createReducer={reducerCreate} getSceneStyle={getSceneStyle}>
        <Scene key="modal" component={Modal} >
          <Scene key="root" hideNavBar hideTabBar>
            <Scene key="echo" clone component={EchoView} getTitle={(navState) => navState.key} />
            <Scene key="sceneA1" clone component={SceneA-1} getTitle={(navState) => navState.key} />
           <Scene key="sceneB" clone component={SceneB} getTitle={(navState) => navState.key} />
            </Scene>

            <Scene key="tabbar">
              <Scene key="main" tabs tabBarStyle={styles.tabBarStyle} tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle}>
                <Scene key="firstTab" component={SceneA} title="A" icon={TabIcon} initial />
                <Scene key="secondTab" component={SceneB} title="B" icon={TabIcon} />
              </Scene>
            </Scene>

          </Scene>
          <Scene key="error" component={Error} />
        </Scene>
      </Router>
    );
  }
}
```

The Button code (which would be triggered within `SceneA`

```
<Button
            onPress={() => Actions.sceneA1()}
            style={GenStyles.smaller}
          >
            Goto Scene A-1
          </Button>
```

**Comment by alizbazar** [comment]
I'm getting the same issue with react-native version 0.33.0 and react-native-router-flux 3.36.0 on iPhone 5s simulator. I would expect to return to the same subscene after navigating to a different tab and back (same as for.ex. Facebook app is operating).

-Albert

**Comment by quoctuams** [comment]
I am also facing the similar issue, there is clear animation that the sub-scenes were popped and the initial scenes appeared. Is there any update regarding this?

**Comment by mrnahidtalukder** [comment]
I am facing the same issues as well.

**Comment by alizbazar** [comment]
I just tried with the [current master](https://github.com/aksonov/react-native-router-flux/commit/2177a7f53d927cc3c983c28462d8c3264ab61ded) and there the issue doesn't seem to exist anymore. 👍
