### ISSUE TITLE
Cant return a initial Scene from Drawer

### ISSUE THREAD

**Issue by luisfuertes** [aksonov/react-native-router-flux#1278]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.2
- react-native v0.34.1

### My index tree
```
<Router>
   <Scene key="root" >
      <Scene key='Login' component={Login} />
      <Scene key='Drawer' component={SideDrawer} />
         <Scene key='drawerRoot' />
             <Scene key='Home' component={Home} />
         </Scene>
      </Scene>
   </Scene> 
</Router>
```

### Expected behaviour
Go to initial Scene on LogOut

### Actual behaviour
If i put Actions.Login() navigation go to Drawer.
If i put Actions.Login({type: 'reset'}) app crash with: `Cannot read property sceneKey of undefined` 

### Steps to reproduce
1. Init in Login
2. Actions.Drawer({type: 'reset'})
3. From home: Actions.Login({type: 'reset'})
4. App crash with error: `Cannot read property sceneKey of undefined`

How can i fix it?

**Comment by luisfuertes** [comment]
Some help?

**Comment by dragfire** [comment]
Do like this `Actions.Drawer()` without `{type: 'reset'}`.

**Comment by luisfuertes** [comment]
If i dont use `{type: 'reset'}`, user can go back with Android back button. I need add it after login.

**Comment by dragfire** [comment]
See this issue #1146

**Comment by luisfuertes** [comment]
But {type: 'reset'} should work fine. I use it in other app with Drawer and TabBar and dont have this issue.

**Comment by dragfire** [comment]
Haven't done much on Android. Try this let's see if it works `Actions.root({key: 'Login'})`

**Comment by luisfuertes** [comment]
When i put `Actions.Login()` or` Actions.root({key: 'Login'})`without reset, navigation flash 1 sec in Login component but after navigate to Drawer.

**Comment by dragfire** [comment]
on  Logout: `Actions.root({key: 'Login', type: 'reset'})`

**Comment by dragfire** [comment]
Mine is working fine on iOS. IDK.

**Comment by luisfuertes** [comment]
With `Actions.root({key: 'Login', type: 'reset'})` give same error: `Cannot read property 'sceneKey' of undefinded`

I have other project with router-flux working fine, but in this project i cant.

**Comment by dragfire** [comment]
The problem is you have already reset the scene history stack after login so login scene is no longer in the stack, it is empty. And you are looking for a sceneKey which is no longer in the stack.

**Comment by luisfuertes** [comment]
But i want start new stack from "Login" component. If i do Action.Login without reset, Login scene is presented a few seconds. But after going back to Drawer

**Comment by luisfuertes** [comment]
Ok the error is for this functions of my `SideDrawer`component:
``` 
	onOpen={()=>Actions.refresh({key:state.key, open: true})}
        onClose={()=>Actions.refresh({key:state.key, open: false})}
```

**Comment by TRIPTI-JAIN** [comment]
TypeError: Cannot read property 'eventName' of undefined, I got the error while using Actions.root({key: 'Login', type: 'reset'});
Can Anyone tell me how can i solve it??
