### ISSUE TITLE
Navigation bar height?

### ISSUE THREAD

**Issue by maphongba008** [aksonov/react-native-router-flux#1279]
### Version
- react-native-router-flux v3.35.0
- react-native v0.35.0

How can I get navigation bar height to add margin to the container view because the navigation bar overlap my container view?

**Comment by YuriyUlantsev** [comment]
@maphongba008 
`
// if can styles
...Platform.select({
      ios: {
        top: 64,
      },
      android: {
        top: 54,
      }
}),

// if you using ScrollView or ListView
<ScrollView
 contentInset={{top: (Platform.OS !== 'ios' ? 54 : 64), left: 0, bottom: 0, right: 0}}
 contentOffset={{x: 0, y: -(Platform.OS !== 'ios' ? 54 : 64)}}
/>
`

**Comment by maphongba008** [comment]
Tks. I just found the answer at [#561](https://github.com/aksonov/react-native-router-flux/issues/561)

**Comment by Gvade** [comment]
While working on android implementation of my app, I couldn't find any mention of navigation to be of height 54 in Material UI docs [here](https://material.io/guidelines/layout/structure.html#structure-app-bar). Seems that App bar (called NavBar here) should be 56 for mobile portrait layout case.
![structure - layout - material design guidelines](https://cloud.githubusercontent.com/assets/23520539/22734996/14a8e282-edf8-11e6-8478-9afcb7713881.jpg)
