### ISSUE TITLE
Expected onPress listener to be a function, instead got type boolean

### ISSUE THREAD

**Issue by michaelkclements** [aksonov/react-native-router-flux#1280]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.34.1

### Expected behaviour

`onPress={Actions.register}` to bring the Register scene forward

### Actual behaviour

When pressing the button, I get the error
`Expected onPress listener to be a function, instead got type boolean`

### Steps to reproduce

In the **Login.js** page I have a button that has an onPress={Actions.register} which doesn't work.

> App.js

```
import React, { Component } from 'react'
import { Router, Scene } from 'react-native-router-flux'
import { Login, Register } from './scenes/index'

export default class App extends Component {

  render() {
    return (
      <Router>
        <Scene key="root" hideNavBar={true}>
          <Scene key="login" component={Login} title="Login" initial />
          <Scene key="register" component={Register} title="Register" />
        </Scene>
      </Router>
    )
  }
}
```

> ./scenes/index.js

```
import Login from './Login'
import Register from './Register'

export { Login, Register }
```

> ./scenes/Login.js

```
import React, { Component } from 'react'
import { StyleSheet, Text, View } from 'react-native'
import { Actions } from 'react-native-router-flux'
import { Font, Button, Header, Footer } from '../components/index'

export default class Login extends Component {
  render() {
    return (
      <View>

        <Header />

        <View>
          <Font>
            <Text style={{fontWeight: '500'}}>Michael's</Text>
            <Text style={{fontWeight: '300'}}> Thing</Text>
          </Font>
        </View>

        <Footer>

          <Button onPress={Actions.register}>
            <Font style={styles.buttonText}>Expore our Demo</Font>
          </Button>

        </Footer>

      </View>
    )
  }
}
```

The Register.js is just a basic page. 
I believe I'm following the instructions as written except for the components and scenes being imported and exported through their index.js files.

**Comment by flaviotobi** [comment]
try onPress={()=>Actions.register()}
if not work try onPress={Actions.register()}

**Comment by michaelkclements** [comment]
@flaviotobi Still the same unfortunately.

**Comment by flaviotobi** [comment]
Try to do Actions.register() in any point of login, not when the button is pressed but for example after the initial render.

**Comment by dragfire** [comment]
Try this `Actions['register']()`

**Comment by michaelkclements** [comment]
No cure from either solution unfortunately.

Trying to put Actions.register in componentDidMount in App.js to see if it's an onPress issue.


```
componentDidMount() {

    // Did nothing
    // Actions.register
    // ()=>Actions.register()

    // Same Error
    // Actions['register']()
    // Actions.register()
  }
```

**Comment by flaviotobi** [comment]
Do you have any other scene that works ?

**Comment by michaelkclements** [comment]
It turns out the issue was I had a button in Header.js that had onPress={Actions.pop()}
That broke that page instead of what I thought was breaking it.

Unfortunately onPress={Actions.pop} won't work either so I need to figure that out, but I'd say this issue is closed.

**Comment by flaviotobi** [comment]
Roger, but try the recommendations that me and @dragfire gave you, in my code they work.
