### ISSUE TITLE
Navigating takes me to the previous scene for a second before going to the desired scene 

### ISSUE THREAD

**Issue by haikyuu** [aksonov/react-native-router-flux#1281]
I encoutered this issue when i upgraded to react-native@35.0
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.35.0
### Expected behaviour

I expect to navigate normally to my view when using `Actions[dest]({...props})`
### Actual behaviour

It shows the previous scene for a second before going to the desired scene.
![gif-app](https://cloud.githubusercontent.com/assets/8558836/19347840/c4fe2df8-9142-11e6-9548-272ffff766fa.gif)
### Steps to reproduce

I navigate with `Actions[dest]`
And go back with `Actions.pop`

**Comment by haikyuu** [comment]
Here is a repo if you want to reproduce it locally https://github.com/haikyuu/rnrfBug
![gif-simple](https://cloud.githubusercontent.com/assets/8558836/19353264/aadfad62-915a-11e6-85c0-9062f3991c4b.gif)

**Comment by feyy** [comment]
+1

**Comment by icynoangel** [comment]
Same here.
I have scene1 that will do Actions.scene2() when a prop it receives is set.
Then in scene2 on button press I am doing Actions.scene3(), and somehow the app goes through scene1, I can see scene3 for a second, then I am redirected back to scene2.

**Comment by thecachedbyte** [comment]
Any work around for this issue? This is happening every time we are doing quick navigation between scenes.

**Comment by Clowning** [comment]
No news ? I've the same issue!
