### ISSUE TITLE
Scene mounting bug

### ISSUE THREAD

**Issue by KirMcC** [aksonov/react-native-router-flux#1282]
### Version
- react-native-router-flux v3.35.0
- react-native v0.31.0
### Expected behaviour

Should navigate to different scene without any issues.
### Actual behaviour

This is the detailed example you provide from your repo. 
The previous navigated scene is shown briefly when navigating to a different scene.

For example if you select register page, then quickly go back and navigate to the Login scene. You will see the register scene for a couple of seconds, then reverts to correct scene. As shown below. 

![routerissue](https://cloud.githubusercontent.com/assets/9655830/19348117/2c68d0c8-9144-11e6-8402-00f05f984c8a.gif)

This issues has also occurred on other apps using react-native-router-flux.
### Steps to reproduce
1. Click Go to Register page
2. Quickly go back, then click Go to Login page

**Comment by KirMcC** [comment]
I'v also created a bare bone test case, using only react-native and react-native-router-flux. The same issue still appears.

![testcase](https://cloud.githubusercontent.com/assets/9655830/19383010/7d5d165e-91fa-11e6-8730-c9a1a97e718a.gif)

**Comment by Raktima** [comment]
I have the same problem! It happens ever since i started using reset function of react navigation
