### ISSUE TITLE
How to use react-native-router-flux and react-native-scrollable-tab-view?

### ISSUE THREAD

**Issue by leonacky** [aksonov/react-native-router-flux#1283]
### Version

Tell us which versions you are using: 

```
- react-native": 0.34.1,
- react-native-router-flux": ^3.36.0,
- react-native-scrollable-tab-view: ^0.6.0,
```
### Actual behaviour

I have an issue on iOS.
I'm using `react-native-scrollsble-tab-view` inside router/scene from `react-native-router-flux`, I have 4 tabs and the first tab contain scrollable-tab-view, its work fine on start but when I try to click on other tab of 4 tabs and go to first tab again, I see that scrollable-tab-view is not working, I can't swipe, can't click the tabs.
### Steps to reproduce
1. Open app, app has 4 tabs, the first tab contain scrollable tabview, check it is work fine
2. Click other tab(ex: second tab)
3. Back to first tab, scrollable tabview not working: cant swipe, cant click tabbar

The main has 4 tabs:

```
<Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#f7f7f7'}} hideNavBar={true}>
                <Scene key="modal" component={Modal} >
                    <Scene key="root" hideNavBar={true}>
                    <Scene key="launch" component={Launch} title="Launch" initial={true} style={{flex:1, backgroundColor:'transparent'}}/>
                    <Scene key="tabbar" tabs={true} hideNavBar={true}>
                        <Scene key="tab1" hideNavBar={false} initial={true} component={HomeScreen} title="Tab #1" icon={TabIcon}/>
                        <Scene key="tab2" component={SearchScreen}  hideNavBar={false} title="Tab #2" icon={TabIcon}/>
                        <Scene key="tab3" hideNavBar={false} component={NotificationScreen} title="Tab #3" icon={TabIcon}/>
                        <Scene key="tab4" hideNavBar={false} component={ProfileScreen} title="Tab #4" icon={TabIcon}/>
                    </Scene>
                    <Scene key="error" component={Error}/>
                    </Scene>
                </Scene>
            </Router>
```

First tab is `HomeScreen` contain `scrollable-tab-view`

```
<ScrollableTabView
                style={{marginTop:60}}
                initialPage={0}
                renderTabBar={() => <HomeTabBar />} >
                <HomeTabC2CScreen style={styles.tabView} tabLabel="ios-list" />
                <HomeTabC2CScreen style={styles.tabView} tabLabel="ios-people" />
                <HomeTabKhuyenMaiScreen style={styles.tabView} tabLabel="ios-notifications" />
            </ScrollableTabView>
```

Pls help me to fix it
Thanks

**Comment by strommmm** [comment]
i have the same problem

**Comment by strommmm** [comment]
this issue occurs not only on IOS, but on android, when i upgrade my react-native version to 0.35.0

**Comment by wuxushun** [comment]
I also have this problem, when you switch the TAB, can no longer scoll scrollview

**Comment by zhanbst** [comment]
It's not only with ScrollableTabView
I have this problem too with react-native-meteor with Switch feature
and version react-native 0.35.0

I fixed it

**Comment by zhanbst** [comment]
#1311

**Comment by phuongpt** [comment]
this issue can be fixed by @zhanbst's solution here https://github.com/aksonov/react-native-router-flux/issues/1311#issuecomment-255790686
but when access tab from places which not from tab bar (such as side menu), adding `type: "refresh"` cause other issues, for example change tab title or pass props not working
