### ISSUE TITLE
Not possible to split scenes that includes switch with redux

### ISSUE THREAD

**Issue by proProbe** [aksonov/react-native-router-flux#1284]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34.0
### Expected behaviour

Splitting up scenes in switches should be able to work
### Actual behaviour

Nothing shows on the scenes
### Steps to reproduce

I currently have this `Action.create` as I use redux.

```
Actions.create(
        <Scene
            key="root"
            component={connect(store => ({session: store.Router.session}))(Switch)}
            tabs={true}
            unmountScenes
            selector={state => state.session ? "main" : "login"}
        >
            <Login/>
            <Main/>
        </Scene>,
        RelayRenderer()
);
```

Where `Main` and `Login` looks similar to this:

```
<Scene
   key="login"
   title='Login'
   component={Login}
   hideNavBar={true}
   initial={true}
/>
```

**Comment by rturk** [comment]
@proProbe 
I've noticed that you're using `RelayRenderer` + `Redux` in the same code are you using Relay?

**Comment by proProbe** [comment]
@rturk yeah I am. `Redux` is for configuring state-data and Relay has all the information-data
