### ISSUE TITLE
Re-render same scene with updated props

### ISSUE THREAD

**Issue by ilkeraltin** [aksonov/react-native-router-flux#1285]
Hello everyone,
I'm trying to change article list on a feed when clicked an item from drawer menu. Same component should render with new props. But couldn't manage to do it. Help needed.
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.34.1
### Expected behaviour

When clicked an item on a Drawer, re-render current scene with new props.
### Actual behaviour

**Drawer Menu**

```
  menuItemClick = (cat) => {
      const drawer = this.context.drawer;
      drawer.close();
      console.log('panel click', cat);
     Actions.refresh({ category: cat, type: ActionConst.REPLACE });
}
```

**Home Scene Component**

```
import Feed from './Feed';

export default class Home extends Component {
  render() {
console.log(this.props.category);  -> here i can see passed new props
    return (
      <View style={{ flex: 1, marginTop: 60 }}>
  <Feed category={this.props.category} />  -> feed should re-render with new category
      </View>
    );
  }
}
```

**Feed Component** 

```
constructor(props) {
  super(props);
  this.state = {
    albums: [],
     loaded: false,
      refreshing: false,
       category: ''
  };
}

  componentWillMount() {
      this.fetchNews(this.props.category);
  }
```

**Route**

```
      <Router
        navigationBarStyle={navBarStyle.bar}
        leftButton={this.renderMenuButton}
      >
          <Scene key="drawer" component={MyDrawer}>
       <Scene key="root">
         <Scene
            key="NewsHome"
            component={Home}
            title={<Icon name='rocket' size={24} color="#ff5722" />}
            type={ActionConst.REPLACE}
            initial
            passProps
         />
        </Scene>
     </Router>
```

**Comment by dannycochran** [comment]
Related to https://github.com/aksonov/react-native-router-flux/issues/1266, or does it happen regardless of timing of the switch?

**Comment by ilkeraltin** [comment]
@dannycochran  It doesn't seem that these are similar problems.

in feed component i can see re-rendered props with code you can see below, but this time, firstly component renders with old data and after that it renders with new data. double render problem :/

  ```
  componentWillMount() {
    console.log('componentWillMount', this.state.category);
      this.fetchNews(this.props.category);
  }

  componentWillReceiveProps(nextProps) {
    console.log('componentWillReceiveProps', nextProps);
  this.fetchNews(nextProps.category);
}

```

**Comment by dannycochran** [comment]
Related #1281 and #1282

**Comment by ilkeraltin** [comment]
@dannycochran  thank you, will check it out.

**Comment by Mimicx** [comment]
i have the same issue, there is a solution for this ?

**Comment by hos4m** [comment]
Actions.refresh({ newPropKey: newPropData })
