### ISSUE TITLE
Unable to run Example - react-native run-android throws an error

### ISSUE THREAD

**Issue by dininski** [aksonov/react-native-router-flux#1288]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.30.0
### Expected behaviour

Running `react-native run-android` should build the Example app and deploy it to the device.
### Actual behaviour

`react-native run-android` fails with error 

`/mnt/68EE7093EE705AF0/crap/react-native-router-flux/Example/android/app/src/main/java/com/example/MainApplication.java:20: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
`
### Steps to reproduce
1. clone repo
2. `cd Example`
3. `react-native run-android`

**Comment by dmhood** [comment]
I fixed this issue by deleting .../java/com/example since .../java/com/aksonov/routerflux/example appeared to be the same thing/the actual package name.
