### ISSUE TITLE
Returning to the core NavigationExperimental Component?

### ISSUE THREAD

**Issue by csotiriou** [aksonov/react-native-router-flux#1289]
Hello,

First of all, thank you for this awesome library. Saves me tons of time.

Based on https://github.com/facebook/react-native/releases it seems that there have been tons of changes and optimizations done by facebook on the NavigationExperimental component. Some of them bring performance improvements, others bring API changes.

I totally understand why the https://github.com/aksonov/react-native-experimental-navigation has been created - to keep the RNRF API stable while facebook is making changes to the core API. 

However, we are now in version 0.35 of React Native, with 0.36 waiting around the corner, and seeing that react-native-experimental-navigation is 4 months old, I am starting to question whether RNRF should continue having the fork as a dependency or if it needs to revert to using the core NavigationExperimental API to take advantage of the new API features, and the performance optimisations. Some bugs, like #1282, #1285, #1275 may also disappear (since they seem to be the result of a race condition, that may be avoided by the new NavigationExperimental threading improvements)

Maybe it's time to revert to using facebook's implementation? Is it possible that we have stayed in the 0.26 version for too long?

Again, thank you for the time and effort you have put into this.

**Comment by aksonov** [comment]
@csotiriou I would like to return, any PR is welcome. Unfortunately it is quite big change because their(RN) API was changed significantly. And who knows how many breaking changes they may introduce later. Maybe when they renamed Experimental to 'stable' we could start migration.

**Comment by csotiriou** [comment]
If someone starts investing time into this, would you migrate into the react native's core component, even before it was made 'stable'?

**Comment by aksonov** [comment]
Sure. I've already started migrating to 0.29, check branch of experimental fork but didn't have time to finish

Pavel.

**Comment by hubciorz** [comment]
Hi @aksonov 

> Maybe when they renamed Experimental to 'stable' we could start migration.

A few days ago an official RN roadmap was published. The bad thing is, based on the current version, I guess that the whole Navigator stuff is going to be deprecated someday (maybe sooner that we think). 

Please check this out: https://github.com/facebook/react-native/wiki/Roadmap#user-content-core-libraries

> A new standard navigation library. Owners: skevy, ericvicenti. ETA: November
Right now there are a large number of navigation libraries. We don't think one navigation library will be enough for every use case, but we do think we can make it better. The goal is for this new navigation library to be ideal for apps that handle navigation in JavaScript. **Once it is released and stable, we can deprecate Navigator, NavigationExperimental, and ExNavigation.**

**Comment by aksonov** [comment]
One more 'standard' library? Huh... It is really strange, why they cannot create normal library from the beginning...
