### ISSUE TITLE
instructions in mini-tutorial result in onPress being called on render when data is passed

### ISSUE THREAD

**Issue by nikitph** [aksonov/react-native-router-flux#1290]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.35.0
### Expected behaviour

instructions in mini-tutorial to work as expected
### Actual behaviour

instructions in mini-tutorial result in onPress being called on render when data is passed
### Steps to reproduce
1. follow instructions in mini-tutorial 
2. in the Passing Information section, execute code as is
3. pageTwo loads on render and then pageOne is non -responsive

**Comment by nikitph** [comment]
i have a fix. need proper bindings for <TEXT>.lmk if you need a PR

**Comment by sibelius** [comment]
@nikitph could u explain more on this?

**Comment by nikitph** [comment]
Essentially if you follow the instructions word to word, instead of being
on page one onload you would be on page two because onpress is being called
on render for page one
