### ISSUE TITLE
Example build breaks on XCode 8

### ISSUE THREAD

**Issue by alexissmirnov** [aksonov/react-native-router-flux#1291]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.?.?
- XCode 8

### Expected behaviour

Build works

### Actual behaviour

Build fails

### Steps to reproduce
1. `cd Example`
2. `npm install`
1. `react-native run-ios`

**Comment by rturk** [comment]
Works for me. What RN version are you using?

**Comment by sibelius** [comment]
this is a problem with ur react native version, please upgrade it or follow this issue https://github.com/facebook/react-native/issues/8108
