### ISSUE TITLE
How to change navigationBarStyle based on routing parameters?

### ISSUE THREAD

**Issue by cmrichards** [aksonov/react-native-router-flux#1294]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.34.1

I'd like to change the colour of the navigation bar based on values of the parameters passed in.  For example, in my app I have the concept of a job which can be 'complete' and 'in-progress'.  When the job is 'complete' I'd like the navigation bar to show as green.  Is this easily possible with rnrf?

If navigationBarStyle accepted a function then this could be made to work.

Thanks!

**Comment by dragfire** [comment]
Yes indeed.

```javascript

// props: {status: 'complete'}

componentWillMount() {
      if(this.props.status === 'complete') {
            Actions.refresh({ navigationBarStyle: {backgroundColor: 'green' }})         
      }
}
```
