### ISSUE TITLE
Warning when calling an Action

### ISSUE THREAD

**Issue by JoaoCnh** [aksonov/react-native-router-flux#13]
Hey,

I've been using this router and it's been doing all I want. It works fine. 

But whenever I call an action. for example: Actions.ACTION_NAME();

it throws a warning in the console:

"An action was called but nothing was dispatched" from WarningBox.js

Am I doing anything wrong? Should I just ignore this warning?

**Comment by aksonov** [comment]
I've found that warning after recent upgrade,  I will ask alt team what does it mean.

**Comment by aksonov** [comment]
Should be fixed within next version of alt, closing for now.
