### ISSUE TITLE
Resetting routers on tabs already selected

### ISSUE THREAD

**Issue by joshuarotenberg** [aksonov/react-native-router-flux#130]
Thanks for your work on this project!

I would like users to be able to top "pop to top" tab routes if they click on a tab that is already selected. So clicking home would let them go straight back to top instead of having to click "back" 5 times.

Is this possible in the current implementation?

Thank you!

**Comment by aksonov** [comment]
Why just don't use Actions.ACTION_NAME with type 'reset' ? You may use own TabBar with such actions...
