### ISSUE TITLE
Is there a method called on a component when it is navigated to?

### ISSUE THREAD

**Issue by cmrichards** [aksonov/react-native-router-flux#1300]
Is there a method called on a component when it is navigated to?  So this would be when the component was first pushed onto the navigation stack, and also whenever the component appeared at the front of the stack again, such as when another scene has been popped and this one re-appears.

It seems like such a method would be quite useful. For example, you might want to refresh some of the data in the scene.

**Comment by dragfire** [comment]
```javascript
componentWillMount() {
    console.log(this.props) 
}

// See the props, everything is there.
```

**Comment by cmrichards** [comment]
Isn't componentWillMount only called when it's first mounted?  So if you went back (pop()) to that screen it wouldn't be called.   I'm looking for a method called whenever it becomes visible again.

**Comment by dragfire** [comment]
then in that case do this 
```javascript
Actions.pop({refresh: {...{hello: 'there'}}})
// then 
// in your component's

componentWillReceiveProps(newProps) {
    console.log(newProps, newProps.hello);
}
```

**Comment by cmrichards** [comment]
That will work, but it means you have to remember to add "refresh:{..." whenever you pop back to that component.  Feels a tad hacky.

I think it'd be nicer if another life cycle method something like this existed on the component: 

```
sceneWillBeDisplayed() {
    ...refresh anything I please...
}
```

**Comment by JeroenNelen** [comment]
@cmrichards I have also been looking for something like this, have you found any cleaner work around than the suggested changing of props? 

Kind regards,
