### ISSUE TITLE
Can I put a logo (image file) in the Nav bar?

### ISSUE THREAD

**Issue by spencerdezartsmith** [aksonov/react-native-router-flux#1301]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0?
- react-native v0.35.0?
### Expected behaviour

I am wondering if it is possible to have a logo (image file) in the Nav bar in place of titles? I would like the Logo to persist over all pages.

**Comment by infacq** [comment]
just use `renderTitle={() => <Title/>}`

**Comment by openmynet** [comment]
```js
        <Scene key="Demo"
          component={Views.Demo}
          titleStyle={titleStyle}
          getSceneStyle={getSceneStyle}
          navigationBarStyle={navStyle}
          NavigationBarBackgroundImage = {bgimage}
          renderRightButton={(e) => <RightButton />}
          renderLeftButton={(e) => <RightButton />}>
        </Scene>
```
