### ISSUE TITLE
Can react-native-router-flux suport time travel with redux-devtools? And how?

### ISSUE THREAD

**Issue by feyy** [aksonov/react-native-router-flux#1306]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.34.1
### Actual behaviour

When I revert to prev state, Router don't switch.

**Comment by mehdichamouma** [comment]
Any solutions ?

**Comment by feyy** [comment]
Then I think this is impossible. Because the prev page maybe has been destroyed. And there is not much revenue to do this.

**Comment by BerndWessels** [comment]
This is pretty essential, otherwise whats the point of `redux` integration with `react-native-router-flux` ?
