### ISSUE TITLE
Scene title is not updated while title={title} value was changed

### ISSUE THREAD

**Issue by liesislukas** [aksonov/react-native-router-flux#1307]
## Version

- react-native-router-flux v^3.35.0
- react-native v0.34.1

### Expected behaviour

change title on props value change

### Actual behaviour

Title is not changed. Static. While i see logs that prop was changed.

### Steps to reproduce

```javascript
render (
const title = `hey ${this.props.title}`;
console.log(`title should be ${title}`);
return (<Scene
  key="some_key"
  hideNavBar={false}
  component={Some}
  title={title}
/>);
)
```

and when this component re-renders, scene's title is not updated

**Comment by dragfire** [comment]
when it rerenders,
```javascript
componentWillReceiveProps(newProps) {
    Actions.refresh({title: 'WhatEverYouWant'})
}
```

**Comment by liesislukas** [comment]
works well, thanks ;)
