### ISSUE TITLE
Initial tab will be frozen when change tab

### ISSUE THREAD

**Issue by phuongpt** [aksonov/react-native-router-flux#1311]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.32.0
### Actual behaviour

The initial tab will be frozen, can't scroll or do anything when we change to another tab then back.

**Comment by Kaishley** [comment]
#1270

**Comment by zhanbst** [comment]
Use this event at initial tab  Actions.calendar({type: ActionConst.REFRESH});
```
<Scene key="myTabBar" tabs={true} hideNavBar tabBarStyle={style.tabBarStyle}>
  <Scene 
    key="myTab" 
    title="My Tab" 
    icon={MyTabIcon} 
    onPress={()=> {
      Actions.myTab_1({type: ActionConst.REFRESH});
    }}
   >
      <Scene key="myTab_1" component={MyTabComponent} hideNavBar/>
  </Scene>
</Scene>
```

**Comment by phuongpt** [comment]
thanks @zhanbst

**Comment by WillCoco** [comment]
thanks

**Comment by leonacky** [comment]
@zhanbst Not work with latest version
