### ISSUE TITLE
[Drawer (side menu) integration] not working with DrawerLayoutAndroid

### ISSUE THREAD

**Issue by inferusvv** [aksonov/react-native-router-flux#1313]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.35.0
### Expected behaviour

[Drawer (side menu) integration](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration) not working with DrawerLayoutAndroid

I've created a component with `index.android.js` and `index.ios.js` file. IOS use `react-native-drawer` component. And for Android `DrawerLayoutAndroid`. I've integrated it per guide  and when I do `NavigationActions.refresh({ key: state.key, open: true });` on Android it doesn't work. With iOS all fine and I see "true" value. 

I know, DrawerLayoutAndroid don't have `open` attribute. Any workaround here?

**Comment by inferusvv** [comment]
Found workaround:

```
  componentWillReceiveProps(props) {
    if (props.navigationState.open) {
      this._drawer.openDrawer();
    } else {
      this._drawer.closeDrawer();
    }
  }
```

It should be inside Drawer component

**Comment by satishmane** [comment]
Hi,
Can you please share working code example. I need to refer how do you to use menu in Drawer content option
thanks
