### ISSUE TITLE
Scene Won't Change With Remote Debugger Enabled

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [aksonov/react-native-router-flux#1314]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.35.0
### Expected behaviour

1.) User Logs In
2.) Scene Changes To 'Main' Scene
### Actual behaviour

1.) User Logs In
2.) Login is successful, but scene does not change to 'Main'Scene. Works fine when remote debugger is turned off. 
### Steps to reproduce
1. Turn on remote debugger
2. Login
3. Watch it not work lol

https://github.com/JohnAntonusMaximus/reactnative-issue/blob/master/src/actions/AuthActions.js
https://github.com/JohnAntonusMaximus/reactnative-issue/blob/master/src/Router.js

Problem is with loginUserSuccess( ) in AuthActions.js, it will navigate to the 'main' scene when remote debugger is turned off, but not when its turned on.

**Comment by Ehesp** [comment]
Have you left it a while?  There's a known problem with Animations in general when debugger is open causing the app to run very slowly.

**Comment by JohnAntonusMaximus** [comment]
No, happens regardless of how long the debugger has been left on. Happens instantaneously when you turn debugger on and persists throughout debugger usage.

**Comment by Ruzo** [comment]
Strangely quiet around this issue. I and at least another student of The Complete React Native and Redux Course on Udemy has the same issue. Seems like JohnAntonusMaximus might be following the same course so there might be something in common with it.
For the record, I'm using VS Code with the React Native Tools extension.

**Comment by franzherzog** [comment]
Same Issue here. Using Nexus5 Emulator.
But when I am switching to real device, debug remotely just works fine.

**Comment by franzherzog** [comment]
updated emulator and now it is running smoothly :)
Emulator: 
- Nexus 5 Android 7.1.1 API level 25
