### ISSUE TITLE
Creating custom parent scene with persistent navigation elements

### ISSUE THREAD

**Issue by IljaDaderko** [aksonov/react-native-router-flux#1315]
### Version
- react-native-router-flux v3.36.0
- react-native v0.35.0

Hello, I am trying to figure out the best solution in order to implement scene that will be used as a parent for sub scenes. Such parent will contain custom navigation elements, lets call them floating header and floating footer items (shown in the image). They will need to be persistent for several nested scenes in the parent. I am trying to figure out a best way to achieve something demonstrated below:

![example](https://cloud.githubusercontent.com/assets/3154053/19621040/5cb2df82-9881-11e6-8dad-80626a84e407.png)

Elements circled by red box will be ones that are not changing, scenes behind them will change with some sort of transition, lets say fade.

First thing that came to my mind was to style header and tabs components to achieve this. But as I want custom events happen to navigation elements based on state (i.e. different animations) I quickly found myself struggling with this approach.

Hence my question here asking community for their views on how to best implement something like this?

**Comment by antoligy** [comment]
I'm looking for very similar functionality to this, which seems to have been possible in version 2...
As far as I can tell, for the meantime the recommendation is to include custom navigation components within scenes...

**Comment by vasilycrespo** [comment]
+1

**Comment by abologna-r7** [comment]
Same here, but looking for persistent elements rather than just navigational elements.
