### ISSUE TITLE
Disable backButton on Modal

### ISSUE THREAD

**Issue by GCour** [aksonov/react-native-router-flux#1316]
Is it possible to disable the hardware backButton from popping when a modal is visible?

I'm using a load screen in a modal scene but users on Android can easily press on the back button which will make the load screen pop, even though the data hasn't even loaded yet..

**Comment by bsy** [comment]
`import {BackAndroid} from 'react-native'`

then in your component...
```
componentWillMount() {
    // Disable back button by just returning true instead of Action.pop()
    BackAndroid.addEventListener('hardwareBackPress', () => {return true});
}
```

**Comment by xyy7260** [comment]
Why, not practical /reset/  this method

**Comment by dancomanlive** [comment]
This is not working for me on RN 0.48, ReactNavigation 2.0 with     

`
componentWillMount = () => BackHandler.removeEventListener('hardwareBackPress', () => true);
`
