### ISSUE TITLE
Save/cancel changes to component from navbar buttons

### ISSUE THREAD

**Issue by brycepavey** [aksonov/react-native-router-flux#1322]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0

What's the best way to handle a screen that has edit/save functionality within the navbar? 

I'm using a custom nav bar thats rendered within my tab scene.
Currently I am connecting both my custom navbar, and the component with the values to update to the redux state, here's how the reducers state looks.

``` javascript
var initialState = { tempVals: [], vals: [] };
```

In my component any changes made to the values within it trigger an update to the redux tempVals state. When the save button in the navbar is pressed the tempVals are commited to vals, or cleared if cancel is pressed. 

Although this works, it seems a bit of a round-a-bout method because I'm maintaining a temporary list in redux for each of my 'vals', which starts to get messy. 
I think ideally I'd like to be able to simply trigger an update action to redux from my component with the local vals when the navbar save is pressed, though I'm not sure.

Is there a better way than what I'm currently doing to achieve the same result, or is this a suitable solution?

**Comment by cmrichards** [comment]
I don't think the way you're using redux is correct.    There's no reason to switch your tempVals to vals,  just use vals.    You can then clear vals from within a reducer after you have saved the data.

Here is one way to do what you need :  

You'll need to install redux-thunk for this to work.

```
// action creators

function createObject(data) {
	return {
		type: "CREATE_OBJECT",
                data
	}
} 

// One of your reducers would react to this action and clear the vals state
function clearForm() {
	return {
		type: "CLEAR_FORM"
	}
}

export function submitForm() {

	return (dispatch, getState) => {
		dispatch(createObject(getState.vals)).then(() => {
			dispatch(clearForm())
		}).then(() => { 
			Actions.mainPage()
		})
	}
	
}
```

Without knowing exactly how your using the data in the form it's not really possible to know how the action creators and reducers should work. 

If you're saving the data to a server then you'd probably want a "fetch" operation in the submitForm() method to send the data to your backend server

**Comment by brycepavey** [comment]
Thanks for the reply Chris.
I'll try to give some more info;
I have a form that contains multiple rows for input, some of these inputs are regular TextInput's but others are items selected from a list. When the user selects one of these multi-selection fields on the form it presents a modal multi-select list. If the user has already selected items, these items are pre-selected from my vals state, otherwise none are selected. 
As the user selects multiple items I update my tempVals state, I do this because if the user cancels rather than saves then the original form still needs to reflect that no changes were made. 

I can see how your example applies to a basic entry form which I already do similar in other areas, but I can't see how it would be suitable in this case (though I could be wrong!). 
I don't have access to the code right now to pull out the relevant pieces but i'll add them to give some more context in the morning.
