### ISSUE TITLE
Trigger Actions.refresh() without rerendering the component???

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#1323]
I'm just trying to understand something with rnrf

If we have dynamic title, navigationStyle or left, back buttons we are supposed to use Actions.refresh() and pass it an object with the desired changes. 

Now where do you put the call to Actions.refresh? If I put it in ComponentDidMount or in componentWillMount, then my component render method is called twice?

Is there a way to call Actions.refresh() so that it won't trigger a render twice. Nothing has changed in my component, that's why I don't understand why we need to rerender? 

If for example I do this.props.navigationState.title = 'something' -> then "something" is my title and render is called just once? But this doesn't always work for some reason. So what't the recomended way to use Actions.refresh()? Is the second call to render an issue at all?

**Comment by dragfire** [comment]
Have you considered `componentWillReceiveProps`

**Comment by cmrichards** [comment]
You wouldn't need to run refresh if the correct parameters were passed as part of the original route.

But, if you do really need to run refresh in ComponentDidMount  then it's not really a big deal because React is quick and will only render what has changed, and if that's only text in your navigation bar then it shouldn't take long.

**Comment by compojoom** [comment]
well, I'm curious how other people are doing it. 

Normally you can have a scene that says "new article" and "edit article".
The scene would also have a save button in the navigation. How would you do that without dynamic properties? Your component determines the title and the save action. 

But ok, if react is fast, then I'll ignore it for now.

**Comment by cmrichards** [comment]
Have you read about sub-scenes?

https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md

**Comment by compojoom** [comment]
Yes, I have, but to be honest I haven't really understand how to use that. Do we have a tutorial or an example app that uses the sub scenes?
