### ISSUE TITLE
NavBar won't display if split(nested) scenes wrapped in Drawer

### ISSUE THREAD

**Issue by ssomnoremac** [aksonov/react-native-router-flux#1324]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.0
- react-native v0.35.0

### Expected behaviour

wrapping a nested scene like so 

```
<workerScenes.js>
module.exports =
<Scene key="worker" component={DrawerComponent} open={false} hideNavBar={false}>
            <Scene key='workerShifts' ...
```

```
<Scene key='root'>
    { workerScenes } 
...
```

with the `DrawerComponent` copied from the example in docs would work (NavBar would display)

### Actual behaviour

Navbar is missing
<img width="283" alt="screen shot 2016-10-26 at 5 21 02 pm" src="https://cloud.githubusercontent.com/assets/3521359/19745679/aa2c7d64-9ba0-11e6-9c44-886f63fa15a6.png">

**Comment by gavin-gmlab** [comment]
I'm having this problem also
react-native-router-flux v3.35.0
react-native v0.35.0

**Comment by kevinlethe** [comment]
Try inserting a scene without a component as as a wrapper around the scenes contained within the drawer component.

So
<Scene key='drawer' component={drawer}>
  <Scene key='wrapper'>
    <Scene key='main' component={main}>

(Sorry for the layout, I'm on mobile)

**Comment by kevinlethe** [comment]
Totally screwed up the layout, but it should be
Scene with drawer component
  Scene with no component
    Other scenes with component s

**Comment by ssomnoremac** [comment]
That's the solution. Thanks for solving this!

**Comment by gavin-gmlab** [comment]
Didn't work for me. Mine is also nested with wrapper, but the problem seems to be if I have hideNavBar='true' in 2 successive components. Created issue #1330
