### ISSUE TITLE
Pop without animation

### ISSUE THREAD

**Issue by scerelli** [aksonov/react-native-router-flux#1325]
How can we move between scenes without transitions?

when you have to navigate to a certain scene we can use `duration: 0`.
But if it's a generic pop? how can i pop without animations?

**Comment by desmondhume** [comment]
@scerelli I managed to disable all transition animations by setting `duration={0}` on the `Router` itself.
```jsx
<Router duration={0}>
```
Maybe you have to use less scarseria.
