### ISSUE TITLE
Problem when showing WebView in drawer (maybe also in tab) 

### ISSUE THREAD

**Issue by eranbes** [aksonov/react-native-router-flux#1326]
**Version**
react-native-router-flux v3.36.0
react-native v0.34.0

**Actual behaviour**
When one of the tabs in drewer-wrapped tab set is or contains a WebView, after switching to that tab the WebView stays on top even when drawer then switches to different tab. Logically (touches, events, etc.) the new screen is active; but what is actually shown, is the old one with the WebView.

**Comment by WernlingTan** [comment]
I have same issue which is something like this issue.
Would you please help me?
