### ISSUE TITLE
Actions.SCENE({type: 'reset'})

### ISSUE THREAD

**Issue by ppiechota** [aksonov/react-native-router-flux#1327]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.32.0
### Expected behaviour

Actions.SCENE({type: 'reset'}) should work navigating from any scene, even from the same scene.
### Actual behaviour

Actions.SCENE({type: 'reset'}) issued from SCENE has no effect, SCENE is not remounted.

Although it works fine when navigating from another scene, it does not work when issued from the same scene. Being on a SCENE, SCENE should remount after issuing Actions.SCENE({type: 'reset'}) but it has no effect, or maybe I am missing something? 

Could you help me how to remount current scene?

**Comment by damir-sirola** [comment]
Try Actions.refresh({ key: 'SCENE' });
