### ISSUE TITLE
Receiving "synthetic event is reused" warning when navigating between scenes using redux sample code

### ISSUE THREAD

**Issue by joeferraro** [aksonov/react-native-router-flux#1328]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.35.0
### Expected behaviour

Navigating from one scene to another using the redux example should work without React performance warning
### Actual behaviour

Receiving the following warning when navigating between scenes using the sample code provided: "Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property "type" on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist()."
### Steps to reproduce
1. Implement the sample code for redux [found here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md), including the following in your first component: 

```
<Text onPress={Actions.home}>Go home</Text>
```
1. Run the app and tap on `Go home`
2. App is directed to `home` view, but several warnings appear with the text above

![glass_and_iphone_6s_ _ios_10_0__14a345_](https://cloud.githubusercontent.com/assets/54157/19781745/c72513d2-9c58-11e6-82e1-7a74d64d0840.png)

**Comment by jamielob** [comment]
@joeferraro I'm also seeing this - did you have any luck figuring out what was going on?

**Comment by Almouro** [comment]
I'm seeing the same thing :\

**Comment by jamielob** [comment]
@joeferraro @Almouro - I've found that changing from 

```
onPress={Actions.otherScene}
```

to

```
onPress={() => Actions.otherScene()}
```

has removed with these errors.

**Comment by Almouro** [comment]
Thanks @jamielob, this was the problem for me too. :)

**Comment by gustavjf** [comment]
Thanks @jamielob.

I wonder why the mini tutorial uses `onPress={Actions.Foo}` instead. Could there be a reason for that?

![screen shot 2017-01-30 at 4 14 27 pm](https://cloud.githubusercontent.com/assets/3981598/22428425/3a30fe56-e707-11e6-86c2-ab5cea65c031.png)

**Comment by EliCDavis** [comment]
jamielob's  suggestion fixed the error for me.

Noob here though, what's going on differently under the hood when you pass it an anonymous function vs an actual reference.

**Comment by CodyBrouwers** [comment]
In case anyone else comes across this error and the above doesn't work, I encountered it because I was passing the first argument from `onSubmitEditing` on a `<TextInput>` to a function like so:

```javascript
<TextInput
  onSubmitEditing={(text) => this.performSearch(text)} // Should be event, not text
/>
```

That text variable is actually the submit event which is what ended up giving me the message above and a headache debugging for a while.

**Comment by qianmenglin** [comment]
event.preventDefault();
event.stopPropagation();

**Comment by demoran23** [comment]
I'm not sure if the cause of this issue has been clearly explained, so please allow me to share my understanding and how I fixed it.

`TouchableWithoutFeedback` defines `onPress?: (event: GestureResponderEvent) => void;`.

Thus, when providing simply the function name, the parameter that is passed in is a `GestureResponderEvent` - and there's a good chance that isn't what you expect.

By changing from the function name to an anonymous function that invokes your function (eg `() => yourFunction()`), the `GestureResponderEvent` is not passed through to your function.

**Comment by FSBalbuena** [comment]
Guys i had this problem on a navigator.

```
Screen.navigationOptions=({navigation})=>{
const handleEditButton=navigation.navigate.bind(this,"EditProduct")
return {
    headerTitle:"My Products",
    headerRight:<CustomHeaderButton 
    iconName="ios-add"
    title="Add"
    iconSize={26}
    color={colors.bright}
    onPress={handleEditButton}
    />
}
}
```

pay attention to the method i used . **I was trying to bind the navigate method.** (Yeah, i know)

`const handleAddButton=()=>navigation.navigate("EditProduct")`
