### ISSUE TITLE
Getting currentRoute inside of Tab Route returns parent Route

### ISSUE THREAD

**Issue by ramilushev** [aksonov/react-native-router-flux#133]
Example: 

    <Router hideNavBar={true}>

                <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} />
                <Schema name="tab" type="switch" icon={TabIcon} hideNavBar={true} />
                <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottomAndroid} />

                <Route name="login" component={LoginWrapper} title="Login" initial={true} />
                <Route name="content">
                    <Router footer={TabBar} hideNavBar={true}>
                        <Route name="stream" title="stream" component={StreamNavigator} schema="tab" initial={true}/>
                        <Route name="popular" title="popular" component={PopularContainer} schema="tab"/>
                        <Route name="notifications" title="notifications" component={NotificationsContainer} schema="tab" />
                        <Route name="user" title="user" component={UserContainer} schema="tab" />
                    </Router>
                </Route>
            </Router>

When I navigate to "stream" via the TabBar, and then call `Actions.currentRouter.currentRoute` it returns `content` instead of `stream`

Any ideas?

**Comment by erdostom** [comment]
fixing this would probably also solve #132

**Comment by erdostom** [comment]
maybe #110 as well

**Comment by aksonov** [comment]
Yes, seems the same issue. Could someone look at it? I have quite limited time nowadays...

**Comment by aksonov** [comment]
Please check with latest version 2.1.3, there was error within TabBar component...
