### ISSUE TITLE
Nested Scenes with 2 successive hideNavBar Scenes causes all other Scenes  not to have Nav Bar

### ISSUE THREAD

**Issue by gavin-gmlab** [aksonov/react-native-router-flux#1330]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35
- react-native v0.35

```
     <Router>
        <Scene key='drawer' component={NavigationDrawer} open={false}>
          <Scene key='drawerChildrenWrapper' navigationBarStyle={Styles.navBar} titleStyle={Styles.title} leftButtonIconStyle={Styles.leftButton} rightButtonTextStyle={Styles.rightButton}>
            <Scene initial key='splashScreen' component={SplashScreen} title='Components' hideNavBar='true' />
            <Scene key='mainLoginScreen' component={MainLoginScreen} title='Login' hideNavBar='true' /> 
            <Scene key='mainScreen' component={MainScreen} title='Home'/> <=== Nav bar no longer appears for all subsequent screens
... Other scenes
          </Scene>
        </Scene>
      </Router>
```
### Expected behaviour

Nav Bar should appear after the initial Splash and Login Screens
### Actual behaviour

Nav Bar never appears if I have 2 successive screens with hideNavBar='true'
### Steps to reproduce
1. Implement the code as above
2. Nav Bar on 3rd screen (mainScreen) does not appear.
3. Remove hideNavBar = true from the Login Scene
4. Everything works as per normal

**Comment by peterkruty** [comment]
I have the same problem:

        <Scene 
          key="productintro"
          component={ProductIntro}
          hideNavBar="true"
          initial
        />

        <Scene
          key="homegym"
          component={HomeGym}
          hideNavBar={false}
          title="Home Gym"
        />

Second one does not have a NavBar.

**Comment by peterkruty** [comment]
I made it work with:

Actions.homegym({hideNavBar: false})

**Comment by gavin-gmlab** [comment]
@peterkruty, thanks - it kinda worked for me, but there were side effects.

I put the Actions.mainScreen({hideNavBar: false}) into my Button on the loginScreen - seems like this action is called automatically cause it automatically transitions straight to the mainScreen without me having to press anything (I am just doing UI work for now)

Also, there was a warning about setState(...): Cannot update during an existing State transition, which wasn't there before. There is no setState in my render() function for either screen. Could be from the Button component - not sure how it is implemented since I am using the one from 'react-native-elements'

**Comment by shroukkhan** [comment]
+1 . currently settings {hideNavBar:false} causes navigation bar to disappear. also putting {hideNavBar:true} causes navigation bar to disappear. basically , the mention of the property hideNavBar causes navigation bar to disappear! using version : react-native-router-flux@3.36.0

**Comment by ssomnoremac** [comment]
I just have all scenes with navbars set to false in the jsx and those without set to true. Sucks but that's how i have it and I've never had a problem. Don't know about passing as props. I wouldn't though. If you want to dynamically choose to show why not just clone the Scene and give it a different key, one with nav and one without?
