### ISSUE TITLE
react-native-navigation with react-native-router-flux

### ISSUE THREAD

**Issue by Amurmurmur** [aksonov/react-native-router-flux#1332]
is there anyway both of those used together?

Since react-native-navigation provides a proper native navigation it would be awesome to use it with react-native-router-flux.

Could maybe someone provide a small example of how to use them both?

**Comment by vonovak** [comment]
my understanding is you wouldn't use them together but only one of them

**Comment by Amurmurmur** [comment]
Thaaank you :)
