### ISSUE TITLE
Navbar / Initital Scene rendering issue

### ISSUE THREAD

**Issue by brobey8** [aksonov/react-native-router-flux#1334]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.34.1

Not sure if I'm doing something wrong here:

For some reason my navBar is rendering like this...

<img width="394" alt="screen shot 2016-10-30 at 5 53 54 pm" src="https://cloud.githubusercontent.com/assets/1326786/19835166/df1cb922-9ec9-11e6-92e7-a0b729ba90e6.png">

And my initial scene is not rendering at all.

Code:

```
import React, { PropTypes, Component } from 'react'
import {
    AppRegistry,
    StyleSheet,
    Navigator,
    Text,
    View,
    DeviceEventEmitter,
    ListView
} from 'react-native';
import { Router, Scene } from 'react-native-router-flux'
import BeaconList from '../components/BeaconList'

class Root extends Component {
    render() {
        return (
            <Router navigationBarStyle={{backgroundColor: '#1e2226', flex:1 ,alignSelf: 'stretch'}}  titleStyle={{color : "#FFF"}}>
                <Scene key="root">
                    <Scene key="beaconList" component={User} title="beaconList" initial />
                </Scene>
            </Router>
        )
    }
}

export default Root
```

**Comment by brobey8** [comment]
Nevermind, this was due to my own stupidity, I had my Root class inside of another component. Closing

**Comment by mmahalwy** [comment]
@brobey8 have the same problem, but I don't get your solution. Mind sharing a little more?

**Comment by brobey8** [comment]
@mmahalwy Hmm.. that first code block that you posted, is that the root js file that gets ran? My problem was that I was wrapping my component that holds my routes (which is the first code block in your comment) in another component, and including that.

**Comment by gp3gp3gp3** [comment]
@mmahalwy Did you ever figure out why this wasn't working?  I'm having the same issue.  The Router is my root component so I'm not seeing why this isn't rendering.

**Comment by mmahalwy** [comment]
@gp3gp3gp3 @brobey8 got it fixed. The problem is that you have to be careful with your `<View>` nesting. In my case, I had `View > Router > Scenes` and that did not allow me to render text. Make sure the router is the top most component.
