### ISSUE TITLE
rightButtonImage with imagesource not working

### ISSUE THREAD

**Issue by arisAlexis** [aksonov/react-native-router-flux#1335]
Using react-vector-icons wired up in the android app. The vector icons are working elsewhere and console.log reveals an imagesource object the second time render runs.
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.36.0
- react-native v0.34.1
### Expected behaviour

render icon in nav bar
### Actual behaviour

nothing gets rendered
### Steps to reproduce

``` javascript

import React, { Component } from 'react';
import { AsyncStorage, StyleSheet } from 'react-native';
import { Scene, Router, Actions } from 'react-native-router-flux';
import Icon from 'react-native-vector-icons/FontAwesome';
import LoginForm from './components/LoginForm';
import TeamList from './components/TeamList';

class RouterComponent extends Component {

  state ={
    exitIcon: null
  }

  componentWillMount() {
    Icon.getImageSource('sign-out', 20, 'white').then(imgsource => this.setState({ exitIcon: imgsource }));
  }

  render() {
    console.log(this.state.exitIcon);
    return (
        <Router>
          <Scene         
            key="main"
            onRight={() => {console.log('exit'); }}
            rightTitle="exit"
            rightButtonImage={this.state.exitIcon}
          >
        </Scene>
        </Router>
      );
  }
}

export default RouterComponent;
```

**Comment by LadislavBohm** [comment]
I don't know if this is correct solution, but what works for me when setting dynamically navbar icon (which is what you are also doing) is to set it via refresh like this:


```
const source = await Icon.getImageSource('sign-out', 20, 'white');

Actions.refresh({ 
      key: 'main', 
      rightButtonImage: source, 
      rightButtonIconStyle: { width: 18, height:18} });

```

I also call this code in componentWillMount

**Comment by arisAlexis** [comment]
Thanks for this. I tried it and it doesn't work but I don't understand why. The object is a {scale,uri}.  
 Where else do you call it? I also tried componentDidMount with same results.

**Comment by LadislavBohm** [comment]
Well, the only place I call it is the componentDidMount function. But the only thing that might cause an issue is, that you are setting both rightTitle and rightButtonImage. Try to have main scene like this:

```
          <Scene         
            key="main"
            onRight={() => {console.log('exit'); }}
          />
```

Then update rightButtonImage and rightButtonIconStyle via Actions.refresh.

**Comment by arisAlexis** [comment]
Yes tried that too, something else must be in place here.

**Comment by danielbm** [comment]
I am having the same problem, also tried the refresh solution, with no success.

**Comment by kirkness** [comment]
Adding the `rightButtonIconStyle` prop got it working for me.

```js
const source = await Icon.getImageSource('sign-out', 30, 'white');
Actions.refresh({
    rightButtonImage: source,
    rightButtonIconStyle: { width: 30, height: 30 },
    onRight: () => {},
});
```

**Comment by matt-d-rat** [comment]
I was experiencing the same issue, setting the rightButtonIconStyle was the solution that fixed it for me.
