### ISSUE TITLE
Tab navigation

### ISSUE THREAD

**Issue by itcurves** [aksonov/react-native-router-flux#1337]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.35.0
### Expected behaviour

Hi, 
I have an application where I have tabs and then under each tab I have navigation view.

What I need is when I am in a tab and navigate to another view and once come back to same tab after clicking any other I want to show the first view of that tab and also I want to make sure data loaded again (refresh) when tab first screen open.
### Actual behaviour
1. I open a tab and navigate to another view. 
2. I click on another tab.
3. Click that first tab again but I can see the last view open (after navigation)

I need to show the first in the Tab.

Please any help.
### Steps to reproduce

1.
2.
3.

**Comment by david50407** [comment]
How did you let the tab hold at the old view?
I want to leave each tab on the last view user seen. but it always return to the first view

**Comment by marceaul** [comment]
I experience the exact same behavior as @david50407, if anyone know how to change that.

**Comment by Dvidan** [comment]
Try the latest from the master branch. Looks like this #1312 changed it back

**Comment by marceaul** [comment]
It works perfectly, thank you for your input!

**Comment by david50407** [comment]
It still pop to the first view of the tab when I click on master branch, any idea?
