### ISSUE TITLE
Use tab to open drawer

### ISSUE THREAD

**Issue by b8ne** [aksonov/react-native-router-flux#1338]
I currently have a basic setup with 4 tabs.
The last tab is "More", which i want to use as a menu.  Clicking the tab should slide a menu in, which is then used to push more pages.
Im just not sure how to lay this out to have it functioning correctly.  Can anyone offer some help?

**Comment by LadislavBohm** [comment]
I did not test it, but I would do is use Actions.refresh somewhat like this:

`<Scene key="tab1_1" component={TabView} onRight={()=> Actions.refresh({key:"drawer", open: true})} />`

Scene definition is taken from https://github.com/aksonov/react-native-router-flux/blob/master/docs/DETAILED_EXAMPLE.md

Property key in onRight must reflect Scene key of your drawer, it sets open value to true, which should open the drawer if you have drawer properly set. Drawer example is here and I can verify, that it works fine: https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md

**Comment by b8ne** [comment]
Thanks mate got it figured.
