### ISSUE TITLE
RouterWithRedux HotReload not working

### ISSUE THREAD

**Issue by a-koka** [aksonov/react-native-router-flux#1339]
### Version
- react-native-router-flux v3.36.0
- react-native v0.33.0

### Expected behaviour
Scene component should update via Hot Reload

### Actual behaviour
I do have my `store` configured properly and Hot Reloading worked well before introducing RNRF. Now, I'm getting the error about `Provider` not supporting changing `store` on the fly.
[(https://github.com/reactjs/react-redux/releases/tag/v2.0.0](https://github.com/reactjs/react-redux/releases/tag/v2.0.0)

### Steps to reproduce

1. Setup a simple project with `redux`
2. Set the `store` and `reducers` as specified [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md)
3. Run the app and change the active scenes content to notice the error

**Comment by charlesbdudley** [comment]
@a-koka not sure why this worked, but for me changing the component I was editing from a `React.PureComponent` to `React.Component` seemed to make hot reloading work as intended.

**Comment by a-koka** [comment]
I haven't tried messing with this since I wrote this post. RN has come a long way and I'm sure there have been many updates to this library. Happy to close this issue if Hot Reloading is no longer a problem.
