### ISSUE TITLE
Example not working on XCode 8

### ISSUE THREAD

**Issue by a-koka** [aksonov/react-native-router-flux#1340]
### Version
- react-native-router-flux v3.36.0
- react-native v0.33.0

### Actual behaviour
Example fails to compile giving an RCT Websocket error.

**Comment by dragfire** [comment]
I think you have to remove some compiler flags from RCTWebsocket.

**Comment by a-koka** [comment]
Would you know which compiler flags @dragfire? I haven't encountered this error before and I'm relatively new to the mobile stack.

Thanks!

**Comment by dragfire** [comment]
https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

**Comment by dragfire** [comment]
Hopefully that should fix it.

**Comment by a-koka** [comment]
That did the trick! Thanks @dragfire.
