### ISSUE TITLE
Pop then push

### ISSUE THREAD

**Issue by acruis** [aksonov/react-native-router-flux#1341]
I'm trying to implement an user interaction which will cause the current scene to pop with the pop animation, and then another scene to be pushed. I tried:
```js
Actions.pop();
Actions.myScene(...);
```

But the `pop` animation doesn't occur, and when I pop `myScene` sometime afterwards, I'll still see the old scene.

So I followed #1125 and used `setTimeout`:
```js
Actions.pop();
setTimeout(Actions.myScene(...), 0);
```

The `pop` animation is still not visible (`myScene` just gets instantly pushed), but at least the old scene is not on the navigator stack any more (so popping `myScene` afterwards will not show me the old scene).

So I'm currently doing this:
```js
Actions.pop();
setTimeout(Actions.myScene(...), 250);
```

This does the job, but I'm wondering if there's a way to do this without `setTimeout`, especially since we can't control the duration of the popping animation (`Actions.pop({duration: 5000})` has no effect on the actual animation duration).

**Comment by ncnlinh** [comment]
@acruis I don't think you can achieve the behaviour you mentioned. The workaround you mentioned (using `setTimeout`) is the only solution at the moment. I have the same problem but with pushing multiple scenes.

**Comment by DeDuckProject** [comment]
setTimeout doesn't seem like a too bad solution. are there any issues with it?

**Comment by ncnlinh** [comment]
@DeDuckProject I feel that it is just ugly, and there is no documentation for this behavior. Since `Actions.<scene_key>()` is an imperative call, I feel that it is expected that the call should succeed every time you try to use it.

**Comment by DeDuckProject** [comment]
Yeah i totally agree.
