### ISSUE TITLE
Customize NavBar

### ISSUE THREAD

**Issue by andrycodestuffs** [aksonov/react-native-router-flux#1346]
Hi, I switched from Facebook's Navigator component to Flux's Router, everything works fine but I have an issue.
I created a custom NavBar for Navigator component using material design and now I'd like to import and use it in my new project, is it possible to change the given NavBar?

Material Design NavBar Code:
```javascript
<MaterialToolbar
  title={ 'NavBarTest' }
  icon={ 'menu' }
  onIconPress={ drawer.openDrawer() }
  rightIconStyle={{ margin: 10 }}
  />
```

**Comment by andrycodestuffs** [comment]
I didn't read the full documentation, I found out that there is navBar prop that gives you the ability to use a custom NavBar component

**Comment by iiitmahesh** [comment]
@andrycodestuffs Can share link exactly where it was. Or please provide code snippet

**Comment by iiitmahesh** [comment]
Oh I found it. 

https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md
