### ISSUE TITLE
navBar contents is not rendered with navigationBarBackgroundImage

### ISSUE THREAD

**Issue by iyel** [aksonov/react-native-router-flux#1348]
### Version
Tell us which versions you are using: 

- react-native-router-flux **v3.36.0**
- react-native v0.36.0?

### Expected behavior
See navBar elements in navBar with set ```navigationBarBackgroundImage```

### Actual behavior
No contents in navBar except image

### Steps to reproduce
```js
const logo = {
  uri: 'https://anyimage',
  height: 19, width: 163, 
};
// removed class code for brevity
<Scene key="cards" title="Cards" icon={TabIcon} 
  navigationBarStyle={styles.navBarWithLogo}
  navigationBarBackgroundImage={logo}
>

const styles = StyleSheet.create({
  navBarWithLogo: { 
    backgroundColor: '#262626', 
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingBottom: 10,
    justifyContent: 'center',
  },
  navBar: {
    backgroundColor: '#262626', 
  }
});
```

If i remove ```navigationBarBackgroundImage={logo}``` back button appears while navigating

Not only back button disappears but title aswell

**Comment by iyel** [comment]
I've made an investigation, problem lies in [file](https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L509) ```src/Navbar.js``` line 509
```js
{navigationBarBackgroundImage ? (
  <Image source={navigationBarBackgroundImage}>
    {contents}
  </Image>
) : contents}
```

Because title, back, left and right buttons have absolute positioning they are not visible if wrapped by image

**Comment by aozisik** [comment]
Also experiencing the same issue
