### ISSUE TITLE
renderLeftButton not working if navbar placed at bottom

### ISSUE THREAD

**Issue by infacq** [aksonov/react-native-router-flux#1351]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.33.0

### Expected behaviour

renderLeftButton to show another icon when navbar is at the bottom

### Actual behaviour

it doesn't render

### Steps to reproduce

1.
```js
<Scene key='product' direction="vertical" navigationBarStyle={{bottom: 0, top: null, borderBottomWidth: 0, borderTopWidth: 1}} component={Product} renderLeftButton={NavItems.hamburgerButton} />
```
2. react-native run-ios

**Comment by zhanbst** [comment]
may be use style props bottom to renderLeftButton too?

**Comment by infacq** [comment]
what do you mean?
