### ISSUE TITLE
Can not read property '<functionname>' of undefined when using onBack in prerendered scenes

### ISSUE THREAD

**Issue by SebasJK** [aksonov/react-native-router-flux#1352]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^3.36.0
- react-native v0.35.0

### Expected behaviour

Expected sucessfull call to the function '_someFunction', as when the Scenes are placed directly within de router: as such:
<Router>
  <Scene key="root">
    <Scene key="login"  component={Login} title="Login"  onBack={ ()=>this._someFunction() } />
    <Scene key="register" component={Register} title="Register"/>
    <Scene key="home" component={Home}/>
  </Scene>
</Router>

Where '_someFunction' is a function of "class App extends Component{ }"

### Actual behaviour

Can not read property '<functionname>' of undefined

const scenes = Actions.create(
  <Scene key="root">
    <Scene key="login"  component={Login} title="Login"  onBack={ ()=>this._someFunction() } />
    <Scene key="register" component={Register} title="Register"/>
    <Scene key="home" component={Home}/>
  </Scene>
)

<Router scenes={scenes}/>

### Steps to reproduce

1. recreate sample from https://github.com/aksonov/react-native-router-flux
2. add onBack as shown and the function '_someFunction' within class App extends Component
3. use const scenes = Actions.create( ... )

**Comment by dragfire** [comment]
So if `_someFunction()` is in `Login` component then what you could do is:
```javascript
<Scene key="login" component={Login} title="Login" onBack={ ()=>{
     Actiions.refresh({triggerSomeFunction: true});
} } />

// then in your login component

componentWillReceiveProps(props) {
     if(props.triggerSomeFunction) { 
             // Now you can do
            this._someFunction();
     }
}

```

**Comment by SebasJK** [comment]
Hello,
yes that would work but '_someFunction' is a function of "class App extends Component{ }" not of login. the onBack could be attach to any scene.

**Comment by SebasJK** [comment]
This might give a better view of what the issue is

_First declare scenes:_

```
const scenes = Actions.create(
  <Scene key="root">
    <Scene key="login" component={Login} title="Login" onBack={ ()=>this._someFunction() } />
    <Scene key="register" component={Register} title="Register"/>
    <Scene key="home" component={Home}/>
  </Scene>
)

```
_Then within the App:_
```

class App extends Component {

  _someFunction() {
     console.log('Debug message: aFunction called');
   }

  render() {
    return (
        <Router
          scenes          = {scenes}
          hideNavBar      = {true}
        />
    )
  }
}

```
The problem is, that when the button is clicked, it generates the error this._someFunction() is not a function.

If we do it like this:
```

class App extends Component {

  _someFunction() {
     console.log('Debug message: aFunction called');
   }

  render() {
    return (
        <Router
          hideNavBar      = {true}
        >
       <Scene key="root">
         <Scene key="login" component={Login} title="Login" onBack={ ()=>this._someFunction() } />
         <Scene key="register" component={Register} title="Register"/>
         <Scene key="home" component={Home}/>
       </Scene>
       </Router>
    )
  }
}

```
