### ISSUE TITLE
Hide drawer/hamburger button in NavBar

### ISSUE THREAD

**Issue by PetterRuud** [aksonov/react-native-router-flux#1353]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.35

I'm trying to create a tabbar like facebook, last tab opens the drawer.
I have 
```
<Scene key="tabbar" component={NavigationDrawer} open={false}>
    <Scene key="main" tabs={true}>
        TABS...
        <Scene key="tabMore" component={TabView} title="More"  icon={TabIcon} onPress={()=> Actions.refresh({key:"tabbar", open: true})}  />
```

I dont want the hamburger icon to show up in the navbar. Is there a way of doing this other than creating custom NavBars for the tabsgroups

Thanks in advance.

**Comment by wuxushun** [comment]
i have the same issues
could you solve it?

**Comment by DiegoGallegos4** [comment]
You should pass to the scene the drawerImage prop:
 
`drawerImage={{uri: ''}}`

**Comment by Timehello** [comment]
just set the drawerImage to false

**Comment by activelogic** [comment]
Setting the drawer image to either ```{{uri: ''}{``` or {false} will throw a warning.
Instead use: ```drawerImage={{ uri: null }}```.

**Comment by WebStew** [comment]
Hi @activelogic 

> Setting the drawer image to either {{uri: ''}{ or {false} will throw a warning.
Instead use: drawerImage={{ uri: null }}. 

This worked perfectly for me on my Andriod emulator but on iOS iPhone 6 emulator it is throwing a `JSON value <null>` error when I run it. Any ideas?

**Comment by activelogic** [comment]
@WebStew - Sorry for the delay.  I have not tested my solution on an iPhone emulator (only Android), so cannot confirm whether or not the error is thrown.

**Comment by tmaly1980** [comment]
There COULD be a better way, but what I did to remove the hamburber navicon was add this to each/every scene:

`renderLeftButton={()=>{}}`

I am using tabs so it didn't seem to work when assigning to the tabbar or tab scene, only the individual component scenes. The back button still renders, though, when you go forward. If you want to disable the back button as well, you'll have to set:

`renderBackButton={()=>{}}`

If there's a better way, I'd love to know. All of the above suggestions didn't work in IOS.
