### ISSUE TITLE
Add support for react-native-windows

### ISSUE THREAD

**Issue by leesolway** [aksonov/react-native-router-flux#1356]
Apologies if this has already been raised, i can't find a ticket for it. 

react-native-windows is coming along nicely, and would benefit from seeing support using this library. As the most popular router, it gives access to the entire UWP platform.

**Comment by semiautomatix** [comment]
Has this been tested?

**Comment by leesolway** [comment]
I managed to test it awhile back. It was missing the back icons, easily fixable, but worked otherwise.

**Comment by semiautomatix** [comment]
Thanks, yes seems to work well
