### ISSUE TITLE
ActionConst.PUSH scene data

### ISSUE THREAD

**Issue by Druux** [aksonov/react-native-router-flux#1357]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.33.2
- react-native v0.31.0

### Expected behaviour

Is there a possibility to get access to actions.scenes if the ActionConst.PUSH has been dispatched. I would like to use more or less the same behavior from ActionConst.FOCUS.
`Object {key: "someScene", type: "REACT_NATIVE_ROUTER_FLUX_PUSH"}`
`Object {scene: Object, type: "REACT_NATIVE_ROUTER_FLUX_FOCUS"}`

I am wondering because ActionConst.FOCUS wont be dispatched after I am pushing a Modal. Probably I am doing it completely wrong.

**Comment by zoharlevin** [comment]
+following

**Comment by autovalue** [comment]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md#reduxflux
