### ISSUE TITLE
Update react-native-experimental-navigation

### ISSUE THREAD

**Issue by olofd** [aksonov/react-native-router-flux#1358]
This library uses nav-code from React Native 0.26 as I understand it?
As of React Native 0.37 we now have Natively driven animations in React Native's Experimental Navigation. (If we disable gestures). Is there any plans to update this outdated dependency?

**Comment by robbue** [comment]
My understanding is that it's a [big change](https://github.com/aksonov/react-native-router-flux/issues/1289), but the improvements would be a big thumbs up :) @aksonov, is there any update on this?

**Comment by hubciorz** [comment]
As far as I know, there is also a PR here dannycochran/react-native-experimental-navigation#1 which patches the existing react-native-experimental-navigation clone used by react-native-router-flux in order to use the native driver

CC: @aksonov @dannycochran
