### ISSUE TITLE
Question: What is the proper way to style and use icons w TabBar?

### ISSUE THREAD

**Issue by rturk** [aksonov/react-native-router-flux#136]
Hi,
I'm using React-native-vector-icons so I'm using the code in order to add icons to TabBar. In order to define the icon I'm using my own iconName props. This code works, but is the best way to achieve a tabbar with icons inside router?

    class TabIcon extends React.Component {
    render(){
      var color = this.props.selected ? Globals.brandlovers.color : 'black';

      return (
        <View style={{flex:1, flexDirection:'column', alignItems:'center', alignSelf:'center'}}>
            <Icon style={{color: color}} name={this.props.iconName} size={18} />
            <Text style={{color: color}}>{this.props.title}</Text>
        </View>
      );
    }
    }

    <Schema name="tab" type="switch" icon={TabIcon} />
    <Route name="tabbar"  wrapRouter={true} >
        <Router footer={TabBar} showNavigationBar={false}>
            <Route name="tab3"    schema="tab" title="NewsFeed" iconName={"newspaper-o"}  hideNavBar={true} component={NewsFeed}  />
            <Route name="myfeed"  schema="tab" title="MyNews"   iconName={"user"}         hideNavBar={true} component={UserNewsFeed}  />
            <Route name="tab4"    schema="tab" title="Settings" iconName={"gear"}         hideNavBar={true} component={Settings} />
        </Router>
     </Route>

Please comment if this is correct, makes sense...

**Comment by aksonov** [comment]
Looks ok.

**Comment by qasimalbaqali** [comment]
Thanks for this! :+1:
