### ISSUE TITLE
Typescript Definition problem

### ISSUE THREAD

**Issue by franleplant** [aksonov/react-native-router-flux#1361]
### Version
Tell us which versions you are using: 

- react-native-router-flux 3.36.0
- react-native 0.36.1
- typescript 2.0.6

### Expected behaviour

I have a route defined with the `key='wardrobe'`.
Then I want to navigate to that route via:

```javascript
Actions.wardrobe();
```

### Actual behaviour

Typescript complains that `wardrobe` does not exist

```
 error TS2339: Property 'wardrobe' does not exist on type 'RNRFActions'.
```

### Steps to reproduce

1. Define a route with a key
2. Attempt to navigate to that route directly
3. See the error by de Typescript compiler

**Comment by wcandillon** [comment]
@franleplant I think it got fixed into master but they didn't release a new version of the package yet.

**Comment by franleplant** [comment]
Ok, thanks a lot, just to document how I monkey-solved it:

```typescript
(Actions as any).wardrobe()
```
