### ISSUE TITLE
About hideNavBar property.

### ISSUE THREAD

**Issue by MechanicKim** [aksonov/react-native-router-flux#1363]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.37.0

### Expected behaviour
As I know, default value of scene property 'hideNavBar' is false.

### Actual behaviour
but When I make hideNavBar true in specific scene, next other scenes are influenced.

### Steps to reproduce

1. Make three scenes and make hideNavBar of only second scene true.
2. If you reload your application, you can see that first page has a NavBar but, second and third don't have NavBar.

I've found a strange thing on DefaultRenderer.js
Two lines(237 ~ 238) are like this.

**const hideNavBar = deepestExplicitValueForKey(state, 'hideNavBar');
if (hideNavBar) {**

I fixed something(238 line) and I could solve this. like this.

**if (child.hideNavBar) {**

**Comment by loug38** [comment]
Great fix! Thanks!

**Comment by MechanicKim** [comment]
Thank you for your reply!

2016-11-16 5:07 GMT+09:00 Lou George <notifications@github.com>:

**Comment by gavin-gmlab** [comment]
Similar issue #1330 . Is this going to be officially fixed?

**Comment by MechanicKim** [comment]
Oh! Can I fix this issue?
I just wrote this issue. I didn't fix it.

**Comment by sarovin** [comment]
@MechanicKim a PR is welcome ;)
