### ISSUE TITLE
How to push a scene while resetting the stack **except** the initial scene?

### ISSUE THREAD

**Issue by leledumbo** [aksonov/react-native-router-flux#1365]
I'm using react-native-router-flux v3.36.0 and I need to replace the current scene with another scene while at the same time resetting the stack except the initial scene. For example:

1. scene stack:
A -> B -> C -> D -> E (we're in E)
2. do something in E that changes the scene stack to:
A -> F

scene A is marked `initial` and `type={ActionConst.RESET}`.

What I've tried so far:
1. In E, do;
```
Actions.A()
setTimeout(() => Actions.F(), 500)
```
Result: too clear that scene goes to A first before displaying F, especially on slow device
2. In E, do:
`Actions.A({someprop: value})`
In A's `component(Did|Will)(Mount|Update)` :
```
if (this.props.someprop) {
  Actions.F()
  this.props.someprop = false
}
```
Result: either race condition causing unfulfilled promise or F becomes the top of scene stack (i.e.: pressing back will close app)

What's the correct way?

**Comment by pewh** [comment]
+1 have same issue

**Comment by voidale** [comment]
+1

**Comment by ericvera** [comment]
+1

**Comment by hakunin** [comment]
How about using `pop()` couple of times and then triggering F?

**Comment by leledumbo** [comment]
> How about using pop() couple of times and then triggering F?

Super clear animation, I believe. What is needed is some kind of invisible `pop()` or trigger F as a new scene stack, discarding existing one silently.

**Comment by leledumbo** [comment]
> What is needed is some kind of invisible pop() or trigger F as a new scene stack, discarding existing one silently.

Sorry, my bad. F should not start as a new scene stack, as A is still expected to be the root, with F right on top of it.

> How about this? Using POP_AND_REPLACE action with popNum set to whatever you need.

Can we get the current stack depth? That value - 1 would be the required `popNum` argument.

**Comment by hakunin** [comment]
> Can we get the current stack depth? That value - 1 would be the required popNum argument.
I think state should be somewhere attached to the navigator prop, I haven't played with it too much yet :)

I was playing with custom toolbar and I had access to `props.navigationState.children` which shows you the stack of scenes.

**Comment by leledumbo** [comment]
> I was playing with custom toolbar and I had access to props.navigationState.children which shows you the stack of scenes.

I hope it has `.length` or `.size` property, will check later. Thanks.

**Comment by dragfire** [comment]
How about using a customReducer?

**Comment by JeroenNelen** [comment]
anyone found anything concerning this? I'm in need of the same situation... clear several items on the stack but not all of them
