### ISSUE TITLE
Add support for customizing right/left buttons

### ISSUE THREAD

**Issue by iheart2code** [aksonov/react-native-router-flux#137]
It doesn't seem possible to provide a custom right or left button with this library.

**Comment by adrienbrault** [comment]
It is:

```
const renderRequestsRightButton = () => {
    return (
      <NavigationBarButtonItem>
        <Button onPress={addRequest}>
          <Icon
            color="#007AFF"
            name="plus"
            size={20}
          />
          Add
        </Button>
      </NavigationBarButtonItem>
    );
  };

  return (
    <Route
      component={ConnectedRequestsView}
      name="requests"
      renderRightButton={renderRequestsRightButton}
      title="Requests"
      type="replace"
    />
  );
```

If I got it correctly, you should be able to pass any of the following props to your routes: https://github.com/exponentjs/ex-navigator/blob/master/ExRoute.js#L6

**Comment by iheart2code** [comment]
I was able to find a similar solution in one of the other closed issues. Would be a great candidate to add to the README or the Example app.
