### ISSUE TITLE
tions

### ISSUE THREAD

**Issue by chrmcg** [aksonov/react-native-router-flux#1371]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Steps to reproduce

1.
2.
3.

**Comment by sarovin** [comment]
@aksonov close it

**Comment by aksonov** [comment]
Thanks for your help. I've added you as collaborator, feel free to close issues/answer them, thanks.

**Comment by sarovin** [comment]
ok, thank you @aksonov
