### ISSUE TITLE
Why doesn't Modal dispatch ActionConst.FOCUS?

### ISSUE THREAD

**Issue by zoharlevin** [aksonov/react-native-router-flux#1373]
### Version

- react-native-router-flux v3.35.0
- react-native v0.36.0

I see that when routing to the Modal scene ActionConst.PUSH is dispatched but not ActionConst.FOCUS.  is this the expected behavior or is it a bug?
What is the correct way to keep track of the Scene currently rendered on screen? (clearly FOCUS is not enough when using modals)

**Comment by jamielob** [comment]
I've just come up against this too. @zoharlevin - did you figure a workaround?

**Comment by jamielob** [comment]
@zoharlevin - Ok, as with the solution I posted in https://github.com/aksonov/react-native-router-flux/issues/1328 I'm seeing the FOCUS event dispatched if I change from

```
onPress={Actions.pop}
```
to
```
onPress={() => Actions.pop()}

```

**Comment by zoharlevin** [comment]
@jamielob 
I do call Actions.pop() explicitly and I don't get a FOCUS dispatched, so not sure why that changed anything in your case.
for my scenario in the reducer I ended up looking at the PUSH and BACK_ACTION which are dispatched for the modal and FOCUS for other scenes (but I look specifically at the Modal scenes according to key).  I don't think it's a very pretty solution, but it's the best I could come up with for my case.
still don't know if this is expected behavior though.

**Comment by jamielob** [comment]
@zoharlevin Very strange - it's all working fine for me now, apart from switching between tabs which doesn't seem to dispatch the correct FOCUS action.

**Comment by jamielob** [comment]
In case it helps anyone else, my version are:
```
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
```
