### ISSUE TITLE
hide navbar and bottom tab bar on scroll

### ISSUE THREAD

**Issue by itelo** [aksonov/react-native-router-flux#1374]
- react-native-router-flux v3.2.4
- react-native v0.3.7.0

A common feature in mobile devices is hide navbar and tabbar on scroll down, and show again it when scroll up, it that possible in that project (with some animation too) ? Also, this lib let me create a custom navbar?

**Comment by nbolender** [comment]
@itelo To answer your second question, you can create a custom navbar. You can either pass a navigationBarStyle prop to your Router or Scene (along with other properties like titleStyle, backButtonTextStyle etc.), or you can pass a whole custom component to the navBar prop List of props here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md

**Comment by vitorebatista** [comment]
I'd like to know how hide navbar too!
