### ISSUE TITLE
Disable swipe back gesture without disabling all gestures

### ISSUE THREAD

**Issue by thngdude** [aksonov/react-native-router-flux#1376]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.34.0

Is it possible to disable the default swipe back gesture without disabling all gestures? I tried panHandlers={null} in the scene, but I can no longer open a drawer component.

**Comment by MattyK14** [comment]
+1

**Comment by frmdstryr** [comment]
panHandlers	object		optional, provide null to disable swipe back gesture

Setting panHandlers={null} worked for me.

**Comment by torihuang** [comment]
+1

**Comment by ricardokdz** [comment]
+1
