### ISSUE TITLE
how can i get the current scene by redux

### ISSUE THREAD

**Issue by wuxushun** [aksonov/react-native-router-flux#1378]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour

I want to get the current scene,but get the whole of scenes

### Actual behaviour

I got the whole of scenes, how can i get the current scene by redux?

thank you for your wonderful component!

**Comment by LukeAvery92** [comment]
Might not be the best way but I achieved it by doing:

`_createReducer = (params:Object):Reducer => {
    const defaultReducer = Reducer(params);
    return (state:Object, action:Object):Function<Reducer> => {
      if (action.hasOwnProperty('scene')) {
        this.props.setRoute(action.scene.name); // This is our redux action. We keep a string of currentRoute
      }
      return defaultReducer(state, action);
    };
  };`

and then <Router createReducer={this._createReducer}>

**Comment by pewh** [comment]
@LukeAvery92 Sometimes your solution shows incorrect current scene on tabbar. 

```
<Scene
      key='tabs'
      tabs
      tabBarStyle={styles.tabBar}
      tabBarSelectedItemStyle={styles.tabBarSelectedItem}
      type='replace'
    >
        <Scene key='foo' ... />
        <Scene key='bar' ... />
</Scene>
```

When I'm on `foo` scene, `action.scene.name` sometimes show `tabs` or `foo`. Is it a bug?
