### ISSUE TITLE
How to change color of menu burger icon

### ISSUE THREAD

**Issue by phuongpt** [aksonov/react-native-router-flux#1380]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.37.0

### Actual behaviour

- I tried  `leftButtonIconStyle={{tintColor: '#fff'}}` or `leftButtonStyle={{tintColor: '#fff'}}` but not successful 
- it works from source code
```
          menuIcon = (
            <Image
              source={buttonImage}
              //style={leftButtonStyle}
              style={{tintColor:'#fff'}}
            />
          );
```

**Comment by Naoto-Ida** [comment]
I can't recreate this.

- react-native-router-flux v3.35.0
- react-native v 0.34.1

````
<Scene
  key='showPost'
  component={PostContainer}
  leftButtonIconStyle={{tintColor: '#fff'}}
   queries={{viewer: () => Relay.QL`query { viewer }`}}
/>
````

This shows a back arrow as the left icon when I push to the component.

**Comment by phuongpt** [comment]
@Naoto-Ida I have no problem with `back button`. I'm getting issue with side menu icon

**Comment by MattyK14** [comment]
Yeah the `back button` is no issue, anyone solve the menu button?

**Comment by ddeanto** [comment]
Was anybody able to solve this? I can't even find where the default blue burger icon is coming from in the codebase

**Comment by MattyK14** [comment]
I changed mine to white using:

    `barButtonIconStyle={{ tintColor: 'white' }}`

**Comment by ddeanto** [comment]
@MattyK14 `barButtonIconStyle={{ tintColor: 'white' }}` is not working for me. Can you paste a bit more of your code? Thanks!

**Comment by MattyK14** [comment]
@ddeanto 

`const RouterComponent = () => {
    return (
      <Router
        barButtonIconStyle={{ tintColor: 'white' }}
        navigationBarStyle={{ backgroundColor: 'black', opacity: 0.65 }}
        panHandlers={null}
        {...this.props}
      >
        <Scene key="auth">
          <Scene
            sceneStyle={{ paddingTop: 40 }}
            key="loginPage" component={LoginForm}
            title="Login" hideNavBar
          />
        </Scene>
        <Scene key="main" component={NavigationDrawer} initial/* skips login for debug */>
          <Scene
            key="home"
            leftButtonIconStyle={{ tintColor: 'white' }}
            titleStyle={{ color: 'white' }}
          >`

**Comment by ddeanto** [comment]
@Mattk14 thanks! What is working for me is placing `leftButtonIconStyle={{ tintColor: 'white' }}` in the Scene with the drawerImage NOT placing `barButtonIconStyle={{ tintColor: 'white' }}` in <Router>

**Comment by Mattk14** [comment]
@aksonov I believe this issue can be closed.

**Comment by phuongpt** [comment]
thanks @ddeanto @Mattk14!  it works for me.

**Comment by sadia-onyxtec** [comment]
```

<Drawer.Navigator
    screenOptions={{
        headerTintColor: 'red', // -----> by changing color from here
    }} drawerContent={props => <DrawerContent {...props} />} >
    <Drawer.Screen />
</Drawer.Navigator >
```
