### ISSUE TITLE
When navigating, why the navigation bar's height is changing?

### ISSUE THREAD

**Issue by scriptfans** [aksonov/react-native-router-flux#1382]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour

when navigation, the navbar's height should be keep consistent.

### Actual behaviour

![bug](https://cloud.githubusercontent.com/assets/359790/20335840/ea3ce98c-ac00-11e6-9042-e8962f3c2ff9.gif)

![0](https://cloud.githubusercontent.com/assets/359790/20335861/f8ee9aac-ac00-11e6-8707-87f62f0ef680.png)

![1](https://cloud.githubusercontent.com/assets/359790/20335870/fe22c994-ac00-11e6-82ad-80cad5742bd9.png)

**Comment by scriptfans** [comment]
It looks like there's a change in position, not a change in height. how to solve this inconsistency? thanks.

**Comment by scriptfans** [comment]
@aksonov

**Comment by imarem** [comment]
Hi @scriptfans 

You've got to solve the problem? Could you share your solution? I have the same problem

**Comment by scriptfans** [comment]
@imarem https://github.com/aksonov/react-native-router-flux/issues/879
