### ISSUE TITLE
how can i close the drawer in designated page?

### ISSUE THREAD

**Issue by wuxushun** [aksonov/react-native-router-flux#1384]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

I used in TAB outer drawer, I hope that in the first TAB used in the first page, other TAB and page are close the drawer, how can i do for this?

**Comment by ddolheguy** [comment]
In the component where you have the drawer do something like this:

```
componentDidMount() {
   Actions.refresh({key: 'drawer', ref: this.refs.navigation});
}
render(){
        const state = this.props.navigationState;
        const children = state.children;
        return (
            <Drawer
                ref="navigation"
                ...
                })}>
                <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </Drawer>
        );
    }

```

Then in your component which you want to close the drawer do this:

```
Navigation.Actions.get('drawer').ref.toggle();
```

Hope this helps :)

**Comment by wuxushun** [comment]
i have the same problem

**Comment by pewh** [comment]
@ddolheguy where is `Navigation` variable come from?
