### ISSUE TITLE
Background Image across multiple scenes

### ISSUE THREAD

**Issue by ssomnoremac** [aksonov/react-native-router-flux#1388]
- react-native-router-flux v3.33.0
- react-native v0.35.0

### Expected behaviour
RNRF allows for background image wrapped scenes as #340 describes and each new scene slides into and over the stationary background.

### Actual behaviour
Previous or "ghost" scene is visible behind the new scene. Both scenes are in view however the previous is offset and semi-transparent.

### Steps to reproduce
see #340.

My work around was to create a blank, empty scene and pass it the nextRoute as a prop to load an in-between scene that is empty

```
export default class Blank extends Component {

    componentWillMount() {
        Actions[this.props.nextScene]()
    }

    render() {
        return (
            <View style={{flex: 1}}/>
        )
    }
}
```
then use like so
```
Actions.blank({nextScene: "myNextScene"})
```
Thoughts?

**Comment by xufang215** [comment]
Is there a better solution?

**Comment by ssomnoremac** [comment]
Yeah, this is not ideal. Could work better I was able to set a new background for other scenes because this background will always render behind any future scene transitions. So far with nested scenes I haven't been able to do this. At least for the first transitions between scenes you'll catch a glimpse of the background image as it is essentially the background image now of the entire app if you wrap the app in it this way.

**Comment by activelogic** [comment]
I am also looking for a solution to this problem!

**Comment by activelogic** [comment]
@ssomnoremac, @xufang215 - I came up with a solution for this by detecting the scene and if it's not the active scene, rendering an empty view. 

To make the current scene object available in my components, I connect the router to redux and catch the ActionConst.FOCUS actions in a reducer that sets the current scene in my redux state as per this guide: https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

**Comment by timmywil** [comment]
I would be happy if I could just disable the fading part of the animation on PUSH, eliminating the transparency that reveals the background.

**Comment by ssomnoremac** [comment]
@activelogic , thanks! That's the solution. A bit of a pain to wrap each component in something like this:

```
if(this.props.routes.scene.sceneKey === "CreateProfile_2"){
   return <SomeComponent/>
}else{
   return <View style={{backgroundColor: "#fff", flex:1}}/>
}
```

but I agree, this definitely is the way to a tackle this problem. This also helps when using a drawer as the scene before the drawer scene will show through on the open/close animation.

**Comment by timmywil** [comment]
Really? I don't think that's the best solution we can come up with...

**Comment by ssomnoremac** [comment]
well, I agree, being able to change the animation on the transition would be best but rendering blank screens when not active is something that would be a lot more useful in the API in my opinion.

**Comment by activelogic** [comment]
It's definitely not the best solution.  It would be better if the fade effect went to 0 opacity entirely.

**Comment by stajics** [comment]
Look at @redbaron76 response in #1202.
I have used that animationStyle function, just changed outputRange in opacity to [1, 1, 0.0].

`
<Router
    scenes={scenes}
    hideNavBar
    getSceneStyle={getTransparentBgSceneStyle}
    animationStyle={animationStyle}
/>
`
