### ISSUE TITLE
Props passed through route remain static

### ISSUE THREAD

**Issue by mkjangid** [aksonov/react-native-router-flux#1389]
Any props passed through scene remain static even if the parent state changes. Imagine a scenario wherein I would like to pass ` internetConnectivity` state from my parent to all the scenes. Whenever the connectivity changes, the state updates and props passed to scenes should be updated as well. Currently this is not working as expected. Copy of issue #167

**Comment by hamidjafari** [comment]
+1 . my problem too . is there any workaround?

**Comment by mkjangid** [comment]
@hamidjafari, I did not wait for the solution. If you still have this issue, you can define functions in top level `<Router>` and those functions can get you whatever you need whenever you want. Do not forget to use `bind`

**Comment by hamidjafari** [comment]
@mkjangid , can you place one example code here ?

**Comment by keyeh** [comment]
I'm having the same issue. @mkjangid a code example would be very helpful!

**Comment by mkjangid** [comment]
Attaching a sample code to get the idea 

```
export default class MyApp extends Component{
    constructor(props) {
        super(props);
            loading:true,
            isConnected:false,
        };
    }

getMainState(){
        return this.state;
    }

<Router getMainState={this.getMainState.bind(this)}>
      <Scene></Scene>
</Router>
}

```
Within every scene, the functions defined at root are accessible as 

`var parentState = this.props.getMainState();`
