### ISSUE TITLE
Not able to pass prop through Actions after upgrade to 3.37.0

### ISSUE THREAD

**Issue by cfs5403** [aksonov/react-native-router-flux#1390]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour
Able to pass prop though Actions.key( props )

### Actual behaviour
Not able to pass prop through Actions after upgrade to 3.37.0, no problem at 3.36.0.

### Steps to reproduce

1.  First I create router for navigation drawer.
`
<Router

          renderLeftButton={ drawerMenuIcon }
          navigationBarStyle={ styles.navBar }
          titleStyle={ styles.navBarTitle }
          leftButtonIconStyle={ styles.leftButtonIconStyle }
          rightButtonTextStyle={ styles.rightButtonTextStyle }>
          <Scene key='root'>
              <Scene
                  key='drawer'
                  open={ false }
                  component={ NavigationDrawer }
                  title='NavigationDrawer'>
                  <Scene
                      initial={ true }
                      key='main'
                      tabs={ true }>
                      <Scene
                          key='home'
                          component={ Home }
                          title='Home' />
                      <Scene
                          key='anotherComponent'
                          component={ AnotherComponent }
                          title='AnotherComponent' />
                      <Scene
                          key='anotherComponent2'
                          component={ AnotherComponent2 }
                          title='AnotherComponent2' />                      
                  </Scene>
              </Scene>
          </Scene>
      </Router>`

2. In the drawer I navigate like this.

` 
_onItemSelect(rowData) {

    closeDrawer();
    switch (rowData) {
      case 'Home':
        Actions.home();
        break;
      case 'Another Component':
        Actions.anotherComponent(myProp: 'hello' );
        break;
      case 'Another Component2':
        Actions.anotherComponent2();
        break;
      case 'Change Password':
      case 'Logout':
    }
`

3. When navigating, the component that suppose to receive props are not receive any props, for example: Actions.anotherComponent(myProp: 'hello' );

4. AnotherComponnent not receiving the passed props.

**Comment by sarovin** [comment]
@cfs5403 `Actions.anotherComponent({ myProp: 'hello' });`

**Comment by cfs5403** [comment]
@sarovin actually my codes are same as your, my mistake previously. But it still did not work, cant pass the props. Thanks.
