### ISSUE TITLE
back_chevron.png goes missing in Release build

### ISSUE THREAD

**Issue by Naoto-Ida** [aksonov/react-native-router-flux#1391]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.34.1
- iOS v10.0.2

### Expected behaviour
**back_chevron.png** should show when our custom action called `Actions.showArticle(id: this.props.node.id)` is called when tapping on a list of articles, transitioning to a screen with the article.

### Actual behaviour
While the **back_chevron.png** shows in `Debug` build, it doesn't show up in `Release` build for iOS. Note that when you tap where the image is expected to be, it behaves the same way; going back to the list of articles.

### Steps to reproduce

1. Run in `Debug` build.
2. Confirm that the **back_chevron.png** is displayed when pushing scene.
3. Run in `Release` build.
4. Confirm that the **back_chevron.png** is not displayed.

````
// ArticleListItem
class ArticleListItem extends Component {
  render() {
    return (
      <TouchableOpacity
        onPress={event => Actions.showArticle({id: this.props.node.id})}
      >
          <Text>Foo</Text>
      </TouchableOpacity>
    )
  }
}

````

````
<Router
  createReducer={reducerCreate}
  wrapBy={RelayRenderer()}
  hideTabBar={true}
>
  <Scene key="modal" component={Modal}>
    <Scene key="root">
      <Scene
        key='showArticle'
        component={ArticleContainer}
        leftButtonIconStyle={{tintColor: '#fff'}}
        queries={{viewer: () => Relay.QL`query { viewer }`}}
      />
      <Scene
        key='showArticles'
        component={ArticleListContainer}
      />
    </Scene>
  </Scene>
</Router>
````

**Comment by Naoto-Ida** [comment]
So suddenly `babelRelayPlugin` starting acting up and could not transpile...
After I made some fixes to remove the error, the arrow is back for some reason.

**Comment by weixingsun** [comment]
@Naoto-Ida I got the same issue.  how did you do that? remove the babelRelayPlugin?

**Comment by Naoto-Ida** [comment]
I just ended up calling `renderBackButton` as a scene argument. Now we have a custom back arrow that always shows.

**Comment by markdaws** [comment]
I'm seeing the same issue in the latest build, the back chevron is displayed in non release builds, but in a release build it is not displayed. I don't see any errors in the build output.
