### ISSUE TITLE
tab bar Icons wont display 

### ISSUE THREAD

**Issue by stefonmarcel** [aksonov/react-native-router-flux#1395]
hello aksonov ,
im trying to display icons in react native router flux tab bar using ```import Icon      from 'react-native-vector-icons/Ionicons';``` but i think theres something that my eye cant catch. I believe i did it right. i keep getting ```required prop name was not specified in 'icon'``` error

``` class TabIcon extends Component { render() {
    var color = this.props.selected ? '#00f240' : '#301c2a';
    return (
      <View style={{flex:1, flexDirection:'column', alignItems:'center', alignSelf:'center', justifyContent: 'center'}}>
      <Icon
            name={this.props.iconName}
            size={18}
            color={this.props.selected ? '#444' :'#AAA'}
         />
                 <Text style={{color: color, fontSize: 12}}>{this.props.title}</Text>
      </View>
    );
  }
}

 <Scene key="homeview" title="Home" icon={TabIcon}>
            <Scene
              key="home"
              component={Home}
              iconName="ion-ios-home-outline"
              title="test"
              initial = {true}
            />
            <Scene
              key="screen1"
              component={screen1}
              title="first screen"
            />
          </Scene>```

thank you

**Comment by sarovin** [comment]
Please ask questions about usage within stackoverflow, not here, with tag
react-native-router-flux, react-native

Il Ven 18 Nov 2016, 21:03 stefonmarcel <notifications@github.com> ha
scritto:

**Comment by lin493369** [comment]
@sarovin I have this problem too.Does any solution to solve this?

**Comment by stefonmarcel** [comment]
@lin493369 hey 
when you use react-native-router-flux
each scene key tab that holds the scenes  needs to call the **Tabicon** variable as displayed below.

<Scene key="bartabpiece" tabs={true} type="reset" duration={0} default="hometest tabBarStyle={{ backgroundColor: '#000000' }}>
        {/* Tab and it's scenes */}
          <Scene key="hometest" /*title="Home"*/ iconName={"home"} icon={**TabIcon**}>
            <Scene key="new page"/>
            <Scene key="new page"/>
          </Scene>
</Scene>
