### ISSUE TITLE
Where is the documentation for DefaultRenderer?

### ISSUE THREAD

**Issue by ldct** [aksonov/react-native-router-flux#1396]
DefaultRender is listed as part of the public API (https://github.com/aksonov/react-native-router-flux/blob/4a399c108201df9e02ff3d960b902a5297fa4d9e/docs/API_CONFIGURATION.md) but I can't find any documentation on it. 

Specifically I want to know why my app seems to break when I put `DefaultRenderer` in a `ScrollView`, and was hoping I could read the documentation for clues.

**Comment by TsuryKnox** [comment]
Also, how do I change the hamburger button on the defaultRenderer?
