### ISSUE TITLE
Drawer layout on some routes

### ISSUE THREAD

**Issue by JonnyBGod** [aksonov/react-native-router-flux#14]
I am trying to implement a drawer menu with this router. The problem is that I do not want to have the drawer for sign in and launch screens and want all other screens to share the same drawers (do not want to apply a new drawer for each route).

Any Idea on how I can implement this?
I have tried using a container but ended up having a vertical split screen with route on top and drawer on bottom.

**Comment by aksonov** [comment]
I think Container is right direction but you should set own custom style on Container 'component'. Could you provide simple github repo with Demo so i could look into.

**Comment by JonnyBGod** [comment]
Will make an example for it. Meanwhile some snippets:

```
<Router>
  <Schema name="default" sceneConfig={Animations.FlatFloatFromRight} openDrawer={() => this.refs.drawer.open()}/>

  <Route name="LaunchScreen" component={LaunchScreen} initial={true} hideNavBar={true} title="Launch"/>
  <Route name="AuthScreen" component={AuthScreen} hideNavBar={true} title="Signin" type="replace"/>

  <Route name="HomeScreen">
    <Container component={Drawer}>
      <Route name="RidesScreen" component={RidesScreen} title="Rides" navBar={RidesNavBar} type="replace"/>
    </Container>
  </Route>

  <Route name="error" component={Error} schema="popup"/>
</Router>
```

```
const DrawerLayout = require('react-native-drawer-layout');

let Drawer = React.createClass({
  render() {
    return (
      <DrawerLayout
        ref='drawer'
        drawerWidth={window.width <= 320 ? (window.width - window.width*.2) : 300}
        renderNavigationView={() => <Menu
          indexNavigator={this.props.indexNavigator}
          changeScene={(name, type) => this.changeScene(name, type)}
          closeDrawer={() => this.refs.drawer.close()} />
        } >

      </DrawerLayout>
    );
  }
});
```

<img width="376" alt="screenshot 2015-10-07 16 58 43" src="https://cloud.githubusercontent.com/assets/405206/10343222/ba3efc7e-6d14-11e5-8c1d-30124d0a8fee.png">

**Comment by aksonov** [comment]
Closing it for now, will re-open when will have demo
