### ISSUE TITLE
Anyone else get  Invalid name: "@exponent/react-native-navigator" during install?

### ISSUE THREAD

**Issue by zentuit** [aksonov/react-native-router-flux#140]
When I attempt to install react-native-router-flux, I get an error from npm - Invalid name: "@exponent/react-native-navigator"

Before I post thison npm/issues, I thought I'd ask here if anyone else encountered this.

**Comment by aksonov** [comment]
Sorry, i can't reproduce it. Make sure you installed latest iojs and all steps required by React Native install

**Comment by alex3t** [comment]
for me solved by updating to last NPM version from 3.3.12
