### ISSUE TITLE
Modal dispatch actions but not showing other scene

### ISSUE THREAD

**Issue by jomaint** [aksonov/react-native-router-flux#1400]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.35.0

### Expected behaviour
Modal to dispatch action to next scene. 

### Actual behaviour
Action PUSH and FOCUS dispatched but view scene doesn't change. Even the back button stop responding unless i click on it a few times (usually works after once, Action.pop() )
Did a console.log on scene that modal is suppose to transit to, logs at render and constructor successfully. But scene still stuck at modal.

### Steps to reproduce

1. Create scene with modal
2. Transit to Modal scene
3. Trigger to dispatch action to another scene

**Comment by binchik** [comment]
Hi, @jomaint did you figure out how to fix it?
