### ISSUE TITLE
Navigator scene config problem

### ISSUE THREAD

**Issue by rshmiraf** [aksonov/react-native-router-flux#1403]
### Version
- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour

After this code: 
`sceneConfig={Navigator.SceneConfigs.FloatFromBottom}`

### Actual behaviour

my navigator should have other transition. But nothing change:
Here is where i got this: [https://facebook.github.io/react-native/docs/navigator.html](url)

### Screenshot of code

![screen shot 2016-11-21 at 8 26 49 pm](https://cloud.githubusercontent.com/assets/14861637/20497474/91367e16-b029-11e6-9782-eb05b9f9e8d3.png)

**Comment by ddolheguy** [comment]
If you want the animation to come from the bottom up, you can do this:

**Scene Setup:**

```
import { Scene, Actions, Modal } from 'react-native-router-flux';
...

<Scene key="modal" component={Modal} >
   <Scene key="root">

<Scene key="currencySearch" title={'My Popup'} component={MyComponent} direction="vertical" />

   </Scene>
</Scene>
```

Note the ```direction="vertical"``` which will cause the animation from bottom.

**Comment by getnashty** [comment]
+1 on this - @ddolheguy 's solution solves from the bottom - but doesn't address the issue that using sceneConfig seems to do nothing...

**Comment by sainthardaway** [comment]
@getnashty  and @rshmiraf i guess, you need to define Schema itself
` <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromTop}/>
<Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>`

**Comment by getnashty** [comment]
@sainthardaway - I'm not able to make this work. it seems as though its completely ignored.

**Comment by ngocdb** [comment]
Where I put the code with Scene ?
<Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromTop}/> <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
Please add the full code...

I always get the warning: React.createElement type is invalid...
