### ISSUE TITLE
backAndroidHandler/onBackAndroid/onExitApp not triggered on Actions.refresh

### ISSUE THREAD

**Issue by pewh** [aksonov/react-native-router-flux#1405]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.7.0
- react-native v0.37

My case is: if this.state.isValueChanged is false, show save confirmation dialog if press back.

```
componentWillMount() {
  Actions.refresh({
      title: 'Kontak Restoran',
      renderRightButton: this.renderUpdateButton,
      backAndroidHandler: this.handleBackAndroidHandler,
      onBackAndroid: this.handleBackAndroidHandler,
      onExitApp: this.handleBackAndroidHandler,
  })
}

handleBackAndroidHandler =  () => {
    console.log('foo')
}

renderUpdateButton = () => {
  console.log('bar')
}
```

### Expected behaviour
on page loaded, show `foo` in console.
when back android button pressed, show `bar` in console.

### Actual behaviour
on page loaded, show `foo` in console.
when back android button pressed, console didn't show `bar`
I already test with debugger, and function not triggered.

**Comment by pavloko** [comment]
I didn't know about this functionality. In my app, I'm currently using

```
BackAndroid.addEventListener('hardwareBackPress', () => Actions.pop());
```

**Comment by pewh** [comment]
Yes, I'm using `hardwareBackPress` event too. But it's not enough because my case is to trigger something before back button in device **or navbar** is pressed .

**Comment by shiqian123** [comment]
me too。 use onBackAndroid  cannot refresh 。 so  when  action.pop need refesh I use   RCTDeviceEventEmitter.emit()
  componentWillUnmount() {
   if(device.android){
     RCTDeviceEventEmitter.emit('update'Id)
   }
  }
