### ISSUE TITLE
Modal as overlay(transparent bg) not as new screen

### ISSUE THREAD

**Issue by DiegoGallegos4** [aksonov/react-native-router-flux#1411]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.25.0

### Expected behaviour

I would like to have an option to add a new screen to the stack when showing a modal or to show it as an overlay where I can see the back screen. 

This behavior: 

![image](https://cloud.githubusercontent.com/assets/5933437/20539587/279857da-b0bb-11e6-83ca-c5070c928d6e.png)

Instead of this, whole new screen behavior.

![image](https://cloud.githubusercontent.com/assets/5933437/20539625/4e2b137e-b0bb-11e6-8d95-d38db32f4b0b.png)

**Comment by jeannei** [comment]
@DiegoGallegos4 any updates on this? I'm looking to do the same.

**Comment by DiegoGallegos4** [comment]
@jeannei I used react-modalbox(or any other modal) and redux. I did not find any other way and I think there is no other way to do it feasibly. You would like to have a flag in the state (e.g modalState) and whenever you click to open the modal you would dispatch an action to change the state.

**Comment by proProbe** [comment]
Im looking for something similar. is this even possible?

**Comment by Mbompr** [comment]
Hi, I have managed to do so by modifying `Modal` component from RNRF. In my case I want to have a `SpinningView` that show up depending on my redux state.
```
export default function SpinningViewModal (props) {
  const children = props.navigationState.children;
  const state = children[0];

  return (
    <View style={{ flex: 1 }}>
      <DefaultRenderer
        navigationState={state}
        key={state.key}
        {...state}
        onNavigate={props.onNavigate}
      />
      <SpinningView/>
    </View>
  );
}
``` 
It's definitely a shortcut and not as complete as the original Modal but it is sufficient in my case.

**Comment by vivaxy** [comment]
@Mbompr How did you modify `Modal`? By passing a props?

**Comment by Mbompr** [comment]
By creating a file called Modal.js in my app directory and importing Modal from there instead of importing it from RNRF
