### ISSUE TITLE
Set Dynamic tabBarStyle

### ISSUE THREAD

**Issue by Rayji96** [aksonov/react-native-router-flux#1412]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.37.0

### Expected behaviour
I expected the tabBar to re-render as I pass it a new tabBarStyle

### Actual behaviour
tabBar remained the same

### Steps to reproduce

1. Create a tabBar scene:
```
<Scene key="NAV" tabs={true} tabBarStyle={[view.background_secondary, {backgroundColor: color(this.props.bootstrap).secondary}]} type={ActionConst.RESET}>
```
2. Pass in new props through the color function.
3. Expect a change.

**Comment by Rayji96** [comment]
For those who are curious, you can pass in a custom tabBar as a component={} in the tab={true} scene.

**Comment by pocesar** [comment]
@Rayji96 how did you do this? I'm trying to create a custom tabbar, but the component won't receive the computedProps from the parent (hideNavBar, hideTabBar, isActive)
