### ISSUE TITLE
Update testing and CI

### ISSUE THREAD

**Issue by charpeni** [aksonov/react-native-router-flux#1414]
- [x] Update Jest
- [x] Fix Jest Snapshots
- [ ] Update Eslint and Airbnb rules
- [ ] Update Example project to the latest version of React Native
- [x] Update node version in CircleCI
- [ ] Configure parallelism to test with LTS and latest node version.
- [x] Add yarn
- [ ] Use yarn instead of npm in CI
- [ ] Build Android example project on CircleCI

Any help is welcome. :rocket:

**Comment by MechanicKim** [comment]
I already have a PR. And, I updated react packages to fix Jest Snapshots.
Could you review my PR #1406 ?

**Comment by charpeni** [comment]
Task list has been updated.

@MechanicKim Jest Snapshots has been fixed, but I'll review your PR.

**Comment by MechanicKim** [comment]
About Update Eslint and Airbnb rules,
Dose this work include fixing style of all source codes or just updating the package?

**Comment by charpeni** [comment]
Update dependencies and fix errors as you did in #1425, thank you btw.

**Comment by Swordsman-Inaction** [comment]
My PR #1451 got an error

`ENOENT: no such file or directory, stat '/home/ubuntu/react-native-router-flux/Example/node_modules/react-native/jest/setup.js'`

Any idea? @charpeni

**Comment by MechanicKim** [comment]
@Swordsman-Inaction 
If you use react-native < 0.38, jest version should be 17.0.3.
Maybe you should fix jest preset.
"jest-react-native" ---> "react-native"

**Comment by Swordsman-Inaction** [comment]
@MechanicKim 
The `Example`'s `pakcage.json` file `https://github.com/aksonov/react-native-router-flux/blob/master/Example/package.json`

It does use `"react-native": "0.30.0"` and `"jest-react-native": "^17.0.3"`
Should I just delete `"jest-react-native": "^17.0.3"`?

And my PR doesn't change the Example, does it mean that the `Example`'s `pakcage.json` is just wrong at beginning.
