### ISSUE TITLE
default custom renderRightButton

### ISSUE THREAD

**Issue by robbue** [aksonov/react-native-router-flux#1417]
I want to keep the right button as it is today, but I want to add a element to it. How can I use the default one as a template for a new custom right button? 

### Version
- react-native-router-flux v3.37.0
- react-native v0.37.0

**Comment by sarovin** [comment]
@robbue It's not possible. The button is an image and you can set only the source with backButtonImage props.
I don't like this solution and i want pass an element like you (i use a web font icon, not image).
But i don't have time for now, can you create a PR for this??
