### ISSUE TITLE
backandroid jump between tabs

### ISSUE THREAD

**Issue by proProbe** [aksonov/react-native-router-flux#1421]
Hello! Thanks for the great lib!

Just wanted to ask if there is a way to actually jump between the tabs on backandroid. With that I mean this:
The history of going through tabs
A -> B -> C -> A
Should give on press backandroid
A -> C -> B -> A

**Comment by rigobcastro** [comment]
@proProbe I want the same, any solution? Thanks!

**Comment by proProbe** [comment]
unfortunately, I havent found any solutions. Would love to hear if anyone has one though!
