### ISSUE TITLE
How can I keep panHandlers on iOS but not on Android

### ISSUE THREAD

**Issue by bawn** [aksonov/react-native-router-flux#1426]
### Version

- react-native-router-flux 3.30.1
- react-native v0.3.8

I know use `panHandlers={null}` can forbid swiping back for a scene, but how can I keep panHandlers on iOS but not on Android.

**Comment by Naoto-Ida** [comment]
+1

**Comment by Naoto-Ida** [comment]
@bawn I just did this for now:

```js
const platformPanHandlers = Platform.OS === 'ios' ? null : {'panHandlers': null}
return (
  //blah blah
  <Scene
    key='something'
    platformPanHandlers
  />
)
```

**Comment by kesjien** [comment]
You can use this instead panHandlers={ ( Platform.OS === 'ios' ) ? undefined : null }
And it will get the default handlers for ios.

  if (typeof(panHandlers) === 'undefined') {
      panHandlers = getPanHandlers ?
        getPanHandlers(props, direction) :
        this.getPanHandlers(direction, props);
    }

**Comment by bawn** [comment]
@kesjien Thanks
