### ISSUE TITLE
duration ignored when passed to Action

### ISSUE THREAD

**Issue by gorangajic** [aksonov/react-native-router-flux#1428]
Is it possible to change duration after Scene is defined? 
For example, I want to set `push` transition to not have animation and pop to have
I have tried to pass duration to Actions.pop and that does not work

```jsx
// Scene is defined something like this
 <Scene
    type={ActionConst.PUSH}
    direction="vertical"
    duration={0}
    key="article"
    component={ArticlePage}
    panHandlers={null}
/>

Actions.pop({ duration: 1000 }})
```

is something like that possible
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.36.0

### Expected behaviour
When provided `duration` to `Actions.pop` it should use that duration no the one defined.

### Actual behaviour
`duration` is ignored when passed to the `Actions.pop`

**Comment by unadlib** [comment]
+1
