### ISSUE TITLE
TabBar directly under NavBar

### ISSUE THREAD

**Issue by BigPun86** [aksonov/react-native-router-flux#143]
Is it possible to put the TabBar directly under the NavigationBar? I tried using header instead of footer, which didn´t work....
   
       <Router....>
               <Schema name="tab" type="switch" icon={TabIcon}/>
                <Route name="tabbar">
                    <Router header/footer={TabBar} hideNavBar={false}  tabBarStyle={{borderTopColor:'#00bb00',borderTopWidth:1,backgroundColor:'white'}}>
                        <Route name="tab1" schema="tab" title="Tab #1" component={NetworkRoute}/>
                        <Route name="tab2" schema="tab" title="Tab #2" component={NewsRoute}/>
                        <Route name="tab3" schema="tab" title="Tab #3" component={MoreRoute}/>
                    </Router>
                </Route>
         </Router....>

**Comment by aksonov** [comment]
Just use proper RN style for 'tabBarStyle' to set it it at the top.

**Comment by aksonov** [comment]
No issue here, CSS layout question, so I'm closing it.

**Comment by kadosh1000** [comment]
still wondering what would be the right style for it

**Comment by aksonov** [comment]
Could you do it without this component? If so, just split it to header and content (i.e. component) and pass header and component to Route, it must work, check sources, there is no magic.
