### ISSUE TITLE
How to flip back button in RTL Layout

### ISSUE THREAD

**Issue by ahmedNY** [aksonov/react-native-router-flux#1430]
- react-native-router-flux v3.37.0
- react-native v0.37.0

In right to left layout , back button should point to right direction,  like this ➡

can i replace back button icon?

**Comment by Sunhat** [comment]
Yes. Read the documentation.

**Comment by ahmedNY** [comment]
Thanks @Sunhat,
it will be nice, if the back button was flipped on RTL layout by default, since react-native support RTL on versions  >=0.33,  instead of adding backButtonImage attribute for each Scene

**Comment by philjoseph** [comment]
Moreover, it will be great if the layout of within the bar will change in RTL so the back button will appear on the right, and will go rightward as mentionned by @ahmedNY
