### ISSUE TITLE
Props not passed from tab scene to sibling scene

### ISSUE THREAD

**Issue by ssomnoremac** [aksonov/react-native-router-flux#1434]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36
- react-native v0.37

### Expected behaviour
object props are passed to scene like so 
```
Actions.myScene({foo: {bar:"baz"}})
```
### Actual behaviour
the props are not showing up in myScene

there is another issue that was closed #1390 for no reason. There were many breaking changes in RN36,37. Anyone else seeing their entire app break suddenly?

**Comment by sarovin** [comment]
Can you show an example?

**Comment by ssomnoremac** [comment]
<Scene key="worker" getSceneStyle={getSceneStyle} component={DrawerComponent} open={false}>
         <Scene key="workerTabs" getSceneStyle={getSceneStyle} tabBarStyle={tabBarStyle} tabs={true} >
               <Scene key='workerHome' component={ WorkerHome } title="Home" />
               <Scene key='workerShiftDetails' component={ WorkerShiftDetails } title="Home" hideTabBar={true} />

In `WorkerHome` navigating like so `Actions.WorkerShiftDetails({foo:"Bar"})

Mind you I am using both Drawer and Tabs and all of this is a subScene so perhaps one of those 3 things could be to blame?

**Comment by sarovin** [comment]
If you don't use drawer or tabs, it works?

**Comment by ssomnoremac** [comment]
Yeah, it's working in other parts of the app. And I tried to pass just a string. No luck, just nothing is passed along in the props. Using Redux `mapStateToProps` in the next scene or not, nothing gets through.

**Comment by sarovin** [comment]
Sorry @ssomnoremac, i do not know...I can try to investigate when I have time.

**Comment by DonnieWest** [comment]
Ran into this issue at work. Unsure if #1472 is the best solution, but it works for us

**Comment by MechanicKim** [comment]
I tested passing value(props) on Example project.
I have no problem.
I pass the value like this.
`{data:"Custom data", title:"Custom title", child: {data:"Child data"}}`
In next page, I can get value from this.props.child.data.

**Comment by DonnieWest** [comment]
@MechanicKim since I can't share my at work project, I'll try to get a minimal project setup that demonstrates the bug based on the example project.

The props only don't pass when the parent scene has tabs set and you are passing the props to a sibling like in the example from @ssomnoremac

**Comment by warrenronsiek** [comment]
Verified, I have the same problem on a personal project. I can solve the problem if I switch the scenes around, but it doesn't work as I would have expected.

Here props are undefined when passing from `someTab` to `Modal` via `Actions.Modal({someProp: theProp})`:
```
<Scene key="Scene" tabs={true}>
    <Scene key="someTab" component={SomeTab} title="SomeTab" icon={TabIcon}/>
    <Scene key="Modal" component={Modal} title="Modal" hideNavBar direction="vertical"/>
</Scene>
```

Here props come in as expected. 
```
<Scene key="Scene" tabs={true}>
    <Scene key="someTab" component={SomeTab} title="Requests" icon={TabIcon}/>
</Scene>
<Scene key="Modal" component={Modal} title="Modal" hideNavBar direction="vertical"/>
```

**Comment by MechanicKim** [comment]
Yes! I found the problem in 'Tab'.

**Comment by DonnieWest** [comment]
@MechanicKim does #1472 fix it for you?

**Comment by danclay91** [comment]
@DonnieWest it fixed it for me, thanks a bunch!

**Comment by blaketarter** [comment]
Since it seems like #1472 fixes this issue is there any chance we can get it merged in?

**Comment by DonnieWest** [comment]
@sarovin @MechanicKim is there something I'm doing wrong that I can fix to get #1472 merged in?

**Comment by MechanicKim** [comment]
@DonnieWest  I have no objection about this fix.

**Comment by anuj002** [comment]
Yes! I found the problem in 'Tab'.
Tabs are 'wrapped' by default - i.e. all children are wrapped by Stack with own nav bar. You may disable wrapping by using wrap={false} for Tabs and check passing props again.

<Scene key="Scene" tabs={true} wrap={false}>
    <Scene key="someTab" component={SomeTab} title="SomeTab" icon={TabIcon}/>
    <Scene key="Modal" component={Modal} title="Modal" hideNavBar direction="vertical"/>
</Scene>

Here props are find when passing from someTab to Modal via Actions.Modal({someProp: theProp})
