### ISSUE TITLE
Push component from a function

### ISSUE THREAD

**Issue by sohelsd** [aksonov/react-native-router-flux#144]
I am new to RN and trying to push a Login component programmatically if user session does not exists. Actions.login does not work when called within a function but does on Button onPress. Any ideas on how to achieve this?

```javascript
var Launch = React.createClass( {
    getInitialState(){
        console.log('Launch hit');
        Actions.login(this); //this does not work!!!
        return {};
    },
    render(){
        return (
            <View style={styles.container}>
                <Text>Launch page</Text>
                <Button onPress={Actions.login}>Go to Register page</Button>
            </View>
        );
    }
});
```

**Comment by aksonov** [comment]
Use setTimeout(()=>Actions.login() instead. Your code doesn't work because Actions.login doesn't exist during getInitialState phase.

**Comment by Daniel-ccx** [comment]
componentDidMount/componentWillMount will work fine,try this
