### ISSUE TITLE
How to create a global component like message or loading

### ISSUE THREAD

**Issue by sirgalleto** [aksonov/react-native-router-flux#1443]
### Version
- react-native-router-flux v3.36.0

### Expected behaviour
I need to create a global component to manage UI things like internal notifications, messages and loading screens, for that I put the router inside a `<View>` and then create the global interactions.

### Actual behaviour
When I put the router inside any component the UI breaks and my way to create my globals components is create a custom `ViewContainer` with the component that I need and register the global referente in the componentDidMount, but now when I go to any route and get back, the last route is not unmounted and I lose a global reference 😅 

What's the best way to create a global component like that?

**Comment by grundmanise** [comment]
+1
I also wanted to create a global [`<Modal />` ](https://github.com/maxs15/react-native-modalbox ) component, but I failed...

**Comment by wytheme** [comment]
I think i have done that, but this is not the best way , hope there comes a better way.

my purpose : a global loading modal overlay on the scenes

now is the way:

1. use a custom `fetching` state  
2. use a `<Drawer>` as the overlay mask
3. the `<LoadingContent />` used for the loading
4. when open equal false , return `<DefaultRenderer />` directly
5. `tweenDuration={0}`

```
  componentWillReceiveProps(nextProps) {
    //TODO: hack
    const state = this.props.navigationState

    if (this.state.fetching != nextProps.fetching) {
      this.setState({
        fetching: nextProps.fetching
      })
      nextProps.fetching ?
        NavigationActions.refresh({key: state.key, open: true}) :
        NavigationActions.refresh({key: state.key, open: false})
    }
  }

  render() {
    const state = this.props.navigationState
    const children = state.children
    //TODO: hack
    if (!state.open) {
      return <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate}/>
    }
    return (
      <Drawer
        ref='navigation'
        type='overlay'
        open={state.open}
        onOpen={() => NavigationActions.refresh({key: state.key, open: true})}
        onClose={() => NavigationActions.refresh({key: state.key, open: false})}
        content={<LoadingContent />}
        styles={Styles}
        tapToClose
        openDrawerOffset={0}
        panCloseMask={0}
        negotiatePan
        tweenDuration={0}
        tweenHandler={(ratio) => ({
          main: {opacity: Math.max(0.54, 1 - ratio)}
        })}
      >
        <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate}/>
      </Drawer>
    )
  }
```

Hope this helps

**Comment by sirgalleto** [comment]
@wytheme looks really nice, so how do you put the Drawer into the scenes tree?

**Comment by wytheme** [comment]
@sirgalleto  sorry to reply so late
 
```
return (
      <Router>
        <Scene key='drawer' component={NavigationDrawer} open={false}>
          <Scene key='drawerChildrenWrapper' navigationBarStyle={Styles.navBar} titleStyle={Styles.title}
                 leftButtonIconStyle={Styles.leftButton} rightButtonTextStyle={Styles.rightButton}>
            <Scene initial key='login' component={LoginScreen} title='Login' hideNavBar/>
          </Scene>
        </Scene>
      </Router>
```

but the solution got a problem, router component will mount each time.
