### ISSUE TITLE
Collapsing drawer when navigating away?

### ISSUE THREAD

**Issue by wrelll** [aksonov/react-native-router-flux#1445]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.35.0

### Expected behaviour
This isn't a bug per se, at least I don't think it is. I'm just trying to figure out how I can collapse my drawer when navigating to a different scene. I'm using `Actions.refresh` to collapse it, i.e. `Actions.refresh({key: 'drawer', open: value => !value})` to toggle its state. When I press an item I want to collapse the drawer and navigate to the associated scene, so I would expect
```
Actions.refresh({key: this.props.navigationState.key, open: false})

Actions.ROUTE_NAME()
```
to work, but it only seems to do the latter, leaving the drawer expanded, as if `Actions.refresh({key: this.props.navigationState.key, open: false})` had never been called. If I switch the two calls, the opposite happens. The drawer is collapsed, but it never navigates to the new scene, as if `Actions.ROUTE_NAME()` had never been called.

So this does make some sense to me, hence why this isn't a bug report. I just want to know how I can update the scene state AND navigate to a different scene.

**Comment by mauricius** [comment]
Same problem here. By now I solved it by using `setTimeout` on the navigation call, but I'm aware that this is not the way to go.

```javascript
Actions.refresh({key: this.props.navigationState.key, open: false});

setTimeout(function() {
    Actions.ROUTE();
}, 10)
```

**Comment by ALawliet** [comment]
The best way I've found to do this: https://github.com/aksonov/react-native-router-flux/issues/1227

Basically get the drawer's `.close()` into your `SideMenu` component and use that instead of `Actions.refresh({ key: 'asdf', open: false })`.

Pissed me off for a long time as well. Now I love my drawer. 👍
