### ISSUE TITLE
Nested tabs

### ISSUE THREAD

**Issue by xnog** [aksonov/react-native-router-flux#1452]
### Version
Tell us which versions you are using: 

- react-native-router-flux "^3.37.0"
- react-native "^4.4.6"

### Expected behaviour

Is it possible to make nested tabs? one in the bottom and, when i click the first link for the first tab, it show another tabbar in the top.

### Steps to reproduce

1.
2.
3.

**Comment by euandrei** [comment]
Hi, any news on it ? I am looking at it to...

**Comment by netsmertia** [comment]
I need the same functionality with structure like
```
Tab 1 (title = "STARS")
Tab 2 (title = "REQUESTS")
       |_ Tab 2.1 (Under same title)
       |_ Tab 2.2 (under same title)
       |_ Tab 2.3 (under same title)
Tab 3 (title = "Settigns")
```
I am about to do the same with React-Navigation and result is satisfactory but I want to know is it possible to do the same with RNRF. 

When I put tab inside another tab scene, the inner tabs are shown but not clickable and  title bar is not shown (I need "REQUESTS" with all nested tabs).

**Comment by roots-ai** [comment]
Any updates here?
