### ISSUE TITLE
how can  refresh parent component when child component is poped 

### ISSUE THREAD

**Issue by ScorpiusZ** [aksonov/react-native-router-flux#1458]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.34.1

### Expected behaviour

how can  refresh parent component when child component is poped 

I tried to use onBack func in a scene 
but i got an error like 
![image](https://cloud.githubusercontent.com/assets/5945675/20950993/24ef40e4-bc5e-11e6-837a-12b51c8889a9.png)

My code is like
`
            <Scene key="msg" clone hideTabBar title="" component={Msg}
              onBack = { () => Actions.pop({refresh: true})}
               />
`

**Comment by drewwells** [comment]
the API mentions refresh: {propstoset} but these props are not set or present in the componentWillReceiveProps(nextProps) function

**Comment by JeroenNelen** [comment]
More or less related: we are also encountering issues with refreshing a page, is there anyone that knows if there is any lifecycle that is triggered when landing on a page again?
Situation: we want an action to be executed every time a user views the page, no matter if it is via redirect or via push or pop or replace... we can't seem to find out how to do this. Any suggestions?

**Comment by ScorpiusZ** [comment]
@JeroenNelen  Yes, i just tring to find a callback like android **onResume**/**onPause**
Or ,if there's any other solution to do this..

**Comment by andrispraulitis** [comment]
I assume "msg" is not the scene you want to refresh. Have you tried Actions.pop({refresh: {key: "SCENE_KEY_TO_REFRESH"})} ???

**Comment by MattyK14** [comment]
Any luck with this issue? Also looking for a solution.

**Comment by NightFarmer** [comment]
Any luck with this issue? Also looking for a solution.

**Comment by Symous** [comment]
+1.

**Comment by mikaelrosquist** [comment]
+1

**Comment by abdulmalik97** [comment]
You can render the Component by using redux and its reducers, change the state of one of the parameters and it automatically renders the component after we pop out of the child screen.
