### ISSUE TITLE
barButtonIconStyle, titleStyle, navigationBarStyle, sceneStyle ignored in Route that is inside nested Router

### ISSUE THREAD

**Issue by herby** [aksonov/react-native-router-flux#146]

**Comment by aksonov** [comment]
Please give detail description and example code. These properties for Router, not Route.

**Comment by herby** [comment]
We used it fine inside `Route`s, not inside `Router`.

**Comment by herby** [comment]
This manifest itself in 1.x. Trying if 2.x will show something better.

**Comment by aksonov** [comment]
There was breaking changes introduced within 1.x and 2.x versions. So please create issues only for latest versions.

**Comment by herby** [comment]
Same for 2.x, styles are ignored in `Route`.

**Comment by aksonov** [comment]
Sure, because it is not for Route. Again: API (syntax) was changed, no need to create issues related to old version syntax incompatibility...

**Comment by herby** [comment]
Was it changed from Route to Router in 1.x -> 2.x transition (eg. it was meant for Route in 1.x)?

**Comment by aksonov** [comment]
Each major version update introduces API changes.

**Comment by herby** [comment]
Eh... that was not what I asked.

**Comment by herby** [comment]
I would like to know if those style props were actually meant for Route in 1.x, so we did our code right when we used 1.x, and 1.x -> 2.x was the time when they were moved to Router.

**Comment by herby** [comment]
So that when moving to 2.x, it is supposed to take styles used inside Route and move them into Router; or we just did it wrong from beginning and it just manifests now...

**Comment by aksonov** [comment]
It is not only change. Now the component uses exNavigator component for navigation

**Comment by aksonov** [comment]
There is small probability that recent changes broke something, please try version 2.0.8 for example.

**Comment by herby** [comment]
Ad "It is not only change. Now the component uses exNavigator component for navigation": You _always_ used exNavigator for navigation, didn't you?

**Comment by aksonov** [comment]
0.3.* version didn't use it, i didn't know what old version you used before.

**Comment by herby** [comment]
I did not start that early, so it was exNavigator as far as I can remember.

**Comment by aksonov** [comment]
Changes should be minimal between 1.x and 2.x, please try 2.0.8

**Comment by herby** [comment]
Ad "There is small probability that recent changes broke something, please try version 2.0.8 for example.": I don't know if anything is actually broken in this issue. I need to get an answer to my question: "Were navigationBarStyle etc. meant to be used in Route in 1.x and this was changed in 1.x -> 2.x transition so they are now meant to be used in Router?".

**Comment by herby** [comment]
If it was so (1.x way was "put xxxStyle in Route", 2.x is "put xxxStyle in Router"), then this is non-issue. But I still did not hear from you whether it is yes or no.

**Comment by herby** [comment]
@aksonov Maybe I solved the mystery. One of the `Route`s with style props, the one that appeared first in chronological order, had `wrapRouter={true}`. Could it be so that both 1.x and 2.x should actually use `xxxStyle` props in `Router` but b/c of `wrapRouter` in was actually inherited by wrapped `Router` from `Route`'s props?

**Comment by aksonov** [comment]
Yes, it could be.
