### ISSUE TITLE
White lines flickering around edges during transitions

### ISSUE THREAD

**Issue by dwilt** [aksonov/react-native-router-flux#1460]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour
There would be no white lines flickering.

### Actual behaviour
I'm aware of this as being an issue in other places ([here](https://github.com/wix/react-native-navigation/issues/14) and [here](https://github.com/facebook/react-native/issues/3375)) however all of the solutions are about styling the `Navigator` component which is something that isn't exposed with this plugin. I haven't been able to find anything specific to `react-native-router-flux` that applies a solution. I saw someone had made a [commit](https://github.com/lananelson/react-native-router-flux/commit/66afc4885036a31d1645319178626221ea7eba82#diff-07ab94a626d050c4a73fb7272713b477) on a fork which looks similar to the solutions I've read about elsewhere but didn't know if it had actually made it back into the build.

See this video for an example: https://www.dropbox.com/s/08vxhuka1svn10o/white-flickering-during-transitions.mov?dl=0

### Steps to reproduce
1. Create an app with black backgrounds
2.Transition between scenes and notice the edges

**Comment by timkendall** [comment]
I've been running into this too - super annoying. Going to see if I can come up with a decent solution.

**Comment by erikuix** [comment]
I noticed these as well, but only on the iOS emulator. After building to an actual device, it didn't seem to be an issue.

**Comment by timkendall** [comment]
I still am seeing it on real devices unfortunately.

**Comment by timkendall** [comment]
Alright so it looks like if we simply add a transparent background to the `NavigationCard` component the white lines go away! 

Example:
```
 <NavigationCard
      {...props}
      key={`card_${key}`}
      style={[animationStyle, style, { backgroundColor: 'transparent' }]}
      panHandlers={panHandlers}
      renderScene={this.renderScene}
    />
```

Source:
https://github.com/aksonov/react-native-router-flux/blob/master/src/DefaultRenderer.js#L253

**Comment by dwilt** [comment]
@timkendall thanks for working on this! Want to make a PR?

**Comment by timkendall** [comment]
@dwilt doing it now!

**Comment by Dineshchitta** [comment]
@timkendall  Even though I set background color as transparent still flickering occurs

**Comment by bunmiedee** [comment]
const sceneConfig = {
  cardStyle: {
    backgroundColor: 'transparent'
  }
}

<Scene key="root" {...sceneConfig}>

This worked for me for v4
