### ISSUE TITLE
Console "Key foo is already defined!" when Android device is rotated

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#1461]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.33.1

### Expected behaviour
No error message

### Actual behaviour
Every time I rotate the device I see the error message in the log "Key foo is already defined!" repeated 12 times for each different scene "foo". 

I'm not sure if this is actually a problem or expected behaviour.

It seems that for some reason on Android the entire component tree is unmounted and remounted every time the device is rotated, and I think I read somewhere that this somewhat surprising behaviour is expected. So when the tree is remounted, should we expect these error messages?

### Steps to reproduce

1. Turn on screen rotation on the device (allow it to rotate)
2. Run `react-native log-android`
3. Rotate the device, observe printout.

**Comment by chetstone** [comment]
This was happening because of https://github.com/facebook/react-native/issues/2716#issuecomment-265844514. Adding the missing line in my AndroidManifest.xml fixed the problem.

**Comment by JohnTree** [comment]
I have the same issue.but make no sense
