### ISSUE TITLE
Navbar custom wrapper proposal

### ISSUE THREAD

**Issue by almirfilho** [aksonov/react-native-router-flux#1462]
Hello,

I think it would be nice to have a way to wrap the default navbar contents with a custom component.
Currently I'd like to use the blur features of [react-native-blur](https://github.com/react-native-community/react-native-blur) to have nicely blurred navbars (like iOS' system apps).

The thing is, it's not a style issue that we can resolve just with `navigationBarStyle` prop configuration, in that case I need to use a custom View component (`<BlurView>`) to wrap the navbar contents.

Looking at the [NavBar render() method](https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L501-L505), the same thing already happens if the prop `navigationBarBackgroundImage` is set: the navbar contents are wrapped by an `Image` component.

So, I'd like to include a `navigationBarWrapper` prop (React.Component type) to do this with a custom component.

What do you guys think about this?

**Comment by amhinson** [comment]
I'm looking to do this exact thing. Have you found an alternative to use react-native-blue in the navbar?

**Comment by almirfilho** [comment]
@amhinson I've managed to do it in a, let's say, __dirty, ugly way__.
I've implemented a new component that extends `NavBar` and tweaked its rendering, as follows:

```javascript
import React from 'react';
import { View } from 'react-native';
import { BlurView } from 'react-native-blur';
import { NavBar, Util } from 'react-native-router-flux';
import Style from './style';


export default class CustomNavBar extends NavBar {
  render(){
    // render original navbar
    const renderedNavBar = super.render();
    // check whether the navbar should be displayed or not
    const hide = Util.deepestExplicitValueForKey(this.props, 'hideNavBar');
    // wrap navbar with whatever you want
    return hide ? renderedNavBar : this.wrap(renderedNavBar);
  }
  
  wrap(renderedNavBar){
    return {
      ...renderedNavBar,
      props: {
        ...renderedNavBar.props,
        children:
          <BlurView blurType='xlight'>
            <View style={Style.container}>{renderedNavBar.props.children}</View>
          </BlurView>
      }
    };
  }
}
```

I really wish to remove this awful pice of code in the future. Hope it help.

**Comment by amhinson** [comment]
Hmm can't seem to get the wrap function to render anything. It's just returning an empty navbar. Any thoughts?

**Comment by almirfilho** [comment]
@amhinson yeah you have to reset its position, sorry xD

```javascript
container: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0
}
```
