### ISSUE TITLE
Can't custom the tab bar icon with title?

### ISSUE THREAD

**Issue by lin493369** [aksonov/react-native-router-flux#1463]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.38.0

### Expected behaviour
I want to custom the tab bar icon with title.And I custom the `icon={TabIcon}`,the TabIcon component is like this:

````
return(
        <View style={styles.tabContainer}>
            <Ionicon
                name={this.props.tabIcon}
                size={24}
                color={this.props.selected ? '#444' :'#AAA'}
            />
            <Text style={[{color: this.props.selected ? '#444' :'#AAA'}, styles.tabIcon]}>{this.props.title}</Text>
        </View>
    )
````

### Actual behaviour

Can't navigator in to the tab pages,and show error:'Invalid data message - all must be length: 7'
And the console show the warning cycle：

````
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
`````

what wrong with my code?

I want it work like flow:
![db08070d-e8a7-4893-8b4e-c37030a1dd5d](https://cloud.githubusercontent.com/assets/8255169/21041465/117ceaec-be26-11e6-86de-c43c69df4f92.png)

**Comment by royjkim** [comment]
I'm facing to same problems as yours.
To slove this, we'd like to look details on react-native-router-flux.

Anyway, I'm searching another libraries and basic features to solved this problems.

**Comment by royjkim** [comment]
@lin493369 
I'm not sure it might be help.

1. You add a certain property in `Scene`
2. In the target of `icon` property of `Scene` component, you can differentiate each tabs.
3. So, input the image. I used `Image` component on the sample image.
- I didn't use `react-native-vector-icons`, despite of that's convenient.
- AFAIK combining many 3rd libraries make side effects. 

<img width="324" alt="sample" src="https://cloud.githubusercontent.com/assets/18474494/21918520/772cddc2-d995-11e6-8a2d-a0a534e860ab.png">

**Comment by AndrewHenderson** [comment]
This worked for me to use text instead of an icon.

```jsx
<Scene key="event"
             tabs
             tabBarStyle={styles.tabBarStyle}
             tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle}>
        <Scene
          key="event_tab"
          icon={()=>(<Text>foo</Text>)}
          iconName="md-person"
        >
          <Scene key="event_initial" component={EventFull} title="Event Details" />
    </Scene>
</Scene>
```

**Comment by royjkim** [comment]
@AndrewHenderson 
Thanks!, You really smart !!.

@lin493369
I tried this way(AndrewHenderson said.) with `Ionicons` of `react-native-vector-icons`.
It works.
<img width="332" alt="sample2" src="https://cloud.githubusercontent.com/assets/18474494/21922770/9a368408-d9b3-11e6-9bc3-f98d49e14b52.png">

**Comment by itswaze** [comment]
I cant get this to work, I only get the text, not the icon...

**Comment by newah** [comment]
Not sure if still relevant... Could be something like this + styles
\<View>
    <Icon
      name={'newspaper-o'}
      type={'font-awesome'}
      size={26}
    />
        \<Text>some title\</Text>
  \</View>

**Comment by AndrewHenderson** [comment]
@itswaze – @newah is correct. You have to return a View that has both your Icon and Text components within it.

**Comment by manideepcs024** [comment]
but still default key title comes with icon.how can we hide that.

**Comment by newah** [comment]
@manideepcs024 you provide your own view representation :) to skip title, instead of doing:
<View>
<Icon
name={'newspaper-o'}
type={'font-awesome'}
size={26}
/>
<Text>some title</Text>
</View>

do:
<View>
<Icon
name={'newspaper-o'}
type={'font-awesome'}
size={26}
/>
</View>
