### ISSUE TITLE
warning: "'useNativeDriver' is not supported" when "Back" button is pressed

### ISSUE THREAD

**Issue by jcollum** [aksonov/react-native-router-flux#1464]
### Version
Tell us which versions you are using:

- react-native-router-flux react-native-router-flux@3.37.0 
- react-native v0.39.1

### Expected behaviour

No warning comes up. 

### Actual behaviour

Pressing the back button from a scene causes this warning to fire. Pressing a button in the 2nd scene that fires `Actions.home` etc. will not cause the warning to show up. 

### Steps to reproduce

1. Create an app that is similar to the mini-tutorial. Place a button in the 2nd scene that takes you back to the home screen. 
2. Go to 2nd scene, press "Home" button, no warning happens
3. Go to home, then 2nd scene, then press back button in upper left, the warning is shown.

**Comment by jcollum** [comment]
Fixed with this workaround: https://github.com/facebook/react-native/issues/11094#issuecomment-263240420

**Comment by jonrh** [comment]
I had the same warning when navigation animations triggered. Started happening for me in react-native v0.38 (and v0.40 which I ultimately upgraded to). Thanks @jcollum for the linked workaround, it got me on the right path. What worked for me was the info provided in these 3 comments: [comment 1 by @henrikra](https://github.com/facebook/react-native/issues/11094#issuecomment-263240420), [comment 2 by @knyga](https://github.com/facebook/react-native/issues/11094#issuecomment-264636397), [comment 3 by @uriklar](https://github.com/facebook/react-native/issues/11094#issuecomment-269446575).

For convenience here are these 3 instructions combined:

1. Open up your React Native project in Xcode
2. Open up the project navigator (folder icon from the left)
3. In Finder, locate the file `RCTAnimation.xcodeproj` in `/path_to_your_project/node_modules/react-native/Libraries/NativeAnimation`
4. Drag & drop `RCTAnimation.xcodeproj` from Finder into the Libraries folder in Xcode
5. In Xcode, go to Build Phases -> Link Binary With Libraries -> click the `+` at the bottom. Select `libRCTAnimation.a` under the Workspace folder and click Add.
6. Celan and Run!
