### ISSUE TITLE
duplicated StaticContainer on `flow check`

### ISSUE THREAD

**Issue by Baransu** [aksonov/react-native-router-flux#1465]
### Version
Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.37.0

### Expected behaviour
Passing `flow` check over my app codebase.

### Actual behaviour
Encountering error with `StaticContainer` provider. And this the only plugin using `react-static-container` as dependency.
```
node_modules/react-static-container/lib/StaticContainer.react.js:0
StaticContainer.react. Duplicate module provider
current provider. See: node_modules/react-native/Libraries/Components/StaticContainer.js:0
```

### Steps to reproduce

1. `npm install react-native-router-flux --save `
2. `flow check`

There was similar issue in `react-native-scrollable-tab-view`
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/384
and it looks like we can easy drop `react-static-container` dependency as well as fixing issue with `flow`.

**Comment by yasaichi** [comment]
For my environment, adding `.*/node_modules/react-static-container/.*` to [ignore] in `.flowconfig` could solve the problem :)

**Comment by Venryx** [comment]
I'm getting a similar problem, as seen here: https://github.com/aksonov/react-native-router-flux/issues/1710#issuecomment-306448293

Except in my case, the problem is detected by watchman (as enabled for the react-native packager) rather than flow.
