### ISSUE TITLE
view is not re-rendered when click button too fast

### ISSUE THREAD

**Issue by yoga1982** [aksonov/react-native-router-flux#1466]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.0
- react-native v15.3.2

### Expected behaviour
I have two Scenes
`<Scene key="myInfoView" component={MyInfoView} hideNavBar={true}/>`
`<Scene key="orderListView" component={OrderListView} hideNavBar={true}/>`
in myInfoView there is several buttons to go to orderListView with different filter params.
So in the handler of the buttons I called Actions.orderListView({filter:`<params>`}) to go to the orderListView to show the different order lists, such as wait for paying orders, wait for delivery orders.

### Actual behaviour
Normally it works fine, but i found there is a issue when i do the actions quickly.

### Steps to reproduce
You can reproduce the action like below:
1. go to orderListView with filter id 0.
2. go back to myInfoView.
3. quickly go to orderListView with filter id 1. ( if i wait for 1~2 seconds, everything is fine )
4. orderListView still show with filter id 0.

I also did some research, like add some logs in render method of orderListView.
I found that if i reproduce the actions quickly, it does not render the view, may be it's because when i trigger the action the animation is not finished, right?

**Comment by jeffreymendez1993** [comment]
I am experiencing this same issue right now and trying to find a solution.

**Comment by erikandersson** [comment]
I also experienced this exact issue. Seem that if you set the animation duration manually this issue will not appear.

`<Router duration={400} ...>`

**Comment by ltjsjyyy** [comment]
Yes, I also using the similar solution to fix the issue, but I think it might be not the best solution, the duration may need to be set to the different values in different devices.

**Comment by ltjsjyyy** [comment]
I think another solution is use redux to pass the value

**Comment by eneskaya** [comment]
@ltjsjyyy Actually, when setting the duration like @erikandersson described, the screens render perfectly, even on fast tap. No matter if set to 400 or 0. I didn't test it on Android yet, but on iOS it works as expected.

**Comment by GuillaumeMunsch** [comment]
I'm experiencing the same issue but the `duration` tip doesn't work for me. At the end of the animation it does a very quick back and forth between the original scene and the new one. I tried with 400, 250, 100 and 0. Doesn't change anything

**Comment by willmcneilly** [comment]
This bug has been about for quite a while. Here's another couple of issues describing the same problem:

* https://github.com/aksonov/react-native-router-flux/issues/1266
* https://github.com/aksonov/react-native-router-flux/issues/1282

**Comment by samsonradu** [comment]
+1 Experiencing exactly the same issue as the OP.
Only the NavBar title gets updated, content seems somewhat cached and stays the same. ComponentDidMount is not being called.

**Comment by leoJFeng** [comment]
same issue

**Comment by Clowning** [comment]
Same issue!
