### ISSUE TITLE
Example app transitions are very very slow on iphone 6 sim

### ISSUE THREAD

**Issue by jcollum** [aksonov/react-native-router-flux#1467]
### Version
Tell us which versions you are using: 

$ react-native --version
react-native-cli: 1.2.0
react-native: 0.30.0

$ cat package.json | grep vers
  "version": "3.37.0",

### Expected behaviour

Animations behave normally. 

### Actual behaviour

Clicking on something like "Go to Register Page" takes 4-5 secs to load the page. Clicking back does the same. There are lots of warnings like "You are manually calling a React.Proptypes validation for the 'position' prop on 'Stylesheet fullScreen'" 

### Steps to reproduce

1. Download repo
1. navigate to Example folder
2. Install with NPM (app start fails if you use yarn install) 
3. `react-native run-ios` 
1. Go to a second page by clicking "Go to Tabbar page"

**Comment by luketgriffith** [comment]
i am also experiencing slow animations running it, both on the sim and on my phone (same versions as above).

**Comment by stonepreston** [comment]
make sure you disable slow animations on the simulator by pressing command + T or toggle the slow animation option in the debug menu on the toolbar.
