### ISSUE TITLE
Missing assets React Native Windows (UWP)

### ISSUE THREAD

**Issue by twvdb** [aksonov/react-native-router-flux#1468]
### Version
- react-native-router-flux v3.37.0
- react-native v0.38.1

### Expected behaviour
Since react-native-router-flux does not seem to be platform dependent, I was excited to include this in my UWP (Universal Windows Platform) project. 

### Actual behaviour
However, when running with react-native run-windows the app gives an error of missing assets. 
When adding these assets manually (e.g. back.windows.png) it seems to work fine.

Are you planning to support react-native-router-flux for react-native-windows?
Or more specifically, will these assets be included in a future release?

**Comment by cridenour** [comment]
HI @twvdb! I doubt anyone here has tested with UWP. Are you willing to submit a PR with the correct assets?

**Comment by leesolway** [comment]
Tested this approach, it works. Aswell as adding Windows specific back button images, maybe there should also be some fallback ones for "other" platforms (MacOS, Linux etc).
