### ISSUE TITLE
Error: "Attempted to assign to readonly property" when using back-button in a RouterWithRedux

### ISSUE THREAD

**Issue by chapati23** [aksonov/react-native-router-flux#1469]
### What's wrong?
When connecting the `<Router>` to redux as per the [docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md#step-3) the back-button causes a redscreen of death.

### Version
- react-native-router-flux v3.37.0
- react-native v0.37.0
- Node: v7.2.0
- NPM: 4.0.3

### Expected behaviour
Hitting the back-button should navigate back.

### Actual behaviour
Hitting the back-button causes a redscreen of death (see screenshot below).
Error message: "Attempted to assign to readonly property"

**Steps to reproduce:**
* Create new sample app
* Connect the router to redux as per the [docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md#step-3) (see screenshot below)
* Start the app
* Navigate somewhere
* Hit the back-button (JS needs to be loaded from the bundle to reproduce. When it's being served directly from packager it seems to work fine.)
* Watch this redscreen of death:

![img_0356](https://cloud.githubusercontent.com/assets/117495/21106245/adf3dac0-c08d-11e6-83b5-74e7e6a8c1ec.PNG)

How i connected the router with redux:
![screen shot 2016-12-12 at 17 12 47](https://cloud.githubusercontent.com/assets/117495/21106591/ec4c05da-c08e-11e6-8afd-855cb1bf7742.png)

**Comment by chapati23** [comment]
Narrowed it down: issue only appears when using reactotron and might be caused by circular references in the RNRF state tree. After blacklisting the RNRF actions in reactotron's config the error disappeared.

I also had to blacklist the RNRF actions in redux-logger because it had a significant performance impact, using the back-button was quite laggy.

**Comment by skellock** [comment]
I'm tracking this over on https://github.com/reactotron/reactotron/issues/306 if you want to close this one.  Thanks for reporting this. =)

**Comment by chapati23** [comment]
sure, thanks
