### ISSUE TITLE
Version 2.x breaks navbar styling, text is not justified vertically

### ISSUE THREAD

**Issue by herby** [aksonov/react-native-router-flux#147]
When moved to 2.x and moved naigationvBarStyle, titleStyle and barButtonIconStyle from `Route`s to enclosing `Router`, the styling breaks in vertical justification of the text and icon. The rest (font family, colours etc.) are retained fine.

As for vertical justification, text was centered, now it's on the bottom.

**Comment by herby** [comment]
Styles used:

```js
{
    navBarStyle: {
        backgroundColor: navBackgroundColor,
        borderColor: navBackgroundColor,
        borderWidth: 1,
        opacity: 0.9
    },
    navTitleStyle: {
        color: actionTextColor,
        fontFamily: baseFont,
        fontWeight: 'bold',
        fontSize: 20
    },
    sceneNavBarFix: {
        paddingTop: 56
    },
    backIconStyle: {
        tintColor: actionTextColor,
        position: 'relative',
        top: 3
    }
}
```

**Comment by aksonov** [comment]
Refer to exNavigator for needed styling. The component is wrapper around exNavigator.

**Comment by herby** [comment]
The 1.x version showed thing properly, the 2.x is not. AFAICT, exNavigator itself wasn't bumped. So this should be the issue of r-n-router-flux.

**Comment by herby** [comment]
I just checked. Both 1.x and 2.x used "^0.3.5" as version of exNavigator dependency.

**Comment by aksonov** [comment]
Ok, please post sample repo which works with 1.x but not with 2.x with screenshots. Information you gave is not enough.

**Comment by herby** [comment]
I cannot, it is proprietary. I can send the render methods that use 1.x and 2.x (they must have been changed), using the styles from before.

**Comment by herby** [comment]
```js
import React, {Component, View, Text, Navigator, StyleSheet} from 'react-native';
// ...
import styles from './screens/components/styles'; // the file pasted above
// ...
import strings from './strings';
```

render for 1.x:

```js
    render () {
        return <Router hideNavBar={true} initialRoutes={['login']}>
            <Route name="login" schema="system" component={connect(state => ({
                installation: state.installation
            }))(Login)} next={() => Actions.welcome()}/>
            <Route name="welcome" schema="system" component={connect(state => ({
                tasks: state.backgroundTasks
            }))(WelcomeScreen)} next={appLoadSequence}/>
            <Route name="onboarding" type="replace" component={OnboardingScreen}/>
            <Route name="offerList" type="replace" barButtonIconStyle={styles.backIcon}
                   titleStyle={styles.navTitleStyle}
                   navigationBarStyle={styles.navBarStyle} component={connect(state => ({
                offers: state.offers
            }))(OfferList)} wrapRouter={true} title={strings.offerList} sceneStyle={styles.navBarFix}/>
            <Route name="offer" component={Offer} sceneStyle={styles.navBarFix} barButtonIconStyle={styles.backIcon}/>
            <Route name="webPage" type="replace" component={connect(state => ({
                uc: state.installation.uc
            }))(OfferWebView)}/>
            <Route name="tandcPage" schema="modal" component={TandcScreen} title={strings.tc}/>
            <Route name="error" schema="system" component={ErrorScreen}/>

            <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
            <Schema name="system" type="replace"/>
            <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        </Router>;
    }
```

render for 2.x:
```js
    render () {
        return <Router hideNavBar={true}>
            <Route name="login" initial={true} schema="system" component={connect(state => ({
                installation: state.installation
            }))(Login)} next={() => Actions.welcome()}/>
            <Route name="welcome" schema="system" component={connect(state => ({
                tasks: state.backgroundTasks
            }))(WelcomeScreen)} next={appLoadSequence}/>
            <Route name="onboarding" type="replace" component={OnboardingScreen}/>
            <Route name="offerList" type="replace">
                <Router barButtonIconStyle={styles.backIcon}
                        titleStyle={styles.navTitleStyle}
                        navigationBarStyle={styles.navBarStyle}
                        sceneStyle={styles.navBarFix}>
                    <Route name="list" initial={true} component={connect(state => ({
                        offers: state.offers
                    }))(OfferList)} title={strings.offerList}/>
                    <Route name="offer" component={Offer}/>
                    <Route name="webPage" type="replace" component={connect(state => ({
                        uc: state.installation.uc
                    }))(OfferWebView)}/>
                </Router>
            </Route>
            <Route name="tandcPage" schema="modal" component={TandcScreen} title={strings.tc}/>
            <Route name="error" schema="system" component={ErrorScreen}/>

            <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
            <Schema name="system" type="replace"/>
            <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        </Router>;
    }
```

**Comment by herby** [comment]
offerList, offer and webPage show the navbar nicely, with centered text in 1.x; but in 2.x, it is in the bottom.

**Comment by aksonov** [comment]
Sorry, i can't found problem with it. I need sample repo which will i could execute and see broken layout. Anyway, this component open source, you could try to check where the problem is and submit PR.

**Comment by eranbes** [comment]
this is where the issue is: https://github.com/aksonov/react-native-router-flux/commit/b6188e81605cf3f54d87b687eb72ef8f7fad22bb

**Comment by aksonov** [comment]
Hm, that commit was suggested within exnavigator github to fix issue _with_ android devices...

**Comment by eranbes** [comment]
Here is the render code

        return <Router hideNavBar={false}>
            <Route name="tandcPage"  schema="modal" component={TandcScreen} title={strings.tc}/>
            <Route name="error" schema="system" component={ErrorScreen}/>
            <Schema name="system" type="replace"/>
            <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        </Router>;

See the following:
1.0.9 default style (ignore the back button)
2.1.3 default style (see that the text is at the bottom and it's higher)
2.1.3 when removing navigationStyles={Navigator.NavigationBar.StylesIOS} 

![removing navigationstyles navigator navigationbar stylesios](https://cloud.githubusercontent.com/assets/342114/12591000/a755fe78-c45d-11e5-8031-6a7362525af5.png)
![2 1 3-nostyle](https://cloud.githubusercontent.com/assets/342114/12591001/a75944fc-c45d-11e5-954d-e8a1aa80b2bb.png)
![1 09-nostyle](https://cloud.githubusercontent.com/assets/342114/12591002/a75d93ae-c45d-11e5-9990-3572257c9629.png)

**Comment by aksonov** [comment]
Ok, submit PR if you want to remote it.

**Comment by pewh** [comment]
Removing `Navigator.NavigationBar.StylesIOS` on `navigationStyles={}` is working for me. Please merge this PR.
