### ISSUE TITLE
Custom NavBar doesn't move to top position

### ISSUE THREAD

**Issue by mackeee-orange** [aksonov/react-native-router-flux#1470]
### MyCode
```
// Router
<Scene
  key="feed_page"
  hideNavBar={false}
  hideTabBar={true}
  initial={true}
  component={FeedPage}
  navBar={Header}
  icon={FeedIcon}
  sceneStyle={simula_styles.tab_scene}
/>
```
```
// Header.js
<View style={my_styles.header_container}>
  <View style={my_styles.header_left}>
    <Icon name="view-list"  size={24} color='white'/>
  </View>
  <View style={my_styles.header_center}>
    ---element---
  </View>
  <View style={my_styles.header_right}>
    <Icon name="search"  onPress={this._toggleSearch} size={24} color='white'/>
  </View>
</View>
```
```
// my styles
const my_styles = {
  header_container: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center'
  },
  header_left: {
    width: 50,
    height: 50,
    padding: 13
  },
  header_right: {
    width: 50,
    height: 50,
    padding: 13
  },
  header_center: {
    flex: 4,
    height: 50
  }
}
```

### Expected behaviour
![sample](https://cloud.githubusercontent.com/assets/12053974/21139293/84619cd6-c175-11e6-93b0-a7d68998ee5a.png)

### Actual behaviour
![sample2](https://cloud.githubusercontent.com/assets/12053974/21139297/86b8d800-c175-11e6-96b8-11cdaca42d2a.png)

I tried:
```
header_container: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start'
}
```
but, NavBar doesn't move to top position.
Why my navbar doesn't move to top position??

**Comment by CoteViande** [comment]
Did you try to add `position: 'absolute', top: 0, left: 0, right: 0` to your `header_container`?

**Comment by wangsha** [comment]
suggestion above works (for me).

**Comment by makino18** [comment]
@CoteViande yes, I did it. and NavBar moved to top position.
**But,**
If I choose that method, I have to set NavBar's width with **px** .
I'd like to make NavBar responsive.

**Comment by CoteViande** [comment]
And you may also have to set a margin or padding top on your main content too. That's how I do it so I cannot help on the responsiveness of your navbar. Sorry.

**Comment by AlisonWonderlandApps** [comment]
I tried setting with position: 'absolute' and my navBar disappears :( Any suggestions? 

Router.js
`    <Scene
      key="api"
      hideNavBar={false}
      navBar={HeaderWithIcon}
      navigationBarStyle={{position: 'absolute', top: 0, left: 0, right:0 }}
      component={APITest}
    />`

HeaderWithIcon.js
`import React, {Component} from 'react';
import { View, Image, Text } from 'react-native';
import { menuStyles } from './styles';

class HeaderWithIcon extends Component {

  constructor(props) {
    super(props);
  }

    render() {
      const icon =
        require('../../assets/images/roundLogoPNG/SquirrelStreet_Roundel-Device_pos_RGB.png');

    return (
      <View>
        <View style={[menuStyles.view, this.props.style]}>
          <Image source={icon} style={[menuStyles.icon, this.props.iconStyle]} />
        </View>
      </View>
    );
  }
};

export default HeaderWithIcon;`

styles.js
`import { HEADER } from '../../global/margins';
import { PRIMARY_COLOUR, SHADOW_COLOUR } from '../../global/colours';

export const menuStyles = {
  view: {
    flexDirection: 'row',
    //height: HEADER.height,
    width: null,
    backgroundColor: PRIMARY_COLOUR,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  //  paddingTop: HEADER.padding,
    shadowColor: SHADOW_COLOUR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    position: 'absolute',
    top: HEADER.height,
    left: 0,
    right: 0
  },
  textView: {
    flexDirection: 'row',
    height: HEADER.height,
    width: null,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    paddingTop: HEADER.padding,
    position: 'absolute',
    elevation: 4,
    top: 0,
    left: 0,
    right: 0
  },
  icon: {
    width: HEADER.icon,
    height: HEADER.icon,
    alignSelf: 'center'
  }
};`

**Comment by AlisonWonderlandApps** [comment]
0
down vote
accept
Nevermind... I realise that my HeaderView is wrapped in 2 views and I was not styling the outer one but the inner one. Leaving this here as example code for others if allowed.....

Fix:

In HeaderWithIcon.js
```

    return (
    <View style={[menuStyles.view, this.props.style]}>
      <Image source={icon} style={[menuStyles.icon, this.props.iconStyle]} />
    </View>
);
```

**Comment by Dani93380** [comment]
@mackeee-orange you can use width:'100%'
