### ISSUE TITLE
Transition when touching the title

### ISSUE THREAD

**Issue by hugohow** [aksonov/react-native-router-flux#1471]
Hello,

I wanted to pass call a transition when the user touches the title.
So I've done something like this : 

> <Scene key="conversation" component={Conversation} getTitle={(state) => {return state.title}} titleProps={{onPress:(props) => Actions.conversations() }} />

It works great, but i'm unable to find a way to have some props of the scene in titleProps. (I wanted to pass some params in the action).

Someone have a better way to do it ? I did not want to use renderTitle (I would like to conserve the style and just add a props).

Thanks for this great library !

**Comment by iramlg** [comment]
Had similar trouble those days, ended using renderTitle with the regular styles like this:

renderChatTitle(props) {
        return (
            <TouchableOpacity 
                style={{
                    marginTop: 10,
                    position: 'absolute',
                    top: 5,
                    left: 0,
                    right: 0,
                }}
                onPress={()=> console.log('trigger press')} >
                <Text 
                    style={{
                        textAlign: 'center',
                        color: '#FFFFFF',
                        fontSize: 18,
                        width: 180,
                        alignSelf: 'center'
                    }}
                    lineBreakMode="tail"
                    numberOfLines={1}>
                    {props.title}
                </Text>
            </TouchableOpacity>
        )
    }

Curious to know if there is another way!
