### ISSUE TITLE
Pushing to scene with tabs loses navbar

### ISSUE THREAD

**Issue by robcalcroft** [aksonov/react-native-router-flux#1473]
When `push`ing from a scene to a a new scene that has `tabs={true}` the navbar disappears before the new one is rendered. See http://g.recordit.co/eo0GVoO0Zj.gif for a visual demonstration.

### Version
- react-native-router-flux v3.37.0
- react-native v0.39.0

### Expected behaviour
The navbar does not disappear and stays fixed during scene `push` transition.
`Actions.tabbar({ title: 'Custom Title })` from `View2`

### Actual behaviour
When the scene `push` starts the navbar disappears and the content moves to the top and the navbar for the new scene slides in. Once the transition is complete there are no issues.

### Steps to reproduce
```javascript
      <Scene key="MainView" title="MainView" icon={TabIcon}>
        <Scene key="View1" component={View1} />
        <Scene key="View2" component={View2} />
        <Scene key="tabbar" tabs>
          <Scene key="infoTab" tabTitle="Info" icon={InvestigateTabIcon}>
            <Scene key="hashtagDetailInfo" component={Info} />
          </Scene>
          <Scene key="eventsTab" tabTitle="Events" icon={InvestigateTabIcon} initial>
            <Scene key="hashtagDetailEvents" component={Events} />
          </Scene>
          <Scene key="notesTab" tabTitle="Notes" icon={InvestigateTabIcon}>
            <Scene key="hashtagDetailNotes" component={Notes} />
          </Scene>
        </Scene>
      </Scene>
```

I have tried wrapping `tabbar` in another scene but this does not work

**Comment by robcalcroft** [comment]
@aksonov Could I get some help with this please, Im getting the same when I `push` open a modal

**Comment by ddeanto** [comment]
I am having the same problem, any update?
