### ISSUE TITLE
Increase back swipe gesture grab range

### ISSUE THREAD

**Issue by robcalcroft** [aksonov/react-native-router-flux#1474]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.0

### Wanted behaviour
The grab range for the back swipe action can be defined, eg when performing a backwards swipe within 50% of the left of the screen the view starts to pop

### Actual behaviour
Only around 5% of space is available on the left to grab and swipe, this results in a a frustrating UX as grabs are harder to achieve and the user must be more specific with their swipe

### Steps to reproduce
Attempt to pop a view using the swiping gesture

**Comment by robcalcroft** [comment]
Something like http://adrian-philipp.com/post/react-native-navigator-swipe-from-middle, not sure of the config I could use for this project?

**Comment by booboothefool** [comment]
@robcalcroft How did you end up making it bigger?
