### ISSUE TITLE
navigation state show correct index?

### ISSUE THREAD

**Issue by rmnegatives** [aksonov/react-native-router-flux#1475]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour
![screen shot 2016-12-14 at 4 55 37 pm](https://cloud.githubusercontent.com/assets/3335740/21202863/2eee7c66-c21e-11e6-8f69-40b3e1f6ae53.png)

I would expect index to be 3.

### Actual behaviour
Instead it shows 0 and the key seems to have right number in it? showing 1.

Any ideas on how to expose this index correctly.

I want to use index to decide whether to show a back button or not, without having to write my own reducer and store this index myself?

**Comment by jaisonveneri** [comment]
Hello @rmnegatives,

I need to do something like that. Can you resolve that?

Thanks!

**Comment by rmnegatives** [comment]
@jaisonveneri you mean @aksonov right?

**Comment by jaisonveneri** [comment]
@rmnegatives Can you get the correct index in another way? Sorry for the misunderstanding.

**Comment by rmnegatives** [comment]
@jaisonveneri  with this specific version notice that key: 'tile_1_tile' you can parse that out. But it seems like index should say 1 as well.

**Comment by jaisonveneri** [comment]
Yes, you are right @rmnegatives,

For me it seems that in "key" has the index inside.
I needed to know the count stack navigation to show or not a custom back button on a custom navbar. I think that I use this.

Thanks for the reply.

**Comment by rmnegatives** [comment]
No prob had the same reason! @jaisonveneri

**Comment by Kernael** [comment]
Any news on this ?
