### ISSUE TITLE
how should I custom animation of 3.x version

### ISSUE THREAD

**Issue by L-Jovi** [aksonov/react-native-router-flux#1478]
I don't know how to custom below animation like native Navigator component

```
PushFromRight
FloatFromRight
FloatFromLeft
FloatFromBottom
FloatFromBottomAndroid
FadeAndroid
HorizontalSwipeJump
HorizontalSwipeJumpFromRight
VerticalUpSwipeJump
VerticalDownSwipeJump
```

and I notice that __No Schema element is supported for now (for simplicity), maybe later it could be added__ in [MIGRATION.md](https://github.com/aksonov/react-native-router-flux/blob/master/docs/MIGRATION.md), and how could I custom scene config like change width of gesture range or disable gesture?

thanks for your time,

regards.

**Comment by bawn** [comment]
+1

**Comment by aiyidu** [comment]
+1

**Comment by nomoreboredom** [comment]
When you define your scenes, use the property:
animationStyle={YourNavigationCardStackStyleInterpolatorFunction}
wheareas your function should be something like: [http://www.reactnativediary.com/2016/12/20/navigation-experimental-custom-transition-1.html](url)

**Comment by L-Jovi** [comment]
@nomoreboredom thanks for your reply, and I encounter `404 page not found` from your link :(

**Comment by nomoreboredom** [comment]
fixed now :)

**Comment by L-Jovi** [comment]
@nomoreboredom  thanks again :)
