### ISSUE TITLE
Can't set Tab Screen to initial screen in v2.1.3

### ISSUE THREAD

**Issue by lentg** [aksonov/react-native-router-flux#148]
`<Route name="tabbar" initial={true}>`   error: route is not defilned
OR
` <Router hideNavBar={true} initialRoutes={['tabbar']}>`  error: route is not defined

**Comment by joelcloralt** [comment]
Just make sure the initial route is at the root level inside the outermost `<Router>` and not nested in a second `<Router>`

If that doesn't solve it, can you post your entire router? it works for me.

**Comment by herby** [comment]
`initialRoutes=[...list of strings...]` is not working any more. It awaits list of objects.
