### ISSUE TITLE
Scenes are not removed from nav stack when moving between tabs

### ISSUE THREAD

**Issue by johnwiseheart** [aksonov/react-native-router-flux#1480]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.35.0

### Expected behaviour

When on one tab, I navigate to a child component of another tab using the `Actions` method. I then navigate back to the original tab by clicking on it in the tab bar. After repeating this a couple of times with different child components of the other tab, on the child component, I press the back button. I would expect that clicking back would navigate to the parent/root of the scene, rather than going through each of the child components first. 

### Actual behaviour

After completing the steps above, I see the previous child components in the reverse order that I viewed them in, rather than navigating back to the root of the scene.

### Steps to reproduce

1. Be on one tab
2. Navigate to a child component of another tab using the `Actions` method
3. Navigate back to the original tab by clicking on it in the tab bar.
4. Repeat steps 2 and 3 several times with different child components each time
5. On the child component, press the back button.
6. See that you get to the previous child component opened, and not the root of the tab.

### Other discussion

I feel like this is the expected behaviour, but I've come up against this issue and I'm interested as to how people are  handling it. I've tried using duplicated scenes for each tab, but there are far too many scenes and I feel like this isn't a good user experience, since in my situation the user is clicking on search results in one tab, and should be navigated to a child component of another tab based on what the results are.

**Comment by femiveys** [comment]
I have the same problem. I would want the nav stack to be cleared when switching tabs.

**Comment by arvindmishra1406** [comment]
I am stuck with same issue. Can someone help us?
