### ISSUE TITLE
OnLeftRoute event

### ISSUE THREAD

**Issue by sirgalleto** [aksonov/react-native-router-flux#1481]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0

What's the best way to detect if an user left any route?

**Comment by Naoto-Ida** [comment]
Is `componentWillUnmount` not enough?

**Comment by sirgalleto** [comment]
Not always because the router saves the component in a history for the back feature, and the component only unmount when the component is not interacting with any part of the application. Any way to know if a component will be "hide" or update it state into the router history is using `onReceiveProps`, usign with `componentWillUnmount` you can create a good flow.
