### ISSUE TITLE
Native-base content being overlayed by navigation bar

### ISSUE THREAD

**Issue by ImTheDeveloper** [aksonov/react-native-router-flux#1486]
### Version

- react-native-router-flux ^3.37.0
- react-native v0.39.0
- native-base v0.5.18
### Expected behaviour
Expect navigation bar to not cover content. This appears to be an issue when using native-base header and other components within a container and content tag.

### Actual behaviour
Navigation bar is covering content such as header and content tags.

![image](https://cloud.githubusercontent.com/assets/1431348/21292959/efcb7050-c50d-11e6-8c2f-be359277e650.png)

### Steps to reproduce

1. Component with following code highlight the issue:

```
import React, { Component } from 'react';
import { Container,Content,Header,Button,Text } from 'native-base';
import { Actions } from 'react-native-router-flux';
import myTheme from './Themes/myTheme.js';
export default class Product extends Component {
  render() {
    return (
      <Container theme={myTheme}>
      <Content>
  <Text>Apply for our {this.props.text}</Text>
            <Button> Open Account! </Button>
      </Content>
      </Container>
    )
  }
}
```

Unsure whether to ask for a change in native-base or whether this is a general issue with react-native-flux-router

Happy to submit an issue at native-base if this is expected behaviour with router-flux

**Comment by lucianomlima** [comment]
Check #1401
