### ISSUE TITLE
Disable title slide animation while using 'fade' animation

### ISSUE THREAD

**Issue by jvaclavik** [aksonov/react-native-router-flux#1487]
When I use
`<RouterWithRedux ... animation='fade'>`
there is still title slide animation from the right. Is is possible to disable it? I didn't find it in docs.

https://dl.dropboxusercontent.com/u/25736835/title-animation.mp4

**Comment by insaneinc01** [comment]
Yes, looking for a general way to disable this. Especially on Android to improve frame rate. 
The header title slide animation is not characteristic to Android, so it makes sense to have a way to disable this.
Thanks

**Comment by vexsnare** [comment]
+1
Yes, title fade animation doesn't look natural in android. For ios it suites well.

**Comment by vexsnare** [comment]
@insaneinc01 @jvaclavik Are you able to disable slide animation for android?

**Comment by jvaclavik** [comment]
@vexsnare Probably the best solution is disable transitions for Android:
```
import { Platform } from 'react-native'
...
<Scene
  key='root'
  duration={Platform.OS === 'android' ? 0 : null}
>
  ...
</Scene>
```
