### ISSUE TITLE
Custom NavBar doesn't appear

### ISSUE THREAD

**Issue by Rhysjc** [aksonov/react-native-router-flux#1489]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.38.0

### Expected behaviour
I'm setting a navBar prop on my root Scene. I'd expect this custom NavBar to be used for all child scenes.

### Actual behaviour
NavBar only appears if the root Scene has a flat tree of children. If there's any nested roots it doesn't appear at all.

### Steps to reproduce
The following code works:
```js
class AppRouter extends Component {
    render() {
        return (
            <Router>
                <Scene key="root" navBar={NavBar}>
                    <Scene key="schedule" component={Schedule} title="Schedule" initial />
                </Scene>
            </Router>
        );
    }
}
```

This doesn't:
```js
class AppRouter extends Component {
    render() {
        return (
            <Router>
                <Scene key="root" navBar={NavBar}>
                    <Scene key="schedule" component={Schedule} title={moment().format('MMM YYYY')} initial>
                        <Scene key="scheduleEvent" component={Event} title="Event" />
                    </Scene>
                </Scene>
            </Router>
        );
    }
}
```

**Comment by ayozemr** [comment]
+1
I have to specify my navbar component on all child scenes because hierarchy does not work when you specify a navBar on a parent scene and child has not one specified.

**Comment by krailler** [comment]
@aksonov Hey, see this.

**Comment by aksonov** [comment]
Try to pass navBar as Router param, if you want to make it global

**Comment by ayozemr** [comment]
Now the first time I visit a tab, navbar flashes like its re-rendering or something... Its possible to fix that? Maybe it has an animation we can edit? It happens only on Android, iOS not flashing.

Thanks @aksonov for your time!

**Comment by aksonov** [comment]
Sorry, can't help here because of iOS usage only. Maybe you could debug and check why it re-renders

**Comment by AAverin** [comment]
#1752  is related to this one

**Comment by roseniltonreis** [comment]
Same problem :/
