### ISSUE TITLE
How does the Actions pop(n)?

### ISSUE THREAD

**Issue by Daniel-ccx** [aksonov/react-native-router-flux#149]
I test the case,but it's not what I want.

such as Actions.pop(2)

It is just from page3 -> page2 ->page1.

How to make this work: page3->page1?

**Comment by rgoldiez** [comment]
You can just route to page1... Actions.page1({params})

**Comment by tristola** [comment]
I have similar situation.

There is no scheneConfig called "FloatFromUp", so If i navigate Actions.page1({params}),
so I cannot have the "correct animation". Of course I can implement such a animation. But being able to pop the history would make this nicer: Actions.pop(2)

**Comment by aksonov** [comment]
Closing it for now, because it is for outdated version (2.x). pop(n) is not supported for 3.0, feel free to submit PR for it.
