### ISSUE TITLE
How to unmount a scene when push to it and pop from it

### ISSUE THREAD

**Issue by Yangzhilang** [aksonov/react-native-router-flux#1491]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.38.1

### Expected behaviour

Here are the scenes A and B.
A -> push to B,and B pop back. 
I want when B is popped it will not be in memory.When I push to B again,B should mount again and the lifecycle method such as componentWillMount should be called.

### Actual behaviour
B can not be mount again .

### Steps to reproduce

1.
2.
3.

**Comment by femiveys** [comment]
It would be interesting to get an answer on this.
I work with tabs. Whenever I press a tab it should be in the state as if I pressed the tab for the first time, no matter what happened in the tab. Having the scene unmount as requested here, could be a workaround.

**Comment by afilp** [comment]
I am also interested to it, not only for tabs though but for scenes too.

**Comment by proProbe** [comment]
any progress on this?

**Comment by jjhesk** [comment]
+1111 need some progress on this pls

**Comment by Clowning** [comment]
No news?

**Comment by vvavepacket** [comment]
any updates?

**Comment by roadev** [comment]
I'm stuck in this too :/

**Comment by qmegas** [comment]
+1
