### ISSUE TITLE
Getting undefined is not a function on Android only

### ISSUE THREAD

**Issue by crysfel** [aksonov/react-native-router-flux#1495]
### Version
Tell us which versions you are using: 

- react-native-router-flux 3.37.0
- react-native 0.38.0

### Expected behaviour
Navigate to the next scene when calling `Actions.CALLBACK`.

### Actual behaviour
In my current App I have two scenes. I have a button on my view, when pressed I call the `Actions.CALLBACK` function to navigate to the next scene. This works great on iOS, however on Android I'm getting an error.

[![Screen Shot 2016-12-22 at 1.07.22 PM.png](https://s23.postimg.org/tgwqm0w3f/Screen_Shot_2016_12_22_at_1_07_22_PM.png)](https://postimg.org/image/semk3hd9z/)

### Steps to reproduce
These are my two scenes.
```
      <Provider store={store}>
        <Router>
          <Scene key="root" hideNavBar>
            <Scene key="workout" component={Workout} initial />
            <Scene key="workoutDetails" component={VideoPlayer} />
          </Scene>
        </Router>
      </Provider>
```

Then, on the `Workout` component, I'm importing the `Actions` class and calling the `workoutDetails` callback when a button is pressed. Here's the relevant code.

```
import { Actions } from 'react-native-router-flux';

// On the render method
<WorkoutControls onPlay={() => Actions.workoutDetails()} />
```

This is working great on iOS, but not on Android :(

Any help would be appreciated. Thanks!

**Comment by denny64** [comment]
@crysfel have you found a solution for this yet?

**Comment by lauriegriffiths** [comment]
I just had this same problem.  My navigation was working fine on iOS but not on Android. 

My navigation was originally in a separate Navigator.js file but I moved it to the root index.android.js and it fixed this problem.  Perhaps this is a bug in the library?  It seems reasonable that the navigation shouldn't have to be in the index directory.
