### ISSUE TITLE
Artificial scene stack (history)

### ISSUE THREAD

**Issue by sealskej** [aksonov/react-native-router-flux#1498]
### Version

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Question

Is there any way how to artificially define scene stack (history)? Let's say I have an app, where the user can naturally navigate from A –> B –> C. I'd like to initiate app on scene C, which has the same history as natural behavior (A -> B -> C), so user navigates back to B from initially opened scene C.

**Comment by JeroenNelen** [comment]
This would be a very handy feature.

**Comment by sealskej** [comment]
I've asked the same on StakcOverflow http://stackoverflow.com/questions/41320717/synthetic-scene-stack-history-with-react-native-router-flux
