### ISSUE TITLE
Get current route in parent element

### ISSUE THREAD

**Issue by Mokto** [aksonov/react-native-router-flux#15]
Hi,

Maybe this is a dumb question because I'm not an expert with Flux.

My react-native-router-flux is inside my drawer like this :
```javascript
<Drawer>
    <Router />
</Drawer>
```

In my drawer I want to know my current routes with getCurrentRoutes(). Is it possible ?

Thank you !

**Comment by aksonov** [comment]
What is your goal? Router should be top-level component, not inside some UI component (Drawer in your case). You may try to use drawer instead of navbar inside components, and navigator object will be passed as prop to it.

**Comment by aksonov** [comment]
Ah, I see - Drawer intended usage to be top-component as well :) Maybe we need to add that component to demo

**Comment by Mokto** [comment]
Yes, and my case is even more special, I have to put a Youtube Player out of the Router (top-level component as well).

```javascript
<Drawer>
       <PlayerQueue>
              <Router />
       </PlayerQueue>
</Drawer>
```

Is there any way to do it ? I absolutely have to set Drawer inside Router ?

**Comment by aksonov** [comment]
Router should be real top level component by design. If you could create github rep demo, I would able to see play with it and fix the problem

Pavel.

**Comment by Mokto** [comment]
Hi,

Thanks a lot but i managed to do it !

I placed a redux store over your router and save current routes.

Thanks again !

**Comment by JonnyBGod** [comment]
I realise you managed to work around it but for reference I did it in a different way.

Import PageStore form react-native-router-flux and then you can have the current route with PageStore.state.currentRoute.

You can probably also listen to the store on Drawer view.

**Comment by aksonov** [comment]
I glad that you found workaround, but i think i could adjust the component to work with drawer in correct designed way (i.e. being top-level component which uses Drawers/Tabbars/Navbars/etc) if you give me proper demo.

**Comment by andreasbhansen** [comment]
If I get this working, I'll try to provide a proper demo for it :)
