### ISSUE TITLE
Component Mounting Twice After React Native 0.39 upgrade with IOS 9.2

### ISSUE THREAD

**Issue by bbc4468** [aksonov/react-native-router-flux#1504]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39

### Expected behaviour
Component Should mount only once

### Actual behaviour
Component Mounting twice with IOS 9.2, Works well with IOS 10.2

### Steps to reproduce

1. Basic App with type="reset" Scene
2. IOS 9.2 emulator
3. Add logger to ComponentDidMount, logs twice
4. Works fine with IOS 10.2

**Comment by bbc4468** [comment]
Also works well with IOS 10.0

**Comment by bbc4468** [comment]
ping @aksonov

**Comment by aksonov** [comment]
Sorry, i'm not using this component at this moment (had to switch to native iOS controllers with react-native-router-native for truly native animations), any PR would be welcome.

**Comment by arnsa** [comment]
Same issue here. Anyone?
