### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by Chren** [aksonov/react-native-router-flux#1508]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour
no error

### Actual behaviour
Native module cannot be null

NativigationRootContainer.js 15

### Steps to reproduce

1. import {Scene, Router} from 'react-native-router-flux';
2. no step2
3.

![simulator screen shot 2016 12 30 10 57 27](https://cloud.githubusercontent.com/assets/349182/21558965/e037ba4e-ce7d-11e6-8088-9c7ef8f896f1.png)

**Comment by aiyidu** [comment]
solution:
You need to add RCTLinkingIOS in your pod file, which the documentation didn't mention.

**Comment by wcandillon** [comment]
@aiyidu Thank you for the solution.

**Comment by Chren** [comment]
It works! I am going to close this issue.

**Comment by affibox** [comment]
I actually added the RCTLinkingIOS to my pod file but I'm still getting the same error. Nothing changed.

**Comment by pgonzalez-santiago** [comment]
Same error here trying to run the Example. :/

# Get the code
git clone https://github.com/aksonov/react-native-router-flux.git
cd react-native-router-flux/Example

# Install dependencies
yarn

# Run it
react-native run-ios

**Comment by aksonov** [comment]
RNRF doesn't use any native modules, check stack trace.

**Comment by pgonzalez-santiago** [comment]
ok. Thank you. The problem was I had another RN project running on background.
