### ISSUE TITLE
How to pass props from navbar to another page?

### ISSUE THREAD

**Issue by vzhen** [aksonov/react-native-router-flux#1516]
I have a product view page with rightTitle Edit on navbar. When edit is clicked i want to pass product view state to another page.

How to do this if i use `Action.productEdit()` in `<Scene />`
```
<Scene
 key='product'
 component={Product}
 title='Product'
 rightTitle='Edit'
 onRight={() => { Actions.productEdit({ product: this.props.product }) }} // How can i get the state and pass it to Edit Page?
/>
```

**Comment by dragfire** [comment]
I think you can't do like that. A quick solution would be:
`onRight={ ()=>Actions.refresh({ product: true }) }`
Then, in your `Product`'s `componentWillReceiveProps`
`componentWillReceiveProps (props) {
    if (props.product) {
        Actions.productEdit({ product: this.state.product });
    }
}`

**Comment by AndrewHenderson** [comment]
@vzhen I use Redux to handle this. I dispatch the product id to a the product reducer and the reducer pulls it from the list and sets is on a sub-state "focus" like so:

```js
products: {
  list: [{…}],
  focus: {…}
}
```
Then, the Product component uses `mapStateToProps` to map the focus state to its props.

**Comment by AndrewHenderson** [comment]
@dragfire I'm dealing with a similar issue, where I want to set the NavBar title based on a value in the Redux store. I tried several things that didn't work. I'm wondering if I should create a new component that is connected to the Redux store like so:

```jsx
import React from 'react'; 
import { Scene } from 'react-native-router-flux';
import { connect } from 'react-redux';

class SceneWithRedux extends React.Component {
  render() {
    return (
     <Scene title={this.props.productTitle} />
    )
  }
}

function mapStateToProps(state) {
  return {
    productTitle: state.product.title
  }
}
export default connect(mapStateToProps)(SceneWithRedux);
```

**Comment by vzhen** [comment]
@AndrewHenderson Ohhh,  got it. Thank you
