### ISSUE TITLE
Disable backButton from navigationBar on tabs

### ISSUE THREAD

**Issue by msdark** [aksonov/react-native-router-flux#1517]
I have the following set.

- initial Scene a login screen
- second Scene is a tabbar
   - Accounts Scene 
   - Pendings Scene

Use case:
- User will always need to go to login screen so login Scene is marked as `initial` and have a navigationBar only with title
- After login, user navigate (automatically) to `Accounts` tab.
- User should not be able to go back to login page.

With my current setup. the Accounts tab (and the other one too) shows a back button if I tap that, I get back to login screen.

How can I disable that behavior?

```
<Router>
    <Scene key="root">
      <Scene
        key="loginPage"
        component={LoginPage}
        title="Iniciar Sesión"
        initial
        navigationBarStyle={{ backgroundColor: primaryBlue }}
        titleStyle={{ color: white }}
        panHandlers={null}
      />
      <Scene
        key="tabbar"
        tabs
        tabBarStyle={{ backgroundColor: white,
          borderTopWidth: 0.5,
          borderColor: lightGray,
          opacity: 1 }}
        renderBackButton={null}
      >
        <Scene
          key="saldos"
          component={SaldosPage}
          title="Saldos"
          navigationBarStyle={{ backgroundColor: primaryBlue }}
          titleStyle={{ color: white }}
          icon={TabIcon}
        />
        <Scene
          key="other"
          component={SaldosPage}
          title="Other"
          navigationBarStyle={{ backgroundColor: primaryBlue }}
          titleStyle={{ color: white }}
          icon={TabIcon}
        />
      </Scene>
    </Scene>
  </Router>
```

### Version
- react-native-router-flux v3.37.0
- react-native v0.39.2

**Comment by AndrewHenderson** [comment]
@msdark Put `renderBackButton={null}` on the "saldos" Scene.

**Comment by MichelKansou** [comment]
@AndrewHenderson `renderBackButton={null}` not working for me

**Comment by MichelKansou** [comment]
@AndrewHenderson here's my rooter when I login in android it work fine but in iOS I always have the back button 
```
<Scene key="root"
                    tabs={true}
                    component={connect(state => ({account: state.account}))(Switch)}
                    selector={(props)=> props.account.get('connected') ? "tab_bar" : "login"}
                    >
                    <Scene key="login" component={Auth} hideNavBar={true}/>
                    <Scene key="tab_bar" tabs={true} tabBarStyle={(Platform.OS === 'android') ? styles.androidtabBarStyle : styles.iOSTabBarStyle}>
                        <Scene key="home_tab" iconSource={images.icons.home} icon={TabIcon}>
                            <Scene key="home" component={Home} title="Home" hideNavBar={(Platform.OS === 'android')} renderBackButton={null}/>
                        </Scene>
                        <Scene key="profile_tab" iconSource={images.icons.profile} icon={TabIcon}>
                            <Scene key="profile" component={Profile} title="Profile" hideNavBar={(Platform.OS === 'android')}/>
                        </Scene>
                        <Scene key="settings_tab" iconSource={images.icons.settings} icon={TabIcon}>
                            <Scene key="settings" component={Profile} title="Settings" hideNavBar={(Platform.OS === 'android')}/>
                        </Scene>
                    </Scene>
                </Scene>

**Comment by AndrewHenderson** [comment]
@MichelKansou I believe the type should a function not an object. Try, `renderBackButton={()=>(null)}`.

**Comment by RobinJayaswal** [comment]
Just what I was looking for @AndrewHenderson, thank you!

**Comment by MichelKansou** [comment]
@AndrewHenderson it's working thank you 👍

**Comment by bishalshr** [comment]
renderBackButton is not working on v4. Are there any changes?

**Comment by aksonov** [comment]
@bishalshr It seems to be a bug, could you create an issue?

**Comment by bishalshr** [comment]
@aksonov is there any way to disable the action buttons? I want to disable the buttons when user saves the form.

**Comment by aksonov** [comment]
Maybe passing empty function ? `onBack={()=>{}}`

**Comment by bishalshr** [comment]
Great. It worked. Thank you.
But there are not mentions of onBack in the doc.

**Comment by aksonov** [comment]
Thanks for the feedback. Feel free to submit PR or we will do it later.

**Comment by t-nabil** [comment]
In RNRF v4.0 : you can use  **type={ActionConst.REPLACE}** ... > Iam not sure if it will work on older versions.

**Comment by pvroosendaal** [comment]
renderBackButton & onBack are not working for me. I'm tried setting those in the Scene declaration:
<Scene key="start" component={Start} renderBackButton={()=>(null)} />
<Scene key="start" component={Start} onBack={()=>{}}/>

"react-native": "0.44.0",
"react-native-router-flux": "^4.0.0-beta.17"

Any other ideas? 
I'd like to have a push animation, but no back button.

**Comment by luco** [comment]
@pvroosendaal Try this on you scene:

```
static navigationOptions = {
    headerLeft:null
  }
```

**Comment by pvroosendaal** [comment]
Yes, great! That works.
Thanks very much!

**Comment by y2k-shubham** [comment]
Sorry for the lame question, but where do I place the above code (static navigationOptions...)?
(I'm new to react-native as well as javascript)

**Comment by pvroosendaal** [comment]
In the Component class from the Scene, e.g.:

export default class SomeView extends Component {
	constructor(props) {
		super(props)
	}

	static navigationOptions = {
		headerLeft:null
	}
}

**Comment by y2k-shubham** [comment]
sorry @pvroosendaal, but that didn't work for me

**Comment by pvroosendaal** [comment]
You’re probably on another version then. Try one of the other solutions mentioned in this thread.

**Comment by y2k-shubham** [comment]
@pvroosendaal, just restarted the packager and re-ran the app, and it worked!
thanx

furthermore, following solution be @luco  in [https://github.com/aksonov/react-native-router-flux/issues/2219](url) also works fine

`static navigationOptions = {
    headerLeft: (<View></View>)
}`

**Comment by pvroosendaal** [comment]
Cool! Something I often forget too :)

Btw, the link gives a 404 for me.

**Comment by miuel** [comment]
hey @pvroosendaal , @aksonov , @MichelKansou  I tried whole the different options no one works for me i'm afraid. I'm using "react-native-router-flux": "^4.0.0-beta.22"
 
 renderBackButton={null}
 renderBackButton={()=>(null)}
 onBack={()=>{}}    

`
const RouterComponent = () => {
    return(
        <Router>    
            <Scene key="root">
                
                    <Scene key="login" component={LoginForm} hideNavBar />
                
                    <Scene 
                        key="employeeList" 
                        component={EmployeeList} 
                        title={"Employees"} 
                        onBack={()=>{}}             
                    /> 
            </Scene>
        </Router>
    )
}`

Even this object I'm not able to make works on my const RouterComponent ..., any idea ?

`
static navigationOptions = {
		headerLeft:null
	}
`
thanks...

**Comment by shibbyy** [comment]
This worked for me Actions.tabBar({type: ActionConst.RESET}).

**Comment by haythamakl** [comment]
type={ActionConst.RESET} in Scene

**Comment by Prashant-Mutnale** [comment]
renderBackButton={()=><View/>}
