### ISSUE TITLE
Use tabbar the tab use the same component I get data in the componentDidmount but entered page is not enter componentDidmount, so it's not re-render page

### ISSUE THREAD

**Issue by w514986768** [aksonov/react-native-router-flux#1518]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

**Comment by salincakli** [comment]
I do this:
  componentWillReceiveProps(nextProps: Props) {
        if (this.props.needsRefresh !== nextProps.needsRefresh) {
            {
                nextProps.needsRefresh &&
                InteractionManager.runAfterInteractions(() => {

                    this.getNewData()
                })
            }
        }
    }


and on the previous screen it pops back with:
        Actions.pop({refresh: {needsRefresh: true}})
