### ISSUE TITLE
Logging previous and next state incorrect

### ISSUE THREAD

**Issue by brycepavey** [aksonov/react-native-router-flux#152]
When using redux-logger in the Chrome debugger the prev state is incorrect, and always matches next-state, seems to be a reference error. This is not an issue in the (now unsupported) react-native-redux-router though.
I'm unsure if this is an issue local to my reducer, or an internal issue of react-native-router-flux.

Here's the action I'm performing in the reducer 

```javascript
case ON_PUSH:
      var newRouterState = action.routerState
      newRouterState.push(action.route)
      return {
        ...state,
        routerState: newRouterState
      };
```

Attached image shows the routerState array containing two objects before and after the ON_PUSH action, though prev state should only contain one.

![screen shot 2016-01-27 at 2 02 03 pm](https://cloud.githubusercontent.com/assets/6986339/12602629/ea2c1916-c4fe-11e5-96fd-6aaa39cab325.png)

**Comment by jgibbons** [comment]
+1

**Comment by aksonov** [comment]
Could you clarify? The component doesn't use redux.

**Comment by aksonov** [comment]
I'm closing it for now because of lack of details
