### ISSUE TITLE
Is there a doc about what ActionConst do?

### ISSUE THREAD

**Issue by vzhen** [aksonov/react-native-router-flux#1520]
Let say I navigate to 3 pages then when a something is deleted i want to auto navigate back to 1st page with stay in same listview position.
Does ActionConst have function for this?
Also, can someone explain to me what these ActionConst type do?

Property	Type	                      Value	Shorthand
ActionConst.JUMP	                      string	'REACT_NATIVE_ROUTER_FLUX_JUMP'	'jump'
ActionConst.PUSH	                      string	'REACT_NATIVE_ROUTER_FLUX_PUSH'	'push'
ActionConst.REPLACE	              string	'REACT_NATIVE_ROUTER_FLUX_REPLACE'	'replace'
ActionConst.BACK	                      string	'REACT_NATIVE_ROUTER_FLUX_BACK'	'back'
ActionConst.BACK_ACTION	      string	'REACT_NATIVE_ROUTER_FLUX_BACK_ACTION'	'BackAction'
ActionConst.POP_AND_REPLACE  string	'REACT_NATIVE_ROUTER_FLUX_POP_AND_REPLACE'	'popAndReplace'
ActionConst.POP_TO	              string	'REACT_NATIVE_ROUTER_FLUX_POP_TO'	'popTo'
ActionConst.REFRESH	              string	'REACT_NATIVE_ROUTER_FLUX_REFRESH'	'refresh'
ActionConst.RESET	                      string	'REACT_NATIVE_ROUTER_FLUX_RESET'	'reset'
ActionConst.FOCUS	              string	'REACT_NATIVE_ROUTER_FLUX_FOCUS'	'focus'

**Comment by mu1ex** [comment]
3,338 stars and extremely bad documentation.

**Comment by jenessawhite** [comment]
This would be IMMENSELY helpful!

**Comment by monotv** [comment]
I think everyone is invited to add documentation :)

**Comment by jenessawhite** [comment]
Agreed @monotv, but I think the point of asking was because we didn't understand ActionConst otherwise I would love to help add to docs

**Comment by gustavjf** [comment]
@vzhen 

There seems to be partial documentation [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#actionconst-and-scenetype-explaination), but there are still some `ActionConst` descriptions missing, for example `JUMP`, `POP_TO`, `POP_AND_REPLACE`, etc.

@aksonov Any chance those descriptions could be updated?

**Comment by aksonov** [comment]
Guys, contributors are actively wanted! It is extremely difficult to support this component alone because I can do it mostly in my free time.

Probably for v4 it will be done someday  - actually all constants represents actions from new React Navigation API (v3 is not supported anymore because of many many bugs within obsolete fork of react-native-experimental-navigation from Facebook)

**Comment by gustavjf** [comment]
@aksonov Safe to say then that v3 docs will not be updated to document missing information? 

There's quite a few breaking changes for v4, so it's likely not everyone using this package will immediately upgrade. In which case, they would still be stuck with missing documentation for core functionality of v3, wouldn't you agree?
