### ISSUE TITLE
Pavel, do you do freelance work?

### ISSUE THREAD

**Issue by ethaniel** [aksonov/react-native-router-flux#1528]
I am looking a React Native developer for 3 app projects.
If interested, let's talk!

**Comment by cpruijsen** [comment]
@ethaniel happy to help as well 👍

**Comment by ethaniel** [comment]
@cpruijsen awesome! how can I contact you?

**Comment by cpruijsen** [comment]
@ethaniel christopher.pruijsen@gmail.com

**Comment by AndrewHenderson** [comment]
@ethaniel Can you close this? Not really the place to post. If you want to reach Pavel directly, use his email address in the pacakge.json: https://github.com/aksonov/react-native-router-flux/blob/master/package.json#L29
