### ISSUE TITLE
Scene's Not "connected" to Redux store. Can't mapStateToProps

### ISSUE THREAD

**Issue by AndrewHenderson** [aksonov/react-native-router-flux#1530]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.37.0

### Expected behaviour
In order for `NavBar`s to be able to react to state changes on their child `Component`s, they need a way to listen for state changes on the Redux store.

### Actual behaviour
Currently, the context and arguments provided to the Scene component event callbacks offer no access to the Redux store, making state-based renders challenging.

### Development
I've been forced to modify the project files within node_modules in order to get various desired behaviors. I'll explore connecting the `Scene` components. If I find a nice solution, I'll submit a PR.

**If anyone has already developed a solution, please respond here.**

**Comment by AndrewHenderson** [comment]
Can anyone provide an example of how to use this: [Custom nav bar for individual scene or even different state of scene (new feature)](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#custom-nav-bar-for-individual-scene-or-even-different-state-of-scene-new-feature)

**Comment by stonepreston** [comment]
I'm trying to figure out how to implement state based navbar buttons. Anyone have any tips?

**Comment by AndrewHenderson** [comment]
@stonepreston Use the [`Scene`'s API](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#navigation-bar-right-button), particularly the render functions such as `renderRightButton` to return a string based on the props. The argument to these methods is the props, however if you're using Redux, this will be a WrapperComponent. The trick is to provide props when executing the scene action, i.e. `Actions.myScene({ user: {…}});`.

```jsx
function renderProfileRightButton(props) {
  if (props.user.id === 1) {
    return <Button><Text>Settings</Text></Button>
  } else {
    return null;
  }
// Somewhere in your router
<Scene renderRightButton={renderProfileRightButton} />
```

**Comment by gwest7** [comment]
Any solution to this yet?

**Comment by AndrewHenderson** [comment]
@gwest7 I created my own NavBar component that I use as a child within my scene. I hide the NavBar at the router level, using it as a proxy to pass props, and then use those props within my scene component – providing relevant ones to my child NavBar.

It's given me a lot more control over the appearance of my NavBar which relies heavily of state within the scene itself.
