### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by jungchris** [aksonov/react-native-router-flux#1531]
### Version

- react-native-router-flux v3.37.0
- react-native v0.40.0
- react v15.4.0-rc.4

Running unmodified 'Example' on iPhone 6 10.2 (14C92) launched from Xcode 8.2.1

### Expected behaviour

On the 'Example' project we expect screen transitions to occur within one second of user requesting new screen

### Actual behaviour

Some transitions, specifically 'back' requests take 4-6 seconds to complete.

### Steps to reproduce

1. Navigating from Launch screen to Login, then Login2, followed by Login3 happens quickly
2. Going back by hitting 'Back' button on each view to return to the former view take 4-6 seconds.
3. There is however NO delay when selecting 'To Root' from Login3

**Comment by booboothefool** [comment]
I'm seeing the same thing. Is it slow on iPhone 7 too? My scenes are super complicated with heavy images, so I was planning on doing some `InteractionManager` optimizations, but this just seems like a problem if it happens on the simple example.

**Comment by DavidKongDesheng** [comment]
Same issue here, whenever click the navigator back button, it will take around 4-5 seconds to back to the previous page.

**Comment by DavidKongDesheng** [comment]
Just found if remove all console.log() and disable logger, everything works fine again.

**Comment by jungchris** [comment]
Thanks @DavidKongDesheng, I'll try that.
