### ISSUE TITLE
How to Action.pop() without animation in a <Scene />, not hold project. I've set duration={0} but it won't work. Many thanks!

### ISSUE THREAD

**Issue by lelup** [aksonov/react-native-router-flux#1532]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Steps to reproduce

1.
2.
3.

**Comment by sakarit** [comment]
Try

Actions.sceneYouWantToPopTo({type: ActionConst.POP_AND_REPLACE})

This should pop to the scene without animation, but it also re-renders the scene.
