### ISSUE TITLE
Painfully slow on iPhone 6, Android, (fast on iPhone 7)

### ISSUE THREAD

**Issue by booboothefool** [aksonov/react-native-router-flux#1536]
### Version
Tell us which versions you are using: 

    "react-native-router-flux": "^3.37.0",
    "react-native": "0.37.0",

App runs great, fast and smooth on iPhone 7, iPhone 7 Plus iOS 10.2, as well as Samsung Galaxy S7.

However on iPhone 6 it takes about 4-7 seconds for transitions...

No `console.log` anywhere. 

Any suggestions?

**Comment by salincakli** [comment]
try doing js expensive js operations in here:

 componentDidMount() {
        InteractionManager.runAfterInteractions(() => {
            // expensive js  -here-
        })
    }

**Comment by booboothefool** [comment]
@salincakli

Moving some network requests to `InteractionManager.runAfterInteractions` seemed to help a bit, but I'm still getting this annoying ~1 second delay before the transition even begins.

Any more things I could try?

**Comment by hugohow** [comment]
I have the same issue with Samsung Galaxy S7 ! It works perfectly on Iphone by the way

**Comment by booboothefool** [comment]
Ended up just switching to Ex-navigation. No delay, smooth transitions on all phones.
