### ISSUE TITLE
Event triggered when routing

### ISSUE THREAD

**Issue by ddolheguy** [aksonov/react-native-router-flux#1538]
Does anyone know if there is an event I can bind too which is triggered each time the user changes the route?

I know I can use componentWillMount, etc but I would prefer not to.

**Comment by coreyphillips** [comment]
Here's a list of other lifecycle methods (https://facebook.github.io/react/docs/react-component.html). What exactly are you attempting to do?

**Comment by CoteViande** [comment]
With redux you can create a custom Middleware like such :

```js
// src/middlewares/custom.middleware.js
const customMiddleware = store => next => action => {
  if (action.type === REACT_ROUTER_FLUX_FOCUS'') {
    doStuff(action)
  }
  return next(action)
}

export default customMiddleware
```

Do not forget to return next(action) and also to link that middleware in your configureStore.js file.
