### ISSUE TITLE
display white screen or hold last state when faster interaction which trigger push

### ISSUE THREAD

**Issue by L-Jovi** [aksonov/react-native-router-flux#1539]
__version__

- react-native-router-flux v3.37.0
- react-native v0.37.0

__issue__

I notice that when user faster press button to push new page which will display white screen all the time, and sometimes it also show last state data,

..maybe 3.x version using new feature from react-native experimental navigator, how could I fix it?

thanks for your time,

regards.

**Comment by wm219** [comment]
year, me too.Maybe react-native experimental navigator do something works.

**Comment by timwzou** [comment]
any solution without updating to V4? I can not update to the new version at present.
btw, does anyone know the cause of the issue?
