### ISSUE TITLE
how to set transition animation

### ISSUE THREAD

**Issue by jaredtibs** [aksonov/react-native-router-flux#1540]
Sorry guys,

Maybe it's under my nose or maybe I'm missing something fundamental, but how do I configure the scene transition when using this library?

i.e. I call: `Actions.newScene` and I want it to float from the bottom instead of slide horizontally. 

If anyone can point me in the right direction that would be much appreciated. 

Thanks

**Comment by IlyasAbdighni** [comment]
Try direction='vertical' for the scene property. Hope it works for you.

**Comment by jaredtibs** [comment]
@IlyasAbdighni this did work for me. thank you!

**Comment by mehdyMa** [comment]
@IlyasAbdighni What about sliding from left to right? 
I have already tried with direction='left' and direction='right' ..

**Comment by ryancoughlin** [comment]
Also looking for some examples of this. Docs highlight properties but don't support any examples on how to add in custom transitions.

**Comment by dan-katz** [comment]
@mehdyMa For left to right try "<Scene direction="leftToRight">"

**Comment by dan-katz** [comment]
@mehdyMa for left to right try `<Scene direction="leftToRight">`

**Comment by ptaking** [comment]
Seem like `direction` does not work anymore
