### ISSUE TITLE
Multiple Routers

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#1541]
I have two routers. Is there a way to communicate between them? Even with referencing?
For example, go to a scene in router 2 by calling a function on router 1?

Thanks

**Comment by jonrh** [comment]
Multiple routers are not supported, [#26](https://github.com/aksonov/react-native-router-flux/issues/26), [#221](https://github.com/aksonov/react-native-router-flux/issues/221), [#513](https://github.com/aksonov/react-native-router-flux/issues/513).

**Comment by luco** [comment]
@jonrh Yea, it seems not. But I think that's essential. I don't say a router inside a router, but at least the props to control them individually.

**Comment by Jlexyc** [comment]
Router inside router important too. iOS has ContainerViewControllers as a base - and it's really useful.
