### ISSUE TITLE
Getting white screen while redux action is performing

### ISSUE THREAD

**Issue by Freego1783** [aksonov/react-native-router-flux#1543]
### Version
 "react": "^15.4.2",
 "react-native": "^0.39.2",
 "react-native-router-flux": "^3.37.0",
 "react-redux": "^5.0.1",
 "realm": "^0.15.2",
 "redux": "^3.6.0",
 "redux-logger": "^2.7.4",
 "redux-thunk": "^2.1.0"

### Expected behaviour

Showing a loading screen while the action is running.

### Actual behaviour

Getting a white screen instead, like app is frozen.

### Issue

I'm using Realm as a database in my app and i have to load some data when launching my app. I want a loading screen while i'm getting the data and writing them into Realm. 

To do so, i created a React-Native Component showing some texts and a progress bar and in the `componentDidMount()` i called my Redux Action doing the job. Then in `componentWillReceiveProps` i do some checking and then i call ` Actions.home({type: ActionConst.RESET});` to go to the next page.

I hoped that my loading screen would be showing but i just have a white screen and then i'm redirected to the Home screen.

Here are my scenes : 

```
scenes = Actions.create(
        <Scene key="root" navigationBarStyle={styles.navbar} titleStyle={styles.title}>
            <Scene key="loading" component={LoadingScreen} initial={true}/>
            <Scene key="home" component={Home} title="Liste des shooters"
                   renderRightButton={()=><NavbarRightButton/>}/>
            <Scene key="shooterDetail" component={ShooterDetail}/>
        </Scene>
    );
```
I'm fairly new to React, React-Native, Redux, and stuff like that so maybe my approach is wrong.

Any help would be appreciated  !

**Comment by CoteViande** [comment]
I personally don't do it using a Loading scene but with a component that I plug into existing scenes, with a redux state parameter, as such:

```js
// customContainer.js
import React from 'react'
import { connect } from 'react-redux'

import LoadingPage from 'app/src/components/general/LoadingPage'

let Container = React.createClass({
  render() {
    const { isLoading } = this.props

    if ( isLoading ) {
      return (
        <LoadingPage />
      )
    }

    return(
      <MyAwesomeComponent />
    )
  }
})

const mapStateToProps = state => ({ isLoading: state.isLoading })

export default connect(mapStateToProps)(Container)
```

If you wish to make it globally, I guess you could place your loading page in your App.js container like so:

```js
// App.js, inside the render() function
if (isLoading) {
  return <LoadingPage />
}

return (
  <View>
    <StatusBar translucent={false} backgroundColor={ color.red900 } barStyle="default" />
    <RouterWithRedux scenes={scenes} />
  </View>
)
```

**Comment by Freego1783** [comment]
Thanks for your response,

Actually i forgot to mention that i want my loading screen to also act as a Splash Screen, that would explain why i tried to do it that way.

But i'll also try what you suggest and maybe work my way from there.

**Comment by CoteViande** [comment]
I do not get the difference between a loading page and a splash screen. I don't know if it is the best way, but it works for me ;)

**Comment by Freego1783** [comment]
Finally had time to try what you suggested but i get the exact same result, a white screen for a few seconds and then it's ok.

I removed the loading scene from my router and i updated the `render() ` of my Home screen to display the Loading component while updating the database.

Kinda strange, i don't get what's happening :/

**Comment by CoteViande** [comment]
How do you update your database? How do you signal that the update is complete?

**Comment by Freego1783** [comment]
Here are my actions : 
```

export function updateDB() {
    return (dispatch, getState) => {
        dispatch(setDBUpdating());

        var shooters = shootersJson.shooters;

        shooters.forEach(function (shooter) {
            realm.write(() => {
                realm.create('Shooter', {
                    name: shooter.name,
                    category: shooter.category,
                    price: shooter.price,
                    strength: shooter.strength,
                    gender: shooter.gender,
                    treachery: shooter.treachery,
                    drinkStyle: shooter.drinkStyle,
                    recipe: shooter.recipe,
                    quote: shooter.quote
                }, true);
            });
        });

        dispatch(setDBUpdated());
    }


}

export function setDBUpdating() {
    return {
        type: types.UPDATING_DB
    }
}

export function setDBUpdated() {
    return {
        type: types.DB_UPDATED,
        shooters:realm.objects('Shooter')
    }
}
```

I have a json file that i parse to populate the database.

Here are my reducers : 

```
export const updatingDB = createReducer(false, {
    [types.UPDATING_DB](state, action){
        let newState={};
        newState.dbIsUpdating=true;
        return newState;
    }
});

export const db = createReducer({}, {
    [types.DB_UPDATED](state, action){
        let newState={};
        newState.shooters=action.shooters;
        newState.dbIsUpdating=false;
        return newState;
    }
});
```
And Here are the relevant parts of my Home screen : 

```
class Home extends Component {

    constructor(props){
        super(props);
        this.props.updateDB();
    }

 render() {

        if(this.props.dbIsUpdating){
            return(<LoadingScreen/>);
        }

        return <View style={styles.mainContainer}>
                //list view with data from Realm
        </View>
    }
}

function mapStateToProps(state) {
    return {dbIsUpdating: state.dbIsUpdating}
}

function mapDispatchToProps(dispatch) {
    return bindActionCreators(ActionCreators, dispatch);
}

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(Home);
```

I call the action in the constructor, i also tried in `componentDidMount()` with no luck.

**Comment by CoteViande** [comment]
When using some kind of redux devtools, is `dbIsUpdating` changing as you expect it to? (true on initialization (as default) and set to false once done)

Among the things I would try:

* Place the LoadingScreen on the top level of your App, where you render your router (so that we are sure that this white screen does not stop appearing as the home component mounts itself)
* Try to reduce your problem to a simpler one by:
  * replacing your updateDb function by a timeout of 2 seconds (async/await) (to make sure you would see your loading screen, then you can also check your devtools to see if the dbUpdated triggers at the right time)
  * replacing your LoadingScreen component with: 
```js
<View style={{ flexGrow:1, justifyContent: 'center', alignItems: 'center' }}>
    <Text style={{ fontSize: 18, fontWeight: 'bold' }}>
       LOADING
     </Text>
</View>
```

After further analysis of my own app, I do have a white screen for a very short period of time (youTube does not), but I still have my loading screen for 1 second afterwards (while I update my store and set up my app). I am guessing that this is why you have bridges for [react native splash screen](https://github.com/crazycodeboy/react-native-splash-screen)

I hope you are going to have better luck with those options.

**Comment by Freego1783** [comment]
There's currently a bug with Realm that prevent me from using Remote Debuging but i think i managed to find what's going on after trying what you suggested.

I have a feeling that Realm is "too quick" or i just have to few data for now. If i wait like 500ms between each Relam Write, i can see my loading component.

But still, that white screen bugs me :D

Thanks for your help man.

**Comment by CoteViande** [comment]
No problem ;)

If you do try out [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen), please let me know how it went and if it does get rid of any white screen.
