### ISSUE TITLE
How to go back to Login again?

### ISSUE THREAD

**Issue by itcurves** [aksonov/react-native-router-flux#1545]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.40.0

### Expected behavior
render() {
    return(
      <Router createReducer={reducerCreate} >
        <Scene key="root">
          <Scene key="login" initial={true} hideNavBar={true} data={this.state.inC} component={Login} />
          <Scene key="mainswitch"  component={NavigationDrawer} logout={() => {this.logout()}} >
              <Scene key="home"  >
                <Scene drawerImage={require('../resources/drawer.png')} key="home1" component={Home} title="" navigationBarStyle={styles.navbar} titleStyle={styles.navbarTitle} />
              </Scene>
          </Scene>

        </Scene>
      </Router>
    );

  }

I want it to go back to Login screen when an Item clicked from Drawer

logout(){
   Actions.login({type: 'reset', data:obj});
  }

2 questions:
1. on Actions.login({type: 'reset', data:obj}); it is not going back to login screen
2. Why I have to add my component {Home} under another scene (an extra level)

I am using it for the first time any help really appreciated.

Thanks

**Comment by davidsharp** [comment]
If your app is guaranteed to pass the login screen, `Actions.popTo('login')` will work. Otherwise run the `Actions.login` without the `type` attribute, and set that as the type on the `login` `<Scene />` in your router, which will reset the nav stack whenever the user ends up on the login screen.

**Comment by dwilt** [comment]
@davidsharp worked perfect. This is probably the simplest solution the people over in https://github.com/aksonov/react-native-router-flux/issues/857 were looking for
