### ISSUE TITLE
Change back transition animation

### ISSUE THREAD

**Issue by vnshgrg** [aksonov/react-native-router-flux#1551]
### Version
- react-native-router-flux v3.37.0
- react-native v0.38.1

I am using react-native-router-flux for navigation. Is there a way to change the type of transition animation when I go back from a scene to previous scene. If you look carefully, there's a small white space above the navbar which I would like to get rid of. I am thinking if the same animation as transitioning to a new scene can be used to the back transition animation.

![Issue](http://i.giphy.com/l0Ex0BaGAJ7k31aVy.gif)

**Comment by booboothefool** [comment]
@vnshgrg https://github.com/aksonov/react-native-router-flux/issues/1202
