### ISSUE TITLE
Please add native animation support (better performance)

### ISSUE THREAD

**Issue by booboothefool** [aksonov/react-native-router-flux#1553]
@aksonov 

https://github.com/facebook/react-native/pull/10289#issuecomment-272992628

This helped out my slow transitions issues quite a bit, however properly implementing it for this library (so it still works with everything e.g. swipe right gestures) is a bit over my head.

**Comment by Naoto-Ida** [comment]
@booboothefool Semi-offtopic, but this just came out yesterday. May be good if you're going for fluid transitions. My app depends on this lib, so I'll probably be sticking around.
