### ISSUE TITLE
hideNavBar does not work

### ISSUE THREAD

**Issue by Vikaton** [aksonov/react-native-router-flux#1554]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour

For the NavBar to completely disappear from the screen.

### Actual behaviour

When using `hideNavBar` prop, it does not go away and just shows a blank navbar at the top with no functionality.

### Steps to reproduce

1. Create a scene with hideNavBar and component scene

My config: 

```
<Scene key="analytics" component={AnalyticView} direction="vertical" navigationBarStyle={{ backgroundColor: 'transparent' }} hideNavBar={true}/>
```
<img width="372" alt="screen shot 2017-01-16 at 8 12 53 pm" src="https://cloud.githubusercontent.com/assets/9522710/22004261/55f4585c-dc28-11e6-8f14-b6246bdd0abf.png">

**Comment by hasanmumin** [comment]
can you try :  
```
<Router showNavigationBar={false}>
.........
</Router>
```

**Comment by leesolway** [comment]
Same issue as reported.

<Router showNavigationBar={false}> didn't work either

**Comment by donovantc** [comment]
Same issue as reported.
