### ISSUE TITLE
After that history stack reset in tab bar, other tabs are not visible

### ISSUE THREAD

**Issue by yasemincidem** [aksonov/react-native-router-flux#1560]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.40.0

### Expected behaviour
When I made  navigation between tabbars , i want to reset history stack.Here is my code block.
```
  <Scene
                key="tabbar"
                tabs={true}
                tabBarStyle={styles.tabbarStyles}>
                <Scene key="profile"
                       icon={TabIcon}
                       title="chart"
                       onPress={()=>{
                       Actions.profile({type:ActionConst.RESET});
                       }}>
                    <Scene key="tabbar1" hideNavBar component={Tabbar1} title="Tabbar 1"/>
                </Scene>
                <Scene key="tabbar2"
                       icon={TabIcon} title="notebook">
                    <Scene key="tabbar3" component={Tabbar3} hideNavBar title="Tabbar 3"/>
                </Scene>
                <Scene key="tabbar4" icon={TabIcon} title="camera">
                    <Scene key="tabbar5" component={Tabbar5} hideNavBar title="Tabbar 4"/>
                </Scene>
</Scene>
```

### Actual behaviour

First of all ,when app is launched ,`tabbar1` is opened without problem,after that i clicked tabbar2 so tabbar2 is opened.But i clicked to `tabbar1` ,other tabs such as `tabbar2`,`tabbar4`  are not visible.There is only `tabbar1` in `tabbar` menu.What does it reason ?

Tabbar appearance when app is launched
<img width="373" alt="screen shot 2017-01-19 at 12 01 12" src="https://cloud.githubusercontent.com/assets/5556159/22099949/19e58182-de36-11e6-9f32-14c979321f74.png">
 
Tabbar appearance ,after `tabbar1` clicked:
<img width="374" alt="screen shot 2017-01-19 at 12 00 48" src="https://cloud.githubusercontent.com/assets/5556159/22099970/36f17218-de36-11e6-90f8-246178e0dc6a.png">

**Comment by mintotsai** [comment]
I'm seeing the same with react-native-router-flux v3.37.0. Is there a workaround?

**Comment by yasemincidem** [comment]
I am working with react-native-router-flux v3.36.0.

**Comment by dioxmio** [comment]
@aksonov can you check this issue? it's been there for a while. It happens to me as well

**Comment by mbenjamin618** [comment]
Any word on this? @yasemincidem @mintotsai

**Comment by yasemincidem** [comment]
@mbenjamin618i didn't understand what you say

**Comment by mbenjamin618** [comment]
I meant, is there any update? Did you solve this issue?

**Comment by yasemincidem** [comment]
Actually i didn't solve it like i talk about above.But i find a solution like this.Maybe it can help to you.
For example you have tabbar scenes like following.

<Scene
                key="tabbar"
                tabs={true}
                tabBarStyle={styles.tabbarStyles}>
                <Scene key="profile"
                       icon={TabIcon}
                       title="chart"
                       onPress={()=>{
                                Actions.tabbar({type: ActionConst.RESET});
                                Actions.popTo("profile");
                         }}>
                    <Scene key="tabbar1" hideNavBar component={Tabbar1} title="Tabbar 1"/>
                </Scene>
                <Scene key="tabbar2"
                       icon={TabIcon} title="notebook">
                    <Scene key="tabbar3" component={Tabbar3} hideNavBar title="Tabbar 3"/>
                </Scene>
                <Scene key="tabbar4" icon={TabIcon} title="camera">
                    <Scene key="tabbar5" component={Tabbar5} hideNavBar title="Tabbar 4"/>
                </Scene>
</Scene>
I mean when you click each icon on tabbar, you should reset tabbar scene and then you should navigate with `popTo` to sceneKey that you clicked.
```
 onPress={()=>{
                                Actions.tabbar({type: ActionConst.RESET});
                                Actions.popTo("profile");
                       }}
```
I hope this code will help to you.

**Comment by mbenjamin618** [comment]
yeah I'm having no problem resetting the tab bar component, my problem is that I want to reset the component inside of the tab bar:

```
<Scene key='main' tabs tabBarStyle={{backgroundColor: 'white', height}} >
      <Scene key='newsfeed' title='newsfeed' type={ActionConst.REFRESH} component={NewsFeed} hideNavBar icon={TabIcon} hideTabBar={false} />
      <Scene key='explore' title='explore' type={ActionConst.REFRESH} hideNavBar icon={TabIcon} hideTabBar={false}>
        <Scene key='explorePage' title='explorePage' component={Explore} type={ActionConst.REFRESH} />
        <Scene key='folder' component={Folder} hideNavBar />
      </Scene>
      <Scene key='alerts' title='alerts' type={ActionConst.REFRESH} component={Alerts} hideNavBar icon={TabIcon} hideTabBar={false} />
      <Scene key='more' title='more' type={ActionConst.REFRESH} component={More} hideNavBar icon={TabIcon} hideTabBar={false} />
    </Scene>
```

When I call the functions 
``` 
RouterActions.main({type: 'reset'})
RouterActions.newsfeed()
```

I want the newsfeed to start at the top again (since it's a listview). I can do this by resetting the component, but I run into the original issue or one icon in the tab bar.

**Comment by stsiushkevich** [comment]
I have the same issue. I found this PR: https://github.com/aksonov/react-native-router-flux/pull/1312
