### ISSUE TITLE
iOS Nav Bar fail to refresh on tab change

### ISSUE THREAD

**Issue by ooicl** [aksonov/react-native-router-flux#1567]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour
I expect the Nav Bar to be rendered according to the scene I selected on the tab. 
It works correctly on Android but not on iOS.

### Actual behaviour
on iOS, the Nav Bar button from the Settings scene got carried over to the 2nd tab Scene.

### Steps to reproduce

1. 4th tab has Nav Bar button rendered by code when the form is dirty.
`    if (this.props.dirty) {
      Actions.refresh({
        renderRightButton: this.renderRightButton,
        renderLeftButton: this.renderLeftButton
      });`

2. Make changes to the form so that the Nav Bar buttons are shown.
![screen shot 2017-01-20 at 8 08 13 pm](https://cloud.githubusercontent.com/assets/19430854/22149462/e4257ba0-df4e-11e6-95ea-418885d8d698.png)

3. Before saving the form, switch to the 2nd tab where the "Add" button was set in the router using onRight= 
![screen shot 2017-01-20 at 8 08 24 pm](https://cloud.githubusercontent.com/assets/19430854/22149383/6a00ae26-df4e-11e6-8a75-0dbd9b5de870.png)

Any idea what was wrong?

**Comment by Lxxyx** [comment]
same problem, need help.

**Comment by Lxxyx** [comment]
Try calling Actions.refresh() after you set new title.

From: 'https://github.com/aksonov/react-native-router-flux/issues/1557'

**Comment by ooicl** [comment]
How do you call Actions.refresh() on tab change?

**Comment by Lxxyx** [comment]
@ooicl just like this.

```javascript
Action.refresh({title: 'new title'}}
```

**Comment by Lxxyx** [comment]
Action.refresh(PARAMS)

PARAMS is the Scene props.

**Comment by ooicl** [comment]
What I meant was, where can we "detect" that the tab has changed? 
In my case, it was about user "clicking a different tab", not about changing the title.

**Comment by Lxxyx** [comment]
@ooicl I use redux.

**Comment by Lxxyx** [comment]
when click a tab, just dispatch an action

**Comment by ooicl** [comment]
The dispatch of tab-click action is not managed by me... it is managed by react-native-router-flux...
