### ISSUE TITLE
Switch does focus first tab and only then jumps to required tab

### ISSUE THREAD

**Issue by andrispraulitis** [aksonov/react-native-router-flux#1568]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour
1) 2 tabs: Tab_A, Tab_B
2) Switch selector: return 'Tab_B'
3) Tab_B focus

### Actual behaviour
3) Tab_A focus
4) Tab_B jump & focus

This seems wrong. Why does Tab_A gets focused if Switch selector asks for Tab_B ?

**Comment by underaj** [comment]
Did you put the unmountScenes props in tabs scene? Removing that would probably stop flashing the first child scene
