### ISSUE TITLE
Tabbar sometimes is pushed up by the keyboard.

### ISSUE THREAD

**Issue by CooLSeS** [aksonov/react-native-router-flux#1569]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.7.0
- react-native v0.4.0

### Expected behaviour

When I focus on the input the tab bar is moved up instead of staying behind the keyboard.

### Actual behaviour

Tabbar to remain in place

### Steps to reproduce

unable to pinpoint

**Comment by fanyuRN** [comment]
I also  meet this problem in android

**Comment by bielcapanema** [comment]
same here

**Comment by liujett** [comment]
when your RN app exit but run in the background,the problem will appear。

**Comment by liujett** [comment]
who know how to solve this problem?

**Comment by bielcapanema** [comment]
It's beacause of: android:windowSoftInputMode="adjustResize"
but it is necessary for react-native-gifted-chat

**Comment by itcurves** [comment]
any solution for this guys?
I am using react native router flux and also react native gifted chat. and kind of stuck :(

**Comment by foggy1** [comment]
On android this is still an issue, especially now that it uses adjustResize in the Android Manifest to make things responsive to the keyboard resizing the window.  It's great that they did that because Android had an issue with this previously, but there should be a way to make tab bar ignore the resizing of the window.

**Comment by ismjt** [comment]
+1

**Comment by therealchuckliu** [comment]
@aksonov would it be possible to have a new release of react-native-tabs with [this](https://github.com/aksonov/react-native-tabs/pull/46) merged and update the dependency?

**Comment by jorge627** [comment]
any solution for this guys?, thanks

**Comment by diegocouto** [comment]
Well, it seems that [a possible solution](https://github.com/react-community/react-navigation/pull/1764) (as pointed by @therealchuckliu) was already merged on react-navigation package, but it's not available on the current version yet (1.0.0-beta.19).

**Comment by kylanhurt** [comment]
We're having this issue on version 4.0.0-beta.28
