### ISSUE TITLE
Pop modals and show modals

### ISSUE THREAD

**Issue by proProbe** [aksonov/react-native-router-flux#1570]
The current example of modals shown in https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md displays a way to show a modal and then hide it. Ive noticed two problems
- It is impossible to get it to show again even if I press the button that should trigger the modal.
- I noticed that if you add different params to the navigation, its possible to open more modals but it also seem to open the old modals that had previously been closed or "hidden".

Is it possible to actually pop the the modal so problem number 2 gets solved. Also, how do you solve problem number 1?

code:

Modalcomponent
```
// @flow
import React, { Component } from "react";
import {
    View,
    TouchableHighlight,
    Text,
    StyleSheet,
} from "react-native";
import {
    Actions,
} from 'react-native-router-flux';

type Props = {
    hide: bool,
    message: string,
}

type State = {
    hide: bool,
    message: string,
}

class StatusModal extends Component {
    state: State
    props: Props

    constructor(props: Props) {
        super(props);
        this.state = {
            message: props.message,
            hide: props.hide,
        };
    }

    componentWillReceiveProps(nextProps: Props) {
        this.setState({
            hide: nextProps.hide,
        });
    }

    dismissModal = () => {
        this.setState({hide: true});
    }

    render() {
        console.log(this.state);
        if(this.state.hide) {
            return (
                <View />
            );
        } else {
            return (
                <View style={styles.mainContainer}>
                    <Text>TESTING ITU P</Text>
                    <TouchableHighlight style={styles.button} onPress={this.dismissModal}>
                        <Text style={styles.text}>{this.state.message}</Text>
                    </TouchableHighlight>
                </View>
            );
        }
    }
}

const styles = StyleSheet.create({
	mainContainer: {
        position: "absolute",
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        backgroundColor: "pink",
        justifyContent: "center",
        alignItems: "center",
	},
    button: {
        height: 200,
        width: 200,
        backgroundColor: "yellow",
    },
});


export default StatusModal;
```
the trigger button:
```
                            <TouchableOpacity
                                style={{
                                    height: 40,
                                    width: 40,
                                    backgroundColor: "pink",
                                }}
                                onPress={() => {
                                    Actions.showPost({hide: false, message: "hello"});
                                }}
                            >
                                <Text>Show post</Text>
                            </TouchableOpacity>
```
the scenes:
```
    _scenes = () => {
        return Actions.create(
            <Scene key="modal" component={Modal}>
                <Scene
                    key="root"
                    component={connect(store => ({
                        session: store.Router.session,
                        hasInitUser: store.Router.hasInitUser,
                    }))(Switch)
                    }
                    tabs={true}
                    unmountScenes
                    selector={this._sceneSelector}
                >
                  ...
                </Scene>
                <Scene key="showPost" component={PostModal} />
            </Scene>,
            RelayRenderer({})
        );
    }
```

**Comment by proProbe** [comment]
this problem actually a misunderstanding from my point. The problem I had lays more in android. gonna open a new issue about this

**Comment by hector** [comment]
@proProbe I am having the same problem (number 1). How did you solve it?

**Comment by proProbe** [comment]
@hector I solved it through using animation. Just removing the view itself made the touch on the screen unresponsive. Animate the view out first and then remove it worked for me

**Comment by hector** [comment]
Thanks @proProbe. I found what was happening. The modal is pushed on top of the scenes stack, so if you make it invisible it is actually there. So, the solution is as easy as:
```javascript
Actions.pop();
```

In case you want to add some animation, like fadeOut, delay the action until the animation has finished, for example:
```javascript
setTimeout(Actions.pop(), fadeOutDuration);
```

I also found a workaround if you do not want to `pop` your modal. You can change the css opacity of the view to 0 (it will make it invisible) and then add the prop `pointerEvents='none'` (which will make it not handle any touch). Anyway, I have the impression this solution would lead to some side-problems.

**Comment by hector** [comment]
@aksonov I believe the modals example in the documentation is wrong. In case you agree, it should be updated with the procedure of my last comment.

**Comment by aksonov** [comment]
Yes, feel free to submit a PR.

**Comment by ryancoughlin** [comment]
@hector I am having a similar problem with popping modals. What was the error you noticed in the documentation?

**Comment by hector** [comment]
@ryancoughlin I explained it above, but essentially you show the modal scenes with `Actions.youModalScene()` and hide it with `Actions.pop()`. There is no need to add conditions to show the modal or not, the router is already responsible for this.

**Comment by zuzuviewer** [comment]
@hector ,just `Actions.pop()`,the modal is still been showed

**Comment by mxmtsk** [comment]
I'm dealing with the same issue. The only thing that does work for me is `Actions.pop()` but I want to transition to a different scene from the modal and tried `Actions.popTo('profile')` as well as `Actions.profile({ type: 'reset' })` which both bring the modal up again as soon as I transition from the profile scene to another scene.

**Comment by hector** [comment]
I am sorry @ryancoughlin, I just posted my discoveries when trying to use this library but I don't really know its internals. I am sure the author @aksonov knows it better
