### ISSUE TITLE
Docs Error: Missing Parenthesis?

### ISSUE THREAD

**Issue by walkerdigital** [aksonov/react-native-router-flux#1572]
On the "Other Info" "Drawer" example within the Docs at the very end of the code block I believe it's missing a closing parenthesis.

https://github.com/aksonov/react-native-router-flux/blob/3.30.1/docs/OTHER_INFO.md#drawer-side-menu-integration

It's Currently:

``Actions.refresh({key: 'drawer', open: value => !value };``

Shouldn't it be:

``Actions.refresh({key: 'drawer', open: value => !value });``

Thanks!

**Comment by chris-at-translate** [comment]
Just a generic typo error, @aksonov.

**Comment by aksonov** [comment]
Feel free to submit PR
