### ISSUE TITLE
Is it possible to use the tabbar like Facebook ?

### ISSUE THREAD

**Issue by petitmat** [aksonov/react-native-router-flux#1573]
Hello,

This is my code :

```
<Scene key="tabbar" tabs={true} tabBarStyle={{ backgroundColor: '#FFFFFF' }}>
          <Scene key="tabA" initial={true} title="tabA" icon={TabIcon} >
                    <Scene key="A_A" initial={true} component={A_A} title="A_A"/>
                    <Scene key="A_B" component={A_B} title="A_B"/>
                    <Scene key="A_C" component={A_C} title="A_C"/>
                    ...
          </Scene>
          <Scene key="tabB" title="tabB" icon={TabIcon}>
                    <Scene key="B_A" initial={true} component={B_A}  title="B_A"/>
                    <Scene key="B_B" component={B_B} title="B_B"/>
          </Scene>
</Scene>
```

You're on a scene (A_X) on tabA and then you change for tabB and you comeback to tabA. The scene on tabA is still A_X, but I want, if you click a second time on tabA to go to the initial scene : A_A. Is-it possible ?

Thanks a lot

**Comment by mgorabbani** [comment]
You can use `ActionConst.RESET`. 
See for details [https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#scene](url)

**Comment by petitmat** [comment]
When I do that, the tabbar is reset and there is only one icon on it, the icon I've just clicked on...
