### ISSUE TITLE
How can I position a view to be on top of the navbar?

### ISSUE THREAD

**Issue by superical** [aksonov/react-native-router-flux#1575]
Right now, the navbar is always on top of every Views added to it.

How can I get a View to show up on top of the navbar? 
In other words, I would like this particular View to be overlapping the navbar.

I've tried setting a View with a style of `position: 'absolute'` with `zIndex: 999`, but this didn't do the trick and the View is still not overlapping the navbar.

**Comment by a20736377** [comment]
top:0

**Comment by superical** [comment]
I have tried setting top:0 and it doesn't work. The navbar is still on top of my view. :/

**Comment by CoteViande** [comment]
Maybe you can use a (Modal)[https://facebook.github.io/react-native/docs/modal.html] on top of your `Scene`

**Comment by kelvinlemus** [comment]
@superical can you try something like this 

1. declare the static method renderNavigation and make your own navigation bar 
```
static renderNavigationBar(props) {
    return (
      <View style={styles.navigationBar}>
        <Text style={styles.navTitle}>Awesome Nav Bar</Text>
      </View>
    )
  }
```

2. add some styles and the views 
```
<View style={styles.container}>
            <View style={styles.topView}>
              <Text>Some Title</Text>
            </View>
            <View style={styles.otherView}>
              <Text>Some Content</Text>
            </View>
          </View>
```
```
navigationBar: {
    height: 56,
    position: 'absolute',
    top: 56,
    left: 0,
    right: 0,
    backgroundColor: 'black',
  },
  navTitle: {
    color: 'white'
  },
  topView: {
    top: 0,
    position: 'absolute',
    height: 56,
    backgroundColor: 'yellow',
    left: 0,
    right: 0
  },
  otherView: {
    marginTop: 56
  }

```

you should see a block, navbar and otherView in order

**Comment by superical** [comment]
@kelvinlemus Thanks! But in this case, the View is still not on top of the custom NavBar. This is how it looks: [Image](http://imgur.com/a/T2Cxf)

Ideally, I have one of the screens which need to have a View overlapping the NavBar.

**Comment by albinhubsch** [comment]
@superical Use <Modal> as @CoteViande proposed! I do it one of our applications and it works very well!

**Comment by superical** [comment]
@albinhubsch @CoteViande Yes, Modal does work. The problem however is that the View I'm working on can be dragged up and down by the user. When the View is dragged down at the bottom of the screen, the user can still interact with other things on the upper part of the screen. 

Problem with Modal is that it will effectively block out all interaction on every elements other than the ones within the Modal. I've tried setting Modal to transparent, but everything else behind the Modal still cannot be interacted. :cry:

**Comment by CoteViande** [comment]
As far as I understand, there are 2 possible cases.

One, you want to add an element on top of your navbar, like an image, for, let's say, design purpose. Where the image/circle/shape is above the navbar. In this case I have no idea how to achieve it.

Two, you want to use the full screen for UI/UX. If you want to display just one thing in a Modal, full screen, it is gonna work. Such as the add friend to your group input in Messenger that pops above your conversations. So it blocks the content while it is visible then is set to visible: false and you can interract with other contents once again.

Could you tell us more about what you want to achieve?

**Comment by superical** [comment]
@CoteViande Thanks for your replies! Sure, what I'm trying to achieve is something like a slide-up panel akin to what Spotify has in their app. Basically, the user can "pull" the panel up from the bottom of the screen. When a user pulls open the panel, it will take up the whole screen. After opening the panel, the user can slide the panel back down to the bottom of the screen. When the panel is slided back down, a tiny part of it is revealed at the bottom of the screen. In other words, this panel is visible throughout the time.

My plan was to make this panel a View which responses to PanResponder gestures. However, I can't find a way to get this View to be on top of the NavBar when it slides up.

Using Modal does get its child View to appear on top of the NavBar. However, a Modal, when visible, consumes every interaction on the screen to itself. In my case, I need the Modal to be always visible even when the slide-up panel is closed because part of it will stay at the bottom of the screen. This will prevent the users from interacting with anything else behind the Modal on the screen. Since I need the Modal to always be visible, I cannot set its visible to false too.

**Comment by andrispraulitis** [comment]
I've tried this but seems that RN zIndex does not work over parent siblings so no luck.

Take a look at the screen shot where my scene is (0_SettingsMenu_), it's deep in the tree and can't overpower NavBar with zIndex. Looks like there is no way unless there is a way to set styles for View key="scenes".

<img width="477" alt="screen shot 2017-02-02 at 23 01 32" src="https://cloud.githubusercontent.com/assets/8721800/22572512/63d8fee2-e99c-11e6-8b6f-70f93bb14074.png">

**Comment by LoreGr** [comment]
@superical have you been able to make it work?

Thanks

**Comment by bilalsyed001** [comment]
@loregr @superical I got similar thing to work using -> https://github.com/magicismight/react-native-root-siblings

Good Luck!
