### ISSUE TITLE
Pop action difference between Android and iOS

### ISSUE THREAD

**Issue by skoob13** [aksonov/react-native-router-flux#1578]
### Version

- react-native-router-flux v3.37.0
- react-native v0.39.2

### Expected behaviour

On multiple Actions.pop() calls when there are no routes to pop shouldn't throw an error "You are already in the root scene".

### Actual behaviour

On iOS the multiple calls of the Actions.pop() won't be an error. On Android the same code throws an error "***You are already in the root scene***".

### Steps to reproduce

1. Run Android simulator or device
2. Call multiple times Actions.pop() when there is more than one scene in stack
3. Error

Is there any solution to handle this error on Android?

**Comment by skoob13** [comment]
Seems like in 0ef1f7a19ca30d99e1892595da5be67a15c8fc22 was firstly introduced this error on Android and removing lines from [121 to 123](https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L121) fixes this issue.

**Comment by afilp** [comment]
I confirm that this behavior has been a problem. Can someone tell us if there is a reason for this warning? I mean why it was added on the first place.

What happens when this code is omitted, I assume the app exits?

**Comment by Swordsman-Inaction** [comment]
Can you check PRs #820 #1049 and #1451 please, that's why I did this. It seems like you got the same issue with #1165, after #1451, this issue has been fixed.
