### ISSUE TITLE
Cannot Style Tabs Text Component

### ISSUE THREAD

**Issue by johnchourajr** [aksonov/react-native-router-flux#1581]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.35.0

### Expected behaviour

I should be able to style the text in the tab bar

### Actual behaviour

I cannot

### Recommendation

1. Add the prop to this component https://github.com/aksonov/react-native-router-flux/blob/b11a84962e4e4d9265770382b8859d21d1a12ea0/src/TabBar.js#L60

**Comment by wangghon** [comment]
@johnchourajr, I suppose you already find a solution since the issue has been for 20+ days.

If not , maybe you can have a try to custom tabIcon, just like the tabIcon in example.
