### ISSUE TITLE
Question: How to add a scene to the stack without actually visiting it?

### ISSUE THREAD

**Issue by Tsury** [aksonov/react-native-router-flux#1583]
I have this structure:

<Router ...>
  <Scene key="sortingScene" ... />
  <Scene key="listScene" .../>
  <Scene key="itemScene" .../>
</Router>

There are 2 ways to open my app - normally and from a notification.
When opening normally sortingScene just navigates to listScene and resets the stack.
When opening from a notification I would like sortingScene to navigate to itemScene, **but to also add listScene to the stack** so that pressing the physical back button/navbar back button will  navigate to listScene.

How can I go about achieving this? I can't find it in the docs.

I am using Actions,[sceneName] to navigate.

**Comment by TrymON** [comment]
I have the same problem

**Comment by mateusz-poliman** [comment]
Have You guys achieved anything in this topic?

**Comment by lirone7** [comment]
Same problem

**Comment by mateusz-poliman** [comment]
as a workaround you can do something like this on notification open:

Actions.listScene({ type: 'reset' });
setTimeout( () => {
    Actions.itemScene();
}, 0);

this will actually render both scenes, but you'll end up with stack you wanted.

**Comment by lirone7** [comment]
Is there a way to do that without render the first scene?

**Comment by mateusz-poliman** [comment]
I've found nothing more, still waiting for that feature..
