### ISSUE TITLE
2 x Drawers (left and right)

### ISSUE THREAD

**Issue by ddolheguy** [aksonov/react-native-router-flux#1585]
Does anyone know if it's possible to have a Scene which inherits from 2 x Drawers (one on the left and another on the right)?

**Comment by ddolheguy** [comment]
Sorry I figured out how to do this.  For anyone else, you can wrap like this 

```
<Drawer
   ref="drawerLeftSide"
   ...>
   <Drawer
      ref="drawerRightSide"
      ...>
      <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
   </Drawer
</Drawer
```

**Comment by chris-at-translate** [comment]
@aksonov Some clean up, this can be closed.
