### ISSUE TITLE
Nested navigators in tabbars

### ISSUE THREAD

**Issue by proProbe** [aksonov/react-native-router-flux#1587]
I would love to understand how to use nested navigators in tabbars. I'm currently not sure how to do this and am wondering if that is because of a lack of documentation or lack of understanding from my side.

So basically, I would love to have `tab1`, `tab2`, `tab3` and have scenes `A`, `B`, `C` that can be reachable from all tabs. If we do `tab1 -> A -> B -> C -> B` and then press `tab2 -> A -> B ->C`, pressing `tab1` again should show the whole `tab1 -> A -> B -> C -> B`-stack. From there pressing `tab2` will show the `tab2 -> A -> B ->C`-stack.

How should this be done?

**Comment by chris-at-translate** [comment]
For help topics its best to ask these sort of question on stackoverflow as there are allot more people there to help you out. But anyway, from the jist of your question you the views that you are wanting to be able accessed from all 3 tabs must still be inside the tablayout, ie meaning you can still see the tabbar if so the way i would personally do it would be having:
`
                    <Scene key={'tab1'} initial={true} component={Tab1}>
                       <Scene key={'tab1A'} component={TabA}/>
                       <Scene key={'tab1B'} component={TabB}/>
                       <Scene key={'tab1C'} component={TabC}/>
                    </Scene>
                    <Scene key={'tab2'} component={Tab1}>
                      <Scene key={'tab2A'} component={TabA}/>
                       <Scene key={'tab2B'} component={TabB}/>
                       <Scene key={'tab2C'} component={TabC}/>
                    </Scene>
                   <Scene key={'tab3'} component={Tab1}>
                      <Scene key={'tab3A'} component={TabA}/>
                       <Scene key={'tab3B'} component={TabB}/>
                       <Scene key={'tab3C'} component={TabC}/>
                    </Scene>`

While you are having to duplicate the scene, in which there is probably a better way to do so. You reuse the components for` A B and C.`  But with different keys to call from each tab.


Like i said the way i would do it and there are probably better ways to do it.
