### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by afilp** [aksonov/react-native-router-flux#1589]
### Version
- react-native-router-flux v3.37.0
- react-native v0.40.0
(windows 10)

When **Debug JS remotely** is **disabled** the app shows this message and cannot start:

![image](https://cloud.githubusercontent.com/assets/7850073/22393228/c729b120-e50b-11e6-86cb-dcbb96ac5695.png)

If it is enabled, everything is OK. Why?

**Comment by afilp** [comment]
@aksonov Any idea how this could be fixed? Thanks a lot!

**Comment by aksonov** [comment]
I don't know how to reproduce it. Sorry, I'm using Mac and iOS only.

**Comment by edmundito** [comment]
@afilp I've gotten the same problem with 0.39 however I am not using react-native-router-flux. Please let me know if you found a solution.

**Comment by agnaf** [comment]
@edmundito This is interesting, I believe that one of our dependencies cause this but do not know which one. In my case, if I remove the *react-native-router-flux* logic and just render a plain *<View />*, it works.

This is why I suspected *react-native-router-flux*.

Can you please let us know if you also use **Windows**?

**Comment by afilp** [comment]
I also see that the problem is caused with "Enable Hot Reloading". When this is ON, the problem occurs unless the **Debug JS remotely** is also ON. If both are OFF, it seems to be working.

**Comment by afilp** [comment]
Major problem: This also happens on the **Release** version, so the app **crashes** immediately after it starts.

See Report bug here:

![image](https://cloud.githubusercontent.com/assets/7850073/22895287/9427b774-f224-11e6-8453-fa3f5a80372a.png)

I hope we can find a solution to this... If someone has any idea or a link to a different issue (on a different package maybe?) please let us know. Thanks!

**Comment by afilp** [comment]
I found something new.

I changed 
`import 'babel-polyfill';`

TO:
`require('babel-polyfill');`

and now it works!

I wonder why (and why the problem was only on Android, not iOS).

The above statement is the 1st one on Main.js component, even above the *React* and *React Native* imports (as the instructions say).

**Comment by suark** [comment]
@afilp Where did you change that? I am having a very similar issue (RN 0.41, windows 10, Android), and it only happens when Hot Reloading is on. Wasn't happening to me before my upgrade from RN 0.35.

I searched the react-native module folder and didn't find any mention of ```babel-polyfill``` except in the package.json

Then I search all of my projects src folder and didn't find any mention of ```babel-polyfill``` as well

**Comment by HelloDeadline** [comment]
I had similar problem but on iPad only. I tested same build on desktop and on Android, but the error occurred only on iPad.  Thanks to @afilp, I checked my webpack config and found that some of dependencies are absent from vendor build. I added them and the problem disappeared.
