### ISSUE TITLE
Repetitive Infinite Tab appearing over itself

### ISSUE THREAD

**Issue by KBLNY** [aksonov/react-native-router-flux#159]
Hi,
I looked for this isssue in the existing issues, but I didn't find.
How to reproduce : check the Example project and select the "Tab" view.
Tap at least twice, or several time on the same selected Tab 1, you will see the View Tab1_1 appearing over itself !
Is there a fix ?
Thanks

**Comment by KBLNY** [comment]
FYI, The "2.0" branch fix the solution, but this is a workaround, not a solution since the 2.0 is still buggy

**Comment by aksonov** [comment]
2.x is official release now, if it is buggy, post issues.

**Comment by KBLNY** [comment]
I found it, due to a stupid mistake:
```
<Route name="tabbar" style={styles.tabBar} >
   <Router footer={TabBar} >
      <Route name="newsFeedTab" schema="tab" title="News" >
         <Router>
            <Route name="newsFeed" title="News" component={NewsFeedPage} />
            // Others routes ...
         </Router>
```
I named the tab and its 1st component with the same `name`.
I now add a suffix "Tab" to the tab `name`.
Done.
