### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by aureldev** [aksonov/react-native-router-flux#1591]
Hi, this is not an issue, just asking for help, and sorry for my bad english I mean thats mainly why I probably missed something in the documentation.
Well I would like to implement authentafication system on my components with firebase, so I already made all my component and here is my Router.js : 

`class RouterComponent extends Component{

	render(){
		return(
			<Router scenes={scenes}/>
		);
	}
}
export default RouterComponent;`
`const scenes = Actions.create(
< Scene key="main">
      < Scene key="login">
              ....
           </ Scene>
 < Scene key="SecondScreen">
              ....
            </ Scene>
</ Scene>
);`

I'm using redux in my application,
so I guess I will have something like that : 
    renderLog = ()  => this.props.isLogging ? 'main' : 'auth'
and a selector={renderLog}
and ofc an redux-thunk watcher for firebase auth, probably created in the componentWillMount I guess

but I tried many thing and it didn't worked.. I know I ask you a lot but it'll help me a probably lot other !:)
I already saw an issue with switch and idk... Thanks for help guys !

**Comment by chris-at-translate** [comment]
Probably more code and more explanation (details) of what you are wanting. I know that your english isn't the best, but try your best.
