### ISSUE TITLE
Reusing scene to push to for different tabs

### ISSUE THREAD

**Issue by Naoto-Ida** [aksonov/react-native-router-flux#1592]
### Version

- react-native-router-flux v3.37.0
- react-native v0.40.0

### Expected behaviour

I want to reuse scenes for different tabs, i.e. a tab containing a list of 'my dogs' pushes to the details page within the same tab, and a tab containing a list of all dogs pushes to the details page within the same tab.

I have two tabs like this:

```
<Scene tabs key='allTabs'>
  <Scene
    key='showMyDogs'
    component='MyDogsContainer'
    icon={<TabIcon />}
  >
    <Scene
      key='showDogDetails'
      component={DogDetailsContainer} />
  </Scene>
  <Scene
    key='showAllDogs'
    component='AllDogsContainer'
    icon={<TabIcon />}
  >
    <Scene
      key='showDogDetails'
      component={DogDetailsContainer} />
  </Scene>
</Scene>
```

The containers are different, as they fetch different data to be rendered in a ListView.
I want to avoid having another scene with a key called 'showMyDogDetails' or something despite the rendering component being the same. Any thoughts? Thanks again.

**Comment by Naoto-Ida** [comment]
Closing this as a comment in #209 suggests the usage of `clone` prop.

**Comment by vincicat** [comment]
Detail example of using `clone` prop is in #750
we need a better example on using tab.

**Comment by Naoto-Ida** [comment]
Ah, I didn't see that issue.
I think `clone` is a very useful prop that should be mentioned more predominantly.
