### ISSUE TITLE
`popTo` and other pop actions modify the behaviour of subsequent actions

### ISSUE THREAD

**Issue by martinarroyo** [aksonov/react-native-router-flux#1594]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.39.2

I have the following router setting for an app:

```jsx
<Router>
    <Scene
    key="root"
    tabs={false}
    hideTabBar={true}>
    <Scene key="main"
        initial={true}
        component={Drawer}
        hideTabBar={true}
        open={false}>
        <Scene key="scenes" tabs={true}>
        <Scene
            key="groupList"
            hideNavBar={false}
            hideTabBar
            initial={false}
            style={{backgroundColor: 'white'}}
            component={GroupList}
            title="Groups" />
        {/*Additional screens*/}
        </Scene>
       <Scene
         key="group"
         component={GroupDetails}
        title="Group" />
    </Scene>
    <Scene
        key="newGroup"
        hideNavBar={false}
        hideTabBar={true}
        component={NewGroup}
        title="New group"
        />
    <Scene
        key="invite"
        hideNavBar={false}
        hideTabBar={true}
        component={Invite}
        title="Invite" />
    {/*Additional screens*/}
    </Scene>
</Router>
``` 

In which the idea is to have a 'New group button' in the `groupList` scene, which pushes the `newGroup`. The user is expected to input some data, and click a 'next' button that takes him to `invite`, where a few more details will be passed. When all data is gathered, a network request is issued and if successful, the app should return to the `groupList` window. For that, I am using:

```jsx
Actions.popTo('groupList');
```

Which works fine in terms of the scene flow, but for some reason, it then makes other actions point to different screens. For instance, if I start the app anew, and do `Actions.group({group: 1})` on a ListView located in `groupList`, it pushes the `group` scene, but if I do the same action *after* going through the aforementioned process, it pushes the `newGroup` tab. It also raises some 'conflicts withanother child' when accessing some of the scenes nested under the `scenes` key.

I am reporting this issue as I do not find this behaviour to be the expected one, but I would also like to know if I am doing something wrong in my Route setup which might be the cause of this.

**Comment by monotv** [comment]
It seems like Actions.popTo does not empty the history stack to the point of the popped to scene properly. The conflicting children that @martinarroyo is talking about are scenes that were pushed on the stack before using Actions.popTo to pop back to the targeted scene. They should not be in the history stack anymore.

**Comment by baetschjunge** [comment]
+1
having the same problem,
even ActionConst.RESET does not empty the stack and scenes are resulting in conflict with children,
it does resetting the route at least

**Comment by baetschjunge** [comment]
@martinarroyo did u find any answer?

**Comment by martinarroyo** [comment]
@baetschjunge I rearranged the screen hierarchy so that newGroup and invite are in the same branch of the tree as the "group" scene. That way the behaviour seemed to be correct.

**Comment by jettandres** [comment]
+1 for this one, too
