### ISSUE TITLE
Build v4 around 'react-navigation' - contributors wanted!

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#1595]
https://reactnavigation.org looks good candidate for new underlying navigation platform.
Some history:
v1 was based on Navigator
v2 was based on exNavigation
v3 was based on react-native-experimental-navigation

Looks like now is time to build v4, react-navigation looks much better than all existing navigators.

**Comment by Steviey** [comment]
But what would be the benefit? React-Navigation has routing and Redux-compatibility on board.

**Comment by aksonov** [comment]
Benefit is to leave RNRF syntax as is that is not changed since v1.

**Comment by Steviey** [comment]
I understand. Are there any advantages for absolute beginners too?

**Comment by MovingGifts** [comment]
I think it's best to contribute to `react-navigation` directly going forward (with the time spent refactoring `RNRF` to integrate with the latest react navigation options). It's a never ending cycle of catching up to the latest version/features, and definitely `react-navigation` is the way forward :)

**Comment by Lenin7** [comment]
Any updates on v4?

**Comment by aksonov** [comment]
@Lenin7 Seems nobody wants to help here.

**Comment by aksonov** [comment]
@MovingGifts I still think that RNRF syntax is better - its syntax/API was not changed during several years. 
Let's hope react-navigation will not change and break own API so often as NavigationExperimental did.

**Comment by Lenin7** [comment]
Seems like this package isnt dying anytime soon. Might as well catch up with `react-navigation` while they are still in beta

**Comment by aayushcoder** [comment]
any updates on v4 using react-navigation ??

**Comment by aksonov** [comment]
I'm researching possible integration but I have very limited time...

**Comment by aksonov** [comment]
Looks like react-navigation is still quite buggy, so I prefer to wait until it will be stabilized.

**Comment by vesper8** [comment]
any update on this? is there going to be a new beta branch opened soon?

**Comment by jemmyphan** [comment]
IMO RNRF's API is better than react-navigation

**Comment by aksonov** [comment]
Okey, guys, I've prepared some 'draft' for v4 based on latest React Navigation library (1.0.0-beta.11):
https://github.com/aksonov/react-native-router-flux/tree/v4/Example

Many features are still missed, it is very very alpha. 
v4 syntax for scenes ("actions") is DIFFERENT from v3 for many reasons:

1. It is pure Javascript, not JSX. As the result we could make unit tests with it and autocomplete works for all existing scenes, like Actions.NAME (in RNRF you had to type it without autocomplete) and 'go to definition' (Cmd+Tap) works for all scenes!
const scenes = new Router({
  modal: {
    initial: true,
    modal: true,
    hideNavBar: true,
    children: () => [scenes.root, scenes.loginContainer],
  },
  root: {
    hideNavBar: true,
    children: () => [scenes.launch, scenes.register],
  },
  launch: {
    hideNavBar: true,
    component: Launch
  },
  register: {
    title: 'Register',
    component: Register
  },
  loginContainer: {
    children: () => [scenes.login, scenes.login2]
  },
  login: {
    component: Login,
    title: 'Login'
  },
  login2: {
    component: Login2
  }

});

2. We could also easily add converter later from 'old JSX-based syntax' to new one so all community could still use old format.

It combines ideas from my statem component - i.e. describe state machine with all transitions as pure javascript functions like:
  a: {
    component: B,
    props: {},
    login: async(username, password) => await loginStore.login(username, password) ? scenes.c() : scenes.refresh({error: 'wrong password'})
  },

This way you can see all transitions in one place and will be core logic of your app.

Please check it, run 'npm test' from Example folder and run ios project. There are many issues left, but core is done. Feel free to send PR to improve, suggest, etc.

**Comment by aksonov** [comment]
Beta was released #1974, closing this ticket. Contributors still wanted for v4...
