### ISSUE TITLE
Custom navBar examples and docs

### ISSUE THREAD

**Issue by asilva2197** [aksonov/react-native-router-flux#1596]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.40.0

I've been looking around for information on how to apply the custom navBar but there is very little information on that. I've managed to use the navBar prop to get the navBar to appear but it does not appear at the top of the viewport. The only way to get it to the top is with absolute positioning but that seems very impractical in terms of having to put margins on the actual content of the page to take the navbar into consideration. I'm just looking for some guidance. Thank you!

**Comment by Wuyue54** [comment]
+1

**Comment by mdeprezzo** [comment]
+1 I've already used the custom NavBar. It show properly on top. But i think that i missed something else, because the navigation between scenes doesn't affect the custom navbar during the native scene transition.
