### ISSUE TITLE
Incorrect FOCUS actions being dispatched for tabs

### ISSUE THREAD

**Issue by ofairfoul** [aksonov/react-native-router-flux#1597]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.39.0

### Expected behaviour

When clicking on a tab bar icon, i would expect a focus action to be raised for the current active tab scene and any active sub-scene if applicable.

### Actual behaviour

The focus action raised is from the top-level scene only

### Steps to reproduce

1. Given this router setup
```xml
<Router>
  <Scene key="root">
    <Scene key="home" tabs>
      <Scene initial key="tab_1" title="Tab 1">
        <Scene initial key="tab_1_1" />
      </Scene>
      <Scene key="tab_2" title="Tab 2" />
    </Scene>
  </Scene>
</Router>
```
2. Tap Tab 2
3. Tap Tab 1
4. `REACT_NATIVE_ROUTER_FLUX_FOCUS` action dispatched for `home` scene only

**Comment by indatawetrust** [comment]
I was having the same problem and I solved it with a small code change.

https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js

line 229

`return { ...state, index: ind };`

`return { ...state, index: ind, name: props.name+'ACTIVE' };`

active tab component is now seen in the following way.

scene.children.filter(child => child.name.match(/ACTIVE/))[0]

**Comment by ssomnoremac** [comment]
@indatawetrust , I don't really understand your implementation. One of these days I'll look at how this router actually works, but for now I just override the `onPress` function of the tabScene to do a refresh and that solves it for me. I only have 3 tabs so it's adding too much bloat.

    <Scene key="tab1" onPress={() => Actions.tab1({type: ActionConst.REFRESH})} />

Another gem from the bizarrely separate ["bonus docs"](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md)

**Comment by ssomnoremac** [comment]
ok, @indatawetrust I tried your solution, but my scene object only gets the children on second render so I modified it 
just doing this in Reducer.js:

    return { ...state, index: ind, name: props.name };

and then on this on the render:

    let sceneName = this.props.scene.children
            ?  this.props.scene.children[0].name
            :  this.props.scene.name

but now my ListView component is acting up when I only render the listView when focused. What a day.

**Comment by duhseekoh** [comment]
This sucks.
