### ISSUE TITLE
Drawer image not showing up 

### ISSUE THREAD

**Issue by weby91** [aksonov/react-native-router-flux#1599]
Hi guys, I wonder why my navigation bar not showing up by default? even if I put the drawer image on the scene

### Version
- react-native-router-flux v3.10.10
- react-native v0.40.0

### Expected behaviour
Drawer (burger icon) should appear on the navbar by default. And when I use the drawerImage props, it should show the icon.

### Actual behaviour
Drawer Image (burger icon) doesn't appear and drawerImage props not working.

### Code
```
const myImage= require('../assets/images/Menu 1.png');
<Scene key="main" initial>
                <Scene key="employeeList" component={EmployeeList} hideNavBar />
                <Scene 
                    key="homeScreen" 
                    component={HomeScreen} 
                    initial
                    tabs
                    sceneStyle={{ paddingTop: 56 }}
                    drawerImage={myImage}
                />
            </Scene>
```

Here's the picture
![image](https://cloud.githubusercontent.com/assets/16458731/22512893/103bcdfc-e8cd-11e6-85a7-c89df1c7ebf6.png)

**Comment by aDEVE** [comment]
It should be a router problem architecture ?

i do like this and it works, ( i'm new, not sure it's the better way) 

```
sidebarButton   = () => (
        <TouchableHighlight onPress={() => { Actions.refresh({ key: 'drawer', open: true }); }}>
            <Image source={require('../assets/img/burger-menu.png')}/>
        </TouchableHighlight>
    );

<Scene key="drawer" component={SideBarContainer} open={false} >
    <Scene key="home" renderLeftButton={this.sidebarButton} type="replace" tabBarStyle={styles.tabBarStyle}>
        <Scene key="A"  title="a" />
        <Scene key="B"  title="b" />
    </Scene>
</Scene>

```

**Comment by weby91** [comment]
@aDEVE thanks for pointing the way out, I changed the Router to Class Based Component and then add a function like that and call it from renderLeftButton props like you did. Thanks man
