### ISSUE TITLE
Notification Count with TabBar

### ISSUE THREAD

**Issue by tylermcginnis** [aksonov/react-native-router-flux#16]
I've learned to ask this question before I start implementing it on my own with this router :)

Is there any way to add Notifications to the Tabbar? Something like this, 
<img width="382" alt="screen shot 2015-10-08 at 11 43 08 pm" src="https://cloud.githubusercontent.com/assets/2933430/10386598/92b374c0-6e16-11e5-8b24-210d30c291ea.png">

Ps great work with the continued progress with this project. Every time I look at it more and more stuff is added. I wouldn't built a RN app without it now.

**Comment by aksonov** [comment]
It is definitely out of scope for this component - this component doesn't represent navbars or tabbars, but only navigation from one component to other

Pavel.
