### ISSUE TITLE
Drawer + Navigation Bar - paddingTop for component visibility

### ISSUE THREAD

**Issue by akusany2** [aksonov/react-native-router-flux#1606]
### Version

- react-native-router-flux v3.37.0
- react-native v0.41.1

### Expected behaviour
After applying paddingTop to Parent/Root component, its child component should be visible just below the Navigation Bar.

### Actual behaviour
Child component is hidden behind Navigation Bar. This thing happened after applying Drawer - I needed to have both Drawer and Navigation Bar on top.

### Steps to reproduce
[Router file link (repo)](https://github.com/akusany2/RNBoiler/blob/master/src/Router.js)

If I add the padding on Router it will give some unusual effect - pushes the Navigation Bar down with the child component.

<img width="375" alt="screen shot 2017-02-04 at 7 57 22 pm" src="https://cloud.githubusercontent.com/assets/3200031/22619938/eb6e38ce-eb25-11e6-8e81-069ebfa45055.png">

I can achieve the desired result by adding paddingTop to children components but that will get hectic later on.

I will not update this repo till I found a solution, so you can check if there is any problem.

**Comment by rom1k** [comment]
I have the exact same problem. Did you find a solution?

**Comment by rom1k** [comment]
I have the exact same problem.

**Comment by fernandovega** [comment]
Delete line 29 
sceneStyle={{paddingTop: Navigator.NavigationBar.Styles.General.TotalNavHeight}}

Works for me

**Comment by akusany2** [comment]
@fernandovega  If I delete `sceneStyle={{paddingTop: Navigator.NavigationBar.Styles.General.TotalNavHeight}}`, the rendered component will be again shift up top behind the NavBar.
