### ISSUE TITLE
missed route data for key=keyValue

### ISSUE THREAD

**Issue by jayspirits** [aksonov/react-native-router-flux#1607]
![screenshot_20170206-094702](https://cloud.githubusercontent.com/assets/14542360/22632129/ad71bf0a-ec51-11e6-8ffb-af6b00a2688c.png)
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.40.0

### Expected behaviour
when clicking logout button, it should redirects to users login page [Action.usersLogin()]

### Actual behaviour
missed route data for key=usersLogin. somehow it cant recognize the key action i set where it supposed to route

### Steps to reproduce
example i have a route like this:
//Router A
Router
   Scene key="usersLogin" component={login} initial
   Scene key="signup" component={signup}
   Scene key="mainPage" component={mainLayout}
/Router

mainPage route/scene renders a component that also defines a new set or group of routes.
for example:
//Router B
Router
   Scene key="tab1" component={tab1} initial
   Scene key="tab2" component={tab2}
   Scene key="tab3" component={tab3}
/Router

so when i route to mainPage it will initially load key tab1 but when i try to route to scene usersLogin or any routes thats on "Router A" it can no longer recognize the route. Is there a way that i can route from a group of routes to another. i designed it this way to group my route based on user roles and routes that needs user authentication.

**Comment by cridenour** [comment]
Unfortunately there's no way to move from Router to Router. I would encourage you to use one router and use additional mechanism for authentication.
