### ISSUE TITLE
How to access right navbar button inside component

### ISSUE THREAD

**Issue by nimamyscreen** [aksonov/react-native-router-flux#1609]
I have a component with few data that must be post to the server.I don't know this is the right way or not , but I need since the user press the post button in navbar , post function will be run inside component.

**Comment by damir-sirola** [comment]
I don't know if this is the best way to do it, but it works:

Inside of the component in which you want to have right navbar button put this code
```
componentWillMount() {
    Actions.refresh({ onRight: this.search, rightTitle: 'Search' });
}
```
