### ISSUE TITLE
Can't get the navigationContext for didfocus and willfocus events

### ISSUE THREAD

**Issue by darkrishabh** [aksonov/react-native-router-flux#161]
the props don't have navigator, which makes it really hard to get the navigationContext. I was using an earlier version before, and that on had it.

**Comment by darkrishabh** [comment]
It worked but by going really deep 
this.props.route.parent.delegate.refs.nav.navigationContext

**Comment by darkrishabh** [comment]
#162

**Comment by aksonov** [comment]
Closing it for now.

**Comment by jackyshek** [comment]
there is no `route` in `this.props`. where can i find the `navigationContext`?
