### ISSUE TITLE
Hide last scene if background is transparent

### ISSUE THREAD

**Issue by georgest** [aksonov/react-native-router-flux#1610]
### Version

- react-native-router-flux v1.0.3
- react-native v0.39

### Expected behaviour

Do not show last scene behind new one if there is no background or if it is transparent, without poping the last scene from navigation stack.

If you have a background image that you want to be shown on all of your scenes, but you want to define it before the Router.
If it is defined init the scene there is background overlapping on animation transition.

<View style={{ flex: 1 }}>
    <Image style={styles.backgroundImage} source={Images.background} resizeMode='stretch' />
    <StatusBar hidden={true} />
    <Router getSceneStyle={getSceneStyle}>
        ...
    </Router>
</View>

Styles for Router:
  flex: 1,
  backgroundColor: 'transparent',
  shadowColor: null,
  shadowOffset: null,
  shadowOpacity: null,
  shadowRadius: null,

**Comment by Jlexyc** [comment]
I've got using custom animationStyle function. But i've got issue with handling POP/PUSH animation.

Have issue:

SCENE1 -(vertical)-> SCENE2 -(horizontal)-> SCENE3

So if I set correct animation for VERTICAL - i'm getting it vertical even for POP from Scene 3 to Scene 2.. but there should be horizontal...
