### ISSUE TITLE
How to directly go to the non-first scene of the sibling scene.

### ISSUE THREAD

**Issue by beiming** [aksonov/react-native-router-flux#1615]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.1

In the following code snippet, how to directly go to `completeInfo` from `login` without executing the `home`?

Thanks.

	<Scene key="root">
	    <Scene key="loginScene">
	        <Scene key="login" component={Login} initial={true}/>
	        <Scene key="register" component={Register}/>
	    </Scene>
	    <Scene key="homeScene">
	        <Scene key="home" component={Home}/>
	        <Scene key="completeInfo" component={CompleteInfo}/>
	    </Scene>
	</Scene>

**Comment by chris-at-translate** [comment]
Set initial={true} on the component you want to goto. Also do this on the login scene if you want that one to come first.

**Comment by beiming** [comment]
@chris-at-translate thanks. it worked. 
> Scenes marked with clone will be treated as templates and cloned into the current scene's parent when pushed. 

If current scene is **home**, then `Actions.completeInfo()`, will clone new **completeInfo** scene? and **homeScene** will contain 3 scenes?
