### ISSUE TITLE
Application crashes when using tabbar after upgrade react native 0.41

### ISSUE THREAD

**Issue by jynlix** [aksonov/react-native-router-flux#1616]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2

### Expected behaviour
tabbar works fine

### Actual behaviour
when changing scene with tabbar ,app crashes

### Steps to reproduce

1.upgrade react native to 0.41.2
2.app runs ok on first scene
3.change to other scene using tabs, app crashes

**Comment by cridenour** [comment]
Can you test with the latest release? Also, can you confirm this is happening in the Example app?
