### ISSUE TITLE
Dynamically changing tab bar title

### ISSUE THREAD

**Issue by arnsa** [aksonov/react-native-router-flux#1620]
### Version

- react-native-router-flux v3.37.0
- react-native v0.41.2

### Problem

When I am changing the language in the app, it updates the state, so the top most app's component (Root) should be updated with the new titles for tab bar. render() method is actually being called with the new titles for the tab bar, but they do not change in the tab bar - old value is being displayed. Why? It seems that there's no way to dynamically change tab bar's title.

**Comment by jonrh** [comment]
I ran into this very issue myself, couldn't find any solution. Would love to know if this a design limitation or of there is an easy solution.

Here is the very hacky solution I came up with:

1. Once language has been changed I write to [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html) two values: `languageChangeRestart: true` and `language: "language_code"`.
2. Reboot/reload the app with [Code Push restartApp()](http://microsoft.github.io/code-push/docs/react-native.html#codepushrestartapp)
3. Startup code checks for the existence of `language` and `languageChangeRestart: true` in AsyncStorage. If so I redirect back to the Settings screen and remove `languageChangeRestart` the variable from AsyncStorage.

**Comment by arnsa** [comment]
@jonrh actually, after many hours of thinking and hacking I've found what works and that was really simple. All I needed to do, was implement FOCUS action like shown here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md Now everything works perfectly!

**Comment by jonrh** [comment]
@arnsa Interesting, thanks for sharing! I'm not using Redux so this never crossed my mind.
