### ISSUE TITLE
disable BackAndroid HardwarePress on bottom scene

### ISSUE THREAD

**Issue by cpsiaki** [aksonov/react-native-router-flux#1621]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2

I'm trying to disable the BackAndroid hardware button when I'm sitting on a certain scene. I've tried using:

```
BackAndroid.addEventListener('hardwareBackPress', () => {...})
```

to control it myself but I can't seem to find a way to get the current scene's "key" If I could test for my "base" key then I would return true and disable BackAndroid. 

Is there another way to do this?

**Comment by cpsiaki** [comment]
Current scene or current router stack i suppose.

**Comment by Amurmurmur** [comment]
You should be able get the scene key/name from props
try to print the following into the console log, to understand what I'm talking about, in your render method:
```
console.log(this.props.navigationState.key)
```

This should return your key, same for name just access the name value inside navigationState.

Hope this helps.
