### ISSUE TITLE
How to hide NavBar on scroll?

### ISSUE THREAD

**Issue by Amurmurmur** [aksonov/react-native-router-flux#1622]
### Version
Tell us which versions you are using: 
- react-native-router-flux v3.37.0
- react-native v0.41.2

### Expected behaviour
Hide on scroll

### Actual behaviour
Doesnt have such feature implemented already.

I tried to set the navigationBarStyle on componentDidMount(), and set position to interpolated animated value like so:
```
componentDidMount(){
      Actions.refresh({
          navigationBarStyle: {
            transform:[
            {translateY: this.state.scrollY.interpolate({
               inputRange: [0, 25, 50],
              outputRange: [-60, 10, 20],
              extrapolate: 'clamp',
                   })}
            ]
        }
      })
  }
```

In my scroll component I pass the following:
```
<ScrollView>
 onScroll={Animated.event(
            [{nativeEvent: {contentOffset: {y: this.state.scrollY}}}]
 )}
</ScrollView>
```

What happens is it just blanks out, and nothing rendered, and React-native starts to eat RAM and than JS Debugger just crashes, I guess it just rerenders all the time :/

Any help would be much appreciated, thanks in advance!

**Comment by cridenour** [comment]
I would create a new NavBar (copy from the repo, rename) and add functionality to listen for an event called StartScroll and hide itself, then unhide itself at the end of the scroll. Then in your component with the scroll, fire off those events (using whatever flux/redux/mobx you choose) based on the scroll.

**Comment by kumarpatel** [comment]
@cridenour How do you fire off events from a given Scene component that are defined within NarBar?
