### ISSUE TITLE
How "Native" Is This Router?

### ISSUE THREAD

**Issue by TamerShlash** [aksonov/react-native-router-flux#1623]
Hello guys,

I'm still new to the RN world and currently I'm comparing the navigation/routing solutions available. I concluded to 3 options that I'm trying to compare, which are:

(1) this solution (`react-native-router-flux`)
(2) [react-native-navigation](https://github.com/wix/react-native-navigation)
(3) [React Navigation](https://reactnavigation.org/)

The part that concerns me the most is how native the solution is. I have seen that in (2) they mention that it's a 100% native navigation solution. This repo, however, doesn't mention anything about that.

Can you guys please tell me if this is a native solution or not?

I would also really appreciate any further info you give on how the 3 mentioned solutions compare to each other.

**Comment by ujwal-setlur** [comment]
react-native-router-flux is not a native solution. It's pure javascript, i believe. The author is [working on a native](https://github.com/aksonov/react-native-router-native) version, but it only supports ios at this time.
