### ISSUE TITLE
Does not navigate to scene if scene exists in nav stack

### ISSUE THREAD

**Issue by laxxers** [aksonov/react-native-router-flux#1626]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.37.0

### Expected behaviour
`Tab A`
|_ `Scene A`
`Tab B`
|_ `Scene B`

`Scene A` has a button to click and navigate to `Tab B`'s `Scene B`.

### Actual behaviour
Does not navigate to `Tab B`'s `Scene B` if `Scene B` is previously opened and existed in the nav stack.

### Steps to reproduce

1. Go to `Tab B` and open `Scene B`
2. Go to `Tab A` and open `Scene A`
3. Click on a button on `Scene A` to try to navigate to `Scene B`

**Comment by cridenour** [comment]
Can you post your router?
