### ISSUE TITLE
Pop all children Scenes when root is removed

### ISSUE THREAD

**Issue by MaxToyberman** [aksonov/react-native-router-flux#1629]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.38.0

### Expected behaviour
1) Press a `TouchableOpacity` on MainScreen  and open a new Scene. 
2) from the client (website ) trigger deletion of the `TouchableOpacity`
3)`TouchableOpacity` is deleted from the main screen and the the Scene is popped.

### Actual behaviour
1)`TouchableOpacity` is deleted in the MainScreen
2)Scene is not popped 

What I need to accomplish is when the triggering scene is popped , all the children are also popped

**Comment by cridenour** [comment]
Can you use `Actions.newScene({type: ActionsConst.RESET})`?

**Comment by MaxToyberman** [comment]
@cridenour it works but this is not the issue... 
I have a listview each view is unique , if i press the second item and move to an other screen and then something changes my list view on the first screen(removes the second view).
the second screen still shows... although it should be popped.
i solved this issue with ReduxRouter by following my scenes

**Comment by cridenour** [comment]
That was going to be my next suggestion. Glad you got it figured out!

**Comment by MaxToyberman** [comment]
@cridenour  it would be nice to have such feature. 
Thank you
