### ISSUE TITLE
Reset on tabbar not always calling componentDidMount

### ISSUE THREAD

**Issue by smaris** [aksonov/react-native-router-flux#1630]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2
- react v15.4.2

### Expected behaviour

Reset on detail item of a tab screen ListView item should always reset and trigger componentDidMount.

### Actual behaviour

Works 2 times, but 3rd time it will not trigger componentDidMount anymore, the component displays a stale DB item which is passed into the "measurementDetail" component for updating the record.

### Steps to reproduce
```
<Router>
  <Scene key="modal" component={Modal} >
    <Scene key="root" hideNavBar={true}>
      <Scene key="splash" component={Splash} hideNavBar={true} duration={duration} type={ActionConst.RESET} initial={true} />
      <Scene key="login" component={Login} hideNavBar={true} panHandlers={null} duration={duration} />
      <Scene key="tabBar" component={TabBar} tabs={true} duration={duration}>
        <Scene key="agenda" component={Agenda} panHandlers={null} duration={duration} />
        <Scene key="measurements" component={Measurement} panHandlers={null} duration={duration} />
      </Scene>
      <Scene key="agendaDetail" component={AgendaDetail} duration={durationSubscreen} />
      <Scene key="measurementDetail" component={MeasurementDetail} duration={duration}  />
    </Scene>
  </Scene>
</Router>
```
When having the "measurements" tab open clicking "save" will execute:
1) update realm.io DB record
2) reset the tabbar to have the updated measurement loaded:
```
Actions.tabBar({selectedTab: 'measurementsTab', type: ActionConst.RESET})
```
The TabBar component uses `react-native-elements`. The TabBar should not be shown when on the "measurmentDetail" screen.

**Comment by maacaro** [comment]
I have the same issue, any help?

**Comment by asimolmez** [comment]
me too.

**Comment by cridenour** [comment]
This might be an upstream bug but honestly I would encourage you to change the structure of your logic to not rely on componentDidMount. Keeping that data in a flux/redux/mobx store will mean all you need is a new render to see the latest data.

**Comment by smaris** [comment]
switched to react-navigation.
