### ISSUE TITLE
Crashing on Actions.pop() on android

### ISSUE THREAD

**Issue by chatras** [aksonov/react-native-router-flux#1636]
### Version
- react-native-router-flux v3.35.0
- react-native v0.38.0

### Expected behaviour
Actions.pop() should pop the window and go back to the previous page

### Actual behaviour
Actions.pop() is crashing the app on android only. And I get this error

> TypeError: expected dynamic type `double', but had type `string'
> getDouble
>     ReadableNativeMap.java:-2
> <init>
>     TransformAnimatedNode.java:55
> createAnimatedNode
>     NativeAnimatedNodesManager.java:101
> execute
>     NativeAnimatedModule.java:190
> doFrameGuarded
>     NativeAnimatedModule.java:112
> doFrame
>     GuardedChoreographerFrameCallback.java:32
> doFrame
>     ReactChoreographer.java:131
> run
>     Choreographer.java:856
> doCallbacks
>     Choreographer.java:670
> doFrame
>     Choreographer.java:603
> run
>     Choreographer.java:844
> handleCallback
>     Handler.java:739
> dispatchMessage
>     Handler.java:95
> loop
>     Looper.java:148
> main
>     ActivityThread.java:5417
> invoke
>     Method.java:-2
> run
>     ZygoteInit.java:726
> main
>     ZygoteInit.java:616
> 

### Steps to reproduce

1. Go to a new scene with a button where action is Actions.pop()
2. Tap on that button 
3. App crashes 

Any help will he highly appreciated! :)

**Comment by cridenour** [comment]
Unfortunately there's not enough here to reproduce. Are you seeing this behavior in the example app?

**Comment by mistenkt** [comment]
I have this exact problem on Android. When trying to pop av view that slides up vertically from the bottom (and back down when popping)

**Comment by aksonov** [comment]
Could you please try v4 beta?

**Comment by mistenkt** [comment]
Last time i tried the v4 (alpha) it had loads of issue, and would require me to rewrite the whole viewstack. does v4 beta support routes in the same way as they were set up in v3?

**Comment by aksonov** [comment]
Yes, it should. Some attributes not supported yet however, please check breaking changes first

**Comment by mistenkt** [comment]
This is super strange. But i have found the cause.

All my components are wrapped with a wrapper component that has a top navbar component. and the views i want to enter/exit vertically send a direction="vertical" prop to the navbar, that then transform rotates the backbutton used to pop the view. Only when this button is rotated does this error happen. the view can still enter/exit vertically as long as the button (arrow) is not rotated.
