### ISSUE TITLE
[question] How should I handle nested tab bars

### ISSUE THREAD

**Issue by Maxwell2022** [aksonov/react-native-router-flux#1637]
I have a main navigation screen defined like this:

```
<Scene key="mainScreenWithTabBar" tabs={true}>
  <Scene key={'A'} component={componentA} title={'Tab A'} />
  <Scene key={'B'} component={componentB} title={'Tab B'} />
  <Scene key={'C'} component={componentC} title={'Tab C'} />
  <Scene key={'D'} component={componentD} title={'Tab D'} />
</Scene>
```

So I end up with 4 tabs, located at the bottom of the screen, and I can navigate through my 4 screens, easy!

Now, on the Scene `C`, just under the `navBar` I want to add 2 tabs to navigate between the default `C` scene and the `Cdetails` scene (using a different component).

However `Cdetails` also has the bottom `TabNab` and the top one too, in order to go back to scene `C`.

Something similar to this:

![image](https://cloud.githubusercontent.com/assets/670701/23052204/945e304a-f523-11e6-9d64-0ce76c75db24.png)

Ideally I would not have to do it like this, but it's a requirement that I have :/

**Comment by cridenour** [comment]
You can create a custom TabBar (copy the one from the source code here) and update the styles, etc. in there to lock itself to the top of the screen vs. the bottom.
