### ISSUE TITLE
Navigate To  child route

### ISSUE THREAD

**Issue by masonwu311** [aksonov/react-native-router-flux#164]
hello,for example ,my route is below：
<Router hideNavBar={true}>

            <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} />
            <Schema name="tab" type="switch" icon={TabIcon} hideNavBar={true} />
            <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottomAndroid} />

            <Route name="login" component={LoginWrapper} title="Login" initial={true} />
            <Route name="content">
                <Router footer={TabBar} hideNavBar={true}>
                    <Route name="stream" title="stream" component={StreamNavigator} schema="tab" initial={true}/>
                    <Route name="popular" title="popular" component={PopularContainer} schema="tab"/>
                    <Route name="notifications" title="notifications" component={NotificationsContainer} schema="tab" />
                    <Route name="user" title="user" component={UserContainer} schema="tab" />
                </Router>
            </Route>
        </Router>

my question is：when i in route login，how i can Navigate To popular

**Comment by pewh** [comment]
Route inside route should be called with prefix '_', so you can navigate to popular by `Actions._popular()`.

**Comment by masonwu311** [comment]
@pewh,first thanks for your answer,i have do this:

```
import _ from 'underscore';
Actions._popular()
```
but i get error below
`TypeError: Actions._task is not a function(…)`
can you help me more

**Comment by pewh** [comment]
No. You don't need `import _ from 'underscore'`. What I've mean is: every route in the parent route should prefix with underscore. For example, you have route `content`, which contains `stream`, `popular`, `notification`, and `user` routes. You can call these routes by `Actions._stream()`, `Actions._popular()`, etc.
Umm it seems I use different version. Please wait for a moment. I'll test on my sample project.

**Comment by masonwu311** [comment]
@pewh ,my version is 
`  react-native-router-flux: "^2.1.3",`
i didnot import  _ from 'underscore',but i get the same error 
`TypeError: Actions._popular is not a function(…)`

**Comment by pewh** [comment]
What the happen if you change that line to:
```
Actions.route('content')
Actions.route('stream')
```
is it working?

**Comment by masonwu311** [comment]
@pewh  the error is below:
`Error: Cannot find router for route= popular current router=undefined(…)`

**Comment by aksonov** [comment]
Usually just Actions.content() or Actions.popular(..) should work, but looks like problem here in lazy loading - "content" Router is not loaded during "login" screen, so Actions were not created...

**Comment by masonwu311** [comment]
@aksonov ,do i have a way to do this

**Comment by pewh** [comment]
@masonwu311 Ummm, mine is working :/
Can you post the content of LoginWrapper?

**Comment by masonwu311** [comment]
@pewh  this is my  router 
`<Router hideNavBar={true} >
         <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
         <Schema name="default"  sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
         <Schema name="withoutAnimation"/>
         <Schema name="tab" type="switch" icon={TabIcon}
           navigationBarStyle={{backgroundColor: '#333'}}
           titleStyle ={{color: '#fff'}}
          />
         <Schema name="tab2" type="switch" icon={TabIcon}
           navigationBarStyle={{backgroundColor: '#333'}}
           titleStyle ={{color: '#fff'}}
           renderLeftButton = {(navigator, index, state) =>{
             return (<HeaderBar title="筛选" action='filterTaskShow'/>)
           }}
           renderRightButton = {(navigator, index, state) =>{
             return (<HeaderBar title="添加" action='addTaskShow'/>)
           }}
          />

         <Route name="launch" component={Start} initial={true} hideNavBar={true}  wrapRouter={true} />
         <Route name="login" component={Login}  hideNavBar={true}  wrapRouter={true} />
         <Route name="register" component={Register}  hideNavBar={true}  wrapRouter={true} />
         <Route name="findPassword" component={FindPassword}  hideNavBar={true}  wrapRouter={true} />
         <Route name="username" component={Username}  hideNavBar={true}  wrapRouter={true} />

         <Route name="tabbar" wrapRouter={true} >
              <Router footer={TabBar}  showNavigationBar={false}
                tabBarStyle={{borderTopColor:'#ccc',borderTopWidth:1,backgroundColor:'#fefefe'}}
                wrapRouter={true}
                >
                  <Route name="message" schema="tab" title="消息"  component={Message} />
                  <Route name="task" schema="tab2" title="日程"  component={Task} />
                  <Route name="linkman" schema="tab" title="通讯录"  component={Linkman} />
                  <Route name="discover" schema="tab" title="发现"  component={Discover} />
                  <Route name="setting" schema="tab" title="我的"  component={Setting} />
              </Router>
          </Route>

     </Router>`  
and this is my login page's code :
`  setToggleTimeout () {
    setTimeout(
       async () => {
         try{
           let oauthToken = await Storage.get('userToken');
           let now = Date.parse(new Date());
           if( oauthToken.expressLogin>now){
             Actions.route('task')
           }else {
             Actions.login();
           };
         }catch (e){
           console.log(e);
           //Actions.login();
         }
       },
       200
     );
 }

 componentWillMount () {
    this.setToggleTimeout();
 }`

**Comment by pewh** [comment]
What the happen if you delete `wrapRouter={true}` on tabbar route?

Then, you can try delete `footer={TabBar}` or change `componentWillMount` to `componentDidMount`. Let me know if you still get an error.

**Comment by pewh** [comment]
It seems you add `wrapRouter={true}` on login route. What the happen if you delete it?

**Comment by masonwu311** [comment]
@pewh  i have the  same error ：
`Error: Cannot find router for route=task current router=undefined(…)`
if what ever i add wrapRouter={true} or remove it

**Comment by masonwu311** [comment]
@pewh  thank you very much

**Comment by aksonov** [comment]
@masonwu311 Please provide working example git repo to reproduce this issue.

**Comment by masonwu311** [comment]
@aksonov，sorry， i did not solve this problem， i will review next time

**Comment by thecodecafe** [comment]
So... You mean you built this package and added support for tabbed navigation and didn't think someone will need to navigate from inside one tab to another?
