### ISSUE TITLE
Tab Navigation Button 

### ISSUE THREAD

**Issue by dioxmio** [aksonov/react-native-router-flux#1640]
Hi,

I'm using the react-native-router-flux with react-native-tabs. It's all working good but I can't see to find a feature on the docs. I want to one of the tabs to be just a button with no view to forward to. Is that possible to do? This is a common pattern where sometimes there's a button in the middle of the navigation bar.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.7
- react-native v15.4.2

### Expected behaviour

To have a tab button which will perform an action and not forward to another view.

**Comment by dioxmio** [comment]
anybody is able to help there??

**Comment by hasLandon** [comment]
You could override the `onPress` prop of the `Scene` to essentially do nothing

**Comment by cridenour** [comment]
If @hasLandon's suggest did not work for you, you should create a custom TabBar (copy the one from our source) and add your button / View there - and make it do as much or as little as you want.

**Comment by dioxmio** [comment]
@hasLandon your solution works. 
@cridenour a custom tab bar seems an overkill. I could be adding this behaviour through a property if needed. I think it would make more sense to have an option for it instead of this hacky solution. By having it as a property it could be included in documentation and would be more intuitive for people to use.

**Comment by cridenour** [comment]
@dioxmio I personally believe in less options and more inheritance, which is why I always suggest a custom component. I'm glad you were able to get this to work without it - but as someone who has a custom tab bar, it's really not a lot of work and feels cleaner. I'm going to close this issue, but feel free to open a PR if you believe there is an easier way!
