### ISSUE TITLE
Use RNRF with redux-sagas

### ISSUE THREAD

**Issue by brendan-rius** [aksonov/react-native-router-flux#1641]
### Version
- react-native-router-flux v3.37.0
- react-native v0.41.2

### Expected behaviour

I would like to be able to navigate by dispatching actions, so I can use RNRF with redux-sagas this way:

```javascript
import {Actions as NavigationActions} from 'react-native-router-flux'

export function * login({username, password}) {
  const response = yield call(API.login, username, password)

  if (response.ok) {
    yield put(NavigationActions.mainScreen()) // <----- here
  }
  else {
    yield put(NavifationActions.errorScreen()) // <---- here
  }
}
```

### Actual behaviour

calling `NavigationActions.XXX()` already calls `dispatch`. I would like to have the object it calls `dispatch` with so I could call `yield put()` it in my sagas.

**Comment by holden-caulfield** [comment]
I had a similar problem and at least for me using `call` instead of put did the job

So you'd do something like 
```javascript
import {Actions as NavigationActions} from 'react-native-router-flux'

export function * login({username, password}) {
  const response = yield call(API.login, username, password)

  if (response.ok) {
    yield call(NavigationActions.mainScreen) // <----- here
  }
  else {
    yield call(NavifationActions.errorScreen) // <---- here
  }
}
```

**Comment by jjhesk** [comment]
+1 do u have more examples on how saga works?

**Comment by brendan-rius** [comment]
Thanks @holden-caulfield 
@jjhesk, you should take a look at [the official documentation of redux-sagas](https://redux-saga.github.io/redux-saga/)
