### ISSUE TITLE
Animation between scene with custom navbar

### ISSUE THREAD

**Issue by mdeprezzo** [aksonov/react-native-router-flux#1648]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.40

### Expected behaviour
I'm using in my custom navbar the ToolbarAndroid component. But when i navigate from a scene to another, the animation slide doesn't affect the custom navbar, like the default navbar. So i'm missing something ? Any suggestions ?

To reproduce that, you can simply pass a custom NavBar like props for a scene

**Comment by cridenour** [comment]
What does your NavBar look like? You should look at the real one for inspiration (or as a starting place) if you want it to behave similar. 

https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js

**Comment by mdeprezzo** [comment]
Maybe my question wasn't clear. I mean, that i'd like to know, how include the custom navbar, on the slide animation of the scene, like the native android animations.
Because right now, only the title is affected from slide animation.

**Comment by cridenour** [comment]
The real NavBar is an Animated.View instead of a normal one, so I imagine that is requirement number one. However, there's no documented list of requirements for this so I would encourage you to start all Custom NavBars by copying the one I linked and customizing from there vs. a fresh component.

**Comment by mdeprezzo** [comment]
Ok thanks man.

Il 1 mar 2017 20:33, "Chris Ridenour" <notifications@github.com> ha scritto:
