### ISSUE TITLE
How to enable transition animation between screen with action reset?

### ISSUE THREAD

**Issue by weeravit** [aksonov/react-native-router-flux#1650]
Do you have any idea?

- react-native-router-flux v3.37.0
- react-native v0.41

**Comment by cridenour** [comment]
I have done this in the past by allowing the transition to happen normally (with animation) and then after the transition, calling Actions.reset(); 

This may or may not work for your case.

**Comment by kumarpatel** [comment]
@cridenour not sure if I understand your approach.
How do you trigger a normal scene transition if you haven't called `Actions.reset()` yet?

Could you provide an example?
