### ISSUE TITLE
Add interactive / gif demo and examples

### ISSUE THREAD

**Issue by ChenLi0830** [aksonov/react-native-router-flux#1654]
Thank you for the repository, I really like it so far. Can you add more demos in which does what? For example, Modals, Sub-Scenes, etc. An image is worth a thousand words. :D

**Comment by cridenour** [comment]
A demo is worth a thousand pictures! I would encourage you to check out the example app provided with the repository. That said, this could be a great contribution to this repository. Thanks for the idea.
