### ISSUE TITLE
Performance question for lots of tabs with large lists. They don't get unmounted when switching? How to make it faster?

### ISSUE THREAD

**Issue by booboothefool** [aksonov/react-native-router-flux#1659]
Looking into the performance issues in my app and I was wondering how tabbing works. 

I noticed my app slows down a ton when I:
1) scroll down a long list ~1500 items
2) fetch a lot of data that is displayed on lists

so imagine clicking a bunch of 

Tab = this library's tabs
Sub Tab = https://github.com/skv-headless/react-native-scrollable-tab-view

loading a bunch of 
lists from pretty much every screen (if you load them all, the app basically slows to a crawl and explodes on older phones):

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/13257645/23644609/21979162-02d6-11e7-9830-c0d925196053.jpg)

Would something like this cause performance issues? Do all of these just get held in memory when switching between tabs, not being cleaned up? Is there anything I can do to mitigate any performance issues so my app doesn't explode with all of this data? That's what it's doing, but I am not sure of the cause.

**Comment by cridenour** [comment]
If memory serves, the unmounting is left up to RN and not this library (I don't think we have that control).

**Comment by miklschmidt** [comment]
Are you using ListViews?

**Comment by booboothefool** [comment]
I updated my initial post with a picture to better illustrate what I'm talking about and what my app does. 

@miklschmidt I am using ListViews in most cases. In other cases where the number of items is smaller, like capped to 12 items, I am just doing a map on an array of objects.

**Comment by codesinghanoop** [comment]
I just solved this by sending one unique param from where i am pushing the same scene and checking the previous and nextprops in componentWillReceiveProps(nextProps)  and if there is change in unique param then i simply update my dataSource and new list gets rendered :)
