### ISSUE TITLE
Can't set Tab Screen to initial screen

### ISSUE THREAD

**Issue by paulbao** [aksonov/react-native-router-flux#166]
render() {
        return (
            <Router hideNavBar={true} name="root">
                <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
                <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                <Schema name="withoutAnimation"/>
                <Schema name="tab" type="switch" icon={TabIcon} />

                <Route name="register" component={Register} title="Register"/>
                <Route name="home" component={Home} title="Replace" type="replace"/>
                <Route name="login" schema="modal">
                    <Router name="loginRouter">
                        <Route name="loginModal" component={Login} schema="modal"/>
                        <Route name="loginModal2" hideNavBar={true} component={Login2} title="Login2"/>
                    </Router>
                </Route>
                <Route name="register2" component={Register} title="Register2"  schema="withoutAnimation"/>
                <Route name="error" type="modal" component={Error}/>
                <Route name="tabbar" initial={true}>
                    <Router footer={TabBar} showNavigationBar={false}>
                        <Route name="tab1" schema="tab" title="Tab #1" >
                            <Router onPop={()=>{console.log("onPop is called!"); return true} }>
                                <Route name="tab1_1" component={TabView} title="Tab #1_1" />
                                <Route name="tab1_2" component={TabView} title="Tab #1_2" />
                            </Router>
                        </Route>
                        <Route name="tab2" schema="tab" title="Tab #2" hideNavBar={true}>
                            <Router onPop={()=>{console.log("onPop is called!"); return true} }>
                                <Route name="tab2_1" component={TabView} title="Tab #2_1" />
                                <Route name="tab2_2" component={TabView} title="Tab #2_2" />
                            </Router>
                        </Route>
                        <Route name="tab3" schema="tab" title="Tab #3" component={TabView} />
                        <Route name="tab4" schema="tab" title="Tab #4" component={TabView} />
                        <Route name="tab5" schema="tab" title="Tab #5" component={TabView} />
                    </Router>
                </Route>
                <Route name="launch" header={Header} component={Launch} wrapRouter={true} title="Launch" hideNavBar={true}/>
            </Router>
        );
    }

Just move  initial={true} to tabbar and the example project got 'route is not defined' error.

**Comment by lentg** [comment]
`
render() {
    return (
        <Router hideNavBar={true} name="root">
            <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
            <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
            <Schema name="withoutAnimation"/>
            <Schema name="tab" type="switch" icon={TabIcon} />


            <Route name="tabbar" initial={true}>
                <Router footer={TabBar} showNavigationBar={false}>
                    <Route name="tab1" schema="tab" title="Tab #1" >
                        <Router onPop={()=>{console.log("onPop is called!"); return true} }>
                            <Route name="tab1_1" component={TabView} title="Tab #1_1" />
                            <Route name="tab1_2" component={TabView} title="Tab #1_2" />
                        </Router>
                    </Route>
                    <Route name="tab2" schema="tab" title="Tab #2" hideNavBar={true}>
                        <Router onPop={()=>{console.log("onPop is called!"); return true} }>
                            <Route name="tab2_1" component={TabView} title="Tab #2_1" />
                            <Route name="tab2_2" component={TabView} title="Tab #2_2" />
                        </Router>
                    </Route>
                    <Route name="tab3" schema="tab" title="Tab #3" component={TabView} />
                    <Route name="tab4" schema="tab" title="Tab #4" component={TabView} />
                    <Route name="tab5" schema="tab" title="Tab #5" component={TabView} />
                </Router>
            </Route>

            <Route name="register" component={Register} title="Register"/>
            <Route name="home" component={Home} title="Replace" type="replace"/>
            <Route name="login" schema="modal">
                <Router name="loginRouter">
                    <Route name="loginModal" component={Login} schema="modal"/>
                    <Route name="loginModal2" hideNavBar={true} component={Login2} title="Login2"/>
                </Router>
            </Route>
            <Route name="register2" component={Register} title="Register2"  schema="withoutAnimation"/>
            <Route name="error" type="modal" component={Error}/>
            <Route name="launch" header={Header} component={Launch} wrapRouter={true} title="Launch" hideNavBar={true}/>
        </Router>
    );
}
`

**Comment by paulbao** [comment]
What's the difference?@lentg
tabbar Route's defined before others? That doesn't work too.

**Comment by lentg** [comment]
Tab route. before other router, work.
