### ISSUE TITLE
Navigation Bar: Back button No changing color

### ISSUE THREAD

**Issue by jasmo2** [aksonov/react-native-router-flux#1662]
Hello I am trying to change the back color but it is not working.
I would like it to change the color to red too.

<img width="318" alt="screen shot 2017-03-01 at 11 55 18 am" src="https://cloud.githubusercontent.com/assets/4839412/23470884/958280f6-fe75-11e6-8a56-de4ce9b32408.png">

**Comment by jasmo2** [comment]
I found the solution:
[issues/460](https://github.com/aksonov/react-native-router-flux/issues/460)

**Comment by jasmo2** [comment]
```
const styles = StyleSheet.create({
  backButton: {
    tintColor: 'white'
  }
})

// ...later

<Scene key='foo' component={Foo} leftButtonIconStyle={styles.backButton} />
```

**Comment by zjjjjjjjjjjd** [comment]
Thanks，this works for me！
