### ISSUE TITLE
A scene takes time to close

### ISSUE THREAD

**Issue by yakirbu** [aksonov/react-native-router-flux#1664]
- react-native-router-flux v3.37.0
- react-native v0.41.2

Hi,
I have listview with items, when the user taps on an item,
I run this code:
`Actions.details( { type: ActionConst.PUSH_OR_POP, id: this.props.item._id } );`
And it opens a scene with details about the item.

### Expected behaviour
If I click on an item, it opens a scene with the details about it, and if I click the back-button and immediately click on **another** item, it should open the same scene but with the new item details.

### Actual behaviour
if I click the back-button and immediately click on **another** item, It opens the previous item details and not the one that I clicked. 
But if I wait 5 seconds and then open other item, it works fine.

It seems like when clicking the back-button it takes some time until the scene is deleted, and if you immediately click on other item , it will just open the same scene that wasn't closed.

Let me know if you need more details.

**Comment by Amurmurmur** [comment]
try to play with:
componentWillMount() and componentWillUnmount()

In other words do things (replace data or check if the component is still mounted)
Hope this helps 👍

**Comment by yakirbu** [comment]
@Amurmurmur 
Hi,
I don't think of something that I can do in these methods that would solve this, since when I close the scene and click on another item the same scene opens with the same data (a new item id wasn't passed as props as it should (       `Actions.details( { type: ActionConst.PUSH_OR_POP, id: this.props.item._id } )`      ), so I can't manipulate this to work)

**Comment by yakirbu** [comment]
Hi! To those who encouter the same issue, just set the duration of the animations to 0, but make sure you do that in the **router** and not scene, as setting animation duration in scene doesn't affect back-button animations.
