### ISSUE TITLE
Update title value from the server

### ISSUE THREAD

**Issue by maanick90** [aksonov/react-native-router-flux#1665]
Hello,

I've 3 tabs to navigate between screens. The title of each tab gets its value from the server. 

Inside 'componentDidMount()', a REST call is made to the server asynchronously and the tab titles are stored in a state variable called 'this.state.bottomTabTitlesList'

In the meanwhile, 'render()' runs once and the tabs are created without any title values being displayed. When the state values are changed (after getting the values from the server), 'render()' is automatically called again and I was expecting that the title values would change for each tab, but it did not happen.

Could you please help me out in displaying the new title values from the server? If 'Action.refresh()' would work, from where should I run it? Can I run it from a normal js method?

![capture](https://cloud.githubusercontent.com/assets/6627116/23485981/a879a012-fea3-11e6-9c0a-97ba923b4798.JPG)

**Comment by Amurmurmur** [comment]
> Could you please help me out in displaying the new title values from the server? If 'Action.refresh()' would work, from where should I run it? Can I run it from a normal js method?

Whenever you receive your request back from the rest, you can do Action.refresh() inside the 
```
componentWillReceiveProps(nextProps){
nextProps && nextProps.yourTitle && Actions.refresh({title: nextProps.yourTitle})
}
```

Hope this helps 👍

**Comment by maanick90** [comment]
Hi Amurmurmur, thanks for your response. 

I am not using Redux in my development. Is there any way that I can achieve without using Redux?

I read from https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops that calling _this.setState_ will not trigger _componentWillReceiveProps_

**Comment by cridenour** [comment]
Just call Actions.refresh from wherever you are handling the response from your server.
