### ISSUE TITLE
would like to stack stacks infinitely,

### ISSUE THREAD

**Issue by satsuki0221** [aksonov/react-native-router-flux#1666]
- react-native-router-flux v3.38.0
- react-native v0.41.2

Hi,
I would like to stack stacks infinitely,
The operation gets heavier as the number of times increases.
I would like to continue using direction vertical,
Type: ActionConst.RESET puts you in trouble with behavior change
How do you solve it?

sorry I made this sentence in Google Translate.

**Comment by cridenour** [comment]
Hi @satsuki0221.

Are you wanting the back button to continue to work?

**Comment by satsuki0221** [comment]
Hi @cridenour
thank you
I want to continue without saving ActionConst.PUSH to a children in the state

**Comment by satsuki0221** [comment]
Hi 
It was self-solved.
Thank you.

**Comment by duhseekoh** [comment]
@satsuki0221 - How did you get infinitely nesting scenes?
