### ISSUE TITLE
eval('Actions.'+ROUTE_NAME+'()')

### ISSUE THREAD

**Issue by woodwoodchow** [aksonov/react-native-router-flux#1670]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.41

### Expected behaviour
Push to `ROUTE_NAME` scene.

### Actual behaviour
Actions is not defined

### Steps to reproduce

Just the code I mentioned in the title.

**Comment by cridenour** [comment]
`Actions.refresh({key: ROUTE_NAME, ... })`

**Comment by nlug** [comment]
@cridenour It's actually not working for me. Can you tell me any solution to make it work whenI has route's name is string so I cant do like this `Action.ROUTE_NAME`

**Comment by chitezh** [comment]
I think` Actions[ROUTE_NAME]()` should work
