### ISSUE TITLE
Get rid of small line between scenes

### ISSUE THREAD

**Issue by mxmtsk** [aksonov/react-native-router-flux#1673]
### Version
- react-native-router-flux v3.38.0
- react-native v0.4.2

### Expected behaviour

No line between scenes

### Actual behaviour

There is a small line when transitioning between scenes. Is it possible to get rid of it?

### Steps to reproduce

Give two scenes a background color that is not white and transition between the two

<img width="436" alt="bildschirmfoto 2017-03-04 um 12 13 07" src="https://cloud.githubusercontent.com/assets/4848184/23578300/2ba30dd4-00d4-11e7-8e0c-6e46b6d6a69b.png">

**Comment by jp928** [comment]
+ 1
