### ISSUE TITLE
react-native-router-flux onright implementation to change the state variable

### ISSUE THREAD

**Issue by ugendrang** [aksonov/react-native-router-flux#1675]
I am trying to make right button ('Add') on navigation bar using react-native-router-flux. When I press this Add button, CategoryList state 'addVisible' should set to false.

`    <Scene key="CategoryList" component={CategoryList} title="Category" initial rightTitle="Add"  onRight={() => { console.log('context'); }}/>`

` import { combineReducers } from 'redux';`
`import categoryReducer from './CategoryReducer';`
`import routerReducer from './RouterReducer';`
`const reducers = {`
`  categoryReducer,`
`  routerReducer`
`}`
`const rootReducer = combineReducers(reducers);`
`export default rootReducer;`

`export default class index extends Component {`
`  render() {`
`    return (`
`      <Provider store={store}>`
`        <Router scenes={scenes}/>`
`      </Provider>`
`    );`
`  }`
`}`

`export default class CategoryList extends Component {`
`  constructor(props) {`
`    super(props);`
`    this.state.addVisible = true;`
`  }`
`}`

The main intention is to set the state variable addVisible = false on pressing 'Add' in Navigation bar in CategoryList component  and if the value is false then Navigation bar should be invisible or hidden. Any suggestion please.

**Comment by miklschmidt** [comment]
This is generally a problem with the onRight feature. In my case i need to reuse route params, but since you don't have access to anything, you can't do much with that function.

**Comment by miklschmidt** [comment]
Apparently navProps is supplied to the renderRightButton function. You could make it a scene prop instead of a state variable. Then you can toggle it by calling Actions.refresh({addVisible: true|false}).

**Comment by ugendrang** [comment]
Kindly advise how to achieve the below steps?
1. On pressing 'Add', NavBar need to hide from current scene
2. The component '<View><Text>Show NavBar</Text></View>' in current scene need to be set to visible 
3. On selecting the text 'Show NavBar', the component at step 2 need to be set to hidden and NavBar to be set to visible

**Comment by Amurmurmur** [comment]
@ugendrang In your onSomething() methods, just use:
`Actions.refresh({onRight: ()=> alert('onRight'), hideNavbar: false, ...otherProps})`

In order to pass new props to the scene when some form of actions happens.

Hope this helps 👍

**Comment by ugendrang** [comment]
Thank you. NavBar is set to invisible with the following code line,
`<Scene key="CategoryList" component={CategoryList} title="Category" initial rightTitle="Add" onRight={() => Actions.refresh({hideNavBar: true})}/>`

But when i assign the hideNavBar value to prop or state as shown below, iam getting the exception 'Attempted to assign to readonly property'.

  `componentWillReceiveProps(nextProps){`
  `  if(nextProps.hasOwnProperty('hideNavBar')){`
  `    this.props.showAddCategory = !nextProps.hideNavBar;`
  `  }`
  `}`

Any thought on how to get rid of the error.

**Comment by cridenour** [comment]
You can't assign a prop in your component. You should be using state to store that information.

**Comment by Chris533** [comment]
componentWillMount () {
    this.fetchCarts()
    Actions.refresh({
      rightTitle: 'Edit',
      onRight: () => {
        Actions.refresh({isBulkEdit: true})
        console.log(this.props.isBulkEdit)
      }
    })
 }

componentWillReceiveProps (newProps) {
     if (newProps.isBulkEdit) {
      this.setState({
        isBulkEdit: !this.state.isBulkEdit
      })
      Actions.refresh({isBulkEdit: false})
    }
}
