### ISSUE TITLE
Actions.pop({ key: 'scene' }) should be documented

### ISSUE THREAD

**Issue by pocesar** [aksonov/react-native-router-flux#1676]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

I found out, by pure luck, that I could pop a whole parent using `Actions.pop({ key: 'scene' })` and it's not documented, and it's super useful to go back exactly where you want

**Comment by bsiddiqui** [comment]
@pocesar what if that scene isn't in the stack?

**Comment by bsiddiqui** [comment]
Just tested this and it doesn't seem to behave any different than `Actions.pop()`

**Comment by pocesar** [comment]
try to do with nested Scenes, you'll understand the limitation of Actions.pop()

**Comment by bsiddiqui** [comment]
got it, I misunderstood that this was specific to nested scenes

**Comment by Tahir-Bitsol** [comment]
@pocesar Can you give me a detailed example 
i am trying
`NavigationActions.pop({key: 'checkoutScreen'})`
but it does not work
