### ISSUE TITLE
Screen disappears after screen orientation rotation and subsequently crashes

### ISSUE THREAD

**Issue by oatcrunch** [aksonov/react-native-router-flux#1677]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^3.37.0
- react-native v0.40.0

### Expected behaviour
App should not crash.

### Actual behaviour
App crash.

### Steps to reproduce

1. From main screen (screen 1), tap a button to go to next screen (screen 2).
2. On screen 2, I enable my phone screen rotation.
3. I rotate my screen (from portrait to landscape).
4. Screen 2 suddenly disappears (the moment orientation changed) and return back to screen 1.
5. Tap again on that button to attempt to go to screen 2.
6. Crash!

Appreciate kind attention on this.

**Comment by cridenour** [comment]
Can you reproduce this in the Example app provided or just in your own app? May be something more going on here.

**Comment by oatcrunch** [comment]
Hi, I tried the Example.js but couldn't reproduce. However, my use case is a little different. Assuming I am in "Home" (1 of the tabs in tabbed scene), and I click on a link that will navigate me away to "Demo" (tab_1, refer codes below) scene (single page scene). I am able to navigate to that scene, but the moment i rotate my phone orientation, "Demo" scene disappears and I return back to "Home". However, when I click on the link again in attempt to return to "Demo", it crashes. Please help.

This is my router:

    <Router createReducer={reducerCreate}>
                <Scene key="modal" component={Modal} >
                    <Scene key="root" hideNavBar hideTabBar >
                         <Scene
                                        key="tab1_1"
                                        component={Demo}
                                        title="Tab #1_1"
                                        onRight={() => alert('Right button')}
                                        rightTitle="Right"
                                    />
                        <Scene key="launch" component={Launch} title="Launch" initial />
                        <Scene key="tabbar" component={NavigationDrawer}>
                             <Scene
                                    key="main"
                                    tabs
                                    tabBarStyle={styles.tabBarStyle}
                                    tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle}
                                >
                                  <Scene key="home" component={(props) => {return (<Home {...props} pubSub={PubSub} storage={Storage} />)}} title="Home" initial icon={HomeIcon} navigationBarStyle={Styles.navBarStyle} titleStyle={{color: 'white'}}
                                    renderRightButton={() => {
                                    return <AvatarIcon src={'https://upload.wikimedia.org/wikipedia/en/1/17/Batman-BenAffleck.jpg'} size={40} />
                                    }} drawerImage={{uri: 'https://facebook.github.io/react/img/logo_small.png', width: 38, height: 38}}>
                                       
                                  </Scene>
                            </Scene>
                        </Scene>
                    </Scene>
                </Scene>
            </Router>

This is my Home.js:

     <View style={[Styles.containerBackgroundColor, {flex: 1}]}>
                <ScrollableTabView
                    style={{marginTop: 50}}
                    initialPage={1}
                    renderTabBar={() => <ScrollableTabBar />}
                    >
                    <View tabLabel="test">
                        <TouchableHighlight onPress={() => {
                            Actions.tab1_1();
                            alert('demo');
                            }}>
                            <Text>123</Text>
                        </TouchableHighlight>
                    </View>
                    <Text tabLabel="All"></Text>
                    <Text tabLabel="Eateries"></Text>
                    <Text tabLabel="Accommodations"></Text>
                    <Text tabLabel="Tours"></Text>
                    <Text tabLabel="Misc"></Text>
                </ScrollableTabView>
            </View>

**Comment by 7laria** [comment]
Same issue

**Comment by didil** [comment]
facing exact same issue with same steps as @oatcrunch

**Comment by deguchi** [comment]
Same issue.
I wrote a Drawer the sample of document.

`            <Drawer
                ref="navigation"
                open={state.open}
                onOpen={()=>Actions.refresh({key:state.key, open: true})}
                onClose={()=>Actions.refresh({key:state.key, open: false})}
                type="displace"
                content={<NavigationMenu />}
                tapToClose={true}
                openDrawerOffset={(viewport) => viewport.width - 271}
                panCloseMask={0.2}
                panOpenMask={0.2}
                negotiatePan={true}
                tweenHandler={(ratio) => ({
                 main: { opacity:Math.max(0.54,1-ratio) }
                })}
                tweenEasing={'easeOutCirc'}
                tweenDuration={200}
            >
                <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </Drawer>
`
Drawer's onOpen and onClose properties were the cause of this problem.
