### ISSUE TITLE
Close current scene and move to another

### ISSUE THREAD

**Issue by yakirbu** [aksonov/react-native-router-flux#1678]
Hi, 
I have a simple question that I couldn't find any refrence to it here.
How do I close a current scene and move to another one (without removing all the previous route stack like 'REPLACE' does).

For example, this is my current stack:
A->B  (I'm in B, and I click a button to go to the next page) and then my stack looks like:
A->B->C , what I'm trying to do is close B and then move to C, which should finally look like:
A->C

Thanks

**Comment by harishsn** [comment]
solution ?
