### ISSUE TITLE
How to apply conditional Tabbar style?  

### ISSUE THREAD

**Issue by bexoss** [aksonov/react-native-router-flux#1680]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

### Expected behaviour

There are tabs icon, I want to when tab selected, apply 2px border to bottom of selected tab. 
But I don't know how to apply it. There are tab icons, and each icon color is changed when I select tab. 
But Border, I don't have any idea. 

![1111](https://cloud.githubusercontent.com/assets/12633102/23638972/416b06fc-0328-11e7-8965-a50ffdc14e25.png)

As you can see above, I want to apply border to selected tab.

### Actual behaviour

![2222](https://cloud.githubusercontent.com/assets/12633102/23638975/4650ef2e-0328-11e7-8366-4afc3118f19f.png)

Above is my app shape. 

### Reproduce

Below is part of my code. Could you give me any hints to do that... 

`const TabIcon = ({ selected, title, iconName }) => {
        return (
            <View>
                <Icon
                    name={iconName}
                    color={selected? '#473332' : '#bdb8bc'}
                    size={35}
                    />
                </View>
            )
    };`

`<Provider store={configureStore()}>
                    <Router>
                        <Scene key="root">
                            <Scene key="todoList" tabs tabBarStyle={{ top: 72, height: 76, backgroundColor: '#f1f2f4', borderColor: '#e6e7e9', borderBottomWidth: 1}} initial>
                            <Scene key="osu1" title="First" iconName="list" icon={TabIcon}>
                                    <Scene key="scarlet" component={TabComponent1} hideNavBar title="Scarlet1" initial />
                            </Scene>
                            <Scene key="osu2" title="Second" iconName="alarm" icon={TabIcon}>
                                    <Scene key="scarlet2" component={TabComponent2} hideNavBar title="Scarlet2" initial />
                            </Scene>
                            <Scene key="osu3" title="Third" iconName="settings" icon={TabIcon}>
                                    <Scene key="scarlet3" component={TabComponent3} hideNavBar title="Scarlet3" initial />
                            </Scene>
                        </Scene>
                    </Scene>
                </Router>
            </Provider>`

**Comment by Amurmurmur** [comment]
Try this, most likely the border will appear just above the icon itself, in that case try to change the tabbar style depending on currently selected tab through `tabBarStyle` scene prop.

`const TabIcon = ({ selected, title, iconName }) => { return ( <View style={{borderTopWidth: selected ? 1 : 0, borderTopColor: selected ? 'white' : 'transparent'}}> <Icon name={iconName} color={selected? '#473332' : '#bdb8bc'} size={35} /> </View> ) };`

**Comment by bexoss** [comment]
I realize there is `tabBarSelectedItemStyle` props in tabbar.
