### ISSUE TITLE
'Show Inspector' triggering reset of app

### ISSUE THREAD

**Issue by Naoto-Ida** [aksonov/react-native-router-flux#1681]
### Version
- react-native-router-flux v3.37.0
- react-native v0.41.2

### Expected behaviour
Opening React Native's inspector should not trigger the app to `reset`.

### Actual behaviour

Opening  React Native's inspector triggers a `reset` of the app.
I have searched my code for any Flux-related listeners that could be triggering a `reset`,
but couldn't find any.

Are any of you experiencing this?

**Comment by MattyK14** [comment]
+1

**Comment by Naoto-Ida** [comment]
My workaround is to obviously set the `initial` component to whatever I need to do some inspection on, but this is slowing my dev a bit. Any possible causes for this?

**Comment by jkvim** [comment]
same problem on problem

## Version

react-native-router-flux: ^4.0.0-beta.22
react-native v0.48.3

**Comment by onrige** [comment]
I am also have the same issue. I will try to find the cause but may be someone have any ideas?

**Comment by aksonov** [comment]
Please check latest master

**Comment by daviscabral** [comment]
Notice: this issue has been closed because it has been inactive for more than 30 days.
You may reopen this issue if it has been closed in error.

**Comment by AgingChan** [comment]
I still get the same issue. No fix or workaround available?

**Comment by sryze** [comment]
I have the same problem with 4.0.6, it's impossible to inspect anything. Is it possible to fix this by changing some configuration? or it's a bug?

**Comment by luongs3** [comment]
got the same.

**Comment by ethanyuwang** [comment]
Still have the same issue. Please reopen this issue
