### ISSUE TITLE
renderBackButton() not working anymore

### ISSUE THREAD

**Issue by GCour** [aksonov/react-native-router-flux#1683]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36.0
- react-native v0.34.1

### Expected behaviour

Show a custom back button

### Actual behaviour

It's not showing anymore all of a sudden. When I remove` renderBackButton()` it shows the default button though.

`renderBackButton={() => <BackButton /> }`

```
  render(){
    const { color } = this.props
    return(
      <TouchableOpacity style={ Style.container } onPress={() => { Actions.main({ type:  ActionConst.BACK_ACTION }) }}>
        <View>
          <Icon name="ios-arrow-round-back-outline" size={35} color="#fff" />
        </View>
      </TouchableOpacity>
    )
  }
```

**Comment by renancsoares** [comment]
For me, it's working:

```
const backButton = () => (<Icon name="arrow-back" size={24} color={COLORS.Light} onPress={()=> Actions.pop()} />);

<Scene renderBackButton={backButton} />
```

**Comment by GCour** [comment]
@renancsoares That's not working either here

**Comment by GCour** [comment]
It was a style setting, I had it on 'position: absolute' .. Weird it only fails now
