### ISSUE TITLE
How to Pop To Last Match Scene in the Stack

### ISSUE THREAD

**Issue by gpminsuk** [aksonov/react-native-router-flux#1684]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2

 Let's say current scene stack is
Scene A, Scene B, Scene C, Scene A, **Scene B**, Scene A, Scene C, Scene E, Scene D
with the first Scene A is "root" and Scene D is "current scene" 
I would like to pop to **Scene B** (NOT THE FIRST SCENE B BUT THE SECOND)

How can I achieve that?

I tried popTo but it seems to pop to the first Scene B (first match item. Traverse was root to leaf.)

Thanks,
-Minsuk

**Comment by renancsoares** [comment]
Hi @gpminsuk, see if it can help you: https://github.com/aksonov/react-native-router-flux/issues/1676
I didn't try it, but it might work for you.

**Comment by gpminsuk** [comment]
@renancsoares #1676 does not work for me at all.
I matched react-native and react-native-router-flux version but still no luck..

**Comment by cridenour** [comment]
I don't think there's a way to do this out of the box. Can you describe more of the use case?

**Comment by gpminsuk** [comment]
The use case is that as below we have < back button and x quit button.
The back button should go to the previous scene in the stack and the quit button should go to the initial scene of the scene flow.
![image](https://cloud.githubusercontent.com/assets/3460594/23819390/fbf44f38-0648-11e7-8081-c11e8cc37403.png)


So in above example, we define scene flow starts with Scene B hence
Scene A, [Scene B, Scene C, Scene A], [Scene B, Scene A, Scene C, Scene E, Scene D]

So when user clicks x button on Scene D, it should pop back to Scene B.
