### ISSUE TITLE
Errors when build Example: ':app:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by drgrey87** [aksonov/react-native-router-flux#1688]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

### Expected behaviour
 succesfull deploy
### Actual behaviour

error [http://storage4.static.itmages.com/i/17/0309/h_1489056808_3782221_71443491a9.png](http://storage4.static.itmages.com/i/17/0309/h_1489056808_3782221_71443491a9.png)

### Steps to reproduce

1.react-native run-android

**Comment by drgrey87** [comment]
created pull request #1691

**Comment by cridenour** [comment]
Merged PR. Thanks again.
