### ISSUE TITLE
Change the `tintColor` of the `drawerImage` sent to the `Router`.

### ISSUE THREAD

**Issue by GuillaumeMunsch** [aksonov/react-native-router-flux#1689]
### Version
- react-native-router-flux v3.37.0
- react-native v0.40.0

### Expected behaviour

I'd like to be able to change the `tintColor` of the `drawerImage` prop passed to the `Router`. I have a set of icons that are all red and I use the `tintColor` to alter their color though all my app.

### Actual behaviour

I managed to replace the burger icon of the `Drawer` from `react-native-drawer` thanks to the `drawerImage` on the `Router` but I remains red. (Which is the color of the original icon). 

Is there any way to change this ? I'd prefer not to directly alter my icon because I'm using it in other parts of the app.

Thanks in advance !

**Comment by cridenour** [comment]
Honestly, I would just suggest copying the image and creating an altered version. It's by far the simplest solution and I can't see the justification for adding an option for this.
