### ISSUE TITLE
Tabbed Nested Router Re-use Question

### ISSUE THREAD

**Issue by jgibbons** [aksonov/react-native-router-flux#169]
How would you structure the router if you wanted the nested routes of one tab to be available for all tabs? If you copy all the routes across all tabs then it works; however, I'm sure there is an elegant way.

Thanks for this great library!

**Comment by MITDelian** [comment]
That's basically how you should do it. You can reuse the same components so it's not really too bad and makes it pretty clear in your routes file that you are using the same routing types.

I would still recommend calling the different routes differently. like `tab1_page1` `tab1_page2` & `tab2_page1` `tab2_page2` even if across the two tabs `page1` and `page2` use the same components
