### ISSUE TITLE
Extra Scene needed when using react-native-drawer with Actions.create()

### ISSUE THREAD

**Issue by Dennitz** [aksonov/react-native-router-flux#1690]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.41.2

### Expected behaviour
When creating all scenes directly as children of Router, it is enough to have the drawer scene as the root scene, i.e. 
```
<Router>
  <Scene key="drawer" component={NavigationDrawer} open={false}>
    <Scene key="requiredBecauseOfDrawer">
      <Scene key="scene1" component={Scene1} />
      <Scene key="scene2" component={Scene2} />
    </Scene>
  </Scene>
</Router>
```

So when creating the scenes with Actions.create() I think it should be the same:

```
const scenes = Actions.create(
  <Scene key="drawer" component={NavigationDrawer} open={false}>
    <Scene key="requiredBecauseOfDrawer">
      <Scene key="scene1" component={Scene1} />
      <Scene key="scene2" component={Scene2} />
    </Scene>
  </Scene>
)
```

and then:
`<Router scenes={scenes} />`

### Actual behaviour
When my scenes are defined using Actions.create() and I then click a button to open the drawer, i get the error: 'No parent is defined for route=drawer'.

It works again when I add another surrounding scene, like this:
```
const scenes = Actions.create(
  <Scene key="root">
    <Scene key="drawer" component={NavigationDrawer} open={false}>
      <Scene key="requiredBecauseOfDrawer">
        <Scene key="scene1" component={Scene1} />
        <Scene key="scene2" component={Scene2} />
      </Scene>
    </Scene>
  </Scene>
)
```

### Steps to Reproduce
1. Define scenes using Actions.create() with drawer scene as the top level scene
2. Click button that calls `Actions.refresh({ key: 'drawer', open: true })`

**Comment by jariwalabhavesh** [comment]
@Dennitz :
Have you find any solution beacuse i am facing same issue. after integrating react-native-drawer??
![screen shot 2017-03-20 at 12 31 06 pm](https://cloud.githubusercontent.com/assets/10993666/24090758/22a3bfde-0d69-11e7-813b-62b7aea28a6a.png)

**Comment by Dennitz** [comment]
@jariwalabhavesh 
I went with surrounding the drawer scene with another scene, so that the drawer scene is not the root scene anymore. Just like described in the opening post.

**Comment by jariwalabhavesh** [comment]
@Dennitz: Thanks,i had totally missed that part. have you any idea how we can manage(show/hide) in some scene(like login and registration not needed sidebar so how to hide it?)

**Comment by Dennitz** [comment]
@jariwalabhavesh 
react-native-drawer has a prop 'disabled'. Set this to true and then maybe also override the left navigation bar button

**Comment by vmitchell** [comment]
@cridenour  
I can confirm this behavior, using Action.create is properly documented, however drawer example doesn't work without a necessary wrapper scene as @Dennitz pointed out.
