### ISSUE TITLE
Can't go back using Swipe left if the actual scene contains an Animated.View.

### ISSUE THREAD

**Issue by krailler** [aksonov/react-native-router-flux#1693]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.40.0

### Expected behaviour
Normal swipe back.

### Actual behaviour
When going to a scene with RN Api that contains an animation, swipe back is cancelled or its unresponsive (Very hard to go back with swipe... Back button works but with bad performance). When you do swipe to go back, it hangs in mid of swipe animation and there is no more swipe action... It seems to be cancelled or something. You have to use back button to go back.

### Steps to reproduce

1. Actions.sceneTwo()
2. Scene Two contains a Animated.View inside a normal View.
3. Can't go back using swipe.

**Comment by cridenour** [comment]
Hmm. Can you change one of the views in the Example project to an Animated.View and see if you can reproduce? This sounds like a `panResponder` issue rather than Animation related.
