### ISSUE TITLE
How to add swipe gestures ? 

### ISSUE THREAD

**Issue by Kris4an7** [aksonov/react-native-router-flux#1695]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0?
- react-native v0.42.0?

Hello,
could anyone help me with an issue. I want to use swipe up and swipe down to change between a number of scenes. Is there any way to do this. I want the next scene to fade into the place of the previous one.

Thank you !

**Comment by charlle** [comment]
@Kris4an7 I would recommend adding a Swiper within your routes.  This [library](https://github.com/leecade/react-native-swiper) can accomplish vertical and horizontal swiping.

**Comment by Kris4an7** [comment]
Thanks. I tried it but the vertical doesn't work on android. I think it was because PageViewer doesn't support vertical scrolling on Android. I am researching other ways to do it , but for now I have nothing. Any other tips on how i should go about this would be greatly appreciated.
