### ISSUE TITLE
Switching between animated scenes eventually grinds Android to a halt

### ISSUE THREAD

**Issue by Quirksmode** [aksonov/react-native-router-flux#1696]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0
- tested on google pixel device

### Expected behaviour
Performance should remain smooth when switching between scenes. 

### Actual behaviour
Each time a new scene is selected it slows down a little bit until eventually the app grinds to a halt and becomes unresponsive. This only happens on Android and is perfect on iOS.

### Steps to reproduce

This is my router code:

`<Router
        hideNavBar={true}>
      <Scene
        key="popular"
        component={MostPopular}
        initial
      />
      <Scene
        key="all"
        component={AllNetworks}
      />
      <Scene
        key="search"
        component={Search}
      />
      <Scene
        key="about"
        component={About}
      />
    </Router>`

I am then selecting the scenes using a custom tab component. The reason I am doing it this way is because I need to have a slide animation between each scene and I also need to be able to use 'back' to return to a tab from some of the scenes. 

`<View style={styles.viewStyle}>
          <TouchableOpacity
            onPress={() => { Actions.popular();} }>
            <Text style={styles.title}>Most popular</Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => { Actions.all();} }>
            <Text style={styles.title}>All networks</Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => { Actions.search();} }>
            <Text style={styles.title}>Search</Text>
          </TouchableOpacity>

          <TouchableOpacity
           onPress={() => { Actions.about(); }}>
            <Text style={styles.title}>About</Text>
          </TouchableOpacity>
        </View>`

What can I do to prevent this slow down from occurring whilst allowing me to have sliding transitions a back button that returns to a tab? Any help is really appreciated

**Comment by Quirksmode** [comment]
To add to this, I did some tests and it seems that the slowdown is definitely being caused by the scenes being added to the 'stack' (if we can call it that). The sliding animation is really important to the design of the app, is there a way I can have this animation and refresh the stack? The reverse sliding animation is really nice, is there a way to pop() back to a scene that has a RESET type being applied?

**Comment by comiclee** [comment]
+1 
I found it happens while the animated view has a nav-bar

**Comment by jariwalabhavesh** [comment]
+1

**Comment by ArtsNCode** [comment]
Any workaround!!

**Comment by dsandmark** [comment]
Experiencing the same thing. App gets slower and slower as move between scenes (Android, both Emulator and release APK on device). Perhaps it's due to the stack of scenes not being emptied?

**Comment by dsandmark** [comment]
The performance issue disappears if I add `hideNavBar` to my scenes. It also works to set
```
<Scene
    ...
    type = {ActionConst.RESET}
/>
```

Did any of you find a solution to this that doesn't require resetting the scene stack? @Quirksmode @comiclee @jariwalabhavesh

**Comment by jariwalabhavesh** [comment]
@dsandmark :
Not yet :-(
