### ISSUE TITLE
Swipe to go back

### ISSUE THREAD

**Issue by chrissm79** [aksonov/react-native-router-flux#17]
Is there a way to include a swipe gesture to go back? For instance, if I use the FloatFromRight animation, I would like the user to be able to swipe right to go back.

Great package btw!

**Comment by aksonov** [comment]
I guess default 'right' scene from Navigator enables swipe, so you could use Navigator's defined sceneconfigs and pass it to the component.

**Comment by chrissm79** [comment]
Thank you for the quick response!

I changed the sceneConfig in the example to the following, but I'm not able to get the swipe back gestures to work:

```js
// ...
var React = require('react-native');
var {AppRegistry, StyleSheet,Text,View,Navigator} = React;
//...
    <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromRight} navBar={NavBarModal}/>
    <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} navBar={NavBar}/>
// ...
```

**Comment by chrissm79** [comment]
Looks like gestures is set to an empty object in the Router's getRoute method. If we could have a gesture prop on the Schema or Route you could change gestures to:

```js
var gestures = route.gestures || schema.gestures || {};
//...
sceneConfig: {
    ...sceneConfig,
    gestures: gestures
}
```

and on the schema or route you could use:

```js
<Schema name="default" sceneConfig={Animations.FlatFloatFromRight} gestures={Navigator.SceneConfigs.FloatFromRight.gestures} navBar={NavBar}/>
```

**Comment by aksonov** [comment]
Thanks, check latest version (0.3.3), should be fixed

**Comment by chrissm79** [comment]
Perfect! Thank you!!

**Comment by JoaoCnh** [comment]
How did you get this to work? I can't seem to get swipe to perform a back
