### ISSUE TITLE
Check if router's stack is null before pop()

### ISSUE THREAD

**Issue by jonathanpalma** [aksonov/react-native-router-flux#170]
I was testing "go back" through navBar's button and I could find that if you tap it quickly in the launch page (before it dissapears) it will throw an unhandled exception caused because this function is not checking if the nav stack is already null before try to pop()

![screenshot_2016-02-02-22-42-44](https://cloud.githubusercontent.com/assets/12414771/12773195/b378f43e-c9fe-11e5-9129-548b939d4854.png)

**Comment by jonathanpalma** [comment]
-

**Comment by MITDelian** [comment]
This is something I am working on

**Comment by jonathanpalma** [comment]
Thanks for your answer @MITDelian I'll try to work on it to. 

Also let people know that I decided make a temporary solution to help me fix it on Android devices overloading [BackAndroid](https://facebook.github.io/react-native/docs/backandroid.html)

```javascript
BackAndroid.addEventListener('hardwareBackPress', (function() {
  try {
    if (Actions.pop() != null) {
      return true;
    } else {
      return false;
    }
  } catch (e) {
    return false;
  }
}));
```

**Comment by aksonov** [comment]
@MITDelian Have you submit PR for that?

**Comment by aksonov** [comment]
Please check 3.0 version. Closing it for now (because it is for outdated 2.x)
