### ISSUE TITLE
Unable to resolve module react-native-router-flux

### ISSUE THREAD

**Issue by yorkor** [aksonov/react-native-router-flux#1706]
### Version 
- react-native-router-flux v3.38.0
- react-native v0.42.0

 
Under Windows or Mac, run cnpm install react-native-router-flux  , under node_modules  react-native-router-flux as the junction, rather than a folder ;
So there is an error :  Modules does not exist in the module map or in these directories...

**Comment by phanivaranasi** [comment]
Hi Team,
I too ran into same trouble.
![screenshot_2017-03-24-11-47-12](https://cloud.githubusercontent.com/assets/6230353/24282787/c0a34738-1087-11e7-9e75-799c0c13a316.png)

After executing 
npm i react-native-router-flux --save

**Comment by roseniltonreis** [comment]
Same error.

**Comment by rajesh7020** [comment]
same issue is here

**Comment by rajesh7020** [comment]
![Untitled](https://user-images.githubusercontent.com/8243138/56735868-4c012c00-6784-11e9-9a86-e9d9c6a94c13.png)

**Comment by rajesh7020** [comment]
![Untitleds](https://user-images.githubusercontent.com/8243138/56735932-718e3580-6784-11e9-8520-1ed907de9e72.png)
