### ISSUE TITLE
When going from tab to tab, how do I get the previous tab?

### ISSUE THREAD

**Issue by booboothefool** [aksonov/react-native-router-flux#1707]
Trying to implement going to a tab -> user presses no -> it kicks them back to where they were, however when I look at my props, I have nothing that indicates where they came from.

Any advice?

**Comment by booboothefool** [comment]
I didn't know `Actions.pop()` worked with tabs! Nice!

**Comment by Maxwell2022** [comment]
If the screen you want to go back to is always the same, then just call `Action.screenKeyName({type:...})`, else if this screen is random... 

I'd say... First you need to save the history of the navigation, you can use a reducer that is connecting to the Router to do this, and listen for Focus event to add the current screen to the history stack. Then you can implement you function `navigateToPreviousScreen` for instance that is looking into the history and trigger the Action to get there
