### ISSUE TITLE
Passing data back to parent with Actions.pop?

### ISSUE THREAD

**Issue by jgibbons** [aksonov/react-native-router-flux#171]
It is easy to pass data through a push as seen in the example:
`Actions.login({data:"Custom data", title:'Custom title' }) `
How should it be done when popping back to the parent?

**Comment by jgibbons** [comment]
The parent can just pass a callback function through props.

**Comment by kimorq** [comment]
you can use Actions.refresh({data:"Custom data", title:'Custom title' }) immediately after Actions.pop() and this will do the trick. Refresh will be called on the parent

**Comment by ugendrang** [comment]
Actions.pop( {refresh: {variable: value} }) will do
