### ISSUE TITLE
pop back and trigger another callback

### ISSUE THREAD

**Issue by jjhesk** [aksonov/react-native-router-flux#1716]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38
- react-native v0.42

### Expected behaviour

trying to use actions.pop to go back to the previous scene  B and trigger another callback in that scene B 

### Actual behaviour

could not find anything to do that

### Steps to reproduce

1. 
2.
3.

**Comment by MattyK14** [comment]
+1

**Comment by baetschjunge** [comment]
dirty solution could be

Actions.pop();
setTimeout(() => {
Actions.SceneB( passPropWhichTriggersCallback ); // you might have to refresh
}, 10);

didnt try tho
