### ISSUE TITLE
[Topic]Navigator perform slowly and NavigationExperimental will be deprecated in RN0.43

### ISSUE THREAD

**Issue by jacobcyl** [aksonov/react-native-router-flux#1717]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

### Expected behaviour

It is not smooth when navigate to another scene

### Actual behaviour

Switch Tab, click back button, jumt to another scene, it is painfully slow on Iphone7 and android 

### Steps to reproduce

I just wandering if react-native-router-flux will upgrade navigator library? Cause RN official docs said:
> As of React Native 0.43, NavigationExperimental is deprecated. It will be removed from the codebase in a later version.  [here](https://facebook.github.io/react-native/docs/navigation.html)

**Comment by chuyik** [comment]
Yeah I wonder what action will be taken when React Native 0.43 released, but it seems like no one thought about this problem.

**Comment by MattyK14** [comment]
Pretty sure that router flux switched from NavigationExperimental to the newer Navigation API

**Comment by K-Leon** [comment]
it's nothing that's pressing immidiatly - router flux is using a fork. Even though i would love seeing the usage of RN Router Flux using the new Navigation Project from the inside.

**Comment by gdboling** [comment]
Hm, so started a new project today. Any ETA on when this will be fixed and are there any work arounds in the meantime?

**Comment by Dev-iL** [comment]
https://github.com/facebook/react-native/commit/febf3d00ed228391ee4dd6541b0d2746dc56d21f
