### ISSUE TITLE
remove animation on back/close transition with duration={1} (NOT working)

### ISSUE THREAD

**Issue by valinaga** [aksonov/react-native-router-flux#1718]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

### Expected behaviour
Setting `duration={1}` to a `<Scene />` performs as expected on open (i.e. immediately) and should perform identical on close/back. 

### Actual behaviour

However on close/back, the duration is ignored and the animation still persists.

### Steps to reproduce

1. Add `duration={1}` to a `<Scene />`
2. Call action navigation to that scene.
3. Call action.pop() to go back.

Any idea on how to make the close/back act immediately instead of animated?
Thanks,

**Comment by ryancoughlin** [comment]
So the exit animation does not listen to the 1 second duration set on the scene?

**Comment by valinaga** [comment]
No it doesn't. It completely ignores and animate with the default delay.
I couldn't find where this is set in the code.

**Comment by pvsong** [comment]
Same problem.

**Comment by James-Coleman** [comment]
I added `duration={0}` to the scene I'm going back to and that worked.
