### ISSUE TITLE
"Cannot read property 'push' of undefined" when mounting router for the second time

### ISSUE THREAD

**Issue by danielweinmann** [aksonov/react-native-router-flux#172]
I have an app that uses navigation only in a small part of it and for the rest it relies on figuring what components to render by state, using redux.

Today I replaced NavigatorIOS for routers in the main place where I used navigation, and at first it seemed to work perfectly. But when I mounted for the second time the navigation flow, after coming from other part of the app that does not use routers, I got the following error:

![simulator screen shot feb 4 2016 3 51 20 am](https://cloud.githubusercontent.com/assets/204765/12807016/965dc1fa-caf2-11e5-9421-279429b1bc3c.png)

I created a simplified scenario where I can simulate the problem here: https://gist.github.com/danielweinmann/8ab67efdf51e773f4a59

To simulate the problem, just run the example and do the following:

- Click on "Next"
- Click on "Sign in"
- Click on "Sing out"
- Click on "Next" again.

I would gladly contribute with a fix for this problem, but I couldn't figure it out so far.

Anyone has any thought on it? @aksonov, can you enlighten me?

**Comment by danielweinmann** [comment]
OK, after reading the code again I found a solution: https://gist.github.com/danielweinmann/4b44271c7d5631177f17

I had to add the following method to my routed main component:

  componentWillUnmount() {
    Actions.currentRouter = null
  }

I don't understand the code very well, but it seems it was losing the nav ref because Actions.currentRouter had a reference to the old, already unmounted router.

@aksonov, what do you think would be a good implementation of a solution for this? Just point a direction and I'll send a PR ;)

Thanks a lot!

**Comment by aksonov** [comment]
It is difficult to understand what you did. ExRouter is just wrapper around ExNavigator and use its refs. For some reasons that refs became null, which should not happen...

**Comment by danielweinmann** [comment]
Yeah, since I'm new to ExNavigator I'm still trying to understand it too.

What I do know is that the problem has to do with this line: https://github.com/aksonov/react-native-router-flux/blob/master/Router.js#L131

**Comment by aksonov** [comment]
Yes, maybe you are right. Try to remove it and check what happens. Probably it is needed to avoid nested routers to be set as current one, but maybe it is OK, please check demo and navigation inside tab router.

**Comment by MITDelian** [comment]
Ha thanks for solving this, I was just experiencing this myself as well. Thanks @danielweinmann !!

**Comment by danielweinmann** [comment]
@MITDelian o/
