### ISSUE TITLE
Passing params into Actions.route appears to fail silently

### ISSUE THREAD

**Issue by tomtang539** [aksonov/react-native-router-flux#1720]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.39.2

### Expected behaviour
Actions.route(params) should navigate to the route with params.  Actions.route() behaves correctly

### Actual behaviour
Actions.route(params) does nothing -- no warnings, no errors.  Actions.route() works just fine.

### Steps to reproduce

My Routes configuration:
```javascript
      <View style={{ flex: 1 }}>
        <Router hideNavBar>
          <Scene key="main" >
            <Scene key='welcome' component={Welcome} type='replace' title='Welcome' initial={true}/>
            <Scene key='textInterview' component={TextInterview}/>
            <Scene key='videoInterview' component={VideoInterview}/>
          </Scene>
        </Router>
      </View>
```

How I'm invoking the navigation:
` Actions.textInterview(params)` Where params is an object -- this does nothing
` Actions.textInterview()` This navigates properly

**Comment by tomtang539** [comment]
Figured out the problem, it's not with React-router-flux

**Comment by warka0** [comment]
@tomtang539 How did you figured it out? I got the same problem with passing params... :/
