### ISSUE TITLE
How to automatically display the return title

### ISSUE THREAD

**Issue by lucasleelz** [aksonov/react-native-router-flux#1721]
### Version
Tell us which versions you are using: 

- react-native-router-flux 3.38.0
- react-native v0.42.0

### Expected behaviour

I want to have a way to automatically get the title of the previous scene and appear in the upper left corner of the current scene.

**Comment by rodperottoni** [comment]
This is not an issue. You should use [StackOverflow](http://stackoverflow.com) for this type of question.
