### ISSUE TITLE
How can I retain parent navbar when switching tabs?

### ISSUE THREAD

**Issue by JCDJulian** [aksonov/react-native-router-flux#1722]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^3.38.0
- react-native v0.42.0
I currently have the following in my router:

>     <Scene key="results" title="Query Results"
>         tabs={true} tabBarStyle={style.tabBarStyle}>
>         <Scene
>           key="listResultsTab"
>           title="List"
>           icon={TabIcon}
>         >
>           <Scene key="listResults" component={ListResultsScene} title="Results List" />
>         </Scene>
> 
>         <Scene
>           key="mapResultsTab"
>           title="Map"
>           icon={TabIcon}
>         >
>           <Scene key="mapResults" component={MapResultsScene} title="Results Map" />
>         </Scene>
>     </Scene>

So far, it creates a tab bar with two tabs that alternate between the ListResults and MapResults components, which is what I want. However, the tabs each maintain their own navbar. This isn't necessarily an issue except that it overrides the parent navbar so I lose access to anything that came before query results.

My ideal setup would be something like:

    queryResults----->listResults -> ... ->
                   |
                    -->mapResults-> ... ->

Is there any way to keep queryResults's navbar while switching between the tabs?

The [docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md) say
> Every tab has its own navigation bar. However, if you do not set its parent <Scene tabs={true} /> with hideNavBar={true}, the tabs' navigation bar will be overrided by their parent.

However this does not seem to be the case. I am not using hideNavBar and the parent's navigation bar is still being overridden by the tab's. I thought perhaps I could use hideNavBar on the tab's, but that only just removes the navBar entirely.

**Comment by danstepanov** [comment]
I'm also facing this issue.

**Comment by JCDJulian** [comment]
Cross-posed to [SO](http://stackoverflow.com/questions/42850064/react-native-router-flux-how-can-i-retain-parent-navbar-when-switching-tabs) with more detail. Still unresolved
