### ISSUE TITLE
How to open scene with Drawer?

### ISSUE THREAD

**Issue by obykoo** [aksonov/react-native-router-flux#1723]
```
const scenes = Actions.create(
    <Scene key="root" >
        <Scene key="drawer" component={NavigationDrawer} open={false} >
            <Scene key="home" component={Home}  initial={true} />
        </Scene>
        <Scene key="profile1" component={Profile1} />
        <Scene key="profile2" component={Profile2}  />
        <Scene key="profile3" component={Profile3}  />
        <Scene key="profile4" component={Profile4}  />
        <Scene key="manage" component={ProfileManage}
               navigationBarStyle={{backgroundColor:'#0b4160'}}
               title={translate.t('profile.myManage')}
               rightTitle={translate.t('ok')}
               titleStyle={{color:'#fff'}}
               onRight={()=>{Actions.home()}}
               leftButtonTextStyle={{color:'#0ef0ff'}}
               rightButtonTextStyle={{color:'#0ef0ff'}}
        />
    </Scene>
);
```

Now If I want to move from scene "manage" (look at onRight) , back to scene "home" which has drawer I can not call Actions.home(); because they are not siblings and it is not doing anything... How do I get back to home scene then??

**Comment by obykoo** [comment]
Whn I call Actions.drawer(); It opens home scene , because of: 

<DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />

However , when I open profile1 again, it shows conflict:

navigationState.children[7].key "scene_profile1_1_profile1" conflicts withanother child!

**Comment by rodperottoni** [comment]
This is not an issue. You should use [StackOverflow](http://stackoverflow.com) for this type of question.

**Comment by sattaman** [comment]
I'm having similar issues.

**Comment by JaxGit** [comment]
@obykoo if you are using react-native-drawer you could try this:
https://github.com/aksonov/react-native-router-flux/issues/2150#issuecomment-322654872
