### ISSUE TITLE
How to add two Actions to a Button ? 

### ISSUE THREAD

**Issue by Kris4an7** [aksonov/react-native-router-flux#1727]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

I want to add tow Actions to my button onPress handler, but I can't seem to figure how to do this. Could anyone assist me ? 

I tried something like this but not surprising it didn't work. 

`<Button 
  onPress={Actions.Main1 && Actions.Tab2} 
  style={{ width: 90, height: 90 }} >
      <Text>Show</Text>
</Button>`

Thank you !

**Comment by rodperottoni** [comment]
This is not an issue. You should use [StackOverflow](http://stackoverflow.com) for this type of question.
