### ISSUE TITLE
How to disable Swipe-Down-To-Close at modal or just close when not scrolled

### ISSUE THREAD

**Issue by goinnovative** [aksonov/react-native-router-flux#1728]
I am showing a component with vertical-direction. It's like a Modal-box.

`<Scene key="details" component={Details} direction="vertical" />`

If the details-Component is open and I swipe down the details getting closed. I really like this feature but the problem is, that the root element of the details is a ScrollView.
Scrolling down is no problem. But if the user scrolls up again, the modal gets closed.

There are two options:
A) Disable Swipe-Down-To-Close (I don't know, how this feature is named)
B) Only close modal if the top of the ScrollView is reached 

Option B would be very nice. Any ideas how to solve one of these options?

Thank you!

EDIT: Option A is simply solved by adding `panHandlers={null}` to the scene. So the question would be, if there is a way to solve option B?

**Comment by ryancoughlin** [comment]
I ran into the same issue on a few client projects. Option B would be great. I am currently doing Option A on projects that open as a modal with `ScrollView`
