### ISSUE TITLE
Root Component that wrap all routes

### ISSUE THREAD

**Issue by redwind** [aksonov/react-native-router-flux#1730]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.1
- react-native v0.33.0

### Expected behaviour

Would we have a component that wrap all routes and i process some animation view inside ?
i have researched but no document talk about root component

Thanks !!!

**Comment by rodperottoni** [comment]
This is not an issue. You should use [StackOverflow](http://stackoverflow.com) for this type of question.
