### ISSUE TITLE
Calling Action.pop and redux change after each other

### ISSUE THREAD

**Issue by obykoo** [aksonov/react-native-router-flux#1732]
I am using React-native-router-flux for navigation and redux store for data storage but I came to problem I am not able to solve. 

I am getting this error:
**"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component."**

Workflow is like this:

I have **view A** which shows list of data. Then user clicks on add new item and router opens new **view B** which cotains list of data that can be added. 

For data adding I have defined redux action. So once user clicks on item he wants to add, I am calling this code:        

    onPress(newData) {
        this.props.addData(newData);  //REDUX ACTION to add new data to list
        Actions.pop(pridajOchorenie); //React-native-router-flux action to pop back to view A
    }

However this is giving me mentoined error.

I tried to pass newData as parameter to pop back to **view A** and then call redux action addData instead of calling redux action addData in **view B** , but this is leading to infinity loop , because nextProps will contain parameter newData from pop on every next call (so also for redux action) if I implement it like this:

    componentWillReceiveProps(nextProps){
       if (nextProps.newData!=null) {
          this.props.addData(nextProps.newData);
       }
    }

So I am not sure how to implement this situation.

**Comment by rodperottoni** [comment]
This is not an issue. You should use [StackOverflow](http://stackoverflow.com) for this type of question.
