### ISSUE TITLE
Android hardware back button not working after Actions.main({type: 'replace'})

### ISSUE THREAD

**Issue by vladbars** [aksonov/react-native-router-flux#1734]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2

I use Actions.main({type: 'replace'}) to logout user, but after that hardware back button not working on any scene.

**Comment by rodperottoni** [comment]
You didn't provide any test case or at least investigated what's causing this error. You should use [StackOverflow](http://stackoverflow.com) for this type of question.
