### ISSUE TITLE
Shared Element Transitions?

### ISSUE THREAD

**Issue by braco** [aksonov/react-native-router-flux#1735]
Seems like this feature is coming up in a few routers. Any plans here?

http://airbnb.io/native-navigation/docs/guides/shared-element-transitions.html

https://github.com/exponent/ex-navigation/tree/master/example-shared-element-transitions

https://github.com/wix/react-native-navigation/tree/master/example/src/screens/transitions/sharedElementTransitions

**Comment by getnashty** [comment]
Just came here to post this same thing! +1
