### ISSUE TITLE
How can I run example app?

### ISSUE THREAD

**Issue by prettyGIT** [aksonov/react-native-router-flux#1736]
"react-native-router-flux": "^3.38.0"
"react-native": "0.42.3"
yarn  v0.21.3

I cloned this repo, navigate to example folder, run 'npm install' and then 'react-native run-ios'
Also I give it a try like below
- clone the repo
- cd example
- yarn
- react-native run-ios

But both cases it logs error like below
...
Installing build/Build/Products/Debug-iphonesimulator/Example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by lazyhoneyant** [comment]
+1
