### ISSUE TITLE
How to share same component across views without redeclaring it ?

### ISSUE THREAD

**Issue by Weakky** [aksonov/react-native-router-flux#1737]
Hey,

I'm trying to use https://github.com/gnestor/react-native-statusbar-alert to inform users that there data are being refreshed when he logs in.

The issue is that i'd have to redeclare the same component on all my views using a global state to make sure that the status bar persists if users navigate from one view to another.

I thought of making a HOC to handle it in a cleaner way, but i'm not really satisfied with it, as i'm forced to encapsulate all my main views with it, it just feels weird.

The library actually propose to share it across view with the default navigator

```JSX
render() {
  return (
    <View style={styles.container}>
      <StatusBarAlert
        backgroundColor="#3CC29E"
        color="white"
        visible={this.state.alerts.length > 0}
        {...this.state.alerts[0]}
      />
      <Navigator
        initialRoute={initialRoute}
        renderScene={this.renderScene}
        navigationBar={
          <Navigator.NavigationBar
            routeMapper={routeMapper}
            style={{top: -20}}
          />
        }
      />
    </View>
  )
}
```

Is there a way to kind of do the same thing using RNRF ?

Thank you guys for your help.

**Comment by rodperottoni** [comment]
This is not an issue, and you should ask these types of questions on [StackOverflow](http://stackoverflow.com/)
