### ISSUE TITLE
[Help me] fixed bottom player like Apple Music all scene

### ISSUE THREAD

**Issue by nhoclove9x** [aksonov/react-native-router-flux#1740]
hi all,

Im newbie. I want make app audio player. I need player fixed bottom every Scene like apple music red border in attach image. Have you any idea please suggest for me :)
![img_0477](https://cloud.githubusercontent.com/assets/2536935/24320374/853ef842-1166-11e7-9e69-c52a90bc7a5e.PNG)

### Version
Tell us which versions you are using: 

- react-native-router-flux v 3.37.0
- react-native v0.42

**Comment by leonacky** [comment]
I can help you. Pls skype me. tuan.dv2011

**Comment by mursang** [comment]
How did you resolve this? 
How did you make a root view containing Router?

Thanks.

**Comment by themakerman** [comment]
@leonacky hey can u throw in some pseudo code? I am facing a similar problem. I actually implemented this using lightbox.

**Comment by mursang** [comment]
@themakerman I have found a solution.  Mi Router now looks like this:

```
<View style={{ƒlex: 1}}>
    <Router ..>
      <My Scenes as usual..../>
     </Router>
     <View style={{position: 'absolute', bottom:0, flex:1, left:0, right:0, height:70}}>
         <Text>THIS IS MY FIXED VIEW :) </Text>
      </View>
</View>
```
Be sure to place your fixed view after the Router in order to be able to click on it.
Also be sure to wrap your router inside a View.
Good luck!
