### ISSUE TITLE
Close Modal and redirect to another scene only works once

### ISSUE THREAD

**Issue by dittmarconsulting** [aksonov/react-native-router-flux#1741]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.41.2

### Expected behaviour

Used your example and added an extra button to the Error.js component
```
<Button onPress={this._action.bind(this, 'register2')}>Go to another page</Button>
```
I expected that the modal scene will be removed from the navigation stack.

### Actual behaviour

When I invoke the `_action` function the modal closes and I get redirected to the new scene. If I try to open the modal again I get the following error msg:
```
Warning: flattenChildren(...): Encountered two children with the same key, `1:$error_1_error`.
Child keys must be unique; when two children share a key, only the first child will be used.
```
So it seems the modal scene didn't get removed from the stack

### Steps to reproduce

1. Add extra button
2. Add function below to Error.js component right under `componentDidMount()`

```
_action(sceneKey) {
  Animated.timing(this.state.offset, {
    duration: 150,
    toValue: -deviceHeight
  }).start(
    Actions[sceneKey]({})
  );
}
```

3. Start app and click on `Popup Error` and then on `Go to another page`
4. Click on `Back` and then on `Popup Error` again.

Is there a workaround for this problem?

**Comment by eiosca** [comment]
Hi, it's because the component use in modal scene should be unmount.
Currently you have to use Actions.pop() which unmount a type scene modal.

But i have a problem when i display a modal (i use a modal scene to display a notification anywhere) if i switch to another scene before it is closed, i have the same error.

**Comment by eiosca** [comment]
This works: #1035

**Comment by dittmarconsulting** [comment]
Thank eiosca,

I tried that but:

`Actions.refresh(key: "error", visible: true, uniqId: new Date().getTime());` gives me an error because refresh seems to expect an object.

If I try `Actions.refresh({key: "error", visible: true, uniqId: new Date().getTime()});` nothing happens. I can see "invoked" in the console but the scene doesn't change

Here my class:

```
import React from 'react';
import {View, Text, StyleSheet} from "react-native";
import Button from "react-native-button";
import {Actions} from "react-native-router-flux";
class Launch extends React.Component {

    constructor(props) {
        super(props)
        this._showModal = this._showModal.bind(this)
    }

    _showModal() {
        console.log('invoked')
        Actions.refresh({key: "error", visible: true, uniqId: new Date().getTime()});
    }

    render(){
        return (
            <View {...this.props}  style={styles.container}>
            <Text>Launch page</Text>
            <Button onPress={()=>Actions.login({data:"Custom data", title:"Custom title" })}>Go to Login page</Button>
            <Button onPress={Actions.register}>Go to Register page</Button>
            <Button onPress={Actions.register2}>Go to Register page without animation</Button>
            <Button onPress={this._showModal}>Popup error</Button>
            <Button onPress={Actions.tabbar}>Go to TabBar page</Button>
            <Button onPress={Actions.switcher}>Go to switcher page</Button>
            <Button onPress={Actions.pop}>back</Button>
            </View>
        );
    }
}
```

**Comment by eiosca** [comment]
Okay, are you call your scene without refresh first. Like
`Actions.error()`

This call mount your component and as you should have in your component on mount, the state should be hide.

So at the first launch, nothing should be appear.
But when you call Actions.refresh with props, in your componentWillReceiveProps, you can update the state visible. Automatically, they re-renderered. (Sorry for my bad english).

Could you share the code of your compoment (error) ?

**Comment by dittmarconsulting** [comment]
Hi eiosca,

As I said I just use aksonov's original code.

If you go to Launch.js I have created an on-click function to open the dialog, which works but I can not use Actions.refresh() at all.

https://github.com/dittmarconsulting/flux-router-example

**Comment by dittmarconsulting** [comment]
I tried everything but it doesn't work once you redirect to another page from a modal scene. The solution [#1035](https://github.com/aksonov/react-native-router-flux/issues/1035) work because it doesn't redirect from the modal.

It sounds crazy but the only solution that work for me is to find the modal in the nav stack (children) and delete the object. Here the hack:

```
const purgeAll = (object, target) => {
    if (object.children) {
        const keys = Object.keys(target)
        // overide the children array with the new purged array
        object.children = object.children.filter(obj =>
            // ignore the matching object
            !keys.every(key => target[key] === obj[key]) && purgeAll(obj, target)
        )
    }
    return object
}
```
and use this function in Example.js in the scene reducer function

```
const reducerCreate = params => {
    const defaultReducer = new Reducer(params);
    return (state, action) => {
        // make sure state and scene exist
        if(state && action.scene) {
            // once we have gone to scene "register2" delete the modal
            if(action.scene.sceneKey === 'register2') {
                // purge modal scene from the child arrays
                purgeAll(state, {
                    key: 'error_1_error',
                    sceneKey: 'error'
                })
            }
        }
        return defaultReducer(state, action)
    }
}
```

Because I redirect from the modal to the scene with the key = 'register2' I just monitor when the action  happens and filter the modal dialog with the key = 'error_1_error' or I can re-write the function to just look for 'error' with <string>.include('error') or something. Just give the dialog a special unique name.

This is the only solution that works for me.

Here the working code: https://github.com/dittmarconsulting/flux-router-example
