### ISSUE TITLE
TabBar with Button for DrawerMenu? 

### ISSUE THREAD

**Issue by WillyRamirez** [aksonov/react-native-router-flux#1744]
### Version
- react-native-router-flux v3.38.0
- react-native v0.42.3

Hi all,

Is it possible to achieve the following setup:

![image](https://cloud.githubusercontent.com/assets/8708591/24404001/a3bec21a-13bf-11e7-88c8-e85aefaa2d6d.png)

I need one of the tabbar tabs to be a button, which triggers the drawer menu to open. Here is my code:

    <RouterRedux>
      <Scene key="tabbar"  initial> 
        <scene tabs={true} key="main" initial >
          <Scene title="Tab #1" iconName="home" key="scene1" initial component={scene1} icon={TabIcon}  />
          <Scene title="Tab #2" iconName="arrow" key="scene2" component={scene2}  icon={TabIcon}/>
          <Scene title="Tab #3" iconName="inbox" key="scene3" component={scene3} icon={TabIcon}  />
          <Scene title="Tab #4" iconName="account" key="scene4" component={scene4} icon={TabIcon}  />
          <Scene title="drawerMenu" iconName="menu" key="sidebar" icon={TabIcon}  />
        </scene>
      </Scene>
    </RouterRedux>

**Comment by mtt87** [comment]
I would do this:

- Create your `Drwer.js` component 
```js
import React, { Component } from 'react';
import Drawer from 'react-native-drawer';
import { Actions, DefaultRenderer } from 'react-native-router-flux';
import SideMenu from './SideMenu';

export default class NavigationDrawer extends Component {
  render() {
    const state = this.props.navigationState;
    const children = state.children;
    return (
      <Drawer
        ref={(ref) => {
          this.navigation = ref;
        }}
        openDrawerOffset={0.25} // 20% gap on the right side of drawer
        panCloseMask={0.25}
        tweenHandler={ratio => ({
          main: {
            opacity: Math.max(0.54, 1 - ratio),
          },
        })}
        open={state.open}
        onOpen={() => Actions.refresh({ key: state.key, open: true })}
        onClose={() => Actions.refresh({ key: state.key, open: false })}
        type="displace"
        content={<SideMenu navigationState={state} />}
        tapToClose
        negotiatePan
      >
        <DefaultRenderer
          navigationState={children[0]}
          onNavigate={this.props.onNavigate}
        />
      </Drawer>
    );
  }
}
```
- Wrap everything inside a scene that is the drawer component
```js
<Scene key="drawer" open={false} component={Drawer} initial> 
    <Scene tabs={true} key="main" initial >
      <Scene title="Tab #1" iconName="home" key="scene1" initial component={scene1} icon={TabIcon}  />
      <Scene title="Tab #2" iconName="arrow" key="scene2" component={scene2}  icon={TabIcon}/>
      <Scene title="Tab #3" iconName="inbox" key="scene3" component={scene3} icon={TabIcon}  />
      <Scene title="Tab #4" iconName="account" key="scene4" component={scene4} icon={TabIcon}  />
      <Scene title="drawerMenu" iconName="menu" key="sidebar" icon={TabIcon} onSelect={...}  />
    </Scene>
  </Scene>
```
- Add `onSelect` to the last scene to manually control what happens when you press
```js
<Scene 
  title="drawerMenu" 
  iconName="menu" 
  key="sidebar" 
  icon={TabIcon} 
  onSelect={() => Actions.refresh({ key: 'drawer' open: value => !value )})}  />
```

**Comment by WillyRamirez** [comment]
@mtt87 Thnx

**Comment by adaerodriguez** [comment]
Hi, I only get a white screen with your solution @mtt87.

"react": "16.3.1",
"react-native": "0.55.3",
"react-native-router-flux": "4.0.0-beta.27"

Thanks!
