### ISSUE TITLE
Is Actions.dismiss() no longer a thing?

### ISSUE THREAD

**Issue by BrendanBerkley** [aksonov/react-native-router-flux#1747]
I saw references to dismiss in the [readme](https://github.com/aksonov/react-native-router-flux/blob/1382d3ce4f0d591bf29b3ccf3d8fddb3a915ec4e/README2.md) and [API configuration](https://github.com/aksonov/react-native-router-flux/blob/1382d3ce4f0d591bf29b3ccf3d8fddb3a915ec4e/README2.md), but it didn't work and I didn't see evidence of it in code.

Just wanted to confirm it's not a thing anymore. I can remove the references with a PR, but if the change is anything more than "use pop instead" then someone else might be more qualified.

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.40.0

**Comment by OhaiBBQ** [comment]
Hi @BrendanBerkley, I believe you're correct.

I think you were confused as `README2.md` is the README for v2.x.x of RNRF. Perhaps a pull request to rename `README2.md` to something like `README-FOR-v2.md` would be good.
