### ISSUE TITLE
Intercept Navigation.pop()

### ISSUE THREAD

**Issue by mykelaballe** [aksonov/react-native-router-flux#1749]
Is there a way to intercept the Navigation.pop() and add a conditional statement whether to continue the pop or cancel it? Already tried this:

componentWillUnmount(){
  return false
}

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.34.0

### Expected behaviour
When navigating to a screen where you can edit some data, then going back to previous screen without hitting the "Save" button, the app should be able to detect that there are changes made and ask the user whether to discard the changes or cancel the navigation back to previous screen

### Actual behaviour
I have no way of intercepting the Navigation.pop() and instead it will just go to previous screen

**Comment by OhaiBBQ** [comment]
Hi @mykelaballe, from what I've seen, the way to do this is use the `refresh` action with custom props.

e.g.
```js
componentWillMount() {
   Actions.refresh({ onLeft: this.onLeft.bind(this)  });
}

onLeft() {
if(saved) { Actions.pop(); } else { alert(); }
}

```
