### ISSUE TITLE
Help With Drawer Menu

### ISSUE THREAD

**Issue by jigarmistry** [aksonov/react-native-router-flux#1750]
Can anybody provide me example of how we can integrate the react-native-drawer with the router flux ?

I have used example provided in OTHER_INFO but when I call any screen which has drawer its not calling by Actions.ACTION_NAME.

Any example for the same would be great for me.

I have used like this..

Example is my screen and I have used like this.

```
<Scene key="drawer" component={NavigationDrawer} open={false} >
       <Scene
            key="Example"
            component={Example1}
            title="Example"
            hideNavBar={false}
        />
</Scene>
```

Now if I call screen using Actions.Example, it is not working. Nothing happen.

**Comment by jigarmistry** [comment]
Any Help ? Anybody integrate the latest router flux with drawer ?

**Comment by filipemonteiroth** [comment]
@jigarmistry I've used the example and it works perfectly.

NavigationDrawer.js

`import React, { Component } from 'react';
import Drawer from 'react-native-drawer';
import SideMenu from './SideMenu';
import {Actions, DefaultRenderer} from 'react-native-router-flux';

export default class NavigationDrawer extends Component {
    render(){
        const state = this.props.navigationState;
        const children = state.children;
        return (
            <Drawer
                ref="navigation"
                open={state.open}
                onOpen={()=>Actions.refresh({key:state.key, open: true})}
                onClose={()=>Actions.refresh({key:state.key, open: false})}
                type="displace"
                content={<SideMenu />}
                tapToClose={true}
                openDrawerOffset={0.2}
                panCloseMask={0.2}
                negotiatePan={true}
                styles={drawerStyles}
                tweenHandler={(ratio) => {
                  return {
                    mainOverlay: { opacity: ratio === 0 ? 0 : 0.3, backgroundColor: '#000' }
                  }
                }}
                // tweenHandler={Drawer.tweenPresets.parallax}
                >
                <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </Drawer>
        );
    }
}

const drawerStyles = {
    drawer: {
        shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 1
    },
    main: { paddingLeft: 0 }
}
`

**SideMenu.js** is a simple component with render method returning a single view.

Simple route.

Router.js

`<Scene key="drawer" type={ActionConst.RESET} component={NavigationDrawer} open={false} >
          <Scene key="main" initial>
            <Scene
              key="dashboard"
              component={Dashboard}
              title="Dashboard"
              hideNavBar={false}
              initial
            />
      </Scene>
`

**Comment by jigarmistry** [comment]
@filipemonteiroth Thanks for the solution. How do you call the dashboard component using Actions ?
And what is ActionConst ?

**Comment by filipemonteiroth** [comment]
**ActionConst** is a set of strings provided by the lib. Just import it like you do with actions.

To call dashboard, I just use Actions.dashboard()

Somehow if you call something from the menu, it doesn't close when the new screen shows.

I'm closing the drawer when my component will mount, just like

```
componentWillMount () {
    Actions.refresh({key: 'drawer', open: false });
}
```

**Comment by jigarmistry** [comment]
Thanks,

But is it still working if dashboard is not the initial component ? In my case it is not the initial component. I do have a same setup.

**Comment by filipemonteiroth** [comment]
Yeah, working fine.

**Comment by jigarmistry** [comment]
Thanks for the solution. I will try this way. 

But in my case when I call Actions.dashboard() nothing happens.  

How do you manage to open the drawer from left button click in navigation bar?

**Comment by filipemonteiroth** [comment]
It should work already without any action.

**Comment by jigarmistry** [comment]
Ok. I will try and let you know if I got any problem or I will share a small snippet of code with you for the same. 

Thanks for the support and time.

**Comment by kyleseaman** [comment]
@jigarmistry I use the following to open/close the drawer from any screen

```
closerDrawer = () => {
    Actions.refresh({key: 'drawer', open: false });
  };

  openDrawer = () => {
    Actions.refresh({key: 'drawer', open: true });
  }
```

My left button is setup as follows 
```
<TouchableOpacity onPress={this.openDrawer}>
  <Image
    resizeMode='contain'
    source={{uri: 'menuBtn'}}
  />
</TouchableOpacity>
```

And as mentioned above, once you call `Actions.dashboard()`, in `dashboard` call 
```
componentWillMount () {
    Actions.refresh({key: 'drawer', open: false });
}
```

There is an issue when calling two `Actions` in a row, so if you have a component that wants to load a `dashboard` from the drawer and then close the drawer, you can use the following
```
Actions.dashboard({ title: title });
setTimeout(() => Actions.refresh({ key: 'drawer', open: false }), 0)
```

Finally, you can set `type='replace'` when you create your `Scenes` if you want the navigation stack to have a new root. For example: 
```
<Scene key='Login' component={Login} title='Login' hideNavBar type='replace' />
```

**Comment by jigarmistry** [comment]
@kyleseaman Thanks for the detailed solution. I appreciate your answer. Its sounds good to me.

@filipemonteiroth I have tried that and come to know that I have problem in router setup. That is now solved and it is finally working. Thanks a lot.

**Comment by jigarmistry** [comment]
It is working but its every time taking the first actions as first actions in scene under the drawer.

In my case I have following in router.js 

```
<Scene key="drawer" type={ActionConst.RESET} component={NavigationDrawer} open={false} > 
        <Scene key="sidemenu">
          <Scene
            key="Dashboard"
            component={Dashboard}
            title="Dashboard"
            hideNavBar={false}
          />
          <Scene
            key="Profile"
            component={Profile}
            title="Profile"
            hideNavBar={false}
          />
          <Scene
            key="Hisotry"
            component={Hisotry}
            title="Hisotry"
            hideNavBar={false}           
          />
        </Scene>
      </Scene>
```

So when I run the app its every time going into dashboard. but I need to go to history first.

**Comment by kyleseaman** [comment]
@jigarmistry if you want `History` to be first, you should pass the `initial` prop. 

My scene structure looks like:
```
<Scene key='root'>
  <Scene key='drawer' component={Drawer} open={false}>
    <Scene key='dashboard' component={Dashboard} type='replace' ... />
    <Scene key='history' initial component={History} type='replace' ... />
  </Scene>
</Scene>
```

**Comment by jigarmistry** [comment]
I am handling the screen movement in using actions. That is if something true then I need to go to history otherwise login.

How I can handle this ?

**Comment by kyleseaman** [comment]
I would suggest having an initial Scene to handle this. I have an `InitialLoad`, which presents a loading screen while determining where to send the user.  Either to `Login`, `Dashboard`, `History` etc.

**Comment by jigarmistry** [comment]
Sounds good to me. Can you share me small snippet for that ? How it is actually working ?

**Comment by kyleseaman** [comment]
In `InitialLoad` on `componentWillMount()` I have my check for the user and then call the appropriate action, either `Action.Login()` or `Action.OtherRoute()`

**Comment by jigarmistry** [comment]
What do you mean by In `InitialLoad on componentWillMount()` ? You mean to the first screen where we need to check ? In our case login ?

**Comment by kyleseaman** [comment]
`InitialLoad` is a React Component
```
<Scene key=`initialLoad` component={InitialLoad} initial type='replace />
```
It's called before anything else, so in it's `componentWillMount()` I perform the checks necessary to load the proper `Scene` for the user.

**Comment by jigarmistry** [comment]
And you have this as the initial scene among all the scenes and it is not having anything extra. Is it ?

**Comment by kyleseaman** [comment]
Correct, it looks something like this. 

```
<Scene key='root'>
  <Scene key='drawer' component={Drawer} open={false}>
    <Scene key='dashboard' component={Dashboard} type='replace' ... />
    <Scene key='login' component={Login} type='replace' ... />
    <Scene key='initialLoad' component={InitialLoad} type='replace' initial ... />
    <Scene key='history' component={History} type='replace' ... />
  </Scene>
</Scene>
```

**Comment by jigarmistry** [comment]
Yeah.. But what if I do not need a drawer in all the scenes ? Only in History one ?

**Comment by kyleseaman** [comment]
You should be able to just nest the other Scenes outside of the `Drawer` Scene, but I haven't implemented this.  I just hide the Drawer button on the `Login` scene.

**Comment by jigarmistry** [comment]
That's not working.. I think hide the navbar will be the trick..

**Comment by AAverin** [comment]
For me navbar is always invisible if I run on Android.
Any tips?

**Comment by xhou** [comment]
@AAverin I got the same issue. I resolved with help of this thread
 https://github.com/aksonov/react-native-router-flux/issues/1354

**Comment by swedge218** [comment]
@filipemonteiroth Where do I need to place this snippet of code:

`<Scene key="drawer" type={ActionConst.RESET} component={NavigationDrawer} open={false} > <Scene key="main" initial> <Scene key="dashboard" component={Dashboard} title="Dashboard" hideNavBar={false} initial /> </Scene>`

I have put it in my application Router Setup but it does not work. I get the same problem - nothing happens when i call Actions.map from another Component. I have the Drawer Component set up as you showed but it seems I am setting the Router up wrongly.

This is my first React or RN app, so pardon if this sounds basic.

**Comment by valerybodak** [comment]
@filipemonteiroth 


0
down vote
favorite
I try to use react-native-drawer (https://github.com/root-two/react-native-drawer) in my app with react-native-router-flux

According to the documentation I've added my scene with drawer to the Router:

import NavigationDrawer from './scenes/NavigationDrawer';
import MetricsScene from './scenes/MetricsScene';
...
<Router>
     <Scene key="root">

         <Scene key="login"
             component={LoginScene}
             hideNavBar={true}
             initial
         />

         <Scene key="drawer" component={NavigationDrawer} open={false} >
             <Scene key="metrics" component={MetricsScene}/>
         </Scene>

     </Scene>
</Router>

In my LoginScene I call:
Actions.metrics({type: ActionConst.RESET});
after press on Login button, but NOTHING happens.

Any ideas? Thanks in advance.

**Comment by swedge218** [comment]
@valerybodak This issue seems like it affects many people including me. 

What I had to do later was to wrap my Router and Scenes in the the <Drawer> tag. 

See full details on stackoverflow answer [here](https://stackoverflow.com/questions/43947814/react-native-drawer-with-react-native-router-flux-set-up-not-working/44025328#44025328)

**Comment by phantom1299** [comment]
Hi, I implemented the Drawer from router-flux v4.0.0-beta.14 like this:
(I couldnt find any info on how to implement the new version, tried to implement it like in the Example App. Hope this helps other people.)

RouterComponent.js:
(This is my root component)
```
import React from 'react';
import { Scene, Router } from 'react-native-router-flux';
import LoginForm from './components/LoginForm';
import Home from './components/Home';
import Profile from './components/Profile';
import SideMenu from './SideMenu';
import Settings from './components/Settings';

const RouterComponent = () => {
    return (
        <Router>
            <Scene overlay>
                <Scene key="lightbox" lightbox leftButtonTextStyle={{ color: 'green' }} backButtonTextStyle={{ color: 'red' }} initial>
                    <Scene key="modal" modal hideNavBar>
                        <Scene key="auth" initial>
                            <Scene key="login" component={LoginForm} title="Please Login" titleStyle={{ textAlign: 'center' }} />
                        </Scene>
                        <Scene key="drawer" drawer contentComponent={SideMenu} initial>
                            <Scene key="main" >
                                <Scene
                                    key="home"
                                    component={Home}
                                    title="Home"
                                    initial
                                />
                                <Scene
                                    key="profile"
                                    component={Profile}
                                    title="Profile"
                                />
                                <Scene
                                    key="settings"
                                    component={Settings}
                                    title="Settings"
                                />
                            </Scene>
                        </Scene>
                    </Scene>
                </Scene>
            </Scene>
        </Router>
    );
};

export default RouterComponent;
```
Where Home, Settings, Profile and LoginForm are usual components. And SideMenu is (yes :)) my side-menu.
SideMenu.js:

```
import React, { Component, PropTypes } from 'react';
import { StyleSheet, Text, View, ViewPropTypes } from 'react-native';
import { connect } from 'react-redux';
import { Actions } from 'react-native-router-flux';
import Button from 'react-native-button';
import { CardSection } from '../src/components/common';

const contextTypes = {
  drawer: React.PropTypes.object,
};

const propTypes = {
  name: PropTypes.string,
  sceneStyle: ViewPropTypes.style,
  title: PropTypes.string,
};

const styles = StyleSheet.create({
  viewContainer: {
    flex: 1,
    backgroundColor: '#fff'
  },
  container: {
    padding: 15,
    height: 45,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  textStyle: {
    fontSize: 18,
    color: '#555',
  },
  nameContainer: {
    padding: 15,
    height: 45,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  name: {
    fontSize: 22,
    color: '#555',
    fontWeight: '400',
  }
});

class SideMenu extends Component {
  render() {
    return (
      <View style={[styles.viewContainer, this.props.sceneStyle]}>
        <CardSection style={{ flexDirection: 'column', padding: 30 }}>
          <Button
            containerStyle={styles.container}
            style={styles.name}
            onPress={() => { Actions.profile(); }}
          >User Name</Button>
        </CardSection>
        <CardSection style={{ flexDirection: 'column' }}>
          <Button
            containerStyle={styles.container}
            style={styles.textStyle}
            onPress={() => { Actions.home(); }}
          >Home Page</Button>
        </CardSection>
        <CardSection style={{ flexDirection: 'column', borderBottomWidth: 0, }}>
          <Button
            containerStyle={styles.container}
            style={styles.textStyle}
            onPress={() => Actions.settings()}
          >Settings</Button>
          <Button
            containerStyle={styles.container}
            style={styles.textStyle}
            onPress={() => Actions.auth()}
          >Log Out</Button>
        </CardSection>
      </View>
    );
  }
}

SideMenu.contextTypes = contextTypes;
SideMenu.propTypes = propTypes;

export default SideMenu;
```

CardSection is just a custom component for styling.
CardSection.js:

```
import React from 'react';
import { View } from 'react-native';

const CardSection = (props) => {
    return (
        <View style={[styles.containerStyle, props.style]} >
            {props.children}
        </View>
    );
};

const styles = {
    containerStyle: {
        borderBottomWidth: 1,
        padding: 5,
        backgroundColor: '#fff',
        justifyContent: 'flex-start',
        flexDirection: 'row',
        borderColor: '#ddd',
        position: 'relative'
    }
};

export { CardSection };

```

Version:
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-button": "^2.1.0",
    "react-native-router-flux": "^4.0.0-beta.14",
```

**Comment by GazizovRuslan** [comment]
@phantom1299, Did everything according to your example, but I have such an error 
![simulator screen shot 29 2017 14 18 08](https://user-images.githubusercontent.com/15098966/29811465-5ac161f0-8c58-11e7-9631-083d5a158259.png)

**Comment by preetampatil3d** [comment]
Thanks lot @phantom1299 ,

i am using 
 "react": "16.0.0-alpha.12",
 "react-native": "^0.46.1",
 "react-native-router-flux": "^4.0.0-beta.15",
 "react-redux": "^4.4.5",
 "redux": "^3.5.2",
 "redux-thunk": "^2.2.0"

I was struggling for drawer, Your example saved me. . .  

Can you please tell me where can i find documentation for this . ? 

**Currently drawer appear on all pages & on left side but i want drawer for home page(main page) only and on right side.**







Thanks in Advance .

**Comment by phantom1299** [comment]
Sorry for the late reply, I somehow didn't see the email notifcation send to me by github.

@GazizovRuslan, I cant say anything without more information, maybe you forgot to export one of your components as it says in the error message.

@preetampatil3d, glad I could save you the struggle^^.

All child scenes of a scene with the drawer property will have the drawer and the drawer button. You can add the "back" property on a scene so it doesn't has the drawer button (but you will still be able to bring the drawer by sliding). I don't know how to make the drawer button on the right, checked the docs a little bit with no success.

In the [router flux repository](https://github.com/aksonov/react-native-router-flux), there are different branches and one of them, the [v4-docs](https://github.com/aksonov/react-native-router-flux/tree/v4-docs) branch seems to have more information about router-flux v4. Maybe you can find it there. I didn't check the other branches but experimenting with the example can help.

**Comment by kbrssmsn** [comment]
@phantom1299 Thanks. It worked :)) You saved my project

**Comment by AndrewMarkley** [comment]
@SunSet1219 
Check out this example from the breaking changes section
https://github.com/aksonov/react-native-router-flux/blob/v4/Example/Example.js

change component => contentComponent

**Comment by traxx10** [comment]
i tried your solution but then when i toggle my navigation, i dont have a nav bar

**Comment by phantom1299** [comment]
@SunSet1219 I never used v3 so I don't know what changed, but the example AndrewMarkley send you should help.

@traxx10 hmm, can you show your router component? Maybe you navigate to a Scene which has the "hidenavbar" property set to true?

**Comment by vijaychouhan-rails** [comment]
@jigarmistry 
Find the example at [https://github.com/vijaychouhan-rails/AllInOne](https://github.com/vijaychouhan-rails/AllInOne)

**Comment by preetampatil3d** [comment]
@phantom1299 Thanks, I have added back={true} in Scene where want to hide drawer and display back. and its worked. But when i swipe back from inner scene it opens drawer instead of going back. (I need click back button only to go back).  

Can you please help me with this.
Thanks

**Comment by ishaqashraf** [comment]
@preetampatil3d  
you need to add the onback function like this 
<Scene
                            key="addwork"
                            component={AddWork}
                            title="Create New Work Order"
                            back={true}
                            onBack={() => Actions.pop()}
                            backButtonTintColor="white"
                            
                        />

**Comment by mohsenmahoski** [comment]
I have this problem after Upgrading to new React Native version :  
My scene structure looks like:
```
<Scene key="root" >
               <Drawer
                      hideNavBar
                      key="drawer"
                      contentComponent={DrawerComponent}
               >
                    <Scene key="Home" component={Home} initial hideNavBar />
                    <Scene key="Settings" component={Settings} />
                    <Scene key="Basket" component={Basket} />
                    <Scene key="Maps" component={Maps} />
               </Drawer>
</Scene>
```
Its worked good in V 0.51 but now in V 0.52 Show :
```
TypeError: Cannot read property 'routeName' of undefined

This error is located at:
    in DrawerView (at DrawerNavigator.js:127)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:412)
    in RCTView (at View.js:112)
    in View (at CardStack.js:411)
    in RCTView (at View.js:112)
    in View (at CardStack.js:410)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:112)
    in View (at CardStack.js:383)
    in RCTView (at View.js:112)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at Router.js:67)
    in App (at Router.js:88)
    in Router (at App.js:197)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

**Comment by GGWacky** [comment]
I'm having an issue using react-native-router-flux along with react-native-drawer. The code compiles but the drawer does not open for some reason. The render method in the Drawer component never seems to execute. I've been stuck for hours on this bug, and couldn't find any similar issues on the internet. Just wondering if I could have missed.

Drawer.js
`export default class MyDrawer extends Component<{}> {
  render() {
    const state = this.props.navigationState;
    const children = state.children;

    return (
      <Drawer
        open={state.open}
        onOpen={()=>Actions.refresh({key:state.key, open: true})}
        onClose={()=>Actions.refresh({key:state.key, open: false})}
        content={this.drawerContent()}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        closedDrawerOffset={-3}
      >
        <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
      </Drawer>
    );
  }
}`

`export default class App extends Component<{}> {
  render() {
    return (
      <Router>
        <Scene key="root">
          <Scene key="pageThatCallsDrawer" component={PageThatCallsDrawer}/>
          <Scene key="myDrawer" type={ActionConst.RESET} contentComponent={MyDrawer} open={true}>
            <Scene key="firstOption" component={FirstOption}/>
            <Scene key="secondOption" component={SecondOption}/>
            <Scene key="thirdOption" component={ThirdOption}/>
          </Scene>
        </Scene>
      </Router>
    );
  }
}`

**Comment by jaysassyinfotech** [comment]
@phantom1299 @jigarmistry @filipemonteiroth @AAverin 
**SideBar.js**
[import React from "react";
import { AppRegistry, Image, StatusBar, ImageBackground } from "react-native";
import {
    Button,
    Text,
    Container,
    List,
    ListItem,
    Content,
    Icon
} from "native-base";
const routes = ["Home", "Profile","NextPage"];

export default class SideBar extends React.Component {
    render() {
        return (
            <Container>
                <Content> 
                    <ImageBackground
                        source={require('../../../assets/drawer-cover.png')}
                        style={{
                            height: 120,
                            alignSelf: "stretch",
                            justifyContent: "center",
                            alignItems: "center"
                        }}
                    >
                        <ImageBackground
                            square
                            style={{ height: 80, width: 70 }}
                            source={require('../../../assets/logo.png')}
                        />
                    </ImageBackground>
                </Content>
            </Container>
        );
    }
}](url)
**NavigationDrawer.js**
[import React, { Component } from 'react';
import Drawer from 'react-native-drawer';
import SideBar from './SideBar';
import {Actions, DefaultRenderer} from 'react-native-router-flux';

export default class NavigationDrawer extends Component {
    render(){
        const state = this.props.navigationState;
        const children = state.children;
        console.log("NavigationDrawer >> state >>",state)
        console.log("NavigationDrawer >> children >>",children)
        return (
            <Drawer
                ref="navigation"
                open={state.open}
                onOpen={()=>Actions.refresh({key:state.key, open: true})}
                onClose={()=>Actions.refresh({key:state.key, open: false})}
                type="displace"
                content={<SideBar />}
                tapToClose={true}
                openDrawerOffset={0.2}
                panCloseMask={0.2}
                negotiatePan={true}
                styles={drawerStyles}
                tweenHandler={(ratio) => {
                  return {
                    mainOverlay: { opacity: ratio === 0 ? 0 : 0.3, backgroundColor: '#000' }
                  }
                }}
                >
                <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </Drawer>
        );
    }
}

const drawerStyles = {
    drawer: {
        shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 1
    },
    main: { paddingLeft: 0 }
}](url)
**Applications.js**
[import React from 'react';
import { Router, Scene,Drawer,ActionConst } from 'react-native-router-flux';
import Login from './Login/Login';
import Profile from './Profile/Profile';
import NextPage from './NextPage/NextPage';
import Home from './Home/Home';
import SideBar from './Home/SideBar';
import NavigationDrawer from './Home/NavigationDrawer';

class Appllication extends React.Component {
    render() {
        return (
            <Router hideNavBar="true"> 
                <Scene key="root">
                    <Scene key="Login" component={Login} initial={true} hideNavBar/>
                    <Scene key="Home" component={Home} title="Home" hideNavBar/>
                    <Scene key="drawer" type={ActionConst.RESET} component={NavigationDrawer} open={false} > 
                        <Scene key="main"> 
                            <Scene key="Profile" 
                                component={Profile} 
                                title="Profile" 
                                hideNavBar={false} /> 
                            <Scene key="NextPage" 
                                component={NextPage} 
                                title="NextPage" 
                                hideNavBar={false} /> 
                        </Scene>
                    </Scene>
                </Scene>
            </Router>
        );
    }
}

export default Appllication;](url)

Hear i include 3 file Applications.js , NavigationDrawer.js  and Side bar js. When i click on drawer button using this <Button  transparent onPress={() => Actions.drawer() } >. Drawer not open in view some error face TypeError: undefined is not an object (evaluating 'state.children'). How to solve that?

**Comment by shubham81407** [comment]
@jigarmistry can you provide some basic example.

**Comment by remoteportal** [comment]
Are there TWO different versions of Drawer?  Perhaps version 3 and version 4.  The version 4 API  doesn't mesh with many of these examples.
