### ISSUE TITLE
Scene component and navBar do not work together

### ISSUE THREAD

**Issue by AAverin** [aksonov/react-native-router-flux#1752]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^v3.38.0
- react-native v0.42.3

### Expected behaviour
Following https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md
and adding both `component={Drawer}` and `navBar={MyCustomNavBar}` should result in a custom navbar with drawer behavior.

### Actual behaviour
Custom navbar is not applied

### Steps to reproduce

Having react-native + react-native-router-flux + react-native-drawer + react-native-material-design
1. Follow https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md for Drawer integration
2. Fix following code
```
<Router
            // then wrap your tabs scene with Drawer:
            <Scene key="drawer" component={NavigationDrawer} open={false} >
                <Scene key="main" tabs={true} >
                ....
            </Scene>
        </Scene>
```

With 
```
<Router>
            <Scene key="drawer" component={Drawer} navBar={ToolbarAndroid}>
                <Scene key="main">
                    <Scene key="mainScreen"
                        leftIconAndroid='menu'
                        type='replace'
                        title="MainScreen"
                        component={MainScreen}
                        initial
                    />
                </Scene>
            </Scene>
        </Router>
```
3. Provide ToolbarAndroid
```
import React, { Component } from 'react';
import { PropTypes, Text, View } from 'react-native';
import { Toolbar } from 'react-native-material-design';
import { NavBar, Actions } from 'react-native-router-flux';

export default class ToolbarAndroid extends NavBar {

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <Toolbar
        title={this.props.title }
        icon={ this.props.leftIconAndroid }
        onIconPress={ this.props.onLeftPressAndroid }
        primary='paperTeal'
        actions={this.props.rightIconAndroid && [{
            icon: this.props.rightIconAndroid,
            onPress: this.props.onRightPressAndroid
        }]}
      />
    );
  }
}
```
4. Expect to see a teal material Toolbar on Android and observe default navBar with odd blue burger menu

**Comment by kamilski81** [comment]
Have you tried setting the navBar explicitly on the scene? <Scene navBar=""/>

**Comment by iiitmahesh** [comment]
@AAverin Did u solved this??

**Comment by roseniltonreis** [comment]
Same error with me, Did you solved this?
