### ISSUE TITLE
Back button disappears when I switch tabs

### ISSUE THREAD

**Issue by shwetachoudhary06** [aksonov/react-native-router-flux#1758]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.0

Following are my scenes

```
<Scene key="tabbar" tabs={true}>
     <Scene key="tab1" title="Tab 1" icon={TabIcon}>
       <Scene key="recommendations" component={RecommendationsScene} title="Reccomendations" />
     </Scene>
     <Scene key="tab2" title="Tab 2" icon={TabIcon}>
       <Scene key="graph" component={GraphScene} title="Graph" />
     </Scene>
     <Scene key="tab3" title="Tab 3" icon={TabIcon}>
       <Scene key="editMetric" component={EditMetricScene} title="Edit Metric" />
     </Scene>
   </Scene>
```

The tab screen shows everything but when I switch between tabs, the Back button disappears.
It seems the Nav Bar is getting completely refreshed when switching tabs.

**Comment by JCDJulian** [comment]
Having the same issue. It would be nice to get this checked out.

**Comment by OhaiBBQ** [comment]
+1

@JCDJulian @shwetachoudhary06 Do either of you know if this behavior recently started occurring? Was it working in past releases?

**Comment by OhaiBBQ** [comment]
I've been digging into this. My scene schema works with v3.36.0. It seems that #1312 reverted functionality that made this work, since there were some other bugs that were introduced by #1057.

I'll see if I can figure out what issues there were with #1057 & add this functionality back to RNRF.

**Comment by JCDJulian** [comment]
This is my first time using RNRF so I don't have anything to compare it to. Thanks for looking into it!

**Comment by raphh11** [comment]
Having the same issue using `react-native-router-flux@3.35.0`

**Comment by OhaiBBQ** [comment]
Just submitted a PR, hopefully it gets merged soon. Waiting for feedback there.
