### ISSUE TITLE
Shouldn't define sceneStyle several times?

### ISSUE THREAD

**Issue by pbassut** [aksonov/react-native-router-flux#1765]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Expected behaviour

I thought I didn't have to define `sceneStyle` everytime like this:
![image](https://cloud.githubusercontent.com/assets/1500037/24717813/1600f7b2-1a0a-11e7-866b-cbd335300c49.png)

Because by defining once in the common ancestor `Scene`, it would propagate to every children.
Am I missing something?

### Actual behaviour

Define only once on the parent scene tag.

**Comment by pbassut** [comment]
I mean, I could write a HOC to suit my needs but come on.

**Comment by OhaiBBQ** [comment]
Hi @pbassut, the RNRF way is to use the `passProps` flag on the parent.


I, however, don't really like that approach. Instead, I just extend RNRF Scene
e.g.
```js class StyledScene extends Scene { }
StyledScene.defaultProps = { sceneStyle: ... }```

**Comment by pbassut** [comment]
I'm using the passProps approach. Sorry I missed that in the docs.
