### ISSUE TITLE
Not working on react-native 43.1

### ISSUE THREAD

**Issue by bilby91** [aksonov/react-native-router-flux#1767]
### Version
- react-native-router-flux v3.38.0
- react-native v0.43.1

### Expected behaviour
It should as previous versions

### Actual behaviour
The packager crashes because is not able to resolve the `react/lib/ReactComponentWithPureRenderMixin` module.

When updating to `react-native` 0.43.1 you need to update React to 16.0.0-alpha.6. I think this version of React drops the pure-render-mixin code and that is why is not finding the module. Any ideas on how to workaround this issue ?

### Steps to reproduce

1. Install react-native 0.43.1 with React 16.0.0-alpha.6 and latest version of react-native-router-flux
2. Run react-native packager

**Comment by gabrielgomesferraz** [comment]
Same issue on https://github.com/aksonov/react-native-router-flux/issues/1761
