### ISSUE TITLE
Action.pop: Refresh only a specific section in render

### ISSUE THREAD

**Issue by IronTony** [aksonov/react-native-router-flux#1768]
Hello all,

I finally got how to use `Actions.pop({ refresh: {key: ....} })`. Actually when I press the Back button I call `Actions.pop` and the parent component will refresh perfectly.

I would like to know if there is a way to force the re-render only of a specific component of the parent view and not the entire parent.

Thank you in adance

- react-native-router-flux v3.30.1
- react-native v0.35

**Comment by afilp** [comment]
I have (almost) the same problem.

The "refresh" makes us lose the scroll position of the parent (which is ScrollView). We do not want to lose this. How?

**Comment by OscarYuen** [comment]
I have the same issue. Any way to deal with it?
My case is a tab view under the parent scene. The tab view is unable to refresh
