### ISSUE TITLE
Multiple screens in a tab

### ISSUE THREAD

**Issue by iiitmanikanta** [aksonov/react-native-router-flux#1770]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.42.0

### Expected behaviour
We are on 4th screen of tab1 and navigated to tab2. If we came to tab1, the same 4th screen should be shown

### Actual behaviour
In place of previous position of screens, tab1 is showing first screen.

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by gabrielgomesferraz** [comment]
+1

**Comment by iiitmanikanta** [comment]
Changing react-native-router-flux from 'v3.37.0' to '3.37.0' worked for me

**Comment by diegorodriguesvieira** [comment]
@iiitmanikanta  from 3.37 to 3.38?

**Comment by iiitmanikanta** [comment]
@diegorodriguesvieira yeah from 3.37 to 3.38. give type={ActionConst.REFRESH} for tab scenes. It solved the issue

**Comment by alsh76** [comment]
@iiitmanikanta if tab scenes have `type={ActionConst.REFRESH}` then `REACT_NATIVE_ROUTER_FLUX_JUMP` is not triggered anymore when tabs are switched 

that does not look like right behavior
