### ISSUE TITLE
Question on making Actions.KEY like tabs?

### ISSUE THREAD

**Issue by ajmakhl** [aksonov/react-native-router-flux#1776]
So for my Project I have a custom footer.
The footer contains 3 buttons each button has an onPress={Actions.KEY}.
<img width="393" alt="screen shot 2017-04-08 at 9 16 50 pm" src="https://cloud.githubusercontent.com/assets/17507288/24833757/b96c6be6-1ca0-11e7-82ed-e992c01805de.png">

I want to switch between scenes without losing the scene state.  

Say Button 1 Scene contains a listView.. 
I want to switch between that Scene and other Scenes without losing the ListView scrolled location.

Something that resembles pop but with navigating between Scenes.

**Comment by mbenjamin618** [comment]
Check out this [issue](https://github.com/aksonov/react-native-router-flux/issues/1686)
