### ISSUE TITLE
How to save current tab's scene and state?

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#1778]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.3

### Expected behaviour
In my one tab, I have nested scenes and I want to save my current scene and state for that tab when I switched to other tabs then came back to the first tab.

### Actual behaviour

Switching between tabs lose route scenes in that specific tabs.

**Comment by mbenjamin618** [comment]
Check out [Issue 1686](https://github.com/aksonov/react-native-router-flux/issues/1686)
