### ISSUE TITLE
Actions.pop() doesn't work when pushing same scene over itself with different props

### ISSUE THREAD

**Issue by Jahans3** [aksonov/react-native-router-flux#1785]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.3

### Expected behaviour

A user clicks on a button inside a scene, the same scene is then re-rendered with new props. When a user clicks the back button they call `Actions.pop()` and go back to the previous scene (in this case, the same scene with different props).

### Actual behaviour

A user clicks on a button inside the scene, the same scene is re-rendered with new props. All good so far. When the user clicks the back button and calls `Actions.pop()` the action is dispatched but nothing happens.

### Steps to reproduce

1. Create a scene, add it to a tab bar
2. Inside that scene, call the same with different props
3. Try calling `Actions.pop()`, the action is dispatched but it has no effect

It's possible to make this work, but not when the scene is inside a tab bar. You have to duplicate the scene and set `clone={true}`. Should this not be possible without the need to copy an entire scene?

**Comment by pkjijie** [comment]
you can define your scene like this:(use clone)
 <Scene clone key={module.frame}
                               component={FrameComponent}
                               title="frame"
                               initial={main === module.frame}
                               hideNavBar={true}/>

**Comment by Jahans3** [comment]
I have got it working by using the `clone` prop but this didn't work when it's inside a tab bar, so I had to duplicate the scene outside the tab bar which isn't ideal
