### ISSUE TITLE
back button cut off

### ISSUE THREAD

**Issue by laclance** [aksonov/react-native-router-flux#1788]
"react-native": "0.42.3",
    "react-native-router-flux": "^3.38.0",

using backButtonImage={closeButtonCharcoal} cuts off the image on the sides

![screen shot 2017-04-12 at 1 23 56 pm](https://cloud.githubusercontent.com/assets/10835285/24955412/9e0beeae-1f83-11e7-9c15-92fcef7c14f9.png)

**Comment by MattyK14** [comment]
Have you tried adding style to it?

**Comment by laclance** [comment]
I couldn't find a way to style it directly, only to override it.
So i changed this:
`backButtonImage={closeButtonCharcoal}`
to this:
`renderBackButton={()` => <Image style={{flex: 1}} source={closeButtonCharcoal}/>}
