### ISSUE TITLE
Help me plz: navbar render not correct

### ISSUE THREAD

**Issue by DjangoGG** [aksonov/react-native-router-flux#1792]
### Help
the navbar render is not correct (see the picture)
does anybody know how to handle this , please tell me, thank you very much

### Version
- react-native-router-flux v3.38.0
- react-native v0.42.0

### code
```
<Scene 
  key='tabHome' 
  title='首页' 
  icon={tabIcon} 
  navigationBarBackgroundImage={require('./Image/nav_bar.png')} 
  titleStyle={styles.navBarTitle} 
  backButtonImage={require('./Image/nav_back_arrow.png')}
>
navBarTitle: {
  backgroundColor: COLOR.clear,
  color: COLOR.white,
}
```
### Unexpected behaviour
![5s](https://cloud.githubusercontent.com/assets/15874921/25039054/5fdf4c36-2134-11e7-8165-780e71c2526b.jpg)
![6plus](https://cloud.githubusercontent.com/assets/15874921/25039055/613485ec-2134-11e7-8118-ad5d730228d9.jpg)

**Comment by i8wu** [comment]
You could try setting navigationBarStyle for the router
