### ISSUE TITLE
Can I hide Tabbar anytime I want?

### ISSUE THREAD

**Issue by lxfriday** [aksonov/react-native-router-flux#1796]

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by lxfriday** [comment]
update the props of scenes does nothing, I want to hide tabbar when I scroll the ListView

**Comment by isaacsun86** [comment]
Hide the tabbar and make a bar in your next view. That's what I did.

**Comment by lxfriday** [comment]
Maybe that is the only way

**Comment by supportclik** [comment]
@isaacsun86  how to do it?

**Comment by lxfriday** [comment]
Hide the tab in your router,and You make a tab youself.
