### ISSUE TITLE
resetTo and immediatelyResetRouteStack action types

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#1798]
I am looking for resetTo and immediatelyResetRouteStack action types similar to `React Native Navigator's`  [resetTo](https://facebook.github.io/react-native/docs/navigator.html#resetto) and [immediatelyResetRouteStack](https://facebook.github.io/react-native/docs/navigator.html#immediatelyresetroutestack) methods, if you have any solution to this let me know please. Thanks.

**Comment by pratomchaip** [comment]
Have you tried popTo()?
`Actions.popTo('SceneA')`

**Comment by shukerullah** [comment]
@pratomchaip no, will this clear stack?

**Comment by pratomchaip** [comment]
SceneA -> SceneB -> SceneC -> popTo('SceneA')
If you mean, will it trigger `componentWillUnmount` on SceneB and SceneC... yes.

**Comment by shukerullah** [comment]
After successfully login I want to reset my navigator to Home screen with a animation. This is possible with React Native Navigator's (resetTo)[https://facebook.github.io/react-native/docs/navigator.html#resetto]. I want same functionality with `react-native-router-flux`

**Comment by pratomchaip** [comment]
I see... hmm, then what about:
`Actions.homeScreen({type: 'reset'})` ?

**Comment by shukerullah** [comment]
This will reset navigator and redirect to home screen without animation but I want animation.

**Comment by baetschjunge** [comment]
@shukerullah we are also looking for something like this
popTo should go back to selected screen and also clear stack but (for us) it doesn't at the moment, just pops back
using 3.35.0

did u find any solution?
