### ISSUE TITLE
popTo initial scene visibly shows scenes in between as well

### ISSUE THREAD

**Issue by pratomchaip** [aksonov/react-native-router-flux#1799]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.40.0

### Expected behaviour
I have (Initial) SceneA, SceneB and SceneC
When at SceneC and I use `Action.popTo('SceneA')`, SceneA should slide in from the left and push SceneC out to the right.

### Actual behaviour
When at SceneC and I use `Action.popTo('SceneA')`, SceneA slides in from the Left and pushes SceneC out to the right as expected... 
... but I can see SceneB sliding from left to right, in between SceneA and SceneC, as well.

### Steps to reproduce

1. SceneA
2. push to SceneB
3. push to SceneC
4. At SceneC, `Actions.popTo('SceneA')`
5. SceneA pops in from the Left but SceneB also visibly animates from left to right as well.

Is this normal behaviour or is it a bug?

If it is normal behaviour, can anyone tell me how do I `popTo` the initial SceneA without the intermediate scenes (i.e. SceneB) showing as well, please?

**Comment by hectorsc** [comment]
I have this same problem. When you return to the parent scene, the other scenes can be see turn, and it's very annoying. :S

I have tested with:
-  Actions.pop({ key: 'myScene' })  **It doesn't work**
-  Actions.myScene({type: ActionConst.POP_TO})  **It doesn't work**
-  Actions.myScene({ type: 'pop' })  **It doesn't work**

**Is there any solution? :(**
