### ISSUE TITLE
From Nested Scene To Other Nested Scene Navigate

### ISSUE THREAD

**Issue by yasemincidem** [aksonov/react-native-router-flux#1801]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.3

### Expected behaviour
I have a nested scenes.I want to navigate from nested scene to other nested scene.But i didn't navigate.Actually here is example :
```
<Scene>
           <Scene key="scene1">
                <Scene key="scene2" hideNavBar component={Scene2}/>
            </Scene>
            <Scene key="scene3">
                <Scene key="scene4" hideNavBar component={Scene4}/>
            </Scene>
</Scene>
```
I want go to scene4 page on scene2 page.Here is code block that i have tried:
```
on `Scene2` component:
Actions.scene4();
```
i have tried that but i didn't happen anything also it did not throw an error.
### Actual behaviour
Actually when i try this code block, it is wanted to navigate to `Scene4` page
`Actions.scene4()` ===> `Scene4 page`

**Comment by yasemincidem** [comment]
@aksonov can you check this issue ?

**Comment by KevinHu2014** [comment]
If you want to navigate from scene2 to scene4.
You should try from scene2 to scene3 instead.

**Comment by yasemincidem** [comment]
Yes,I agree with you for parent child that has one child.But if parent scene called scene3 has multiple children,your recommendation is fail.Let me give an example for this situation that I mean.
```
<Scene>
           <Scene key="scene1">
                <Scene key="scene2" hideNavBar component={Scene2}/>
            </Scene>
            <Scene key="scene3">
                <Scene key="scene4" hideNavBar component={Scene4}/>
                <Scene key="scene5" hideNavBar component={Scene5}/>
                <Scene key="scene6" hideNavBar component={Scene6}/>
            </Scene>
</Scene>
```
Parent scene has multiple children in this example.When I want to navigate from scene2 to scene5,your recommendation is fail because of I use Actions.scene3.if i use this code block ,I go to scene4 not scene5.Because if you navigate parent key of scene3, you will go to the page that parent key has first child.I hope I explain clearly myself.Have you any idea for this situation ?

**Comment by yusmarcastro** [comment]
I had the same problem!!! any solution guys?????????????????

**Comment by kirillpisarev** [comment]
Same problem. I tried to set `initial` scene prop of nested scenes dynamically to point the navigator which nested scene to render when navigating to parent but has no luck. Has anyone any appropriate solution?

**Comment by jamalx31** [comment]
+1

**Comment by 0mkara** [comment]
```
<Scene>
           <Scene key="scene1">
                <Scene key="scene2" hideNavBar component={Scene2}/>
            </Scene>
            <Scene key="scene3">
                <Scene key="scene4" hideNavBar component={Scene4}/>
                <Scene key="scene5" hideNavBar component={Scene5}/>
                <Scene key="scene6" hideNavBar component={Scene6}/>
            </Scene>
</Scene>
```

To route from scene2 to scene4 you need to do following
```
Actions.scene3()
Actions.scene4()
```

Another working example
```
<Scene key="root">
    <Scene key="auth" tabs={false} hideNavBar>
        <Scene key="login" component={LoginComponent} title="Login"/>
    </Scene>
    <Scene key="drawer" component={NavigationDrawer} close>
        <Scene key="main" tabs={false}>
            <Scene key="home" component={HomeComponent} initial/>
        </Scene>
    </Scene>
</Scene>
```
Here to go from login scene to home scene I had to do
```
Actions.drawer();
Actions.main();
Actions.home();
```

**Comment by kirillpisarev** [comment]
@0mkara as i wrote above this solution has much overhead

**Comment by 0mkara** [comment]
@kirillpisarev that is true, I think it is costing my app much more time to move from scene to scene. Does anyone else experiences that behaviour ?

**Comment by petervavro** [comment]
Really don't like double , triple calling ... Is there better solution ? Thanks

**Comment by Vladislav-Vinnikov-Narvar** [comment]
+1

**Comment by ptaking** [comment]
Any update on this?

**Comment by ravalikarumuri** [comment]
Hello  Aksonov,
I want to send data from one router child to another router child in React Native Router flux, the call is happening after sometime, meanwhile the page is rendering, so I am not getting data populated, Can you help me to fix this issue.
Here is how my router  structure.
<Router>
      <Scene key="root" hideNavBar>
        <Scene key="auth">
          <Scene key="login" component={SignIn} title="Login" initial />
        </Scene>
        <Router key="register">
          <Scene key="createUser" component={CreateUserForm} title="Create Account" />
        </Router>
        <Router key="dashboard">
          <Scene key="homePage" component={Home} title="Dashboard" hideNavBar />
        </Router>
        <Router key="userSettings">
          <Scene key="updateUser" component={EditUserForm} title="Edit Profile" />
        </Router>
      </Scene>
    </Router>

**Comment by jhon-andrew** [comment]
Is there a solid guide to navigating through nested scenes already?
