### ISSUE TITLE
 Duplicate module name: TouchHistoryMath

### ISSUE THREAD

**Issue by cherishloveyou** [aksonov/react-native-router-flux#1806]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.43.3

### Actual behaviour

naming collision:

### Steps to reproduce

1.
2.
3.

**Comment by wuyunqiang** [comment]
me too ,you know why?

**Comment by devkhan** [comment]
https://github.com/facebook/react-native/issues/7384
