### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by shettyrahul8june** [aksonov/react-native-router-flux#1807]
### Version
Tell us which versions you are using: 

"react": "16.0.0-alpha.6",
"react-native": "0.43.3",
"react-native-router-flux": "^3.38.1",

### Expected behaviour
No warnings in the console.

### Actual behaviour
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Scene.js**
import React, { PropTypes } from 'react';

### Steps to reproduce
Create a `<Scene />` with title and you should be able to see this Warning.

**Comment by karltaylor** [comment]
I'd check out https://github.com/reactjs/prop-types, they've removed it from the main react package.

**Comment by iegik** [comment]
Jest test failed:
```
TypeError: Cannot read property 'style' of undefined
      
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Scene.js:30:106)
      at Object.<anonymous> (node_modules/react-native-router-flux/src/Actions.js:10:12)
      at Object.<anonymous> (node_modules/react-native-router-flux/index.js:1:398)
```
