### ISSUE TITLE
 Duplicate module name: react-native-packager

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#1809]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.43.3

### Expected behaviour

everything works fine

### Actual behaviour

error:

> Failed to build DependencyGraph: @providesModule naming collision:
>   Duplicate module name: react-native-packager
>   Paths: $$$$/node_modules/react-native-router-flux/node_modules/react-native/packager/package.json collides with $$$$$$/node_modules/react-native/packager/package.json
> 
> This error is caused by a @providesModule declaration with the same name across two different files.
> Error: @providesModule naming collision:
>   Duplicate module name: react-native-packager
>   Paths: $$$$$$$$/node_modules/react-native-router-flux/node_modules/react-native/packager/package.json collides with $$$$$$$/node_modules/react-native/packager/package.json
> 

### Steps to reproduce

1. react-native init
2. yarn add react-native-router-flux
3. require this module
4. build/run the application

**Comment by ChristianTucker** [comment]
In the mean-time you can remove react-native from the node_modules folder in react-native-router-flux. however ultimately the example dependencies should be removed from the module and added to the examples package.json

**Comment by itinance** [comment]
Thx @ChristianTucker This helped!

**Comment by itinance** [comment]
PR sent

**Comment by leyuan** [comment]
I have tried to remove them and move them to `devDependencies` and `peerDependencies`, but I got the following errors
```
 FAIL  __tests__/xxx-test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, stat '{projectDir}/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Core/ErrorUtils.js'
        at Error (native)

      at Object.fs.statSync (fs.js:1000:11)
      at Object.statSync (node_modules/graceful-fs/polyfills.js:297:22)
      at Object.<anonymous> (node_modules/react-native/jest/setup.js:64:532)

```

Am I missing something here?

**Comment by leyuan** [comment]
Also is `React` a needed `dependency`? It caused me [react-ref-owner-error](https://facebook.github.io/react/warnings/refs-must-have-owner.html)

**Comment by pckz** [comment]
1. ```npm i react-native-router-flux@3.38.0 --save```
2. ```npm cache clean```
3. ```react-native run-ios```

**Comment by wuhenwuya** [comment]
+1
