### ISSUE TITLE
ERROR: UNMET PEER DEPENDENCY react@15.5.4

### ISSUE THREAD

**Issue by ugendrang** [aksonov/react-native-router-flux#1811]
Environment:
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4"

I have installed the latest react-native project and tried to install react-native-router-flux, but end up with the error message "UNMET PEER DEPENDENCY react@15.5.4". Is there any solution to use the react-native-router-flux package with the latest react-native?

C:\workspace\SampleProject>npm i --save react-native-router-flux
SampleProject@0.0.1 C:\MyDrive\Project\workspace\SampleProject
`-- react-native-router-flux@3.38.1
  +-- lodash.isequal@4.5.0
  +-- UNMET PEER DEPENDENCY react@15.5.4
  +-- react-addons-pure-render-mixin@15.5.2
  +-- react-dom@15.5.4
  | `-- prop-types@15.5.8
  +-- react-native@0.41.2
  | +-- glob@5.0.15
  | +-- jest-haste-map@18.0.0
  | | `-- multimatch@2.1.0
  | |   `-- array-union@1.0.2
  | +-- mime-types@2.1.11
  | | `-- mime-db@1.23.0
  | `-- regenerator-runtime@0.9.6
  +-- react-native-experimental-navigation@0.26.12
  | `-- clamp@1.0.1
  +-- react-native-tabs@1.0.9
  `-- react-static-container@1.0.1

npm WARN react-native@0.41.2 requires a peer of react@~15.4.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none was installed.

**Comment by Moyal17** [comment]
same problem

**Comment by sock-osg** [comment]
I have the same problem, can be the issue related to OS? In Ubuntu it's working fine but on Linux Mint it's not working.

**Comment by cobaltsys** [comment]
same problem

**Comment by trikyas** [comment]
Same problem

**Comment by Joel-Mercier** [comment]
Yep same, does anyone have a package.json file locked with the latest working pair of react, react-native and react-native-router-flux ?

**Comment by Joel-Mercier** [comment]
I fixed this thanks to #1803 and added the 3.38.0 version of react-native-router-flux

**Comment by roseniltonreis** [comment]
same problem

**Comment by wvicioso** [comment]
I fixed this by removing the little `^` symbol in my package.json file in front of the version number of  react-native-router-flux. Removing that symbol forces `npm install` to install the version indicated instead of the newest version.

**Comment by dylannlaw** [comment]
Version 3.38.1 is having issue. By following @wvicioso solution, it should temporary fixes the problem.

**Comment by ugendrang** [comment]
Issue still occurs in  react-native-router-flux@3.38.1

**Comment by ThiagoLottici** [comment]
Even after installing react-native-router-flux@3.38.0 I was getting a dependency issue with react-static-container. To solve this I followed this https://github.com/aksonov/react-native-router-flux/issues/1710 . Go to `react-native-router-flux/src/TabbedView.js` and replace the third line of this file with:
`const StaticContainer = require('react-native/Libraries/Components/StaticContainer.react'); ` You can check this file in the path location inside react-native module. Doing this you will remove the react-native-router-flux dependency with react-static-container. Now remove the react-static-container folder (if it doesn't have any other dependency with other modules). This worked for me.

**Comment by ridhwandaud** [comment]
I use yarn install , and @wvicioso solution . work perfectly

**Comment by moadqassem** [comment]
I think there has something to do with ```react-native-router-flux``` module, when I run it  ```rm -rf node_modules``` and then  ```npm install``` it works fine, but once I try to get  ```react-native-router-flux``` it crashes

**Comment by foxsent** [comment]
same problem

**Comment by jolinkomo-code** [comment]
same problem

**Comment by unadlib** [comment]
+1

**Comment by brimes** [comment]
Same problem.

**Comment by NightFarmer** [comment]
+1

**Comment by razki** [comment]
+1

**Comment by valerybodak** [comment]
+1

**Comment by wdmeida** [comment]
+1

**Comment by connordear** [comment]
+1

**Comment by Spookykiller** [comment]
+1

**Comment by akibe** [comment]
+1

**Comment by Bing-Xia** [comment]
+ 1 with version 0.38.1

**Comment by bvn13** [comment]
UNMET PEER DEPENDENCY react@15.5.3

**Comment by wvicioso** [comment]
use version 3.37.0

**Comment by encantador-coder** [comment]
Solution provided by @ThiagoLottici above works for me. It is at least a temporary fix until the react-native-router-flux library comes up with a newer version which fixes this issue.

**Comment by shortdistance** [comment]
same problem.

**Comment by arpitcrest** [comment]
same problem.

**Comment by ntvinh11586** [comment]
I had same problem, but I resolved it by upgrading NPM to newest version (v5.0) and after that I installed the lastest `react-native-router-flux` with no `UNMET PEER DEPENDENCY` error.

**Comment by pbialy** [comment]
I fixed this by updating react and npm.

**Comment by jolipixel** [comment]
Reinstalling yarn did the trick.

`npm install -g yarn`

**Comment by NightFarmer** [comment]
fixed it
I update npm to the latest version by `sudo npm install -g npm`
then recreate project by `react-native init MyProject`
then `npm i react-native-router-flux --save` successfully

**Comment by cavemanbravo** [comment]
yarn add whatever dependency. 

If you are using expo, you may encounter an error. Restart your expo.

**Comment by LeonidKokhnovich** [comment]
+1

**Comment by luminaxster** [comment]
+1. "+1. None of the fixes above worked for me with npm."

**Comment by Jogibaer1963** [comment]
+1 same issue with react-flip-move

![image](https://user-images.githubusercontent.com/15709263/31302530-130780f4-aac8-11e7-81e7-59e86d9309a1.png)

**Comment by queli1990** [comment]
npm install -g yarn
then create-react-app AppName
then npm install react-router
(sudo npm install -g npm)
