### ISSUE TITLE
reactNativeRouterFlux.Actions.xxx is not a function

### ISSUE THREAD

**Issue by jasan-s** [aksonov/react-native-router-flux#1813]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.3

Using Actions with firebase onAuthChanged()
I keep getting the error that 

> Actions.main() is not a function

 however If I call the Actions.main() after a separate  promise function has resolved the Actions workes fine. 

```
export function onAuthChange(user) {
  return (dispatch) => {
    if (!user) {
      dispatch(notAuthed())
    } else {
      Actions.main() // **ERROR IF CALLED HERE**
      // update user in firebase database
      const { uid, displayName, photoURL } = user
      updateUser({
        uid,
        displayName,
        photoURL,
      }).then(() => {
        dispatch(isAuthed(uid))
        // Route change using react-native-router-flux
        Actions.main() // **WORKS FINE HERE**
      })
    }
  }
}
```

But the issue of calling it after promise resolves is that for a Short time the my intial Scene of Login comes on before the EmployeeList Scene comes into View.

My Route:
```
<Router>
  <Scene key='login' component={AuthContainer} title='Please Login' />
  <Scene key='LibraryList' component={LibraryListViewContainer} title='Libraries' />
</Router>
```

**Comment by subhashdamodaran** [comment]
+Same here

**Comment by raoulj** [comment]
Encountering something similar.  Is this nested promise solution the best solution you found?  Did you isolate why this was happening?
