### ISSUE TITLE
Conditional first scene rendering with redux.

### ISSUE THREAD

**Issue by niklas-palm** [aksonov/react-native-router-flux#1814]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.35.0
- react-native v0.42.0

### Expected behaviour
If logging in, expect to navigate to the scene 'main' when login completed.

### Actual behaviour
remains on scene 'auth'.

```
class RouterComponent extends Component {

  renderScenes() {
    if (this.props.user === null) {
      return (
        <Scene key="auth" >
          <Scene
            key="login"
            component={LoginForm}
            title="Login"
            sceneStyle={{ marginTop: 65 }}
            initial
          />
        </Scene> 
      );
    }
    console.log('After if-clause')
    return (
      <Scene key='main' tabs tabBarStyle={{ backgroundColor: '#F8F8F8' }}>

        <Scene key="left" title="Left" icon={this.TabIcon.bind(this)}>

          <Scene
            sceneStyle={{
              marginTop: 65,
              marginBottom: 55
            }}
            key='feed'
            component={Feed}
            title='Feed'
          />

          <Scene
            sceneStyle={{
              marginTop: 65,
              marginBottom: 55
            }}
            key='voice'
            component={Voice}
            title='Lös titel'
          />

        </Scene>
      </Scene>
    );
  }

  render() {
    return (
      <Router>
        {this.renderScenes()}
      </Router>
    );
  }
}
const mapStateToProps = (state) => {
  return { user: state.auth.user } 
}

export default connect(mapStateToProps, { getVoices })(RouterComponent);
```

What i want, is for my application's first scene to depend on the login-state. Via Redux's connect-method, there's a prop (user) in my RouterComponent which I want to determine which scenes are rendered.

When first booting the app, the LoginForm is rendered, as expected. However, when I login (I have verified that user is not null when logged in) the scene "main" doesn't render, even though the console log after the if-clause is logged. The app just remains on the LoginForm. I don't understand what the problem is as I use conditional rendering via helper methods throughout the rest of the app.

Do observe that I've only included the first "tab" of the app due to brevity. I also didn't include any imports nor the tabIcon method, which I'm certain are working properly.

**Comment by quadsurf** [comment]
@niklas-palm this actually does work as expected... one caveat though, it only works if you have auth status predetermined (like on a prior screen)... if you are asynchronously determining auth status, it will not work since <Router> instantly needs children

**Comment by ethanyuwang** [comment]
whats a good way to implement this functionality. on react navigation we have https://reactnavigation.org/docs/en/switch-navigator.html specifically for this
