### ISSUE TITLE
Change route dynamically

### ISSUE THREAD

**Issue by bodhi** [aksonov/react-native-router-flux#182]
Is there any way to modify a route's properties after the initial render?

I want to dynamically add/remove buttons to the navbar (by changing the `rightTitle` and `onRight` props of `<Route>`).

**Comment by lynndylanhurley** [comment]
@bodhi - I'm having a similar issue. I proposed a solution here: https://github.com/aksonov/react-native-router-flux/issues/158#issuecomment-181618505 - would something like this help you solve your problem?

**Comment by aksonov** [comment]
@bodhi Have you tried to do it with `Actions.ROUTE({rightTitle:..., onRight:....})` where ROUTE is your new route?

**Comment by bodhi** [comment]
No I haven't. Is this the correct/preferred way to deal with this? Maybe I missed it in the docs.

**Comment by aksonov** [comment]
Closing it for now.

**Comment by erdostom** [comment]
@aksonov I'm trying to do something with this now, where I call the current route with Replace and a new rightTitle, but it doesn't work.

```
    const rightTitle = getState().currentStack.editMode ? 'Edit' : 'Done'
    Actions.stackstab_stackview({ type: ActionConst.REPLACE, rightTitle})
```

running RN 0.30 and RNRF 3.30.1

**Comment by kiranruth** [comment]
@erdostom did you get this it to work ?
TIA

**Comment by erdostom** [comment]
Yes, I got the code above to work ultimately.
