### ISSUE TITLE
Navigate routes while keeping one component the same

### ISSUE THREAD

**Issue by lightninglu10** [aksonov/react-native-router-flux#1821]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.0

Hey guys, is there anyway to navigate routes but keep one component static? In the web version of react-router you can initialize a parent route and then render the children of the parents in different URL's. Is there any sort of behavior like this for react-native-router-flux?

For example, in the Spotify app, the player component always stays on top no matter where you go in the app. How do we do this behavior with react-native-router-flux?

**Comment by twksos** [comment]
From our experience, you just need to wrap an View outside your Router, and append your shared component after it with absolute position.

**Comment by privateOmega** [comment]
@lightninglu10 any updates? I am looking for the same answer.  Tried switching to react-router native version, couldn't make sense out of anything.

**Comment by lightninglu10** [comment]
@privateOmega I haven't had time to do it yet, but I think @twksos's advice is good. Just put it outside of the Router, and you can use Redux to send signals of when / when not to display the component you want.

**Comment by privateOmega** [comment]
@lightninglu10 can I also perform authentication check using that solution?

**Comment by lightninglu10** [comment]
@privateOmega What's your use case / flow? I have an authentication check without keeping the component live. 

It goes in my flow that first your check if a user is authenticated or not in a Home.js container (basically a splash screen), and then that container pushes you to the auth screen if you're not authenticated or to the main app if you are.

**Comment by lightninglu10** [comment]
Issue resolved: put the component you want live outside of the router.

**Comment by dhavrosh** [comment]
@lightninglu10  was it working OK? Cause when i put it outside of router, it appeared but the router started to work incorrectly (with pushing new scene design become broken)
