### ISSUE TITLE
Double touch TabIcon will remount the page

### ISSUE THREAD

**Issue by PeterRock** [aksonov/react-native-router-flux#1823]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42

### Expected behaviour
I upgraded the packages of my application.
After that, when I double touched the tabicon, the reference tabpage will remount, and the console show `type: 'REACT_NATIVE_ROUTER_FLUX_JUMP'`.

### Actual behaviour
It will refetch data from server when it remount.
Please who can tell me how to prevent it.

**Comment by i8wu** [comment]
I've got a PR that should fix what you're talking about https://github.com/aksonov/react-native-tabs/pull/51

**Comment by Clowning** [comment]
You need to downgrade to 3.37 !
``` "react-native-router-flux": "3.37.0" ```

It worked for me
