### ISSUE TITLE
My scene is not unmount

### ISSUE THREAD

**Issue by Clowning** [aksonov/react-native-router-flux#1825]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "3.37.0"
- "react-native": "0.41.2"

### Expected behaviour

I've a list with some different data in each row. When i tap on one of them, i have another page with some informations about a specific row.

### Actual behaviour

When i tap too fast, my page doesn't change, the informations are about the previous item i was tapped! The page is not unmount fast enough :/ ! 

So do you have any ideas to force to mount my component / page when i pop back on my list ? 

Thanks :-)

**Comment by eemebarbe** [comment]
Having the same issue

**Comment by hellomaya** [comment]
This time, redux or [mobx](https://mobx.js.org/) will be useful addition, for example, if you are using mobx, then try to observer the item in your detail page, and change the item data at list, it will work just fine.

**Comment by Clowning** [comment]
@hellomaya  Yes i guess, but this comportment is not normal ! Component will be unmount just after pop ! No few times after! But yes, with Redux, this issue will be solved !

**Comment by hellomaya** [comment]
@Clowning 

Agree, as the component is managed to be unmounted by RN asynchronously, I saw this happened a lot, try use unmountScene in your ```<Scene/>```, could help, but not much.

**Comment by GuillaumeMunsch** [comment]
Any news on this ? This issue has been there for a while now ...

**Comment by vingrad** [comment]
+1

**Comment by 426-330** [comment]
+1

**Comment by rparma** [comment]
+1
