### ISSUE TITLE
RecyclerViewBackedScrollView - unable to resolve module

### ISSUE THREAD

**Issue by pedro-mass** [aksonov/react-native-router-flux#1828]
### Version
Tell us which versions you are using: 

- react-native-router-flux: 3.38.1
- react-native: 0.43.4

### Expected behaviour
Expected to load the scene like previous version (RN 0.42.3)

### Actual behaviour
Simulator complains about being unable to find the RecyclerViewBackedScrollView within React-Native.

### Steps to reproduce

1. Use React-Native 0.43 cli to initialize a project
2. look at the package.json 
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-router-flux": "^3.38.1",
3. Initialize a router with one scene
4. load up the simulator

**Comment by pbassut** [comment]
`npm install -g react-native-git-upgrade`
`react-native-git-upgrade`

Does that solve it?

**Comment by pbassut** [comment]
Also, if you're using master you should delete `react-native-router-flux`'s `node_modules/`

**Comment by pedro-mass** [comment]
Looks like deleting `react-native-router-flux`'s `node_modules/` fixed, but I did run it after installing and running react-native-git-upgrade.

Is this something that has to be done after every clean install?

**Comment by pbassut** [comment]
After every npm install. Unless you stop using the master branch

Enviado do meu iPhone

Em 30 de abr de 2017, às 19:44, Pedro Mass <notifications@github.com<mailto:notifications@github.com>> escreveu:


Looks like deleting react-native-router-flux's node_modules/ fixed, but I did run it after installing and running react-native-git-upgrade.

Is this something that has to be done after every clean install?

**Comment by pedro-mass** [comment]
the master branch for `react-native-router-flux`?

**Comment by pbassut** [comment]
Yes. Are you using it?

**Comment by Nemsae** [comment]
Or just rollback to v 3.38.0

`npm install --save react-native-router-flux@3.38.0`

**Comment by teyou** [comment]
tried rollback to 3.38.0 and also tried to upgrade from 0.43.4 to 0.44.
Still throws me an error on RecyclerViewBackedScrollView

`
renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}
`

**Comment by fbacker** [comment]
Same issue
"react": "15.5.4",
"react-native": "0.44.0",
"react-native-router-flux": "^3.38.1",

**Comment by akinolu52** [comment]
same issue on v4

"react-native-router-flux": "^4.0.0-beta.32",

**Comment by akinolu52** [comment]
@aksonov any help?

**Comment by colorfulberry** [comment]
@akinolu52  How to you solve it at end?

**Comment by akinolu52** [comment]
Yeah; That is what I used @colorfulberry

**Comment by clevertree** [comment]
To solve this problem I had to explicitly state the version
    "react-native-router-flux": "3.38.0",

If you do:
    "react-native-router-flux": "^3.38.0",
Then the later version with the 127 phantomChildren libraries will be used instead and break building. Corporate sabotage?

**Comment by daviscabral** [comment]
To avoid duplicating my comment: https://github.com/aksonov/react-native-router-flux/issues/960#issuecomment-424953838. 😝
