### ISSUE TITLE
Actions.currentRouter.currentRoute is not updated

### ISSUE THREAD

**Issue by mmazzarolo** [aksonov/react-native-router-flux#183]
Hi,
I'm having a strange issue, whenever I try to get the current route name from `Actions.currentRouter.currentRoute` I get the previous outdated route.
The strange thing is that if I check `currentRoute` of `Actions.currentRouter` in the developer console I can see the correct route.

```javascript
function onEnterHandler() {
  console.log(Actions.currentRouter)
  console.log(Actions.currentRouter.currentRoute)
  return true
}

export default class Routes extends React.Component {
  render() {
    return (
      <Router sceneStyle={{ paddingTop: topPadding }}
        onPop={onEnterHandler}
        onReplace={onEnterHandler}
        onPush={onEnterHandler}
      >
        <Route
          name='session'
          component={SessionScreen}
          type="replace"
          initial={true}
        />
        <Route
          name='place'
          component={PlaceScreen}
          type="replace"
          title='Ristoranti'
        />
      </Router>
    )
  }
}
```

The result from the logging when I navigate to the `place` route from the `session` route is the following:
<img src="http://i.imgur.com/GAf8ut1.png" />

As you can see the log of `Actions.currentRouter` shows the correct `currentRoute`, while `Actions.currentRouter.currentRoute` show the outdated one.

I even tried checking the currentRoute from different places (e.g.: componentDidMount) and components with different Actions (pop/replace) but the issue persist.

Thank you in advance,
Matteo.

**Comment by lynndylanhurley** [comment]
I'm having the same problem.

**Comment by micksabox** [comment]
I've noticed this during an `onPop` event too. Maybe that's what is happening here - at the time of the `console.log` call, the route state hasn't been updated. But when you check the dev console it appears correctly.

**Comment by mmazzarolo** [comment]
I've found a workaround: you can use the `navigationContext` of the React-Native Navigator to get the current route from the component itself.
```javascript
componentWillMount() {
  const navigationContext = this.props.route.parent.delegate.refs.nav.navigationContext
  console.log(navigationContext)
  navigationContext.addListener('didfocus', event => {
    console.log(navigationContext.currentRoute.name) // This is the current focused route
  })
}
```
You can find info about the listenere [here](https://facebook.github.io/react-native/docs/navigator.html#configurescene).
The listener is called on every route change, which means that if you need to know if the component is the focused one you can do something like this in the listener callback (and you can update the state in redux/flux here too):
```javascript
const isComponentFocused = navigationContext.currentRoute.name === 'componentName'
```

It worked fine for me so far, but it doesn't seem to be an optimal solution  in my opinion because you need to dig deep to find the navigationContext and also for the same reasons stated by @lynndylanhurley in the issue #158 

Related issues:
#158 #78

**Comment by aksonov** [comment]
Please check 2.2.0 version and its Example

**Comment by mmazzarolo** [comment]
Thank you for the new version aksonov! (And also thank you for the awesome work you're doing with this router).


The Redux support seems to be working, now I can update my store currentRoute from my own reducer:
```javascript
case Actions.AFTER_ROUTE:
case Actions.AFTER_POP:
  return state.set('currentRoute', action.name)
```

...but I'm still trying to find out the best way to handle the currentRoute information from a component.
For example:
I have a component that shows a list of items fetched from a server.
I need to trigger the server request (update the list) when the component is focused.
`componentDidMount` is not the right place, because I need to trigger the request on POP too.
What I'm doing at the moment is using the `didFocus` listener like in my previous comment:
```javascript
componentWillMount() {
  const navigationContext = this.props.route.parent.delegate.refs.nav.navigationContext
  console.log(navigationContext)
  navigationContext.addListener('didfocus', event => {
    console.log(navigationContext.currentRoute.name) // This is the current focused route
  })
}
```

Am I missing something? Does anyone know an alternative solution?   
(maybe #158 is a better place for talking about this)

**Comment by aksonov** [comment]
@mmazzarolo Hm... If you can change redux state with currentRoute, what problem to pass this state to the component? It is Redux, isn't?

**Comment by mmazzarolo** [comment]
Yes, it's Redux.
You mean something like changing the state (i.e.: setting `justFocused` to true) and catching the state change from the component in `componentDidUpdate`/`componentWillUpdate` and trigger the fetching?

I thought about it at first but it just didn't seem the optimal solution... but it's still probably better than the above solution.

**Comment by aksonov** [comment]
Maybe the component could call something like routeDidFocus (if it exists)? Maybe you could submit PR (just add that listener to ExRouter?)

**Comment by mmazzarolo** [comment]
Did it this way (using Redux):

**1. Connect the Router with Redux and before using it**
```javascript
import ReactNativeRouter, { Route } from 'react-native-router-flux'
const Router = connect()(ReactNativeRouter.Router)
```
Now when you use a `<Router>` it will be connected to the store and trigger the following actions:
- Actions.BEFORE_ROUTE
- Actions.AFTER_ROUTE
- Actions.AFTER_POP
- Actions.BEFORE_POP
- Actions.AFTER_DISMISS
- Actions.BEFORE_DISMISS

Take a look at [this](https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js) for an example.

**2. Catch the interested actions in your reducer**
I have a `global` reducer (where I keep the information needed by all my app) where I set the `currentRoute`.
```javascript
case Actions.AFTER_ROUTE:
case Actions.AFTER_POP:
  return state.set('currentRoute', action.name)
```
Now `global.currentRoute` will always have the currently focused route.

**3. Update your component on focus**
I'm doing it on `componentDidUpdate` of my `payment` component.
If `global.currentRoute` is `payment` and the previous `global.currentRoute` was different that the component has just been focused.
```javascript
  componentDidUpdate(prevProps) {
    const prevRoute = prevProps.global.currentRoute
    const currentRoute = this.props.global.currentRoute
    if (currentRoute === 'payment' && prevRoute !== currentRoute) {
      this.props.actions.doSomething()
    }
  }
```

**Comment by aksonov** [comment]
@mmazzarolo Looks very good, could you add it to README and i will close this issue

**Comment by mmazzarolo** [comment]
Of course, I'll do it this after work.

**Comment by jamesone** [comment]
Very good and easy solution to implement! @mmazzarolo Thanks for doing this, I was trying to find a "good" way of doing this exact thing for a while.

**Comment by SudoPlz** [comment]
@jamesone for some reason I can't get this to work. Did you get it working with the latest rnrf version?
