### ISSUE TITLE
No dimension set for key window

### ISSUE THREAD

**Issue by serkanerip** [aksonov/react-native-router-flux#1832]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.44.0
- android device

### Problem

After installing react-native-router-flux app crashs.The error is that "No dimension set for key window".I didnt import router but its crash app.

**Comment by kokokenada** [comment]
+1

**Comment by atmortensen** [comment]
You need to revert to 3.38.0

[https://github.com/aksonov/react-native-router-flux/issues/1816](url)

**Comment by wuhenwuya** [comment]
+1

**Comment by inter8ection** [comment]
@atmortensen  Reverting to 3.38.0 generates a new error 

`-- react-native-router-flux@3.38.0 
    -- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0`

This is because `react-native 0.44.0` depends on `react 16.0.0-alpha.6`

**Comment by inter8ection** [comment]
I followed @ThiagoLottici solution in comment from issue #1811 in which he references #1710 as a workaround. This worked for me with version 3.38.0.

**Comment by gamingumar** [comment]
i am having the same issue :(

**Comment by buptkang** [comment]
I have the same issue, it is pain.

**Comment by vnhnhm** [comment]
I've "downgraded" to `"^3.38.0"`, and it has worked:

```javascript
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-router-flux": "^3.38.0"
  },
```

**Comment by Chandhru08** [comment]
im having the same problem :
`-- react-native-router-flux@3.38.0
  +-- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0
  `-- react-native-experimental-navigation@0.26.12
    `-- react-addons-pure-render-mixin@15.5.2

"dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.0",
    "redux-thunk": "^2.2.0"
  }

**Comment by jfpalngipang** [comment]
v3.38.0 of react-native-router-flux seems to have a dependency on DatePickerIOS for some reason.

**Comment by DavideValdo** [comment]
+1

**Comment by abologna-r7** [comment]
Happens to me as well on a clean react-native project.

**Version**

Tell us which versions you are using:

1. react-native-router-flux v3.38.1
2. react-native v0.44.0
3. react 16.0.0-alpha.6

**Comment by LastxTemplar** [comment]
I am experiencing the same problem. Strangely enough the same project works on my Mac with `run-ios`, but after bringing the project to my PC and running `run-android` I started getting this issue. 
Here is my package.json:

```
"dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "3.38.0",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
```

**Comment by Chandhru08** [comment]
I got it worked by following below steps.

1.Remove the "^" symbol from dependencies in package.json.
It should be like this  "react-native-router-flux": "3.38.0"
2. Install v 3.38.0.

Even though some warning are thrown after this step, it is working for me.

**Comment by Chandhru08** [comment]
@lastxtemplar have you installed react-native-router-flux 3.38.0 after removing "^" from dependencies?

**Comment by valerybodak** [comment]
@Chandhru08
Your solution is not working for me. It is my dependencies:

**"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-localization": "^0.1.30",
    "react-native-router-flux": "3.38.0"
  },**

After remove node_modules I perform **npm install** and I see:
**-- react-native-router-flux@3.38.0 +-- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0--** 

Could you please provide your package.json.

**Comment by Anima-t3d** [comment]
I tried @Chandhru08 solution but I get this red error screen when running the app (`{"type":"InternalError", ...}`) and in the terminal:
```
Loading dependency graph, done.
error: bundling: Error: ENOENT: no such file or directory, open '/Users/xxx/Desktop/testApp/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Components/ActivityIndicator/ActivityIndicator.js'
```

**Comment by vingrad** [comment]
Please fix asap

**Comment by msqar** [comment]
Damn @Anima-t3d  im getting the exact same error!!! any solution yet?

**Comment by cesarmal** [comment]
Take a look at https://github.com/facebook/react-native/issues/13758. Particularly at the commentaries from @rkbhochalya and @mattdufeu. Check if you have other projects running (or were running on the same session - because rebooting solved for me).

**Comment by rkbhochalya** [comment]
Try clearing cache https://gist.github.com/jmoses89/c2e4786fd342b3444f3bc6beff32098d

**Comment by rkbhochalya** [comment]
If you have yarn installed this would be much faster `watchman watch-del-all && rm -rf node_modules/ && npm cache clean && yarn install && npm start -- --reset-cache`

**Comment by MasseElch** [comment]
I needed to restart my Mac and to run the commands provided by @rkbhochalya and now its working with the following package.json:

`"react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.1"`

**Comment by Chandhru08** [comment]
@valerybodak  please find my complee JSON text below,
note: after installing react native router flux again the "^" symbol replaced automatically
{
  "name": "manager",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

I have removed "^"  before installing react native router flux.
To install specific version-> npm install --save react-native-router-flux@3.38.0
(some warnings may occur... ignore those

If you run android application after installing this, it will work

**Comment by jsRuner** [comment]
the same question . it not work when i try above method.   first project is work but other is not work

**Comment by rahmanazhar** [comment]
i have done @Chandhru08 and @rkbhochalya steps. It is not working. I am working on windows. 

Instead this command
`watchman watch-del-all && rm -rf node_modules/ && npm cache clean && yarn install && npm start -- --reset-cache
`
I do 
`rd /s /q node_modules && npm cache clean && yarn install && npm start -- --reset-cache`

The error is still no dimension is set for key window. I wonder why.

My package.json as below.
```
{
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.0",
    "react-redux": "^5.0.1",
    "realm": "^0.15.4",
    "redux": "^3.6.0",
    "redux-persist": "^4.0.0-alpha7",
    "redux-thunk": "^2.1.0",
 }
```

**Comment by MasseElch** [comment]
@rahmanazhar have you tried deleting the `yarn.lock` before running yarn install? Or running `npm i`instead?

**Comment by wvicioso** [comment]
React-Native v .44 will work with flux-router .38+ but its not released yet.

Until then, use version 3.37.0 and make sure your in package.json file it looks like this 
`"react-native-router-flux": "3.37.0",`
Notice that I removed the `^` symbol from the version number. This step is very important as the symbol forces npm install to look for the newest version instead of the version indicated. Cheers!

**Comment by jpca999** [comment]
I keep getting this issue too, here's my package file. 

[{
  "name": "manager",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.0",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
](url)

**Comment by wvicioso** [comment]
change `"react-native-router-flux": "^3.38.0",` to `"react-native-router-flux": "3.37.0",`
then delete and reinstall node_modules

**Comment by jpca999** [comment]
@wvicioso 
Here's my updated package. 

{
  "name": "manager",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-router-flux": "3.37.0",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}





Now the app doesnt even open on simulator.

**Comment by wvicioso** [comment]
@jpca999  Make sure you close the all processes including the packager and delete and reinstall your node-modules. You can do that by running this command `rm -rf node_modules && npm install` then do `react-native run-ios` or `react-native run-android` depending on which you're building for.

**Comment by jpca999** [comment]
"Make sure you close the all processes including the packager"
Packager means all terminal processes - right ?
I quit the whole terminal.

**Comment by wvicioso** [comment]
Yes. Also very important you delete your node modules folder before you run
npm install. Share the error your get if the problem persists and let me
know if you're getting the problem on iOS or Android

**Comment by jpca999** [comment]
hmm i do delete the whole node modules folder, & then npm i 
I'm running on ios. 
Thanks: ) 

Here's the error: 


![image](https://cloud.githubusercontent.com/assets/1026325/25869569/caa8948e-34ce-11e7-9f05-58df819deaf1.png)

**Comment by jpca999** [comment]
It's a package issue not my code issue

**Comment by jpca999** [comment]
Give me a pcakcage file that works for other people...

**Comment by jpca999** [comment]
@wvicioso

**Comment by jpca999** [comment]
resolved here https://github.com/aksonov/react-native-router-flux/issues/1816
"react": "16.0.0-alpha.6",
    "react-addons-pure-render-mixin": "15.5.2",
    "react-native": "0.43.3",
    "react-native-router-flux": "3.38.0",
    "react-static-container": "^1.0.1",

**Comment by wvicioso** [comment]
so you downgraded the react-native version. that's intersting. My projects use react-native .41 and flux-router 3.37

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by jpca999** [comment]
Resolved, just try changing the versions

**Comment by diegorodriguesvieira** [comment]
@jpca999 now I'm using react-native 0.44 and still happens

**Comment by gabrielgomesferraz** [comment]
+1

**Comment by julesmoretti** [comment]
@aksonov - Is this repo no longer maintained? I am having the same issues and have tried some suggestions from this feed with no success.

**Comment by diegorodriguesvieira** [comment]
It seems to me that this project is not being maintained, I am now using react-navigation...

**Comment by jpca999** [comment]
How's it working out ?

**Comment by aksonov** [comment]
Latest versions of RN are not supported yet. I will take a look it but have limited available time. PR is welcome 

> 12 мая 2017 г., в 16:30, jayp <notifications@github.com> написал(а):
> 
> How's it working out ? 
> 
> 
> 
>

**Comment by julesmoretti** [comment]
Same here for react-navigation https://reactnavigation.org/

**Comment by jsRuner** [comment]
it  work after i restart pc;

**Comment by tibbus** [comment]
I had this issue on a clean react-native project, I don't even use flux.

It happened when I switch to another react-native project and back. I fixed by killing emulator, terminal, Xcode, remove node_modules and it worked.

**Comment by efkan** [comment]
I am affected from this issue too although I still use` "react-native-router-flux": "^2.3.9"`.

**Comment by iegik** [comment]
Have You tried kill all background-running "react-native packager" processes and `npm start --reset-cache` again?

**Comment by Ethan0007** [comment]
The same issue.

![image](https://user-images.githubusercontent.com/12542052/26960390-53c90116-4d09-11e7-8535-a90f0ddf3775.png)

I'm configuring now our IOS Platform, unfortunately I'm encountering with this issue.

**Comment by airman00** [comment]
@Ethan0007 : any luck fixing it? I'm stuck on the same issue , tried everything suggested

**Comment by Ethan0007** [comment]
@airman00  yes sir, if you're configuring IOS please set your Dimensions.get('window'); instead of Dimensions.get('screen');

**Comment by airman00** [comment]
Himm I tried replacing all Dimensions.get('window') with Dimensions.get('screen'), now I just get this error
`No dimension set for key screen', reason: 'Unhandled JS Exception: No dimension set for key screen
`
I also tried making sure that all Dimensions.get('screen') were Dimensions.get('window') and that just gets you
`No dimension set for key screen', reason: 'Unhandled JS Exception: No dimension set for key screen
`

Any ideas what to try next?

**Comment by Ethan0007** [comment]
make sure that you replace them all. then try to npm start --reset-cache

**Comment by airman00** [comment]
Sorry, to be clear - you replaced all  Dimensions.get('window') with Dimensions.get('screen')  for your solution?

Or you replaced all  Dimensions.get('screen') with Dimensions.get('window')  for your solution?

**Comment by Ethan0007** [comment]
replace Dimensions.get('screen') with Dimensions.get('window') if you are configuring IOS.
