### ISSUE TITLE
How can I position an overlay layer on top of the navbar?

### ISSUE THREAD

**Issue by loregr** [aksonov/react-native-router-flux#1833]
Hello everyone,
I'm trying to use https://github.com/jacklam718/react-native-popup-dialog and https://github.com/maxs15/react-native-modalbox in a project with react-native-router-flux. In both cases I get the navbar on top of the overlay layer.

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.43.4

### Expected behaviour
The navbar should be below the overlay layer

### Actual behaviour
The navbar is on top of the overlay layer

![screenshot_392](https://cloud.githubusercontent.com/assets/7204248/25641322/bfe2404e-2f93-11e7-92a5-7f6509000aac.png)

### Code
(main part)

```
onNewArticlePress() {
        this.refs.modal4.open()
    }

    render () {

        return (
            <View>
            <View style={{marginTop:StyleUtil.navBarHeight}}>
                <ListView
                    enableEmptySections
                    dataSource={this.dataSource}
                    renderRow={this.renderRow}
                    renderHeader={this.renderHeader.bind(this)}
                    showsVerticalScrollIndicator = {false}
                />

            </View>

                <Modal style={[styles.modal, styles.modal4]} position={"bottom"} ref={"modal4"}>
                    <Text style={styles.text}>Modal on bottom with backdrop</Text>
                </Modal>
            </View>
        )
    }


const styles = {
    modal: {
        justifyContent: 'center',
        alignItems: 'center'
    },

    modal4: {
        height: 300
    }
}
```

Any suggestion on how to fix it?

Thanks

**Comment by Amurmurmur** [comment]
Simple enough
Try this:
```
const styles = {
    modal: {
        justifyContent: 'center',
        alignItems: 'center'
    },

    modal4: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
       height: 300
    }
}
```

You need to make the modal absolute, so it will be on top of the navbar and other elements 👍 
Hope this helps!
