### ISSUE TITLE
How can I use refs to active scene component from Outer Component 

### ISSUE THREAD

**Issue by KunwarSingh** [aksonov/react-native-router-flux#1834]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42

For 2 simple components, parent, child both using Redux I'm able to use refs, to invoke a child method. But how can I achieve same using above library 'react-native-router-flux', where can I set ref to Scenes.

ParentComponent

    var Parent = new React.createClass({

        render : function() {
            return (<Child ref={(child) => {this.child = child}})
        }

        // able to trigger child.somefunction via this.child.getWrappedInstance().somefunction()
    })

    module.exports = connect(select)(Parent)

Child Component

    var Child = new React.createClass({
        somefunction: function(){
            //working
        }
    })

    module.exports = connect(select, null, null, {withRef: true})(Child)

render function of Child component after using above library

    render: function() {
       return (
         <Router>
           <Scene>
             <Scene key="WelcomeModal" component={WelcomeModal} title="welcomeTitle" initial={true} 
                navigationBarStyle={styles.welcomeModal_navigationBarStyle}
                titleStyle={styles.welcomeModal_titleStyle}
                rightTitle='INFO'
                rightButtonStyle={styles.baseModal_rightButtonStyle}
                rightButtonTextStyle={styles.baseModal_rightButtonTextStyle}
                rightButtonIconStyle={styles.baseModal_rightButtonIconStyle}
                ref={(_WelcomeModal) => {this._WelcomeModal = _WelcomeModal}} //need some way to add ref here
             />
           </Scene>
         </Router>
       )
    }

**Comment by mackenziemance** [comment]
Did you find a way to accomplish this ?

**Comment by jan4984** [comment]
make a global place to keep the component instance. do set in mount and unset in unmount.
