### ISSUE TITLE
Help: Cannot resolve symbol Actions

### ISSUE THREAD

**Issue by iegik** [aksonov/react-native-router-flux#1835]
In PHPStorm there is Code Inspection tools for JavaScript. When I try to import Action like this:
```
import { Actions } from 'react-native-router-flux';
```
It Tells me "Cannot resolve symbol `Actions`". How to prevent these notifications?

**Comment by hellomaya** [comment]
I have used WebStorm 2016.3.3 version, and a lot component it can't resolve, even some of them I have build with same code but different name, it could be IDE bug, which I have googled, and know probably it is.

**Comment by iegik** [comment]
The only solution is to disable this check in Preferences...
