### ISSUE TITLE
Actions.currentRouter.currentRoute throwing 'undefined is not an object'

### ISSUE THREAD

**Issue by desktp** [aksonov/react-native-router-flux#1836]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^3.37.0
- react-native 0.43.3

### Expected behaviour

`Actions.currentRouter.currentRoute` returning the current active `Scene`

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/7454286/25658927/ac2614ca-2fdb-11e7-8feb-58f917f7ad30.png)

### Steps to reproduce

I'm trying to use in conjunction with `react-native-popup-menu` to open a user list of each `Chat` scene, but I'm getting the above error.

`Chat` scene is defined as
```
<Scene 
  key="chat" 
  component={Chat} 
  leftButtonIconStyle={{ tintColor: '#825c12' }}
  animationStyle={animationStyle}
  titleStyle={styles.navbarTitleStyle}
  sceneStyle={{ paddingTop: (Platform.OS === 'ios') ? 65 : 54 }}
  renderRightButton={MoreMenu}
/>
```

`MoreMenu`:
```
import React from 'react';
import { Menu, MenuTrigger, MenuOptions, MenuOption } from 'react-native-popup-menu';
import { Icon } from 'native-base';
import { Actions } from 'react-native-router-flux';
 
const MoreMenu = () => (
  <Menu>
    <MenuTrigger>
      <Icon ios='ios-more' android='md-more' style={{ color: '#825c12', marginTop: -3 }} />
    </MenuTrigger>
    <MenuOptions>
      <MenuOption onSelect={() => console.log(Actions.currentRouter.currentRoute)} text='Group Users' />
    </MenuOptions>
  </Menu>
);

export default MoreMenu;
```
Thanks in advance for the help.

**Comment by Dictory** [comment]
Yeah, that dosnt work

**Comment by MaximusBaton** [comment]
you should use redux and [this example](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md)
