### ISSUE TITLE
conflict react-native version with your router-flux dependencies's react-native version 0.41.2

### ISSUE THREAD

**Issue by SunflowerGJ** [aksonov/react-native-router-flux#1839]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.1
- react-native v0.42.3
![Uploading issue.png…]()

### Actual behaviour
The react-native version0.43.2 is conflict with the latest react-native version0.41 in your router-flux dependencies ,this will cause some duplicate file about react-native.

### Steps to reproduce

Edit router-flux dependencies

**Comment by jasan-s** [comment]
Yup For now now downgrade to v3.38.0

**Comment by SunflowerGJ** [comment]
@jasan-s Yes, I did it !

**Comment by svallen** [comment]
Is there an ETA on an updated so that we don't have to downgrade?

**Comment by D1no** [comment]
I ran into the same problem today!! needed to force fix to v3.38.0. Please fix
