### ISSUE TITLE
Router should pass its own props to Route's on subsequent renders?

### ISSUE THREAD

**Issue by danielweinmann** [aksonov/react-native-router-flux#184]
I have the following scenario:

1. I have a Router with its routes inside a presentational component, which I want to be totally unaware of state.
2. In a few routes of this router, I need to receive new redux state from my container.
3. The container re-renders the Router with my new state as props.
4. But since Router is not a React Component, it does not re-render the routes and does not pass the new props to the component.

Here is a Gist with a simple example (in the example I try passing props both to Router and Route): https://gist.github.com/danielweinmann/09a2c980fe2fa405eb39

What I suggest is the following:

* Add a passProps prop to Router
* Change the following block on ExRouter to pass these props manually to the route: https://github.com/aksonov/react-native-router-flux/blob/master/ExRouter.js#L293

I'm gonna send a PR with this soon, probably tonight, but wanted to document the issue first ;)

**Comment by danielweinmann** [comment]
Actually, I've now noticed that Router already passes its own props to Route on the first render. I think I wont create passProps prop and just use the router's prop.

What do you think, @aksonov?

**Comment by danielweinmann** [comment]
@aksonov, I don't think you understand the problem I fixed. I am actually astonished that nobody else has run into it! I'm thinking everybody is implementing the default Router-as-first-component-in-the-render-stack approach.

This change broke it: https://github.com/aksonov/react-native-router-flux/commit/2724b8163a1798775046926c70ade4e4fcfe8066#diff-07ab94a626d050c4a73fb7272713b477R294

The problem was that the _original Route_ component had static props that didn't change on subsequent renders. So I had to do this ugly `router.routes[route].props =` there.

I know it's ugly, and I know it would be better to use react's component lifecycle. But it just didn't work. I'm thinking the problem is on the way we "store" the routes on a non-react class and then try to pass them around. I think we'll have to made an architectural change to make it more elegant.

But for now I'm going to send a new PR fixing it with the ugly `router.routes[route].props =`, ok?

**Comment by shakdoesgithub** [comment]
@danielweinmann are you still having this issue?
I have a redux provider wrapping the router, and it's not passing the store props down to the route with the 3.2.7 react-native-router-flux version.

**Comment by danielweinmann** [comment]
@shakdoesgithub unfortunately I had to focus on launching my project (which will happen later this month), so I couldn't keep up with the changes here.

I'm using a fork right now, with 1 commit that I didn't try to merge with @aksonov's version. Here is my version: https://github.com/danielweinmann/react-native-router-flux/tree/d88aa3b84ee908aca3aa3a5ef6edad4180ee820b

I don't recommend using my fork, though. @aksonov is probably better, mine is 2 months old, but maybe you can take a look at my commits and see if you can create a PR here for fixing this issue if it is still present.

**Comment by shakdoesgithub** [comment]
@danielweinmann I got it to work by using the latest version and using the compiled version of your scenes. 

```
const scenes = Actions.create(
  <Scene key="root">
    <Scene key="login" {...this.props} component={Login} title="Login" />
  </Scene>
);

class RouterContainer extends Component {
  render() {
    console.log('RouterContainer render', this.props)
    return(
      <Router {...this.props} scenes={scenes}>
      </Router>
    )
  }
}

class ConnectedRouter extends Component {
  render() {
    return (
      <RouterContainer {...this.props} />
    )
  }
}

ConnectedRouter = connect(state => ({
  todo: state,
}))(ConnectedRouter)
```
