### ISSUE TITLE
Question: How can I swipe forward and backward

### ISSUE THREAD

**Issue by dittmarconsulting** [aksonov/react-native-router-flux#1840]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.3

### Question

How can I swipe forward and backward? I can't find the documentation for this feature.

Thanks in advance

**Comment by inferusvv** [comment]
Scenes can be swipe backward by default. [Gestures API](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#gestures)
Forward seems to be impossible out of the box

**Comment by dittmarconsulting** [comment]
Yeah, I figured that out.

I used the `react-native-swipe-gestures` and wrapped the router. That works really well.

    <GestureRecognizer
       onSwipeLeft={(state) => ::this.onSwipeLeft(state)}
       onSwipeRight={(state) => ::this.onSwipeRight(state)}
       config={config}>
          <Router createReducer={reducerCreate} animationStyle={animationStyle}>
              <Scene key="root">
              </Scene>
          </Router>
    </GestureRecognizer>

**Comment by MrChe** [comment]
@dittmarconsulting  you have full preview example? This solution its very good for me but i need see full example if its possible! Thank you)
