### ISSUE TITLE
Using it with React-native-Tab-View (question) 

### ISSUE THREAD

**Issue by jasan-s** [aksonov/react-native-router-flux#1841]
- react-native-router-flux v3.38.0
- react-native v0.43.3

How can I use THis lib along with the [React native Tab View](https://github.com/react-native-community/react-native-tab-view). Right now I just wrapped the entire tab view component within a single scene but I can't figure out how to pass the active tab view to the redux store.  So I can keep track of which tab the user is on etc. 
My current usage:

```
 <Router>
    <Scene key='root'>
      <Scene hideNavBar  key='home' component={ReactNativeTabViewContainer}
       tabs ={true} initial={true} />
    </Scene>
  </Router>
```

**Comment by i8wu** [comment]
Why don't you using the tabs that are built into this module? Example/docs explain usage

**Comment by zalesky** [comment]
@i8wu It's not the same
