### ISSUE TITLE
Is it possible to create dynamic tabbar icon,title which listens redux state?

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#1844]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^3.38.0
- react-native v0.42.3

I want to show shopping cart icon with number inside on tabbar. That number would listen redux state. How would I do this?

**Comment by hellomaya** [comment]
My idea, try make a tab icon and observe the state, when the state change, change the tab icon somehow, by using mobx, is pretty easy, by using redux, actually pretty much same thing, just different way. All of them will call render for tab icon.
