### ISSUE TITLE
Drawerlayout android, openDrawer

### ISSUE THREAD

**Issue by mynameisbams** [aksonov/react-native-router-flux#1845]
im try use DrawerLayout android, and i try open menu drawer using button, but always give me error 'undefined is not a function (evaluating '_this2.openDrawer()')' what should i do? please help me :(, its make me dizzy

App.js

    import React, { Component,PropTypes } from 'react';
    import {
    AppRegistry, Button,
    StyleSheet,
    Text,
    View  } from 'react-native';

    import { Router, Scene, Actions } from 'react-native-router-flux';
    import Home from './Scene/Home';
    import Login from './Scene/Login';
    import Register from './Scene/Register';
    import DrawerLayout from './Component/DrawerLayout';

    export default class Flux extends Component {
    // componentDidMount() {
    //     Actions.refresh({rightTitle: 'Refresh', onRight: this.openDrawer})
    // }
    // static propTypes = {
    //     openDrawer: PropTypes.func.isRequired
    // };
    constructor() {
        super();
        this.openDrawer = this.openDrawer.bind(this);
    }
    openDrawer() {
        this.ref['DRAWER'].openDrawer();
    }
    render() {
        let {sidebarRef} = this.props
        var createRightButton = function() {
            return (
                <View>
                    <Button onPress={()=>{this.openDrawer()}} title={"open"}>
                        Register
                    </Button>

                </View>
            )};
        return (
            <Router renderLeftButton={createRightButton}>
                <Scene key="root">
                <Scene key="drawer" component={DrawerLayout}>
                    <Scene key="Main" tabs={true}>
                        <Scene key="home" component={Home} title="Home" initial={true}/>
                        <Scene key="login" component={Login} title="Login" />
                        <Scene key="register" component={Register} title="Register" />
                    </Scene>
                </Scene>
                </Scene>
            </Router>
        );
    }
    // reload = () => {
    //     this.refs['DRAWER'].openDrawer();
    // };
    // _setDrawer() {
    //     this.refs['DRAWER'].openDrawer();
    // }

    }

    AppRegistry.registerComponent('Flux', () => Flux);

DrawerLayout.js

    import React, { Component } from 'react';
    import Drawer from 'react-native-drawer';
    import SideMenu from './SideMenu';
    import {Actions, DefaultRenderer} from 'react-native-router-flux';
    import {Button, DrawerLayoutAndroid, TouchableOpacity, View} from "react-native";

    export default class NavigationDrawer extends Component {
     componentWillMount() {
        Actions.refresh({rightTitle: 'Refresh', onRight: this.openDrawer})
         //console.log("aaaa");
     }
    constructor() {
        super();
        this.openDrawer     = this.openDrawer.bind(this);
        this.closeDrawer    = this.closeDrawer.bind(this);
    }
    openDrawer(){
        this.refs['navigation'].openDrawer()
    }
    closeDrawer(){
        this.refs['navigation'].closeDrawer()
    }

    render(){
        const state = this.props.navigationState;
        const children = state.children;

        //Actions.refresh({rightTitle: 'Refresh', onRight: this.openDrawer})
        var navigationView = (<View>
            <Button onPress={()=>{this.closeDrawer();Actions.home()}} title={"Home"}>
                Home
            </Button>
            <Button onPress={()=>{this.closeDrawer();Actions.login()}} title={"Login"}>
                Login
            </Button>
            <Button onPress={()=>{this.closeDrawer();Actions.register()}} title={"Register"}>
                Register
            </Button>
        </View>);
        return (
            <DrawerLayoutAndroid
                drawerWidth={300}
                ref='navigation'
                drawerPosition={DrawerLayoutAndroid.positions.Left}
                renderNavigationView={() => navigationView}>
                <DefaultRenderer leftTitle="menu" leftButton={this.openDrawer} navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </DrawerLayoutAndroid>

        );

    }
    openDrawer(){
        this.refs['navigation'].openDrawer()
    }

}

**Comment by rajasrinivasan-raja** [comment]
can you find the solution
