### ISSUE TITLE
Bundling error

### ISSUE THREAD

**Issue by Carel155** [aksonov/react-native-router-flux#1847]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.44.0

### Expected behaviour

App compiling correctly.

### Actual behaviour

Bundling error happens. 

error: bundling: Error: ENOENT: no such file or directory, open 'F:\Failid\app\node_modules\react-native-router-flux\node_modules\react-native\Libraries\Components\ActivityIndicator\ActivityIndicator.js'

### Steps to reproduce

1. react-native init
2. Install packages
3. react-native run-android

**Comment by beiming** [comment]
I have the same issue. and now downgrade version.

**Comment by kishorekanala-innoplexus** [comment]
I also have the same issue. I tried downgrading the version but still getting the same error.

**Comment by beiming** [comment]
I consider replace react-native-router-flux with react-native-navigation

**Comment by hama** [comment]
me too

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by AviramCohen** [comment]
I also have this. And that's after downgrading from 3.38.1 to 3.38.0 cause of other error

**Comment by marcoj** [comment]
+1

**Comment by adnkh** [comment]
+1

**Comment by diegorodriguesvieira** [comment]
@aksonov Do you have idea how to fix this error?

**Comment by ddereszewski** [comment]
+1

**Comment by corymayer** [comment]
Same error with ActivityIndicator on v0.39.1 (react-native 0.44.0 and react 16.0.0-alpha.6)

**Comment by FMGordillo** [comment]
+1

**Comment by aksonov** [comment]
Does demo work for you?

**Comment by Adamnator92** [comment]
@ddereszewski life saver

**Comment by Liqiankun** [comment]
@ddereszewski  You saved my ass!

**Comment by renancompuece** [comment]
@ddereszewski Thanks !
