### ISSUE TITLE
Android back soft button on navigation bar removes tab

### ISSUE THREAD

**Issue by stephenjen** [aksonov/react-native-router-flux#1848]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.3

### Expected behaviour
On Android emulator, for apps using the tab bar, clicking the back soft button takes user back to previous tab while maintaining all available tabs

### Actual behaviour
User is taken back to previous tab, but the last tab is removed

### Steps to reproduce

1.  Launch app
2.  Click on a tab that is not the first tab
3.  Click the back soft button

![d5omre39zq1ds](https://cloud.githubusercontent.com/assets/8771850/25787106/294c791e-33d1-11e7-9793-646ac3c98703.gif)

**Comment by beastwinside** [comment]
my version of react-native is 0.44,has the same problem as yours.
the rn version has conflict with the rnrf version,I suggest u rollback the rn version to 0.42

**Comment by uncledent** [comment]
I have the same problem on android, rn 0.42, react-native-router-flux 3.38.0.
Any news on this case?

**Comment by stephenjen** [comment]
Our design call for immersive mode without the soft buttons and navigation bar, so, luckily we don't have to deal with this problem.

**Comment by beastwinside** [comment]
a fool way to hack it,
example：
<Router>
  <Scene key='scene1'/>
  <Scene key='scene2'/>
  <Scene key='scene3'/>

  <Scene key='noback' component={NOBACK} title='加载中' hideTabBar  />***can solve this，and I don't know why?)*****
</Router>
,more in this js
https://github.com/beastwinside/DUHAPP/blob/master/meituan/src/RootScene.js
