### ISSUE TITLE
Switch shows first item for a while

### ISSUE THREAD

**Issue by inferusvv** [aksonov/react-native-router-flux#1857]
### Version

- react-native-router-flux v3.38.0
- react-native v0.44

### Code

```
const scenes = Actions.create(
  <Scene
    key="root"
    tabs
    unmountScenes
    // component={connect(state => ({ user: state.user }))(Switch)}
    component={Switch}
    selector={props => {
      // console.log('props.user.authorized', props.user.authorized);
      return 'app';
      // return (props.user.authorized ? 'app' : 'signin');
    }}
  >
    <Scene key="signin" component={SignIn} title={'Sign In'} hideNavBar initial />
    <Scene key="app" component={Drawer}>
      <Scene key="navbar" navBar={NavBar}>
        <Scene key="home" component={Home} title={APP_NAME} main panHandlers={null} />
      </Scene>
    </Scene>
  </Scene>,
);
```
### Problem 
I am using Switch to make authorization. In some reasons it shows first scene for less than a second and then second. As you can see I commented some of my code and always return `app` scene. But it is not helping, so my redux state is ok.

As a workaround currently I wrote `return null` in `SignIn` when user authorized. But it is not ok, because user see blank white page instead.

**Comment by ujwal-setlur** [comment]
Try removing initial from signin. Not sure if that will help.

**Comment by gijoehosaphat** [comment]
We see this as well, to get things working, we created an empty Component listed as the first Scene. This one gets loaded temporarily before the selector kicks in and routes you to the correct Scene. It's definitely a bug. Unfortunately Switch seems unstable at the moment.

**Comment by ujwal-setlur** [comment]
Is there an alternative to using switch? I also see some cases when switch does not correctly detect that it needs to switch between scene sets.

I do agree switch is a bit buggy. Is there a way the same can be achieved without Switch component?
