### ISSUE TITLE
Experimental Navigator API

### ISSUE THREAD

**Issue by MITDelian** [aksonov/react-native-router-flux#186]
@ericvicenti has implemented a new experimental API for Navigation that offers a much more redux-like implementation. I think it's worth looking into building on top of his API, it matches the philosophy of what this library has done in comparison to ExNavigator/Navigator/NavigatorIOS

I'm going to be spending today looking into integrating the two.

https://github.com/facebook/react-native/commit/a3085464f6ea36fc6b53cd0c711c048ffb1516f9

https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/Navigation.md

https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/Reducer_Actions.md

**Comment by ericvicenti** [comment]
Excellent! Let me know how I can help, or if you have any feedback. 

Those docs are slightly out of date. I'll update them this afternoon :smile:

**Comment by MITDelian** [comment]
haha no way wasn't expecting an answer so quickly from you. I'm just going through your examples first and making sure I fully understand them.

Was going to email you and ask if you thought this was a good idea but I'll take the comment as implicit approval

**Comment by ericvicenti** [comment]
I'm happy to see that you're experimenting with it. Bu my hope is that we won't need to rely on many libraries, so people can easily do navigation out of the box with react-native. If you're missing anything important from the built-in Navigation library, please consider sending a PR to react-native so everybody can benefit!

If you want to create custom reducers or navigation views, those would be great to publish independently!

**Comment by graywolf336** [comment]
@ericvicenti Where can we find the documentation for the Experimental Navigator API? I'm starting to work on a project and am looking into my options for navigation, started to use this repository but then saw this issue and your comments so was just curious. Thanks!

**Comment by ericvicenti** [comment]
You will probably learn the most by looking through the examples: https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/NavigationExperimental

Right now the docs are quite sparse, but I'm working on them here: https://github.com/ericvicenti/navigation-rfc/tree/master/Docs

If you want to contribute to the docs, that would be very welcome!

**Comment by graywolf336** [comment]
Okay thanks, I will take a look and try them out.

I won't promise anything, but I will make an effort to if I grasp the understanding of it!

**Comment by aksonov** [comment]
@ericvicenti You new experimental API looks very good, but let me explain why i still want to use my component and probably many other people does.

#1 I want to have all my routes in one place. Like Storyboard in iOS, but more convenient (because of JSX)! I believe navigation logic should be separated from other code.
#2 I want to have very simple transitions. Like 'performSegueWithIdentifier' in iOS.

Sorry, maybe it is already done in your API but I've missed it....

**Comment by MITDelian** [comment]
I have to agree w/ @aksonov.

I've actually been spending some time this last week trying to integrate the best of both APIs. Simple transitions, routes defined in a single place, with a more direct connection to redux similar to react-router-redux.

My goal is to publish it by the end of this weekend and I'd love to get the community's feedback on it. I basically started from @aksonov's library and worked towards an interface similar to the react-router-redux ideology.

**Comment by aksonov** [comment]
@MITDelian it would be great if you could make it as 'plugin' for this component, like ExRouter.

**Comment by MITDelian** [comment]
The only real issue with that @aksonov is that I think the stack of the Router class needs to be stored in redux rather than in the state. I'll send you an early version this weekend so you can take a look over it and let me know what you think

**Comment by MITDelian** [comment]
So there are some slight tweaks I have to make in Actions.js and Router.js in order for it to be more properly "redux" and have all the data stored in the store rather than on a particular component or class state

**Comment by aksonov** [comment]
We could really make Router (now it is BaseRouter) immutable and its Route, so it could be stored in state...

**Comment by danielweinmann** [comment]
+1!

**Comment by MITDelian** [comment]
Yes! That is what I'm working on @aksonov

**Comment by MITDelian** [comment]
I have all of the adjustments made to the rest of the codebase as if BaseRouter was immutable, and now I need to actually move the stack to the store and make it so the logic for pop, jump etc are in the reducers rather than in the class

**Comment by aksonov** [comment]
Hm, why? Just modify pop/jump within BaseRouter so it will return new BaseRouter instance. This way all logic still will be within BaseRouter.

**Comment by aksonov** [comment]
This way also it the component still could be backward compatible with ExRouter (sure, some modification of ExRouter will be necessary)

**Comment by MITDelian** [comment]
Ahhh smart idea. Hehe this is what I wanted to discuss on gitter the other day

**Comment by grin** [comment]
Storing router's transitions stack as redux state is the only feature I'm missing from this great library

:+1:

**Comment by aksonov** [comment]
@grin Any problems to make BaseRouter/Route immutable and store it within your state?

**Comment by grin** [comment]
@aksonov No problem at all. That was just meant as encouragement to @MITDelian and his idea that he mentioned he is working on. From a library user perspective this sort of functionality would be really nice to have out-of-the-box and I believe it would make this lib even more attractive.

**Comment by aksonov** [comment]
The problem I don't want this component to depend from redux or any other flux library - many users don't want it at all. Many react native components has own inner state (for example TextInput) and you don't add all their state to redux (for example, in most cases you need to add completed text, but not 'in-progress' text). So you may consider navigation component state as TextInput state or any other...

**Comment by MITDelian** [comment]
I mean I understand that TextInput has its own internal state however the navigation state of an application is far more important and I think exposing that to the user and letting them store it in redux is quite important.

It also allows you to start from scratch, load in the store, and then be popped deep into a navigation hierarchy rather than starting from the main page each time you reload

**Comment by danielweinmann** [comment]
Why not make BaseRouter immutable/stateless and implement state management in an optional decorator?

**Comment by aksonov** [comment]
@MITDelian  any ETA for your changes? 
@danielweinmann It looks very good idea, looks like @MITDelian  works on it. I think it even could be not connected with Experimental Navigator API at all. Anyway, PR is welcome.

**Comment by MITDelian** [comment]
@aksonov I got a preliminary version working for my fork that I use internally, but it's not really quite ready to be integrated into this library.

Apologies but this (https://github.com/facebook/react-native/issues/5404#issuecomment-188571340) is my priority right now, but I'll dedicate some time to this once it is resolvde

**Comment by aksonov** [comment]
Ok, looks like now this integration is priority No.1 for this component because 
"Facebook is dropping support for Navigator and will focus on NavigationExperimental from now on" according to  https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md

**Comment by aksonov** [comment]
Also seems we can't make it fully backward compatible (because of reducers & state), i'm going to work on this for next 3.0 release

**Comment by philipshurpik** [comment]
Ok, if you need some help - please mention me in issue :)
Also it would be great if you create new issue for 3.0 release with planned subtasks

**Comment by aksonov** [comment]
@philipshurpik Looks like 0.21 or even 0.22-rc doesn't contain latest experimental Navigator API changes... Maybe it is too early to work on it because of unstable API - for example latest Navigator example  cannot be run with 0.21.0

**Comment by aksonov** [comment]
@philipshurpik , all Okey, i've submitted very early alpha, branch 3.0.0alpha, check Example project there. API & syntax is changed. Nested containers (Login, TabBar within Example) don't work yet (you may fix it if you can), but go to Register/Register2/Home works with good animation, thanks @ericvicenti for great library, it is really amazing!

**Comment by aksonov** [comment]
3.0 version is released, too pity that nobody was able to help, i thought open source community could be more active...
