### ISSUE TITLE
undefined is not an object _reactNative.NavigationExperimental.CardStack (NavigationExperimental deprecated)

### ISSUE THREAD

**Issue by Anima-t3d** [aksonov/react-native-router-flux#1860]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.8.1
- react-native v0.44.0

### Expected behaviour
The router to just work

### Actual behaviour
Red error screen: Undefined is not an object _reactNative.NavigationExperimental.CardStack

> The CardStack and other NavigationExperimental views live on as a part of the React Navigation project. The new library aims to be easy to use, while continuing to enable the smooth and customizable animations that NavigationExperimental pioneered.
> 
> As of React Native 0.43, NavigationExperimental is deprecated. 

It seems like it is removed completely in 0.44: https://github.com/facebook/react-native/commit/febf3d00ed228391ee4dd6541b0d2746dc56d21f

**Comment by hellomaya** [comment]
Try 3.38.0, I have tried 3.37 and 3.38.1, both not working with latest react native.

**Comment by aksonov** [comment]
Please use 3.39.1 or greater with RN0.44
