### ISSUE TITLE
Android assemble cannot package

### ISSUE THREAD

**Issue by hekairui** [aksonov/react-native-router-flux#1861]
### Version

- react-native-router-flux v3.38.1
- react-native v0.44.0

### Expected behaviour

Assembled a release: gradlew assembleRelease
Expected it to build .apk

### Actual behaviour

Build failed:

bundle: Copying 12 asset files
bundle: Done copying assets
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources
/Users/kyle/gz/fermion/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnative_libraries_customcomponents_navigationexperimental_assets_backicon.png: error: Invalid filename.  Unable to add.

:app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

### Steps to reproduce

run  ./gradlew assembleRelease

**Comment by iNeedCode** [comment]
Same here

### verision


```
    "react-native": "0.44.0",
    "react-native-router-flux": "^3.38.1",
    "react-native-simple-store": "^1.2.0",
    "react-native-vector-icons": "^4.1.1",
```
### shell output
```
This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: /Users/imalik/code/IdeaProjects/jamaat/AMJNamazzeiten/Gebetszeiten/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Copying 12 asset files
bundle: Done writing bundle output
bundle: Done copying assets
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources
/Users/imalik/code/IdeaProjects/jamaat/AMJNamazzeiten/Gebetszeiten/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnative_libraries_customcomponents_navigationexperimental_assets_backicon.png: error: Invalid filename.  Unable to add.

:app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by aksonov** [comment]
Please check 3.39.1. Sorry, I can't verify android, but iOS Example project works fine.

**Comment by gigeos** [comment]
Try with 3.38.0 and same for me

```
 "react": "16.0.0-alpha.6",
 "react-native": "0.44.0",
 "react-native-code-push": "^2.0.3-beta",
 "react-native-router-flux": "^3.38.0",
```

**Comment by iNeedCode** [comment]
Does this have to do something with maximum byte number?
see: https://github.com/aksonov/react-native-experimental-navigation/issues/1#issuecomment-301360042

**Comment by gigeos** [comment]
@iNeedCode I don't know but I confirm updating the library to `3.39.1` fix release Android
