### ISSUE TITLE
Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by Kaihuang724** [aksonov/react-native-router-flux#1864]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.3

### Expected behaviour
For the scene to come up on load.

### Actual behaviour
Error comes up saying "Cannot read 'property' of undefined"

ExceptionsManager.js:71 Unhandled JS Exception: Cannot read property 'component' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:71
ExceptionsManager.js:71 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

### Steps to reproduce

1. Run application using `react-native run-ios`

**Comment by Kaihuang724** [comment]
Code for scenes:

`'use strict'

import React from 'react';
import { Actions, ActionConst, Scene } from 'react-native-router-flux';
import { Auth0Login } from './components/Authenticate/Auth0Login'

//Routes
import {
  LoginContainer
} from './containers/index';

const scenes = Actions.create(
  <Scene key="root">
    <Scene key="authenticate" hideNavBar>
      // <Scene key="loginInitial" component={LoginContainer} panHandlers={null} initial />
      <Scene key="auth0Login" component={Auth0Login} panHandlers={null} initial />
    </Scene>
  </Scene>
)

export default scenes;
`

**Comment by aksonov** [comment]
Check latest version and Example project.

**Comment by Kaihuang724** [comment]
Hi @aksonov,

Thanks for the reply. I checked the latest version and copied the latest Example project, but still getting the same error. Could you tell me which part of the project I should be focused on - I'm not too sure why it's still throwing the error.

Thanks!
