### ISSUE TITLE
Removed react-native-router-flux but still getting error

### ISSUE THREAD

**Issue by FMGordillo** [aksonov/react-native-router-flux#1866]
### Version

- react-native-router-flux v3.39.1
- react-native v0.44.0

### Expected behaviour

Previously I've installed it using
 `npm i react-native-router-flux --save`
 and I got a similar error like #1832 so I removed it manually from package.json, uninstalled all `node_modules` folder, and reinstalled everything again, but with `yarn` 

I expected to keep everything as the same

### Actual behaviour

I got this error: 
`error: bundling: Error: ENOENT: no such file or directory, open 'D:\<my-folder>\node_modules\react-native-router-flux\node_modules\react-native\Libraries\Components\ActivityIndicator\ActivityIndicator.js'`

**Comment by ujwal-setlur** [comment]
Did you reset the cache?

**Comment by FMGordillo** [comment]
If you mean `npm cache clear` then yes, i've done that.
Also I've deleted all the content where I installed all the `npm install --global` just in case.

**Comment by ujwal-setlur** [comment]
Blow away the yarn.lock file and run yarn again. Or use npm install.

**Comment by FMGordillo** [comment]
I recall deleting the yarn-lock file, but seems that now it worked!
Dunno.. but... thanks!
We can close now
