### ISSUE TITLE
`-- UNMET PEER DEPENDENCY react@15.5.4

### ISSUE THREAD

**Issue by steelow** [aksonov/react-native-router-flux#1868]
### Version
Tell us which versions you are using: 
-react v15.5.4

### Expected behaviour
React v15.5.4 is installed and package.json file updated to reflect the addition

### Actual behaviour
It produces the following message instead:
`-- UNMET PEER DEPENDENCY react@15.5.4
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN crazytenants@1.0.0 No repository field.
npm ERR! code 1

### Steps to reproduce
1. Using the CLI in Windows 10
2. In your package.json file, either remove the 'react':'xxx' entry OR modify it to 'react':'^15.5.4'
2. Type: npm install react

**Comment by tgaff2x** [comment]
I seem to have the same issue.

**Comment by Ledbelly2142** [comment]
I have the same issue.

**Comment by danqing-jin** [comment]
Same on Mac with react-native-router-flux 3.39.1.
