### ISSUE TITLE
Handling the Android hardware back scene popping in chronological order

### ISSUE THREAD

**Issue by jonolock91** [aksonov/react-native-router-flux#1869]
- react-native-router-flux v3.37.0
- react-native v0.4.0

I'm interested in understanding how are people handling the Android hardware back button when they're using tabs so that is navigates through history in chronological order while switching tabs. 

# Expected behaviour
When pressing the Android back button only a single tabs navigation stack is popped, when the initial scene of that tab is reached the next pop exits the app.

# Current behaviour
I haven't yet implemented any Android back handler, I'm interested in hearing other peoples approaches as I'm unsure how to approach my desired result in a 'non hacky' way.

**Comment by Jahans3** [comment]
+1
