### ISSUE TITLE
Animating modals

### ISSUE THREAD

**Issue by ljhender** [aksonov/react-native-router-flux#187]
Any support for this? Haven't been able to get a modal to animate, am I missing something?

**Comment by aksonov** [comment]
No support, it is not implemented. PR is welcome.

**Comment by sbycrosz** [comment]
Hey, 
I'm interested in helping out. So far I could think of 3 possible ways of implementing this:

1.  Implement the animation in the modal view itself (example: ExNavigatorModal example, or https://github.com/sbycrosz/react-native-router-flux/commit/1a386d16b273e42f838e805fbee0e3a63cc9158f)
2.  Integrate the animation into the ```Router``` object (or maybe create a ModalRoute specific for modal components?)
3.  Use ```type="push"``` to display full-screen view with transparent background (will need to override previous view sceneConfig'

So yeah, any comments?

**Comment by aksonov** [comment]
https://github.com/sbycrosz/react-native-router-flux/commit/1a386d16b273e42f838e805fbee0e3a63cc9158f Looks interesting, have you tried it?

**Comment by sbycrosz** [comment]
It's working pretty well..
![modal-animation](https://cloud.githubusercontent.com/assets/4867178/13030493/1bed07d4-d2e8-11e5-9fe1-96a16de973ee.gif)
The timing function need some fine tuning though..

**Comment by sbycrosz** [comment]
After some thought, I think it's better to let the user animate their own modals since It's quite simple and they could have more control over it (i.e. modal size/ animation/ backdrop/ gestures etc.) and we could use https://github.com/maxs15/react-native-modalbox for a nice swipe-able modal

Example: https://github.com/sbycrosz/react-native-router-flux/commit/a5dac2e0e1a231fcb4df6f1befdcdc9bd2484c2b

![modal-animation](https://cloud.githubusercontent.com/assets/4867178/13033700/84fd76e6-d35b-11e5-9731-00b3fce3bbff.gif)

**Comment by ljhender** [comment]
Yeah @sbycrosz @aksonov thats actually how we solved this problem. Animating the actual modal itself was the best solution to this. We could update the documentation for people curious as to how to do this however.

**Comment by aksonov** [comment]
@sbycrosz Well done! Could you submit PR with Example update?

**Comment by ninjz** [comment]
With the current modal implementation, I can't seem to get this type of functionality (non full screen sized modal with a transparent backdrop).

**Comment by ninjz** [comment]
With the current modal implementation, I can't seem to get this type of functionality (non full screen sized modal with a transparent backdrop).

**Comment by braco** [comment]
@ljhender: would be interested in your implementation, if available

**Comment by jdmunro** [comment]
I'm also trying to get a modal to appear transparently over some other scenes. I've tried the example from @sbycrosz but this doesn't seem to work anymore because ```Schema``` is no longer supported. I can get a modal to appear but it is not rendering the scenes beneath. Has anyone had any luck?

**Comment by ms88privat** [comment]
@jdmunro its working something like this. You can find it in the documentation [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md)

```jsx
import {Scene, Router, Modal} from 'react-native-router-flux';

<Scene
    key='homeView'
    component={Modal} 
     >
    <Scene key='home' >
       .... normal scenes
    </Scene>
    <Scene key='Modal1' component ..../>
    <Scene key='Modal2' component .. />
```

Then push and pop the modal like normal, hope this helps

**Comment by jdmunro** [comment]
Thanks @ms88privat I'll give that a go 👍

**Comment by Naoto-Ida** [comment]
@sbycrosz Thanks for the example! Unfortunately it doesn't seem to reappear when I call the same action.

**Comment by Naoto-Ida** [comment]
Never mind, if you set the `onClosed` callback to `Actions.pop` instead of `Actions.replace`, the example works.
