### ISSUE TITLE
Scenes inside tabs (switch) getting corrently unmounted and then incorrectly re-mounted

### ISSUE THREAD

**Issue by ujwal-setlur** [aksonov/react-native-router-flux#1870]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.1
- react-native v0.44

This is a clone of #1329. I am opening a new issue since I cannot reopen #1329. All relevant history is there.

**Comment by ezha86** [comment]
can confirm it. all scenes do re rendering while clicking between tabs.

**Comment by sarovin** [comment]
Can you test this PR? => #1386

**Comment by ujwal-setlur** [comment]
I did. It did not help. I essentially used your fork of the repo. I still see the issue.

**Comment by lukemiles** [comment]
This is happening to us as well

**Comment by lukemiles** [comment]
(Also, this didn't start happening until we upgraded from React Native 0.42 to 0.44)

**Comment by ujwal-setlur** [comment]
That's interesting. Did you do this comparison with the same version of react-native-router-flux?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ezha86** [comment]
i had to downgrade router-flux for now. my deps:
      "react": "16.0.0-alpha.3",
      "react-native": "v0.43.0-rc.3",
     "react-native-router-flux": "3.37.0".
works for me

**Comment by NachosSs** [comment]
Thanks, downgrade to 3.37.0 resolve the issue.

**Comment by zxcpoiu** [comment]
@sarovin 

thanks, I've tested your PR, and it fix the problem.

**Comment by duhseekoh** [comment]
@ezha86 - confirmed that works. 0.43.3 comes with react 16.0.0-alpha.6 -- important to note becuase you have to downgrade to -alpha.3 for this to work.
