### ISSUE TITLE
[question] how to change in tabs without reload scene

### ISSUE THREAD

**Issue by pckz** [aksonov/react-native-router-flux#1872]
Hello. This is a really simple question that days searching I can't find a solution (I must be very bad looking, I do not know)

THIS CAN BE SKIPPED:

_My experience with react native has mobile native and hybrid dev has been weird. Really good after understanding the basics and see how powerful is. And lousy in terms of documentation and learning. No tutorial good, incomplete documentation in almost all the content, examples that do not work, components that do not exist and must be created by hand, etc._

Question:
I developed an app with router flux and works very well. After that, I created a scene with tabs. My only problem is where change the tab, the content is reloaded as a new scene. The views are like a dashboard, so you can scroll a lot, but when you change the tab, you loose the scroll and all content that has been loaded. To change the scene I use Actions.<Component(props)>

**Comment by lukemiles** [comment]
I think this behavior you're experiencing is a bug (see #1870). FWIW, this doesn't happen to us on React Native 0.42 so perhaps downgrading to that before it's fixed.

**Comment by pckz** [comment]
wow, I did not think it could be a bug.

The version of my project and components are:

react-native --version
`react-native-cli: 2.0.1
react-native: 0.43.3`

npm list --depth=0
```
├── @remobile/react-native-refresh-infinite-listview@1.0.6
├── babel-jest@19.0.0
├── babel-preset-react-native@1.9.1
├── jest@19.0.2
├── react@16.0.0-alpha.6
├── react-native@0.43.3
├── react-native-button@1.8.2
├── react-native-circle-button@1.0.4
├── react-native-drawer@2.3.0
├── react-native-fast-image@0.0.9
├── react-native-fit-image@1.4.8
├── react-native-htmlview@0.9.0
├── react-native-image-fit@0.9.10
├── react-native-image-progress@0.6.0
├── react-native-image-to-base64@0.1.0
├── react-native-infinite-scroll-view@0.4.2
├── react-native-loading-spinner-overlay@0.4.4
├── react-native-material-design@0.3.7
├── react-native-modalbox@1.3.9
├── react-native-photo-view@1.2.0
├── react-native-radio-buttons@0.14.0
├── react-native-router-flux@3.38.0
├── react-native-share@1.0.20
├── react-native-side-menu@0.20.1
├── react-native-simple-router@0.12.0
├── react-native-tabs@1.0.9
├── react-native-tooltip@5.0.0
├── react-native-tooltip-menu@1.0.8
├── react-native-vector-icons@4.0.1
├── react-native-webview-autoheight@1.0.4
└── react-test-renderer@16.0.0-alpha.6
```

**Comment by mbenjamin618** [comment]
Just use the type REFRESH

**Comment by avishayhajbi** [comment]
@mbenjamin618  he said "without reload"

**Comment by chenqiang1121** [comment]
@mbenjamin618   thank you , you are right!
