### ISSUE TITLE
Back button action

### ISSUE THREAD

**Issue by ugendrang** [aksonov/react-native-router-flux#1877]
Let us consider screen with Navigation Path as follows:
Scene A > Scene B

From Scene B, pressing Back button '<' will take to Scene A. 
1. Is there any hook available for back button, ie on pressing back button in Scene B, need to access methods in Scene A to change some properties.
2. Do we have onPress action for back button, so that before going to Scene A, some action need to be perform in Scene B

**Comment by redhelix** [comment]
+1

**Comment by Dani93380** [comment]
`
 onBackFunction()
{
 ....
}

<Scene key="root>
    <Scene key="sceneA"  component={SceneA} />
    <Scene key="sceneB" onBack={this.onBackFunction()}  component={SceneB} />
 </Scene>
`

**Comment by Dani93380** [comment]
This should work
`
 onBackFunction()
{
 ....
}

<Scene key="root>
    <Scene key="sceneA"  component={SceneA} />
    <Scene key="sceneB" onBack={this.onBackFunction()}  component={SceneB} />
 </Scene>
`

**Comment by Dani93380** [comment]
This should work:

onBackFunction()
{
  console.log("backkkkkkkkkk")
  Actions.sceneA()
}


  <Scene key="root"  backButtonImage={require('./resource/img/menuIcone.png')}>
          <Scene  key="sceneA" component={SceneA} />
          <Scene  key="sceneB" onBack={this.onBackFunction()} component={SceneB} />
  </Scene>

**Comment by Dani93380** [comment]
This should work:

```
onBackFunction()
{
  console.log("backkkkkkkkkk")
  Actions.sceneA()
}


```
```
  <Scene key="root" >
          <Scene  key="sceneA" component={SceneA} />
          <Scene  key="sceneB" onBack={this.onBackFunction()} component={SceneB} />
  </Scene>

```

**Comment by ugendrang** [comment]
@Dani93380, I like to pass property from SceneB to SceneA on back button action as like below, but not sure how to call the 'onBackFunction' when I press back button in SceneB
```
class SceneB extends Component {
    render() {...}

    onBackFunction(){
        Actions.sceneA({myprop:'test'});
    }
}
```

**Comment by atljoseph** [comment]
question was asked...issue was closed...no data on solution for original issue... useless forum

**Comment by ac1dr3d** [comment]
https://gist.github.com/yanqiw/31aaa7502b74a51c3467d080409257ab

will try this.
