### ISSUE TITLE
Animate Same Scene Transition

### ISSUE THREAD

**Issue by caiokf** [aksonov/react-native-router-flux#1879]
Is there a way to animate same scene transition?

Let's say I have two scenes, Home and Product. Home being the initial scene.

When I call:

`Actions.Product()` <-- coming from Home, it animates the transition
`Actions.Product()` <-- coming from Product, it doesn't animate.

How can I animate that second transition?

-------------------------------
Using:
react-native-router-flux v3.37.0

**Comment by Dani93380** [comment]
Actions.Product({animation : 'fade'})

**Comment by caiokf** [comment]
@Dani93380 Thank you for your answer, but this works only coming from a different route. If I am already at a Product scene, no animation happens.
