### ISSUE TITLE
Confusing nomenclature with the term router

### ISSUE THREAD

**Issue by danielweinmann** [aksonov/react-native-router-flux#188]
Currently, 3 things are called router:

1. Router class on Router.js
2. The default export in ReactRouter.js (the whole documentation uses Router when requiring the class).
3. The router prop passed to Router (the one in ReactRouter.js)

I believe we should change them to something like this:

1. Router.js should become BaseRouter.js or something that makes clear that it is not the component we're going to import and render.
2. ReactRouter.js should become Router and have Router as class name in it, for debugging purposes.
3. The router prop should become adapter or something that makes clear that it is the implementation of an "abstraction". Router in ReactRouter.js is kind of abstract: it depends on ExRouter or other "adaptors" to work. The term adaptor is what comes to mind, but maybe there is something else.

What do you think of that, @aksonov?

**Comment by aksonov** [comment]
Maybe docs are unclear about it, here is explanation: Router is pure router (no react dependency). ReactRouter is adoptation for React. ExRouter is 'plugin' for ReactRouter.

**Comment by danielweinmann** [comment]
Yeah, I understand that. I just think it's better to have different terms for each thing. I also think it means trouble when you have to document these kind of thing instead of making it evident on the code.

This line creates the main problem, in my view: https://github.com/aksonov/react-native-router-flux/blob/master/index.js#L4

We're calling the react adaptation internally ReactRouter but exporting it as Router. It becomes more troubling because we already have a Router class internally as well.

As for the prop "router" on ReactRouter, I think it should be called "plugin", then.

**Comment by aksonov** [comment]
I agree with you - Router as component name was used for backward compatibility with prev. versions and for easy reading of route map. Maybe we really should rename current Router class to BaseRouter and ReactRouter to Router, PR will be welcome.

**Comment by danielweinmann** [comment]
Great ;) I'll try to do this and update the README as I do this.

I don't know when, though. If anyone else wants to do it, please feel free. I'll check here before starting.

**Comment by philipshurpik** [comment]
Hi!
I think possibly can be good idea to clean-up index folder.
Now it' really confusing.
As a proposal: move Schema, Route, TabBar, Actions, Router, Animations to maybe 'components' folder

About ReactRouter, EXRouter - we need example for it
And I also agree with idea of renaming
