### ISSUE TITLE
React native with redux REPLACE and RESET not working

### ISSUE THREAD

**Issue by RobertoP2012** [aksonov/react-native-router-flux#1880]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.1
- react-native v0.44

### Expected behaviour
Actions.scene({ type: ActionConst.REPLACE }) and Actions.scene({ type: ActionConst.RESET }) are not working, no errors are displayed. In redux logger i can see that REACT_NATIVE_ROUTER_FLUX_REPLACE is called but nothing happens, PUSH is working fine.

**Comment by rodolph66** [comment]
Prior to the last update, which resolved the 'BackAndroid replace with BackHandler' warning, the react-native-router-flux worked properly, now it doesn't and my case seems identical to the above mentioned reset issue.
Using same versions as above.

**Comment by bragur** [comment]
Hmm, strange... I'm having an issue with the default push not working, but RESET and REPLACE work fine. On same versions as well. Been trying to debug what's going on all day and pretty much going nuts 😝
