### ISSUE TITLE
not an object (_reactNative.BackHandler.addEventListener)

### ISSUE THREAD

**Issue by holleword** [aksonov/react-native-router-flux#1894]
"react-native": "^0.42.0",
 "react-native-router-flux": "^3.39.1",
Enter software error
![screenshot_2017-05-25-17-50-06-717_com nooshnotif](https://cloud.githubusercontent.com/assets/20741163/26445382/a43de38e-4172-11e7-9940-ee85c6a6d7e1.png)

**Comment by skyrbe** [comment]
I am facing the same issue when I try to use BackHandler . Any ideas where I should be putting the BackHandler event listener. My code currently looks like this

`
import React from 'react';
import { Actions, Scene, ActionConst } from 'react-native-router-flux';

// Consts and Libs
import { AppConfig } from '@constants/';

// Components
import Drawer from '@containers/ui/DrawerContainer';

// Scenes
import AppLaunch from '@containers/Launch/LaunchContainer';
import AuthScenes from './auth';
import TabsScenes from './tabs';
import HomeContainer from '@containers/Home/HomeContainer';

import {
  StyleSheet,
} from 'react-native';

/* Styles ==================================================================== */
const styles = StyleSheet.create({
  navBarTitle: {
    textAlign:'left'
  }
});

/* Routes ==================================================================== */
export default Actions.create(
  <Scene key={'root'} {...AppConfig.navbarProps} barButtonTextStyle={styles.navBarTitle}>
    <Scene
      hideNavBar
      key={'splash'}
      component={AppLaunch}
      analyticsDesc={'AppLaunch: Launching App'}
    />

    {/* Auth */}
    {AuthScenes}

    {/* Main App */}
    <Scene key={'app'} {...AppConfig.navbarProps} title={AppConfig.appName} hideNavBar={false} type={ActionConst.RESET}>
      {/* Drawer Side Menu */ }
      <Scene key={'home'} component={Drawer} initial={'tabBar'}>
        {/* Tabbar */}
        {TabsScenes}
      </Scene>
    </Scene>
  </Scene>,
);
`

**Comment by unadlib** [comment]
+1

**Comment by nilliu** [comment]
+1

**Comment by SuperKareem** [comment]
+1

**Comment by sdotson** [comment]
+1
