### ISSUE TITLE
how to get current top route or a route has navigated back?

### ISSUE THREAD

**Issue by sopaco** [aksonov/react-native-router-flux#1899]
how to get current top route or a route has navigated back?

**Comment by markdaws** [comment]
Add a reducer to the router, as in this example, you can then look at the action.type value to see if it was a back, pop, push, reset etc, should be all the info you need in there: https://github.com/aksonov/react-native-router-flux/blob/b11a84962e4e4d9265770382b8859d21d1a12ea0/Example/Example.js#L43
