### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by 0bit** [aksonov/react-native-router-flux#19]
I try to use this module in iOS project, and it running very well.
but when I try to use it in Android project, it has some strange problem.
So I want to know are there any plans to add Android support?

Thanks for providing such a cool module.

**Comment by aksonov** [comment]
What problems do you have?

Pavel.

**Comment by 0bit** [comment]
use with `react-native-tabs` like in "Example", 
 
but sometimes the component will has some vertical offset, like this:
![screenshot_com huncheowner_2015-10-13-18-55-09](https://cloud.githubusercontent.com/assets/1421728/10453313/aa7c4634-71dd-11e5-8579-3123649aa0c1.png)

and sometimes display ok:

![screenshot_com huncheowner_2015-10-13-18-54-55](https://cloud.githubusercontent.com/assets/1421728/10453308/a40f7b2c-71dd-11e5-8d9b-31e95ce8ed4a.png)

the same code run very well in iOS.

**Comment by aksonov** [comment]
Maybe it is issue of android react native version...

Pavel.

**Comment by aksonov** [comment]
Closing it for now
