### ISSUE TITLE
No support for latest 16.0.0 alpha version

### ISSUE THREAD

**Issue by RohanVB** [aksonov/react-native-router-flux#1904]
### Version
Tell us which versions you are using: 

- react: "^16.0.0-alpha.6"
- react-native-router-flux: "^3.39.1"
- react-native: "0.44.2"

### Expected behaviour
No npm warnings

### Actual behaviour
`npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.`

### Steps to reproduce

 ```
npm install --save react@16.0.0-alpha.6
npm i react-native-router-flux --save
```

Please note that I can't install ^15.0.0, as it would override the 16.0.0 version which is required by other packages:
```
npm WARN react-native@0.44.2 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-test-renderer@16.0.0-alpha.6 requires a peer of react@^16.0.0-alpha.6 but none was installed.
```
Also note that the warning message cannot be ignored. It leads to https://github.com/facebook/react-native/issues/4968 and the app build failing.

**Comment by RohanVB** [comment]
Similar result on simulator as we have on https://github.com/aksonov/react-native-router-flux/issues/1903

**Comment by killinit** [comment]
Same issue. :-(

**Comment by Jeyloh** [comment]
Is there a solution to this? Any compatible versions or workarounds? We have to present our mobile app for our customer in 2 days and this is really hindering the team!

**Comment by RohanVB** [comment]
I think a workaround for this would be changing the version in the dependencies, `yarn.lock` file line:4172 to 4174 as:

```
react@^16.0.0-alpha.6:
  version "^16.0.0-alpha.6"
  resolved "https://registry.yarnpkg.com/react/-/react-^16.0.0-alpha.6.tgz#41f7991b26185392ba9bae96c8889e7e018397ef"
```
and then save it and do `yarn add react@^16.0.0-alpha.6`
or if you use npm, `npm install react@^16.0.0-alpha.6`
would be the workaround if your other packages depend on `16.0.0-alpha.6`

**Comment by Jeyloh** [comment]
Already tried to install the latest version. This is my current package.json:

`{
  "name": "MobFamKal",
  "version": "0.0.4",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.9.0",
    "moment": "^2.18.1",
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.2",
    "react-native-calendar": "^0.11.0",
    "react-native-modalbox": "^1.3.9",
    "react-native-onesignal": "^3.0.3",
    "react-native-osd-simple-button": "^1.1.0",
    "react-native-router-flux": "3.38.0",
    "react-native-vector-icons": "4.1.1",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-saga": "^0.15.3",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6",
    "redux-mock-store": "^1.2.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

I've tried to run react-native-git-upgrade as well. Is there anything else obvious I can do? I've tried this whole thing:

rm -rf node_modules
watchman watch-del-all
npm install
npm start -- --reset-cache
source: https://github.com/facebook/react-native/issues/7022 

Anything else I can provide? 
[Here is a link to my last bug screen!](https://goo.gl/photos/VnDRjVnFLZL2ajqj8)

**Comment by toanlv92** [comment]
npm i react-native-router-flux --save
applxandroid@0.0.1 D:\Code\applxandroid
`-- react-native-router-flux@3.39.2
  +-- lodash.isequal@4.5.0
  +-- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0
  +-- react-native-experimental-navigation@0.27.0
  | `-- clamp@1.0.1
  +-- react-native-tabs@1.0.9
  `-- react-static-container@1.0.1

npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
Please help me fix this warning

**Comment by Jeyloh** [comment]
My solution was to rollback to my old versions of everything and modify `android/build.gradle` with


`allprojects {
    configurations.all {
      resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
          if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
            details.useVersion "0.44.2" // Your real React Native version here
          }
        }
      }
    }
}`

**Comment by killinit** [comment]
I have changed in package.json
React-native to 0.44.0

npm install.

It helped!



29.05.2017 3:30 PM "Jeyloh" <notifications@github.com> napisał(a):

**Comment by hynese** [comment]
Please try:

kill any lingering node processes:
`sudo kill -9 \`pgrep node\`` 

`rm -rf ./node_modules`

`npm update`

`react-native run-ios`

**Comment by sattaman** [comment]
+1

**Comment by vdolbilov** [comment]
I ran into this when downgrading from 0.45 back to 0.44.3. Tried a bunch of different combinations of everything but what worked was running

`react-native-git-upgrade 0.44.3` 
Followed by all of the commands suggested in the simulator:
`watchman watch-del-all`
`rm -rf node_modules && yarn`
`rm -rf $TMPDIR/react-*`
`yarn start -- --reset-cache`

**Comment by JasonGore** [comment]
This just happened to me and it was because I had a hung 'node' process on port 8081, preventing a new instance of react packager from starting. I did killall -9 node and then was fine.

**Comment by antzshrek** [comment]
as @hynese said, try killing any lingering node processes by running these codes:

`sudo kill -9 ```pgrep node``` `

`rm -rf ./node_modules`

`npm update`

then you should try running the codes again.

*******:~$ `sudo npm install --save react@16.0.0-alpha.6`

It should show you this after it installs successfully 

    + react@16.0.0-alpha.6

    added 16 packages in 35.241s

and 

*******:~$ `npm i react-native-router-flux --save`

    + react-native-router-flux@4.0.0-beta.21
    added 72 packages in 82.299s

**Comment by RohanVB** [comment]
@antzshrek issue obsolete and closed already :)
