### ISSUE TITLE
Navigation Component re-mounts when app is re-entered on android

### ISSUE THREAD

**Issue by eemebarbe** [aksonov/react-native-router-flux#1915]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.43.1

### Expected behaviour

App is pulled up after being in background, and the last scene that the app was left on is still present

### Actual behaviour

Navigation component is re-mounting every time the app is exited and re-entered (without being totally closed)

### Steps to reproduce

1. Press the home button
2. Re-select app
3. Initial scene is registered

**Comment by inferusvv** [comment]
But when you press Home button - you don't close app. App just minimizing

**Comment by TheMarsGuy** [comment]
@inferusvv Yes the app is minimizing.Though the app is minimizing, clicking on the app icon again, the navigation component is re-mounted i.e it starts again from the root component.

**Comment by eemebarbe** [comment]
@themarsguy exactly. I also logged something or in the constructor and that is also being called.

**Comment by efournival** [comment]
Is there any known workaround for this issue?

**Comment by inferusvv** [comment]
Maybe Scenes should be declared like this:

```
import {Actions, Scene, Router} from 'react-native-router-flux';

const scenes = Actions.create(
  <Scene key="root">
    <Scene key="login" component={Login} title="Login"/>
    <Scene key="register" component={Register} title="Register"/>
    <Scene key="home" component={Home}/>
  </Scene>
);

/* ... */

class App extends React.Component {
  render() {
    return <Router scenes={scenes}/>
  }
}
```

**Comment by mleung** [comment]
Hey guys, I know this ticket is closed, but in case anyone else runs into this problem--this actually solved it for me:

https://stackoverflow.com/questions/39657029/react-native-android-several-apps-instances-running-at-the-same-time-as-result

Basically, if you don't manually set android:launchMode="singleInstance", your route file and entire app will get created over and over coming from the background.

**Comment by jasongrishkoff** [comment]
This one's bugging me too -- the singleInstance or singleTask solution doesn't seem to work. If you minimize the app and re-open it, everything remounts.

**Comment by yoyo0427** [comment]
@mleung Thank you for helping me solve this problem.
