### ISSUE TITLE
navigationBarTitleImage won't display

### ISSUE THREAD

**Issue by g4laura** [aksonov/react-native-router-flux#1916]
- react-native-router-flux v3.37.0
- react-native v0.41.2

I'm trying to use navigationBarTitleImage to put an image in the nav bar of a few scenes. It was working up until a few days ago, but now the image won't display. I'm not sure why it stopped working. I didn't make  changes to that part of my project.

### Steps to reproduce

        <Scene sceneStyle={styles.pageStyle} key="home" component={Home}
          navigationBarTitleImage={require('./images/logo.png')}
          navigationBarTitleImageStyle={{  width:125, height: 35}}
         />

  pageStyle:{
    backgroundColor:'white',
     marginTop:78,
  }

**Comment by pbassut** [comment]
Upgrade to  3.39.1

**Comment by g4laura** [comment]
Thanks. I was hoping there was an another way because when I tried to upgrade it, I got an error, which would probably be resolved by upgrading react native, but upgrading react native leads to more errors. So, I was hoping there was a temporary work around. Oh well. Thanks for the reply!

**Comment by pbassut** [comment]
You could try react-native-git-upgrade to upgrade react-native. That could help

**Comment by pbassut** [comment]
There isn't other way no. It was a bug on the version you're using. And it was fixed on 3.39.0
