### ISSUE TITLE
[Question] Before route change event

### ISSUE THREAD

**Issue by inferusvv** [aksonov/react-native-router-flux#1917]
Hello! 
I have a page in my app with editable data by user. When user add some data there I need to show alert like "Are you sure you want to close page? You will loose your data" when user click Android Back button, or some link in Drawer Menu.

**Comment by Dani93380** [comment]
Hello , can you share your code ?

**Comment by inferusvv** [comment]
@Dani93380 I don't know what share. I just want to prevent `Actions['any_route']` somehow if it is called.

**Comment by Dani93380** [comment]
I think you should set a listener on your Back Button and your link in Drawer Menu then inside your function do your alert before redirecting to other page
