### ISSUE TITLE
[Question] Why use this instead of react-community/react-navigation?

### ISSUE THREAD

**Issue by jameskhamil** [aksonov/react-native-router-flux#1919]
I am curious why anyone is switching from this package to https://github.com/react-community/react-navigation/? I have read that people are abandoning this in favor of react-navigation, but it has so many bugs.

**Comment by hellomaya** [comment]
I like RNRF, both in Android & iOS, it bring consistent user experience in the app, which I have already used in a production app, but I am also trying react-navigation on a simple app, for now, feel like react-navigation wasn't my favorite yet, but it do provide more clean and simple API.

Also in RNRF, unmount a scene is also something I concerned about, usually it will not unmount a scene in navigation stack, it will bring extra memory use when memory is a critical point for the app.

**Comment by haipengz** [comment]
I think one of the reasons is that the docs of this package is far from completed, in fact it is rather awful and outdated, but no one seems to complete that docs. And it causes lots of confusion, which leads to tons of unresolved issues.

**Comment by jameskhamil** [comment]
@haipengz Do you think there more contributors needed or is this project just too personally locked in by repo owner?
