### ISSUE TITLE
Router issues when popping from a modal presented from the root

### ISSUE THREAD

**Issue by ninjz** [aksonov/react-native-router-flux#192]
I have my routes set up like this: 
```
<Router
  onPush={onEnterHandler}
  onReplace={onEnterHandler}
  onPush={onEnterHandler}
  hideNavBar={true} >
  <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
  <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
  <Schema name="withoutAnimation"/>
  <Schema name="tab" type="switch" icon={TabIcon} />

  <Route name="pager" schema="modal" onPop={()=>{return false}} wrapRouter={true} component={PromoPager} hideNavBar={true} title="PopularPager" />
  <Route name="bizpage" schema="modal" wrapRouter={true} component={BusinessPage} title="Starbucks"/>

  <Route name="initial" initial={true}>
    <Router footer={TabBar} showNavigationBar={false} style={{backgroundColor:'#24272A'}} >
      <Route name="main" schema="tab" source={require('./components/img/innactive_main.png')} component={MainFeed} hideNavBar={true} title="MainFeed"/>
      <Route name="popular" schema="tab" component={PopularFeed} source={require('./components/img/innactive_popular.png')}  title="PopularFeed"/>
      <Route name="activity" schema="tab" source={require('./components/img/innactive_activity.png')} hideNavBar={false} component={ActivityFeed} title="Activity"/>
      <Route name="profile" schema="tab" source={require('./components/img/innactive_profile.png')} component={ProfileView} title="Profile"/>
    </Router>
  </Route>
</Router>
```
So my issue is that I am opening a modal within the "popular" route which is presented from the root because i need it to cover the tab bar. I am able to pop the modal, but when switching to another tab I get this error:

<img width="374" alt="screen shot 2016-02-10 at 2 07 37 am" src="https://cloud.githubusercontent.com/assets/5641860/12940859/1be69a48-cf9b-11e5-9bba-af13a15cebf9.png">

My only ideas I have would be to keep track of the previous router when opening and closing the modal and manually assigning it back when popping the modal. But even then I don't know how I would go about doing that. Any ideas? Thanks.

**Comment by aksonov** [comment]
Modal window should be designed in such way, so it should be impossible to call other action, but only dismiss() from it.

**Comment by ninjz** [comment]
hmm so I set the type of the modal schema to type "modal", and made it dismiss by calling Actions.dismiss() and that seemed to work. But the issue now is that when displaying the modal, it gets stuck half way with the tab bar staying at the center. 

<img width="503" alt="screen shot 2016-02-10 at 2 09 39 pm" src="https://cloud.githubusercontent.com/assets/5641860/12958480/f4e74f36-cfff-11e5-80d1-af3d6711af9f.png">

**Comment by aksonov** [comment]
Check Example, error popup there. You need to use absolute positioning for that.

**Comment by ninjz** [comment]
Awesome thanks that worked thanks for the quick response. Is there any way to keep the FloatFromBottom transition when doing a modal popup like this?

**Comment by aksonov** [comment]
Unfortunately no at this moment. You could check sources, now modal is just 'view' inserted after navigator within ExRouter. It doesn't have nothing common with navigation and its transitions, so you could send PR to implement it.

**Comment by ninjz** [comment]
ahh i see alright will definitely look into doing that. cheers
