### ISSUE TITLE
Is there a way to remove/delete/clear all scenes which added before?

### ISSUE THREAD

**Issue by denghejun** [aksonov/react-native-router-flux#1922]
Is there a way to remove/delete/clear all scenes which added before? 
e.g.: `Actions.clear();`
```
function createScenes(props) {
    const { location: { city } } = props
    const movieShowingTitle = 'showing' + '(' + city + ')';
    const movieComingTitle = 'coming' + '(' + city + ')';
    const movieSearchTitle = 'search';

    return Actions.create(
        <Scene key='root'>
            <Scene key='cnew' component={Components.cnew} initial={true} hideNavBar={true} />
            <Scene key='movie' duration={10} renderBackButton={() => { }} component={Components.movie} navigationBarStyle={Styles.scene.navigationBar} hideNavBar={false}>
                <Scene key='movie_showing' title={movieShowingTitle} titleStyle={Styles.scene.title} />
                <Scene key='movie_coming' title={movieComingTitle} titleStyle={Styles.scene.title} />
                <Scene key='movie_search' title={movieSearchTitle} titleStyle={Styles.scene.title} />
            </Scene>
        </Scene>
      );
  }
```

The newer `title` (anyone of `movieShowingTitle`,`movieComingTitle`,`movieSearchTitle`) can NOT be passed into the target scene **when `createScenes` was called `multiple times`**.

How do I need to fix this ?

## Updated
Please see example above, I mean the state `city` will be changed sometime, so the router must be re-rendered at that time, **BUT** the new title (e.g: "showing(New York)") not pass into the screen, the screen's title still keep the old one!

**Comment by markdaws** [comment]
Are you saying you want to be able to dynamically change the title string of the scene?

You should be able to just pass in the title when you change to the new scene e.g.
Actions.movie_showing({ title: 'foo' })

Or if you need to update the title of a scene you are already viewing, you can call refresh e.g.
Actions.refresh({ title: 'bar' })

**Comment by denghejun** [comment]
Actually I raise this question because I want change the question below:

[https://github.com/aksonov/react-native-router-flux/issues/167](url)

Finally I found a perfect way to solve this:

Ok, you can pass a factory method as a prop into your screen, the method return a **reference type** value, here is `this.props`, see below:

```
<Scene key='home' getNewerProps={()=>this.props}  {....other props} />
```

And then in your scene view, use the method like this:
```
const newerProps = this.props.getNewerProps(); // newerProps must be latest.

Actions.Refresh({ title: newerProps.title }); // then refresh current screen's title. it works.
```

## How it works
Two Points: 

- the factory method is a lazy way to get some data. it only be executed when it is called.
- the return value of factory method had better be a reference type rather than value type.

So we can get the newer props value from the same reference memory address. So the most important thing is keep the reference, you can get it whenever the value changed.
