### ISSUE TITLE
How to refresh a scene that is not currently the active scene

### ISSUE THREAD

**Issue by markdaws** [aksonov/react-native-router-flux#1923]
The docs state:
"Actions.refresh(PARAMS) will update the properties of the current screen."

I load SceneA, then start a network call to get some data, before it returns the user might have transitioned to SceneB, so I call Actions.refresh() wanting to update SceneA, but because the user is viewing SceneB the update it lost.

How can I refresh a specific scene, even if it is not the active one?

**Comment by waheed25** [comment]
my issue is almost same i have page which connects to internet and than display but when internet is not connected it shows a page which say internet error i want to integrate a button on error page to refresh the page which display a login page if internet is connected and if internet is doesn't connected it should display again same error page ...is there any solution of that problem???

**Comment by markdaws** [comment]
Can't you just put the network error inside the login page? Then hitting refresh is just doing a network check and updating some react state on that page to conditionally show the error message or not. Doesn't seem like something you need to involve reac-tnative-router-flux with.

**Comment by waheed25** [comment]
i am using actions.refresh() to refresh a page it works fine after login screen or in the main app but if my internet is off and i open the app it displays the error on login screen and actions.refresh does't work if even  i connects with internet it remains on the same page and refresh button looks like disable
