### ISSUE TITLE
SceneView warning when upgrading to RN 0.45

### ISSUE THREAD

**Issue by mikaello** [aksonov/react-native-router-flux#1929]
### Version
- react-native-router-flux v3.39.1
- react-native v0.45.0

### Expected behaviour

No warnings.

### Actual behaviour

Warning encountered for every change of scene:

```
Warning: SceneView has a method called shouldComponentUpdate().
shouldComponentUpdate should not be used when extending React.PureComponent.
Please extend React.Component if shouldComponentUpdate is used.
```

### Steps to reproduce

1. `$ git clone git@github.com:aksonov/react-native-router-flux.git`
2. `$ cd react-native-router-flux/Example`
3. `$ react-native-git-upgrade`
4. `$ npm install`
4. `$ react-native run-[android | ios]` (I also have to start server manually `npm run start -- --root .`)

![screenshot_20170607-160056](https://user-images.githubusercontent.com/2505178/26882524-eefd3fdc-4b9a-11e7-8cf7-cda1321ec5e8.png)

I do not encounter this warning with a clean install of RN 0.45 without RNRF (aka `react-native init test; cd test; npm install; react-native run-[android | ios]`)

**Comment by zhmeng** [comment]
I have the same problem , and how to resolve it ?

**Comment by zhmeng** [comment]
is it support  react 16 ? 
ilkkzm@ilkkzm-Inspiron-7460:~/Projects/Own/MiniDai$ npm install
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.

  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.0",
    "react-native-router-flux": "^3.39.1"

**Comment by Justkant** [comment]
Should be fix soon
https://github.com/aksonov/react-native-experimental-navigation/pull/23

**Comment by zhmeng** [comment]
ok , thank you . @Justkant

**Comment by janfix** [comment]
Same question. Thank you!

**Comment by cronos88** [comment]
If I publish my app in Play Store, this warning appear in consumers' phones?

**Comment by radko93** [comment]
@cronos88 no. Warnings are disabled by default in release mode.

**Comment by j8jacobs** [comment]
i just included react native flux router into my project today, but there has already been a commit and merge on the issue. how do i get the latest code to fix this issue?

**Comment by radko93** [comment]
@j8jacobs you would probably need to replace this with `master` branch from github https://github.com/aksonov/react-native-router-flux/blob/master/package.json#L41

**Comment by didil** [comment]
same issue

**Comment by guysegal** [comment]
is a release with the fix is expected soon?
