### ISSUE TITLE
renderRightButton throw this.function is not a function

### ISSUE THREAD

**Issue by kinber95** [aksonov/react-native-router-flux#1931]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.1
- react-native v0.44.0

I implemented in my router-flux nav bar a right button like this:

```
  static renderRightButton = (props) => {
          return (
              <TouchableOpacity onPress={() => this.getCurrentPosition()} style={{bottom: 4, right: 8}}>
                  <Icon name='ios-locate-outline' style={{color: 'white'}} />
              </TouchableOpacity>
          );
    }
```
But If I click on my button I get this error :

`this.5.getCurrentPosition is not a function
`
I declare my function in the constructor with  
`this.getCurrentPosition = this.getCurrentPosition.bind(this)
`

**Comment by mymachine8** [comment]
you cannot refer to 'this' in a static method
