### ISSUE TITLE
direction: vertical why only from down to top?

### ISSUE THREAD

**Issue by hasancanozkan** [aksonov/react-native-router-flux#1932]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.44.0

### Expected behaviour

I just have an gallery app and using swipe to reach the pictures or other parts of the app. What I only need is for example when I swipe down, I want to see the upcoming page from up to down(on the swipe direction). However, when I use the direction as vertical, the next page pops up from down to top which I dont want. Is there a sollution for it ? may be something like leftToRight as the opposite transition to horizontal??

**Comment by hasancanozkan** [comment]
I changed it on my own, in case someone needs, you can ask

**Comment by tobiaslins** [comment]
@hasancanozkan Are you searching for the `topToBottom` option? 

I only can't figure out how to close it by swiping up

**Comment by hasancanozkan** [comment]
if you use topToBottom, the reverse move is basically in the direction of swiping up, isnt it?
