### ISSUE TITLE
[Android] Custom header is overlaid with statusbar

### ISSUE THREAD

**Issue by atpunk** [aksonov/react-native-router-flux#1934]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.1
- react-native v0.44.0
- react 16.0.0-alpha.3

### Expected behavior
For Android, the status bar is usually the padding between each new screen

### Actual behavior
The top of the screen is overlayed with the Android status bar
![android_capture](https://user-images.githubusercontent.com/6874950/26996835-058dc01a-4d2a-11e7-8702-5d45104896bc.jpg)

### Steps to reproduce

1. The main app has a dashboard created from react-native-tab-view
2. Create button to Invoke navigation to another js file that has react-native-tab-view
3. View status bar on Android.

**Comment by jfajardo** [comment]
I solved it with:

```
import { StatusBar } from 'react-native';

<Router navigationBarStyle={{marginTop:StatusBar.currentHeight}}>
```
