### ISSUE TITLE
How to create custom navigation bar

### ISSUE THREAD

**Issue by satishmane** [aksonov/react-native-router-flux#1943]
Can anyone please share working example of custom navigation bar? I am using react-native-drawer for showing list of menu items. My use case is that I want to add a custom refresh button using vector icon in the middle of navigation bar to reload a particular scene. At the same time, I want to also maintain standard drawer menu icon in the left corner.

**Comment by satishmane** [comment]
I have managed to get custom navigation bar and able to add custom button like 'Refresh' button. But when I try to call Actions.<SceneName>, it does not refresh current scene. My requirement is that on click refresh button, it should refresh current open scene. Any idea how to refresh current scene from custom navigation bar

**Comment by satishmane** [comment]
Here is code

Scenes.js

<RouterWithRedux navBar={CustomNavBar}>
<Scene key="Main"  component={NavigationDrawer}>
            <Scene key="drawerRoot"   >
                <Scene key="home" component={AerBikeMap}  />
                <Scene key="alert" component={Dashboard}/>
           </Scene>
</Scene>
</RouterWithRedux navBar={CustomNavBar}>

MyNavBar.js
export default Class CustomNavBar extends Component {
return (
            <Animated.View style={[styles.header]}>
                <View style = {[styles.leftButton, { alignItems: 'flex-start' }]}>
<TouchableOpacity onPress={this.context.drawer.open} >
<Image source={burger}  resizeMode="contain"/>
</TouchableOpacity>
</View>
                <View style = {[styles.rightButton, { alignItems: 'flex-end' }]}>
                    <Icon.Button name="refresh"  **onPress={Actions.home()}**>
                    </Icon.Button>
                </View>
            </Animated.View>
        );
}

NavigationDrawer.js

<Drawer
        ref="navigation"
        type="overlay"
        onOpen={() => Actions.refresh({ key: state.key, open: true })}
        onClose={() => Actions.refresh({ key: state.key, open: false })}
        content={<MainMenu />}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        negotiatePan
        tweenHandler={(ratio) => ({
          main: { opacity: Math.max(0.54, 1 - ratio) },
        })}
      >
        <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
      </Drawer>

MainMenu.js

<View >
 <Icon.Button name="home" onPress={() => {  drawer.close();  Actions.mapMain() }}> 'Home' </Icon.Button>
</View>
<View >
<Icon.Button name="warning" onPress={() => { drawer.close(); Actions.alerts() }}>
                    'Alert'
  </Icon.Button>
</View>

**Comment by fossage** [comment]
Try passing `{type: 'reset'}` into your call to Actions.home()
