### ISSUE TITLE
it  will refresh when i click the tabbar twice 

### ISSUE THREAD

**Issue by kliuj** [aksonov/react-native-router-flux#1945]
<Button onPress={() => { drawer.close(); Actions.tab1(); }}>Switch to tab1</Button>
      <Button onPress={() => { drawer.close(); Actions.tab2(); }}>Switch to tab2</Button>
      <Button onPress={() => { drawer.close(); Actions.tab3(); }}>Switch to tab3</Button>
      <Button onPress={() => { drawer.close(); Actions.tab4(); }}>Switch to tab4</Button>
      <Button onPress={() => { drawer.close(); Actions.tab5(); }}>Switch to tab5</Button>

if i click  the same button twice, the page will refresh

**Comment by IamAlchemist** [comment]
same problem

**Comment by kliuj** [comment]
@IamAlchemist   你是在爱奇艺的小伙伴？
