### ISSUE TITLE
UNMET PEER DEPENDENCY when attempting to install with react-native 0.45.1

### ISSUE THREAD

**Issue by mechcow** [aksonov/react-native-router-flux#1946]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.40.1
- react-native v0.45.1

### Expected behaviour

Able to install application on a fresh init

### Actual behaviour

C:\Users\Joel\Documents\TestProject>npm i react-native-router-flux --save
TestProject@0.0.1 C:\Users\Joel\Documents\TestProject
`-- react-native-router-flux@3.40.1
  +-- lodash.isequal@4.5.0
  +-- UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0 || ^15.0.0
  +-- react-native-experimental-navigation@0.28.0
  | +-- babel-preset-react-native@1.9.2
  | `-- clamp@1.0.1
  +-- react-native-keyboard-aware-scroll-view@0.2.9
  +-- react-native-tabs@1.0.9
  `-- react-static-container@1.0.1

npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.

C:\Users\Joel\Documents\TestProject>react-native -v
react-native-cli: 1.0.0
react-native: 0.45.1

### Steps to reproduce

1. init a new project using react-native version 0.45.1
2. Attempt to install react-native-router-flux

**Comment by LukasNavickas** [comment]
Doesn't work with React 16 :(
