### ISSUE TITLE
componentDidMount not always get called in Tabs

### ISSUE THREAD

**Issue by atilaqi** [aksonov/react-native-router-flux#1953]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.2
- react-native v0.44.0

### Expected behaviour
componentDidMount should be always get called when tap the tabs

### Actual behaviour

componentDidMount not always get called , sometimes called , sometimes nothing happened

### Steps to reproduce

1. in tab view 
2. click tab icon
3.  the initial view's componentDidMount sometimes get called , sometimes not.

Hope get your reply , thanks in advance

**Comment by olegdev** [comment]
I get same issue with tabs!

`componentDidMount` not always get called and scene not always refreshes with new props when I switch between tabs.

**Comment by mounibec** [comment]
Same issue using the same versions of react-native and react-native-router-flux

**Comment by douglasjunior** [comment]
Same problem here, not just with the tabs.

**Comment by nmfzone** [comment]
What I've faced, `componentDidMount` only called when we go to more than 1 scene..I don't think if It's an issue..

**Comment by mounibec** [comment]
It's related to this [1466](https://github.com/aksonov/react-native-router-flux/issues/1466). 
A workaround is to add "duration" to the related route  `<Router duration={300} ...>`. I think 300 is the default..

**Comment by aksonov** [comment]
Could you please check v4 beta #1974
