### ISSUE TITLE
Overlap of header and tab bar

### ISSUE THREAD

**Issue by RHinderiks** [aksonov/react-native-router-flux#1954]
### Version
Tell us which versions you are using: 

- react-native-router-flux latest
- react-native latest

### Expected behaviour

Views being rendered between the header and the tabbar

### Actual behaviour
header is being renderen on tab of view, view is rendered on top of tabbar

### Steps to reproduce
Just a page with a header and tabs

<img width="377" alt="screen shot 2017-06-22 at 10 43 53" src="https://user-images.githubusercontent.com/26223525/27425144-b9aba226-5737-11e7-85b6-4dd190bffab8.png">

Code being used

```javascript
<Router>
          <Scene key="root">
              <Scene key="login" style={{flex:1}}  component={LoginPage} hideNavBar={false}/>
              <Scene key="tabbar" type={ActionConst.REPLACE} tabs={true} >
                  <Scene key="gallery" style={styles.fitView} component={Gallery} title="Gallery" icon={TabIcon}/>
                  <Scene key="tab2" style={styles.fitView} component={LoginPage} title="Tab #2" icon={TabIcon}/>
                  <Scene key="tab3" style={styles.fitView} component={LoginPage} title="Tab #3" icon={TabIcon}/>
                  <Scene key="tab4" style={styles.fitView} component={LoginPage} title="Tab #4" icon={TabIcon}/>
                  <Scene key="tab5" style={styles.fitView} component={LoginPage} title="Tab #5" icon={TabIcon} />
              </Scene>
          </Scene>
          <Scene key="error" component={Error}/>
    </Router>);
```

**Comment by Devikaelangovan** [comment]
I am also getting same issue. is it resolved?

**Comment by RHinderiks** [comment]
@Devikaelangovan It might not even be an issue since ios is always rendered from the absolute top. You can solve it by setting your own padding but i'm not quiet sure how much and if it differs from device to device (especially on android with all kinds of ratios etc.)
