### ISSUE TITLE
 componentWillUnMount be not always get called when back

### ISSUE THREAD

**Issue by liuboshuo** [aksonov/react-native-router-flux#1957]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Expected behaviour

componentWillUnMount be not always get called when back

### Actual behaviour

componentWillUnMount be not always get called when click back previous view

### Steps to reproduce

1.
2.
3.

**Comment by IamAlchemist** [comment]
I ran into the same case

**Comment by rthor** [comment]
It's `componentWillUnmount` not `componentWillUnMount`.

**Comment by MarcusHurney** [comment]
Also wondering why components do not unmount when using Actions.pop?
