### ISSUE TITLE
SyntaxError /node_modules/react-native-router-flux/src/navigationStore: Unexpected token (18:0)

### ISSUE THREAD

**Issue by thanhtr** [aksonov/react-native-router-flux#1959]
### Version
- react-native-router-flux v4.0.0-alpha.4
- react-native v0.41.x
- typescript 2.3.2

### Details
I do the straightforward route creation:
```javascript
<View style={{flex: 1, backgroundColor: Layout.backgroundColor.white}}>
        <View style={styles.app}>
          <Router sceneStyle={{backgroundColor:'#fff'}}>
            <Scene key="root">
              <Scene key="tour" initial={initialRouteName === 'tour'} component={Tour}/>
              <Scene key="signup" initial={initialRouteName === 'signup'} component={SignUp}/>
              <Scene key="register" component={Register}/>
              <Scene key="login" component={Login}/>
              <Scene key="main" tabs={true} initial={initialRouteName === 'main'}>
                <Scene key="feed" component={Feed} icon={selected => (<Image source={selected ? iconFeed : iconFeedGray}/>)
                  }></Scene>
                <Scene key="map" component={View} icon={selected => (<Image source={selected ? iconMap : iconMapGray}/>)
                  }></Scene>
                <Scene key="camera" component={Scan} icon={selected => (<Image source={selected ? iconCamera : iconCameraGray}/>)
                  }></Scene>
                <Scene key="search" component={View} icon={selected => (<Image source={selected ? iconFind : iconFindGray}/>)
                  }></Scene>
                <Scene key="profile" component={Profile} icon={selected => (<Image source={selected ? iconProfile : iconProfileGray}/>)
                  }></Scene>
              </Scene>
            </Scene>
          </Router>
        </View>
      </View>
```
And got the error dictated in the title. Is this dependency problem?
Thank you very much

**Comment by lattuguini** [comment]
I had the same problem, if you go to navigationStore you can see @autobind, that's the problem, I solved the issue with this: 
https://moduscreate.com/using-es2016-decorators-in-react-native/
But I'm not sure if this gonna work to you because I don't use Typescript!

**Comment by winnerliu** [comment]
+1

**Comment by ryohlan** [comment]
+1

**Comment by thanhtr** [comment]
@lattuguini Thank you for your suggestion. I'd try it out now and let you know the result :)

**Comment by thanhtr** [comment]
After clear the node_modules, installing babel-plugin-transform-decorators-legacy and declare as plugin in .babelrc as instructed from the site you suggested I got into this error. So I don't know if it is still result of the fact that I use typescript.

![screen shot 2017-06-26 at 14 07 35](https://user-images.githubusercontent.com/4426707/27536716-0c7274b4-5a79-11e7-943d-e4416300ca32.png)

**Comment by nmfzone** [comment]
+1 Struggling with this issue..

**Comment by thanhtr** [comment]
I will downgrade stabler version of router flux. This one seems to be really alpha and maybe it's not the time yet.

**Comment by nmfzone** [comment]
Yep, same here @thanhtr. I just realized it. Downgrade to `3.39.1` should fixed this issue.

**Comment by peter-pogocarshare** [comment]
@thanhtr I've gotten "Cannot read property 'style' of undefined for this module before but for a different issue. I was able to correct that issue with `react-native-git-upgrade`.

I've yet to solve this thread's issue for my project. I'd rather not downgrade... will touch base when I get it resolved on my end.

**Comment by tonytamps** [comment]
I'm curious why the v4-alpha version was published to npm from a branch and the latest master (and latest release on github) is `3.39.1`.

The v4-alpha is clearly not ready yet.

**Comment by lattuguini** [comment]
@thanhtr, after my "solving" method I had another issue :( So I downgraded my version to 3.40.1 and now I don't have any problem.t

**Comment by aksonov** [comment]
Sorry, but v4.0.0 is ALPHA and definitely is not ready for production. As I see npm recognize 'alpha' correctly and doesn't install it by default.

@thanhtr You have to add 'decorator' support to your project. Check Example project for .babelrc config.

**Comment by aksonov** [comment]
@thanhtr API for Router is changed - you have to wrap root Scene with Router function, see more details here: https://github.com/aksonov/react-native-router-flux/issues/1595 and Example project.

**Comment by mistenkt** [comment]
yarn did install the 4.0.0 alpha by default

**Comment by aksonov** [comment]
@mistenkt Fixed now, thanks.

**Comment by aksonov** [comment]
@thanhtr You may want to try latest v4 beta now, it should not have this error.
