### ISSUE TITLE
Which version is the latest supporting RN0.43.1?

### ISSUE THREAD

**Issue by booker-laputa** [aksonov/react-native-router-flux#1962]
I have been using `npm i react-native-router-flux` to install

Because of other plugins, I have to stay with RN0.43.1 and I found the latest release is not working with it.

Could any one tell me which release version on npm is the latest supporting RN0.43.1?

**Comment by aksonov** [comment]
Could you try 3.40.1 ?

**Comment by booker-laputa** [comment]
@aksonov Tried, it is broken, once 'react-native-router-flux' is imported, as ViewPropTypes.style is undefined in RN0.43.1

I have tried all and finally found 3.38.0 is the latest working with RN0.43.1
