### ISSUE TITLE
Authentication/Unlock on AppState change

### ISSUE THREAD

**Issue by kwnccc** [aksonov/react-native-router-flux#1963]
First of of all, great work with this react-native package and the support, it's been pretty useful and one of the top alternatives right now for react-native routing.

What I need to implement is a Scene as a wrapper on other specific Scenes for authentication purposes. I have read and searched different resources, github issues, stackoverflow, medium blog post etc. and I can understand that a splash screen for authenticating and the correct redirection is needed. But my problem is a little different from this approach because. 

I'm strongly dependent in RN AppState because I need to check when change to/from active/background state. There are private data that need to be protected, so then user clicks on home button and the app gows on background I need a parent Scene to listen to the events on the AppState. When application comes in the foreground I ask user to unlock the application using either TouchID or Passcode. In case of error user should be redirected to login screen, otherwise navigate to a screen.

My code seems like below:

index.js
```
...
  <Router>
    <Scene key="root" hideNavBar>
      <Scene key="splashScreen" component={SplashScreen} initial />
      <Scene key="login" component={Login} />
      <Scene key="authenticated" component={AuthenticationContainer}>
        <Scene key="dashboard" component={Dashboard} title="Dashboard" hideNavBar />
      </Scene>
    </Scene>
  </Router>
...
```

AuthenticationContainer.js
```
class AuthenticationContainer extends Component {
  constructor(props) {
    super(props)
    this.state = {
      appState: '',
      isLoggedIn: false
    }
  }

  componentWillMount() {
    AppState.addEventListener('change', this._handleAppStateChange)
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange)
  }

  _handleAppStateChange = (nextAppState) => {
    if(this.state.appState.match(/background/) && nextAppState === 'active') {
      // App has come to the foreground!
      // this function will check if the user is logged in
      // in case the user is already logged in, touchid or passcode authentication will be needed
      // and on successful authentication user will be redirected to dashboard
      // otherwise user is redirected to login screen to provide credentials
      this._checkLoginStatus()  
    }
    this.setState({appState: nextAppState})
  }

  render() {
    let elem = ''
    if(this.state.isLoggedIn) {
      let compArr = this.props.children.map((scene, idx) => React.createElement(scene.component, {key: idx}))
      return <View>{compArr}</View>
    } else {
      return null
    }
  }
}
```

The actual problem here is not only the authentication, since this could also be initiated and redirect from a single scene, but mainly the revoking of access on AppState change to background. How would you propose to implement such functionality?

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.40.1
- react-native v0.45.1

**Comment by aksonov** [comment]
You have to use Redux or Mobx to manage app state. Latest RNRF v4 uses Mobx internally so you will benefit from mobx.

**Comment by aksonov** [comment]
v3 provides `Switch` to change screen dynamically, v4 uses mobs-powered navigationStore

**Comment by aksonov** [comment]
@frangeris Great example! @kwnccc Have you tried it? Closing this ticket anyway, now v4 is only version supported.
