### ISSUE TITLE
Multiple buttons on navbar

### ISSUE THREAD

**Issue by YogendraShelke** [aksonov/react-native-router-flux#1964]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.40.1
- react-native v0.45.1

### Expected behaviour

Need help to show multiple buttons on right hand side of navigation bar like this

![screen shot 2017-06-28 at 6 18 57 pm](https://user-images.githubusercontent.com/25844542/27637746-6ddde114-5c2e-11e7-8c9c-4347c5f96adb.png)

### Actual behaviour

Can only add one button like this

![screen shot 2017-06-28 at 6 22 06 pm](https://user-images.githubusercontent.com/25844542/27637842-c32a6980-5c2e-11e7-8dfb-98c33176aaae.png)

**Comment by aksonov** [comment]
You may pass own navbar and render as many buttons as you need.
