### ISSUE TITLE
react-native-router-flux (undefined is not an object ... viewPropTypes.style)

### ISSUE THREAD

**Issue by hulusimizrak** [aksonov/react-native-router-flux#1968]
### Version
- react-native-router-flux@3.40.1

### Problem
- for index.android.js

> import { Router, Scene } from 'react-native-router-flux';

Error Picture :
[https://i.stack.imgur.com/cBK5Z.png](url)

I get an error adding, Can there be help ? 
Thank you

**Comment by sofianegargouri** [comment]
Same here

**Comment by aksonov** [comment]
Please check latest 3.41.0, Example project doesn't have such issue.

**Comment by Blapi** [comment]
I've downgraded my version of react-native-router-flux on 3.37.0 after starting getting this error.

If you want it fixed with latest version of RNRF, you should check your version of RN, on 0.44 it should work fine !

(I have to downgrade RNRF because of some dependencies that require RN < 0.42..)
