### ISSUE TITLE
refresh param of children of Drawer.

### ISSUE THREAD

**Issue by Symous** [aksonov/react-native-router-flux#1969]
Hi, I use a drawer to contains a home scene. just like this:
```js
<Scene key = "drawer" component={DrawerPage} open = {false} initial = {true} >
            <Scene key = "home" component={HomePage} hideNavBar initial={false}/>
</Scene>
```
And I have another page A which is not contained with drawer, when I pop from A to home,
```js
Actions.pop({refresh : { param:'value' }})
```
 it is supposed to  receive the refresh in the componentWillReceiveProps of home , but the truth is drawer  receive this param but the A scene didn't;

Please it is very confused me ,is there any way to getting the refreshed param in home scene ? T-H-A-N-K-S !

**Comment by aksonov** [comment]
RNRF is not state management solution, could you use Redux or MobX instead?
