### ISSUE TITLE
Drawer left and right button image change dynamically

### ISSUE THREAD

**Issue by gayancliyanage** [aksonov/react-native-router-flux#1970]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.42.0

![screen shot 2017-07-03 at 19 31 07](https://user-images.githubusercontent.com/1917140/27791129-2c39e194-6026-11e7-81f8-33a7700d9c84.png)

I'm trying to update drawer navigation bar right image dynamically where I have used leftButtonImage, rightButtonImage, where once user read all the notification I want to change the button image. 

I could not manage to re-render or update this button image, Is this feature not supported or is there something that I'm missing?

**Comment by aksonov** [comment]
It is not supported. You may pass your class to renderLeftButton and render button differently depending from app state.
