### ISSUE TITLE
componentWillUnMount

### ISSUE THREAD

**Issue by linjinfa** [aksonov/react-native-router-flux#1971]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.41.0
- react-native v0.45.0

Actions.pop()  No call componentWillUnMount & componentDidUnMount

**Comment by abdurrahmanekr** [comment]
It also does not work for `Actions.Page({"type: reset"})`. **version: 3.41.0**

**Comment by aksonov** [comment]
Please try v4 beta #1974
