### ISSUE TITLE
IMPORTANT: v4 beta release is ready (v3 is not supported anymore)

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#1974]
Please check latest 4.0.0-beta.* , Example as demo:
https://github.com/aksonov/react-native-router-flux/tree/v4

V4 Features:
* Based on latest https://reactnavigation.org API
* Separated navigation logic from presentation. You may change now navigation state directly from your business logic code - stores/reducers/etc. navigationStore
* Built-in state machine (former `Switch` replacement) - each ‘scene’ has `onEnter`/`onExit` handlers.
* MobX-powered, all used scenes are wrapped as 'observer' automatically. You may subscribe to `navigationStore` (former `Actions`), observe current navigation state, etc. If you are using Redux, you still could pass your reducer factory to `createReducer` param for Router.
* Flexible nav bar customization, that is not allowed by react navigation right now:
https://github.com/react-community/react-navigation/issues/779
* Built-in reactnavigation drawer support (use `drawer` attribute for `Scene` and `contentComponent` to use your own `Drawer`)
* 'Lightbox' support (used by popups like Error alert within Example project)

Breaking changes (comparing to v3):
1. No duration/panHandlers support - you have to implement custom navigator now instead and pass it as ‘navigator’ prop:
https://reactnavigation.org/docs/navigators/custom

2. No support for partial hiding of tab bar for some tabs because of react navigation bug:
https://github.com/react-community/react-navigation/issues/1584

3. No possibility to skip animation during reset/replace:
https://github.com/react-community/react-navigation/issues/1493

4. `Switch` is removed - you may use `onEnter` (or just `on`) / `onExit` handlers for more flexible logic. They could be async functions. Success termination of `onEnter` will run `success` handler, `failure` handler will be run otherwise. You can pass just state keys to success/failure too. This way you can create very complex state machine and don't use `Switch` or navigation from componentDidMount.

5. getSceneStyle is removed (no needed in v4).

6. Custom reducer (‘createReducer prop for Router) - Redux actions now are passed from React Navigation (‘Navigation/BACK’, ‘Navigation/NAVIGATE’, etc.)

7. Drawer is 'drawer' attribute `Scene` 

8. Modal is 'modal' attribute for `Scene`

9. No flux 'focus' actions - use onEnter/onExit handlers instead.

As you can see React Navigation still contains some issues, but anyway it is more stable than obsolete 'react-native-experimental-navigation' used by v3 now.

Here is link about road to v1 (so you can see all issues at one place):
https://github.com/react-community/react-navigation/issues/723

**Comment by Kennytian** [comment]
Good news, I love you!!

**Comment by hungdev** [comment]
i love you.

**Comment by AlmogRnD** [comment]
How do you install version 4, I'm not seeing a tag or release for it?

**Comment by aksonov** [comment]
It is with 'beta' tag. Latest beta for today is 4.0.0-beta.5

**Comment by southerneer** [comment]
@AlmogRnD in package.json it would be:

`"react-native-router-flux": "^4.0.0-beta.5",`

**Comment by AlmogRnD** [comment]
Thanks this is perfect

**Comment by aksonov** [comment]
Master is replaced with v4 now. v3 is moved to 'v3' branch.

**Comment by guysegal** [comment]
Amazing Work!

I have a few questions though:

1. When is documentation for v4 is expected? Will it contain a tutorial for migration from v3 to v4?

2. if a future release of react-native will break something in v3, will it be fixed in v3 patch releases?

Thanks

**Comment by aksonov** [comment]
@guysegal 
1. We will start working on it next week. Yes, eventually migration tutorial will be created too - actually most API is the same, differences are already listed. Feel free to submit PRs, it is open-source project.

2.  If community will submit PR/patch I will publish new v3 revision.

**Comment by Dictory** [comment]
@aksonov awesome. But i have one q: why mobx in dependencies?

**Comment by aksonov** [comment]
@Dictory mobx manages navigation state and reload navigators after state changes.

**Comment by AlmogRnD** [comment]
Hi off topic have you had a chance to look at my githup issue with redux
been stuck and can't move forward

**Comment by aksonov** [comment]
@AlmogRnD Will do it today.

**Comment by AlmogRnD** [comment]
Thanks appreciate it, getting behind

**Comment by bragur** [comment]
Beautiful! How about further drawer attributes, like drawerPosition, initialRoutename etc.? Where or how would they be declared?

**Comment by aksonov** [comment]
@bragur Check beta.7, you could define it as Scene props for drawer now

**Comment by aksonov** [comment]
My lighting talk proposal about RNRF v4 version:
https://gist.github.com/aksonov/e2d7454421e44b1c4c72214d14053410

**Comment by itinance** [comment]
Can you explain pls the following statement:

> Built-in reactnavigation drawer support (use drawer attribute for Scene and contentComponent to use your own Drawer)

In the API-documentation i've found nothing about it.

Is the new drawer-Attribute simply a boolean setting to true when a scene is managed by a drawer? I understood, that contentCOmponent is the attribute where to pass the final Drawer-Component is it was with "drawer" in v3

**Comment by aksonov** [comment]
@itinance Please check Example project to see new drawer syntax.

**Comment by aksonov** [comment]
I've just updated 'migration' docs about drawer.

**Comment by saimonmoore** [comment]
@aksonov I just upgraded a really simple app from v3 to v4 (4.0.0-beta.17) and navigation just stopped working (no errors or anything in the console). I checked the breaking changes and migration file but I didn't see anything that affected my app so I haven't really changed anything. Not sure how to proceed:
![screenshot from 2017-08-09 10-19-47](https://user-images.githubusercontent.com/494/29112052-d948e7f8-7cec-11e7-818d-f85ca2454f71.png)

(onPress for each song would execute this: `const goToSongScene = () => Actions.song({song: this.props.song});`). The callback executes but the Action call does nothing.

Is there anything there that you can see offhand? Or tips to go about debugging this? 

Very much appreciate any help with this. 
Thanks.

**Comment by saimonmoore** [comment]
Nm thanks, I switched to react-navigation pure

**Comment by tonygriv** [comment]
Tell me, what is better to use for production with redux?

**Comment by waqas19921** [comment]
@aksonov  Please provide a better documentation for v4 as in example The components Lightbox, modal are used and there is no documentation about them and also many changes in props but have nothing documented.

**Comment by tejacoder** [comment]
how to add icon in v4 ?

**Comment by Dictory** [comment]
Anyone can write migration guide like [webpack](https://webpack.js.org/guides/migrating/)

**Comment by aksonov** [comment]
@waqas19921, @Dictory Yes, v4 lacks of documentation and we are trying to improve it. Unfortunately we have lack of maintainers now. 

Guys, this project is open source, feel free to check sources and submit PR for docs. Guys, let's improve open source, not just use it for free.

@tejacoder Check Example project and existing docs. If still not clear, create separate issue.

All, I'm closing this ticket (original aim was just to make announce), create issue (and better with PRs) if any.
