### ISSUE TITLE
NavBar doesn't render with new scene

### ISSUE THREAD

**Issue by igorarkhipenko** [aksonov/react-native-router-flux#1979]
My router is built like this: 
```
export default class Routers extends Component {
  render() {
    return (
      <Router createReducer={reducerCreate}>
        <Scene key="root" hideNavBar>
          <Scene key="main" tabs tabBarStyle={{backgroundColor: '#e75a73'}}>
            <Scene key="coaches"
              component={Coaches} title="Coaches"
              icon={() => TabIcon('supervisor-account')}
            />
            <Scene key="dashboard" initial
              component={Dashboard} title="Dashboard"
              icon={() => TabIcon('dashboard')}
            />
            <Scene key="aboutMe"
              component={MyProfile} title="About me"
              icon={() => TabIcon('person')}
            />
          </Scene>

          <Scene key="auth" 
            component={Auth} title="Auth"
          />
          <Scene key="password"
            component={Password} title="Password Screen"
          />
          <Scene key="training"
            component={Training} title="Training"
          />
          <Scene key="finishedDay" 
            component={FinishedDay} title="Finished Day"
          />
          <Scene key="personalInfo"
            component={PersonalInfo} title="Personal Info"
          />
        </Scene>
      </Router>
    )
  }
}
```
But for some reasons navbar is not rendering in scenes which are not belonged to 'main' scene. Every scene should create its own tabbar and navbar, but why it's not displayed after navigating from tabs scene? Or did I get something wrong in documentation and this is pretty normal behavior? 
Any kind of clue would be really appreciated.

- react-native-router-flux v4.0.0-beta.3
- react-native v0.45.0

**Comment by aksonov** [comment]
You set `hideNavBar` for root, so that navBar will be hidden for all its children.

**Comment by igorarkhipenko** [comment]
@aksonov and when I remove prop this prop from root, scene with tabs has two navbars with empty first one. What am I doing wrong there?

**Comment by aksonov** [comment]
Could you try to set hideNavBar for 'main' only?

**Comment by igorarkhipenko** [comment]
@aksonov sure, I've already tried that before and get this kind of behavior:
![jul-07-2017 15-19-23](https://user-images.githubusercontent.com/24496348/27957614-dc7966f2-6327-11e7-8303-bfa25ea1e5c4.gif)
Can I get rid of this buffer empty navbar when route is changing somehow?

**Comment by aksonov** [comment]
It is how ReactNavigation animation works. Maybe it makes sense to mark 'Training' as 'clone' scene( add clone attribute) This way it will be pushed FROM your internal tabbar stack.

**Comment by igorarkhipenko** [comment]
@aksonov it didn't help, but thank you for trying. At least now I know that the problem is in react-navigation but not in my router.

**Comment by aksonov** [comment]
Actually it is not a bug, it is real iOS-kind of navigation - animation of headers is separate from animations of body. So it needs header of prev scene (that is hidden by your). As I remember react-navigation supports 'android-style' animation as well (when header sticks with body during animation). Maybe you can play a bit with pure react-navigation to get desired behaviour.

**Comment by igorarkhipenko** [comment]
@aksonov but components dispatched from `tabs` are doing right the way I'm looking for. I thought this is the native behavior.
![jul-07-2017 16-11-09](https://user-images.githubusercontent.com/24496348/27959138-f0e6c790-632e-11e7-86c1-0f6259dcad43.gif)
Why does tab scene require additional struggles then?

**Comment by aksonov** [comment]
It happens because 'Training' from your original request is pushed from MAIN, but not from TABS controller. That is why I asked you to use 'clone' for 'Training' screen
