### ISSUE TITLE
Please how can i implement Router in react-native-scrollable-tab-view

### ISSUE THREAD

**Issue by miknonny** [aksonov/react-native-router-flux#198]
I have been able to implement Router on one of my views by going through the example. 
But when i try to nest it on one of the tabs from  [https://github.com/brentvatne/react-native-scrollable-tab-view](url) nothing shows up except for the tabs. I do not see the router component in tabs.

```javascript
...
return (
      <View style={styles.container}>
       <ScrollableTabView initialPage={0} renderTabBar={() => <TabBar />}>
         <ScrollView tabLabel="ios-videocam-outline" style={styles.tabView}>
            <Router hideNavBar={true} wrapRouter={true}>
              ...
            </Router>
         </ScrollView>
      </ScrollableTabView>
     </View>
)
```

thanks.

**Comment by miknonny** [comment]
Realised i had to wrap all in Router. Issue solved.

**Comment by chetankotkar** [comment]
can you post an example .. or any link on how to do it..
