### ISSUE TITLE
TabIcons focused prop

### ISSUE THREAD

**Issue by alexchia** [aksonov/react-native-router-flux#1983]
### Version

- react-native-router-flux v4.0.0-beta 5

In the new beta,
the 'focused' prop is passed to the TabIcon in _renderIcon (src/views/TabView/TabView.js)
but in the example, 'selected' is used. (which was in v3) (Example/components/TabIcon.js)

I take it that 'selected' has been renamed to 'focused'?
If so, the example should be updated.

**Comment by aksonov** [comment]
Good catch! Example was updated (it is master branch now)
