### ISSUE TITLE
Unable to set animation direction

### ISSUE THREAD

**Issue by alexchia** [aksonov/react-native-router-flux#1986]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta5

Previously, 
<Scene ... direction="vertical"/>
could be used to set the direction in which the new scene would be animated when pushed into the stack.

This does not work anymore and I can't seem to find a way in the current framework to change the direction of animation.

**Comment by aksonov** [comment]
`direction` is not supported anymore because underlying reactnavigation API doesn't support it. Unfortunately now RN doesn't allow to have different animations for one stack:
https://github.com/react-community/react-navigation/issues/124

One workaround is to create two nested stacks (`Scene`), one should be `modal` for vertical direction, another is usual, left-to-right direction.

**Comment by aksonov** [comment]
@alexchia Check also Example, Login has different animation there.

**Comment by ajaykumar97** [comment]
You an use your custom transition effects like as follow:

    import StackViewStyleInterpolator from 'react-navigation-stack';
    
    <Scene
    key='main'
    hideNavBar
    transitionConfig={transitionConfig}
    >
    
    ...more scenes
    
    </Scene>
    
    const MyTransitionSpec = ({
        duration: 1000,
        // easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
        // timing: Animated.timing,
    });
    
    const transitionConfig = () => ({
        transitionSpec: MyTransitionSpec,
        // screenInterpolator: StackViewStyleInterpolator.forFadeFromBottomAndroid,
        screenInterpolator: sceneProps => {
            const { layout, position, scene } = sceneProps;
            const { index } = scene;
            const width = layout.initWidth;
    
            //right to left by replacing bottom scene
            // return {
            //     transform: [{
            //         translateX: position.interpolate({
            //             inputRange: [index - 1, index, index + 1],
            //             outputRange: [width, 0, -width],
            //         }),
            //     }]
            // };
    
            const inputRange = [index - 1, index, index + 1];
    
            const opacity = position.interpolate({
                inputRange,
                outputRange: ([0, 1, 0]),
            });
    
            const translateX = position.interpolate({
                inputRange,
                outputRange: ([width, 0, 0]),
            });
    
            return {
                opacity,
                transform: [
                    { translateX }
                ],
            };
    
            //from center to corners
            // const inputRange = [index - 1, index, index + 1];
            // const opacity = position.interpolate({
            //     inputRange,
            //     outputRange: [0.8, 1, 1],
            // });
    
            // const scaleY = position.interpolate({
            //     inputRange,
            //     outputRange: ([0.8, 1, 1]),
            // });
    
            // return {
            //     opacity,
            //     transform: [
            //         { scaleY }
            //     ]
            // };
        }
    });

**Comment by kalraneeraj24550** [comment]
thanks sir, sir will this only work in root scene . if i want to have this transition only to particular screen. that not working. but i apply transition config to root scene only then it is working.


   <Router
    
      >
        <Scene
          key="root"
          hideNavBar
          transitionConfig={transitionConfig}      
        >
          <Scene key="SplashScreen" component={SplashScreen} hideNavBar />
          <Scene key="LandingScreen" component={LandingScreen} hideNavBar
          transitionConfig={transitionConfig}
          />
          <Scene key="Login" component={Login} hideNavBar
          />
          <Scene key="SignUp" component={SignUp} hideNavBar
          />
          <Scene key="ForgotPassword" component={ForgotPassword} hideNavBar />
          <Scene key="EditProfile" component={EditProfile} hideNavBar />
</Scene>
</Router
