### ISSUE TITLE
Parent scene component visible in inherited scenes

### ISSUE THREAD

**Issue by xahon** [aksonov/react-native-router-flux#1988]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4
- react-native v0.45.1

Is there a way to embed inherited scenes into parent, like  
```JSX
<Scene
   key='tab_parent'
   component={ ParentComponent }
>
   <Scene
      key='tab_1'
      component={ Comp1 }
   >
   <Scene
      key='tab_2'
      component={ Comp2 }
   >
</Scene>
```
  
_parent_component.js_
```JavaScript
export default class Parent extends Component {
   render () {
      return (
         <View>
            <CustomHeader />
            <CustomTabManipulator />
            <InheritSceneReference />
         </View>
      )
   }
}
```

I haven't found in documentation how to create custom header, custom tab switcher and refence to inherited scene.

How can i create something like this?
![screenshot from 2017-07-08 16-52-23](https://user-images.githubusercontent.com/18731681/27985745-c09f06b8-6434-11e7-88df-963f9345b056.png)

**Comment by aksonov** [comment]
You need to create custom navigator and pass it as `navigator` prop to parent scene.
Please check Custom Navigators section within https://reactnavigation.org <https://reactnavigation.org/>

**Comment by aksonov** [comment]
Also it is probably could be achieved with two navbars. One navbar belongs to first container, another to second (`tabs`).

Please check reactnavigation docs, v4 just creates needed hierarchy of Stack/Tab/Drawer navigators from defined Scenes.

**Comment by xahon** [comment]
There is not explained how to create custom tab buttons in documentation

**Comment by aksonov** [comment]
Please create separate issue for it and check reactnavigation docs - does it provide API for it or not. If so, then RNRF probably support it as well - Router.js passes all props as TabNavigator second param (i.e. `config`)
