### ISSUE TITLE
Navbar properties not working in v4

### ISSUE THREAD

**Issue by jaumebosch** [aksonov/react-native-router-flux#1991]
Almost migrated to v4! great job!

but I'm unable to use this properties for navBar

  drawerImage={require('../img/burger.png')}  -> not working
  navigationBarStyle={[STYLES.navBar]}  -> this one works
  navigationBarTitleImage={require('../img/logo.png')}  -> not working
  navigationBarTitleImageStyle={[STYLES.navBarLogo]} -> not working

**Comment by aksonov** [comment]
@jaumebosch Thanks for the feedback. Will add these properties soon.

**Comment by jaumebosch** [comment]
Keep informed, I'll do the testing :D

**Comment by aksonov** [comment]
And, of course, PR would be welcome if you want to speed up things. There is nothing difficult, you maybe check how other properties are passed.

For drawerImage you may set leftImage directly for now, you may check Example project.

**Comment by aksonov** [comment]
Please check latest beta.7

**Comment by jaumebosch** [comment]
tested on beta7

navigationBarStyle={[STYLES.navBar]} -> working
navigationBarTitleImage={require('../img/logo.png')} -> working!!
navigationBarTitleImageStyle={[STYLES.navBarLogo]} -> working!!
drawerImage={require('../img/burger.png')} -> not working

I've notice on beta6 that the drawerImage import on navBar.js isn't used anywhere

**Comment by igorarkhipenko** [comment]
Seems like `leftButtonTextStyle` and `backButtonTextStyle` props don't work either. Can someone approve that?

**Comment by aksonov** [comment]
@jaumebosch `drawerImage` should work, I've just checked:
` <Scene key="drawer" drawer contentComponent={TabView} drawerImage={require('./images/back_chevron.png')} >`
I see 'chevron' instead of 'burger'
Maybe you didn't set it for drawer Scene but for inner tabs?

**Comment by jaumebosch** [comment]
yep! I was setting once per scene, instead in the drawer scene.
Almost perfect!, but the icon is too low, is there any way to pass a "drawerImageStyle" ??

**Comment by aksonov** [comment]
Was it supported within v3? Maybe you could list other missed nav bar properties too there.

**Comment by jaumebosch** [comment]
you're right
I've check again on V3 documentation and I can use "leftButtonIconStyle", which also applies to drawerImage

**Comment by jaumebosch** [comment]
I think we can close it, everything resolved!
