### ISSUE TITLE
Unhandled JS Exception: _reactNativeRouterFlux.Actions.create is not a function

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#1992]
Hi, 
I'm using the latest version, version 4 and I'm getting the following error 

Unhandled JS Exception: _reactNativeRouterFlux.Actions.create is not a function

I'm trying to set up routing with redux, I'm sure I'm doing something wrong. 

My router 
```
export const Scenes = Actions.create(
    <Router>
    <Scene key='root'>
        <Scene key="login"
               component={Login}
               title="Login"
               initial
        />
    </Scene>
    </Router>
);

```

app/index.js

```
import { Scenes } from "../app/config/Router";
render() {
        return (
            <Provider store={store} >
                <ConnectedRouter scenes={Scenes} />
            </Provider>
        );
    }
```

**Comment by aksonov** [comment]
Sorry, I will add this to 'Breaking Changes for v4'. Could you use another syntax to define routes - without Actions.create, just <Router> as component. Check Example for more details.

**Comment by aksonov** [comment]
Added note about `Actions.create` to README.md

**Comment by AlmogRnD** [comment]
I did that and now I'm getting the following error "Failed prop type: Invalid prop `children` of type `array` supplied to `Provider`, expected a single ReactElement." 

I understand that provider needs to wrap everything 


Here is my update app index.js file 
```
render() {
        return (
            <Provider store={store} >
                /* Breaking changes with react-native-router-flux all
                   routes need to be here and not in a separate routing file, check back for support.
                */
                <Router>
                    <Scene key="root">
                        <Scene key="login" component={Login} />
                        <Scene key="ResetPassword" component={ResetPassword} />
                    </Scene>
                </Router>
            </Provider>
        );
    }
```
