### ISSUE TITLE
Is it possible to pass component with props in Scene?

### ISSUE THREAD

**Issue by xahon** [aksonov/react-native-router-flux#1993]
Is this possible to pass component property in `Scene` like `<Component prop1={ 'someval' } />` ?  
Or there is exist another approach?

**Comment by aksonov** [comment]
Yes, it should work! Please check

**Comment by xahon** [comment]
When i call `Actions.nameOfInnerScene` nothing occurs

**Comment by aksonov** [comment]
It is function, not property. Fork Example and show your problem
