### ISSUE TITLE
Mobx enabled useStrict

### ISSUE THREAD

**Issue by astulip** [aksonov/react-native-router-flux#1994]
[mobx] Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: NavigationStore@2._state

**Comment by aksonov** [comment]
Thanks, will work on it. Disable strict-mode for a while.

**Comment by astulip** [comment]
OK

**Comment by aksonov** [comment]
Please check latest branch

**Comment by astulip** [comment]
Hard work, it is already possible.

**Comment by astulip** [comment]
console.error: "Error handling:Error: [mobx] Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: NavigationStore@4._onEnterHandlerExecuted"
