### ISSUE TITLE
How to use DefaultRenderer?

### ISSUE THREAD

**Issue by xahon** [aksonov/react-native-router-flux#1995]
Is defaultrenderer a container for inner scenes?

         MasterScene                ( Component={ MasterSceneComponent } )  
         |          |  
         V          V  
    InnerScene1    InnerScene2  
    (initial)

If i understand right, MasterScene containing code below...

```JSX
render () {
   return (
      <View>
         <Text>Hello from master scene</Text>
         <DefaultRenderer navigationState={ children[0] } onNavigate={ this.props.onNavigate }  />
      </View>
   )
}
```

will produce merged Master and Inner scene and Inner scene will be within defaultRender?
Without defaultrenderer element my scene won't rendering but with one it renders outside under that element and won't stretch it by its content. What should this element do? There is not enough information about that element in documentation.

**Comment by aksonov** [comment]
Sorry, v3 is not supported, please try v4 and custom navigator for reactnavigation
