### ISSUE TITLE
Tabbar properties not working in V4

### ISSUE THREAD

**Issue by jaumebosch** [aksonov/react-native-router-flux#1996]
I'm unable to have this property working, in v3 worked perfectly

tabBarSelectedItemStyle={STYLES.tabSelected}

Also don't know how to set style for {props.title} which is setted to small fontsize and in the lower half of the tab. In V3 it was setted to the middle of the tab and in normal font size

**Comment by aksonov** [comment]
Will be added as well. Please check https://reactnavigation.org/docs/navigators/tab, TabNavigatorConfig is passed by v4 from your Scene props.

**Comment by aksonov** [comment]
Looks like react-navigation doesn't support something similar to tabBarSelectedItemStyle. Have you tried activeBackgroundColor, inactiveBackgroundColor, etc. ?

**Comment by jaumebosch** [comment]
activeBackgroundColor works, but with tabBarSelectedItemStyle you could also set the active text color.
Another thing we've lost is the that the property "title" now is rendered as a subtitle in small font size at the bottom of the tab. If we don't set an icon, the title must be rendered at the middle of the tab in normal font size

**Comment by AlmogRnD** [comment]
I'm having issues setting icons per tab, does anyone have an example of this with V4?

**Comment by igorarkhipenko** [comment]
Seems like `leftButtonTextStyle` and `backButtonTextStyle` don't work either as for me. Can someone approve that?

**Comment by aksonov** [comment]
@AlmogRnD Check Example - you could pass your React element as `icon` for tabs.

**Comment by jaumebosch** [comment]
But if you don't set an icon, the text must be centered and bigger, mustn't it?

**Comment by aksonov** [comment]
I don't know what is the must, it is default ReactNavigation behaviour. As I see it allows to pass your own tabbar component, just check. Maybe you could help with docs about Tabbar customization with v4.

**Comment by aksonov** [comment]
Closing it because original issue was resolved.
