### ISSUE TITLE
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Provider`, expected a single ReactElement.

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#1998]
Using V4 with Redux getting the following error "Failed prop type: Invalid prop `children` of type `array` supplied to `Provider`, expected a single ReactElement." 

The code is based off the doc/example 

```
const ConnectedRouter = connect()(Router);

render() {
        return (
            <Provider store={store} >
                /* Breaking changes with react-native-router-flux all
                 routes need to be here and not in a separate routing file, check back for support.
                 */
                <ConnectedRouter>
                    <Scene key="root">
                        <Scene key="login" component={Login} initial={true} />
                        <Scene key="ResetPassword" component={ResetPassword} />
                    </Scene>
                </ConnectedRouter>
            </Provider>
        );
    }
}
```

**Comment by aksonov** [comment]
Nice, try to remove that comment about 'Breaking changes'! I've just added redux to Example without any problem, but reproduce your issue only after adding comment as child for Provider. Weird redux issue.


P.S. You may want to switch MobX ;)

**Comment by AlmogRnD** [comment]
That's crazy never even thought about that. MobX looks good but I need redux they have redux offline which I need thanks for the quick support
