### ISSUE TITLE
No transition option

### ISSUE THREAD

**Issue by tylermcginnis** [aksonov/react-native-router-flux#2]
Is there a way to change routes without having a transition animation? I don't want a slideRight or slideFromBottom. I just want the new router to appear.

**Comment by aksonov** [comment]
It should be done now with 0.0.9 version, please check - you just don't need to pass sceneConfig parameter to avoid animation, check updated Example project.

**Comment by tylermcginnis** [comment]
Awesome. Thanks for the quick update!
