### ISSUE TITLE
Example of calling Action from a fucntion?

### ISSUE THREAD

**Issue by CoreSoft2** [aksonov/react-native-router-flux#20]
do you have a working example of action (simple ones will do like pop) from a page?

**Comment by aksonov** [comment]
Just Actions.NAME where NAME is action name attribute defined as for Route or Action element, and its schema="popup"

**Comment by aksonov** [comment]
Check example project from the repository

**Comment by CoreSoft2** [comment]
Found answer, Actions.NAME only works onpress= .... it does nothing, if you can call from your own function. 

if you have own function, & processing, you have to use Actions.NAME(this);

**Comment by nagendrakk** [comment]
how to pass data while using action in own function

**Comment by aksonov** [comment]
Have you tried Actions.name(DATA)  ?

**Comment by nagendrakk** [comment]
I tried like this, Actions.name(this,data)

**Comment by aksonov** [comment]
No, it is not correct, check examples.

**Comment by nagendrakk** [comment]
i'm unable see navbar in the app,I have followed the steps mentioned in the begining page.

**Comment by aksonov** [comment]
Could you check demo, where is no navbar?
