### ISSUE TITLE
this.props.navigationState is undefined

### ISSUE THREAD

**Issue by xahon** [aksonov/react-native-router-flux#2000]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration

```JSX
<Scene
  key='main'
  component={ MainScreen }
  hideNavBar={ true }
  type='reset'
  tabs={ true }
>
  <Scene
    key='contacts'
    component={ ContactsView }
    initial={ true }
  />
  <Scene
    key='projects'
    component={ ProjectsView }
  />
</Scene>
```

Inside `MainScreen#render()` this.props.navigationState is undefined, why?

rnrf: 4.0.0-beta.6

**Comment by aksonov** [comment]
You may use props.navigation.state instead. I will add navigationState for backward compartibility soon.

**Comment by xahon** [comment]
In this path the field `children` is missing

**Comment by aksonov** [comment]
Do you mean this.props.navigationState.children? Yes, it is replaced to this.props.navigation.state.routes. Will add it to 'Breaking changes'.

**Comment by xahon** [comment]
Yes, i mean that but there is no `routes` field 
![image](https://user-images.githubusercontent.com/18731681/28005412-c75b077c-658d-11e7-9519-feada49428f9.png)

**Comment by aksonov** [comment]
Could you check `navigation.routes` ?

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/28005588-cec4e662-658e-11e7-8b72-b6a756d719d9.png)

**Comment by aksonov** [comment]
It is weird, let me check.

**Comment by aksonov** [comment]
There is no 'children' because Router interpret 'main' as leaf (because 'component' is defined). So V4 accepts `children` OR `component` prop.

If you want to use custom tab container you have to use custom Navigator:
https://reactnavigation.org/docs/navigators/custom

**Comment by prashoor-infobeans** [comment]
To be honest, I am not sure what the last comment means.

Can you elaborate more @aksonov ?

**Comment by amang8662** [comment]
Yeah, even I don't understand the meaning behind the last comment @aksonov . Can you please explain it?

**Comment by aksonov** [comment]
Original code was taken from v3 and applied to v4 that is wrong. Starting from v4 'container' scenes (like tabs, stack, etc.) cannot have 'component' prop but 'contentComponent' instead

**Comment by amang8662** [comment]
I am trying to implement react-native-drawer in rnrf but facing following error.
![capture1](https://user-images.githubusercontent.com/24224603/35914786-8fb7d068-0c2a-11e8-9ef5-529f76a1caec.PNG)

the props i am gettting are

![capture](https://user-images.githubusercontent.com/24224603/35914822-bf3f8f6a-0c2a-11e8-8e2f-cff413c3d33c.PNG)

My Code is:
**NavigationDrawer.js**
![capture3](https://user-images.githubusercontent.com/24224603/35915565-664854ac-0c2d-11e8-8083-0ebd7b28aad3.PNG)

**Routes.js**

![capture2](https://user-images.githubusercontent.com/24224603/35915516-33634af6-0c2d-11e8-849e-cd94aa7b802e.PNG)


What should i pass to DefaultRenderer component to make it work?

**Comment by Blapi** [comment]
Not really sure about what is your issue here but as you can see in your logs, you have no `children` defined.

As a workaround, you may use `Actions._state` where `routes` is defined :

![screenshot from 2018-02-07 13-32-40](https://user-images.githubusercontent.com/3853597/35916846-15af5822-0c0c-11e8-96a0-92c9d74b42b0.png)

**Comment by amang8662** [comment]
I want to know about the parameters to be passed to navigationState & onNavigate props of DefaultRenderer. Data i'm getting from Actions._state in NavigationDrawer.js

![capture4](https://user-images.githubusercontent.com/24224603/35917352-ccfcb200-0c33-11e8-8071-5dedf46c01a2.PNG)

**Comment by temadev** [comment]
Stuck on the same place. I think we have to extend somehow children[0] by data from Actions._state, but have no idea how can we do that trick.

**Comment by prashoor-dev** [comment]
@Dgs-asohail4 RNRF has now its own drawer.
react-native-drawer can be removed and simple RNRF's drawer can be used.

It's easy to use and manage. You might need to refactor your routing file though.

And this.props.navigationState is now available as this.props.navigation.state.

**Comment by burhanuddin-emaster** [comment]
I have updated with RN-v0.59.8 and I am also not getting children key, can you please tell me how we can achieve that ?
