### ISSUE TITLE
Correct way to setup tabs and drawer, showing two headers 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2002]
Hi, first so far this is a really great lib. I'm working off the example which is a bit hard I used to more docs. 

I'm trying to setup the following navigation structure 
Public scenes 
 - Login
 - ResetPassword 
Main scenes should have tabs at the bottom 
 - Home
    - Teams (part of home)
  - Photos 

Right now I have the following code 
```
<Provider store={store} >
                <ConnectedRouter>
                    <Scene key="root">
                        <Scene key="login" component={Login} initial={true} title={'Login'} />
                        <Scene key="ResetPassword" component={ResetPassword} title={'Reset Password'} />
                        <Scene key="tabBar" tabs>
                            <Scene key='Home' component={Home} title='Home' initial={true} icon={TabIcon}  />
                        </Scene>
                    </Scene>
                </ConnectedRouter>
            </Provider>
```

But as you can see I'm getting the login header which should not show and also the back button should not work for the main/home scene 

<img width="401" alt="screen shot 2017-07-10 at 12 49 57 am" src="https://user-images.githubusercontent.com/169507/28007806-bb257b74-6509-11e7-87ef-492870cbe98b.png">

**Comment by aksonov** [comment]
Just use `hideNavBar`, `hideTabBar` to hide navbar/tabbar

**Comment by AlmogRnD** [comment]
That does not solve the issue if I have hideNavBar={true} it hides the login and home. On the home scene/view, I should just see the home header without the back button.

**Comment by aksonov** [comment]
No, it should not. Please check Example, TabBar.

**Comment by AlmogRnD** [comment]
To clarify by example TapBar you mean - https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js

**Comment by aksonov** [comment]
yes

**Comment by AlmogRnD** [comment]
Thanks, I got it I had the hideNavBar={true} on the tabs but on the main component but I can still use gesture to gesture back the login back is there a way to disable that?

**Comment by aksonov** [comment]
Will implement for next version, please rename ticket or create new one.

**Comment by AlmogRnD** [comment]
@aksonov I just tested gestureEnabled={false} and it's not working

**Comment by aksonov** [comment]
Check Example tabs
