### ISSUE TITLE
v4 Actions.popTo() is not function   when I run Example

### ISSUE THREAD

**Issue by shiqian123** [aksonov/react-native-router-flux#2004]
when I in login3 page click go Root  is error
<img width="355" alt="fe734203-f588-4ec7-9dab-898814941ee2" src="https://user-images.githubusercontent.com/9497069/28022680-6f8b0cbe-65be-11e7-94f0-cd6d59b4df47.png">

**Comment by aksonov** [comment]
Please check your version, it should be fixed within 4.0.0-beta.7

**Comment by shiqian123** [comment]
@aksonov  when I used 4.0.0-beta.7 it is can login3 to login ,but  login3 to Root ,it is still error,it is died,
<img width="774" alt="3b39d4b2-aacb-4b45-8f41-ab16026dc123" src="https://user-images.githubusercontent.com/9497069/28045718-61295380-6611-11e7-9c22-9471231a81e3.png">  
   "react-native": "0.44.0",
    "react-native-router-flux": "^4.0.0-beta.7",
    "react-navigation": "^1.0.0-beta.11"

**Comment by AlmogRnD** [comment]
+1 but I'm on beta 6, couldn't update for some reason

**Comment by aksonov** [comment]
@shiqian123 Please update Example too, there was error - popToRoot should use `popTo('launch`)` not `popTo('root')`
