### ISSUE TITLE
disabling panHandlers

### ISSUE THREAD

**Issue by alexchia** [aksonov/react-native-router-flux#2005]
Can you provide some guidance on how to disable panHandlers in this new version of react-native-router-flux?

The current swipe right to dismiss feature is very disruptive to my app flow.

If you could provide some guidance on how to implement a CustomNavigator etc, I would be glad to submit a PR to show this could be done in Example.

**Comment by aksonov** [comment]
panHandlers set to null should work for beta.7

**Comment by alexchia** [comment]
okay i can confirm that works.
please include in future documentation.
