### ISSUE TITLE
undefined is not an ovject (evaluating '_react.PropTypes.string')

### ISSUE THREAD

**Issue by MiLeung** [aksonov/react-native-router-flux#2009]
I get this error and it points to this node module in src/Scene.js

I looked at the file and it's still using React.PropTypes and not import PropTypes from prop-types.  That might be part of the problem.

**Comment by aksonov** [comment]
Please check 4.0.0-beta.7, I don't see usage of React.PropTypes

**Comment by LuckySambial** [comment]
I am facing same issue and don't have any Idea how I can resolve it, could you please explain me why it's happening ?
