### ISSUE TITLE
when i  created a WiFi hotspot,  and my tabBar  was pushed down

### ISSUE THREAD

**Issue by zhan1128** [aksonov/react-native-router-flux#2010]
![Uploading WX20170710-193720@2x.png…]()
when i  create a WiFi hotspot,  and my tabBar  was pushed down！  like the photo。
can u give some advice. thanks
dependencies:
"react": "16.0.0-alpha.3",
"react-native": "0.43.4",
 "react-native-router-flux": "3.37.0",

**Comment by aksonov** [comment]
v3 is not supported anymore, sorry.
