### ISSUE TITLE
Drawer children is not defined

### ISSUE THREAD

**Issue by Venumteam** [aksonov/react-native-router-flux#2011]
Hey, guys, I was faced with the troubles with Drawer on v4 beta 7, Drawer children don't exist anymore like it was in v3 with state.children. For now this.props don't contain react children.
Here is my scenes structure:
https://pastebin.com/szy2bBHp

**Comment by aksonov** [comment]
@Venumteam Please check 'Breaking changes' section.

**Comment by quarryman** [comment]
@aksonov Are you referencing this change?
>>Container scenes (that has children) cannot have component (or it will be considered as child!). If you want to customize containers, use react navigation custom navigators and pass it as navigator prop.

**Comment by aksonov** [comment]
Yes

**Comment by quarryman** [comment]
@aksonov Is there a chance you guys will give an example of usage?

Given we have a structure
<Scene key='drawer' type={} component={NavigationDrawer} open={false}>
  <Scene />
  <Scene />
</Scene>

NavigationDrawer component was rendering children.
What must it render since new version?

**Comment by aksonov** [comment]
v4 uses built-in react navigation Drawer navigator. Please use `contentComponent` for SideMenu component, remove `component` attribute. Please check docs about DrawerNavigator from ReactNavigation.

**Comment by Venumteam** [comment]
this helps https://github.com/aksonov/react-native-router-flux/blob/v4/Example/Example.js
thanks for your feedback
