### ISSUE TITLE
Crash when hiding the tabbar

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2012]
I'm thinking of migrating my v3 project to v4 and I was looking at the demo. 
I discovered that if I hid the tabbar then using the "switch to tab" causes a crash.

undefined is not a an object (evaluating component.setNativeProps

Here is a branch with the change I did. 
https://github.com/compojoom/react-native-router-flux/tree/crash-undefined

In my case I want to hide the tabbar and render one myself.

**Comment by aksonov** [comment]
Is it similar to https://github.com/react-community/react-navigation/issues/1584 ?

**Comment by compojoom** [comment]
Ah ok. Seems to be the same issue.

**Comment by nishiltamboli** [comment]
I had similar issue. I was switching to **router flux** from **react navigation**. I then completely removed react navigation and reinstalled router flux and cleaned watchman logs. You may as well try uninstalling the app if yours is a case similar to mine. I did that also for safer side. And then, this error went away without any change in code. Thanks @aksonov for this library. I have always admired router flux and the work you put in. And good job with clearing soo many open issues in such less time! Appreciate it.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
