### ISSUE TITLE
TabBarIcon can not call class as a funtion

### ISSUE THREAD

**Issue by colorfulberry** [aksonov/react-native-router-flux#2013]
![image](https://user-images.githubusercontent.com/8124046/28100788-da35be40-66f6-11e7-8d1c-0e271e8173a2.png)
code 
```
export default class TabIcon extends Component {
  constructor(props) {
    super(props)
    this.state = {
      TbIcon: '',
      TbIconActive: ''
    }
  }

  render(){
    return <Text
      style={{color: props.selected ? 'red' : 'black'}}
    >TAB
      {props.title}
    </Text>
  }

};
```
And if we will not support an class with TabIcon?

**Comment by aksonov** [comment]
Use stateless function instead. It seems requirement from ReactNavigation and I agree - icon should not maintain any state.
