### ISSUE TITLE
Navbar props don't affect on back button style

### ISSUE THREAD

**Issue by igorarkhipenko** [aksonov/react-native-router-flux#2014]
Neither `leftButtonTextStyle` nor `backButtonTextStyle` do make any changes for me, but titleStyle does. Can someone approve that behavior?
```
<Scene key="root" 
  leftButtonTextStyle={{ tintColor: 'red' }} 
  backButtonTextStyle={{ tintColor:'red'}} 
  titleStyle={{color: 'white'}
</Scene>
```

**Comment by aksonov** [comment]
@igorarkhipenko Just try 'color', not 'tintColor' because it is usual style applied to Text element.

**Comment by igorarkhipenko** [comment]
@aksonov I forgot to mention that I've tried 'color' before as well as the same prop assigned to `rightButtonTextStyle` with component `rightButton={<Text>right</Text>}`.
<img width="313" alt="screen shot 2017-07-12 at 10 07 08 am" src="https://user-images.githubusercontent.com/24496348/28105821-ebbf3748-66e9-11e7-933b-6eabdf4403e2.png">
Am I doing something completely wrong?

**Comment by aksonov** [comment]
1. I've just set `leftButtonTextStyle={{ color: 'red' }} backButtonTextStyle={{ color:'red' }}` to Example 'root' element and definitely see red colours for Login 'Cancel' button.

2. Sure it will not work because rightButton is complete component for right Button. Try `rightTitle` instead.

**Comment by rohitgoyal** [comment]
@aksonov The back button just gets disappeared when i try to set backButtonTextStyle for a scene. The issue might be with using drawer.

```
<Scene key="root">
        <Scene key="drawer" drawer contentComponent={SideMenu}
          drawerOpenRoute= 'DrawerOpen'
          drawerCloseRoute= 'DrawerClose'
          drawerToggleRoute= 'DrawerToggle'
          hideNavBar={true}
          drawerImage={require('../images/img1.jpg')}
        >
          <Scene key="main" navTransparent={true}>
            <Scene key="home" component={Home} />
            <Scene key="details" component={Details} hideDrawerButton backButtonTextStyle={{color:'black'}} />
          </Scene>
        </Scene>
      </Scene>
```

But with this the back button just gets disappeared instead of changing color to black. If i remove the backButtonTextStyle prop then back button is shown in blue color. Any ideas?

**Comment by whayler1** [comment]
I'm having the same issue

**Comment by haratmalli** [comment]
> @aksonov The back button just gets disappeared when i try to set backButtonTextStyle for a scene. The issue might be with using drawer.
> 
> ```
> <Scene key="root">
>         <Scene key="drawer" drawer contentComponent={SideMenu}
>           drawerOpenRoute= 'DrawerOpen'
>           drawerCloseRoute= 'DrawerClose'
>           drawerToggleRoute= 'DrawerToggle'
>           hideNavBar={true}
>           drawerImage={require('../images/img1.jpg')}
>         >
>           <Scene key="main" navTransparent={true}>
>             <Scene key="home" component={Home} />
>             <Scene key="details" component={Details} hideDrawerButton backButtonTextStyle={{color:'black'}} />
>           </Scene>
>         </Scene>
>       </Scene>
> ```
> 
> But with this the back button just gets disappeared instead of changing color to black. If i remove the backButtonTextStyle prop then back button is shown in blue color. Any ideas?

thanks for `hideDrawerButton`
