### ISSUE TITLE
actions[type] is not a function

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2017]
I have this code with v3:
```
<Scene key="companies"
                           initial={loggedIn ? true : false}
                           hideNavBar={true} {...styles} type={ActionConst.BACK} component={Companies}/>

```

and I have a scene that calls Actions.companies({refresh: { goBack: true }})

that was working fine on v3, but on v4 I get actions[type] is not a function.

If I remove type={ActionConst.BACK}, then I no longer get the error, but the scene transitions from the wrong side. It seems like it's being added on the stack, but it should behave like pop() - removing the current scene to show the one below.

**Comment by quarryman** [comment]
try using type={'back'} instead.

**Comment by aksonov** [comment]
Not 'back', but 'pop'. I'm not sure about support of 'refresh' inside pop. Could you just raise two actions?

**Comment by compojoom** [comment]
yep, it's pop and not back. But if I do use type={'pop'} navigating to this scene behaves like pop -> it just pops the last scene from the stack. 

And since on the scene I am I have a tabbar -> when you navigate between the tabs and then hit the actions.companies() buttons you first switch between the tabs and once they are off the stack you navigate back to hte companies page. And I just want to directly transition back to companies no matter how many screens there are on the stack. 

I tried popTo, but it seems to cause some endless loop or so... The app freezes :)

**Comment by aksonov** [comment]
You should pass child scene to pop to, not container one.

**Comment by compojoom** [comment]
okaay, so adding type={'popTo'} to the scene seems to work fine. 

Using Actions.popTo({scene: 'companies'}) seems to cause the endless loop

**Comment by aksonov** [comment]
Because 'companies' is not child.

**Comment by compojoom** [comment]
Why does companies need to be a child? It's a parent in this case and I would like to navigate back to the parent?

And what's with refresh now? Can we use it in v4 or not?
```
Actions.companies({
	refresh: {
	  goBack: true
	 }
 })
```
This doesn't seem to pass goBack as property to the previous scene. No matter if I use type={'popTo'} or not. It just doesn't seem to pass the property back to the previous scene. ComponentWillReceiveProps is never fired.

**Comment by aksonov** [comment]
'Companies' is stack. Stack cannot be presented, you always see some child within the stack.
'refresh' inside pop looks a little bit strange, have you tried just two calls - popTo & refresh?

**Comment by compojoom** [comment]
Sorry, I'm lost. I don't understand what you mean with " Stack cannot be presented, you always see some child within the stack."

companies is the first scene in the stack. 
I discovered that I can remove the type={'popTo'} from the scene definition. The way then to popTo this scene is by using
Actions.popTo('companies')
instead of v3 syntax
Actions.popTo({scene: 'companies'})

unfortunatly passing params as second argument doesn't do anything. 

I tried it with 2 calls like this:
```
Actions.popTo('companies');
Actions.companies({wtf: true});
```

wtf was auto added to props.navigation.state.params. So we no longer need to use the refresh object?

**Comment by aksonov** [comment]
Have you tried `Actions.popTo('companies');Actions.refresh({data});` ?

**Comment by compojoom** [comment]
Yep,that also seems to work. 
Are those 2 the same in behavior? Calling refresh on actions is somehow strange for me as I don't know on which scene the refresh is going to be called.

```
Actions.popTo('companies');
Actions.refresh({data}); 
```

```
Actions.popTo('companies');
Actions.companies({data});
```

**Comment by aksonov** [comment]
On current scene. After `popTo` currentScene is changed.
