### ISSUE TITLE
Constant rerendering of scenes in the stack. 

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2018]
I just noticed that if you a transitioning to a new scene the re-render method of your component will be called for each component in the navigation stack.

This can easily be reproduced. Just add 
console.log('rerender: launch'); 
to the launch.js file in the example and 
console.log('rerender: login');
to the login.js

then navigate around. You'll notice that with each navigation the rererender: login will be output to the console.

If you move to the login screen and then navigate further to login2, 3 etc you'll always see both launch and login re-rendering. This seems to make the navigation to the different scenes pretty slow.

**Comment by aksonov** [comment]
Could you please check that PR:
https://github.com/aksonov/react-native-router-flux/pull/2015 ?

**Comment by compojoom** [comment]
wow! my app seems fast again! Thanks, it seems that the re-rendering issue is gone.
