### ISSUE TITLE
Using modal properly

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2020]
Hey guys, great work you've done on router flux. It's amazing and handy.
I have a simple question based on the new `v4` release.

I'm trying to use the new modal flow. When I set my `root` scene as `modal` and the child as a card, it duplicates the `navbar`. So I tried to hide the navBar and display it on card, but it still hidden on my modal view.

My router:

```
        <Router>
            <Scene key="root" modal hideNavBar={true}>
              <Scene key="home1" card hideNavBar={false}>
                <Scene key="home" component={Home}/>
                <Scene key="home2" component={Home2}/>
              </Scene>
              <Scene key="modal" component={Modal}/>
            </Scene>
          </Router>

```
I already tried to set `hideNavBar={false}` on my modal Scene.  I wasn't lucky.
Any tips? Thanks

**Comment by aksonov** [comment]
Please check Example project. There is modal Login with own navbar.

**Comment by luco** [comment]
Oh, sorry. Thank you.
Now it's working as expected.
