### ISSUE TITLE
Cannot close Modal and Scene at once from inside of the Modal

### ISSUE THREAD

**Issue by mswokk** [aksonov/react-native-router-flux#2022]
I'm using react-native-router-flux : 3.40.1

**Scenario and expected result.**
I have a stacked scene and before pop this scene (using Actions.pop()), 
I show a confirm Dialog using Modal from react-native-router-flux.
On OK press in the Dialog, I want to close Dialog (Modal) and pop the Scene at once.

**Actual result** 
Actions.pop() dismisses the Dialog but not Scene.

**My code structure**
Same with Modal example in https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md

**I tried in the onPress() in the Dialog**
```
// Call twice
Actions.pop();
Actions.pop();
```

```
// Pop with param
Actions.pop(2)
```

```
//Using setTimout()
setTimeout(Actions.pop, 10)
setTimeout(Actions.pop, 1000)
```

```
// Combine upper tries using async 
async()=>{
setTimeout(Actions.pop, 10)
setTimeout(Actions.pop, 1000)
}
```

Am I doing right?

**Comment by aksonov** [comment]
Sorry, v3 is not supported.

**Comment by luco** [comment]
@aksonov How can we achieve this on v4?

**Comment by tendolukwago** [comment]
@aksonov @luco did you ever find an answer to this?

**Comment by mswokk** [comment]
I found workaround in v3.
Just calling `setTimeout(Actions.pop) ` works.
In my original post, I made some mistakes. 
`setTimeout(Action.pop, N)` should works.
