### ISSUE TITLE
Navigation 'back' button won't render on Android for scenes with 'back' attribute.

### ISSUE THREAD

**Issue by quarryman** [aksonov/react-native-router-flux#2023]
Issue can be reproduced on Example project.

Given we have scene with 'back' attribute passed
`<Scene key="echo" back clone component={EchoView} getTitle={({navigation}) => navigation.state.key}/>`

Router renders 'back' button for iOS (top left corner)

<img width="316" alt="screen shot 2017-07-13 at 11 07 43 am" src="https://user-images.githubusercontent.com/1093040/28156958-7bdf5e2e-67bd-11e7-8c42-9e330382aaa5.png">

And doesn't render back button for Android (back button missing)

![andoid-back-button-missing](https://user-images.githubusercontent.com/1093040/28157365-ed51d8ba-67be-11e7-9d9b-4cc78d11da77.png)

Initially found on other project and reproduced with Example to consider it bug.

**Comment by aksonov** [comment]
@quarryman Sorry, I'm currently working with iOS app only. Could you debug and find where is the problem (probably within NavBar.js)? Maybe because of upper tabbar and absolute positioning?

**Comment by quarryman** [comment]
@aksonov I will take a look and tell if i can narrow it down.

**Comment by aksonov** [comment]
@quarryman Could you check latest master now?

**Comment by quarryman** [comment]
@aksonov I can not confirm this has been fixed for Android on master. 
Looking into PR now

**Comment by quarryman** [comment]
PR merged fixed the issue.
Still it was merged to master and Example rely on beta.xxx currently.

**Comment by buncismamen** [comment]
how to use master in my project?

I've tried with yarn add https://github.com/aksonov/react-native-router-flux.git#master but it keep using the latest release

**Comment by aksonov** [comment]
It is because of yarn cache. Pass latest commit ID instead of 'master'

**Comment by buncismamen** [comment]
I put the commit ID 
`yarn add https://github.com/aksonov/react-native-router-flux.git#d4fff5036653e723a697f8ab28d0ce9ee387ffb8`

and got this 
```
 Warning: Installed version 4.0.0-beta.11 of 'react-native-router-flux' does not satisfy required version https://github.com/aksonov/react-native-router-flux.git#d4fff5036653e723a697f8ab28d0ce9ee387ffb8

If there is an issue running your project, please run `npm install` in /home/user/nav-playground and restart.
```
