### ISSUE TITLE
Tabbar Navigation always goes back to the last screen

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2026]
I'm version 8 beta 
I have a tabbar 
Tab 1
 - Home 
 - Teams 
Tab 2 
  - Photos

If I'm on the teams view and move onto the photos view and then click on the tab 1 I'm taken to the teams view the last view I was on, but I should be taken to the home view which is the first view for tab 1. 

![bug](https://user-images.githubusercontent.com/169507/28169040-f3d35cfa-6795-11e7-8ed7-265b187a3034.gif)

**Comment by aksonov** [comment]
It seem ReactNavigation behaviour, but maybe I didn't understand issue.  I want to repeat, screenshots only are not helpful for me, I need runnable project also.

**Comment by AlmogRnD** [comment]
Possible it's a ReactNavigation behavior but I didn't have this issue when I using React Navigation.  
Let me explain 
I have the home tab which has to two internal pages home and teams if I navigate to teams and then to the photos tabs and then click the home tab at the bottom the app goes or loads the teams component i.e. the last I was on it should load the home view.

**Comment by aksonov** [comment]
It is about 'backBehavior' for TabNavigator. It is set to 'none' by RNRF:
https://reactnavigation.org/docs/navigators/tab
Maybe I will remove 'none' and use default value instead ('initialRoute') for beta.9

**Comment by AlmogRnD** [comment]
I would suggest using initialRoute I believe that is more of the expected behavior

**Comment by aksonov** [comment]
I've removed 'none' as back behaviour but don't see any changes. Maybe you could check ReactNavigation itself for desired behaviour.
