### ISSUE TITLE
How to update TabBar icon on V4?

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2027]
I have a AsyncStorage which gives me info that I want to update on my Scene TabBar Icon.
How can I do it? Currently I set my TabBar item this way:

```
static navigationOptions = {
	    tabBarIcon: ({ tintColor }) => (
	     	<View style={{backgroundColor: 'transparent', borderWidth: 2, borderColor: AppStyles.colors.primary, padding: 1, borderRadius: 18}}>
	     	     	<Text>Test</Text>
	     	</View>
	    ),
	};
```

Let's suppose I want to change the value, or yet, render an Image. How can I update?
Thanks

**Comment by aksonov** [comment]
connect it to redux or mobx observer and change it when do you need. It is not about RNRF, even not about React Navigation...
