### ISSUE TITLE
Color of Back Button Arrow

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2028]
I'm trying to change the color of back button arrow, but still not getting it.

```
var sceneConfig = {
  navigationBarStyle: {backgroundColor: 'black'},
  headerTitleStyle: {
      color: 'white',
      fontWeight: '500'
  },
  headerBackTitleStyle: {
    color: 'white',
  },
  headerTintColor: 'white',
  cardStyle: {
        backgroundColor: 'white'
  }
}
```
The color of back button label I had success, but not on arrow.

Tips?

**Comment by aksonov** [comment]
Please check beta.9

**Comment by luco** [comment]
@aksonov Thanks a lot!

**Comment by luco** [comment]
@aksonov Just updated. Tried all the options, but still not getting it:

```
var sceneConfig = {
      navigationBarStyle: {'black'},
      headerTitleStyle: {
          color: 'white',
          fontWeight: '500'
      },
      tintColor: '#fff',
      navBarTintColor: '#fff',
      navBarButtonImageColor: '#fff',
      headerTruncatedBackTitle: 'Voltar',
      headerBackTitleStyle: {
        color: 'white',
      },
      cardStyle: {
            backgroundColor: 'white'
      }
    }
```

**Comment by aksonov** [comment]
Sorry, did it only for right button.
Check now beta.10

**Comment by luco** [comment]
@aksonov Getting this error:

![image](https://user-images.githubusercontent.com/246373/28229745-5df22d6c-68ba-11e7-8994-f4114fbfbdca.png)

**Comment by aksonov** [comment]
Oops, did typo again. Try beta.11

**Comment by luco** [comment]
@aksonov Tried all the options and didn't get it. What's the correct param?

**Comment by aksonov** [comment]
Check Example. I used tintColor

**Comment by luco** [comment]
I tried everything, specially using `tintColor` as you used on the example, but it didn't work.
`
<Router createReducer={reducerCreate} tintColor='yellow'>`

**Comment by aksonov** [comment]
Do you see red color for arrow within Example?

**Comment by luco** [comment]
Yes, I do. But when I try to apply on my Router, it doesn't work. In fact, it works on my modals, but not on my card stack.

**Comment by aksonov** [comment]
Could you reproduce it on Example?

**Comment by luco** [comment]
On example, it works. But not on my project. I'm setting this way:

```
  <Router createReducer={reducerCreate} tintColor='white'>

            <Scene key="modal" modal hideNavBar tintColor='white'>
                <Scene key="root" hideNavBar tintColor='white'>
                  <Scene key="tabbar" 
                  tabs 
                  showLabel={false} 
                  tintColor='white'
                  tabBarComponent={this.tabBarElement}
                  headerBackTitle={'Voltar'}
                  activeTintColor={AppStyles.colors.default}
                 >
```

As you can see, I tried on every element.
![image](https://user-images.githubusercontent.com/246373/28251265-015c1fee-6a50-11e7-87db-558baab20526.png)

**Comment by aksonov** [comment]
Have you tried to set backTitle?

**Comment by luco** [comment]
But backTitle sets the text, right?

**Comment by aksonov** [comment]
Yes, I'm just trying to debug :) maybe you see built in reactnavigation bar but not rnrf one

**Comment by luco** [comment]
I thought as well, so I removed react-navigation from my project and it still not working. It's annoying me.

**Comment by luco** [comment]
I can get the color on inspector:

![image](https://user-images.githubusercontent.com/246373/28251438-63f4af42-6a53-11e7-81a4-be960a0d49ff.png)

**Comment by luco** [comment]
I managed to work. Digging into your code I found that setting `navBarButtonColor` works for setting the tint color for the back arrow.

Thanks for your attention.

**Comment by Norfeldt** [comment]
Would you mind sharing a code snippet of the solution? I can't seem to make it work..

![screen shot 2017-10-01 at 20 06 25](https://user-images.githubusercontent.com/678806/31057493-0a1bee22-a6e4-11e7-932a-0c0fe8023a6c.png)

![screen shot 2017-10-01 at 20 07 43](https://user-images.githubusercontent.com/678806/31057512-33d10d6a-a6e4-11e7-8f1f-d5e5c7f0601c.png)


```
import React, { Component } from 'react'
import { AppRegistry, Text } from 'react-native'
import { Router, Stack, Scene } from 'react-native-router-flux'
import Events from './src/components/Events'
import Details from './src/components/Details'

const App = () => (
  <Router
    navigationBarStyle={{ backgroundColor: '#669966' }}
    titleStyle={{
      fontFamily: 'Pacifico-Regular',
      fontSize: 22,
      color: '#003300',
    }}
    navBarButtonColor={{ color: '#003300' }}
  >
    <Stack key="root">
      <Scene init key="events" component={Events} title="Event Expert" />
      <Scene key="details" component={Details} title="Details" />
    </Stack>
  </Router>
)

AppRegistry.registerComponent('EventExpert', () => App)

```

**Comment by lcleite** [comment]
@Norfeldt write `navBarButtonColor='#003300'` instead of `navBarButtonColor={{ color: '#003300' }}` and it's gonna work

**Comment by Daredevll** [comment]
navBarButtonColor='#ffffff' does not work for me, tried all the options/variants mentioned above.

**Comment by MattyK14** [comment]
@Daredevll applying just `tintColor` worked for me.

**Comment by fercho0** [comment]
> Solution :)

`barButtonIconStyle={{ tintColor: 'red' }}`

`<Router renderLeftButton={data} barButtonIconStyle={{ tintColor: 'red' }} navigationBarStyle={styles.navigationBarStyle}  titleStyle={styles.title}>
            <Scene key="root" >
              .... ?
            </Scene>
</Router>`

**Comment by rsp8055** [comment]
titleStyle={{
      fontFamily: 'Pacifico-Regular',    //  fontFamily: 'Filson_Soft_W03_Book',
      fontSize: 22,
      color: '#003300',
    }}

fontFamily is not working, why?

**Comment by rsp8055** [comment]
Yes, I have. I just found that any fontFamily is not applicable to the title of the nav bar.
