### ISSUE TITLE
null is not an object AppNavigator.router

### ISSUE THREAD

**Issue by d7laungani** [aksonov/react-native-router-flux#2029]
I was able to run the example app just fine but I am running to issues integrating with my own app.

The issue I get is 'null is not an object (evaluating 'AppNavigator.router)'. I saw in another issue some created regarding this problem that they solved it with something I am not using/defining as yet, which is the action for the route. I am using the TabView from the example app.

I inserted a stripped down version of the example with code:

// routes/index.js
```
<Scene key="root" >

        <Scene
            key="tabbar"
            gestureEnabled={false}
            tabs
            activeBackgroundColor='#ddd'
            initial
        >
            <Scene key="tab1" component={TabView} title="Tab #3" />
        </Scene>
    </Scene>
```
// App.js

as per the example.
```
const reducerCreate = params => {
    const defaultReducer = new Reducer(params);
    return (state, action) => {
        console.log('ACTION:', action);
        return defaultReducer(state, action);
    };
};
```
 ```
render() {
    return (
      <Provider store={store}>
          <Router createReducer={reducerCreate}>
            <Routes /> //routes/index.js import
         </Router>
      </Provider>
    )
  }
```

**Comment by aksonov** [comment]
You have to include Scene directly into Router, check Example.

**Comment by d7laungani** [comment]
The <Routes/> line does import everything including this code, which has the scene like this.

**Comment by d7laungani** [comment]
Thanks. Issue Fixed !

**Comment by danieljvdm** [comment]
For any others who get this error, I solved it by wrapping my scenes in a root scene `<Scene key="root">`. I can't find this mentioned anywhere in the documentation, but there has to be a root Scene wrapping everything.

**Comment by ivorscott** [comment]
@danieljvdm this your suggestion still works. Now in 4.0.0-beta it's done like this:

```
 <Router>
    <Stack key="root">
      <Scene key="login" component={Login} title="Login"/>
      <Scene key="register" component={Register} title="Register"/>
      <Scene key="home" component={Home}/>
    </Stack>
  </Router>
```

**Comment by thiagoh** [comment]
@danieljvdm, it actually doesn't have to be key(ed) as root. This worked for me:

```

const RouterComponent = () => {
  return (
    <Router>
      <Scene>
        <Scene key="login" component={LoginForm} title="Please login" />
      </Scene>
    </Router>
  );
};

```

**Comment by A86S** [comment]
Thanks @thiagoh , I got this error because i am writing code like this
```
<Router>
             <Scene key="login" component={LoginForm} title="Please login" />
</Router>
```

**Comment by Tuanhoangle** [comment]
> @danieljvdm, it actually doesn't have to be key(ed) as root. This worked for me:
> 
> ```
> 
> const RouterComponent = () => {
>   return (
>     <Router>
>       <Scene>
>         <Scene key="login" component={LoginForm} title="Please login" />
>       </Scene>
>     </Router>
>   );
> };
> ```
const RouterComponent = () => {
  return (
    <Router>
      <Scene>
        <Scene key="login" component={LoginForm} title="Please login" />
      </Scene>
    </Router>
  );
};

This give me an error "TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')

I get this error just by importing router to my App.js. Any idea?

**Comment by Maradox-D-Krypt** [comment]
> @thiagoh
> 
> ```
>  const RouterComponent = () => {
>    return (
>      <Router>
>        <Scene>
>          <Scene key="login" component={LoginForm} title="Please login" />
>        </Scene>
>      </Router>
>    );
>  };
> ```
> 
> This give me an error "TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')
> 
> I also try adding key="root" to the parent scene, but no luck.
> Same with changing parent scene to Stack. Nothing seem to work.
> 
> I get this error just by importing router to my App.js. Any idea?

I also am experiencing this issue
