### ISSUE TITLE
Adding buttons to Nav Bar

### ISSUE THREAD

**Issue by atn4z7** [aksonov/react-native-router-flux#203]
Hi, 

Thank you for this awesome library. I am trying to add right buttons (search, filter, settings,...) to the nav bar but I couldn't find anything about this in your examples as well as documentation. Is adding buttons not currently supported? 

Thanks!

Edited:
Nvm, figured out how to do it by looking at router class.

**Comment by marcelglaeser** [comment]
Hello atn4z7,

can you give me a example for that?

Regards,
Marcel

**Comment by matiascba** [comment]
Hello atn4z7, do you have the example?

Thanks

**Comment by atn4z7** [comment]
@marcelglaeser @matiascba 
Sure. Here is an example from https://github.com/aksonov/react-native-router-flux/issues/100. You can do the same with renderLeftButton
```
var createRightButton = function() {
      return (
          <View stlye={styles.rightButton}>
              <Button style={{color: 'green'}}>
                 +
              </Button>
          </View>
      );

<Route name="something" renderRightButton={createRightButton}>
```
