### ISSUE TITLE
Scene onPress doesn't work anymore?

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2030]
I used to have an onPress on one of my Scenes, but is not working anymore.
```
<Scene key="add" component={Message}  title="Add" icon={TabIcon}  hideNavBar={true} 
   onPress={()=> {
   alert('a');
   return false;
}}></Scene>
```

Tips?

**Comment by aksonov** [comment]
Sorry, it was quite unclear syntax and it will not be supported by v4. v4 uses ReactNavigation TabNavigator as tabbar. You may pass own tabbar, please check TabNavigator docs.

**Comment by luco** [comment]
Ok, thanks for the feedback!
