### ISSUE TITLE
Swipe back with Vertical threshold

### ISSUE THREAD

**Issue by tikkichan4** [aksonov/react-native-router-flux#2031]
For the swipe back function, i changed the pan handler as below to make the respond area bigger.
const RESPOND_POSITION_MAX_HORIZONTAL = Dimensions.get('window').width / 2;

However it still has a problem which is the swipe back gesture can only detect the swipe right gesture. When the user swipe with top-right, no any action will be taken. 
![123](https://user-images.githubusercontent.com/18086245/28198283-a34a8aa6-688f-11e7-80ca-8bb9db1ffe6b.png)

Just tried to change
const POSITION_THRESHOLD = 1 / 3;
to
const POSITION_THRESHOLD = 1 / 2;

It seems better but sometimes still not working. And it is weird. Any advance for this purpose ? Thanks a lot !!

**Comment by aksonov** [comment]
Sorry, v4 is just wrapper around ReactNavigation (v4), so probably you have to ask there.
