### ISSUE TITLE
Transform error with beta 9 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2032]
Just updated to  "react-native-router-flux": "4.0.0-beta.9", 
getting the following error 
<img width="393" alt="screen shot 2017-07-14 at 8 37 18 am" src="https://user-images.githubusercontent.com/169507/28219128-b6ae8374-686f-11e7-9668-98f05ff6aa78.png">

**Comment by aksonov** [comment]
Cannot reproduce on fresh install of Example

**Comment by AlmogRnD** [comment]
I just did yarn add react-native-router-flux@4.0.0-beta.9 

maybe it only happens when you update but there is an issue

**Comment by AlmogRnD** [comment]
Same thing with npm install react-native-router-flux@4.0.0-beta.9 --save

**Comment by aksonov** [comment]
Try clean clone and run Example

**Comment by AlmogRnD** [comment]
I did yarn remove and then yarn add works now
