### ISSUE TITLE
Custom TabBar Component in v4

### ISSUE THREAD

**Issue by thngdude** [aksonov/react-native-router-flux#2036]
Hi, I'm trying to implement a custom tabbar. As a control, I tried the following, which did not work:

```
import { TabNavigator, TabBarBottom } from 'react-navigation';

<Scene
          key="tabbar"
          gestureEnabled={false}
          tabs
          hideNavBar
          activeBackgroundColor='#ddd'
          component={TabNavigator}>
```
I also tried substituting TabNavigator with TabBarBottom and it still didn't work.

Resulting errors:
1) with TabNavigator --> "Cannot read property 'screen' of undefined"
2) with TabBarBottom --> "Cannot read property 'map' of undefined"

**Comment by aksonov** [comment]
You have to use `navigator` param, `component` is used only by children to display screens

**Comment by thngdude** [comment]
Thanks, @aksonov. Is this currently documented somewhere? Perhaps there's a README I missed.

Btw, this library is really awesome. Thanks for your work.

**Comment by thngdude** [comment]
Ok, I got it working. This would be a first for me, but I would be willing to contribute to add a section about this to the documentation for v4.
```
<Scene
          key="tabbar"
          gestureEnabled={false}
          activeBackgroundColor='#ddd'
          tabs
          tabBarComponent={CustomTabBarComponent}>
          	<Scene key="tab1" component={TabOne} title="Tab1"/>
          	<Scene key="tab2" component={TabTwo} title="Tab2"/>
          </Scene>
```
You must add the `tabs` and `tabBarComponent` props, where the CustomTabBarComponent may extend a component such as `TabBarBottom` from the React Navigation library.

**Comment by aksonov** [comment]
Great! Could you submit PR for docs?

**Comment by kunaldodiya** [comment]
would you please give example for CustomTabBarComponent as i want to render tabs inside custom component, i am able to render "hello" when i use tabBarComponent={CustomTabBarComponent} but instead i want to render tabs view with tap and slide effect, please help

**Comment by kunaldodiya** [comment]
i want to add a ui like on top left back arrow, right side two icons 1) search 2) more (three dots)

and bottom the 3 tabs => Home,  Profile, Settings

If I use tabs i can render tabs but can't set custom header upside, and slide effect working  but tap on any tab does not work work :) your guidance  would be great help

**Comment by roots-ai** [comment]
Hi! Was this issue resolved? How did you finally made the custom slidable tabbar components?

**Comment by cicer1** [comment]
@kunaldodiya can you please share your CustomTabBarComponent?

**Comment by kunaldodiya** [comment]
@cicer1 i am no more using this module.. I am now using react navigation

**Comment by bruno-edo** [comment]
I was able to make a custom tab bar following the method @thngdude described.

I'll prepare an example and submit a PR to add it to the docs. Meanwhile here's some code that should give some idea on how to implement the custom tab bar:

```javascript
import { MaterialTopTabBar } from 'react-navigation-tabs';

class testbar extends MaterialTopTabBar {
    static propTypes = {

    }

    render() {
      return (
          <View>
            {
                this.props.navigationState.routes.map((element) => {
                  return (
                      <TouchableOpacity key={element.key} onPress={() => console.log(element.key)}>
                            <Text>{element.key}</Text>
                      </TouchableOpacity>
                  );
                })
            }
        </View>
      );
    }
}

export default testbar;
```

**Comment by micahkatz** [comment]
@ajaykumar97 you can use `Actions['yourtabroute']();` to switch between tabs
For example, if you have Tab1 and Tab2, and you are currently in Tab1, you can call `Actions['Tab2']();` to switch to Tab2

**Comment by ajaykumar97** [comment]
Thanks for your reply @micahkatz
