### ISSUE TITLE
The vertical position of navigation bar does changes while popping or pushing

### ISSUE THREAD

**Issue by imWildCat** [aksonov/react-native-router-flux#2037]
```
React Version: **0.46.2**
React Native Version: **16.0.0-alpha.12**
OS: **10.12.5** 
Node.js: **v8.1.3**
Yarn: **v0.27.5**
```

### Expected Behaviour:

1. The vertical position of navigation bar does not change while popping or pushing.

2. Tabbar displays well without any extra *shadow*

### Actual Behaviours:
![2017-07-15 14_34_13](https://user-images.githubusercontent.com/2396817/28237172-bc125be0-696b-11e7-927e-850c713a173f.gif)
![snipaste_20170715_143427](https://user-images.githubusercontent.com/2396817/28237180-1556e194-696c-11e7-9930-f66e6a6f51a0.png)

### Sample Code
```jsx
        <Router>
            <Scene key="root" hideNavBar={false}>
                <Scene key="tabbar" hideNavBar={true} tabs={true} tabBarStyle={styles.tabBarStyle}
                    tabBarPosition={'bottom'}
                    hideTabBar={false}
                    showIcon={true}
                    labelStyle={styles.labelStyle}>
                    <Scene key="moment" title="Moment" icon={TabIcon} component={MomentPage} initial={true} />
                    <Scene key="activity" title="Activity" component={ActivityPage} />
                    <Scene key="ranking" title="Ranking" component={RakingPage} />
                    <Scene key="setting" title="Setting" hideNavBar={true} component={SettingPage} />
                </Scene>
                <Scene key="moment2" title="Moment" component={MomentPage} />
            </Scene>
        </Router>
```

**Comment by aksonov** [comment]
RNRF is just wrapper around ReactNavigation. It is how default 'headerMode' (float) works.
As I can see you completely hide navbar for first scene and then show it for second. You could change headerMode to 'screen' (check RN docs) OR don't hide navbar on first page.

You may want to try pure ReactNavigation also.

**Comment by redwind** [comment]
@imWildCat : did you have any update for this issue ?
@aksonov : in my case, i implement static navigationOptions for tab's children without hideNavbar. But when pop back from another screen, the header work like above gif image.

Thanks
