### ISSUE TITLE
Back navigation won't work on Android

### ISSUE THREAD

**Issue by diegocouto** [aksonov/react-native-router-flux#2040]
I've noticed that, on Android:

- When moving from a screen to another, not only the back button won't be shown (as reported on #2023), but also the physical back button will put the app in background instead of leading to the previous screen.
- When the app is put in foreground again, the initial screen is rendered, instead of previously opened screen.

All of these issues can be reproduced using the Example project.

**Comment by aksonov** [comment]
Sorry, I'm actively looking for Android contributor right now because I'm working on iOS app only.

**Comment by hofuchi** [comment]
A workaround for the Android hardware back button closing the app is to use react-native's BackHandler. Would be something like this:

Docs are here: https://facebook.github.io/react-native/releases/0.45/docs/backhandler.html

```
import React, { Component } from 'react'
import { BackHandler } from 'react-native'
import { Actions } from 'react-native-router-flux'

export default class Page extends Component {
  constructor (props) {
    super(props)
  }

  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', () => this.backAndroid()) // Listen for the hardware back button on Android to be pressed
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', () => this.backAndroid()) // Remove listener
  }

  backAndroid () {
    Actions.pop() // Return to previous screen
    return true // Needed so BackHandler knows that you are overriding the default action and that it should not close the app
  }

  // ...other stuff
}
```

**Comment by diegocouto** [comment]
Thanks for the fast reply, @aksonov and @hofuchi! I'm going to take the day to investigate this issue a bit further.

Considering the current scenario, my initial hypothesis is that the scenes aren't being stacked correctly on Android. It would explain why it can't identify where to go when the app is put back in foreground and also won't pop when expected (or show the back button on header).

Do you think that this is a valid approach? 😊

**Comment by hofuchi** [comment]
Yea that might help explain some things, `console.log(JSON.stringify(Actions.state))` should help determine which scenes are stacked where

**Comment by diegocouto** [comment]
Again, thanks for you help, @hofuchi! I'm already working on it. It seems that the initial issue displaying the back button is related to its positioning, as aksonov initially suggested on #2023.

The scenes are being correctly stacked, so the physical back button problem on android is something else. I hope to submit a pull request soon. 😄

**Comment by diegocouto** [comment]
Hey guys, I've just submitted a pull request with a fix for the issue #2023. It seems that, even though different from v3, it's expected that the back button action on android is going to be implemented by the user when using react-navigation (at least, this is what I could take out of [this thread](https://github.com/react-community/react-navigation/issues/117)). 

Following what was suggested by hofuchi and [here](https://github.com/react-community/react-navigation/issues/117#issuecomment-301014577), I'm handling the physical back button with:

``` javascript
import React, { Component } from 'react'
import { BackHandler } from 'react-native'
import { Actions } from 'react-native-router-flux'

class App extends Component {
  constructor (props) {
    super(props);
  }

  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress () {
    if (Actions.state.index === 0) {
      return false;
    }

    Actions.pop();
    return true;
  }

  // ...
}
```

**Comment by aksonov** [comment]
@diegocouto We could also add it to v4 ('App' component within src/Router.js), could do you submit PR?

**Comment by diegocouto** [comment]
@aksonov Sure, I'm glad to help!

**Comment by quarryman** [comment]
@diegocouto did you check it with Example app?

**Comment by diegocouto** [comment]
@quarryman Yep! It should look like this:

![Register screen](https://user-images.githubusercontent.com/1069623/28264901-80bc574a-6ac3-11e7-8cea-edf26d3b7f67.png)

**Comment by quarryman** [comment]
@diegocouto  are you on master?

**Comment by quarryman** [comment]
Just did clean install on master and buck button is still not there

**Comment by aksonov** [comment]
@quarryman Example doesn't use master branch but latest beta, are you sure that you are using master?

**Comment by quarryman** [comment]
@aksonov that was the issue. 
It works after switching example router dependency to master
Do you think it makes sense to merge this fix into beta branch not to confuse new users trying example app.
It will at least prevent this issue reports from being submitted by those who try example.

@diegocouto thanx for a fix

**Comment by ecavalcanti** [comment]
The Actions.state.index always has the same value. This solution does not work for me.

**Comment by ecavalcanti** [comment]
I solved this way:
`<Router backAndroidHandler={this.onBackPress}>`
and:
``` 
onBackPress = () => {
    if (Actions.state.index === 0) {
      return false
    }
    Actions.pop()
    return true
}
```

**Comment by Salehjarad** [comment]
In  **"react-native-router-flux"** version **( 3.41.0 )**
You can use **ActionConst.RESET** to exit the app from any **Component**.
```python
import { Router, Scene , ActionConst } from 'react-native-router-flux'
<Router>
    <Scene duration={0} key="main" type={ActionConst.RESET}>
</Router>
```

**Comment by amarkovits** [comment]
backAndroidHandler does not work for me. the function is never called

**Comment by sadi304** [comment]
@ecavalcanti  this solution puts the app in background. any idea about this?

**Comment by ernanielyjr** [comment]
const onBackAndroid = () => {
  return Actions.pop();
};

<Router backAndroidHandler={onBackAndroid}>

**Comment by esutton** [comment]
How do you exit app without shutting app down?  I think I have tried all the above combinations.

Anytime I return false from either the **router backAndroidHandler** or the **React Native** **BackHandler**, my app disappears and closes completely.  I do not want this.  My user may be in the middle of uploading or downloading and this kills the process.

When I try to resume, I see the splash screen so I know it is restarting from scratch.

**Anytime the app the back handler returns false the app is shut down and closed completyely.**

````
      <router  backAndroidHandler={this.routerBackAndroidHandler} />

  routerBackAndroidHandler = () => {
    const result = Actions.pop();
    console.log('dbg: Actions.pop()', result);

    // returning false will close app completely
    return true;
  }
````

Using:
````
		"react": "^16.2.0",
		"react-native": "^0.52.2",
		"react-native-router-flux": "4.0.0-beta.27",
````

**Comment by Blapi** [comment]
I think this is because of Android behaviour.

On my end : When I exit the app with the backButton because my route stack is empty, the app exits but is not killed. If I come back quickly to the app, I will still be on my latest screen (which for me is a home page (with a type `reset`)).
If I open a new app or wait a bit, the app will start again from the beginning.

**Comment by esutton** [comment]
@Blapi A MainActivity.java fix was the *only* thing that prevented app from terminating.

````
import android.content.Intent;

public class MainActivity extends ReactActivity {

  // Prevent back button from terminating app
  // https://github.com/react-navigation/react-navigation/issues/1372#issuecomment-299432731
  @Override
  public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true);
  }
````

**Comment by Blapi** [comment]
Nice info to know, thanks

**Comment by policz** [comment]
Firstly my BackHandler works fine, but when i'm on Home screen (consider as one or last screen) the app actually navigating to Sign in page(it's throwing the user out of application)
Below are my files

_**### AppNavigatorContainer.js**_

class AppNavigatorContainer extends Component {

addListener = createReduxBoundAddListener("root")

constructor(props) {
super(props)
this.state = {
didReceiveNotificationThatCanBeHandled: false,
notification: null,
didNetworkBecomeUnreachable: false
}
this.onBackPress = this.onBackPress.bind(this)
}
componentWillReceiveProps(nextProps) {
//TODO: Uncomment once VPN problem is fixed
// if (nextProps.isNetworkReachable !== this.props.isNetworkReachable) {
// this.state.didNetworkBecomeUnreachable = !nextProps.isNetworkReachable
// }
}

componentWillMount() {
BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
}

componentWillUnmount() {
BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
//TODO: Uncomment once VPN problem is fixed
// stopListening()
}

onBackPress() {
console.log(this.props);
const { dispatch, navigationState } = this.props
dispatch(NavigationActions.back());
return true;
}

_**AppNavigator.js**_

import React from 'react'
import {
StackNavigator,
addNavigationHelpers
} from 'react-navigation';
import stackConfiguration from './stackConfiguration'
import routeConfiguration from './routeConfiguration'

export const AppNavigator = StackNavigator(
routeConfiguration,
stackConfiguration
);

export default ({
dispatch,
navigationState,
addListener
}) => {
return (
<AppNavigator navigation={addNavigationHelpers({
dispatch,
state: navigationState,
addListener
})} />
)
}

**Comment by nitinAct** [comment]
> In **"react-native-router-flux"** version **( 3.41.0 )**
> You can use **ActionConst.RESET** to exit the app from any **Component**.
> 
> ```python
> import { Router, Scene , ActionConst } from 'react-native-router-flux'
> <Router>
>     <Scene duration={0} key="main" type={ActionConst.RESET}>
> </Router>
> ```

Hy, I want to know that if I use your way it works through the app?

**Comment by nitinAct** [comment]
> I solved this way:
> `<Router backAndroidHandler={this.onBackPress}>`
> and:
> 
> ```
> onBackPress = () => {
>     if (Actions.state.index === 0) {
>       return false
>     }
>     Actions.pop()
>     return true
> }
> ```

Thanks @ecavalcant IT WORKS FOR ME. IM USING ROUTER FLUX V-4.0.1(STABLE). KEEP IT BRO  GOD BLESS YOU. :)
