### ISSUE TITLE
Custom animations for scenes (disabling transition animation)

### ISSUE THREAD

**Issue by ywongweb** [aksonov/react-native-router-flux#2042]
In v3 we can use `duration={0}` to diable the transition aimation. V4 no longer has the `duration` prop and the doc suggest we should **implement custom navigator now instead and pass it as ‘navigator’ prop**. Being not familiar with React Navigation, I was wondering if anyone have an example on how to do this?

Thanks 👍

**Comment by aksonov** [comment]
Very good question. Probably we will implement some workaround soon if ReactNavigation doesn't allow it. What is your use case? You could try to use 'tabs' with tabbar hidden for 'disabled' animations or you could try type 'reset' (check Example/Register UI, or it doesn't allow animation too?)

Check related issue:
https://github.com/react-community/react-navigation/issues/175

**Comment by ywongweb** [comment]
@aksonov Thanks for the link, I will check it out.

My use case is that my app has a static background image that doesn't change or move when you navigate between screens. 

In V3 this was achieved by wrapping the Router component with an Image and setting a transpararent background for every scene. Because the default visual effect for transition is to slide in the new scene while fading out the old one. Having a transparent background means that we can see both scenes durings parts of the transition. 

In the past I have tried using 'reset' as an alternative and it mostly worked, but I had to manually implement every scene's back button behaviour, which can get out of hand very quickly.

**Comment by aksonov** [comment]
@ywongweb Maybe you could implement own custom navigator for your use case - probably you could just copy & past StackNavigator and remove transitions from there. I will also investigate how to solve this problem...

**Comment by aksonov** [comment]
Looks like we could add this functionality using `transitionConfig`:

**Comment by aksonov** [comment]
Here is helpful post:
https://stackoverflow.com/questions/43974979/react-native-react-navigation-transitions/43981835#43981835

**Comment by alexwasner** [comment]
@aksonov I created a simple PR for adding `transitionConfig` to the Navigator. #2062

**Comment by JoshStaff** [comment]
Did this get resolved? Interested in contributing to this.

**Comment by aksonov** [comment]
@JoshStaff Feel free to submit PR

**Comment by aksonov** [comment]
Okey, closing this ticket for now. As I found nice workaround by passing `transitionConfig` for needed container - this way you can create very customisable transitions:
https://github.com/react-community/react-navigation/issues/1759

Also I will add `duration` support using the trick from https://github.com/react-community/react-navigation/issues/1254

P.S. I've just updated Example to make 'Login' animation as standard android 'fade' animation.

**Comment by ajaykumar97** [comment]
You an use your custom transition effects like as follow:

    import StackViewStyleInterpolator from 'react-navigation-stack';
    
    <Scene
    key='main'
    hideNavBar
    transitionConfig={transitionConfig}
    >
    
    ...more scenes
    
    </Scene>
    
    const MyTransitionSpec = ({
        duration: 1000,
        // easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
        // timing: Animated.timing,
    });
    
    const transitionConfig = () => ({
        transitionSpec: MyTransitionSpec,
        // screenInterpolator: StackViewStyleInterpolator.forFadeFromBottomAndroid,
        screenInterpolator: sceneProps => {
            const { layout, position, scene } = sceneProps;
            const { index } = scene;
            const width = layout.initWidth;
    
            //right to left by replacing bottom scene
            // return {
            //     transform: [{
            //         translateX: position.interpolate({
            //             inputRange: [index - 1, index, index + 1],
            //             outputRange: [width, 0, -width],
            //         }),
            //     }]
            // };
    
            const inputRange = [index - 1, index, index + 1];
    
            const opacity = position.interpolate({
                inputRange,
                outputRange: ([0, 1, 0]),
            });
    
            const translateX = position.interpolate({
                inputRange,
                outputRange: ([width, 0, 0]),
            });
    
            return {
                opacity,
                transform: [
                    { translateX }
                ],
            };
    
            //from center to corners
            // const inputRange = [index - 1, index, index + 1];
            // const opacity = position.interpolate({
            //     inputRange,
            //     outputRange: [0.8, 1, 1],
            // });
    
            // const scaleY = position.interpolate({
            //     inputRange,
            //     outputRange: ([0.8, 1, 1]),
            // });
    
            // return {
            //     opacity,
            //     transform: [
            //         { scaleY }
            //     ]
            // };
        }
    });
