### ISSUE TITLE
Actions.{route} not defined for nested scenes

### ISSUE THREAD

**Issue by SpadarShut** [aksonov/react-native-router-flux#2045]
Triggering actions for the most nested screens produce such an error:

```
undefined is not a function ( evaluating '_reactNativeRouterFlux.Actions.kriyaView()')
```

```
import React, { Component } from 'react'
import { Router, Scene, Actions } from 'react-native-router-flux'
import { KriyaView } from '../KriyaView'
import { KriyaEdit } from '../KriyaEdit'
import { HomeTimer } from '../HomeTimer'
import { Kriyas } from '../Kriyas'
import { NavDrawer } from '../NavDrawer'

class Root extends Component {
  render() {
    return (
      <Router>
        <Scene key="root">
          <Scene
            drawer
            contentComponent={NavDrawer}
            key="navDrawer"
            hideNavBar
            drawerPosition="right"
          >
            <Scene
              key="hometimer"
              component={HomeTimer}
              navTransparent
            />
            <Scene
              key="kriyas"
              component={Kriyas}
              title="Kriyas"
              initial
            >
              <Scene
                key="kriyaEdit"
                component={KriyaEdit}
                title="Edit Kriya"
              />
              <Scene
                key="kriyaView"
                component={KriyaView}
                backTitle="View Kriya"
              />
            </Scene>
          </Scene>
        </Scene>
      </Router>
    )
  }
}

export { Root }

```

I tried not wrapping all the screen in a drawer but still get this error.
Using "react-native-router-flux": "^4.0.0-beta.11"
Calling e.g. Actions.hometimer() works good though.

**Comment by aksonov** [comment]
It depends when you try to call it. Maybe you are calling it before router creates actions

**Comment by SpadarShut** [comment]
I call it by tapping a button when everything is rendered long ago

**Comment by aksonov** [comment]
Strange. Could you try to reproduce it on Example project?

**Comment by aksonov** [comment]
Oh, parent scenes cannot have `component` (it is breaking change from v3, please check docs).

**Comment by SpadarShut** [comment]
I'm not migrating from v3, just strted new project from 4.b11. Would be
cool to have docs for v4 where it's written what's allowed and what's not.

17.7.2017 12.25 пасля паўдня карыстальнік "Pavel Aksonov" <
notifications@github.com> напісаў:

Closed #2045
<https://github.com/aksonov/react-native-router-flux/issues/2045>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aksonov/react-native-router-flux/issues/2045#event-1166100135>,
or mute the thread

**Comment by aksonov** [comment]
for v4 I didn't write anywhere that Scene could have both element and component. I will add check for it to throw exception for next version.

**Comment by itinance** [comment]
Any drawbacks available? Running into the same issue after upgrade from v3.39 to v4.0.0.
If i understand it correctly: 

Something like:

```
<ReduxRouter >
        <Scene
          key='drawer'
          component={Drawer}
          open={false}
          >
          <Scene
            key='homeView'
            component={Modal}
            >
            <Scene key='homeViewNormal'
              hideNavBar={false}
              drawerImage={require('./img/menu.png')}
              navigationBarStyle={{ backgroundColor: COLORS.HEADER_BACKGROUND, borderBottomWidth: 0 }}
              leftButtonIconStyle = {{ tintColor:'white'}}
              titleStyle={{color: 'white', fontSize: normalize(14), fontWeight: 'bold'}}
              >

              <Scene key='main' hideNavBar={false} title='Chats'
                type={ActionConst.REPLACE}
                renderRightButton={this.renderRightButtonForChat}
                component={ChatListViewScene} sceneStyle={getScreenContainerStyle()}
                initial={ currentUser !== null && currentUser.id }
              />

```

will not work anymore when it comes to force a scene to appear like

`RouterActions.main()` ?

Thanks for clarifing!
