### ISSUE TITLE
Can't read property 'router' of null

### ISSUE THREAD

**Issue by xilibro** [aksonov/react-native-router-flux#2049]
"react": "16.0.0-alpha.12",
"react-native": "0.46.1",
"react-native-router-flux": "^4.0.0-beta.11",

` <Router>
        <Scene
            key='login'
            component={LoginForm}
            title='Login'
        />
    </Router>`

when i run my code,give me following error message:
'Can't read property 'router' of null'
in Router.js 279:46

**Comment by aksonov** [comment]
You must have container scene as root. Otherwise this component doesn't make any sense.

**Comment by ranasing** [comment]
Can you explain what you mean by this, 'container scene as root'? I am getting the same error. Thanks

**Comment by ranasing** [comment]
Ok, I'm not getting the error any more, but it only shows a blank screen on my Android simulator. Here is the relevant code:

import React, { Component } from 'react';
import { Scene, Router } from 'react-native-router-flux';
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux';
import LoginForm from './components/LoginForm';

  render() {
    const store = createStore(reducers, {}, applyMiddleware(ReduxThunk));

    return (
      <Provider store={store}>
        <Router>
          <Scene key='login' component={LoginForm} title='Login' />
        </Router>
      </Provider>
    );
  }

**Comment by aksonov** [comment]
Your root scene is not container

**Comment by alfchee** [comment]
@ranasing you should check the documentation, you need to nest all you scenes in the root scene as in the example:
`<Router>
    <Scene key="root">
      <Scene key="login" component={Login} title="Login"/>
      <Scene key="home" component={Home}/>
    </Scene>
  </Router>`

**Comment by TeslaMotors91** [comment]
@alfchee This solved it, thank you so much!! I am two weeks into the Udemy course The Complete React Native and Redux Course by Stephen Grider.

He does the code on his example like @ranasing showed here.

**Comment by SarasArya** [comment]
@TeslaMotors91 came here after that course as well. This does it. Thanks so much.

**Comment by muhammedbasilsk** [comment]
@alfchee thanks for the help...
```
<Router>
    <Scene key="root">
      <Scene key="login" component={Login} title="Login"/>
      <Scene key="home" component={Home}/>
    </Scene>
 </Router>
```

**Comment by atljoseph** [comment]
@aksonov the guy asked a question and did not get a response. If you take the time to answer a question, do it fully please.

**Comment by lichao0817** [comment]
@alfchee This is really helpful!

**Comment by obetomuniz** [comment]
@TeslaMotors91 @SarasArya In the Stephen Grider course, he is using a different version of this library.

**Comment by blackinitial** [comment]
Sthepen Grider use 3.35.0 version, but i choose to use last version and got same error like this issue..
Thanks for all, for the answer...
