### ISSUE TITLE
How to position tab bar on bottom. v4

### ISSUE THREAD

**Issue by heartgamer** [aksonov/react-native-router-flux#2054]
I'm using V4 and react-native 0.46. 

I tried to run an example code for a bottom tab bar, 
but the tab bar is on the top at Android Emulator. 

How to position the tab bar on the bottom?

**Comment by luco** [comment]
Try `tabBarPosition={'bottom'}` on your `Scene` component.

**Comment by heartgamer** [comment]
@luco It works! Thank you.
