### ISSUE TITLE
Lightbox not transparent

### ISSUE THREAD

**Issue by alexwasner** [aksonov/react-native-router-flux#2061]
Hey aksonov,
We are having difficulty getting a transparent modal to pop up over our home screen. Perhaps this is related to #2033, or we may just be doing something wrong. Here is our router stack:

```
            <Provider {...stores}>
                <Router createReducer={reducerCreate}  {...sceneConfig}>
                  <Scene key=“lightbox” lightbox  {...sceneConfig}>
                    <Scene key=“modal” modal hideNavBar  {...sceneConfig}>
                      <Scene key=“root” hideNavBar hideTabBar>
                          <Scene key=“login” component={Login}  type=‘reset’ direction=‘vertical’/>
                          <Scene key=“splash” component={SplashScreen} initial type=‘reset’/>
                          <Scene key=“home” component={Home} type=‘reset’ direction=‘vertical’></Scene>
                      </Scene>
                      <Scene key=“test” component={Modal} />
                    </Scene>
                  </Scene>
                </Router>
            </Provider>
```
We've moved around ```sceneConfigs``` to a few different spots to see if we can get it to do something different to no avail. Thanks in advanced!

**Comment by aksonov** [comment]
Could you check Example project? It has Error lightbox and it is transparent.
Btw, you may pass sceneConfig just once, within Router.

**Comment by alexwasner** [comment]
@aksonov Oops. I thought I had copied exactly, but I had it at the modal level. Thanks
