### ISSUE TITLE
How can I pass parameters to a tabbar's child?

### ISSUE THREAD

**Issue by 1335382915** [aksonov/react-native-router-flux#2065]
Here is my scenes
```
<Scene key='tabbar' tabs hideNavBar >
            <Scene key='home' title='home' component={HomeComponent}></Scene>
            <Scene key='cart' title='cart' component={CartComponent}></Scene>
            <Scene key='personal' title='personal' component={PersonalComponent}></Scene>
</Scene>
<Scene key='error' title='error' component={ErrorPage}></Scene>
```
I want to jump  from error scene to personal scene and pass something,but I can't get these parameters at personal scene.
On the contrary,I jump from personal scene to error scene and pass parameters,I can get them at error scene.

**Comment by luco** [comment]
Where's your code?

**Comment by 1335382915** [comment]
@luco Now you can see the demo

**Comment by aksonov** [comment]
@1335382915 ReactNavigation doesn't pass params for some reason. I've just committed fix to use 'refresh' after 'navigate'. Please check latest master. Example also contains demo when Tab5 could be switched with data param (but you have to switch Example to latest master as well)

**Comment by aksonov** [comment]
Try beta.12 now

**Comment by 1335382915** [comment]
@aksonov  Thank you
