### ISSUE TITLE
Nested scenes not working in 4.0.0

### ISSUE THREAD

**Issue by tywoodpav** [aksonov/react-native-router-flux#2066]
I have the following structure

    <Router>
      <Scene key="root">
        <Scene key="unauthenticated" type="reset">
           <Scene key="intro" component={IntroScene} initial={true} />
        </Scene>
        <Scene key="authenticated" type="reset">
          <Scene key="profile" component={ProfileScene} initial={true} />
        </Scene>
      </Scene>
    </Router>

I have `unauthenticated` and `authenticated` scenes for sanity. 

When I run `Actions.authenticated()` from `IntroScene`, I get an error saying:

    There is no route defined for key authenticated must be one of 'intro'.

This worked previously, but I updated to `^4.0.0-beta.11` and it no longer works.

Do I need to flatten my scenes?

**Comment by tywoodpav** [comment]
In the migration guide it says 

No component support for scene containers (that contains children `Scene`) - you have to use custom navigator.

What does that mean?

**Comment by aksonov** [comment]
> No component support for scene containers (that contains children Scene) - you have to use custom navigator.

It is not for the problem you mentioned. Probably React Navigation doesn't support such scenario - as workaround you could remove 'reset' and use 'tabs' for 'root' navigator (with hideTabBar).

To see your case could you fork this component and modify Example so I can run it?

**Comment by tywoodpav** [comment]
As you suggested switching to tabs works (the problem is with `reset`). However, the original (unauthenticated) component never unmounts. 

https://github.com/tywoodpav/react-native-router-flux

**Comment by aksonov** [comment]
Could you please clone & modify Example project to demonstrate issue?

**Comment by tywoodpav** [comment]
I did. Check link on previous comment. Running will throw the same error.

**Comment by aksonov** [comment]
Thanks for repo, I've just checked it. It works fine without 'reset', so as I guessed before ReactNavigation doesn't support such transitions for some reason. Could you build pure ReactNavigation example and ask there to help? If they could give some receipt we could change RNRF 'reset' behaviour accordingly...

**Comment by tywoodpav** [comment]
I figured it out.

According to https://github.com/react-community/react-navigation/issues/1127, you need to set `key: null` in the reset action.

Here's a demo I put together

https://github.com/tywoodpav/reset-nested-navigators-react-native-navigation

**Comment by aksonov** [comment]
@tywoodpav Good job! Please check latest master now. And replace Actions.pop to Actions.unauthenticated within Home screen because 'reset' clears stack completely (so no pop is possible)

**Comment by aksonov** [comment]
Could you try latest master? Not beta.12

**Comment by tywoodpav** [comment]
> Could you try latest master? Not beta.12

Nice. My mistake. Thanks!

**Comment by tywoodpav** [comment]
Original bug was fixed, but a new one was created. When I try to transition between scenes in the same container (i.e. `authenticated`), the same error is thrown. I'm guessing this is because `key: null`

Here is a demo: https://github.com/tywoodpav/rnrf-4.0.0-nested-2066

**Comment by aksonov** [comment]
Again, I've just implement `key:null` for replace you suggested before. could you implement it with pure react navigation ? Or it is better to submit PR.

**Comment by tywoodpav** [comment]
Here's a link to the updated repo with `react-navigation` https://github.com/tywoodpav/reset-nested-navigators-react-native-navigation

I think the problem is when RNRF detects what type of action to dispatch, it defaults to the one highest up in the tree. This makes `reset` work but when you navigate to a scene within the stack it still thinks you want a `reset` action when you actually just want to `navigate` normally. 

I'd love to help, but I think I'll have to change `navigationStore` and I have trouble following how params are parsed. Maybe some comments would help? ;)

**Comment by aksonov** [comment]
Have you tried to pass reset type as actions param and remove it from scene param?

**Comment by aksonov** [comment]
Ops, looks like type is the inherited property. I will fix it. For now just set type for children to push

**Comment by tywoodpav** [comment]
That works. Thanks!

**Comment by roots-ai** [comment]
This issue still seems unresolved? Which version of RNRF to use with the latest version of RN?

**Comment by roots-ai** [comment]
> I figured it out.
> 
> According to [react-navigation/react-navigation#1127](https://github.com/react-navigation/react-navigation/issues/1127), you need to set `key: null` in the reset action.
> 
> Here's a demo I put together
> 
> https://github.com/tywoodpav/reset-nested-navigators-react-native-navigation

This link is broken

**Comment by roots-ai** [comment]
> Here's a link to the updated repo with `react-navigation` https://github.com/tywoodpav/reset-nested-navigators-react-native-navigation
> 
> I think the problem is when RNRF detects what type of action to dispatch, it defaults to the one highest up in the tree. This makes `reset` work but when you navigate to a scene within the stack it still thinks you want a `reset` action when you actually just want to `push` normally.
> 
> I'd love to help, but I think I'll have to change `navigationStore` and I have trouble following how params are parsed. Maybe some comments would help? ;)

broken link

**Comment by woodpav** [comment]
We resolved this issue a while ago. I have since deleted the example repo. If you still experience it, please open a new issue and link to this issue for backlink purposes.

**Comment by roots-ai** [comment]
@woodpav Please see to this https://github.com/aksonov/react-native-router-flux/issues/3587

**Comment by roots-ai** [comment]
@woodpav Can you please see to this as this has broken our production release? Thanks.

**Comment by roots-ai** [comment]
Any updates here? 
This is still not working with the latest versions of RNRF.
