### ISSUE TITLE
V4 : How to pass props to custom navBar using Action ?

### ISSUE THREAD

**Issue by sylvainbaronnet** [aksonov/react-native-router-flux#2069]
Hello,

```
Actions.profil({
  viewMode: 'full',
  pseudo: profil.pseudo,
})
```

In my custom navBar I don't get `pseudo` or `viewMode` as props. If I set a props to the scene I got it in the navBar.
How to get props set with Action parameters in custom navBar ?

**Comment by sylvainbaronnet** [comment]
I found that I access them with `Actions.currentParams`

**Comment by aksonov** [comment]
@sylvainbaronnet Please check latest master

**Comment by sylvainbaronnet** [comment]
Yes it now works as expected, thanks a lot !
