### ISSUE TITLE
calling same route with different data

### ISSUE THREAD

**Issue by kadosh1000** [aksonov/react-native-router-flux#207]
My side menu is calling the same action each time with different data inside,
the first time works great and after that it stops calling the route, and therefore the route wont reload with the new data.

How can I make it work?

## Edit 1:
After few more tests, it seems that after the route was loaded once it won't reload again, event after moving to a different route and trying to go back to the first one

## Edit 2:
trying to debug using the componentWillReceiveProps method, it seems that the component not getting the new data, it stays with the old data

## Edit 3:
after debugging Actions.render it seems to be connected to the fact I've chose schema type "switch", probably connected to the onJump handler. changing to any other schema type fixed the issue

**Comment by aksonov** [comment]
Yes, looks like it is limitation of React Native navigator.jumpTo method, which doesn't allow to pass new properties to existing routes. Could you try new Actions.refresh(props) method? If it works fine you may want to submit PR to add this call at the end of ExRouter.onJump method after jumpTo to update route with new props...

**Comment by lrettig** [comment]
I ran into this too. refresh did not, but manually setting the props on the existing route did. Not sure if this is the safest/right way to do it, but it works. Just submitted #259.

**Comment by lrettig** [comment]
This is more complicated than I thought. The component continues to receive the props from the router every time push or pop is called, i.e., when another component is added on the nav stack on top of it, or popped back off. @aksonov do you know why this happens?

In my use case, I want to act on the props only when they're received _explicitly_ (i.e. via an Action) and not _implicitly_ (the push/pop case I just described). I'm receiving them in `componentWillReceiveProps` but I don't know how to handle the first case but ignore the second.

**Comment by lrettig** [comment]
It's even stranger than I thought. I'm seeing nondeterministic behavior, where my component sometimes receives the props, sometimes doesn't (i.e., `componentWillReceiveProps` is called sometimes when the route is loaded, but not always). Maybe this has something to do with RN's internal mechanism for deciding when updates need to happen?

I worked around this for now by defining multiple routes so that I can act upon `componentDidMount` rather than `componentWillReceiveProps`.

**Comment by aksonov** [comment]
Please check latest 3.0 release. I'm closing this ticket because it for 2.x
