### ISSUE TITLE
v3 to v4 : Route 'myRoute' should declare a screen.

### ISSUE THREAD

**Issue by enguerranws** [aksonov/react-native-router-flux#2074]
Hi,

following your advice on #158, I migrated from v3 to v4, I had some issues I fixed, but I'm stuck on this one.

``` 
ExceptionsManager.js:63 Route 'splashscreen' should declare a screen. For example:

import MyScreen from './MyScreen';
...
splashscreen: {
  screen: MyScreen,
}
```

With my Router:

```
<Router>
               <Scene key="root">

                  <Scene key="splashscreen" component={Splashscreen} title="Splashscreen" initial />
                  <Scene key="login" component={Login} title="Login"/>                            
                  <Scene key="newsfeed" showMainMenu={true} component={Newsfeed} title="Newsfeed" />
                  <Scene key="profile" showMainMenu={true} component={Profile} title="Profile" />
                  <Scene key="jobs" showMainMenu={true} component={Jobs} title="Jobs" />
                
               </Scene>
              
               
              
               
             </Router>
```

As far as I understand, this comes from StackNavigator, but I thought RNRF was handling this?

**Comment by enguerranws** [comment]
I guess I messed up with my Components declaration. MyScreen wasn't referencing to any MyScreen component found in this context.

**Comment by gardner** [comment]
I am getting this too. How did you fix it?

**Comment by NickBefore** [comment]
#1974

**Comment by peter017** [comment]
I had this issue, fortunately for me it indicated the undefined import statement. I was missing "export" in the imported subcomponent. Therefore the import failed and my <Scene component="XYZ" /> was undefined. So first thing, try to check for this. Maybe that helps someone.

**Comment by isaackdamian** [comment]
@gardner  did you find a fix? I'm currently stuck with the same error

**Comment by Blapi** [comment]
@isaackdamian be sure your Component is a real component, exported and imported correctly.
