### ISSUE TITLE
Actions.pop() with data is not working

### ISSUE THREAD

**Issue by rajsuvariya** [aksonov/react-native-router-flux#2075]
Action.Actionname(data) is working but Actions.pop(data) is not working.

Here is my code
```
      <RedButton
        style={styles.buttonStyle}
        buttonTextStyle={styles.buttonTextStyle}
        onPress = { () => Actions.pop({ refresh: {data: 'dads'}}) }
        >
        Add
      </RedButton>
```

I have added lot of life cycles methods in parent screen and added log inside them but non of them are getting called.
```

    componentWillUpdate() {
      console.log('componentWillUpdate');
    }

    componentWillMount(){
        console.log('componentWillMount');
    }

    componentWillUnmount(){
      console.log('componentWillUnmount');
    }

    componentWillReceiveProps(nextProps){
      console.log(nextProps);
    }
```

I am not even getting undefined. There is no reflection in debug console.

Please check might be the issue with React Native updates. I am using following dependencies.
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.3",
    "react-native-router-flux": "^4.0.0-beta.12"
  }
```

**Comment by aksonov** [comment]
Thanks, I will add it to 'migration' section. Use `Actions.pop();Actions.refresh({..})`

**Comment by rajsuvariya** [comment]
Actions.pop();Actions.refresh({..}) this is work around only right?

**Comment by aksonov** [comment]
Actually it is not workaround but much better syntax. v3 just was not able to support it.

**Comment by aksonov** [comment]
However it is not difficult to add old syntax for backward compatibility. Feel free to submit PR.

**Comment by rajsuvariya** [comment]
In navigationStore.js the pop is written like this

```
 pop = () => {
    this.dispatch(NavigationActions.back());
  };

```
It is even not taking any params. Is it the cause of this problem?

**Comment by rajsuvariya** [comment]
Is this fix live now?

**Comment by aksonov** [comment]
Yes, master branch. Will publish beta.13 soon.
