### ISSUE TITLE
Double navBar on nested Scenes

### ISSUE THREAD

**Issue by psycura** [aksonov/react-native-router-flux#2077]
Hello, and thank you for great work.

My version 4.0.0-beta.12:

My router is:
```
<Router>
            <Scene key="root">
                <Scene key="auth">
                    <Scene key="login" component={LoginForm} title="Please Login"/>
                </Scene>
                <Scene key="main">
                    <Scene key="employeeList" component={EmployeeList} title="Employees"/>
                </Scene>
            </Scene>
 </Router>
```
and in emulator i see this issue:
![2017-07-20_1753](https://user-images.githubusercontent.com/22491732/28423757-97b71684-6d74-11e7-97e1-b260ff5efc7b.png)

as you can see i have 2 headers - i suppose - one for "auth" and one for "login".
How can i disable one of them?
if i put hideNavBar to the parent or to the child - as result i dont see navBar at all.

And another question - if i want after login redirect user to the "employeeList", and i dont want that user will have BACK button at the navigation - how i can achieve this?

Thank you

**Comment by luco** [comment]
Set `hideNavBar` on `root`.

**Comment by psycura** [comment]
Ohh, thanks ))
what about 2nd question?

**Comment by psycura** [comment]
Oh, sorry, now the back button is gone.
Issue closed

**Comment by xuananpham93** [comment]
I love you #luco

**Comment by mukunzidd** [comment]
I love u @luco  u saved my ass. Stephen Grider too? @aksonov

**Comment by silasakk** [comment]
thanks @luco

**Comment by hastishb** [comment]
Hey! 
I'm also going through Stephen Grider's tutorials and I just had this problem. the hidNavBar thing didn't work for me. But I realized that sceneStyle={{ paddingTop: 65 }} on the Router caused it. without it there's no problem. I guess you should do the styling for the nested scenes only. Setting it in the Router also applies it to root and it doubles.
