### ISSUE TITLE
Pop with props

### ISSUE THREAD

**Issue by xahon** [aksonov/react-native-router-flux#2078]
Is this possible to pop with props to previous screen?

**Comment by diegocouto** [comment]
Hi, @xahon! No, it is not. As [you can see here](https://github.com/aksonov/react-native-router-flux/blob/master/src/navigationStore.js#L208), pop doesn't expect params.

To achieve this behavior, you can refresh after a pop. Take a look on #2047 to get some ideas about how to implement this. 😉

**Comment by aksonov** [comment]
Please check latest master now, I've added support for refresh for backward compatibility
