### ISSUE TITLE
Using onEnter/onExit from Component

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2081]
Is there a way from using `onEnter` and `onExit` from component itself?
I mean, I want to call a function from my component every time I enter on it.

I tried using on Scene component, but wasn't lucky.

**Comment by tywoodpav** [comment]
I wanted to do something similar. Calling `Actions.refresh()` in the transitioning scene rerenders the new scene so you could put something in `componentWillReceiveProps`

**Comment by aksonov** [comment]
@luco Have you tried to add onEnter/onExit on containers or on child? It works only for child. I've just added possibility to define them on component level (as static functions), please check.

**Comment by rochapablo** [comment]
Shouldn't this be working?

```
<Scene key="login" component={Login} title="Login" onEnter={this.doSomething} />
```

**Comment by aksonov** [comment]
Depends from what is `this.doSomething`. Just put `onEnter={()=>console.log("onEnter!")}`  to see log

**Comment by rochapablo** [comment]
Yep, you're right! I may be doing something wrong. Thank you.

**Comment by EnriqueDev** [comment]
I still don't really understand how onEnter works. Is it possible to call a function from the component from there? Is there a tutorial / doc on how to use it?

**Comment by aksonov** [comment]
Demo is in progress... You may define it as static component function

**Comment by NelGarbuzova** [comment]
Is there such event listener for Drawer? I need to listen for Drawer opens/closes. I can't find this in docs.

**Comment by daviscabral** [comment]
`<Drawer />` is the same as `<Scene drawer />`. When it opens/closes is the onEnter/onExit event - but you can also use only `react-navigation` for that with [`NavigationEvents`](https://reactnavigation.org/docs/en/navigation-events.html#docsNav).
https://github.com/aksonov/react-native-router-flux/blame/master/docs/API.md#L67
