### ISSUE TITLE
navTransparent Does not work

### ISSUE THREAD

**Issue by paloman** [aksonov/react-native-router-flux#2084]

**Comment by diegocouto** [comment]
Hey, @paloman! Are you able to reproduce this on the example project? The more details you share, the easier it gets to help you. 😄

**Comment by paloman** [comment]
Hi @diegocouto it worked on the example, but throughs an error in my project...

**Comment by paloman** [comment]
import React from 'react';
import { Scene, Router, Actions, Reducer, ActionConst } from 'react-native-router-flux';
import LoginForm from './components/auth/LoginForm';
import NameSignup from './components/auth/signup/Name';
import UsernameSignup from './components/auth/signup/Username';
import BirthdaySignup from './components/auth/signup/Birthday';
import VerificationSignup from './components/auth/signup/Verification';

const RouterComponent = () => {
    return (
    <Router sceneStyle={{ paddingTop: 65 }}>
      <Scene key="auth">
        <Scene
        key="login"
        component={LoginForm}
        hideNavBar
        sceneStyle={{ paddingTop: 0 }}
        /*title="Please Login"*/
        />
      </Scene>
      <Scene 
      key="signup" 
      //onLeft={() => Actions.pop()}
      gestureEnabled={false}
      
      sceneStyle={{ paddingTop: 0, back: true }}
      //back={true}
      >
        <Scene
        key="NameSignup"
        component={NameSignup}
        //title="NameSignup"
        sceneStyle={{ paddingTop: 0 }}
        initial
        />
        <Scene
        key="UsernameSignup"
        component={UsernameSignup}
        //title="UsernameSignup"
        sceneStyle={{ paddingTop: 0 }}
        />
        <Scene
        key="BirthdaySignup"
        component={BirthdaySignup}
        //title="BirthdaySignup"
        sceneStyle={{ paddingTop: 0 }}
        />
        <Scene
        key="VerificationSignup"
        component={VerificationSignup}
        //title="VerificationSignup"
        sceneStyle={{ paddingTop: 0 }}
        />
      </Scene>
    </Router>
  );
};

export default RouterComponent;

**Comment by paloman** [comment]
how do I update to beta 12? @diegocouto

**Comment by paloman** [comment]
![screenshot_1500617729](https://user-images.githubusercontent.com/9502594/28451312-68ca75dc-6da1-11e7-9896-1fcac323c711.png)

**Comment by paloman** [comment]
<Router sceneStyle={{ paddingTop: 65 }}>
      <Scene key="auth">
        <Scene
        key="login"
        component={LoginForm}
        hideNavBar
        sceneStyle={{ paddingTop: 0 }}
        /*title="Please Login"*/
        />
      </Scene>
      <Scene 
      key="signup" 
      //hideNavBar
      navTransparent
      sceneStyle={{ paddingTop: 0, back: true }}
      leftButtonImage={backButtonLogo}
      onLeft={() => Actions.pop()}
      //back={true}
      >
        <Scene
        key="NameSignup"
        component={NameSignup}
        //title="NameSignup"
        sceneStyle={{ paddingTop: 0 }}
        initial
        />
        <Scene
        key="UsernameSignup"
        component={UsernameSignup}
        //title="UsernameSignup"
        sceneStyle={{ paddingTop: 0 }}
        />
        <Scene
        key="BirthdaySignup"
        component={BirthdaySignup}
        //title="BirthdaySignup"
        sceneStyle={{ paddingTop: 0 }}
        />
        <Scene
        key="VerificationSignup"
        component={VerificationSignup}
        //title="VerificationSignup"
        sceneStyle={{ paddingTop: 0 }}
        />
      </Scene>
    </Router>

**Comment by aksonov** [comment]
Issue was created without details (version, etc.) As I see it could be even not v4 (Scene's doesn't contain root scene). Please use v4.

**Comment by adaerodriguez** [comment]
Hi, I still have the same problem in versión "react-native-router-flux": "4.2.0".  If I put navTransparent={true}, the content of the scene appear behind the navBar. Could you put an example of how solve this problem?
