### ISSUE TITLE
tabbar icon cannot class?

### ISSUE THREAD

**Issue by shiqian123** [aksonov/react-native-router-flux#2085]
in v3
`
class TabIcon extends Component {}
`
`
<Scene key="home" icon={TabIcon}>
   <Scene key="homePage" component={HomePage}/>
</Scene>
`
but in v4 this is error .I mast write that 
`
const TabIcon = ()=>{}
`
`
<Scene key="home" icon={TabIcon}>
   <Scene key="homePage" component={HomePage}/>
</Scene>
`

**Comment by aksonov** [comment]
Yes, it is limitation of React Navigation and it makes sense. Please use pure functions for icons.
