### ISSUE TITLE
Back button does not render 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2086]
Using the latest version 4.0.0-beta.12 

I have two components/scenes that I load 'home' and 'photos' when I navigate from home too to photos everything loads and on mount runs but if I press the back button on the top header and go back to home and then from home again to photos on mount does not re run so I can't load new data. 

It seems that the back button does not clear the loaded component this might be a react navigation issue. 

Is there a way to fix this or some king of work around

**Comment by aksonov** [comment]
Could you reproduce it with Example project? Also it will be helpful to check if it is react-navigation issue (by implementing pure react navigation example).

**Comment by AlmogRnD** [comment]
I think it's a react-navigation issue, I can't reproduce it right now but I think this is the same issue - https://github.com/aksonov/react-native-router-flux/issues/723

**Comment by aksonov** [comment]
Just try mobx

**Comment by aksonov** [comment]
Or Actions.refresh

**Comment by AlmogRnD** [comment]
I was able to find out what's going on. It has nothing to do with the back button but

`Actions.tab2(); `

So when you call Actions tabs it renders the component then if you click the back button and then run again 

`Actions.tab2();  `

It does not re mount the component, for some reason its saved in memory so it pushes the component to the front of the view but does not re run any of the code. 

If I run the following Actions.Photos(); it works as expected but then you get the issue with were the component twice.

**Comment by AlmogRnD** [comment]
You can also see this issue by just clicking the tabbar in the example, it mounts the first time but does not mount again. There should be a way to force it to remount

**Comment by aksonov** [comment]
Use `Action.refresh` to 'refresh' tabs (componentWillReceiveProps). Tabs should not be remounted.
Or use `onEnter` handler for tabs.

**Comment by aksonov** [comment]
I have just added BLUR/FOCUS passed to reducer (latest master, will be beta.13 soon). Closing this ticket

**Comment by AlmogRnD** [comment]
@aksonov I have tested this and it's not working. on enter only first the first time the router is loaded. 
` <Scene key='Photos' component={Photos} title='Photos' back backTitle='Back' initial={false} onEnter={alert('aaa')} />`

And I can't use componentWillReceiveProps as I'm not passing any props but just using redux state

Can you please example how to use BLUR/FOCUS

**Comment by AlmogRnD** [comment]
I did a workaround not really sure this is the correct way or best way but I just used 
redux-subscriber 

Which subs to the change and re runs my function
