### ISSUE TITLE
Drawer with drawerPosition="right" has menu button on the left

### ISSUE THREAD

**Issue by SpadarShut** [aksonov/react-native-router-flux#2087]
So the issue is in the subject: Drawer with drawerPosition="right" has menu button on the left.

**Comment by aksonov** [comment]
Good catch! PR would be great. As workaround just use rightButtonImage and set drawerImage to null.

**Comment by aksonov** [comment]
Should be fixed with 4.0.0.beta.13

**Comment by Rojeena-maharjan** [comment]
Is this solved yet??
