### ISSUE TITLE
Action to the same route

### ISSUE THREAD

**Issue by fukuball** [aksonov/react-native-router-flux#2091]
I have some question, when I trigger the same route action multiple times, will the app create the same view multiple times?

For example:

1. I have drawer navigation, and on the menu I have an action: Actions.home()
2. When press on the action, the app create home view and goes to the home view
3. Then I open the drawer menu again, and press Actions.home() again, and the app goes to the home view again.

I want to know the last home view is new created view or old one, can we reuse the old one?

**Comment by fukuball** [comment]
I write some code to prevent the issue I describe above:

```
const popToRoute = (route, route_callback) => {
  popping = true;
  if (_.includes(navHistory, route)) {
    let find = false;
    while (!find) {
      if (_.last(navHistory) == route) {
        find = true;
      } else {
        navHistory.pop();
      }
    }
    Actions.popTo(route);
  } else {
    navHistory.push(route);
    route_callback();
  }
  console.log(navHistory);
  setTimeout(function (){
    popping = false;
  }, 1000);
};

const goToLaunch = () => {
  navHistory = ['launch'];
  Actions.popTo('launch');
};
const goToLogin = () => {
  if (!popping) {
    var route_callback = function(){
      Actions.login();
    };
    popToRoute('login', route_callback);
  }
};
const goToLogout = () => {
  if (!popping) {
    var route_callback = function(){
      Actions.logout();
    };
    popToRoute('logout', route_callback);
  }
};
const goToRegister = () => {
  if (!popping) {
    var route_callback = function(){
      Actions.register();
    };
    popToRoute('register', route_callback);
  }
}
```

Anyone have better way?

**Comment by aksonov** [comment]
App should re-use existing 'home'. If it doesn't give me steps to reproduce. Check Example project for this repo.
