### ISSUE TITLE
Drawer-Image not shown on android

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#2092]
What could be the reason, that the drawer-image not appear on Android while it is visible on iOS?

This is the code:

```
<ReduxRouter tintColor='white'>
          <Scene
            key='homeView'
            drawer={true}
            drawerImage={require('myapp/src/img/menu.png')}
            contentComponent={MenuScene}
            >

```

Working well on iOS. But not on Android. Any ideas?

**Comment by aksonov** [comment]
What version do you use? We had some issues before, but it should be fixed with beta.12 I believe

**Comment by itinance** [comment]
This sounds great. I use 4.0.0-beta.11.
Will upgrade and test again and give feedback

**Comment by itinance** [comment]
4.0.0-beta.12 fixes this. Thank you!
