### ISSUE TITLE
hideBackImage and renderBackButton not working

### ISSUE THREAD

**Issue by ysfkc** [aksonov/react-native-router-flux#2093]
hi,
i using flux v4. 

renderBackButton does not work v4. I tried Actions.refresh but same problem not working. 

Example:

<Scene ..... hideBackImage={true} renderBackButton={ () => {return (<Text>Hi</Text> } } ... />

what should I do?

**Comment by diegocouto** [comment]
Hi, @ysfkc! Yep, I don't think that they're part of [v4 API](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md). To hide the back button, you could use `back={false}` instead. 😄 

Hope it helps!

**Comment by ysfkc** [comment]
Ok. but what should i do two button back and drawer menu icon?

**Comment by diegocouto** [comment]
Hum... I haven't worked with it myself but, based on the example project, I think you can get the drawer menu icon with the `drawer` prop.

You can see a [demo of the project](https://github.com/aksonov/react-native-router-flux), and [here is the line](https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L59) I'm talking about.

**Comment by ysfkc** [comment]
Solution:

My component: ContentDetail

```
import React, {Component} from 'react';
import { StackNavigator } from 'react-navigation';

class ContentDetail extends Component {
    static navigationOptions  = {
        headerStyle: {backgroundColor:'#000'},
        headerLeft: <LeftButtonMenu backMenu={true}  />,
        headerRight: <TouchableHighlight><Image source={require('../assets/icons/icnBack/icnBack.png')} style={{marginRight:18}} /></TouchableHighlight>,

    }
}

```
