### ISSUE TITLE
tabBarComponent transparent background hides content

### ISSUE THREAD

**Issue by ChristianTucker** [aksonov/react-native-router-flux#2095]
When using a custom component for the tabBarComponent it takes up space the size of the component, in our case we have a tab in our application that is a big circular button as the tab, for example: ![https://s-media-cache-ak0.pinimg.com/736x/58/c5/7d/58c57dd6eb1c3a07f7d3c7b6bb10753e.jpg](https://s-media-cache-ak0.pinimg.com/736x/58/c5/7d/58c57dd6eb1c3a07f7d3c7b6bb10753e.jpg)

Because of this our tabBar needs to have some extra space, so we do it like this:

```
container: { 
    height: 80,
    backgroundColor: "transparent"
    ...
},
tabBar: {
    height: 60
    ...
}
````

However, this pushes the content of the page up 80px, and doesn't show the content for the 20px of the transparent container. So there is a big gray area (on android).

I tried to set the position to "absolute" on the container, but this makes the tab bar render off screen. 

--

Because we also animate the tab bar, we really need a way to implement a `absolute` position tab bar.

**Comment by aksonov** [comment]
Sorry, this component is just wrapper around ReactNavigation and uses TabBar provided by ReactNavigation. Could you check their github?

**Comment by ChristianTucker** [comment]
@aksonov  I come from react-navigation, and this problem doesn't exist when using a custom component for the TabBar over there. Here is an example of what the `transparent` background looks like in RNRF, 

![https://gyazo.com/8a3bcdd38c0ba36ca1da019270e2979d](https://gyazo.com/8a3bcdd38c0ba36ca1da019270e2979d)

It's the gray that cuts off the content. In react-navigation you are able to give your component a absolute position and overlay it on the screen, however in RNRF applying `position: "absolute"` stops the component from displaying.

**Comment by aksonov** [comment]
It is strange because RNRF just passes everything to react-navigation... I need to more concrete Example (modification of this repo Example?) and more react-navigation example that works - maybe some parameters were overriden. You may check Router.js and how it passes params to TabNavigator.

**Comment by ChristianTucker** [comment]
@aksonov This is actually a problem with an outdated dependency in the version of react-navigation that's being used, as I forced an update to `react-native-tabs-view` to 0.66 (Currently 0.65) and it fixed this issue.

**Comment by StasVitAlex** [comment]
Get the same problem
@ChristianTucker help pls how to solve, installed react-native-tabs-view 0.66 version

**Comment by KamranKhankhail** [comment]
@ChristianTucker was you able to fix that grey area issue on android? if yes, can you please share how you did it?
