### ISSUE TITLE
BackHandler remove on v3.39.1

### ISSUE THREAD

**Issue by stefan0s** [aksonov/react-native-router-flux#2096]
Hello,

We are using version 3.39.1 and we are having the following batch of scenes:
<Scene key="root">
            [Scene key="splashscreen" component={SplashPage} hideNavBar initial type={ActionConst.REPLACE} /]
            Scene key="loginScene" hideNavBar]
              [Scene key="login" component={Login} /]
              [Scene key="authenticate" component={Authenticate} /]
              [Scene key="register" component={Register} /]
              [Scene key="forgotPassword" component={ForgotPassword} /]
            [/Scene]
            [Scene key="mainScene" hideNavBar]
              [Scene key="home" component={Home} /]
              [Scene key="scene1" component={scene1} /]
              [Scene key="scene2" component={scene2} /]
            [/Scene]
          [/Scene]

After successfull login app navigates to splash and finally to mainScene. We need to disable BackHandler from mainScene!

We have used type RESET with no luck. Also we have tried to remove event listener using refs but it seems not to work. Any suggestions?

**Comment by aksonov** [comment]
Please use v4, v3 is not supported
