### ISSUE TITLE
about example  Jump animation

### ISSUE THREAD

**Issue by shiqian123** [aksonov/react-native-router-flux#2097]
when i Actions.login() is from bottom to top, other is from right to left, I did not find where to set up， please help me。thanks

**Comment by shiqian123** [comment]
other problem 
![099210c5-a173-4da2-8595-8baa1a20cb72](https://user-images.githubusercontent.com/9497069/28505588-dcfad8bc-7057-11e7-8b1e-ee9d627074cc.png)
in the tableIcon  ,v3,console.log(props) is 
![145d520e-7220-45b7-b904-d44f6b15652e](https://user-images.githubusercontent.com/9497069/28505599-ff188926-7057-11e7-9d64-750156b12cdd.png)
but in v4 console.log(props)
![87391abe-583d-42ee-8141-7dcc1f6a4571](https://user-images.githubusercontent.com/9497069/28505605-11491020-7058-11e7-9f5e-5374c005d171.png)

**Comment by aksonov** [comment]
It depends from your parent scene. If it is modal - it will be bottom to top.
