### ISSUE TITLE
How to reset back stack?

### ISSUE THREAD

**Issue by rajsuvariya** [aksonov/react-native-router-flux#2098]
In v3 to clear the back stack I was using Actions.Scene({ type: 'reset' }). But apparently it's not working in v4.

**Comment by rajsuvariya** [comment]
I was able to achieve it using Actions.reset("Scene") but the animation looks too bad. Actually, it shows every screen being closed.
Can I have the option to remove this animation while clearing back stack

**Comment by aksonov** [comment]
Duplicate of https://github.com/react-community/react-navigation/issues/1493

**Comment by karanwadhwa** [comment]
'replace' works fine to clear the back stack

**Comment by karanwadhwa** [comment]
`'replace'` Pops the current scene from the stack and pushes the new scene to the navigation stack. *No transition will occur.
