### ISSUE TITLE
Navigation doesn't work when using Chrome debugging

### ISSUE THREAD

**Issue by Predjo** [aksonov/react-native-router-flux#210]
react-native-router-flux: 2.1.4
react-native: 0.19.0
Using it on android with Genymotion emulator. 

It works perfectly fine without the debugging. But once its on it fails on first navigation attempt. And just freezes the current screen.

**Comment by aksonov** [comment]
Have you tried pure ExNavigator?

**Comment by Predjo** [comment]
I have now and same problem is present :/
