### ISSUE TITLE
v4 replace behaves different to v3?

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2102]
The normal navigation between my scenes is:
A->B->C

on scene B, you can press and add button and this would send you to scene D. When you click save, then you are sent to scene C. Now clicking the back button on scene C shouldn't send you back to scene D, but to B.
A->B->D->C
back is
C->B->A

I was able to achieve this with v3 by using type replace. Now on v4 if I use Actions.replace('D') -> then all the scenes in the stack are replaced with scene D and not just the last one. Is there a way to just replace the last one?

**Comment by aksonov** [comment]
Looks like it is the problem of React Navigation:
https://github.com/react-community/react-navigation/issues/774

If you could find solution how to do 'replace'  correctly with react-navigation I could implement it with RNRF.

**Comment by aksonov** [comment]
I have one idea - do Actions.pop and Actions.push for 'replace'. I will try to implement this.

**Comment by compojoom** [comment]
I tried pop and then push, but I'm not sure if it was my components or what, but I was running in a "max execution callstack" error.

**Comment by aksonov** [comment]
OK, I will try for Example.

**Comment by aksonov** [comment]
@compojoom Could you check latest master?

**Comment by itinance** [comment]
Have you unpublished beta11 and beta12? We got an empty folder after "npm install" of an other library and while reinstalling neither beta11 nor beta12 can be found on npm.

**Comment by aksonov** [comment]
Have you tried `4.0.0-beta.12` ?

**Comment by itinance** [comment]
ooops.... thx! don't know how it could work without the dot yesterday (or the dev was on del-key)^^
However, can you tell pls the roadmap for 4.0.0 - non-beta?

**Comment by aksonov** [comment]
It would be a little bit strange to remove beta if react-navigation is still in beta, what do you think?
I would like to remove beta once we will have one week without bugs. But how to deal with react-navigation bugs (like bugs with tab bar)

**Comment by itinance** [comment]
yes, wouldn't think that. thats why i was asking :) with `git remote show origin` and` git branch` i could see a lot of release-branches but not these both. was a bit confusing.
Originally I ran into this [npm-issue that removes](https://github.com/npm/npm/issues/16839) other dependencies sometimes and lost RNRF and all this got followed up with lots of side-issues... It's clear now :)

**Comment by aksonov** [comment]
Should be fixed with 4.0.0-beta.13

**Comment by aksonov** [comment]
I've just added ActionConst.POP_AND_PUSH action for this (previous REPLACE could be useful to replace root scene)
