### ISSUE TITLE
Drawer w/ Nested Nav and Header Issue

### ISSUE THREAD

**Issue by chrissm79** [aksonov/react-native-router-flux#2103]
I'm having an issue when I'm inside a nested nav stack and pushing from a Drawer page. During the transition the Drawer header gets pushed underneath the next scene's header. Even if I put `hideNavBar` on the Drawer and the internal drawer scene, it pushes the content down during the transition to the next scene. 

The `drawer` and `external` scenes are separated into different stacks because I need to avoid accidentally opening the drawer on the `external` scenes when trying to swipe to go back (something has has plagued me w/ `react-navigation` until this package came along).

Thanks for any help!!

```js
export default App = () => (
  <Router createReducer={reducerCreate} getSceneStyle={getSceneStyle}>
    <Scene key="root" tabs hideTabBar hideNavBar>
      <Scene key="guest" modal initial hideNavBar>
        <Scene key="login" component={Login} initial />
        <Scene key="register" component={Register} />
      </Scene>
      <Scene key="authenticated">
        <Scene key="drawer" drawer hideNavBar contentComponent={Drawer} initial>
          <Scene key="dashboard" title="Dashboard" component={Dashboard} initial />
        </Scene>
        <Scene key="external" component={External} title="Some External Scene" />
        {/* Additional external scenes... */}
      </Scene>
    </Scene>
  </Router>
)
```

![simulator screen shot jul 24 2017 2 08 47 pm](https://user-images.githubusercontent.com/1976169/28542948-61e1b398-707b-11e7-957c-09c8f50b05ab.png)
![simulator screen shot jul 24 2017 2 27 48 pm](https://user-images.githubusercontent.com/1976169/28543231-5001989a-707c-11e7-9f7f-b069d722a4b2.png)

**Comment by aksonov** [comment]
It is how react-navigation works - you have to use Drawer on top level. Similar to https://github.com/react-community/react-navigation/issues/374 ?

**Comment by webdevsyd** [comment]
Im currently encountering this. Any straight forward solution for this issue? When I click the message `Icon` as you can see below in the code, same thing happen to with my navigation 
Here's what I have.

<img width="625" alt="screen shot 2018-07-16 at 9 57 51 pm" src="https://user-images.githubusercontent.com/15810023/42762620-5c7a8ea2-8943-11e8-87e0-05ace6848469.png">
