### ISSUE TITLE
Proper way of using onEnter / success?

### ISSUE THREAD

**Issue by EnriqueDev** [aksonov/react-native-router-flux#2109]
Hi! First of all congratulations for this awesome work you have done so far, it has been very useful. I would like to know what is the correct way to use the onEnter/success props of the scene and if can I call component methods from there. 

Thanks. 

PD: If someone explains it properly I could maybe write a doc/example and make a pull request.

**Comment by aksonov** [comment]
You can call static function onEnter of component or just pass it as prop to Scene. If it returns non-null value RNRF makes automatic transition to scene defined by `success` (`failure` otherwise)

**Comment by aksonov** [comment]
Sorry, no access to component methods - it just accesses to your navigation state, like navBar static methods.

**Comment by EnriqueDev** [comment]
So inside my component I should call:

```
static onEnter = (callback) => {
    callback()
}
```

?

**Comment by aksonov** [comment]
Current state params are passed to onEnter. So you could try to pass callback, like
`Actions.login({callback})` and then your `onEnter` will be executed with `{callback}` param.

**Comment by EnriqueDev** [comment]
My main problem here is that as ReactNavigation does not unmount tabs, all the component's lifecycle methods are not called and it's impossible to perform requests in the usual place. Using the current API v4 what would you recommend as an approach (not code, I just need some guidance).

Thanks for your time!

**Comment by aksonov** [comment]
I believe `onEnter` is way to go. Another way is to use `type=replace` instead of tabs, so your scenes will be unmounted.

**Comment by EnriqueDev** [comment]
good enough. Is there a way use lazy when using TabNavigator?

**Comment by aksonov** [comment]
Yes, just pass lazy prop

**Comment by EnriqueDev** [comment]
Awesome. Thank you so much!
