### ISSUE TITLE
DrawerIcons disables DrawerImage

### ISSUE THREAD

**Issue by bartaveld** [aksonov/react-native-router-flux#2110]
Version:
 -  react-native-router-flux:  ^4.0.0-beta.14
 -  react-native-vector-icons:  ^4.2.0

So I used the DrawerImage property to change the hamburger Icon on the NavBar and it worked.

`
    <Router>
        <Scene key="root">
            
            {/*Login  */}
            <Scene key="login"
            component={LoginScreen}
            title="Login"
            type="reset"
            hideNavBar
            initial/>

            {/*Home  */}
            <Scene
            key='drawer'
            drawer={true}
            contentComponent={DrawerComponent}
            hideBackImage
            drawerImage = {Hamburger}
            hideNavBar>
              <Scene 
              key="order"
              component={OrderScreen}
              DrawerIcon = {Hamburger}
              title="Order"
              /> 
              <Scene 
              key="information"
              component={OrderScreen}
              title="Information"/>
              <Scene 
              key="account"
              component={OrderScreen}
              title="Account"/>
              <Scene 
              key="settings"
              component={OrderScreen}
              title="Settings"/>
              <Scene 
              key="logout"
              component={LogoutScreen}
              onEnter={() => Actions.popTo('login')}
              title="Logout"
              hideNavBar/>
            </Scene>
        </Scene>
    </Router>
`

![DrawerImage](https://user-images.githubusercontent.com/22222143/28575956-bd8b6e1e-7152-11e7-9aaa-5a6d9fc9fb92.png)

Now I want to add DrawerIcons to the childscenes so it shows up in the drawer menu, I did it like this.
`<Scene 
              key="order"
              component={OrderScreen}
              drawerIcon={({ tintColor }) => (
                <Icon
                  name='email'
                  size={24}
                  color={tintColor}
                />)}
              title="Order"
              /> `

and I added this for all childscenes this does what we want:

![result](https://user-images.githubusercontent.com/22222143/28576237-a528820c-7153-11e7-9da9-9ced30bb4737.png)

But the thing is it removes the DrawerImage, so the drawer is not accessible with the click of the button. 

![Gone](https://user-images.githubusercontent.com/22222143/28576281-cba6ff94-7153-11e7-9894-0ad5f03e02a2.png)

Any ideas?

**Comment by aksonov** [comment]
Does it work with pure react-navigation? Is it similar to https://github.com/react-community/react-navigation/issues/374 ?

**Comment by bartaveld** [comment]
In react-navigation it is possible to add a headerleft to get the effect 

`export const HomeStack = StackNavigator ({
    Home: {
        screen: HomeScreen,
        navigationOptions : ({ navigation }) => ({
            title: 'Glasportaal',
            headerTintColor: 'white',
            headerStyle: {
                backgroundColor: '#C62828',
            },
            headerTitleStyle: {
                alignSelf: 'center',
                marginRight: 56
            },
            headerLeft: <View
                        style={styles.icon}> 
                            <Icon 
                            name= 'menu'
                            size = {24} 
                            color = 'white'
                            onPress = { () => navigation.navigate('DrawerOpen') }/>
                        </View>,
        })
    }`

and adding it to my drawer stack

`export const Drawer = DrawerNavigator ({
    HomeScreen: {
        screen: HomeStack,
        navigationOptions : {
            drawerLabel: 'Home',
            drawerIcon: ({ tintColor }) => (
            <Icon
            name= 'email'
            size = {24}
            color = {tintColor}
            />
        ),
        }
    },
    InformationScreen: {
        screen : InformationStack,
        navigationOptions : {
            drawerLabel: 'Information',
            drawerIcon: ({ tintColor }) => (
            <Icon
            name= 'info'
            size = {24}
            color = {tintColor}
            />
        ),
        }
    },
    AccountScreen: {
        screen : AccountStack,
        navigationOptions : {
            drawerLabel: 'Account',
            drawerIcon: ({ tintColor }) => (
            <Icon
            name= 'person'
            size = {24}
            color = {tintColor}
            />
        ),
        }
    },
    SettingsScreen: {
        screen : SettingsStack,
        navigationOptions : {
            drawerLabel: 'Settings',
            drawerIcon: ({ tintColor }) => (
            <Icon
            name= 'settings'
            size = {24}
            color = {tintColor}
            />
        ),
        }
    }, LogoutScreen: {
        screen : LogoutStack,
        navigationOptions : {
            drawerLabel: 'Logout',
            drawerIcon: ({ tintColor }) => (
            <Icon
            name= 'exit-to-app'
            size = {24}
            color = {tintColor}
            />
        ),
        }
    }
},{
    contentOptions:{
        activeTintColor: '#FFB300',
    },
    drawerWidth: 250,
    contentComponent: props => 
    <View>
        <View style={styles.container}>
        <View style={styles.drawerIconContainer}>
            <Icon 
            name= 'account-circle'
            size= {46}
            color= 'white'
            />
            <Text style={styles.drawerText}>dummyaccount@live.nl</Text>
        </View>
        </View>
        <DrawerItems {...props}/>
    </View>
})`

**Comment by aksonov** [comment]
RNRF uses headerLeft as well. Maybe the reason is in missed drawerIcon? Is it required to pass to drawer? Looks like RNRF doesn't use it...

**Comment by bartaveld** [comment]
So you are saying I should add a drawerIcon here aswell?

```
 <Scene
        key='drawer'
        drawer={true}
        contentComponent={DrawerComponent}
        hideBackImage
        drawerIcon = ... //Like this?
        drawerImage = {Hamburger}
        hideNavBar>
```

**Comment by aksonov** [comment]
I'm just thinking. Yes, try that. Also try to remove icon from pure react nav solution

**Comment by bartaveld** [comment]
If I removed the icons from the pure react nav solution there just wouldn't be any icons in the drawer..

**Comment by bartaveld** [comment]
```
 <Scene
                        key='drawer'
                        drawer={true}
                        contentComponent={DrawerComponent}
                        hideBackImage
                        drawerIcon= {null}
                        drawerImage={Hamburger}
                        hideNavBar
                        contentOptions={{ activeTintColor: Colors.ACCENT }}>
                        <Scene
                            key="order"
                            component={OrderScreen}
                            drawerIcon= {({ tintColor }) => (
                            <Icon name= 'email' size = {24} color = {tintColor}/>)}
                            title="Order" />
```

still makes the drawerimage disapear

**Comment by bartaveld** [comment]
```
{/*Home  */}
                    <Scene
                        key='drawer'
                        drawer={true}
                        contentComponent={DrawerComponent}
                        hideBackImage
                        drawerIcon= {({ tintColor }) => (
                        <Icon name= 'email' size = {24} color = {tintColor}/>)}
                        drawerImage={Hamburger}
                        hideNavBar
                        contentOptions={{ activeTintColor: Colors.ACCENT }}>
                        <Scene
                            key="order"
                            component={OrderScreen}
                            title="Order" />
```

And this just makes every icon 'email' and still removes drawerImage

![image](https://user-images.githubusercontent.com/22222143/28609840-8471f708-71e6-11e7-84b6-bcbcc75fb76e.png)

![image](https://user-images.githubusercontent.com/22222143/28609858-94f2e984-71e6-11e7-9887-8b7e0106bc95.png)

**Comment by bartaveld** [comment]
Is this a bug or should I do something different?

**Comment by aksonov** [comment]
Probably it is a bug, but it is difficult for me to find the reason. Please fork & modify Example project to demonstrate the issue.

**Comment by bartaveld** [comment]
I fixed my issue by using the unicode for a menu icon 

```
  {/*Home  */}
                    <Scene
                        key='drawer'
                        drawer={true}
                        contentComponent={DrawerComponent}
                        hideNavBar
                        onLeft = {() =>  Actions.drawerOpen()}
                        leftTitle='&#9776;'
                        leftButtonTextStyle={styles.Hamburger}
                        contentOptions={{ activeTintColor: Colors.ACCENT }}>
```

**Comment by bartaveld** [comment]
You can even just put a <Icon> from 'React-native-vector-icon'

```
 <Scene
                        key='drawer'
                        drawer={true}
                        contentComponent={DrawerComponent}
                        hideNavBar
                        onLeft = {() =>  Actions.drawerOpen()}
                        leftTitle= {({ color }) => (
                        <Icon name= 'menu' size = {24} color = {color}/>)}
                        leftButtonTextStyle={styles.Hamburger}
                        contentOptions={{ activeTintColor: Colors.ACCENT }}>
```

**Comment by aksonov** [comment]
Close due forked repo was not given.

**Comment by bartaveld** [comment]
Sorry I don't have the time to give a forked repo
