### ISSUE TITLE
renderTitle image not shown on all device

### ISSUE THREAD

**Issue by PumpkinSeed** [aksonov/react-native-router-flux#2111]
`"react-native-router-flux": "3.38.0"`

I rendered the title as an image: 

```
const logo = require('../media/logo.png');
const NavBarImage = () => {
    return (
        <View style={{ alignItems: 'center', marginTop: 16 }}>
            <Image
                style={{ width: 200, height: 24 }}
                source={logo}
            />
        </View>
    );
};
```
But there is few phone where the image not shown. I tested on Sony Xperia XZ, OnPlus 3G and it was there, but on OnePlus 2 it isn't. The other images which is loaded on the same way to the application (like `const logo = require('../media/logo.png');`) working properly only the renderTitle have this error. 

Do you have any idea why is it happening?

**Comment by aksonov** [comment]
v3 is not supported, sorry. Please try v4.

**Comment by PumpkinSeed** [comment]
I didn't found any stable version under v4. I got the BackHandler error like the #1894  and I think it is using newer React Native which is breaking some other dependency. 

Thank you, but I think currently my application not supporting the v4.
