### ISSUE TITLE
Unable to overlay the tabbed navigation view

### ISSUE THREAD

**Issue by JoshStaff** [aksonov/react-native-router-flux#2112]
Hi all,

Having a nightmare with what should relatively simple. I'm attempting to overlay the Tabbed navigation with a View which animates via a button press – However I am unable to get the tabbed navigation to sit behind no matter what I do. I'm wondering if I am missing something and/or there is a major difference between the tabbed navigation and the ordinary navigation as it works fine with the latter.

**Comment by aksonov** [comment]
Could you fork & modify Example project to show the problem? Are you able to achieve your goal via pure react-navigation?

**Comment by JoshStaff** [comment]
I'll do the above when I get a mo. It's incredibly frustrating as it should be extremely simple. If it isn't immediately obvious to you I think it'll be something to do with react-navigation. I'll look further into this asap.

**Comment by aksonov** [comment]
Closed due inactivity.
