### ISSUE TITLE
[Question] Share a Scene

### ISSUE THREAD

**Issue by dittmarconsulting** [aksonov/react-native-router-flux#2114]
I have been working with RNRF for over 6 months now and about to release the first Android/iOS app to the store. It's time for refactoring.

I'm wondering whether I can open a scene that is not a child scene? Here a simple example in pseudocode:

```
<Root Scene>
   | -- <Anonymous Scene>
   |        | -- <Child Scene 1/> -----> open Shared Scene 1
   |        | -- <Child Scene 2/> -----> open Shared Scene 2
   |     <Anonymous Scene/>
   | 
   | -- <Authorised Scene>
   |        | -- <Child Scene 1/> -----> open Shared Scene 1
   |        | -- <Child Scene 2/> -----> open Shared Scene 2
   |    <Authorised Scene/>
   |
   | -- <Shared Scene 1/>
   | -- <Shared Scene 2/>
</Root Scene>
``` 
At the moment I have to have a copy of the `<Shared Scene 1/>` and `<Shared Scene 2/>` in each folder, which is against the reusability principle.

In a real world application `<Shared Scene 1/>` could be the **About** page and `<Shared Scene 2/>` could be the **Privacy Policy** page for instance, which need to be accessible from a user that has not been logged in as well as from a user that is logged in.

**Comment by aksonov** [comment]
Just use `clone` for shared scenes.

**Comment by dittmarconsulting** [comment]
Thanks Pavel for the quick reply.

Do you have an example code how to accomplish that? Do I leave the same scene structure as above and just assign the `clone` property to the `<Shared Scene 1/>` & `<Shared Scene 1/>` scenes?
