### ISSUE TITLE
Не отображается хэдэр

### ISSUE THREAD

**Issue by impuulse** [aksonov/react-native-router-flux#2116]
Приветствую, такая ситуация:
если ставлю initial тут : 
```
<Router>
      <Scene key="loginForm" component={LoginForm} hideNavBar={true}/>
      <Scene key="selectScene" component={SelectScene} hideNavBar={true}/>
      <Scene key="pastingList" component={PastingList} title="Расписание" titleStyle={{color: '#fff'}} navigationBarStyle={{backgroundColor: '#150529'}} initial/>
    </Router>
```

То все ок, но если убрать initial и пройти до экрана pastingList там просто белое поле
http://joxi.ru/823zwJbc69bWYm
так если initial проставить экрану http://joxi.ru/GrqvqEziN4Eaam
перехожу на этот экран - так <TouchableOpacity onPress={() => Actions.pastingList()}>

Не знаете в чем может быть проблема?

**Comment by aksonov** [comment]
English please.
