### ISSUE TITLE
Header not not displayed

### ISSUE THREAD

**Issue by impuulse** [aksonov/react-native-router-flux#2117]
Hello, if i set initial here: 
```
<Router>
      <Scene key="loginForm" component={LoginForm} hideNavBar={true}/>
      <Scene key="selectScene" component={SelectScene} hideNavBar={true}/>
      <Scene key="pastingList" component={PastingList} title="Расписание" titleStyle={{color: '#fff'}} navigationBarStyle={{backgroundColor: '#150529'}} initial/>
</Router>
```
Header is ok, http://joxi.ru/GrqvqEziN4Eaam , but when initial not set and go to pastingList via 
<TouchableOpacity onPress={() => Actions.pastingList()}> it's white screen
http://joxi.ru/823zwJbc69bWYm
Can u help me?

**Comment by aksonov** [comment]
What version? v4 is only supported now and it requires to have one, root container Scene as child for Router.

**Comment by impuulse** [comment]
Yes last version, like this? 
```
<Router>
      <Scene key="root">
        <Scene key="loginForm" component={LoginForm} hideNavBar={true}/>
        <Scene key="selectScene" component={SelectScene} hideNavBar={true}/>
        <Scene key="pastingList" component={PastingList} title="Расписание" titleStyle={{color: '#fff'}} navigationBarStyle={{backgroundColor: '#150529'}}/>
      </Scene>
    </Router>
```
also not work :(

**Comment by aksonov** [comment]
Please record animated gif. You may check also Example project that has hidden nav bar.

**Comment by impuulse** [comment]
https://youtu.be/XQm78UnecGk

**Comment by aksonov** [comment]
I see, but it is difficult to understand the reason. Do you see any white screen on Example project? Please fork & modify Example accordingly so I could look at source code.

**Comment by aksonov** [comment]
Closed due inactivity. Btw, try to set `headerMode='screen'` when you are moving from hidden navbar to shown navbar to avoid any flickering (default iOS header transition)
