### ISSUE TITLE
How to get the Routing stack?

### ISSUE THREAD

**Issue by sds311** [aksonov/react-native-router-flux#2118]
I want register the <Router>'s backAndroidHandler event , like Following Code:

<Router backAndroidHandler={
(navProps)=>{ console.log(navProps.navigationState); }
} />,

but , this function Not a bit of navProps , why not injection this parameters, so, how I get the navigationState in backAndroidHandler function,  how use the backAndroidHandler function at the difference Scenes show  to run the defference logic code?

**Comment by aksonov** [comment]
duplicate of #2122
