### ISSUE TITLE
Does any one have an example app using RNRF & Mobx?

### ISSUE THREAD

**Issue by keith527** [aksonov/react-native-router-flux#2120]
I am a react-native coder, recently,I want to use the new version RNRF and Mobx to my new App.But,I am not good at mobx, also, I do not know more about RNRF v4, I couldn't understand the documents clearly. 
Any one have a example app use these(RNRF v4 & Mobx) or show me a link to learn these?
Thanks .

**Comment by scriptfans** [comment]
+ 1 for this.
