### ISSUE TITLE
onLeft() or onRight() use compoent function?

### ISSUE THREAD

**Issue by shiqian123** [aksonov/react-native-router-flux#2121]
If this method is inside the component, is there a way to call it? with onRight,

**Comment by aksonov** [comment]
Yes, just define them as `static`

**Comment by shiqian123** [comment]
like this?
login compoent have test11 function,I want used in onLeft
<img width="794" alt="875ed1a4-4a7e-4462-9fde-18cf0181a5f1" src="https://user-images.githubusercontent.com/9497069/28660387-50341980-72e5-11e7-9b6f-4893303d076d.png">

<img width="936" alt="95b7f533-1b29-4178-933f-154391336fd7" src="https://user-images.githubusercontent.com/9497069/28660392-53f9a60c-72e5-11e7-952f-2b843ba8f1c0.png">

**Comment by aksonov** [comment]
Just rename it to onLeft.

**Comment by shiqian123** [comment]
oh ,thanks
