### ISSUE TITLE
Back props & Android back button ?

### ISSUE THREAD

**Issue by RZulfikri** [aksonov/react-native-router-flux#2122]
Hi, i'd like to ask is there any way to handle back button in android like in V3 ? and i'm trying back prop in android but it didn't work. maybe someone can help me.

Thanks.

**Comment by aksonov** [comment]
Could you please post your code for v3? For v4 you could pass custom reducer as shown in Example project and check events.

**Comment by aditya-sodhani** [comment]
@aksonov you duplicated #2118 for #2112 and #2112 for #2118. lol.
