### ISSUE TITLE
renderBackButton not working

### ISSUE THREAD

**Issue by bishalshr** [aksonov/react-native-router-flux#2124]
### Version

- react-native-router-flux v4.0.0 (v3 is not supported)
- react-native v0.44.0

Previously there was renderBackButton so that I can hide the back button using Actions.refresh({renderBackButton: () => null}). But it seems like this thing is not supported in v4. So, are there any ways to do this?

**Comment by aksonov** [comment]
Could you try to set `init` prop ?
