### ISSUE TITLE
how to add a custom navigation bar with a leftbutton and multiple right buttons  

### ISSUE THREAD

**Issue by adarshTS** [aksonov/react-native-router-flux#2125]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.14 (v3 is not supported)
- react-native v0.46.4

**Comment by aksonov** [comment]
You may pass `navBar` property and render whatever you want for whole nav bar. Or you could pass `left` /`right` to render left/right Buttons

**Comment by adarshTS** [comment]
can we pass 2 images in navBar property for 2 right buttons

**Comment by adarshTS** [comment]
this is my code :
how can I add 2 right buttons to this or how can I use a custom navBar instead 

`import React from 'react';
import { Scene, Router } from 'react-native-router-flux';
import mainScreen from './components/mainScreen';
import challengeScreen from './components/challengeScreen';

const RouterComponent = () => {
  return (
    <Router>
    <Scene key="root">
    <Scene key="homeScreen" component={mainScreen} navTransparent={1} />
    <Scene
     key="screen2" component={challengeScreen} navTransparent={1}
     leftButtonImage={require('./components/Images/bg_inner.png')} headerTintColor="white"
     />
    </Scene>
    </Router>
  );
};
export default RouterComponent;
`

**Comment by aksonov** [comment]
There is no such option. You may submit PR to support it, like passing `right` as array for buttons. But it is better just to put two button inside `right`

**Comment by adarshTS** [comment]
how can we use navBar property to add multiple buttons

**Comment by adarshTS** [comment]
hey I sorted out that issue, 
In my Router.js file, I created a navBar property and gave it my NavBar.js file to it like navBar={NavBar} and inside my NavBar.js file I  have customized the buttons that I needed on both left and right sides 

hope this might help someone 

and thanks @aksonov

**Comment by itokonoha** [comment]
Hi, I am Ito,

**Comment by adarshTS** [comment]
Refer this: [https://stackoverflow.com/questions/42479184/customizing-default-navigation-bar-of-react-native-router-flux/45372828#45372828](https://stackoverflow.com/questions/42479184/customizing-default-navigation-bar-of-react-native-router-flux/45372828#45372828)

**Comment by wkwyatt** [comment]
@adarshTS I tried something similar but the navigation bar would not render.  Did you do something special in the Router.js to get the custom navbar to render?

**Comment by adarshTS** [comment]
@wkwyatt I did this : ` <Scene
     key="screen2" component={challengeScreen} navTransparent={1}
     navBar={NavBar}
       />` in the Router.js file where NavBar is the custom navbar that I created and don't forget to import `import NavBar from './components/NavBar';`

**Comment by wkwyatt** [comment]
Thanks 👍🏽 I got it working!

**Comment by aaron25mt** [comment]
V4, I just put my two buttons in a View and applied flexDirection row style on them and that worked for me.

`let navButtons = <View style={{flexDirection: "row"}}>
        <Button icon transparent onPress={this.search}>
          <Icon name="search"></Icon>
        </Button>
        <Button icon transparent onPress={this.showCart}>
          <Icon name="cart"></Icon>
        </Button>
      </View>`
