### ISSUE TITLE
How to wait until the scene is refreshed?

### ISSUE THREAD

**Issue by faost** [aksonov/react-native-router-flux#2126]
- react-native-router-flux v4.0.0-beta.1
- react-native v0.42.0

I want to do something like this:

```javascript
Actions.refresh({
  foo: 'bar'
}, () => {
  console.log(this.props.foo); // is 'bar'
});
```
Similar to setState callback https://facebook.github.io/react/docs/react-component.html#setstate:

```javascript
this.setState({
  foo: 'bar',
}, () => {
  console.log('a = ', this.state.a);
});
```

**Comment by aksonov** [comment]
Actually state is changed immediately, after that scene will be re-rendered according to the new state. So you could just to use `componentWilReceiveProps` for this.
