### ISSUE TITLE
Clear history stack without route change?

### ISSUE THREAD

**Issue by gmverdon** [aksonov/react-native-router-flux#2127]
- react-native-router-flux v4.0.0 

Is it possible clear the history stack and eliminate the navbar back button, without doing a route change. 

Example:

When I open the app I am on the initial screen. I push a new screen on top of the initial screen. The new screen has a button which says 'Clear history stack'. When I click on the button I want to stay on the same page (so no route switch), but clear the history stack so it is not possible to go back to the previous screen (the initial screen).

Thanks in advance.

**Comment by aksonov** [comment]
Try `Actions.ROUTE_NAME({type: 'replace'})` where ROUTE_NAME is name of current route.

**Comment by aksonov** [comment]
Closed because of inactivity.
