### ISSUE TITLE
Support for custom component for NavBar

### ISSUE THREAD

**Issue by priyank2005** [aksonov/react-native-router-flux#2128]
### Version
- react-native-router-flux v4.0.0-beta.14
- react-native v0.46.4

### Expected behaviour
Support for custom component for NavBar

### Actual behaviour
Navbar custom component cannot be used, thus cannot have an ios 11 style heading.

**Comment by aksonov** [comment]
Could you clarify? Does react-navigation support it?

**Comment by aksonov** [comment]
Closed due inactivity
