### ISSUE TITLE
renderRightButton with save button.

### ISSUE THREAD

**Issue by fionita** [aksonov/react-native-router-flux#213]
How to pass data from component form, to the Route.

**Comment by SudoPlz** [comment]
Did you solve this? How ? Could you please share? Thank you.

**Comment by fionita** [comment]
I've hided the router flux navbar and used toolbarAndroid instead.

**Comment by SudoPlz** [comment]
@fionita didn't that result in messy code? If I understand correctly you no longer use the ExperimentalNavigator that comes with the navbar, but you're using `ToolbarAndroid` with Android and `NavigatoriOS` with iOS ? 
So you actually manage the `ToolbarAndroid` and `NavigatoriOS` on each schene seperately?
