### ISSUE TITLE
[Question] renderNavigationBar alternative in v4?

### ISSUE THREAD

**Issue by ChristianTucker** [aksonov/react-native-router-flux#2130]
I was going through the documentation for transitioning from v3 to v4 and I was trying to figure out how to render a custom navigation bar on each screen. While using `hideNavBar={true}` and creating a `<PageContent navigation={() => <NavBar />}>` is definitely a solution that works, I figured there's got to be something similar to `renderNavigationBar` in the new version.

You can close this with your answer, @aksonov  I'll make sure to check my email to see that you replied. Thanks.

**Comment by aksonov** [comment]
I will add it. You could use shorter syntax for now - `navBar`
