### ISSUE TITLE
navigationBarStyle or navTransparent and also navigationBarStyle={[STYLES.navBar]} is not working while trying to make the custom navigation bar transparent 

### ISSUE THREAD

**Issue by adarshTS** [aksonov/react-native-router-flux#2132]
### Version
- react-native-router-flux v4.0.0-beta.14 (v3 is not supported)
- react-native v0.46.4
-react-native-router-flux-nav-bar v1.1.0

### Expected behaviour

transparent navigationbar background

### Actual behaviour
white color background in the navigation bar

**Comment by aksonov** [comment]
Probably issue with react-navigation. Please check pure react-navigation examples and try to make transparent navbar there. If you are able to do it then send me the link.

**Comment by adarshTS** [comment]
Here's something that I found : [https://github.com/react-community/react-navigation/issues/312]
But it didn't work with my project and I didn't install react-navigation but still, I don't think that it will work

**Comment by aksonov** [comment]
Yes, I used this for `navTransparent` and it works well.

**Comment by aksonov** [comment]
But I didn't tried for custom nav bar.

**Comment by adarshTS** [comment]
yes navTransparent worked well for me in default navigation bar but it didnt work in custom nav bar

**Comment by aksonov** [comment]
Then you must check pure react-navigation first. It has navigationOptions.header option for custom navbar (header).

**Comment by adarshTS** [comment]
here are the few links that I found referring react-navigation @aksonov [https://reactnavigation.org/docs/navigators/tab#tabBarVisible](url)
[https://reactnavigation.org/docs/navigators/stack#header](url)
can I make my custom navbar transparent without changing from RNRF to React-navigation

**Comment by aksonov** [comment]
`tabBarVisible`? Try to do it with React-Navigation. If it is possible, it could be easy done with RNRF.

**Comment by adarshTS** [comment]
@aksonov What I observed is that when I  change it to any other color the background of the navigation bar is changing but when we are trying to make it transparent it changes into white why is it so? for making it transparent I tried these : `backgroundColor: 'transparent'`  and `backgroundColor: 'rgba(52, 52, 52, 0.8)'`

this is what I get now 
![navbar](https://user-images.githubusercontent.com/22904766/28761861-6272514c-75cf-11e7-9e93-8f4c826555ad.jpg)

**Comment by aksonov** [comment]
Could you try pure react-navigation? If it has this issue, it is react-navigation bug, create ticket there.

**Comment by adarshTS** [comment]
@aksonov will this help in making the navBar transparent 
[https://github.com/aksonov/react-native-router-flux/pull/1476](url)

**Comment by aksonov** [comment]
It is unknown when it will be done for v4.

**Comment by aksonov** [comment]
Have you looked at https://github.com/react-community/react-navigation/issues/716 ?

**Comment by adarshTS** [comment]
@aksonov 
I was facing some issues in react-navigation I couldnt navigate properly in react navigation and thats why i switched to RNRF but we could hide the default navBar 

Can u make help in making changes and see if its getting transparent  in my project  [](https://github.com/adarshTS/bookCricket-app)
 I am just a beginner can u please help
