### ISSUE TITLE
[Feature] Deep Linking Support

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2137]
Hello!

I've seen comments here: https://github.com/aksonov/react-native-router-flux/issues/704

Can someone add deep linking in v4?

I'll try to play around. Maybe someone already has working code?

**Comment by aksonov** [comment]
Okey, I added `path` passing to react-navigation, but it doesn't work good. react-navigation router doesn't return any action for deep nodes, only for top level. Also it creates several pushes for some reason... You need to debug react-navigation code to make it work. Check PR above, you may open login popup using `xcrun simctl openurl booted mychat://login/123`, but it pushes two login screens for some reason.

**Comment by kesha-antonov** [comment]
Thanks!

**Comment by luco** [comment]
This would be awesome.

**Comment by luco** [comment]
Any updates?

**Comment by shukerullah** [comment]
Any updates on this?

**Comment by thg303** [comment]
I need deep linking! :(

**Comment by luco** [comment]
Is there any workaround for deep link while we wait?

**Comment by thg303** [comment]
I used react-router. it supports deep linking

**Comment by willymulyana** [comment]
Try to use `crossroads ` follow this: [http://ihor.burlachenko.com/deep-linking-with-react-native/](url). I was try it with v4 and it works well. Hope it help.

**Comment by pewh** [comment]
@willymulyana the link is broken

**Comment by jasongrishkoff** [comment]
@pewh here's a working link: [http://ihor.burlachenko.com/deep-linking-with-react-native/](http://ihor.burlachenko.com/deep-linking-with-react-native/)

**Comment by dittmarconsulting** [comment]
Hi @jasongrishkoff have you tried to send the URL via email or SMS and close the app (iOS swipe up) What happens when you click the link? Will it just open the app or open the app and go to the "Hello World" scene?

**Comment by kesha-antonov** [comment]
https://github.com/aksonov/react-native-router-flux/pull/2148#issuecomment-342881209

Thanks! @aksonov
