### ISSUE TITLE
How to hide drawer for specific scenes

### ISSUE THREAD

**Issue by Shubham-Sinha** [aksonov/react-native-router-flux#2142]
### Version
- react-native-router-flux v4.0.0-beta.14.
- react-native v0.46.3

### Expected behaviour

Drawer shouldn't be visible on some scenes.

### Actual behaviour

If Scene with key as 'root' is child of Scene with drawer, the drawer is always accessible.
### Steps to reproduce
I have a specific use case and that is of authentication ( common concern  )
1. Set up routes as in Example
2. Use hideNavBar and hideTabbar to desiguise a scene as not accessible to unauthenticated user.
3. Swipe to access drawer even for non-authenticated user.

**Comment by aksonov** [comment]
Hm, it seems wrong design decision - have you tried to put drawer lower, it should not be parent of unauthenticated screen.

**Comment by Shubham-Sinha** [comment]
![initial code](https://preview.ibb.co/iAHrUk/rnrf_previous.png)

When I put drawer lower

![code lower](https://preview.ibb.co/d3apFQ/drawer_down.png)

I get following error :

![error](https://preview.ibb.co/jO9c25/error_drawer.png)

**Comment by aksonov** [comment]
I can't help with external code, only with Example project from this repo. Check latest master, I moved drawer

**Comment by chrissm79** [comment]
@aksonov I just tried the new example project and it indeed lets you navigate to the `echo` scene without throwing the `no route defined` error. However, the swipe to go back gesture will instead open the drawer. Based on the router's structure it would seem that the `echo` scene is in a different stack (not nested in with the `drawer`) which shouldn't allow you to open the drawer (or at least that's what I assume when looking at the router).

To be fair, I don't know how to resolve this issue in `react-navigation` either as I can't find a way to pass params down to a nested screen on another navigator (and also keeping the back button) so this is a big help to me, just wondering if there's a way to navigate away from the `drawer` while keeping the swipe to go back gesture (as well as the back button).

Thanks, the package is 💯 !

**Comment by warrenronsiek** [comment]
Same problem here. 

To recreate in Example project move the drawer to wrap only the register scene and then add a custom 'onBack' function to navigate to the base registration scene (or any other scene e.g. tabbar):

```
<Router createReducer={reducerCreate}>
    <Scene key="lightbox" lightbox>
      <Scene key="modal" modal hideNavBar>
        <Scene key="root" hideNavBar>
         <Scene key="echo" back clone component={EchoView} 
                       getTitle={({navigation}) => navigation.state.key}/>
          <Scene key="drawer" drawer drawerPosition="right" contentComponent={TabView}>
           <Scene key="register" back>
             <Scene key="_register" component={Register} title="Register"/>
             <Scene key="register2" component={Register} title="Register2" 
                           back onBack={() => Actions.register({type: 'reset'})}/>
             <Scene key="home" component={Home} title="Replace" type='replace'/>
           </Scene>
          </Scene>
```
This will result in the following error:

<img width="277" alt="screen shot 2017-08-05 at 10 50 45 pm" src="https://user-images.githubusercontent.com/9755852/29000959-a75e79a6-7a30-11e7-8e91-17a33bf073cf.png">

**Comment by aksonov** [comment]
@warrenronsiek So problem with 'reset' type, but not with drawer, right? Probably you have to use 'replace' instead, because reset clears stack entirely.

**Comment by warrenronsiek** [comment]
@aksonov Tried using 'replace' instead, still get a 'route not defined' error. So it probably isn't just the 'reset' type. I don't know if that means the problem is the drawer or the actions. 

**Additional addendum**
Adding a 'hideNavBar' to the drawerRoot will remove the duplicated NavBar described above. So it looks like a structure in the  'potential solution' solves all the problems so long as it doesn't pass any action types when navigating within a drawer.

**Comment by aksonov** [comment]
@warrenronsiek There were real issues with 'replace' because react-navigation doesn't have it and their 'reset' doesn't work well for deep nested containers. Finally I implement it by myself within RNRF, please check latest master, see #2189
