### ISSUE TITLE
How to use both left and right drawer in v4?

### ISSUE THREAD

**Issue by harmeetv** [aksonov/react-native-router-flux#2144]
`<Scene key="main" drawer contentComponent={MainDrawer} hideNavBar>`
`<Scene key="main2" drawer contentComponent={MainDrawer} hideNavBar drawerPosition="right">`
`    <Scene key="mainScreen" component={MainScreen} title="Main Screen" hideNavBar />`
`</Scene>`
`</Scene>`

I want 2 drawers in single screen and above is the code I am using. When I close the left drawer 2nd drawer automaticaly opens.

**Comment by aksonov** [comment]
Looks like it is open issue for react-navigation: https://github.com/react-community/react-navigation/issues/780

Maybe we could maintain own DrawerNavigator and include proposed PR into RNRF. Feel free to submit PR to include this functionality
