### ISSUE TITLE
4.0.0-beta.14 mobx strict-mode is enabled bug

### ISSUE THREAD

**Issue by astulip** [aksonov/react-native-router-flux#2145]
console.error: "Error handling:Error: [mobx] Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an action if this change is intended. Tried to modify: NavigationStore@4._onEnterHandlerExecuted"

version: 4.0.0-beta.14

**Comment by aksonov** [comment]
Could you try latest master version?

**Comment by astulip** [comment]
I am through the version of the installation of yarn, it is not easy to test. If you follow the latest release version. I can try. I have now closed mobx strict mode

**Comment by aksonov** [comment]
I'm going to publish new version today (beta.15)

**Comment by astulip** [comment]
Okay, after i'm released, I'll try it.

**Comment by aksonov** [comment]
Closing now, feel free to open if it will happen with beta.15
