### ISSUE TITLE
header onBack bug?

### ISSUE THREAD

**Issue by astulip** [aksonov/react-native-router-flux#2146]
`export default props => (
    <Scene key="root" hideNavBar>
        <Scene
            key="home" tabs
            initial={props.initKey === 'home'}
            tabBarComponent={TabBarBottom} >
            <Scene tabBarIcon={welcomeIcon} key="homeWelcome" tabBarLabel="Welcome" component={Welcome}  title="React Native"/>
            <Scene tabBarIcon={homeIcon} key="homeIndex" title="home" tabBarLabel="home" component={HomeScene}/>
            <Scene tabBarIcon={imIcon} key="homeIm" title="im" tabBarLabel="im" component={ImScene}/>
            <Scene tabBarIcon={meIcon} key="homeMe" title="me" tabBarLabel="me" component={MeScene}/>
        </Scene>
        <Scene
            key="sub" hideTabBar
            initial={props.initKey === 'subLogin'}
            headerStyle={styles.headerStyle}
            headerTitleStyle={styles.headerTitleStyle}
            tintColor={mainColors.sub.headerTitleColor} >
            <Scene key="subLogin" component={Login} hideNavBar/>
            <Scene key="subIOS" component={IOS} title="iOS" />
            <Scene key="subAndroid" component={Android} title="Android"/>
        </Scene>
    </Scene>
)`

I am using the Actions.push ("subAndroid") on the tabs welcome page;
And then click on the subAndroid page header return button, the results are not welcome page welcome page
But the Login page
Is my configuration problem, or bug?

**Comment by aksonov** [comment]
Please try to reproduce on Example project and give me a link.

**Comment by astulip** [comment]
I am in China, do you look at this git address (https://git.oschina.net/stulip/react-native-template) Can you visit?

Project catalog
Adb install build / android / iyimu-main-debug-0.1.17.apk
Yarn && yarn start

Home click Android or iOS text.

**Comment by aksonov** [comment]
Do you see the bug on iOS? I don't have android sdk.

**Comment by astulip** [comment]
There is also this problem.
If you can access my project git. After you update git can run on ios above
Script: react-native run-ios

**Comment by aksonov** [comment]
I can't help here, I could work only with modified Example from this repository, not your projects.

**Comment by astulip** [comment]
Yes, I changed your example:
addcode in TabView.js
`<Button onPress={Actions.home}>home</Button>`
You can reproduce the problem.
Should be Action.pop bug

**Comment by aksonov** [comment]
Home is used to demonstrate 'pop and push' action - it cannot be used for initial scenes like TabView.

**Comment by aksonov** [comment]
It is definitely configuration problem - you are calling screens from another parent tree - so you will be switched to that tree, so back action will return you to parent tree, not your one. You could try to use `clone` scenes so they will be pushed from your current nav tree.
