### ISSUE TITLE
How to make drawer navigation?

### ISSUE THREAD

**Issue by inferusvv** [aksonov/react-native-router-flux#2149]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.14
- react-native v0.46.4

I can't understand how to make navigator with `DrawerLayoutAndroid`.

Here is my code:

```
const Home = (props) => {
  return (
    <View>
      <Text onPress={() => Actions.test({ title: 'hey' })}>
        Home
      </Text>
    </View>
  );
}

const Test = (props) => {
  return (
    <View>
      <Text>Test</Text>
    </View>
  );
}

export default class RouterTest extends Component {
  render() {
    return (
      <Router>
        <Scene>
          <Scene key="drawer" tintColor={'#f00'} drawer component={DrawerLayoutAndroid} renderNavigationView={Test} title={'test'}>
            <Scene key="home" component={Home} title={'Home'} initial />
            <Scene key="test" component={Test} />
          </Scene>
        </Scene>
      </Router>
    );
  }
}
```

Drawer works fine. In navbar I see title `test`. And content is not visible. Just blank page. So what I am doing wrong.

**Comment by Shubham-Sinha** [comment]
You don't have a scene with ``key="root"`` . It will be parent to ``key="home`` and ``key="test"`` . Check Example/Example.js for better understanding

**Comment by aksonov** [comment]
Check breaking changes section, now containers cannot have 'component', but 'contentComponent' instead. And right, check Example project for more details
