### ISSUE TITLE
rerender navigator bar

### ISSUE THREAD

**Issue by InnerPeace080** [aksonov/react-native-router-flux#215]
hello every body.

i want to update content on navigator bar (right button) when some event happen, example click a button in screen.

anyone know how to do this.? 

thank you verymuch

**Comment by oureta** [comment]
Use `renderRightButton` to use an element that is subscribed to the store.

**Comment by aksonov** [comment]
It maybe related to #207 . You could try to use 'jump' action type.

**Comment by aksonov** [comment]
Please try latest 2.3.1 version with new Actions.refresh(props)
