### ISSUE TITLE
can i use it with react-redux  or  it will support redux？？

### ISSUE THREAD

**Issue by SXQJSL** [aksonov/react-native-router-flux#2151]
my project use v3 with redux，but i want upgrade to v4. i find it can`t work with react-redux.so,i have a question,v4 can support redux by some other method?????

**Comment by aksonov** [comment]
v4 (latest 4.0.0-beta.15) provides full redux support (v3 provided partial, 'read-only' support, it was not possible to provide external redux state). PR about new integration is welcome. For now check #2115 and rnrfSample repo provided there.

**Comment by SXQJSL** [comment]
thank u
