### ISSUE TITLE
(Warning) Multiple mobx instances running

### ISSUE THREAD

**Issue by rota-rossi** [aksonov/react-native-router-flux#2155]
Hi, folks. I just added mobx to my RN project, and I'm receiving the warning below. Am I doing something wrong?

> [mobx] Warning: there are multiple mobx instances active. This might lead to unexpected results. See https://github.com/mobxjs/mobx/issues/1082 for details.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.15
- react-native v0.46.4
- mobx v3.2.2
- mobx-react v4.2.2

### Expected behaviour / Actual behaviour
So far, no problems found (except for the warning message)

### The step-by-step
1. added mobx and mobx-react to project
2. added babel-plugin-transform-decorators-legacy to project
3. created a new store (so far, 3 observables and one computed), using decorators
4. add Provider to Project root Component
5. use inject and observer in Components, also using decorators.

**Comment by rota-rossi** [comment]
I 'solved' the issue by downgrading my mobx and mobx-react versions for the same used by RNRF.

**Comment by aksonov** [comment]
Feel free to upgrade RNRF's dependencies and submit PR.

**Comment by rota-rossi** [comment]
I don't know if it would be just that. 
The proper way (as I understood) is actually to change the mobx packages to be a peer dependency here. But this way, the users will need to install by hand mobx and mobx-react, even if they do not plan to use it (peerDependencies are not installed by default).
Should I proceed on this path?

**Comment by aksonov** [comment]
Could you just upgrade dependencies to match latest mobx version, without peerDependencies?

**Comment by aksonov** [comment]
Closed due inactivity
