### ISSUE TITLE
Decorators (MobX) not supported by React Native defaut Babel preset

### ISSUE THREAD

**Issue by rubycon** [aksonov/react-native-router-flux#2156]
### Version
- react-native-router-flux v4.0.0-beta.15
- react-native v0.4.6

After updating to the last version of RNRF my app broke. This was cause by the use of MobX decorators in Router.js (and in other files too). As of now it seems [React Native default Babel presets](https://github.com/facebook/react-native/tree/master/babel-preset) don't handle ES7 decorators.

### Fix
The fix is simple, but this new dependency should be clearly stated in the install section of the readme.
```
npm install babel-plugin-transform-decorators-legacy --save-dev
```
Create a `.babelrc` in your project directory with these options:
```js
{
 "presets": ["react-native"],
 "plugins": ["transform-decorators-legacy"]
}
```

**Comment by aksonov** [comment]
RNRF provides compiled version within `dist` folder. Plugin is necessary only if you want to use source code directly, without transpiling.

**Comment by rubycon** [comment]
Thanks. How do I import the transpiled version directly in my code?

**Comment by aksonov** [comment]
It should be done automatically - RNRF package.json points to dist/index.js, not to src/index.js.
I just removed that plugin from .babelrc for this repo's Example project and run it without any problem. Please check Example project from latest master.

**Comment by aksonov** [comment]
I see `"main": "dist/index.js",` there

**Comment by rubycon** [comment]
Sorry, put the wrong link (that was the 4.0.0-beta.15 tagged branch). I fixed it.

**Comment by aksonov** [comment]
I've fixed package.json now for master

**Comment by rubycon** [comment]
Great! Thank you very much.
