### ISSUE TITLE
Scene Not changing

### ISSUE THREAD

**Issue by emilj858** [aksonov/react-native-router-flux#2157]
"react-native-router-flux": "3.38.0"

Expected Behavior: Scene should change to settings component upon button press.

Actual behavior: Nothing happens, I do see the console.log for the button press though. 

Code: 

`I am trying to add a button to get to my settings component (index.js) from my home component(main screen). For some reason this is not working, I have added different screens before and copied them as an example but I am not having any luck with this. I tripled checked the imports and they all seem good.

Here is what my AppNavigator.js looks like:

    `<Scene key="driverRootView" component={RootView}>
        <Scene key="driverHome" component={DriverHome} />
        <Scene key="startRide" component={StartRide} />
        <Scene key="dropOff" component={DropOff} />
        <Scene key="settings" component={Settings} />
     </Scene>`

Here is the action on my home component (default screen) index.js:

`<Right>
      <Button transparent onPress={() => {
        console.log('settings button')
        Actions.settings()}}>
      <Icon name="ios-settings"
      />`

I can see the console.log message in my terminal so I know the onPress is working.. Any help would be appreciated. I would be happy to share more of the code if needed. Thanks!

**Comment by aksonov** [comment]
V4 is only supported now, sorry
