### ISSUE TITLE
Can't read property 'router' of null #2049

### ISSUE THREAD

**Issue by ranasing** [aksonov/react-native-router-flux#2158]
Sorry, I reposted this because realized that original post was closed.

Can you explain what you mean by this, 'container scene as root'? I am getting the same error. Thanks

Ok, I'm not getting the error any more, but it only shows a blank screen on my Android simulator. Here is the relevant code (**update:**, it gave me a blank screen, but then went back to the old error above reappeared) :

import React, { Component } from 'react';
import { Scene, Router } from 'react-native-router-flux';
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux';
import LoginForm from './components/LoginForm';

render() {
const store = createStore(reducers, {}, applyMiddleware(ReduxThunk));
return (
`<Provider store={store}>
    <Router>
      <Scene key='login' component={LoginForm} title='Login' />
    </Router>
  </Provider>`
);
}

**** Only showing render method, because if I take out components and replace with just LoginForm component, it will render correctly.

**Comment by mikaello** [comment]
I think _container scene as root_ means that you should have a Scene-component directly under Router-component with `key='root` that encapsulates all your other scenes:

```javascript
render() {
  const store = createStore(reducers, {}, applyMiddleware(ReduxThunk));
  return (
    <Provider store={store}>
      <Router>
        <Scene key='root'>
          <Scene key='login' component={LoginForm} title='Login' initial />
        </Scene>
      </Router>
    </Provider>
  );
}
```

**Comment by ranasing** [comment]
Ok thank you! I’ll give that a try.
