### ISSUE TITLE
Is it possible to render navBar at the bottom? Also, disabling 'fade with slide' animation when entering a Scene

### ISSUE THREAD

**Issue by mdusza** [aksonov/react-native-router-flux#2161]
Hello,

I'm using 4.0.0-beta.15.

I'm using my custom navBar component through navBar prop on Router component, and I have 2 simple issues with it that I cannot resolve:

1) Can i make my navBar render on the bottom of the screen?

2) Can I prevent my navBar from animating while changing scenes? Right now it fades in (quite of), and I would like it to hold still at the bottom of the screen all the time.

Thanks in advance

**Comment by aksonov** [comment]
1. Have you tried absolute layout, `bottom:0`  ?
2. Use headerMode='screen' for different animation

**Comment by mdusza** [comment]
@aksonov 
1. yes and it works, I was just wondering if there is a way that won't make me add bottom padding everywhere in order to prevent navbar from overlapping the content.

2. it doesn't change anything, can you tell me where it can be found in the sources? I think I've looked everywhere but didn't find anything...

Thanks in advance

**Comment by aksonov** [comment]
1. You can set global style for all scenes using getSceneStyle or cardStyle option, check Example.
2. headerMode is option for react-navigation StackNavigator, read rn docs about it. You have to set it for container Scene

**Comment by aksonov** [comment]
Closed due inactivity

**Comment by mdusza** [comment]
@aksonov 

Sorry, I didn't have time to focus on that more, but your answer actually helped to get me a better understanding :)

Thanks for a quick help
Cheers
