### ISSUE TITLE
 Actions.popTo not working with beta 15 and above

### ISSUE THREAD

**Issue by d7laungani** [aksonov/react-native-router-flux#2163]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0.beta15 (v3 is not supported)
- react-native v0.45.1

### Expected behaviour
Pops all scenes and and pushes new scene in argument. This works up until beta 11. 

### Actual behaviour

Does nothing

### Steps to reproduce
 Actions.popTo('launch') and this is called from a route inside a tab bar.

-routes.js
```
<Scene key="root" {...sceneConfig} hideNavBar={true} style={{backgroundColor: 'white'}} >
               <Scene key="launch"{...sceneConfig} component={InitialScreen} initial hideNavBar style={{ backgroundColor:'white'}}/>
               <Scene key="login" {...sceneConfig} cardStyle={{backgroundColor: 'white'}} component={Login} title="Login" duration={1}/>
               <Scene key="register" {...sceneConfig}component={Register} duration={1}/>
</Scene>

var sceneConfig = {
   cardStyle: {
       backgrouwndColor: 'white'
   },
   labelStyle: {
       fontFamily: 'open-sans',
   },
   activeTintColor: '#de1d3e',
   inactiveTintColor: 'gray',
   navBarTintColor: 'red',
}
```
       
Is there a new function that needs to be called in the newer versions for this to work?

**Comment by aksonov** [comment]
Thanks, should be fixed now. Please check latest master (Example Login3 page contains popTo)

**Comment by d7laungani** [comment]
Ty, it works now.

**Comment by HemantRMali** [comment]
Action.popTo works fine,

Use it as  **Actions.popTo("sceneName");**

Note: Make sure component name should be in **double quotes**.

**Comment by digitaldavenyc** [comment]
@HemantRMali There is no RNRF `beta.28` yet?

**Comment by digitaldavenyc** [comment]
nvm ... beta.28 is missing from the repo release but was submitted to npm.

**Comment by digitaldavenyc** [comment]
@HemantRMali and @aksonov I'm on 

"react": "16.2.0",
"react-native": "0.53.0",
"react-native-router-flux": "^4.0.0-beta.28"

And `popTo` is still broken. Trying to use it crashes the app.

**Comment by aksonov** [comment]
Sorry, beta.28 is fully experimental and should not be used (some developers asked to publish to fix react-navigation 1.x issues)
