### ISSUE TITLE
Tabbed Scene Jumping Back to first tab

### ISSUE THREAD

**Issue by MakeAndyBetter** [aksonov/react-native-router-flux#2164]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.15 
- react-native v0.46.4

`<Router createReducer={reducerCreate}>
      <Scene key="root">
          <Scene key="t1" tabs title="Tabs">
               <Scene key="t1_1" tabBarLabel="Tab 1" component={Tab1} navigationBarStyle={{height:0}}/>
               <Scene key="t2_2" tabBarLabel="Tab 2" component={Tab1} navigationBarStyle={{height:0}}/>
               <Scene key="t3_3" tabBarLabel="Tab 3" component={Tab1} navigationBarStyle={{height:0}}/>
          </Scene>
      </Scene>
    </Router>`

### Expected behaviour
Tabbed Navigation to stay on current tab.

### Actual behaviour
When the scene is loaded I swipe to a new tab, and then after a few seconds it tabs back to the first tab automatically. 

The time it takes to do this is also the same time it takes to change tab when you press on the tab bar to go to the next tab... which is quite a delay.  

But after that time window it operates as expected

### Steps to reproduce
1. As soon as scene is loaded swipe to next tab
2. Wait a few seconds
3. Scene jumps back to first

**Comment by aksonov** [comment]
Could you check pure react-navigation TabNavigator first? It is possible that the problem is there because RNRF uses react-navigation internally.

**Comment by MakeAndyBetter** [comment]
I started the project with RNRF 3.38 and it worked perfectly apart from being sluggish in debug mode. But also I've noticed that in v4 the tabs mount together where before a tab mounted on request.

**Comment by aksonov** [comment]
Use `lazy` prop for `tabs` Scene

**Comment by MakeAndyBetter** [comment]
Thank you `lazy` helped me not rewrite some redux. Although the automatic tab back is still happening.

**Comment by aksonov** [comment]
>Could you check pure react-navigation TabNavigator first? It is possible that the problem is there because RNRF uses react-navigation internally.

**Comment by MakeAndyBetter** [comment]
I'll give that a try when I've got a little more time on my hands. However it does look like the issue is connected to hot-loading. I'll confirm soonest. Thanks.

**Comment by aksonov** [comment]
Closed due inactivity. Fee free to reopen if any.
