### ISSUE TITLE
Tab bar not showing in Android 

### ISSUE THREAD

**Issue by nakulkundaliya** [aksonov/react-native-router-flux#2165]
Hello @aksonov 

I am facing issue in android. Tabbar doesn't display in android device.  I have checked your demo app code. It's working fine in IOS but, I facing issue in android.

I attached two screenshot 1st is android and 2nd is IOS/

Please help me.

![screenshot at aug 02 14-50-17](https://user-images.githubusercontent.com/15937642/28867118-a695c59c-7792-11e7-8535-be949f5fb7ea.png)
![screenshot at aug 02 14-58-22](https://user-images.githubusercontent.com/15937642/28867269-11b511de-7793-11e7-9a33-59c97803166a.png)

**Comment by mikaello** [comment]
I am experiencing the same thing. Samsung S7, Android 7.0.

**Comment by aksonov** [comment]
Try to run pure react-navigation tab bar demo and check. RNRF just uses react-navigation TabNavigator internally.

**Comment by aksonov** [comment]
https://github.com/react-community/react-navigation/issues/1420

**Comment by nakulkundaliya** [comment]
Thanks for link
But i used **'react-native-router-flux'** from page nevigation. let me know how it's possible to use  '**react-navigation**'

**Comment by aksonov** [comment]
RNRF uses react-navigation internally.

**Comment by nakulkundaliya** [comment]
Okay,
So how Can i fixed it. you have any idea about this?

**Comment by luco** [comment]
It seems that it's something related to styles. In fact, the tabbar appears, but it's not properly styled, as you can see below:

![image](https://user-images.githubusercontent.com/246373/28904750-813b9d2a-77e3-11e7-92c2-9765d3a05639.png)

**Comment by aksonov** [comment]
@nakulkundaliya First I need to know where is the bug - in RNRF or within react-navigation. That is why I asked you to try react-navigation tabbar demos first. If the bug is there, create issue there please.

**Comment by nakulkundaliya** [comment]
@aksonov  i agree @luco tab is appear but not display properly. 
How can i set tabbar at bottom ( Android)?

One more thing if i set `showLabel={true}` then tab is appear with label but its display at top of the screen.

**Comment by aksonov** [comment]
Then probably you have to set proper styling. Definitely react-navigation issue...

**Comment by nakulkundaliya** [comment]
Can you please suggest to me how can i fixed it?

Here is my router code
```
<Scene
  key="tabbar"
  gestureEnabled={false}
  showLabel={false}
  tabs
  tabBarStyle={{backgroundColor:'red',marginTop:50}}
  initial

>
  <Scene key="Home"
    component={Home}
    hideNavBar
    iconName="homeTab"
    icon={TabIcon}
    initial
  />
  <Scene key="Search"
    component={Search}
    hideNavBar
    iconName="searchTab"
    icon={TabIcon}
  />
  <Scene key="AddPhoto"
    component={AddPhoto}
    hideNavBar
    iconName="addPhotoTab"
    icon={TabIcon}
  />
  <Scene key="Activity"
    component={Activity}
    hideNavBar
    iconName="activityTab"
    icon={TabIcon}
  />
  <Scene key="profile"  icon={TabIcon} iconName="profileTab">
    <Scene
      key="profile_1"
      component={Profile}
      hideNavBar
      initial
    />
    <Scene
      key="favourites"
      component={FavouritesSaved}
      title="SAVED"
      renderRightButton={() => <Text>Save</Text>}
    />
  </Scene>
```

**Comment by aksonov** [comment]
I don't have android. Probably set absolute layout for tabbar.

**Comment by nakulkundaliya** [comment]
@aksonov  Finally, i got the solution. 

Need to add `showIcon={true}` in <Scene>

```
<Scene
  key="tabbar"
  gestureEnabled={false}
  showLabel={false}
  tabs
  showIcon={true}
  tabBarPosition='bottom'
  swipeEnabled={false}
  activeTintColor='black'
  activeBackgroundColor='transparent'
  tabBarStyle={{backgroundColor:'black'}}
  initial

>
```

**Comment by mikaello** [comment]
It looks like `showIcon={true}` is default on iOS, but not on Android. See screenshot of Example-app for iOS and Android:
![tabbar_rnrf_ios_android](https://user-images.githubusercontent.com/2505178/28957061-8a16f170-78f0-11e7-83eb-f2ee58132ff8.png)

**Comment by aksonov** [comment]
@mikaello @nakulkundaliya Good catch! Could you submit PR to make it default for both iOS and Android?

**Comment by nakulkundaliya** [comment]
@aksonov  Sure i will do it
