### ISSUE TITLE
Title in navigation bar is not centered in Android (7.0)

### ISSUE THREAD

**Issue by mikaello** [aksonov/react-native-router-flux#2166]
### Version
- react-native-router-flux [v4](https://github.com/aksonov/react-native-router-flux/tree/c029b4f2ae8cb972b4cda365ed8995b191fd5df4) (same version as in Example-app, but also tested with 4.0.0-beta.15 with same result)
- react-native v0.44.0 (also tested v0.46)

- Samsung S7
- Android 7.0

### Expected behaviour

Title in navigation bar to be centered in both iOS and Android

### Actual behaviour

Title in navigaton bar is not centered in Android (but is centered in iOS).

**Android (wrong):**
![router_flux_not_centered_title](https://user-images.githubusercontent.com/2505178/28869603-95529180-777d-11e7-8ca3-2e9567329569.png)

**iOS (correct):**
![router_flux_ios_centered_title](https://user-images.githubusercontent.com/2505178/28869606-97ef3c40-777d-11e7-84a3-85a31852b775.png)

### Steps to reproduce

You can use the Example app:

```bash
# Get the code
git clone git@github.com:aksonov/react-native-router-flux.git
cd react-native-router-flux/Example

# Install dependencies
yarn

# Run it
react-native run-android
```

I have tried to center the title by adding centering-styles to `titleStyle`- and `headerStyle`-props, but with no result. The best I can do is adding Android-specific left-padding/margin to `titleStyle` to make it centered, but that is difficult with different titles and different screen sizes.

**Comment by aksonov** [comment]
https://github.com/react-community/react-navigation/issues/253

**Comment by mikaello** [comment]
Ah, thanks! 

```javascript
<Scene
  ...
  titleStyle={{alignSelf: 'center'}} 
/>
```
... solved the issue.

**Comment by mikaello** [comment]
I created a PR #2172 with the example updated with this prop, if that is wanted in the example.

**Comment by krishan-kumar-mourya** [comment]
For me it worked with 
`<Scene
    ...
    titleStyle={{ textAlign: 'center', flex: 1 }}
/>`
