### ISSUE TITLE
No option to change default indicator style color of yellow in Tab bar on android

### ISSUE THREAD

**Issue by d7laungani** [aksonov/react-native-router-flux#2171]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0.beta 15 (v3 is not supported)
- react-native v0.45.1

### Expected behaviour

Indicator style changes to color #de1d3e

### Actual behaviour

 The default indicator style of yellow is not changed based on my code. 

### Steps to reproduce
I followed react-navigation documentation at https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md .

```
<Scene key="tabbar"  tabBarStyle={styles.tabBarStyle} tabBarPosition={'top'} {...sceneConfig} hideNavBar tabs={true}  >


tabBarStyle: {
        backgroundColor: '#eeeeee',
        indicatorStyle : {
            color: '#de1d3e'
        },
    },
```

**Comment by MakeAndyBetter** [comment]
It uses a separate styling : See below

```
<Scene tabs indicatorStyle={navStyle.indicatorStyle}/>

const navStyle = {
 tabBarStyle: {
        backgroundColor: '#eeeeee',
},
  indicatorStyle:{
    backgroundColor:'#de1d3e'
  },
};
```

**Comment by d7laungani** [comment]
I just tried that and it doesn't seem to work.

**Comment by irvanniz** [comment]
it's work for me
`const tabMaterial = createMaterialTopTabNavigator(
  {
    option1: Option1Screen,
    option2: Option2Screen
  },
  {
    tabBarOptions: {
      indicatorStyle: {
        backgroundColor: "#ffffff"
      }
    }
  }
);`
