### ISSUE TITLE
[suggestion] modal independent of navigation

### ISSUE THREAD

**Issue by beiming** [aksonov/react-native-router-flux#2174]
I think modal should be on top of navigation. and have its own logic.

Now in react-native-router-flux. If you want to hide modal  and pop scene together. muse be `setTimeout(Actions.pop, xxx)` twice. and `Modal.dismiss()` not working.

**Comment by aksonov** [comment]
`modal` within RNRF v4 is bottom-to-top navigation, nothing about `Modal` from React Native. For popups you could use `lightbox` as shown within Example project. With lightbox you could use Actions.pop without problems.
