### ISSUE TITLE
How to set NavBar above Tabs?

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2181]
### Version
- react-native-router-flux v4.0.0-beta.15
- react-navigation: ^1.0.0-beta.11
- react-native: 0.47.0

I want to have only one NavBar above Tabs,  how can I achieve this?

### Here is my code

```
<Scene
  tabs
  key="home"
  title="Home"
  tabBarPosition={"bottom"}
  type={ActionConst.REPLACE}
  tabBarStyle={styles.tabBarStyle}
  activeBackgroundColor="#ddd"
>
  <Scene
    key="Title1"
    title="Title1"
    tabBarLabel="Title1"
    component={Profile}
    icon={TabIcon}
  />
  <Scene
    title="Title2"
    tabBarLabel="Title2"
    key="Title2"
    component={Profile}
    icon={TabIcon}
  />
  <Scene
    key="Title3"
    title="Title3"
    tabBarLabel="Title3"
    component={Profile}
    icon={TabIcon}
    hideNavBar
  />
</Scene>
```
### Screenshot
![screenshot](https://user-images.githubusercontent.com/963765/28938393-5dae9af0-78a7-11e7-8231-0b6facecf844.gif)

**Comment by mybolide** [comment]
The new version does not seem to support the icon property

**Comment by shukerullah** [comment]
working in my case, just add showIcon in the parent scene, Home in my case.

**Comment by aksonov** [comment]
@shukerullah Could you clarify? Could you check Example project, its tab bar has only one nav bar.

**Comment by shukerullah** [comment]
I want to have only one nav bar for all tab, is that possible?

**Comment by aksonov** [comment]
Yes, check Example project
