### ISSUE TITLE
Press Android back button immediately exit application 

### ISSUE THREAD

**Issue by cporawat** [aksonov/react-native-router-flux#2182]
### Version
- react-native-router-flux v4.0.0-beta.16
- react-native v0.47.1

### Expected behaviour
When I go to second scene and press Android back button, it should back to previous page (like Actions.pop())

### Actual behaviour
It exit from application from every pages I tried

### Steps to reproduce
I just upgrade version from v4.0.0-beta.14 to v4.0.0-beta.16 and unexpected behaviour occurred
1. Navigate to second scene or deeper
2. Press Android back button and it will exit from application.

**Comment by ahmadms1** [comment]
I'm having the same problem. Even tried to override it with BackHandler but it will still directly exit from application.

**Comment by ahmadms1** [comment]
On second thought, I applied the BackHandler wrongly. Please take a look at the workaround suggested in #2040 using BackHandler. Cheers!

**Comment by cporawat** [comment]
Thanks for your help, @ahmadms1. This workaround solve my problem

**Comment by durgesh387** [comment]
i was unable to solve the problem even after the work around suggested in #2040.

**Comment by daviscabral** [comment]
If you think you found a bug - please open a new issue with all the information asked in the template. Beta versions are not supported - I recommend you to download the most recent release to test.
