### ISSUE TITLE
Modal nested navigation

### ISSUE THREAD

**Issue by dhavrosh** [aksonov/react-native-router-flux#2183]
Hey guys,

I'm using react-native-router-flux 3.37 and have tried 4.0.0-beta.14; react-native version is 0.45.1

I'd like to know if there is way to create nested navigation inside a modal (popup). It doesn't depend on module version for me, I just want to solve it.

### Expected behaviour
```
<Scene key="modal" component={Modal}>
      <Scene
        key="root"
        style={mainStyle.container}
        navigationBarStyle={navigationStyle.bar}>
        <Scene
          initial={true}
          key="chat"
          title='GET STARTED'
          titleStyle={navigationStyle.title}
          titleWrapperStyle={navigationStyle.titleWrapper}
          sceneStyle={onboardingStyle.container}
          component={ChatViewContainer}
        />
      </Scene>
      <Scene key='cubeModal' component={TestView}>
        <Scene key='firstModal' component={ModalView}/>
        <Scene key='secondModal' component={ModalView}/>
      </Scene>
  </Scene>
```
When I open my popup by Actions.cubeModal() I expect to navigate inside it while calling Actions.firstModal() or Actions.secondModal()

### Actual behaviour

After opening my popup it doesn't navigate to a secondModal inside a popup, it just add that block to the level where chat and cubeModal are.

If this issue could be solved with a newer version, let it be. Main goal - to have popup (not full screen modal) with its own navigation.

Thanks for your great module.

**Comment by aksonov** [comment]
Check Example project and Login modal popup

**Comment by dhavrosh** [comment]
Thank you,
Is here some way to not open modal on full screen?
Like in version 3.* we have animationStyle, where I can set translateY of scenes

**Comment by aksonov** [comment]
Use `lightbox`for it - check Example, Error popup. But probably it is only for one screen. Unfortunately no animationStyle for v4 - ask react-navigation team to add that feature...

**Comment by dhavrosh** [comment]
Okay, thank you!
