### ISSUE TITLE
Icon hamburger on each scene

### ISSUE THREAD

**Issue by littlejohn19** [aksonov/react-native-router-flux#2184]
### Expected behaviour
I would like to display hamburger icon (to open drawer menu) on each scene in my app.

### Actual behaviour
Currently hamburger icon is only on first scene. How can I change that behaviour?

On rest scenes instead of hamburger app renders backButton icon.

**Comment by OrianeInMoon** [comment]
Did you try with the `drawerImage ` prop? (found [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md))

**Comment by aksonov** [comment]
Please check latest master, it should work better now. If you check Example, you will find that scenes has `back` option to render backButton - otherwise drawer icon will be rendered.
