### ISSUE TITLE
ComponentWillUnmount is not called when Action is triggered

### ISSUE THREAD

**Issue by phaeton2040** [aksonov/react-native-router-flux#2185]
Hi!

Here is the problem. I have a component with audio player on one screen. I hooked up to `componentWillUnmount` method to stop audio playback - `audio.stop()`. But when I try to navigate to another page the audio is still playing so it seems that `componentWillUnmount` is never triggered.

**Comment by aksonov** [comment]
It should not be triggered if screen is still at the stack. Check pure react-navigation demos and docs, it is normal behaviour.
