### ISSUE TITLE
back on TAB is not working when using hideTabBar and swipeEnabled={false} a on parent

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2186]
### Version
- react-native-router-flux ^4.0.0-beta.15
- react-native 0.47.0
- react-navigation ^1.0.0-beta.11

### Expected behaviour
It should pop back to the previous TAB.

### Actual behaviour
When swipeEnabled and back & hideTabBar props on tab, Actions.pop is working well. Its going back to the previous tab. After disabling swip it through following error: `undefined is not an object (evaluating '_this24._component.setNativeProps')`

### Steps to reproduce
1. Add  `swipeEnabled={false}` on tabs parent
2. Add back and hideTabBar props on one of the tab
3. When pressing on back button is should pop back to previous tab, but it through error here.

**Comment by aksonov** [comment]
Duplicated of #2012
