### ISSUE TITLE
[iOS, v4.0.0-beta.16] TabBar is above the NavBar when using tabBarPosition="top"

### ISSUE THREAD

**Issue by OrianeInMoon** [aksonov/react-native-router-flux#2190]
### Version

- react-native-router-flux v4.0.0-beta.16
- react-native v0.46.4

### Expected behaviour

`TabBar` should be below `NavBar` when using ` tabBarPosition="top"`.

### Actual behaviour

Two problems:
- On iOS 10.3 (simulator), the `TabBar` renders above the `NavBar` when using ` tabBarPosition="top"`
- `title` doesn't appear in the `header`

### Steps to reproduce

```jsx
<Scene
  key="pagewithtabs"
  title="Page with tabs"
  swipeEnabled
  gestureEnabled
  initial
  showLabel
  tabs
  tabBarPosition="top"
>
  <Scene
    key="tab1"
    tabBarLabel="TAB #1"
  >
    <Scene
      key="tab1_1"
      component={Page1}
    />
  </Scene>
  <Scene
    key="tab2"
    tabBarLabel="TAB #2"
  >
    <Scene
      key="tab2_2"
      component={Page2}
    />
  </Scene>
</Scene>
```

____________

Do some has a working ios code with this versions??
Thanks!

**Comment by aksonov** [comment]
Looks like react-navigation issue: https://github.com/react-community/react-navigation/issues/88
Could you please test pure react-navigation tabbar demo?

**Comment by aksonov** [comment]
Closed due inactivity. Feel free to reopen.

**Comment by pgonzalez-santiago** [comment]
Having the same problem. How did you fix it? @OrianeInMoon
