### ISSUE TITLE
Press Android back button immediately exit application

### ISSUE THREAD

**Issue by sayhei** [aksonov/react-native-router-flux#2191]
#2182 
my app is using react-native 0.42.0 ,in this version there is not BackHandle  and Press Android back button immediately exit application ,if i update the react-native version ,it will be a lot of errors ,so 
how can i deal with android back correctly on react-native 0.42.0. Anybody can help me?? help!!help!!

**Comment by ecavalcanti** [comment]
I solved this way:
`<Router backAndroidHandler={this.onBackPress}>`
and:
`  onBackPress = () => {
    if (Actions.state.index === 0) {
      return false
    }
    Actions.pop()
    return true
  }
`

**Comment by Assem-Hafez** [comment]
This solved my problem

<Router backAndroidHandler={() => {return Actions.pop()} }>
</Router>
