### ISSUE TITLE
Hardware back button doesn't close drawer menu

### ISSUE THREAD

**Issue by littlejohn19** [aksonov/react-native-router-flux#2192]
### Expected behaviour

I would like to close drawer menu (left sidebar) after tap on hardware back button.

### Actual behaviour

After tap hardware back button is called only Actions.pop and I see previous scene, but menu drawer component is still visible.

**Comment by CptFabulouso** [comment]
For me It works for expected on version 
"react-native-router-flux": "^4.0.0-beta.15", 
"react-native": "0.46.4",

**Comment by littlejohn19** [comment]
Where may I find the solution for this issue?

**Comment by aksonov** [comment]
Please check latest beta.17, it should work.
