### ISSUE TITLE
'DrawerClose' action pushes new scene instead of just closing drawer

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#2193]
Steps to reproduce (Example project):
* Tap "Go to TabBar page"
* Tap drawer icon
* Tap inactive area of Drawer to close it

Expected behaviour:
* Close drawer

Actual behaviour:
* Closes drawer and creates new tab2_1 scene with bottom-to-top animation

**Comment by aksonov** [comment]
Looks like it is bug of react-navigation for complex structures like we have for Example project. Will fix it by processing 'DrawerClose' by RNRF

**Comment by OrianeInMoon** [comment]
I'm still facing this problem with beta 17 and 18. After downgrading to beta 14, no bug anymore.

When the Drawer close, it will redirect to the first scene (in history, not in the scenes stack)

**Comment by aksonov** [comment]
Could you check latest master?

**Comment by zeeshanjan82** [comment]
still facing the same issue. Any fix yet?
