### ISSUE TITLE
Access to Component's props from NavBar.

### ISSUE THREAD

**Issue by tendolukwago** [aksonov/react-native-router-flux#2195]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.15 (v3 is not supported)
- react-native v0.46.4?

### Expected behaviour

First, great library. it's been a ton of help so far. There is some important functionality though, that I'd like some clarification on. 

In v4, I expect to be able to call a static method that has access to the component's props. 

Being able to save and interact with the store, seems like pretty necessary functionality....maybe that's just me, though. I've seen you discuss this in a couple of threads, but there hasn't been any clear solution. If it's the custom navigation that's the answer, can you please provide an example of how to use it with the rnrf? The documentation isn't very clear. 

Thanks.

### Actual behaviour
I can't access the component's props.

**Comment by aksonov** [comment]
Check 4.0.0-beta.18 - now you can access your component instance via `Actions.refs.SCENE_NAME`
