### ISSUE TITLE
Back button on Android always closes app

### ISSUE THREAD

**Issue by cobarx** [aksonov/react-native-router-flux#2196]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.16
- react-native v0.47.1

### Expected behaviour
When pressing the back button on Android, app returns to the previous scene if there is one, otherwise it closes the app.

### Actual behaviour
RNRF always closes the app and never returns to previous scene.

### Steps to reproduce
1. Launch example app
2. Go to Login page
3. Press Back button

**Comment by aksonov** [comment]
Please check latest master

**Comment by wayne1203** [comment]
@asokol Hi, how can I install the latest master? 
I'm in beta16 now, but seems not the latest master version.

**Comment by aksonov** [comment]
Set link to direct master with commit ID for package.json like
```
    "react-native-router-flux": "github:aksonov/react-native-router-flux#92f055e52d11e0ff8c38bd5f1a5100bc927d5242",
```

**Comment by wayne1203** [comment]
Thanks @asokol , it's work~

**Comment by cobarx** [comment]
Working properly here as well. Thanks for the quick fix!
