### ISSUE TITLE
How can I show tab inside the tab (Nested tabs)?

### ISSUE THREAD

**Issue by nakulkundaliya** [aksonov/react-native-router-flux#2199]
How can I show tab inside the tab?

Example 
![g1zny](https://user-images.githubusercontent.com/15937642/29060865-2bcdfe64-7c39-11e7-9b6a-52d275e8b547.png)

**Comment by aksonov** [comment]
Have you tried to put Scene tabs inside Scene tabs?

**Comment by nakulkundaliya** [comment]
Yes i have tried it

**Comment by aksonov** [comment]
And what do you see? Probably react-navigation doesn't support it, please try pure react-navigation solution first.

**Comment by nakulkundaliya** [comment]
You mean it's not possible in `react-native-router-flux`

**Comment by aksonov** [comment]
@nakulkundaliya If react-navigation doesn't support it then yes. But it seems to support it with some `lazy` tweaking: 
https://github.com/react-community/react-navigation/issues/662

**Comment by nakulkundaliya** [comment]
@aksonov I fixed it 
I forgot to removed **component** from the root tab
That's why sub tabs are not showing.
Thanks

**Comment by tasharofi** [comment]
@aksonov can you please share sample code block on how to do the nested tabs here? I am also looking to do the similar thing. Would be great if you can do that. thanks

**Comment by nakulkundaliya** [comment]
@tasharofi  you can find demo from 
https://github.com/nakulkundaliya/react-native-router-flux/

**Comment by tasharofi** [comment]
@nakulkundaliya thanks but I dont see the nested tabs section? I am running the "Example" project. Can you tell me where to find it please?

**Comment by nakulkundaliya** [comment]
```
<Scene
  key="tab1"
  title="Tab #1"
  tabBarLabel="TAB #1"
  icon={TabIcon}
  navigationBarStyle={{backgroundColor: 'red'}}
  titleStyle={{color: 'white', alignSelf: 'center'}}
>
  <Scene
    key="tab1_1"
    component={TabView}
    title="Tab #1_1"
    onRight={() => alert('Right button')}
    rightTitle="Right"
  />
  <Scene
    key="tab1_2"
    component={TabView}
    title="Tab #1_2"
    back
    titleStyle={{color: 'black', alignSelf: 'center'}}
  />
</Scene>
<Scene key="tab2" initial title="Tab #2" icon={TabIcon}>
  <Scene
    key="tab2_1"
    component={TabView}
    title="Tab #2_1"
    renderRightButton={() => <Text>Right</Text>}
  />
  <Scene
    key="tab2_2"
    component={TabView}
    title="Tab #2_2"
    back
    onBack={() => alert('onBack button!')}
    backTitle="Back!"
    panHandlers={null}
  />
</Scene>
```

**Comment by mayur10** [comment]
How can hide parent tab bar if i click on a particular child tab bar.
For eg: with reference to the picture posted in the question.
I want to show VIEW P1,VIEW P2,VIEW P3 only in view 1 and want to hide the parent tab in view 2. 
Is this possible
