### ISSUE TITLE
Unable to Launch TabBar on Android

### ISSUE THREAD

**Issue by chai2** [aksonov/react-native-router-flux#22]
Hi, I just started implementing react-native-router-flux(Lovin it - beer for you @aksonov ) for my app. It works like a charm for my IOS version. Trying the basic setup on Android, and I cant get to the TabBar view. Getting the following error. I looked up for the documentation for <a href="https://facebook.github.io/react-native/docs/navigator.html#content" target="_blank"> Navigator </a> of React Native Android, and it find anything different when compared to iOS. Did anyone run into this issue?

Thanks in advance. 

<img width="483" alt="screen shot 2015-10-15 at 1 23 34 am" src="https://cloud.githubusercontent.com/assets/168434/10508352/6239f71e-72db-11e5-8f83-2bc014b4b944.png">

**Comment by aksonov** [comment]
Try to debug in Chrome dev tools (set breakpoint for exception). For now i don't see what code of my component could raise it (stacktrace doesn't show it as well)

**Comment by chai2** [comment]
Not entirely sure, if this info is what you're looking for or not .. this is the exception. And, this is the error from the call stack - https://gist.github.com/chai2/7e4dc8d672f285b580e5

<img width="1192" alt="screen shot 2015-10-15 at 2 11 04 am" src="https://cloud.githubusercontent.com/assets/168434/10509457/04aaedb8-72e2-11e5-9f81-4f08f6f1ffe3.png">

**Comment by aksonov** [comment]
No, it is useless. If you are sure that the exception raised from my component, you have to find the line in the component code. Set breakpoints on all 'navigator' code and find out where the exception happen.

**Comment by aksonov** [comment]
Closing it for now
