### ISSUE TITLE
On hiding child nav bar, parent nav bar gets hidden

### ISSUE THREAD

**Issue by rupalpatel0008** [aksonov/react-native-router-flux#2200]
### Version

- react-native-router-flux v4.0.0-beta.15
- react-native v0.45.1

### Expected behaviour

I want to hide nav bar of nested tab bars in my app. When I put hideNavbar prop in my scene defination of a nested tab bar view, it should hide the nav bar of that view only.

### Actual behaviour

Instead its hiding all nav bars in app.

### Steps to reproduce

See the screenshot. http://prntscr.com/g5spnf

The red one is title bar of parent tab bar. The yellow one is nested tab bar. And the green one is nav bar of the nested tab bar. I want to hide the green nav bar.

I have put hideNavbar for green nav bar as following.

```
<Scene
  key="favourites"
  title="SAVED"
  tabs
  tabBarPosition='top'
  showLabel={true}
  showIcon={false}
  lazyLoad={false}
  swipeEnabled={true}
  activeTintColor='black'
  activeBackgroundColor='transparent'
  activeTintColor='white'
  indicatorStyle={{backgroundColor:'#1DC43C'}}
  renderRightButton={() => <Text>add</Text>}
>
  <Scene
    key="favourites_saved_all"
    title="All"
    component={FavouritesSavedAll}
    iconName="activityTab"
    hideNavBar
  />
  <Scene
    key="favourites_saved_groups"
    title="Groups"
    component={FavouritesSavedGroups}
    iconName="activityTab"
    initial
    hideNavBar
  />
</Scene>
```

**This is the current output:**
http://prntscr.com/g5svuu

**Comment by aksonov** [comment]
It looks react-navigation issue. Please check pure react-navigation demos - once you set `header` to `null` within `navigationOptions` it will hides all navbars. Related:
https://github.com/react-community/react-navigation/issues/88

**Comment by aksonov** [comment]
Closed because it is not supported right now. Feel free to submit PR or open issue for react-navigation about this.

**Comment by wluxion** [comment]
Reminder for others looking at this: you may be able to achieve what you want with headerMode (none/float).
