### ISSUE TITLE
Error and warning: "Cannot update during an existing state transition an error", using react-native-router-flux and redux-form Field

### ISSUE THREAD

**Issue by OrianeInMoon** [aksonov/react-native-router-flux#2201]
## bug

using [react-native-router-flux](https://github.com/aksonov/react-native-router-flux/) with `<Field />` from [redux-form](https://github.com/erikras/redux-form), I run into warnings and an error.

## versions

```javascript
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-router-flux": "^4.0.0-beta.16",
"react-redux": "^5.0.5",
"redux": "^3.7.2",
"redux-form": "^7.0.1",
```

## expected behavior

No warnings and no error

#### errors

-   a warning: 
>`Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`
-   an error: 
> Uncaught RangeError: Maximum call stack size exceeded

#### observations

- The problem came after passing `mapStateToProps` to ConnectedRouter:

```jsx
const ConnectedRouter = connect(mapStateToProps, null, mergeProps)(Router);
```

- in #2063 

 `I just did a little digging. Would you mind explaining why does the component need to be stateless?`, **I suspect** that the `<Field />` component is not stateless and so, not compatible with the react-native-router-flux render.

@necsoft resolved the problem switching from
```jsx
class App extends Component {
```
to
```jsx
const App = () => {...}
```

- in [react-router/issues/4713](https://github.com/ReactTraining/react-router/issues/4713#issuecomment-287675609)

updating could be solution, or was a solution at this time and with react-router.

### step to reproduce

```jsx
<ConnectedRouter />
  <Scene contentComponent={PageHome}/>
    <MyReduxForm />
      <Field />
```

- `<ConnectedRouter />` 
```jsx
const ConnectedRouter = connect(mapStateToProps, null, mergeProps)(Router);
```

- `<Scene />` 
```jsx
<Scene
  key="pagehome"
  component={PageHome}
  title="Home"
/>
```

- `<Page />` 
```jsx
const PageHome = ({ onSubmit }) => {
  return (
    <View>
      <MyReduxForm onSubmit={onSubmit} />
    </View>
  );
};

const mapStateToProps = (dispatch) => {
  return {};
};

const mapDispatchToProps = (dispatch) => {
  return {
    onSubmit: () => console.log('submit')),
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(PageAccount);
```

- `<Form />` 
```jsx
import { Field, reduxForm } from 'redux-form';

let MyReduxForm ({ handleSubmit, onSubmit }) =>
<View>
  <Text style={styles.label}>{I18n.t('strings.formAccount.fields.email.label')}</Text>
  <Field
    name="email"
    type="text"
  />
</View>


MyReduxForm = reduxForm({
  form: 'myReduxForm',
  validate,
})(MyReduxForm);

FormAccount = connect()(MyReduxForm);


```

**Comment by aksonov** [comment]
I don't understand - why `MyReduxForm` is children of `Scene` ?

**Comment by MaxInMoon** [comment]
@aksonov the schema is very trivial. In fact `MyReduxForm ` is a children of the `Scene` component's **`PageHome `**

**Comment by MaxInMoon** [comment]
@aksonov did you ever used/encountered a real working exemple with redux-form?

**Comment by aksonov** [comment]
No, I don't have any. Please give me link to repo so I can reproduce that issue. Please also check pure react-navigation, maybe the issue is from there:
https://github.com/react-community/react-navigation/issues/1589

**Comment by MaxInMoon** [comment]
@aksonov I'll do my best to provide one before tomorrow

**Comment by aksonov** [comment]
Closed due inactivity

**Comment by Stophface** [comment]
I am having the same problem. As suggested here (https://github.com/aksonov/react-native-router-flux/issues/2063) rewriting it as stateless component is no option for me because I pass props down from another `component`.
