### ISSUE TITLE
V4 RenderRightButton not working when passed in Actions.refresh

### ISSUE THREAD

**Issue by escobar5** [aksonov/react-native-router-flux#2204]
### Version

- react-native-router-flux@4.0.0-beta.14
- react-native v0.44.2

### Expected behaviour

When using `Actions.refresh({ renderRightButton: this.renderRightButton });` it is expected that the renderRightButton method is called and the right button rendered.

This is the renderRightButton method:

```
renderRightButton = (props) => {
    return <TouchableOpacity onPress={this.logout}><Icon name="power" size={25} color="white" /></TouchableOpacity>
  }
```

### Actual behaviour

No button is rendered, but if I try the static renderRightButton it works.

**Comment by aksonov** [comment]
Could you try to pass `right` ? `renderRightButton` is too long, probably we need to update docs to use `right`.

**Comment by luco** [comment]
It's `right` as @aksonov said. I had this issue yesterday, tried `renderRight` and `headerRight`.

**Comment by tusharv-bidchat** [comment]
With `right` the button gets rendered button if width is large then it gets cut off.
But if I use `renderRightButton` as Scene prop in Router then it does not get cut off.
Any idea about this?
