### ISSUE TITLE
[react-native-router-flux] initialState should not be null

### ISSUE THREAD

**Issue by pdavid0** [aksonov/react-native-router-flux#2205]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.17
- react-native v0.47.1

### Expected behaviour
The app launch.

### Actual behaviour
```
[react-native-router-flux] initialState should not be null
assert
    Util.js:34:10
reducer
    Reducer.js:282:9
getReducer
    index.js:35:35
Router
    Router.js:42:63
```

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

1. Upgrade from an older version

**Comment by aksonov** [comment]
> For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

**Comment by aksonov** [comment]
Closed because of lack of details

**Comment by pdavid0** [comment]
I would love to give more details but I don't more to share ... ?

I just start the app after an upgrade to 0.47 and it crashes without telling me what's up.

**Comment by aksonov** [comment]
Upgrading to major version of any product could have breaking changes. Have you ever read docs? How I can help you if you even didn't share any code.
