### ISSUE TITLE
How can i add gradient in background color of navbar?

### ISSUE THREAD

**Issue by aitemr** [aksonov/react-native-router-flux#2206]
Version

Tell us which versions you are using:

react-native-router-flux v4.0.0-beta.17
react-native v0.47.1

I know that I can add custom navBar but I don't know how?

**Comment by aksonov** [comment]
Pass `navBar` property as your custom navbar to `Router` - it will be propagated to all scenes.

**Comment by aitemr** [comment]
@aksonov Could you share how to create custom navigation bar?

**Comment by aksonov** [comment]
No. It is about react native programming - just pass your component to `navBar`, have you tried it? Check react-navigation docs (because RNRF uses react-navigation) about customisation of nav bar (i.e.`header` within `navigationOptions`)
