### ISSUE TITLE
leftButtonImage is not working

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2207]
### Version
- react-native-router-flux v4.0.0-beta.17
- react-native v0.47.1

`rightButtonImage` with source is working but leftButtonImage does not appear.

```
Actions.refresh({
  back: true,
  rightButtonImage: source,
  leftButtonImage: source,
  onLeft: () => func,
  onRight: () => func
});
```

**Comment by aksonov** [comment]
I can't reproduce it. Just replaced rightTitle within `Login.js` of Example project:
```
    Actions.refresh({
      title: 'Login!',
      //rightTitle: 'rightTitle',
      rightButtonImage: require('../images/menu_burger.png'),
      onRight: () => {},
    });
```
and saw image normally.

Please fork & modify Example project to demonstrate issue.

**Comment by shukerullah** [comment]
leftTitle and rightTitle both are working in Example.

**Comment by shukerullah** [comment]
`leftButtonImage` is not working, its because `navigationParams.leftButtonImage` condition is missing in [navigationStore.js](https://github.com/aksonov/react-native-router-flux/blob/master/src/navigationStore.js#L166-L173), `leftButtonImage` working on `v4.0.0-beta.16`.

### Version
- react-native-router-flux v4.0.0-beta.17

**Comment by aksonov** [comment]
Thanks! Please check latest master

**Comment by shukerullah** [comment]
Thank you for quick response.

**Comment by shukerullah** [comment]
Still `leftButtonImage` is not working, but if I move `navigationParams.leftButtonImage` outside the onLeft condition then its working.

#### From
```
((onLeft && (leftTitle || navigationParams.leftTitle || leftButtonImage || navigationParams.leftButtonImage)) || drawerImage || drawerIcon)
```
#### To
```
((onLeft && (leftTitle || navigationParams.leftTitle || leftButtonImage)) || drawerImage || drawerIcon || navigationParams.leftButtonImage)
```

### Version
react-native-router-flux v4.0.0-beta.18

**Comment by ssomnoremac** [comment]
migrating from v3, I assume there is no longer back, there is only left?
If so, then yeah this isn't working for me.
`<Scene ... leftButtonImage={backImage}/>`

### Version
react-native-router-flux": "^4.0.0-beta.21

**Comment by Dhrupal** [comment]
Does this issue resolved in latest, because following code is not changing left title to image.:
Actions.refresh({
          leftButtonImage:src,
          onLeft: () => {
            this.props.onRefresh()
          },
        });

**Comment by hatemjaber** [comment]
onLeft is not working for me either. I have tried quite a few things and cannot control the < in the header to run custom code within it. I wrote a custom component and it only worked for the > 'right' button which worked with both 'renderRightButton' and 'right'. 

`          <Scene
            key="employeeList"
            component={EmployeeList}
            title="Employees"
            right={() => {
              return (
                <RightButton onPress={() => Actions.employeeCreate()}>
                  Add
                </RightButton>
              );
            }}
            initial
          />
          <Scene
            key="employeeCreate"
            component={EmployeeCreate}
            title="Create Employee"
            onLeft={() => console.log('backbutton from create pressed....')}
          />
          <Scene
            key="employeeEdit"
            component={EmployeeEdit}
            title="Edit Employee"
            onLeft={() => {
              console.log('backbutton from edit pressed....');
            }}
          />
        </Scene>`

what is the proper way to go back and to customize the functionality?

**Comment by Dhrupal** [comment]
Actually mine is working now, i have added this, which is not allowing to access left in ios
static navigationOptions =Platform.OS =='ios' && {
    headerLeft: (
    <View>
       <Text onPress={() => Actions.pop()} >Cancel</Text>
    </View>)
  }
