### ISSUE TITLE
`Back` prop to Scene is not functioning properly

### ISSUE THREAD

**Issue by tbarmann** [aksonov/react-native-router-flux#2209]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.0-beta.17
- react-native v0.46.1

### Expected behaviour
Left button arrow should be hidden when using the `back` prop set to false on `<Scene>` component, according to the docs.

### Actual behaviour
Button is showing:
![image](https://user-images.githubusercontent.com/249463/29144058-77b49666-7d25-11e7-8359-a611ae8ac940.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Use the `back` prop set to `false` for a `Scene` component
2. Render
3. Back arrow is displayed and is functional

Here is my `Router` component's return:
```
    return (
      <Router>
        <Scene
          rightButtonTextStyle={styles.buttonTextStyle}
          navTransparent={true}
          rightTitle={rightTitleText}
          onRight={this.handleLogoutPress}
          key="root">
          <Scene
            key="login"
            back={false}
            component={Login} />
          <Scene
            key="profileLanding"
            initial={true}
            back={false}
            component={ProfileLanding} />
        </Scene>
      </Router>
    );
```

**Comment by aksonov** [comment]
Could you try to use `init` instead? Currently `back` is used to add back button, not to hide it. Need to improve docs.

**Comment by tbarmann** [comment]
I don't see `init` in the docs. Can you explain?

**Comment by aksonov** [comment]
Just add `init` prop to `Scene`, it is not documented yet.

**Comment by aksonov** [comment]
More correct way is not to hide 'back', but use 'replace' action instead. Actually `back` now is kind of workaround of react-navigation bug where 'back' button is not properly determined.

**Comment by aksonov** [comment]
Closing it for now.
