### ISSUE TITLE
Lazy prop mount other pages which are not selected

### ISSUE THREAD

**Issue by jordenchang55** [aksonov/react-native-router-flux#2211]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.17
- react-native v0.46.4

### Expected behaviour
lazy prop should mount only the tab I selected.

### Actual behaviour
On android, it mount first tab only at initial state, but when I click other tab, it will mount all tabs between first one and the one I clicked. For example, I click third tab, it will mount second tab as well.
It works as expected on iOS.

**Comment by aksonov** [comment]
RNRF is wrapper around react-navigation. Please check pure react-navigation TabNavigator demos with `lazy` enabled: https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md

**Comment by aksonov** [comment]
Closed due inactivity.
