### ISSUE TITLE
Unexpected behaviour when rendering an array of Scenes

### ISSUE THREAD

**Issue by Stophface** [aksonov/react-native-router-flux#2214]
### Version
- react-native-router-flux v4.0.0-beta.16
- react-native v0.46.1

### Expected behaviour
I expect the Scenes to be rendered.

### Actual behaviour
Got the error Message 
> [react-native-router-flux] key should be defined for [object Object]

### Steps to reproduce
That is my Code.
What I am having trouble with is rendering an `array` of Scenes. I need to do that if I don't want to hardcode every `Scene` and its corresponding `Component`, but rather feed it an `object` and then create the `Scenes` and the `Routing`. I have no idea how to render a list of `Scenes`...

```
_createList = () => {
    const list = this.state.structure.map((obj, index) => {
    return (
      <TouchableOpacity
        key = {obj.key}
        onPress = {() => this._onPress(obj, index)}
        <View style={{ flexDirection: "row", display: "flex" }}> 
            <Text 
              style = {this._createStyleText(index)}>   
              {obj.name}
            </Text>
        </View>
      </TouchableOpacity>
    )
    });
    return list;
   }

   _createScene = () => {
     const filterList = this._createList();
     const sceneList = filterList.map(obj => {
      return (
        <Scene 
          key = {obj.key}
          component = {obj}
          title = "Filter"/>
      )
     });
    return sceneList;
   }

  render() {
    return (
      <Router>
        <Scene key = "root">
          <View>
            {this._createScene()}
          </View>
        </Scene>
      </Router>
    )
  }
}
```

**Comment by aksonov** [comment]
Sorry, it is not supported behaviour.

**Comment by Stophface** [comment]
@aksonov so there is actually no way to render Scenes from a list of scenes? I have to hardcode every scene?

**Comment by aksonov** [comment]
Yes, it is how routing works. You don't `render` scenes within `Router`, but declare them.

**Comment by aksonov** [comment]
Probably you have to read more about navigation in general.

**Comment by Stophface** [comment]
@aksonov  How would you set up a navigation if you do not know how "deep" it goes, how many layers it has etc?

**Comment by aksonov** [comment]
Sorry, it is about your architecture app, not about RNRF.

**Comment by Stophface** [comment]
@aksonov okay. thanks for your quick help!
