### ISSUE TITLE
How to hide back button Text Label

### ISSUE THREAD

**Issue by tendolukwago** [aksonov/react-native-router-flux#2219]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0.beta.17 (v3 is not supported)
- react-native v0.46.4

### Expected behaviour

the back title always shows the title of the previous screen. I would like to override this behavior by either a) being able to disable or hide the text or b) render by own custom back button (in v3 renderBackButton was a prop available, but that doesn't seem to be the case in v4)

### Actual behaviour

the back button always shows with the previous screens title

**Comment by aksonov** [comment]
Have you tried `backTitle` ?

**Comment by tendolukwago** [comment]
@aksonov I tried modifying the example by setting the second login screen's backTitle prop to an empty string and it defaulted to the previous page's title.

![screenshot-1](https://user-images.githubusercontent.com/16335697/29234563-d8cd4a14-7ec5-11e7-8f38-dcfd0c02dc7c.jpg)

![screenshot-2](https://user-images.githubusercontent.com/16335697/29234562-d8c7bab8-7ec5-11e7-92f2-63f856b078dc.jpg)

**Comment by luco** [comment]
Try using `headerLeft` to render a custom component:

```
static navigationOptions = {
    headerLeft: (<View></View>)',
  }
```

I think `backTitle` doesn't work anymore. What works is `headerBackTitle`, which must be set on the previous screen.

**Comment by tendolukwago** [comment]
@luco setting headerLeft in the static navigationOptions object allowed me to hide the left title, but broke the navigationBarStyle option in RNRF.

**Comment by luco** [comment]
@tendolukwago Can you post some screenshots? `headerLeft` should only render the back button and not break any styles.

**Comment by tendolukwago** [comment]
@luco I ended up setting the headerStyle option on naviationOptions. It worked. Thanks for pointing me in the right direction!

**Comment by y2k-shubham** [comment]
@tendolukwago, instead of setting backTitle prop to empty string / null value, I assigned it to space (string), i.e. backTitle=" ", and it worked like a charm!
(though that isn't the right way to go about it)

**Comment by tendolukwago** [comment]
@y2k-shubham thanks for the follow up. i'll try that out.

**Comment by pigflymoon** [comment]
@y2k-shubham  @tendolukwago  
I tried  init={false}( If it is true back button will not be displayed), but it didn't work, so I tried backTitle=" ",Yeah! it works perfect. I have no idea what is the right way to hide back button. So I ended it up with backTitle = ""

**Comment by ajkhatibi** [comment]
@tendolukwago Thanks for point this out. I too am having this issue. Can you explain a few things to me? What do you mean by, "setting the headerStyle option on naviationOptions"? I'm not familiar with headerStyle or navigationOptions in RNRF.

**Comment by js1599** [comment]
Can confirm that setting BackTile to an empty string WITH A space ON THE SCENE YOU WANT IT REMOVED FROM does work. So for example: 

`<routes.Scene backTitle = " " key="Reply" component={Reply} title="Replies" />`

**Comment by Huy1908** [comment]
navigationOptions: () => ({
      title: `A`,
      headerBackTitle: 'A much too long text for back button from B to A',
      headerTruncatedBackTitle: `to A`
    }),

**Comment by Justin9606** [comment]
The above solutions did not work for me but This worked for me!
  
options={{
            headerBackTitleVisible: false,
          }}

**Comment by nica0012** [comment]
@Justin9606 do you apply this on your scene?
