### ISSUE TITLE
Nested scenes in v4?

### ISSUE THREAD

**Issue by pukhalski** [aksonov/react-native-router-flux#2220]
### Version

react-native-router-flux v4.0.0-beta.16
react-native v0.46.4

### Expected behaviour

Be able to use a `Scene` to wrap another scenes with some background image/video.

### Actual behaviour

No availability.

### Steps to reproduce
```jsx
<Scene key="wrapper" component={BackgroundImage}
  <Scene key="scene1" component={Component1} />
  <Scene key="scene2" component={Component2} />
  <Scene key="scene3" component={Component3} />
</Scene>
<Scene key="scene4" component={Component4} />
```

**Comment by devvtms** [comment]
Interesting, need same solution elsewhere,  i deal with in these days :)

**Comment by aksonov** [comment]
It is not supported yet, but probably I could add it.

**Comment by pukhalski** [comment]
@aksonov, thanks. It'd be really great since it is a show stopper for us to use it on a real project for now.

**Comment by themakerman** [comment]
@aksonov would be grateful if you can do it ASAP as i am using this library on an production APP. Can you please give me any leads on ETA on when you will be able to do it?

**Comment by aksonov** [comment]
Sorry, don't have any ETA. PR is welcome - you need to optionally wrap scenes with View and overlayComponent

**Comment by luco** [comment]
+1 on this.

**Comment by aksonov** [comment]
Please check PR #2281

**Comment by aksonov** [comment]
You must use 'Overlay' custom navigator (check Example project) that will display ALL its children. This way you could add 'backgroundImage' component easily (check Tab #1 overlay from Example)
