### ISSUE TITLE
onPress for "back button" on Android only works sometimes

### ISSUE THREAD

**Issue by oakis** [aksonov/react-native-router-flux#2221]
### Version
Tell us which versions you are using: 

- react-native-router-flux: github:aksonov/react-native-router-flux#92f055e52d11e0ff8c38bd5f1a5100bc927d5242
- react-native: 0.47.1

### Expected behaviour

Touch fires onPress event every time.

### Actual behaviour

Touch fires randomly. Sometimes it takes 7 touches for it to respond.

-----------------------------------------

This is my code for the back button.

```jsx
<Router
	titleStyle={{ color: colors.alternative, alignSelf: 'center', fontSize: 14 }}
	navigationBarStyle={{ backgroundColor: colors.primary, paddingHorizontal: 10 }}
	rightButtonTextStyle={{ color: colors.alternative }}
	leftButtonTextStyle={{ color: colors.alternative }}
	renderBackButton={() => {
		return (
			<Icon 
				name="ios-arrow-back"
				style={{ color: colors.alternative, fontSize: 24 }}
				onPress={() => Actions.pop()}
			/>
		);
	}}
>
```

**Comment by oakis** [comment]
Solved it with the code below.. maybe not best practice but it works.

```jsx
<Router
	titleStyle={{ color: colors.alternative, alignSelf: 'center', fontSize: 14 }}
	navigationBarStyle={{ backgroundColor: colors.primary, paddingHorizontal: 10 }}
	rightButtonTextStyle={{ color: colors.alternative }}
	leftButtonTextStyle={{ color: colors.alternative }}
	renderBackButton={() => {
		return (
			<TouchableWithoutFeedback
				onPress={() => Actions.pop()}
			>
				<View
					style={{
						width: 30,
						height: 30,
						justifyContent: 'center'
					}}
				>
					<Icon 
						name="ios-arrow-back"
						style={{ color: colors.alternative, fontSize: iconSize }}
					/>
				</View>
			</TouchableWithoutFeedback>
		);
	}}
>
```

**Comment by oakis** [comment]
Is there any better way to solve this? Please let me know..

**Comment by aksonov** [comment]
@oakis Sorry, but it doesn't have nothing with RNRF, but with React Native or React Navigation (used by RNRF) - try pure react-navigation demos and if it works well (I doubt so), reopen this issue.
