### ISSUE TITLE
Props is not properly sent down to children when using tabs

### ISSUE THREAD

**Issue by luqmanrom** [aksonov/react-native-router-flux#2222]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.17
- react-native v0.44.2

### Expected behaviour

When a tab is selected, I expected `props.selected=true` to be passed down to the active scene child. 

### Actual behaviour

Apparently, the `props.selected` is not properly passed, hence the tabIcon color is not changed to active color

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

Here is a simplified version of my router:
 
```html
<Scene key={'tabBar'} tabs showLabel={false}>


        <Scene
            key={'contacts'}
            tabBarLabel="Contact"
            icon={props => TabIcon({ ...props, icon: 'search' })} > // This is where I need the props.selected
                <Scene
                    key={'contactsListing'}
                    component={Contact}
                    title={'Contacts'}/>
        </Scene>

        <Scene
            key={'timeline'}
            icon={props => TabIcon({ ...props, icon: 'timeline' })}>
                <Scene
                    key={"timelineDetails"}
                    title={'Timeline'}
                    component={Timeline}>
                </Scene>
        </Scene>


</Scene>

```

**Comment by aksonov** [comment]
It is not `selected` but `focused` for v4, please check

**Comment by luqmanrom** [comment]
@aksonov You are right. It is `selected` in v4. Thanks!
