### ISSUE TITLE
Tabs with fetch not rerendering on changetab

### ISSUE THREAD

**Issue by jaumebosch** [aksonov/react-native-router-flux#2225]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta17 (v3 is not supported)
- react-native v0.45

### Expected behaviour

I have 3 tabs each one launching a fetch call on componentDidMount, then it renders a listview, but only the initial tab renders correctly, the other 2 appear in blank

Any idea about how to re-render on changetab?

thanks!

**Comment by aksonov** [comment]
Have you tried `lazy` prop to set for `tabs` scene?

**Comment by jaumebosch** [comment]
nope, and it works now!
thanks a lot.

By the way, where can I find the documentation for the tabs? Haven't seen "lazy" option, and also I need to refresh onChangeTab.

Thanks again!

**Comment by aksonov** [comment]
Use `onEnter`, `onExit` props for `Scene` (or as static functions of component class).
`lazy` is documented here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md
