### ISSUE TITLE
QUESTION: How to disable swipe-back but not disable drawer-swipe

### ISSUE THREAD

**Issue by abeltje1** [aksonov/react-native-router-flux#2226]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.17
- react-native v0.46.4

Now, when implementing a drawer, swiping left opens the drawer AND pops the scene. The only workaround is to disable gestures altogether by using panHandlers or disableGestures but that's not the behaviour i'd like. My question: is it possible at this moment to only disable swipe-back gestures but not drawer-init-gestures per scene?

**Comment by zainmustafa** [comment]
Try adding `type="replace` in drawer Scene. 
This works for me. 

    <Scene key="drawer" drawer contentComponent={SideBar} type="replace" hideNavBar={true}>
          <Scene key="main" >
              <Scene key="scarlet" component={ScarletScreen} title="Scarlet" />
        </Scene>
    </Scene>

**Comment by aksonov** [comment]
@abeltje1 I don't understand your issue. Check Example project, tab2_2 - it has panHandlers disabled but you still can open drawer by swipe.

**Comment by abeltje1** [comment]
@aksonov you're right, on my simulator I couldnt swipe for some reason but on phone it actually works, sorry. Is the reverse also possible? (Disable drawer swipe but not back swipe)?

Thanks for your response!

**Comment by aksonov** [comment]
It is not supported yet: https://github.com/react-community/react-navigation/issues/390

**Comment by preetampatil3d** [comment]
@aksonov ,  

Below is my Router, 
```

<ReduxRouter getSceneStyle={getSceneStyle}>
<Scene overlay>
<Scene navigationBarStyle={[{backgroundColor: '#005685'}]} leftButtonTextStyle={{ color: 'green' }} backButtonTextStyle={{ color: 'red' }} initial>
<Scene key="modal" modal hideNavBar>
<Scene key="drawer" drawer contentComponent={SideDrawer} >
<Scene key='root' >
<Scene key="HomeComponent" component={HomeComponent} initial renderTitle={() => { return <AppLogo name="App Name" />; }} />
<Scene back={true} key="SecondPage" component={SecondComponent} renderTitle={() => { return <AppLogo name="App Name" />; }} />
<Scene back={true} key="ThirdPage" component={ThirdComponent} renderTitle={() => { return <AppLogo name="App Name" />; }} />			
</Scene>
</Scene>			
</Scene>
</Scene>
</Scene>
</ReduxRouter>
```

**Current behavior:**  Drawer is visible on 'HomeComponent' and i have disabled it on other scenes using "back={true}".
But on SecondComponent & ThirdComponent swipe back opens drawer and also goes to back page on closing of drawer.

**Expected:**
1. Drawer on all page and back button on all page except HomeComponent.
OR
2. Drawer on HomeComponent and back button on rest of the pages . 
(Drawer or back button  back button must be disabled on thease page, to avoid comflict)

Any solution or any alternate ways to overcome this issue ?
Anybody please help.

Thanks in advance.

**Comment by alex-shevchenko** [comment]
@preetampatil3d did you found any solution for your case?
