### ISSUE TITLE
remove bottom shadow not work

### ISSUE THREAD

**Issue by slowman123** [aksonov/react-native-router-flux#2231]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.17
- react-native v0.46.4

### Expected behaviour

remove bottom shadow

### my code

const getSceneStyle = () => ({
    backgroundColor: 'white',
    shadowOpacity: 0,
    shadowColor:'white',
    shadowRadius: 0,
  });

class App extends React.Component {
    render() {
        return (
            <Router 
                getSceneStyle={getSceneStyle} 
                >
                <Scene key="main"
                    backButtonImage={require('../imgs/ic_nav_back.png')}
                    navigationBarStyle={{backgroundColor: 'white'}}
                    leftButtonIconStyle={{ width: 24, height: 16}}
                    >
                    <Scene key="TestScreen" component={TestScreen} title="Test" />
                </Scene>

            </Router>
        )
    }
}

![91552a9e-ed76-44b3-9cbb-20d22ffd091b](https://user-images.githubusercontent.com/5105604/29269151-a169b6d4-8122-11e7-9f33-ba6cc5293cd8.png)

**Comment by aksonov** [comment]
Duplicated of https://github.com/react-community/react-navigation/issues/297 ?

**Comment by slowman123** [comment]
@aksonov thanks
