### ISSUE TITLE
Cant change background color

### ISSUE THREAD

**Issue by gvimlan95** [aksonov/react-native-router-flux#2232]
Good evening,

I am using the latest version v4 react native router flux in my app. Unfortunately, I could not change the background color of the scene. I tried using sceneStyle={{backgroundColor:'red'}} and style={{backgroundColor:'red'}}, neither of this works. The background is currently in grey color.

Any way to change the color of this?

Thank you

**Comment by aksonov** [comment]
use `cardStyle` for `Router`. I will add support of `sceneStyle` (now only getSceneStyle as function is supported)

**Comment by duguying** [comment]
@aksonov It's useless in `4.0.0-beta.21`.

**Comment by dwilt** [comment]
@aksonov worked for me in `4.0.0-beta.28`

**Comment by kyoyadmoon** [comment]
I have tried `cardStyle` props in both `4.0.0-beta.27` and `4.0.0-beta.28`
`cardStyle` props dose not work on `Router` component, but did work on `Stack` and `Scene`
so I wrap Scenes with a root `Stack` like this
```
<Router>
  <Stack key="root" cardStyle={{backgroundColor: '#FFF'}}>
    <Scene key="scene1" />
    <Scene key="scene2" />
  </Stack>
</Router>
```

**Comment by sunday58** [comment]
@kyoyadmoon thanks...u saved my day.
