### ISSUE TITLE
Hope to improve the docs for v4 and latest rnrf example

### ISSUE THREAD

**Issue by TGSoftware** [aksonov/react-native-router-flux#2233]
### Version

- react-native-router-flux v4.?.? -beta17
- react-native v0.47.1

### Expected behaviour
Well and right docs for newest version.
And same to the rnrf redux example.

### Actual behaviour
Current docs are old and lack of new features details, 
and many props used in example are not in docs.
It is so hard for newbees to learn about it. So bad!

**Comment by aksonov** [comment]
Sorry, but it is open source and free software. If you can improve something - submit PR. 

P. S. I don't see you in either list of contributors or sponsors or bakers. So bad!
