### ISSUE TITLE
popTo hangs

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2234]
I was trying to figure out why my app was hanging when I use popTo('sceneName'). I launched the Example with the following version:
"react-native-router-flux": "github:aksonov/react-native-router-flux#c248109ec19576dcdf24b9593d6f9542d9e59608", (beta 18)
and I was able to reproduce the issue there as well. Navigate to the last login screen (login 3) and then press "to login"

I don't see any high CPU usage or memory leak, but the app is totally unresponsive afterwards. You can't press anything and it doesn't go to the login scene. 

I'm experiencing the same behavior in my app with beta17

**Comment by compojoom** [comment]
Actually that seems to be a bug in the demo. You are missing key="loginModal" on the login scene. After adding it there it seems to works properly.

**Comment by compojoom** [comment]
I was also able to reproduce the situation in which the app is hanging for me. Here is a branch with the example app:
https://github.com/compojoom/react-native-router-flux/commit/4c02194051826bda64247815244c70393a4406d4

To reproduce press the register button in the tabbar and then press the tabbar1 button.

For some reason navigating to a new scene and then trying to go back to the tabbar scene causes this.

**Comment by aksonov** [comment]
Sorry, but tab1 is not accessible from register page (i.e. by using pop), right?

**Comment by compojoom** [comment]
Sorry, for the stupid question but why? How can I go back by specifying the scene I want to go to?

We can do a Actions.tab1(), then why can't we do Actions.popTo('tab1')? Actions.pop() works, but there are situations where one need to be specific as we don't know how many screens we have visited before tab1.

**Comment by compojoom** [comment]
@aksonov - here is my use case
A -> B -> C

C is an edit screen that has a delete option. If I use delete I can't pop to scene B as the object it was showing previously is no longer existing. That's why I want to popTo('A'), but since A is a tab RNRF hangs. 

If I popTo something that is before scene A, that is not a tab - then it works... Do I need to structure my project differently? The scenes I'm sending the user from the tab are not tabs on their own... They have their own navigation etc...

**Comment by aksonov** [comment]
Maybe it happens because A is wrapped internally (if tab is not stack), so A is stack container. Try add underscore prefix to refer inner original component, i.e. ‘_A’

**Comment by compojoom** [comment]
Where do I add the underscore? to the key or where?

**Comment by aksonov** [comment]
to the key.

**Comment by compojoom** [comment]
```
  <Tabs key="tabbar" gestureEnabled={false} showLabel={false} tabs tabBarStyle={styles.tabBarStyle} activeBackgroundColor="#ddd">
                <Stack
                  key="_tab1"
                  title="Tab #1"
                  tabBarLabel="TAB #1"
                  icon={TabIcon}
                  navigationBarStyle={{ backgroundColor: 'green' }}
                  titleStyle={{ color: 'white', alignSelf: 'center' }}
                >
```

like that? and then Actions.popTo('_tab1')? That doesn't work.

**Comment by aksonov** [comment]
No. Tabs are wrapped automatically, so you don't need to define key with underscore. Anyway, it is not your use case. popTo works in pretty simple way - just do pop until current scene will be not _name_ . After first pop current scene will be tab2_1 (popTo('tab2_1') works). After that you have to 'navigate' not to 'pop' to switch to tab1. Closing this ticket.

**Comment by compojoom** [comment]
hä??? wtf...

**Comment by aksonov** [comment]
Nice. Thanks.

**Comment by compojoom** [comment]
:) I didn't understand what you mean, but I'll try to bang my head a little more...

**Comment by aksonov** [comment]
Probably I have to wait for a week or two before answering like react-navigation team does and not try to help everybody with their problems.

**Comment by kamranyounis12** [comment]
I'm suffering from same issue with `RNRF 4.0.0-beta.27`
