### ISSUE TITLE
Reset stack with transition

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2236]
I'm trying to reset the stack when transitioning a scene. Is this possible?
I know that` { type: "reset" }` and `{ type: "replace" }` works, but without transition.

Thanks

----

## Edit

I've seen that react-navigation has some method for this:

```
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Profile'})
  ]
})
this.props.navigation.dispatch(resetAction)
```

How can I achieve this on RNRF?

**Comment by luco** [comment]
@aksonov Tips?

**Comment by aksonov** [comment]
Try to modify RNRF's `navigationStore.reset` to your one and check.

**Comment by luco** [comment]
Where can I get `navigationStore.reset `? I didn't find it in props.

**Comment by luco** [comment]
@aksonov Tips?

**Comment by aksonov** [comment]
I meant fork & edit source code of RNRF (and rebuild dist folder)

**Comment by luco** [comment]
But since React Navigation has this, shouldn't RNRF has this option as well?

**Comment by aksonov** [comment]
I can add it but I need clear demo first to understand issue. Please fork & modify Example project.

**Comment by luco** [comment]
I'm getting a issue when trying to fork & run:
`ENOENT: no such file or directory, uv_chdir`

Still, I think it's pretty simple what I'm suggesting. 

` [Screen 1] -> [Screen 2] -> [Screen 1]
`

Here, we are transitioning through screens. However, what I'm suggesting is when user reaches the last screen 1, RNRF resets the stack, not allowing the user to go back by NavBar or swipe.

**Comment by aksonov** [comment]
'replace' does this trick, right? Do you want also animation? It seems out of scope for this component (and a bit unusual) - why just don't use `Actions.pop` ? I've tried also method you mentioned and I don't see any animation for it as well.

**Comment by shukerullah** [comment]
@aksonov any news on this? I want to reset stack to new screen with transition is this possible with `transitionConfig`?

**Comment by luco** [comment]
@shukerullah Since RNRF is based on React Navigation, this is not possible yet. However there's a discussion on React Navigation repo based on this issue: react-community/react-navigation/issues/2390

What I was suggested to @aksonov is something similar as Facebook does on Navigator with `resetTo`:
http://facebook.github.io/react-native/releases/0.34/docs/navigator.html#resetto

> resetTo(route) 
>Navigate to a new scene and reset route stack.

From what I've learned, it appears that react-navigation will approach this on V 1.0.

**Comment by luco** [comment]
@aksonov Since when can now reset a child stack, would it be possible?
Something like resetTo from https://github.com/wix/react-native-navigation/
