### ISSUE TITLE
How do I override (or disable) hardware back press button for a given scene?

### ISSUE THREAD

**Issue by oatcrunch** [aksonov/react-native-router-flux#2237]
I want to override hardware back press button so that Actions.pop() will not be executed by default. In other words, I want to block user (or disable hardware back press) from tapping hardware back press button for a particular scene.

Is there a way to accomplish that? If yes, how can that be done?

**Comment by aksonov** [comment]
Try to use https://facebook.github.io/react-native/docs/backhandler.html and check navigationState (`Actions.state`) from there.

**Comment by jonrh** [comment]
@oatcrunch Were you able to figure this out? I'm in a similar situation and looking into `BackHandler` now.
