### ISSUE TITLE
[react-native-router-flux] key should be defined for [object Object]

### ISSUE THREAD

**Issue by rathorebs** [aksonov/react-native-router-flux#2238]
Hi Pavel,

I'm unable to run "Example" project under react-native-router-flux repo.

Please see attached screen-grab.

Thanks,
Bhanwar
![error](https://user-images.githubusercontent.com/9293248/29309879-2ac18352-81c9-11e7-950e-62c6d719cd9c.jpg)

**Comment by aksonov** [comment]
Please switch Example to use latest master

**Comment by rathorebs** [comment]
You mean master branch, I have downloaded and try again but I'm still facing same issue.

**Comment by aksonov** [comment]
Okey, I updated Example's package.json, check now.

**Comment by rathorebs** [comment]
Thanks Pavel !!! 

Now it's working fine.

**Comment by Aamirali86** [comment]
I still facing this issue
