### ISSUE TITLE
[Help Wanted] Is it possible to make navigation bar and tabs style like this? 

### ISSUE THREAD

**Issue by themakerman** [aksonov/react-native-router-flux#2239]
So far i can only add transparency. But the thing is navBar has customFont as well. Also Will it be possible to style tabs like this? 
![image](https://user-images.githubusercontent.com/14818804/29309869-12e1d45c-81de-11e7-9cd1-a5438b210521.png)

**Comment by rathorebs** [comment]
Hi,
Can you help me out on below issue.
Actually 
![error](https://user-images.githubusercontent.com/9293248/29310482-77372c8a-81cb-11e7-95ab-37cfd0bb4429.jpg)
I'm unable to run "Example" project under react-native-router-flux repo.

Please see attached screen-grab.

Thanks,
Bhanwar

**Comment by themakerman** [comment]
@rathorebs Plz attach  the chrome debugger output. This error comes up when you miss 
key props for particular scene.

**Comment by aksonov** [comment]
Just use latest master for Example

**Comment by rathorebs** [comment]
Still facing same issue.

**Comment by compojoom** [comment]
@rathorebs - you are using beta17 and not latest master. Change the package name to the github url with the latest commit and then it should build fine
"react-native-router-flux": "github:aksonov/react-native-router-flux#c248109ec19576dcdf24b9593d6f9542d9e59608",

**Comment by aksonov** [comment]
@themakerman Check docs, probably you have to style title for that - `titleStyle` or `headerTitleStyle`

**Comment by rathorebs** [comment]
Thanks!!!
Now it's working as fine...
