### ISSUE TITLE
How to render screen-specific navbar buttons?

### ISSUE THREAD

**Issue by tomkur** [aksonov/react-native-router-flux#224]
I have a screen implemented as modal for filtering data with given criteria.
I'd like to render navbar's left and right button as "Cancel" / "Apply filters":
![menu](https://cloud.githubusercontent.com/assets/2394102/13147587/ccd98ad0-d659-11e5-8e65-c631344da731.png)

The logic done when pressing apply is to start fetching data and to pop the modal. I'd like to implement it inside my filtering screen, so I guess I'd like to have something like:

```
<Route component={Filters} 
    renderRightButton={() => {this.ref['component'].renderApplyButton()}} ... /> 
```

and inside ```Filters.js```:
```
class Filters extends React.Component {
  renderApplyButton () {
    // redux-connected component
    this.props.dispatch(<some_action>)
    Actions.pop()
  }
  ...
}
```

How can I achieve that?

**Comment by aksonov** [comment]
Please try new Actions.refresh(props) added to latest 2.3.1 version.

**Comment by tomkur** [comment]
I'm confused, please describe how I can achieve my goal with Actions.refresh

**Comment by aksonov** [comment]
You may set needed props and check them within renderRightButton(route) function. It should be accessible via route.props.

**Comment by tomkur** [comment]
All right, I'll check that soon, thanks

**Comment by arthurvi** [comment]
Hi @tomkur, when you upgraded to 2.3.1 you can use the new Action.refresh like this:

First import `Actions` in the component from where you want to change/control the navbar button:
```javascript
import { Actions } from 'react-native-router-flux';
```

Then when you want to change the navbar button, refresh like this:
```javascript
Action.refresh({
    applyButton: <ApplyButton />
})
```

And then in your root file where all the routes are defined:renderRightButton:
```javascript
<Route
	renderRightButton={
		(route) => {
			return route.props.applyButton;
		}
	}
/>
```
You can define everything in object you pass with the Action.refresh. It could als just be the text of the button or a specific function to call.

This at least worked for me!

**Comment by tomkur** [comment]
Thanks for thorough example, @arthurvi, much appretiated! I'll test that first thing tomorrow

**Comment by arthurvi** [comment]
No problem, happy to help. Had some issues with it today as well.

**Comment by tomkur** [comment]
I did as you suggested, but in my case ```route.props.applyButton``` returned ```undefined```. However, I was able to find the button via ```route.props.router.delegate.state.applyButton```.
What am I doing wrong?

**Comment by andreasbhansen** [comment]
@tomkur @arthurvi Where would you put Actions.refresh()? I tried putting it in both componentWillMount and componentDidMount, but neither of those rendered successful. Didn't find the button/function, neither through route.props.* nor route.props.router.delegate.state.*.

**Comment by tomkur** [comment]
In my case this was in handler of button press

**Comment by andreasbhansen** [comment]
Hm. Maybe I misunderstand something here. 

In my route:
```<Route name="detailView" schema="default"  component={DetailView} renderRightButton={(route) => { console.log(route); }} title="Detail View" />```

in my ```DetailView``` component (trying both life cycle methods just to check):

```
  componentWillMount() {
    Actions.refresh({ editButtonRight: <EditButtonRight /> })
  }

  componentDidMount() {
    Actions.refresh({ editButtonRight: <EditButtonRight /> })
  }
```

Shouldn't this enable me to see the ```editButtonRight``` component/function in the console.log within the renderRightButton?

**Comment by andreasbhansen** [comment]
Ah, sorry, I didn't see your edit, @tomkur. 

So let me get this straight. The component that calls ```Actions.filters()``` handles the ```_renderApplyButton()```, even though that button belongs to your ```filters``` route, not to the overarching component (the one that calls ```Actions.filter()```)?

**Comment by tomkur** [comment]
Exactly, @andreasbhansen and it's good enough for me, although it's not a clean solution. It would be indeed better if it could be delegated to the "Filters" component (as I suggested in my first comment)  and I don't know if it can be achieved.

**Comment by tomkur** [comment]
I do have one problem though - I'd like to disable the 'Apply' button under certain circumstances while the 'Filters' view is opened (not during opening). @aksonov is that possible?

**Comment by ralphpina** [comment]
I also had issues getting the button to change. Below is what I did. In the router, I had to check to nullability. Otherwise, on first load, it would throw:

```js
<Route name="Settings" schema="tab" title="Settings" component={SettingsTab}
           renderRightButton={(route) => {
                      return route.props.router.delegate.state != null 
                                 ? route.props.router.delegate.state.rightButton 
                                 : <View/>;
                      }}/>
```

Then, in my component, I called `Actions.refresh()` in `componentDidMount()`. I also called it again inside the button click so that I could update the text. The button would only render the first time if I used a timeout in `componentDidMount`. Is this right?

```js
componentDidMount() {
    setTimeout(()=>Actions.refresh({
        rightButton: this._renderApplyButton()
    }), 200);
},

_renderApplyButton () {
    return (<TouchableHighlight
        style={styles.toolbarButton}
        onPress={() => {
                    this._editButtonClicked();
                        Actions.refresh({
                            applyButton: this._renderApplyButton()
                        });
                      }}>
        <Text style={styles.toolbarButtonText}>{this.state.inEditMode ? 'Save' : 'Edit'}</Text>
    </TouchableHighlight>);
},
```

**Comment by aksonov** [comment]
Should be possible with 3.0 release, closing this ticket for now

**Comment by rsavignon** [comment]
Is it possible to do this with 3.0 release ? If so, how ?

Thanks in advance.

**Comment by greatwitenorth** [comment]
It'd be nice to see a full example of how to change the renderRightButton dynamically. I'm using 3.2.8 and calling ```Action.menu({renderRightButton: () => <Text>Test</Text>})``` but the right button never shows up.

**Comment by rsavignon** [comment]
Hi greatwitenorth , i think i figured out how to acheive that. Both renderRightButton and renderLeftButton properties accept enclosured functions.

var gbl_mycomponent_create_nav_right_button = function() {
      return (<Text>Test</Text>} );
};

class MyComponent extends Component {
...
constructor(props) {
    super(props);
    Actions.refresh({ renderRightButton: gbl_mycomponent_create_nav_right_button } );
}
...
}

Check out and tell me if it worked as expected.

If you got the hit to refer Components Method Directly let me know. I tried but without successs.

regards.
