### ISSUE TITLE
Screen navigation is mixed up / confused.

### ISSUE THREAD

**Issue by ddobby94** [aksonov/react-native-router-flux#2242]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.38.0

### Expected behaviour

Opening the good screen.

### Actual behaviour

After using the application for a while the Navigation is broken. Maybe this is a specific issue for my app, and I can't even come up with a way the reproduce it.
The actual behaviour is: I am using the app for several minutes, preforming a smoke test and than somehow the navigation stops working properly. Beyond this moment the navigation never works how it should: sometimes it does not open the screen on tap event, sometimes it opens the previously clicked screen or a complete different one.
I actually researched this issue and the proper function is being called however it does not work.

Any ideas?

**Comment by aksonov** [comment]
v3 is not supported, sorry.
