### ISSUE TITLE
[Question] How to pass props to previous screen when back button pressed (or any other button)?

### ISSUE THREAD

**Issue by SpadarShut** [aksonov/react-native-router-flux#2243]
### Version
- react-native-router-flux v4.0.17

So I have a form on screen A and when I tap a button, screen B is opened, I fill some data and want to pass it back to screen A on pressing back or some Save button. How can this be achieved?

**Comment by aksonov** [comment]
Try `Actions.pop({refresh: DATA})`

**Comment by SpadarShut** [comment]
This is possible for a custom button, but how can I pass `{refresh: DATA}` when back in header is pressed?
