### ISSUE TITLE
Better way to declare rightTitle/onRight inside component

### ISSUE THREAD

**Issue by danieljvdm** [aksonov/react-native-router-flux#2244]
I'm currently following the example in `Login.js` and doing the following: 
```
componentDidMount() {
    Actions.refresh({
      rightTitle: 'rightTitle',
      onRight: () => {
        this.searchDropdown.toggle();
      },
    });
}
```

However, this causes a rerender and also resets my refs.

`<SearchDropdown ref={this.searchDropdown} />`

This ref exists on the first render but is set to null on the second render (caused by Actions.refresh). Is there a better way to set up the navbar before the component is rendered?

**Comment by aksonov** [comment]
It is wrong approach - declare rightTitle and onRight as static function for your component. You could access to your component ref via `Actions.refs.SCENE_NAME`  #2195

**Comment by danieljvdm** [comment]
Ok, it would be useful if you also mentioned that this was a mistake in the example, not my mistake.

https://github.com/aksonov/react-native-router-flux/commit/e8c5a428bfe1de72036e71db7ec6d7b17475325f#diff-32afed19f718c82f2588a4adaa45100e

**Comment by aksonov** [comment]
Yes, you are right
