### ISSUE TITLE
Custom navbar example

### ISSUE THREAD

**Issue by danieljvdm** [aksonov/react-native-router-flux#2245]
There are no docs or examples for custom navbar support. How can I implement one on a per-scene basis?

I've attempted to add it as prop to both `Router` and `Scene` but I get react errors when doing so: `Cannot add property 1, object is not extensible`. I'm assuming that I'm not wrapping it properly, but there is no documentation to tell me what to do.

**Comment by aksonov** [comment]
Fork & modify Example project to demonstrate the issue. Just try to set custom navbar for some screen (like Register2).

**Comment by aksonov** [comment]
Closed due inactivity.
