### ISSUE TITLE
Creating an Authenticated Scene

### ISSUE THREAD

**Issue by wwwemree** [aksonov/react-native-router-flux#2246]
Hi, I want to create an Authenticated Scene. For example if users logged in, they will see the screen otherwise they won't. I wrote a code like this:

`
export default class AuthenticatedScene extends Scene {

    static defaultProps = {
        onEnter: (props) => {
            if (!AppStore.getState().login.isOtpVerified) {
                return null;
            }
            return "success";
        },
        success: (data) => {
        },

        failure: (data) => {
            Actions.pop();
        }
    };

    constructor(props) {
        super(props)
    }

So, the problem is that if users not logged in, I am closing the current screen with .pop() and going back after users opened the screen, but my purpose was that if users not logged in, just don't open the screen instead of opening and closing again. So, how can I achieve this?

Thanks

**Comment by aksonov** [comment]
It is not correct usage. `success`, `failure` should be name of screens to navigate.

**Comment by aksonov** [comment]
Closed due inactivity
