### ISSUE TITLE
Setting style for Scenes, title, ...

### ISSUE THREAD

**Issue by Stophface** [aksonov/react-native-router-flux#2249]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.16
- react-native ^0.46.1

### Expected behaviour
I want to set the `backgroundColor` of the `title` in a `Scene`. I cannot find any props in the `docs` of to set the `backgroundColor` of the `title` (or `fontSize`, ...)

### Actual behaviour
Its staying white (on Android).

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
```
export default class Router extends Component {
  render() {
    return (
      <Router>
        <Scene key = "root">
          <Scene 
            key = "index"
            component = {NumberOne}
            title = "Color Me!"
            initial />
          <Scene 
            key = "webgis"
            component = {NumberTwo} />
        </Scene>
      </Router>
    )
  }
};
```

**Comment by aksonov** [comment]
Try `titleStyle`. Added it to docs.

**Comment by Stophface** [comment]
@aksonov thanks!
Is there a way to wrap `<Router> <Scene .../>...</Router>` in a `<Scrollview>`? When I do it, everything disappears.

**Comment by aksonov** [comment]
I don't know, maybe add `flex:1` to style, but anyway it seems not good idea to include Router into ScrollView
