### ISSUE TITLE
Cannot read property "onWillFocus" of undefined

### ISSUE THREAD

**Issue by Mokto** [aksonov/react-native-router-flux#225]
Hi guys,

I trigger this error when doing Actions.pop() and Actions.mapdirection(); if the pop if not finished.

Here is my router : 

```jsx
<Router header={NavBar} hideNavBar>
      <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} type="replace" />
      <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>

      <Route name="home" component={Home} title="Accueil" />
      <Route name="map" initial={true} title="Carte" hideNavBar>
           <Router>
                <Route name="maphome" initial={true} component={Map} title="Carte"/>
                <Route name="mapdirection" component={Direction} title="Direction" schema="modal"/>
           </Router>
      </Route>
</Router>
```

If I click on the direction icon : 

```jsx
const route = Actions.currentRouter.currentRoute;
if(route.name == 'maphome' || route.name == 'map') {
     Actions.mapdirection();
} else {
     Actions.pop();
}
```

![img_0063](https://cloud.githubusercontent.com/assets/5103928/13162763/12366f2e-d675-11e5-990a-298ebb91b06b.PNG)
![img_0064](https://cloud.githubusercontent.com/assets/5103928/13162764/123ad500-d675-11e5-8078-d0db39f26d69.PNG)

Thanks !

**Comment by aksonov** [comment]
Have you tried to debug? Stack trace error?

**Comment by aksonov** [comment]
Closing it because no answer.

**Comment by Mokto** [comment]
I'm sorry for the delay. Can you please reopen ? I will be more reactive.

Here is my stack trace :


![img_0080](https://cloud.githubusercontent.com/assets/5103928/13623881/c4249830-e577-11e5-8092-317dc74e7a45.PNG)

Please let me know if you need anything else.

**Comment by aksonov** [comment]
Sorry, but error stack is from exNavigator, not from this component. Try to check behaviour without this component, if you will see the same - report bug to exNavigator team

**Comment by adrienthiery** [comment]
Hi @Mokto,

I had this error today, it seems my problem was that I was going to fast between 2 views with an TextInput with an `autofocus={true}` so the router was basically trying to close the keyboard and open it again before the closing was finished.

To verify if that is your problem, you can put a setTimeout on your `Actions.**` and see if it helps, or if you have a route rendered very quickly inbetween your source route and your target route!

I hope that might help!
