### ISSUE TITLE
How do you setup a background image for the entire app that is shared across different scene  

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2250]
I'm trying to set a background image for my entire app and it seems that it's not working, is there a way to set a bg image for the entire app that would work across different scenes

**Comment by aksonov** [comment]
Check #2218

**Comment by AlmogRnD** [comment]
It's not working, is there a correct way or example?

**Comment by aksonov** [comment]
Okey, fork and modify Example project to demonstrate the issue.

**Comment by aksonov** [comment]
Closed due inactivity.

**Comment by AlmogRnD** [comment]
@aksonov it doesn't work you don't need to fork an example. Right now I had to set background for each scene.

**Comment by aksonov** [comment]
Check latest Example project with usage of `Overlay` - tab1 uses background defined by other scene (#2220 related)

**Comment by AlmogRnD** [comment]
@aksonov I think you have a mistake you have the following code 

```
<Overlay>
                    <Scene component={BackgroundView} />
                    <Scene
                      key="tab1_1"
                      component={TabView}
                      title="Tab #1_1"
                      onRight={() => alert('Right button')}
                      rightTitle="Right"
                    />
                  </Overlay>
```

but I don't see BackgroundView component anywhere?

**Comment by AlmogRnD** [comment]
Never mind I see it
