### ISSUE TITLE
titleStyle only sets backgroundcolor for small area

### ISSUE THREAD

**Issue by Stophface** [aksonov/react-native-router-flux#2251]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.16
- react-native 0.46.1

### Expected behaviour
I want to color the background of the header. Right now its white, I want to set a costum color. 

### Actual behaviour
There is the `titleStyle` from the API, but it only colors a small part. 
See the images:

Without text:
http://imgur.com/w0PZUeB

With text:
http://imgur.com/gUzrO3G

With text and `textStyle`
http://imgur.com/Ls2vXmz

```
export default class TestComp extends Component {
  render() {
    const { navigate } = this.props.navigation;
    return (
      <Router>
        <Scene key = "root">
          <Scene 
            key = "index"
            component = {NumberOne}
            title = "Headline"
            titleStyle = {styles.header}
            initial 
            />
          <Scene
            key = "Test2"
            component = {NumberTwo} 
            />
      </Router>
    )
  }
};

const styles = StyleSheet.create({
  header: {
    backgroundColor: "#108EE9",
  }
})
```

Interesting enough, when I replace the `Component` like so:

```
export default class TestComp extends Component {
  render() {
    const { navigate } = this.props.navigation;
    return (
        <Text>No Header here?</Text>
    )
  }
};
```

See the image what happens then:
http://imgur.com/s6Ahg1k

So, I assume that the white `header` comes from `react-native-router-flux`. Where can I change its color?

**Comment by aksonov** [comment]
It is not a bug. Title style is for title style (!!!), not for whole navbar. Use `navigationBarStyle` for navbar styling.

**Comment by Stophface** [comment]
@aksonov sorry. i did not find that in the docs... Maybe add it? Further, how do I set the `backgroundColor` of the whole thing? When you look at this image http://imgur.com/s6Ahg1k it defaults to white. Here its grey http://imgur.com/Ls2vXmz.

**Comment by aksonov** [comment]
use `sceneStyle` for `Router`. Thanks for the feedback, it is added to docs now:
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md

**Comment by Stophface** [comment]
@aksonov That
`<Router sceneStyle = {styles.container}> ... </Router>` 

with

```
const styles = StyleSheet.create({
  container: {
    backgroundColor: "#FFF"
  },  
  header: {
    backgroundColor: "#108EE9",
  },
});

```

is not getting applied. Does it need a different `style` object? Further, is the textcolor of the header modifiable as well?

**Comment by aksonov** [comment]
Check Example project for white background colour.  `titleStyle` must be used for textcolor of the header, as I said before.

**Comment by aksonov** [comment]
> navigationBarStyle is style of nav bar (as I said already)

**Comment by Stophface** [comment]
@aksonov yes :) But I want to set the `backgroundColor` for the whole router - not the `header`. 
Here its all white  http://imgur.com/s6Ahg1k while its grey here http://imgur.com/Ls2vXmz. 
I dont want the `backgroundColor` of the header white, but everything else (where the text is and everything below it). And that
`<Router sceneStyle = {styles.container}> ... </Router>`

with
```
const styles = StyleSheet.create({
  container: {
    backgroundColor: "#FFF"
  },  
  header: {
    backgroundColor: "#108EE9",
  },
});
```

Does not do the trick.

**Comment by aksonov** [comment]
Do you see white for Example? If so, probably you are using outdated RNRF version (Example uses latest)

**Comment by Stophface** [comment]
No, I can exchange

 `...container: {
    backgroundColor: "#FFF"
  },...` 

with `backgroundColor: "red"` and it does not change. I am using `react-native-router-flux 4.0.0-beta.16` which is the most recent I assume?
