### ISSUE TITLE
Issue with back button not unmounting and remount tab scene 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2257]
Version
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-router-flux": "4.0.0-beta.14",

When I click the back button and go to my teams view to select a different team my photos view which are under a different tab is not re mounting, so I can't load the new data. I need to be able to re mount a tab view it seems that it's always cached  

You can see the issue here
![example](https://user-images.githubusercontent.com/169507/29417354-c675b156-831d-11e7-9836-ec4d6e264dcb.gif)

**Comment by aksonov** [comment]
It is how tabbar works - it doesn't remount anything. Use `Actions.refresh` to update props.

**Comment by AlmogRnD** [comment]
I tried Actions.refresh it doesn't help in this case

**Comment by aksonov** [comment]
Okey, it is about your app state management, not navigation.
You could try to use `onEnter` handler (as static function) for Photos screen to get photos for 'active' screen. Also you could (or even should) use Redux or Mobx to re-render photos once home is changed.

**Comment by AlmogRnD** [comment]
Yea I'm using Redux, the core issue is with the EasyListView package that I'm using, which is not rendering when props

**Comment by aksonov** [comment]
So it is not problem of RNRF.

**Comment by AlmogRnD** [comment]
No I don't think so, my idea was to see if I can force an unmount and mount which would make it work

**Comment by AlmogRnD** [comment]
I thought RNRF back button should unmount the tab compount

**Comment by aksonov** [comment]
No. It is how react-navigation works and how tabbar works. Why you can't use `onEnter`, `onExit`?

**Comment by aksonov** [comment]
Btw, always try to use LATEST beta (or even master) before creating an issue.

**Comment by AlmogRnD** [comment]
Ok I thought I was on the latest version
