### ISSUE TITLE
Please help me how to use "react-native-router-flux" in my scenario

### ISSUE THREAD

**Issue by rathorebs** [aksonov/react-native-router-flux#2259]
Hi Pavel,

Please help me how to create two tabs for its parent button or router button.

Please see attached screen grab.
![untitled-2](https://user-images.githubusercontent.com/9293248/29420583-02871b90-8390-11e7-9fbb-93647d97d8e9.jpg)
.

Thanks,
Bhanwar

**Comment by abeltje1** [comment]
Have you tried A nested tabbar?

**Comment by rathorebs** [comment]
Yes, but it's not working.

**Comment by aksonov** [comment]
Sorry, probably it is out of scope for RNRF - as I see underlying react-navigation doesn't support nested tabbars in good way (if you can implement it with pure react-navigation but cannot with RNRF - share your code then). I'd use react-native-tab-view for inner tabs.
