### ISSUE TITLE
Dynamic Title

### ISSUE THREAD

**Issue by digitalhobo** [aksonov/react-native-router-flux#226]
Hello,
Thanks for the great module - Is their any way to dynamically change the sate of a title and navbar.

For example. 
`<Route key="UserCredentials" name="UserCredentials" hideNavBar={this.state.UserCredentialsNavBar} component={UserCredentials} initial={ false } title={this.state.title} schema="withoutAnimation" />`

And then I would have a listener which would change the state this.state.UserCredentialsNavBar 'true' or 'false' and this.state.title 'Some title' or 'Some other title'.

I tried but didn't get any where.

Thanks in advance.
:0)

**Comment by aksonov** [comment]
I've just added support to set properties without navigator transition using Actions.refresh(props), please try it (version 2.3.1)

**Comment by digitalhobo** [comment]
Thanks aksonov.
I may not be understanding you properly. 
So, for instance if I wanted to change the state of the title. I would call
`Actions.refresh({title: 'Some other title'})`
Many thanks for getting back to me.
:0)

**Comment by digitalhobo** [comment]
My bad, its all working great. Thanks very much for your help aksonov. Much appreciated. :0)

**Comment by shaharz** [comment]
I'm running into an issue that seems like a bug here with setting the title dynamically. It seems like Actions.refresh sets it for all routes, overriding their static titles.

In my case, I have a master-detail setup where the master route has a title prop and the detail route title is only set dynamically. When I'm in the detail route and the title changes what happens is that both the title and the back button change to the same text. When going back to the master, the dynamic title stays on (rather than going back to its schema title).

I'm new to React Native so I'm not sure if this is by design or not...?

Thanks!

**Comment by greatwitenorth** [comment]
Is there a way to set it for a specific scene even if I'm not currently on that scene? ie 
```
Actions.refresh({key: 'home', title: 'My new title'})
```

**Comment by JuHwon** [comment]
@greatwitenorth whats your exact use case?
e.g. if you are navigating to a view with the key `view2` you can set the title with the props like this

```javascript
Actions.view2({ title: 'My New Title' })
```

**Comment by greatwitenorth** [comment]
My issue was that I wasn't navigating to the scene that needed it's title updated. My screen updated the user's address, but the address was displayed as a title on a completely seperate screen.

**Comment by edencakir** [comment]
@greatwitenorth I ran into same problem. How to change the title without navigating to a new route with changed title?

**Comment by edencakir** [comment]
OK, I should have read the documentation better, it's simply `Actions.refresh{title: 'new title'}`

**Comment by JeroenNelen** [comment]
@greatwitenorth did you find any decent solution?
I'm fetching the title from the state, so whenever the state changes, I want a specific view to have that value as a title. Sometimes people change the title and navigate via the back button, in that case I can't seem to define the {title: } parameter (and pass the state-value in the back action), or am I missing something?

Kind regards,

**Comment by jondbm** [comment]
@JeroenNelen I had a similar issue and solved it by putting the refresh in ComponentDidMount and setting the state in Redux reducers - I tie a Redux action into every user action that changes the title, update the app state, and the props the refresh reads updates too.

So basically something like this line in ComponentDidMount:

`Actions.refresh({title: this.props.state.myapp.myvalue}) `

**Comment by JeroenNelen** [comment]
@jondbm thanks for the suggestion, but we've decided to switch to a different navigator.

Kind regards,

**Comment by edencakir** [comment]
@JeroenNelen which navigator are you using right now?

**Comment by jaynakus** [comment]
Why below setup is not refreshing right button? console.log writes the new value, but the right title never gets refreshed?

```
const RouterWithRedux = connect()(Router);

export class App extends Component {

  constructor(props) {
    super(props);
  }

  render() {
    let title = '(' + this.props.basket.length + ')';
    console.log(title);
    return (
      <RouterWithRedux rightTitle={title} onRight={() => alert('All right')}>
        <Scene key="root">
          <Scene key="home" component={Main} title="Main"/>
          <Scene key="page1" component={SomePage} title="SomePage"/>
        </Scene>
      </RouterWithRedux>
    );
  }
}
App.propTypes = {
  dispatch: PropTypes.func.isRequired
};

// Wrap the component to inject dispatch and state into it
export default connect(
  state => {
    return {basket: state.basket.items}
  }
)(App);
```

**Comment by edencakir** [comment]
@jaynakus righttitle or right button?

**Comment by jaynakus** [comment]
The Title!

**Comment by edencakir** [comment]
I would suggest using custom navbar, with whatever you want it to be in it.

**Comment by jondbm** [comment]
@jaynakus try putting your rightTitle and onRight into your Scene component instead of at the top RouterWithRedux level, that might work.

**Comment by jaynakus** [comment]
@jondbm putting them to root scene didn't solve, but calling Actions.refresh() in componentWillReceiveProps did the trick ;)

```
const RouterWithRedux = connect()(Router);

export class App extends Component {

  constructor(props) {
    super(props);
  }

  componentWillReceiveProps(nextProps) {
    if (this.props.basket.length !== nextProps.basket.length) {
      console.log(nextProps.basket.length);
      let title = '(' + nextProps.basket.length + ')';
      Actions.refresh({rightTitle: title});
    }
  }

  render() {
    let title = '(' + this.props.basket.length + ')';
    return (
      <RouterWithRedux>
        <Scene key="root" rightTitle={title} onRight={() => alert('All right')}>
          <Scene key="home" component={Main} title="MixiPay"/>
          <Scene key="fatura" component={Fatura} title="Fatura"/>
        </Scene>
      </RouterWithRedux>
    );
  }
}
App.propTypes = {
  dispatch: PropTypes.func.isRequired
};

// Wrap the component to inject dispatch and state into it
export default connect(
  state => {
    return {basket: state.basket.items}
  }
)(App);
```

**Comment by denghejun** [comment]
look here: [https://github.com/aksonov/react-native-router-flux/issues/1922](https://github.com/aksonov/react-native-router-flux/issues/1922)

**Comment by glendenning** [comment]
If you want to dynamically put in left or right buttons, use 'right' and 'left' instead of 'renderRightButton', e.g.

  componentWillMount(){
    Actions.refresh({title: 'dynamic title', left: this.renderLeftButton, right: this.renderRightButton})
  }

  renderRightButton(){
    return(
      <TouchableOpacity>
        <Text>Right Button</Text>
      </TouchableOpacity>
    )
  }

  renderLefttButton(){
    return(
      <TouchableOpacity>
        <Text>Left Button</Text>
      </TouchableOpacity>
    )
  }

For some reason, renderRightButton wouldn't work as a key in the Actions.refresh and it was just 'right' instead, found that to be a gotcha to look out for

**Comment by minhhung96966** [comment]
> @greatwitenorth whats your exact use case?
> e.g. if you are navigating to a view with the key `view2` you can set the title with the props like this
> 
> ```js
> Actions.view2({ title: 'My New Title' })
> ```How can we access it in setup file?
