### ISSUE TITLE
There is no route defined for key {route}.

### ISSUE THREAD

**Issue by signorekai** [aksonov/react-native-router-flux#2261]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.18
- react-native v0.45.1

### Expected behaviour

Actions.{route}() should work and navigate me to scene.

### Actual behaviour

Throws error ```ExceptionsManager.js:63 There is no route defined for key {route}.
Must be one of: 'root','newBroadcast'```

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

This is my <Router> routes.

```
<Router>
  <Scene modal={true} hideNavBar>
    <Stack key='root' renderTitle={navBarLogo}>
    <Scene key='loading' component={LoadingPage} hideNavBar={true} inital />
    <Scene key='splash' component={NewRegisterPage} type="replace" hideNavBar={true}  />
    <Scene key='feed' component={FeedPage} type="reset"  />
  </Stack>
  <Scene key='newBroadcast' component={NewBroadcastPage} direction='vertical' />
  </Scene>
</Router>
```

`Actions.feed()` throw me the no route defined error. I'm at my wit's end and would appreciate any form of help.

**Comment by signorekai** [comment]
After some diagnosing, I realise the `type='reset'` is the one causing the issue. Does anyone have any idea on how to fix this?

**Comment by aksonov** [comment]
Have you tried to use `replace` instead?

**Comment by signorekai** [comment]
Hey @aksonov, not sure why I haven't tried this previously but using `type={ActionConst.REPLACE}` fixed the issue. Will submit a PR for the docs

**Comment by ZeroCool00** [comment]
anyone solve this error..  replace is not working.

**Comment by daviscabral** [comment]
Please open a new issue with the details of your error and sample code to help someone to jump on this.

**Comment by ZeroCool00** [comment]
#3104

**Comment by ZeroCool00** [comment]
@daviscabral i open this issue here #3104
