### ISSUE TITLE
Top nav bar customization 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2262]
I wanted to know if it would be possible to customize the top nav bar like attached photo and if so how would I go about doing it? 

<img width="525" alt="screen shot 2017-08-18 at 3 00 03 am" src="https://user-images.githubusercontent.com/169507/29454318-8446fb42-83c1-11e7-80b7-2487c6501bdc.png">

**Comment by aksonov** [comment]
I don't see any issue to implement that using custom styles and navbar button images. Please specify the problem, this one is too generic (like 'is it possible to implement app like attached photo?' )

**Comment by AlmogRnD** [comment]
Ok, how would I do a custom style that has the top text i.e. Alex Smith and then the bottom test which is smaller, right now in nav bar I can just set the title and the back button text but I can't set a custom component that has both texts unless I'm missing something?

**Comment by aksonov** [comment]
I guess you may just set two lines of `<Text>` as usual React component as return it from`renderTitle` prop.

**Comment by AlmogRnD** [comment]
I thought the title prop for the back button can only accept string i.e. `back backTitle={this.props.title}`

How would you set <Text>?

**Comment by aksonov** [comment]
I believe you must use renderTitle with 'left' align, not backTitle for your design. Anyway you could just use your own navbar. 
And it looks definitely not issue, but react-native programming question (for stackoverflow or other forums).
