### ISSUE TITLE
Scene's key on the background of TabIcon

### ISSUE THREAD

**Issue by ShiiRochi** [aksonov/react-native-router-flux#2264]
### Version
- react-native-router-flux v4.0.0-beta.18
- react-native v0.46.1

### Expected behaviour
Expected to see tabbar with and Icon and Text below it with the possibility of tapping on it, so the selected will be highlighted

### Actual behaviour
Actually see Tabbar with an Icon and Text below it with Scene's keyname on the background of Tabbar item with the possibility of tapping on it, but instead of TabIcon, Scene's keyname is highlighted

### Steps to reproduce
I faced the problem with this code:
`<Router sceneStyle={{ backgroundColor: 'white' }}>
        <Scene key="root" hideNavBar>
            <Scene key="Tabbar" hideNavBar tabs default='Main' tabBarStyle={{height:50}}>
              <Scene hideNavBar key="Main" component={MainSceneContainer} icon={TabIcon} iconName="user" title="Main page"/>
          </Scene>
        </Scene>
      </Router>`
There is a picture, so you can understand what it mean:
![voaupi0zusa](https://user-images.githubusercontent.com/10761254/29455892-a83dba4a-841b-11e7-805e-dc729efe5971.jpg)

**Comment by ShiiRochi** [comment]
UPD:
Downgraded to version 3.41.0 and the code is working, so the issue persisting in vesion 4

**Comment by aksonov** [comment]
Tabbar is big breaking change for v4 unfortunately. Try to disable labels like shown in Example project: `showLabel={false}` for tabs container.

**Comment by ShiiRochi** [comment]
It helped, thanks
