### ISSUE TITLE
How to open Drawer using a custom event / action within a screen

### ISSUE THREAD

**Issue by sujayjaju** [aksonov/react-native-router-flux#2265]
#### Version
react-native-router-flux v4
#### Expected behaviour
A way to open the drawer from within a scene
#### Actual behaviour
Only the navbar button opens the drawer
#### Steps to reproduce
This is my Router
````
<Scene key="root" titleStyle={{}} hideNavBar>
    <Scene key="auth">
        <Scene key="login" component={Login} title={ I18n.t('loginTitle') }/>
    </Scene>
    <Scene key="drawer" drawer contentComponent={SideMenu} initial drawerPosition="right" drawerWidth={200} drawerLabel="Hi">
        <Scene key="main">
            <Scene key="menu" component={Menu} title={ I18n.t('menuTitle') }/>
            <Scene key="orders" component={Orders} title={ I18n.t('ordersTitle') }/>
        </Scene>
    </Scene>
</Scene>
````

I need a custom button within the Menu scene to open the drawer.
I tried: 
````
Actions.refresh({key: "drawer", open: true})
````
But that does not work since the new DrawerNavigatior does not have "open" as a config option. Docs say the way to open is:
````
this.props.navigation.navigate('DrawerOpen');
````
Not sure how to call that?

**Comment by aksonov** [comment]
Try `Actions.drawerOpen()`

**Comment by Tanumay92** [comment]
Just Add in root scene a prop drawer={true}

**Comment by Tanumay92** [comment]
Can anyone tell me how to customize the drawer which is added in root scene
??

**Comment by sujayjaju** [comment]
@Tanumay92 
You can define your own component for the drawer
```js
<Drawer key="app" contentComponent={DrawerContent} drawerWidth={300} >
```

**Comment by Tanumay92** [comment]
Can you explain a Bit @sujayjaju

**Comment by Blapi** [comment]
@Tanumay92 read the doc : 


contentComponent | React.Component |   | Component used to render the content of the drawer (e.g. navigation items).
-- | -- | -- | --

**Comment by nguyenvanphuc2203** [comment]
@aksonov it work for me

**Comment by baxri** [comment]
Worked also for me, good job :)

**Comment by cjinghong** [comment]
I'm currently facing this problem. Because I have 2 drawers, `Actions.drawerOpen()` will only open the root drawer.

**Comment by roots-ai** [comment]
> I'm currently facing this problem. Because I have 2 drawers, `Actions.drawerOpen()` will only open the root drawer. I need to be able to open a specific drawer.

How did you solve this?
