### ISSUE TITLE
[Error] The sources for assing MUST be an object. 

### ISSUE THREAD

**Issue by itswaze** [aksonov/react-native-router-flux#2266]
Hey,

I was using react-navigation, but it is full of bugs and it lacks alot of functionality, so I decided to give router-flux a try.
After changing react-navigation code with router-flux, I get this error when I try to run the app:

http://imgur.com/a/kxrwp

I have no idea why I'm getting this error. I've tried running the example app and it works perfectly, so it must be something on my app, but I have no idea what.

**Comment by aksonov** [comment]
Sorry, it is impossible to say something without code. Please fork & modify Example to reproduce issue.

**Comment by itswaze** [comment]
@aksonov I've added one screen at a time and it worked :) but unfortunetly the lib won't solve the problem I was having... I thought It was a problem with react-navigation, but I guess not.

Everytime I rotate the device, on a child screen, the transition is not smooth at all. Only on parent screens re-renders smoothly. This is the problem I'm having: https://vid.me/hhE3A

I know it's not related with this library, but I'm hoping that someone knows how to fix it.

**Comment by aksonov** [comment]
Sorry, can't help here. RNRF doesn't do any transition, it is job of react-navigation (for v4). So create issue at react-navigation github (but create pure react-navigation demo before). Make sure that you don't do any processing during device rotation.
