### ISSUE TITLE
Can I set onEnter from inside the Component?

### ISSUE THREAD

**Issue by egunsoma** [aksonov/react-native-router-flux#2267]
The code below doesn't work for me, `onExit` is not executed.

```js
  componentDidMount() {
    Actions.refresh({
      onExit: () => {
        console.log('DEBUG', this.state)
      }
    });
  }
```

**Comment by aksonov** [comment]
No, it is not possible and it is anti-pattern (because unnecessary nav state change). Just try `Actions.refs.SCENE_NAME` to use your component instance from static onExit/onEnter (you can define onEnter/onExit as STATIC functions for your component)

**Comment by egunsoma** [comment]
@aksonov And is there a way I can access the state of the component from onExit?

**Comment by aksonov** [comment]
Actions.refs.SCENENAME

**Comment by JorgeCeja** [comment]
Hello, I have been searching but I cannot find an example of how to use `Actions.refs.SCENENAME` to handle `onExit` from inside the component. Can someone please point me to an example? Thanks!
