### ISSUE TITLE
hideNavBar issue on tabs scene

### ISSUE THREAD

**Issue by todorone** [aksonov/react-native-router-flux#2268]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta18 (v3 is not supported)
- react-native v0.46.1

### Expected behaviour

`hideNavBar` prop should hide navigation bar for Scene with `tabs` prop enabled.

### Actual behaviour

`hideNavBar` prop does not hide navigation bar for Scene with `tabs` prop enabled, there is blank NavBar at the top. To get rid of NavBar I have to add `navBar={() => <View />}`.

**Comment by EskelCz** [comment]
Can confirm, I have the exact same problem.

**Comment by aksonov** [comment]
@todorone As workaround could you use `hideNavBar` for all tab children?

**Comment by todorone** [comment]
@aksonov I've tried to add `hideNavBar ` to all tab children, but it didn't work. Anyway, I'll use workaround with invisible component as `navBar` prop until bug is fixed. Thanks a lot for Your efforts with `rnrf`.

**Comment by aksonov** [comment]
I've just added `hideNavBar` to all tabs for Example project and it works well. Could you reproduce the issue with Example project.

For general fix - sorry, I can't fix this 'bug' because `hideNavBar` is NOT 'inheritable' property (i.e. children should not inherit it from parent).
