### ISSUE TITLE
How to disable swipe to back

### ISSUE THREAD

**Issue by romk1n** [aksonov/react-native-router-flux#2269]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.18
- react-native v0.47.1

### Expected behaviour
swipe to back not popping the scene

### Actual behaviour
Swiping to the right (standard swipe back behaviour) popping the scene with no back button

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. create two scenes, i.e. `Auth` and `Main`
2. define `Login` sceme in Auth and `Home` in `Main`
3. perform login action which executed Main action.
4. swipe back from Main gets you to the Login screen.

**Comment by aksonov** [comment]
Use `gestureEnabled={false}` or `panHandlers={null}`

**Comment by romk1n** [comment]
@aksonov thanks, is there a place for all of the props ? it seems in the example you using it in Tabs, but it would work in scene as well?

**Comment by mkayswork** [comment]
@aksonov gestureEnabled is not working but panHandlers is (using version 4.0.0-beta.21). What's the difference between those props???

**Comment by iKronyck** [comment]
Hi, how could I disable the virtual button to go back android, any ideas?

**Comment by Blapi** [comment]
@iKronyck What do you mean by "virtual button" on Android ?

**Comment by dancham86** [comment]
@iKronyck Do you mean the hardware back button? You need to implement the [BackHandler](https://facebook.github.io/react-native/docs/backhandler.html)

**Comment by iKronyck** [comment]
Thanks!! I'll read about that

**Comment by mrded** [comment]
Just curious, why is `gesturesEnabled` and `panHandlers` not documented?

**Comment by asatour** [comment]
Try swipeEnabled={false}

**Comment by ninechung** [comment]
> Use `gesturesEnabled={false}` or `panHandlers={null}`

its save me, thanks u.

**Comment by ninechung** [comment]
> Try swipeEnabled={false}

its not working.

**Comment by VB10** [comment]
> Just curious, why is `gesturesEnabled` and `panHandlers` are not documented?

++++

**Comment by ashishlamse** [comment]
whenever you are moving one scene to another and you want to disable swipe for current scene.Then use **Actions.replace('next-scene');** instead of Actions.push('next-scene'); or Actions.next-scene().

I resolve my problem by doing this.
