### ISSUE TITLE
Can't run example -- npm start fails with a Naming Collision

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#227]
Running npm start gives the following error:
```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/chet/github/react-native-router-flux/Example/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/chet/github/react-native-router-flux/Example/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/chet/github/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/chet/github/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/chet/github/react-native-router-flux/Example/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
This has to do with react-redux having a peer dependency on react as I comment [here](https://github.com/facebook/react-native/issues/5412#issuecomment-186432187).

I get the same result with npm2 or npm3.

**Comment by chetstone** [comment]
I've worked around this by removing the redux-related stuff from the Example. The comments in the Example state the redux stuff is optional, but it's not totally obvious how to remove it for someone not familiar with redux. 

IMHO the Example is getting a bit too complicated. It seems like the redux features could be demonstrated in a separate, much simpler example.

**Comment by kacperpotega** [comment]
When I had the same issue, removing the node_modules folder, updating node and npm and then doing a new npm install resolved the issue.

**Comment by aksonov** [comment]
Cannot reproduce with clean npm install, possibly it was upgrade problems.
