### ISSUE TITLE
navigationBarTitleImage not working in v4

### ISSUE THREAD

**Issue by iuraya** [aksonov/react-native-router-flux#2272]
### Version
- react-native-router-flux v4.0.0-beta.17
- react-native v0.47.1

### Expected behaviour
The image should appear in the navBar

### Actual behaviour
The app crashes. Seems like the import for 'Image' is missing in the NavigationStore.js

**Comment by Julinar** [comment]
same here
![screenshot_1503414969](https://user-images.githubusercontent.com/8913366/29572807-a664c1d8-875d-11e7-8bf1-cacc799ea009.png)
