### ISSUE TITLE
Can't use 4.x in TypeScript project anymore

### ISSUE THREAD

**Issue by pocesar** [aksonov/react-native-router-flux#2273]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.18
- react-native v0.47.1

### Expected behaviour

React-native-router-flux work out of the box like 3.x

### Actual behaviour

It doesn't, the typings are gone

**Comment by aksonov** [comment]
v4 has several breaking changes, so I cannot just copy typings from v4. I don't use Typescript, but feel free to submit PR

**Comment by pocesar** [comment]
the API.md file is up-to-date? if so, I can hack together a functional typing really quick

**Comment by aksonov** [comment]
Probably some props are still missing, but you could take it as the base. Also you may find new more useful syntax for containers  - you could use Stack, Modal, Tabs, Lightbox instead of Scene for containers (check Example project)...

**Comment by daviscabral** [comment]
Typings merged in #2448.
