### ISSUE TITLE
Multiple routers with v4?

### ISSUE THREAD

**Issue by JaxGit** [aksonov/react-native-router-flux#2274]
Our navigation is so complex that we are planning to use a router for main navigations and another for navigations in side drawer. (just like #353 and many others but with v4)
We are currently using react-native-drawer instead of react-navigation drawer as described in [this comment](https://github.com/aksonov/react-native-router-flux/issues/2150#issuecomment-322654872) because the former works well with react-native-scrollable-tabview.

We could demonstrate multiple 'routers' with pure react-navigation when connecting multiple AppNavigator to redux, however when using multiple `<Router/>` of router-flux v4 it failed with error "no route defined for key [other router scene key]" in getScreenForRouteName. 

As it seems in router-flux the AppNavigator is a new navigator created by new NavigationStore instance create(), I guess this is still possible to achieve with appropriate extensions?

**Comment by aksonov** [comment]
Current `Actions` (`navigationStore`) is singleton for simplicity - i.e. one instance across ap..  It is not difficult to support multiple navigationStore instances by exporting also NavigationStore class from `navigationStore.js` and don't use `Actions` but app-defined classes for it. After that it is easy to modify `Router.js` to accept `navigationStore` as optional parameter or create new instance of NavigationStore class each time.

PR is welcome. I don't have time to implement it right now and I would need some demo code anyway to work with.

**Comment by JaxGit** [comment]
Thanks for your explanation~
We are currently time restricted and may not have time for extension either, also our case may be a bit rare and single Router with react-navigation built-in drawer is sufficient for most of the cases. However we verified the following workaround for us which is faster:

- Upgrade to router-flux v4, keep using it for main navigations and track main nav states in redux by createReducer prop;
- Use pure react-navigation Navigator and manage drawer nav states in redux.
