### ISSUE TITLE
OnEnter not called for componentless scenes

### ISSUE THREAD

**Issue by brunsy** [aksonov/react-native-router-flux#2275]
This is more of a question than an issue.

I'm using v4 and would ideally like to use something similar to [#176](https://github.com/aksonov/react-native-router-flux/issues/78#issuecomment-176332149) for a basic authentication flow.

However, onEnter seems to only be called when the parent scene has a component attached to it.
Can onEnter be used like this without having to assign the parent its own component?
```javascript
<Scene key="parent" onEnter={this.isLoggedIn} 
                    onSuccess={()=>Actions.authorized()} 
                    onFail={()=>Actions.unAuthorized()}> 

          <Scene key="unAuthorized">
            <Scene key="login" component={Login}/>
          </Scene>

          <Scene key="authorized">
            <Scene key="somethingElse" component={SomethingElse}/>
          </Scene>
</Scene>
```

**Comment by aksonov** [comment]
Sorry, onEnter/onExit works only on 'component' scenes (I've just updated docs). PR is welcome for componentless scenes. 

You could add first screen (i.e. 'loading..') and move your `onEnter`, `success='authorized'`, `failure='unauthorized'` (RNRF doesn't have onSuccess/onFail) there.
