### ISSUE TITLE
Unexpected header behavior in TabNavigation

### ISSUE THREAD

**Issue by EnriqueDev** [aksonov/react-native-router-flux#2277]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.12
- react-native v0.47

### Expected behaviour
When declaring a tab navigator I would like all the tabs to share the same header, so I guessed the proper way to do this would be:

```
<Scene key="ComponentLessScene" tabs swipeEnabled={true}>
    <Scene
         key="cs1"
         hideNavBar
         component={ComponentScene1} />
    <Scene
          key="cs2"
          hideNavBar
          component={ComponentScene2} />
</Scene> 
```
And so, the expected behaviour would be something like:

![simulator screen shot 22 ago 2017 11 57 11](https://user-images.githubusercontent.com/25365731/29562436-33141ad4-8731-11e7-8112-22474d34547f.png)

### Actual behaviour
Instead what happens is this:

![simulator screen shot 22 ago 2017 12 03 47](https://user-images.githubusercontent.com/25365731/29562685-4257b69e-8732-11e7-9934-da2398dc30de.png)

**Comment by aksonov** [comment]
Unfortunately react-navigation doesn't work good for nested containers. You must add 'hideNavBar' for 'tabs' Scene to hide upper navbar.
