### ISSUE TITLE
Actions state inside Drawer

### ISSUE THREAD

**Issue by pocesar** [aksonov/react-native-router-flux#2280]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta-18
- react-native v0.47.2

```jsx
class DrawerView extends React.Component {
  render() {
    return (
      <View><Text>{this.props.data /* is always empty */}</Text></View>
    )
  }
}
// ...
<Drawer contentComponent={DrawerView}>
  <Scene key="something" />
</Drawer>
<Scene initial key="something_else" onEnter={() => Actions.something({ data: { stuff: { one: 1, two: 2 } } }) } />
```

There are no `this.props.data` *ever* inside the Drawer, and `activeItemKey` shows "something"

**Comment by aksonov** [comment]
Passing props to drawer is not supported (by react-navigation) - you are calling "something" so you must check component defined by "something", not drawer.

**Comment by pocesar** [comment]
but how to create dynamic menus inside the drawer then?
