### ISSUE TITLE
Main props in navigation options

### ISSUE THREAD

**Issue by harishsn** [aksonov/react-native-router-flux#2282]
- react-native-router-flux 4.0.0-beta.18
- react-native v0.47.2

Unable to access main props inside static navigation options. 

class ExampleComponent implements Component{

      static navigationOptions = ({ navigation, screenProps }) => ({
          headerRight: this.props.data.data.length > 0 ? <Button/> : null
    });

constructor(props) {
	super(props);
}

// Render method 

export default connect(state => ({
	data: {
		data: state.data.data,
	},
})
}))(ExampleComponent);

**Comment by aksonov** [comment]
`navigationOptions` is react-navigation stuff, not RNRF. Please use proper API of RNRF if you want to use RNRF features (like props of scenes).
