### ISSUE TITLE
Hardware Back not working when on First Scene

### ISSUE THREAD

**Issue by tusharv-bidchat** [aksonov/react-native-router-flux#2283]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.18
- react-native v0.47.1

### Expected behaviour
On Press on Hardware Back button on First Scene it should close the app.

### Actual behaviour
App does not close.

### Steps to reproduce
Here is my Router Component
const RouterComponent = () => {
    return (
        <Router
            createReducer={reducerCreate}
            getSceneStyle={getSceneStyle}
            navBarStyle={styles.navBarStyle}
        >
        <Stack key="root" hideNavBar>
            <Stack key="auth" hideNavBar>
                <Scene
                    key="login"
                    component={Login}
                    title={I18n.t('title_login')}
                    onEnter={isLoggedIn}
                />
            </Stack>
            <Stack key="home">
                <Scene
                    key="main"
                    component={Login}
                    title={I18n.t('title_login')}
                />
            </Stack>
            <Scene
                key="error"
                component={Error}
            />
        </Stack>
        </Router>
    );
};

const isLoggedIn = () => {
    const auth = AuthService.getAuthObject();
    console.log(TAG, 'IsLoggedIn Check');
    if (auth && auth.loggedIn) {
        //Actions.home({ type: ActionConst.RESET });
    }
};

**Comment by michaelduminy** [comment]
Same problem here

**Comment by aksonov** [comment]
Just pass prop backAndroidHandler to Router with own handler of back. Many users of RNRF didn't want to exit app for back button for some reason, so it works in such way.

**Comment by michaelduminy** [comment]
Ah okay, that seems to fix it. I used to use `onBackAndroid`.

**Comment by AntonDatsik** [comment]
Help me please, as I understood, onBackAndroid works only on Android?
How to resolve this problem on IOS?

**Comment by aksonov** [comment]
Do you have hardware IOS back button??

**Comment by AntonDatsik** [comment]
Oh, sorry)
I use only Android.
