### ISSUE TITLE
How to remove the effect of replacing renderTitle(title) when navigating between scene?

### ISSUE THREAD

**Issue by gtauniverse** [aksonov/react-native-router-flux#2287]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.19 
- react-native v0.46.4
 
How to remove the effect of replacing render Title when navigating between scene?

Exemple code: 
```
  <Scene lazy key="Root" renderTitle={level}>
  <Scene lazy tabs hideNavBar key="TabBar" renderRightButton={settingButton} renderLeftButton={profileButton}>
    <Scene key="myFeed" component={myFeed}/>
    <Scene  key="hotNews" component={hotNews}/>
  </Scene>

  <Scene clone key="discussion" component={discussion} renderLeftButton={backButton}/>
  <Scene clone key="pageNews" component={pageNews} renderLeftButton={backButton}/>
</Scene>
```

That's what I want to get rid of: https://i.stack.imgur.com/Oojkr.gif

**Comment by aksonov** [comment]
set `headerMode='screen'` for container

**Comment by gtauniverse** [comment]
@aksonov How to disable the NavBar animation when navigating between scenes ?
