### ISSUE TITLE
In the new version of the 'tabbar' on android does not work the 'tabBarPosition' property

### ISSUE THREAD

**Issue by gtauniverse** [aksonov/react-native-router-flux#2288]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.19
- react-native v0.46.4

### Expected behaviour
When specifying the " tabBarPosition='bottom' " property, the tabbar should be displayed at the bottom.

### Actual behaviour
Is displayed at the top.

In the previous version it works correctly

**Comment by Megamind2301** [comment]
+1

**Comment by seratonik** [comment]
+1

**Comment by aVozgrin** [comment]
+1

**Comment by sachithamadhupa** [comment]
+1

**Comment by aksonov** [comment]
Please check latest master

**Comment by sachithamadhupa** [comment]
@aksonov  can you update the package version also pls

**Comment by aksonov** [comment]
@sachithamadhupa Let's make sure that it fixes issue, could you check?

**Comment by sachithamadhupa** [comment]
@aksonov  yes I checked it, its working :)

**Comment by ValentinBlokhin** [comment]
Waiting for new npm version, thanks

**Comment by davojan** [comment]
In beta20 default tabBar position for iOS is broken. TabBar is on top by default.

**Comment by aksonov** [comment]
@davojan Thanks, check beta21
