### ISSUE TITLE
Get route title when using renderTitle

### ISSUE THREAD

**Issue by axelander** [aksonov/react-native-router-flux#229]
How do I get the title of a route when using the `renderTitle` property? I tried using below code but it doesn't work. 

```javascript
renderTitle={props => (<CustomTitle { ...props } />)}
```
When using the default title functionality it works as expected, I can pass the title property in the action to the next route. 
```javascript
Actions.login({ title: 'Hello user' })
```

**Comment by aksonov** [comment]
route is passed as first argument, so you need to use route.title

**Comment by axelander** [comment]
Hm, still doesn't work.
The part of my router that I'm having trouble with looks like this:
```javascript
<Route name="tabbar">
  <Router footer={TabBar} showNavigationBar={false}>
    <Route name="tab_menu" schema="tab" title="Sections" style={styles.route}>
      <Router>
        <Route name="menu" schema="firstView" component={MenuView} />
        <Route name="page" schema="secondView" component={PageView} />
        <Route name="article" schema="secondView" component={ArticleView} />
      </Router>
    </Route>
  </Router>
</Route>
```
So, when switching to the tab `tab_menu` the menu route is default.
When dispatching an action from MenuView to go to the page route like this:
`Actions.page({ title: 'Sports' })`
I get "Sections" as the route.props.title in my custom title.
If I remove the renderTitle prop from my scheme (also tried adding directly to the routes with the same result) I get "Sport" as the title. So it works when using the default title behaviour.

**Comment by aksonov** [comment]
Could you debug? It maybe bug.

**Comment by axelander** [comment]
Seems like route is not passed to renderTitle callback. I created a PR for ex-navigator to fix this.
https://github.com/exponentjs/ex-navigator/pull/97

**Comment by aksonov** [comment]
Hm, why PR to ex-navigator? ex-navigator is not connected with routing from this component.
As far as i see renderTitle is binded to route within ExRouter:
```
        if (this.route.props.renderTitle){
            this.renderTitle = this.route.props.renderTitle.bind(this.route);
        }
```

**Comment by axelander** [comment]
When passing in the route like in my PR you get an `ExRouteAdapter` as the first argument in `renderTitle`. When removing it, you get a `ExNavigator`. So I guess the `.bind` part is not working as expected? Do you have any ideas how this could be fixed within RNRF?

**Comment by axelander** [comment]
So, I found the problem with the `.bind` and created a [PR](https://github.com/aksonov/react-native-router-flux/pull/245).

**Comment by aksonov** [comment]
Please check issue for new 3.0 release. Closing this ticket (because it is for outdated 2.x release)
