### ISSUE TITLE
[Lack of Docs:- Easy Example] Can someone please help me with side-menu (drawer)? 

### ISSUE THREAD

**Issue by themakerman** [aksonov/react-native-router-flux#2291]
This is what my Router looks like now. I am really struggling with the docs. I have implemented my own toolbar using views which has hamburger icon. The toolbar is at mainscreen.
![toolbar](https://user-images.githubusercontent.com/14818804/29744271-27424a7c-8ad4-11e7-81cd-ca85e4e4d269.png)

Due to lack of Documentation i am really struggling to use navDrawer in my code. The app is in production so i feel very reluctant to make changes to the code as it can break it if i don't use it correctly. Debugging again will be a pain.

This is how my file with Router component looks like.
```
<Router getSceneStyle={() => ({ backgroundColor: 'transparent' })}>
                  <Scene key="root">
                    <Scene key="splash" component={SplashScreen} hideNavBar initial />
                    <Scene key="mainscreen" component={MainScreen} type="reset" hideNavBar />
                    <Scene key="settingsScreen" component={SettingsScreen} hideNavBar />
                  </Scene>
                </Router>
```
What should i do so that on my component={MainScreen} i can trigger the navDrawer on `<TouchableOpacity onPress={ () => ?} />`. Hamburger icon is nested inside TouchableOpacity component.

Would really be grateful if someone can help me out on this.

**Comment by aksonov** [comment]
Have you tried Example project from this repo?

**Comment by mkayswork** [comment]
@themakerman you could call the drawer via _Actions.drawerOpen()_. @aksonov within the example there is nothing about read or see about the drawer.

**Comment by themakerman** [comment]
@mkayswork Yes but i am more like confused towards defining the view itself. Where should i define it as a component? Should it be nested inside <Scene key="root"> ....... </Scene> ?

**Comment by mkayswork** [comment]
You mean the view that should be displayed as drawer a.k.a. side menu? You could define a Scene  which contains the drawer like so ( version 4 of this project, not version 3):

`<Scene key='drawer' drawer contentComponent={YourSideMenu} hideNavBar>
</Scene>`

And within this tag you nest in the the views which should access the side menu. Let's assume you have a view which contains a button on the left side of the navBar:

`<Scene key='sampleView' onLeft={() => this.openSideMenu()} leftButtonImage={require('your image source'}/>
`
Somewhere inside your function you have this function
`openSideMenu() {
  Actions.drawerOpen()
}`

Hope this helps you.

**Comment by themakerman** [comment]
@mkayswork Great. Thank you so much :). Gonna try it tonight.
