### ISSUE TITLE
Refresh drawer

### ISSUE THREAD

**Issue by Nautal** [aksonov/react-native-router-flux#2292]
- react-native-router-flux v4.0.0 beta-19
- react-native v0.45

I want to refresh drawer when a button in a scene is clicked, is there any way to do that??

Thanks

**Comment by aksonov** [comment]
As I know it is not supported (by react-navigation and RNRF). You have to use mobx or redux for that.

**Comment by Nautal** [comment]
And it's possible to get an example?

Thanks a lot

**Comment by aksonov** [comment]
Sorry, it is not about RNRF, but your app state management. Drawer `contentComponent` is usual react component, check mobx or redux docs about it.

**Comment by aksonov** [comment]
Maybe it is possible to refresh state for drawer component, I will think about it.

**Comment by Nautal** [comment]
Would be great, at least in my case. I show user info in the drawer and when he updates the info on the profile scene, I must refresh the drawer info.

**Comment by aksonov** [comment]
I don't have any ETA for this. I have similar drawer too and it is not about react navigation - you definitely need to use mobx/redux for that (mobx is much easier, as for me)

**Comment by aksonov** [comment]
With mobx your drawer will be re-rendered automatically once you change profile :)

**Comment by aksonov** [comment]
Sorry, I will not do things more complex - just check #2094 example
