### ISSUE TITLE
Spacing between leftButton and title on navBar

### ISSUE THREAD

**Issue by wayne1203** [aksonov/react-native-router-flux#2294]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.19

I found a spacing between leftButton and title, can I remove the white spacing so the title part can move left

![2017-08-28 5 37 30](https://user-images.githubusercontent.com/8578341/29768225-0e0ef52e-8c18-11e7-87f9-80eab9a323d4.png)

**Comment by aksonov** [comment]
It is not supported at this moment. You may fork and edit sources of `NavBar` or event `react-navigation` to achieve that.
