### ISSUE TITLE
Setting initial route on router?

### ISSUE THREAD

**Issue by tristangodfrey** [aksonov/react-native-router-flux#230]
My RN app determines what the initial route should be before anything is rendered, is there a way of passing this initial route to the `Router` and letting it handle everything from there?

My only other option would be to do something like this for all routes

```
<Route
      name={routeNames.TASK_LIST}
      initial={initialRoute === routeNames.TASK_LIST}
      schema="default"
      title="Tasks"
      component={Screens.TaskList} />,
```

**Comment by kacperpotega** [comment]
I had a similar issue. Solved this by setting the initial route to a loading screen and dispatching a navigate action (Action.NewRouteName), navigating to the route that the application calculated.

**Comment by tristangodfrey** [comment]
@kacperpotega Yeah that was my old solution but it's far less than ideal, I guess it's time to finally read the source code and see if I can submit a PR at some point.

@aksonov Do you think it's a good idea to be able to set an initial route prop on a Router component to allow dynamic initialisation? Or am I missing an easier solution?

**Comment by aksonov** [comment]
@tristangodfrey Yes, it is good idea, old version supported it in the past, feel free to submit PR to support it for latest version...

**Comment by tristangodfrey** [comment]
@aksonov I'll be able to look at it at some point next week I think, should I leave this issue open until then?

**Comment by dan-lee** [comment]
@tristangodfrey Good issue, I also need this :+1: ! Did you have some time working on this?

**Comment by aksonov** [comment]
Switch custom renderer for newly release 3.0 version could be used for this, check README. 2.x version is not supported from now.
