### ISSUE TITLE
How to make "navBar" not animated, for example as "tabBar". 

### ISSUE THREAD

**Issue by gtauniverse** [aksonov/react-native-router-flux#2300]
### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.46.4

 How to make "navBar" not animated, for example as "tabBar". That is, when switching between scenes, the transition animation was not applied to "navBar".

**Comment by aksonov** [comment]
Use `headerMode='screen'` prop.

**Comment by gtauniverse** [comment]
@aksonov it's not exactly what I want. How to make a 'navbar' a global component? That is, it did not redraw when switching between scenes
