### ISSUE TITLE
Transition between scene with navbar and transparent navbar

### ISSUE THREAD

**Issue by dgruseck** [aksonov/react-native-router-flux#2301]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

### Expected behaviour

A smooth transition where the first screen is not modified.

### Actual behaviour

When you switch from a screen with a navbar and one with a transparent (navTransparent={true}) the first screen is also changing to a transparent navbar and the content is moving up.
If you have a page with a lot of content that looks really laggy.

You can check the Example App. If you go from Login2 to Login3 the content of Login2 is moving and the navbar is transparent.

Do you have any solution for that or is it a issue of react navigation?
Thank you

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Go to Login2
2. Go to Login3
3. Watch Login2 during the transition

**Comment by aksonov** [comment]
You need to use `headerMode='screen'` for different animation.
