### ISSUE TITLE
Back button does not disappear when use the 'back' property on Scene.

### ISSUE THREAD

**Issue by Jaehwi** [aksonov/react-native-router-flux#2302]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-bata.21 (v3 is not supported)
- react-native v0.47.1

### Expected behaviour
back button disappear

### Actual behaviour
back button appear

**Comment by mcabs3** [comment]
Are you saying that you are using `back={false}` prop in a scene and it still shows the back button? We need a little more context to assist you with your issue.

**Comment by aksonov** [comment]
`back` is used only to `display` back button. Try to use `init` prop not to display back button
