### ISSUE TITLE
Custom navBar

### ISSUE THREAD

**Issue by pgonzalez-santiago** [aksonov/react-native-router-flux#2304]
Hey guys, 
first of all, I want to thank for the react-native-router-flux. It is amazing. 

I have been using the router since the version 3, but now I have migrated my project to the latest version.

I was using a custom navBar in some of my screens but it seems that custom navBar doesn't work as before. Its possible to have a custom navBar working in v4 as in v3? I need to render a left button with title and two right buttons.

E.g.
![menu](https://user-images.githubusercontent.com/17064785/29867815-0b7797e2-8d7d-11e7-8a02-017290d7b758.jpg)

With a customBar in the Scene I have this strange behaviour when navigate, looks like it is rendering back and menu icon at the same time.

![customnavbar2](https://user-images.githubusercontent.com/17064785/29868836-d41ccf70-8d80-11e7-9eb0-099cd60edf6b.gif)

Any ideas?

Also, its possible to increase the whole area of the right or left button? Imagine that I want a search input from the right when the search icon is pressed.

Thank you.

### Version
- react-native-router-flux v4.0.0-beta.17
- react-native v0.47.1

**Comment by pgonzalez-santiago** [comment]
Here you can see the effect with slow animation. You can appreciate it after the back icon button is pressed.
![customnavbar3](https://user-images.githubusercontent.com/17064785/29873524-dbf3ed56-8d93-11e7-815c-f9708180a074.gif)

**Comment by mcabs3** [comment]
From the looks of your second slow animation, it looks like it could be rendering the "actual" navigation first, and then laying your navBar overtop, you can see the slight shift of the hamburger icon which would suggest this.

so I think it is actually going back a screen, rendering that navBar internally (built from RNRF) and then laying your navBar on top after.

**Comment by aksonov** [comment]
@mcabs3 is right, please disable RNRF navbar then. If you still have issue please try to reproduce it with Example project.

**Comment by pgonzalez-santiago** [comment]
Sorry for asking but How can I disable the navBar? :/ I know how to hide it, but no how to disable it. @aksonov

**Comment by aksonov** [comment]
hide==disable

**Comment by pgonzalez-santiago** [comment]
RNRF navbar is hidden (disabled) in my case. The main problem is the "animation" between two custom navbars or a navbar and a custom navbar. As you can see in the image that I posted it looks like one navbar dissapear, then a black background appears and then the new navbar is rendered. How can I avoid that? Its possible to remove those 'animations'?

Did you test the transitions between custom navBars?

**Comment by aksonov** [comment]
Try `headerMode='screen'` for container scene for different animation

**Comment by aksonov** [comment]
I didn't test custom nav bars. Please fork and add it to Example project to demonstrate the issue.

**Comment by pgonzalez-santiago** [comment]
My fork has been merged. Now the example have some scenes with custom navbar.

Thank you.

**Comment by ericklarac** [comment]
@pgonzalez-santiago Hey, how do you modify the navBar on react-native-router-flux, I mean how do you set a custom navBar

**Comment by hugoh1995** [comment]
@ericklarac you can customize most attributes of the nav bar check out the doc otherwise you can hide it with hideNavBar and create a custom component to replace it instead
