### ISSUE TITLE
Dynamically hide tabbar

### ISSUE THREAD

**Issue by knightsforce** [aksonov/react-native-router-flux#2306]
It is indispensable to dynamically hide or show a tabbar. For example with onFocus and onBlur. The call to Actions.refresh ({hideTabBar: true}) removes the focus from the TextInput.

**Comment by aksonov** [comment]
Looks like it is behaviour of `react-navigation` and it just re-renders whole view with losing focus. Probably you need to check `react-navigation` tabbar demos and try to reproduce the problem there (and create issue if any)
