### ISSUE TITLE
Change drawer icon 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2307]
Is there an example or some simple code showing how you can change the drawer icon, I'm not seeing this in the docs and not sure how to do this. 

Thanks,
Almog

**Comment by esb1** [comment]
![image](https://user-images.githubusercontent.com/9201195/29907533-39fffbf0-8e1c-11e7-8654-1f62226ab77a.png)
It seems to me there is a prop you can pass to `Scene` when declaring it, unless I misunderstood your question. 
Image is from [Docs - API](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md)

**Comment by AlmogRnD** [comment]
@esb1 I'm not sure I understand the following "you have to set it together with drawer prop"

And is this correct 
`
drawerImage={{require('../../images/icon.png')}}`

**Comment by mcabs3** [comment]
I think you need to remove a pair of {}

`drawerImage={require('path/to/image.png')}`

**Comment by AlmogRnD** [comment]
Thanks this is perfect

**Comment by adriannecris** [comment]
Does anybody know how to reposition the drawer image?

**Comment by adriannecris** [comment]
![image](https://user-images.githubusercontent.com/35050635/55201718-3ccba480-51ff-11e9-9c39-7ca98c266fe6.png)

**Comment by Nathar2412** [comment]
@adriannecris Did you find the solution for this. I am facing the same problem.
