### ISSUE TITLE
How to transfer parameters to another scene without going over to it?

### ISSUE THREAD

**Issue by rogoja** [aksonov/react-native-router-flux#2309]
How to transfer parameters to another scene without going over to it?

**Comment by luco** [comment]
mobx?

**Comment by aksonov** [comment]
It could be good enhancement. Check navigationStore.refresh method sources - you may add optional `key` retrieving from `data`. The problem here that `key` is generated by `react-navigation` and it is not the same as RNRF `key` property...

**Comment by aksonov** [comment]
Closing due inactivity.
