### ISSUE TITLE
Allow passing container scene name for popTo method

### ISSUE THREAD

**Issue by ptquang86** [aksonov/react-native-router-flux#2310]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.21
- react-native ^0.44.3

### Expected behaviour

My project use middlewares in v3.

~~~
export default (s: State, a: PlainAction): State => {
    switch (a.type) {
    case 'LOGIN_FORM_OPEN':
        return { name: 'login' }
    case 'LOGIN_FORM_CLOSE':
        return { name: 'pop' }
    case 'AUTH_DID_AUTH':
            return { name: 'popTo', data: 'root' }
    }
    return noRoute
}
~~~

~~~
export default () => {
    return <Router createReducer={reducerCreate} tintColor={colors.greeny_blue} getSceneStyle={getSceneStyle}>
        <Stack key='root'>

            <Tabs key='tabs' hideNavBar tabs showLabel={false} tabBarComponent={TabBar}>
                <Stack {...navBarProps} key='feed'>
                    <Scene key='feedView' title='Feed' component={FeedContainer} />
                </Stack>

                <Stack {...navBarProps} hideNavBar={false} key='more'>
                    <Scene key='moreView' title='More' component={More} />
                </Stack>
            </Tabs>

            <Scene key='login' component={Login} hideNavBar={true} />

        </Stack>
    </Router>;
};
~~~

### Actual behaviour

pop works
popTo does not work now. It cause the app freezed
How to migrate middlewares to v4?
Are there any examples?

**Comment by aksonov** [comment]
`popTo` now requires scene name, not container ('root' is container)

**Comment by ptquang86** [comment]
thanks for your feedback @aksonov

i tried popTo tabs with no luck
my flow is: tabs > login > back to tabs
Do you have any suggest?

Sorry for my stupid questions.
If possible, please add more examples to prevent the newbies like me to bother your time :)

**Comment by aksonov** [comment]
tabs is container as well - `popTo` requires child only - like feedView in your example.

**Comment by aksonov** [comment]
But I see problem in your case - you don't know what child will be...

**Comment by ptquang86** [comment]
feedView works
thank you

How about currentTab or activeTab?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
