### ISSUE TITLE
Reset Stack

### ISSUE THREAD

**Issue by EnriqueDev** [aksonov/react-native-router-flux#2312]
### Version
- react-native-router-flux v4.0.0-beta.12
- react-native v0.47

Is there a way to reset the navigation stack when navigating to a scene?

**Comment by taylorgoolsby** [comment]
Does this work?
```
import { Actions } from 'react-native-router-flux';
Actions.reset('SCENE_NAME')
```

**Comment by mcabs3** [comment]
If you want it to reset overtime, apply the `type={ActionConst.RESET}` to your `Scene` if you are trying to do it per situation, then you can do `Actions.reset('SCENE_NAME');` like @taylorgoolsby stated.

Cheers

**Comment by EnriqueDev** [comment]
As far as I've understood reset just resets the state, but doesn't seem to unmount the stack because I'm getting an error of an undefined value when I try to log out an user in my app. Weird.

**Comment by aksonov** [comment]
Please reproduce that error on Example project.

**Comment by aksonov** [comment]
Closing because of no details are given. Feel free to reopen when you can describe problem in more detail.
