### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.BackHandler.addEventListener')

### ISSUE THREAD

**Issue by frankcary** [aksonov/react-native-router-flux#2316]
undefined is not an object (evaluating '_reactNative.BackHandler.addEventListener')

componentDidMount
    Router.js:26:152
<unknown>
    native.js:525:15
measureLifeCyclePerf
    ReactCompositeComponent.js:64:11
<unknown>
    ReactCompositeComponent.js:362:12
notifyAll
    CallbackQueue.js:75:26
close
    ReactNativeReconcileTransaction.js:36:4
closeAll
    Transaction.js:222:29
perform
    Transaction.js:163:24
batchedMountComponentIntoNode
    ReactNativeMount.js:78:4
perform
    Transaction.js:149:24
renderComponent
    ReactNativeMount.js:149:6
renderApplication
    renderApplication.js:34:4
runApplication
    AppRegistry.js:163:26
__callFunction
    MessageQueue.js:244:47
<unknown>
    MessageQueue.js:108:26
guard
    MessageQueue.js:46:4
callFunctionReturnFlushedQueue
    MessageQueue.js:107:10

**Comment by frankcary** [comment]
"react": "16.0.0-alpha.6",
"react-native": "0.43.2",
 "react-native-router-flux": "^4.0.0-beta.21"

**Comment by mcabs3** [comment]
Can you provide some more detail about your Router?

**Comment by aksonov** [comment]
@frankcary I believe you must use latest React Native, it is not RNRF issue. Try to google error first...
https://stackoverflow.com/questions/44077830/undefined-is-not-an-object-evaluating-reactnative-backhandler-addeventlistene
