### ISSUE TITLE
Is it possible to reset child stack only?

### ISSUE THREAD

**Issue by rexlow** [aksonov/react-native-router-flux#2317]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.39.1
- react-native v0.44.0

### Expected behaviour
I now have several scenes and would like to keep the root scene alive while shutting down some specific child scene in the stack.

This is my router configuration.
`root` -> `A` -> `B` -> `C`

When move from `B` to `C`, is it possible to entirely remove both `A` and `B` from the stack, so my navigation stack would become as follow:
`root` -> `C`

There will be a time where user will pop the scene from `C` to `root` without going through either `A` or `B`.

If we keep `A` and `B` in the stack while presenting `C`, will there be a performance trade-off?

Rex.

**Comment by aksonov** [comment]
Unfortunately it is not supported (by react-navigation), but it is possible to implement - just define `reset` action without `react-navigation`, PR is welcome...
