### ISSUE TITLE
react-native-router-flux

### ISSUE THREAD

**Issue by RamkumarBPE** [aksonov/react-native-router-flux#2319]
How to display the tab bars in all scenes react native router flux

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment]
Just set `<Tabs>` or `<Scene tabs>` as root scene.
