### ISSUE TITLE
How to use react-native-custom-navigation module in this router ?

### ISSUE THREAD

**Issue by Iliyass** [aksonov/react-native-router-flux#232]
Hi guys,
I really like this router, but react native transitions are not that good, I found a another module that have really cool transitions, but I couldn't figure out how it's been done in the source code, so, is there anyway I can use the other module or just transitions into this router ?

**Comment by aksonov** [comment]
Currently this component just uses standard react native transitions (sceneConfig property).
react-native-custom-navigation looks very nice, all components are open source, feel free to submit PR with improved transitions.

**Comment by aksonov** [comment]
3.0 version is release. It uses new RN Navigation API with better transitions.
