### ISSUE TITLE
Cannot set tabbar position

### ISSUE THREAD

**Issue by biancaFarcas** [aksonov/react-native-router-flux#2320]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.19(v3 is not supported)
- react-native v0.47.2

### Expected behaviour
On ios i want to set tabbar position on top

### Actual behaviour
Tabbar is displayed only on bottom

### What I tried: 
-added props like: top or tabBarPosition='top'. I added those props to  <Tabs> and <Scene tabs={true}> and still did not work.

**Comment by aksonov** [comment]
Please always try to use LATEST version before reporting... #2288
