### ISSUE TITLE
App closes when pressing hardware back button

### ISSUE THREAD

**Issue by pvroosendaal** [aksonov/react-native-router-flux#2323]
### Version
"react-native-router-flux": "^4.0.0-beta.20",
"react-native": "0.44.0",

### Expected behaviour
App doesn't close, but only goes back in navigation stack

### Actual behaviour
App closes, but when I reopen it, it has gone back a step in navigation stack

Any help is welcome, thanks!

**Comment by pvroosendaal** [comment]
Fixed it by overriding 'hardwareBackPress':

```
componentDidMount() {
	BackAndroid.addEventListener('hardwareBackPress', this.handleBackButton)
}

componentWillUnmount() {
	BackAndroid.removeEventListener('hardwareBackPress', this.handleBackButton)
}

handleBackButton() {
	return true
}
```

**Comment by Salman18** [comment]
Where we have to override this.

In code ?


Any Dependencies need to be installed

**Comment by Blapi** [comment]
It's from react-native, not react-native-router-flux, check the doc : https://facebook.github.io/react-native/docs/backhandler.html

And of course, this is only for Android.

**Comment by Salman18** [comment]
yeah. I am using android only.

But I am using react-native router flux for navigation.

my application gets closed if I press back button on Android.


any Suggestions?

**Comment by Blapi** [comment]
If you read the doc carefully, you'll see this foe the Router component :


Property | Type | Default | Description
-- | -- | -- | --
children |   | required | Scene root element
wrapBy | Function |   | function to wrap each Scene component and nav bar buttons - allows easy MobX integration (by passing observer)
sceneStyle | Style |   | Style applied to all scenes (optional)
backAndroidHandler | Function |   | Allows custom control of hardwareBackPress in Android (optional). For more info check BackHandler.
uriPrefix | string |   | A uri prefix to strip from incoming urls for deep linking. For example, if you wanted to support deep linking from www.example.com/user/1234/, then you could pass example.com to only match paths against /user/1234/

Use the `backAndroidHandler` property, there's already a lot of examples of how to do it on GitHub and SO

**Comment by Salman18** [comment]
okay thanks
 will look on this,
