### ISSUE TITLE
How to achieve Multi Level Menu inside Control Panel ?

### ISSUE THREAD

**Issue by Balasnest** [aksonov/react-native-router-flux#2327]
### Version
versions: 4.0.0-beta.18

I have created control panel using `react-native-drawer`. I want to navigate from main menu to sub menus.

### Expected behaviour
 Its navigating over the screen where drawer is created.

### Actual behaviour
[Like this one - Multi Level Menu](https://dl.dropboxusercontent.com/content_link/fJsrU4CEjCGadQIlmTfPOB5OLYX2oXYkMjUgbEdb2lvv3bz6UQClUPzPJCxX2Y7f/file)
Is it possible to navigate inside the control panel itself ?

**Comment by mcabs3** [comment]
The link you provided is a 404 error

**Comment by aksonov** [comment]
Anyway only built-in `Drawer` is supported at this moment...
