### ISSUE TITLE
Actions list is empty

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2329]
Hello!

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

### Expected behaviour

```Actions.myScene``` should transition to that scene

### Actual behaviour

throws ```underfined is not a function```

### Steps to reproduce

Could not start  Example project to reproduce. It gave me ```native module cannot be null```

I have almost same setup as in README. But in my case ```Actions``` does not have any information about my scenes. I've tried to log ```create``` and ```processScene``` in ```navigationState (Actions)``` - they never called.

What I'm missing?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project. Probably you are using Actions before it is created. Try to wrap it into function, like `() => Actions.myScene()`

**Comment by kesha-antonov** [comment]
@aksonov Thanks!

My mistake! I'm trying to migrate from v3 to v4 and I was using
```Scene, Router``` from ```react-native-mobx```. I guess it is not needed anymore?

**Comment by aksonov** [comment]
Yes. Just pass `wrapBy={observer}` to `Router` and you don't need to wrap your scenes manually!

**Comment by kesha-antonov** [comment]
Ok! Thanks!
