### ISSUE TITLE
BEFORE_ROUTE action doesn't return the right route.

### ISSUE THREAD

**Issue by alexmngn** [aksonov/react-native-router-flux#233]
Hello,
When I activated the following to see what I get from the action, it looks like the action returned by BEFORE_ROUTE is not correct.

```
case Actions.BEFORE_ROUTE:
	console.log('BEFORE_ROUTE:', action);
	return state;
case Actions.AFTER_ROUTE:
	console.log('AFTER_ROUTE:',  action);
	return state;
```

Navigating from `login` to `register`, then from `register` to `login`, I get this:

> BEFORE_ROUTE: Object {} Object {type: "BEFORE_ROUTER_ROUTE", route: Route, name: "register"}
> index.ios.js:20 AFTER_ROUTE: Object {} Object {type: "AFTER_ROUTER_ROUTE", route: Route, name: "register"}
> index.ios.js:23 BEFORE_POP: Object {} Object {type: "BEFORE_ROUTER_POP", route: Route, name: "register"}
> index.ios.js:26 AFTER_POP: Object {} Object {type: "AFTER_ROUTER_POP", route: Route, name: "login"}

As you can see, the `BEFORE_ROUTE` says `register` while it should return `login`, because before I was on the login page.

My router looks like this:

```
class MyApp extends Component {
	render() {
		return (
			<Provider store={store}>
				<Router name="root">
					<Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} />
					<Route name="login" component={Login} initial={true} title="Login" renderTitle={false} rightTitle="Register" onRight={() => {
						Actions.register();
					}} />
					<Route name="register" component={Register} title="Register" />
				</Router>
			</Provider>
		);
	}
}
```

**Comment by aksonov** [comment]
3.0 version is released. Closing this ticket (because it is for outdated 2.x release)

**Comment by joshbedo** [comment]
@aksonov is their still a `BEFORE_ROUTER_ROUTE` event that gets called in 3.0?
