### ISSUE TITLE
[Tabs] How to setup initial scene as tab scene?

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2330]
Hello again!

I have this setup (simplified):

```
<Router>
  <Stack key='root'>
    <Scene initial={false} key='scene1' component={Component1}>
    </Scene>
    <Scene key='scene2' component={Component2}>
    </Scene>
    ...
    <Tabs key='tabbar'>
      <Scene key='tab1' initial={true}>
        <Scene key='tab1_scene1' component={TabComponent1} />
      </Scene>
      <Scene key='tab2' initial={false}>
        <Scene key='tab2_scene2' component={TabComponent2} />
      </Scene>
      ...
    </Tabs>
  </Stack
</Router>
```

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

### Expected behaviour

I want to see ```tab1_scene1``` as an initial scene when app starts

### Actual behaviour

Scene ```scene1``` renders as initial

In v3 this configuration worked as expected

Please help! @aksonov 
I've tried different combinations of options with no luck.

**Comment by mcabs3** [comment]
set `initial` on the `tabbar` and it will load the tabbar and by default the first scene in the tabbar. Or move tabbar to the first scene in the nested `Stack` and you won't need the `initial` attribute.

**Comment by kesha-antonov** [comment]
@mcabs3 Thanks! I'll try this
