### ISSUE TITLE
How to give new scene title in parameter?

### ISSUE THREAD

**Issue by zilahir** [aksonov/react-native-router-flux#2332]
### Version

```
"react-native-router-flux": "^3.35.0",
"react-native": "0.44.0",
```

I have 3 screens defined in `Router.js` as the following: 

```
<Scene key="main">
 <Scene
        key="channelView"
        component={ChannelView}
        title="Channel"
        />
</Scene>
```

The way I am navigating to this scene is the following: 

`onRowPress() {
    channelView({ channel: this.props.channel });
  }`

The `this.props.channel` contains an object, which has a `title` attr, and I would like to use this one as the `title` of the Scene. How can i do that?

**Comment by mcabs3** [comment]
Referring to the [docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md)

Try `Actions.channelView({ title: this.props.channel.title, channel: this.props.channel })`
