### ISSUE TITLE
Element type is invalid: expected a string.

### ISSUE THREAD

**Issue by GuillaumeMunsch** [aksonov/react-native-router-flux#2336]
### Version
- react-native-router-flux v4.0.0-beta.21 
- react-native v0.44.2

I'm having issues implementing the new version of the router into my application.
Whatever I try I keep running into this error: 

<img width="320" alt="capture d ecran 2017-09-04 a 18 24 02" src="https://user-images.githubusercontent.com/8775145/30033870-591356ba-919e-11e7-8286-a8060748ada0.png">

I did some tests with my app and I even tried removing all my routing but just the fact that I'm upgrading the package to the v4 pops this error out.

I'm sadly out of ideas :/. Do you have any clue what could cause this ?

**Comment by luco** [comment]
Please, post some code.

**Comment by GuillaumeMunsch** [comment]
Alright, there it is:

`index.ios.js`: 
```
import {
  AppRegistry,
} from 'react-native';
import SquareboardMobile from './src';

AppRegistry.registerComponent('SquareboardMobile', () => SquareboardMobile);
```

`./src/index.js`:
```
import React from 'react';
import { Provider } from 'react-redux';
import AppView from './AppView';
import store from './store';

const SquareboardMobile = () => (
  <Provider store={store}>
    <AppView />
  </Provider>
);

export default SquareboardMobile;
```

`./src/AppView.js`:
```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
} from 'react-native';
import {
  Scene,
  Router,
  Reducer,
  Stack,
} from 'react-native-router-flux';
import { connect } from 'react-redux';

const getSceneStyle = () => ({
  backgroundColor: '#F5FCFF',
  shadowOpacity: 1,
  shadowRadius: 3,
});

class AppView extends Component {
  constructor(props) {
    super(props);
    this.reducerCreate = this.reducerCreate.bind(this);
  }

  reducerCreate(params) {
    const defaultReducer = new Reducer(params);
    return (state, action) => {
      console.log('ACTION:', action);
      this.props.dispatch(action);
      return defaultReducer(state, action);
    };
  }

  render() {
    return (
      <Router createReducer={this.reducerCreate}>
        <Stack key="root">
          <Scene key="login" component={<Text>Test</Text>} title="INIT" />
        </Stack>
      </Router>
    );
  }
}

export default connect()(AppView);
```
`react-native-router-flux` and `react-native` versions are still the same. The error kind of changed though. I have an additional information. There it is:

![capture d ecran 2017-09-05 a 11 38 58](https://user-images.githubusercontent.com/8775145/30055470-e0698b16-922f-11e7-9526-30830664e423.png)

It looks like there is something with the `Wrapped` component.

**Comment by GuillaumeMunsch** [comment]
`<Scene key="login" component={<Text>Test</Text>} title="INIT" />` should be `<Scene key="login" component={() => <Text>Test</Text>} title="INIT" />` ...

I'm getting blind after hours of debugging ...
Thanks for your time guys
