### ISSUE TITLE
Example project error

### ISSUE THREAD

**Issue by pgonzalez-santiago** [aksonov/react-native-router-flux#2337]
I am trying to run the Example project and get this error. 

![screen shot 2017-09-05 at 11 30 15](https://user-images.githubusercontent.com/17064785/30054882-e1622c50-922d-11e7-8f98-eec53aa855ae.png)

Any ideas?

**Comment by aksonov** [comment]
Should be fixed now, please update to latest master

**Comment by pgonzalez-santiago** [comment]
Its solved. Thank you.
