### ISSUE TITLE
Two routers, one for Main Application and one for Share application

### ISSUE THREAD

**Issue by arribbar** [aksonov/react-native-router-flux#2338]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta17
- react-native v0.47.1

### Description
I have an application using RNRF with all routes. I created a share application, to be able to share photos with my main application on Android.

### Old config in RNRF v3
I was creating two different routers for the main app and the share app. It was working fine.

I had to change routers component to be stateless to prevent warnings and doing so, my router component for the share part is not working anymore. 
There is an error in getScreenForRouteName, line 21 saying `There is no route defined for key mainApplication. Must be one of 'shareApplicationRouteOne', 'shareApplicationRouteTwo'

### Question
Do I have to do only one router component for the Main App and the Share App? Or is there something else I need to do ?

I made a fork reproducing the bug in Example folder here
https://github.com/arribbar/react-native-router-flux/tree/errorRouter

**Comment by arribbar** [comment]
@aksonov Do you have an hint about how to do it ?

**Comment by arribbar** [comment]
Well, it was working with an old version of RNRF, 3.38.0

It is not due to stateless components as I thought before, I have still the bug.
I do not have the bug on iOS. This is only for Android.

**Comment by arribbar** [comment]
@aksonov Any idea to help me, please ?

**Comment by aksonov** [comment]
It is not supported for v4, sorry.

**Comment by arribbar** [comment]
Questions, is it due to react-navigation or react-native-router-flux ?
And what would you advise? Go back to v3.38 or do without router for the share part ?
