### ISSUE TITLE
No ability to hook onto the onPress of a tab button to reset stack, etc

### ISSUE THREAD

**Issue by seratonik** [aksonov/react-native-router-flux#2343]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

### Expected behaviour

Should be able to hook onto the action of pressing a tab item so that stacks within tab can be reset, or scrolling to top can be implemented when tab is pressed multiple times.

### Actual behaviour

No onPress capabilities, there's an open PR in `react-navigation` that will potentially enable this: https://github.com/react-community/react-navigation/pull/1335

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Build tabbed content
2. Clone or push a bunch of views into one of the tabs
3. Press tab to reset back to default scene for that tab

**Comment by aksonov** [comment]
Sorry, it is not supported yet.

**Comment by aksonov** [comment]
For now, you can try onEnter handler.

**Comment by mcabs3** [comment]
@seratonik you could also try creating an `Icon` component that will do what you are asking. Just trying to toss ideas around for you to find a solution.

**Comment by seratonik** [comment]
@aksonov @mcabs3 Thank you both for the suggestions, I'll give those a try and see if they get me up and running.

**Comment by d7laungani** [comment]
@seratonik Have you managed to fix this issue and if so how did you do it ?

**Comment by seratonik** [comment]
@d7laungani Sorry for delay getting back, I built a custom component to use as a tab bar and passed it to the `tabBarComponent` prop of the <Tabs> scene.

The upstream PR for react-navigation that I mentioned in this issue has now been merged, so perhaps it could be used in the future when its makes it into this project?

**Comment by ovaris** [comment]
I need similar functionality and I would not like to build a custom tab bar :( @aksonov onEnter does not work because it's only called when entering scene/tab, not when it pressed for the second time. I also tried to add this to scene component:
```
static navigationOptions = (props) => {
    return {
      tabBarOnPress: (tab, jumpToIndex) => {
        console.log('FOO', props);
        if (!tab.focused) {
          jumpToIndex(tab.index);
        } else {
          if (_scrollView) {
            _scrollView.scrollTo({ x: 0, y: 0, animated: true })
          }
        }
      },
    };
  };
```
which would be a perfect solution because I need ref to scrollView BUT adding navigationOptions to scene component will make Icon to disappear. Any further ideas howto implement this? I could use `onTabPress` handler in Scene but I would need to hae `ref` to scroll view...

**Comment by ovaris** [comment]
My hack(ish) solution:
```
onTabPress(scene) {
    const { focused, route } = scene;
    if (route.key === 'feed' && focused) {
      return this.feedRef.scrollToTop();
    }
    return Actions[route.key].call();
}
....
                   <Tabs
                      initial
                      key="tabs"
                      showLabel={false}
                      activeBackgroundColor="white"
                      inactiveBackgroundColor="white"
                      tabBarPosition="bottom"
                      animationEnabled
                      hideNavBar
                      tabBarOnPress={this.onTabPress} // THIS
                    >
                      <Scene
                        key="feed"
                        component={() => ( // AND THIS
                          <Feed ref={component => {
                            this.feedRef = component && component.wrappedInstance;
                          }}
                          />)}
                        iconName="ios-home"
                        icon={TabIcon}
                      />
...
```

**Comment by Mike96Angelo** [comment]
Is there any plan to support this?  It would extremely useful.  Was use this in v3 to refresh data for the view, but now with v4 its not working.

**Comment by aksonov** [comment]
backToInitial is supported now to reset stack for tab bar
