### ISSUE TITLE
Passing props to every scene

### ISSUE THREAD

**Issue by vhoen** [aksonov/react-native-router-flux#2345]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.47.0

I am trying to migrate to react-native-router-flux v4

We used to pass a few props to the "&lt;app /&gt;" component and theses props where passed to each Scene of our app : 

```
import scenes from '../scenes/scenes';

class App extends Component {
  render() {
    return (
      <Router
        {...this.props}
        scenes={scenes}
      />
    );
  }
}

function mapStateToProps(state, ownProps) {
  return {
    global: state.global,
    userData: state.userData,
    ...ownProps,
  };
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    ...globalActions,
    ...completeActions,
  }, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

Here is how the scenes are declared : 
```
const scenes = Actions.create(
  <Modal>
    <Scene
      key="pageSplash"
      component={SplashViewContainer}
      title="Loading"
      initial
      hideNavBar
    />
    <Scene
      key="pageAccount"
      component={AccountUserView}
      titleKey="account"
      type={ActionConst.RESET}
    />
  </Modal>
```

As far as I can see, props are correctly set in <App /> but never reach any Scene. It worked with react-native-router-flux v3, but not anymore.

Is there something I am missing ?

**Comment by RazerTang** [comment]
<Scene {...this.props} key="login" component={RNHighScores} title="Login" initial={true} />
I think  you should pass props to the scene.

**Comment by vhoen** [comment]
I didn't have to that in v3 and I was hoping wouldn't have to do this. My scenes are imported from several files and there are a bunch of scenes so it would be quite time consuming.

Thanks for your answer.

**Comment by aksonov** [comment]
You have to move scenes into Router for this, or pass params as second argument for `Actions.create`
