### ISSUE TITLE
Custom navBar component doesn't get custom title for a component

### ISSUE THREAD

**Issue by mzdunek93** [aksonov/react-native-router-flux#2348]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.21
- react-native v0.47.0

### Expected behaviour

When using a custom navBar component in a `Stack` navigator and setting a scene's title through component's `navigationOptions`, the title should be passed as a prop to the navBar, preferably as `props.title`. 

### Actual behaviour

The only title I get is the one set under the `title` key of the `Scene`. The weird thing is that when I'm using the `StackNavigator`'s default header, the title is passed correctly.

**Comment by as123456py** [comment]
I have the same promble.
At present,I can only use the title key of the Scene,and in custom navBar component ,I only render icon image.
I hope it works for you

**Comment by as123456py** [comment]
Hi,you can try `showLabel={false}`  ,like this:
`<Scene key='upPortal'  lazy={true} tabs={true}  showLabel={false}>
//other Scene
</Scene>
`
that will hide all the default `title` under the `Scene`

**Comment by aksonov** [comment]
Sorry, but you are using react-navigation feature (`static navigationOptions`) and want to make it work within RNRF advanced functionality (like dynamic prop.title)? Please read docs and follow docs how to define custom navBar for RNRF.
