### ISSUE TITLE
Major issues on Android - "There is no route defined for key key0."  

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2350]
### Version
- "react-native": "0.47.2",
- "react-navigation": "^1.0.0-beta.11",

On Andirod when I go from vertical to horizontal on the device I'm getting the following error "There is no route defined for key key0." and the app crashes I think this is related to the routing based on the error.

**Comment by aksonov** [comment]
Not enough data. Reproduce it on example project.

**Comment by gusti-andika** [comment]
I've also got this when doing 'toggle inspector' from dev menu

![screenshot from 2017-09-24 06-33-26](https://user-images.githubusercontent.com/1448515/30777667-5aa18390-a0f2-11e7-862b-7b8db5367ba4.png)

**Comment by rvasoya** [comment]
You likey forgot to add the key.
