### ISSUE TITLE
componentWillUnmount not firing 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2351]
### Version
"react-navigation": "^1.0.0-beta.11",
"react-native-router-flux": "^4.0.0-beta.21",
 "react-native": "0.47.2",

componentWillUnmount not firing, I need to be able to it fire. I have a login and logout view after a user log ins they are takend to a different view but the componentWillUnmount for the login never fires. 

Here is my code 
```
// Login
    _autoLogin() {
        const token = store.getState().oauth.tokens.access.value;
        if (typeof token  !== "undefined" && token) {    
            Actions.Photos({title:selectedTeam.name});

        }
    }

<ConnectedRouter navigationBarStyle={{backgroundColor:'#25abf9'}} titleStyle={{color:'white'}} headerTintColor="#FFF">
                        <Scene key="root" hideNavBar hideTabBar>
                            <Scene key="public">
                                <Scene key="login" component={Login} initial={true} title={'Login'} />
                                <Scene key="ResetPassword" component={ResetPassword} title={'Reset Password'} />
                            </Scene>
                            <Drawer contentComponent={CustomDrawer} drawerImage={require('./images/ic_menu_white_24dp_2x.png')}>
                                <Scene key='Photos' component={Photos} title={'Home'}  initial={false} renderLeftButton={()=>{}} backTitle='' backButtonTextStyle={{color:'white'}} />
                                <Scene key='SinglePhoto' component={SinglePhoto} title={'Photo'} renderLeftButton={()=>{}} back backTitle='' backButtonTextStyle={{color:'white'}} initial={false} />
                                <Scene key='PhotoDraw' component={PhotoDraw} title='Photo Edit' renderLeftButton={()=>{}} back backTitle='' backButtonTextStyle={{color:'white'}} initial={false} />
                                <Scene key='PhotoUpload' component={PhotoUpload} title='Upload Photo' renderLeftButton={()=>{}} back backTitle='' backButtonTextStyle={{color:'white'}} initial={false} />
                                <Scene key='Sync' component={Sync} title='Syncing Data' initial={false}  hideTabBar hideNavBar />
                            </Drawer>
                        </Scene>
                    </ConnectedRouter>
```

**Comment by mcabs3** [comment]
I think its because it isn't removing the `Scene` from the stack when you do `Actions.Photos`, it is pushing it onto the stack, and because of that, isn't calling `componentWillUnmount` because it technically isn't unmounting because it is still in the stack.

**Comment by aksonov** [comment]
@mcabs3 is right.

**Comment by AlmogRnD** [comment]
@mcabs3 yes that is correct but when I try the following `"popAndPush"` and `"popTo" ` they don't work, nothing happens. 

@aksonov  can you please reopen this, I think there needs to be a way to unmount and not just push the scene

**Comment by aksonov** [comment]
@AlmogRnD I don't see any issue here but app programming logic. Maybe you must add type='replace' to replace one route by another.

**Comment by AlmogRnD** [comment]
I don't understand the docs say 

popTo | Function | (sceneKey: String, props: Object)
-- | -- | --

**Comment by mcabs3** [comment]
@AlmogRnD just for clarification, `popTo` is used to pop back `x` number of times to a scene in the stack. `popAndPush` doesn't seem to be implemented in the v4. I will look to add this feature back.

In the meantime, what I would do is look at the `componentDidUpdate` lifecycle method that has a check to see if your user is logged in, and then carries out the action you desire like navigation. `componentWillUnmount` will fire when the `Scene` is popped from the stack.

In the meantime, please consider adding the function you desire to a PR. I try to stay on top of the issues and comments here.

**Comment by mackenziemance** [comment]
@mcabs3 Any updates on popAndPush implementation, thanks in advance.
