### ISSUE TITLE
Jump to specific scene and refresh it

### ISSUE THREAD

**Issue by sy-tian** [aksonov/react-native-router-flux#2352]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.40.1 (v3 is not supported)
- react-native v0.46.4

### Expected behaviour
When I press button, What I expected to go to the specific page and refresh it.
  
When I use Actions.home({ type: ActionConst.RESET}), it actually go to the home page, but doesn't refresh.

When I use Actions.home({ type:ActionConst.REPLACE}), it go to the home page and refresh it. But When I trigger some actions to refresh the home page again, I will send multiple requests to the backend. I found the issue, it's caused by 'REPLACE', which will keep the old home component in the stack. When I refresh it, it will make all home components refreshed.

Can you help me how to resolve it? I want to go the home page and refresh it and keep only one home component in the stack.

Thanks,

**Comment by sy-tian** [comment]
Can anyone help me?

**Comment by rexlow** [comment]
I am having the same problem as well.
This is my current setup. 
```
a -> b-> c -> d 
```
If I try to reset from `d` to `a`, it works but screen `a` would show a blank screen. Do note that this only happen to Android and this bug does not appear consistently.

**Comment by compojoom** [comment]
try 

> Actions.home(); 
> Actions.refresh({params})

**Comment by aksonov** [comment]
v3 is not supported anymore, sorry.
