### ISSUE TITLE
Change transition animation on v4

### ISSUE THREAD

**Issue by FacuAcosta** [aksonov/react-native-router-flux#2353]
### Version

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.1

The Animation props where really useful and straightforward on v3, but since this it's not supported and I have to use v4, I'd like to have the same behaviour for this version. Why did you remove it in the first place? I used react-navigation and swapped to here because It was giving me a lot of headaches and it will be a shame if RNRF becomes as buggy as react-navigation.

**Comment by aksonov** [comment]
Only react-navigation provides NATIVE 60fps animations from available JS solutions. You may check how to implement custom animations by looking Example project.
