### ISSUE TITLE
Can I create scenes/routes during runtime using RNRF?

### ISSUE THREAD

**Issue by pekka** [aksonov/react-native-router-flux#2354]
I am loading a tree of items from a JSON file. Each tree item should be a Screen in the app. 
The user should be able to navigate through this tree of screens like in the iOS settings dialog: 

![Image of iOS settings dialog](https://i.stack.imgur.com/GZkGL.png)

I was hoping to load the JSON when the app starts, and to dynamically generate screens and nested navigators based on the data.

This is not possible in React Native Navigation, though: screens need to be known statically.

Is there a way to do this in RNRF, or is it a React Native specific limitation?

I'm still new to RN, sorry if this is a dumb question.

**Comment by arribbar** [comment]
Well, RNRF is built on top of react-native-navigation. So it is the same, you cannot generate screens dynamically.

**Comment by mcabs3** [comment]
@pekka I would have all of the screens load, but some sort abstraction that will show what routes are available to use versus what aren't. If you are using a store like Redux or Mobx then that would be a good place to store that.

**Comment by aksonov** [comment]
It is not supported.
