### ISSUE TITLE
how to pass params while using actions.pop() in version RNRF-3.41.0??

### ISSUE THREAD

**Issue by senthilbalajiganesan** [aksonov/react-native-router-flux#2355]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.41.0 (v3 is not supported)
- react-native v0.47.2

### Expected behavior
I'm sorry to change this issue for v3, because I'm half way away from completion of my project turning back again is so hard. 
I'm trying to pass params while returning back from one scene to other, which cannot be done with 
Actions.pop(refresh:{params:"jb"})
and tried to log in componentWillReceiveProps and other places too

### Actual behavior
But I cannot receive any props anywhere in the component

Can someone help me fix this issue

**Comment by mcabs3** [comment]
did you just try passing them `Actions.pop({foo: 'bar'})`

**Comment by ynsgnr** [comment]
I tried but no luck on RN 0.48 and react-native-router-flux v4beta21 on Android 7.0.
It does run componentwillreciveprops function but it doesnt add that values to components maybe i should use something like super(props) in componentwillreciveprops ?

**Comment by aksonov** [comment]
Sorry, it is not related to RNRF. Check RN docs

**Comment by kosmicke** [comment]
You can send a function from the first scene to the second scene, so it can be executed before popping.

// First scene
Actions.push("secondScene", { 
    beforeBack: () => { this.loadData() } 
})

// Second scene
this.props.beforeBack ? this.props.beforeBack() : null;
Actions.pop()
