### ISSUE TITLE
Android hardware back button does not run onBack function

### ISSUE THREAD

**Issue by ynsgnr** [aksonov/react-native-router-flux#2359]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.beta21 (v3 is not supported)
- react-native v0.48

When Android hardware back button pressed onBack function is not called. I dont know if its intentinal or not and can be solved by adding an event on BackHandler and returning true in function but i think that this should be mentioned in docs.

Thank you for your efforts, if you want i can add this into docs

**Comment by aksonov** [comment]
You are right, BackHandler should be used, feel free to submit PR for docs.

**Comment by SurpassRabbit** [comment]
What is your solution? Can I provide the code?

**Comment by ynsgnr** [comment]
`componentDidMount(){   
  BackHandler.addEventListener('hardwareBackPress', this.handleAndroidBack)
  }

  componentWillUnmount(){
    BackHandler.removeEventListener('hardwareBackPress', this.handleAndroidBack)
  }

  handleAndroidBack = () =>{
    //Add desired function here (onBack in this case)
    Actions.pop();
    return true
  }`
