### ISSUE TITLE
Right Button call function from Component

### ISSUE THREAD

**Issue by marcelglaeser** [aksonov/react-native-router-flux#236]
Hello,
I need a route with a right button, but I don't understand how it works.
If I set a function for the right button, then the library search the function in the parent component, not in the route component.

I hope everyone can understand my English and my question.

Thanks for support,
Marcel

**Comment by marcelglaeser** [comment]
No one an idea or is my English to bad? I can try to explain it again ;-)
It's very very important for me!!

Thanks Marcel

**Comment by aksonov** [comment]
I don't understand, sorry.

**Comment by marcelglaeser** [comment]
No problem :) I try to explain it better!

I have two classes. In the first class I define the router and the route.

<Route name="cam" schema="modal">
<Router name="camRouter">
<Route name="camModal" component={Cammodal} wrapRouter={true} title="TITLE" type="modal" renderLeftButton={Icons.CloseIcon} leftButtonPress={()=>{Actions.pop();}} renderRightButton={Icons.TorchIcon} rightButtonPress={this._switchTorchMode} />
</Router>
</Route>

The function _switchTorchMode (rightButtonPress) is defined in the second class 'cammodal', not in the first class. But that's doesn't worked. How can I fix it?

**Comment by aksonov** [comment]
params starting from 'render' should be functions returned React component, not react component itself.
also the component doesn't have rightButtonPress param, check docs

**Comment by marcelglaeser** [comment]
Thanks for your answer. Are there examples?

**Comment by aksonov** [comment]
There is documentation. You may add example PR if you want.
