### ISSUE TITLE
Performance issue, taking 4-5 second to pop/push screen

### ISSUE THREAD

**Issue by rishabhbsdei** [aksonov/react-native-router-flux#2360]
### Version
"react-native-router-flux": "^3.41.0",

### Expected behaviour
It should not take much time to pop screen from toolbar back button, but taking 4-5 seconds to remove current screen on click of toolbar back button or Android hardware back button.

### Actual behaviour
Its taking 4-5 seconds to pop screen.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Crate screen as below
        <Router>
           <Scene key="root">
            <Scene key="main" tabs tabBarStyle={styles.tabBar} default="tab1" >
            <Scene  key="tab1"
              title="WELCOME"
              iconName="home"
              icon={TabIcon}
              hideNavBar={false}
              component={Home}
              navigationBarStyle={{ backgroundColor: '#ffffff' }}
              titleStyle={ {color: '#262626'}}
              renderRightButton={()=>this.button() }
              initial={true}
            />
            <Scene key="tab2"
              title="MAPS"
              iconName="map"
              icon={TabIcon}
              hideNavBar={false}
              renderRightButton={()=>this.button() }
              component={Maps}
              navigationBarStyle={{ backgroundColor: '#ffffff' }}
              titleStyle={ {color: '#262626'}}
            />
         </Scene>
<Scene key="purchaseTourDetail"
            clone
            title=""
            hideNavBar={false}
            component={PurchaseTourDetail}
            navigationBarStyle={{ backgroundColor: 'transparent', borderBottomColor:"transparent" }}
            leftButtonIconStyle={{ tintColor: '#fff' }}
            titleStyle={ {color: '#fff'}}
          />
  </Scene>
   </Router>

2 From Tab1 I am using Actions. purchaseTourDetail({ title: 'custom title'}) and its loading after few seconds

3.On click of back button on Toolbar or Android hardware its taking 4-5 seconds to remove detail page.

4.I deleted all logs too.

**Comment by aksonov** [comment]
v3 is not supported anymore

**Comment by ishaqashraf** [comment]
same situation with me with version 4 ,, please someone solve this issue
