### ISSUE TITLE
Disable back button from inside a scene.

### ISSUE THREAD

**Issue by princenaman** [aksonov/react-native-router-flux#2362]
### Version
- react-native-router-flux v4.0.0
- react-native v0.47.1

### Expected behavior
None

### Actual behavior
None

### Steps to reproduce
1. None

I am using react-native-popup-dialog for dialogs. [Issue](https://github.com/jacklam718/react-native-popup-dialog/issues/67#issuecomment-328317800)
Is there a way I can disable the back button while the dialog is shown?

Thanks!

**Comment by aksonov** [comment]
It is not RNRF issue. You may use `Modal` to disable background elements.
