### ISSUE TITLE
How to give new title image in parameter when navigating new scene

### ISSUE THREAD

**Issue by althurzard** [aksonov/react-native-router-flux#2363]
### Version

- react-native-router-flux v4.0.0 
- react-native v0.47.2

I tried to navigate to new scene with these parameters

let imageStyle = {resizeMode:'contain',width:30,height:30,backgroundColor:'red'}
let imageUri = {uri:this.props.userInfo.profileUrl}
Actions.chat({navigationBarTitleImage: imageUri, navigationBarTitleImageStyle: imageStyle)

But it didnt work.

**Comment by mcabs3** [comment]
@althurzard for your `navigationBarTitleImage` are you passing an object? or an `<Image />` component? `navigationBarTitleImage` requires you pass an `Image` RN component.

Let me know if that changes your outcome.

**Comment by althurzard** [comment]
I tried sir but it didnt work either! @mcabs3 

 onPress = (userInfo) => {
  var avatar = (
    <Image
      style = {{width:30,height:30,backgroundColor:'black'}}
      source = {{uri:userInfo.profileUrl}}
      resizeMode = 'contain'
    />
  )
   Actions.chat({userInfo:userInfo,localUser:this.props.localUser, navigationBarTitleImage: avatar})
 }

i took a look in navigationStore.js and saw that it only receive an object, doesnt it? 
if (navigationBarTitleImage) {
      res.headerTitle = <Image source={navigationBarTitleImage} style={navigationBarTitleImageStyle} />;
 }

**Comment by mcabs3** [comment]
@althurzard touche! I will take a look
