### ISSUE TITLE
Android tab bar at the bottom

### ISSUE THREAD

**Issue by piloulac** [aksonov/react-native-router-flux#2365]
### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.2

### Problem 
Hello! 

I wonder how we can put the tab navigation bar at the bottom on Android. By default it looks like the iOS one is at the bottom but it's not the same thing for Android (which is at the top). 
How can I have the same behaviour between the two platforms?

Is there a property which define it? If so, I searched it but not find.. :( 

Thank you in advance!

**Comment by mcabs3** [comment]
@piloulac please look at `tabBarPosition` in the [docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md). To keep native feel, android defaults to top and iOS defaults to bottom.

**Comment by piloulac** [comment]
Ok thank you!!
