### ISSUE TITLE
Always show backbutton, and exit app on back. 

### ISSUE THREAD

**Issue by sneerin** [aksonov/react-native-router-flux#2366]
Is it possible always show back button? For my case, I just need to exit react activity. But for other cases it could be a menu as well, wasn't able to find it in the documentation. please advise. 
Should it be state changes, totally custom navbar?

**Comment by mcabs3** [comment]
The back button will show only when you have a `Scene` to navigate back to. this is based on `react-navigation`. If you are looking to always have a back button to perform some sort of action, you can try the `onLeft` features of the `Scene` or indeed implement your own custom navBar.

**Comment by sneerin** [comment]
I was looking here: 
renderLeftButton 
not sure if it works for v4, but anyway thanks for suggestion

**Comment by mcabs3** [comment]
Sure, if you need further help, let me know.

**Comment by luisfuertes** [comment]
I have that router: 
``` 
			<Router sceneStyle={{backgroundColor:'white'}}>
				<Scene key='lightbox' lightbox>
					<Scene key='root'>
						<Scene key='Login' initial={true} component={Login} hideNavBar/>
						<Scene key='User' component={User} />
					</Scene>
				</Scene>
			</Router>
``` 

From `Login` scene i do `Actions.User()` and in `User` scene, `react-native-router-flux` show back button but when i press it, app crash with: `_this.props.navigation.goBack is not a function` instead do a simple `pop`

**Comment by luisfuertes** [comment]
If i add `onLeft={(e) => console.log("e: ", e)}` prop to scene, console.log isnt printed, but when i press back button do pop correctly...
