### ISSUE TITLE
v4, pop action doesn't close the app and existing view with onExitApp true

### ISSUE THREAD

**Issue by sneerin** [aksonov/react-native-router-flux#2367]
I have a view started from native view, I want to close it 

```
  return <Router onExitApp={true}>
    <Scene key="root" hideBackImage = {false}>
      {this.getScene(routes.REVIEWS, Reviews, "reviews")}
      </Scene>
    </Router>
```

after I do Actions.pop(), nothing happened, no matter I set onExitApp true or false. Please advice.

**Comment by vishnuc** [comment]
same problem

**Comment by tikkichan4** [comment]
same problem too. It seems removed in v4

**Comment by aksonov** [comment]
You should use BackHandler with v4.
