### ISSUE TITLE
Change tab programmatically

### ISSUE THREAD

**Issue by onrige** [aksonov/react-native-router-flux#2368]
In previous version it was able to change current tab programmatically by Actions.refresh({ key: 'tab_1' }), but now it doesn't work. According to the docs I guess it doesn't work because of refresh action now refreshing only current scene. So may be someone know the solution?

UPD: Fine, I found the solution and it's was easy. If someone will have the same problem - just use default syntax to navigate between scenes (`Actions.tab_1()` for example).

**Comment by onrige** [comment]
@fxhereng I don't understand how does tab switch via my solution can create a new scenes stack :) Could you show me your scenes?
In my case it was something like this:
```javascript
<Scene key="root">
    <Tabs key="tabs">
        <Scene key="tabs_tab1" />
        <Scene key="tabs_tab2" />
    </Tabs>
</Scene>
```
So if I will use `Actions.tabs_tab2()` somewhere - I will navigate to this tab.
Anyway if you have the problem with stacked navbar may be you will need to try `wrap` or `hideNavBar` property.

**Comment by fxhereng** [comment]
Thanks for answering!

When doing `Actions.tabs_tab2()` it creates a new tab scene and add it to the tab's navigation stack. So I have, after it, two scenes `tabs_tab2`, and I don't want that kind of behavior.

Finally the solution I found was to do an `Actions.replace('tabs_tab2')`, it goes to the tab2 and doesn't add up scene to the stack navigation. It refreshes the scene as well, in my case I didn't care but it can be useful too.

Cheers,

**Comment by onrige** [comment]
Interesting. In my case it works good. Could you give an example with such problem? It's probably a bug because I don't understand how scene change functionality can do something like this. o_O

**Comment by fxhereng** [comment]
Pretty similar with yours:

version: 4.0.0-beta21

```javascript
<Scene key="root">
    <Tabs key="tabs" showLabel={true} swipeEnabled={false} lazy={true} backBehavior={'initialRoute'}>
        <Scene key="tabs_tab1" />
        <Scene key="tabs_tab2" />
    </Tabs>
</Scene>
```

Doing `Actions.tabs_tab2()` or `Actions.jump('tabs_tab2')` adds scene to the navigation stack and duplicates scene.

`Actions.replace('tabs_tab2')`avoids duplicating the scenes
