### ISSUE TITLE
Tabs label / text colour change

### ISSUE THREAD

**Issue by tasharofi** [aksonov/react-native-router-flux#2369]
I have both icons and labels displayed for each tab on tabs element (showLabel set to true which is default anyway). 
I can change the icon colour by passing "focuses" props to the tabIcon component but haven't been able to set the focused tab text / label colour.
 
I know about the following which when its set in the tabs element 

labelStyle={{ color: '#....' }}

it changes all the text colour (focused and not focused) to what I set and it does not care whether its focused or not. 

Now how can I change the tab label colour depending on focused or not focused?

Thanks, 

### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.1

**Comment by onrige** [comment]
Hey. Just have a look at the API docs. 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs

You are probably looking for activeTintColor and inactiveTintColor properties.

**Comment by tasharofi** [comment]
Great thanks that was it. Closing the issue
