### ISSUE TITLE
Is there any way to define a Router in a sub-component?

### ISSUE THREAD

**Issue by alexmngn** [aksonov/react-native-router-flux#237]
Hi there,

I'm trying to have independent modules with their own router, but so far I can't make it work.

Basically, I have the following defined in `index.ios.js`

```
<Router hideNavBar={true}>
	<Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight} />
	<Route name="start" component={Start}></Route>
	<Route name="main" component={Main}></Route>
</Router>
```

And I have a router in my component `Start`

```
class Start extends Component {
	render() {
		return (
			<Router name="startRouter">
				<Route name="login" component={Login} initial={true} rightTitle="Register" onRight={() => {
					Actions.register();
				}} />
				<Route name="register" component={Register} title="Register" leftTitle="Login" />
			</Router>
		);
	}
};
```

The navigation bar is properly rendered, but when I click the Register button, I get an error:

<img width="487" alt="screen shot 2016-02-21 at 13 22 35" src="https://cloud.githubusercontent.com/assets/4203845/13204447/39e0dfc0-d89e-11e5-9a17-8fe1b8e7e1a0.png">

Do you have any idea how I can make this work?

Thanks.

**Comment by aksonov** [comment]
Just pass route attribute to children route, route={this.props.route} or just {...this.props} to child Router

**Comment by alexmngn** [comment]
I tried this but it still doesn't want to work, I get the same error:

```
<Route name="start" component={Start} {...this.props} />
```

**Comment by dan-lee** [comment]
You should pass the props to the router: `<Router name="startRouter" {...this.props}>`

**Comment by AndrewKovalenko** [comment]
I have similar problem. 
I'm trying to build "parent-child" view like on mockup below
[mockup](http://i.imgur.com/cG7vxa5.png)

to do this I defined top-level routing:
```
'use strict';

import React, { Navigator } from 'react-native';
import LandingScreen from './components/landing.js';
import ParentScreen from './components/parent.js';
import RNRF from 'react-native-router-flux';
let {Router, Route, Schema} = RNRF;

export default class Example extends React.Component {
  render(){
    return(
      <Router hideNavBar={true} name='root'>
        <Schema name='default' sceneConfig={ Navigator.SceneConfigs.FloatFromRight }/>

        <Route name='landing' component={ LandingScreen } title='Home' initial={true}/>
        <Route name='parent' component={ ParentScreen } title='Parent'/>
      </Router>
    );
  }
}
```
*parent* component:
```
'use strict';

import React, {View, Text} from 'react-native';
import Button from 'react-native-button';
import { Actions } from 'react-native-router-flux';
import {Router, Route} from 'react-native-router-flux';
import ChildScreen from './child.js';
import AnotherChildScreen from './another-child.js';

export default class ParentScreen extends React.Component {
  render(){
    return(
      <View>
        <Text>Parent screen</Text>
        <Text>Passed param: {this.props.data.nested.field}</Text>
        <Button onPress={ Actions.landing }>Back</Button>
        <Button onPress={ Actions.child }>Child</Button>
        <Button onPress={ Actions.anotherChild }>Another Child</Button>

        <View>
          <Router name='parentRouter' {...this.props}>
            <Route name='child' initial={true} component={ ChildScreen } />
            <Route name='anotherChild' component={ AnotherChildScreen } />
          </Router>
        </View>
      </View>
    );
  }
}
```

*parent* component get rendered with no problem, but it doesn't show any child content.
also when I click on *child* link - nothing happens.

[screenshot](http://i.imgur.com/HINvozj.png)

Could you pls help me to figure out, what do I do wrong?

**Comment by aksonov** [comment]
3.0 version just released, please check it. 2.x release will not be supported except very critical issues.

**Comment by alexmngn** [comment]
Okay so now that we are version 3, how can I nest my `Scene`?
It looks like Actions create everything, but in my case I don't want to create everything in one place :pensive:
