### ISSUE TITLE
Left Button Image not getting rendered

### ISSUE THREAD

**Issue by tusharv-bidchat** [aksonov/react-native-router-flux#2370]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.47.1

### Expected behaviour
Left Button Image should be shown

### Actual behaviour
No Left Button Image getting rendered

### Steps to reproduce
I am trying to render left button using leftButtonImage but nothing is displayed.
leftTitle gets displayed only when I provide onLeft={Actions.pop}, otherwise left title does not show up.
Please help as I want to render left button with image.

**Comment by pedrogyn** [comment]
Olá,

Eu tentei assim: `<Scene navBarButtonColor='white' left={<Image style={{width: 15, height: 15, marginLeft: 8}}source={require('./imgs/icons/close.png')}/>} key='cadastro_screen' component={CadastroScreen} title='Cadastro' hideNavBar={false} />`

O botão apareceu mas o click deixou de funcionar

**Comment by tusharv-bidchat** [comment]
Hi
I made it work as follows:
`
<Scene
                            initial
                            key='home'
                            navTransparent
                            component={Home}
                            tabBarLabel={I18n.t('title_tab_home')}
                            icon={TabIcon}
                            renderLeftButton={renderLeftButton}
                        />

const renderLeftButton = () => {
    return (
        <Image
            style={styles.navBarIconStyle}
            resizeMode={UIConst.RESIZE_MODE.COVER}
            source={chatIcon}
        />
    );
};
`

But I wanted to render the button from inside the scene component.
I tried using
`
Actions.refresh({
        renderLeftButton: () => <Image
            style={styles.navBarIconStyle}
            resizeMode={UIConst.RESIZE_MODE.COVER}
            source={chatIcon}
        />
});
`
but its not working.

**Comment by Seventhly** [comment]
Hi
If you use left={}，the refresh can working in the scene component.
like its
`    
Actions.refresh({
      left : ()=> {
        return (
          <TouchableOpacity onPress={()=>{
            alert('In the scene component.')
          }}>
            <Text style={{fontSize: 14,marginLeft: 10,}} >leftButton</Text>
          </TouchableOpacity>
        )
      } ,
    })
`

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
