### ISSUE TITLE
drawer open -> close app -> drawer not working

### ISSUE THREAD

**Issue by mtt87** [aksonov/react-native-router-flux#2372]
### Version
```js
"react-native-router-flux": "4.0.0-beta.21"
"react-native": "0.46.4"
```

### Expected behaviour
When you close the app with the drawer open, you won't be able to reopen it again when you reopen the app.

### Actual behaviour
When you reopen the app the drawer is closed and the 

### Steps to reproduce
1) Open the drawer
2) Close the app (background not forced)
3) Reopen the app
4) The drawer is closed and you are not able to open it again

### Workaround
I suspect the reason is that the state of the drawer is `open` when you close the app so calling again `Actions.drawerOpen()` won't have any effect because the router thinks the drawer is open, tough it's not visible.

I see `react-navigation` has the option to toggle the drawer rather than just open/close, I think that would be great to have here.

In the meantime this workaround in your app root can fix the issue
```js
  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
  }

  handleAppStateChange(nextAppState) {
    if (nextAppState === 'background') {
      Actions.drawerClose();
    }
}
```

**Comment by AlmogRnD** [comment]
+1

**Comment by aksonov** [comment]
I can't reproduce it with latest RNRF.
