### ISSUE TITLE
App crashing when opening app from background from Tabs screen

### ISSUE THREAD

**Issue by tusharv-bidchat** [aksonov/react-native-router-flux#2373]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.47.1

### Expected behaviour
Open app properly from background when on Tabs screen

### Actual behaviour
App crashes with following error message
There is no route defined for key key0. Must be one of: 'key1'

### Steps to reproduce
Here is my Router.js data
`
<Stack key="main">
                <Scene hideNavBar>
                    <Tabs
                        key='tabbar'
                        swipeEnabled
                        showLabel
                        showIcon
                        tabBarPosition='bottom'
                        tabBarStyle={styles.tabBarStyle}
                        activeTintColor={UIConst.router.tabActiveColor}
                        inactiveTintColor={UIConst.router.tabInActiveColor}
                        activeBackgroundColor={UIConst.router.tabActiveBackgroundColor}
                        inactiveBackgroundColor={UIConst.router.tabInActiveBackgroundColor}
                    >
                        <Scene
                            initial
                            key='home'
                            navTransparent
                            component={Home}
                            tabBarLabel={I18n.t('title_tab_home')}
                            icon={TabIcon}
                            iconSource={TAB_ICONS[0].imageSrc}
                            renderLeftButton={renderLeftButton}
                            renderRightButton={renderRightButton}
                            navigationBarStyle={styles.navigationBarStyle}
                        />
                    </Tabs>
                  </Scene>
</Scene>
`

When I am on Home Tab I press hardware back button and the app goes in background, Now if I try to open the app again it crashes. Please help.

**Comment by PaulCotterell** [comment]
I don't know if you have already solved this, as it has been a few months, but I found that I needed to add the key property to EVERY tag and I can see that you have a Scene tag without a key.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
