### ISSUE TITLE
One NavBar only for grouped Scenes

### ISSUE THREAD

**Issue by waubau** [aksonov/react-native-router-flux#2375]
Can someone tell me how to have one navBar **Only** if I want to group Scenes like below.  It is so basic requirements that I can't figure out.
Instead of one NavBar I see two . Version 4.0.0-beta.21",
```
<Router>
            <Scene>
                <Stack >
                    <Scene key="login" component={LoginForm} title="Please Login"/>
                </Stack>
                <Stack>
                    <Scene key="employeeCreate" component={EmployeeCreate} title="Create Employee"/>
                </Stack>
            </Scene>
       </Router>
```
`hideNavBar` prop hides all navBars but I need one

**Comment by joel611** [comment]
I have experience same problem on my project that the screen show 2 nav bars. I guess one of the nav bar is from parent scene.
1. Add hideNavBar to root Scene.
2. Add hideNavBar={false} to the scene require nav bar.

**Comment by joel611** [comment]
Check out where the api said.
Stack:
A component to group Scenes together for its own stack based navigation. Using this will create a separate havigator for this stack, so expect two navbars to appear unless you add hideNavBar.

**Comment by waubau** [comment]
@joel611 Thanks. That worked out.

**Comment by traf** [comment]
This doesn't seem to work for me. when I try adding hideNavBar to the root scene, and hideNavBar={false} to the scene requiring the nav bar, the navbar hides completely.
