### ISSUE TITLE
pop/popTo freezes

### ISSUE THREAD

**Issue by rhk10** [aksonov/react-native-router-flux#2376]
I'm using react-native-router-flux v4.0.0-beta.21 (on Android)
I have three scenes.
SceneA -> SceneB -> SceneC
```
<Scene key="root">
  <Scene key="SceneA" initial component={SceneA}  />
  <Scene key="SceneB" component={SceneB}  />
  <Scene key="SceneC" component={SceneC}  />
</Scene>
```
When at SceneC and push back button( or hardware back  ) several times quickly, it shows SceneA  but freezes and componentDidMount of SceneC is called infinitely.
I don't know if it is related, if disabled back button on SceneB and push back button at SceneC in the same way, SceneA is displayed although back button on SceneB is disabled.
Please help.

**Comment by mtt87** [comment]
I see `componentDidMount` called infinitely on my issue as well:
https://github.com/aksonov/react-native-router-flux/issues/2371

They might be related.

Seems like somehow the scene is being unmounted and mounted infinitely

**Comment by rhk10** [comment]
It seems to happen only when Actions.refresh({anything}) called on SceneC.
Perhaps back event is overwritten for some reason.

**Comment by aksonov** [comment]
Cannot reproduce it on Example project. If you still have this issue, fork and modify Example project to demonstrate.
