### ISSUE TITLE
Disable reset transition

### ISSUE THREAD

**Issue by celso-henrique** [aksonov/react-native-router-flux#2377]
When i call Actions.reset there is a transition between screens, how to disable it?

- react-native-router-flux v4.0.0-beta.21 
- react-native v0.47.1

**Comment by fmoessle** [comment]
+1

**Comment by kesha-antonov** [comment]
+1

**Comment by fmoessle** [comment]
does no one has this problem too?

Is it posible to disable the transition-animation via a transition-config?

**Comment by ValentinBlokhin** [comment]
I do not have transition on Action.reset.
How to enable it?

**Comment by gabrielbull** [comment]
@ValentinBlokhin that's the normal behavior, to get animations you should use push or pop. 

Reset has a bug where it has an animation when used in a stack where, for example, you push to the stack and then reset it will play the pop animation.

**Comment by wbattel4607** [comment]
This is still a problem in beta 28. The docs say there will be no transition but, like _gabrielbull_ said there is one in some cases.

**Comment by amansahil** [comment]
Is there any update on this issue ?

**Comment by maurobender** [comment]
I'm having the same problem. Was anyone able to find a solution or workaround for this?

**Comment by aksonov** [comment]
Looks like React Navigation issue (RNRF just sends actions to RN)
