### ISSUE TITLE
Unable to set selected default tab

### ISSUE THREAD

**Issue by ippy04** [aksonov/react-native-router-flux#238]
Hi - I'm trying to set the default tab to be the middle tab rather than the first tab on a 3 tab screen. My Route / Router:

```
<Route name="tabbar" hideNavBar={true}>
    <Router footer={TabBar} hideNavBar={true}>
        <Route name="foo" component={Foo1} title="Foo1" icon={FooIcon} schema="tab" />
        <Route name="foo2" component={Foo2} title="Foo2" icon={FooIcon2} schema="tab" />
        <Route name="foo3" component={Foo3} title="Foo3" icon={FooIcon3} schema="tab" />      
    </Router>
</Route>
```

Trying to set the selected prop on the react-native-tabs component copied from https://github.com/aksonov/react-native-router-flux/blob/master/TabBar.js

```
<Tabs selected="foo2" onSelect={this.onSelect.bind(this)} {...this.props}>
    {this.state.children}
</Tabs>
```

Results in a "cannot find router for route=foo2 current router=undefined" error

I'm assuming this is related to #164? Any ideas on how to set the default tab to not be the first defined route?

Thanks!

**Comment by uyson** [comment]
+1

**Comment by tugh** [comment]
+1

**Comment by aksonov** [comment]
Please check latest version, 2.3.0, setting initial for Route will set initial route.

**Comment by ippy04** [comment]
just upgraded and confirmed that setting initial={true} works. Thanks!

**Comment by tugh** [comment]
@aksonov 
It sure worked as initial route, but the tab we rendered in the footer doesn't highlight properly.

I've found that there is a "selected" property for the Router, and it throws an error when we use it with initial={true}.

Could you please look into that too.

Thanks.
