### ISSUE TITLE
Migrating RNRF v3 to RNRF v4

### ISSUE THREAD

**Issue by GeekRishabh** [aksonov/react-native-router-flux#2381]
I am using airbnb google-maps in my project & it act as a base component of my app in v3 of RNRF I have used nested Scene code below & it was working fine .While upgrading to V4 it is not working can anyone here help me out .how to do it ?
```
<Drawer
        ref={ref => {
          this._drawer = ref;
        }}
        type="overlay"
        content={<SideBar navigator={this._navigator} />}
      >
        <StatusBar backgroundColor={statusBarColor} />
        <RouterWithRedux>
          <Scene key="root" hideNavBar>

            <Scene
              key="StartupService"
              component={StartupService}
              hideNavBar
              initial={this.props.JwtAccessToken}
            />

            <Scene key="rootView" component={RootView}>
              <Scene key="home"  component={Home} />
              <Scene key="confirm" component={Confirm} />
              <Scene key="Booked" component={Booked} />
            </Scene>

            <Scene key="sideBar" component={SideBar} />
            <Scene key="history" component={History} />
          </Scene>
        </RouterWithRedux>
      </Drawer>
````
here the rootView contain the map & the other component are screen on top of rootView 
how to do that in V4

**Comment by aksonov** [comment]
Please check docs/examples, there are some breaking changes.

**Comment by GeekRishabh** [comment]
@aksonov  i am not able to figureOut any work around .
As the rootView contain react-native-maps that is common in the other screen (home, confirm & booked) . any lead will be appreciated
v3.38 is laggy with RN V48.x thats why i need to upgrade the RNRF version .
