### ISSUE TITLE
How to quit Android App？I used BackHandler

### ISSUE THREAD

**Issue by SurpassRabbit** [aksonov/react-native-router-flux#2383]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.21 (v3 is not supported)
- react-native v0.48.0

### Expected behaviour
Exit App

### Actual behaviour
Use BackHandler after crashing

### Steps to reproduce
1.

```
const reducerCreate = params => {
    const defaultReducer = new Reducer(params);
    return (state, action) => {
        console.log('ACTION:',action)

        if(action.type === 'Navigation/BACK'){
            console.log('退出APP');
            BackHandler.exitApp();
        }
    return defaultReducer(state, action);
}
```

2.Error: `Cannot read property 'startsWith' of undefined`

```
handleException @ index.android.bundle:11796
handleError @ index.android.bundle:12611
reportFatalError @ index.android.bundle:685
__guard @ index.android.bundle:2064
callFunctionReturnFlushedQueue @ index.android.bundle:1947
(anonymous) @ debuggerWorker.js:71
```

3.
![default](https://user-images.githubusercontent.com/10183022/30365932-f78b7e72-989b-11e7-97fc-3efe7e302a23.png)

**Comment by vhoen** [comment]
You seem to call startsWith method on something that is undefined. I don't think backHandler is responsible for this error. Could you check if error is not occuring elsewhere ?

**Comment by ynsgnr** [comment]
You  can try to override BackHandler from react native in root component

**Comment by SurpassRabbit** [comment]
I'm adding the code in the Example @vhoen

**Comment by SurpassRabbit** [comment]
I was in the Example `Launch`  to add your code, click the Android return button can not be used

**Comment by aliszafar1** [comment]
this library has solved my issue
https://github.com/wumke/react-native-exit-app
