### ISSUE TITLE
Support for custom backButton

### ISSUE THREAD

**Issue by thebergamo** [aksonov/react-native-router-flux#2385]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)

### Expected behaviour
Using a custom component for the backButton in NavBar instead of just an image

### Actual behaviour
You can't register a custom component to backbutton just images

**Comment by hungdev** [comment]
this is props in <Scene. read more API docs.
back backButtonImage={Images.arrowLeft} leftButtonIconStyle={styles.backButtonStyle} navigationBarStyle={styles.navBarHideStyle}

**Comment by thebergamo** [comment]
@hungdev the issue is related to the NavBar (In this case, NavBar is a shortcut for some configurations in Scene).
We can set images and styles for the back button, but if I want to add more behaviors I can't just using a fully custom "backButton"

**Comment by hungdev** [comment]
but if i want to add more behaviors you can use custom navbar component.

**Comment by mcabs3** [comment]
try `renderLeftButton`

**Comment by thebergamo** [comment]
@mcabs3 you can close this issue at this moment. I back using the v3. The v4 demands a lot of refactoring that unfortunately we don't have time to do. :(

**Comment by mcabs3** [comment]
@thebergamo i'm sorry to hear that. if you have more questions i'll do my best to help.
