### ISSUE TITLE
Nested scene issue

### ISSUE THREAD

**Issue by quanpotato** [aksonov/react-native-router-flux#2386]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0 beta.21 (v3 is not supported)
- react-native v0.47.2

### Expected behaviour
When I put login and employeeList into two different nested Scene, after login, the employeeList appears without back button to itself.
`<Router sceneStyle={rootSceneStyle}>
            <Scene key="root" >
                <Scene key="auth">
                    <Scene key="login" component={LoginForm} title="Please Login" initial/>
                </Scene>
                <Scene key="main" >
                    <Scene key="employeeList" component={EmployeeList} title="Employees" />
                </Scene>
            </Scene>
        </Router>`

### Actual behaviour

The back button is still here. And when I press back button, I go to employeeList again.

![simulator screen shot sep 13 2017 9 50 32 pm](https://user-images.githubusercontent.com/8279850/30384713-43c939b8-98cf-11e7-892b-f17cbf360828.png)

**Comment by patrickdronk** [comment]
And you will get a double navbar
<img width="384" alt="screen shot 2017-09-15 at 16 19 21" src="https://user-images.githubusercontent.com/10230877/30486716-aaad2fc8-9a31-11e7-90a6-deaa0b3ba2d6.png">

**Comment by quanpotato** [comment]
Yes, if I using `<Scene key="root" hideNavBar>`, the top navBar disappear. However, the back button is still here

**Comment by mcabs3** [comment]
@quanpotato can you give more information on how you are navigation from `login` to `employeeList`?

**Comment by ArtemAstakhov** [comment]
same issue, I'm using Actions.employeeList() to navigate

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
