### ISSUE TITLE
Custom tabBarComponent does not receive all additional data (children props)

### ISSUE THREAD

**Issue by yuletodim** [aksonov/react-native-router-flux#2389]
- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

Hi, I would like to build my own custom tabBarComponent but when I open props inside render function of this custom TabBarComponent in _routes -> route.params_  is missing some of additional data I pass through props.  Here is my simplify code: 

**Routes:**
![routes](https://user-images.githubusercontent.com/7632065/30428920-1947ce72-995e-11e7-927b-54b174cb2945.PNG)

**Custom TabBarComponent:** 
![tabbar](https://user-images.githubusercontent.com/7632065/30428943-45951192-995e-11e7-92f9-767c56211b94.PNG)

I expect additional data that I pass through _props_ of the Tabs child Scene _imageActive, imageInactive_ to be in _params_ of _each route_ but they are not there: 
![paramspicture](https://user-images.githubusercontent.com/7632065/30427982-875a9e34-995a-11e7-9ab2-90b76960c37b.PNG)

When I use built in TabBar + custom icons for the tabs I receive this data in render function. What I am missing?
![iconprops](https://user-images.githubusercontent.com/7632065/30428350-e7d37c08-995b-11e7-8954-a4076100b008.PNG)

Desired effect - for each scene with tabs to have different Title and different image icons. I made it with custom NavBar and built in TabBar.
![navbar](https://user-images.githubusercontent.com/7632065/30428753-7446ed18-995d-11e7-8b30-ebb14fcaab02.PNG)

![navbar2](https://user-images.githubusercontent.com/7632065/30428812-ac481ac0-995d-11e7-9ce2-1397468933b8.PNG)

Because of other reason I need to hide NavBar. So I need custom TabBar. Any help?

**Comment by therealaldo** [comment]
I need help with implementing a custom tab bar as well

**Comment by aksonov** [comment]
Custom tabor should receive `navigation` prop with all needed data inside

**Comment by sarthak216-blr** [comment]
> Custom tabor should receive `navigation` prop with all needed data inside

Saved
