### ISSUE TITLE
Two navbars inside root tabs if using modal

### ISSUE THREAD

**Issue by onrige** [aksonov/react-native-router-flux#2392]
There is a problem with navbar wrapping in root tabs. For example:
```javascript
<Router>
  <Modal key="modal">
    <Tabs key="root">
      <Scene key="tab_1" icon={...}>
        <Scene key="tab_1_scene1" component={...} initial />
        <Scene key="tab_1_scene2" component={...} />
      </Scene>
      <Scene key="tab_2" icon={...}>
        <Scene key="tab_2_scene1" component={...} initial />
        <Scene key="tab_2_scene2" component={...} />
      </Scene>
    </Tabs>
    <Scene key="someModal" component={...} />
  </Modal>
</Router>
```
So in this case there are two navbars on each tab scene.

it seems like this problem appears because `Modal` parent have his own navbar, but `wrap={false}` for `Tabs` doesn't do the trick. There is only one way for now - use `hideNavBar` on `Modal` scene and `hideNavBar={false}` on each `Tabs` initial child. But in this case there is also will be a problem if you will use nested tabs with custom tab bar because `hideNavBar` won't work on these scenes.

I will try to find the reason and create pull request, but for now may be someone have any suggestions on this problem?

UPD: Lol, just a moment ago I updated the package to the master version, added `hideNavBar` property to the root `Tabs` and it's did the trick, there is only one navbar now. Magic. Any way I will try to reproduce the problem but for now I am closing this issue.

**Comment by pedrogyn** [comment]
Hello, 
I had the same problem. How did you solve it? 
When I request the modal page the navigation bar some :(

**Comment by onrige** [comment]
@pedrogyn Hey, could you give me a part of your code? Also you can look at my UPD section - there is a solution for my case (and may be for yours too)

**Comment by pedrogyn** [comment]
Hello, 
Can solve by doing the following:

```
<Router>
    <Modal>
        <Stack hideNavBar>
            <Scene>
            </Scene>
            <Scene>
            </Scene>
        </Stack>
        <Scene>
        </Scene>
    </Modal>
</Router>
```
