### ISSUE TITLE
Dynamically set status bar color depending on scene (Android)

### ISSUE THREAD

**Issue by NathHorrigan** [aksonov/react-native-router-flux#2393]
I can't seem to find out how to do this with the docs. (I am using a custom navbar if that changes anything).

**Comment by shukerullah** [comment]
[RNStatusBar](https://facebook.github.io/react-native/docs/statusbar.html#backgroundcolor)?

**Comment by StanislavSergeev** [comment]
How can I make dynamically set status bar color using Router-flux?

**Comment by aksonov** [comment]
It is not supported
