### ISSUE TITLE
blank map using router-flux

### ISSUE THREAD

**Issue by pedrogyn** [aksonov/react-native-router-flux#2395]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.48.2

hello,
I have the following issue
https://github.com/airbnb/react-native-maps/issues/1653

> When I use the Direct MapView component, the map is rendered. But when I use the component in conjunction with the router-flux library I have a blank map.
> Only one red line appears on the side of the screen

package.json

`"dependencies": { "react": "16.0.0-alpha.12", "react-native": "0.48.2", "react-native-keyboard-aware-scroll-view": "^0.3.0", "react-native-maps": "^0.16.3", "react-native-router-flux": "^4.0.0-beta.21" }`

git project
https://gitlab.com/projetosReactNative/enjoyBR

![screenshot_1505712370](https://user-images.githubusercontent.com/20590307/30530039-a4981168-9c19-11e7-81c4-1dc9999ee4b7.png)

**Comment by hungdev** [comment]
i dont think cause router flux. you should set height and width for style Mapview.

**Comment by pedrogyn** [comment]
Thanks for the answer @hungdev :D

I have made all the settings that the react-native-maps library shows in the documentation and even then the screen is still blank. I tested in a separate project just the map and it worked ok.

<img width="378" alt="captura de tela 2017-09-18 as 08 46 07" src="https://user-images.githubusercontent.com/20590307/30540515-e2c1d76a-9c4d-11e7-8145-347740009eb4.png">

**Comment by hungdev** [comment]
you are resolved. i think you should close the issue.

**Comment by pedrogyn** [comment]
@hungdev I was able to solve using the command react-native link react-native-maps. The problem was not connected to the RNRF library
