### ISSUE TITLE
expected to the previous scene,but it backs to  the Home scene?

### ISSUE THREAD

**Issue by wenwen1995** [aksonov/react-native-router-flux#2396]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.44.2

### Expected behaviour and Actual behaviour
For example, there are 3 pages,Home Page,A Page and B Page, just like this:

`<Scene key="Home" duration={0} component={Home} type={ActionConst.REPLACE} title="Home" />`
`<Scene key="A" duration={0} component={A} type={ActionConst.PUSH} title="A" />`
`<Scene key="B" duration={0} component={B} type={ActionConst.PUSH} title="B" />`

when I login the app,It goes to the Home page.I press one button in Home page,and it will goes into A Page. In A page, there is another button, and I press it into B Page,but when I want to exit B Page and back to A Page,refresh something in A Page,it will back to Home Page...not back to the A Page?

However,in my opinion, the stack will be like this:

![stack](https://user-images.githubusercontent.com/12100065/30574355-f7923228-9d2b-11e7-9a8a-aca9d52b7f08.png)

so, in order to back to A Page,I use  this code in B Page:

`Actions.A({ type: ActionConst.REPLACE })` 

and it is okay....But I want to know the reason...Why....

**Comment by aksonov** [comment]
Could you fork and modify Example project to reproduce this issue?
