### ISSUE TITLE
I cont Exit App on Android

### ISSUE THREAD

**Issue by itwangyu** [aksonov/react-native-router-flux#2399]
the Example neither cont exit on Android

what should i do?

**Comment by mcabs3** [comment]
I would look at maybe implementing a handler to accomplish this for you in your top level component.

https://facebook.github.io/react-native/docs/backhandler.html

**Comment by wsxyeah** [comment]
I get a workaround here.

add following code to your reducer
```
if (action.type.includes('/BACK') && state === newState) {
  BackHandler.exitApp()
}
```

**Comment by itwangyu** [comment]
@wsxyeah  newState我不知道是从哪来的 ,不过我通过判断routes里面的routeName来返回了

**Comment by itwangyu** [comment]
I have sovled the problem by the following code:

     if (action.type === 'Navigation/BACK' && state.routes[state.routes.length - 1].routeName === "MainPage") {
            if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
                //最近2秒内按过back键，可以退出应用。
                NativeModules.MyNativeMoudle.exitApp();
            }
            this.lastBackPressed = Date.now();
            ToastAndroid.show('再按一次退出应用', ToastAndroid.SHORT);
        }
