### ISSUE TITLE
Getting state from Route at NavBar

### ISSUE THREAD

**Issue by JoaoCnh** [aksonov/react-native-router-flux#24]
I followed the example and I have a NavBar and a Route that uses that NavBar.

Is there any way I can access state from that Route at the NavBar level?

**Comment by FaridSafi** [comment]
Hello, I was in a similar situation. The best way is to use a Store.
Example: https://github.com/mrblueblue/react-native-alt-demo

So you can set the state in the Store, then access it from anywhere you want

**Comment by JoaoCnh** [comment]
@FaridSafi I've succesfully setup flux in my project. I got what I want working. But how can I access the state stored in my navbar?

I'm trying to find it online but not being lucky

**Comment by FaridSafi** [comment]
You should be able to access it using YourStore.getState()

**Comment by JoaoCnh** [comment]
:facepalm: I was being an idiot.

@FaridSafi Thanks for helping out. It solved my problem

**Comment by FaridSafi** [comment]
You are welcome
