### ISSUE TITLE
how to make my custom navBar change backgroundColor dynamically

### ISSUE THREAD

**Issue by beilunyang** [aksonov/react-native-router-flux#2400]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.41.0
- react-native v0.47.1

### Expected behaviour
i customized navBar by override static method 'renderNavigationBar'. 
```
static renderNavigationBar({ title, whiteBgColor }) {
  return (
    <View style={[styles.navBar, WhiteBgColor ? styles.whiteBg : null]}>
      <Text>{title}</Text>
    </View>
  );
}
```
the static method accept a param "whiteBgColor" and the whiteBgColor will change true from false.
i think the renderNavigationBar will re-execute and the navBar backgroundColor will change white from transparent.

### Actual behaviour
renderNavigationBar don't re-execute. 
the navBar backgroundColor always transparent, don't change to white.

how to make my custom navBar change backgroundColor dynamically?

**Comment by mcatmos** [comment]
I need the same but for tabBar. Running the same issue.

**Comment by aksonov** [comment]
Please check Example project for custom nav bar
