### ISSUE TITLE
CardStackStyleInterpolator module not found

### ISSUE THREAD

**Issue by rborn** [aksonov/react-native-router-flux#2402]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.21
- react-native 0.44.0
- (just ran the example in the repo)

### Expected behaviour

The example app in the repo should run.

### Actual behaviour

I dies on run with `error: bundling: UnableToResolveError: Unable to resolve module react-navigation/src/views/CardStackStyleInterpolator from /Work/mine/reacttest/react-native-router-flux/Example/Example.js`

Very simple fix, it seems that react-navigation changed the location of the file.

So in Example.js
```diff
-import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';
+import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';
```

I can make a PR if you want. Thank you 🤗

**Comment by mcabs3** [comment]
PR is always welcome, just make sure the Example application will run in your PR. Thanks

**Comment by mcabs3** [comment]
This has been fixed with Pull Request [2405](https://github.com/aksonov/react-native-router-flux/pull/2405)
