### ISSUE TITLE
Unable to disable dynamic text in header

### ISSUE THREAD

**Issue by dcgray85** [aksonov/react-native-router-flux#2409]
### Version

- react-native-router-flux v4.0.0-beta.19
- react-native v0.47.2

### Expected behavior

If the user on the iPhone enables larger text, I should be able to lock down the text so that it does not resize in the header.  I would expect allowFontScaling={false} to be able to be applied to the header text.

### Actual behavior
When the user allows dynamic text,  I can't disable the text resizing in the header.

**Comment by niktonic21** [comment]
Also I would expect allowFontScaling on tabbar Label.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
