### ISSUE TITLE
Restore last scene from previous session

### ISSUE THREAD

**Issue by James2516** [aksonov/react-native-router-flux#2410]
Is there any way to restore the last scene from previous session based on cached path in local storage (eg. redux-persist)?

Currently it has to be done in `ComponentWillUpdate` of the initial scene, which will cause the initial scene to be displayed before it gets transited to the last accessed scene. 

It cannot be done in `ComponentWillMount` as the state from local storage only gets hydrated after `ComponentWillMount` has already been executed.

**Comment by mcabs3** [comment]
@James2516 making sure I understand you correctly. Are you asking how you could reload the previous routing "history" when the app initiates?

**Comment by James2516** [comment]
Yes. Alternatively, being able to restore just the last scene might suffice.
Eg. the app has initial scene at Scene 1, which goes to Scene 2 with a button press, If the user goes to Scene 2 then quit the app, the app should display Scene 2 directly (skipping Scene 1) when the user opens the app again.

**Comment by asciifaceman** [comment]
I wonder if this might be possible using deep links combined with an AsyncStorage call to change your location on reload. It's not as good as the native approach, but it miiiight work?

**Comment by techyrajeev** [comment]
is it even possible?

**Comment by aksonov** [comment]
Not supported

**Comment by asciifaceman** [comment]
@James2516 imho it's not an entirely bad look to load the first view and then push the next one. You can make it look more official with an overlay. Just my 2 cents that it won't detract the user experience.
