### ISSUE TITLE
drawerIcon not working

### ISSUE THREAD

**Issue by ShMcK** [aksonov/react-native-router-flux#2412]
### Version
Tell us which versions you are using: 

- react-native-router-flux: 4.0.0-beta.21
- react-native: 0.47.1 (within CRNA)

### Expected behaviour

Should have a drawer icon.

### Actual behaviour

No drawer icon.

### Steps to reproduce

Add a drawerIcon of any Component. Open the app and find nothing there.

```js
<Drawer
    key='drawer'
    contentComponent={DrawerContent}
    drawerIcon={() => <Text>Here</Text>}
    >
     <Stack key='app' hideNavBar default='first'>
        <Scene key='first' title='I have no drawer icon' component={SomeComponent}>
    </Stack>
</Drawer>
```

**Comment by tasharofi** [comment]
I am having a same problem. Any updates?

**Comment by ASheikhi82** [comment]
Same issue here.

**Comment by ShMcK** [comment]
I believe I may have a hint to the cause of this. "React-native-router-flux" is now tied to the frequently changing beta APIs of "react-navigation".

Within "react-navigation", `drawerIcon` does not actually refer to the menu icon controlling the drawer. "React-navigation" uses the API to autogenerate menu items in a drawer, with optional (drawer) icons. This is not clear from the current docs.

See the [react-navigation drawer example](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/Drawer.js).

**Comment by kholiavko-roman** [comment]
@ShMcK, and how to set up drawerIcon now ?
I tried to do as in example that you show, using `navigationOptions`, on page, but it does not work too.

**Comment by ShMcK** [comment]
I'm not sure how to get this to work with "react-native-router-flux". In my own project, I've switched to "react-navigation" instead.

**Comment by shukerullah** [comment]
is this issue fixed?

**Comment by gabrielbuzziv** [comment]
This is not working for me aswell, someone have a light?
