### ISSUE TITLE
BackHandler not working in initial Scene

### ISSUE THREAD

**Issue by astonmd** [aksonov/react-native-router-flux#2413]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.48.3

### Expected behaviour

exit app

### Actual behaviour

not working

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. BackHandler.addEventListener('hardwareBackPress', this.onBackAndroid);
2. BackHandler not working in initial Scene
3. working in other Scene

**Comment by RobTS** [comment]
Same for me...

**Comment by mikesol** [comment]
Same here...

**Comment by jash90** [comment]
`  <Router
                backAndroidHandler={() => {
                if (Actions.currentScene == "name your Scene") {
                    if (backLoginScene == false) {
                        ToastAndroid.show("Click back again to exit.", ToastAndroid.SHORT);
                        backLoginScene = !backLoginScene;
                        return true;
                    } else {
                        backLoginScene = false;
                        BackHandler.exitApp();
                    }
                    return false;
                }}}>`

**Comment by jash90** [comment]
You must add backAndroidHandler in Router

**Comment by Maxitk** [comment]
my version is 4.0.0-beta.23
i have add Router,but it doesn't run backAndroidHandler when i press back

**Comment by aksonov** [comment]
@Maxitk Please check latest master now.

**Comment by Maxitk** [comment]
@aksonov ok，i will try it tomorrow,thamks...

**Comment by Maxitk** [comment]
@aksonov i have tried it a moment ago,but the same as before
I have deleted other 'backHandler' in my code and I try to do two things :
1、I add <Router backAndroidHandler> 
2、I add backHandler.addEventListener in initial page
both of them didn't work

**Comment by liukaixin01** [comment]
please try it.<Router backAndroidHandler={() => {}}></Router>

**Comment by vikrantnegi** [comment]
I'm having the same problem. 
Here is the StackOverflow question. 
https://stackoverflow.com/questions/47898965/exist-app-when-clicked-back-on-home-screen

**Comment by aksonov** [comment]
Latest Example works fine with hardware back button

**Comment by Assem-Hafez** [comment]
I think the problem is with react-native BackHandler itself i tried adding this line and no toast appears
` BackHandler.addEventListener('hardwareBackPress', () => { ToastAndroid.show("Cannot pop. Exiting the app...", ToastAndroid.SHORT); return true })`
