### ISSUE TITLE
Issue passing object to Scene

### ISSUE THREAD

**Issue by Enricopv** [aksonov/react-native-router-flux#2416]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

### Expected behaviour
Expect component to receive object in props using Actions.

### Actual behavior
Component returns undefined.

### Steps to reproduce
The below works, but I don't want to hard code the key:
`Actions.key({data: 'hello})`

Instead I want to use:
`Actions.push('key', {data: 'hello'})`

While the app does load the component associated to 'key', this.props.data is undefined. Is there another way to pass an object to a scene using Actions?

**Comment by mcabs3** [comment]
try `Actions['key'].call({data: 'hello')`

**Comment by andreaskarantzas** [comment]
Where exactly do you use the data? If it is outside the render can you try if props.data works?

**Comment by aksonov** [comment]
Closed due inactivity

**Comment by Dhrupal** [comment]
Using Actions['key'].call({data: 'hello'}), not able to get in props in next screen

**Comment by xeastcrast** [comment]
> Using Actions['key'].call({data: 'hello'}), not able to get in props in next screen

Me too
