### ISSUE TITLE
Question - How can I call a function from a custom navbar back into my main component 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2417]
I'm not sure how to do this within react navigation flux as my component is under a scene and not a basic child compoent. 

I have my scene 
`<Scene key='photoUpload' component={PhotoUpload} title='Upload Photo' photoDate={null} save={this._savePhotoUpload} initial={false} navBar={CustomNavBarUpload} />`

Which has a custom component for the navbar I have a save button and when that is pressed I would like it to run a function inside my PhotoUpload component  

I have the following which pass down to my index but now how do I trigger the function inside my PhotoComponet 

```
 // Save call
    _savePress(){
        this.props.save();
    }
```

**Comment by mcabs3** [comment]
Your easiest solution would be to use redux or mobx and have the function there, and then render a button that connects to the method and then can fire in the `onPress` of the save button.

**Comment by mcabs3** [comment]
Otherwise just spitballing, you could create a PR that encapsulates the button's `onPress` and try and pass it down to a scene.

**Comment by AlmogRnD** [comment]
@mcabs3 thanks want to help out but don't have time for a pr right now we need to launch our app, redux is might be an option don't like it but I guess that is the only option.

**Comment by mcabs3** [comment]
Yeah, unfortunately since React components only get their props from their parent or from redux, currently the router (which would be a scenes parent) doesn't pass anything down to the scene that would support what you are asking. So I agree currently the minimal effort would be using a state store like redux.
