### ISSUE TITLE
How do you get current route or scene? 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2418]
How do you get the current route or scene? And how come this is not anywhere in the docs I feel this is basic and needed?

**Comment by kholiavko-roman** [comment]
`Actions.currentScene`

**Comment by mcabs3** [comment]
I have added `currentScene` to the docs.

**Comment by AlmogRnD** [comment]
Thanks

**Comment by ssomnoremac** [comment]
@mcabs3, isn't `currentScene` a property not a function

**Comment by mcabs3** [comment]
Good call, I will update the docs.

**Comment by mmorcc** [comment]
@mcabs3  Good call, I will update the docs.
are you added it?
