### ISSUE TITLE
how to combine with react-native-tabs?I need to display four custo

### ISSUE THREAD

**Issue by jeffzing** [aksonov/react-native-router-flux#2419]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.19"
- react-native "0.47.1",

### Expected behaviour
I need to display four customer tabbar at the bottom of the view container

### Actual behaviour
tabbar are on the top and I don't know how to customization tab icon

**Comment by jeffzing** [comment]
sent someone to save me.

**Comment by shukerullah** [comment]
Is this (following code snippet) you want?

```
<Scene
  tabs
  lazy
  showIcon
  key="tabs"
  showLabel={false}
  tabBarPosition="bottom"
  iconStyle={styles.iconStyle}
  tabBarStyle={styles.tabBarStyle}
  indicatorStyle={styles.indicatorStyle}
>
  <Scene initial key="home" title="Home" icon={HomeIcon} component={Home}>
  <Scene initial key="settings" title="Settings" icon={SettingsIcon} component={Settings}>
</Scene>
```

**Comment by jeffzing** [comment]
man,your code works for me,You did help me out
