### ISSUE TITLE
Style the left button Icon on a scene, works on android but not on ios, please help :) 

### ISSUE THREAD

**Issue by HunterMarrow** [aksonov/react-native-router-flux#2421]
### Version
Tell us which versions you are using: 

- react-native-router-flux: im using version "react-native-router-flux": "^4.0.0-beta.21",
- react-native: im using "react-native": "^0.47.0",

### Expected behaviour
Im trying to style the leftButtonIcon, im using the leftButtonIconStye attribute with the tintColor property, which is working perfectly on android, but it does nothing on IOS. Could you please lead me in the right direction. What should i use to set the color of the left button icon on a scene. Please help :)

**Comment by mcabs3** [comment]
Can you provide a code snippet of what you are doing? that will help us understand what you are doing.

**Comment by aksonov** [comment]
Closed due inactivity
