### ISSUE TITLE
The back button event not working

### ISSUE THREAD

**Issue by vvmgev** [aksonov/react-native-router-flux#2425]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.2

I want get "BACK" event
i use onLeft function but
this code doesn't work for me
help me please

`const LeftBtn = () => {`
  `console.log('Left Button');`
`}`

`const my = () => (`
  `<Provider store={store}>`
   ` <RouterWithRedux  >`
     `         <Router hideNavBar>`
         ` <Stack key="root" >`
            `<Lightbox key="Lightbox">`
             ` <Scene key="MainPage" component={MainPage} hideNavBar initial/>`
             ` <Scene key="Popup" component={Popup} hideNavBar schema="popup"/>`
            `</Lightbox>`
            `<Scene key="ImagesModal" onLeft={LeftBtn} title={'Photo'} component={ImagesModal} navigationBarStyle={{backgroundColor: '#008ed6'}}  hideNavBar={false} headerTintColor={'white'} titleStyle={{color:'white'}}/>`
            `<Scene key="OpenImage"   component={OpenImage} navigationBarStyle={{backgroundColor: '#008ed6'}} hideNavBar={false} headerTintColor={'white'} titleStyle={{color:'white'}} />`
          `</Stack>`
       ` </Router>`
      `</RouterWithRedux>`
   ` </Provider>`
`)`
`

**Comment by mcabs3** [comment]
the `onLeft` is a function for then the `renderLeftButton ` is pressed. You need to provide a `renderLeftButton ` component.
