### ISSUE TITLE
There is no route defined for key "xxx" when registering more than one react native app

### ISSUE THREAD

**Issue by celbyo** [aksonov/react-native-router-flux#2429]
### Version

- react-native-router-flux ^4.0.0-beta.21
- react-native v0.46.4

### Expected behaviour
open the app with initial Scene correctly in both A and B.

### Actual behaviour
open A correctly,when open B with error "There is no route defined for key AA. Must be one of: 'BA','BB'"

### Steps to reproduce

index.ios.js:
```
AppRegistry.registerComponent('A', () => A);
AppRegistry.registerComponent('B', () => B);
```
A/index.js
```
<Router>
    <Stack
        key="root1"
    >
        <Scene key="AA" component={AA} initial/>
        <Scene key="AB" component={AB}/>
    <Stack>
</Router>   
```
B/index.js
```
<Router>
    <Stack
        key="root2"
    >
        <Scene key="BA" component={BA} initial/>
        <Scene key="BB" component={BB}/>
    <Stack>
</Router>
```
1. there are two entries in Native page
2. enter A with initial Scene AA, then exit A
3. enter B, error occured with message, "There is no route defined for key AA. Must be one of: 'BA','BB'"
4. actually, the above code is running correctly in rnrf v2

**Comment by aksonov** [comment]
RNRF doesn't support it
