### ISSUE TITLE
Ability to set background color

### ISSUE THREAD

**Issue by cdimascio** [aksonov/react-native-router-flux#243]
I would like to set the background color on the Router.
Currently, this is not possible and background is assumed to be transparent (app defaults to white) which makes for some unappealing looking transitions in darkly styled apps

Perhaps, it would be useful to enable the user to apply a custom style to the ActionSheet's child view. This could be done on line `300` in `ExRouter.js`. Something like `<View style={[styles.transparent, this.props.customStyle]}>`

This would be useful for Redux apps where the typical app entry point looks something like:
    
  ```
render() {
    return (
      <Provider store={store}>
        {() => <Router />}
      </Provider>
    );
  }
```

**Comment by aksonov** [comment]
Feel free to submit PR, name style as routerStyle or something like that

**Comment by dan-lee** [comment]
:+1:  I'm also in need of this, so I proposed a PR.

**Comment by zelphir** [comment]
@aksonov How to set custom background in the new version?

**Comment by aksonov** [comment]
Duplicate of #340
