### ISSUE TITLE
Stack produces console warnings `React.createElement: type is invalid`

### ISSUE THREAD

**Issue by enguerranws** [aksonov/react-native-router-flux#2430]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.17
- react-native v0.48.3

### Actual behaviour

Right now, I've set up my Scenes / Stack like the example:
```
<Stack key="auth" hideNavBar>
                        <Scene
                          onEnter={this.onEnterSceneHandler.bind(this)}
                          key="auth"
                          animation={'fade'}
                          panHandlers={null}
                          component={LoginScreen}
                          title="Login"  />
                      </Stack>
```

The issue is I get warning each time I reproduce this pattern, where the console warns:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

The stack trace is pointing the line where I'm opening the Stack components.

Should I ignore those warnings? What cause them?

**Comment by zyfccc** [comment]
Me too have this issue.

**Comment by g33ktony** [comment]
Same here but I'm using LightBox

**Comment by aksonov** [comment]
Looks like something was wrong with LoginScreen definition. Not RNRF related.

**Comment by Koshub** [comment]
Same issue using react-native-router-flux@4.0.0-beta.28
<img width="831" alt="screen shot 2018-01-26 at 1 01 23 pm" src="https://user-images.githubusercontent.com/7643346/35436960-2241ff26-0299-11e8-8876-b0d88d16de8b.png">
<img width="971" alt="screen shot 2018-01-26 at 1 01 02 pm" src="https://user-images.githubusercontent.com/7643346/35436962-22652d02-0299-11e8-9a85-a834065e3fa5.png">

**Comment by Koshub** [comment]
Same issue using:
- react-native-router-flux@4.0.0-beta.28
- react-native: 0.51.0

<img width="831" alt="screen shot 2018-01-26 at 1 01 23 pm" src="https://user-images.githubusercontent.com/7643346/35437237-359f1882-029a-11e8-8180-48e0304ed9c8.png">
<img width="971" alt="screen shot 2018-01-26 at 1 01 02 pm" src="https://user-images.githubusercontent.com/7643346/35437238-35bb11a4-029a-11e8-9a8f-5ae548a84cb4.png">

**Comment by Blapi** [comment]
You're importing `Sceene` with 2 'e' instead of `Scene` if 1 'e'....

**Comment by Koshub** [comment]
Haha, cool - it's working without warnings with correct name `Scene`.
Thank you.
