### ISSUE TITLE
multiple sub applications jump question

### ISSUE THREAD

**Issue by zetaoWu** [aksonov/react-native-router-flux#2431]
I'm so sorry, I have a old program by v3. 

### Version
 
- react-native-router-flux v^3.38.0 
- react-native v0.45.0

### Steps to reproduce
My application is divided in multiple sub applications that has its own route.
For example, A and B , start by startReactApplication of Native .

index.android.js:
```
AppRegistry.registerComponent('A', () => A);
AppRegistry.registerComponent('B', () => B);
```
 
A/index.js
```
<Router>
    <Stack>
        <Scene key="AA" component={AA} initial={true}/>
        <Scene key="AB" component={AB}/>
    <Stack>
</Router>   
```

B/index.js
```
  render(){
     return (
      <View></View>   
    )
 } 
```

1.  two entries  A and B;
2.  AA.js  have a button to startLaunch B , next  B exit;
3.  back  A ,I will start AB  by Actions.AB ,  error occured with message, "[react-native-router-flux] missed route data for key =AB"

**Comment by aksonov** [comment]
Sorry, RNRF doesn't support this use case
