### ISSUE TITLE
Header title rendered wrong

### ISSUE THREAD

**Issue by mysiar** [aksonov/react-native-router-flux#2433]
### Version
- react-native-router-flux 4.0.0-beta.21
- react-native v0.48.4

### Expected behaviour
Header title = Book List

### Actual behaviour
Header title = Books

### Steps to reproduce

```
<Router>
      <Scene key="root">
        <Scene key="books" headerMode="none" title="Books">
          <Scene key="BookList" component={BookList} title="Book List"  />
        </Scene>
        <Scene key="Home" component={Home} title="Home"/>
      </Scene>
</Router>
```

**Comment by mcabs3** [comment]
What are you navigating to? `BookList` or `books`?

**Comment by mysiar** [comment]
it is just the begining and all I have in the router is above app fires up and displays BookList component but with wrong header title

**Comment by mysiar** [comment]
I found soultion 
```
<Router>
      <Stack key="root" hideNavBar>
        <Stack key="books" >
           <Scene key="BookList" component={BookList} title="Book List"  />
        </Stack>
        <Scene key="Home" component={Home} title="Home"/>
      </Stack>
</Router>
```

I will see how it goes when I use more <Scene> & <Stack> components
