### ISSUE TITLE
Inactive tab will not update

### ISSUE THREAD

**Issue by wayne1203** [aksonov/react-native-router-flux#2434]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

### Expected behaviour

Tab will be show normally

### Actual behaviour

Tab got blank

### Steps to reproduce
Load data when tab inactive

I recorded an GIF to explain the issue
![video-to-gif](https://user-images.githubusercontent.com/8578341/30845009-0f0a4ef2-a2c4-11e7-8e19-fed64e94b00b.gif)

**Comment by windwang** [comment]
see #2225

**Comment by wayne1203** [comment]
Thanks for reply, I have tried "lazy" before.
I think it's not fully work.
In my situation, "Tab 1" is loading some data and in the same time I go to "Tab 3".  "Tab 3" show normally now. But I back to "Tab 1", will see blank page

**Comment by wayne1203** [comment]
I made a workaround for this issue, 
just scroll by program when tab force

```
const reducerCreate = params => {
  const defaultReducer = new Reducer(params);
  return (state, action) => {
    //console.log("ACTION:", action);

    // Special handle for iOS tab blank bug
    if (action.type == "REACT_NATIVE_ROUTER_FLUX_FOCUS" && Platform.OS === "ios") {
      if (action.routeName == "chat" || action.routeName == "mainPostList" ) {
        if (typeof Utils.a_listView[action.routeName] != "undefined") {

          const scrollPosition = Utils.a_listView[action.routeName].scrollProperties.offset;
          Utils.a_listView[action.routeName].scrollTo({y: scrollPosition+0.5});
          Utils.a_listView[action.routeName].scrollTo({y: scrollPosition-0.5});
        }
      }
    }
    return defaultReducer(state, action);
  };
}; 
```

**Comment by julien-innovantic** [comment]
Maybe the problem comes from listview, not from router : https://stackoverflow.com/questions/44022857/listview-not-displayed-unless-i-scroll-on-it

**Comment by onrige** [comment]
It's definetly the problem of ListView. At least it was so in my case. Try to add `removeClippedSubviews={false}`

**Comment by wayne1203** [comment]
I found this solution too and I trued before it will slow when too much items.
