### ISSUE TITLE
I do not want the user to return to the start page. Like on Android, intercept the push of the button "Back".

### ISSUE THREAD

**Issue by gtauniverse** [aksonov/react-native-router-flux#2435]
### Version 
- react-native-router-flux 4.0.0-beta.21
- react-native v0.46.4

### Expected behaviour
The user does not need to navigate 'custom TabBar', pressing the system button backward.
I do not want the user to return to the start page.

**Comment by yuletodim** [comment]
same problem

**Comment by vijaychouhan-rails** [comment]
same problem me too

**Comment by pgonzalez-santiago** [comment]
Same issue here. I need to set a custom action when the physical back button of the android device is pressed. Any ideas?

**Comment by gtauniverse** [comment]
I just deleted the code responsible for returning to the previous scene when I presses hardware back button. And wrote my code what to do when I click hardware back button.

**Comment by asciifaceman** [comment]
I run into the same problem currently swiping back at the first tab in a <Tabs>, it pops back to the initial scene before it ?

**Comment by aksonov** [comment]
Sorry, but it is not issue but the question for stackoverflow. You should disable back gesture and back button then OR use 'replace' action so tabbar will be first scene.
