### ISSUE TITLE
Dynamically Navigate to a Scene

### ISSUE THREAD

**Issue by mitajunior** [aksonov/react-native-router-flux#2436]
### Version
- react-native-router-flux v4.0.0-beta.17 
- react-native v0.47.1

### Expected behaviour

Is there a way I can dynamically navigate to a scene. Say i have
<Scene key="a" ..blah>
<Scene key="b" ..blah>
<Scene key="b" ..blah>
<Scene key="c" ..blah>

`js 
const links =  [
  { title: "Some Title", route: 'a'}
]
`
Then i render a list of links with onPress action mapping to the specific route 
`js Actions.{links.router} or something like that'

**Comment by mcabs3** [comment]
`Actions[links.route].call()` would be what you are looking for
