### ISSUE TITLE
hideNavBar is propagated to scenes outside of the Scene, Stack.

### ISSUE THREAD

**Issue by viktormmarkov** [aksonov/react-native-router-flux#2437]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4
- react-native v0.46.2

Sorry for the vague title, hope my example makes it more clear

### Steps to reproduce
1. I have moved the login2Modal scene to be on the same level as login scene.
```javascript 
<Scene
            key="loginModal2"
            component={Login2}
            title="Login2"
            duration={1}
          />
        <Stack key="login" titleStyle={{ alignSelf: 'center' }}>
          <Scene
            key="loginModal"
            component={Login}
            title="Login"
            hideNavBar
            onExit={() => console.log('onExit')}
            leftTitle="Cancel"
          />
       </Scene>
```
2. I have set `hideNavBar` on the loginModal scene.

### Expected behaviour
When navigating between scenes I expect the navBar to be hidden only on the loginModal scene

### Actual behaviour
The navBar is hidden in the login2Modal as well.

I was expecting the default NavBar to be present on the login2Modal. I'm relatively new to react and RNRF and I'm not sure whether I am expecting is correct or not.

**Comment by onrige** [comment]
Please have a look at API docs. You're trying to create modals in a wrong way.
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#modals-modal-or-scene-modal

**Comment by viktormmarkov** [comment]
Hey,
Thanks for taking time to respond. I don't think the issue is connected to Modals. If I were to remove the Modal from the architecture of the app, I would get a similar result.  

More concrete example:
```javascript
<Scene
            key="loginModal"
            component={Login}
            title="Login"
            hideNavBar
            default
            onExit={() => console.log('onExit')}
            leftTitle="Cancel"
          />
```

I would expect the login2 screen to have a navBar

**Comment by niktonic21** [comment]
I have same issue and its between the scenes.

**Comment by viktormmarkov** [comment]
I 'hacked' it by adding type="replace" in the scene that the navigation wasn't present. Hope it helps you. It partially works for me. I'm still trying to configure it properly :)

**Comment by aksonov** [comment]
'hideNavBar' is applied to stack container, not child screen (for v4)
