### ISSUE TITLE
Cannot pop to a scene from a scene pushed over itself

### ISSUE THREAD

**Issue by foyarash** [aksonov/react-native-router-flux#2438]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.48

### Expected behaviour

With the following code:

```
<Scene
          key="authentication"
          initial
          hideNavBar>
          <Scene
            onEnter={() => StatusBar.setBarStyle('light-content')} // Set the status status bar with light content for first view
            key="signin"
            initial
            component={SigninContainer}/>
          <Scene
            hideNavBar
            key="signup"
            clone
            component={SignupContainer}
            stepIndex={0} />
        </Scene>
```

I have the first screen of the app which is a login page. There is a button redirecting to a signup form, which has multiple steps. It uses the same scene, just one prop is changing. The component of those steps has a button to go back from the signup form to the login scene. Clicking on it should redirect from the signup scene to the signin scene

### Actual behaviour

When clicking this button when we are in the first step, we are correctly redirected. When we get to the following steps, nothing happens.

To update my scene, I use `Actions.signup({ stepIndex: stepIndex + 1 });`
To pop to my signin scene, I use `Actions.popTo('signin');`

Thank you!

**Comment by mcabs3** [comment]
The simplest solution would be to create separate `Scenes` for your `signup` route. I do not believe popTo supports the behavior you are suggesting currently. A PR is always welcome!
