### ISSUE TITLE
There is no route defined for key key0. Must be one of: 'key3','< clone view key >' (nested scenes)

### ISSUE THREAD

**Issue by brandonjyuhas** [aksonov/react-native-router-flux#2439]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.18 (v3 is not supported)
- react-native v0.47.1

### Expected behaviour

I have my router set up like this:

```
<Router>
  <Scene key='root' hideNavBar>
    <Scene key='onboarding'>
      <Scene key='welcome' component={Welcome} title='Welcome' />
      <Scene key='selectItems' component={SelectItems} title='Select Items' />
    </Scene>
    <Scene
      key='main'
      showLabel={false}
      tabs={true}
      initial={this.props.user.onboarded}
      showIcon={true}
      iconStyle={{width: 100, height: 30}}
    >
      <Scene key='tab1' title='My Items' icon={TabIcon} iconName='glass'>
        <Scene component={MyItems} />
      </Scene>
      <Scene key='tab2' title='Items' icon={TabIcon} iconName='search' initial={true}>
        <Scene component={Feed} />
      </Scene>
      <Scene key='tab3' title='Saved' icon={TabIcon} iconName='heart'>
        <Scene component={SavedItems} />
      </Scene>
    </Scene>
    <Scene key='itemShow' back clone component={ItemShow} />
  </Scene>
</Router>
```

When the app loads initially (with no persisted data), the scene of key `"welcome"` is loaded. A button on that component calls `Actions.selectItems()`, and navigates to the scene of key `"selectItems"`.

The component in `SelectItems` has a button that calls `Actions.main()` (as well as firing an action which sets `user.onboarded` to true).

I'd expect that the scene of key `"main"` would load, which in turn would load it's initial scene, `"tab2"`.
 
### Actual behaviour

When `Actions.main()` is called from `SelectItems`, an error is thrown:

`There is no route defined for key key0. Must be one of: 'key3','itemShow'`.

However, if the app is reloaded (now that `this.props.user.onboarded` = `true`, the app successfully loads to the `Feed` component.

Note: the reason I have nested the scenes within their tab scenes is that otherwise, when navigating to a clone view, the tab for the scene which you navigated from is replaced with a tab for the clone view (which is reproducible in the Example app by navigating to tab3 and then the echo view. tab3 will disappear).

### Steps to reproduce
Please let me know if you need me to fork the example app.

Thanks!!

**Comment by joel611** [comment]
Every scene needs a key. Try add key to scene within tabs(myitem, feed, saveditem)

**Comment by brandonjyuhas** [comment]
@joel611 that worked! Thanks so much!

**Comment by greenzeal** [comment]
worked for me also! thanks!

**Comment by michaelstokes** [comment]
I just had to replace my `ActionConst.RESET` with `ActionConst.REPLACE`

**Comment by hossein-kheirabadi** [comment]
@joel611 that worked! Thanks so much!

**Comment by hugoh1995** [comment]
I already have a key for all my scenes but still getting that error.

**Comment by shamanking** [comment]
I have same issue, this is my code:

`<Router>
      <Scene key="root" hideNavBar >
        <Scene key="auth">
          <Scene key="login" component={LoginForm} title="Please Login" />
        </Scene>
        <Scene key="main">
          <Scene
            key="employeeList"
            rightTitle="Add"
            onRight={() => { Actions.employeeCreate(); }}
            component={EmployeeList}
            title="Employees"
          />
          <Scene key="employeeCreate" component={EmployeeCreate} title="Employee Create" />
        </Scene>
      </Scene>
    </Router>`

When I try: Actions.employeeList({ type: 'reset' });
It has error: there is no route define for key employeeList, must be one of 'auth', 'main'

**Comment by chelseaisgood** [comment]
@shamanking Same here. I used Actions.main or Actions.pop to resolve this. But I do want to know how to navigate to some scene like employeeList, not the direct sub-scene of the root scene.

**Comment by shamanking** [comment]
@chelseaisgood : Thank you. I call employeeList from Scene employeeCreate. In Scene employeeCreate, I call action like:

`export const employeeDelete = ({ uid }) => {
  const { currentUser } = firebase.auth();

  return () => {
    firebase.database().ref(`/users/${currentUser.uid}/employees/${uid}`)
      .remove()
      .then(() => {
        **Actions.employeeList();**
      });
  };
};`

If I try:  Actions.employeeList({ type: 'reset' }); It has error.

**Comment by selvesandev** [comment]
@shamanking Did you solve this issue ?

**Comment by abohannon** [comment]
I am also getting this error. 

**There is no route defined for key key1. Must be one of: 'key2'**

Was working fine until I introduced the modal + the additional 'rootPrivate' scene as the docs detail for setting up the modal.

```
<Router getSceneStyle={this.getSceneStyle}>
        <Scene key="root" hideNavBar>
          <Scene key="public">
            <Scene
              key="login"
              component={LoginForm}
              title="Please Login"
              rightTitle="Sign up"
              onRight={() => Actions.signup()}
              hideNavBar
            />
            <Scene
              key="signup"
              component={SignupForm}
              title="Create Account"
              hideNavBar
            />
          </Scene>
          <Scene key="private" hideNavBar>
            <Modal>
              <Scene key="rootPrivate">
                <Scene
                  key="nearby"
                  component={Nearby}
                  title="Nearby"
                  leftTitle="Settings"
                  onLeft={() => Actions.push('settings')}
                  rightTitle="My places"
                  onRight={() => Actions.userDash()}
                  titleStyle={styles.titleStyle}
                  rightButtonTextStyle={{ color: GREY_DARK }}
                />
                <Scene
                  key="userDash"
                  component={MyPlaces}
                  title="My places"
                  titleStyle={styles.titleStyle}
                  backTitle="Nearby"
                  backButtonTextStyle={{ color: GREY_DARK }}
                  navBarButtonColor={GREY_DARK}
                />
              </Scene>
              <Scene
                key="settings"
                component={Settings}
                title="Settings"
                titleStyle={styles.titleStyle}
                rightTitle="Nearby"
                onRight={() => Actions.pop()}
                direction="leftToRight"
              />
            </Modal>
          </Scene>
        </Scene>
      </Router>
```

**Comment by Blapi** [comment]
@abohannon try adding a key to your Modal View ?

**Comment by saurabhabh** [comment]
@shamanking @selvesandev  I am facing the same issue. Any suggestions as to how to fix it?

**Comment by JanSros1** [comment]
![capture](https://user-images.githubusercontent.com/38139248/41499006-b57fe46e-71a3-11e8-935d-732b66e6f02f.PNG)

**Comment by daviscabral** [comment]
Also, not sure if is the same error - so, please, open a new issue, and be sure to put all the possible information to make easier to reproduce this error. Thank you again.

**Comment by mightym** [comment]
Same issue here. 
`"react-native-router-flux": "^4.0.0-beta.31",`
All scenes and stacks have a unique key. Btw. I'm encountering this since around beta.18 from time to time. The only way to reproduce it is to do a long time nothing with the app. Happens also on iOS simulator. Wonder if its happening when the app returns from background/sleep sometimes.


<img width="354" alt="bildschirmfoto 2018-06-29 um 19 37 19" src="https://user-images.githubusercontent.com/11863/42106296-dd095a12-7bd3-11e8-8a7f-aa5daeddaf52.png">

**Comment by jwilliamson1** [comment]
@shamanking @saurabhabh and anyone else who is having this problem, and is probably also doing Stephen Grider's React-Native course that this example seems to be from. You need to call `Actions.pop()` or `Actions.main()`, to go back on instead of using `Actions.employeeList({ type: 'reset' })`;.

try the following if the key is named main:

`export const employeeSave = ({ name, phone, shift, uid }) => {
  const { currentUser } = firebase.auth();

  return () => {
    firebase.database().ref(`/users/${currentUser.uid}/employees/${uid}`)
      .set({ name, phone, shift })
      .then(() => {
        Actions.main();
      });
  };
};`

or this if you just want to go back one; they both should have the same result:

`export const employeeSave = ({ name, phone, shift, uid }) => {
  const { currentUser } = firebase.auth();

  return () => {
    firebase.database().ref(`/users/${currentUser.uid}/employees/${uid}`)
      .set({ name, phone, shift })
      .then(() => {
        Actions.pop();
      });
  };
};`

**Comment by saurabhabh** [comment]
Thank you so much.
