### ISSUE TITLE
component only mounted once

### ISSUE THREAD

**Issue by jeffzing** [aksonov/react-native-router-flux#2440]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.19(v3 is not supported)
- react-native v0.47.1

<Scene key="root" navBar={NavigationBar} >
        <Scene key={'logIn'} hideNavBar component={ KSence['logIn'].screen }/>
        <Scene
            tabs
            lazy
            showIcon
            key="tabs"
            showLabel={false}
            tabBarPosition="bottom"
        >
            <Scene   key={'groupSet'}  focused title={'groupSet'} hideNavBar icon={TabbarView}  component={ KSence['groupSet'].screen }/>
            <Scene   key={'statistic'}  title={'statistic'} hideNavBar icon={TabbarView} component={ KSence['statistic'].screen }/>
            <Scene   key={'memberSet'}  focused title={'memberSet'} hideNavBar icon={TabbarView} component={ KSence['memberSet'].screen }/>
            <Scene initial  key={'cusService'}  title={'cusService'} hideNavBar icon={TabbarView} component={ KSence['cusService'].screen }/>
        </Scene>
        <Scene key={'userInfo'} title={'userInfo'} component={ KSence['userInfo'].screen }/>
        </Scene>

### Expected behaviour
there four tabs ,I switch tab to tab, is there anyway to know that I will switch tab1 to tab2,and I can decide go or not to go next scence?

### Actual behaviour
when I switch between tabs, I can get nothing from componentwillUpdate

**Comment by duyluonglc** [comment]
My experience use "lazy" props
```js
        <Tabs
          key='home'
          tabs
          tabBarPosition='bottom'
          animationEnabled={false}
          gestureEnabled={false}
          showLabel={false}
          swipeEnabled={false}
          hideNavBar
          tabBarStyle={styles.tabBarStyle}
          navigationBarStyle={styles.navBarStyle}
          lazy
        >
```

**Comment by jeffzing** [comment]
@duyluonglc the lazy prop did not help,whether there has lazy ,the component only mounted once
<Router
            >
            <Scene key="root" navBar={NavigationBar} >
                <Scene key={'logIn'} hideNavBar component={ KSence['logIn'].screen }/>
                <Scene
                    tabs
                    lazy
                    showIcon
                    key="tabs"
                    showLabel={false}
                    tabBarPosition="bottom"
                >
                    <Scene key={'groupSet'}  focused title={'groupSet'} hideNavBar icon={TabbarView}  component={KSence['groupSet'].screen}/>
                    <Scene key={'statistic'}  title={'statistic'} hideNavBar icon={TabbarView} component={KSence['statistic'].screen}/>
                    <Scene key={'memberSet'}  focused title={'memberSet'} hideNavBar icon={TabbarView} component={KSence['memberSet'].screen }/>
                    <Scene initial key={'cusService'}  title={'cusService'} hideNavBar icon={TabbarView} component={ KSence['cusService'].screen }/>
                </Scene>
                <Scene key={'userInfo'} title={'userInfo'} component={ KSence['userInfo'].screen }/>
            </Scene>
        </Router>

**Comment by duyluonglc** [comment]
Yes the component will mount once time. You can use onEnter prop to know when the tab is focused
My example everytime focus to favorite tab I do reload favorite data
```
class Favorite extends Component {
  static onEnter = () => {
    NavigationActions.refresh({
      enterTime: new Date()
    })
  }

  componentWillReceiveProps (nextProps) {
    this.forceUpdate()
    if (this.props.enterTime !== nextProps.enterTime) {
      this.getFavorites()
    }
  }
```

**Comment by jeffzing** [comment]
@duyluonglc static onEnter = () => { 
  } I wrote onEnter method like you, but onEnter not executed.

**Comment by jeffzing** [comment]
@duyluonglc now executed, thank you

**Comment by mcabs3** [comment]
When the tabs are "loaded" they are continuously in the navigation "state" so they only mount once and stay mounted. If you are looking for something when you `enter` or `exit` a scene, I believe there are some API methods you can attach to your tabs for this purpose.

**Comment by santiblanko** [comment]
This is a good solution if you want to reload on pop.

**Comment by himanshuc3** [comment]
Does this method work in v3.43.0?

**Comment by himanshuc3** [comment]
Does the ```onEnter``` method work in v3.43.0?
