### ISSUE TITLE
Keyboard disappears instantly when user taps on input

### ISSUE THREAD

**Issue by SoldierCorp** [aksonov/react-native-router-flux#2442]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.48.3

### Expected behaviour
Don't hide the keyboard when the user taps on input

### Actual behaviour
When the user taps on an input the keyboard shows up but instantly it hides and I've been tested all my plugins separately and the issue is when I'm implementing the Router with your package.

This is my Router.js for this demo

```
<Router createReducer={reducerCreate} openSideMenu={props.openSideMenu} closeSideMenu={props.closeSideMenu}>
      <Stack key='root'>
        <Scene key='login' hideNavBar='true' component={Login} type={ActionConst.REPLACE} />
      </Stack>
</Router>

```

It's very simple, I deleted all the other scenes in order to test just the login and the error is still there.

Hope you can help me.

**Comment by mcabs3** [comment]
Can you provide a video or snapshot of what you are experiencing. What TextInput are you selecting on which component, etc. Snippets and videos are very helpful if an issue is hard to document.

**Comment by m-sanduka** [comment]
same issue here, when I updated the router-flux to version v4.0.0-beta.21 the problem started to happen on android keyboard ... did u find the issue ?!

**Comment by SoldierCorp** [comment]
https://i.gyazo.com/a2afff7d5040d0b03f32e3bff17fbb2b.mp4

**Comment by koblinec** [comment]
"react-native": "^0.48.4"
"react-native-router-flux": "^4.0.0-beta.22"

my problem was the react-native-drawer component. I replaced this component in the react-native-router-flux drawer and everything works perfectly

**Comment by SoldierCorp** [comment]
Yes, yesterday at morning I realised of it and now I don't have that issue anymore :)

**react-native-drawer was the problem.**

**Comment by syq7970** [comment]
@SoldierCorp I have the same issual, could you please tell me how to fix this? thx

**Comment by fauzzi** [comment]
Hi @syq7970, @SoldierCorp I have same issue for dismiss keyboard in Android, for IOS this fine.
The issue is I have Slider using IndicatorViewPager with autoPlayEnable is true. My router flux using Tab. I set the Slider in dashboard. May be you can check each your Scene that have some autopalay active or not,

**Comment by syq7970** [comment]
@fauzzi Thanks! actually I using IndicatorViewPager too, after check my scene, issue just solved.

**Comment by munkhorgil** [comment]
@mcabs3 I got the same problem I don't have any slider, this issue needs to be open

**Comment by bilalsyed001** [comment]
See https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by ZeerakHameem32** [comment]
@fauzzi @syq7970 how did you guys solve this issue? I am also using the autoPlayEnable = true.
