### ISSUE TITLE
Closing the drawer reloads tabs and switches back to default tab

### ISSUE THREAD

**Issue by rwillemsandroid** [aksonov/react-native-router-flux#2443]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "4.0.0-beta.21"
- "react-native": "0.44.0"

### Expected behaviour

I have a Drawer Scene wrapping a Tab scene (similar to the Example App).
When I open and close the drawer without performing any other actions, the user should remain on the same tab.

### Actual behaviour

When I'm not in the default tab (Tab_#2 in Example app) and I open & close the drawer, the scene will re-open and bring me back to Tab_#2)

### Steps to reproduce

1. Clone react-native-router-flux repo
2. Compile Example app
3. Go to TabBar Page
4. Open Tab_#1 
5. Open drawer by clicking on the blue hamburger icon
6. Close drawer by clicking right of the drawer on the underlying scene
7. Scene will refresh and tab2 will be open again

**Comment by redwind** [comment]
add `backBehavior={'none'}` to your tabs route
