### ISSUE TITLE
How to create Tabbar with icon&Text

### ISSUE THREAD

**Issue by nghialuutrung** [aksonov/react-native-router-flux#2446]
I search in doc, i don't know how to create tabbar with icon&Text use react-native-router-flux.
Please help me!!!!
Thank you very much!!!!

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.4.8

**Comment by ghoshabhi** [comment]
I also want to look at a clean example of just tabbed navigation.

**Comment by mcabs3** [comment]
this can be done using `icon` and `tabBarLabel` component on an individual Tabbed `Scene`.

```jsx
<Tabs>
  <Scene
  tabBarLabel={'Something'}
  icon={IconComponent}
  />
</Tabs>
```

**Comment by nghialuutrung** [comment]
thank you very much!

**Comment by dwilt** [comment]
Just a heads up. This seems really weird, and might be a bug, but you can't pass a rendered component to the `icon` prop:

```js
<Scene
    hideNavBar
    key={MY_ACCOUNT_KEY}
    tabBarLabel={`My Account`}
    component={MyAccount}
    icon={<Icon
            size={iconSize}
            color={iconColor}
            name={`home3`}
        />}
/>
```
You get this error:
![image](https://user-images.githubusercontent.com/1065539/31337070-94884016-acf1-11e7-9147-d787f217d909.png)

The way around it is to wrap the component in a function:
```js
<Scene
    hideNavBar
    key={MY_ACCOUNT_KEY}
    tabBarLabel={`My Account`}
    component={MyAccount}
    icon={() => (
        <Icon
            size={iconSize}
            color={iconColor}
            name={`home3`}
        />
    )}
/>
```

**Comment by dwilt** [comment]
It seems the `icon` prop uses the v3 callback as explained [here](https://github.com/aksonov/react-native-router-flux/issues/2313#issue-254392288). Except now, the `selected` prop is now `focused`. Here's how I got it working:

```js
<Tabs
    showLabel={false}
    lazy={true}
    tabStyle={styles.tab}
    tabBarStyle={styles.tabs}
    labelStyle={styles.label}
    swipeEnabled={false}
>
    <Scene
        hideNavBar
        key={MY_WATER_KEY}
        component={MyWater}
        icon={({ focused }) => (
            <Icon
                size={iconSize}
                color={focused ? activeIconColor : iconColor}
                name={`drop2`}
                text={`My Water`}
                textStyle={focused ? [styles.label, styles.activeLabel] : styles.label}
            />
        )}
    />
    <Scene
        hideNavBar
        key={INBOX_KEY}
        component={Inbox}
        icon={({ focused }) => (
            <Icon
                size={iconSize}
                color={focused ? activeIconColor : iconColor}
                textStyle={focused ? [styles.label, styles.activeLabel] : styles.label}
                name={`envelope`}
                text={`Messages`}
            />
        )}
    />
    <Scene
        hideNavBar
        key={MY_ACCOUNT_KEY}
        component={MyAccount}
        icon={({ focused }) => (
            <Icon
                size={iconSize}
                color={focused ? activeIconColor : iconColor}
                textStyle={focused ? [styles.label, styles.activeLabel] : styles.label}
                name={`home3`}
                text={`My Account`}
            />
        )}
    />
</Tabs>
```
![image](https://user-images.githubusercontent.com/1065539/31338504-7402a56a-acf7-11e7-9c58-d4f92b3a4a6e.png)

By the way, I wanted more control over the labels so I passed the text into my `Icon` component and render it there and use the `showLabel={false}` on the `Tabs` component.

**Comment by ghoshabhi** [comment]
@dwilt Thanks for the example. Just had a small question. How do I change the scene being rendered based on the tab click ? Just usual `Action.sceneKey()` ?

Thanks.

**Comment by dwilt** [comment]
@ghoshabhi yep

**Comment by wincod75** [comment]
Does this still work? My text label is not showing...

icon={({ focused }) => (
            <Icon
                size={iconSize}
                color={focused ? activeIconColor : iconColor}
                textStyle={focused ? [styles.label, styles.activeLabel] : styles.label}
                name={`home3`}
                text={`My Account`}
            />
        )}

**Comment by uncvrd** [comment]
@wincod75 any luck after a day? I'm just running into this issue as well and cannot get anything to display

**Comment by wincod75** [comment]
@uncvrd No luck, can't get anything to display either.

**Comment by uncvrd** [comment]
@wincod75 ugh well keep me posted if you do. I'll keep searching

**Comment by webjyh** [comment]
@uncvrd @wincod75 
```javascript
const TabIcon = (props) => {
    console.log({...props});
    return (
        <View>
            <Text>{JSON.stringify(props.focused)}</Text>
        </View>
    )
};


<Scene icon={TabIcon} ... />
```
