### ISSUE TITLE
How to display background Image on Navbar

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2447]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

I would like to show background Image on `Navbar`, or  is there anyway to apply Gradient (`react-native-linear-gradient`) on `Navbar`?

**Comment by mcabs3** [comment]
I think you would need to provide your own custom navBar component. @aksonov sound about right?

**Comment by shukerullah** [comment]
I have no issue with custom `navBar` as far as iOS `navBar` animation works fine.

**Comment by aitemr** [comment]
@shukerullah  You can use "react-native-router-flux": "^3.37.0", and you can pass backgroundImage props.

**Comment by shukerullah** [comment]
@aitemr are you sure `backgroundImage` work in v^4 ?

**Comment by aitemr** [comment]
@shukerullah I said react-native-router-flux": "^3.37.0 version

**Comment by kylanhurt** [comment]
@aitemr Will you guys be adding this sort of functionality for version 4? I know you guys get swamped with feature requests. I specifically am looking to use a colored gradient as the background for the header within version 4. Is it possible to pass a colored gradient as the navBar component? What would the code / API for that look like?

**Comment by mirrorshades** [comment]
@aitemr react-native-router-flux ^3.37.0 is a terrible fix if you are using a newer version of react-native since it calls proptypes the old way.

```import React, {
  PropTypes,
} from 'react';```

**Comment by aksonov** [comment]
Just use custom navbar for v4.
