### ISSUE TITLE
Can't hide tab icon

### ISSUE THREAD

**Issue by bjarkof** [aksonov/react-native-router-flux#2450]
Tell us which versions you are using: 
4.0.0-beta.21

I'm trying to hide the tab icon. I have tried setting the "icon" prop to null and also not specifying one at all. Are there any way to do this, without making a custom tabbar?

**Comment by mcabs3** [comment]
By default there are no tab icons provided. just the tabBarLabel. Can you provide more context to your situation?

**Comment by bjarkof** [comment]
I solved this by adding `showIcon={false}` to the `Tabs` component. I dont know why, but even though I had not provided an `icon` prop on the child scenes, there was visually left "room" for the icons, so that the labels were not centered at the tabs.
