### ISSUE TITLE
Navigation between Scene and Tabs is slow

### ISSUE THREAD

**Issue by mikesol** [aksonov/react-native-router-flux#2457]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21 
- react-native v0.48.4

### Expected behaviour

Navigating to a sub-scene with tabs is fluid.

### Actual behaviour

Navigation is laggy compared to navigation between non-tab Scenes.  I think this is because all the tabs render at once.  If this is true, then it would be nice to have an option that glances ahead only by a certain number of tabs to avoid the rendering happening all at once.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create a tab scene with 7 subtabs full of stuff (text, images, etc).
2. Navigate from a normal scene to the tab scene.

**Comment by aksonov** [comment]
Maybe you can try latest version, but anyway this component doesn't provide rendering, only easier JSX syntax to define routes. Rendering is done by react navigation
