### ISSUE TITLE
Loading a specific tab and pressing backbutton navigates to initial tab

### ISSUE THREAD

**Issue by vhoen** [aksonov/react-native-router-flux#2459]
### Version

- react-native-router-flux v4.0.0-beta.21
- react-native v0.44.4

### Expected behaviour
I played around with the example and found a behaviour that doesn't seem logical to me. 
I added a Button on the "Launch" Scene, this button loads the "tabbar" Scene on the third tab (see "Steps to reproduce"). When tapping on the navbar's backbutton, I was expecting to come back to come back on the "Launch" Screen, instead of that I come back on the second tab (which has the "initial" attribute)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. On Launch.js, add a button : &lt;Button title="Go to TabBar N°3" onPress={Actions.tab_3} /&gt;
2. Load the app and tap on the button
3. Tap the backbutton in navbar

**Comment by aksonov** [comment]
I see this issue but it is how react navigation works (used by RNRF) - so first tab bar is display with initial tab_2 then it navigates to tab_3.
