### ISSUE TITLE
Feature: `activeLabelStyle` and `activeTabStyle`

### ISSUE THREAD

**Issue by dwilt** [aksonov/react-native-router-flux#2460]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.4

### Expected behaviour
Since we have a `labelStyle`and `tabStyle` along with `activeBackgroundColor` and `activeTintColor`, it would be handy to have `activeLabelStyle` and `activeTabStyle` which would be styles that could be passed in and applied when that tab is currently selected

**Comment by dwilt** [comment]
I've ditches these all together and am using the `icon` prop to get all of the styling for inactive and active states on the icon and text. See my example [here](https://github.com/aksonov/react-native-router-flux/issues/2446#issuecomment-335146783)

**Comment by aksonov** [comment]
It is not supported right now, PR is welcome.
