### ISSUE TITLE
Update sceneStyle propTypes on Router to take number, not just object

### ISSUE THREAD

**Issue by dwilt** [aksonov/react-native-router-flux#2461]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.4

### Actual behaviour
```
<Router
    sceneStyle={styles.router}
>
```
This should not throw a warning for passing in a style reference (`styles.router`). The styling works, but you get the standard proptype yellow box warning:

![image](https://user-images.githubusercontent.com/1065539/31224321-53ce41c6-a9c5-11e7-88a5-fcd21dbec712.png)

### Steps to reproduce

1. Attach any referenced style (not an inline style object) to `sceneStyle` on `Router`

**Comment by aksonov** [comment]
The component just uses 'ViewPropTypes.style'
