### ISSUE TITLE
Tabs do not work on android

### ISSUE THREAD

**Issue by scotttharvey** [aksonov/react-native-router-flux#2465]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0 (v3 is not supported)
- react-native v0.49.1

### Expected behaviour
Tabs to work on both android and iOS

### Actual behaviour
Tabs only work on iOS

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment]
Example project works well.
