### ISSUE TITLE
Error: Show Inspector in Developer Menu

### ISSUE THREAD

**Issue by LouisJS** [aksonov/react-native-router-flux#2466]
### Version

- react-native-router-flux v4.0.0-beta.21
- react-native v0.44.0

MacOS Sierra 10.12.6

### Expected behaviour

I've cloned the repo and launched the Example App on iOS simulator
I open the **Developer Menu** and clicked **Show Inspector** and i should be able to select and see my UI components properties

### Actual behaviour

It works fine, until i opened the **Developer Menu** and clicked **Show Inspector**
Then it triggers an error which tells us : 

_There is no route defined for key key1. Must be one of: 'key5','error','login'._

And it makes your entire app crash even when you press **(ESC)Dismiss** on the **Error Screen**

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. git clone https://github.com/aksonov/react-native-router-flux.git
2. cd react-native-router-flux/Example
3. yarn
4. react-native run-ios
5. In the Simulator, use the **⌘D** keyboard shortcut
6. Click 'Show Inspector'

**Comment by tedkimzikto** [comment]
having same issue :(

**Comment by onrige** [comment]
It happens because you don't specify `key` for some `Scene`.

**Comment by aksonov** [comment]
Please check latest master now
