### ISSUE TITLE
TextInput into NavBar

### ISSUE THREAD

**Issue by serialbandicoot** [aksonov/react-native-router-flux#2468]
Hi I was looking at putting a TextInput into the navigation bar in order to create a search facility and I was struggling to find an example or some docs how to proceed.

Would anyone be able to point me in the right directions. 

thanks :)

**Comment by sanjeevkse** [comment]
Need the same.

**Comment by jaywalklabs** [comment]
[https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#scene](url)

navBar | React.Component |   | Optional React component to render custom NavBar
-- | -- | -- | --

i.e. set the navbar to be a custom React component

then put 

`<Scene navBar={CustomNavBar} />`

**Comment by serialbandicoot** [comment]
Great thanks, i tried the following and at least started making progress. 

```
class NavBar extends Component {
    render() {
        return (
            <View>
                <StatusBar />
                <TextInput style={{height: 40, width: 100, backgroundColor: 'white'}}/>
            </View>
        );
    }
}

```

**Comment by serialbandicoot** [comment]
A bit of a followup question, but how would you enable and disable the TextInput from being displayed, after clicking Left/Right Button on the nav?

**Comment by jaywalklabs** [comment]
not sure what your flow is but you can use 

` Actions.refresh({status:xyz})`
or render based on whats in` Actons.currentScene`
or look in to the life cycles using `onEnter,onLeave, onLeft, onRight` etc

**Comment by serialbandicoot** [comment]
That's great, I went with a slightly different option by using SearchBar from the library 'react-native-searchbar', as it's got an easy method to hide.

<img width="363" alt="screen shot 2017-10-10 at 07 13 03" src="https://user-images.githubusercontent.com/742312/31371742-7d402aba-ad8a-11e7-8c24-1dc4a880459f.png">

User can exit the search routine if required.

<img width="359" alt="screen shot 2017-10-10 at 07 14 05" src="https://user-images.githubusercontent.com/742312/31371763-9d1e8782-ad8a-11e7-9d91-0b1ce46b5b1f.png">

Happy to leave a code snippet if anyone interested...I'll close the ticket otherwise as my question has been answered - :)

**Comment by onrige** [comment]
You also can create you own navbar with input and show it "on the fly" by using Actions.refresh({ navBar: `Your searchbar here` }) when you need this.
