### ISSUE TITLE
API Documentation is missing a definition for Actions.popTo()

### ISSUE THREAD

**Issue by agm1984** [aksonov/react-native-router-flux#2470]
### Steps to reproduce
1. navigate to the API documentation
2. scroll down to **Actions.popTo()**
3. read the text
4. the wording is incomplete
5. here is a screenshot
6. i just noticed the option above it also is missing a description
7. **Actions.popAndPush()** description is missing

![rnrf](https://user-images.githubusercontent.com/17655219/31304928-b074c8b4-aae2-11e7-8e49-41cada60ce06.png)

It should say something like "Pops the stack until the specified scene is reached" ?

**Comment by mcabs3** [comment]
Docs have been updated, thanks for pointing that out.
