### ISSUE TITLE
how to leftAlign Left Image button on NavBar

### ISSUE THREAD

**Issue by serialbandicoot** [aksonov/react-native-router-flux#2471]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.21
- react-native v0.48.4

### Issue

I've added an image as the leftButton, however I can't seem to align left of the screen. Is there anyway to re-position the search image? 

Many thanks...

<img width="315" alt="screen shot 2017-10-07 at 11 33 47" src="https://user-images.githubusercontent.com/742312/31307049-2dceada4-ab54-11e7-9181-cf67c39df9be.png">

**Comment by mcabs3** [comment]
Can you show us a code snippet?

**Comment by serialbandicoot** [comment]
Just the following inside the Scene:

`onLeft={ () => Actions.search() } leftButtonImage={require("./images/img.png")}`

**Comment by aksonov** [comment]
Looks like you have more navbar global stylings defined. Please check Example project - it renders left button correctly.
