### ISSUE TITLE
map next scenes

### ISSUE THREAD

**Issue by James2516** [aksonov/react-native-router-flux#2475]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

```
    const scenes = [
      ['Scene1', <Scene1 />],
      ['Scene2', <Scene2 />],
    ].map(([key, Component], i, arr) => [key, () => React.cloneElement(Component, {
      nextScene: (arr[i + 1] || [])[0],
      previousScene: (arr[i - 1] || [])[0],
    })]);

    <Scene>
      {scenes.map(([key, component]) => (
        <Scene key={key} component={component} />
      ))}
    </Scene>
```

`Scene1` and `Scene2` has "Previous" and "Next" buttons that navigates to the previous/next scene (based on the `scenes` array), so the `nextScene` and `previousScene` must be passed to the scenes. 

Is this the right way to do it?

**Comment by aksonov** [comment]
Sorry, dynamic declaration is not supported by RNRF
