### ISSUE TITLE
how to give as props navigationBarStyle, when calling some component from Actions

### ISSUE THREAD

**Issue by nursultan1201b** [aksonov/react-native-router-flux#2479]
### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.0

For example, when i call Actions.login({title: 'Login', navBarStyle: styles.navBar}), I want my login form header to have red background (my styles).
const styles = {
  navBar: {
    backgroundColor: 'skyblue',
    paddingTop: 30,
  },
}

**Comment by aksonov** [comment]
Have you tried to used navigationBarStyle mentioned in docs? You can pass it pass as prop to 'login' Scene

**Comment by nursace** [comment]
Yes, I tried, but what if this component is universal and I want to change its style depending on where it was called?

**Comment by bilalsyed001** [comment]
Try setting headerStyle
