### ISSUE TITLE
Tabs attributes `activeBackgroundColor` and `inactiveBackgroundColor` do not work on nested Tabs component

### ISSUE THREAD

**Issue by Baltino** [aksonov/react-native-router-flux#2482]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.44.0

### Expected behaviour
Tabs attributes `activeBackgroundColor` and `inactiveBackgroundColor` should always work, in nested tabs components.

### Actual behaviour
Tabs attributes `activeBackgroundColor` and `inactiveBackgroundColor` do not work on android when `tabBarPosition="top"` is used in a nested Tabs Component.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. On Example.js, within Tabs component with key="tab_1", add `tabBarPosition="top"`
2. Run and open the emulator.
3. Go to Tabbar page.

**Comment by aksonov** [comment]
Sorry, it is not supported (by react navigation) - you have to pass it only for parent tabs container.
