### ISSUE TITLE
Bad performance during orientation change with tabs

### ISSUE THREAD

**Issue by CptFabulouso** [aksonov/react-native-router-flux#2483]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0 - beta 21
- react-native v0.48.4

### Expected behaviour
When I have tabs layout and rotate device, I do not expect to see next screen to the right. In other words: rerender layouts during screen transition

### Actual behaviour
When device is rotated, the whole layout gets rotated first with the width of previous orientation and next tab (screen and header) to the right of selected tab is visible for awhile (if we go from port to land). 

### Steps to reproduce
running on ios device (iPhone 5), it is not visible on emulator. Android not tested at all
Happens in example project in tabBar page. It is noticeable in debug scheme and not very noticeable in release scheme, but that changes with more complicated layout.

It would be great if it could be implemented into this library somehow, but workarounds are also welcomed. I would much rather wait for recalculation of layout before the whole transition happens than the current behaviour.

**Comment by aksonov** [comment]
RNRF uses react-navigation for rendering. Please check beta.22 (it uses rn beta.13) and check pure react-navigation examples. If it doesn't work as expected, please create issue there.

**Comment by CptFabulouso** [comment]
This is actually problem of react-native-tab-view, which react-navigation is using for tabs. But in react-navigation is [this](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js) example of custom tabs, which just renders current screen and custom tab bar and no screens around. 
So we could recreate that logic, use TabView components of react-navigation so it looks like current Tabs navigation and use that if swipeEnabled = {false}. We don't need pages rendered next to each other, if we don't swipe between them. I would love to do that, but Iam quite confused how this library even works.
