### ISSUE TITLE
Drawer : `onEnter`, `onExit` or `open`... 

### ISSUE THREAD

**Issue by matthieupinte** [aksonov/react-native-router-flux#2485]
### Version

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

### Expected behaviour

`onEnter`, `onExit` callbacks on `Drawer` not "working"...

### Actual behaviour

I try to figure out how to know if Drawer is opened or not... to change `StatusBar` style or other styles depending on drawer status.
Is this possible ? In fact `Drawer` doesn't respond to `onEnter`, `onExit` or to props `open`...

Can you guys give me some help ? ^^

Thanks for your work

**Comment by aksonov** [comment]
Sorry, it is not supported.

**Comment by Mimicx** [comment]
Same issue

**Comment by NelGarbuzova** [comment]
+1

**Comment by daviscabral** [comment]
v3 and 4.0.0-beta are not supported. Drawer support for `onEnter` and `onExit` were just added on `4.0.2`.
