### ISSUE TITLE
Going from tab through non-tabs back to different tab

### ISSUE THREAD

**Issue by ssomnoremac** [aksonov/react-native-router-flux#2486]
### Version
- react-native-router-flux Latest
- react-native v0.48.2

### Expected behaviour
Go from a tab scene to a non-tab scene, another non-tab, back to a different tab with a smooth, single transition on the last step.

### Actual behaviour
I can only navigate back safely by popping back to the tab, then to the second tab -- if I try to directly push to the second tab it goes but then does a reset to scene right afterwards(2 transitions and I'd rather not reset).

### Steps to reproduce
```
<Scene>
     <Tabs key="company">
              <Scene key="tab1"/>
              <Scene key="tab2"/>              
              <Scene key="tab3"/>
     </Tabs>
     <Scene key="A"/>
     <Scene key="B"/>
</Scene>
```

I want to go from tab1 -> A -> B -> tab2.

I have a feeling like it doesn't work to do this, which is fine, but then I need a way to either

1. Pop immediately back to tab1 without animations and then go to to tab2. Can't do this, can I?
 or
2. Display a modal over the popping animation. Modal can't do this as far as I can tell.

**Comment by ssomnoremac** [comment]
I have a work-around so I'm going to close with it. Don't have time to solve this properly. Maybe I'll come back to it if people want. 

Here's what I did. I'm still popping back to my tab scene, but you can trick lightbox into staying visible as you pop by doing this:

```
// display the modal
Actions.loadingModal()
// pop as much as needed to get back to tab scene (popTo doesn't work in this case for me)
Actions.pop()
Actions.pop()
// load the modal back immediately
Actions.loadingModal()        
// close the popup by navigating to new tab
setTimeout(() =>{
     Actions.tab2()            
}, 3000)

```

**Comment by bilalsyed001** [comment]
This works for me:

```
  popToRoot = state => {
    Actions.pop();
    if (state.routes) {
      return state.routes.every(popToRoot);
    }

    return true;
  }
```

```
popToRoot(Actions.state);
Actions.jump('tab2');
```

**Comment by munkhorgil** [comment]
@ssomnoremac Any update on this? When I wrap all my scenes and tab in drawer, All scenes considered as same level that is why it is not stacking and goes back to initial which is tab1. Still no solution...
