### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by Frexuz** [aksonov/react-native-router-flux#2488]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.45.1

### Expected behaviour

Running the app successfully.

### Actual behaviour

Using Tabs isn't working for me. *Removing it works fine!*

```
class AppRouter extends Component {
  render () {
    return (
      <Router
        createReducer={reducerCreate}>
        <Modal hideNavBar>
          <Scene hideNavBar>
            <Tabs
              key='tabbar'
              showLabel
              swipeEnabled={false}
              tabBarPosition='bottom'
              lazy>
              <Stack
                key='HomeStack'
                title='Home'
                icon={TabIcon}
                initial >
                <Scene
                  key='Profile'
                  hideNavBar
                  component={UserHistoryList}
                />
              </Stack>
            </Tabs>
          </Scene>
       </Modal>
      </Router>
    )
  }
}
```

![screen shot 2017-10-10 at 16 27 10](https://user-images.githubusercontent.com/49692/31376619-21be961a-add8-11e7-9f0c-2b43d00f3b67.png)

### Steps to reproduce

- Strangely, the Example app works for me.
- Another developer can run our repo fine.

- I've tried `rm -r node_modules`, `npm start --reset-cache` and `yarn install`

I understand since its not easily reproducible, you don't have much to go on.

**Comment by aksonov** [comment]
Probably you have to use atleast two tabs for TabBar.
