### ISSUE TITLE
Need to unmount component on leaving a tab

### ISSUE THREAD

**Issue by sina-mirhejazi** [aksonov/react-native-router-flux#2489]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.49.3

Is there any way to unmount a component as soon as I leave its tab?

I have four tabs and using `lazy` attribute, so component will not be mounted until their tab is active, but I want to unmount them when I leave them.
I'm new on RN and the problem is each of my tabs has lots of data and when the user goes around on app for a while it gets laggy and unusable on some devices.

**Comment by aksonov** [comment]
Sorry, it is not possible, probably you could try to use 'replace' action instead.

**Comment by fadlykayo** [comment]
@sina-mirhejazi hello, any success with unmounting the tab on leaving?

**Comment by sina-mirhejazi** [comment]
@fadlykayo Hi. No, I didn't find a way to unmount them. But I cannot remember what did I do to overcome the problem! It was like a year ago

**Comment by Rananjaya** [comment]
I have same problem, any solution for this
