### ISSUE TITLE
Actions transitions cannot be configured

### ISSUE THREAD

**Issue by raynor85** [aksonov/react-native-router-flux#2490]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.14
- react-native v0.46.4

### Expected behaviour
I'd like to have an option to avoid transition whether I use Actions.[method]

### Actual behaviour
The transition cannot be configured at all. I'd like to see an example of how it is possible to achieve that, and it should be documented

**Comment by aksonov** [comment]
Please check Example project to check custom transitions.
