### ISSUE TITLE
Missing navigationBarStyle typing on Stack

### ISSUE THREAD

**Issue by bm-software** [aksonov/react-native-router-flux#2493]
I'm using the latest version and trying to integrate it in my app.
All works for now but many typings are missing like `navigationBarStyle` on `Stack` object.

Do you plan to complete typings?

**Comment by aksonov** [comment]
It is open source project. I'm not using typescript, but feel free to add PR with typings and I will merge. As I know recently there were some PRs about that (beta.22)
