### ISSUE TITLE
Transitions not working (transitionConfig)

### ISSUE THREAD

**Issue by bm-software** [aksonov/react-native-router-flux#2499]
### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.1

### Expected behaviour
Setting `transitionConfig` property must apply the transition.

### Actual behaviour
Setting `transitionConfig` property has no effect, also after `duration` property is set like in the Example app.

### Steps to reproduce
In the root component (`App.tsx`)

    render() {
        return (
            <Root>
                <StatusBar
                    backgroundColor='#D3C030'
                    barStyle='light-content'
                    translucent={true}
                />
                <Provider store={this.state.store}>
                    <AppRouter />
                </Provider>
            </Root>
        )
    }

In the `AppRouter` component render method:

    <Router createReducer={createReducer} backAndroidHandler={onBackPress}>
        <Modal
            hideNavBar
            transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal })}
        >
            <Stack key='root' navigationBarStyle={sharedStyles.header}>
                <Scene key='splash' component={SplashScreen} initial hideNavBar duration={1}/>
                <Scene key='login' component={LoginScreen} title='Accedi' renderLeftButton={null} duration={1}/>
                <Scene key='main' component={MainScreen} title='CaliUp' renderLeftButton={null} duration={1}/>
                <Scene key='course' component={CourseScreen} duration={1}/>
                <Scene key='alerts' component={AlertsScreen} duration={1}/>
                <Scene key='account' component={AccountScreen} title='Gestione Account' duration={1}/>
            </Stack>
        </Modal>
    </Router>

### Moreover
Which components support the `transitionConfig` property? Docs are very incomplete and I can't figure out on which component I have to apply the configuration.
I tried to set it on `Modal` like in the Example app but it doesn't work and the same is for `Stack` and `Scene`.

**Comment by aksonov** [comment]
I clearly see different transition for Example project If you still have issue with latest RNRF, please fork & modify Example project to demonstrate the issue. You may also check  #2628

**Comment by maulikdhameliya** [comment]
I have tested and it works properly with scenes also .

install react-navigation

`import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';`


```
<Router>
   <Scene key="root" transitionConfig={() => ({screenInterpolator: CardStackStyleInterpolator.forHorizontal})}>
       <Scene key="OnBoarding" hideNavBar={true} component={OnBoarding} type={'reset'}/>
       <Scene key="CreateAccount" hideNavBar={true} component={CreateAccount}/>
    </Scene>
</Router>
```

so I am able to get iOS style transition animation for all the scenes

**Comment by dccmmtop** [comment]
@maulikdhameliya  thank you very much
