### ISSUE TITLE
PopUp View can't call programatically....

### ISSUE THREAD

**Issue by pmpSalween** [aksonov/react-native-router-flux#25]
I fetch some data from url and while downloading I show loading view using Actions.popupLoadingView() in componentWillMount/componentDidMount. But after updating to version 0.3.4, Loading popup View does not show up anymore. But it does show when refresh button is pressed to re-download data from url again. 

    componentWillMount: function () {
        this.fetchDataFromUrl();
    },

    refreshList: function() { //onPress function of some button and popUpLoadingView shows up.
      this.setState({
          networkError : false,
      });
    this.fetchDataFromUrl();
    },

    fetchDataFromUrl() {
       Actions.popUpLoadingView({msg: 'Downloading....'}); //This does not show up 
      
       fetch(some_Url)
         .then((response) => response.json())
      .then((responseData) => {
       console.log(responseData);
        Actions.dismiss();
      })
       .catch((error) => {
        console.warn('error ::: ' + error);
        Actions.dismiss();
        this.setState({
          networkError: true,
        });
      })
      .done(()=> {
      });

**Comment by aksonov** [comment]
It is very strange, there is nothing about popup changes in 0.3.4, could you check when it became not working? Maybe it happens after upgrade of React Native? Anyway, sample github repo with error would be helpful.

**Comment by pmpSalween** [comment]
https://github.com/pmpSalween/FLUX_EXAMPLE

**Comment by aksonov** [comment]
I believe you should fix it to work with latest React Native first. I'm getting that:

that one is outdated:
var Dimensions = require('Dimensions');
var {width, height} = Dimensions.get('window');

![simulator screen shot 21 2015 4 20 15 pm](https://cloud.githubusercontent.com/assets/1321329/10639301/b58decac-780f-11e5-8ad7-00a89de9969c.png)

**Comment by pmpSalween** [comment]
I am using react-native 0.12.0 and I still got that error. So I need to declare Dimensions in Animation.js file by myself.

**Comment by aksonov** [comment]
I don't understand. Your repo doesn't work and show that exception. Component demo works fine.

Pavel.

**Comment by pmpSalween** [comment]
I tested component demo. It does not show that error. I just added component demo with popup in componentDidMount function. It does not work either. Could you please check my repo again. There is a new folder called "FluxExampleOrigin" which is component demo with modification. Sorry for late reply.

**Comment by aksonov** [comment]
I've removed popups for new version to avoid extra complexity. If there will be enough interest for it,  i will add it to new version
