### ISSUE TITLE
Accessing Route outside of Router looses Navigation bar (with Drawer)

### ISSUE THREAD

**Issue by ws3li** [aksonov/react-native-router-flux#250]
**Question:** How to properly route between component (with drawer) and another component (without drawer) without loosing navigationbar 

I have the following code in my **Router.js**
```
  <Router hideNavBar={true} navigationBarStyle={{backgroundColor: '#0bd5a2'}}>

        {/* main route */}
        <Route name='main' hideNavBar={true} type='reset' initial={true}>
          <Drawer>
            <Router navigationBarStyle={{backgroundColor: '#0bd5a2'}}>

              <Route name="main_main" component={maincomponent} title="main_main"
                hideNavBar={false} type='replace'
                renderLeftButton={()=> <Button 1/>}
                renderRightButton={()=> <Button 2/>}
                />

            </Router>
          </Drawer>
        </Route>

        {/* page two route */}
        <Route name="page_two" component={pagetwocomponent}
          title="page_two"
          hideNavBar={false} 
          renderLeftButton={()=> <BackButton />
          />
</Router>
```

When the app lauches it navigates to **main** and then to another router -> route **main_main**.
In the **maincomponent** I have shown a navigation bar with a **left** and **right** button.

When the right button **(Buttton 2)** is pressed it does an **Action.page_two()** which routes to component **pagetwocomponent**

This all works fine. Unitl now, I get routed to **pagetwocomponent** but the entire navigationbar (containing a backbutton) is missing.

I could place the **Route name="page_two"** inside the Drawer Router (as shown below) and everything works fine, but the drawer will also be part of the **pagetwocomponent**, which is something I do not want. I want **maincomponent** to have a Drawer but not **pagetwocomponent** 

```
  <Router hideNavBar={true} navigationBarStyle={{backgroundColor: '#0bd5a2'}}>

        {/* main route */}
        <Route name='main' hideNavBar={true} type='reset' initial={true}>
          <Drawer>
            <Router navigationBarStyle={{backgroundColor: '#0bd5a2'}}>

              <Route name="main_main" component={maincomponent} title="main_main"
                hideNavBar={false} type='replace'
                renderLeftButton={()=> <Button 1/>}
                renderRightButton={()=> <Button 2/>}
                />

        {/* page two route */}
        <Route name="page_two" component={pagetwocomponent}
          title="page_two"
          hideNavBar={false} 
          renderLeftButton={()=> <BackButton />
          />

            </Router>
          </Drawer>
        </Route>
</Router>
```

Any help would be appreciated!
Thank you in advanced.

**Comment by aksonov** [comment]
You hidden root nav bar and then switched to 'root' route then sure, it will not have navbar. Have you tried to put renderLeftButton, renderRightButton to root router and show it?

**Comment by ws3li** [comment]
When you say 'root' which route are you indicating?
in my main router I do hideNavBar={true} already.
Can you show me an example? Thanks

**Comment by aksonov** [comment]
You may check 3.0 release now with approach of 'custom' renderer. Closing this ticket for now.
