### ISSUE TITLE
 the question is  how can i  let the children scenes will have right-to-left  animation on android?

### ISSUE THREAD

**Issue by liuzhe429** [aksonov/react-native-router-flux#2502]
### Version

- react-native-router-flux  : "^4.0.0-beta.21",

### Expected behaviour

| `modal`     | `boolean` | `false` |  Defines scene container as 'modal' one, i.e. all children scenes will have bottom-to-top animation. It is applicable only for containers (different from v3 syntax) |, 

### Actual behaviour
on the android the scenes is from bottom to top, ios is from right to left,
and the question is  how can i  let the children scenes will have right-to-left  animation on android?

**Comment by aksonov** [comment]
It is default animation for android (bottom to top) for all containers. Please use custom animation like shown in Example to achieve right-to-left.

**Comment by Blapi** [comment]
@liuzhe429 check #2628
