### ISSUE TITLE
Navigate on modification in the redux store

### ISSUE THREAD

**Issue by amarkovits** [aksonov/react-native-router-flux#2503]
I'm having a react-natvie application using redux and react-native-router-flux with user authentication and I want to navigate to the main screen when the user is authenticated (no matter how this authentication is made) and to the login screen when the authentication token is invalid (no matter when or how this happens). 

My first thought was to make the navigation in the reducer like this:

     case LOGIN_SUCCESS:
          DataManager
                .getInstance()
                .setToken(action.payload.token);
            return {
                ...state,
                token: action.payload.token,
                loading: false
            }`

The problem is that in this case the navigation happens before the state is updated and I get in the situation that I render the main screen but my token from the store is not updated yet. 

I can solve the login case by checking the state in my login component but for the logout case wich can happen in any component I don't know how to make something general. 

How should I make my app navigation based on modifications in the redux store?

**Comment by jordanfloyd** [comment]
This is a great use case for a side effect library like redux-saga: https://redux-saga.js.org/. Essentially actions that would modify the store like a user set action can also be picked up by the middleware and trigger some other functionality like a navigation change. You can setup a generator function that watches for actions of a certain type to come in, and when they do then go get data from the store and use that data to inform your navigation action, like the presence or absence of a token. You don't necessarily have to use redux-saga, but it fits in nicely with the architecture if you are already using redux. 

Example implementation:
`
function * watchForAuthChanges() {
  while(true) {
    const action = yield take([
      UserTypes.LOG_IN,
      UserTypes.LOG_OUT
    ])

    const user = yield select(UserSelectors.get)
    if (user.token) {
      yield call(Navigation.Actions.Main)
    }
    yield call(Navigation.Actions.Other)
}
`
