### ISSUE TITLE
Help needed with multiple drawers on each page.

### ISSUE THREAD

**Issue by parthgandhi7** [aksonov/react-native-router-flux#2506]
I am using 
- react-native-router-flux 4.0.0-beta.22
- react-native 0.49.3

I want to have 1 left drawer and 1 right drawer on every page. I have made it working following the [API Docs](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md). What actually happens is that when i open my left drawer my right drawer also opens up on its own. So when i select a scene from the left drawer and navigate to the page , the right drawer closes instead of the left drawer (expected behavior : - the left drawer should get close).  And when i simply open the left drawer i could see the right drawer also opening up on its own. and if i close the left drawer , the right drawer is still open. Can you please help me with this? 
Scene code:
```
  <Scene key="root" hideNavBar>
    <Scene
      key="loggedIn"
      hideNavBar
      type={ActionConst.RESET}
    >

      <Scene
        key="drawerLeft"
        contentComponent={DrawerLeft}
        drawer={true}
        renderTitle={<Toolbar />}
        open={false}
      >
        <Scene
          key="drawerRight"
          contentComponent={DrawerRight}
          drawer={true}
          drawerPosition={'right'}
          open={false}
          >
          <Scene
            key="dashboard"
            component={Home}
            type={ActionConst.REPLACE}
            initial={true}
          />
           <Scene
            key="orders"
            type={ActionConst.REPLACE}
            component={Orders}
          />
         </Scene>
      </Scene>
    </Scene>
</Scene>
```

PS: Drawer left and Drawer right and simple react components.

**Comment by aksonov** [comment]
Two drawers probably are not supported yet by react-navigation. Please reopen once react-navigation provides support for both right/left drawers

**Comment by parthgandhi7** [comment]
Link to related react-navigation issue to keep track of the progress : [#780](https://github.com/react-community/react-navigation/issues/780)

**Comment by parthgandhi7** [comment]
Can you suggest me any kind of possible workaround or something for this?

**Comment by aksonov** [comment]
I don’t know exact workaround. Maybe try to use react-native-drawer ?

**Comment by parthgandhi7** [comment]
How to do that? i have custom drawer component with code as follows:

DrawerLeft.js
```
import React, { Component } from 'react';
import {View, Text } from 'react-native';
import { connect } from 'react-redux';
import Drawer from 'react-native-drawer';
import { Actions, DefaultRenderer } from 'react-native-router-flux';
import LeftDrawerContent from '../LeftDrawerContent';
import { openLeftDrawer, closeLeftDrawer } from '../../actions';

const mapStateToProps = (state) => ({
  isLeftDrawerOpen: state.global.isLeftDrawerOpen,
});

class DrawerLeft extends Component {

  onDrawerOpen = () => {
    const { dispatch } = this.props;
    dispatch(openLeftDrawer());
  }

  onDrawerClose = () => {
    const { dispatch } = this.props;
    dispatch(closeLeftDrawer());
  }

  render() {
    // const state = this.props.navigationState;
    // const children = state.children;
    // const state = this.props.navigation.state;
    // console.log("Drawer left askjdksjdk");
    // const children = state.routes || [];
    console.log("drawer left rendered");
    return (
      <Drawer
        ref={(ref) => { this.drawer = ref; }}
        open={this.props.isLeftDrawerOpen}
        onOpen={this.onDrawerOpen}
        onClose={this.onDrawerClose}
        type="overlay"
        elevation={4}
        content={<LeftDrawerContent navigator={this.navigator}/>}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        negotiatePan={true}
        acceptPan={true}
        panOpenMask={0.25}
        tweenHandler={(ratio) => ({
          main: { opacity: Math.max(0.2, 1 - ratio) },
        })}
      >
        {/* <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} /> */}
      </Drawer>
    );
  }
}

export default connect(mapStateToProps)(DrawerLeft);
```

How do i use this component in the scene code of react native router flux( as specified above)..

This used to work in older versions of router flux with 
```

      <Scene
        key="drawerLeft"
        component={DrawerLeft}
        open={false}
      >
```

But i am not sure how to do it in this version.Can you help me out?

- react-native-router-flux 4.0.0-beta.22
- react-native 0.49.3

**Comment by parthgandhi7** [comment]
Using this scene code: 
```
  <Scene key="root" hideNavBar>
    <Scene
      key="loggedIn"
      hideNavBar
      type={ActionConst.RESET}
    >
      <Scene
        key="drawerLeft"
        component={DrawerLeft}
        drawer={true}
        renderTitle={<Toolbar />}
        open={false}
      >
          <Scene
            key="dashboard"
            component={Home}
            type={ActionConst.REPLACE}
            initial={true}
          />
           <Scene
            key="orders"
            type={ActionConst.REPLACE}
            component={Orders}
          />
         </Scene>
      </Scene>
</Scene>
```
helps render my custom drawer component but it does not allow child components to be used . i.e. when i hit Actions.orders() , it says
`_reactNativeRouterFlux.Actions.orders is not a function`


Also this [documentation](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#scene) says that component props is not required while specifying nested components.

**Comment by parthgandhi7** [comment]
Anyone wanting to implement this thing with latest react navigation can try this work around which i implemented and is working perfectly fine. I implemented two drawers seperately. One with react-router-flux and the other drawer (right drawer) on each page using seperate drawer component (eg, drawer from native base , react-native-drawer etc.).
