### ISSUE TITLE
[BUG] navigation.setParams stopped working

### ISSUE THREAD

**Issue by EnriqueDev** [aksonov/react-native-router-flux#2509]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta22 (v3 is not supported)
- react-native v0.48

### Expected behaviour
Using the current react-navigation API you should be hable to call:

`this.props.navigation.setParams({ key: value })`

anywhere in the code, and set a parameter in the React-Navigation state.

### Actual behaviour
Parameter is never set.

### Steps to reproduce

    class MyAwesomeClass extends React.Component {
      static navigationOptions = ({ navigation }) => {
          headerRight: <TouchableIcon size={22} name="search" onPress={() =>    
                        navigation.state.params.handleIconTouch()} />,
       }

       componentWillMount() {
          this.props.navigation.setParams({ handleIconTouch:  this.handleIconTouch });
       }

       handleIconTouch = () => {
         console.log('Touched!');
       }

    }

**Comment by aksonov** [comment]
You are using react navigation API. Please use `Actions.refresh` or switch to react navigation.
