### ISSUE TITLE
Cannot read property 'dispatch' of undefined on componentDidMount

### ISSUE THREAD

**Issue by sibeliusseraphini** [aksonov/react-native-router-flux#251]
I am trying to create a Login screen that will go directly to another screen if the user is already authenticated.

```js
componentDidMount() {
    const { isAuthenticated, isFetching } = this.props.user;

    if (isAuthenticated && !isFetching) {
      Actions.tabbar(); // go to tabbar if is authenticated and is not fetching
    }
  }
```

I am getting the user from `AsyncStorage`, is there any work around to do the same behavior?

**Comment by aksonov** [comment]
Have you tried setTimeout(()=>Actions.tabbar()) ?

**Comment by sibeliusseraphini** [comment]
I've just removed this from componentDidMount, because I think it is not a good ideia anyway

thanks
