### ISSUE TITLE
Tabs child Scenes remounted after every tab navigation or Lightbox navigation

### ISSUE THREAD

**Issue by yopif** [aksonov/react-native-router-flux#2510]
### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.46

### Expected behaviour
In v4.0.0-beta.12 tabs Scenes were loaded only once and switching tabs didn't call constructor , componentWillMount or render functions in the Tabs child Scenes and I think it was the expected behaviour.

### Actual behaviour
I updated to v4.0.0-beta.22 to use Lightbox and now either switching tabs or navigating to the Lightbox overlay remounts the initial component

### Steps to reproduce
Here History and Orders are remounted every time I switch tabs using this.props.navigation.navigate('history' or 'orders')  :

                           `<Tabs
                                lazy={false}
                                key="tabs"
                                tabBarComponent={TabBar}
                                headerMode={'none'}
                                swipeEnabled={false}
                            >
                                <Scene
                                    key="orders"
                                    component={Orders}
                                    initial={true}
                                    title="Mes commandes"
                                    type={ActionConst.REPLACE}
                                />
                                <Scene
                                    key="history"
                                    component={History}
                                    title="Historique"
                                    type={ActionConst.REPLACE}
                                />
                            </Tabs>`

Here Orders is remounted after navigating to 'preparingProducts' using Actions.preparingProducts():

                     `<Lightbox key="main" hideNavBar>
                            <Tabs
                                lazy={false}
                                key="tabs"
                                tabBarComponent={TabBar}
                                headerMode={'none'}
                                swipeEnabled={false}
                            >
                                <Scene
                                    key="orders"
                                    component={Orders}
                                    initial={true}
                                    title="Mes commandes"
                                    type={ActionConst.REPLACE}
                                />
                                <Scene
                                    key="history"
                                    component={History}
                                    title="Historique"
                                    type={ActionConst.REPLACE}
                                />
                            </Tabs>
                            <Scene key="preparingProducts" component={PreparingProducts} type={ActionConst.PUSH} />
                        </Lightbox>`

**Comment by aksonov** [comment]
Could you try to fork & modify Example project to demonstrate the issue?
