### ISSUE TITLE
How can I make a decision when press the tabbar?

### ISSUE THREAD

**Issue by abellee** [aksonov/react-native-router-flux#2511]
I have four tabs, and when users was login, then it could goes into the second tab, if not, the login view will be prompted before the second scene shows up,
I do know I could do this by the onEnter, but if I do use this, before the login view is prompted,
the second view will show up in a second, that makes me not comfortable, so how can i do this?

**Comment by aksonov** [comment]
You may check https://github.com/aksonov/react-native-starter-app or try to ask this question at stackoverflow
