### ISSUE TITLE
How can I manipulate 2 different scenes on a single screen?

### ISSUE THREAD

**Issue by nahuelfederico** [aksonov/react-native-router-flux#2513]
Hello guys, Someone knows how to manipulate different 2 scenes on a single screen

This screen will have a main scene at the top (it contains a hamburguer and a search field(with  a input field))
and bellow  , it will have a second scene with two switchable tap-bars

I didn't find information about it , and I would like implement a abstraction between both scenes

In the following image,  you'll see an example of that screen

Thanks

![sss](https://user-images.githubusercontent.com/24900081/31638458-1cfc5b40-b2aa-11e7-8f3b-52ac408e53b1.PNG)

**Comment by catrieldapice** [comment]
+1

**Comment by onrige** [comment]
You can try to do it on only one `Scene` with your own custom tab bar (`tabBarComponent` property).

**Comment by EnriqueDev** [comment]
or you could use redux to fire events in your views...

**Comment by aksonov** [comment]
It is out of scope for this component. Use redux or mobx
