### ISSUE TITLE
Scene props are not changing when pressing onRight and calling Actions.refresh() 

### ISSUE THREAD

**Issue by manoelbo** [aksonov/react-native-router-flux#2514]
### Version

- react-native-router-flux 4.0.0-beta.22 
- react-native v0.49.3

### Expected behaviour

I expected to change my scene props pressing onRight and calling Actions.refresh() 

```
const RouterComponent = () => {
	return (
		<Router sceneStyle={{ backgroundColor: '#fff' }}>
			<Modal>
				<Scene tabs key="login" component={LoginForm} title="Login" />
				<Scene 
					tabs 
					key="clientList" 
					component={ClientList} 
					title="Clientes" 
					initial 
					/* renderRightButton={<SearchIcon onPress={() => this.onRigthButton.bind(this)} />} */
					navigationBarStyle={styles.navBarStyle}
					titleStyle={styles.titleStyle}
					navBarButtonColor={'#ffff'}
					rightButtonImage={require('./img/ic_search.png')}
					isSearchOpen={false}
					onRight={() => Actions.clientList({ type: ActionConst.REFRESH, hideNavBar: false })}
				/>
			</Modal>
		</Router>
	);
};
```
### Actual behaviour

`onRight={() => Actions.clientList({ type: ActionConst.REFRESH, hideNavBar: false })}`

or

`onRight={() => Actions.refresh({ hideNavBar: false })}`

Both doesn't change my props and doesn't re-render my component.

**Comment by aksonov** [comment]
hideNavBar dynamic changing is not yet supported, see #2492

**Comment by kallayyash** [comment]
navBarButtonColor={'#96c41c'}                 use this image button color
