### ISSUE TITLE
How to navigation through Props using onLogin, onSignUp, .....

### ISSUE THREAD

**Issue by TheRemjx01** [aksonov/react-native-router-flux#2516]
I plan to start my new project with RNRF and MobX and I found that your React native Starter Kit with MobX and RNRF v4 is suitable. 
However, I don't understand how could Navigation Event could pass through Scene Declaration:
`<Scene key="login" component={Login} type="reset" title="Login"
               onLogin="doAuth"
               onSignUp="signUp"
               onForgotPassword="passwordReset"/>`
I have tried in my project: add wrapBy={observer} to Router, declare onSubmit="keyOfOtherScene" . But when pass to component in Scene, it's only a normal string, not a function. 
Can you please guide or give me some documentation about it?

**Comment by aksonov** [comment]
You could check https://github.com/aksonov/react-native-starter-app
