### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by papsti7** [aksonov/react-native-router-flux#2517]
### Version
These are my dependencies:
"dependencies": {
		"firebase": "^4.5.0",
		"prop-types": "^15.6.0",
		"react": "^16.0.0",
		"react-native": "0.49.3",
		"react-native-router-flux": "^3.26.22",
		"react-native-router-redux": "^0.2.2",
		"react-redux": "^5.0.6",
		"redux": "^3.7.2",
		"redux-thunk": "^2.2.0"

I tested it with "react-native-router-flux": "^4" too, but same behaviour.

### Expected behaviour
Show component with router header.

### Actual behaviour
![simulator screen shot - iphone 6 - 2017-10-17 at 17 05 09](https://user-images.githubusercontent.com/11005451/31672618-57eb7aac-b35d-11e7-8099-5edfbb438d10.png)

Click on "<unknown> Scene.js:23:2" shows up this file:
<img width="845" alt="screen shot 2017-10-17 at 17 06 50" src="https://user-images.githubusercontent.com/11005451/31672726-984dcfa0-b35d-11e7-9e7d-d354b47e3694.png">
 
### Steps to reproduce
Codesnippet should explain enough:
`const RouterComponent = () => (
  <Router>
    <Scene key="login" component={LoginForm} tabTitle="Login" />
  </Router>
);`
PS: tested "tabTitle" and "title", but the error is the same.

**Comment by mvanroon** [comment]
try `Text.proptypes.string` instead of `PropTypes.string`

**Comment by papsti7** [comment]
When I try this, it is crashing in TabbedView: 
static propTypes = {
    navigationState: PropTypes.object.isRequired,
    renderScene: PropTypes.func.isRequired,
    style: View.propTypes.style,
  };

**Comment by papsti7** [comment]
@mvanroon Still there with react-native-router-flux@3.41.0. 
If I try Text.proptypes.string instead of PropTypes.string in Scene.js, it doesn't crash in TabbedView, but in NavigationContainer.js.

**Comment by papsti7** [comment]
It's working at version 3.41.0 after replace the deprecated `PropTypes` import from `React` to `prop-types` everywhere it crashes.

**Comment by mvanroon** [comment]
Try upgrading to v4.x and see if the issue still persists.
Please bear in mind that GitHub is not the place the ask questions about old versions of RNRF.
I recommend asking your question on stackoverflow.com. Make sure you add the react-native-router-flux label

**Comment by papsti7** [comment]
@mvanroon Ok, next time I'll ask it there. 
I upgraded to 4.0.0-beta.22, but then I got this error.
![simulator screen shot - iphone 6 - 2017-10-19 at 13 24 52](https://user-images.githubusercontent.com/11005451/31768728-f3504ee0-b4d0-11e7-95db-f0190d054382.png)

**Comment by mvanroon** [comment]
Post your problem on stackoverflow along with your code and I'll have a look.

@aksonov could you close this issue please?

**Comment by miuel** [comment]
Hello @papsti7 did you finally solve ? I have same problem in this versions: 
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-router-flux": "^3.35.0",

**Comment by mak12** [comment]
any update on this?
