### ISSUE TITLE
 The pages on your demo are not animating only from bottom to top on Android

### ISSUE THREAD

**Issue by bkniya** [aksonov/react-native-router-flux#2521]
"react-native-router-flux": "^4.0.0-beta.21"
    "react-native": "0.49.1"

After version 4 update, my page transition is not sideways anymore. It is from bottom to top only. I downloaded and tried on your demo, too and it is the same. The pages on your demo are not animating only from bottom to top. How c

an we fix that issue?

![bandicam-2017-10-19-12-33-34-584](https://user-images.githubusercontent.com/6282439/31764749-c8fa2d74-b4ca-11e7-905d-7e8f82a9cd4c.gif)

**Comment by aksonov** [comment]
Please check #2628
