### ISSUE TITLE
Actions.currentScene don't update on back button press

### ISSUE THREAD

**Issue by CarbonC** [aksonov/react-native-router-flux#2524]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native v0.49.3

### Expected behaviour
When navigating using the back button, Actions.currentScene update

### Actual behaviour

It doesn't update

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Log Actions.currentScene in componentWillMount
2. Navigate with push then with back button on android
3.

**Comment by aksonov** [comment]
As I understand componentWillMount is not re-called for pop() call (React lifecycle)
