### ISSUE TITLE
[bug/question HOWTO] Transition from TabBar (without NavBar) to scene with NavBar

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2527]
Hello! @aksonov 
Thank you so much for V4!
Trying to migrate to it again.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0 beta-22
- react-native v0.50-rc

### Expected behaviour

When transition from Scene in TabBar (without NavBar) to scene with NavBar 
It should not add NavBar to previous scene without NavBar

### Actual behaviour

I recorded video:

![rnflux4_bug_with_transition](https://user-images.githubusercontent.com/11584712/31850703-ae888364-b65f-11e7-99f2-873a8476d667.gif)

As you see when I go to scene with NavBar it pushes content of TabBar down.
When I go back - it pushes content up.
Looks jerky.

If I add hideNavBar={false} to TabBar I see 2 NavBars in TabBar.
This way there will be no "push content up-down" since NavBar always be present.
![screen shot 2017-10-21 at 12 49 09](https://user-images.githubusercontent.com/11584712/31850698-7d9a40d0-b65f-11e7-90f5-7007a003d146.png)

Is there a way to remove backButton from appear NavBar, add there title and remove 2nd NabBar?

Or what's proper way to fix this?

**Comment by kesha-antonov** [comment]
Answer.

Just add ```hideNavBar={true}``` to ```<Tabs>``` component.

**Comment by kesha-antonov** [comment]
Solved it by position NavBars absolute.
Not sure if there's another way but it works.

**Comment by redwind** [comment]
@kesha-antonov kesha: i faced same issue, it work like this
[https://user-images.githubusercontent.com/2396817/28237172-bc125be0-696b-11e7-927e-850c713a173f.gif](url)
How did you set navbar position absolute to resolve it ?
thanks !!

**Comment by kesha-antonov** [comment]
```
<Tabs tabBarStyle={{position: 'absolute', top: 0, left: 0, right: 0}}
```
@redwind
