### ISSUE TITLE
Usage of NON-static onEnter / onExit within component replacing componentDidMount / componentDidUnmount

### ISSUE THREAD

**Issue by TeslaMotors91** [aksonov/react-native-router-flux#2528]
### Version
- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native v0.48.4

### Expected behaviour
`onEnter ( )` / `onExit ( )` use as a non-static type.

### Actual behaviour
static onEnter / onExit is functional but cannot access `this.<object>` within the class Component.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Obvious bug, forking not needed.
2.
3.

**Comment by TeslaMotors91** [comment]
Bye bye react-native-router-flux and Hello react-native-navigation :l

**Comment by aksonov** [comment]
It is not supported. You can access class Component by using Actions.refs.SCENE_NAME as stated in docs.
