### ISSUE TITLE
[Bug] ComponentWillMount/DidMount/WillUnmount fires after Actions.pop()

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2531]
Hello!

After migrating from v3 to v4 I see this problem:

When push 3 scenes to stack and then go back with ```Actions.pop()``` 3 times lifecycle methods will be called on same components again after unmount.

My guess that is component will get remounted and then immedeately unmounted.

```
componentWillMount
index.ios.bundle?platform=ios&dev=true&minify=false:164287 componentDidMount
index.ios.bundle?platform=ios&dev=true&minify=false:164298 componentDidUpdate
index.ios.bundle?platform=ios&dev=true&minify=false:164298 componentDidUpdate
index.ios.bundle?platform=ios&dev=true&minify=false:164298 componentDidUpdate
index.ios.bundle?platform=ios&dev=true&minify=false:164308 componentWillUnmount
index.ios.bundle?platform=ios&dev=true&minify=false:164279 componentWillMount
index.ios.bundle?platform=ios&dev=true&minify=false:164287 componentDidMount
index.ios.bundle?platform=ios&dev=true&minify=false:164308 componentWillUnmount
```

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta22
- react-native v0.50-rc

### Expected behaviour

Components lifecycle methods called again ```ComponentWillMount/DidMount/WillUnmount```

### Actual behaviour

Should not call lifecycle methods after unmount.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Go to 3 scenes deep
2. Call programmatically 
```
for ( let x in new Array(3).fill() ) {
  await Actions.pop();
}
```
3. See problem in console

**Comment by daviscabral** [comment]
Are these nested `same` Scenes? Cause `react` 16 talks about something that might be related to this (out of order calls).

> Component Lifecycle
>
> Since React prioritizes the rendering, you are no longer guaranteed componentWillUpdate and shouldComponentUpdate of different components will fire in a predictable order. The React team is working to provide an upgrade path for apps that would break from this behavior.
Source: https://edgecoders.com/react-16-features-and-fiber-explanation-e779544bb1b7

**Comment by kesha-antonov** [comment]
@daviscabral Hello!

When I do ```Actions.pop``` components that should just unmount will unmount and remount and unmount again. I don't think it's React related

**Comment by daviscabral** [comment]
I see. Are you using `redux`? I am asking to see if Is there any way to track the page actions.

**Comment by kesha-antonov** [comment]
@daviscabral I use mobx.

@aksonov Thank you for looking at it. I'll provide an example.

I have 
```
<View>
  <Router ...>
    {this.scenes()}
  </Router>
   ...other Components
</View>
```

**Comment by kesha-antonov** [comment]
Ok. Solved it with other way
Closing for now

**Comment by kesha-antonov** [comment]
It's definitely something wrong @aksonov 
Because when I call ```Actions.tabbar({ type: ActionConst.RESET })```
(see https://github.com/aksonov/react-native-router-flux/issues/2595)

it remounts ```signIn``` scene twice. I think this is also cause of this error: ```Could not locate shadow view with tag #122, this is probably caused by a temporary inconsistency between native views and shadow views.```


![screen shot 2017-11-05 at 18 28 24](https://user-images.githubusercontent.com/11584712/32416229-32cc90c2-c257-11e7-954e-c438707b8f89.png)

**Comment by aksonov** [comment]
Now try to do the same with pure react-navigation and check results. RNRF doesn't do almost any rendering.

**Comment by kesha-antonov** [comment]
Maybe related https://github.com/react-community/react-navigation/issues/2599

**Comment by kesha-antonov** [comment]
Ok. Maybe it's my app related.

I found out that my App and Router re-renders after sign in.

![screen shot 2017-11-05 at 19 16 27](https://user-images.githubusercontent.com/11584712/32416660-dc422ed6-c25d-11e7-9d13-5d405f00195a.png)

What's be best way to solve it?
If you need to re-render component with Router. But not Router itself @aksonov

**Comment by kesha-antonov** [comment]
Ok. Rewrote without re-render
Same errors

**Comment by kesha-antonov** [comment]
When I disabled ```Actions.refresh``` on scene where I go from ```signIn``` errors disappear. SignIn will unmount and not errors/warnings.

**Comment by kesha-antonov** [comment]
Wrapping ```Actions.refresh``` in ````InteractionManager.runAfterInteractions``` helped. No errors/warnings

So I think they appear if ```Actions.refresh``` called on new scene when previous is not unmounted yet. What do you think? @aksonov 

Ref: https://github.com/react-community/react-navigation/issues/2702

**Comment by aksonov** [comment]
It looks very useful, could you submit PR?

**Comment by kesha-antonov** [comment]
> Wrapping Actions.refresh in ```InteractionManager.runAfterInteractions``` helped. No errors/warnings

This is bad idea. If you're talking about this.

Need to detect that prev scene is unmounted and if not skip ```setProps``` in ```Actions.refresh```

**Comment by aksonov** [comment]
Have you tried just to wrap it with `setTimeout` ?

**Comment by kesha-antonov** [comment]
No. Now I track it in mobx store

Good suggestion

**Comment by kesha-antonov** [comment]
@aksonov 
Yes. ```setTimeout``` works

**Comment by kesha-antonov** [comment]
But if I use
```
refresh = (data) => {
    const key = getActiveState(this._state).key;
    const params = filterParam(data);
    setTimeout(() => {
      this.dispatch(NavigationActions.setParams({ key, params }));
    })
  };
```
for all scenes I see delay of rendering title, navbar buttons.

**Comment by kesha-antonov** [comment]
So this is what is going on:

```Actions.tabbar({ type: 'reset', ... })```

1. Blur current scene_1
2. Focus next scene_2
3. ```componentDidMount``` in ```scene_2```
3. Call ```Actions.refresh```
4. Since ```scene_1``` is not unmounted yet ```setParams``` is called on that scene
5. ```componentWillUnmount```, ```componentDidMount```, ```componentWillUnmount``` called on scene_1

**Comment by kesha-antonov** [comment]
Related https://github.com/react-community/react-navigation/issues/2931

**Comment by aksonov** [comment]
@kesha-antonov It is interesting. We could easily modify our Reducer and process SET_PARAMS by RNRF (not to forward to RN). Could you try  @gaodeng receipt?

**Comment by kesha-antonov** [comment]
Tried but didn't understand RNRF code.
Can you please help try adapt that code? @aksonov

**Comment by aksonov** [comment]
Sorry, don't have time. You may check Reducer.js and its code. For many actions it just forward requests to `navigationStore.router.getStateForAction`. You may add own `if else` block for REFRESH action (and remove it from `supportedActions` map)

**Comment by kesha-antonov** [comment]
Ok. Thanks! I'll find solution.

**Comment by msageryd** [comment]
@kesha-antonov Did you find any solution? 

I'll probably have to go back to beta 12 (problems came when I upgraded to beta 17), but it would be really great with a solution instead of backing down to older version.

**Comment by aksonov** [comment]
Closed because it is not related to RNRF.

**Comment by xiaoxiaoyongPersonal** [comment]
i have the same problem,use Actions.pop({refresh: {update: new Date()}})。what i should do

**Comment by fadlykayo** [comment]
@kesha-antonov hi, do you found any solution for this? my current workaround is by adding `setTimeout(() => { Actions.home(), 0);`. But it still give me flicker effect.

**Comment by kesha-antonov** [comment]
Hello @fadlykayo ! I've migrated to react-navigation today
