### ISSUE TITLE
Action.pop() throws error when hideTabBar=true in the scene

### ISSUE THREAD

**Issue by Aqueelmiq** [aksonov/react-native-router-flux#2533]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.46.1

Using <Tabs> for Tab Navigation for App
**I use hideTabBar = true for one of the tabs** 
I have a close button in that particular tab scene
I use Actions.pop() in the onPress handler for the button

### Expected behavior

When I press the close button, the scene is popped, the previous tab is open

### Actual behavior

App crashes with the error message: undefined is not an object, evaluating '_this24.componen.setNativeProps'

callback
in AnimatedImplementation.js 1796:28

### Steps to reproduce

Create a simple Tab based App
```
 <Router>
                <Scene>
                    <Tabs key="main" showLabel={false} tabBarStyle={{backgroundColor: '#fff'}}>
                        <Stack key="home" title="Home" icon={TabIcon} initial={true}>
                            <Scene key="homeView" component={HomeScene} title="Home" />
                        </Stack>
                        <Stack key="search" title="Search" icon={TabIcon}>
                            <Scene key="mapView" component={SearchScene} initial={true} title="Map" />
                        </Stack>
                        <Stack key="post" title="Post" icon={TabIcon} hideTabBar={true}>
                            <Scene key="postView" component={PostScene} initial={true} title="Post"/>
                        </Stack>
                    </Tabs>
                </Scene>
</Router>
```

Create close button on the screen where hideTabBar={true}
in the onPress handler, do Actions.pop()

You can also do the same for another screen without sidebar to see the difference

Run the simulator
Go to the tab with hideTabBar = true, click on the close button you created.
The error will show up.

**Comment by daviscabral** [comment]
I am not able to reproduce it here with the `Example` project. It might be related to other package or setting in your project.

[![https://gyazo.com/91be31317e1fe251c20d234bd557361a](https://i.gyazo.com/91be31317e1fe251c20d234bd557361a.gif)](https://gyazo.com/91be31317e1fe251c20d234bd557361a)

You can check the code I used in the `Example` folder here: https://github.com/daviscabral/react-native-router-flux/tree/issue-2533-sample/Example

**Comment by aksonov** [comment]
Closed due inactivity (thanks @daviscabral for checking)
