### ISSUE TITLE
  componentWillReceiveProps() and shouldComponentUpdate() not working with android

### ISSUE THREAD

**Issue by prawee** [aksonov/react-native-router-flux#2534]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.48

### Expected behaviour
android and ios should be call  shouldComponentUpdate()

### Actual behaviour
shouldComponentUpdate() is working with ios
but not working on android

**Comment by onrige** [comment]
Could you give more info about this? I also use this versions on both and I don't have such problems with `shouldComponentUpdate()`.

**Comment by aksonov** [comment]
Closed due inactivity
