### ISSUE TITLE
Unexpected margin/padding on the top of the page

### ISSUE THREAD

**Issue by rahulmishra-goibibo** [aksonov/react-native-router-flux#2536]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour
No margin on the top of the page and page must start just below the status bar of the ios device

### Actual behaviour
A margin of approx 40-50 pixel appears unexpectedly even after removing all/any styling on the component

I have connected react native router flux with redux and just connected a simple page with it and the margins appear on the out of nowhere on the top of the page. Is there any extra parameter to be added by me to avoid that or did i miss something. Adding code snippet for the above and also the rough look of what i mean to show

Any help would be appreciated and do let me know if i need to give some more information. Thanks in advance!
```
const RouterWithRedux = connect()(Router);  
<RouterWithRedux>
    <Scene key="root">
        <Scene key="SignUp"  initial>
          <Scene key="signup" component={SignUp} title="SignUp" />
        </Scene>
      </Scene>
      </RouterWithRedux>
```

![simulator screen shot 23-oct-2017 3 46 22 pm](https://user-images.githubusercontent.com/20772089/31884034-76286fe2-b809-11e7-9e41-fb1acf9cdf79.png)

**Comment by rahulmishra-goibibo** [comment]
```
const RouterWithRedux = connect()(Router);  
<RouterWithRedux>
    <Scene key="root">
        <Scene key="SignUp"  initial>
          <Scene key="signup" component={SignUp} title="SignUp" />
        </Scene>
      </Scene>
      </RouterWithRedux>
```

**Comment by onrige** [comment]
It happens because any new parent will create his own NavBar. So all you need is just add `hideNavBar`.

**Comment by rahulmishra-goibibo** [comment]
@onrige Thanks for your quick reply. It worked
