### ISSUE TITLE
Cannot read property 'props' of null

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2539]
This is not really a bug, but something that would be nice to have.

I'm using environment configurations. We have some features that are not ready for release and I'm just hiding the scenes. 

my code would look like this:
```
let users = <Scene .... />
if(config.hide_incomplete_features){
users = null
}

<Tabs ...>
<tab ...>
<tab2 ..>
{users}
</Tabs>
```

When I do that I get a "Cannot read property 'props' of null" from the navigationStore. I think that we should check if the scene is null and just return early in the function?

Right now what I ended up doing is - defining the whole tabs once. and then redefining them again without the scene. this way my null scene doesn't trigger the error

**Comment by daviscabral** [comment]
Can you provide these informations below? 

### Version
Tell us which versions you are using: 

- react-native-router-flux v?.?,?
- react-native v0.?.?

Also more data about the error.

**Comment by aksonov** [comment]
Sorry, it is not supported
