### ISSUE TITLE
Pop scene from stack on tab change

### ISSUE THREAD

**Issue by rudyryk** [aksonov/react-native-router-flux#2543]
Is it possible to pop scene from stack on tab change? Not clear from docs.

We have such structure:

- Tab1
   - Scene1-1
   - Scene1-2
- Tab2

Consider we are here `Tab1` -> `Scene1-1` -> `Scene1-2`, I'd want to pop `Scene1-2` on switching from `Tab1` **manually, in some cases**. Is that possible?

I tried `onExit={() => Actions.pop()}` for `Scene1-2` but it is ambiguous (what exactly to pop, from which tab?) and finally not working.

Also there's a property `backToInitial` that will always reset `Tab1` to first sub-scene but it won't work in our case. For example `Scene1-2` could be Camera screen - and may be in recording state (then not popped) or idle state (then popped).

### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.22
- react-native v0.47.1

**Comment by onrige** [comment]
Your case is not the default so you can provide your own tab icon press logic by `tabBarIconPress` property. Have a look at this one for example: https://github.com/aksonov/react-native-router-flux/blob/master/src/navigationStore.js#L227

**Comment by rudyryk** [comment]
@onrige Actually as I now understand it can be handled with generic thing. Is it possible to change stack state inside [not current] tab programmatically? In other words, how to "navigate" to scene inside tab without really switching to that scene?

**Comment by onrige** [comment]
I can't answer on your question, sorry. I am not sure that this is possible in React Navigation.

**Comment by rudyryk** [comment]
@onrige Thank you for the hint! Seem like React Navigation has Reset feature for such scenarios: https://reactnavigation.org/docs/navigators/navigation-actions#Reset - so we could produce arbitrary navigation state if I understand correctly. But I can's find such kind of stuff in router flux.

**Comment by onrige** [comment]
What about `Actions.reset`? 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions
