### ISSUE TITLE
Support for both Transparent Scenes and bottom-to-top animation

### ISSUE THREAD

**Issue by thecachedbyte** [aksonov/react-native-router-flux#2545]
- react-native-router-flux "^4.0.0-beta.22"
- react-native "^0.49.3"

Need support for transparency of the background for some of the scenes and for some scene need support of direction vertical (bottom-to-top animation).

As per documentation to have transparency support we can use Lightbox and for bottom-to-top animation Modal can be used. 

Any workaround to get both the feature?

**Comment by thecachedbyte** [comment]
With 3.x version i was able to achieve these requirements. By passing style via getSceneStyle. I used createReducer hook to have a onEnter kind of life cycle.

const getSceneStyle = (prop) => {
  if (**prop.scene.navigationState.overlay**) {
    return {
      backgroundColor: 'transparent',
      transform: [],
      opacity: 1
    };
  }
  return {};
};

const AppRouter = () => (
  <Router
    getSceneStyle={getSceneStyle}
    createReducer={(params) => {
      const defaultReducer = Reducer(params);
      return (state, action) => {
        _// this is how i was able to have a onEnter kind of event lifecycle_
        if (action.scene && action.type === ActionConst.FOCUS && action.scene.component) {
          const targetComponent = action.scene.component;
          if (targetComponent.onScreenVisible) {
            targetComponent.onScreenVisible(action.scene);
          }
        }
        return defaultReducer(state, action);
      };
    }}
  >
    _// normal scenes_
    <Scene key="hotels" component={Home} initial />

    _// scenes with bottom-to-top animation_
    <Scene key="filter" direction="vertical" component={Filter} />
    
    _// scenes with transparent background (overlay)_
    <Scene **overlay animationStyle={{}}** key="error" component={ErrorToast} />
  </Router>
);

**Comment by aksonov** [comment]
Probably you should use Lightbox for this - atleast some other guys solved similar problems with lightbox.
