### ISSUE TITLE
Unable to disable tab bar item

### ISSUE THREAD

**Issue by rasikapunde** [aksonov/react-native-router-flux#2547]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.48.4

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment]
It is not supported (by both RNRF and react-navigation)
