### ISSUE TITLE
How to refresh already opened scene below the Drawer View from the Drawer View buttons

### ISSUE THREAD

**Issue by amitbravo** [aksonov/react-native-router-flux#2549]
### Version

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.4

### Expected behaviour
Clicking on buttons from Drawer View/menu should change parameter or refresh opened scene where both buttons points to same opened scene.

### Actual behaviour

I have few(two right now) buttons in drawerview.js e.g. about us , contact us , they should open one same secene which is custompage , at custompage according to ID new data is fetched and title should be changed so that for many pages I do not need write hardcoded but just one custompage scene is good to go .  

Drawer.js important code below  

```
toCusTomPageContact() {
console.log('comparestring',Actions.currentScene);
Actions.custompage({id: Constants.CustomPages.contact_id, title: Languages.contact});
}
toCusTomPageAboutUs() {
Actions.custompage({id: Constants.CustomPages.aboutus_id, title: Languages.aboutus});
}
From Render() function :
<ListItem key="aboutus" title="About Us" hideChevron={true} titleStyle={{ color: '#FFFFFF', fontSize: 16 }} onPress={this.toCusTomPageAboutUs.bind(this)} />
<ListItem key="contact" title="Contact" hideChevron={true} titleStyle={{ color: '#FFFFFF', fontSize: 16 }} onPress={this.toCusTomPageContact.bind(this)} />
```

If I am not on custompage scene and click on aboutus or contact us page  then , it reflects aboutus/contactus title and ID pretty good but if custompage is already opened and I click on any of these clicks , nothing changed , not even incoming properties are changed , simply drawer hides aways .

custompage.js important code : 

```
export default class CustomPage extends Component {
	constructor(props) {
		super(props);
		this.state = {
			html: '',
			page_id: this.props.id,
			page_title: this.props.title
		}
	}
componentWillMount(){
			const htmldata = this.fetchData(this.state.page_id);
}
render() {
		return (
			<ScrollView>
				<Text>{this.state.page_id} {this.state.page_title}</Text>
				<WebView html={this.state.html}/>
</ScrollView>
		)
	}
}
```

Actions.refresh is not working in this case as Actions.refresh refresh Drawer View  not the custompage

**Comment by aksonov** [comment]
Please reproduce the issue with forked & modified Example project.
