### ISSUE TITLE
Navigation between scenes of different tabs renders scene twice

### ISSUE THREAD

**Issue by iuraya** [aksonov/react-native-router-flux#2550]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.1

I have the following structure:

```javascript
<Router>
	<Stack key="root" >
		<Drawer key="drawer" type={ActionConst.RESET} >
			<Tabs key="tabBar" tabs >
				<Stack key="tabA" >
					<Scene key="a1" component={a1Component} />
					<Scene key="a2" component={a2Component} hideTabBar back />
					<Scene key="a3" component={a3Component} hideTabBar back />
				</Stack>
				<Stack key="tabB" >
					<Scene key="b1" component={b1Component} />
				</Stack>
			</Tabs>
		</Drawer>
	</Stack>
</Router>
```

I want to navigate from b1 directly to a3.

I have tried ```javascript Actions.replace('RequestList') ``` but the scene a3 gets rendered twice and the tabBar disappears

Is it possible to do this navigation?

**Comment by alexwasner** [comment]
Guessing this is also related to #2651

**Comment by aksonov** [comment]
Could you reproduce the issue with forked & modified Example project?
