### ISSUE TITLE
Jump when transitioning from scene with NavBar to one without

### ISSUE THREAD

**Issue by mxmtsk** [aksonov/react-native-router-flux#2552]
### Version
- react-native-router-flux dev-master
- react-native v0.49.3

### Expected behaviour
It should be a smooth transition (smooth slide up) or just stay where it is on the previous scene

### Actual behaviour
You can see how the NavBar get's removed. Just doesn't look super smooth as one would except from a good iOS app.

![jump](https://user-images.githubusercontent.com/4848184/32064593-8e458b50-ba7a-11e7-8435-855d3db0d091.gif)

### Steps to reproduce
Create two scenes, one with NavBar and one without NavBar. transition to the one with to the one without.

**Comment by Frexuz** [comment]
Exactly the same problem here. Can't understand the reason why the bar must be displayed while dragging back.

![2017-11-03 13 55 42](https://user-images.githubusercontent.com/49692/32361807-c88d6d76-c09e-11e7-8070-f6a1a85b2f25.gif)

**Comment by mcatmos** [comment]
+ 1

**Comment by igorarkhipenko** [comment]
Seems like this issue is related to react-navigation package. But it's unbelievable there's not any workaround with that. Did someone solve this problem?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by godofmadness** [comment]
So, any resolution to this issue?

**Comment by xuho** [comment]
Have same issue :(

**Comment by xuho** [comment]
@mxmtsk did you fixed this issue?
