### ISSUE TITLE
remove the shadow in android navBar

### ISSUE THREAD

**Issue by Timson020** [aksonov/react-native-router-flux#2554]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native v0.47.2

**Comment by onrige** [comment]
You can just open inspector and look at current styles for NavBar. All you need is to set `elevation` property to `0` in NavBar styles.

**Comment by Timson020** [comment]
@onrige thank
the shadow is remove
but the border for bottom is no remove
my code like it 
```
const normalNav = { navigationBarStyle: { backgroundColor: Utils.themeColor, borderBottomWidth: 0, elevation: 0 } }
...

<Scene key="root" headerMode="screen" titleStyle={{ color: 'white' }} {...normalNav} {...hidenBack}>
```
is not work

**Comment by aksonov** [comment]
Can't reproduce it with latest RNRF
