### ISSUE TITLE
Actions key being called but nothing happend

### ISSUE THREAD

**Issue by rahmanmarija** [aksonov/react-native-router-flux#2555]
I'm using v3.40.1.

In the error part of axios interceptor I expect when I get for example 403 (refresh token has expired) to use Actions.sceneName() and to be rerouted to home page where user can login and get new tokens. Right now when I get to point where this Actions.sceneName() is being called in debug mode it just step over and scene is not being change and I get white screen. Can someone help me with this issue or point me where might be error?

**Comment by daviscabral** [comment]
Are you using redux-saga? You will probably yield call/put or dispatch this action to have it working.

**Comment by rahmanmarija** [comment]
Yes, I've already tried that but nothing happens. Action is dispatched and called but no rerouting to the login screen.

**Comment by daviscabral** [comment]
Do you mind showing me some code of how are you calling it inside your saga?
