### ISSUE TITLE
Actions.key() not working (v4) and goes to catch()

### ISSUE THREAD

**Issue by archito2** [aksonov/react-native-router-flux#2556]
### Version
Tell us which versions you are using: 

- react-native-router-flux: ^4.0.0-beta.22
- react-native 0.49.3

### Expected behaviour
Navigate to next page on Actions.key()

### Actual behaviour
It isn't navigating to the next page. Stays put on the same Login page and as a result Firebase auth fails runs despite successful login. 

Sharing the necessary LOC
Router.js
```
`<Router>
	<Stack key='root'>
		 <Scene key='login' component={LoginForm} title='Please Login' />
		<Scene key='test' component={EmployeeList} title='Employee List' />
	</Stack>
</Router>`
```

Action Creator- On login success
```
`const loginUserSuccess = (dispatch, user) => {
	dispatch({ type: LOGIN_USER_SUCCESS, payload: user });	
	debugger;
	Actions.test();
};`
```

No navigation happens on button press. When i debugged and stepped into next function after Action.test() it goes to catch section, i presume an error is being caught straight away.

![image](https://user-images.githubusercontent.com/26257898/32133871-1d241466-bbfe-11e7-8109-0db7fcdd1c69.png)

**Comment by Rarer** [comment]
When i try something similar, it crashes the app, and comes with the error:
undefined is not a function (evaluating '_reactNativeRouterFlux.Actions.test')

**Comment by wbattel4607** [comment]
I'm having the same issue with:

react-native-router-flux: ^4.0.0-beta.23
react-native 0.50.3

**Comment by Rarer** [comment]
@wbattel4607 so you got it to work?

**Comment by Tahir-Bitsol** [comment]
i'm also facing the same issue. No navigation happens on button press, but it is working in screen life cycle methods like componetDidMount() and ComponentWillReceiveProps()..

react-native-router-flux: '4.0.0-beta.23'
react-native: '0.48.4'

any solution ?

**Comment by Tahir-Bitsol** [comment]
@aksonov can you help us here please ??

**Comment by aksonov** [comment]
It is more question for stackoverflow, not for github. Anyway it could happen only in one case - Actions.key is called before actions are created.

**Comment by wbattel4607** [comment]
@Rarer Yes, but the problem wasn't related to this package. Something weird was going on with my react-native-fbsdk authentication setup after I updated React Native.

**Comment by Tahir-Bitsol** [comment]
@aksonov  thanks for your review .
It navigates on login success from login screen to landing screen, but nothing happens when i tries to go on nested screen on button click.

**Comment by aksonov** [comment]
Please reproduce this issue with Example project.

**Comment by dannyk08** [comment]
Running into the same problem.. my app spikes the CPU when I click on a "link",
Theres a warning along the lines of "no memory left"
I've tried downgrading versions , clearing cache, reinstalling , restarting my laptop, another version of expo... nothing works 
```
these are my deps
"react": "^16.0.0",
"react-native": "^0.49.3",
"react-native-router-flux": "^4.0.0-beta.24",
```
this is a [file](https://github.com/dannyk08/kale/blob/f0a4abe9dcb95f1645a83ce615c84ae57d80b2ec/app/components/core/routes.component.js) in my develop branch

I've stuck for 2 days with this problem. nothing seems to let the routes work

**Comment by aksonov** [comment]
Closed because it is not related to RNRF - I can't reproduce it with Example project.
