### ISSUE TITLE
[Question] Navbar is pushed as well when changing tabs

### ISSUE THREAD

**Issue by damathryx** [aksonov/react-native-router-flux#2557]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native v0.49.5

I tried the Example folder and noticed that the navbar is pushed as well when you change tabs.
![routerflux](https://user-images.githubusercontent.com/14576761/32142640-36f16a8c-bcd6-11e7-8929-3afd931db8a4.gif)

Is it possible to reproduce the behavior of navbar and tabs of v3 on v4?

**Comment by onrige** [comment]
It happens because the fourth tab doesn't have his own NavBar definitely. If my memory serves me the same was in v3.

**Comment by aksonov** [comment]
It is default behaviour of react-navigation.
