### ISSUE TITLE
Not receiving props when click on button and duplicated Actions

### ISSUE THREAD

**Issue by SoldierCorp** [aksonov/react-native-router-flux#2558]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native v0.49.5

### Expected behaviour

Receive the props I'm sending in the component

### Actual behaviour

I'm sending data using this format

`
<TouchableOpacity
          key={business.id}
          onPress={() => Actions.business({
            data: business,
            id: business.id,
            title: business.name
          })}
          style={styles.btnBusiness}
        >
....
</TouchableOpacity>
`

and this is my route

`
<Scene
            key='business'
            component={Business}
            getTitle={props.title}
            navigationBarStyle={navBar}
            titleStyle={titleStyle}
            navBarButtonColor='#FFF'
            type={ActionConst.PUSH}
            passProps={true}
          />
`

But I am not receiving those props, do you know why?

**Comment by SoldierCorp** [comment]
I just realised when I pressed on that button, it's entering twice in the `business` route but I don't know why.

![image](https://user-images.githubusercontent.com/1775881/32149815-61dfc17e-bcd8-11e7-82b3-f79ec1ff1e56.png)

This my `Routes.js` file

The Drawer is not being used for the splash and the signup screens.

>      
        import React from 'react';
        import {
          StyleSheet
        } from 'react-native';
        import { Actions, Stack, Scene, Router, ActionConst, Reducer, Tabs, Drawer } from 'react-native-router-flux';

        //Components
        import Splash from './components/Splash';
        import SignUp from './components/SignUp';

        import Filter from './components/Filter';

        import Contact from './components/Contact';
        import Tutorial from './components/Tutorial';
        import Gifts from './components/Gifts';
        import MyGifts from './components/MyGifts';

        import Team from './components/Team';

        import BusinessList from './components/BusinessList';
        import Business from './components/Business';
        import Featured from './components/Featured';
        import Events from './components/Events';

        import SideMenu from './components/SideMenu';


        import TabIcon from './components/TabIcon';

        const RouterComponent = (props) => {

          console.log('ROUTER PROPS', props);

          const reducerCreate = params => {
            const defaultReducer = new Reducer(params);
            return (state, action) => {
              console.log('ACTION:', action);
              return defaultReducer(state, action);
            };
          };

          const {
            navBar,
            titleStyle,
            filterTextStyle
          } = styles;

          return(
            <Router createReducer={reducerCreate}>
              <Stack key='main'>
                <Scene key='splash' hideNavBar='true' component={Splash} type={ActionConst.REPLACE} />
                <Scene key='signup' hideNavBar='true' component={SignUp} type={ActionConst.REPLACE} />

                <Drawer
                  hideNavBar
                  key='drawer'
                  contentComponent={SideMenu}
                  drawerImage={require('./assets/images/icons/menu_trigger.png')}
                  drawerWidth={300}
                  type={ActionConst.REPLACE}
                >
                  {/* Home Tabs */}

                  <Tabs
                    key='home'
                    tabs
                    tabBarStyle={styles.tabBarStyle}
                    hideNavBar='true'
                    showLabel={false}
                    tabBarPosition='bottom'
                    titleStyle={titleStyle}
                    navigationBarStyle={navBar}
                    onRight={() => Actions.filter()}
                    rightButtonTextStyle={filterTextStyle}
                    hideBackImage={true}
                    leftButtonImage={require('./assets/images/icons/menu_trigger.png')}
                    rightButtonImage={require('./assets/images/icons/filter_icon.png')}
                    activeBackgroundColor='#262a62'
                    inactiveBackgroundColor='#444881'
                    lazy
                  >
                    <Scene
                      key='list'
                      component={BusinessList}
                      icon={TabIcon}
                      type={ActionConst.REPLACE}
                      title='🏬 Negocios'
                    />
                    <Scene
                      key='featured'
                      component={Featured}
                      title='♥ Destacados'
                      icon={TabIcon}
                      type={ActionConst.PUSH}
                      passProps={true}
                    />
                    <Scene
                      key='events'
                      component={Events}
                      title='🎉 Eventos'
                      type={ActionConst.PUSH}
                      icon={TabIcon}
                      passProps={true}
                    />
                  </Tabs>

                  <Scene
                    key='business'
                    component={Business}
                    getTitle={props.title}
                    navigationBarStyle={navBar}
                    titleStyle={titleStyle}
                    navBarButtonColor='#FFF'
                    type={ActionConst.PUSH}
                    passProps={true}
                  />

                  <Scene key='contact' hideNavBar='true' backTitle={'Regresar'} component={Contact} passProps={true} type={ActionConst.REPLACE} />
                  <Scene key='tutorial' hideNavBar='true' backTitle={'Regresar'} component={Tutorial} passProps={true} type={ActionConst.REPLACE} />
                  <Scene key='filter' component={Filter} type={ActionConst.PUSH} passProps={true} navigationBarStyle={navBar}
                    title={'Filtros de búsqueda'}
                    titleStyle={titleStyle}
                    leftButtonImage={require('./assets/images/icons/close_icon.png')}
                    onLeft={Actions.pop}
                  />
                  <Scene key='team' hideNavBar='true' backTitle={'Regresar'} component={Team} passProps={true} type={ActionConst.REPLACE} />



                  {/* Gifts Tabs */}

                  <Tabs
                    key='gifts'
                    tabs
                    tabBarStyle={styles.tabBarStyle}
                    hideNavBar='true'
                    showLabel={false}
                    tabBarPosition='bottom'
                    titleStyle={titleStyle}
                    navigationBarStyle={navBar}
                    onLeft={props.openSideMenu}
                    hideBackImage={true}
                    leftButtonImage={require('./assets/images/icons/menu_trigger.png')}
                    activeBackgroundColor='#262a62'
                    inactiveBackgroundColor='#444881'
                    lazy
                  >
                    <Scene
                      key='allgifts'
                      component={Gifts}
                      icon={TabIcon}
                      type={ActionConst.REPLACE}
                      title='🎁 Regalos disponibles'
                    />
                    <Scene
                      key='mygifts'
                      component={MyGifts}
                      title='🎁 Mis regalos'
                      icon={TabIcon}
                      passProps={true}
                    />
                  </Tabs>
                </Drawer>
              </Stack>
            </Router>
          );
        };

**Comment by omeraplak** [comment]
I have same issue but i found temp solution.
I suggest try this;
Add Scene under drawer.

Example;

```
<Scene key="drawer" drawer contentComponent={SideMenu}>
   <Scene key="App">
              ... your scenes
   </Scene>
</Scene>
```

**Comment by SoldierCorp** [comment]
Not working for me u.u

**Comment by PhoebePan** [comment]
Not working for me, too Q.Q

**Comment by aksonov** [comment]
Could you reproduce it with latest RNRF and forked Example project? This way I could look into the issue.

**Comment by PhoebePan** [comment]
this is my solution.  

my lightbox `lightbox.js`
```
const TargetDetailLightbox = children => (
  <BaseLightbox verticalPercent={0.7} horizontalPercent={0.9}>
    <Title>
      <Name>{children.title}</Name>
      <Close onPress={() => Actions.pop()}>X</Close>
    </Title>
    <TargetDetail>
      <Avatar
        resizeMode="contain"
        source={{
          uri: children.avatar_url
        }}
      />
      <Button
        title="聊天"
        icon={{ name: "chat" }}
        buttonStyle={{
          backgroundColor: "#79006E",
          marginLeft: 0,
          marginRight: 0,
          marginTop: 10
        }}
        onPress={() => Actions.chatScreen({ title: children.title })}
      />
    </TargetDetail>
  </BaseLightbox>
);

export default TargetDetailLightbox;
```
  
my `app.js`
```
            <Scene
              key="chatScreen"
              component={ChatScreen}
              navBarButtonColor="white"
              navigationBarStyle={{
                backgroundColor: "#79006E",
                height: 40
              }}
              onEnter={props => alert(JSON.stringify(props.title))}
            />
```

**Comment by jf4444** [comment]
same problem

**Comment by aksonov** [comment]
Closed due inactivity and absence of reproducible forked Example project.
