### ISSUE TITLE
Navbar accessibility - bigger text

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2561]
I'm testing our app with bigger text set to maximum. As far as I can observe - the default behavior in iOS is to leave the NavBar as is and only increase the content of the app. That is not the case for RN-router-flux

Leftbutton, rightbutton, title are all being increased which often leads to text overlapping. 

I'm proposing that we add the following to our text elements in the Navbar:
allowFontScaling={false}

this way the text won't increase.

**Comment by aksonov** [comment]
Could you submit PR?

**Comment by compojoom** [comment]
Yep, I'll do it in few hours

**Comment by aksonov** [comment]
Closing this ticket for now.

**Comment by hjylewis** [comment]
Was this PR ever submitted?

**Comment by compojoom** [comment]
@hjylewis - no, I never got it.

**Comment by compojoom** [comment]
I had a look at this again today and it is achievable without modifications to rn-router-flux
The stacknavigator https://reactnavigation.org/docs/stack-navigator.html#navigationoptions-used-by-stacknavigator has a property: headerTitleAllowFontScaling - if this is set to false, then the title is not scaled. And then depending on how you define your scene you can either use your won renderBack and renderRight components. Or if you are providing a function for rightTitle you can pass your own text element and set the allowFontScaling to false
