### ISSUE TITLE
this.props.navigationState return undifined (v4)

### ISSUE THREAD

**Issue by Ali-Dalal** [aksonov/react-native-router-flux#2562]
Can somebody provide a solution to get the children of a scene ?

I have this scenes

`<Scene key={'tabBar'} tabs tabBarIconContainerStyle={AppStyles.tabbar} pressOpacity={0.95}>

        <Scene {...navbarPropsTabs} title={'CV Builder'} key={'homeScreen'}
               icon={props => TabIcon({...props, icon: 'edit'})}
               component={HomeView}/>

        <Scene {...navbarPropsTabs}
               title={'Profile'}
               key={'profile'}
               icon={props => TabIcon({...props, icon: 'account-circle'})}
               component={ProfileView}/>
        <Scene
            key={'error'}
            {...navbarPropsTabs}
            title={'Jobs'}
            component={Error}
            icon={props => TabIcon({...props, icon: 'assignment'})}
        />
    </Scene>`

and inside the drawer, I want to select the first child to be shown as default

`
const state = this.props.navigationState;
const children = state.children;
   <SideMenu ref={(a) => {
                    this.rootSidebarMenu = a;
                }}
                openMenuOffset={AppSizes.screen.width * 0.75}
                menu={
                    <Menu
                        closeSideMenu={this.props.closeSideMenu}
                        ref={(b) => {
                            this.rootSidebarMenuMenu = b;
                        }}
                    />
                }
                isOpen={this.props.sideMenuIsOpen}
                onChange={this.onSideMenuChange}
                disableGestures={true}
            >
                <View style={{backgroundColor: '#000', flex: 1}}>
                    <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate}/>
                </View>
            </SideMenu>`

Thanks a lot

**Comment by Blapi** [comment]
What's your status there? Little bit confused with your code and your explanations. Did you try to log Actions and see if there's the data you need?

**Comment by aksonov** [comment]
Closed due inactivity.
