### ISSUE TITLE
[Android] High memory usage.

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2564]
Hello guys!
I'm experiencing very high memory usage in my app 165-350MB

Can you share how much memory your apps use? Or how do you reduce memory usage with many screens?

Thanks!

To see memory usage type in terminal:

```adb shell dumpsys meminfo com.your.packageName```

I also created an issue in RN github repository: https://github.com/facebook/react-native/issues/16590

Because same code works without lags in iOS it's definitely something wrong.

### Version

- react-native-router-flux v4.0.22-beta
- react-native v0.49.5

**Comment by kesha-antonov** [comment]
Also I've noticed then you ```pop``` from scene memory not released. Although views reduced

**Comment by aksonov** [comment]
Please check pure react-navigation. I'm closing this until more details will appear (about RNRF code)
