### ISSUE TITLE
Can't use renderLeftButton and renderTitle on the same scene

### ISSUE THREAD

**Issue by bsiddiqui** [aksonov/react-native-router-flux#2565]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour
Should be able to use renderTitle and renderLeftButton

### Actual behaviour
If I add renderLeftButton to a scene, the component provided to renderTitle will not be displayed. If I remove the renderLeftButton prop, the title is properly rendered.

**Comment by aksonov** [comment]
Cannot reproduce it with Example project. Please demonstrate it with modified Example.
