### ISSUE TITLE
How to can disable drawer-swipe on the someone screen?

### ISSUE THREAD

**Issue by avorochenko** [aksonov/react-native-router-flux#2566]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.16 (v3 is not supported)
- react-native v0.47.1

I have structure:
![image](https://user-images.githubusercontent.com/19621498/32218177-cd98f04c-be32-11e7-826b-7268bfead3ad.png)

I need to disable drawer-swipe on mainScreen for example.

Thanks for help!

**Comment by tonygriv** [comment]
+1

**Comment by aksonov** [comment]
Try drawerLockMode prop. Check https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode for more details. Docs were updated.

**Comment by tonygriv** [comment]
And what about iOS?

**Comment by aksonov** [comment]
Have you tried it on iOS?

**Comment by blindbox** [comment]
If anyone didn't manage to get this to work, that's because you're supposed to put `drawerLockMode` into the children of `<Drawer />`, not the parent itself.

**Comment by sujitpk-perennial** [comment]
@blindbox as per doc drawerLockMode not support in iOS. Is it working for you?

**Comment by blindbox** [comment]
@sujitpk-perennial I don't know, I haven't got the time to give iOS a try. Anyway, I've changed the way that I'm doing my drawer. Currently, I only wrap Drawer around Scenes that requires the drawer, so drawerLockMode isn't actually needed.

**Comment by bsiddiqui** [comment]
worked for me on iOS

**Comment by edoantonioco** [comment]
In my case its a very similar code, and drawerLockMode does not works. Thats because `<Scene key="root">` is between the Drawer and the Scenes, if its not there it works fine.
On the other hand, you need to keet that `<Scene key="root">` where it is so the app works fine (thats why I also have it there)

So I was wondering if you make it work, and how?

**Comment by danielsGit** [comment]
I have the same problem with @edoantonioco . Anyone resolved this?

**Comment by sujitpk-perennial** [comment]
@danielsGit  I have crated drawerNavigator as follows 

```
const DrawerNavigation = createDrawerNavigator (
    {
        Drawer: {
            screen: Drawer,       
    },
        HomeStacknavigation: {
            screen: customStacknavigation
        }
    },
    {
        initialRouteName: 'HomeStacknavigation',
        contentComponent: ({ navigation, ...props }) =>
            <Drawer style={{flex: 1}}/>
    }
)
```

In Index.js file I handled the drawerLockMode as 

```
  constructor() {
    super()
    this.state = {
      drawerLockMode: 'unlocked'
    }
}

  render() {
    return (
      <View style={{ flex: 1 }}>
        <DrawerNavigation screenProps={{ drawerLockMode: this.state.drawerLockMode }} 
        />
      </View>
    );
  }

```

**Comment by danielsGit** [comment]
Well @sujitpk-perennial . Thanks for your reply. Btw, in this case all screens under customStacknavigation will have the side drawer? This index.js is the placeholder in the screens under customStacknavigation. yeah?

**Comment by sujitpk-perennial** [comment]
No need. You can use multiple stack navigator which will be not part of drawer navigator. 
But if you have a case for ex. You want to show drawer for first and third screen, then all first, second, third will have drawer. Only using drawerLockMode we can lock the drawer for second screen.

**Comment by danielsGit** [comment]
Ok Thanks. Btw, I am using react native router flux. Your solution works with react-navigation. yeah? Do you have any suggestion how could I implement this using RNRF apis?

**Comment by sujitpk-perennial** [comment]
I am not yet used RNRF
