### ISSUE TITLE
Loose /images after yarn install

### ISSUE THREAD

**Issue by Juan1ll0** [aksonov/react-native-router-flux#2567]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0.beta-22 (v3 is not supported)
- react-native v0.48.3

### Expected behaviour

Have that folder.

### Actual behaviour

After "yarn install" there is no folder /node_modules/react-native-router-flux/images/ and causes app crash. I solved it downloading .zip project and copy /images folder to /node_modules/react-native-router-flux/

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Remove node_modules.
2. Install all dependencies with "yarn install"

**Comment by aksonov** [comment]
Cannot reproduce, sorry. Check Example project.

**Comment by Juan1ll0** [comment]
Only occurs with "yarn install" not with "npm install"

**Comment by aksonov** [comment]
Tried with yarn, the same - everything works well.

**Comment by Juan1ll0** [comment]
Hi, I found the solution to my problem. There is a ".yarnclean" file in the root folder of the project that have an entry "images". The package installs the images but yarn delete then in post-procesing. Comment or delete that line solved the problem

Sorry for your time and thank you for your response.
Best regards.

**Comment by fisherwise** [comment]
Thank you Juan. @aksonov I feel it could be a common problem for people using yarn and has the default yarnclean.
