### ISSUE TITLE
Tabs rendering scenes in all Stack

### ISSUE THREAD

**Issue by anushbmx** [aksonov/react-native-router-flux#2568]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour

Only first scene in the initial Stack should be rendered.

### Actual behaviour

Scenes ( first ones ) in all stacks are rendered.

**Comment by onrige** [comment]
Please have a look at `lazy` property in docs: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs

**Comment by iDuuck** [comment]
The lazy property isn't working for me at the moment. Will open another issue for this.
