### ISSUE TITLE
in tabs when change tab screen can't rerender

### ISSUE THREAD

**Issue by yogeshmoradiya121** [aksonov/react-native-router-flux#2572]
i have 4 tabs.
all tabs are renderd when app is opened.
when i change tab i want to rerender screen.
please help me.

"react-native": "0.48.1",
"react-native-router-flux": "^4.0.0-beta.21",

**Comment by mirrorshades** [comment]
Add the lazy prop to your tab component. It's in the docs. https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs

```
<Tabs
    {...props}
    lazy
>
```

**Comment by aksonov** [comment]
Use onEnter static prop for this.
