### ISSUE TITLE
Stacked scenes when replace can't dispose

### ISSUE THREAD

**Issue by omeraplak** [aksonov/react-native-router-flux#2573]
### Version
- react-native-router-flux 4.0.0-beta.22
- react-native v0.48.4?

### Expected behaviour
When replace scene, dispose all stacked scenes.

### Actual behaviour
Replaced scene but can't dispose all stacked scenes.

### Steps to reproduce
1. Actions.Replace('Root');
2. Actions.Replace('Messages');
3. Actions.Push('Profile');
4. Actions.Replace('Payment')

I think when replace current scene with Payment. Messages scene will destroy. Someone has such issues?

**Comment by aksonov** [comment]
Payment will replace Profile but not Messages.
