### ISSUE TITLE
componentWillUnmount not firing when Action.[key]

### ISSUE THREAD

**Issue by NathHorrigan** [aksonov/react-native-router-flux#2575]
### Version
Tell us which versions you are using: 

-  react-native-router-flux: ^4.0.0-beta.21
-  react-native: 0.48.3
 
I'm using a decorator to redirect app if the network drops while in a certain scene. The problem I'm having is that componentWillUnmount in child comp (`Comp` in code) is not firing which is major problem. Is there any workarounds or fixes for this??

```
// Decorator
export default (Comp) => {
  class OnlineComponent extends Component {

    componentWillMount () {
      this.comp = null
      NetInfo.addEventListener('connectionChange', this._handler)
    }

    componentWillUnmount () {
      NetInfo.removeEventListener('connectionChange', this._handler)
    }

    _handler (status) {
      if (status.type == "none") {
        Actions.noNetwork()
      }
    }

    render () {
      return <Comp {...this.props} />
    }

  }
  return OnlineComponent
}
```

**Comment by aksonov** [comment]
It means that component is still in stack - it is how navigation works. Use onExit static method for this.
