### ISSUE TITLE
[Bug] Tab icons mounted twice

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2576]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta22 (from master)
- react-native v0.49.5

### Expected behaviour

5 tabs mounted only once.

### Actual behaviour

5 tabs mounted twice.

![screen shot 2017-11-01 at 22 24 38 1](https://user-images.githubusercontent.com/11584712/32293379-f79e2110-bf53-11e7-9eb4-d5f5e82fe4fc.png)

```
<Tabs icon={TabIcon}>
  <Scene />
  <Scene />
  <Scene />
  <Scene />
  <Scene />
</Tabs>
```

**Comment by SoldierCorp** [comment]
Same error but we don't know whether the error belogns to react nativation or this repository.

**Comment by jaschaio** [comment]
Having the same issue, both with Tabs, Drawers or Modals. #2449, #2382 and #2388 are probably related. The `lazy` property as suggested in #2440 helped with the other Tabs, but the inital one is still mounted twice.

**Comment by aksonov** [comment]
I can't reproduce it with Example project. I added logging to TabView.js and see exactly 5 statements.

**Comment by aksonov** [comment]
Looks like the issue not in RNRF (because it doesn't mount/render scenes at all):react-navigation/react-navigation#476

**Comment by mightym** [comment]
Same issue here. rebuild my whole setup with react-navigation. No issue. 

Here is the issue, assume the following structure:
```
<Tabs key='tabbar'>
    <Stack key='tab_1'}>
        <Scene key='home'>
        <Scene key='list'>
        <Scene key='detail'>
    </Stack>
    <Stack key='tab_2'}>
        <Scene key='profile'>
    </Stack>
</Tabs>
```
and now navigate to tabbar or to home. and you will see `componentWillMount` will be called multiple times

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by malithjkmt** [comment]
```
<Router sceneStyle={styles.main}>
    <Tabs
        key="tabs"
        showLabel={false}
        icon={TabIcon}>
        <Scene
            key="tab1"
            component={PostJobView}
            title='A' />
        <Scene
            key="tab2"
            component={ProfileView}
            title='B' />
    </Tabs>
</Router>
```

TabIcon function is called twice for each Scene.
I checked that router renders only once.

![image](https://user-images.githubusercontent.com/9573056/51043187-1a54c280-15e4-11e9-9e4d-b08592cf74f0.png)


 react: 16.4.1
 react-native: 0.56.0

Tested for all react-native-router-flux: 4.0.0-beta.31, 4.0.0-beta.40, and the latest version - 4.0.6

**Comment by tuaaasa** [comment]
Same issue here.

**Comment by sandeep-sethia** [comment]
I am facing a similar issue. is there a simple workaround?
