### ISSUE TITLE
*** issues hide navbar Drawer

### ISSUE THREAD

**Issue by nmhcoc** [aksonov/react-native-router-flux#2579]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by yordis** [comment]
I would flag you for such of language and useless issue. The last I would want is OOS contributors deal with you and get frustrated.
