### ISSUE TITLE
Doing 'reset' as route type produces error

### ISSUE THREAD

**Issue by ws3li** [aksonov/react-native-router-flux#258]
When I add the 'reset' type to route I get this error: 
_this3._navBar.immediatelyRefresh is not a function.

I recently updated to react-native 0.20+ and got the latest react-native-router-flux 2.3.6

**Comment by smikulenas** [comment]
I can confirm - it's the new issue that does not exist in 2.3.0

**Comment by tinygipxy** [comment]
I have same issue

**Comment by zxcpoiu** [comment]
this issue occurs from version 2.3.4

**Comment by zxcpoiu** [comment]
Current workaround:

* You can downgrade to stable 2.3.1 or master 2.3.3.
* if you don't need to render NavBar, you can try setting up prop `showNavigationBar={false}` instead of `hideNavBar={true}` to tell `ExNavigator` do not render NavBar specifically. see: #262

**Comment by rturk** [comment]
@zxcpoiu tks

**Comment by aksonov** [comment]
Please check 2.3.7

**Comment by zxcpoiu** [comment]
confirmed.

2.3.7 fixed this issue.
tested under react-native@0.20

thanks!
