### ISSUE TITLE
Performance of exiting modal is not good as official Modal 

### ISSUE THREAD

**Issue by tikkichan4** [aksonov/react-native-router-flux#2581]
I am using the modal which contains a TextInput component:
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour
Official modal: Close the keyboard and modal at the same time.
Router flux modal: Close the keyboard and modal at the same time.

### Actual behaviour
Official modal: Close the keyboard and modal at the same time (It is smooth)
Router flux modal: The keyboard is dismissed after the modal is closed. (It is weird)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
N/A

**Comment by aksonov** [comment]
Originally RNRF's Modal was created before current 'official'. If you are not satisfied, please just use official Modal for your use cases.
