### ISSUE TITLE
react-native-router-flux Tabbar when placed on top in android does not display the labels properly

### ISSUE THREAD

**Issue by 11et401012** [aksonov/react-native-router-flux#2583]
#

![screenshot from 2017-11-02 17-24-15](https://user-images.githubusercontent.com/26785189/32325541-67d996de-bff5-11e7-8a45-791e81614421.png)
`            <Tabs
              key="tabbarMain"
              gestureEnabled={false}
              tabs
              wrap={false}
              activeTintColor="#C6426E"
              tabBarStyle={{ backgroundColor: '#fff' }}
              inactiveTintColor="black"
              navBarButtonColor="#fff"
              upperCaseLabel={false}
              tabBarPosition="bottom"
              showIcon
              initial
            >
              <Scene
                key="dashboardtab"
                tabBarLabel="Dashboard"
                tabBarIcon={() => (<Icon name='ios-home-outline' size={25} color="#000" />)}
              >
                <Scene
                  key="dashboard"
                  component={Dashboard}
                  title="Dashboard"
                />
                <Tabs
                  key="eventdetailPage"
                  gestureEnabled={false}
                  tabs
                  titleStyle={{ color: '#fff' }}
                  showLabel={false}
                  wrap={false}
                  swipeEnabled={true}
                  lazy
                  tabBarPosition={{ top: 0 }}
                  tabBarStyle={{
                    backgroundColor: '#fff',
                    height: 70,
                    //  width:
                    marginBottom: 1,
                    shadowColor: '#000',
                    shadowOffset: { width: 10, height: 2 },
                    shadowOpacity: 0.2,
                    shadowRadius: 2,
                    elevation: 1,
                  }}
                >
                  <Scene
                    key="eventprofile"
                    component={EventProfile}
                    swipeEnabled={true}
                    tabStyle={{
                      padding: 55,
                      marginBottom: 25,
                      width: 40
                    }}
                    tabBarIcon={() => (<Text style={{ color: 'black', fontSize: 10 }} > Profile </Text>)}
                  />
                  <Scene
                    key="eventmembers"
                    swipeEnabled={true}
                    tabStyle={
                      backgroundColor = 'red'
                    }
                    component={Members}
                    tabBarIcon={() => (<Text style={{ color: 'black' }} > Members </Text>)}
                  />
                  <Scene
                    key="taskmanagement"
                    swipeEnabled={true}
                    component={EventTasks}
                    tabBarIcon={() => (<Text style={{ color: 'black' }} > Tasks </Text>)}
                  />

                </Tabs>`

**Comment by 11et401012** [comment]
Please help  how to  solve it this problem

**Comment by kesha-antonov** [comment]
Try 
```
    flexWrap: 'nowrap',
```
for your labels. To prevent them go in two lines

**Comment by 11et401012** [comment]
<Tabs
                  key="eventdetailPage"
                  gestureEnabled={false}
                  tabs
                  titleStyle={{ color: '#fff' }}
                  showLabel={false}
                  wrap={false}
                  swipeEnabled={true}
                  lazy
                  style={{ flexWrap: 'nowrap' ,flex:1,flexDirection:'row'}}
                  tabBarPosition={{ top: 0 }}
                  tabBarStyle={{
                    backgroundColor: '#fff',
                    height: 40,
                    //  width:
                    marginBottom: 1,
                    flexWrap: 'nowrap',
                    //flexDirection:'row',
                    shadowColor: '#000',
                    shadowOffset: { width: 10, height: 2 },
                    shadowOpacity: 0.2,
                    shadowRadius: 2,
                    elevation: 1,
                  }}
                >
i  Am  putting style  inside in tabs  but  he  doesn,t  work

**Comment by 11et401012** [comment]
where  we  write code

**Comment by kesha-antonov** [comment]
Try inside your label
```
<Text style={{ flexWrap: 'nowrap' }}>{'My label'}</Text>
```

**Comment by aksonov** [comment]
Please check Example project. @kesha-antonov thank you for the support.

**Comment by HenryHengZJ** [comment]
is this solved yet?
