### ISSUE TITLE
layout with three columns horizontally

### ISSUE THREAD

**Issue by koblinec** [aksonov/react-native-router-flux#2585]
### Version
- react-native-router-flux v4.0.0-beta.22 (v3 is not supported)
- react-native 0.48.4

### Expected behaviour
how can i create a master layout with three columns horizontally (flexDirection: 'row') for a tablet. With overlay unfortunately only goes vertical

![layout-structure-regions-guidance3](https://user-images.githubusercontent.com/6593344/32333284-29481954-bff0-11e7-955d-a6d53a633e50.png)

**Comment by aksonov** [comment]
Not related to RNRF, sorry.
