### ISSUE TITLE
There is no route refined for key app. Must be one of: ......

### ISSUE THREAD

**Issue by fmoessle** [aksonov/react-native-router-flux#2588]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.48.3

### Expected behaviour

Template:

```
<Router>
   <Modal key="modal">
      <Lightbox key="lightbox">
         <Stack key="root">
             <Scene key="loading" component={Loading} initial={true} />
             <Drawer key="app" contentComponent={Sidebar} >
                <Tabs key="tabs">
                   <Scene key="dashboard" component={Dashboard}/>
                   <Scene key="details" component={Details}/>
                </Tabs>
             </Drawer>
          </Stack>
      </Lightbox>
   </Modal>
</Router>
```

The first screen that does get rendered is 'loading'. After doing some checks (token validation) I am trying to call 
`Actions.reset('app')` or `Actions.push('app')` or `Actions.app()`
in my redux saga (side effects) and want to reset the application to the screen with key 'app'.

### Actual behaviour

An error occurs and the application does not perform the navigation.

Error: There is no route refined for key app. Must be one of: 'modal'
[https://ibb.co/fJNh7b](url)

**Comment by aksonov** [comment]
Unfortunately `reset` action is quite buggy because it uses underlying react-navigation API reset action and probably the bug is there (you may debug and find out what is wrong there). We really need to implement own reset action handling within our reducer.

You may want to change containers to 'lazy' tabs and switch to 'app' tab instead of 'reset' action.

**Comment by aksonov** [comment]
Okey, check latest master and add `type='reset'` to  'app' scene. `Actions.app` should work. Don't use 'reset' - it is for root container only.
