### ISSUE TITLE
Warning PropTypes

### ISSUE THREAD

**Issue by dsah** [aksonov/react-native-router-flux#2590]
### Version
RN 0.48.1, react 16.0.0-alpha.12, react-native-router-flux 4.0.0-beta.21
Getting warnings when using this module:

Expected behaviour
This modules need to be updated to make compatible with react native latest version.

Actual behaviour

Warning: PropTypes has been moved to a separate package.

Warning: checkPropTypes has been moved to a separate package.

Warning: React.createClass is no longer supported. Use a plain JavaScript class instead.

### Steps to reproduce

1 Create any scene and run app, the issue is present in both ios and android

Stack trace:
reactConsoleErrorHandler | @ | ExceptionsManager.js:74
-- | -- | --
  | console.error | @ | YellowBox.js:67
  | printWarning | @ | warning.js:35
  | warning | @ | warning.js:59
  | get | @ | react.development.js:2133
  | babelHelpers.interopRequireWildcard | @ | babelHelpers.js:162
  | (anonymous) | @ | index.ios.bundle?pla…&minify=false:66379
  | loadModuleImplementation | @ | require.js:174
  | guardedLoadModule | @ | require.js:126
  | _require | @ | require.js:110
  | (anonymous) | @ | StackNavigator.js:5
  | loadModuleImplementation | @ | require.js:174
  | guardedLoadModule | @ | require.js:119
  | _require | @ | require.js:110
  | get StackNavigator | @ | react-navigation.js:27
  | NavigationStore.processScene | @ | navigationStore.js:493
  | NavigationStore.create | @ | navigationStore.js:348
  | Router | @ | Router.js:44
  | (anonymous) | @ | ReactNativeStack-dev.js:1681
  | measureLifeCyclePerf | @ | ReactNativeStack-dev.js:1610
  | _constructComponentWithoutOwner | @ | ReactNativeStack-dev.js:1680
  | _constructComponent | @ | ReactNativeStack-dev.js:1671
  | mountComponent | @ | ReactNativeStack-dev.js:1629
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | mountChildren | @ | ReactNativeStack-dev.js:2871
  | initializeChildren | @ | ReactNativeStack-dev.js:2940
  | mountComponent | @ | ReactNativeStack-dev.js:2969
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | mountChildren | @ | ReactNativeStack-dev.js:2871
  | initializeChildren | @ | ReactNativeStack-dev.js:2940
  | mountComponent | @ | ReactNativeStack-dev.js:2969
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | performInitialMount | @ | ReactNativeStack-dev.js:1703
  | mountComponent | @ | ReactNativeStack-dev.js:1655
  | mountComponent | @ | ReactNativeStack-dev.js:1327
  | mountComponentIntoNode | @ | ReactNativeStack-dev.js:1998
  | perform | @ | ReactNativeStack-dev.js:1382
  | batchedMountComponentIntoNode | @ | ReactNativeStack-dev.js:2004
  | perform | @ | ReactNativeStack-dev.js:1382
  | batchedUpdates | @ | ReactNativeStack-dev.js:2077
  | batchedUpdates$1 | @ | ReactNativeStack-dev.js:1456
  | renderComponent | @ | ReactNativeStack-dev.js:2032
  | render | @ | ReactNativeStack-dev.js:3258
  | renderApplication | @ | renderApplication.js:33
  | run | @ | AppRegistry.js:116
  | runApplication | @ | AppRegistry.js:191
  | __callFunction | @ | MessageQueue.js:306
  | (anonymous) | @ | MessageQueue.js:108
  | __guard | @ | MessageQueue.js:269
  | MessageQueue.callFunctionReturnFlushedQueue | @ | MessageQueue.js:107
  | (anonymous) | @ | debuggerWorker.js:72

**Comment by kesha-antonov** [comment]
Check recent master. I think it has been fixed. I have no warnings on this

**Comment by einomi** [comment]
The problem disappeared for me after upgrading to React 16.0.0
