### ISSUE TITLE
TabBarStyle and tabStyle  not working in react native router flux  

### ISSUE THREAD

**Issue by greenraze** [aksonov/react-native-router-flux#2591]
![screen shot 2017-11-04 at 1 08 22 pm](https://user-images.githubusercontent.com/31312734/32403654-4cd72852-c161-11e7-9c37-63134d15415e.png)
i m showing five tabs  i want to set the background color which is not working
"react-native-router-flux": "3.41.0",
"react-native": "0.46.4",
The icons are showing but  the icon view is not adopting the free space and styles are not working  in tabs.

i m setting the icon like this..
const FavoriteIcon = ({selected,title }) =>
{
  return (
    <View style={styles.tabIconStyle}>

      <Image
        resizeMode={'contain'}
        style ={{ width: 30,
          height: 30,

        }}
        source={ selected ? require('../../assets/img/tab/tab_three_selected.png') :require("../../assets/img/tab/tab_three.png")  }/>
      <Text  style={[styles.tabIconTextStyle,{color:selected?PURPLE_COLOR
      :GRAY_DARK_COLOR_SETTINGS
      }]}>FAVORITES</Text>
    </View>
  )

}

these are the tabs in my router 
             <Scene key="bottomtabbar" 
               hideNavBar   type="reset"    tabs={true}
                tabBarStyle={styles.tabBar}
               TabBarStyle={styles.tabBarStyle}
              
              >
                <Scene
                   tabBarStyle={styles.tabBar}
                  tabStyle={{backgroundColor:'green', borderWidth:1}}
                  key="featuredtab"     icon={FeaturedIcon} navBar={DrawerHeader}>
                  <Scene key="featured" component={Featured} initil   navBar={DrawerHeader} />
                </Scene>

                <Scene key="exploretab"
                  icon={ExploreIcon} navBar={DrawerHeader} >
                  <Scene key="explore"  initial component={Explore}      navBar={DrawerHeader} />
                  <Scene key="activities"   component={Activities}  navBar={ActivitiHeader} />
                </Scene>

                <Scene key="favoritetab"   icon={FavoriteIcon} navBar={DrawerHeader}>
                  <Scene key="favorites" component={Favorites} initil   navBar={DrawerHeader} />
                </Scene>
               </Scene>

**Comment by aksonov** [comment]
v3 has very limited support right now and it seems you mixed v3/v4 syntax to tab bars. Thanks to @daviscabral, it works with latest RN, please ask him any questions.
