### ISSUE TITLE
back button tint color do not work

### ISSUE THREAD

**Issue by yordis** [aksonov/react-native-router-flux#2593]
### Version
Tell us which versions you are using: 

- react-native-router-flux: `"version": "4.0.0-beta.22"`

### Expected behaviour
From `<Scene key="webview" component={WebViewScreen} backButtonTintColor="red"/>` to be red

### Actual behaviour
Default color

### Steps to reproduce
Pretty much did `<Scene key="webview" component={WebViewScreen} backButtonTintColor="red"/>`  expecting to be a `red` arrow.

**Comment by jaschaio** [comment]
Having the same problem, on both iOS and Android

**Comment by yordis** [comment]
I think the issue is affecting all the properties or most of them because something tells me is related to https://github.com/aksonov/react-native-router-flux/issues/2598#issuecomment-342375932

It doesn't work for me either.

**Comment by cjcheshire** [comment]
Trying to update from V3 to V4.  Also having the same problem

**Comment by aksonov** [comment]
You should use this property for containers, not for child scenes. I just added it to Example project and see red 'back' image normally.

**Comment by shiftrtech** [comment]
I am facing the same issue using this:

<Stack backButtonTintColor='#ffffff' key='auth' initial transitionConfig={transitionConfig} >
  <Scene />
  <Scene />
  ....
</Stack>

//package,json
"react-native-router-flux": "^4.0.5",
