### ISSUE TITLE
Props not working for tab scenes. 

### ISSUE THREAD

**Issue by amarkovits** [aksonov/react-native-router-flux#2594]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta22
- react-native v0.49.3

### Expected behaviour
Scene receives the props

### Actual behaviour
Props are not received by scene

### Steps to reproduce
I have a router like this (this is simplified, I removed the rest of the scenes):
```
       <Router>
            <Scene key="root">
                <Scene
                    key="tournament"
                    wrap={false}
                    tabs
                    tabBarPosition="top"
                    tabBarComponent={TabBarTop}
                    hideNavBar={false}
                    swipeEnabled
                    title="Tournament Name">
                    <Scene key="bets" component={GameList} tabBarLabel="Bets" gameType='bets' />
                    <Scene key="results" component={GameList} tabBarLabel="Results" gameType='results'/>
                    <Scene key="leaderboard" component={Leaderboard} tabBarLabel="Leaderboard"/>
                </Scene>
            </Scene>
        </Router>

```
The problem is that in my GameList component I don't receive the gameType props.

**Comment by aksonov** [comment]
I can't reproduce it with latest RNRF and Example project.Just add `data='wow'` to tab scenes and you will see 'Tab data:' changed.
