### ISSUE TITLE
[Bug/Warning] Could not locate shadow view with tag #3050, this is probably caused by a temporary inconsistency between native views and shadow views

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#2595]
Hello!

I have this setup:

```
<Stack>
  <Scene key='signIn' ... />
  <Tabs key='tabbar' ...>
    <Scene ... >
      <Scene ... />
    </Scene>
    ...
</Stack>
```

In ```signIn``` scene after log in I call ```Actions.tabbar({ type: ActionConst.RESET })``` and after reset scenes I have these warnings.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta-22 (master)
- react-native v0.50-rc

### Expected behaviour

Gives warninings.

### Actual behaviour

No warninings.

![screen shot 2017-11-05 at 11 24 47](https://user-images.githubusercontent.com/11584712/32413158-678dca82-c21c-11e7-99bd-bc38e68f0d6b.png)

**Comment by kesha-antonov** [comment]
@aksonov  Ok. thanks!

BTW If i don't use ```type: ActionConst.RESET``` then I have 2 scenes in ```routes``` instead of 1. And no warnings

**Comment by aksonov** [comment]
Please check react navigation, it could be their issue of react native

**Comment by kesha-antonov** [comment]
Please see https://github.com/aksonov/react-native-router-flux/issues/2531

I've updated info

**Comment by aksonov** [comment]
Closed because it is not related to RNRF.

**Comment by valery-lavrik** [comment]
faced with this problem.
I had a SafeAreaView inside another SafeAreaView, which caused this effect.

Maybe it will help someone

**Comment by jacobp100** [comment]
@valery-lavrik is this from the react-native-safe-area-context package? You should (in theory) be allowed to do that

**Comment by valery-lavrik** [comment]
@jacobp100     Yes, that's right

**Comment by jacobp100** [comment]
I’ve submitted a PR to the repo to fix it
