### ISSUE TITLE
 Drawer with duplicate menu

### ISSUE THREAD

**Issue by 1fabiopereira** [aksonov/react-native-router-flux#2598]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.48.1

### Expected behaviour

I'm trying to use Drawer but when I add Drawer I end up getting two navigation bars.

### Actual behaviour
![screenshot_1509994671](https://user-images.githubusercontent.com/11349795/32458712-74481428-c314-11e7-850d-9abb0c03b8e5.png)

how can I fix this?

**Comment by yordis** [comment]
@1fabiopereira if you figure it out please give me some updates because we are two already. I am using either Stack or Scene with Scenes inside does this thing.

There is a option you could pass `hideNavBar` but it does hide everything and dont let me show the menu per scene at least ....

**Comment by 1fabiopereira** [comment]
@yordis you can leave, if I find out something, I'll let you know.

**Comment by foyarash** [comment]
Using hideNavBar does the trick for me

What’s your code?

**Comment by yordis** [comment]
@foyarash 
```
<Stack hideNavBar> // I expect to hide the main nav bar
  <Scene hideNavBar={false}/> // I expect to show the sub nav bar
  <Scene hideNavBar={false}/>
</Stack>
```

**Comment by 1fabiopereira** [comment]
I solved my problem by putting a hideNavBar in the Drawer.

```
<Router>
    <Stack key="root">
        <Scene
             component={Loading}
             hideNavBar
             key="loading"
             panHandlers={null}
        />        
        <Drawer
             contentComponent={Index}
             key="menu"
             hideNavBar
         >
              <Scene
                   component={Home}
                   key="home"
                   panHandlers={null}
                   title={I18n.t("pagina_home")}
                />
           </Drawer>
      </Stack>
</Router>
```

**Comment by yordis** [comment]
@foyarash you would have 2 nav bar then

**Comment by yordis** [comment]
@aksonov I dont want to open another issue but I saw that you closed this one.

I am having some issues with any override properties on the child views, and I am still having this issue.

I had to reverse back to 3.x
