### ISSUE TITLE
Listen to route changes globally

### ISSUE THREAD

**Issue by sondremare** [aksonov/react-native-router-flux#2599]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.48.4

I am migrating from v3 of RNRF to v4, and am struggling with how to listen to route changes on a global level. We listen to RNRF actions and act accordingly in terms of dismissing keyboard, changing the statusBar style etc. However, after upgrading to v4 I am struggling with making this work. First I tried "createReducer", but this is not connected to the rest of the app's state (which I need to determine what do to given a RNRF Action). I also tried passing my own dispatch and state into the Router, but everything just blows up. Any pointers on how to make this work? Any help is appreciated greatly.

**Comment by sondremare** [comment]
Ended up using a generator to create all my scenes, and added a default onEnter for all scenes.

**Comment by mikeevstropov** [comment]
@sondremare Are you mean you added `onEnter` to each `<Scene>`?
