### ISSUE TITLE
Is it able to create multiple router instances?

### ISSUE THREAD

**Issue by VansonLeung** [aksonov/react-native-router-flux#26]
e.g.

For a tab bar view with 5 categories, 5 Routers need to be present for these 5 navigation pages.

Is it able to make 5 different routers in the same app ??

**Comment by aksonov** [comment]
No, you should use 'Container' element, check demo with tab bar..

**Comment by imothee** [comment]
I also am interested in this.

If you push another Route into the navigation stack from within a TabBar the TabBar is removed and the new route is basically full screen. Then when performing Action.pop it falls back to the first Tab selected.

I really want to emulate the native tabbar behaviour. How would I use a container to do this?

This is not the default behavior of iOS native navigation controllers embedded inside a tabbarcontroller. Each navigation controller is completely independent

**Comment by aksonov** [comment]
Yes, I've found this bug recently and trying to fix

**Comment by aksonov** [comment]
Should be fixed with new release

**Comment by aksonov** [comment]
There is no Container now, but just inner Router instance.
