### ISSUE TITLE
Clear example with top-level Redux `connect` 

### ISSUE THREAD

**Issue by adamski** [aksonov/react-native-router-flux#260]
I'm struggling to work out how to access redux state from a connected component's props, using the top level method connecting it to the Router. 
I'd like to avoid using multiple `connect`s, as the Redux docs state:
>  Try to only do this for a top-level component, or route handlers

I'm refactoring some code using NavigatorIOS and was previously passing the necessary props using `passProps`. I can't see an equivalent - I guess that happens behind the scenes with `connect`? Or do I need to `connect` each Route's component?

**Comment by adamski** [comment]
Think I found some good advice on #56 
Still would be good to have clearer example I think.

**Comment by aksonov** [comment]
Feel free to submit PR for improving documentation. Btw, there is quite large discussion at redux github about having only one connect for top-level component, and i don't agree with this sentence.
