### ISSUE TITLE
Scene tabs={true} lazy={true} on Android does not work as expected

### ISSUE THREAD

**Issue by Ilario17** [aksonov/react-native-router-flux#2600]
### Version

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour

Tabbar Lazy should load the various tabs only when they are shown, right?

### Actual behaviour

when I open the third tab from the first one, also the second one is loaded. So renderRightbutton does not work because the third tab override that of the second tab

### Steps to reproduce
In my Router.js

```
<Scene key="tabbarRoot" tabs lazy>
  <Scene key="myTab1>
    <Scene key="tab1" component={One} renderRightButton />
  </Scene>
  <Scene key="myTab2>
    <Scene key="tab2" component={Two} renderRightButton />
  </Scene>
  <Scene key="myTab3>
    <Scene key="tab3" component={Three} renderRightButton />
  </Scene>
</Scene>
```

My app opens on One, then if I tap on Three, with console.log I can see that renderRightButton is called both in Three and Two

**renderRightButton Two:**

```
componentDidMount() {
  Actions.refresh({ right: this.renderRightButton() });
}

renderRightButton() {
  console.log('render right button TAB SOCIAL');
  return (
	<TouchableOpacity onPress={this.onRightButton.bind(this)}>
		<Image
			style={{ width: 21, height: 21, marginRight: 15 }}
			source={require('../img/btn2.png')}
		/>
	</TouchableOpacity>
  );
}
```

**renderRightButton Three**

Equal to that of the Two, but obviously point to different method in onPress

**Comment by aksonov** [comment]
Sorry, RNRF is just wrapper around react-navigation. Try to check pure react-navigation TabNavigator with lazy option.

**Comment by Samesh** [comment]
Hey so did you find a solution @Ilario17? I'm also struggling with the same problem.

**Comment by andreaskarantzas** [comment]
I faced the same issue. You can try to use animationEnabled={false}. Worked for me in addition with "lazy" and swipeEnabled={false}. As @aksonov said you can also check the documentation of https://reactnavigation.org/docs/tab-navigator.html

**Comment by AutomaticWaffle** [comment]
Been having this problem for the past two weeks, fixed it with @andreaskarantzas's method.

Thank you @andreaskarantzas!

```
<Tabs
    lazy
    animationEnabled={false}
    swipeEnabled={false}>
```
