### ISSUE TITLE
Docs to handle custom Pan Handler

### ISSUE THREAD

**Issue by alexwasner** [aksonov/react-native-router-flux#2603]
### Version
-    "react-native-router-flux": "^4.0.0-beta.22"
-    "react": "16.0.0-beta.5",
-    "react-native": "0.49.3",

In v3, we could pass `getPanHandlers` to add custom gestures to the view to trigger the swipe back. In the changelog, I see that it mentions this is removed in exchange for writing a custom navigator for react navigation. Can we get an example/docs of how this actually would work using RNRF?

**Comment by aksonov** [comment]
Sorry, I don't have any idea. v3 uses react-native-navigation-experimental API (btw, it still works with latest RN) but v4 uses react-navigation that doesn't have this feature. Feel free to submit PR

**Comment by alexwasner** [comment]
Figured it out. Closing

**Comment by alexwasner** [comment]
If you wanted it re-opened to add getPanHandlers to V4, I can re-open
