### ISSUE TITLE
navTransparent iOS has black border on bottom

### ISSUE THREAD

**Issue by brycepavey** [aksonov/react-native-router-flux#2604]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.4

### Expected behaviour
Not show border bottom when navTransparent={true} or be able to override borderBottomWidth or borderBottomColor with navigationBarStyle={{borderBottomWidth:0}} which has no effect

### Actual behaviour
shows black border on bottom of transparent navbar
```
<Stack key="homeTab" headerMode="screen" >
    <Scene key="scene1" component={Scene1} title="" navBar={HomeNavBar} />
    <Scene key="scene2" component={Scene2} title="" navTransparent/>
</Stack>
```
![screen shot 2017-11-08 at 4 51 25 pm](https://user-images.githubusercontent.com/6986339/32534144-6135f50e-c4a8-11e7-97a8-2ed6eb1d1000.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create a route with navTranparent set to true
2. Navigate to route

**Comment by luco** [comment]
+1 on this.

**Comment by lighthugger** [comment]
You can see in src/navigationStore.js that navTransparent will use preset styling with elevation set 1, and will also disregard any other styling you might've passed with navigationBarStyle:

```
if (navTransparent) {
      res.headerStyle = { position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0,
        borderBottomWidth: 0, elevation: 1 };
    }
```
Use navigationBarStyle with elevation: 0 instead of navTransparent.

```
<Scene
  // your scene settings
  navigationBarStyle = {{
    position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0,
    borderBottomWidth: 0, elevation: 0
  }}
>
...
</Scene>
```
This fixed my issue with elevation shadow on Android, haven't tested on iOS.

**Comment by aksonov** [comment]
Added navTransparent to register screen for Example project, don't see black border with latest RNRF/react-navigation. Closing the issue.

**Comment by antonsivogrivov** [comment]
and how to set border when navTransparent is true? Now I dont's see border even with

```
borderBottomWidth: 1,
borderBottomColor: 'rgba(255, 255, 255, 0.3)',
```
