### ISSUE TITLE
duplicate Scene several times

### ISSUE THREAD

**Issue by iCodePup** [aksonov/react-native-router-flux#2606]
I have a scene and i need to duplicate this scene as many times as the user need.

So i add "clone" property to my Scene.

```
   <Scene
                            initial={false}
                            navBar={NavBar}
                            component={MyComponent}
                            hideNavBar={false}                               
                            key='MyComponent'
                            title={('App')}
                            back
                            clone
                        />
```
And in my component {MyComponent} i have a button to duplicate this component

```
  <TouchableOpacity
                    onPress={() => Actions.MyComponent()}                       
                    <MIcon name="skip-next" size={24} color="#FFF"/>
                </TouchableOpacity>
```

but its working only one time...

**Comment by aksonov** [comment]
It is 'feature' to avoid double push for the same scene if user taps it several times. Try to add some random param to avoid that...

**Comment by BhaumikSurani** [comment]
I Have same issue.
i'm defined Scene as clone and use
`Actions.MyScreen({ randomParam: randomValue })`
But still not working. It Every time update value. 
How to Resolve this issue?
