### ISSUE TITLE
Example Project loads, but tapping actions does nothing in iOS Simulator

### ISSUE THREAD

**Issue by toblerpwn** [aksonov/react-native-router-flux#2610]
See video of problem @ https://youtu.be/jkMxlnQwccg

macOS 10.13.1
iPhone 6 - iOS 11.1 Simulator
Xcode 9.1

Steps to reproduce:
```
# Get the code
git clone https://github.com/aksonov/react-native-router-flux.git
cd react-native-router-flux/Example

# Install dependencies
yarn

# Run it
react-native run-ios
```

**Comment by aksonov** [comment]
Cannot reproduce. Probably some old cache / react-navigation version exist within your node_modules / watchman memory / etc
