### ISSUE TITLE
"Error during onExit handler:" when calling `this.setState()` from within a Component's `onExit()` implementation

### ISSUE THREAD

**Issue by toblerpwn** [aksonov/react-native-router-flux#2611]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.23
- react-native v0.50.3

### Expected behaviour

Can call `this.setState()` from within a Component's `onExit()` implementation, just like one can successfully do from a Component's `onEnter()` implementation.

### Actual behaviour

Calling `this.setState()` from within a Component's `onExit()` implementation results in "red screen" error:

```
console.error: "Error during onExit handler:", {}

console.error
    YellowBox.js:71:10
NavigationStore._callee$
    navigationStore.js:658:1650
tryCatch
    runtime.js:63:39
Generator.invoke [as _invoke]
    runtime.js:337:21
Generator.prototype.(anonymous
    index.bundle?platform=ios&dev=true&minify=false:11458:21
tryCatch
    runtime.js:63:39
invoke
    runtime.js:139:19
<unknown>
    runtime.js:184:10
tryCallTwo
    core.js:45:4
```

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

**NOTE:** I was hoping to reproduce the issue in a simplified form, but I ran into this issue: https://github.com/aksonov/react-native-router-flux/issues/2610

1. Create app of structure:
    ```
    <Provider store={store}>
      <Router>
        <Modal
          headerMode='none'
        >
          <Tabs
            key='tabbar'
            tabBarPosition='bottom'
            tabBarStyle={{ backgroundColor: '#eee' }}
            headerMode='none'
          >

            {/* FIRST tab */}
            <Scene
              key='firstTab'
              tabBarLabel='First'
              icon={Tab}
              image={require("./assets/images/tab-image-1.png")}
              initial={true}
              headerMode='float'
              title='Cool Tabs'
            >
              <Scene key='firstContainer' component={FirstTab} />
            </Scene>

            <Scene
              key='secondTab'
              tabBarLabel='Second'
              icon={Tab}
              image={require("./assets/images/tab-image-2.png")}
            >
              <Scene key='secondContainer' component={SecondTab} />
            </Scene>

          </Tabs>

          <Scene
            key='modal'
            component={Modal}
          />

        </Modal>
      </Router>
    </Provider>
    ```
2. Add the following (example) `setState()` code to the `FirstTab` component:
    ```
    // this works!
    static onEnter = () => {
      console.log('firstTab.js // onEnter()')
      this.setState({
        visible: true
      })
    }

    // this CRASHES!
    static onExit = () => {
      console.log('firstTab.js // onExit()') // this log is executed
      this.setState({ // this seems to be where things fall apart
        visible: false
      })
    }
    ```
2. Call `Actions.push('modal')` from somewhere.
3. Observe crash per description above.

(Also note that my entire intention is to get some "visible"-type state implemented here so I can return false to `shouldUpdateComponent()` when there is a `Modal` Component "covering" the base tab/component/scene. If there is a better way to do the same, please let me know!)

**Comment by aksonov** [comment]
`static` cannot work with `this`

**Comment by toblerpwn** [comment]
@aksonov Thank you. It does work (no crash & functions correctly) with `static.onEnter()`, fwiw.
