### ISSUE TITLE
Tabs clone subscene

### ISSUE THREAD

**Issue by FitoFeat** [aksonov/react-native-router-flux#2614]
react-native-router-flux": "^4.0.0-beta.22",

I want to know if its possible to clone one Scene inside Tabs many times as the user need (click on a button) with avaibility to navigate  backward (pop()) AND forward (?).

      <Tabs
                                tabBarPosition="bottom"
                                animationEnable={true}
                                tabBarOptions= {{
                                    activeTintColor: "red",
                                }}
                                swipeEnabled
                                showLabel={true}
                                tabBarStyle={styles.tabBarStyle}
                                indicatorStyle={styles.tabIndicatorStyle}

                            >
                                <Scene
                                    initial={false}
                                    hideNavBar={true}
                                    component={ViewToDuplicateXTimes}
                                    navigationBarStyle={styles.navbar}
                                    titleStyle={styles.navbarButtonText}
                                    key='FreeWorkout'
                                    title={'ViewToDuplicateXTimes'}
                                    back
                                    clone
                                />
     </Tabs>

ViewToDuplicateXTimes : Button to create new ViewToDuplicateXTimes Scene : (work but Tabs are not refresh (only a single Tab is visible))

         <TouchableOpacity
                        onPress={() => Actions.ViewToDuplicateXTimes()}
                        style={[styles.navBarItem, {paddingLeft: 18}]}>
                        <Icon name="skip-next" size={24} color="#FFF"/>
                    </TouchableOpacity>

Thanks for help

**Comment by aksonov** [comment]
It is not supported
