### ISSUE TITLE
Drawer with modal scene 

### ISSUE THREAD

**Issue by v3yr0n** [aksonov/react-native-router-flux#2617]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.23
- react-native v0.50.0

### Expected behaviour
Show scene as modal and when clicking on the back button pop to the previews scene

### Actual behaviour
Shows scene normally but when pop occurs show the same scene again

`<Drawer {...} 
<Scene key="root" initial>
    <Scene key="afterlogin">
        <Scene key="getHomeNoLogin" hideNavBar={true} component={HomeNoLogin} titleImage={logo_horizontal}  navBar={CustomNavBar} />
    </Scene>
        <Scene key="beforelogin" modal>
        <Scene key="getLogin" hideNavBar={true} component={Login} titleImage={logo_horizontal}  navBar={CustomNavBar} />
        <Scene key="getForgotPassword" hideNavBar={true} component={ForgotPassword} titleImage={logo_horizontal}  navBar={CustomNavBar} />
    </Scene>
</Scene>
</Drawer>`

![out](https://user-images.githubusercontent.com/864980/32731056-b4eade4a-c880-11e7-95b5-cef9e8a4803f.gif)

**Comment by v3yr0n** [comment]
@aksonov Am I doing something wrong?

**Comment by aksonov** [comment]
Modal should be not included within drawer but outer stack. Please check Example project
