### ISSUE TITLE
Actions.pop(refresh: { }) cannot trigger componentWillReceiveProps

### ISSUE THREAD

**Issue by hawx1993** [aksonov/react-native-router-flux#2620]
### Version
`"react-native-router-flux": "3.38.0",`

I from scene A to scene B, and save data at scene B. After saving data,I need pop to Scene A, and refreshing data of  scene A.  But I tried at scene B :

```javascript
setTimeout(()=> {Actions.refresh({refresh: true})}, 50);
Actions.pop();
```

and after the first time pop to scene A, I get the props : `refresh ` of undefined, at second times, I get true. But after the second time pop to scene A , I try to fetch data at `componentWillReceiveProps` , which caught infinite loop.

### Expected behaviour

I expect from scene B pop to scene A, and refresh the data of scene A.

**Comment by veer3383** [comment]
did you get this working?

**Comment by hawx1993** [comment]
yes,it works.

**Comment by jota-info** [comment]
hawx1993 how did you solve this?

**Comment by esutton** [comment]
@hawx1993 or @veer3383 How did you solve this?

Using refresh to trigger componentWillReceiveProps always seems to work **sometimes**, maybe once or twice then it never triggers it again.

1) When my detail view exits, I attempt to use REFRESH to get the parent list view to update via componentWillReceiveProps

2) Sometimes componentWillReceiveProps() is called a time or two, then it is not?
````
// When the detail view exits, I attempt to use REFRESH to get the parent list view to update 
  componentWillUnmount() {
    Actions[scene.Key.MenuPlanList]({ type: ActionConst.REFRESH });
  },
````

Using:
````
		"react": "^16.2.0",
		"react-native": "^0.53.3",
		"react-native-router-flux": "4.0.0-beta.27",
````

**Comment by veer3383** [comment]
Its just a small hack, not a solution. @esutton  Yes, It can refresh a particular view only once, until and unless that particular view is reloaded again. Router flux didn't seem to help here. I dumped Router flux and used react navigation with Redux in my next React project

**Comment by esutton** [comment]
@veer3383 Thanks for feedback.

This what you switched to?
- https://github.com/react-navigation/react-navigation

> I dumped Router flux and used react navigation with Redux in my next React project

I wondered if that might be a trend.
