### ISSUE TITLE
Tabbar title color not changing 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2622]
I have a bottom tabbar and I set the title color but it's not working, attached screenshot and here is my code 

```
<Tabs
                                    key="tabbar"
                                    swipeEnabled
                                    showLabel={true}
                                    showIcon={true}
                                    activeBackgroundColor="#25abf9"
                                    inactiveBackgroundColor="#30393F"
                                >

                                <Stack key="main"
                                       title="Photos"
                                       tabBarLabel="Photos"
                                       inactiveBackgroundColor="#30393F"
                                       activeBackgroundColor="#25abf9"
                                       icon={PhotosTabIcon}
                                       titleStyle={{ color: 'white', alignSelf: 'center' }}
                                >
```

As you can see the photos and apps are not white

<img width="374" alt="screen shot 2017-11-15 at 2 15 06 pm" src="https://user-images.githubusercontent.com/169507/32816957-6fb91d10-ca0f-11e7-8737-8d660e2705a2.png">

**Comment by delia-m** [comment]
I was hack around of same issue.. 
Title color is for title text on the top, 
for tab label, use need to use `inactiveTintColor` and `activeTintColor`
check [API](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs)

**Comment by AlmogRnD** [comment]
@delia-m thanks that did it
