### ISSUE TITLE
await is a reserved word

### ISSUE THREAD

**Issue by denny64** [aksonov/react-native-router-flux#2623]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.24
- react-native v0.50.3

### Expected behaviour
It should load?

### Actual behaviour
![screen shot 2017-11-15 at 3 47 07 pm](https://user-images.githubusercontent.com/9099997/32819260-691b5542-ca1c-11e7-85cf-c1512f9b2059.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

Upgraded from v3, and immediately hit this error on initial load...

**Comment by aksonov** [comment]
No details. It is not related to RNRF
