### ISSUE TITLE
 animation for navigation bar

### ISSUE THREAD

**Issue by karenYerevan** [aksonov/react-native-router-flux#2626]
hi there...
has a RNRF animation like this ???
if no, how can build something like this ?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9501068/32889867-f4573792-cae5-11e7-8762-87c00c2198e5.gif)

**Comment by themakerman** [comment]
@karenYerevan You can use a lightbox to control opacity parameters of the top tittle bar. Wrap the component in the Animated.View. RNRF won't provide animation from out of the box but only the lightbox component. Make sure to set position to absolute and arrange it at toolbar/tittle bar position.

**Comment by aksonov** [comment]
Right, it is not supported from the box
