### ISSUE TITLE
[Help] How can i replicate this gesture. GIF Included. Please have a look.

### ISSUE THREAD

**Issue by themakerman** [aksonov/react-native-router-flux#2629]
************Please Zoom out chrome for better understanding of what i want****************

I Know i will be dealing with panResponders and Animated.View and already tried those. The thing is i am unable to move the whole component Screen and just components inside render method are moving. The white background behind remains static. I want to move whole component so that the one behind the stack becomes visible. 
Really grateful if some one can give me pointers.

![gif_1510930119627](https://user-images.githubusercontent.com/14818804/32953688-f32e43d6-cbeb-11e7-8a3e-7de91cd58fef.gif)

**Comment by aksonov** [comment]
Sorry, it is question for stackoverflow, not the issue. I'm not sure that it is supported by RNRF.

**Comment by themakerman** [comment]
@aksonov Sorry i forgot to close the issue. Actually i implemented it using RNRF LightBox.

**Comment by aksonov** [comment]
Glad to hear, maybe you can post PR to docs how to implement that, it could be very useful.

**Comment by themakerman** [comment]
@aksonov OK I can document it. However I havent done any PR before. Can you tell me how can I do it? I am greatly interested in supporting rnrf community both by technical as well as financial contributions.
