### ISSUE TITLE
V2.3.6 "Current Router = undefined" when navigating from a child tab route to a parent tab route

### ISSUE THREAD

**Issue by iZaL** [aksonov/react-native-router-flux#263]
after updating to the latest version i.e 2.3.6, I cannot navigate to routes outside of the parent router.
that is, in the below example, If i try to navigate to **favorites** tab or **appointments** tab from any child routes within the **main** route, it throws an error saying "**cannot find router for route={routName} current Router = undefined**".
also the navigation bar title are missing when passed dynamically.

`
    <Route name="home">
          <Router footer={TabBar} tabBarStyle={{backgroundColor:'#99ddff'}} showNavigationBar={false}>
            <Route name="main" title="Home" schema="tab" hideNavBar={false} selectedTabIcon="ion|ios-home" tabIcon="ion|ios-home-outline">
              <Router >
                <Route name="categories" component={Categories} hideNavBar={true} title=""/>
                <Route name="categoryEntity" component={Category} title=""/>
                <Route name="companyEntity" component={Company} title=""/>
                <Route auth={true} name="appointmentContainer" component={Appointment} title=""  />
              </Router>
            </Route>
            <Route auth={true} name="favorites" component={Favorites} schema="tab" title="Favorites" hideNavBar={true}  selectedTabIcon="ion|android-favorite" tabIcon="ion|android-favorite-outline"/>
            <Route auth={true} name="appointments" schema="tab" title="Appointments" component={Appointments} hideNavBar={true}  selectedTabIcon="ion|ios-alarm" tabIcon="ion|ios-alarm-outline"/>
            <Route name="settings" schema="tab" title="Settings" component={Settings} selectedTabIcon="ion|ios-gear" tabIcon="ion|ios-gear-outline" />
          </Router>
        </Route>
`

**Comment by iZaL** [comment]
ok, for some reason, the code is not indenting properly, sorry for that

**Comment by oureta** [comment]
I am also having issues with Back Button on v2.3.6. I think v2.3.1 is more stable.

**Comment by aksonov** [comment]
Please check 2.3.7

**Comment by iZaL** [comment]
V2.3.7 doesn't fix the bug

**Comment by aksonov** [comment]
Then it means different issue. Ok, please modify Example to reproduce this bug in sample repo.

**Comment by aksonov** [comment]
Closing it for now. Feel free to re-open when sample repo will be ready.
