### ISSUE TITLE
How to disable Tab bar item

### ISSUE THREAD

**Issue by mourice** [aksonov/react-native-router-flux#2630]
I have different Scene define for tabs and I want to disable one of them. by disable I mean to say it will only open after some condition is true in the previous tab.

How can I disable particular tab bar item (Scene) ?

### Version
"react-native-router-flux": "^3.40.1",
"react-native": "0.48.4"

**Comment by aksonov** [comment]
Sorry, I don't see that it is supported by RNRF and react-navigation built-in tabbar. But you may define own custom tabbar for this.

**Comment by gharivand** [comment]
add this:
`tabBarOnPress={()=>{return}}`
