### ISSUE TITLE
[Question / Request] Can we increase the size of the navbar back button hitbox?

### ISSUE THREAD

**Issue by wbattel4607** [aksonov/react-native-router-flux#2631]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.0-beta.24
- react-native v0.50.3

### Requested behaviour
Has there been any discussion/thought regarding an ability to increase the hitbox size of the back button? I like the icon size but a lot of our users have complained about the hitbox size being too small. It takes many users upwards of five attempts to hit the button. It'd be fantastic if we could increase the size of the press-able area without changing the icon size. Maybe this already exists but I couldn't find anything speaking to it.

I can try to submit a PR if it'd help.

Thanks! :)

![img_e081f964e85b-1](https://user-images.githubusercontent.com/13490339/32999913-e1d5b1cc-cd72-11e7-9793-32434a0fb4fa.jpeg)

### Steps to reproduce
N/A (feature request)

**Comment by wodCZ** [comment]
See this commit: https://github.com/aksonov/react-native-router-flux/commit/03ea875b554d6857289274dea4b3c37b117bebca#diff-06256c97a1b294653af6f5dfc597dcaaR14

It already has `hitSlop` ( [documentation](https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#hitslop) ). 

This change is already present in version you are using, so maybe try tweaking these numbers on your local copy - at least file referenced in link above should be place to start.

**Comment by wbattel4607** [comment]
Okay, I'll take a look. Thanks!
