### ISSUE TITLE
router flux not showing camera component

### ISSUE THREAD

**Issue by nestormejia98** [aksonov/react-native-router-flux#2632]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.43
-react-native-camera v0.12
- react-native v0.49.5

### Expected behaviour

Open the camera when calling the component QrScanner

### Actual behaviour

Showing a blank screen, I was able to tell it was my component because i've conditioned my render with some state variables

### Steps to reproduce

1. new project, install router-flux and react-native camera
2. Create three components: Login, Menu and QrScanner
3. Routing:
         from Login to Menu and from Menu to QrScanner

PS. I've tested rendering just the QrScanner component before installing router-flux and worked fine so I assume it's not an issue with the component.

**Comment by wodCZ** [comment]
You are using version 3.43, which is not supported.
Also, steps to reproduce are too generic. Without specific code example (like one created using https://snack.expo.io/) you will probably not get any help.
