### ISSUE TITLE
Router flux doesnt accept any props.

### ISSUE THREAD

**Issue by jrsakizci** [aksonov/react-native-router-flux#2633]
Hey there. I am using React-Native Router Flux for 2 days. No matter what i do, i couldnt disable back button, back action or even top bar. It seems router doesnt accept and see any props im sending..

> export default class App extends React.Component {
  render() {
    return (
      <Provider store={createStore(reducers, {}, applyMiddleware(ReduxThunk))}>
        <Router>
          <Stack key="root" onBack={() => {return false}} back={false}>
            <Scene key="login" hideNavbar={true} headerMode="none" hideTabBar={true} component={Login} navigationBarStyle={{ backgroundColor: '#fff', paddingTop: 8, borderBottomWidth: 0, height: 0 }} initial={true} />
            <Scene
              key="tabbar"
              tabs={true}
              tabBarStyle={{ backgroundColor: '#FFFFFF' }}
              showLabel={false}
            >
                <Scene key="home" title="Home" backToInitial={false} hideBackImage={true} component={HomeContainer} icon={TabIcon} />
            </Scene>
          </Stack>
        </Router>
      </Provider>
    );
  }
}

This is what my code looks like. And hideNavbar, headerMode, hideTabBar doesnt even working.. User cant go back to Login page.. But i cant set that up :/

**Comment by aksonov** [comment]
You really need to check Example project first.
