### ISSUE TITLE
popTo doesn't pop back over 2+ same scenes

### ISSUE THREAD

**Issue by wodCZ** [aksonov/react-native-router-flux#2634]
### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.50.3

### Expected behaviour
Please see this PR: https://github.com/aksonov/react-native-router-flux/pull/2179 
I have same issue that should be fixed by that PR. 
Unfortunately this change was overridden by this commit: https://github.com/aksonov/react-native-router-flux/commit/92f055e52d11e0ff8c38bd5f1a5100bc927d5242#diff-98b3594cf65eb9acfce1160c51678d6eR55

### Steps to reproduce
exactly same as in https://github.com/aksonov/react-native-router-flux/pull/2179 

having 2 scenes with same key in current stack beaks `popTo`. Navigation silently fails, without transition to desired scene.

**Comment by wmonecke** [comment]
I am having this same issue right now, only that I have 4 Scenes which I want to 'popBack' to.
They all have different keys.

**Comment by aksonov** [comment]
@wodCZ Sorry about overriding, could you re-submit this PR again?

**Comment by wodCZ** [comment]
@aksonov I wasn't an author of the PR I've referenced (@ulentini was). But I'll have a look if I can re-submit that change.

**Comment by ulentini** [comment]
I just resubmitted the PR, hope it helps.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
