### ISSUE TITLE
Get state of drawer

### ISSUE THREAD

**Issue by GenericJam** [aksonov/react-native-router-flux#2635]
### Version
Tell us which versions you are using: 
Using version ^4.0.0-beta.24 according to package.json

### Expected behaviour
I would think there would be a way to get the state of the drawer like Actions.key.state or something...

### Actual behaviour
I can't find any documentation or anything in the source code I've seen. I've also looked into Drawer for ReactNavigation as this is based on that (?).

**Comment by aksonov** [comment]
You may check state of whole navigation tree and you will see DrawerOpen, DrawerClose keys there
