### ISSUE TITLE
Actions.key() crash issue in Android devices

### ISSUE THREAD

**Issue by RamkumarBPE** [aksonov/react-native-router-flux#2636]
### Version
react-native: 0.47.2

- react-native-router-flux v4.?.? 4.0.0-beta.24
- react-native v0.47.2

### Expected behaviour
App should redirects to the scene specified

### Actual behaviour
App is crashing before Actions.key()

### Steps to reproduce
I have a button, when I click on it I am doing the following process:
1. Through RNFetchBlob I am searching internal storage Android whether the file is present or not?
2. Getting a value from Async 

After these 2 processes, I am redirecting to a new scene
Ex: Actions.myProfile();

The above two steps is executed properly, app crashes in Android when it comes on redirection line. No promise rejection occured,

This happens only in Android. in iOS It is working fine.
Android: OS: 7(Nougat)

Kindly help me on this to overcome this issue

**Comment by Blapi** [comment]
Could you show your code @RamkumarBPE please?

**Comment by aksonov** [comment]
Closed due inactivity
