### ISSUE TITLE
React-Native-Router-Flux and Redux routes state not updating

### ISSUE THREAD

**Issue by thirddimensionstudios** [aksonov/react-native-router-flux#2638]
### Version
- react-native-router-flux v4.0.0-beta.24
- react-native v0.49.0

### Expected behaviour
Redux routes state should be updated on route change.

### Actual behaviour
Redux routes state is initialised with the first route and then is never updated throughout the lifetime of the app.

### Steps to reproduce
Create a project using Redux and React-Native-Router-Flux with Redux Logger and navigate around the app using Actions.routekeyhere(); - the routes state will not change. Adding console.logs in any reducer to show the actions being called will show there are no actions being dispatched to redux from rnrf.

**Comment by davidgeilfus** [comment]
Hi @thirddimensionstudios, did you find a solution to this? I have the exact same problem. Thanks

**Comment by thirddimensionstudios** [comment]
@davidgeilfus Not really, instead I 'bodged' it temporarily by creating my own state to track the navigation and to dispatch navigation events. Not pretty at all but it gets the job done.

**Comment by aksonov** [comment]
Have you checked Example? I see all actions within reducer there. Also have you tried sample from #2115?

**Comment by davidgeilfus** [comment]
Thank you @aksonov, I'll have a look at #2115… Is Example app Redux-based?

**Comment by tonygriv** [comment]
I have the same problem!

**Comment by aksonov** [comment]
Closing, you should really check #2115.
