### ISSUE TITLE
Programatically changing navigationBarStyle not working

### ISSUE THREAD

**Issue by smith64fx** [aksonov/react-native-router-flux#2639]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.50.3

### Expected behaviour

It should change the color to green.

### Actual behaviour

Nothing happens =/

### Steps to reproduce

```
    Actions.refresh({
      navigationBarStyle: { backgroundColor: 'green' }
    })
```

**Comment by hpbl** [comment]
I am having the same problem as well :/

**Comment by smith64fx** [comment]
I solved this issue using my own Header using native-base.

**Comment by aksonov** [comment]
It is not supported, PR is welcome. Solution is to use custom navbar.
