### ISSUE TITLE
jumpToIndex is not a function

### ISSUE THREAD

**Issue by arnsa** [aksonov/react-native-router-flux#2641]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.49.3

### Expected behaviour

When you click on an item in tabbar, it will switch tabs.

### Actual behaviour

If tabs component has "backToInial" prop set to true and if I click on any tabbar item, I get an error saying: "jumpToIndex is not a function".  It worked in beta.22 version, but probably because backToInitial prop didn't exist yet in that version.

**Comment by kenhkelly** [comment]
I'm getting the same behavior

**Comment by PerspectivesLab** [comment]
i get the same, but sometimes on other devices its works

**Comment by mtreilly** [comment]
![image](https://user-images.githubusercontent.com/1463519/33389788-dd644840-d52b-11e7-9c82-c77a508b7331.png)
Use @PerspectivesLab  method, or you can use destructuring like this

`tabBarOnPress: ({scene, jumpToIndex, previousScene})`

**Comment by FuYaoDe** [comment]
Achieve the same function workaround  
```
<Scene key="home" tabBarOnPress={() => { Actions.popTo('page1'); }}>
   <Scene key="page1" component={page1} />
</Scene>
```

**Comment by Alp4ga** [comment]
Hi,

I found an other solution, you change in file react-native-router-flux/dist/navigationStore.js line 245

> jumpToIndex(tab.index);

by 

> tab.jumpToIndex(tab.scene.index);

**Comment by aksonov** [comment]
Should be fixed within latest RNRF
