### ISSUE TITLE
How to call a function in other scene component when onExit scene?

### ISSUE THREAD

**Issue by itsaberi** [aksonov/react-native-router-flux#2642]
### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

`<Scene key="W1" component={W1} title="W1"/>`
`<Scene key="ShowLightbox" component={ShowLightbox} onExit={() => this.onSave()} />`

Hi
I want to call onSave function in W1.
can you help me?

**Comment by frangeris** [comment]
**This issue is not related to the lib itself :/**

But... you could implement state management and _observe_ changes or you could emit an event `onExit` and listen that event in your `W1` component...

**Comment by aksonov** [comment]
Please check latest beta.27, now you can define onEnter, onExit methods as your react component methods.
