### ISSUE TITLE
Back button not working on open item from drawer twice

### ISSUE THREAD

**Issue by greenzeal** [aksonov/react-native-router-flux#2644]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.50.3

### Expected behaviour
I have router below.
expected to go to home after entering setting twice or more time from drawer.
```
<Router>
   <Stack hideNavBar key="root" titleStyle={{ alignSelf: 'center' }}>
        <Scene key="auth">
          <Scene key="login" component={LoginForm} hideNavBar={true} title="Please Login"  panHandlers={null}/>
        </Scene>
          <Drawer key="drawer" contentComponent={SideMenu} drawerImage={MenuIcon} drawerWidth={250} panHandlers={null}>
            <Scene>
              <Scene panHandlers={null} key="dashboard" component={Dashboard} title="AVaStar!" initial/>
              <Scene back panHandlers={null} key="settings" component={Settings} title="Settings"/>
              <Scene back panHandlers={null} key="feedback" component={Feedback} title="Feedback"/>
            </Scene>
          </Drawer>
    </Stack>
</Router>
```
### Actual behavior
Back button not working on open item from drawer twice or more

### Steps to reproduce
1. you swipe drawer on main screen(dashboard)
2. select settings, 
3. settings opened, 
4. open drawer with swipe, 
5. select settings again 
6. settings opened again 
7. back button not responding

**Comment by aksonov** [comment]
Please reproduce the issue with Example project.

**Comment by mightym** [comment]
Same issue here on the Back Button. In my case even the complete view doesn't respond to any click

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
