### ISSUE TITLE
Router Scenes inside Drawer

### ISSUE THREAD

**Issue by mightym** [aksonov/react-native-router-flux#2645]
### Version
- react-native-router-flux@4.0.0-beta.23
- react-native v0.4.95

### Expected behaviour
Maybe I missed the point but shouldn't it be possible to use stacks/scenes insides other view of your application? In my case I need several scenes that represent a navigation tree inside a drawer. First Scene = Level 1, Second Scene = Level 2 etc.

I expected when a Modal can hold a Scene that a drawer could also hold a scene.

### Actual behaviour
Using scenes in a drawer are ignored. Wrapped in a stack, view or just a plain scene are not getting rendered. 

Thanks in advance!

**Comment by aksonov** [comment]
Please check Example project with Drawer.

**Comment by mightym** [comment]
Just to ensure: this question is not about handling content in the drawer like you do by https://github.com/aksonov/react-native-router-flux/blob/master/Example/components/drawer/DrawerContent.js in the example.

The question was: is is possible to use as content of a drawer its own routing. Like that a drawer could hold 3 scenes.

**Comment by mightym** [comment]
@aksonov I my case I want to have a 3 steps in the drawer. 
First step -> Scene 1, Second step -> Scene 2 , Third step -> Scene 3

I tried to use a own stack with scenes in the component that got passed here https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L131

But this didn't work. So as you closed this I assume its not possible?

**Comment by aksonov** [comment]
Probably yes, it is not possible with RNRF

**Comment by mightym** [comment]
Thanks!
