### ISSUE TITLE
reactNativeRouterFlux.Actions.SignUp is not a function

### ISSUE THREAD

**Issue by atchuthsai468** [aksonov/react-native-router-flux#2647]
I'm using react-router-flux module and getting an error like
reactNativeRouterFlux.Actions.SignUp is not a function,
reactNativeRouterFlux.Actions.SignUp is undefined
![screen shot 2017-11-24 at 2 24 44 pm](https://user-images.githubusercontent.com/32636257/33203155-251dd6de-d125-11e7-9aca-92b3abf1202f.png)

**Comment by aksonov** [comment]
Sorry, it is question not issue and must be posted at stackoverflow. This error usually means that actions are not generated yet but you are using them already

**Comment by bilalma** [comment]
Is there any one can solve this problem i'm also facing this problem.
