### ISSUE TITLE
Open Drawer on rotate screen.

### ISSUE THREAD

**Issue by manoj2166** [aksonov/react-native-router-flux#2648]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.21
- react-native 0.50.3

### drawer menu open in screen rotation.
       I have issue with this When I am going to rotate screen, drawer menu open and close  slightly 

### Actual behaviour
        drawer menu should not open in screen rotation.

**Comment by aksonov** [comment]
Sorry, it is how built-in react navigation drawer works now. Maybe you could you latest version. If the bug is still there, create the issue within react-navigation github repo.

**Comment by nguyenvanphuc2203** [comment]
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-08-13 at 16 13 46](https://user-images.githubusercontent.com/33291479/62929802-6586bc00-bde5-11e9-8900-af716d8d5d53.png)
exacly my issue
