### ISSUE TITLE
Initial scene mounted twice

### ISSUE THREAD

**Issue by enguerranws** [aksonov/react-native-router-flux#2651]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native v0.48.3

### Expected behaviour

When the app loads, the router should mount the initial scene component once.

### Actual behaviour

Right now, I'm using this simple example : 

```
             <RouterWithRedux style={styles.mainViewContainer}>
                <Stack key="root" hideNavBar>
                  <Scene
                      key="splashscreen"
                      initial
                      component={Splashscreen}
                      title="Splashscreen"
                  />  
                </Stack>

            </RouterWithRedux>
```

And a simple console.log() into `Splashcreen`'s `componentDidMount`. 

Whatever I do, the log is fired twice. I don't see any reason for that.

Any idea how to solve that?

**Comment by kyhnlbyrk** [comment]
I had the exact problem. I solved it with a wrapper scene. 

> <RouterWithRedux style={styles.mainViewContainer}>
                <Stack key="root" hideNavBar>
                 <Scene key="wrapperScene">
                  <Scene
                      key="splashscreen"
                      initial
                      component={Splashscreen}
                      title="Splashscreen"
                  />
                </Scene>  
                </Stack>

            </RouterWithRedux>

and, when you are calling that scene, you should write Actions.wrapperScene()

**Comment by alexwasner** [comment]
Noticing the same behavior. The constructor is called twice. If I navigate from one stack to another, it will mount the initial `Scene` of the second stack before mounting the scene I'm trying to navigate to.

**Comment by davidwadge** [comment]
Also having this issue with react-native: 0.48.4 / react-native-router-flux: 4.0.0-beta.22, yet to find a workaround either.

**Comment by davidwadge** [comment]
I've finally managed to stop my component mounting twice by adding `type={ActionConst.REPLACE}` onto the scene in my routes file.

`export default (

     Actions.create(
        <Scene navBar={NavigationBar} hideNavBar>
            <Stack key="PreLoginStack">
                <Scene key="Home" component={Home} type={ActionConst.REPLACE} hideNavBar/>
            </Stack>
        </Scene>
     )`

**Comment by aksonov** [comment]
Strange, RNRF just passes routing to react navigation, so it could be react navigation issue. Please check core examples and re-open issue if it works fine there.

**Comment by vijaya06** [comment]
Also having this issue with react-native: 0.54.0/ react-native-router-flux: 4.0.0-beta.28.

**Comment by Leadrive** [comment]
+1
https://github.com/SurpassRabbit/react-native-template
If you add
    componentDidMount() {
        console.log('Test1 componentDidMount')
    }
into Test1.js

you can see twice componentDidMount

**Comment by sandeep-sethia** [comment]
> I had the exact problem. I solved it with a wrapper scene.
> 
> > 
> 
> ```
>             <Stack key="root" hideNavBar>
>              <Scene key="wrapperScene">
>               <Scene
>                   key="splashscreen"
>                   initial
>                   component={Splashscreen}
>                   title="Splashscreen"
>               />
>             </Scene>  
>             </Stack>
> 
>         </RouterWithRedux>
> ```
> 
> and, when you are calling that scene, you should write Actions.wrapperScene()

this does not work with the  "react-native-router-flux": "^4.0.6",
