### ISSUE TITLE
TextInput keyboard auto disappears in few seconds.

### ISSUE THREAD

**Issue by syq7970** [aksonov/react-native-router-flux#2652]
### Version
- react-native-router-flux v4.0.0-beta.24
- react-native v0.50.4

this issue is similar to #2442, and still exist in latest version.

Dose someone have a workaround to fix this ?

**Comment by munkhorgil** [comment]
@syq7970 I got the same issue. How did u solve?

**Comment by syq7970** [comment]
@munkhorgil Answer in #2442 , In my case, IndicatorViewPager or something like ViewPager with autoPlay will trigger this issue
