### ISSUE TITLE
Actions.popTo(anyTabSceneKeyInYourApp) breaks and freezes the app.

### ISSUE THREAD

**Issue by wmonecke** [aksonov/react-native-router-flux#2653]
### Version
Tell us which versions you are using: 

"react-native-router-flux": "^4.0.0-beta.22",
"react-native": "0.46.4",

### Expected behaviour
The scene should pop until it reaches the tab bar.

### Actual behaviour
App freezes with no kind of error or message.

### Router.js

```
<Tabs
        lazy
        headerMode="none"
        key="tabBar"
        navBar={NavigationComponent}
        tabBarPosition={'bottom'}
        >
        <Scene
          key="home"
          initial
          component={HomeComponent}
          panHandlers={null}
          />

        <Scene
          key="profile"
          component={ProfileComponent}
          panHandlers={null}
          />

        <Scene
          key="activeJobs"
          component={ActiveJobsComponent}
          panHandlers={null}
          />

        <Scene
          key="favorites"
          component={FavoritesComponent}
          panHandlers={null}
          />

        <Scene
          key="inbox"
          component={InboxComponent}
          panHandlers={null}
          />
      </Tabs>

  <Scene
        key="jobDetailsPhotos"
        hideNavBar
        component={JobTagsAndPhotosComponent}
        panHandlers={null}
      />
```
I am doing Actions.popTo('tabBar') from the scene with the key 'jobDetailsPhotos' but the app just breaks. Am I doing something wrong?

Here is the stackoverflow question: https://stackoverflow.com/questions/47496628/actions-poptotabbarkey-breaks-app-react-native-router-flux

**Comment by aksonov** [comment]
Answered there. Closing.

**Comment by wmonecke** [comment]
Thank you, @aksonov! Could you please elaborate more on your answer? I am still stuck on this.
