### ISSUE TITLE
How disable swipe on drawer navigation 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2658]
### Version
Latest  

Right now in my app if a user swipes to the left from the drawer navigation (when it's open) they are taken back to the login screen, I would like to disable this from happing

**Comment by tonygriv** [comment]
+1

**Comment by Mimicx** [comment]
Add this gesturesEnabled={false} into the Scene

**Comment by tonygriv** [comment]
@Mimicx, you mean drawer scene <Drawer gesturesEnabled={false}/>?

**Comment by aksonov** [comment]
@AlmogRnD Try `drawerLockMode` prop. Check https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode for more details. Docs were updated.

**Comment by edoantonioco** [comment]
I have this 
<Scene initial key="aclaracionesUso" component={AclaracionesUso} title="Aclaraciones de uso" hideNavBar={true} drawerLockMode='locked-closed' gesturesEnabled={false} />

And it does not work.
It does hide the navBar, but it still allow to see the drawer
