### ISSUE TITLE
onEnter and onExit callback

### ISSUE THREAD

**Issue by iwangx** [aksonov/react-native-router-flux#2659]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.23
- react-native v0.50.2

I hope that after the page jumps, the current page will execute a function to show the current page entry, no matter which page comes in. If the current page left, I also hope to have a function to perform, whether it is to go to the page, and these functions should be in the specific component which calls rather than on the properties above Scene, as onEnter and onExit should be in component inside the back instead of in Scene.

**Comment by aksonov** [comment]
Please check latest beta.27, now you can define `onEnter`, `onExit` methods as your react component methods.

**Comment by shukerullah** [comment]
@aksonov Example?

**Comment by BatDroid** [comment]
@aksonov would please tell how to do it?

**Comment by shukerullah** [comment]
Here is example working for me, write these methods in your react component.

```
static onEnter() {
  ...
}

static onExit() {
  ...
}
```

**Comment by BatDroid** [comment]
@shukerullah thanks but it seems that onEnter onExit is added to beta.27 but neither of them works even if i want to call them like this its not working 
<Scene key="x" component={X} hideNavBar={true}  onEnter={() => X.onEnter()}/>

**Comment by e3bmo3ty** [comment]
why this closed.....no one provide a working example for now :(
