### ISSUE TITLE
How to change scene outside of onPress()

### ISSUE THREAD

**Issue by ralphpina** [aksonov/react-native-router-flux#266]
I am brand new to React Native and Javascript, so this may be a dump question. But... How do you kick off a scene change outside of the ```onPress()``` callbacks shown in your samples and docs?

This works fine:
```javascript
<TouchableHighlight
    onPress={Actions.LoginScreen}>
    <Text style={styles.buttonText}>Go Login Screen</Text>
</TouchableHighlight>
```

However this does nothing. The console statement prints fine.
```javascript
componentDidMount() {
    let auth = Realm.objects('Authorization');
    if (auth.length == 0) {
        console.log("going to login!");
        Actions.LoginScreen;
    }
}
```

I know that `Actions.LoginScreen` is not a method, so it does nothing there. But I can't seem to figure out how to get it working outside outside of ```onPress()```. Any chance something can be added to the docs?

**Comment by aksonov** [comment]
It is not question about this component but about Javascript, please post them at Stackoverflow. Actions.LoginScreen is function, why you don't call Actions.LoginScreen() ? Also it may not exist on this stage, so you could use `setTimeout(()=>Actions.LoginScreen())`

**Comment by ralphpina** [comment]
> It is not question about this component but about Javascript

Yeah... see this:

> I am brand new to React Native and Javascript

So clearly I'm still learning the difference. But yeah, it was a lifecycle issue.

Thanks for the quick response!
