### ISSUE TITLE
Rerender root <Router> component.

### ISSUE THREAD

**Issue by hosembafer** [aksonov/react-native-router-flux#2661]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.50.4

### Expected behaviour
I want to rerender root <Router> component

### Actual behaviour
setState is not rerendering <Router> component, is there any solution?

**Comment by morfsys** [comment]
Use Actions.refresh
