### ISSUE TITLE
Can I use a single tab bar button as a regular button, without rendering a component from it?

### ISSUE THREAD

**Issue by Jahans3** [aksonov/react-native-router-flux#2663]
Hi, first of all thanks for the ace library! I have a question regarding using tab bar buttons for things other than rendering a scene.

I want to have the button act like a button and not try to render anything.

### Version
Tell us which versions you are using: 4.0.0-beta.24

### Expected behaviour
I want to add a function to be called when a user presses a tab button.

### Actual behaviour
There is an error saying that `<Scene />` expects a component to render.

### Steps to reproduce
I had quickly tried omitting the `component` prop (it says it's semi-required in the docs, but couldn't find anything in the example!) and also adding a function to the `on` prop:
```
<Scene
  tab
  title='More'
  key='more'
  headerMode='none'
  on={doSomething}
  uri={SITE_URL}
  icon={TabBarIcon({ src: setting3 })}
/>
```

Is this possible? Or do I need to use a custom tab bar?

Thanks!

**Comment by aksonov** [comment]
Use tab container and then define inner 'tab' components. For those components you may add onEnter, onExit methods.

**Comment by bneigher** [comment]
@aksonov can you be a little more illustrative?  I'm not sure how to follow your instructions.  Can't seem to find out how to add a Scene in a Tab stack that doesn't require a component / key prop.  Regular components (like a Button) don't work
