### ISSUE TITLE
Access component method from custom navigation bar

### ISSUE THREAD

**Issue by iCodePup** [aksonov/react-native-router-flux#2665]
Hello
I have a Scene with custom navbar 

  ```
     <Scene
                            navBar={CustomNavBar}
                            component={MComponent}                   
            
                        />
```
MyCOmponent have on method called _hello()

```
export default class MComponentextends PureComponent {
    constructor(props) {
        super(props);     
    }
    _hello = () => {
        console.warn('HELLO WORLD')
    }
```

Is it possible to call MyComponent _hello() method inside my navbar component ?

```
export default class CustomNavBar extends Component {
    constructor(props) {
        super(props);
        this.state = {        
        };
        this.props._hello () // does not work
    }
}
```

Thanks for help.

**Comment by iCodePup** [comment]
Maybe someone can tell me how can i submit one form with props inside my component from a button inside my custom navbar ?
So, maybe i can access all form props in my component with Actions.refs.MyComponent and submit form with a method inside navbar ?
 
Should i use redux/mobx or  native react-router-flux can do the trick ?

**Comment by markmorcos** [comment]
@iCodePup did you manage to reach a solution? I am facing the same problem and I'm not sure what is the best practice.

**Comment by iCodePup** [comment]
Hello @markmorcos ,no i put the navigation bar component directly into the main component... But i think the best way is to use redux/ mobx . Btw i am not using rnrf anymore..

**Comment by markmorcos** [comment]
@iCodePup That's what I ended up doing; adding the navigation bar component in my component. Can you explain how it could be done using Redux? I need to pass values from my component's React state to the Redux action.

**Comment by aksonov** [comment]
The only way now is to use `Actions.refs.SCREEN_NAME`
