### ISSUE TITLE
Add just button in Drawer

### ISSUE THREAD

**Issue by Psyycker** [aksonov/react-native-router-flux#2667]
Hello, I want a bottom bar with react native router flux but I want 5 buttons  : 

2 first are for profile and promotions pages,

3rd is just a button to start geolocating my phone but I don't want to show a view, just start a little service

And 2 lasts are for 2 others pages.

But I don't know if it's possible to add juste a button in a tabbar.

Do you have an idea ?

**Comment by aksonov** [comment]
Sorry, it is not issue but the question, use stackoverflow for this.
