### ISSUE TITLE
Moving the Nav Bar Leaves Black Bar in its Place

### ISSUE THREAD

**Issue by SSTPIERRE2** [aksonov/react-native-router-flux#2671]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.23
- react-native ^0.50.3

### Expected behaviour
I can move the nav bar from its original position (at the top) to somewhere of my choosing, like at the bottom of the screen, a common iOS UX pattern.

### Actual behaviour
Using a navigationBarStyle like `navigationBarStyle={{ backgroundColor: '#26a69a', top: 300 }}` effectively moves the nav bar from its original position, but leaves a black view of its same dimensions in its place (it actually takes up that space). See screenshot: https://www.dropbox.com/s/yjmxozsd5fyl5aj/Screenshot%202017-12-01%2009.26.27.png?dl=0

### Steps to reproduce
1. Define some boilerplate for a router and a scene
2. Set the navigationBarStyle to something like `navigationBarStyle={{ backgroundColor: '#26a69a', top: 300 }}`to move the nav bar from its original position
3. Inspect the black bar at the top of the screen and notice it comes from createAnimatedComponent.js

### Conclusion
My team and I made an iOS app using RNRF v3 and did manage to put the nav bar on the bottom of the screen by passing a navigationBarStyle. Is this not intended in v4? 

Is moving the nav bar to the bottom of the screen something people do? Is it valid? Is there some other way to achieve a similar function, like a tab bar?

This issue is similar to https://github.com/aksonov/react-native-router-flux/issues/1218.

**Comment by SSTPIERRE2** [comment]
@aksonov is this intended?

**Comment by aksonov** [comment]
You should really check react navigation component and create issue there (if any), because RNRF is just useful wrapper.

**Comment by SSTPIERRE2** [comment]
Okay thanks!
