### ISSUE TITLE
back/pop does not go back to previous scene

### ISSUE THREAD

**Issue by amitava82** [aksonov/react-native-router-flux#2672]
With following sctructure
```
<Tabs key="rootTabs">
  <Stack key="mine" hideNavBar title="MINE">
    <Tabs
      key="mineTabs"
      tabBarPosition="top">
      <Scene key="attending" component={Attending} title="Attending" hideNavBar />
    </Tabs>
  </Stack>
  <Stack key="chatTab" title="CHAT">
    <Scene key="conversations" component={ConversationList} title="Conversations" />
    <Scene key="conversation" component={Conversation} hideTabBar back />
  </Stack>
</Tabs>
```
### Version
Tell us which versions you are using: 
- react-native-router-flux 4.0.0-beta.24
- react-native0.50.3

### Expected behaviour
Navigating from `attending` to `conversation` scene and then pressing back button should take me back to `attending`, not `conversations`

### Actual behaviour
From `attending` scene I'm navigating to `conversation` scene. Back button should take me back to `attending` but it is taking me back to `conversations`.

**Comment by amitava82** [comment]
@aksonov checking if you saw this.

**Comment by aksonov** [comment]
@amitava82 It is how react navigation for tabs works.
