### ISSUE TITLE
backgroundColor don't work in sceneStyle (Scene, Modal, Router)

### ISSUE THREAD

**Issue by den666** [aksonov/react-native-router-flux#2673]
### Version

- react-native-router-flux v4.0.0-beta.24
- react-native v0.49.3
I use: sceneStyle={{backgroundColor: '#000'}}  , but the background don't change in Router, Modal, Scene

**Comment by tevatahiti** [comment]
It does work with:
-react-native: 0.50.4
-"react-native-router-flux": "^4.0.0-beta.24"
`<Router sceneStyle={{ backgroundColor: '#fff' }}>`

**Comment by den666** [comment]
thanks @tevatahiti ; now, how i can change the default background or styles on scenes or router, have some documentation for this version

**Comment by tevatahiti** [comment]
I believe the doc for v4 is not yet ready as version is still in beta
