### ISSUE TITLE
BackTitle dont work Android

### ISSUE THREAD

**Issue by remch1990** [aksonov/react-native-router-flux#2675]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?
"react-native-router-flux": "^4.0.0-beta.24",
- react-native?
"react-native": "^0.48.3",

backTitle={'back'} 
Dont show nothing on Android

**Comment by Blapi** [comment]
Where do you implement this? Show your exact code please @remch1990 because it's difficult to help you there

**Comment by Blapi** [comment]
Moreover, backTitle requires a string, you pass an object there

**Comment by remch1990** [comment]
with the Example code backTitle don't works on Android, this with the last update RNRF, with version 22 it works.
```
<Scene
            key="loginModal2"
            component={Login2}
            title="Login2"
            backTitle="Back"
            panHandlers={null}
            duration={1}
          />
```

**Comment by remch1990** [comment]
??

**Comment by aksonov** [comment]
@Blapi could you look on this android issue?

**Comment by Blapi** [comment]
Ok so after investigated on this, the point is that on NavBar.js

```
  if (!state.backButtonImage) {
    return (
      <HeaderBackButton
        onPress={onPress}
        title={state.backTitle}
        titleStyle={textButtonStyle}
        tintColor={tintColor}
        truncatedTitle={state.truncatedTitle}
      />
    );
  }
```

When you don't pass a backButtonImage, it should return this Component from react-navigation but this component is returning an Image with the back-arrow, so the backTitle is ignored.

So 2 solutions, either we implement an other Component which will be an other HeaderBackButton with the result we wish (requiring a PR), or either passing a fake path as backButtonImage, so the backTitle will be displayed but with a warning (quick crappy fix).

**Comment by arif2009** [comment]
@Blapi In my case BackButton shows and works fine but problem is 1st row it shows BackButton and 2nd row it shows Title like my screenshot, they are not showing together.
