### ISSUE TITLE
Error: [react-native-router-flux] unique key should be defined

### ISSUE THREAD

**Issue by CoderHar** [aksonov/react-native-router-flux#2676]
import React from 'react';
import { Scene, Router,Actions } from 'react-native-router-flux';
import LoginForm from '../src/LoginForm';
import EmployeeList from '../src/EmployeeList'
import EmployeeCreate from '../src/EmployeeCreate'  

const RouterComponent=()=>{
    return(
        <Router sceneStyle={{paddingTop:55}}>
            
                <Scene 
                       key="Login" 
                       component={LoginForm} 
                       title='Login' />   
                <Scene 
                       key="EmployeeList" 
                       component={EmployeeList} 
                       title='EmployeeList'
                       rightTitle="ADD"
                       onRight={()=>console.log("error")}  />
                <Scene 
                       Key="EmployeeCreate" 
                       component={EmployeeCreate} 
                       title='Employee'  />       
            
        </Router>
    );
}

export default RouterComponent;

**Comment by tevatahiti** [comment]
Which version do you use?

**Comment by CoderHar** [comment]
@tevatahiti 
i use 3.43.0 and couldnt find out what the problem is yet

**Comment by CoderHar** [comment]
i updated my router flux version to 4.0.0 and used stack to wrap up the scenes now  the error is now gone 
but i could not navigate from EmployeeList to EmployeeCreate using onRight and Actions

**Comment by Blapi** [comment]
@CoderHar show your navigation please, how do you do it ?

**Comment by tevatahiti** [comment]
@CoderHar I see onRight={()=>console.log("error")}  in you EmployeeList scene
The function should call Actions.EmployeeCreate() (in actionsCreator if you use Redux)

**Comment by CoderHar** [comment]
@tevatahiti im sorry it was actually used for checking whether the onRight works or not.even if i change onRight to Actions.EmployeeCreate it doesnt work

**Comment by Blapi** [comment]
Even with Actions.EmployeeCreate**()** ? Did you try it?

**Comment by Blapi** [comment]
@CoderHar Show more of your code and the error messages because you don't really help here

**Comment by CoderHar** [comment]
@Blapi see i want to put my navigation to emplyeecreate in theat onRight part but i couldnt do it with Actions.EmployeeCreate so that i put there a console.

**Comment by Blapi** [comment]
Please @CoderHar, show your exact code and show the error message

**Comment by CoderHar** [comment]
@Blapi Check out the code that i have chenged and the employeeCreate component
        import React,{Component}from 'react';
        import { Scene, Router,Actions,Stack } from 'react-native-router-flux';
        import LoginForm from '../src/LoginForm';
        import EmployeeList from '../src/EmployeeList'
        import EmployeeCreate from '../src/EmployeeCreate'  
        import * as actions from './actions'
        import { connect } from 'react-redux';

       class RouterComponent extends Component{
        
           render(){
            return(
                <Router sceneStyle={{paddingTop:0}}>
                    <Stack key='root'>
                        <Scene 
                            key="Login" 
                            component={LoginForm} 
                            title='Login' />   
                    
                        <Scene 
                            key="EmployeeList" 
                            component={EmployeeList} 
                            title='EmployeeList'
                            rightTitle="ADD"
                            onRight={()=>Actions.EmployeeCreate()}  />
                          
                   
                        <Scene 
                            Key="EmployeeCreate" 
                            component={EmployeeCreate} 
                            title='Employee'  />  
                     
                    </Stack>
                </Router>
            );
        }
        }
       /*const mapStateToProps=state=>{
          return  {authentication:state.authentication}
        } */
    
 export default connect(null,actions )(RouterComponent);

**Comment by CoderHar** [comment]
import React,{Component} from 'react'
import {Text, View} from 'react-native'
 class EmployeeCreate extends React.Component{
     render(){
         return(
            <View/>
         );
     }
 }

export default EmployeeCreate;

**Comment by CoderHar** [comment]
@Blapi  the error is the **Actions.EmployeeCreate is not a function**

**Comment by Blapi** [comment]
@CoderHar ,
`                    <Scene 
                        Key="EmployeeCreate" 
                        component={EmployeeCreate} 
                        title='Employee'  />  `

key and not Key

**Comment by CoderHar** [comment]
@Blapi  could you please be more specific i couldnt get you

**Comment by Blapi** [comment]
You wrote key with a capital K on your EmployeeCreate scene, it is key with a lowercased k, not a uppercased k (key !== Key)

**Comment by CoderHar** [comment]
really really thank you @Blapi

**Comment by Blapi** [comment]
@CoderHar no problem, I guess you can close this issue ;)

**Comment by CoderHar** [comment]
@Blapi sure

**Comment by aksonov** [comment]
@Blapi thank you for help!. As you can see most issues here are not issues, but questions - you may redirect them to stackoverflow and answer there with getting all benefits. Also I can make you collaborator to deal with it if you wish.

**Comment by Blapi** [comment]
@aksonov yep sure I'd like that !

**Comment by aksonov** [comment]
Done. Please be careful with PR merging - the code should be reviewed and tested before

**Comment by Blapi** [comment]
Sure, btw could you help me with this please ? #2628 , more and more users (like me) would love information about this. We can talk about this in DM on Twitter if you want, I already follow you
