### ISSUE TITLE
Navbar title - translation

### ISSUE THREAD

**Issue by compojoom** [aksonov/react-native-router-flux#2677]
I'm using i18n https://github.com/AlexanderZaytsev/react-native-i18n to translate our app.
I'm trying to implement a "hot reload" of the languages. The user selects a language and the UI updates. Now this works, but It doesn't work with the navbar titles. I have to restart the app in order for the changes to take effect.
my scenes are defined like this:
```
          <Scene hideNavBar={false}
                 gestureEnabled={true}
                 gestureResponseDistance={{horizontal: 50}}
                 renderBackButton={renderBackButton} key="settings"
                 rerender={this.state.rerender}
                 {...styles} component={Settings}
                 title={I18n.t('settings')}/>
```

I'm triggering a rerender in the component that defines the scenes. A console.log of I18n.t('settings') shows the translated string, but the title is not translated. Same applies to tab titles. 
Is there a way to refresh the titles without having to rely on refreshing in componentWillMount in the component itself. I have defined like 40 scenes and it would be stupid to have to use componentWillMount to update the title?

**Comment by aksonov** [comment]
Try to pass function instead of value.

**Comment by todorone** [comment]
@compojoom As a workaround, You can re-render top-level component which contains `Router` component with whole navigation tree, then probably all `title` props will be recalculated?

**Comment by aksonov** [comment]
Closed due inactivity

**Comment by compojoom** [comment]
@aksonov - thanks. Using a function for the titles worked.

**Comment by OlivierGagnon07** [comment]
I used this and it worked.

`<Scene hideNavBar={false}
                 gestureEnabled={true}
                 gestureResponseDistance={{horizontal: 50}}
                 renderBackButton={renderBackButton} key="settings"
                 rerender={this.state.rerender}
                 {...styles} component={Settings}
                 title={**() =>** I18n.t('settings')}/>`

**Comment by 1453alabanda** [comment]
> Try to pass function instead of value.

hey @aksonov , this was exactly what i was looking for. Thanks very much
