### ISSUE TITLE
Simple Draw menu on HomeScreen only

### ISSUE THREAD

**Issue by serialbandicoot** [aksonov/react-native-router-flux#2678]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
4.0.0-beta.24
- react-native v0.?.?
0.45.1

### Expected behaviour
Drawer

### Actual behaviour

I'm trying to do a real simple drawer with hamburger menu from home screen. So when I click on the Drawer it open a left menu with some links.

```
 <Router>
     <Scene>
        <Scene key="home_screen" component={ HomeScreen } title="title" initial/>
         <Scene key="article_screen" component={ FirstScreen } title="App"  backTitle={' '}/>
    </Scene>
  </Router>
```

If I use `<Scene drawer>` then I get the draw and I can put components into the side menu, however when I select some from HomeScreen to Open FirstScreen. I still get the hamburger icon. 

I only want drawer active on the home screen. Any help would be appreciative!

**Comment by serialbandicoot** [comment]
So I tried the following and although it does kind of what I'm after the displaying of the nav bar is awful. It just keeps sliding up and down.

```
<Scene>
   <Drawer>
         <Scene key="home_screen" component={ HomeScreen } title="App"  initial/>
    </Drawer>
   <Scene key="article_screen" component={ ArticleScreen } title="App"  backTitle={' '}/>
 </Scene>
```

**Comment by serialbandicoot** [comment]
After a bit of fiddling around, you can use hideDrawerButton, however it then means the back button uses the last title, which cannot be overwritten with backTitle.

```
<Router>
                <Drawer key="drawer" contentComponent={DrawerContent} drawerWidth={300} >
                     <Scene hideNavBar>
                         <Stack>
                             <Scene key="home_screen" component={ HomeScreen } title="App" initial/>
                             <Scene key="article_screen" component={ SecondScreen } title="App" hideDrawerButton/>
                         </Stack>
                     </Scene>
                </Drawer>
            </Router>
```

**Comment by nica0012** [comment]
I am having the same issue, did you resolve this at all?
