### ISSUE TITLE
Is it possible to render tabs when the tab is pressed 

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2680]
With the current version it loads the tabs once and only runs the component did mount when the tab is first pressed but I need to update my component when the tabs is pressed again is that possible?

**Comment by eli0shin** [comment]
I am having a similar issue. I need to add a handler when leaving a tab, in addition, nested scenes change the status bar color but being that they are still mounted at a higher level when i navigate to another tab the status bar color does not update to the color defined by the new scene.

**Comment by AlmogRnD** [comment]
I just did a workaround, not the best option but I'm using redux-subscriber to listen to my redux change and based on renderer the component 

```
// Subscribers to selected team change
        this.subToSelectedTeamChangeApps = subscribe('selectedTeam', state => {
            const random = Math.random() * (100 - 15) + 15;

            // Updates the state with a random key so the list view will force an update
            this.setState({key: random}, function () {
            }.bind(this));
        });
```

**Comment by aksonov** [comment]
Now you can use onEnter/onExit method within your react component for tabs.
