### ISSUE TITLE
TabView: Android hardware Back-button transitions backwards through tabs

### ISSUE THREAD

**Issue by asciifaceman** [aksonov/react-native-router-flux#2683]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour
Default behavior here is for the tabs to load into the "profile" stack and PrivateProfileTab scene. Everything looks and swipes as expected. No erroneous scene transitions should occur. If android back button is hit in a Tab stack, the scene returns to the `initial={true}` tab.

### Actual behaviour
However, if say on android the hardware "back" is hit, it goes backwards through the tabs. So friends -> profile -> settings -> further back the routing stack to what led to the TabView. Normally this would be fine as a pop behavior for push'd scenes, but the tab central illusion is broken by it.

This may just be a case of me not finding a silly stupid answer in my searches 

### Steps to reproduce
```
                <Tabs
                  key="tabexample"
                  swipeEnabled
                  showLabel={false}
                >
                  <Stack
                    key="settings"
                    title="Settings"
                    renderTitle={false}
                    tabBarLabel="Settings"
                    inactiveBackgroundColor="#FFF"
                    activeBackgroundColor="#DDD"
                    icon={TabIcon}
                  >
                    <Scene key="SettingsTab"
                      component={SettingsTab}
                      animation='fade'
                      hideNavBar={false}
                      initial={false}
                    />
                  </Stack>
                  <Stack
                    key="profile"
                    title="Your Profile"
                    tabBarLabel="Your Profile"
                    inactiveBackgroundColor="#FFF"
                    activeBackgroundColor="#DDD"
                    icon={TabIcon}
                  >
                    <Scene key="PrivateProfileTab"
                      component={PrivateProfileTab}
                      animation='fade'
                      hideNavBar={false}
                      init={true}
                      onEnter={this.onEnter}
                      initial={true}
                    />
                  </Stack>
                  <Stack
                    key="friends"
                    title="Friends"
                    tabBarLabel="Friends"
                    inactiveBackgroundColor="#FFF"
                    activeBackgroundColor="#DDD"
                    icon={TabIcon}
                  >
                    <Scene key="FriendsListTab"
                      component={FriendsListTab}
                      animation='fade'
                      hideNavBar={false}
                      initial={false}
                    />
                  </Stack>
                </Tabs>
```

**Comment by asciifaceman** [comment]
Actually, would this be a case of using 

```
BackHandler.addEventListener('hardwareBackPress', function() {
});
```

to ensure it returns to the central tab? Would this not interfere when you navigate away from the tab view to single purpose push/pop scenes?

**Comment by todorone** [comment]
@asciifaceman You can override the default behavior of back button by passing function handler to `Router` component via `backAndroidHandler` prop.

**Comment by asciifaceman** [comment]
Thanks for the info @todorone I'll play around with it. Do you know of any projects with this that I could reference for a better idea?

**Comment by asciifaceman** [comment]
@todorone I've now tested it and found that backAndroidHandler seems to just be ignored.

**Comment by aksonov** [comment]
@Blapi Could you please check this android issue?

**Comment by asciifaceman** [comment]
Yeah I can provide some more details later, but when I was playing around with it I found that for some reason my state index was *always* 0 so  I Couldn't seem to write any logic around when back should pop or when it should exit. I wanted to write a somewhat elegant back handler for android.

**Comment by aksonov** [comment]
@asciifaceman Check example. It should just work with default (built-in) handler.

**Comment by asciifaceman** [comment]
Did you add the `back` prop? I'll grok it a bit. I know this isn't the appropriate place, but could you also give me a a very very quick/brief idea of what the Reducer is for?

**Comment by aksonov** [comment]
Just check Example project. Reducer is to demonstrate redux integration

**Comment by aksonov** [comment]
Btw, I'm talking about is about exit app with hardware back button.

**Comment by asciifaceman** [comment]
Yeah I'm looking at the example just doesn't explain context of things. I only asked that as an aside because I saw it around but couldn't grok it.

The back stuff I'll test tonight

**Comment by Blapi** [comment]
@asciifaceman what do you mean ?

> @todorone I've now tested it and found that backAndroidHandler seems to just be ignored.

**Comment by asciifaceman** [comment]
I solved this by just writing some backHandler logic. It's a little
