### ISSUE TITLE
Help: Custom Animations between scenes 

### ISSUE THREAD

**Issue by tjsaini007** [aksonov/react-native-router-flux#2684]
Hello,

I'm new to react native technology. I need to add animations between one to another scenes for now here is only Left to Right and Bottom to Top.
Can anybody help me to add custom animations for transition.
please help me with source code, demo or if anyone have useful link please share here.

Thank you.

**Comment by Blapi** [comment]
Hey @tjsaini007 , follow this issue : #2628 , be sure you'll have the informations as soon as possible !

**Comment by tjsaini007** [comment]
Hello @Blapi , thanks for your instant reply but the provided link #2628 , does not work for me as I am not talking about the default "Left to Right" or "Bottom to Top" animation provided by react-native-router-flux. All I need is to animate two screens with some blur ,fade, focus in, focus out, bounce etc. effects , which are to be customized at our end. So i need help with some source code or demo regarding the same and this issue can not be closed now as the problem still prevails.

**Comment by Blapi** [comment]
Yes I understood your issue, it is the same for me, I need to do custom animations/transitions. If you recheck the issue #2628 , you will see that aksonov replied to it. I'm about to investigate on what he said and will update my own issue.
