### ISSUE TITLE
onPress Event for Scene Title

### ISSUE THREAD

**Issue by GopiKrishna10** [aksonov/react-native-router-flux#2686]
Hi @aksonov and Guys,

I don't Know whether this option is availabe in this library.i searched for a solution to solve this functionality from two days but am not able to solve this .Actually what i need is every scene has a title.For that Specific Scene title i need to give a onpress event.when i click on title need to show specific Scene.How i should give the onpress event for title.I tried to give a component for rendering the title.But its showing an error message (i.e) "views nested within a <Text> must have a width and height".I gave width and height for the text and View.but again showing the same error.Could you please help me guys.

### Version
Tell us which versions you are using: 

- react-native-router-flux : "3.37.0"
- react-native : "^0.39.0"

### Expected behaviour
When i press on the title it redirects to the specific scene

### Actual behaviour
showing error like  "views nested within a <Text> must have a width and height"

### Steps to reproduce

1.I gave the value for title is like <Scene title='Food'/>
2.In My Component wrote something like Actions.key({'title':<NewTitle/>}).
3.Am giving screen shots of my code.better to understand more Guys

![screen shot 2017-12-08 at 3 15 55 pm](https://user-images.githubusercontent.com/7385834/33760559-10a59694-dc2c-11e7-95c9-6828d620a41e.png)
Component for New Title
![screen shot 2017-12-08 at 3 24 01 pm](https://user-images.githubusercontent.com/7385834/33760603-359eb4c6-dc2c-11e7-86d4-33706bad73d9.png)

![screen shot 2017-12-08 at 3 24 41 pm](https://user-images.githubusercontent.com/7385834/33760669-7073232a-dc2c-11e7-8b62-786cb70fc20d.png)

**Comment by Blapi** [comment]
You should maybe use this prop in your scene : `renderTitle`, it should help you doing the logic you want.

**Comment by GopiKrishna10** [comment]
@Blapi ,

I added this line in my scene  renderTitle={<TitleNavBar />}.getting error be like renderTitle is not a function

**Comment by Blapi** [comment]
renderTitle expects a ReactComponent

**Comment by GopiKrishna10** [comment]
Yes, i gave the Component like am sending screen shots as reference
![screen shot 2017-12-08 at 10 38 29 pm](https://user-images.githubusercontent.com/15904913/33776906-de025c26-dc68-11e7-805c-60c7369a8bbd.png)


![screen shot 2017-12-08 at 10 39 52 pm](https://user-images.githubusercontent.com/15904913/33776888-d5747832-dc68-11e7-8dc3-e56f4a6aa38a.png)

**Comment by Blapi** [comment]
Show your error please ?
Moreover, I think you should add a return in your renderNewTitle function in your TitleNavBar component

**Comment by aksonov** [comment]
renderTitle should be a function

**Comment by GopiKrishna10** [comment]
Yes, 
I forgot that before,after that i added that return. i saw the same error @Blapi 

![simulator screen shot dec 8 2017 10 48 11 pm](https://user-images.githubusercontent.com/15904913/33777237-0d51b5fc-dc6a-11e7-93ea-f7446e69d48d.png)

**Comment by Blapi** [comment]
Aaah.. I see you're using RNRF V3 and not v4, maybe renderTitle is not available in the V3, you should update RNRF's version!

**Comment by GopiKrishna10** [comment]
Thanks @Blapi. I will check and let you know.

**Comment by GopiKrishna10** [comment]
Hi Guys and @Blapi ,

 I upgraded the RNRF V3 to V4.After  Running the Project am seeing errors like 
![simulator screen shot dec 13 2017 3 32 09 pm](https://user-images.githubusercontent.com/15904913/33933139-d59769d6-e01a-11e7-8f97-c3f41923e8f9.png)
Should i need to update the React-native version ?
am using the React-native -  "^0.39.0"

**Comment by Blapi** [comment]
Show your code please yes !
And I strongly suggest you to upgrade react-native as well, you will have a more powerful API to work with :) (I'm using RN 0.50.3 and the migration was quick enough, don't worry)

**Comment by GopiKrishna10** [comment]
you mean that routing part.Here you go.
![screen shot 2017-12-13 at 3 46 26 pm](https://user-images.githubusercontent.com/15904913/33933788-d93bfcc6-e01c-11e7-824f-e66443ee4bd1.png)

**Comment by Blapi** [comment]
It is.. weird.. I feel like you should return your Router as it is and not put a Loader (which is not imported?), and then, in your initial scene, you can check if either you should put a Loader or display whatever else you want.

Show me your app.js (where you put your NavigationRouter) please

**Comment by GopiKrishna10** [comment]
Actually i have many lines of code.I removed so much code for sharing purpose.I didn't get the full file screenshot that's why i removed the code.My app.js Code is
![screen shot 2017-12-13 at 3 58 30 pm](https://user-images.githubusercontent.com/15904913/33934322-93c14a64-e01e-11e7-9e16-29b5c7b903f9.png)
Here is RootContainer
![screen shot 2017-12-13 at 4 00 32 pm](https://user-images.githubusercontent.com/15904913/33934410-d34d2072-e01e-11e7-8bf3-18922a5737ea.png)

**Comment by Blapi** [comment]
Which version of RNRF?

**Comment by GopiKrishna10** [comment]
few minutes back i upgraded the RNRF : "4.0.0-beta.24",
Now I update the RN version to 0.50.3. I think for RN 0.50.3 need to update React Version?

**Comment by Blapi** [comment]
You can use this one 16.0.0

**Comment by GopiKrishna10** [comment]
After the updating the RN(0.50.3) and React(16.0.0).getting errors while running the project in xcode @Blapi .
![screen shot 2017-12-13 at 4 16 35 pm](https://user-images.githubusercontent.com/15904913/33935210-226ef70a-e021-11e7-99ab-32f3afa30b6b.png)

**Comment by Blapi** [comment]
Not related to this issue but try this : https://github.com/facebook/react-native/issues/13371

Moreover, I saw you had a problem with a style, in you RootContainer file, where is styles.applicationView coming from?

**Comment by GopiKrishna10** [comment]
Actually there is a code for styles.applicationView.i removed the code @Blapi . Am showing the main content in single screenShot.The code is
 // Styles
const styles = StyleSheet.create({
  applicationView: {
    flex: 1
  }
});

**Comment by Blapi** [comment]
Update me when you've fixed your issue with your xcode error, looks like it's a problem with the configuration

**Comment by GopiKrishna10** [comment]
Sure @Blapi .I will Update you

**Comment by GopiKrishna10** [comment]
@Blapi I tried to fix the errors in Xcode which are caused by Version changes.But am not able to fix the errors.Could you please help me.

**Comment by Blapi** [comment]
There's nothing more I can do, I'm an Android user, check the issue I sent you earlier, as I saw it's about the order of the Import. Check also on GitHub or SO some issues related to "import <React/RCTEventEmitter.h>".

This is not related anymore to RNRF at this point.
