### ISSUE TITLE
tabBarPosition="top" bug

### ISSUE THREAD

**Issue by hyunjun19** [aksonov/react-native-router-flux#2687]
git clone ``react-native-router-flux@4.0.0-beta.24`` and run Example.

### Version
```
  "dependencies": {
    "autobind-decorator": "^1.4.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "mobx": "^3.2.1",
    "mobx-react": "^4.2.1",
    "prop-types": "^15.5.10",
    "react": "^16.0.0",
    "react-native": "^0.50.1",
    "react-native-button": "^2.0.0",
    "react-native-message-bar": "^1.6.0",
    "react-native-router-flux": "4.0.0-beta.24",
    "react-navigation": "1.0.0-beta.17"
  },
```

### Expected behaviour
Expected TabBar on Top
<img width="511" alt="2017-12-08 7 27 55" src="https://user-images.githubusercontent.com/421863/33762003-58f7d930-dc4e-11e7-9d3f-1399d0de2da8.png">

### Actual behaviour
actual TabBar invisible

iOS default
<img width="881" alt="2017-12-08 7 05 22" src="https://user-images.githubusercontent.com/421863/33762629-8f0ae574-dc50-11e7-91e5-19fbda8c9194.png">

iOS set tabBarPosition="top"
<img width="878" alt="2017-12-08 7 05 42" src="https://user-images.githubusercontent.com/421863/33762093-b06a9ea0-dc4e-11e7-9d7d-10bd2adb237f.png">

Android default
<img width="830" alt="2017-12-08 7 28 16" src="https://user-images.githubusercontent.com/421863/33762666-b6091a2e-dc50-11e7-8e35-5c3dc5d3d8c9.png">

Android tabBarPosition="top"
<img width="825" alt="2017-12-08 7 28 40" src="https://user-images.githubusercontent.com/421863/33762121-c279aee2-dc4e-11e7-806a-e84196b5f2a8.png">

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. https://github.com/hyunjun19/react-native-router-flux
2. https://github.com/hyunjun19/react-native-router-flux/blob/master/Example/Example.js#L146

**Comment by aksonov** [comment]
It works as expected for me for latest RNRF (iOS). Can't verify on android, but anyway RNRF just calls react navigation `TabNavigator`.

![simulator screen shot - iphone 8 plus - 2018-01-04 at 14 34 07](https://user-images.githubusercontent.com/1321329/34565750-5625fdd6-f15c-11e7-900a-c872a430da13.png)

**Comment by glebez** [comment]
I had the same issue today and it seems that setting `showLabel` to `true` can help with the top navbar. Otherwise it collapses.

**Comment by edoantonioco** [comment]
I have the same bug
![screenshot_20181205_151313](https://user-images.githubusercontent.com/5560824/49544406-67849c80-f8a0-11e8-98a0-c71007b93373.png)
Only when tabBarPosition="top", when it is "bottom" (or no tabBarPosition property setted), it works fine.

Please fit it. Im in latest Expo (which has latest RN)
