### ISSUE TITLE
Navigating from home to another scene, suddenly reverts

### ISSUE THREAD

**Issue by udarts** [aksonov/react-native-router-flux#2688]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.22
- react-native v0.50.3

### Expected behaviour

Navigating to another scene and remain there unless user navigates away. 

### Actual behaviour

When navigating to another scene, after 2 seconds the scene suddenly returns back to the home.

The weird part is, that it didn't shows when debugging, only shows when released (testing) on ios and android.

### Steps to reproduce
It's difficult to add the steps, since the code I created is on my local macbook.

But this is the router layout:
`<Router>
            <Scene key="root">
                <Scene key="homeScreen" component={HomeScreen} hideNavBar={true} initial />

                <Scene key="loginScreen" component={LoginScreen} hideNavBar={true} title={I18n.t('login')} />
                <Scene key="registerScreen" component={RegisterScreen} hideNavBar={true} />
                <Scene key="profileScreen" component={ProfileScreen} hideNavBar={true} />
                
                <Scene key="mededelingenScreen" component={MededelingenScreen} hideNavBar={true} />
                <Scene key="announceDetails" component={AnnounceDetails} hideNavBar={true} handleClick={props.handleClick} />

                <Scene key="infoScreen" component={InfoScreen} hideNavBar={true} />
                
                <Scene key="contactScreen" component={ContactScreen} hideNavBar={true} />
                
            </Scene>
        </Router>`

Anyone an idea?

Cheers,

**Comment by morfsys** [comment]
You are probably using a custom NavBar and inside it some code such as Actions.pop()
You must change this code to Actions.pop only
Let me know if that helps.

**Comment by udarts** [comment]
Thanks for your reply.
I am using: react-native-navbar

On the NavigationBar setting the handler: Actions.pop, but still is causing the revert.

**Comment by udarts** [comment]
I figured out why the revert is happening, it is because I use a setInterval instead of setTimeout. Now it seems to work.

Cheers,
