### ISSUE TITLE
How to pop or go to another scene without transition.

### ISSUE THREAD

**Issue by Dorentin1997** [aksonov/react-native-router-flux#2689]
### Version
"react-native": "0.50.3",
"react-native-router-flux": "^4.0.0-beta.24"

I tried setting the duration  to 0 but it still does an animation from bottom top

**Comment by Dorentin1997** [comment]
Solved!

I placed  the duration : 0 to the stack component instead of router. 

<Stack key="root" hideNavBar={true} duration={0} >

**Comment by Blapi** [comment]
Check this if you want to do more with transitions : #2628

**Comment by bhaskardabhi** [comment]
@Dorentin1997 can you let me know what property need to be set? right now stack doesn't have any property called duration
