### ISSUE TITLE
Example has no Navigation Bar Buttons

### ISSUE THREAD

**Issue by wkirby** [aksonov/react-native-router-flux#269]
The demo gif shows the navigation component with Back buttons and has several properties that indicate  customization of left and right navbar buttons. I was unable to get these to work locally, and after pulling the example code, it is not working there either.

![screenshot 2016-02-29 11 26 47](https://cloud.githubusercontent.com/assets/579688/13406305/93fbf884-ded7-11e5-94a4-14e4a41888be.png)

**Comment by aksonov** [comment]
Feel free to improve it by sending PR.

**Comment by wkirby** [comment]
The issue is not with the example itself, it's that I believe the underlying code isn't working as intended. In neither the example nor my own use can I actually get navbar buttons to display — back or otherwise — using any of the exposed functions.

**Comment by jeduan** [comment]
@wkirby Did you try adding `onRight` to the props in `<Route>`?

**Comment by RealOrangeOne** [comment]
I am having a problem like this aswell. I can only seem to get the buttons to render using `renderRightButton` if they are on a `<Route... />` that is a direct child of the main `<Router .../>` component. Any ideas?

**Comment by adamski** [comment]
I wonder if this is at all related to my issue #304?

I've just downloaded and run the demo, and feel its quite misleading - I've spent the last couple of hours trying to understand why my navbar does not show back buttons etc and now I see the example app does not do that either. The animation shows back buttons etc so the example code should be updated or the example animation changed.

**Comment by wkirby** [comment]
@jeduan Yes. So far, nothing I've been able to do with this library adds navigation buttons to the navbar. It sounds like @RealOrangeOne  is having the same problem.

I haven't had time to debug this, but for now we've decided to switch away from this library in favor of the native navbar.

**Comment by adamski** [comment]
Are you guys on the latest version? I had a similar problem and updating to latest (2.3.12) sorted it all out for me.

**Comment by kristianmandrup** [comment]
I see the `NavBar.js` in the `Examples` but can't find it used anywhere. How do I hook it up. I thought this could be done by setting `header={NavBar}` in the main `Router`?
Anyone has a working example I can look at?

Thanks :)

**Comment by aksonov** [comment]
Check 3.0 release, now the component uses new React Native Navigation API and I've added nav bar buttons to Example. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
