### ISSUE TITLE
Gradually change the StatusBar color from one color to another when swiping through tabs

### ISSUE THREAD

**Issue by isbirkan** [aksonov/react-native-router-flux#2690]
Hi guys,

Sorry if this is not the place where to ask, but I've seen a lot of questions similar to mine, but they do not actually aim for what I am looking for.

I've seen that react native router flux has a way of gradually changing the tab bar icon colours when swiping from one screen to another, like in the bellow gif.

![screen](https://user-images.githubusercontent.com/20062931/33770036-f0cef708-dc34-11e7-9cb1-2f34278d6b5b.gif)

Could this be achieved the same way for the status bar? The closest way of doing this was using OnEnter, OnExit events, but they do have a delay since the events themselves trigger upon transition is finished.

If you need more explanations, I will provide them, since I really want to implement this feature in the app.

Cheers,
Birkan

**Comment by aksonov** [comment]
Sorry, I can't help here, maybe it is question for stackoverflow.
