### ISSUE TITLE
renderRightButton and renderLeftButton on Actions.refresh not working

### ISSUE THREAD

**Issue by JanidHam** [aksonov/react-native-router-flux#2692]
### Version 
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.24
- react-native v0.?.?

### Expected behaviour
Refresh the actual component on navbar leftButton and rightButton

### Actual behaviour
No refreshing the actual component on navbar leftButton and rightButton

**Comment by Blapi** [comment]
Please give an example of your code or there's nothing we can do to help you!

**Comment by JanidHam** [comment]
In my App.js i have this:

`const profile = <Image source={{ uri: avatar }} style={ styles.profile }/>`

`<Stack key="mainStack" hideNavBar>
          <Scene key="main" component={MainView} hideNavBar={false}
            navigationBarStyle={{backgroundColor: '#5cd9ff'}}
            title={'Amarentas'}
            renderRightButton={profile}
            renderLeftButton={profile}
          />
        </Stack>`

and the left button shows fine, but if i try to change the left button in other component with 

`
const profile = <Image source={{ uri: 'uriofOtherImage' }} style={ styles.profile }/>
Actions.refresh({ renderLeftButton: () => {profile} })
`

is not working

**Comment by delia-m** [comment]
You look have typo in your code.
If you want to return profile component
you should do like this (change curly brackets)
```Actions.refresh({ renderLeftButton: () => (profile) })
```
renderLeftButton: () => { profile } won't return profile

**Comment by JanidHam** [comment]
I already tried like you said and nothing :(

![image](https://user-images.githubusercontent.com/8473033/33899984-b380531e-df32-11e7-8d56-d7d9c89ddab1.png)

**Comment by delia-m** [comment]
Pass some value as a prop on refresh rather than pass function itself

try this 
```
renderRightButton={(props) =>  { 
    console.log(props);
    // you can handle return components here by props
    return (<DrawIcon />)}}
```

and refresh it with your own prop
```
Actions.refresh({ extraProp: 'refresh' });
```

**Comment by JanidHam** [comment]
Thanks !! it work fine 👍
