### ISSUE TITLE
Swipe Back Gesture does not works on Right To Left Layout (iOS)

### ISSUE THREAD

**Issue by AmeerTgh** [aksonov/react-native-router-flux#2693]
### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.50.3

My app has "**Right To Left**" layout (`I18nManager.forceRTL(true)`).
in navigation bar in iOS, back button is correct position but swipe back gesture(from right to left) does not works.

**Comment by AmeerTgh** [comment]
please review!

**Comment by Blapi** [comment]
Do you mean you're having issue with the transitions between your scenes?

**Comment by AmeerTgh** [comment]
yes, swipe back on rtl layout not work, only tap on back button work

**Comment by aksonov** [comment]
Please check react navigation core examples. RNRF internally uses react navigation, so the issue could be there.
