### ISSUE TITLE
[Android] rightTitle text cut issue

### ISSUE THREAD

**Issue by bilalsyed001** [aksonov/react-native-router-flux#2696]
![rightbutton](https://user-images.githubusercontent.com/16684397/33806402-ab72b10e-ddd8-11e7-9056-86100b3f4ba6.png)

Using latest master. setting `rightButton={{ right: 0 }}` fixes the issue

https://github.com/aksonov/react-native-router-flux/blob/9796b8fe485f8e8e43b3813c84f507b5ed7ddcec/src/NavBar.js#L316

**Comment by zhaonian** [comment]
not working

**Comment by aksonov** [comment]
@Blapi could you look on this android issue?

**Comment by ddereszewski** [comment]
<img width="334" alt="screen shot 2018-01-07 at 17 29 29" src="https://user-images.githubusercontent.com/2223591/34651420-5aea35be-f3d0-11e7-853c-10b38b1661df.png">


Same happens with the image on android 
Settings 
`<Scene key='player' component={PlayerScreen} rightButtonImage={require('../Images/Icons/message-icon-btn.png')}  back={true} />`

**Comment by zhaonian** [comment]
maybe try this prop rightButtonStyle={{ right: 0 }}?

**Comment by Blapi** [comment]
Yes there's this issue on Android, @bilalsyed001 provided the good solution to fix this, however you can still manage to fix this adding a style.

Without a style : 

![26853856_10216189423276844_524213007_o](https://user-images.githubusercontent.com/3853597/34774649-6faa385e-f610-11e7-847f-aa697df505f5.png)

With a style `leftButtonStyle={{ paddingLeft: 0, left: 0 }}`

![26829610_10216189423236843_286140174_o](https://user-images.githubusercontent.com/3853597/34774648-6f891b38-f610-11e7-91a9-d1fa00b788a9.png)

**Comment by ilteoood** [comment]
+1 here

**Comment by russellgoldman** [comment]
Got this issue but fixed it with {{ marginLeft: 5, marginRight: 5 }} (doesn't have to be 5, just something to balance out the marginLeft shift)
