### ISSUE TITLE
[Android] transition effects stopped working after RN 0.13 update

### ISSUE THREAD

**Issue by JonnyBGod** [aksonov/react-native-router-flux#27]
```
<Schema name="default" sceneConfig={Animations.FlatFloatFromRight} />
```

This was working more or less with RN 0.12 (the transition was translating but opacity was not happening). Now with RN 0.13 there is simply no effect. I can see a delay waiting for effect to finish and than it just switches screens.

**Comment by aksonov** [comment]
Do own Navigation scene animations work well?

**Comment by qbig** [comment]
@JonnyBGod @aksonov   related to this  https://github.com/facebook/react-native/issues/3669 ?

**Comment by aksonov** [comment]
@qbig Seems that the reason, closing this issue.
