### ISSUE TITLE
how to use Actions Binding in ListView

### ISSUE THREAD

**Issue by shipcake** [aksonov/react-native-router-flux#2700]
hi, i stuck in new problem. i hope to binding ID send to the new page but i have error any solution in Question on internet :( i trying to fix error but i am the beginner to leaning React Native Help me 

i hope my project is done.  my project something like this
https://reactnativecode.com/send-listview-item-click-onpress-value/

My code in ListView Tag
`

          dataSource={this.state.dataSource}

          renderSeparator= {this.ListViewItemSeparator}

          renderRow={(rowData) => 
          <Text style={styles.rowViewContainer}onPress={this.OpenSecndActivity.bind(this, rowData.product_id)}>
            {rowData.product_name}</Text>}

        />`

And  My Function OpenSecondActivity
`
OpenSecndActivity (product_id) {

  //Alert.alert(product_id); 
  //How to send value Data ID using Actions
  
  
}
`

My full code
https://codeshare.io/alAbQg

**Comment by aksonov** [comment]
Not related to RNRF
