### ISSUE TITLE
undefined is not an object state.children

### ISSUE THREAD

**Issue by navneet-sandhu** [aksonov/react-native-router-flux#2701]
Hello Guys,
I'm facing issue while implementing drawer provided by router flux in the project version given below:
Earlier no such issue was arising when project version was react-native:0.44.0

Versions used in the current project are:
react-native-drawer: 2.5.0
react-native-router-flux: 4.0.0 beta.24 
react-native: 0.50.3

The error faced is : undefined is not an object state.children

Please help me out to resolve this issue.

Thanks

**Comment by Blapi** [comment]
There's nothing we can do to help you with what you're providing, show your code @navneet-sandhu ..

**Comment by amanbadhan** [comment]
I am facing the same issue. :(

**Comment by Blapi** [comment]
I am facing the same problem as I can not help you without an example of your code.

**Comment by amanbadhan** [comment]
HI I am posting code here.

import React from 'react';
import { StyleSheet, Text, View, Image, TouchableOpacity } from 'react-native';
import {
  Scene,
  Router,
  Stack,
  Drawer,Actions,ActionConst
} from 'react-native-router-flux';
import login from './login';
import signup from './sign';
import option from './option';
import Welcome from './Welcome'
 import side from './side';
import NavigationDrawer from './NavigationDrawer';
export default class App extends React.Component {
  render() {
    return (
      <Router>
         <Scene key="root">
             { <Scene key="side" component={side} hideNavBar={true} /> }
        <Scene key="navigationdrawer" component={NavigationDrawer} hideNavBar panHandlers={null} type={ActionConst.RESET} open={false}>
            <Scene key='drawerChildrenWrapper' initial>
            <Scene key="option" component={option} hideNavBar={true} />
       {/* <Drawer key="drawer" component= {side} hideNavBar = {true}> */}
        
       <Scene key="signscreen" component={signup} hideNavBar={true} />
          <Scene key="loginscreen" component={login} hideNavBar={true} />
        

         
            
          {/* </Drawer> */}
        </Scene>
        </Scene>
        </Scene>
      </Router>
    );
  }
}



**Second component where we call actions is mentioned below;**
import React from 'react';
import { StyleSheet, Text, View ,Image,TouchableOpacity,AsyncStorage } from 'react-native';
import {
    Scene,
    Router,
    Stack,
    Actions
  } from 'react-native-router-flux';
 // import option from './option';

export default class side extends React.Component {
  abc()
  {
    //AsyncStorage.clear();
    console.log("aman");
    Actions.option();
  }
  
  render() {
      console.log("in side drawer");
    return (

      <View style={styles.container}>
      
      <Text>Hello</Text> 
      <TouchableOpacity onPress={()=>Actions.option()} activeOpacity={0.8} style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <Text>
          Dummy
          </Text>
         
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#706c69',
    alignItems: 'center',
    justifyContent: 'center',

  },
});

**Comment by Blapi** [comment]
Well well, first, it looks like it's missing some code, I don't see your declaration of the router and no trace of your Scene "root".
Then, you're doing a Actions.option(), where is your Scene with the key "option" ??

Please, when you send your code, use the triple ` (at the beginning and at the end of your code snippet) so the code will be well formated and easy to read.

**Comment by amanbadhan** [comment]
@Blapi  Sorry I forget to mentioned that.Kindly check below mentioned missing part of the code

import React from 'react';
import { StyleSheet, Text, View ,Image,TouchableOpacity,AsyncStorage} from 'react-native';
import {
    Scene,
    Router,
    Stack,
    Actions
  } from 'react-native-router-flux';
  import Drawer from 'react-native-drawer';
  import NavigationDrawer from './NavigationDrawer';

export default class option extends React.Component {
    _onPressButton()
    {
        //Actions.loginscreen();
       
    }
    componentWillMount()
    {
      AsyncStorage.clear();
        AsyncStorage.getItem("NameKey").then((value) => {
            console.log("" + value);
            debugger;
            if (value != null) {
                alert('Welcome '+ value+ 'You signed in')
            }
        })
    }
    
    _onpressign()
    {
      //AsyncStorage.clear();
      Actions.signscreen();
    }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={() => Actions.refresh({ key: 'navigationdrawer', open: value => !value })}>
        <Text> Click </Text>
            {/* <Image style={{ height: 25, width: 25, marginTop: 15, marginLeft: 10 }} source={require('./img/lion.png')} /> */}
          </TouchableOpacity>

      <Image style= {{width :300,height:300}}
          source={require('./img/lion.png')}
          
        />
        <TouchableOpacity onPress={this._onPressButton}>
          <Image style= {{width :200,height:49,marginTop:80}}
            source={require('./img/in.png')}
          />
        </TouchableOpacity>
        <TouchableOpacity onPress={ this._onpressign}>
          <Image style= {{width :200,height:49,marginTop:10}}
            source={require('./img/up.png')}
          />
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#706c69',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by Blapi** [comment]
Please send me your entire App.js and use ``` PLEASE like this :

(insert the 3 backquotes)
theCodeYouPaste
(insert the 3 backquotes)

So it looks like

```
<myComponent>
  Oh cool easy to read
</myComponent>
```

ok? your App.js was not full.

**Comment by amanbadhan** [comment]
'''
import React from 'react';
import { StyleSheet, Text, View, Image, TouchableOpacity } from 'react-native';
import {
  Scene,
  Router,
  Stack,
  Drawer, Actions, ActionConst
} from 'react-native-router-flux';
import login from './login';
import signup from './sign';
import option from './option';
import Welcome from './Welcome'
import side from './side';
import NavigationDrawer from './NavigationDrawer';
export default class App extends React.Component {
  render() {
    return (
      <Router>
        <Scene key="root">
          {<Scene key="side" component={side} hideNavBar={true} />}
          <Scene key="navigationdrawer" component={NavigationDrawer} hideNavBar panHandlers={null} type={ActionConst.RESET} open={false}>
            <Scene key='drawerChildrenWrapper' initial>
              <Scene key="option" component={option} hideNavBar={true} />
              {/* <Drawer key="drawer" component= {side} hideNavBar = {true}> */}

              <Scene key="signscreen" component={signup} hideNavBar={true} />
              <Scene key="loginscreen" component={login} hideNavBar={true} />




              {/* </Drawer> */}
            </Scene>
          </Scene>
        </Scene>
      </Router>
    );
  }
}


'''

**Comment by amanbadhan** [comment]
```
import React from 'react';
import { StyleSheet, Text, View, Image, TouchableOpacity } from 'react-native';
import {
  Scene,
  Router,
  Stack,
  Drawer, Actions, ActionConst
} from 'react-native-router-flux';
import login from './login';
import signup from './sign';
import option from './option';
import Welcome from './Welcome'
import side from './side';
import NavigationDrawer from './NavigationDrawer';
export default class App extends React.Component {
  render() {
    return (
      <Router>
        <Scene key="root">
          {<Scene key="side" component={side} hideNavBar={true} />}
          <Scene key="navigationdrawer" component={NavigationDrawer} hideNavBar panHandlers={null} type={ActionConst.RESET} open={false}>
            <Scene key='drawerChildrenWrapper' initial>
              <Scene key="option" component={option} hideNavBar={true} />
              {/* <Drawer key="drawer" component= {side} hideNavBar = {true}> */}

              <Scene key="signscreen" component={signup} hideNavBar={true} />
              <Scene key="loginscreen" component={login} hideNavBar={true} />




              {/* </Drawer> */}
            </Scene>
          </Scene>
        </Scene>
      </Router>
    );
  }
}


```

**Comment by Blapi** [comment]
contentComponent | React.Component |   | Component used to render the content of the drawer (e.g. navigation items).
-- | -- | -- | --

I guess your error is because you use `component` instead of `contentComponent` in your Drawer

**Comment by Blapi** [comment]
@navneet-sandhu @amanbadhan what's the status now?

**Comment by aksonov** [comment]
Closed due inactivity
