### ISSUE TITLE
<Drawer > doesnt work for me 

### ISSUE THREAD

**Issue by RadhaSwathi** [aksonov/react-native-router-flux#2702]
Hi I am trying to use drawer but it doesnt work for me .

<Drawer
                hideNavBar
                key="drawer"
                contentComponent={DrawerContent}
                drawerImage={MenuIcon}
                drawerWidth={300}
              >
  <Scene key='ComplaintDetails' component={ComplaintDetails} title='Complaint Details' />
              </Drawer>

I have used above code and i can not navigate to complaint details.

i get a warning react.create.element type is invalid....... 

I have exported all my components

**Comment by Blapi** [comment]
Which code?

**Comment by RadhaSwathi** [comment]
<Drawer
                hideNavBar
                key="drawer"
                contentComponent={DrawerContent}
                drawerImage={MenuIcon}
                drawerWidth={300}
              >
  <Scene key='ComplaintDetails' component={ComplaintDetails} title='Complaint Details' />
              </Drawer>

**Comment by Blapi** [comment]
Show all your code please, copy paste it because there's a lot of things missing there.

**Comment by RadhaSwathi** [comment]
[index.txt](https://github.com/aksonov/react-native-router-flux/files/1552717/index.txt)

**Comment by Blapi** [comment]
Ok so after checking your code, I saw that you had twice the same Scene with the key "ComplaintDetails", try to fix this.

```
const RouterComponent = () => {
  return (
    <Router>
      <Scene key='root'>
        <Scene key='login' component={Login} title='Login' sceneStyle={{top:55}} />
        <Scene key="tabbar" tabs={true} hideNavBar={true} tabBarStyle={{ backgroundColor: '#FFFFFF' }}>
          <Scene key="Ticketstatus1" title="Ticketstatus1" icon={TabIcon}>
            <Scene key="Active" component={NewTicket}  title="Active"/>
          </Scene>
          <Scene key="Ticketstatus2" title="Ticketstatus2" icon={TabIcon1}>
            <Scene key="solved" component={ResolvedTicket} title="Resolved" />
          </Scene>
        </Scene>
        <Scene key='FrgtPsswd' component={FrgtPsswd} title='FrgtPsswd' />
        <Scene key='ComplaintDetails' component={ComplaintDetails} title='Complaint Details' /> //THERE
        <Scene key='Dashboard' component={Dashboard} title='Dashboard' initial />
        <Drawer
          hideNavBar
          key="drawer"
          contentComponent={DrawerContent}
          drawerImage={MenuIcon}
          drawerWidth={300}>
          <Scene key='ComplaintDetails' component={ComplaintDetails} title='Complaint Details' /> //THERE
        </Drawer>
      </Scene>
    </Router>
  );
};
```

**Comment by RadhaSwathi** [comment]
That issue is fixed. If I use my scene component outside drawer it works . It doesn't work inside drawer component.

**Comment by Blapi** [comment]
I suggest you to watch the Example project if you still have some issues using this library, the Example project contains a lot of example of how to use the components you might need !

**Comment by Mimicx** [comment]
hey guys, the drawer works fine in Android, but in iOS i can't hide the status bar. Any ideas?
