### ISSUE TITLE
How to pass value to two tabs? 

### ISSUE THREAD

**Issue by RadhaSwathi** [aksonov/react-native-router-flux#2703]
Hi I am new to react native. I  am using tab. I have been passing value from a root page to a tab page with two tabs. The first tab receives value from Actions.tab({myval : state.myval}) . Wen I switch to tab2 how do I fetch myVal?

**Comment by Blapi** [comment]
How do you switch yo your tab2 ? You're using Actions.tab2() right? Then, just pass the props to the tab2 as you did for tab.

**Comment by RadhaSwathi** [comment]
![1513101385430643373445](https://user-images.githubusercontent.com/30224635/33900318-01d15520-df94-11e7-838b-354fe5ccf56c.jpg)

I use Actions.tabbar() and it take me to first tab. I can directly switch to my second one by clicking tab2

**Comment by Blapi** [comment]
Ok so have you really try to fetch you value? I just tried with the Example project and when I call the `Actions.tabbar({ whateverParam: whateverValue })`, If I log` Actions.currentParams`, I can clearly see in all the tabs that I have the `whateverParam`
