### ISSUE TITLE
navTransparent doesn't work in Router>Scene

### ISSUE THREAD

**Issue by romaintich** [aksonov/react-native-router-flux#2704]
### Expected behaviour

Does the props "navTransparent" for Scene work for you ? 
I want my header from scene "profil" to be transparent in order to put components ahead. 

### Actual behaviour

<Scene
        key="profil"
        component={ProfilePage}
        rightTitle="Modify"
        onRight={()=>Actions.modify()}
        backButtonImage={BackImage}
        title="Profile"
        titleStyle={{fontFamily: 'Helvetica', color: '#fff', fontWeight: "bold"}}
        rightButtonTextStyle={{fontFamily: 'Helvetica', color: '#fff'}}
        navTransparent={true}
      />

**Comment by aksonov** [comment]
`navTransparent` should be defined for container scene
