### ISSUE TITLE
onBack not working on any scenes

### ISSUE THREAD

**Issue by whyAto8** [aksonov/react-native-router-flux#2706]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4 - ^4.0.0-beta.23
- react-native v0 0.49.3

### Expected behaviour
onBack function should execute the code 

### Actual behaviour
onBack is not fired on any of the scenes I have

### Steps to reproduce
My router code looks like this:
```
		<Router>
			<Scene key="root">
				<Scene key="setup">
						<Scene key="setupOptions" component={Setup} />
						<Scene key='healthIssue' component={SetupHealthIssue} onBack={ ()=> console.log('am in')}/>
				</Scene>
			</Scene>
		</Router>
```

The onBack is just firing, when I click that back arrow in top left on healthIssue page. I tried creating other scenes and calling onBack on them didnt work either.

**Comment by whyAto8** [comment]
Just tried that if i add  "back" or "backTitle" to this scene, it made it work. Strange, seems like onBack needs another attr to make it working.

**Comment by MatthieuCoelho** [comment]
This is still not working on : "react-native-router-flux": "^4.0.6"
You're workaround still works but it is inconvenient when we have dynamic backTitle
