### ISSUE TITLE
translucent Navbar on ios

### ISSUE THREAD

**Issue by shukerullah** [aksonov/react-native-router-flux#2707]
I want to have transparent Navbar with backbutton on ios, is this possible?

**Comment by Blapi** [comment]
`navTransparent | boolean | false | nav bar background transparency`

This is in https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md, have you tried this?

**Comment by shukerullah** [comment]
I tried `navTransparent`, header set back to visible while navigation to new screen or pop back.

**Comment by aksonov** [comment]
I can't reproduce. Just added `navTransparent` to `<Stack key='register'` within Example project and see transparent navbar without problems.
