### ISSUE TITLE
[BUG] Actions.popTo crashes navigation on v4

### ISSUE THREAD

**Issue by digitaldavenyc** [aksonov/react-native-router-flux#2712]
### Version
- react-native-router-flux v4.0.0-beta24
- react-native v0.51.0

This bug is really simple, if you try use `Actions.popTo` anywhere in our app, it crashes navigation. It does not actually navigate to where you expect it to and you cannot navigate anywhere else in the app. Crazy thing is, there are no errors thrown at all. It just locks up the app without any messaging. 

Example:

`Actions.popTo('profile');`

or 

`Actions.profile({type: ActionConst.POP_TO})`

**Comment by Blapi** [comment]
Is your profile page in your navigation stack?

**Comment by Blapi** [comment]
@digitaldavenyc ?

**Comment by aksonov** [comment]
Closed due inactivity
