### ISSUE TITLE
Content Component returns this error :TypeError: undefined is not an object (evaluating 'route.routeName')  in beta 22 but works in beat21

### ISSUE THREAD

**Issue by padmanabanSampath** [aksonov/react-native-router-flux#2723]
this is the github repo link: https://github.com/kakulgupta/CustomDrawer

it works weel in beat 21 but at beta22 it throws error TypeError: undefined is not an object (evaluating 'route.routeName')

maybe package broken

advance thankyou for your valuable reply

**Comment by Blapi** [comment]
Duplicate #2718
