### ISSUE TITLE
Exist app when clicked back on home screen

### ISSUE THREAD

**Issue by vikrantnegi** [aksonov/react-native-router-flux#2725]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native v0.50.4

### Expected behaviour
Back button should exit the app when navigating from other screens to home screen.

### Actual behaviour
Back button exits the app when the app loads for the first time. But when navigating to other screens and coming back to home screen the back button doesn't do anythinng.

### Steps to reproduce
Here is the link to StackOverflow question.
https://stackoverflow.com/questions/47898965/exist-app-when-clicked-back-on-home-screen

**Comment by Blapi** [comment]
Add this in your app.js (or where your Router is implemented)

```
const reducerCreate = (params) => {
  const defaultReducer = new Reducer(params)
  return (state, action) => {
    console.log('Action :', action)
    console.log('State :', state)
    return defaultReducer(state, action)
  }
}
```

And then in your Router : 
```<Router
          backAndroidHandler={this.onBackPress}
          createReducer={reducerCreate}>
```

New when debugging, check if everything's fine or if there's a problem with the scenes ?

**Comment by vikrantnegi** [comment]
@Blapi I'm not using redux on this app. Any non-redux equivalent debugging code?

**Comment by Blapi** [comment]
If you had a look on the Example project, you could see that what I sent you previously is being used and without implementing redux.

**Comment by vikrantnegi** [comment]
@Blapi Thanks.
 weirdly enough but everything now seems to be working. I reinstalled the node modules and then everything started working.

Thanks a lot.
