### ISSUE TITLE
How do I keep the tab bar visible?

### ISSUE THREAD

**Issue by lazzlo** [aksonov/react-native-router-flux#2726]
When I navigate to a component via an onPress function that is located on one of my tabs, the tab bar disappears. I can't seem to wrap my head around how to keep it in the same stack.

My navigation structure looks like this:

<Drawer key="sideMenu" contentComponent={SideMenu} hideNavBar={true}>
          <Tabs>
            // OTHER SCENES HERE
            <Scene
              key="knowledge"
              initial
              component={Knowledge}
              tabBarLabel="KNOWLEDGE"
              icon={KnowledgeIcon}
            />
          </Tabs>
      </Drawer>

// This is the scene that I want to navigate to which should still have the same tab bar
<Scene key="categoryItemList">
        <Scene component={CategoryList} back />
</Scene>

I've tried nesting that scene within the knowledge scene, but when I do that and navigate to it, RNRF complains that it can't find the scene with the specified key. It also doesn't work when I push the scene onto it. I've also tried changing the knowledge scene to a stack instead, but no dice.

What am I doing wrong?

**Comment by aksonov** [comment]
I don't understand the issue. Please check Example project and its tabbar
