### ISSUE TITLE
key="tab1_1"

### ISSUE THREAD

**Issue by teilala** [aksonov/react-native-router-flux#2728]
https://github.com/aksonov/react-native-router-flux/blob/30f65a56e762bc52d62c735de91fa5ed7389d977/Example/Example.js#L158

key="tab1_1" and key="tab1_2" fix to key="tab_1_1" and key="tab_1_2" 

:TabView.js  error 
{this.props.name === 'tab_1_1' &&
        <Button onPress={() => Actions.tab_1_2()}>next screen for tab1_1</Button>
        }

**Comment by aksonov** [comment]
Should be fixed now, thanks! https://github.com/aksonov/react-native-router-flux/commit/7c9b2d1a30444ad4bd8259e3a1d9e0b4c60fd950
