### ISSUE TITLE
Behavior of back button on device android not same back button on toolbar

### ISSUE THREAD

**Issue by bachphuc** [aksonov/react-native-router-flux#2729]
### Version
Tell us which versions you are using: 

- react-native-router-flux: "^4.0.0-beta.24",
- react-native-cli: 0.2.0
- react-native: 0.51.0

Hi I'm using react-native-router-flux v4.
This's my code.

```
<Router>
	<Stack key="root">
		<Scene key="VideoHomeScreen" component={VideoHomeScreen} initial={true} title="Home"  />
		<Scene key="VideoDetailScreen" component={VideoDetailScreen} title="Video Detail" />
	</Stack>
</Router>
```

Very simple case. I'm working with android 7.1. 
When I start app it goes home screen, it's good then I click video on home screen then it opens Video Detail Screen, it's correct too. 

Problem in Video Detail Screen, if I click back button on toolbar then it goes back to home screen, it's correct. but if I click back button on device then it doesn't go back to home screen, it closes app like you press home button.

I want that in Video Detail Screen when I press back device button it should be same behavior with when I click on back on toolbar.

Or I did some wrong, Can you help me?

**Comment by Blapi** [comment]
You need to handle to BackButton within your Router, just add this where you implemeted it : 

```
  onBackPress() {
    if (Actions.state.index === 0) {
      return false
    }
    Actions.pop()
    return true
  }
```
...
...
```
<Router
  backAndroidHandler={this.onBackPress}>
```

**Comment by bachphuc** [comment]
Hi,

I have it already but it's not working. In VideoDetailScreen when I press back on device then it doesn't go back, it closes app like press home device button

```
export default class App extends Component {
    backAndroidHandler = () => {
        return false;
    }

    componentDidMount = () => {
        BackHandler.addEventListener('hardwareBackPress', function() {
            // this.onMainScreen and this.goBack are just examples, you need to use your own implementation here
            // Typically you would use the navigator here to go to the last state.
          
            // if (!this.onMainScreen()) {
            //     this.goBack();
            //     return true;
            // }
            return false;
        });
    }

    render() {
        return (
            <Router backAndroidHandler={this.backAndroidHandler}>
                <Stack key="root">
                    <Scene key="VideoHomeScreen" component={VideoHomeScreen} initial={true} title="Home" />
                    <Scene key="VideoDetailScreen" component={VideoDetailScreen} title="Video Detail" />
                </Stack>
            </Router>
        );
    }
}
```

**Comment by bachphuc** [comment]
Hi, 

Thank you so much! I think I did it wrong :)

So sorry about this.
