### ISSUE TITLE
Drawer is not working with same source code in Example.

### ISSUE THREAD

**Issue by JJMoon** [aksonov/react-native-router-flux#2730]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native : ^0.50.1

### Expected behaviour
Open Drawer Scene

### Actual behaviour
Red screen.

### Steps to reproduce
I guess this is not a source code issue. Because I got different results with identical source code.

I hope you to compare those 2 projects, and tell me what the difference is, what caused the problem.

1. https://github.com/JJMoon/rnrf-example  > it's working. I erased and edited from Example project.
2. https://github.com/JJMoon/routerflux  > it's not working. Created from react-native init.

Thank you in advance..

**Comment by marcoj** [comment]
Same issue... 
had a project implemented 3 days ago, navigation was working perfectly.
Meanwhile had to install react-native-router-flux again (yesterday), and with the new version it doesn't work. 
I'm sure it's something related to  Dec 19, 2017 or  Dec 20, 2017 commits.

So, I've cloned react-native-router-flux again, tested the example and confirmed that I can't navigate to any scene inside the Drawer.

Please fix.

**Comment by Blapi** [comment]
This issue is known and duplicated from #2718

**Comment by JJMoon** [comment]
For somebody who are unfamiliar npm module system. (me too.)
Delete yarn.lock and edit package.json as follow.
"react-native-router-flux": "git+https://github.com/aksonov/react-native-router-flux.git#30f65a5",
