### ISSUE TITLE
scen with same routeName pushed with different pragms onEnter not called

### ISSUE THREAD

**Issue by jf4444** [aksonov/react-native-router-flux#2731]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.23 (v3 is not supported)
- react-native v0.5.0

### Expected behaviour

Can push same scen and scenes onEnter called everytime,and I can know which one Compent be enterd.

### Actual behaviour
 when touched a button in scen want push the same compent with same scen key, but second push the scen onEnter method not called, and when I pushed 5 same scenes,Action.refs just contain one scen 

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.My route is:

const Example = () => (
  <Router
    createReducer={reducerCreate}
    getSceneStyle={getSceneStyle}
    uriPrefix={prefix}
  >
    <Stack key="customNavBar" hideNavBar hideTabBar titleStyle={{alignSelf: 'center'}}>
      <Scene hideNavBar>
        <Tabs
          key="tabbar"
          swipeEnabled={false}
          showLabel={false}
          tabBarStyle={styles.tabBarStyle}
          activeBackgroundColor="white"
          inactiveBackgroundColor="rgba(255, 0, 0, 0.5)"
        >
          <Stack
            key="tab_1"
            title="Tab #1"
            tabBarLabel="TAB #1"
            inactiveBackgroundColor="#FFF"
            activeBackgroundColor="#DDD"
            icon={TabIcon}
            navigationBarStyle={{backgroundColor: 'green'}}
            titleStyle={{color: 'white', alignSelf: 'center'}}
          >
            <Scene
              key="tab1_2"
              component={TabView}
              title="Tab #1_2"
              back
              titleStyle={{color: 'black', alignSelf: 'center'}}
            />
          </Stack>

          <Stack
            key="tab_2"
            title="Tab #2"
            icon={TabIcon}
            initial
          >
            <Scene
              key="tab_2_1"
              component={TabView}
              title="Tab #2_1"
              renderRightButton={() => <Text>Right</Text>}
            />
           
          </Stack>

          <Stack key="tab_3">
            <Scene
              key="tab_3_1"
              component={TabView}
              title="Tab #3"
              icon={TabIcon}
              rightTitle="Right3"
              onRight={() => {
              }}
            />
          </Stack>
          <Stack key="tab_4">
            <Scene key="tab_4_1" component={TabView} title="Tab #4" hideNavBar icon={TabIcon}/>
          </Stack>
          <Stack key="tab_5">
            <Scene key="tab_5_1" component={TabView} title="Tab #5" icon={TabIcon}/>
          </Stack>
        </Tabs>
      </Scene>

      <SPScen hideTabBar={false} key="echooooooo" back clone init component={EchoView} getTitle={({navigation}) => navigation.state.key}/>
      <Scene key="echo1" back clone component={EchoView1} getTitle={({navigation}) => navigation.state.key}/>
      <Scene hideTabBar key="echo2" back clone component={EchoView2} getTitle={({navigation}) => navigation.state.key}/>
    </Stack>
  </Router>
);

2. in tab two press button push in echooooooo
3.  in echooooooo press button push in echooooooo

**Comment by aksonov** [comment]
Please check latest master - I've just added onEnter/onExit class instance method support.
