### ISSUE TITLE
componentDidMount hook re-triggered

### ISSUE THREAD

**Issue by mackenziemance** [aksonov/react-native-router-flux#2732]
### Version

- react-native-router-flux v4.0.0-beta.24
- react-native v0.51.0

I can't fathom why this is happening but when I dispatch a action that triggers a saga from the redux-saga library my componentDidMount hook is re-triggered which can lead to a cascadeing update if dispatched from mount, this happens with rn 0.51.0 and only inside router. This behaviour doesn't happen outside router. This is might be a problem with react-navigation, was just seeing if anyone here could reproduce.

**Comment by aksonov** [comment]
RNRF uses react-navigation. Please check react-navigation core examples.

**Comment by mackenziemance** [comment]
My mistake this was a caused by nesting redux connects, thanks @aksonov.

**Comment by shahidmau** [comment]
Hi, I am getting the same issue, it is showing the first screen when the app is waiting for the ajax response using saga. @mackenziemance  Kindly provide the code which is working in your case.
