### ISSUE TITLE
Android how to destory flux when finish activity 

### ISSUE THREAD

**Issue by wuyingtong** [aksonov/react-native-router-flux#2733]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.50.3

### Expected behaviour
when Android activity finish, how to destory flux, because there severals activity use flux cause  multiplex

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment]
Sorry, I can't help here - RNRF doesn't need to be destroyed, all should be done automatically by RN, maybe you could ask at stackoverflow.
