### ISSUE TITLE
Send params to a child scene when calling a parent stack

### ISSUE THREAD

**Issue by QQizi** [aksonov/react-native-router-flux#2734]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0
- react-native v0.50.3

### Expected behaviour
 I'm trying to send params to my next view which is the first scene of a stack.

### Actual behaviour
My scenes are pretty much perfect for what i'm trying to do.
Basicly, on the `home_page` i have a bunch of album & user profil. I can navigate like this home>profil>album>album>profil>album and such.

My problem is that when i am in the home and navigate to my album by doing `Actions.album`, the next scene is `album_scene` but the params are not sent to it.

If i call `Actions.album_scene` directly in my home scene, the params are sent but i got a navigation issue, it open 2 `album_scene` scene. So when i `.pop` i have to back 2 time to go back to the home.

My need is to send params to a child while calling a parent. 

### Steps to reproduce
```
<Stack key="home">
   <Scene key="home_page" component={Home} back={false} panHandlers={null} />
   <Scene key="profil" component={Profil} />
   <Modal>
      <Stack key="album">
         <Modal>
		<Stack key="album_stack">
			<Scene key="album_scene" component={Album} />
			<Scene key="photo" component={Photo} />
		</Stack>
		<Scene key="comments" component={Comments} />
	</Modal>
      </Stack>
      <Lightbox>
         <Scene key="albuminfo" modal={true} component={AlbumInfo} />
      </Lightbox>
   </Modal>
</Stack>
```

**Comment by aksonov** [comment]
It is not supported, PR is welcome.
