### ISSUE TITLE
Drawer not showing, details inside

### ISSUE THREAD

**Issue by fullhdpixel** [aksonov/react-native-router-flux#2738]
### Version
- react-native-router-flux: ^4.0.0-beta.24,
- react-native: 0.50.4,

### Expected behaviour
I want to show a drawer only for feeds, notifications, post and camera scenes. The drawer never shows on any screen when being called with Action.openDrawer().

 ```
<Router>
    <Stack hideNavBar key="root">
      {/* Login Screen */}
      <Scene key="login" component={LoginScreen} hideNavBar initial />
      {/* Register Screen */}
      <Scene key="register" component={RegisterScreen} hideNavBar />
      {/* Feed Screen */}
      <Stack>
        <Scene key="drawer" drawer drawerWidth={250} contentComponent={DrawerContent} open={false}>
          <Scene key="feed" component={FeedScreen} hideNavBar />
          {/* Notifications Screen */}
          <Scene
            key="notifications"
            component={NotificationScreen}
            hideNavBar
          />
          {/* Posts Screen */}
          <Scene key="post" component={PostScreen} hideNavBar />
          {/* Camera Screen */}
          <Scene key="camera" component={CameraScreen} hideNavBar />
        </Scene>
      </Stack>
    </Stack>
  </Router>
```

`onPress={() => {Actions.drawerOpen()}} `

### Actual behaviour
- The drawer is never visible
- When adding drawer to the Scene, going to the page doesnt work

**Comment by ninjarails** [comment]
Same issue here

**Comment by aksonov** [comment]
Please reproduce the issue with Example project (i.e. fork and change the code)

**Comment by binonxia** [comment]
Same issue here

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
