### ISSUE TITLE
could router be nested??

### ISSUE THREAD

**Issue by fatfatson** [aksonov/react-native-router-flux#2739]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native v0.50.4

could react-native-router-flux's router be nested??
I see the example, all the availabe scenes are putted into the root component, it's too confusion
I want a component could has its own router：

in root view:
```
			<Provider store={store}>
				<View style={{ backgroundColor: '#f5f5f5', flex: 1 }}>
					<NetState />
					<Router
						backAndroidHandler={() => {
							console.log('back...');
							console.log(Actions.state);
							Actions.pop();
							return true;
						}}
					>
						<Scene key="root" hideNavBar="true">
							<Scene key="About" component={About} title="About" />
							<Scene key="Login" component={Login} title="Login" />
							<Scene key="Home" component={Home} title="Home" />
						</Scene>
					</Router>
				</View>
			</Provider>
```

then in subview(Home):
```
			<Router>
				<Scene>
					<Scene key="Info" component={Info}  initial />
					<Scene key="Discover" component={Discover}   />					
				</Scene>
			</Router>
```

but i get the error:

> Error: There is no route defined for key Home.  Must be one of: 'Info'

**Comment by asciifaceman** [comment]
Can you explain why you want a whole new router in that way? It is kind of counter intuitive, I would think you would want to use Stacks instead in the original file and build them all out, then you transition between. 

I don't mean for you to use this code exactly, but demonstrating that you should utilize Stacks:

```
<Router
  backAndroidHandler={() => {
    console.log('back...');
    console.log(Actions.state);
    Actions.pop();
    return true;
  }}
>
  <Stack key="root">
      <Scene key="About" component={About} title="About" />
      <Scene key="Login" component={Login} title="Login" />
      <Scene key="Home" component={Home} title="Home" />
  </Stack>
  <Stack>
    <Scene>
      <Scene key="Info" component={Info}  initial />
      <Scene key="Discover" component={Discover}   />         
    </Scene>
  </Stack>
</Router>
```

**Comment by aksonov** [comment]
Sorry, currently it is not supported.
