### ISSUE TITLE
navigationBarStyle in Route doesn't work

### ISSUE THREAD

**Issue by vtambourine** [aksonov/react-native-router-flux#274]
For some reason I am unable to override scene NavBar style with `navigationBarStyle` option, as it stated in docs.

My component structure is following:
```
<Router ... navigationBarStyle={styles.bar}>
   <Route name='onboarding' ... navigationBarStyle={styles.bar2} />
</Router>
```

I expect the Onboarding page will have custom NavBar color, but it doesn't.

**Comment by BigPun86** [comment]
+1

**Comment by ajoshdee** [comment]
hide the router navbar

**Comment by vtambourine** [comment]
@ajoshdee, yes, I can figure out some workaround, but I think more solid API might be more suitable for my and similar situation.

**Comment by DVassilev** [comment]
The navbar is also not changing for me despite using navigationBarStyle.

**Comment by jayesbe** [comment]
ditto.  Trying to center the title in the navigation bar.. not working.

**Comment by aksonov** [comment]
It is NOTE supported now  - customisation of nav bar for each route. PR will be welcome.
