### ISSUE TITLE
[server error] Cannot load the stats for react-native-router-flux – please try again later

### ISSUE THREAD

**Issue by pouyajabbarisani** [aksonov/react-native-router-flux#2740]
Hi there,
When I'm trying to install react-native-router-flux, npm returns this error on terminal:

[server error] Cannot load the stats for react-native-router-flux – please try again later

**Comment by welson327** [comment]
same problem for several days @@"

**Comment by Mardii-D-King** [comment]
Same here and i keep getting an error that says:
TypeError: undefine is not a function (evaluating "instant.render()")

the error is located at:
in Routes(at App.js)
in RCTView(at View.js:112)
etc...

Is this a problem relating to this component not working?

**Comment by FarihulR** [comment]
Same the problem. How to Fix ?

**Comment by aksonov** [comment]
It seems to be not related to RNRF - just installed Example project normally without any errors.

**Comment by sultan2Dilawar** [comment]
+1

**Comment by saphir100** [comment]
> Hi there,
> When I'm trying to install react-native-router-flux, npm returns this error on terminal:
> 
> [server error] Cannot load the stats for react-native-router-flux – please try again later

hi pouya, do you resolve this problem?

**Comment by wahidshadab** [comment]
Same problem here.
