### ISSUE TITLE
Transition direction

### ISSUE THREAD

**Issue by kmatias** [aksonov/react-native-router-flux#2741]
### Version

- react-native-router-flux "^4.0.0-beta.24"
- react-native "0.50.3"

Is there a way to configure the direction of the transition animation - eg. from left-to-right / right-to-left?

Also, as documented in the API, When navigating using Actions.reset("sceneKey"),  no transition occurs. Is there a way to add a transition manually?

**Comment by kmatias** [comment]
#2628

**Comment by sohagfaruquebd** [comment]
@ajaykumar97 bro it only works if i add it to root.But what if i want to change for a single scene ?

**Comment by ajaykumar97** [comment]
You can set a check on the name of particular scene inside the transitionConfig like:

```
if (scene.route.routeName === 'myScene') {
const inputRange = [index - 1, index, index + 1];

        const opacity = position.interpolate({
            inputRange,
            outputRange: ([0, 1, 0]),
        });

        const translateX = position.interpolate({
            inputRange,
            outputRange: ([width, 0, 0]),
        });

        return {
            opacity,
            transform: [
                { translateX }
            ],
        };
}
```
