### ISSUE TITLE
scene component always recreates when component containing router re-render

### ISSUE THREAD

**Issue by fatfatson** [aksonov/react-native-router-flux#2744]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0
- react-native v0.51

### Expected behaviour
unchanged child components shouldn't recreate thus their local states won't lose

### Actual behaviour
everytime the container component rerender, all the scene components will recreate,  but normal children won't

### Steps to reproduce
see above code:
in render2, `Login` component won't recreate if the parent rerender due to redux state change,
in render3, `Login` component wrapped in `Router/Scene` will.
```

	render2() {
		console.log('render app2');
		return (
			<View style={{ backgroundColor: '#f5f5f5', flex: 1 }}>
				<NetState />
				<Login />
			</View>
		);
	}

	render3() {
		console.log('render app3');
		return (
			<Router
				backAndroidHandler={() => {
					console.log('back...');
					console.log(Actions.state);
					Actions.pop();
					return true;
				}}
			>
				<Scene key="root" hideNavBar>
					<Scene
						key="Login"
						component={Login}
						title="Login"
						onEnter={() => {
							console.log('onenter login');
						}}
					/>
				</Scene>
			</Router>
		);
	}

```

**Comment by piubellofelipe** [comment]
hey @fatfatson , did you resolve this yet?
I managed an workaround for this, hope this help you:

My idea is to wrap my Router in an external Class, and simply return false from shouldComponentUpdate. it's something like this:

```

  render() {
    return (
        <Drawer
          open={this.props.drawerState === 'opened'}
          type="overlay"
          content={<SideBar />}
          tapToClose
          onClose={() => this.props.closeDrawer()}
        >
          <MyRouter />
        </Drawer>
    );
  }
}

class MyRouter extends Component {
  shouldComponentUpdate () {
    // so we keep our state when opening the drawer!!!
    return false;
  }
  render (){
    return (
          <RouterWithRedux key="router">
            <Scene key="root" hideNavBar>
              ...
            </Scene>
          </RouterWithRedux>
    )
  }
}

```

Note that I was facing this issue because opening my drawer was unmounting and mounting again any scene that was being rendered in background. Can't tell if my solution is classy at all, but it's working fine for now

**Comment by aksonov** [comment]
Sorry, it is not intended behaviour to have several Routers.

**Comment by nabilfreeman** [comment]
I had this issue with the provider re-rendering and resetting the router. Fixed using pureComponent on the parent component.
