### ISSUE TITLE
Drawer does not work

### ISSUE THREAD

**Issue by DevNamedZed** [aksonov/react-native-router-flux#2746]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native 4.0.0-beta.24

### Expected behavior
Drawers should work

### Actual behavior
Use of drawer fails with error below

TypeError: Cannot read property 'routeName' of undefined

This error is located at:
    in DrawerView (at DrawerNavigator.js:127)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at SceneView.js:31)

### Steps to reproduce
1. clone the repo
2. go to the example folder and run
3. click on the button 'Go to tabber page'

I upgraded all my nuget packages and drawers stopped working. Seems like there might be some type of breaking change in react-navigator. did not have a chance to read through yet. Possibly workaround downgrading react-navigator 

https://github.com/react-navigation/react-navigation/releases
https://github.com/react-navigation/react-navigation/issues/3095
https://github.com/react-navigation/react-navigation/commit/d5618ebd41ec1ac53cb40301d0f71610fbbb7172

**Comment by DevNamedZed** [comment]
Updating the example as per below fixes

```
            <Drawer
              hideNavBar
              key="drawer"
              contentComponent={DrawerContent}
              drawerImage={MenuIcon}
              drawerWidth={300}
            >

```

to 
           
```
<Drawer
              hideNavBar
              key="drawer"
              contentComponent={DrawerContent}
              drawerImage={MenuIcon}
              drawerWidth={300}
              drawerOpenRoute="DrawerOpen"
              drawerCloseRoute="DrawerClose"
              drawerToggleRoute="DrawerToggle">

```

**Comment by Blapi** [comment]
This issue is known and duplicated from #2718
