### ISSUE TITLE
Scene switching is slow

### ISSUE THREAD

**Issue by xiaoxiaoyongPersonal** [aksonov/react-native-router-flux#2747]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0
- react-native v0.46.4

### Expected behaviour
Scene switching is normal

### Actual behaviour
Scene switching is slow

### Steps to reproduce
i used Actions.xx({Home:this,title:xx}),it will become slow
It's a problem caused by ’this‘ parameter。In the old version, it was normal 。

**Comment by aksonov** [comment]
Sorry, but it is not good practice to pass 'this', you should pass small serializable data.
