### ISSUE TITLE
Reset with transition

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2748]
Since now it's possible to reset child stack, would it be possible to reset to a specific scene with a transition? Such as wix does with resetTo?

Thanks

**Comment by aksonov** [comment]
It is not supported yet, PR is welcome.

**Comment by NSShentu** [comment]
I add this to Actions.  emmmm...

function resetTo(routeName, params) {
    const resetAct = NavigationActions.reset({
        index: 0,
        actions: [
            NavigationActions.navigate({routeName: routeName}, {
                params: params
            })
        ]
    });
    Actions.dispatch(resetAct);
}
Actions.resetTo = resetTo;

**Comment by csmtcy** [comment]
@NSShentu I used your solution and added the new plugin react navigation. It does work.
