### ISSUE TITLE
React flux Data Transmission: Can't transmit specific data through scenes.

### ISSUE THREAD

**Issue by mn7676** [aksonov/react-native-router-flux#2750]
### Version

- react-native-router-flux "16.0.0"
- react-native v0.51.0

### Expected behaviour

While using Actions.reset('drawer',{data: 'Hello Scene'}) function in the scene "page2", it should transmit the data 'Hello Scene' from "page2" to "home" and reset the stack.

page2 :

`import { Actions } from 'react-native-router-flux';

export default class Page2 extends Component{

    onPress(){
        Actions.reset('drawer',{data: 'Hello Scene'});
    }

    render(){
        return(
            <View>
                    <TouchableOpacity onPress={this.onPress}>
                        <Text>reset stack and open home with data</Text>
                    </TouchableOpacity>
                    
            </View>

        )
    }
}`

### Actual behaviour

The data won't transmit to the "home" props.

myRouter :

 `<Router>

                <Lightbox>
                    <Stack key='root' hideNavBar>
                        <Scene key='splash' component={Splash} initial/>
                        <Scene key='page1' component={Page1}/>
                        <Scene key='page2' component={Page2}/>
                        <Drawer
                            hideNavBar
                            key="drawer"
                            contentComponent={myDrawer}
                            drawerWidth={300}
                            drawerOpenRoute = 'DrawerOpen'
                            drawerCloseRoute = 'DrawerClose'
                            drawerToggleRoute = 'DrawerToggle'
                            drawerPosition = 'right'
                        >
                            <Scene key='home' component={Home} hideNavBar/>
                        </Drawer>
                    </Stack>

                    <Scene key='lightbox1' component={Lightbox1}/>
                </Lightbox>

            </Router>`

**Comment by aksonov** [comment]
Sorry, it is not supported yet (passing data via `reset`), PR is welcome
