### ISSUE TITLE
how delete the black line at the bottom of navigationbar

### ISSUE THREAD

**Issue by wangfaguo** [aksonov/react-native-router-flux#2751]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.25
- react-native v0.51.0

### Expected behaviour

 delete the black line at the bottom of navigationbar

### Actual behaviour

do not know how to do

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by Michael-xiaojie** [comment]
I think we should rewrite the tabBarStyle style

**Comment by aksonov** [comment]
I can't reproduce. Just added `navTransparent` to register stack for Example project and see transparent navbar.
