### ISSUE TITLE
Exit the App when the default scenario is returned

### ISSUE THREAD

**Issue by Michael-xiaojie** [aksonov/react-native-router-flux#2752]
### Version
Tell us which versions you are using: 4.0.0-beta.24

- react-native-router-flux  4.0.0-beta.24
- react-native 0.51.0
    ###I have four scenarios, A, B, C, D, A is the default scene, when I click to D scene in turn, I click the back button and in theory should be returned to A scene, but it directly out of the App, here is my code

<Scene key="root" >
        <Stack hideNavBar key="stack" titleStyle={{ alignSelf: 'center' }} >
            <Scene  key="Scenne" tabBarPosition="bottom" hideNavBar  >
                <Tabs key="Tabs"
                    swipeEnabled
                    showLabel={false}>
                    <Stack
                        key="tab1"
                        title="AA"
                        tabBarLabel="tab1"
                        icon={TabIcon}
                    >
                        <Scene key="aaa" component={Index} ></Scene>
                    </Stack>
                    <Stack
                        key="tab2"
                        title="BB"
                        tabBarLabel="tab2"
                        icon={TabIcon}
                    >
                        <Scene key="bbb" component={My} ></Scene>
                    </Stack>
                    <Stack key="tab3" tabBarLabel="tab3">
                        <Scene key="tab3_1" component={My} title="CC"  icon={TabIcon} />
                    </Stack>
                    <Stack key="tab4" tabBarLabel="tab4">
                        <Scene key="tab4_1" component={My} title="DD" icon={TabIcon} />
                    </Stack>
                </Tabs>
            </Scene>
        </Stack>
    </Scene>

**Comment by Michael-xiaojie** [comment]
here is my code:  
<Scene key="root" >
        <Stack hideNavBar key="stack" titleStyle={{ alignSelf: 'center' }} >
            <Scene  key="Scenne" tabBarPosition="bottom" hideNavBar  >
                <Tabs key="Tabs"
                    swipeEnabled
                    showLabel={false}>
                    <Stack
                        key="tab1"
                        title="AA"
                        tabBarLabel="tab1"
                        icon={TabIcon}
                    >
                        <Scene key="aaa" component={Index} ></Scene>
                    </Stack>
                    <Stack
                        key="tab2"
                        title="BB"
                        tabBarLabel="tab2"
                        icon={TabIcon}
                    >
                        <Scene key="bbb" component={My} ></Scene>
                    </Stack>
                    <Stack key="tab3" tabBarLabel="tab3">
                        <Scene key="tab3_1" component={My} title="CC"  icon={TabIcon} />
                    </Stack>
                    <Stack key="tab4" tabBarLabel="tab4">
                        <Scene key="tab4_1" component={My} title="DD" icon={TabIcon} />
                    </Stack>
                </Tabs>
            </Scene>
        </Stack>
    </Scene>

**Comment by Blapi** [comment]
Check #2737
