### ISSUE TITLE
Issue on Navigation 

### ISSUE THREAD

**Issue by jamesDZ** [aksonov/react-native-router-flux#2753]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

<Scene key="HomeScreen" component={HomeScreen} title="Home"/>
              <Scene key="LandingScreen" component={LandingScreen} title="Login"/>
              <Scene key="PhoneRegister" component={PhoneRegister} title="Register"/>
              <Scene key="OtpScreen" component={OtpScreen} title="Register"/>
### Expected behaviour

Screen navigate but Only Screen-1  is open full screen rest of the other is opening as drawer. why ? 

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by jaderYang** [comment]
I run the example without changing any code, and only the 'MessageBar alert' responds to my click in the LaunchPage. There is something wrong with navigation.

**Comment by jamesDZ** [comment]
I use this libaray in my code and it is working but only 1st screen is navigating properly. 
2nd and 3rd screen navigating as a drawl.

**Comment by Blapi** [comment]
Show your navigation code please.

**Comment by jamesDZ** [comment]
This is Route.js file
import React, { Component } from 'react';
import {Router,Stack,Scene} from 'react-native-router-flux';

import HomeScreen from './Screens/HomeScreen';
import LandingScreen from './Screens/LandingScreen';
import PhoneRegister from './Screens/PhoneRegister';
import OtpScreen from './Screens/OtpScreen';

export default class Routes extends Component{

    render(){
        return(
            <Router>
            <Stack key="root" hideNavBar={true}>
              <Scene key="HomeScreen" component={HomeScreen} title="Home"/>
              <Scene key="LandingScreen" component={LandingScreen} title="Login"/>
              <Scene key="PhoneRegister" component={PhoneRegister} title="Register"/>
              <Scene key="OtpScreen" component={OtpScreen} title="Register"/>
              {/* <Scene key="home" component={Home}/> */}
            </Stack>
          </Router>
        )
    }
}


On Buttons click I am calling these functions like this :- 

Already imported this:- 

 import { Actions } from 'react-native-router-flux';
anonymus(){
      Actions.LandingScreen()
  }

  PhoneRregister(){

    Actions.PhoneRegister();
  }

  fbLogin(){
   
    Actions.OtpScreen()
  }

**Comment by Blapi** [comment]
Ok.. so what's your issue? If it navigates properly I don't really think it is an issue with the library (because you are doing it well, maybe add an initial scene) but more like a problem with your components

**Comment by jamesDZ** [comment]
That is I am not able to identify why it is taking Drawable Menu.. I want it navigate like the previous screens but it is not happening can you help me on that.

**Comment by aksonov** [comment]
@jamesDZ Just installed Example from clean clone and then `yarn` and it works without any problem.
