### ISSUE TITLE
react native ListView not working after one update of dataSource

### ISSUE THREAD

**Issue by CoderHar** [aksonov/react-native-router-flux#2754]
hello guys, im here trying to make a game but im encountering with a problem in which the first click on the tile would change the image and after that next click onwards the image of the tile doesn't change is this a problem of the listView that it doesn't  re-render after 

`# LIstView component
  class ListSection extends Component{
   
    
    renderRow(image){
        console.log("each image",image)
        return (<Row image={image}/>)
    }

    render(){
        console.log("props",this.props)
        return(
            <View>
                {this.props.fetched==1?(
                    <ListView  
                        initialListSize={16}
                        removeClippedSubviews={false} 
                        enableEmptySections
                        contentContainerStyle={Style.ListViewStyle}
                        dataSource={this.props.datasource} 
                        renderRow={this.renderRow}/>)
                        :null}
            </View>
        )
    }
}

const Style={
    ListViewStyle:{
        flexDirection: 'row',
        flexWrap:'wrap',
    }
}

const mapStateToProps=state=>{
    console.log("state",state);
    const {datasource,fetched,imageArray}=state.list;
    return{
       datasource,
       fetched,
       imageArray ``
    }
}

export default connect(mapStateToProps,actions)(ListSection);

# Row Component
class Row extends Component{
  
    render(){

        console.log('element',this.props)
        const {element,i}=this.props.image
        const {imageArray,turn}=this.props;
        return(
        <View style={Style.containerStyle} >
                <TouchableWithoutFeedback onPress={()=>this.props.changeElement(imageArray,turn,i)} >  
                    <Image  style={{width:78.8,height:79}}
                            source={element}/>
                </TouchableWithoutFeedback>
        </View>
        )
    }
}
Style={
    containerStyle:{
      borderWidth:13,
      borderColor:'#424242',
      width:102.8
    }
  }
mapStateToProps=state=>{
  console.log("State in Row",state)
  const {imageArray,turn,image1}=state.list;
  return {imageArray,turn,image1}
}

export default connect(mapStateToProps,actions)(Row);
`
![screenshot_1514885333](https://user-images.githubusercontent.com/34229360/34479557-8c40fca8-efcd-11e7-8230-a9f4fc850067.png)
![screenshot_1514885327](https://user-images.githubusercontent.com/34229360/34479571-98dd35b2-efcd-11e7-9f9f-c3c0225209cc.png)

**Comment by Blapi** [comment]
Not related tout RNRF, use StackOverflow if you want help with this issue.
