### ISSUE TITLE
Question: Tabview showing lines after Tab?

### ISSUE THREAD

**Issue by dlucidone** [aksonov/react-native-router-flux#2755]
In emulator its not there but then i tried installing it in device its showing lines after particular tab. Any solution to this?
![whatsapp image 2018-01-02 at 5 16 43 pm](https://user-images.githubusercontent.com/9256365/34482907-0d081516-efe1-11e7-9695-c5522e3adfdb.jpeg)

**Comment by aksonov** [comment]
Sorry, can't help here, probably the question to stackoverflow. It looks like about proper styling. Have you tried Example project with custom styles?
