### ISSUE TITLE
There is no route defined for key "X"

### ISSUE THREAD

**Issue by 14076156deiefyp** [aksonov/react-native-router-flux#2756]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.51

### Expected behaviour
I am new with React Native.
I have two route JS file, one is for before login routing, and one is for logged in routing.  It should be alright to swap between these two JS file and no error occurred in previous time.

App.js (code in render())

    if(authStatusReported) {
      if(isUserAuthenticated){
        return (
          <View style={styles.container}>
          <StatusBar
            backgroundColor="#aeaeae"
          />
          <Homeroute />
          </View>
        );
        
      }
      else{
        return (
          <View style={styles.container}>
          <StatusBar
            backgroundColor="#aeaeae"
          />
          <Route />
          </View>
        );
        
      }
    }
    else{
      return (
        <View style={styles.container}>
        <StatusBar
          backgroundColor="#aeaeae"
        />
         <Loading/>
        </View>
      );
    }
  

Route.js  (code in Router)

> <Router>

       <Stack key="root" hideNavBar={true}>
          <Scene key="login" component={Login} title="Login" initial={true} />
          <Scene key="signup" component={Signup} title="Register"/>
       </Stack>
</Router>`

Homeroute.js  (code in Router)

> <Router>

    <Scene key="home">
        <Scene key="main" 
                      tabs={true}  
                      default="tab1" 
                      tabBarPosition='bottom' 
                      activeTintColor="#000000">
                <Scene  key="Join"
                        title="Join"
                        hideNavBar={true}
                        iconName='car'
                        icon={TabIcon}
                        component={Joincar}
                        initial={true}
                />
                <Scene  key="Hostcar"
                        title="Host"
                        iconName='flag-variant'
                        icon={TabIcon}
                        hideNavBar={true}
                        component={Hostcar}
                />

                <Scene  key="Register"
                        title="Register Car"
                        iconName='border-color'
                        icon={TabIcon}
                        hideNavBar={true}
                        component={Registercar} />

                <Scene  key="Profile"
                        title="Profile"
                        iconName='account'
                        icon={TabIcon}
                        hideNavBar={true}
                        component={Profile} />
                </Scene>
            </Scene>
      </Router>

### Actual behaviour
It shows error "There is no route defined for key login.  Must be one of: 'main' " when logged in and "There is no route defined for key main.  Must be one of: 'login','signup'" when logged out. But it is work to load the pages when I refresh it again. Did I miss something that need to do?

**Comment by recs182** [comment]
I have problems with this structure too... so far nothing that I tried solved it.

**Comment by aksonov** [comment]
Sorry, you should declare your scenes within one file, one structure - I see different `Route.js`, 'Homeroute.js' in your example.
