### ISSUE TITLE
can't  refresh the last page

### ISSUE THREAD

**Issue by xiaoxiaoyongPersonal** [aksonov/react-native-router-flux#2758]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.24
- react-native v0.46.4

### Expected behaviour
can refresh  the last page

### Actual behaviour
can't  refresh the last page

### Steps to reproduce
1.Action.a()
2.Action.b()
3.Actions.pop({refresh: {update: true}})  (can work)
4.Action.b()
5.Actions.pop({refresh: {update: true}})  (can't work)

**Comment by aksonov** [comment]
As I see `a` screen already has `update` property after step `3`, so it will not be updated after step 5 (the same property). Anyway it is question for stackoverflow, not issue for RNRF.

**Comment by xiaoxiaoyongPersonal** [comment]
thanks,I added a time parameter that can be updated
