### ISSUE TITLE
How to create this structure?

### ISSUE THREAD

**Issue by scwl-studio** [aksonov/react-native-router-flux#2762]
I've got a one problem.
I should implement a structure, where in any tab of tabbar i can show my scene (check my image).
Help me pls :(
![default](https://user-images.githubusercontent.com/23195550/34583693-c6f2a17a-f1a9-11e7-9b76-b036ccea7c72.png)

**Comment by aksonov** [comment]
It is more question for stackoverflow, not github issue. You should check Example project. Usually it could be outer container-stack OR it could be 'clone' scene.
