### ISSUE TITLE
Drawer enters the screen from the opposite direction on RTL Devices the first time it opens

### ISSUE THREAD

**Issue by Assem-Hafez** [aksonov/react-native-router-flux#2764]
- react-native-router-flux v4.0.0-beta.27
- react-native v0.49.5

**Comment by barghi** [comment]
same issue here

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by firdousali86** [comment]
Can easily produce this on:
"react-native": "^0.55.3"
"react-native-router-flux": "^4.0.1"
