### ISSUE TITLE
Type replace not removing transition animation

### ISSUE THREAD

**Issue by munkhorgil** [aksonov/react-native-router-flux#2766]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0 (v3 is not supported)
- react-native v0.16.0

### Expected behaviour
Change scene without transition animation

### Actual behaviour
Scene with type="replace" not removing transition animation

Main is initial component that decides user is logged in or not. When user is logged in it navigates to A tabbar with transition. Even I put type="replace" still shows transition animation.
```
<Router>
    <Scene key="root">
        <Scene key="main" inital type="replace"/>
        <Scene key="login"/>
        <Scene key="tabbar">
            <Scene key="a"/>
            </Scene key="b"/>
        </Scene>
    </Scene>
</Router>
```

**Comment by Blapi** [comment]
The "replace" type will not affect the transition, it will affect your navigation stack.

If you want to fix your transition issue, please have a look at #2628, I still have to do a PR for this but I'm too busy with my own work..
