### ISSUE TITLE
TypeError: Cannot read property 'delegate' of null at ExRouter.componentWillUnmount 

### ISSUE THREAD

**Issue by seantempesta** [aksonov/react-native-router-flux#277]
I'm hitting an exception if I rapidly switch between routes in the iOS Simulator.  Looks like it's in [ExRouter.js](https://github.com/aksonov/react-native-router-flux/blob/master/ExRouter.js) (lines 197-201):

```javascript
    componentWillUnmount() {
        if (this === Actions.currentRouter.delegate) {
            Actions.currentRouter = null;
        }
    }
```

The component is checking currentRouter for this delegate property, but it's already null.  Has anyone else hit this issue?  I guess the problem could be fixed by checking if it's already null?

I don't really know how to repro the issue as it happens randomly when I'm clicking around really fast in my app.

**Comment by aksonov** [comment]
Should be ok with latest version.
