### ISSUE TITLE
Double rendering of navigator

### ISSUE THREAD

**Issue by NahuelBordon** [aksonov/react-native-router-flux#2770]
Hello guys, I have a problem when I try to build my app on Ios, 
In my main screen , i have a double rending of natvar, only on ios , on android it works perfectly , and i don't know why, i don t know which  is the reason of that, 
I really need help , . @aksonov 

Lot of thanks

Ios : 
![img_1069](https://user-images.githubusercontent.com/35227299/34676070-52667a16-f46a-11e7-83ee-7e19dd76cae1.PNG)

Android:
![screenshot_20180108-095806](https://user-images.githubusercontent.com/35227299/34676830-ea395a0a-f46c-11e7-8dca-340a681c8b5a.png)

code:
![screen shot 2018-01-08 at 12 15 51](https://user-images.githubusercontent.com/35227299/34677082-be4bf654-f46d-11e7-8155-ec6f8283669c.png)

**Comment by catrieldapice** [comment]
+1 I have a problem, it seems be the same :/

**Comment by NahuelBordon** [comment]
Hello again, I really need your help to resolve this, 
I couldn't find anything to fix it.
Do you have any idea about it ?

@aksonov

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
