### ISSUE TITLE
how make the left drawer push the entire screen to the right?

### ISSUE THREAD

**Issue by DavitVosk** [aksonov/react-native-router-flux#2771]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.22
- react-native 0.50.0

### Expected behaviour

I wanna make the left drawer to push the entire screen to the right

### Actual behaviour

The drawer just slides on the screen closing its content

Please help to find a solution of doing this action.

**Comment by DavitVosk** [comment]
You can see my code here: 

<Scene panHandlers={null} drawer hideNavBar drawerPosition={'left'} contentComponent={LeftDrawer}>
                    <Scene key={MAIN_CONTENT} tabs tabBarStyle={{backgroundColor: 'black'}} tabBarPosition={'bottom'} tabBarComponent={BottomToolbar}>
                        <Scene key={DASH_BOARD} hideNavBar component={DashboardScreen} />
                        <Scene key={CHAT_SCREEN} hideNavBar component={ChatScreen} />
                   <Scene>
<Scene>

**Comment by rvasoya** [comment]
I also want to know how to push the screen to the right side when the drawer is open.
https://github.com/react-navigation/react-navigation/issues/939
this issue helps in that but it user react-navigation.
I want to accomplish that with react-native-router-flux.

I'm using 
"react-native": "0.55.4",
"react-native-router-flux": "^4.0.0-beta.31"
