### ISSUE TITLE
How to use component template for some routes?

### ISSUE THREAD

**Issue by melkayam92** [aksonov/react-native-router-flux#2773]
### Version
Tell us which versions you are using: 

- react-native-router-flux  - latest.
- react-native v0.?.? - latest

I can do that:

  ```
<View>
         <Router>
               <Scene>
                <Scene>
         </Router>
         <Footer/>
  </View>
```

But how can I do that? 
  ```
<View>
         <Router>
               <Scene>
               <Scene>                    
                <View>
                      <Scene>
                      <Footer/>
                 </View>
         </Router>
  </View>
```
I mean for some routes i want to display the footer, but not for all.

How can I achieve that? -I was looking over the examples but didn't find anything similar.

Thanks.

**Comment by Blapi** [comment]
Because this is not really related to RNRF, you should create a template Component with a footer and taking children as params which will be your Components you need.

```
import FooterComponent from 'path'

class ParentComponent extends React.Component {
  render() {
    return (
      <View>
        {this.props.children}
        <FooterComponent />
      </View>
    )
  }
}

export default ParentComponent
```

and then

```
import ParentComponent from 'path'

class ChildComponent extends React.Component {
  render() {
    return (
      <ParentComponent>
        <View>
          {/* put all the stuff you want */}
        </View>
      </ParentComponent>
    )
  }
}

export default ChildComponent
```

So then, you create as many differents ChildComponent you need and you pass them as Scene's Component

**Comment by melkayam92** [comment]
I know I can do that, but it doesn't what I asked for. 
What you saying is that for every scene I want the footer I will wrap in that staff, and no , I wanted to do that in  one place. Please look at my example above!

**Comment by Blapi** [comment]
@melkayam92  what's the status there?
