### ISSUE TITLE
 I want to hide hideTabBar, But it's not always easy to make it

### ISSUE THREAD

**Issue by SurpassRabbit** [aksonov/react-native-router-flux#2775]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour
  If I want to hide hideTabBar, the first success, the second failed.
I need to hide / show tabbar in the page.

### Actual behaviour

The first time is ok, the second one fails, the third time is ok. But the layout is wrong

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.

```
this.state.hideTabBar
                ?
                <Animatable.View
                    key='bottom'
                    // animation="fadeInUp"
                    style={styles.deleteViewStyle}>
                    <Text style={styles.deleteStyle}>Delete</Text>
                </Animatable.View>
                :
                null
```
2.

```
 _editPress = () => {

        this.editSelected = !this.editSelected ;

        this.setState({
            hideTabBar: !this.state.hideTabBar
            }, () => {
                Actions.refresh({
                    hideTabBar: this.state.hideTabBar
                });
            }
        );
    };
```

**Comment by Blapi** [comment]
@SurpassRabbit don't forget to help the community, if you closed this issue because you found the solution, share it ! You might not be the only one with this issue.

**Comment by GianniGM** [comment]
@SurpassRabbit i have the same issue may you post the solution?
