### ISSUE TITLE
onLeft and onRight not firing 

### ISSUE THREAD

**Issue by aelallam** [aksonov/react-native-router-flux#2777]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.24
- react-native v0.50.3

### Expected behaviour

When i press on the left button, or right button, the function should fire.

### Actual behaviour

It does not.

### Steps to reproduce

I have the following Scene with child scenes: 
```
      <Scene key="eng"
          drawer
          drawerIcon={<MenuButton />}
          drawerWidth={250}
          hideNavBar
          contentComponent={MenuContent}
          renderRightButton={SettingButton}
          onRight={() => console.log('hello)}
        >
          <Scene key="home" component={Home} hideNavBar={false} title="Home" initial />
          <Scene key="company" component={Companies} hideNavBar={false} title="Companies" />
          <Scene key="fav" component={Favourites} hideNavBar={false} title="Favourites" />
        </Scene>
```
The component inside my renderRightButton looks like this: 
```
const SettingButton = () => {
  return (
    <TouchableOpacity style={styles.iconContainerStyle}>
      <Icon name='md-settings' size={20} style={styles.iconStyle} />
    </TouchableOpacity>
  );
};
```
When I do press on the right button, I do not see a hello in the console log. Why is it not firing ?

**Comment by aksonov** [comment]
onRight can be used only with rightTitle and rightButtonImage. If you use renderRightButton, onRight is ignored for obvious reason

**Comment by aelallam** [comment]
@aksonov Please tell me how to resolve this? As you can see my setting button is not an image nor a title.

**Comment by aksonov** [comment]
Just add your onPress within SettingsButton. Sorry, please ask questions at stackoverlflow, not here. It is for issues.
