### ISSUE TITLE
Public API for navigation history

### ISSUE THREAD

**Issue by todorone** [aksonov/react-native-router-flux#2778]
Is there any approved way to access navigation history atm? I can access `Action.state.routes` to watch it, but is it "right" way as I can't find any doucmented one?

**Comment by Blapi** [comment]
That's what I'm using when I need to debug, don't know if there's something else but it's enough for me

**Comment by todorone** [comment]
@Blapi Thanks. It's more than enough, I just want to make sure it's kind of approved API so it won't break with next release...

**Comment by daviscabral** [comment]
It has changed from v3 - but I don't think it is going to change so soon. 

Since it seems this issues seems to be solved, I am closing it - feel free to reopen in case it needs further discussion.
