### ISSUE TITLE
Can someone show we an example how i can change the Animation while navigating.

### ISSUE THREAD

**Issue by Dorentin1997** [aksonov/react-native-router-flux#2780]
I want an animation that when i change screen another screen  comes on top of it form left, Like in iphone. My application is for andorid.

This is router code.

`<Router>
                <Stack key="root" hideNavBar={true} duration={0} >
                        <Scene key="splashScreen" sceneStyle={{ backgroundColor: 'transparent '}}  component={SplashScreen} title="SplashScreen"/>
                        <Scene key="homeScreen" sceneStyle={{ backgroundColor: 'transparent '}} type="reset"  component={HomeScreen} title="HomeScreen"/>
                        <Scene key="signUp" sceneStyle={{ backgroundColor: 'transparent '}} component={Signup} title="Signup"/>
                        <Scene key="signIn" sceneStyle={{ backgroundColor: 'transparent '}} component={SignIn} title="SignIn"/>
                        <Scene key="addSafe"  sceneStyle={{ backgroundColor: 'transparent '}} component={AddSafe} title="AddSafe"/>
                        <Scene key="safeKeyEntry" sceneStyle={{ backgroundColor: 'transparent '}} component={SafeKeyEntry} title="SafeKeyEntry"/>
                        <Scene key="safeList"  sceneStyle={{ backgroundColor: 'transparent '}} type="reset" component={SafeList} title="SafeList" duration={0} />
                        <Scene key="log" sceneStyle={{ backgroundColor: 'transparent '}} component={Log} title="Log"/>
                        <Scene key="settings" sceneStyle={{ backgroundColor: 'transparent '}} component={Settings} title="Settings"/>
                </Stack>
            </Router>`

**Comment by Blapi** [comment]
#2628
