### ISSUE TITLE
RNRF V4 w/ [FBsdk, Mobx-Persist, Node, AsyncStorage] 

### ISSUE THREAD

**Issue by richTheCreator** [aksonov/react-native-router-flux#2782]
> Not 100% sure this is the place to post this but the contributing guidelines do say "How To's", which this is. 

![RNG](https://github.com/richTheCreator/RN_GUARD/blob/master/src/assets/images/banner.png?raw=true)

### What is it?
A starter kit for social authentication apps built on RNRF V4. The routes are all secured with a combination of `mobx-persist`, `fb-sdk`, `rnrf`, and `asyncStorage`.

There is also a backend server written in node, mongo, and express that verifies the token from the frontend and then provides a secure API.

### Why does it exist?
There aren't too many current RNRFV4 demo apps that have auth baked in. I've been using RNRF for about 2 years so I'm pretty familiar with it and the recent switch to MobX only support really messed with me and a few others. Hopefully, this can provide a rough starting point!

### Where to get it 
Check out the repo [here](https://github.com/richTheCreator/RN_GUARD)!

**Comment by aksonov** [comment]
Great starter kit! Feel free to submit PR to add your link into our docs. Btw, check latest version that works with react navigation v2.x
