### ISSUE TITLE
Duplicate scenes when using stack within stack

### ISSUE THREAD

**Issue by Jun711** [aksonov/react-native-router-flux#2784]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

"react": "16.0.0",
"react-native": "0.50.4",
"react-native-router-flux": "^4.0.0-beta.27",

### Expected behaviour
One scene which is within a stack is pushed onto the view.

### Actual behaviour
The same scene is pushed twice but with different key. One of the keys has a prefix of 'Init_'.
Check the screenshot to see Actions state. Maybe I configured the scenes incorrectly? 

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.
Duplicate About Scenes:
```
 onBackPress() {
    console.log('Actions.state: ', Actions.state)
    if (Actions.state.index !== 0) {
      Actions.pop();
      return true;
    }
    
    return false;
  }

<Router
  backAndroidHandler={this.onBackPress.bind(this)}
>
  <Stack
    hideNavBar
    key='root'
    titleStyle={{alignSelf: 'center'}}
  >
    <Scene key='home' component={HomeContainer} title='home' initial/>
    <Stack
      key='_about'
      titleStyle={{alignSelf: 'center'}}
    >
      <Scene hideNavBar key='about' component={AboutContainer} title='about'/>
    </Stack>
  </Stack>
</Router>
```
Console screenshot:
![screen shot 2018-01-10 at 5 48 28 pm](https://user-images.githubusercontent.com/6880939/34804669-ae77b598-f62e-11e7-902a-8739d0ba3edf.png)

The following works:
```
<Router
  backAndroidHandler={this.onBackPress.bind(this)}
>
  <Stack
    hideNavBar
    key='root'
    titleStyle={{alignSelf: 'center'}}
  >
    <Scene key='home' component={HomeContainer} title='home' initial/>
    <Scene hideNavBar key='about' component={AboutContainer} title='about' />
  </Stack>
</Router>
```

**Comment by Blapi** [comment]
```
<Router
  backAndroidHandler={this.onBackPress.bind(this)}
  scenes={scenes}
>
```

What is in your scenes prop ?

And is it doing the same when you have more than 1 Scene in your 2nde Stack ?

**Comment by Jun711** [comment]
@Blapi 

It is the same function as the snippet above. 

```
 onBackPress() {
    console.log('Actions.state: ', Actions.state)
    if (Actions.state.index !== 0) {
      Actions.pop();
      return true;
    }
    
    return false;
  }
```

and, yes, I have tried with 2 scenes in the second stack, the first scene on the second stack was duplicated but the second scene on the second stack was not duplicated. The structure is as below:

```
<Router
  backAndroidHandler={this.onBackPress.bind(this)}
>
  <Stack
    hideNavBar
    key='root'
    titleStyle={{alignSelf: 'center'}}
  >
    <Scene key='home' component={HomeContainer} title='home' initial/>
    <Stack
          hideNavBar
          key='root'
          titleStyle={{alignSelf: 'center'}}
        >
          <Scene hideNavBar key='about' component={AboutContainer} title='about' />
          <Scene
            hideNavBar={false}
            key='faq'
            component={FaqContainer}
            title='FAQ'
            titleStyle={{alignSelf: 'flex-start'}}
            back={true}
          />
    </Stack>
  </Stack>
</Router>
```

**Comment by Blapi** [comment]
I was talking about the fact that you had a `scenes={scenes}` as prop in your Router, not your `onBackPress`function, but you preferred edit your post and remove this..

Anyway, you have 2 Stack with the same key, there's an issue there. And also, how are you navigating to your Scene ? Are you navigating to the Scene or to the Stack?

**Comment by Jun711** [comment]
@Blapi sorry, scenes prop was because all the scenes were imported like the following so I forgot to remove them when I put them together. That was also a mistake when I tried to reproduce the error. The key of the stack can be different and still produce duplicated first scene. 

```
import scenes from '../routes/scenes';

<Router
     backAndroidHandler={this.onBackPress.bind(this)}
     scenes={scenes}
/>
```
 I am navigating to the first scene on the second stack. `Actions.about` . yes, that is the problem. Thanks @Blapi
