### ISSUE TITLE
Drawer showing white line or border to left of the screen on some android phones

### ISSUE THREAD

**Issue by TarunBardawa** [aksonov/react-native-router-flux#2785]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4
- react-native v0.52

### Expected behaviour
Should not show the drawer's right border on the left of screen when drawer is closed.
(its only showing in Samsung galaxy s8 device, in other devices its working fine.)

### Actual behaviour
![whatsapp image 2018-01-10 at 3 11 49 pm 1](https://user-images.githubusercontent.com/22677538/34811098-28035836-f6c5-11e7-9cbc-1bdeafdcaa36.jpeg)

you can see a white line or border of drawer on left side, it is appearing on every Scene which is under the Drawer..

Here is my code of Drawer 

`<Router sceneStyle={{backgroundColor : '#fff'}} backAndroidHandler={this.onBackPress}>
        <Scene key='root'>
        <Scene initial={!this.state.logged} key='launchScreen' component={LaunchScreen} title='LaunchScreen' panHandlers={null} hideNavBar />
            <Scene key='selectType' component={SelectType} title='MY APP NAME'  hideNavBar/>
            <Scene key='login' component={LoginScreen} title='MY APP NAME' hideNavBar />
            <Scene key='subscription' component={Subscription} title='' hideNavBar />
            <Scene key='signup' component={SignUpScreen} title='MY APP NAME' hideNavBar />
            <Scene key='mobile' component={MobileVerification} title='Verification' hideNavBar/>
            <Scene key='payment' component={Payment} title='PURCHASE' hideNavBar />
        <Scene key='drawer' drawer contentComponent={DrawerContent} open={false} hideNavBar sceneStyle={{backgroundColor : '#fff'}} drawerWidth={width*0.74} gestureResponseDistance="200">
          <Scene key='drawerChildrenWrapper' navigationBarStyle={Styles.navBar} titleStyle={Styles.title} leftButtonIconStyle={Styles.leftButton} rightButtonTextStyle={Styles.rightButton}>

            <Scene key='homeScreen' component={HomeScreen} title='HOME' hideNavBar={false} navBar={CustomNavBar} panHandlers={null} />
            <Scene key='bookmarks' component={Bookmarks} title='BOOKMARKS' hideNavBar={false} navBar={CustomNavBar} />

        </Scene>
        <Scene key='inbox' component={Inbox} title='MESSAGES' hideNavBar/>
        <Scene key='chatScreen' component={ChatScreen} title='Ernest Woods' hideNavBar={true} />
        <Scene key='editProfile' component={EditProfile} title='Edit Profile' hideNavBar />
        </Scene>
      </Router>`

**Comment by niices** [comment]
I have the same BUG ~ ~
![image](https://user-images.githubusercontent.com/8327775/34814859-32435902-f6ea-11e7-8a5e-53cd83adc0a9.png)
![image](https://user-images.githubusercontent.com/8327775/34814868-374a4f28-f6ea-11e7-9cf7-ee48514176eb.png)

**Comment by andidev** [comment]
I have this issue in ios devices as well

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by nathanguigui** [comment]
not fixed in 4.2.0 :(
