### ISSUE TITLE
Intermediate Tab's componentDidMount get called when switching tabs

### ISSUE THREAD

**Issue by sadi304** [aksonov/react-native-router-flux#2786]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24^
- react-native v0.50.1

### Expected behaviour

componentDidMount() should not be called when switching to another tab

### Actual behaviour

# Home  # Middle # Last 

When switching from Home to Last, Middle's componentDidMount get called

### Steps to reproduce
Default App Config

---
I am not sure whether its a default behaviour or not. If default, any way to bypass this scenario? as Get request is being called in the intermediate tab that results in the callback call of the request even on the other tab

**Comment by sadi304** [comment]
closing . just testing a thing .

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
