### ISSUE TITLE
[Question] Why are invisible scenes back in the stack still rendered in iOS?

### ISSUE THREAD

**Issue by jan-happy** [aksonov/react-native-router-flux#2788]
### Version
- react-native-router-flux 4.0.0-beta.27
- react-native 0.51.0

### Expected behaviour
I have a stack of scenes in iOS, scene 3 is on top:
scene 1 - scene 2 - scene 3

Scene 1 & scene 2 don't need re-rendering since they are not visible

### Actual behaviour
Scene 1 & scene 2 are being rendered

Is this a limitation of UINavigationController? When I have a performance hogging module like a MapView in scene 1 this slows down the app even if only scene 3 is visible. 
Thanks for clarifications.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
