### ISSUE TITLE
Unable to pass function as a prop down to scene 

### ISSUE THREAD

**Issue by KunwarSingh** [aksonov/react-native-router-flux#2790]
I'm trying to pass  function down t scene from top level flie with <Router> component
`
           <Router>
                <Scene key="root">
                    <Scene
                        key="WelcomeModal"
                        component={WelcomeModal}
                        title={Env.welcomeTitle}
                        customePropFunc={this.customPropFunc}
`

It shows undefined prop in that scene, If above is not possible, may I know how can I trigger a function inside component of Scene by clicking onRight or onLeft in Navbar

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.8.0
- react-native v0.43

**Comment by Blapi** [comment]
You should use the v4 of RNRF, v3 is not supported anymore.

If this is about passing props, you have to read the doc and check the Example project.
