### ISSUE TITLE
App hangs on use of Actions.refresh()

### ISSUE THREAD

**Issue by sujay-bidchat** [aksonov/react-native-router-flux#2791]
### Version
Tell us which versions you are using: 4.0.0-beta.24

### Expected behaviour
App should not hang after rendering view using **Actions.refresh();** on **NavigationBar** after performing some action such as API call.

### Actual behaviour
App hangs after rendering view using **Actions.refresh();** on **NavigationBar** after performing some action such as API call / in-app logic.
Error: Maximum call stack reached
XHR finished loading: POST "http://localhost:8082/callback_result".
XHR finished loading: POST "http://localhost:8082/call_method".

**Comment by sujay-bidchat** [comment]
@simonso3 that workaround do not seam to work for me.

**Comment by simonso3** [comment]
Are you calling it multiple times relatively quickly? I had the same problem when I discovered a bug in my code that I was calling refresh multiple times unnecessarily.

**Comment by EvianZhow** [comment]
@simonso3 I encountered this when calling `Actions.refresh()` both on `componentDidMount` and `componentWillReceiveProps`. Former is to set a default navigation bar component, latter is to update it. If `Actions.refresh()` fired too quickly, RNRF will loop in `Navigation/SET_PARAMS` and cause app to freeze.

**Comment by aksonov** [comment]
Use `setTimeout` for this.
