### ISSUE TITLE
Actions.SCENE() re rendering all visited Scene

### ISSUE THREAD

**Issue by salimbutex** [aksonov/react-native-router-flux#2794]
### Version
->react-native-router-flux 4.0.0

###explanation. 
Suppose I have 3 scene. A,B,C
I am now at Scene A, Then I am moving to C Using Actions.C(). Then Moving to B by Actions.B().
Now I want to back to A Scene without re render. I can use Actions.A(). But which re renders A Fully.

### Expected behaviour
Actions.SCENE() should not re render already visited Scene. 

### Actual behaviour
Actions.SCENE()  re rendering all visited SCENE

### Steps to reproduceissue and include link here.
1. Create an project 
2. and follow my example 
3.

**Comment by Blapi** [comment]
Considering your logic, this is the expected behaviour.

**Comment by salimbutex** [comment]
I think, Actions.popTo() is working as per my requirements. but is there any way, I can check Actions.popTo() success or not?
