### ISSUE TITLE
Reset stack however pass data between screens

### ISSUE THREAD

**Issue by Schabaani** [aksonov/react-native-router-flux#2795]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.27
- react-native 0.51.0

```
  <Router>
        <Scene>
            <Scene
                key="login"
                component={LoginScreen}
                initial
                type="reset"
            />
            <Scene
                key="registerScreen"
                component={RegisterScreen}
            />

            <Scene
                key="codeValidationScreen"
                component={CodeValidationScreen}
            />

            <Drawer
                hideNavBar
                key="drawerMenu"
                contentComponent={SideMenu}
                drawerWidth={250}
                drawerPosition="right"
            >
                <Scene
                    key="profileScreen"
                    component={ProfileScreen}

                />
                <Scene
                    key="carsListScreen"
                    component={CarsListScreen}
                />

                <Scene
                    key="carViewScreen"
                    component={CarViewScreen}
                />

            </Drawer>
        </Scene>





    </Router>);
```

And:
`Actions.drawerMenu(params)
`
### Actual behaviour

I want to navigate from login to drawerMenu. After login I need to reset stack that I cant go back. 
**In loginScreen:**
```
const params= {
            user_name: data.params.name,
            user_id: data.params.id,
           type: 'reset'
            };
Actions.drawerMenu(params)
```

After reset, in destination(SideMenu) I dont have access to user_id and user_name
**In SideMenu**
```
const {params} = this.props.navigation.state;
//parasm.user_id == undefinded
```

### Expected behaviour

I need to reset and access information that pass to destination. What should I do?
If I don't reset, user_id and other info are defined. But I can go back.

**Comment by Schabaani** [comment]
I am using [redux ](https://github.com/reactjs/redux)for pass data and react-native-router-flux only for navigation.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by vickykeshri** [comment]
Did anyone got the answer. Please post it here. I am still not finding the solution
