### ISSUE TITLE
[react-native-router-flux v4.0.0-beta.27/npm module]PopTo method is not fixed

### ISSUE THREAD

**Issue by sharkrice** [aksonov/react-native-router-flux#2799]
### Version
react-native-router-flux v4.0.0-beta.27

### Actual behaviour
if stack has same scenes as your current scenes, popTo doesn't pop back 

[Fixed popTo method (again)](https://github.com/aksonov/react-native-router-flux/pull/2761)

However...
Left pic is react-native-router-flux npm module's source code
Right pic is source code on github

![???](https://i.imgur.com/XCKD8ll.png)

Their version numbers are both v4.0.0-beta.27, but codes are differences
![They are both v4.0.0-beta.27](https://i.imgur.com/KzYyiqj.png)

**Comment by Blapi** [comment]
```
rm -rf node_modules
yarn cache clean
yarn install
```

**Comment by sharkrice** [comment]
@Blapi I try that, didn't work,so I dowloaded the package,em...same
[https://registry.npmjs.org/react-native-router-flux/-/react-native-router-flux-4.0.0-beta.27.tgz](https://registry.npmjs.org/react-native-router-flux/-/react-native-router-flux-4.0.0-beta.27.tgz)

**Comment by Blapi** [comment]
@sharkrice, just upgraded from 0.24 to 0.27 and looks like you're right, I've got the same issue.

@aksonov, could you have a look on this please?

**Comment by aksonov** [comment]
@Blapi Published 0.28, could you check?

**Comment by Blapi** [comment]
@aksonov just upgraded and everything looks fine !

@sharkrice closing this as it's solved, upgrade your RNRF version properly to 0.28

**Comment by sharkrice** [comment]
@Blapi @aksonov 
another strange problem, i upgrade my RNRF to 0.28, but React Native throw an error

>  [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@10]
ExceptionsManager.js:73
TypeError: Cannot read property 'map' of undefined
ExceptionsManager.js:73
Cannot read property 'map' of undefined

 So I copied node_modules\react-native-router-flux outside and builded it, and then i copied new `dist` to node_modules\react-native-router-flux overwrite old `dist` folder, and then it fixed, react-native didn't throw error.

I cleared cache and deleted node_modules folder several times, it always happens.

My Computer OS is WIN 10.

**Comment by Blapi** [comment]
Yeah same for me, I downgraded to 0.24 because it is enough stable for me and I'm in a hurry but yep, I also have these issues as well as some `Illegal invocation` warnings.

The `TypeError: Cannot read property 'map' of undefined` appeared for me because of the `type='replace'` in my scenes

@aksonov I guess @sharkrice gave the good fix?

**Comment by esutton** [comment]
+1 Same issue on Android:
````
TypeError: undefined is not an object (evaluating 'resetAction.actions.map')

````
On attempt to switch to this scene:
````
            <Scene
              key={scene.Key.WaypointScreenParentAddNew}
              component={props => (
                <WaypointScreenParent {...props} {...this.props} />
                )}
              type="replace"
              hideNavBar={false}
              hideTabBar={false}
            />
````
Android:
		"react": "^16.2.0",
		"react-native": "^0.51.0",
		"react-native-router-flux": "^4.0.0-beta.28",

How far do I need to rollback?

**Comment by Blapi** [comment]
Yeah I'm now using .27 because .28 is broken with this. This one is stable, be careful to put
`"react-native-router-flux": "4.0.0-beta.27"` and not
`"react-native-router-flux": "^4.0.0-beta.27"`

**Comment by FacuAcosta** [comment]
Had the same bug on `4.0.0-beta.28` when using `Actions.replace('screen')`. Downgrading to `4.0.0-beta.27` fixed it but the last version is broken. @kesha-antonov

**Comment by aksonov** [comment]
Looks like we need to revert related commits...

**Comment by esutton** [comment]
@Blapi and @FacuAcosta Thank you. 

I also confirm 4.0.0-beta.27 does not crash on ````Actions.replace('screen')````
````
yarn remove react-native-router-flux
yarn add react-native-router-flux@4.0.0-beta.27
````

**Comment by mvanroon** [comment]
Beta 27 and 28 **are** crashing for me with the aforementioned error.
Beta 26 is working.

**Comment by afilp** [comment]
Note: I also use REDUX through connected components and works on 0.24 (but I cannot use "onExit" which I really need to use in order to clear a timer and this can be done only in 0.28.... but I cannot use this either).

**Comment by marcosmartinez7** [comment]
Same problem here with beta 28

im getting: 

> TypeError: undefined is not an object (evaluating 'resetAction.actions.map')


when doing this:

`                Actions[this.props.targetScene].call()
`
where targetScene is just the scene to redirect

Im using redux too, now i've just download the beta 26 version that has the react-navigation version fixed, could you please check at this too? https://github.com/aksonov/react-native-router-flux/issues/2865 

because if we need to go for the beta 24 version for using redux we need to use the fixed version of react-navigation, i mean:

    "react-navigation": "1.0.0-beta.22"

instead of

    "react-navigation": "^1.0.0-beta.19" (this willl result in 1.0.0 nowadays)

kind regards

**Comment by Ekhui** [comment]
in 0.27 the PopTo method is not fixed and then in 0.28 the replace breaks...

**Comment by kesha-antonov** [comment]
Hey guys! https://github.com/react-navigation/react-navigation/releases

react-navigation 1.0 was released. Maybe it has been fixed there!
Could you check it?

**Comment by marcosmartinez7** [comment]
i have tried RNRF beta 28 with react nativation 1.0 and i have this problem https://github.com/aksonov/react-native-router-flux/issues/2865

the thing is that RNRF from versions beta0 to beta24 uses ^1.0.0-beta.19 of react navigation and RNRF beta 28 uses react-navigation 1.0.0-beta.22, a fixed version ....

**Comment by joaosardinha** [comment]
Also getting:

TypeError: undefined is not an object (evaluating 'resetAction.actions.map')

With 24, 27 and 28.

**Comment by famadori** [comment]
Herar work only type: "replace" in beta 27

**Comment by chaipipatP** [comment]
Thanks guys
working on beta 27

**Comment by bachphuc** [comment]
Today, latest version 4.0.0-beta.28 is not working, Beta 27 is working. Anybody can look into it? with new newbie that's really challenge.

**Comment by aayushis12** [comment]
I am getting the same error on beta27. The scene is like this
```<Scene
                  key="myScreen"
                  component={screen}
                  initial
                />```
And I have a function for navigation like this  ```onPress={() => Actions.myScreen({ type: ActionConst.REPLACE })```
or when I am using it like this Actions.replace('myScreen') then also I get the same error.

**Comment by mkhuda** [comment]
The error occurs on beta 28, but beta 27 works fine.
`TypeError: Cannot read property 'map' of undefined`
