### ISSUE TITLE
Changeing Tab in Container

### ISSUE THREAD

**Issue by vanBrunneren** [aksonov/react-native-router-flux#28]
hi thank you for this awesome plugin
I have a container with two scenes in it. I want to change the scenes with a button in the first scene. When I press this button and execute Actions.scene2() the scene changes but the selected tab in the tabbar won't change.
Is there a method to do this?

**Comment by aksonov** [comment]
Please check demo, does it work well on your side?

**Comment by vanBrunneren** [comment]
I made a little demo
![screenvideo](https://cloud.githubusercontent.com/assets/11269836/10841402/575e0d02-7ee9-11e5-9c89-ca8a34a08026.gif)

When I press the button "Goto tab#2" the Scene switches but the tab in the tabbar doesn't change. Is there a way to do this? I only added a simple onPress to your demo.

```javascript
class TabView extends React.Component {

    onTouch(){
        Actions.tab2();
    }

    render(){
        return (
            <View style={styles.container}>
                <Text>Tab #{this.props.name}</Text>
                <TouchableHighlight onPress={this.onTouch}>
                    <Text>Goto tab#2</Text>
                </TouchableHighlight>
            </View>
        );
    }
}
```

**Comment by aksonov** [comment]
Oh,  I see now. Tthe problem that tabs is not connected with actions - it is not implemented - you should add listener to PageStore and change tab accordingly. 

Support of 'tabs' is rather experimental and doesn't work well - see #26, for example

**Comment by vanBrunneren** [comment]
thank you for your fast response I managed it with your advice and added a listener to the PageStore.
