### ISSUE TITLE
navigationBarStyle: backgroundColor not correct when the app is in the background on Android

### ISSUE THREAD

**Issue by Jun711** [aksonov/react-native-router-flux#2801]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?
using "react-native-router-flux": "^4.0.0-beta.27"

### Expected behaviour
expect the navbar when the app is in the background to have the color as when the app is running.

### Actual behaviour
navbar is grey color while the app is in the background mode. This happens when I press the home button and android phone shows a list of apps running in the background. navbar color is not correct but the app icon does show up.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Note the navbar color 
2. Press home button
3. Android device will show a list of apps running in the background
4. Note the navbar color of the app is different from the color when the app is running
Maybe I missed out some props?
```
<Scene
        navigationBarStyle={{backgroundColor: 'red'}}
        key='home'
        component={HomeContainer}
        title='Home'
/>
```

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
