### ISSUE TITLE
DRAW THE APP UNDER THE STATUS BAR

### ISSUE THREAD

**Issue by greenraze** [aksonov/react-native-router-flux#2803]
### Version
"react-native-router-flux": "4.0.0-beta.22",
"react-native": "0.50.1",

in ios 10   navbar starting from under the status bar but in ios 11  navbar starting from below the status bar .
i want to start nav bar from 0x 0y of screen  for all versions of ios.
like in android there is support like setTranslucent() but on ios i have not found support.

**Comment by aksonov** [comment]
Lack of details
