### ISSUE TITLE
undefined is not an object (evaluating 'resetAction.actions.map')

### ISSUE THREAD

**Issue by CrazzzyDev** [aksonov/react-native-router-flux#2808]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.?.? (v3 is not supported) 4.0.0-beta.22
- react-native v0.?.? ^0.47.2

### Expected behaviour

Push screen using "Actions.userprofile()" should push & replace the screen with profile screen.

### Actual behaviour

Getting error: undefined is not an object (evaluating 'resetAction.actions.map')

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.  Set scene like,
```
<Scene
                  key="userprofile"
                  component={Profile}
                  title="Profile"
                  back={true}
                  backButtonImage={Images.backArrow}
                  type={ActionConst.REPLACE}
                />
```
2. Try to push screen using Actions.userprofile()

**Comment by Blapi** [comment]
Duplicate #2799
