### ISSUE TITLE
Different navBars

### ISSUE THREAD

**Issue by BigPun86** [aksonov/react-native-router-flux#281]
Hey there! 

I am trying to style a navbar in a nested router/route. Here is the code: 

    ......
    <Route name="dashboard" type='reset'>
        <SideDrawer>
		<Router hideNavBar={false} sceneStyle={styles.routerScene} navigationBarStyle={styles.navBar} titleStyle={styles.navTitle}>
            <Route name='home' component={ Routes.Dashboard } title={translate('home')} renderTitle={renderTitle}/>
            <Route name="chatAndGroups" component={ Routes.ChatAndGroups } title={translate('myGroups')} renderTitle={renderTitle} renderLeftButton={renderBackButton}/>
								
    .....

I need to have a different navigationBarStyle for my Dashboard Component as for any other, in this example ChatAndGroups. I tried to overwrite navigationBarStyle for Dashboard Component, after that i thought to just simply hideNavBar on Dashboard and than make a custom one within the Component. But i couldn´t overwrite/toggle the hideNavBar prop as well!

I would appreciate any ideas how to solve this....

**Comment by aksonov** [comment]
Check demo for hideNavBar, Tab#2 has this property and navbar is hidden.
