### ISSUE TITLE
How can I save redux state in onExit static function?

### ISSUE THREAD

**Issue by chinavane** [aksonov/react-native-router-flux#2810]
Because static function can't get this reference,but i want to save data to redux state, what can i do?
 static onExit(){
       // what can i do anything?
 }

**Comment by themakerman** [comment]
@chinavane Can you explain the actual scenario you want? Do you want to save redux state so that when you reopen the app the data comes back again?

**Comment by chinavane** [comment]
When I switch the scene, I will trigger the onExit method. At this time, I want to store some data in redux store, for example, the rolling position of flatlist. But onExit is a static method, and the static method can't get the this object, so it's not good to operate this.state

**Comment by afilp** [comment]
I tried to use it with a "connected" component but onExit does not even trigger. Is this normal?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
