### ISSUE TITLE
TabBar displaying above navbar

### ISSUE THREAD

**Issue by eahema** [aksonov/react-native-router-flux#2811]
### Version
^4.0.0-beta.22
- react-native v0.?.0.49.3

### Expected behaviour
tabbar should display below to navbar

### Actual behaviour
![image](https://user-images.githubusercontent.com/4590907/35137632-aafbc2ac-fcea-11e7-95df-121c1ca5d062.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/4590907/35137787-6ba7fc1e-fceb-11e7-9306-847105c6c3a1.png)

**Comment by bas00445** [comment]
I have the same problem with you ... no solution for me yet

**Comment by kholiavko-roman** [comment]
Hey guys, did you found a solution for that ?

**Comment by eahema** [comment]
not yet, looking some help from group

**Comment by nikolas7892** [comment]
👍

**Comment by pgonzalez-santiago** [comment]
I have the same problem. Did you find something? 

I didn't see this post and I have created a new issue: https://github.com/aksonov/react-native-router-flux/issues/2913

**Comment by kholiavko-roman** [comment]
I use this module https://github.com/react-native-community/react-native-tab-view

**Comment by AndrejZdravev** [comment]
in the root Scene hideNavBar then in tabs hideNavBar={false} !!!

<Scene  key="root" hideNavBar >     
<Scene key="ResultslistScene">

                <Scene key="Results"
                    tabs={true}
                    hideNavBar={false}
                    headerMode='none'
                    wrap={false}
                    title="Results list"
                    lazy
                >
                    <Scene key="Resultslist" component={ResultslistScene} title="Results list" />
                    <Scene key="Favorites" component={InfoScene} title="Favorites" />
                </Scene>

            </Scene>
</Scene>

**Comment by AndrejZdravev** [comment]
<Scene  key="root" hideNavBar >
<Scene key="ResultslistScene">
                <Scene key="Results"
                    tabs={true}
                    hideNavBar={false}
                    headerMode='none'
                    wrap={false}
                    title="Results list"
                    lazy>
                    <Scene key="Resultslist" component={ResultslistScene} title="Results list" />
                    <Scene key="Favorites" component={InfoScene} title="Favorites" />
                </Scene></Scene></Scene>

**Comment by AndrejZdravev** [comment]
`<Scene  key="root" hideNavBar ><Scene key="ResultslistScene">
                <Scene key="Results"
                    tabs={true}
                    hideNavBar={false}
                    headerMode='none'
                    wrap={false}
                    title="Results list"
                    lazy
                >
                    <Scene key="Resultslist" component={ResultslistScene} title="Results list" />
                    <Scene key="Favorites" component={InfoScene} title="Favorites" />
                </Scene></Scene></Scene>`

**Comment by jingoldby** [comment]
why would anyone literally ever want the tabs above the nav....

**Comment by MaxInMoon** [comment]
After 1 day of struggle I found a way.
I’ll give you a functional link to help you (let me 3 days)

**Comment by jingoldby** [comment]
Oh it's fine I just ended up hiding the nav and putting the component in my custom tabs component..... just needed sleep when I posted my last comment 😆

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by edoantonioco** [comment]
hey, did someone found a way to fix this? 
For normal scenes you can use the navBar property and set the component which has to be on top, but a Drawer has no component, so I really need to know how to fix this.

**Comment by bbturtle** [comment]
same +1 with tabar position = "top"
