### ISSUE TITLE
Actions.refresh not working on hidden scene

### ISSUE THREAD

**Issue by riwu** [aksonov/react-native-router-flux#2812]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.24
- react-native v0.51

https://snack.expo.io/@riwu/router-flux-actions.refresh
1. Click NEXT
2. Click INCREMENT
3. Click back navigation

Expected: the first scene should have right text rendered (like the second scene after pressing INCREMENT).
Actual: `Actions.refresh` doesn't seem to have effect on inactive scene

**Comment by aksonov** [comment]
Duplicate of #2309
