### ISSUE TITLE
Stack behaving same as Scene

### ISSUE THREAD

**Issue by riwu** [aksonov/react-native-router-flux#2813]
### Version
Tell us which versions you are using: 

-react-native-router-flux ^4.0.0-beta.24
-react-native v0.51

https://snack.expo.io/rkiHn5yBM
If I replace `Stack` by `Scene`, the result appears to be identical.
Under what circumstances would`Stack` differ from `Scene`?

**Comment by aksonov** [comment]
It is the same ;) It is just syntax sugar for better readability.
