### ISSUE TITLE
onEnter to make Api call and update screen

### ISSUE THREAD

**Issue by Albin-CR** [aksonov/react-native-router-flux#2815]
### Version
Tell us which versions you are using: 

    "react-native-router-flux": "^4.0.0-beta.27",
    "react-native": "0.50.3",

### Expected behaviour

Is there any way to use  onEnter to make Api call and update screen

### Actual behaviour

only able to get global values in onEnter not able to call apis using redux

**Comment by afilp** [comment]
We need to have better support for Redux, if possible. Thanks!

**Comment by aksonov** [comment]
Please check Example project and its 'reducer' param for redux integration
