### ISSUE TITLE
Strange behavior in back button and drawer after focus and unfocus the textinput in Example App

### ISSUE THREAD

**Issue by HessiPard** [aksonov/react-native-router-flux#2817]
### Version
Tell us which versions you are using: 

Test has been Done in Example app.

### Expected behaviour
After tapping android back button app must goes to tabbar page with drawer open.

### Actual behaviour
After tapping android back button app goes to new tabbar page with drawer close, again if you tap android back button you will go to register page again.

### Steps to reproduce

1. Clone and run-android example App
2. Add new Component `<TextInput></TextInput>` in TabView.js render function.
3. Add another Button in DrawerContent.js for navigate to register page from drawer`<Button onPress={Actions.register}>go to register</Button>`
4. now reload app and GO TO TABBAR PAGE
5. focus and unfocus/blur the TextInput (in my case i dont type anything)
6. open drawer and go to register page
7. Tap on hardware back button in android ( not the one that is provided in the register page)
8. app goes to new Tabbar page with drawer closed, then if you tap back again you will go to register page again.
9. Tap on android back button and you will go to tabbar page AGAIN!!!!

**Comment by barghi** [comment]
+ 1
same issue here
behavior of android back button is strange
but default back button works fine

**Comment by HessiPard** [comment]
I fixed the issue just by calling `Actions.drawerClose()` before `Actions.register`!
