### ISSUE TITLE
Setting Tab icon

### ISSUE THREAD

**Issue by lishine** [aksonov/react-native-router-flux#2819]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour

Emitting refresh action with title: xxx, should change the props.title of TabIcon

### Actual behaviour

The title stays same as the that initialized.
So actually I cannot change tab title on the dynamically. On the navbar title changes, if not hidden
Even using repository example. 

I would love to hear a way to change tab title.
Thanks! It is a great library.

**Comment by snrn-Pontus** [comment]
Did you find a way around this? I am having the same issue when my tabs are lazyloaded.

**Comment by lishine** [comment]
Nop. Using directly react navigation

**Comment by aksonov** [comment]
Not supported, sorry
