### ISSUE TITLE
Hall of Fame on front page for Apps using RNRF in Production

### ISSUE THREAD

**Issue by themakerman** [aksonov/react-native-router-flux#2820]
Hey Guys, I was wondering if we can show some apps in production using RNRF so that people can start getting more comfortable and develop early trust in the library. Similar how facebook has showcased apps using React Native in production we can do Apps using RNRF in production.

**Comment by Blapi** [comment]
I love this idea

**Comment by themakerman** [comment]
@aksonov what do you think? This will encourage developers fearful of RN.

**Comment by themakerman** [comment]
@aksonov OKay i'll add new section named hall of fame in docs. Will submit PR as i get free.

**Comment by daviscabral** [comment]
@aksonov you are a machine today 🤣
