### ISSUE TITLE
How to use indicator ("loading") with RNRF v4

### ISSUE THREAD

**Issue by sfrribeiro** [aksonov/react-native-router-flux#2821]
### Version
"react-native-router-flux": "^4.0.0-beta.25
"react-native": "0.44.2",
"redux": "^3.6.0",

### Expected behaviour
What do you use as a processing indicator (famous "loading") in the RNRF v4?

### Actual behaviour
When I use react-native ActivityIndicator inside the Scene tag component, the indicator loading only covers the component itself, leaving out the navbar and tabbar.

**Comment by mechabyte** [comment]
Have you checked out the [modal](https://github.com/aksonov/react-native-router-flux/tree/master/Example/components/modal) component in the project's [Example app](https://github.com/aksonov/react-native-router-flux/tree/master/Example)? Accomplished something similar with an alert popup for a work task. The example covers a lot of different possibilities if you comb through it.

**Comment by sfrribeiro** [comment]
Show @mechabyte.

I'll test in the Example App and give a return.

thank you

**Comment by sfrribeiro** [comment]
I used Lightbox with ActivityIndicator and it worked perfectly.
