### ISSUE TITLE
Replace related issue in React-Native

### ISSUE THREAD

**Issue by shyam1211** [aksonov/react-native-router-flux#2823]
project working ways :
             Splash Screen -> Login Screen -> Signup Screen.
      i working on navigate screens using router-flux .Like..
           //code here
           <Router>
                <Stack key="root" hideNavBar={true}>
                    <Scene key="splash" component={Splash} title="Splash" initial={true}/>
                    <Scene key="login" component={Login} title="Login"/>
                    <Scene key="signup" component={Signup} title="Register"/>
                </Stack>
            </Router>
Already i hide the navigation back button .
but i want , when the hardware backbutton pressed in login screen it not going to splash screen.its should close the app.
i used  type="replace" but its not working.Like
 <Scene key="login" component={Login} title="Login" type="replace"/>
 
So please resolve  these issue .

**Comment by Blapi** [comment]
Use the listener on BackHandler (imported from react-native)

```

    this.loginBackPressHandler = BackHandler.addEventListener('loginBackPress', () => {
      if (yourConditionToNotExitTheApp) {
        return true
      }
      return false
    })
```

Add this in your `componentDidMount` for example
