### ISSUE TITLE
How to create a structure with Drawer, Tabbar

### ISSUE THREAD

**Issue by munkhorgil** [aksonov/react-native-router-flux#2828]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 (v3 is not supported)
- react-native v0.51

### Expected behaviour
Create a structure with drawer, tabbar. When I wrap all my scenes and tab, It can't stack scenes.
Tab1 is initial and goes to A -> B -> C, If I pop in B it supposed to go back A, in C -> B.
### Actual behaviour
In every scene when I pop it goes back to tab1 which is initial.

Code as follows
```
<Router>
    <Scene key="root">
        <Scene key="signIn" initial={!this.state.signedIn>
        <Drawer initial={this.state.signedIn}>
            <Scene tabs={true}>
                <Scene key="tab1">
                    <Scene key="foo"/>
                </Scene>
                <Scene key="tab2">
                    <Scene key="bar"/>
                </Scene>
            </Scene>
            <Scene key="A" />
            <Scene key="B" />
            <Scene key="C" />
        </Drawer>
    </Scene/>
</Router>
```

**Comment by aksonov** [comment]
Check Example project
