### ISSUE TITLE
Need to handle renderRightButton

### ISSUE THREAD

**Issue by ankitbisht143** [aksonov/react-native-router-flux#2829]
### Version
 - react-native-router-flux v4.0.0-beta.28
- react-native v0.52.0

How to handle renderRightButton(or any callback) from any class.
I have defined my scenes in my app.js file. 
The right button is properly rendering on the right side of navigation but I want to handle this callback from other class(not from app.js).

This is my app.js file where all my scenes are defined. 
![screen shot 2018-01-24 at 11 07 43 pm](https://user-images.githubusercontent.com/13850433/35347631-b39b03c6-015b-11e8-8a07-aecf049fab7f.png)

**Comment by aksonov** [comment]
Check Example project for more details
