### ISSUE TITLE
Changing background colour that appears during animation

### ISSUE THREAD

**Issue by DVassilev** [aksonov/react-native-router-flux#283]
When you slide 'back' to return to the previous route there is a white background behind the screen as it gets bigger to fill the screen. This clashes with my UI, is there a way to change the colour or somehow make it match the background colour of the app?

**Comment by aksonov** [comment]
Check 3.0 release, now the component uses new React Native Navigation API. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.

**Comment by julesmoretti** [comment]
@aksonov - Would love to know how to implement this also. I am working on a dark themed UI and the transitions from scene to scene fades to a white background which is not desirable.

I have tried the following on the Router component but with no success on the transitions:

```
getSceneStyle={getSceneStyle}
```

I am testing it out on Android and have:

```
    "react": "15.4.2",
    "react-native": "^0.41.2",
    "react-native-router-flux": "^3.37.0",
```

Thank you.

**Comment by tomexa** [comment]
You did not provide any solutions, I'm also building a dark themed app and this clashes a lot.
I'm currently using V3 from the Ignite + Native base boilerplate, but let's assume I can upgrade to V4 without breaking too much stiff, how would I set a dark/black background in V4 during screen transitions?

**Comment by aksonov** [comment]
Unfortunately V3 animations were sluggish and buggy, that is why I wrote V4 based on react-navigation. Looks like react-navigation allows black/dark background - use `<Router cardStyle={{backgroundColor:'black'}}>...</Router>` and `navigationBarStyle` to set proper navbar style.

**Comment by tomexa** [comment]
Thanks! I'll try that and tell you the outcome.
