### ISSUE TITLE
Its possible create new route inside a component?

### ISSUE THREAD

**Issue by userinova** [aksonov/react-native-router-flux#2832]
class App extends Component {
  render() {
    return (
      <View style={style.backgroundGParent}>
       
          <Router  >
          
            <Stack key="root" >

                <Scene key="Client_app" component={Client_app}  title="Selecionar uma opção" hideNavBar  />
            
                  <Scene key="Init_Wherego" component={Init_Wherego}  title="Init_Wherego"  hideNavBar />
                  <Scene key="getLocation" component={getLocation}  title="Selecionar um Endereço"   />
                  <Scene key="Login_options" component={Login_options}  title="Login_options"  hideNavBar />                    
                  <Scene key="Splash_Screen" component={Splash_Screen}  title="Splash_Screen" hideNavBar /> 

            </Stack>
          </Router> 

           
      </View>
      );
  }
}

_________________________________ and inside a Client_app

class Client_app extends Component {
  render() {
    return (
      <View style={style.backgroundGParent}>
       <Text>title</Text>

<TouchableOpacity -> tab1
<TouchableOpacity -> tab2
<TouchableOpacity -> tab3

          <Router  > 
            <Stack key="root" >

                <Scene key="tab1" 
                <Scene key="tab2" 
                <Scene key="tab3" 
            

            </Stack>
          </Router> 

           
      </View>

I need create tabs with route inside the route parent

**Comment by Blapi** [comment]
This is not the library works. You should just add these other Scenes in your first Router and adapt your logic.
