### ISSUE TITLE
navTransparent does't work well on android

### ISSUE THREAD

**Issue by UrielShimony** [aksonov/react-native-router-flux#2834]
### Version
 "react-native-router-flux": "^4.0.0-beta.28"
    "react-native": "0.52.1",

### Expected behaviour
like in ios,  completely transparent
![image](https://user-images.githubusercontent.com/20382785/35441454-3948bed6-02ac-11e8-83e8-471982f6720b.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/20382785/35440925-354a9400-02aa-11e8-8b29-8b3cbc53f464.png)

**i have a very very thin white line in the bottom of the nav bar, looking like 3D/zIndex upper layer**
 
<Stack key='root'>
                    <Scene key='Home' component={HomeComponent} hideNavBar/>
                    <Drawer key='DrawerRoot' contentComponent={SideMenu} drawerWidth={200}
                            drawerImage={MenuIcon} drawerPosition='left' hideNavBar>

                        **<Scene key='scene1' component={component1}
                               drawer={true}
                               navTransparent={true}
                        />**

                        <Scene key='creators' component={creatorScreen} title={'Creators'} back/>
                    </Drawer>
                </Stack>

Thanks for the helpers

**Comment by ljmkimqx** [comment]
+1

**Comment by ljmkimqx** [comment]
I resolved it. Don't use navTransparent. use

navigationBarStyle={{
                  position: 'absolute',
                  backgroundColor: 'transparent',
                  zIndex: 100,
                  top: 0,
                  left: 0,
                  right: 0,
                  borderBottomWidth: 0,
                  elevation: 0,
              }}

like this:
<Scene
     key='scene1' 
    component={component1}
    navigationBarStyle={{
                  position: 'absolute',
                  backgroundColor: 'transparent',
                  zIndex: 100,
                  top: 0,
                  left: 0,
                  right: 0,
                  borderBottomWidth: 0,
                  elevation: 0,
              }}              
 />

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
