### ISSUE TITLE
iPhone X: Remove the internal shadow of react-native-stack-navigator when using safearea

### ISSUE THREAD

**Issue by afilp** [aksonov/react-native-router-flux#2836]
I have the same problem as here:
https://stackoverflow.com/questions/48361898/how-to-remove-internal-shadow-of-react-native-stacknavigator-when-using-safearea

I am not sure if we can use the ``cardStyle`` fix with ``react-native-router-flux``.

### Version
Tell us which versions you are using: 
    "react-native-router-flux": "^4.0.0-beta.27",
    "react-native": "0.52.0",

### Expected behaviour
No shadow on blank statusbar

### Actual behaviour
It shows a shadow
![image](https://user-images.githubusercontent.com/7850073/35472831-3f21d472-037f-11e8-9d2b-ce567f113522.png)

````
 <Scene
                        key="Main"
                        component={Main}
                        initial
                        hideNavBar
                        panHandlers={null}
                    />
````

**Comment by timqha** [comment]
Try this:
```
<Router
        getSceneStyle={
           { elevation: 0,
              shadowOpacity: 0,
              borderBottomWidth: 0}
}   >
```

**Comment by VasiliyPolyakov** [comment]
@timqha Thank you. It is awesome. It helped me and I fixed this problem related to internal shadow.

**Comment by daviscabral** [comment]
Closing this issue as it seems the fix provided by @timqha has worked for everyone.
