### ISSUE TITLE
Actions.replace('Scene') does not work.

### ISSUE THREAD

**Issue by davychhouk405** [aksonov/react-native-router-flux#2837]
**Problem**
On click to navigate to new scene, whenever I use the `Actions.replace('SceneName')`, the action is not working and the error log is `Cannot read property of 'map' of undefined` in _**StackRouter.js**_ of React Navigation.

**My Quick Solution**
For quick fix, I used `Actions.pop(); Actions.push('SceneName')`. And this works for me.
I just wonder why it does not work when I use the `Actions.replace('SceneName')`.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28 (v3 is not supported)
- react-native v0.52.0

### Expected behaviour
Reload the scene with a new scene.

### Actual behaviour
![simulator screen shot - iphone 6 - 2018-01-29 at 16 59 52](https://user-images.githubusercontent.com/13924709/35504764-847db9bc-0516-11e8-8020-55eaba8bf6f0.png)

**Comment by Blapi** [comment]
Duplicate, downgrade to .27
