### ISSUE TITLE
Actions.pop() not working.

### ISSUE THREAD

**Issue by blackstar217** [aksonov/react-native-router-flux#2839]
Actions.pop() not working for me.
![screen shot 2018-01-30 at 4 51 05 am](https://user-images.githubusercontent.com/30436669/35533681-3d46fb9a-0579-11e8-8e62-43f1005744e9.png)
in screen, I called Actions.pop() to go to prev screen.
but there is nothing.

**Comment by Blapi** [comment]
First, did you really have a look on the Example project??? Because `Actions.pop()` is very popular and is known to work.. So I'm really convinced you haven't checked how to use it.

Second, would you mind showing more of your code please in case of the Example project is not clear enough for you to understand `Actions.pop()`

**Comment by blackstar217** [comment]
export default class HeaderComponent extends Component {
  constructor(props) {
    super(props);
  }

  navigate() {
    NavigationActions.refresh({
      key: 'drawer',
      open: true
    })
  }

  goBack = () => {
    NavigationActions.pop()
  }

  render() {
    return (
      <Header style={styles.header} noShadow={true}>
        <Left>
          <Image source={Images.logo} />
        </Left>
        <Right>
          <Button transparent onPress={() => this.goBack()}>
            <Icon active name="ios-arrow-back" size={25} color="#ffffff" />
          </Button>
          <Button transparent onPress={() => this.navigate()}>
            <Icon active name="ios-menu" size={30} color="#ffffff" />
          </Button>
        </Right>
      </Header>
    );
  }
}

**Comment by blackstar217** [comment]
Here is my code snippet
![screen shot 2018-01-30 at 4 54 10 am](https://user-images.githubusercontent.com/30436669/35533822-a2df714e-0579-11e8-8a84-df28b59ee699.png)

**Comment by Blapi** [comment]
You are not even using `Actions.pop()` and still, you open an issue about it ?!

**Comment by blackstar217** [comment]
in the above code, the NavigationActions.pop() = Actions.pop()
I can use the other functions, just can't use the pop()

**Comment by Blapi** [comment]
Maybe because all your scenes are in `type='replace'` so there is nothing to go back to in your NavigationStack?

Check the doc and the Example project before opening an issue please.

**Comment by blackstar217** [comment]
Oh, sorry, It my mistakes.

**Comment by Pradeep119** [comment]
somewhere you used Actions.replace then you can you `Actions.replace('SceneName')` with the replace
