### ISSUE TITLE
Can't navigate to new Scene

### ISSUE THREAD

**Issue by schlaegerz** [aksonov/react-native-router-flux#2840]
### Version
Tell us which versions you are using: 

 "react-native-router-flux": "^4.0.0-beta.27",
 "react-native": "^0.52.2",

### Expected behaviour

Be able to navigate between two scenes with Actions.Loading2()

### Actual behaviour
 
If I add a reducer can see if the reducer is called, but nothing happens

### Steps to reproduce

Here is my whole app:
```

import React, { Component }  from 'react';

import {
  Scene,
  Router,
  Stack,
  Reducer,

} from 'react-native-router-flux';

import {Text} from 'react-native'

import {
    Actions,
    
  } from 'react-native-router-flux';
class Loading extends Component{
    render(){
      return (
        <Text
          onPress={Actions.Loading2}>LOADING</Text>
      );
    }
  }
  
  class Loading2 extends Component{
    render(){
      return (
        <Text
          onPress={Actions.Loading2}>LOADING2</Text>
      );
    }
  }

const reducerCreate = params => {
  const defaultReducer = new Reducer(params);
  return (state, action) => {
    console.warn('ACTION:', action);
    return defaultReducer(state, action);
  };
};



 class App extends Component{
  
  render()
  {
    return (
      <Router
      createReducer={reducerCreate}>
  
      <Stack
          key="root">
          <Scene key="Loading" component={Loading} title="Loading" />
          <Scene key="Loading2" component={Loading2} title="Loading2" />
        
      </Stack>
          
  
    </Router>
    )
  }
}


export default App
```

I would expect clicking on the text to switch the scene, but nothing ever happens. I have tried every iteration of Actions.Loading, Actions["Loading"], etc that I can think of and nothing seems to work

I have also switched out the Stack with a Scene, with no effect.

I feel like I must be missing something super basic, but I cannot figure this out.

**Comment by schlaegerz** [comment]
Really confused by this, I was playing around with my installed packages and then it just started to work, there must be some weird caching that prevented it from working, I had been trying this on and off for months and never got it to work until now.

**Comment by Blapi** [comment]
Have a look at the Example project next time, it will be very helpful in your case !

**Comment by schlaegerz** [comment]
I was basing it off the example. There does appear to be a weird caching thing that prevented it from working. I don't understand why.

**Comment by schlaegerz** [comment]
So it was working for me, then after I was messing with packages again and trying to get a production build of my app, it completely stopped working again.

My code didn't change at all, I only updated some unrelated packages.

**Comment by Blapi** [comment]
Be careful with your packages that you clean the cache before reinstalling them, you might have some troubles.
Anyway, what is your situation? The Example project is the true example of what you should follow to use this library, especially to just change scenes..

**Comment by schlaegerz** [comment]
Yeah I was using the Example project, the issue is entirely a caching issue which is very weird. It has happened to me multiple times, and is probably happening to other people. What commands would you suggest to clear the cache?

**Comment by Blapi** [comment]
```
rm -rf node_modules
rm yarn.lock
yarn cache clean
yarn install
```

If you're on Android : `cd android && ./gradlew clean`

Then run on your device
