### ISSUE TITLE
How to  disappears instantly narTab when user taps on TextInput box 

### ISSUE THREAD

**Issue by hoangph91** [aksonov/react-native-router-flux#2841]
![red](https://user-images.githubusercontent.com/20775146/35547786-d99f341a-05ad-11e8-99ed-451ef161dcdb.png)

### Version
Tell us which versions you are using: 
 
- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by mechabyte** [comment]
I would try refreshing the current [navigation scene's state](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#scene) through `Actions.refresh()`. You could wire it up to a text input like so:
```

<TextInput
  onFocus={() => Actions.refresh({ hideTabBar: true })}
  onEndEditing=>{() => Actions.refresh({ hideTabBar: false })}
  value={this.state._etc_}
/>
```

RN TextInput docs: [onFocus](https://facebook.github.io/react-native/docs/textinput.html#onfocus), [onEndEditing](https://facebook.github.io/react-native/docs/textinput.html#onendediting)

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
