### ISSUE TITLE
How to increase Gesture Response Distance of Drawer in v4

### ISSUE THREAD

**Issue by tikkichan4** [aksonov/react-native-router-flux#2844]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 (v3 is not supported)
- react-native v0.52

### Expected behaviour
N/A

### Actual behaviour
For increasing swipe back gesture response distance, we can do it by adding
```
          <Stack key="root" gesturesEnabled gestureResponseDistance={{horizontal: viewportWidth}}>
            <Scene key="splash" component={SplashScreen} />
          </Stack>
```
But now, i want to increase swipe open drawer gesture response distance, the gestureResponseDistance is not worked. And the documentation is not mentioned.
```
            <Scene key="drawer" gesturesEnabled gestureResponseDistance={{horizontal: viewportWidth}} hideDrawerButton drawer drawerWidth={200} drawerPosition="right" contentComponent={TopicDetailsSideMenu}>
              <Scene key="topicDetails" hideNavBar component={TopicDetailsScreen} />
            </Scene>
```
Is there any workaround here ? Thanks a lot.

### Steps to reproduce
N/A

**Comment by aksonov** [comment]
You really should check react navigation docs about this - RNRF just passes params to Drawer from react navigation
