### ISSUE TITLE
onEnter call action

### ISSUE THREAD

**Issue by sfrribeiro** [aksonov/react-native-router-flux#2847]
### Version
"react-native-router-flux": "^4.0.0-beta.28",
"react-native": "0.44.2",
"redux": "^3.6.0",

### Expected behaviour
How can I access a redux action (mapped in the scene via mapDispatchToProps) through the onEnter method?

### Actual behaviour
I'm having trouble accessing a redux action through the onEnter method within the scene. I think it's because of the onEnter method being static.

### Steps to reproduce
<pre>
class MyContainer extends Component {
  static onEnter() {
    setIsLoggedIn();
  }
  
  ...
  ...
  ...
  ...
  
  const mapDispatchToProps = dispatch => (
  {
    setIsLoggedIn: () => {
      dispatch(setIsLoggedIn());
    },
  }
);

export default connect(null, mapDispatchToProps)(MyContainer);
</pre>

**Comment by afilp** [comment]
Hi! Is there any solution to this?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
