### ISSUE TITLE
How to kill an activity by pressing any button in React-Native using Router-Flux????

### ISSUE THREAD

**Issue by shyam1211** [aksonov/react-native-router-flux#2849]
For Example:->
Flow Direction
Splash -> Home
I want ,when the backbutton pressed is not going to home -> spalsh but its should closed the app
and i already use  Actions.onExit(); but its not working.

please resolve these issue

**Comment by Blapi** [comment]
Use the BackButton listener or just a listener, there's already closed issues about it, have a look please.

**Comment by shyam1211** [comment]
Hi Blapi 
Thanks for your reply It is working for android.But in ios there are no back button ,there are some issue with sliding view.
so can i resolved it?

**Comment by Blapi** [comment]
I don't understand your point here.. You were talking about a back button to kill your app so it's Android.

Now you're talking about exiting your app when you're on your Home page and on iOS right ? I'm not sure about the iOS experience here, but why would you kill the app if this is on iOS? What does your Home page look like ?

And what's the issue with sliding view you're talking about ?
