### ISSUE TITLE
Title after pop with (custom title)

### ISSUE THREAD

**Issue by farwayer** [aksonov/react-native-router-flux#285]
How can I get title of route in reducer of AFTER_POP?
`action.title` and `action.route.title` is empty. Look like custom title saved only in `ExRouteAdapter` and we can't get access to it.

**Comment by aksonov** [comment]
Check 3.0 release, now the component uses new React Native Navigation API. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
