### ISSUE TITLE
Keep the data in a component loaded?

### ISSUE THREAD

**Issue by jsrbn** [aksonov/react-native-router-flux#2852]
- react-native-router-flux v4.0.0-beta.28 
- react-native v0.50.4

**Hi there,**
is it possible to keep the data in a component loaded when you navigate to another component and then back? When I e.g. set a `Text` to 0 by default and then change the 0 to 1, the number is 0 again when I navigate to another component and back.

**Comment by piubellofelipe** [comment]
@jsrbn I truly recommend using an state management tool like redux for this, will easy things a lot for you
