### ISSUE TITLE
iOS landscape tabbar bug

### ISSUE THREAD

**Issue by arnsa** [aksonov/react-native-router-flux#2858]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28" (v3 is not supported)
- react-native v0.49.3

### Expected behaviour

When I rotate iOS device from Portrait to Landscape mode, I expect tabbar to visually look normal, like on Portrait mode.

### Actual behaviour

When iOS device is rotated from Portrait to Landscape, tabbar is "pushed down" and half of it cannot be seen. No styles are applied to Tabs component or any other components of this library.

### Steps to reproduce

Run the example from Example folder. If you rotate iOS device to Landscape mode, you'll see that tabbar becomes smaller for some reason. It works okay on Android.

**Comment by arnsa** [comment]
Okay, I've fixed it myself by adding height to style prop and paddingBottom to tabStyle prop on Tabs component.

**Comment by rooque** [comment]
@arnsa I'm having the same issue, can you provide the code you used to fix it ? Thank you. Also, you can reopen the issue, this can affect more people and it's not a normal behavior.
