### ISSUE TITLE
Problem about pop and refresh

### ISSUE THREAD

**Issue by vnext-tungns** [aksonov/react-native-router-flux#2860]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 (v3 is not supported)
- react-native v0.52.?

### Expected behaviour
I have the situation like that. I'm in scene A and push to scene B. I want to change something in scene B and pop to scene A and scene A should be update some data (not all). I used:

Actions.pop({ refresh: { coordinates: coordinate } });

+It works well with instances where the data entered is different, but nothing changes when the same input data.

### Actual behaviour
When app pass data from scene A to scene B with same data in two time, only firsttime, scene A receive data.
componentWillReceiveProps(){
        console.warn('1');
    }
I debug in function componentWillReceiveProps, only first time it works, in other times, componentWillReceiveProps is not call.
When i research source code, I found this function:
@action setState = async (newState) => {...} 
in file    react-native-router-flux/src/navigationStore.js
             react-native-router-flux/dist/navigationStore
, it check status of data and prevent data receiver.
How can i fix this.

Thank you!

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
