### ISSUE TITLE
Pages before the page "push" need not be drawn

### ISSUE THREAD

**Issue by iwangx** [aksonov/react-native-router-flux#2863]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour

Push three pages like `Navigator` and then look at the layout on the Xcode

![image](https://user-images.githubusercontent.com/11516318/35915013-52e47400-0c40-11e8-93dd-e3973c64a040.png)

I think the page before the current page should not be drawn out, so it will consume unnecessary memory, I hope to improve, thank you.

### Actual behaviour

After using `react-native-router-flux` to push three pages, look at the layout on the Xcode

![image](https://user-images.githubusercontent.com/11516318/35915204-ee6e538c-0c40-11e8-89d8-d6bd3d92d640.png)

This will cause an increase in memory, which may cause app to crash.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
