### ISSUE TITLE
[Feature request] iOS 11 Style Navbar Titles

### ISSUE THREAD

**Issue by iampmat** [aksonov/react-native-router-flux#2866]
It would be great to support this large title format natively since it seems to be the new UI standard for iOS.

![image](https://user-images.githubusercontent.com/6267264/35940697-fed5572a-0c1d-11e8-96fb-30a1b32c0f30.png)

**Comment by aksonov** [comment]
Please raise this issue within react-navigation github, because RNRF is wrapper around react-navigation

**Comment by rudyryk** [comment]
https://github.com/react-navigation/react-navigation/issues/2749

**Comment by aksonov** [comment]
@rudyryk Yes, react-navigation doesn't provide it yet.. PR are welcome, we can do any header we want with RNRF!

**Comment by aksonov** [comment]
https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

Closing it because no RNRF changes are needed to implement custom nav bars

**Comment by AliUZAR** [comment]
@aksonov please check this; https://github.com/react-navigation/react-navigation/issues/2749#issuecomment-573191521
It seems added to react navigation with this prop; 
https://reactnavigation.org/docs/en/next/native-stack-navigator.html#headerlargetitle
How we can use it in RNRF ?
