### ISSUE TITLE
Multiple iOS URL types cause deep link parse to be crashed

### ISSUE THREAD

**Issue by EvianZhow** [aksonov/react-native-router-flux#2867]
Duplicated for https://github.com/aksonov/react-native-router-flux/issues/2787

Check this line: https://github.com/aksonov/react-native-router-flux/blob/0d528d81ebd1faf5be2c46b60abef957489d08f3/src/Router.js#L41

`"somePaymentMethod://callbackData".split("myApp://")[1]` definitely return `undefined`, then passing to `pathParser`.

Crashed here: https://github.com/aksonov/react-native-router-flux/blob/0d528d81ebd1faf5be2c46b60abef957489d08f3/src/pathParser.js#L70

**Comment by EvianZhow** [comment]
Naive fix here: https://github.com/EvianZhow/react-native-router-flux/tree/fix-multi-url-types

**Comment by m-vdb** [comment]
Experiencing this as well. Having multiple URI schemes is not uncommon at all... @aksonov can you cherry-pick this commit https://github.com/EvianZhow/react-native-router-flux/commit/685d0151fbbe811d9a64adc5dc9e886755332e0a in your repo? I guess you would want tests for that as well?

**Comment by aksonov** [comment]
@EvianZhow Could you submit PR?

**Comment by EvianZhow** [comment]
@m-vdb @aksonov https://github.com/aksonov/react-native-router-flux/pull/3009
