### ISSUE TITLE
Back button resizing

### ISSUE THREAD

**Issue by rohitgoyal** [aksonov/react-native-router-flux#2869]
### Version
Tell us which versions you are using: 
-react-native-router-flux": "4.0.0-beta.24
-react-native": "0.51.0

### Expected behaviour
backButtonTextStyle should change the size of the back button text.

### Actual behaviour
The text size of the back button remains the same

### Steps to reproduce
Below code should be able to make the back button size to 30 but it doesn't.
```
<Scene key="root" headerMode={'screen'} backTitle=" "
        navBarButtonColor='white'
        titleStyle={{fontSize:20*global.constants.FONT_SCALE}}
        backButtonTextStyle={{fontSize:30}}
      >
```

**Comment by tmaly1980** [comment]
It looks like you're telling it to not show any text with backTitle=" " . Are you expecting the back arrow to resize?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
