### ISSUE TITLE
I need to display image (loader) on button click in React-Native

### ISSUE THREAD

**Issue by shyam1211** [aksonov/react-native-router-flux#2870]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by Blapi** [comment]
Not related to RNRF.
Read the react-native docs or use Stackoverflow.
