### ISSUE TITLE
setParams in Tabs doesn't work

### ISSUE THREAD

**Issue by panhs** [aksonov/react-native-router-flux#2871]
setParams in Tabs doesn't work ,but the first seccen in tabs work,
### Version 
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour
 setParams ok

**Comment by Blapi** [comment]
Could you elaborate please?

**Comment by Blapi** [comment]
@panhs what's there status there?
