### ISSUE TITLE
getTitle stills retrun a title 

### ISSUE THREAD

**Issue by OdaiTu** [aksonov/react-native-router-flux#2872]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported) yes 4.0.0-beta.28
- react-native v0.?.? 0.50.3

### Expected behaviour

i expect to hide the title from my screen when navigate to it

### Actual behaviour

the title still shows

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.
![image](https://user-images.githubusercontent.com/12837840/36063258-0206f180-0e83-11e8-9112-f4bd0de47483.png)

**Comment by Blapi** [comment]
Use the `title` or `renderTitle` property.

**Comment by mklb** [comment]
This issue still exists in 4.3.1.

Setting the `title` prop to null or an empty string does not work. The fallback title that is used seems to be set from the `key` prop.

However setting `renderTitle={null}` works.
