### ISSUE TITLE
Android hardware back button unexpected behavior while using drawer when app coming to foreground from background.

### ISSUE THREAD

**Issue by rohitgoyal** [aksonov/react-native-router-flux#2873]
### Version
- react-native-router-flux 4.0.0-beta.27
- react-native 0.51.0

### Expected behaviour
Let's say i have screen_1 button on drawer and by clicking it I am going to screen_1. Now press the home button(App goes to background) and open the app again(App comes to foreground). Now when i press the android back button the app should go back to drawer screen (drawer in open state) and again pressing the back button should close the drawer.

### Actual behaviour
I have screen_1 button on drawer and by clicking it I am going to screen_1. Now press the home button(App goes to background) and open the app again(App comes to foreground). Now when i press the android back button the app goes back to home screen (drawer in close state) and again pressing the back button open the screen_1 screen.

### Steps to reproduce

```
render(){
  return <Router>
      <Scene key="root" headerMode={'screen'}
      >
        <Scene key="drawer" drawer
          contentComponent={SideMenu}
          drawerOpenRoute= 'DrawerOpen'
          drawerCloseRoute= 'DrawerClose'
          drawerToggleRoute= 'DrawerToggle'
          initial={true}
          hideNavBar={true}
          // drawerWidth={400}
        >
          <Scene key="home" component={Home}/>
        </Scene>
        <Scene key="screen_1" component={Screen_1}  />
    </Scene>
  </Router>
}

```

Just have these routes. Have anything in Home, Screen_1 and SideMenu.

**Comment by rohitgoyal** [comment]
@aksonov Have any idea about this?

**Comment by Gluhovroma** [comment]
having same

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

If it is still actual, please ask @daviscabral because he works with Android

**Comment by andidev** [comment]
@daviscabral @aksonov 
Could you reopen this? This is still there in latest release 4.0.6. I have been having this bug a long time know not able to figure out what was triggering it.

I also found out another situation when this bug occurs. 
1) Open app
2) Click on a InputText that the keyboard displays
3) Open drawer
4) Open new scene from drawer
5) Close scene with hardware back button
  (note that this closes both the scene and the drawer, though the scene component never get unmounted, i.e. componentWillUnmount is never called)
6) Open the drawer again
7) Try to open a scene from the drawer and it is now not possible

This may be related to 
https://github.com/facebook/react-native/issues/21316

I would love to assist further. I could create an example project If needed or test a fix.

**Comment by andidev** [comment]
Okey I just migrated a part of my code to React Navigation and it looks like this issue is there as well (in both rohitgoyal case and my case). One difference though. When closing the scene from drawer (step 4), the opened modal is still visible (so that would somewhat explain that componentWillUnmount is never called).

So I guess this is a React Navigation bug.

**Comment by MeetTheBest** [comment]
@rohitgoyal Hi Guy, Have you solved the problem.I had the same problem.
