### ISSUE TITLE
How to set Drawer Menu Transparent?

### ISSUE THREAD

**Issue by Donhv** [aksonov/react-native-router-flux#2875]
I setBackground: transParent in DrawerContent (<Drawer contentComponent={DrawerContent}> ).
 But It can't see through. it only opacity

In contentComponent: 
` return (
      <View style={[styles.container]}>
    </View>
)`
container style: 
container: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0,0.2)',
    borderWidth: 2,
    borderColor: 'red',
  }.
I try replace backgroundColor:'transparent' but it same.
![screen shot 2018-02-12 at 3 43 28 pm](https://user-images.githubusercontent.com/16864971/36090079-71875b00-1011-11e8-9488-d8a243f1e2c7.png)
Anyone help me make it transparent & see through( with  contentComponent={DrawerContent} )

**Comment by daviscabral** [comment]
@Donhv That might not be related to `react-native-router-flux`, but to `react-native-drawer-layout-polyfill` - the `DrawerView` component used in `react-navigation`.

It seems the `DrawerView` has a `drawerBackgroundColor` that you might try use to set the transparency. I haven't tried, but let me know if that does not work.

**Comment by alejandropinson** [comment]
@Donhv Did you make it work? Im having the same issue... @daviscabral how can I access the DrawerView?

**Comment by Donhv** [comment]
@alejandropinson I should use react-native-drawer. it work well with router-flux v4
