### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'addListener')

### ISSUE THREAD

**Issue by GeekRishabh** [aksonov/react-native-router-flux#2876]
"react": "16.2.0",
    "react-native": "0.51.0",
 "react-native-router-flux": "4.0.0-beta.22",
![screen shot 2018-02-12 at 8 52 58 pm](https://user-images.githubusercontent.com/23093075/36103993-cbff4a6e-1036-11e8-89f0-b9f407577361.png)

**Comment by Blapi** [comment]
Could you add more infos please? What are you trying to do? Show some code ?

**Comment by GeekRishabh** [comment]
@Blapi  I guess because RNRF uses React Navigation  as its dependency 
https://github.com/react-navigation/react-navigation/issues/3416
https://github.com/infinitered/ignite/issues/1225

Few days back everything was working fine the same code but when i tried to do `npm i` and started the project this error comes.

**Comment by Blapi** [comment]
Try RNRF 4.0.27
