### ISSUE TITLE
Jump to screen with no animation

### ISSUE THREAD

**Issue by Talkwondo** [aksonov/react-native-router-flux#2879]
Hi,
Please someone explain me how to do it.

Thanks,

**Comment by JulioOrellana** [comment]
Have you tried Actions.(yourScreenName)({ type: ActionsConst.REPLACE })

You must import { Actions, ActionsConst } from 'react-native-router-flux'

i.e: Actions.home({ type: ActionsConst.REPLACE })

**Comment by Talkwondo** [comment]
Hi,
I tried this. and this is the error:

<img width="310" alt="screen shot 2018-02-13 at 15 37 10" src="https://user-images.githubusercontent.com/20122139/36152482-e2dae9c6-10d3-11e8-89a8-dc913b421015.png">

**Comment by JulioOrellana** [comment]
Hello, I am so sorry, it is ActionConst, not ActionsConst (mind the "s")

![screen shot 2018-02-13 at 10 39 41 am](https://user-images.githubusercontent.com/10372340/36152583-42e3b55c-10aa-11e8-935c-23330215ec77.png)

**Comment by Talkwondo** [comment]
does not help. I used this RNRF before and for some reason this not the same syntax 

import { Actions, ActionConst } from 'react-native-router-flux'
this is my code:
setTimeout(function() {
                Actions.main({type: ActionConst.REPLACE})   
            },3000)
<img width="318" alt="screen shot 2018-02-13 at 16 36 55" src="https://user-images.githubusercontent.com/20122139/36155155-3f45770a-10dc-11e8-96db-5eee83ebcdc3.png">

**Comment by JulioOrellana** [comment]
What's your version of RNRF? if it is beta.28, change it for beta.27.

npm uninstall --save react-native-router-flux
npm install --save react-native-router-flux@4.0.0-beta.27

**Comment by Talkwondo** [comment]
It is now has no Error but there is still animation from right to left. and I tried couple keywords like JUMP and PUSH.... no change

**Comment by JulioOrellana** [comment]
Then, try Actions.replace("main")

**Comment by Talkwondo** [comment]
I tried this already... very strange...

**Comment by Blapi** [comment]
If it is about the transitions, have a look at #2628 please :) You will find your answer here. Ask if you need anything else.

**Comment by mackenziemance** [comment]
Yepp I reproduced, Actions.replace() seems to be broken with beta.28

**Comment by Blapi** [comment]
It is on .28, it works on .27
