### ISSUE TITLE
How to delete the navigation's bottom line?

### ISSUE THREAD

**Issue by DengGCccc** [aksonov/react-native-router-flux#2880]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 
- react-native v0.51.0

### Expected behaviour
delete the navigation's bottom line

### Actual behaviour
both android & ios have the black bottom line.

**Comment by NN01010101** [comment]
Had the same problem with iOS (grey / white) line at the bottom. Fixed with borderBottomWidth: 0 in navigationBarStyle

**Comment by aksonov** [comment]
@NN01010101 is right.
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
