### ISSUE TITLE
How to implement onRight function call on Scene component itself?

### ISSUE THREAD

**Issue by rohitgoyal** [aksonov/react-native-router-flux#2881]
### Version
"react-native-router-flux": "4.0.0-beta.27"
"react-native": "0.51.0"

I want to set the onRight function on the scene file itself so that i can apply functions which are only dependent on that scene. 

But i am unable to find a way to implement the onRight function in the scene file itself.

One way is defining a static function but in that case this is not available which ruins the whole purpose of it since i can't use things dependent on that scene. 

This is what something i want to achieve. 
```
onRight = function(){
    this.props.onSubmitPhoto(this.state.selectedUri)
  }
```

I want to access props passed to this scene  and state in the onRight function.

**Comment by aksonov** [comment]
You have to use redux/mobx or use navigation state & Actions.refresh inside static function
