### ISSUE TITLE
StatusBar Text Color

### ISSUE THREAD

**Issue by svallen** [aksonov/react-native-router-flux#2882]
Router (4.0.0-beta.28) seems to have some kind of StatusBar text overlay where it is making the text always black.

I can override that within a Scene by using **StatusBar.setBarStyle('light-content', true);** inside the render(). However it has this flashing from black to white and I'd like to have it consistently white the whole time.

Is there a parameter that I'm missing from the documentation that will allow me to set the StatusBar to white right way and maintain it through the whole app?

![screen shot 2018-02-13 at 11 34 05 am](https://user-images.githubusercontent.com/6169781/36161704-59fc3158-10b2-11e8-9377-7f8443b3efbf.png)

![screen shot 2018-02-13 at 11 34 29 am](https://user-images.githubusercontent.com/6169781/36161703-59e7ac92-10b2-11e8-85fc-a55a4b78c4f2.png)

**Comment by Proyoyo** [comment]
I'm having this issue as well.

**Comment by Rootedy** [comment]
+1

**Comment by Rootedy** [comment]
+1

**Comment by svallen** [comment]
Any update on how to get this fixed with an override of some sort?

**Comment by sendyputra** [comment]
this is work for me 
`<StatusBar barStyle="light-content"/>`

**Comment by svallen** [comment]
I tried this outside and inside the Router structure but that didn't work.

Still not able to get the statusbar color to update. Always stays black.

**Comment by daviscabral** [comment]
I use `<StatusBar barStyle="light-content"/>` out and before the routes - and works like a charm. Could you write a sample of this problem in the `Example` app and point the link here?

**Comment by svallen** [comment]
After using Expo/Snack I finally determined that it is not a router-flux issue. It was the use of NativeBase's Header component that is overriding the statusbar theme.

**Comment by vladcorn** [comment]
Hi guys.
To resolve this issue 
`<StatusBar style='dark' />`
`StatusBarStyle = 'auto' | 'inverted' | 'light' | 'dark';`

**Comment by Saliheen** [comment]
Below code works for me
```
import {useEffect} from 'react';
import {StatusBar} from 'react-native';

const TranslucentStatusBar = ({isDarkSelected = false}) => {
  useEffect(() => {
    StatusBar.setBarStyle(isDarkSelected ? 'dark-content' : 'light-content');
  }, [isDarkSelected]);
  return (
    <>
      <StatusBar
        translucent={true}
        backgroundColor="transparent"
        animated={true}
      />
    </>
  );
};

export default TranslucentStatusBar;
```
