### ISSUE TITLE
Static leftButtonImage not working

### ISSUE THREAD

**Issue by alexey-pelykh** [aksonov/react-native-router-flux#2883]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28 (v3 is not supported)
- react-native v0.53.0

### Expected behaviour

```
static leftButtonImage = () => {
    return require('./assets/image.png');
}
```
works as expected

### Actual behaviour

Not working

### Steps to fix

https://github.com/aksonov/react-native-router-flux/blob/master/src/navigationStore.js#L191
this check does not take `componentData` into the account, so either it should be removed to work as `onRight` portion, or expanded

### Workaround

```
leftButtonImage={something}
```
in the `<Scene/>` declaration

**Comment by M3po** [comment]
Having same problem, same versions

**Comment by delia-m** [comment]
Try with <Image src={} /> 
static leftButtonImage = () => {
    return <Image source={require('./assets/image.png')} />
}

**Comment by delia-m** [comment]
leftButtonImage shouldn't be a function...
try this ```leftButtonImage={require('./assets/image.png')}```

**Comment by alexey-pelykh** [comment]
It's irrelevant if it's a function, tried all ways possible
This works:
```
  static get rightButtonImage () {
    return require('./assets/correct-darkblue.png');
  }

  static get onRight () {
    return () => Actions.editprofile();
  }
```

This does not:
```
static get leftButtonImage () {
    return require('./assets/done.png');
  }

  static get onLeft () {
    return () => Actions.about();
  }
```

**Comment by alexey-pelykh** [comment]
@delia-m fyi: https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L79 is the reason why `leftButtonImage` may be a function

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
