### ISSUE TITLE
Removal of Scene Shadows by getSceneStyle is not applied

### ISSUE THREAD

**Issue by chanchilun** [aksonov/react-native-router-flux#2884]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour
I want to remove the shadow of all scenes when the router is wrapped by the SafeAreaView.

### Actual behaviour
The getSceneStyle gets is not applied
<img width="383" alt="screen shot 2018-02-15 at 11 02 38 am" src="https://user-images.githubusercontent.com/10358280/36238916-b17dee64-1240-11e8-921e-501c2acbdb18.png">

### Steps to reproduce
**My Code**
```javascript  
const getSceneStyle = () => ({
    shadowColor: 'transparent',
    shadowOffset: {
        width: 0,
        height: 0
    },
    shadowRadius: 0,
    shadowOpacity: 0
});

export default function AppContainer() {
    return (
        <ApolloProvider client={client} store={store}>
            <Root>
                <SafeAreaView style={AppStyles.appContainer}>
                    <RouterWithRedux
                        getSceneStyle={getSceneStyle}
                        navigator={AppRoutes}/>
                </SafeAreaView>
            </Root>
        </ApolloProvider>
    );
}
```

**Comment by ahmadw** [comment]
don't warp your Router with SafeAreaView just warp your content

**Comment by ThadeuBrito** [comment]
same here : (

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by haorh** [comment]
Pretty late to answer but for v4.0.6, if you're not using SafeAreaView, you can follow [this](https://stackoverflow.com/questions/51181965/react-navigation-header-has-a-faint-line) guy solution
```
<Router
   headerStyle= {{
        elevation: 0,
        shadowOpacity: 0,
        borderBottomWidth: 0,
      }}
/>
```
If you have SafeAreaView, you can do this
```
<Router
  cardStyle= {{ shadowColor: 'transparent' }}
/>
```
refer [this](https://stackoverflow.com/questions/48361898/how-to-remove-internal-shadow-of-react-native-stacknavigator-when-using-safearea?noredirect=1&lq=1)
