### ISSUE TITLE
Prop/State change of Parent is causing child components to Re-mount

### ISSUE THREAD

**Issue by KunwarSingh** [aksonov/react-native-router-flux#2886]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.53.0

### Code
Parent

`    
     render () {
             <Router>
                <Scene key="root">
                    <Scene
                        key="Child1"
                        component={Child1}
                    </Scene>

                    <Scene
                        key="Child2"
                        component={Child2}
                    </Scene>
                </Scene>
              </Router>
        }
`

### Expected behaviour
on prop/state change of parent component which is connected to redux, only parent component should re-render, and also those child components which have same redux state connected.  

### Actual behaviour
on state/prop change in parent, Its re-mounting the child component, which triggers re-render, componentDidMount again for child 

### Assumption
I believe issue is in the way u initialize Router and Scenes, I didn't had any issue in earlier version

**Comment by KunwarSingh** [comment]
For now I have resolved this by returning false from shouldComponentUpdate  in Parent. I think its not feasible to re-render the component where u declared Router

**Comment by KunwarSingh** [comment]
Still issue is there now Parent Component where Router is defined doesn't re-renders, but some the active scene does following on redux state change which is connected to parent component

WillMount
Render
WillUnmount
DidMount

**Comment by Blapi** [comment]
First, you should have a Stack/Scene with the key 'root' as a Parent.

Second, why are you doing this ?

**Comment by Blapi** [comment]
@KunwarSingh status there?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

Closed due inactivity

**Comment by aksonov** [comment]
@Blapi Feel free to close inactive tickets, thanks
