### ISSUE TITLE
[Closed] hideTabBar do not work

### ISSUE THREAD

**Issue by iugo** [aksonov/react-native-router-flux#289]
The tab3 `hideTabBar` has be set as `{true}`, but TabBar in footer is not be hidden.

React Native 0.21.0
Test code: https://github.com/aksonov/react-native-router-flux/tree/adb8e076e583b119854cababe05fa7d3144c6af6/Example

<img width="663" alt="2016-03-07 17 29 29" src="https://cloud.githubusercontent.com/assets/499364/13565307/4c36f9b4-e48a-11e5-813b-3985aadf3b43.png">

I see the file https://github.com/aksonov/react-native-router-flux/blob/f8e67ebb423bf47dd23645ed8adff61e313e8cb6/TabBar.js . alert(el.props.hideTabBar) -> `true`, but alert(this.props.hideTabBar) -> `undefined`.

**Comment by aksonov** [comment]
Thanks for the feedback! Please check latest 2.3.11
