### ISSUE TITLE
Actions.key not working with onPress - Android

### ISSUE THREAD

**Issue by xMaarf** [aksonov/react-native-router-flux#2890]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.50.0

### Expected behaviour

`<TouchableOpacity onPress={ Actions.getLogin } >`
  or
`<TouchableOpacity onPress={ () => Actions.getLogin() } >`
should navigate to getLogin screen

### Actual behaviour

- `onPress={Actions.getLogin}` or `onPress={() => Actions.getLogin() }` does not navigate to getLogin screen. 
- It works fine in IOS but in Android it doesn't.
- if I call Actions.getLogin() outside of onPress the app launches fine with the getLogin() screen.
- It's only happening in Android

**Comment by Blapi** [comment]
It's definitely on your side, you must have done something wrong in your own implementation.
`Actions.key` works fine on Android.
