### ISSUE TITLE
Updating state inside Static onRight() or onLeft() - undefined function error

### ISSUE THREAD

**Issue by luisbenan** [aksonov/react-native-router-flux#2891]
### Version
Tell us which versions you are using: 
    "react": "^16.2.0",
    "react-native": "^0.51.0",
    "react-native-beacons-manager": "^1.0.7",
    "react-native-calendars": "^1.16.1",
    "react-native-elements": "^0.18.5",
    "react-native-router-flux": "^4.0.0-beta.27",

### Expected behaviour
 Update this.state.daySelected to today's value

### Actual behaviour

Getting error of undefined function, either:

- [cannot read property "bind" of undefined ] when using 
this.goToday.bind(this) 
- goToday is not a function when using this.goToday()

However, these functions work fine outside of the Static onRight() {} 

What am I missing here?
 
What's the best way to update state when using Static onRight() or onLeft() ?

Thanks

<img width="279" alt="screen shot 2018-02-19 at 12 36 25 pm" src="https://user-images.githubusercontent.com/3769480/36390976-9d6634f6-1572-11e8-875b-4fb2b6aa7778.png">

<img width="545" alt="screen shot 2018-02-19 at 12 36 50 pm" src="https://user-images.githubusercontent.com/3769480/36390983-a051c22a-1572-11e8-9369-cea82b0d0b57.png">

**Comment by kylethebaker** [comment]
Since `onRight` is static you don't have access to `this` or any other internal component state. It is essentially just a regular function, external from the component.

This was a limitation for us as well. We weren't able to come up with a reasonable solution for changing the state, but maybe someone else can chime in with ideas.

**Comment by luisbenan** [comment]
Thanks. That makes total sense, I knew I was missing something/breaking some rules. Hopefully there's a work around. Anybody?

**Comment by Paul-Todd** [comment]
Lets see if this works....

Inside the onRight function you will need to get the ref for the component view. This can be found in the Actions.refs.SCENE_NAME (see #2256).

so..

we bind the function to "this" in the constructor.

`constructor(props) {
  super(props);
  this.goToday = this.goToday.bind(this);
  }'

We can then access it in the static

`static onRight() {
  const c = Actions.refs.todayScene;
  c.goToday();
}
`

Remember if you are wrapping your class in connect (if you are using redux) you will need to add a withRef to the config settings of your connect call

`export default connect(mapStateToProps, mapDispatchToProps, null, { withRef: true })(Today);`

Of course the easiest way is just to use Actions.refresh in the componentDidMount though this is an anti-pattern

`
componentDidMount() {
        Actions.refresh({
            right: () => {
                return (
                    <Text onPress={this._onSave} >
                            {"Save"}
                     </Text>
                );
            }
        });
    }`

**Comment by wardjk87** [comment]
I was able to user Paul-Todd comment to finally get my onRight method to call my component's method using redux without having to use static method on my class.

I didn't have mapDispatchToProps but only mapStateToProps, so I used the following export line:

`export default connect(mapStateToProps, null, null, {withRef: true})(NewStatusPage);`

I called the method on NewStatusPage component from my scene using the following:

`onRight={()=> {Actions.refs.details.getWrappedInstance().submitPost();}}`

The getWrappedInstance method returned my current mapStateToProps values in my redux store.

**Comment by maac4422** [comment]
Thanks @Paul-Todd  you save my life

**Comment by kylethebaker** [comment]
@timeturnback If I'm understanding the solution correctly you don't create a ref yourself but rather use the one provided by the router. It should be `Actions.refs[yourSceneName]`, where `yourSceneName` is the identifier for the scene that you set up in the router.
