### ISSUE TITLE
Update react-navigation dependency to release version

### ISSUE THREAD

**Issue by kylethebaker** [aksonov/react-native-router-flux#2893]
Is there a reason that the project is depending on React Navigation 1.0.0-beta22? This is 16 releases behind the current version of React Navigation which is now on v1.0.3 and out of the beta/rc stage.

I assume it's due to compatibility issues, have these been identified? I think it would be a good idea to start of list of these kinds of issues so that they can be addressed. Presumably now that react navigation is out of beta there will be less compatibility issues moving forward if we're able to get caught up.

**Comment by marcosmartinez7** [comment]
I have posted the same issue here https://github.com/aksonov/react-native-router-flux/issues/2865

i think that is more important to have compatibility with previous versions, i mean, RNRF beta 24 is using the last react-navigation, and RNRF beta 28 is using 10.0.0-beta22

**Comment by aksonov** [comment]
Unfortunately newer react navigation version completely changes state integration stuff: https://reactnavigation.org/docs/redux-integration.html 

PR is welcome but I doubt we can avoid any breaking changes to support newer react navigation version...

**Comment by aksonov** [comment]
There are more breaking changes coming:
https://github.com/react-navigation/react-navigation/pull/3392

**Comment by asciifaceman** [comment]
Yeah I've had a ton of issues with everything after 22, I even had to back up my react-native lib to keep everything working right

**Comment by marcosmartinez7** [comment]
react navigation is preparing v2, do u guys have a plan to keep supporting the RN changes? 

can u guys post some guidance in order to help with that?

**Comment by aksonov** [comment]
@marcosmartinez7 I'm working on new RNRF version that will work with v2 views. For v1, I will try to adopt current RNRF by adding empty addListener (if it would work).

**Comment by marcosmartinez7** [comment]
Great! let us know if we can colaborate in something in particular.

**Comment by aksonov** [comment]
It would be great if you could make RNRF work with v1. I can't add where I have to add 'addListener'

**Comment by kylethebaker** [comment]
I think if we compiled a list of the necessary changes it would make it
easier to collaborate. I guess a good place to start would be to bump the
version of the dependency and see what breaks?

**Comment by aksonov** [comment]
Ok, please check latest master and beta.30. Current error is following (Example project) - addListener is missed:
![simulator screen shot - iphone 7 - 2018-03-17 at 07 50 36](https://user-images.githubusercontent.com/1321329/37552548-ee72218a-29b7-11e8-8334-6f5b557fb6d1.png)

P.S. I've added `addListener` to `navigationStore` but it seems not to be enough...

**Comment by kylethebaker** [comment]
I'll play around with the current master this week and see if I can make any progress, I will use the example projects as a base and then when we start making progress I will try the latest version on my ongoing application.

**Comment by aksonov** [comment]
RNRF 4.0.0-beta.40 uses latest react-navigation now (2.x)
