### ISSUE TITLE
Bottom navigation gets disappeared from the previous scene when the new one is pushed.

### ISSUE THREAD

**Issue by igorarkhipenko** [aksonov/react-native-router-flux#2894]
### Version
- react-native-router-flux v4.0.0-beta.27
- react-native v0.53.0

### Expected behaviour
Bottom navigation is expected to be on the previous scene when the animation of transition is producing.

### Actual behaviour
Bottom navigation component disappears from the previous scene when the animation is producing.
![bottomnavigation_bug](https://user-images.githubusercontent.com/24496348/36411224-324555ac-161d-11e8-8cb7-fc0aff15bdc0.gif)

### Steps to reproduce
1. Create a bottom navigation with the button inside to transit to another container.
```
<Router createReducer={this._reducerCreate}>
  <Scene key="root">
    <Scene
      key="main"
      tabBarComponent={tabBarComponent}
      tabBarPosition="bottom"
      hideNavBar
      tabs
      initial={initial.dashboard}
    >
      {/* another scenes for tabBarComponent */}
      <Scene
        key="achievements"
        clone
        hideTabBar
        tabBarLabel="Achievements"
        component={Achievements}
        title="Achievements"
      />
      {/* another scenes for tabBarComponent */}
    </Scene>
    <Scene 
      key="personalRecords"
      component={PersonalRecords}
      title="Personal records"
    />
  </Scene>
</Router>
```
2. Smoothly go back using gesture.
3. Bottom navigation has disappeared from the previous scene.

**Comment by igorarkhipenko** [comment]
I wonder if I'm doing something wrong or nobody else uses this kind of simple transition between scenes. If so, could you guys give me any advice about that please?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
