### ISSUE TITLE
Problem: All tabs setting same title & One navigation bar for all tabs

### ISSUE THREAD

**Issue by MERTKIRKALI** [aksonov/react-native-router-flux#2895]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.28
- react-native v0.53.3

Hello,
I want only one NavigationBar on my tabbar but when i hide navbar in below scene, all navbar is gone.

Also when i set top scene title something else, all tabs title is setting same. How can i prevent this ?

Thank you, best regards.

Image
[https://i.hizliresim.com/jy6nQg.jpg](https://i.hizliresim.com/jy6nQg.jpg)

###My Codes

` <Scene key="tabbar" tabs hideNavBar={false} title='Plakapedi' rightTitle=" Ara" onRight={() => Actions.studentCreate()} leftTitle=" " onLeft={() => (null)} titleStyle={{
    textAlign: 'center',
    alignSelf: 'center', }}  `
  >
    ` <Scene onRight={() => Actions.studentCreate()} rightTitle=" Yeni" type={ActionConst.RESET} key="tab1" component={StudentsList} title="Bugün" />
    <Scene onRight={() => Actions.studentCreate()} rightTitle=" Yeni" type={ActionConst.RESET} key="tab2" component={StudentsList} title="Gündem" />
    <Scene onRight={() => Actions.studentCreate()} rightTitle=" Yeni" type={ActionConst.RESET} key="tab3" component={StudentsList} title="Favoriler" />
    </Scene> `

4.0.0-beta.28

**Comment by Blapi** [comment]
Tab Scene (child <Scene> within Tabs)

A Scene that is a direct child of Tabs and can use all props listed above in Scene

Property | Type | Default | Description
-- | -- | -- | --
icon | component | undefined | a React Native component to place as a tab icon
tabBarLabel | string |   | The string to override a tab label

**Comment by MERTKIRKALI** [comment]
@Blapi Thank you a lot ! But how about the hide tabs navigation bar  ? When i use hideNavBar, it is hide all NavBar. I want only hide tabs navigationbar.

Best regards.

**Comment by Blapi** [comment]
Try `hideNavBar` in your Tab Scene?

**Comment by MERTKIRKALI** [comment]
@Blapi  I already did. It is hide all navbar. I want to stay my top NavBar.

**Comment by Blapi** [comment]
Show me your code again please?

If you just apply this to your Tab Scene : `type={ActionConst.RESET} key="tab1" component={StudentsList}`, is it ok?

**Comment by MERTKIRKALI** [comment]
@Blapi [Image](https://i.hizliresim.com/qGvd4Z.jpg)

**Comment by Blapi** [comment]
In your Tab Scenes : 

Remove `onRight, rightTitle, title, hideTabBar`. Use `tabBarLabel` instead
