### ISSUE TITLE
Functionality for popping multiple scenes and pushing a new scene

### ISSUE THREAD

**Issue by bishalshr** [aksonov/react-native-router-flux#2896]
Can we have a functionality of popping x number of scenes and pushing a new scene?
using popTo along with push gives unnecessary animation

**Comment by Blapi** [comment]
You can try to push a new Scene with a type `replace` or `reset` instead?

Or you can handle your `Actions.pop` according to where you should stop pop.

**Comment by bishalshr** [comment]
@Blapi Doesn't "replace" only replace one scene?
Reset resets the whole stack and we can't achieve this by Actions.pop.

 I am trying to achieve:
Scene A => Scene B => Scene C=> Scene D to Scene A => Scene B => Scene E

**Comment by Blapi** [comment]
Well, you pop your Scene D and you replace your C by E then ?

**Comment by Blapi** [comment]
> we can't achieve this by Actions.pop.

I'm doing this on my own app and I had/have no troubles

**Comment by bishalshr** [comment]
I also tried to do the same thing but after Actions.pop is called, Scene C will be visible for 1-2 seconds.

**Comment by Blapi** [comment]
Surely because you're in debug mode.

You may have troubles getting rid of the transitions animations, but your Scene shouldn't be visible at all, or not that long, when doing this

**Comment by bishalshr** [comment]
@Blapi 
There is a bizarre issue here. When I do
`Actions.pop();
  Actions.replace(newScene);
`
It works fine.

But If I do
`await apiCall();
  Actions.pop();
  Actions.replace(newScene);
` it is showing old scene for some seconds.

**Comment by Blapi** [comment]
@bishalshr status there ?

**Comment by aksonov** [comment]
Closed due inactivity

**Comment by nik910** [comment]
What is the status of this issue? @bishalshr

**Comment by e3bmo3ty** [comment]
any updates ?

**Comment by briantofu** [comment]
updates?
