### ISSUE TITLE
Undefined is not a function (evaluating 'addListener') 

### ISSUE THREAD

**Issue by Dorentin1997** [aksonov/react-native-router-flux#2897]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.24
- react-native 0.50.3
- react-navigation ^1.0.0-beta.23

### Expected behaviour
Application should run normally

### Actual behaviour
It crashes after i just run "npm install"

TypeError: undefined is not a function (evaluating 'addListener')

This error is located at:
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:39)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at Router.js:67)
    in App (at Router.js:88)
    in Router (at Routes.js:47)
    in Routes (at App.js:126)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
<unknown>
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-navigation\src\getChildEventSubscriber.js:59:16
getChildEventSubscriber
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-navigation\src\getChildEventSubscriber.js:58:49
_getScreenDetails
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-navigation\src\views\CardStack\CardStack.js:106:10
render
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-navigation\src\views\CardStack\CardStack.js:219:47
proxiedMethod
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-proxy\modules\createPrototypeProxy.js:44:35
finishClassComponent
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1667:86
updateClassComponent
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1659:33
beginWork
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:1786:44
performUnitOfWork
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2528:33
workLoop
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2554:141
_invokeGuardedCallback
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:73:23
invokeGuardedCallback
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:47:40
performWork
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2593:41
scheduleUpdateImpl
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2728:101
scheduleUpdate
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2711:38
scheduleTopLevelUpdate
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2992:91
updateContainer
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3003:39
render
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3948:53
renderApplication
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\ReactNative\renderApplication.js:34:4
run
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:120:10
runApplication
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:207:26
__callFunction
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:302:47
<unknown>
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116:26
__guard
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:265:6
callFunctionReturnFlushedQueue
    D:\Projects\Wertheim2017\SmartSafeMobileApplicaiton\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:17

**Comment by Blapi** [comment]
Duplicate #2865

**Comment by mjstelly** [comment]
```
"react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-button": "^2.0.0",
    "react-native-message-bar": "^1.6.0",
    "react-native-router-flux": "4.0.0-beta.30",
    "react-navigation": "1.5.8"
```
I tried the `rm -rf node_modules` as mentioned above. I get the same error `Unhandled JS Exception: TypeError: addListener is not a function`

**Comment by daviscabral** [comment]
Same here - Example is broken right now - can't build it. Working on it for other issue - but no success so far.

**Comment by daviscabral** [comment]
Great news guys - I just fixed this issue and I am pushing a PR right now. 

/cc @aksonov
