### ISSUE TITLE
Change the navigationBarStyle dynamically

### ISSUE THREAD

**Issue by YoranRoels** [aksonov/react-native-router-flux#2898]
### Version
react-native-router-flux: 4.0.0-beta.24,
react-native: 0.48.4

### Expected behaviour
I want to be able to change the navigationBarStyle dynamically.

### Actual behaviour
I've tried using:
```
Actions.sceneName({ 
   navigationBarStyle: {
   backgroundColor: X,
   borderBottomColor: X,
});
```
When navigating to the scene.
And
```
Actions.refresh({
   navigationBarStyle: {
      backgroundColor: X,
      borderBottomColor: X,
   },
});
```
When mounting the scene.
However, this isn't changing anything.

**Comment by Blapi** [comment]
Not supported

https://github.com/aksonov/react-native-router-flux/issues/2639
