### ISSUE TITLE
Presenting some views as modal while others as normal from the same root view

### ISSUE THREAD

**Issue by R1ckye** [aksonov/react-native-router-flux#2899]
I'm wondering if it's possible (as the title states) to have a root view that presents both modals and normal side-navigated (a.k.a. pushed) Scenes?
According to the documentation, you have to wrap it in a <Modal> but that makes everything appear as a modal. Is there a workaround or an other way to do it?

**Comment by aksonov** [comment]
You may also check Example project with Modal usage
