### ISSUE TITLE
Intercept transitions

### ISSUE THREAD

**Issue by jbadeau** [aksonov/react-native-router-flux#29]
Is it possible to intercept a route transition and check if it's ok to proceed? I would like to allow the anonymous users to navigate the app except for a few pages where you must first authenticate. I would like to pop up a login modal view then redirect to the original route.

**Comment by aksonov** [comment]
It is not supported at this moment...

**Comment by aksonov** [comment]
Supported with 1.x release!

**Comment by aksonov** [comment]
I will think how to implement such scenario in nice way ('restricted' routes).

**Comment by aksonov** [comment]
But for now you could intercept it using Actions.onPush

**Comment by jbadeau** [comment]
Thanx you. I will have s look at at and see what I can come u with 😀
