### ISSUE TITLE
Search field in navigation bar

### ISSUE THREAD

**Issue by webdevsyd** [aksonov/react-native-router-flux#2902]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24(v3 is not supported)
- react-native v0.50.3

I would like to ask on how to put a search field in the navigation bar, can't see any example. Hoping there are some people that already did this.

**Comment by rstims** [comment]
I haven't tried it but perhaps you could build out your own navbar component and add it to the `Scene` using the `navbar` prop, see https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#scene

**Comment by aksonov** [comment]
Custom navbar is solution, @rstims is correct
