### ISSUE TITLE
Android: scenes transition vertically instead of horizontally

### ISSUE THREAD

**Issue by Twinbird24** [aksonov/react-native-router-flux#2903]
I'm having a problem where, on android, the transitions between scenes/ pages is vertical, instead of horizontal. I was thinking I could add a prop to a scene, like so: `<Scene direction="leftToRight" />` but this does not work. How should I go about fixing the transitions on android devices?

### Version
- react-native-router-flux v4.0.0-beta.22
- react-native v0.49.3

### Expected behaviour
Scenes transition horizontally (i.e. left-to-right) on both android and iOS devices.

### Actual behaviour
On android: scenes transition vertically (from bottom-to-top) instead of horizontally like they do in iOS.

### Steps to reproduce
1. Set up project with multiple sciences. i.e.
```
<Router>
      <Stack>
        <Scene />
        <Scene />
        ...
```
2. Navigate between scenes
3. Should see iOS transitions vertically, while android transitions pages horizontally

I've tried `<Stack key="root" transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal })}>` but this throws an error: `undefined is not a function (evaluating 'addListener'`. Please do not link to https://github.com/aksonov/react-native-router-flux/issues/2628 and close this issue, because I've read through that thread and I'm still having issues.

**Comment by Dorentin1997** [comment]
Import this at the file you register scenes. 
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';

And Add this to transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal })}
to your stack like this : 
<Stack key="root" hideNavBar={true} transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal })}>

**Comment by Blapi** [comment]
Show your main file with all your Scenes, as well as your imports please

**Comment by Twinbird24** [comment]
@Dorentin1997 upgrading react-native-router-flux from v4.0.0-beta.22 to 4.0.0-beta.26 fixed it for me!  Closing issue.
