### ISSUE TITLE
Is there  a way to "hide" a scene but not "pop" a scene?

### ISSUE THREAD

**Issue by Shu-Ji** [aksonov/react-native-router-flux#2906]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.53.0

### Expected behaviour

Keep components in memory.

### Actual behaviour

Actions.pop() will destroy the current scene.

### Steps to reproduce

There are 2 tabs in my app:

```jsx
Router(backAndroidHandler={() => {
  Actions.pop();
  return true;
}})
  Stack
    Scene(key=main initial={is_user_authed})
        Tabs(key=tabs)
          Scene(key=home)
          Scene(key=settings)
    Scene(key=profile)
    Scene(key=login initial={!is_user_authed})
```

We know tabs will keep tab-component-scene in memory.
See if I visit tab-home, do scroll for a while, then visit tab-settings, do somthing.
If I click tab-home icon, the scrollbar keeps well. This is the default and expected behavor.

In the tab-settings-scene, I have a button.
```jsx
  < Button onPress={() => {
        Actions.push('profile');
  }}>Go to profile</Button>
```
When I click this button, the profile screen shows, then I tap the Android Back Button, the profile-scene unmounted. I want make the profile mounted in forever.

In my Router, I write a backAndroidHandler, call Actions.pop().

Is there a way to not pop the profile-scene, as profile is a tab like tab-home, so that I can keep the tab-profile state(such as the scrollbar position) if user visit again?

Maby a `Actions.hide()`.

Or:

Is there a "virtual tab" that is a tab-scene, but invisible in tabbar?

```jsx
Router
  Stack
    Scene(key=main initial={is_user_authed})
        Tabs(key=tabs)
          Scene(key=home)
          Scene(key=settings)
          Scene(key=profile lazy={true} virtual={true})  {/* see the virtual props */}
    Scene(key=login initial={!is_user_authed})
```
So that user will see two tabs(home and settings) in the tabar, but in real, I have three tabs(home, settings and profile).

Sorry for my poor English.

What I want to do is something like this:

In jQuery/Bootstrap, 
I have a `<div class="modal">...</div>`, 
then I can use `$(".modal").show() / $(".modal").hide()`, 
But not `$(".modal").create() / $(".modal").destory()`

I tried the Modal and Lightbox component, it will also unmount.

The same question in react navigation:
https://github.com/react-navigation/react-navigation/issues/2331
https://github.com/react-navigation/react-navigation/issues/2365
I created a expo repo snack:
![image](https://user-images.githubusercontent.com/1127594/36766750-31aeffe8-1c72-11e8-9194-7f063dc64a31.png)
Everytime I enter the detail page, it will remount(the number changes), which I don't want.

**Comment by aksonov** [comment]
You may try to use tabs with hideTabBar so all your scenes will not be destroyed

**Comment by qiruiqq3** [comment]
how to fix this issue? tks

**Comment by Riant** [comment]
I think the drawerNavigator is a better solution, but not the best solution.

https://react-navigation.canny.io/feature-requests/p/is-there-a-way-to-keep-some-screen-alive-after-goback-similar-as-the-drawer-navi
