### ISSUE TITLE
Setting init to true on a Scene component doesn't remove back button

### ISSUE THREAD

**Issue by tkalejaiye** [aksonov/react-native-router-flux#2907]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.53.3

### Expected behaviour
Setting init={true} should remove back button from header on a scene

### Actual behaviour
Setting init={true} doesn't remove back button but setting init={false} does

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create a scene and set init to true
2.
3.

**Comment by tkalejaiye** [comment]
Would appear setting to false didn't resolve the issue either actually. Using left={null} to get around the issue now

**Comment by asciifaceman** [comment]
Hmm, out of curiosity, if it isn't too inconvenient, and you feel up to it, could you see if you can reproduce on `^4.0.0-beta.22`? It's purely for my own curiosity, since thats the last version I've been able to use without weirdness.

**Comment by MayankRajSinha** [comment]
The issue still persists in `^4.0.0-beta.31`. As mentioned by @tkalejaiye doing` left={null}` is the workaround.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
