### ISSUE TITLE
Actions.pop() on mounted but not visible component

### ISSUE THREAD

**Issue by lrettig** [aksonov/react-native-router-flux#291]
Hello,

I'm using a TabBar-based navigation scheme, which means that there are multiple navigation stacks. Sometimes I need to pop an element off one of these stacks while it isn't the currently visible stack (concrete example: user was viewing a data element in tab A, then proceeds to delete that element in tab B). I noticed that calling `Actions.pop()` inside an element on a different stack actually pops the topmost element off the current stack, which doesn't seem like desirable behavior.

I'm happy to try to fix this, but I want to know if you agree with my proposed behavior: that calling `Actions.pop()` from a component mounted in stack A, while stack B is visible, would pop it off of stack A, rather than popping the topmost element from stack B.

Thanks.

**Comment by aksonov** [comment]
Sounds good.

**Comment by lrettig** [comment]
Okay I'll take a crack at this and let you know if I get stuck. Not sure yet how to tell which stack the component should be popped from, if e.g. it's on multiple stacks!

**Comment by aksonov** [comment]
What about setting  Actions.currentRouter to that 'hidden' stack, doing pop and then restore currentRouter?

**Comment by lrettig** [comment]
Makes sense. But what if the component in question is actually mounted on multiple stacks?

**Comment by aksonov** [comment]
Hm, give him different properties then to distinguish stacks. Or i don't understand the question

**Comment by lrettig** [comment]
This is working for me, what do you think? https://github.com/lrettig/react-native-router-flux/commit/e0db8f1f664c50b9619adbef890cf43c305b74c7

The view-to-be-popped must call Actions.pop with `this.props.route.parent`.

Another option is to modify the `Route` class to add a `pop()` method, so that, instead, the view could call `this.props.route.pop()`.

**Comment by aksonov** [comment]
Doing this.props.route.pop() looks better option..

**Comment by lrettig** [comment]
Sure. Thanks for the feedback. Will submit a PR asap!

**Comment by adbl** [comment]
@lrettig I'm also interested in this 👍

**Comment by lrettig** [comment]
Will submit PR by this weekend

**Comment by lrettig** [comment]
Changes are done, tested (briefly), and working. Closing in favor of PR https://github.com/aksonov/react-native-router-flux/pull/313.
