### ISSUE TITLE
How to make Modal & Lighbox

### ISSUE THREAD

**Issue by Koshub** [aksonov/react-native-router-flux#2910]
This is not a bug but it is not so clear how to make both`modal` and `lightbox` together - modal with transparent background. I tried to find the way and decided to post a question. Is there any way to combine components on router level rather than make lighbox with fake modal animation?

**Comment by asciifaceman** [comment]
What are you going for? They are separate because they do slightly different things. The example demonstrates using both, albeit not rendering at the same time IIRC.

**Comment by Koshub** [comment]
@asciifaceman because in iOS it is currently a trend to make modal transparent transition, especially with blured background. `modal` is required to be natively according to iOS UIKit components transitions, but the transparent background is a bit like feature here. Look at mail app in iOS11 when new  message  is creating - it is something like what I'm talking about but without blured background.

**Comment by Koshub** [comment]
@aksonov Why it is closed?

**Comment by aksonov** [comment]
I don't understand the issue. Check Example project that uses Lightbox and Modal
