### ISSUE TITLE
How to show a toast view and has no effect for scene interaction?

### ISSUE THREAD

**Issue by JohnDn** [aksonov/react-native-router-flux#2912]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by asciifaceman** [comment]
not quite enough information

**Comment by Blapi** [comment]
And not related to RNRF
