### ISSUE TITLE
Tabs section under the navbar.

### ISSUE THREAD

**Issue by pgonzalez-santiago** [aksonov/react-native-router-flux#2913]
### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

Right now I have a screen in my RN application that need 3 tabs in the top. My question is: It is possible to place the tabs under the navbar?

right now its looking like this:

![image](https://user-images.githubusercontent.com/17064785/36850518-55803af4-1d67-11e8-9e89-0a07faa43792.png)

The structure is:

```
           <Scene
              key="mediaContainerScreen"
              panHandlers={null}
              hideNavBar
            >
                <Tabs
                    key="mediaContainerTabs"
                    swipeEnabled
                    showLabel={true}
                    tabBarPosition='top'
                    tabBarStyle={{ backgroundColor: Colors.navBar }}
                    labelStyle={{ color: Colors.primaryColor }}
                    indicatorStyle={{ backgroundColor: Colors.primaryColor }}
                    activeBackgroundColor="white"
                    lazy
                    >
                      <Scene
                        key="Images"
                        component={MediaContainerScreen}
                        title="MediA Images"
                        tintColor={Colors.primaryColor}
                        back={false}
                      />
                      <Scene
                        key="Videos"
                        component={MediaVideoContainerScreen}
                        title="MediA VideoS"
                        tintColor={Colors.primaryColor}
                        back={false}
                      />
                      <Scene
                        key="Pdfs"
                        component={MediaPdfContainerScreen}
                        title="MediA Pdfs"
                        tintColor={Colors.primaryColor}
                        back={false}
                      />
                </Tabs>
            </Scene>
          </Scene>
```
I need to see the tabs down the navbar.

**Comment by filiipake** [comment]
same here

**Comment by pgonzalez-santiago** [comment]
Finally I got success with a custom navBar, the only problem with it is that I can not refresh the props of the navBar from the child components(tabs).

<img width="465" alt="screen shot 2018-03-02 at 17 28 31" src="https://user-images.githubusercontent.com/17064785/36909800-5998ba5c-1e3f-11e8-8aa8-589786f68280.png">

My structure:

```
           <Scene
              key="mediaContainerScreen">
              <Tabs
                  key="mediaContainerTabs"
                  swipeEnabled
                  showLabel={true}
                  tabBarPosition='top'
                  tabBarStyle={{ backgroundColor: Colors.navBar }}
                  labelStyle={{ color: Colors.primaryColor }}
                  indicatorStyle={{ backgroundColor: Colors.primaryColor }}
                  activeBackgroundColor="white"
                  navBar={MediaNavBar}
                  lazy
                  >
                    <Scene
                      key="Images"
                      component={MediaContainerScreen}
                      title="MediA Images"
                      tintColor={Colors.primaryColor}
                      hideNavBar
                      back={false}
                    />
                    <Scene
                      key="Videos"
                      component={MediaVideoContainerScreen}
                      title="MediA VideoS"
                      tintColor={Colors.primaryColor}
                      hideNavBar
                      back={false}
                    />
                    <Scene
                      key="Pdfs"
                      component={MediaPdfContainerScreen}
                      title="MediA Pdfs"
                      tintColor={Colors.primaryColor}
                      hideNavBar
                      back={false}
                    />
              </Tabs>
            </Scene>
```

**Comment by tomcrusader** [comment]
I don't get any tabs at all on Android. Tabs are there, you can swipe between them, but icon and title doesn't show.
Works fine on iOS.
```javascript
const mainIcon = () => (
  <FontAwesome name='map-o' size={TabIconSize} style={Theme.tabBarIcon} />
);
const AppNavigator = () => {
  return (
    <Router
      createReducer={reducerCreate}
      // @ts-ignore
      uriPrefix={prefix}
    >
      <Scene key='root' style={Theme.container}>
          {/*

              tabBarPosition='bottom'
              tabBarComponent={TabBarBottom}
        */}
        <Scene key='tabWrapper' hideNavBar panHandlers={null} style={Theme.container}>
            <Tabs
              tabBarComponent={TabBarBottom}
              key='tabbar'
              showLabel
              lazy
              activeTintColor={Colors.CrossYellow}
              tabBarStyle={Theme.tabBar}
            >
              <Scene
                key='main'
                title='Start'
                icon={mainIcon}
                tabBarLabel='Start'
                titleStyle={Theme.tabBarTitle}
                back={false}
                tintColor={Colors.CrossYellow}
                component={Main}
              />
              <Scene
                key='main2'
                title='Start2'
                icon={mainIcon}
                tintColor={Colors.CrossYellow}
                tabBarLabel='Start2'
                back={false}
                component={Main}
              />
            </Tabs>
          </Scene>
      </Scene>
    </Router>
  );
};
```

**Comment by GreenCame** [comment]
adding `wrap={false}` to tabs component save me !!

ex.
` 
<Stack
 title="Events"
 ....
 panHandlers={null}
 >
    <Tabs
    ...
    headerMode="screen"
    wrap={false}
    >
      <Scene/>
   </tabs>
</Slack>`

**Comment by Blapi** [comment]
It looks solved

**Comment by Mozartted** [comment]
@GreenCame thanks man... the wraps props was definitely the best way to solve it, but take care to avoid a Scene or a Stack on the outside in order to avoid another navbar above the Tab's navbar

```js
<Tabs
       swipeEnabled
       type="replace"
	key="tribeSummary"
	title="Tribe summary"
	showLabel={false}
	back
	wrap={false}
>
	<Scene key="overview" title="overview" icon={TabIcon} component={TribeOverviewComponent} />
        <Scene key="harvest" title="harvest" icon={TabIcon} component={TribeHarvestComponent} />
        <Scene key="seeds" title="seeds" icon={TabIcon} component={TribeSeedsComponent} />
</Tabs>

```

**Comment by edoantonioco** [comment]
So as @pgonzalez-santiago stated the way to fix this is with navBar={MediaNavBar}

but what about a Scene that is a Drawer? SInce it has no component attached (to be replaced with MediaNavBar)

**Comment by IgorUsoltsev** [comment]
> adding `wrap={false}` to tabs component save me !!
> 
> ex.
> 
> ```
> <Stack
>  title="Events"
>  ....
>  panHandlers={null}
>  >
>     <Tabs
>     ...
>     headerMode="screen"
>     wrap={false}
>     >
>       <Scene/>
>       <Scene/>
>    </tabs>
> </Slack>
> ```
Adding `wrap={false}` also did a trick for me. Even with a standard navbar.

**Comment by MohitR1999** [comment]
> Finally I got success with a custom navBar, the only problem with it is that I can not refresh the props of the navBar from the child components(tabs).
> 
> <img alt="screen shot 2018-03-02 at 17 28 31" width="465" src="https://user-images.githubusercontent.com/17064785/36909800-5998ba5c-1e3f-11e8-8aa8-589786f68280.png">
> 
> My structure:
> 
> ```
>            <Scene
>               key="mediaContainerScreen">
>               <Tabs
>                   key="mediaContainerTabs"
>                   swipeEnabled
>                   showLabel={true}
>                   tabBarPosition='top'
>                   tabBarStyle={{ backgroundColor: Colors.navBar }}
>                   labelStyle={{ color: Colors.primaryColor }}
>                   indicatorStyle={{ backgroundColor: Colors.primaryColor }}
>                   activeBackgroundColor="white"
>                   navBar={MediaNavBar}
>                   lazy
>                   >
>                     <Scene
>                       key="Images"
>                       component={MediaContainerScreen}
>                       title="MediA Images"
>                       tintColor={Colors.primaryColor}
>                       hideNavBar
>                       back={false}
>                     />
>                     <Scene
>                       key="Videos"
>                       component={MediaVideoContainerScreen}
>                       title="MediA VideoS"
>                       tintColor={Colors.primaryColor}
>                       hideNavBar
>                       back={false}
>                     />
>                     <Scene
>                       key="Pdfs"
>                       component={MediaPdfContainerScreen}
>                       title="MediA Pdfs"
>                       tintColor={Colors.primaryColor}
>                       hideNavBar
>                       back={false}
>                     />
>               </Tabs>
>             </Scene>
> ```

Thanks for your code, I was actually stuck at creating a Tabbed Navigation and you helped me a lot :heart:
