### ISSUE TITLE
Additional props not being passed to component when push is used to call scene

### ISSUE THREAD

**Issue by rstims** [aksonov/react-native-router-flux#2914]
### Version

- react-native-router-flux v4.0.0-beta.28
- react-native v0.51.0

### Expected behaviour

I expect additional props to be passed to component when using `push` to show scene

### Actual behaviour
Additional props are not passed to component when using `push` to show scene

**Comment by bacancy-suresh** [comment]
Try Actions.currentParams. you can get Object of all params for current scene.
