### ISSUE TITLE
Provide better v4 redux integration docs

### ISSUE THREAD

**Issue by luizguilhermefr** [aksonov/react-native-router-flux#2916]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.beta28
- react-native v0.54

Would you please provide better redux integration docs, beyond the example project?

I've upgraded recently and it's very confusing now. In v3 you should just `const RouterWithRedux = connect()(Router)` and that's it. Now everything seems very different.

**Comment by Lxxyx** [comment]
Yes, please provide better v4 redux integration docs. Current way is too difficult for me

**Comment by hosembafer** [comment]
Any news around that? I'm starting a new application with v4 and want to know how to redux?

**Comment by hosembafer** [comment]
@southerneer the author of previous [documentation](https://github.com/aksonov/react-native-router-flux/blob/master/docs/v3/REDUX_FLUX.md); maybe he can help.

**Comment by aksonov** [comment]
Duplicate #2851
