### ISSUE TITLE
Tab View looks weird on android (emulator)

### ISSUE THREAD

**Issue by zxccvvv** [aksonov/react-native-router-flux#2917]
I'm learning how to use flux on this [article](https://medium.com/differential/react-native-basics-using-react-native-router-flux-f11e5128aff9)

the code looks well, but the tab view has some space above

![screenshot_2018-03-04-01-20-20](https://user-images.githubusercontent.com/19633881/36937724-3de290a6-1f4a-11e8-869d-6d2cc4d2f0aa.png)

anyone can help me?

**Comment by tomcrusader** [comment]
Try `flex: 1` style on everything **except** the tabs, since that will break their design and hide them

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
