### ISSUE TITLE
hideDrawerButton removes back button from child scenes

### ISSUE THREAD

**Issue by avin3sh** [aksonov/react-native-router-flux#2918]
### Version
- react-native-router-flux 4.0.0-beta.28
- react-native v0.53.3

Firstly, the drawer hamburger icon is even rendered on nav bar of scenes which are not child of `<Drawer>` (or `<Scene drawer>`) 

Secondly, if the `hideDrawerButton` property is used then drawer icon is indeed hidden but even back button from navbar of child scenes vanishes.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
