### ISSUE TITLE
Pass Value from Drawer To <Scene in Drawer

### ISSUE THREAD

**Issue by Donhv** [aksonov/react-native-router-flux#2919]
I use react-native-drawer and react-native-router-flux v4.
My router:
 ``` 
 <Router>
<Scene key="root" hideNavBar={true} >
<Scene overlay contentComponent={contentComponent}>
<Scene key="Basic" initial={true} component={Basic} title="Basic" />
</Scene>
</Router> 

My contentComponent:
<Drawer onOpen={() => this.setState({ isDrawerOpen: true })} >
{React.cloneElement(this.props.children[0], YourProps: this.state.isDrawerOpen })}
</Drawer>
```
Now i want pass state isDrawerOpen to component Basic. i want when drawer open will set a state in Basic. 
Anyone can help me?

**Comment by asciifaceman** [comment]
Can you reformat your post using tripple ticks ``` which should make it a bit more readable.

I'm also not quiiiiite following what you are trying to do. I think I have an idea, but could you elaborate before I make suggestions?

**Comment by Donhv** [comment]
@asciifaceman  thanks for reply :D

**Comment by asciifaceman** [comment]
I'm trying to understand the flow of what is going on here.

You are rendering `Basic` inside the drawer are you not? And it looks like you were trying to pass in isOpen with `YourProps`?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
