### ISSUE TITLE
DeviceEventEmitters getting lost on Action.pop()

### ISSUE THREAD

**Issue by rgoldiez** [aksonov/react-native-router-flux#292]
I have a route who's component (lets call it the `ChatComponent`) includes `keyboardWillShow` event listeners to add a spacer below a text input field so that the `TextInput` sits right above the keyboard.  

This works fine, except this scenario:
`Actions.ChatComponent()` --> keyboard shows, event listeners working as expected --> user taps on a buddy's avatar, so `Actions.UserProfile()` --> user views profile, keyboard event listeners still listening and responding --> user goest back to `ChatComponent` with `Actions.pop()` --> keyboard event listeners no longer work.

The `ChatComponent` never unmounts, which is fine and expected.  The event listeners fire from `ChatComponent` fire when `UserProfile` is on the top of the stack, which is fine and expected.  But as soon as the user goes back (`Actions.pop()`) the event listeners no longer work.

I'm on React Native 0.21.0 and `react-native-router-flux` version 2.3.10

**Comment by aksonov** [comment]
The component doesn't do anything with event emitters. It is just wrapper around React native navigator.

**Comment by rgoldiez** [comment]
Confirmed.  I narrowed down the issue.  Thanks.
