### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by juliusspencer** [aksonov/react-native-router-flux#2922]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.53.3

### Expected behaviour
When using typescript I expect there to be no error when I don't supply a component using a drawer.

### Actual behaviour
I get the following error using Typescript with the following Scene JSX:
```javascript
<Scene
	key="drawer"
	drawer={true}
	contentComponent={NavDrawer}
	hideNavBar={true}
	drawerIcon={this.navDrawerImage()}
>
```

src/App.tsx(103,10): error TS2322: Type '{ key: "drawer"; drawer: true; contentComponent: ComponentClass<Pick<Props & Actions, never>> & {...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SceneProps & TabsProps & TabSceneProps &...'.
  Type '{ key: "drawer"; drawer: true; contentComponent: ComponentClass<Pick<Props & Actions, never>> & {...' is not assignable to type 'Readonly<SceneProps & TabsProps & TabSceneProps & DrawerProps & ModalProps>'.
    Property 'component' is missing in type '{ key: "drawer"; drawer: true; contentComponent: ComponentClass<Pick<Props & Actions, never>> & {...'.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Use the JSX above with a NavDrawer Component.
2. Use tsc to transpile
3. View the output log

### Fix
I think this could be fixed by changing:
```javascript
component: React.ComponentType<any>
```
to
```javascript
component?: React.ComponentType<any>
```

**Comment by tomcrusader** [comment]
Dito. Very annoying

**Comment by windwang** [comment]
+1

**Comment by JosePBrotons** [comment]
+1

**Comment by aksonov** [comment]
Should be fixed now
