### ISSUE TITLE
Actions.key not working

### ISSUE THREAD

**Issue by nogard** [aksonov/react-native-router-flux#2928]
Reference to bug #2890. I was also having a problem of Actions.key not working. It seems the problem could be more than 1 mobx instances being loaded. The reactions are not being fired because of different mobx versions. I moved the mobx dependencies in react-native-router-flux to peerDependencies and it seems to solve the issue. Not sure if this is right way to fix it.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
