### ISSUE TITLE
Nested tabs are not working and Header is removed by nested tabs. 

### ISSUE THREAD

**Issue by netsmertia** [aksonov/react-native-router-flux#2929]
### Version
Tell us which versions you are using: 

"react-native-router-flux": "^4.0.0-beta.28"
 "react-native": "0.53.3",

### Expected behaviour

Nested Tabs like 
Tab 1 (title = STARS)
Tab 2 (Title = REQUESTS)
      -> Tab 2.A (tabbar=top, title = REQUESTS)
     -> Tab 2.B  (tabbar=top, title = REQUESTS)
Tab 3 (Title = ACCOUNT)

![whatsapp image 2018-03-11 at 8 02 46 pm](https://user-images.githubusercontent.com/4003316/37255086-49caf006-256d-11e8-9413-deed34078e50.jpeg)

Above navigation is build by React Navigation by putting a TabNavigator in another TabNavigator. 

### Actual behaviour
issues
1. No title in 2nd tab (nested tab).
2. Nested tab not behave as it should be. No tab switching. Primary tabs are still working.
![screen shot 2018-03-11 at 8 45 19 pm](https://user-images.githubusercontent.com/4003316/37255107-b077f484-256d-11e8-9a81-8f14d6112d6b.png)

![screen shot 2018-03-11 at 8 45 29 pm](https://user-images.githubusercontent.com/4003316/37255194-f3d34ef8-256e-11e8-8d99-b60f84fd9930.png)

### Steps to reproduce
Create a tab with title and 3 bottom tabs. 
put nested Tab with 3 tabs in 2nd tab of primary. (secondary tab should be under the same title as given by 2nd primary tab).

This is my router structure.

```jsx
    <Router>
      <Scene key="root">
        <Scene key="mainTab" tabs tabBarPosition="bottom"
          showLabel={false}
          showIcon={true}
          tabBarStyle={styles.tabBarStyle}
          navigationBarStyle={styles.navigationBarStyle}
          titleStyle={styles.titleStyle}
         >
          <Scene key="stars" component={StarsScreen} icon={getTabIcon} tabIndex="stars" title="STARS"></Scene> 
          <Scene key="requests" hideNavBar = {false} icon={getTabIcon} tabIndex="request" title="REQUESTS">
            <Scene key="inner" tabs tabBarPosition="top" hideNavBar = {false} title="googd">
              <Scene key="t1" component={DeclinedTab} icon={getTabIcon} tabIndex="stars" title="STARS"></Scene> 
              <Scene key="t2" component={PendingTab} icon={getTabIcon} tabIndex="stars" title="STARS"></Scene> 
            </Scene>

          </Scene>
          <Scene key="account" component={StarsScreen} icon={getTabIcon} tabIndex="account" title="MY ACCOUNT"></Scene> 
        </Scene>
      </Scene>
    </Router>
```
I have also tried to put the secondary tab directly under the 2nd tab of primary and different combination of `hideNavBar` but got the same issues.

**Comment by telmen** [comment]
?

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
