### ISSUE TITLE
Question: Drawer slide out from bottom

### ISSUE THREAD

**Issue by asciifaceman** [aksonov/react-native-router-flux#2931]
Is it possible with the current API to have a drawer slide upwards from the bottom? 

On looking initially it only supports left and right, but wondering if this is possible in general with the API, or perhaps with minor modifications in a fork (and contribute back if it works)

I just need some guidance.

**Comment by aksonov** [comment]
Sorry, it is not supported

**Comment by asciifaceman** [comment]
@aksonov If I can get something together would you accept a PR for other directions? No promises, but I have it working in a project and might be able to abstract it to RNRF

**Comment by aksonov** [comment]
Sure!
