### ISSUE TITLE
TouchableNativeFeedback and ripple effect

### ISSUE THREAD

**Issue by Almaju** [aksonov/react-native-router-flux#2933]
That might sounds like a dumb question but when using `onPress={() => Actions.AnotherView()}` this kind of disable the ripple effect from TouchableNativeFeedback. It's still there if I keep pushing on the button but if I just tap, it won't show and I feel like this is not the proper behaviour expected.

**Comment by asciifaceman** [comment]
Doing some cursory searching around, it looks like ripple is a common thing to break - especially with react navigation.

ex. https://github.com/react-navigation/react-navigation/issues/2329

I wonder if it is because the scene is changing faster than the animation can fire?

**Comment by Almaju** [comment]
I just did a test and this works perfectly:

    <TouchableNativeFeedback
        onPress={() => {
          setTimeout(() => { Actions.AnotherView(); }, 0);
        }}
      />

**Comment by Almaju** [comment]
Here is the fix I ended up doing that works:
```js
import React from 'react';
import { Platform, TouchableOpacity, TouchableNativeFeedback, View } from 'react-native';
import _ from 'lodash';

const Touchable = (props) => {
  const { ...other } = props;

  if (Platform.OS === 'ios' || Platform.Version < 21) {
    return (
      <TouchableOpacity {...other}>
        {other.children}
      </TouchableOpacity>
    );
  }

  if (_.isFunction(props.onPress)) {
    other.onPress = () => {
      setTimeout(() => { props.onPress(); }, 0);
    };
  }
  return (
    <TouchableNativeFeedback
      useForeground
      {...other}
    >
      <View {...other} pointerEvents="box-only">
        {other.children}
      </View>
    </TouchableNativeFeedback>
  );
};
```

**Comment by asciifaceman** [comment]
Yeah it looks like it gives just enough time for the ripple to occur before the transition is fired.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
