### ISSUE TITLE
Router showing old mounted views with old props when being re-launched in android

### ISSUE THREAD

**Issue by RajeshBatth** [aksonov/react-native-router-flux#2936]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.52.0

### Expected behaviour
Router should update the props of children when launched after closing and opening again with updated props from native app

### Actual behaviour
Reopen the page(Page B) with new props after closing the old page (Page A), old page (Page A) is being showed and props of pages are also *not* updated

### Steps to reproduce
1. Clone the demo app: https://github.com/RajeshBatth/rn-router-flux-load-issue
2. Run the app `react-native run-android`
3. Click on 'OPEN PAGE ONE' button you'll see a Red page with text SCREEN ONE
4. Now Press back and click on 'OPEN PAGE TWO' button you still see a Red page with text SCREEN ONE, instead of a green page with text SCREEN TWO

to check the props connect to debugger and check the logged values with text "AppRouter.props"

**Comment by ANKITGUPTAMMT** [comment]
Happening for me too. Pls help

**Comment by ranjanrukhaya** [comment]
Please help..happening for me as well. Need it urgently.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
