### ISSUE TITLE
How to refresh Tabs scene every time i switch tabs?

### ISSUE THREAD

**Issue by AndrejZdravev** [aksonov/react-native-router-flux#2937]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "^4.0.0-beta.28"
- "react-native": "0.54.0",

**Comment by asciifaceman** [comment]
onOpen:

In stack definition:

```
                    <Scene key="SomeView"
                           component={SomeView}
                           onEnter={this.onEnterSomeView}
                    />
```

In SomeView:

```
export default class SomeView extends Component {

  static onEnterExplore = () => {
    Actions.refresh({
      enterTime: new Date()
    });
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props.enterTime);
    console.log(nextProps.enterTime);   // for you to see what is happening
    if (this.props.enterTime !== nextProps.enterTime) {
      this.refreshData(); // a function that changes the state to re-render
    }
  }
```

What is going on here is that when you navigate to a View, onEnter is fired. This even works if you are going back and forth between tabs. The refresh line refreshes the view setting enterTime to that time. If there is a delta between enterTime and the and the next enterTime, it will fire whatever is in that function or whatever you put there. 

This can be expensive if you are doing heavy lifting.

You also have to change the state (setState) of something that is rendered to trigger it. (someone could correct me here, but I'm 90% sure you have to change state of something rendered)

**Comment by AndrejZdravev** [comment]
Thanks @asciifaceman for your help, but when i use this code i get warning "Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op."

**Comment by asciifaceman** [comment]
What are you doing specifically?

**Comment by aaron25mt** [comment]
You might be clicking too fast, I get that sometimes but usually works fine using the Actions.refresh method.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
