### ISSUE TITLE
How to get props from Actions.pop()

### ISSUE THREAD

**Issue by thngdude** [aksonov/react-native-router-flux#294]
When you pop a Route, there is the option to pass a props parameter. How would you obtain this after the pop?

**Comment by aksonov** [comment]
use onPop handler (for Router) or redux events (check docs)

**Comment by thngdude** [comment]
Ah, I see. When you refer to docs, are you talking about the readme or is there something I'm missing? I've been trying to undersatnd how this awesome project works by looking at the code. Thanks
