### ISSUE TITLE
How to pass props to Actions.replace?

### ISSUE THREAD

**Issue by jingoldby** [aksonov/react-native-router-flux#2943]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.52.2

Tried the following...
Actions.replace({ key: tabKey, props: tabPage });
Actions[key]({ type: ActionConst.REPLACE, tabPage: tabPage })
and several variations there of

**Comment by jingoldby** [comment]
currently working around by just checking Actions.currentScene and returning null on the container I don't want to see the tab on....

best way? *shrug*

**Comment by jingoldby** [comment]
Ah just also realized that replace is apparently broken.... :|   any work arounds?

**Comment by Blapi** [comment]
Downgrade to RNRF .27 :)

**Comment by jingoldby** [comment]
@Blapi hey thanks for the heads up! I've downgraded to 0.27 but how do I properly pass props with a replace or refresh?

**Comment by Blapi** [comment]
Check the Example project please, it's done there, something like this : 

`Actions.refresh({title: "Changed title", data: "Changed data"})}`
