### ISSUE TITLE
Change the navbar Background color Dynamically

### ISSUE THREAD

**Issue by GopiKrishna10** [aksonov/react-native-router-flux#2944]
### Version
Tell us which versions you are using: 

-  "react-native-router-flux": "^4.0.0-beta.28",
-  "react-native": "0.52.0",

HI @Blapi , @aksonov 

I need to change the Navbar Background color with the prop **navigationBarStyle**  Dynamically.  I tried the code like Action.refresh({navigationBarStyle:{backgroundColor:'red'}).but its not reflecting on navbar.How can I change the Background color for nav bar from my component. I don't have much functionality for writing the custom navBar

### Expected behaviour
I Think using this  Action.refresh({navigationBarStyle:{backgroundColor:'red'}) code.Color has to change 

### Actual behaviour
It's not changing the backgroundColor for my screen.

Sorry for bad English.

**Comment by Blapi** [comment]
Not supported

https://github.com/aksonov/react-native-router-flux/issues/2639

**Comment by fcustodiof** [comment]
I found this solution using react navigation

`{this.props.navigation.setParams({headerStyle:{backgroundColor:this.props.vehicle.pinColor}})
