### ISSUE TITLE
Hardware back button is behaving differently in release build and debug build.

### ISSUE THREAD

**Issue by rohitgoyal** [aksonov/react-native-router-flux#2945]
### Version
Tell us which versions you are using: 
    "react-native-router-flux": "4.0.0-beta.27",
    "react-native": "0.51.0",

### Expected behaviour
Android hardware back button should take to previous screen and close the app if there is no route left to go back while running the app in debug/release mode. 

### Actual behaviour
Android hardware back button takes to previous screen and closes the app if there is no route left to go back while running the app in debug mode. But in release mode the android hardware back button is always closing the app.

**Comment by Blapi** [comment]
It's working well on my end, you must have done something wrong in your code.
