### ISSUE TITLE
How to reset <Stack> from Tab on leave

### ISSUE THREAD

**Issue by MagicFlag0x90** [aksonov/react-native-router-flux#2950]
### Version

- react-native-router-flux 4.0.0-beta.28
- react-native v0.53.0

### Code 
 <Router {...DefaultProps.RouterProps} >

         <Scene key="tabbar" tabs={true} showLabel={true}
                hideNavBar={true}
                tabBarPosition="bottom"
                {...DefaultProps.tabProps}
         >

             <Stack   key="one">
                <Scene key="one" component={oneComponent} title="one"
                   icon={() => <Icon name="basket"  {...DefaultProps.icons} />}/>
             </Stack>

             <Stack   key="two" title="two">
               <Scene key="two" component={twoComponent} title="two" icon={() => <Icon name="list-box"  {...DefaultProps.icons} />}/>
               <Scene  back key="two_1" component={twoSubComponent1} icon={() => <Icon name="list-box"  {...DefaultProps.icons} />}/>
               <Scene  back key="two_2" component={twoSubComponent2} icon={() => <Icon name="list-box"  {...DefaultProps.icons} />}/>
             </Stack>

         </Scene>
        </Router>

**Comment by aaron25mt** [comment]
See here #717

**Comment by GuidoSchweizer** [comment]
#717 seems to be unresolved. Non of the workarounds described there worked for me

**Comment by aksonov** [comment]
Please check 4.0.0-beta.41 and Example with `backToInitial` prop
