### ISSUE TITLE
Disable Transition(sliding) animation while navigating between Scenes inside tabs

### ISSUE THREAD

**Issue by RamkumarBPE** [aksonov/react-native-router-flux#2953]
### Version
Tell us which versions you are using:Router Flux -

- react-native-router-flux v4.?.?  4.0.0-beta.24
- react-native v0.?.? 0.53.0

### Expected behaviour
I just want to disable the transition animation.
Ex: when I navigate to a screen "Actions.sceneName()", there is a sliding transition animation from left to right. I just want to disable the sliding transition.

### Actual behaviour
Transition happens like sliding Door, when navigating between scenes.I tried using direction=vertical. It works in Android, but in iOS it is not working.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Open app
2. Navigate to any new Scene (Actions.SceneName())
3. Loot at the transition behaviour

**Comment by Blapi** [comment]
#2628
