### ISSUE TITLE
Actions.refs.SCREEN_NAME doesn't work

### ISSUE THREAD

**Issue by Royalone-mobile** [aksonov/react-native-router-flux#2958]
I can see this message Actions.refs is undefined;
I want to toggle menu in home screen in app.js where i defined routers.
so I have to call component's method but i can't.
I want to hear your opinion

**Comment by Blapi** [comment]
What are you doing exactly ? Have you cheched the example project to know how to use this library??

**Comment by Royalone-mobile** [comment]
Yes, of course.
Do you have experience really how to do like my way?

**Comment by Blapi** [comment]
No because I don't see the point of using refs on Action. And this might not be defined in Actions.

**Comment by Royalone-mobile** [comment]
Nope, You need to google before answer my question.
since I had seen it is working in previous version when I first implement it.
but After adding some packages and modified code, it doesn't work.
and i have no that version code so I wanted to get help.

**Comment by Blapi** [comment]
You've asked on StackOverflow and somebody replied. I will not do your researches for you. I'm here to help you using this library and I asked you more details, which you didn't.

What you could do is :

- Either using a HOC
- Either using Redux to pass the same method in your components
- Either using your method as a prop and doing the trick in this way

There's a large amount of ways of doing what you want. You don't need Actions.refs to do that, which includes there is no need to open an issue on this library, so, YOU HAVE TO DO THE RESEARCHES.

Closing this.
