### ISSUE TITLE
how pass data from component to title

### ISSUE THREAD

**Issue by blackinitial** [aksonov/react-native-router-flux#2959]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.6.1
- react-native v0.52.2

### Expected behaviour
how to make title like picture, with place and date dynamic from component . catch data from scene component to title router ??

![title](https://imgur.com/wxz3qP3.png)

thanks

**Comment by Blapi** [comment]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md

Scene


renderTitle | React.Component |   | React component to render title for nav bar
-- | -- | -- | --

**Comment by blackinitial** [comment]
ok, solved.
I use Actions.scene({ params: valueHere })

**Comment by igorsantos07** [comment]
Not sure if `renderTitle` solves this matter, but it was mentioned by OP - even though he solved in another way... Is it possible to set the title dynamically, from inside the Scene's component? E.g. my component's title is based on a field of a prop it receives.
