### ISSUE TITLE
Actions.replace () not working on beta 28 version

### ISSUE THREAD

**Issue by SandeshBG** [aksonov/react-native-router-flux#2962]
- react-native-router-flux v4.0.0-beta.28
- react-native v0.54.2

Calling Actions.key({type:'replace',props:'props'})  or Actions.replace({sceneKey:'key',props:'props'}) is supposed to pop the current scene from the stack and pushes the new scene to the navigation stack. But it is not changing or moving to new scene. If I pass the scenekey without parameters, it's working fine. I downgraded the version to 25 which I had previously used in some other project. After downgrading it's working. So this is the issue in latest version.

**Comment by NSShentu** [comment]
sure , i  find the problem , too.   So, how to deal it

**Comment by NSShentu** [comment]
evaluating 'resetAction.actions.map' , undefined is not an object~~~~~

**Comment by Blapi** [comment]
This is a known issue, .27 is more stable

**Comment by guanbiao33** [comment]
the same，did you fixed it？thank you

**Comment by mjstelly** [comment]
@Blapi I downgraded from `.28` to `.27`. The app crashes at launch now. So, I don't think that's a viable solution.

**Comment by Blapi** [comment]
Works fine for me, are you sure it really is .27 and that you did nothing wrong in your package.json ?

**Comment by NSShentu** [comment]
@Blapi  i  update .28 for Actions.popTo  can be used normally
However .28  Actions.replace is broken
Can you give me a solution ehhhhhhhhhhhhhhhh

**Comment by Blapi** [comment]
@NSShentu can you show me your package.json when you're on .27 please? As I said, it's working fine on my app with .27

**Comment by NSShentu** [comment]
@Blapi 
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-router-flux": "4.0.0-beta.27",
    "react-navigation": "1.0.0-beta.21",

replace function is ok
when in several same page case，popTo function is broken.
whether my package.json is some wrong?

**Comment by MaxInMoon** [comment]
Actions.replace works with **4.0.0-beta.31**
