### ISSUE TITLE
Tabs can't hide navbar

### ISSUE THREAD

**Issue by blackinitial** [aksonov/react-native-router-flux#2964]
How to make tabs pretty and hide nav under tabs, i use tabs but like this

![gambar](https://imgur.com/aSNY5kt.png)

this my code: 
```js
<Tabs 
    key="tab_report" title="History" hideNavBar={false} back
    navigationBarStyle={{ backgroundColor: '#344147' }} navBarButtonColor="#fff"
    renderRightButton={more} onRight={() => console.log('more')}
 >
  <Stack key="report_booking_airline_tab" tabBarLabel="Booking">
    <Scene
       key="report_booking_airline" component={ReportBookingAirline}
     />
  </Stack>
  <Stack key="report_issued_airline_tab" tabBarLabel="Issued">
     <Scene
        key="report_issued_airline" component={ReportBookingAirline}
      />
  </Stack>
</Tabs>
```

**Comment by aaron25mt** [comment]
Try changing `<Tabs hideNavBar={false}>` to `<Tabs hideNavBar={true}>` and then add `hideNavBar={false}` to each scene. I think that'll work.. a little repetitive but it's what I'm doing for now.

**Comment by blackinitial** [comment]
@aaron25mt Thanks for your reply, i was do it but the top nav goes missing.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
