### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: undefined is not an object (evaluating 'resetAction.actions.map')

### ISSUE THREAD

**Issue by NSShentu** [aksonov/react-native-router-flux#2965]
When i do a replace action. Such as: Actions.replace('HomePage');

yellowbox show: Possible Unhandled Promise Rejection (id: 0): TypeError: undefined is not an object (evaluating 'resetAction.actions.map').

And the screen still show current router.

My package detail:
    "react-native-router-flux": "^4.0.0-beta.26",
    "react-navigation": "^1.0.0-beta.22",
    "react": "16.0.0",
    "react-native": "0.51.0",

**Comment by Blapi** [comment]
There's already a lot of issues about this, did you even check ???

Upgrade to .27.
