### ISSUE TITLE
Drawer and tabs slide conflict.

### ISSUE THREAD

**Issue by QingYong** [aksonov/react-native-router-flux#2966]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.27
- react-native v0.51.0

### Expected behaviour
At the page of 'drawer',When slide from left(out of the screen) side of the screen into the right side.
The drawer was slide out, not the tabs move to the right side with a white space.

### Actual behaviour
At the page of 'drawer' ,When slide from left (out of the screen) into the screen,Sometimes drawer was slide out  and sometimes the tabs was slide to the right side with a white space.

What should I do to disable tabs' left slide.
### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
![1edb7261-3746-4812-b66f-327b6344d5c0](https://user-images.githubusercontent.com/5309786/37979645-ac7f0d3a-321b-11e8-8ce3-1c3c948104d6.png)
![9b0bbabf-6fe7-459c-8b32-521e635c4b80](https://user-images.githubusercontent.com/5309786/37979646-acf8c49a-321b-11e8-8222-c27c6c78f6c0.png)

👉  https://opencollective.com/react-native-router-flux/donate -->

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
