### ISSUE TITLE
push multi Modal doesn't work

### ISSUE THREAD

**Issue by fatfatson** [aksonov/react-native-router-flux#2968]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.54.0

### Expected behaviour
push multi Modal(or LightBox), they should overlay from old to new.

### Actual behaviour
only the latest one exist, all others are unmounted.

**Comment by aksonov** [comment]
It is how it was designed. Feel free to submit PR for improved/desired functionality
