### ISSUE TITLE
Drawer Always show on iPad or tablet ?

### ISSUE THREAD

**Issue by Q8hma** [aksonov/react-native-router-flux#2971]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.(last ver)
- react-native v0.54.0 (last ver)
****** I’m sorry I’m on mobile and I dont know the ver for both of them but I just install both of them and I remember I see beta ver for both of them

I don’t have problem but I want to ask how can I make the Drawer always show on iPad version??

Like other app have Drawer on the page all the time

Thnx and I’m very sorry because my English not good and I hop I clean my ask 

Thnx

**Comment by aksonov** [comment]
Sorry, it is not supported
