### ISSUE TITLE
Parent scene with no component generates "ghost" screen?

### ISSUE THREAD

**Issue by igorsantos07** [aksonov/react-native-router-flux#2972]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28 (v3 is not supported)
- react-native v0.54.3

### Expected behaviour
a parent scene without a component should not render a navbar, as it's a simple container to group scenes. If that's not correct, please create a new component (e.g. `<SceneGroup>`) for that matter.

The [`<Modal>` example](https://github.com/igorsantos07/react-native-router-flux/blob/patch-1/docs/API.md#modals-modal-or-scene-modal) doesn't work as expected because of this behaviour.

### Actual behaviour
A single navbar should be rendered, only on Scenes with components.

### Steps to reproduce
```jsx
<Router>
  <Modal>
    <Scene key="root"> {/* this will generate a navbar, unless we use hideNavBar */}
      {/* thus, the inner screens won't get a navbar unless we use hideNavBar=false */}
      {/* which is ugly and boring across many screens */}
      <Scene key="login" component={LoginScreen}/>
      <Scene key="blabla" component={BlablaScreen}/>
      {/* if left this way, the final result will present two navbars */}
    </Scene>
    <Scene key="modal" component={MyModal}/>
  </Modal>
</Router>
```

**Comment by aksonov** [comment]
Please make `Modal` as top level component. Feel free to re-open if it doesn't help
