### ISSUE TITLE
problem with Actions.pop ,, send me to initial Scene

### ISSUE THREAD

**Issue by Q8hma** [aksonov/react-native-router-flux#2975]
### Version
- react-native-router-flux v4.0.0-beta.28
- react-native v0.54.3

the problem when im on Scene 5 and i used "Actions.pop" send me to Scene 1 

the steps
Scene 1 > 2 > 3 > 4 > 5 (when i use "Actions.pop" it must push me back to Scene 4 but it send me to the first Scene)

thnx and sorry if i add wrong issues and make new one and so sorry for my bad english

**Comment by asciifaceman** [comment]
Can you give your code examples? 

`Actions.pop()` will only work if you were using `Actions.push()` to add new views, if you are using `replace` for example it clears the routing stack.

Also IOS or Android as their "back" functionality is different.

**Comment by Q8hma** [comment]
i used action.SceneName
i test it on ios not android

**Comment by drailanjohngss** [comment]
im also experiencing this problem.

**Comment by Blapi** [comment]
You might have replace the navigation stack at a moment, Actions.pop works just fine, the issue is in your code, not in the library.

Have a look at the example project, the best practices and the solution for your problems will be there.

Moreover, check your navigation stack by doing this : 

```
const reducerCreate = (params) => {
  const defaultReducer = new Reducer(params)
  return (state, action) => {
    console.log('Action :', action)
    console.log('State :', state)
    return defaultReducer(state, action)
  }
}

...
...

<Router createReducer={reducerCreate}>
```

You will have the best overview to see what's wrong.

**Comment by Q8hma** [comment]
thnx alot and i fix it by move Drawer over (<Scene key="root" hideNavBar>)
new code :
`
      <Router hideNavBar= "true" createReducer={reducerCreate}>
<Drawer key="drawer" contentComponent={DrawerContent} drawerWidth={250} hideNavBar>
        <Scene key="root" hideNavBar>
          <Scene key="home_page"  component={home_page}  title="home_page" initial={true} hideNavBar/>
          <Scene key="search_page"  component={search_page}  title="search_page" hideNavBar/>
          <Scene key="cats_page"  component={cats_page}  title="cats_page" hideNavBar/>
          <Scene key="tops_page"  component={tops_page}  title="tops_page" hideNavBar/>
          <Scene key="sound_page"  component={sound_page}  title="sound_page" hideNavBar />
          <Scene key="sounds_page"  component={sounds_page}  title="sounds_page" hideNavBar />
          <Scene key="aboutus_page"  component={aboutus_page}  title="aboutus_page" hideNavBar />
        </Scene>
</Drawer>
      </Router>`

old code :
`
      <Router hideNavBar= "true" createReducer={reducerCreate}>
        <Scene key="root" hideNavBar>
<Drawer key="drawer" contentComponent={DrawerContent} drawerWidth={250} hideNavBar>
          <Scene key="home_page"  component={home_page}  title="home_page" initial={true} hideNavBar/>
          <Scene key="search_page"  component={search_page}  title="search_page" hideNavBar/>
          <Scene key="cats_page"  component={cats_page}  title="cats_page" hideNavBar/>
          <Scene key="tops_page"  component={tops_page}  title="tops_page" hideNavBar/>
          <Scene key="sound_page"  component={sound_page}  title="sound_page" hideNavBar />
          <Scene key="sounds_page"  component={sounds_page}  title="sounds_page" hideNavBar />
          <Scene key="aboutus_page"  component={aboutus_page}  title="aboutus_page" hideNavBar />
</Drawer>
        </Scene>
      </Router>`

thnx alot u help me

**Comment by jeff63115** [comment]
This helped me. Thank you!
