### ISSUE TITLE
Examples Broken

### ISSUE THREAD

**Issue by duro** [aksonov/react-native-router-flux#2976]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.30

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 1.3.2
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2

### Expected behaviour

Following example steps should successfully build example locally

### Actual behaviour

I get this error in simulator

![iphone_6_-_ios_11_1](https://user-images.githubusercontent.com/17632/38157379-38c3f6ea-343b-11e8-866e-ce00f5179c36.jpg)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

```
# Get the code
git clone https://github.com/aksonov/react-native-router-flux.git
cd react-native-router-flux/Example

# Install dependencies
yarn

# Run it
react-native run-ios
```

**Comment by asciifaceman** [comment]
There is unfortunately some crazy things going on upstream, https://github.com/react-navigation/react-navigation/issues/3416


To get you going, and just for my own curiosity, can you try to uninstall the react-native-router-flux package in the project and then install the version pinned `4.0.0-beta.28` or `4.0.0-beta.22`

**Comment by IronTony** [comment]
Tried with `4.0.0-beta.28` and it works

**Comment by aksonov** [comment]
4.0.0-beta.31 fixes it as well
