### ISSUE TITLE
the example code is still v3?

### ISSUE THREAD

**Issue by Tomatoo** [aksonov/react-native-router-flux#2977]
in [example](https://github.com/aksonov/react-native-router-flux/tree/master/Example), i found Router componment has a 'createReducer' prop, but i cannot find createReducer in [v4 api doc](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md), and i cannot find 'Overlay' componment in v4 doc. 

so, the example code is still v3?

**Comment by asciifaceman** [comment]
createReducer is largely for REDUX integration, and the Example is meant to be more of a documentation on how to create a reducer. The prop isn't super well documented outside of that.
