### ISSUE TITLE
getCurrentRoutes api in v4?

### ISSUE THREAD

**Issue by Tomatoo** [aksonov/react-native-router-flux#2978]
how can i get all route in current route stack in v4? i find some talk about [Actions.currentRouter](https://github.com/aksonov/react-native-router-flux/issues/101), but i cannot find about currentRouter code in v4 source code.

**Comment by asciifaceman** [comment]
Ah crap I thought I had a code example for this, digging around still...

**Comment by Tomatoo** [comment]
i use react native's own navigator now(version 0.39), it has a api called [getcurrentroutes](https://facebook.github.io/react-native/docs/0.36/navigator.html#getcurrentroutes), this can get a list include all pushed routes, and i cannot found a similar api in rnrf.

**Comment by aksonov** [comment]
@fatfatson is correct.

**Comment by matteocollina** [comment]
But Can i get the Stack size?

**Comment by daviscabral** [comment]
@matteocollina have you looked at the state object as pointed above? you can get the idea of the stack size by that.

This is a sample that I got by running the tests from the project:
```json
{
  "key": "StackRouterRoot",
  "isTransitioning": false,
  "index": 0,
  "routes": [
    {
      "key": "id-1537858201424-3",
      "isTransitioning": true,
      "index": 1,
      "routes": [
        {
          "params": {
            "init": true,
            "param": "1"
          },
          "routeName": "a",
          "key": "id-1537858201424-2"
        },
        {
          "params": {
            "error": "",
            "param": "2",
            "init": true,
            "data": "abcde",
            "routeName": "c"
          },
          "routeName": "c",
          "key": "id-1537858201424-4"
        }
      ],
      "params": {
        "init": true
      },
      "routeName": "b"
    }
  ]
}
```
