### ISSUE TITLE
Calling the same modal component twice throws error on .dismiss()

### ISSUE THREAD

**Issue by crockpotveggies** [aksonov/react-native-router-flux#298]
Here's what my routing tree looks at its simplest:

```
<Router>
  <Route name="errorModal" type="modal" component={ErrorModal}/>
  <Route name="mainScreen" initial={!needSignIn}>
    .. tab bar stuff ...
  </Route>
  <Route name="Login" initial={needSignIn} component={LoginScreen}/>
</Router>
```

Whenever an error happens within the app, I usually call `Actions.errorModal({message: 'bad'})`. However, during testing I noticed if I call that modal, then `Actions.dismiss()` and immediately afterwards call the error modal again then `Actions.dismiss()` a second time, the modal will not dismiss. Then, if I try to navigate to another part of the app, the app will crash with the following error:

![screen shot 2016-03-08 at 3 51 49 pm](https://cloud.githubusercontent.com/assets/1445295/13620582/b8cbcfd0-e545-11e5-816c-113385f9923a.png)

It looks like there's an error with resetting the route stack when calling `dismiss()` and the router can't handle a second modal being called immediately thereafter (with no other navigation). Is this a bug or am I not properly using modals?

**Comment by aksonov** [comment]
It is wrong use case - modal should not be called twice, prevent it from your code.

**Comment by crockpotveggies** [comment]
@aksonov can you elaborate a little more? What if there are two errors in a row (for instance, we start having API troubles and multiple requests fail?)

**Comment by aksonov** [comment]
Should be fixed for 3.0 release

**Comment by crockpotveggies** [comment]
Thanks for the update. Anything I can do to help with the release?

**Comment by aksonov** [comment]
You may check how it works. I didn't test it with several popups yet.

**Comment by aksonov** [comment]
And 3.0 is not backward compatible...

**Comment by crockpotveggies** [comment]
Yep just saw the breaking changes. Let me put together a fork of our mobile repo later tonight and I'll start testing it out :)

**Comment by aksonov** [comment]
I'm closing it for now
