### ISSUE TITLE
Icons for Tabs not showing on React Native 0.54.4

### ISSUE THREAD

**Issue by FacuAcosta** [aksonov/react-native-router-flux#2981]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 
- react-native v0.54.4

### Expected behaviour

I was using React Native 0.52.3 and custom tab icons were working as expected, as you can see in the image but once i updated React Native to the latest version they stopped working with no changes applied to the code or anything

![screen shot 2018-04-03 at 12 18 54](https://user-images.githubusercontent.com/19332669/38246325-548ca074-3739-11e8-813c-d4e44817b0ad.png)

```
<Scene
     key="activity"
     tabBarLabel="Activity"
     gesturesEnabled={false}
     hideNavBar
     component={ActivityScreen}
     icon={({ focused }) => (
     <Icon
        name={focused ? 'activity-active' : 'activity'}
        size={30}
        color={focused ? '#FFC920' : '#353535'}
      />
      )}
/>
```

### Actual behaviour

The Icons are missing from the tab but the onPress behaviour works. It's not a problem with the icons library because they are shown in the whole app apart from the tab bar.

![screen shot 2018-04-03 at 12 19 43](https://user-images.githubusercontent.com/19332669/38246398-9245d9a8-3739-11e8-972f-894ded474a24.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Update to RN 0.54.4
2. Use custom Icon on the bar with react-native-vector-icons library
3. Check that the icons are not showing

### Update
I managed to fix the issue, It seems like for some reason you need to add the width to the style of the Icon and it will be shown again.

![screen shot 2018-04-03 at 12 36 32](https://user-images.githubusercontent.com/19332669/38247026-a98a0b14-373b-11e8-8850-7439282e57ec.png)

```
icon={({ focused }) => (
    <Icon
       style={{ width: 30 }}
       name={focused ? 'profile-active' : 'profile'}
       size={30}
       color={focused ? '#FFC920' : '#353535'}
    />
)}
```

**Comment by MaxInMoon** [comment]
@FacuAcosta thanks for the fix which also fixes with react-native@0.55.0

**Comment by eddiesigner** [comment]
In my case I had to set the height as well (react-native@0.54.4)

**Comment by dwilt** [comment]
It makes `<Text>` invisible too. You need to wrap a `<View>` around the `<Text>` and give it a width and height.
