### ISSUE TITLE
Using default and custom NavBar together

### ISSUE THREAD

**Issue by Carlosarturo28** [aksonov/react-native-router-flux#2982]
### Version

- react-native v4.0.0-beta.28

### Expected behaviour

Custom navBar and the default RNRF working together in my Scenes.

### Actual behaviour

I need a BottomNavigation and a TopNavigator. The TopNavigator is handled very well with RNRF but 
the bottomNav is not, so I'm using [this component](https://github.com/timomeh/react-native-material-bottom-navigation). I'm using it in my Router this way: ```<Stack key="root" navBar={BottomMenu}>```. The problem is that when I use this, the BottomMenu component works very well, but the default navigator (the top one with title, and left/right buttons) disappears from the screen.

I wonder if there is a way to use the default navigation with a custom one (I really hope there is a way haha)

**Comment by aksonov** [comment]
Sorry, it is not supported
