### ISSUE TITLE
Chaneg Event for Tabs click

### ISSUE THREAD

**Issue by GopiKrishna10** [aksonov/react-native-router-flux#2986]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported) - "^4.0.0-beta.28"
- react-native v0.?.?  - "0.52.0

**Tabs Navigation**
### Steps to reproduce
I have Three tabs
like Home,Search,Settings 

In Home Tab
    - homeScreen
    - SectionOne
    - SectionTwo

In Search Tab
   - SearchScreen

In Settings Tab
   - A
   - B
   - C
### Issue is
Here the issue when I click on **Home Tab** it redirects to  **homeScreen** then clicked on item in **homeScreen** it redirects to **SectionOne**.Then I  click on **Search Tab**.it redirects to **SearchScreen**.Then again Click on **Home Tab**.it redirects to **SectionOne** Scene(Actually i need to redirect **homeScreen** ).And am not using Redux Guys
![simulator screen shot - iphone 6s - 2018-04-09 at 21 32 52](https://user-images.githubusercontent.com/15904913/38508943-197e8e5c-3c3e-11e8-9b3f-c17f5a13ff8c.png)

Could you please help Me guys @Blapi @aksonov  . and Sorry for bad English

**Comment by aksonov** [comment]
Sorry, it is not supported
