### ISSUE TITLE
onEnter not always fired

### ISSUE THREAD

**Issue by Jerameel** [aksonov/react-native-router-flux#2987]
### Version
v4.0.0-beta.28
0.44.2

### Expected behaviour

onEnter should be called everytime i switch tab

### Actual behaviour

gets called first, but not everytime

**Comment by aksonov** [comment]
Please give me more details and reopen the ticket if any. It may not called if you have stack inside your tab

**Comment by mightym** [comment]
@aksonov Does this mean `onEnter` is never called inside any scene inside tabs? 

I have this setup:
```
                  <Tabs key='tabbar'>
                    <Stack key='tab_1'>
                      <Scene key='home'
                             component={HomeView}/>
                    </Stack>
                    <Stack key='tab_2'>
                     <Scene key='start_create'
                            component={HomeCreateView}/>
                    </Stack>
                  </Tabs>
```
and basically in ever Scene 
```
  static onEnter() {
    console.log('On Enter')
  };
```
gets not fired.
