### ISSUE TITLE
Feature request - A method for printing header beneath navigation bar

### ISSUE THREAD

**Issue by thessem** [aksonov/react-native-router-flux#299]
Currently the header option prints the header above any navigation bar, I would like an additional field so that I can print something beneath the navigation bar but above the Component. I would be using this for a top TabBar

**Comment by aksonov** [comment]
I don't understand the problem - it is all about css styling. did you try to use paddingTop or top ?

**Comment by thessem** [comment]
Thanks for your response, I'll try to be a little more specific

I want to be able to have a list of tabs in a view which is accessed by a list of tabs. For example:
```javascript
<Route footer={TabBar} tabBarStyle={tabStyles.tabBarStyle}>
    <Route name="Tab_A" schema="tab" title="Tab A">
        <Route header={TopTabBar} name='Tab_A Content' title='TabAContent'>
            <Router>
                <Route name='Tab_A1' schema="tab" component={TabAContent}/>
                <Route name='Tab_A2' schema="tab" component={TabAContent}/>
            </Router>
        <Route/>
    </Route>
    <Route name="Tab_B" schema="tab" component={TabBContent}\>
</Router>
```
So that I can select between Tab_A/Tab_B using the built in TabBar component, but when I am in Tab_A I have a second TabBar at the top and can select between TabA1 and TabA2 within it. Right now as written if I use `footer` for the second one it messes with the one there already, and `header` prints above the navigation bar, I'd love an additional setting called `top` or something better than that so I can easily throw my second tab bar at the top of the content using the built in infrastructure in this package.

As it is, I've implemented this by manually putting in a TabBar in TabAContent with the appropriate calls to switch routes, but I'd love to be able to specify this in the actual route itself.

I'd love if there was some way of placing the `header` stuff below the navbar, I'm just starting out with react native so it's likely I've missed something obvious here.

**Comment by aksonov** [comment]
Sorry, but it is not the component issue.
