### ISSUE TITLE
how to make a custome style Scene component?

### ISSUE THREAD

**Issue by felixzxk** [aksonov/react-native-router-flux#2990]
### Version
- react-native-router-flux version: '4.0.0-beta.28'
- react-native version: '0.55.2',

### Expected behaviour
```
import {Scene} from 'rect-native-router-flux';
const sceneStyle = {
  navigationBarStyle: {
    height: 44
  },
  titleStyle: {
    fontSize: 16,
    fontWeight: '100'
  }
}
export const MyScene = props => <Scene {...sceneStyle } {...props} />
```

and then at where I want to user MyScene
```
<MyScene {...someProps}  />
```

### Actual behaviour
MyScene works, but sceneStyle does not work

**Comment by aksonov** [comment]
Please check Example project for details how to define sceneStyle - you must define `sceneStyle` key for the scene style like you did for `titleStyle`, etc.
```
const sceneStyle = {
  navigationBarStyle: {
    height: 44
  },
sceneStyle: {
   backgroundColor: 'red'
},
  titleStyle: {
    fontSize: 16,
    fontWeight: '100'
  }
}
```
