### ISSUE TITLE
<Tabs>Properties passing to children <Scene>'s

### ISSUE THREAD

**Issue by VilleKokkarinen** [aksonov/react-native-router-flux#2991]
### Version
- react-native-router-flux v4.0.0-beta.26
- react-native v0.54.2

### Expected behaviour
Expecting props being passed to the `<Tabs>` to inherit to all of it's children `<Scene>`'s

- via Actions.jump("Tabs", {property: data} )

### Actual behaviour

Only the first scene inside `<Tabs>` received props, the rest were not so lucky.

#### 1. 

- 2 or more Scene's inside a <Tabs> component
```

  <Tabs key="tabs tabBarPosition={'bottom'} >
  <Scene key="Page1" component={Page1} title="Page1" onLeft={Actions.pop} />  
  <Scene key="Page2" component={Page2} title="Page2" onLeft={Actions.pop} /> 
  </Tabs> 

```

#### 2.  

Navigating to the Tabs
`
Actions.jump("tabs", { property:this.state.data } )  
`

#### 3.
Only Page 1 received props named "property".

##### Though

Solved for the meanwhile by just Actions.Jump(ing) with the props, to every page that needs them

**Comment by aksonov** [comment]
Correct, it is not supported functionality, PR is welcome.

**Comment by anuj002** [comment]
Yes! I found the problem in 'Tab'.
Tabs are 'wrapped' by default - i.e. all children are wrapped by Stack with own nav bar. You may disable wrapping by using wrap={false} for Tabs and check passing props again.

`<Scene key="Scene" tabs={true} wrap={false}> <Scene key="someTab" component={SomeTab} title="SomeTab" icon={TabIcon}/> <Scene key="Modal" component={Modal} title="Modal" hideNavBar direction="vertical"/> </Scene>`

Here props are find when passing from someTab to Modal via Actions.Modal({someProp: theProp})
