### ISSUE TITLE
Removing multiple screens from stack

### ISSUE THREAD

**Issue by dentsmokaliuk** [aksonov/react-native-router-flux#2992]
### Version
- react-native-router-flux 4.0.0-beta.14
- react-native v0.46.4

### Expected behaviour
Is it possible remove from stack some screens with the same name? 
For example, my screens:
**ScreenA -> ScreenB -> ScreenC -> ScreenA -> ScreenD** 
and i would like to receive the next stack without **ScreenA**:
**ScreenB -> ScreenC -> ScreenD**

**Comment by AlexDM0** [comment]
I have a similar issue.

ScreenA -> ScreenB -> ScreenC -> ScreenD

I'd like a normal transition between ScreenC and ScreenD, then back from ScreenD should be ScreenA.

What is the best way to do this? I'd need to pop ScreenB and ScreenC when the transition to D is completed?

**Comment by AlexDM0** [comment]
I solved this by changing the reducer you pass to Router.createReducer

```js

export const reducerCreate = (params) => {
  const defaultReducer = Reducer(params, {});
  return (state, action)=>{
    if (action && action.type == "REACT_NATIVE_ROUTER_FLUX_PUSH") {
      if (action.params && action.params.__popBeforeAddCount) {
        let newState = {...state};
        for (let i = 0; i < action.params.__popBeforeAddCount; i++) {
          newState.routes.pop();
          newState.index -= 1;
        }
        return defaultReducer(newState, action);
      }
    }
    return defaultReducer(state, action);
  }
};
```

I added a custom field to the action params `__popBeforeAddCount` which I filter for in the reducer (yes, that IS a little ugly ;)). If this is the case I pop a few items off the routing stack before continuing. Similarly, when you'd want to remove screenA from the stack, you can change the stack in the reducer you provide.

Hope it helps!
