### ISSUE TITLE
Actions.replace have a problem

### ISSUE THREAD

**Issue by guanbiao33** [aksonov/react-native-router-flux#2993]
### Version
Tell us which versions you are using: 

"react": "16.3.1",
"react-native": "0.55.2",
"react-native-router-flux": "^4.0.0-beta.27",

### Actual behaviour

undefined is not an object (evaluating 'resetAction.actions.map')

**Comment by riwu** [comment]
Change to `"react-native-router-flux": "4.0.0-beta.27"` (remove `^`) otherwise your package manager will still install the `.28` version.

**Comment by Sharcoux** [comment]
Related to [this issue](https://github.com/aksonov/react-native-router-flux/issues/2799)

**Comment by afilp** [comment]
I believe this is not fixed in 4.0.6. I have problems with the REPLACE.
