### ISSUE TITLE
Android hardware return key sometimes does not work

### ISSUE THREAD

**Issue by zc-Mukden** [aksonov/react-native-router-flux#2995]
I tried to override ''BackHandler.addEventListener()'' to listener, but listening will not be called.....This is only sometimes the case, but the chances of it appearing are also high. Is that why?
"react-navigation": "^1.2.1",
"react-native-router-flux": "^4.0.0-beta.28",

**Comment by Blapi** [comment]
Never had the issue while doing it, and this is not related to this library.
