### ISSUE TITLE
Why reducer isn't called on initial screen?

### ISSUE THREAD

**Issue by qmegas** [aksonov/react-native-router-flux#2996]
Hi,
I use custom reducer function provided through `createReducer` prop in `Router`. It works fine when I push/pop screens, but it doesn't called when showing initial screen. Why?
In order to be consistent library should call reducer on pushing first screen too.

Library version: 4.0.0-beta.28
RN version: 0.54.4

**Comment by digitaldavenyc** [comment]
@qmegas can you post a code example?

**Comment by qmegas** [comment]
@digitaldavenyc Unfortunately one month have passed, so I had to move back to version 3.x, thus I have no example code.

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
