### ISSUE TITLE
How to make 2 tabs in the same Scene?

### ISSUE THREAD

**Issue by Rafazeon** [aksonov/react-native-router-flux#2997]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.27
- react-native 0.55.2

Hi everyone, I need help putting 2 tabs together in the same scene, how can I do this has some other way?
![filter](https://user-images.githubusercontent.com/16168129/38779386-f5580332-409d-11e8-8e3d-312dfa58d70a.png)

**Comment by aksonov** [comment]
Not enough information. Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
