### ISSUE TITLE
Error: Route 'scarlet' should declare a screen. For example:  import MyScreen from './MyScreen'; ... scarlet: {   screen: MyScreen, }

### ISSUE THREAD

**Issue by AzizUrRehman1** [aksonov/react-native-router-flux#3001]
import React, { Component } from 'react';
import {
  StyleSheet,
} from 'react-native';
import { Router, Scene } from 'react-native-router-flux';

import ScarletScreen from './app/ScarletScreen';
import GrayScreen from './app/GrayScreen';

const App = () => {
    return (
      <Router> 
        <Scene key="root">
          
          
          <Scene 
            
            key="scarlet"
            Component={ScarletScreen}
            title="Scarlet"
            initial
          />
        
        <Scene 
            key="gray"
            Component={GrayScreen}
            title="Gray"
          />

        </Scene>
      </Router>

    );
  }

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },

});
export default App;

**Comment by Blapi** [comment]
component | React.Component | semi-required | The Component to be displayed. Not required when defining a nested Scene, see example.
-- | -- | -- | --


It is component with a lowercased c

**Comment by AzizUrRehman1** [comment]
it' not work

**Comment by Blapi** [comment]
Show you ScarletScreen component code please
