### ISSUE TITLE
Switch/selector equivalent for v4

### ISSUE THREAD

**Issue by tmaly1980** [aksonov/react-native-router-flux#3003]
I've got the most recent RNRF 4.0.0.beta-28 , and migrating from v3 . The docs say that Switch is deprecated, but what is an example for v4 that does the same effect? For example this is v3:

```
<Scene
  hideNavBar={true}
  key="root"
  tabs={true}
  title="Main"
  component={connect(state=>({auth:state.auth, app:state.app}))(Switch)}
  selector={props=>!props.app.persisted ? "wait" : props.auth.token ? "loggedIn" : "auth"}
>
```

Basically, if redux has app.persisted truthy, show 'wait', otherwise show 'loggedIn' if auth.token is set, otherwise default to 'auth'.

The migration does says "Switch is removed - you may use onEnter/onExit handlers for more flexible logic." - but I don't see any examples, not even in the example app.

How do I rewrite this to work with v4?

**Comment by sofwu** [comment]
+1

**Comment by aksonov** [comment]
`on`, `success`, `failure` is v4 equivalent for v3 switch. Please check https://github.com/aksonov/react-native-starter-app as the example
