### ISSUE TITLE
Cannot pass params to screens on navigate

### ISSUE THREAD

**Issue by FrenchMajesty** [aksonov/react-native-router-flux#3005]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28 (v3 is not supported)
- react-native v0.52.0

### Expected behaviour

For the app to navigate to the new screen with the params as props.

### Actual behaviour

Error code `undefined is not a function (evaluating '_this2[type](routeName, res)')`

![image](https://user-images.githubusercontent.com/24761660/39087283-694b83ca-4564-11e8-949f-4187e267e99f.png)

### Steps to reproduce

The code for my router looks like this:

```
<Scene
	key="Filters"
	component={Filters}
	hideNavBar
/>

<Scene
	key="FiltersList"
	component={FiltersList}
	hideNavBar
/>

```
In my Filters screen, I want to navigate to the FiltersList and pass props but I get the error code I mentioned.

This is what my action looks like:

```
<ListItem
 	icon
 	button={true}
 	onPress={() => Actions.FiltersList({type: 'controller'})}
/>
 	<Body>
		<Text>Controllers</Text>
	</Body>
 	<Right>
 		<Icon name="ios-arrow-forward" />
 	</Right>
</ListItem>
```

Whenever I **remove the params**, then the app navigates to FiltersList without a problem but if I try to add the params I need then my app crash.

Any solutions around this problem?

**Comment by FrenchMajesty** [comment]
If anybody had this issue, please use the `react-navigation` API that is provided in this package.

I wasn't really sure about what the documentation meant when it mentions the API... I guess for people familiar with the package there wouldn't be any need to mention it but the react-navigation API is accessible from Actions object. 

Something along the lines of:

```
import { Actions } from 'react-native-router-flux';

Actions.push('FiltersList', {type: 'controller'});
```

**Comment by Blapi** [comment]
It is because `type` is a prop already used in this library (i.e. `reset`, `refresh` etc..), this is why it was not working.

A quick look at the API would have helped you.

**Comment by d7laungani** [comment]
Same @kholiavko-roman did you end up finding a solution?

**Comment by kholiavko-roman** [comment]
@d7laungani, I did like this:
`Actions.settings({ title: 'settings title' });`
And when defined all routes of the app, you need set some default value for this params:
`<Scene title='my page' />`

**Comment by arthedza** [comment]
> It is because `type` is a prop already used in this library (i.e. `reset`, `refresh` etc..), this is why it was not working.
> 
> A quick look at the API would have helped you.

I confirm this.
