### ISSUE TITLE
Example app doesnt run

### ISSUE THREAD

**Issue by ranadeep47** [aksonov/react-native-router-flux#3006]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "4.0.0-beta.30"

### Expected behaviour
The example app should run fine

### Actual behaviour
I ran `yarn install` and `react-native run-android` inside the `Examples` folder and the app fails with an error
![image](https://i.imgur.com/2nwNRMT.png)

**Comment by serjek** [comment]
please see https://github.com/aksonov/react-native-router-flux/issues/2976

**Comment by aksonov** [comment]
4.0.0-beta.31 fixes it, please check latest Example
