### ISSUE TITLE
Can't refresh renderBackButton

### ISSUE THREAD

**Issue by schlaegerz** [aksonov/react-native-router-flux#3010]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0=beta.27
- react-native v0.54.2

### Expected behaviour
Able to refresh backbutton/leftButton

### Actual behaviour
Refresh does nothing, unless I pass in null

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Load scene
2. On button press try Actions.resresh({renderBackButton: ()=>{return <View />})
3. Still old back button

**Comment by midas-gufei** [comment]
PageA
componentWillReceiveProps ()  {
  this.onRefresh()
 }

PageB
Actions.pop({refresh: {}});

**Comment by aksonov** [comment]
Sorry, it is not supported. Instead define your logic _inside_ `renderBackButton` function
