### ISSUE TITLE
what function be execute,when navigationIcon onClick?

### ISSUE THREAD

**Issue by MackYang** [aksonov/react-native-router-flux#3011]
### Version
Tell us which versions you are using: 
![image](https://user-images.githubusercontent.com/24520545/39238587-33d78dec-48b1-11e8-8ed6-7b16f0f80043.png)

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aaron25mt** [comment]
I believe the Back button calls NavigationActions.back() from React Navigation ([see here](https://reactnavigation.org/docs/navigation-actions.html#back)).

**Comment by aksonov** [comment]
`Actions.pop` should be called, you may write custom reducer to observe it.
