### ISSUE TITLE
Open Drawer dynamically

### ISSUE THREAD

**Issue by hamsddxn** [aksonov/react-native-router-flux#3014]
Hello, this is my scene with Redux Router flux

`<Drawer 
                ref={(ref) => { this.drawer = ref; }}
                contentComponent={DrawerContent} hideNavBar key="mainTab">
            <Scene key="splash" component={MainTab} title="Bienvenue" hideNavBar/>
          </Drawer>`

I Have a button menu in MainTab in order to open drawer when it's pressed 
How can i open drawer from child component??

**Comment by flashimxd** [comment]
I wanna know this as well...

**Comment by zhangjingzhu19930808** [comment]
you can try Actions.drawerOpen();
