### ISSUE TITLE
Sticky bar on the bottom

### ISSUE THREAD

**Issue by bialasik** [aksonov/react-native-router-flux#3015]
### Version
- react-native-router-flux v4.0.0 (v3 is not supported)
- react-native v0.54.*

### Expected behaviour

Hi. I'd like to have sticky bar on the bottom, with button to other scene. Visibility should depends of state of my app.
This bar should be visible for multiple views.
What's the best way to achieve this? Should I use tabbar or something else?

Thank you,
Marcin

**Comment by tianling536** [comment]
try tabBarPosition='bottom'，example:
<Tabs  key='tabBar'
           swipeEnabled
           showIcon={true}
           showLabel={false}
           tabBarPosition='bottom'
           hideNavBar
           type={ActionConst.RESET}
           inactiveTintColor="#999999"
           activeTintColor={platform.brandPrimary}
           initial={false}
           default='home'>
     Scenes...
</>

**Comment by tianling536** [comment]
try tabBarPosition='bottom',example:
<Tabs  key='tabBar'
           swipeEnabled
           showIcon={true}
           showLabel={false}
           tabBarPosition='bottom'
           hideNavBar
           type={ActionConst.RESET}
           inactiveTintColor="#999999"
           initial={false}
           default='home'>
   your Scenes...
</Tabs>
