### ISSUE TITLE
onEnter problem of use

### ISSUE THREAD

**Issue by IronTony** [aksonov/react-native-router-flux#3016]
Hi,

I don't know if I am against any repo rule, I hope not so I try anyway.
I am trying to use the `onEnter` property in the `Scene`. What I am trying to do is to check if an user is authenticated per `Scene`, if not redirect to Login page.

I am doing something like this, in the `App.js` component:

```
class App ..... {
    isLogged(isAuth) {
        if (isAuth) {
            Actions.Login();
        }
     };

     render() {
         .......
         return (
             <Provider store={store}>
             <PersistGate loading={null} persistor={persistor}>
             <Router>
                 <Scene key="root">
                     <Scene
                         key="Login"
                         component={Login}
                         gesturesEnabled={false}
                         hideNavBar
                      />
                     <Scene
                         key="Home"
                         component={Home}
                         gesturesEnabled={false}
                         hideNavBar
                         onEnter={this.isLogged(isAuth)}
                      />
                </Scene>
         </Router>
         </PersistGate>
         </Provider>
      );
    }
}
```
Unfortunately when I execute this code, I get back this error:
`TypeError: _reactNativeRouterFlux.Actions.Login is not a function`

Any help on this would be more than welcome.

### Version
- react-native-router-flux v4.0.0-beta.28
- react-native v0.55.2

**Comment by ryanmr** [comment]
I don't know if this will solve your problem. `onEnter` needs a function reference, while you gave it `this.isLogged(isAuth)` which resolves to undefined (which is not a function).

Try this: `onEnter={() => this.isLogged(isAuth)}`. Note, it is unclear what `isAuth` is or if it's even in scope.
