### ISSUE TITLE
Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by CZHach** [aksonov/react-native-router-flux#3017]
I'm trying to use react-native-router-flux with my project.

### Version
- react-native-router-fluxv 4.0.0-beta.30
- react-native v0.54.4

### Error

> TypeError: Cannot read property 'clone' of undefined
> 
> This error is located at:
>     in Router (at RouterComponent.js:9)

### My Code

```
import React from 'react';
import { Scene, Router, Stack } from 'react-native-router-flux';
import LoginForm from './components/LoginForm';

const RouterComponent = () => {
    return (
        <Router hideNavBar= "true">
            <Scene key="root">  {/* App parent/root scene */}
                <Scene key="login" component={LoginForm} title="Please Login" />
            </Scene>
        </Router>
    );
};

export default RouterComponent;
```

**Comment by aksonov** [comment]
I can't reproduce. Please check Example project. Maybe you should not use `{` `}` inside `Scene`

**Comment by socialcode-rob1** [comment]
@CZHach did you figure out the cause?

**Comment by zi6xuan** [comment]
You must like this `Actions.product({ time: new Date() });`to input the props
