### ISSUE TITLE
how to reset stack on nested scenes in tabBar ?

### ISSUE THREAD

**Issue by Stettinum** [aksonov/react-native-router-flux#3019]
i have tabbar with nested scenes :

```
      <Scene key="root"
          icon={TabIcon}
          title="Root"
          navBar={Navbar}
      >

        <Scene
          initial
          key={'keyA'}
          component={ComponentA}
        />

        <Scene
          key={'keyB'}
          component={ComponentB}
        />

      </Scene>
```
when i got to scene 'keyA' and after that navigate to scene  'keyB' its pushed to stack. When i navigate to another tab, and switch back to tab 'root' current scene is 'keyB', how to reset stack and after switch back has 'keyA' as active ? 
Regards

**Comment by kr0000** [comment]
The same issue

**Comment by aksonov** [comment]
Please check 4.0.0-beta.41 and Example with `backToInitial` prop
