### ISSUE TITLE
How to Change State of Previous Scene

### ISSUE THREAD

**Issue by StanislavSergeev** [aksonov/react-native-router-flux#3020]
> https://stackoverflow.com/questions/50063023/camera-always-working-in-react-native-router-flux-scene
This is my problem.

There are two scene in parent scene which have tab bar.
Initial Scene is simple view and second scene is QR Scanner and it uses RNCamera.

My problem is that Camera always working even though I am working at Initial Scene.

So if I can, I want to change state of second scene, so that stop camera.
Or is there any other way to stop camera?

**Comment by aksonov** [comment]
Answered. 

Please use onEnter/onExit function together with Actions.refs.YOUR_CAMERA_SCENE to start/stop camera like this:
```
   <Router ...>
     <Scene tabs>
       <Scene />        // Scene1
       <Scene key='QR' onEnter={()=>Actions.refs.QR.startCamera()} onExit={()=>Actions.refs.QR.stopCamera()} />        // Scene2
     </Scene>
   </Router>
```
And your QR React Component should have startCamera and stopCamera methods.
