### ISSUE TITLE
isMounted is deprecated when using tab views

### ISSUE THREAD

**Issue by kaym0** [aksonov/react-native-router-flux#3021]
I get this whenever I go into my tabbed scene ever since I added it. If I view the two components separately they work fine, it's adding the tabs which cause it to break. I've tried various things like unmountScene={true} (pretty sure it doesn't do anything)

Should I mute this error, because everything seems to work okay. I'm just wondering if there is something I'm doing wrong, or if this is an actual issue with the package.

```json
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-navigation": "^1.5.11",
```

```js
const AppRouter = () => {
	return (
		<Router>
			<Modal key="modal">
				<Stack key="root" hideNavBar > 
					<Drawer key="Drawer" hideNavBar contentComponent={Sidebar} drawerWidth={deviceWidth/1.38}>
						<Stack key="MainStack" navBar={Layout} >
							<Scene key="Main" component={Main} />
							<Scene key="Settings" component={Settings}/>    
							<Scene key="TVInfo" component={TVInfo}/>
							<Scene key="Login" component={Login} />           
							<Scene key="TabBar" tabs={true} hideTabBar={false}>
								<Scene key="Info" hideNavBar={true} title="Info" icon={TabIcon} component={MovieInfo} />
								<Scene key="Cast" hideNavBar={true}  title="Cast" icon={TabIcon} component={Cast} />
							</Scene>
						</Stack>
					</Drawer>
				</Stack>	
			</Modal>
		</Router>
	)
}

```
Sorry for formatting, Markup seems to take my two space tabs as if they were like 4 or 5 spaces.

**Comment by ajangi** [comment]
Guys, I have the same issue! How can we fix it?

**Comment by ajangi** [comment]
@januswel @andrew @daviscabral @joenoon Is there any solution for this guys?

**Comment by guangyuzhihun** [comment]
Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by ajangi** [comment]
@guangyuzhihun What do you mean bro? Is there any solutions for this issue? did you fixed it?

**Comment by ajangi** [comment]
@aksonov How can I solve this issue dear Pavel? 
Thanks!

**Comment by daviscabral** [comment]
That's not an error - it is a warning. Even a few official packages still make references to `isMounted` yet. 

By the way, this is not even used by `react-native-router-flux` anywhere. I believe that `react-navigation` is the culprit here.

**Comment by ajangi** [comment]
@daviscabral Thanks buddy.
But I don't wanna ignore the warning and want to solve it. The warning says that it might cause memory leakage.

**Comment by daviscabral** [comment]
That's fine. Please provide a pull-request with your solution.

**Comment by xuho** [comment]
I have the same issue too.

**Comment by Nigh7Sh4de** [comment]
This may be coming from within react itself:

https://github.com/facebook/react-native/issues/18868#issuecomment-396631905

**Comment by daviscabral** [comment]
Btw, hide the warning is not a solution. I don't consider a warning a blocker in a release, just a heads-up about possible out of date packages and future unsupported code.

**Comment by RijaAdrian** [comment]
Same issues here !

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40 (and RN0.56). Feel free to open if the issue still exists

**Comment by daviscabral** [comment]
Thank you sir! 👍🏻👊🏻
