### ISSUE TITLE
Most Stable/Recommended version to use?

### ISSUE THREAD

**Issue by nonotest** [aksonov/react-native-router-flux#3022]
Hi guys,

After trying a few different versions and hitting different problems every time it seems that
beta.27 is the most stable version out right now?

Sentiment seems similar on stackoverflow:
https://stackoverflow.com/questions/49975810/reacct-native-router-flux-undifine-is-not-a-function-evaluationg-addlistner/

It may be a good idea to add a comment in the docs? would probably save people some time?
thanks!

**Comment by digitaldavenyc** [comment]
The repo is still in beta for a reason, every version seems to still have some issues. I would stick to earliest version possible. We're on beta.27

**Comment by aksonov** [comment]
4.0.0-beta.31 should be major upgrade and recommended version right now
