### ISSUE TITLE
Error: There is no route for key home . must be one of drawer

### ISSUE THREAD

**Issue by zurez** [aksonov/react-native-router-flux#3024]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.
- react-native v0.50.4

### Expected behaviour
Actions.reset("home") should navigate to Scene with "home" key.

### Actual behaviour

Red Screen Error:There is no route for key home . must be one of drawer

### Steps to reproduce
Android:
` <Router >
                <Stack key="root">
                    
                   <Drawer
                    hideNavBar
                    key="drawer"
                    open={this.state.show_drawer}
                    type="overlay"
                    content={<SideBar toggle_drawer={this.toggle_drawer}/>}
                    drawerWidth={200}
                    
                    tapToClose={true}
                    openDrawerOffset={0.6}
                    
                    closedDrawerOffset={-3}
                    
                                   
                    >
              
                    <Scene hideNavBar={true}  key="home" 

                    onEnter={this.state.is_authenticated} component={HomeScreen}  />

                   
                      </Drawer>
                </Stack>

            </Router>
`

**Comment by zurez** [comment]
https://files.slack.com/files-tmb/T491AE9NX-FALHQHGTZ-1af647b5d2/screenshot_20180507-204320_1024.jpg

**Comment by zurez** [comment]
[](https://files.slack.com/files-tmb/T491AE9NX-FALHQHGTZ-1af647b5d2/screenshot_20180507-204320_1024.jpg)

**Comment by aksonov** [comment]
It is not correct usage of `reset` - you are trying to make `home` only one scene of the app, but it is not true -` drawer` is top-level within your Example
