### ISSUE TITLE
NavBar breaking KeyboardAvoidingView functionality

### ISSUE THREAD

**Issue by sgardn** [aksonov/react-native-router-flux#3025]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.53.0 (via expo)

### Expected behaviour
When I use the `KeyboardAvoidingView` as a view with `behavior="padding"`, I expect that the TextInput contained within should be kept in view when I focus it doing something similar to the following:

https://snack.expo.io/@sgardn04/scrolling-with-textinput 

### Actual behaviour

The TextInput never emerges, due to the offset introduced by the NavBar. I've confirmed this by disabling the NavBar with `hideNavBar` and confirming that the `KeyboardAvoidingView` works as expected.

### Steps to reproduce

1. clone https://github.com/sgardn/react-native-router-flux
2. run `npm i` inside the Example directory
3. open the app on a device where the keyboard pops up (doesn't do this for the simulator for me - is there a way to force `react-native run-ios` to choose particular hardware?)
4. navigate to the login screen and try to type in the `TextInput`
5. try hiding the nav bar to see the desired effect in that component

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by ningacoding** [comment]
so?
