### ISSUE TITLE
xcode can't be installed 

### ISSUE THREAD

**Issue by fawadjadeedid** [aksonov/react-native-router-flux#3027]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by fawadjadeedid** [comment]
react-native

**Comment by daviscabral** [comment]
Please, provide information in the ticket to get assistance.
