### ISSUE TITLE
TypeError:undefined is not a function (evaluating 'addListener')

### ISSUE THREAD

**Issue by Hgq1001** [aksonov/react-native-router-flux#3033]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.30
- react-native 0.55.3
- react 16.3.1
- react-navigation 1.5.12

### Expected behaviour

Let the project run properly

### Actual behaviour

![image](https://user-images.githubusercontent.com/21699465/39981129-be6b00ae-5781-11e8-9ef1-96869f1e12e0.png)

**Comment by lorcanluo** [comment]
I have the same problem.

**Comment by daviscabral** [comment]
Please upgrade to `4.0.0-beta.31` - a fix was added to it a few hours ago.

**Comment by JackGZY** [comment]
I have the same problem,too.

**Comment by Hgq1001** [comment]
@daviscabral i have updated it  to 4.0.0-beta.31,but that does not work,too！

**Comment by daviscabral** [comment]
@Hgq1001 can you try cleaning your cache and removing all your files from `node_modules`? 

Also, could you show me your `package.json` and the packager error?

To clean use these commands: 

```
```

**Comment by aksonov** [comment]
Closed due inactivity
