### ISSUE TITLE
[question] popN(...) functionality?

### ISSUE THREAD

**Issue by ChristianTucker** [aksonov/react-native-router-flux#3036]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta28
- react-native v0.55.2

Currently when moderating my navigation stack in an attempt to not keep pushing additional items on the stack and utilizing the `componentWillUnmount` function for various clean-up and not having a huge navigation stack sitting around. Sometimes I need to do something like this.. 

```javascript
Actions.pop()
Actions.pop()
Actions[key]()
```

This would be for example, a user goes from..

`Home Screen::Tabs -> Search -> Group -> (Action: Join)`

and needs to go to

`Home Screen::Tabs -> Profile`

after the action is completed. I can't use `popTo` because supplying a key for the <Scene /> acting as the tabs causing the application to freeze.  I can't use `replace` because there will be no transition, but calling `pop` twice causes 3 transitions which is a little weird. 

Any solutions? 

```
<Scene key="rootTabs" ...>
   <Scene key="tab1" ... />
   <Scene key="tab2" ... />
   <Scene key="tab3" ... />
</Scene>
```

I don't want to `popTo('tab1')` because the user may have been on 'tab3' when he left the page. I guess I could work around this by always going to tab1 and then replacing, something like `Actions.popTo('tab1'); Actions.replace('tab3')`

**Comment by aksonov** [comment]
popN is not supported right now. PR is welcome.
