### ISSUE TITLE
Can you add or remove Scenes from router based on platform

### ISSUE THREAD

**Issue by CristianCosmic** [aksonov/react-native-router-flux#3038]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.22
- react-native v0.50.3

Is there any way to add or remove a  <Secene/> from tab Bar with plarform Select ?
Or have on Android 2 Sceens  and 3 on iOS ?

**Comment by aksonov** [comment]
Sorry, it is not supported
