### ISSUE TITLE
By default lazy prop = {true} on beta.31. Are the docs wrong or is this a bug?

### ISSUE THREAD

**Issue by themakerman** [aksonov/react-native-router-flux#3039]
### Version
Tell us which versions you are using: 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-elements": "^0.19.1",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-persist": "^5.9.1",
    "redux-thunk": "^2.2.0"
  }
}
```

### Expected behaviour
By default lazy prop for tabs should be false (as per docs)

### Actual behaviour
By default i am seeing its true in 4.0.0-beta.31

Should the docs be updated? or something wrong with beta.31?

**Comment by daviscabral** [comment]
Do you mind checking which version of `react-navigation` was installed over there? As soon as I get some time, I'll investigate this and get back to you about it. Thank you for reporting.

**Comment by themakerman** [comment]
@daviscabral As per release docs, 4.0.0-beta.31 is using react-navigation 1.5.8

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
