### ISSUE TITLE
Request for multiple Router.uriPrefix and Scene.path values

### ISSUE THREAD

**Issue by grahamyesfit** [aksonov/react-native-router-flux#3040]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27
- react-native v0.55.4

We are using an attribute provider (AppsFlyer) so deep links will either be to `https://yes.fit/path/...` or `https://yesfit.onelink.me/other-path/...`. For the 2nd URL, we don't have control over the first path value (in this example, it's `other-path`).

Consequently, I've set the `Router uriPrefix` property to `yesfit.onelink.me` in order to process deep links to that location. Unfortunately, this means that regular non-AppsFlyer links will no longer work, as the `uriPrefix` would have to be `yes.fit` in order for it to work. It would really help me out if `uriPrefix` was an array of strings so that I can pass both domains.

In addition, because we have no control over the `path` portion of the URL from AppsFlyer, it would help me out if the `Scene.path` property could also take an array of strings.

So, my `Router` definition would look something like this:

```
<Router uriPrefix={['yes.fit', 'yesfit.onelink.me']}>
  <Scene path={['/path', '/other-path']} ... />
</Router>
```
With this configuration, deep linking will work for both `https://yes.fit/path/...` and `https://yesfit.onelink.me/other-path/...`

**Comment by aksonov** [comment]
It is not supported, PR is really welcome.
