### ISSUE TITLE
LayoutAnimation interferes with tab navigation

### ISSUE THREAD

**Issue by mackenziemance** [aksonov/react-native-router-flux#3042]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.31
- react-native 0.55.

### Expected behaviour

Ability to to use LayoutAnimation in the initial scene of a tab.

### Actual behaviour

After navigation to scene with LayoutAnimation tabs jump as a modal.

**Comment by aksonov** [comment]
Sorry, it is not supported
