### ISSUE TITLE
Show Drawer's nav bar when drawer is open.

### ISSUE THREAD

**Issue by cxrod** [aksonov/react-native-router-flux#3046]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55.4

### Expected behaviour
Show Drawer's nav bar when Drawer is open

### Actual behaviour
Drawer show parent nav bar

This is my router:

```
<Stack key="root" hideNavBar>
    <Scene
      hideNavBar
      key="launcher"
      title="LAUNCHER"
      {...DefaultProps.navbarProps}
      component={LauncherContainer}
      Layout={LauncherComponent} />

    <Stack key="app">
      <Scene
        hideNavBar
        key="login"
        title="LOGIN"
        {...DefaultProps.navbarProps}
        component={LoginContainer}
        Layout={LoginComponent} />
      <Scene
        hideNavBar
        key="fingerprint"
        title="FINGERPRINT"
        {...DefaultProps.navbarProps}
        component={FingerprintContainer}
        Layout={FingerprintComponent} />

      <Scene
        drawer
        key="drawer"
        title="Menu"
        {...DefaultProps.navbarProps} >
        <Scene
          key="home"
          title="HOME"
          renderRightButton={() => <Logout />}
          {...DefaultProps.navbarProps}
          component={HomeContainer}
          Layout={HomeComponent} />
      </Scene>
    </Stack>
  </Stack>

```
Some screens

![image](https://user-images.githubusercontent.com/16138018/40364692-f1bd52ca-5da0-11e8-994c-8d6880ab4431.png)

![image](https://user-images.githubusercontent.com/16138018/40364727-066e4878-5da1-11e8-9b75-37bb8785a0d6.png)

![image](https://user-images.githubusercontent.com/16138018/40364749-0f577b30-5da1-11e8-9dcd-41901049b4f4.png)

**Comment by daviscabral** [comment]
If I understood it right, that's the expected behavior - and it's documented on `react-navigation`. To have it behaving the way you want, you will need to reorganize your scenes in a different and more complex way. But in a nutshell, the scene containing the drawer need to be at the top level, or it will be nested.

> Nesting DrawerNavigation
> Please bear in mind that if you nest the DrawerNavigation, the drawer will show below the parent navigation.
https://v1.reactnavigation.org/docs/drawer-navigator.html#nesting-drawernavigation
