### ISSUE TITLE
type: ActionConst.RESET and Android back button

### ISSUE THREAD

**Issue by b1acKr0se** [aksonov/react-native-router-flux#3048]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31

### Problem

Suppose you have 4 scenes, A B C D. You can go to the respective scene for that order.
When I go from A to B, and when from B to C I use `type: ActionConst.RESET` to reset the history stack. After that when I'm in C, I press the Android back button (the app will now quit), and then relaunch the app from the app drawer.

### Expected behaviour

App starts with scene A.

### Actual behaviour

App starts with scene C.

### Steps to reproduce

Make some scenes and try `type: ActionConst.RESET` when navigating to one scene, and then press the Android back button.

**Comment by kirkjoan** [comment]
@b1acKr0se 
Have you tried this? Actions.root({ type: ActionConst.RESET }) This one will put you back to the initial scene.

**Comment by yeomann** [comment]
after all tries I just switched to v 3.43.0

**Comment by Symous** [comment]
please I have the same issue! #3102

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
