### ISSUE TITLE
The props is not working. I can not pass the props.

### ISSUE THREAD

**Issue by kyhnlbyrk** [aksonov/react-native-router-flux#3049]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55

I am using expo, and I recently upgrade the expo sdk to 27 to use react native 0.55. The new sdk needs react navigation version 1.5.11. I updated it too. You can find the versions below before and after the update. Before the update, everything works perfectly... 

BRIEF INFO: I have a drawer scene in my router.js and below that there are some other scenes. The expected behaviour is that the props will be pass to the children automatically because it was like that before. However, now in the actual behaviour props is undefined..

BEFORE:
expo: 25
react native: 0.52
react-native-router-flux": "^4.0.0-beta.22"
react-navigation": "^1.0.0-beta.19

AFTER:
expo: 27
react native: 0.55
"react-native-router-flux": "^4.0.0-beta.31",
"react-navigation": "^1.5.11"

Now, I can not pass props to a component. The props are always undefined.. How can I fix this issue?

**Comment by kyhnlbyrk** [comment]
@aksonov do you know this kind of issue? I need urgent help..

**Comment by kyhnlbyrk** [comment]
`<Scene
key = "tabBar"
            tabs
            tabBarPosition={'bottom'}
            activeTintColor="#b78300"
            labelStyle={styles.labelStyle}
            tabBarStyle={styles.tabBar}
            onRight={null}
            rightButtonImage={null}
          >
              <Scene key="activitiesMain" component={Activities} hideNavBar={true} headerTintColor="#fff">`

Like this, I pass a prop to the tabBar, but I can not read that prop in activitiesMain

**Comment by daviscabral** [comment]
Please add an example of your issue in the `Example` app in the repository. That will make easier to trace the issue.

**Comment by kyhnlbyrk** [comment]
[issue #3049.zip](https://github.com/aksonov/react-native-router-flux/files/2045119/issue.3049.zip)

This the issue that I was talking about. You can find the app in the link. The app is on Expo..  It created with create-react-native-app code. node modules are not in the file.

**Comment by aksonov** [comment]
Sorry, but Expo is not supported at this moment. Probably sometimes we will test it and support it (probably after migration to v2 react-navigation)
