### ISSUE TITLE
Disable swipe back function

### ISSUE THREAD

**Issue by rodrigofbm** [aksonov/react-native-router-flux#3050]
## Version
- react-native-router-flux v4.0.0 @beta.21
- react-native v0.54.3

### Expected behaviour
Disable swipe back function

### Actual behaviour
I can't make it work

### Steps to reproduce
I have tryied:
1. type="reset", but it minimizes the app 
2. panHandlers={null} 
3. gesturesEnabled={false} 

but nothing works for me. Can someone help me?

**Code:**

```
<Router>
            <Stack key="root">
              <Scene key="Inicio" component={Inicio} titleStyle={{color: '#FFF', fontSize: 18}} navigationBarStyle={{ backgroundColor: '#4c486f' }} title="All About My Pet" type="reset"/>
              <Scene key="FormLogin" component={FormLogin} titleStyle={{color: '#FFF', fontSize: 18}} navigationBarStyle={{ backgroundColor: '#4c486f' }} title="Faça seu Login"/>
              <Scene key="FormCadastro" component={FormCadastro} titleStyle={{color: '#FFF', fontSize: 18}} title navigationBarStyle={{ backgroundColor: '#066c76' }} title="Cadastro"/>
            </Stack>
</Router>
```

**Comment by lupino22** [comment]
You can use
```
import { Scene, Router, ActionConst } from 'react-native-router-flux'; 
``` 
then
```
<Scene key="someScene" type={ActionConst.REPLACE} />
```
Scene will be disabled doing swipe back.

**Comment by rodrigofbm** [comment]
@lupino22 
After I added `type={ActionConst.REPLACE} ` the scene does not load anymore. Just type='reset' works, but it minizes the app

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Comment by faheem121** [comment]
just put the  gestureEnabled={false} in scene tag 
example:its work for me after login switch to home scene and now never swipe back
<Scene key="home" hideNavBar={true} gesturesEnabled={false} component={HomePage} title="Home" />

**Comment by faheem121** [comment]
<Scene key="home" hideNavBar={true} gesturesEnabled={false} component={HomePage} title="Home" />

**Comment by faheem121** [comment]
`` <Scene key="home" hideNavBar={true} gesturesEnabled={false} component={HomePage} title="Home" />

**Comment by faheem121** [comment]
![image](https://user-images.githubusercontent.com/34395002/45136418-6a96c080-b1bd-11e8-9125-929ee93aed0f.png)

**Comment by adeamos83** [comment]
You must use "drawerLockMode='locked-closed' gesturesEnabled={false}" together inorder for the swipe action to be fully disabled

<Scene key="home" drawerLockMode='locked-closed' gesturesEnabled={false} component={HomeContainer}/>

**Comment by jituumaria** [comment]
> ## Version
> * react-native-router-flux v4.0.0 @beta.21
> * react-native v0.54.3
> 
> ### Expected behaviour
> Disable swipe back function
> 
> ### Actual behaviour
> I can't make it work
> 
> ### Steps to reproduce
> I have tryied:
> 
> 1. type="reset", but it minimizes the app
> 2. panHandlers={null}
> 3. gesturesEnabled={false}
> 
> but nothing works for me. Can someone help me?
> 
> **Code:**
> 
> ```
> <Router>
>             <Stack key="root">
>               <Scene key="Inicio" component={Inicio} titleStyle={{color: '#FFF', fontSize: 18}} navigationBarStyle={{ backgroundColor: '#4c486f' }} title="All About My Pet" type="reset"/>
>               <Scene key="FormLogin" component={FormLogin} titleStyle={{color: '#FFF', fontSize: 18}} navigationBarStyle={{ backgroundColor: '#4c486f' }} title="Faça seu Login"/>
>               <Scene key="FormCadastro" component={FormCadastro} titleStyle={{color: '#FFF', fontSize: 18}} title navigationBarStyle={{ backgroundColor: '#066c76' }} title="Cadastro"/>
>             </Stack>
> </Router>
> ```

using 

 type="replace"

**Comment by edoantonioco** [comment]
Im in same situation, with latest version of all packages, and this doesnt work
drawerLockMode: 'locked-closed' Does not disable the left menu to show up if you use your finger to open it
drawerLockMode='locked-closed' gesturesEnabled={false} Neither

**Comment by AE0011** [comment]
i have the same issue 
is there any solution?

**Comment by AE0011** [comment]
@adeamos83 Thanks it works

**Comment by Ryan113** [comment]
<Router navigationBarStyle={styles.navBar} titleStyle={styles.navTitle} panHandlers={null} >

Worked for me.

**Comment by Ryan113** [comment]
`<Router navigationBarStyle={styles.navBar} titleStyle={styles.navTitle} panHandlers={null} >`

Worked for me.

**Comment by moribaleta** [comment]
Can you disable Swipe Back gesture on the Class itself?

**Comment by AliUZAR** [comment]
> You must use "drawerLockMode='locked-closed' gesturesEnabled={false}" together inorder for the swipe action to be fully disabled
> 
> `<Scene key="home" drawerLockMode='locked-closed' gesturesEnabled={false} component={HomeContainer}/>`

Thanks
