### ISSUE TITLE
Best Practice Using Router/Scene/Modal (Not an issue)

### ISSUE THREAD

**Issue by alittletf** [aksonov/react-native-router-flux#3051]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.54.4

###

I am curious what the best practices were around how to structure your Router.js file. Currently, I have every single Scene in my Router.js file and all the the Scenes are nested in one Router tag. Some scenes are nested inside other Scenes. 

Is this common best practice? 

I started looking into using a Modal tag since I wanted to load up a specific screen from the bottom up and in the documentation it told me to wrap my root Scene which contains all my other Scenes in the modal tag. I not only could not get it to work but I also dont want every single screen to animate in from bottom up. 

It started to make me wonder if I am not using Scenes in my Router file correctly. 

Thoughts?

**Comment by Blapi** [comment]
What I am doing on my end is : 

```
        <Router
          backAndroidHandler={this.onBackPress}
          createReducer={reducerCreate}>
          <Stack
            key='root'
            hideNavBar
            transitionConfig={() => ({
              screenInterpolator: (props) => {
                const { scene, scenes } = props
                switch (scene.route.routeName) {
                  case 'myScene':
                    return theTransitionIWant
                  default:
                    return defaultTransition
                }
              }
            })}>
            <Scene
              key='myKey'
              component={myComponent}
              initial />
// all my other scenes
          </Stack>
        </Router>
```

As I'm not using the Tab, Drawer or Modal, I don't need to use nested scenes, I just put them all inside of my Stack :)

**Comment by aksonov** [comment]
@alittletf You may check also Example project as well as starter pack https://github.com/aksonov/react-native-starter-app

Basically good practice is to put everything in one place to see whole app logic.
