### ISSUE TITLE
empty default background used when transiting 

### ISSUE THREAD

**Issue by weijiederrick91** [aksonov/react-native-router-flux#3052]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.27 (v3 is not supported)
- react-native v0.53.0

### Expected behaviour
  i still having issue to set the animation between my splash screen and between scenes anyway to remove all animation 

            <Scene key="tabbarRoot" hideNavBar type='reset' duration={300}>
              <Lightbox key="theLightBox">
                <Tabs
                    key="tabbar"
                    swipeEnabled={false}
                    animationEnabled={false}
                    showLabel={false}
                    tabBarStyle={styles.tabBar}
                    tabBarPosition = "bottom"
                    activeBackgroundColor="rgba(0, 0, 0, 0)"
                    inactiveBackgroundColor="rgba(0, 0, 0, 0)"
                    default="tabDashboard"
                    tabBarOnPress={this.onTabPress}
                    lazy={true}
                    gesturesEnabled={false}
                    //panHandlers={null}
                    type='reset'
                  >
                          <Scene key="tabDashboard" icon={TabIconMain} navBar={HeaderDashboard} title="Dashboard" titleStyle={{color:'white'}} iconName={'tabMain'} >
                           
            </Scene>

### Actual behaviour

it is not suppose to have a loading screen before the screen

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment]
It is not supported at this moment
