### ISSUE TITLE
Is this lib still supported to work with react-navigation 2.0

### ISSUE THREAD

**Issue by waqas19921** [aksonov/react-native-router-flux#3053]
As react-navigation library has been updating continuously updating and have very breaking changes since version 1.5.8 and moved to 2.0.
So still this is usable with react-navigation 2.0?

**Comment by daviscabral** [comment]
`react-native-router-flux` is still on `react-navigation@1.5.8` - and there is no active work for supporting 2.0 that I am aware of. PRs are always welcome.
