### ISSUE TITLE
Provide API to disable Status bar height in Navigationbar

### ISSUE THREAD

**Issue by rhishikeshj** [aksonov/react-native-router-flux#3055]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55.3

### Expected behaviour

We should be able to optionally remove the status bar height from navigation header.

### Actual behaviour

Navigation bar height always includes status bar height.
This is an issue in portrait mode if we wrap the Router with a react-native SafeAreaView.
Since the SafeAreaView comes with its own insets for the Status bar in portrait mode, this height getting added to the Navigation bar is extra and looks incorrect.
Adding the Safe area view inside the Router does not work correctly as the SafeAreaView does not then provide the correct insets

SafeAreaView
   Router
/SafeAreaView

![simulator screen shot - iphone x - portrait](https://user-images.githubusercontent.com/719190/40602018-de96a9c0-6274-11e8-861a-afde0fc58676.png)
![simulator screen shot - iphone x - landscape](https://user-images.githubusercontent.com/719190/40602055-09d91a46-6275-11e8-8a0d-2d02545e982b.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Wrap your Router inside a SafeAreaView from react-native

**Comment by lafiosca** [comment]
Why was this issue closed? I have been digging through the documentation and code for quite a while now and trying various things, but I haven't found a way to pass the `forceInset` param through the `Scene`, other than perhaps constructing my own `navBar`.

**Comment by lafiosca** [comment]
I finally realized you can just pass `headerForceInset` directly as a property of the `Scene`:

```
<Scene
    key="foo"
    component={Foo}
    hideNavBar={false}
    title="Foo"
    headerForceInset={{ top: 'never' }}
    navigationBarStyle={{ backgroundColor: '#ffffff' }}
/>
```
