### ISSUE TITLE
Execute function before a tab is changed

### ISSUE THREAD

**Issue by antonkulyk** [aksonov/react-native-router-flux#3056]
Hi! I have a tab-based app. One of the tabs contains a form. When the form inputs become dirty and a user doesn't save the form and tries to switch a tab, I need the app to show an alert saying that the form data will be lost.

Any ideas how can I make this check and show an alert before the router switches a tab?

- react-native-router-flux v4.0.0-beta.28
- react-native v0.52.0

**Comment by aksonov** [comment]
Sorry, it is not supported at this moment.
