### ISSUE TITLE
physical back on Android works weird after executing Linking.openURL

### ISSUE THREAD

**Issue by jaychenjun** [aksonov/react-native-router-flux#3057]
### Version
Tell us which versions you are using: 

react-native-router-flux v4.0.0
react-native v0.55.4

### Expected behaviour

back to previous scene

### Actual behaviour

send me to the initial scene

### Steps to reproduce

1. open a link using Linking.openURL ( inside About scene ) and send me to the browser
2. come back to the app from the browser
2. press physical backbutton on Android
3. send me to the initial scene( do not call componentWillUnmount, do not call BackHandler )
4. I can strangely swipe back from my initial scene back to the About scene.
5. press physical backbutton again back to previous scene like normal( finally call componentWillUnmount)

This is just so weird, everything works fine without calling openURL, and I did this in another component, works fine too, but in this component it doesn't.

I don't understand why it just send me to the initial screen without calling componentWillUnmount or BackHandler, and everything works perfect using swipe back gesture and directly calling Action.pop() works perfect too.

This issue happens inside my About component, both on my SM S6 and Android simulator.

```
<Router>
<Stack 
	key="root" 
	hideNavBar 
	hideTabBar
>
		<Drawer 
			key={ 'Drawer' } 
			drawer={ true } 
			contentComponent={ Drawer } 
			drawerWidth={ width*0.7 } 
			drawerPosition={ 'left' }
			tapToClose={ true }
		>
			<Scene 
				key="Feeds" 
				component={ Feeds } 
				hideNavBar 
				hideTabBar 
				initial 
			/>
		</Drawer>

		<Scene key="FeedDetail" component={ FeedDetail }  />
		<Scene key="ArticleDetail" component={ ArticleDetail }  />
		<Scene key="LoginForm" component={ LoginForm } gesturesEnabled={ false } />
		<Scene key="About" component={ About } />
		<Scene key="AddFeed" component={ AddFeed } gesturesEnabled={ false } />
</Stack>
</Router>
```

**Comment by jaychenjun** [comment]
One thing to note, when I put all the scenes inside the Drawer, doesn't have this issue.

**Comment by aksonov** [comment]
Yes, please wrap all scenes inside the Drawer.
