### ISSUE TITLE
How to hide tabbar item in tabs

### ISSUE THREAD

**Issue by jie** [aksonov/react-native-router-flux#3058]
### Version

- react-native-router-flux v4.0.0 (v3 is not supported)
- react-native v0.45.1

### Expected behaviour

![222222](https://user-images.githubusercontent.com/8618/40644783-ca7866da-6356-11e8-8d8d-2bfe4b367397.jpg)

### Actual behaviour
![1527579578082](https://user-images.githubusercontent.com/8618/40644711-9252f234-6356-11e8-99ed-f60976258c21.jpg)

### Steps to reproduce

In v3.0, I can create a scene without icon and tabContent, it will not show in tabbar, 
**but in v4.0.0**, it will show an tab item with empty label and empty icon.
```
<Scene key="main" initial={true} tabs={true} >
  <Scene key="Home" component={Home} title={'TITLE'} />
  <Scene
    key="HotNews1"
    text="hotNews_title"
    icon={TabIcon}
    component={HotNewsPage}
    tabContent={{
      iconSource: ICON_1,
      selectedIconSource: SL_ICON_1
    }} />
  
  <Scene
    key="HotNews2"
    text="hotNews_title"
    icon={TabIcon}
    component={HotNewsPage}
    tabContent={{
      iconSource: ICON_1,
      selectedIconSource: SL_ICON_1
    }} />
</Scene>
```

**Comment by aksonov** [comment]
Looks like v4 doesn't support it. PR is welcome (it should not be difficult to filter by icon and tabContent). But I really suggest you to change your nav hierarchy - move away Home if it is not part of tabbar.

**Comment by kr0000** [comment]
@jie any progress here? i have the same issue.

**Comment by kr0000** [comment]
@aksonov i have the same problem - how can i hide icon on menu any ideas?

**Comment by jie** [comment]
@kr0000 I use custom tabbar instead

**Comment by RobinJayaswal** [comment]
@jie did you extend react-navigation TabBarBottom? Do you mind posting the code for the custom tabbar you ended up using?

**Comment by jie** [comment]
@RobinJayaswal 
No, I don't use react-navigation,
here is the code:

``` javascript
                                <Scene
                                    key="main"
                                    initial={true}
                                    tabs={true}
                                    showLabel={false}
                                    tabBarComponent={TabBar}
                                    tabBarStyle={styles.tabBarStyle}
                                    tabBarPosition={"bottom"}
                                >

```

 TabBar is a React.Component
