### ISSUE TITLE
Disable Swipe Gestures in Android (Scene)

### ISSUE THREAD

**Issue by RamkumarBPE** [aksonov/react-native-router-flux#3062]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.24 (v3 is not supported)
- react-native v0.53.0

### Expected behaviour
Need to lock the Swipe Gestures, inside a scene in a tab.

### Actual behaviour
Could not able to lock the swipe gesture

I have tried panHandlers={null}, SwipeGesturesEnabled={false}, SwipeGestureEnabled={false}. I could not able to disable the swipe gesture in Android.

**Comment by delia-m** [comment]
It's case sensitive. try swipeEnabled={false} this works for me.

https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#tabs-tabs-or-scene-tabs
