### ISSUE TITLE
Weird stack behavior. Scene disappears right after pushing it, but then reappears after next push.

### ISSUE THREAD

**Issue by RobinJayaswal** [aksonov/react-native-router-flux#3064]
### Version
Tell us which versions you are using: 

"^4.0.0-beta.31"

![giphy](https://user-images.githubusercontent.com/8921279/40890518-71386fbe-6745-11e8-8a80-6b351a552ac0.gif)

Code:

```
            <Scene
              key="referral"
              type="replace"
              component={ReferralPage}
              title="Free Points"
              titleStyle={styles.title}
              renderLeftButton={() => <View />}
              onLeft={() => {}}
              renderRightButton={customRightCloseButton}
              rightButtonStyle={styles.navIconButton}
              navigationBarStyle={styles.mainNavigationBar}
              back={false}
            />
```
```
const customRightCloseButton = ({ rightCallback }) => (
  <TouchableOpacity onPress={Actions.pop} style={styles.closeButton}>
    <IonIcon name="ios-close" size={30} color="white" />
  </TouchableOpacity>
)
```

### Expected behaviour

Screen opens first time and stays open until close pressed

### Actual behaviour

Screen opens, closes, and then when I reopen, both come up and the stack is messed up so Actions.pop() does nothing.

**Comment by aksonov** [comment]
Probably navigation hierarchy is wrong. Please refer to Example project - you need to use LightboxNavigator for popups.
