### ISSUE TITLE
How to blur the background of the drawer while having some transparency?

### ISSUE THREAD

**Issue by ajaykumar97** [aksonov/react-native-router-flux#3066]
### Version

- react-native-router-flux v4.0.0-beta.28
- react-native v0.55.4

I want to blur the background of the drawer showing blurry effect on the currently opened scene. I have tried something like:
       drawerBackgroundColor='rgba(0, 0, 0, 0.6)'
and passing it to the <Drawer /> component but it only decreases the opacity of the Drawer. What should I do to have a blurry effect like
![side](https://user-images.githubusercontent.com/38132295/40976170-d85e8cea-68ea-11e8-8067-87f93a0fa105.jpg)

**Comment by aksonov** [comment]
It is not supported by RNRF
