### ISSUE TITLE
Put specific scene on top of the stack

### ISSUE THREAD

**Issue by kirkjoan** [aksonov/react-native-router-flux#3069]
May i know how can i achieve this? I have the following Scenes below as example.

Scene A > Scene B > Scene C > Scene D 

Scene A is the initial scene and Scene D is the one on top of the stack. The question is, how can i move Scene B on the top of the stack and will have something like this.

SceneA > Scene C > Scene D > Scene B

**Comment by delia-m** [comment]
Not sure you want this, but you could try popTo()

https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions

**Comment by kirkjoan** [comment]
@delia-m popTo() will close the scenes along the way.

**Comment by aksonov** [comment]
It is not supported at this moment
