### ISSUE TITLE
Trouble handling android hardware back button

### ISSUE THREAD

**Issue by AkAyush** [aksonov/react-native-router-flux#3074]
Version
    "react-native-router-flux": "^4.0.0-beta.28",

I didn't find any solution to solve the issue of back handle form android 

Looking forward to a solution as I have to implement the same in running project .

Thanks in advance.

**Comment by delia-m** [comment]
https://facebook.github.io/react-native/docs/backhandler.html

I think it's enough to add Actions.pop() in this addEventListener

**Comment by Blapi** [comment]
```
  onBackPress() {
    if (Actions.state.index === 0 || yourCustomCondition) {
      return false
    }
    Actions.pop()
    return true
  }
```

and then

```
        <Router
          backAndroidHandler={this.onBackPress}>
```
