### ISSUE TITLE
Custom NavBar animation looks weird in transition

### ISSUE THREAD

**Issue by exhibition315** [aksonov/react-native-router-flux#3075]
### Version
Tell us which versions you are using: 

- react-native-router-flux: v4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
I have a custom NavBar for <Scene> and the props of <Scene> as below:
Scene 1:
hideNavBar: true
initial: true

Scene 2:
hideNavBar: false
initial: false

I expect custom NavBar will fit the component when go back.

### Actual behaviour
When I click back button, custom NavBar animation looks weird:

![f1](https://user-images.githubusercontent.com/10154125/41280285-25e414f0-6e61-11e8-87fa-319b0961bb3d.png)
This is 'Scene 2' (custom NavBar with yellow arrow and white background). 

![f2](https://user-images.githubusercontent.com/10154125/41280397-6a419988-6e61-11e8-9330-82e31d1397fe.png)
The yellow background is 'Scene 1'. 

My custom NavBar are gone in transition

### Steps to reproduce
1. Create a custom NavBar
2. Set Scenes props as below:
Scene 1:
hideNavBar: true
initial: true

Scene 2:
hideNavBar: false
initial: false
3. Go back from Scene 2 to Scene 1.
4. The header NavBar looks weird

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
