### ISSUE TITLE
router flux  tab bar in View template

### ISSUE THREAD

**Issue by reza-mazarlou** [aksonov/react-native-router-flux#3077]
I want create simple page like this : 

_______________________________
                                                
             section A                    
_______________________________ 
                                                
                Tabs                       
_______________________________ 
                                                
                section B                 
_______________________________ 

and my App.js like this : 

```
const App = () => (
    <Router>
        <Scene key="root" >
            <Scene key="home" component={Home} />
        </Scene>
    </Router>
);

export default App;
```

and Home.js like this :  

```
export default class Book extends React.Component {

    render(){
        return(
            <View style={styles.container}>
                {/*Section A*/}
                <View style={styles.sectionA}>
                </View>

                {/*Tabs*/}
                <View style={styles.tabs}>
                    {/*How can I use router flux tabbar in this section*/}
                </View>

                {/*Section B*/}
                <View style={styles.sectionB}>
                </View>
            </View>
        
        )

    }


}
```
How can I use router flux tab bar in tabs section ?

**Comment by aksonov** [comment]
Not enough information, closing
