### ISSUE TITLE
Should scenes that are not at the top of the stack be able to re-render as the main scene on redux store changes?

### ISSUE THREAD

**Issue by kwoumn3** [aksonov/react-native-router-flux#3079]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.28 (v3 is not supported)
- react-native v0.54.x

I have a Redux connected component  called `GreekMap` and onPress, goes to another redux connected component called `Chat` by doing `Actions.chat`. When sending a message on this chat screen, my redux store is updated and navigates back to the `GreekMap` page but I didn't explicitly pop that page off the stack.

### Expected behaviour

I expected the screen to *not* navigate back to the previous screen unless explicitly stated otherwise...even in the condition of a redux store update

### Actual behaviour

The screen navigates to the previous screen when the redux store is updated.

### Steps to reproduce
This is my router

```
const RouterWithRedux = connect()(Router);

export default class App extends React.Component {
  render() {
    return (
      <FormattedWrapper locale="en" currency="USD">
        <Provider store={store}>
          <RouterWithRedux>
            <Stack key="root">
              <Scene key="greekMap" component={GreekMap} />
              <Scene key="chat" component={Chat} />
            </Stack>
          </RouterWithRedux>
        </Provider>
      </FormattedWrapper>
    );
  }
}
```

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
