### ISSUE TITLE
navigation bar apperas when swipe back to a non-navigation-bar scene

### ISSUE THREAD

**Issue by plrthink** [aksonov/react-native-router-flux#308]
I have a scene in my project which has been configed to remove navigation bar. But when I swipe back from a scene which has a navigation bar, the navigation bar still appears on the scene which should have that. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2429369/13735354/57e8aa7e-e9e3-11e5-8104-3a72c5b39e92.gif)

Here's the config:

````js
<Router name="root">
    <Route
        component={Project}
        gestures={Navigator.SceneConfigs.FloatFromRight.gestures}
        hideNavBar={true}
        initial={true}
        name="project"
        sceneConfig={Navigator.SceneConfigs.FloatFromRight}
        title="Project"
    />
    <Route
        barButtonIconStyle={{ tintColor: MAIN_COLOR }}
        component={Settings}
        gestures={Navigator.SceneConfigs.FloatFromRight.gestures}
        leftButtonTextStyle={{ color: MAIN_COLOR }}
        name="settings"
        sceneConfig={Navigator.SceneConfigs.FloatFromRight}
        title="Settings"
    />
 </Router>
```` 

Any ideas?

**Comment by kristianmandrup** [comment]
Do you have a copy of your project so I can have a look :) I'm having trouble figuring out how to show a `Navbar` in the header at all. The `/Example` doesn't really show how this works...

**Comment by plrthink** [comment]
@kristianmandrup Just like what described in docs, provide `hideNavBar` prop to `Route` or `Router` component will toggle the navbar.

**Comment by kristianmandrup** [comment]
Thanks, I resolved it now. Wasn't aware from docs that the navbar would autodisplay given the routing stack by default. I thought I actively had to hook it up somehow.
The `NavBar` file in the Example tricked me into thinking I had to use it. Not used I think?

**Comment by plrthink** [comment]
@kristianmandrup I think it's used for customizing the navbar, something like you want a button on the right.

**Comment by plrthink** [comment]
@aksonov Is it fixed already?

**Comment by aksonov** [comment]
Please check latest 3.0 release

Pavel.

**Comment by plrthink** [comment]
@aksonov Awesome!

**Comment by flavordaaave** [comment]
I'm still having kind of this issue with version `3.35.0`. When swiping to go back from a scene that HAS a navbar to a scene that HAS NO navbar, the navbar for the scene that should NOT have one is visible and only appears as soon as the transition is completed.

I'd expect that even during the swipe transition, the navbar is NOT visible for the previous scene. Is there a solution to achieve this?
