### ISSUE TITLE
App Goes Back To Initial Route On Hot Module Reload

### ISSUE THREAD

**Issue by thecodecafe** [aksonov/react-native-router-flux#3081]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.43.0
- react-native v0.55.4

### Expected behaviour
Maintain current route after hot module reload occurs.

### Actual behaviour
Whenever hot module reload occurs, the app returns to the initial route, this is inconvenient because I have to start navigating all the way deep in to the screen I was on, and in most cases it's just  a small change, this makes development very painstaking, is there something I can do about this?

### Steps to reproduce
My Router is connected to redux and I used `Actions.create(/**/)` to create the scenes.

**Comment by Blapi** [comment]
Use the scene you want to test as initial

Your issue is actually not an issue.. it is a common behaviour and it totally makes sense

**Comment by thecodecafe** [comment]
I can't agree that it makes sense, navigating all the way back to the screen you're working on because of a small adjustment you made to it isn't convenient, it kills my vibe when I'm working.
