### ISSUE TITLE
Problem installing flux router (code ENOGIT)

### ISSUE THREAD

**Issue by mostafa5731** [aksonov/react-native-router-flux#3082]
### Version
Tell us which versions you are using: 
- react-native v0.55.4

I'm justified in installing this error:

E:\ReactNative\react native\P\app3_part19>npm i react-native-router-flux --save
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/react-navigation/react-native-tab-view.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mostafa\AppData\Roaming\npm-cache\_logs\2018-06-14T10_43_36_962Z-debug.log

I can not install this package at all. please guide me.

**Comment by Blapi** [comment]
`npm ERR! Please check if you have git installed and in your PATH.`

**Comment by mohammad1374** [comment]
داداش گیت و دانلود کن و نصب کن بعدش این دستور و توی ترمینال ویندوز بزن اوکی میشه

download and install git then enter this command in cmd
