### ISSUE TITLE
Deep Linking is not working

### ISSUE THREAD

**Issue by j3rin** [aksonov/react-native-router-flux#3083]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.50.1

I was able to open the app when I send app name://pagename, but it doesn't direct me to the page name. attaching the code below, I set up everything on info list and AppDelegate

			<Scene key="root">

			<Scene key="tabs" tabs={true} showLabel= {false} unmountScenes={false}  tabBarStyle={styles.tabNavigator} pressOpacity={1} type={ActionConst.RESET} >
				<Scene key="Home"
					initial={true}
					component={Home}
					hideNavBar 
					icon={props => ( 
						<TabIcon
           	 tab_icon="Book"
							tab_title="Recipes"
							selected={props.focused}
						/>
			  		)}>
			  </Scene>

			<Scene key="search" path = {"search"}			
			component={Search} 
			hideNavBar
	
			icon={props => (
			  <TabIcon
			  tab_icon="Search"
				tab_title="Search"
				selected={props.focused}
			/>
			)}>
		  </Scene>
			
			
			<Scene key="favorite"
			path = {"favorite"}			
			component={Favorite} hideNavBar
		  icon={props => (
				<TabIcon
				tab_icon="Heart"
				tab_title="Favorites"
				selected={props.focused}
		  />
		  )}>
		</Scene>	
		<Scene key="devices"

		component={Device} 
		hideNavBar 
		icon={props => (
		  <TabIcon
		  tab_icon="Cloud"
			tab_title="Devices"
			selected={props.focused}
		/>
		)}>
		
	  </Scene>
	  <Scene key="settings"

		component={Settings} 
		hideNavBar
	  icon={props => (
			<TabIcon
			tab_icon="Settings"
			tab_title="Settings"
			selected={props.focused}
	  />
	  )}>
	  
	</Scene>
		
			</Scene>
			<Scene key="intro" direction="leftToRight" type='reset' component={Intro} hideNavBar={true} title="Intro" initial={false}/>

**Comment by taichi-jp** [comment]
I've encountered the same issue using iOS simulator.
It works after I shutdown the app, but when the app is running, it only reopen the app, not directing to the page. I used the following command:
```
xcrun simctl openurl booted "my-app://path/to/the/page"
```

**Comment by taichi-jp** [comment]
@j3rin 
I resolved the problem, it works now!
Check out the configuration in `AppDelegate.m` .
https://facebook.github.io/react-native/docs/linking
