### ISSUE TITLE
_reactNativeRouterFlux.Actions.tab_4 is not a function

### ISSUE THREAD

**Issue by mjstelly** [aksonov/react-native-router-flux#3084]
### Version
Tell us which versions you are using: 

"react-native-router-flux": "^4.0.0-beta.31"
"react": "^16.4.1",
"react-native": "^0.55.4",

### Expected behaviour
When `tab_4` is clicked, display tab contents

### Actual behaviour
App throws error
![simulator screen shot - iphone 6 - 2018-06-15 at 15 18 13](https://user-images.githubusercontent.com/313819/41485907-5e8bb5aa-70b0-11e8-93aa-396de1ce81cf.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

1. Launch app
2. Select `Go to TabBar page`
3. Select `Switch to tab4`

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
