### ISSUE TITLE
Erro: [react-native-router-flux] Router should contain only one scene, please wrap you scenes with root Scene

### ISSUE THREAD

**Issue by BrNogueira** [aksonov/react-native-router-flux#3085]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0 beta.31
react-native-cli: 2.0.1

### Expected behaviour

that the router could be accessed by my app!

### Actual behaviour

My code

import React from 'react';
import {Router, Scene, root } from 'react-native-router-flux';

import FormLogin from './Components/FormLogin';
import FormCadastro from './Components/FormCadastro';

export default props => (
	<Router>
		<Scene key = 'FormLogin' component={FormLogin} title ='Login' /> 
		<Scene key = 'FormCadastro' component={FormLogin} title ='Cadastro' /> 
	</Router>

	);

**Comment by Blapi** [comment]
There's no code to watch actually.

Moreover, the error message is clear enough, there should be one wrapper inside of your Router like this : 

```
<Router>
  <Stack key='root'>
    <Scene />
    <Scene />
    <Scene />
    <Scene />
    <Scene />
  </Stack>
</Router>
```

Check the Example project for more infos
