### ISSUE TITLE
Slowly switching screens in Tabs component will not mount them

### ISSUE THREAD

**Issue by SourceCipher** [aksonov/react-native-router-flux#3087]
### Version
Tell us which versions you are using: 

- react-native-router-flux: ^4.0.0-beta.31
- react-native: ^0.55.3

### Expected behaviour

When slowly changing the scenes in tab component by sliding left or right, the scene will mount

### Actual behaviour

I have 2 scenes within the tab and if I slowly slide to the right to switch the scenes, the next scene even when it switches, will not be mounted properly.  As seen [in this video](https://streamable.com/54xaj), when I switch to the next scene the header icon color will change, but it will not do it if I do it slowly and it will trigger the component only if I move a bit again.

### Steps to reproduce

See the video -> [Here](https://streamable.com/54xaj)

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
