### ISSUE TITLE
Going from one screen to the home screen does not work

### ISSUE THREAD

**Issue by NdozHH** [aksonov/react-native-router-flux#3088]
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
I have a password reset screen, I want you to press the back button of android, go back to the home screen

### Actual behaviour
The application is minimized by pressing the back button on the ForgotPassword screen.

### Steps to reproduce
This is my route stack
![imagen](https://user-images.githubusercontent.com/25773289/41521865-6fad11c2-7299-11e8-8251-24b8a33b171e.png)

And this is the code to overwrite the back button.
![imagen](https://user-images.githubusercontent.com/25773289/41521934-bc96831a-7299-11e8-86e3-27a8558fd931.png)

I've used pop, popTo, Actions.Home(), Actions.reset("Home"), but none of them work.

Additionally I want to know if this logic is added in the app.js or in the file of each component where you want to perform a certain action?

**Comment by Blapi** [comment]
If this may help you, when I need to overwrite the `backAndroidHandler` I'm doing this in the constructor of the Component I want to change the behaviour : 

```
    this.myComponentBackPressHandler = BackHandler.addEventListener('myComponentBackPress', () => {
      if (Actions.currentScene === 'myComponentKey' && someCondition) {
        doSomething()
        return true
      }
      return false
    })
```

And of course, I remove the eventListener in the `componentWillUnmount()`

What I think you're doing wrong is maybe using `Actions.state.index` there, are you sure that you haven't `reset` or `replace` your stack when going to your Password Component ?

**Comment by NdozHH** [comment]
Thanks for the answer. I used your example and it only works in debug mode, go back to the previous screen, but if I close the debug mode it still minimizes the application.

**Comment by Blapi** [comment]
Could you please try to put `key='root'` instead of your `key='App'` please ?

Also, try to put some logs to be sure you overwrite the `backAndroidHandler` in the Router

**Comment by Blapi** [comment]
You could check with `adb logcat` while testing your app without the debug mode :)

**Comment by NdozHH** [comment]
@Blapi It still doesn't work, I've done everything you recommended but it's still minimizing the application

Change my App.js 
![imagen](https://user-images.githubusercontent.com/25773289/41613876-843dbe92-73bc-11e8-8b00-af4071ac4ca2.png)

And I added the code to my ForgotPassword component constructor, plus, i checked that the if condition was true and it is, but it still works only in debug mode, i don't understand why or if i'm doing something wrong
![imagen](https://user-images.githubusercontent.com/25773289/41614025-eccedb30-73bc-11e8-853d-f36a9e6da233.png)

**Comment by NdozHH** [comment]
I was looking for and I found several people who had the same thing happen to them as to me about the events in the back button, which also worked in debugg mode but not in development mode, and I found this answer that worked for me

https://github.com/facebook/react-native/issues/3223#issuecomment-355064410

It may be useful for someone else or for RNRF managers to make future modifications. Thanks for the help.

**Comment by Blapi** [comment]
Happy you found the solution. Weird edge case but obviously it was not linked to this library.
