### ISSUE TITLE
Event when route changed?

### ISSUE THREAD

**Issue by FrankSalad** [aksonov/react-native-router-flux#309]
Is there a way to subscribe to these?

**Comment by crockpotveggies** [comment]
Not an author but chiming in. I think this is clearly described in the documentation, and is very easy to use if you're using Redux.

When using Redux, you can subscribe to the event in your reducer (via README):
```
Connect a <Router> to Redux
If you need to inform Redux of the navigation status (i.e. when you pop a route) just override the <Router> component included in react-native-router-flux with a connected one:

import ReactNativeRouter, { Actions, Router } from 'react-native-router-flux'
const Router = connect()(ReactNativeRouter.Router) 
Now when you use a <Router> it will be connected to the store and will trigger the following actions:

Actions.BEFORE_ROUTE
Actions.AFTER_ROUTE
Actions.AFTER_POP
Actions.BEFORE_POP
Actions.AFTER_DISMISS
Actions.BEFORE_DISMISS
``` 

And if you want to simply make a traditional subscribe (via README):
```
Also all route actions can be hooked by adding handlers for Actions.onPush, Actions.onReplace, Actions.onPop in your store(s).
```

**Comment by aksonov** [comment]
Check 3.0 release, now the component uses new React Native Navigation API and you may pass own reducer without subscription to 'event's. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
