### ISSUE TITLE
Back Icon Does Not Display On Android

### ISSUE THREAD

**Issue by thecodecafe** [aksonov/react-native-router-flux#3090]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.43.0
- react-native v0.55.4

### Expected behaviour
The back icon for the navbar does not show on android.

### Actual behaviour
The back icon does not display when i navigate to a new screen on android, but does in iOS

### Steps to reproduce
Below is what the scene looks like.
```
<Scene key='Login' component={LoginScreen} 
  hideNavBar={true} hideTabBar={true}
  backButtonImage={backIcon.icon}
  leftButtonIconStyle={[Styles.navbar.imageIcon, Styles.navbar.back]}
  navigationBarStyle={Styles.navbar.container}/>
```

It's quite sad I've come so far into the project i'm in only to realise so many problems with this package.
:(

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
