### ISSUE TITLE
How to avoid opening the page two times

### ISSUE THREAD

**Issue by nfq6612** [aksonov/react-native-router-flux#3091]
- react-native-router-flux v4.
### Expected behaviour
How to avoid opening the page two times

**Comment by nfq6612** [comment]
When I double click ,the page opening two times.
`
onclick=()=>{
Actions.push('login');
}
`

**Comment by MaxInMoon** [comment]
@nfq6612 I'm thinking about something like this:


```javascript
onPress={() => {
  const currentScene = Actions.currentScene;
  if (currentScene !== 'login') {
    Actions.push('login');
  }
}}

```

**Comment by aksonov** [comment]
Please check latest beta.40, it should solve this issue

**Comment by jackychanfox** [comment]
no, this issue is happening yet

**Comment by Kuhne1** [comment]
The problem exists on 4.0.6, Downgraded to 4.0.1 and the double click issue is gone.
