### ISSUE TITLE
How do I insert a scene in Tabs, without placing it in the TabsBar?

### ISSUE THREAD

**Issue by sinevitch** [aksonov/react-native-router-flux#3092]
![image](https://user-images.githubusercontent.com/35930695/41715062-ef85c8e4-755a-11e8-853a-265eb46960db.png)

![image](https://user-images.githubusercontent.com/35930695/41715093-0867d6b8-755b-11e8-9aec-6b27c6327a8a.png)

**Comment by dextermb** [comment]
I've found myself needing an answer for this too. That or being able to render tabs from a scene that is not nested within `Tabs`.

**Comment by AlexCatch** [comment]
From a UX perspective, you're looking a modal rather than replacing a tab screen, only scenes inside a tab bar will be rendered with a tab bar because they're the core sceeens of the app.

Any additional views like edit profile screens etc should be presented as modals.

**Comment by aksonov** [comment]
@AlexCatch is right, closing this ticket.

You may try to use `clone` attribute, but I didn't test it for Tabs (only for Stack)
