### ISSUE TITLE
[mobx] Warning: there are multiple mobx instances active

### ISSUE THREAD

**Issue by Symous** [aksonov/react-native-router-flux#3093]
### Version
Tell us which versions you are using: 

- react-native-router-flux: 4.0.0-beta.31
- react-native: 0.45.1

- my own mobx/mobx-react: 3.2.2/4.2.2 

### Description
I already have integer mobx in my application before. after I upgrade my react-native-router-flux from v3.x to v4.0 , I see this waring : there are multiple mobx instances active , but it seems like that have not bring any influence to my application . but please how can I fix this ? thanks.

### Steps to reproduce
1. install react-native-router-flux v3.x to a application that already installed mobx;
2. upgrade the react-native-router-flux to v4.0

related issue: #2155

**Comment by Maxence-Machu** [comment]
Same here

**Comment by mrkhoros** [comment]
I looked into this issue, and the only way around it is to not use react-native-router-flux and find an alternative apparently

**Comment by spiritman110** [comment]
I'm having the same problem. Would love to see this issue addressed. 

Currently using versions:
"mobx": "^5.0.3",
"mobx-react": "^5.2.3",
"react-native-router-flux": "^4.0.0-beta.31"

Any help would be appreciated! Thank you!

**Comment by aksonov** [comment]
Latest version doesn't use mobx, closing it

**Comment by veereshamma** [comment]
[mobx] Warning: there are multiple mobx instances active #3093
versions
react": "16.9.32
mobx-react": "6.1.4
