### ISSUE TITLE
Drawer's default scene Reloads Twice

### ISSUE THREAD

**Issue by ankur-nd** [aksonov/react-native-router-flux#3096]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 
- react-native v0.55.4

### Expected behaviour
On signing-in the default scene of navigation drawer should load just once i.e. componentDidMount() and componentWillMount() should be called just once. 

### Actual behaviour
On signing-in the default scene of navigation drawer's componentDidMount() and componentWillMount() gets called twice. 

### Steps to reproduce
I have a scene 'alertsView' which is supposed to be the default scene i.e. if back is pressed from any scene, user should land at scene 'alertsView'. 
In order to work around this bug:
https://github.com/aksonov/react-native-router-flux/issues/2342

I went for wrapping scenes that are children of the Drawer in a Scene 'drawerRoot', so that the Drawer has one direct child Scene and then that child has components and list Scenes.

Snippet from my router file:
           
```
<Drawer
            key="main"
            contentComponent={DrawerMenu}
            hideNavBar
            initial={loginState === LOGGED_IN}
            drawerOpenRoute="DrawerOpen"
            drawerCloseRoute="DrawerClose"
            drawerToggleRoute="DrawerToggle">

           
            <Scene
              key="drawerRoot"
              hideNavBar>
              <Scene
                key="alertsView"
                component={AlertsView}
                hideNavBar={false}
                initial={loginState === LOGGED_IN}
              />


              <Scene
                key="GZchart"
........
.......

```

**Comment by china-english** [comment]
Same issue here.

- "react": "16.3.1"
- "react-native": "0.55.4"
- "react-native-router-flux": "^4.0.0-beta.31"

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
