### ISSUE TITLE
   Requiring unknown module "780".If you are sure the module is there, try restarting Metro Bundler. You may also want to run `yarn`, or `npm install` (depending on your environment). 

### ISSUE THREAD

**Issue by Nisharunnisaa** [aksonov/react-native-router-flux#3098]
### Version

   "moment": "^2.22.2",
    "react": "16.3.1",
    "react-moment": "^0.7.7",
    "react-native": "0.55.4",
    "react-native-pathjs-charts": "0.0.34",
    "react-native-side-menu": "^1.1.3",
    "react-native-svg": "^6.3.1",
    "react-navigation": "^2.5.3"
![screenshot_1530118166](https://user-images.githubusercontent.com/38999595/41988051-9b732186-7a58-11e8-84c6-200441d01285.png)

**Comment by aksonov** [comment]
Something wrong with your node_modules/packager. Please check Example project
