### ISSUE TITLE
Invariant Violation: View config not found for name RNSVGRect     

### ISSUE THREAD

**Issue by Nisharunnisaa** [aksonov/react-native-router-flux#3099]
### Version
Tell us which versions you are using: 

`"dependencies": {
    "prop-types": "^15.6.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-charts": "^3.0.0",
    "react-native-pathjs-charts": "0.0.34",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-svg": "^6.3.1"
  },
  "devDependencies": {
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.2.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }`
![screenshot_1530192908](https://user-images.githubusercontent.com/38999595/42037790-e4d66dfc-7b06-11e8-8cac-31d535f38bf1.png)

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by hungdev** [comment]
i think the error of react-native-svg or react-native-pathjs-charts

**Comment by rayjadore** [comment]
same issue

**Comment by aksonov** [comment]
Not related to RNRF
