### ISSUE TITLE
Getting "props should be defined for stack"

### ISSUE THREAD

**Issue by joshbedo** [aksonov/react-native-router-flux#310]
Trying to install `react-native-router-flux` but i can't seem to get past this error, does anyone have any ideas on how i can fix it?

![](http://imgur.com/HqwLhPL.jpg)

**Comment by aksonov** [comment]
Don't use 3.0alpha, it is not ready yet

Pavel.

**Comment by joshbedo** [comment]
Awesome, downgrading to 2.3.1 solved my problem! By default npm downloads the alpha version.

**Comment by sashafklein** [comment]
@aksonov -- I'm getting this with 3.1.3 -- which as of 3 days ago is [an official release](https://github.com/aksonov/react-native-router-flux/releases). Should I also downgrade to a 2.0 version? Or am I potentially doing something wrong?

**Comment by aksonov** [comment]
Check Example project. v3 has different API.
