### ISSUE TITLE
Multiple instances of Mobx in v4

### ISSUE THREAD

**Issue by Hypothesis-github** [aksonov/react-native-router-flux#3100]
I am using
```
 "mobx": "^4.3.1",
    "mobx-react": "^5.2.3",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-router-flux": "^4.0.0-beta.31"
```

and I have gotten the multiple instances since I was already using `mobx `in react native for routing.
I tackled this ( or at least I think I tackled this) by the instruction provided by the author of react-native-router-flux, which is to search for duplication of `mobx `in modules, and sure there were 2 extra in `react-native-router-flux`'s node module folder.
package.json also contained a lower version of `mobx `and `mobx-react` , I believe v3 or mobx.
so I deleted both folders and the dependency in the package.json and refreshed.
the warning of multiple instances went away. but I have some concerns now.

1. `Npm install` brings back both folders of mobx and mobx-react to the module folder of react-native-router-flux. How can I make sure these 2 dependencies will never come back since I deleted the line in `react-native-router-flux`'s package.json as dependency but they still get installed after` npm install`.

2.  Why the `mobx `and `mobx-react` exist in the module folder of `react-native-router-flux`, and if of course they are handling some actions will they be interrupted because I have deleted the folders manually ?

**Comment by mrkhoros** [comment]
mentions:aTable the latest is 4.0.0-beta.31, I cannot see 32 in the release list [https://github.com/aksonov/react-native-router-flux/releases](url)

**Comment by aTable** [comment]
I guess it's an unofficial beta at this stage

` npm i react-native-router-flux@4.0.0-beta.32`

**Comment by catherinetcai** [comment]
If for some reason you don't feel like bumping the version, I was able to workaround this using yarn and resolutions, as outlined [here](https://stackoverflow.com/questions/49429718/there-are-multiple-mobx-instances-actives).

**Comment by aksonov** [comment]
Latest version no longer uses mobx, closing it.
