### ISSUE TITLE
Open multiple instances of one scene

### ISSUE THREAD

**Issue by jay7707** [aksonov/react-native-router-flux#3101]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55.4

I have category and subcategory1,2,3,N wants to open the same scene with different data also stack should maintain. but now it is not working anything. It supposes to open multiple time but not working

Here is my router file
  `<Router>
            <Stack key="root" hideNavBar>
                <Scene key="login" component={Login} hideNavBar initial/>
                <Scene key="main" tabs={true}  >
                    <Scene key="directory" title="Directory" icon={({ focused }) => { return renderIcons("search", focused) }} >
                        <Scene key="category" component={Category} title="Directory" />
                        <Scene key="contact" component={Contacts} title="Contacts" />
                        <Scene key="profile" component={Profile} title="Profile" />
                    </Scene>
                    <Scene key="notes" title="Notes" icon={({ focused }) => { return renderIcons("create", focused) }}>
                        <Scene key="notesList" component={Notes} title="Notes" />
                        <Scene key="noteDetail" component={NotesDetail} title="Notes" />
                        <Scene key="addnote" component={AddNote} hideNavBar />
                    </Scene>
                    <Scene key="settings" component={Settings} icon={({ focused }) => { return renderIcons("settings", focused) }} title="Settings"  />
                    <Scene key="myprofile" component={Profile} icon={({ focused }) => { return renderIcons("ios-contact", focused) }} title="Profile" />
                </Scene>
            </Stack>
        </Router>
`

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
