### ISSUE TITLE
initial scene not working when re-open the app

### ISSUE THREAD

**Issue by Symous** [aksonov/react-native-router-flux#3102]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.31
- react-native v0.45.1

### Description
I have 2 scene in my app:
```
<Scene key="home" component={HomePage} initial={false} type={ActionConst.REPLACE}/>
<Scene key="splash" component={SplashScreen} hideNavBar initial={true} />
```
in the splash scene, I make it do some initial worksand then  Actions.home({ type: ActionConst.REPLACE }) to home scene.

### Expected behaviour
As expected, each time when the app is start , it will open "splash" and then reset to home

### Actual behaviour
In Android, when I am in home scene and press the back button, the app closed. but when I re-open the app it seems like that the app have not come into the splash scene but come into home scene directly...

### Steps to reproduce
1. create 2 scene and one of them marked it as initial scene
2. in the initial scene reset to another scene
3. and press android back button to close the app
4. when we re-open, the app will come into another scene

#### PS
My app used to integer with react-native-router-flux v3.x before and it works very well. I met this issue after I upgrade to v.4.

**Comment by mswokk** [comment]
Did you find any workaround for this issue?

**Comment by Symous** [comment]
@mswokk not yet friend, this only appeared with Android, so I have to write a native module to force to kill the app manually. :(

**Comment by aksonov** [comment]
Sorry, Android maintainer is really wanted, I'm using iOS right now.

**Comment by aksonov** [comment]
cc @daviscabral

**Comment by daviscabral** [comment]
I am on it :+1:

**Comment by aksonov** [comment]
@Symous have you tried latest version? Could you reproduce this issue with Example project?

**Comment by daviscabral** [comment]
@symous I cant reproduce it here. Closing due inactivity - but let me know if the last version haven’t fixed it for you.
