### ISSUE TITLE
navbar background color animation is buggy with different background colors while navigating.

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3105]
### Version
Tell us which versions you are using: 
4.0.0-beta.31

### Expected behaviour
A smooth header background transition when background colors are different.

### Actual behaviour
When navigating between scenes with different header background colors, everything is smooth . except the background color animation.  It seems to switch colors right away (makes it look buggy) and when navigating back with a swipe gesture the background color will not change until completed.

Here are a couple images to give you a better idea: 

<img width="702" alt="screen shot 2018-06-30 at 4 45 13 pm" src="https://user-images.githubusercontent.com/8635153/42128962-1a3bfbae-7c85-11e8-82e8-d05e4b30658e.png">
<img width="683" alt="screen shot 2018-06-30 at 4 45 52 pm" src="https://user-images.githubusercontent.com/8635153/42128963-1a494890-7c85-11e8-9f80-6d3cf3e90b9e.png">

Cheers.

**Comment by aksonov** [comment]
Please check latest 4.0.0-beta.40 version
