### ISSUE TITLE
Lightbox background not displaying the initial screen but displays a white background

### ISSUE THREAD

**Issue by repapa** [aksonov/react-native-router-flux#3109]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55.3

### Expected behaviour
Should see the initial screen when navigating to a Lightbox Scene

### Actual behaviour
<img width="367" alt="screen shot 2018-07-02 at 8 38 44 pm" src="https://user-images.githubusercontent.com/19182530/42164223-f09d0464-7e37-11e8-921f-d2ee906089c1.png">

My Implementation:
Router.js
<img width="614" alt="screen shot 2018-07-02 at 8 34 40 pm" src="https://user-images.githubusercontent.com/19182530/42164306-3c11148a-7e38-11e8-8469-75eeb8e4dddd.png">

DemoLightBox.js (from Example project)
<img width="667" alt="screen shot 2018-07-02 at 8 35 06 pm" src="https://user-images.githubusercontent.com/19182530/42164329-4c01595e-7e38-11e8-90fc-9fb264f8650c.png">

BaseLightBox (from Example project)
<img width="362" alt="screen shot 2018-07-02 at 8 35 34 pm" src="https://user-images.githubusercontent.com/19182530/42164350-5c8f0fa0-7e38-11e8-805a-49ad3172a16e.png">

**Comment by aksonov** [comment]
Please check Example, it uses Lightbox with semi-transparent background
