### ISSUE TITLE
Duplicate scene when Actions.push to child in Stack or Scene group

### ISSUE THREAD

**Issue by zealgt** [aksonov/react-native-router-flux#3112]
### Version

  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-router-flux": "4.0.0-beta.31"
  },

### Expected behaviour

When I click "Go to register" it should have only one Register's scene mounted.

### Actual behaviour

I got double scenes Register have mount, When you click back Register button then back to Register scene again.
So I'm not sure, Is it a bug or feature?

### Steps to reproduce

```javascript
const Home = (props) => (
  <View style={styles.container}>
    <Text onPress={() => Actions.register()}>
      Go to register
    </Text>
  </View>
)

const Register = (props) => (
  <View style={styles.container}>
    <Text>Register</Text>
  </View>
)

const Register2 = (props) => (
  <View style={styles.container}>
    <Text>Register2</Text>
  </View>
)

export default App = () => (
  <Router style={styles.container}>
    <Scene key="root">
      <Scene key="home" component={Home} title="Home" />
      <Stack key="group1" title="group1">
        <Scene key="register" component={Register} title="Register" />
        <Scene key="register2" component={Register2} title="Register2" />
      </Stack>
    </Scene>
  </Router>
)
```

### My solution

use ```Actions.group1()``` instead of ```Actions.register()```

**Comment by aksonov** [comment]
Your solution is right. Yes, it is 'feature' - first Scene is already part of stack.

**Comment by digitaldavenyc** [comment]
This saved me a bunch of time!
