### ISSUE TITLE
 I would like to reload data when go back from Scene B to Scene A

### ISSUE THREAD

**Issue by matteocollina** [aksonov/react-native-router-flux#3113]
### Version
- react-native-router-flux v4.0.0-beta.31
- react-native: v0.55.4

### Actual behaviour
- From "A" => Actions.push("B")
- When press "back" on "B", I would like to reload data (or override a method) on "A", like a "**onResume**" on Android. 

Is it possible?

![schermata 2018-07-04 alle 23 25 11](https://user-images.githubusercontent.com/8715726/42294492-85a2b540-7fe1-11e8-8cdc-e6032854a646.png)

**Comment by aksonov** [comment]
You may use `Actions.pop({refresh: data})`

**Comment by yogendrajs** [comment]
> You may use `Actions.pop({refresh: data})`

@aksonov 
This doesn't seem to be working! Can you provide any working examples for this?

**Comment by xenos28** [comment]
> > You may use `Actions.pop({refresh: data})`
> 
> @aksonov This doesn't seem to be working! Can you provide any working examples for this?


Try: 
`  
Actions.pop();
Actions.refresh({propsKey: propsValue});
`
Or use refs
`
Actions.pop();
Actions.refs.SceneName.refreshMethod();
`
