### ISSUE TITLE
popTo can't find scene

### ISSUE THREAD

**Issue by SexySix** [aksonov/react-native-router-flux#3118]
### Version

- react-native-router-flux v4.0.0-beta.32 (v3 is not supported)
- react-native v0.52.3

### Code

my code like following:
```
    <Router>
        <Modal hideNavBar>
          <Stack
            key="mainStack"
          >
            <Tabs
              key="tab"
            >
              <Scene key="home"/>
            </Tabs>
            <Scene key="some"/>
          </Stack>
          <Stack key="loginStack">
            <Scene key="login"/>
            <Scene key="register"/>
          </Stack>
        </Modal>
      </Router>
```

### Expected behaviour

When current scene is 'register', `Actions.popTo('home')` should back to 'home'

### Actual behaviour

When current scene is 'register', `Actions.popTo('home')` doesn't work.
And In 4.0.0-beta.31, it works.

#3043 may cause this bug.

P.S.My English is poor. Sorry.

**Comment by aksonov** [comment]
Please check latest 4.0.0-beta.40, Example Login->Login2->login3->popToRoot uses popTo function
