### ISSUE TITLE
renderRightButton Actions.refresh() not working

### ISSUE THREAD

**Issue by zouminhuababa** [aksonov/react-native-router-flux#3119]
"react-native": "0.55.4"
"react-native-router-flux": "^4.0.0-beta.31"

in my code :
    renderRightButton = () => (
        <TouchableOpacity
          onPress={() => {
              DeviceEventEmitter.emit(TYPE.EDIT_ADDRESS_BOOK);
          }}
        >
            <Text style={{ color: '#33ccff', fontSize: 20, marginRight: 20 }}>Edit</Text>
        </TouchableOpacity>
        )

    componentDidMount() {
        Actions.refresh({ renderRightButton: this.renderRightButton });
    }

**Comment by zouminhuababa** [comment]
using right insteadof renderRightButton

**Comment by fozhao** [comment]
I saw quite a few people mentioning the `setTimeout` fix. I tried it with `renderRightButton`, didn't work. However, using right does work. Thanks @zouminhuababa, life saver. And I am surprised that I can't find `right` in any API doc. @aksonov, is that deprecated or something else?
