### ISSUE TITLE
Navigation Titile on Android is in additional View instead of just being Text 

### ISSUE THREAD

**Issue by yuilsang** [aksonov/react-native-router-flux#312]
https://github.com/aksonov/react-native-router-flux/issues/98
https://github.com/exponentjs/ex-navigator/issues/24

- I have the same problem with the link.
- The solution is https://github.com/delta1/react-native-router-flux/commit/fd9812c06b6339e0844f5f9795276ebff83d85dd (ExRouter.js)
- Please add features. ^^

thank you.

**Comment by aksonov** [comment]
Check 3.0 release, now the component uses new React Native Navigation API. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
