### ISSUE TITLE
Very confused about the lightbox...

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3120]
Version: 4.0.0-beta.28

Hi all.

After doing some looking around in the docs and online, I haven't had any luck with this Lightbox. I am trying to display an image full screen with its props when pressed in my grid but it seems like I'm doing something wrong?

```
import { Scene, Router, Drawer, Stack, Actions, Lightbox } from 'react-native-router-flux';

<Lightbox>
     <Scene
         key="imageFull"
         component={imageFull}
         title="Image"
     />
 </Lightbox>
```

Can someone direct me to a useful example? or show me what they have done to implement it? I would love some guidance. 

Cheers!

**Comment by aksonov** [comment]
Just check Example project that use it
