### ISSUE TITLE
Unable to Hook Into drawerClose Event

### ISSUE THREAD

**Issue by kylanhurt** [aksonov/react-native-router-flux#3121]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.51.0

### Expected behaviour

Howdy, we are using react-native-router-flux's <Drawer> component as our sidebar and we have some items in the sidebar that have Redux state. While apparently you can call `drawerClose` and `drawerOpen`, there is not an actual event (eg `onDrawerClose`) which we can hook into in order to reset the sidebar's Redux state. We want it reset so that when they re-open it the user will see a fresh sidebar (ie no persistence)

### Actual behaviour

No callback / event to hook into for the closing of the drawer (eg if someone swipes it closed).

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Open sidebar / drawer
2. Close sidebar / drawer... there is no callback or event into which you can hook and attach on additional function calls

Any help would be appreciated. Thank you.

**Comment by aksonov** [comment]
With latest version you can see this for Example project:
```
2018-08-08 16:44:08.796 [info][tid:com.facebook.react.JavaScript] 'reducer: ACTION:', { type: 'Navigation/DRAWER_CLOSED', key: 'id-1533739425368-12' }
```

**Comment by vijayhfs** [comment]
@aksonov : I am using version 4.0.6 . But in my case also drawerOpen event in not firing. Here is my code snippet : 
```
<Drawer
            hideNavBar
            key="drawerMenu"           
            contentComponent={() => <TMenu  />}
            drawerWidth={250}
            drawerOpen ={()=>console.log('drawer open')}
            drawerPosition="left">
```
