### ISSUE TITLE
Keyboard will show up after calling Actions.reset() from a scene containing Text Input

### ISSUE THREAD

**Issue by BatDroid** [aksonov/react-native-router-flux#3122]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.28 (v3 is not supported)
- react-native v0.55.1

### Expected behaviour
when i don't want to return to previous scene (eg: after login/signup) i use Actions.reset("sceneKey") (in my case is Actions.reset("home")). since the page contains text input and the keyboard is up. first i make sure that the keyboard is dismissed and then i navigate to new scene.

### Actual behaviour
though the keyboard is fully dismissed in source scene (login/signup page), in destination scene(home) suddenly keyboard shows up for a few seconds and then get dismissed automatically. this bug doesn't happen when i navigate like this Actions.sceneKey() (eg: Actions.home()) but the problem is that user can pop to it which it is not what i want. i even tried 4.0.0-beta.31 but the bug was worse since the keyboard didn't show up in second scene but when user navigated to third scene it showed up like what i mentioned.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. make a scene which contains text input (and there will be a keyboard showing up)
2. using Actions.reset("sceneKey") or Actions.sceneKey({type: "reset"})
3. in destination scene you will see keyboard wont hide for a few seconds (if you haven't fully dismissed keyboard in source scene) or it will show up (if you are sure that the keyboard is dismissed first in the source scene)

**Comment by aksonov** [comment]
Please check latest version based on react navigation 2.x - 4.0.0-beta.40, it should be solved
