### ISSUE TITLE
How to hide the descriptions of tabs ?

### ISSUE THREAD

**Issue by Koshukey** [aksonov/react-native-router-flux#3130]
### Version
Tell us which versions you are using: 
"^4.0.0-beta.31"

### Expected behaviour

I want to hide descriptions of tabs.

### Actual behaviour

I cannot hide the descriptions.

<img width="349" alt="2018-07-16 10 22 53" src="https://user-images.githubusercontent.com/31874274/42740422-450e0bf6-88e2-11e8-86d1-f81f6445a993.png">

**Comment by Koshukey** [comment]
@dextermb  Thanks it worked !!!

**Comment by dextermb** [comment]
@Koshukey 👍 be sure to close this thread then
