### ISSUE TITLE
ActionConst.BACK vs ActionConst.BACK_ACTION

### ISSUE THREAD

**Issue by sajaddp** [aksonov/react-native-router-flux#3134]
Hi,
What is the difference between `ActionConst.BACK` and `ActionConst.BACK_ACTION` in v4?

**Comment by dextermb** [comment]
There doesn't seem to be a difference. Check out the API table [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md).

| Property | Type | Value | Shorthand |
|-----------------|----------|----------|--------------------------------------------|
| `ActionConst.BACK` | `string` | 'REACT_NATIVE_ROUTER_FLUX_BACK' | `pop` |
| `ActionConst.BACK_ACTION` | `string` | 'REACT_NATIVE_ROUTER_FLUX_BACK_ACTION' | `pop` |
