### ISSUE TITLE
Receive the whole scene from navigation stack 

### ISSUE THREAD

**Issue by sajaddp** [aksonov/react-native-router-flux#3138]
Hello,

### Version
- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

How can I see and receive the list from the whole scene off the nav stack? Take, for example,
the user navigates from **screen A to the screen B, then C, after that D**. Therefore, we intend to have a stack like the mentioned example in bold: D,C,B,A

**Comment by aksonov** [comment]
`Actions.state` contains all navigation state.
