### ISSUE TITLE
Issue with flashing on load of scene

### ISSUE THREAD

**Issue by mcoder14** [aksonov/react-native-router-flux#3139]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.55.3

### Expected behaviour
I want the scene to load without any flashes

### Actual behaviour
The scene flashes on every page transition even with duration={0}

### Steps to reproduce
```
<Scene key="root" hideNavBar duration={0}>
          {
            require("./main/mainScreens")
          }
</Scene>
```
and then the required section 
```
module.exports = <Scene key="main" duration={0}>
  <Scene key="landing"
    component={LandingPage}
    title="Landing"
    initial
    hideNavBar
    duration={0}
  />
</Scene>;
```

**Comment by aksonov** [comment]
Have you tried it without export? I don't see any flashes for Example project, please check

**Comment by aksonov** [comment]
Closed due inactivity, feel free to reopen it with recorded video for the issue with Example project.
