### ISSUE TITLE
improve docs for right navbar item, including onRight

### ISSUE THREAD

**Issue by kristianmandrup** [aksonov/react-native-router-flux#314]
Tried to render a hamburger menu item in the navbar of my initial route:

```js
<Route name="launch" initial={true} component={ChatRoomScreen} wrapRouter={true} hideNavBar={false} title="Home" rightTitle="menu" onRight={Actions.drawer}/>
```

The docs for displaying the right nav button are a little unclear. With this setup, nothing is displayed, however changing to this works:

`onRight={() => {Actions.drawer() }}`

**Comment by aksonov** [comment]
3.0 release should solve this problem. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
