### ISSUE TITLE
What is the way to view the current pages stack?

### ISSUE THREAD

**Issue by nfq6612** [aksonov/react-native-router-flux#3143]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 
-  react v16.3.2
-  react-native v0.53.0

### Expected behaviour
for example : where I open page A、page B、page C, the  pages navigation stack Is :A->B->C .
                     What is the way to view the current pages stack?

**Comment by aksonov** [comment]
`Actions.state`
