### ISSUE TITLE
[Drawer] Horizontal ScrollView inside Drawer

### ISSUE THREAD

**Issue by protectmeoleg** [aksonov/react-native-router-flux#3144]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 
- react-native v0.56.0

### Expected behaviour
ScrollView should respond to right swipe gesture

### Actual behaviour
ScrollView do not respond to right swipe gestures, because of Drawer gestures

### Steps to reproduce
1. Add Drawer
2. Add Horizontal ScrollView inside drawer

![ezgif-5-eb2f1bc5bd](https://user-images.githubusercontent.com/37074297/43147154-10457f46-8f6b-11e8-9fdf-dc45a94c8851.gif)

**Comment by misuna1997** [comment]
Any suggestions on this?

**Comment by aksonov** [comment]
Please check latest version based on react navigation 2.x - 4.0.0-beta.40. If the problem exist, reproduce it with react navigation examples and create the issue there (because RNRF uses react navigation)
