### ISSUE TITLE
How to hide, dismiss keyboard on every navigation change?

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#3148]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta31 (v3 is not supported)
- react-native v0.53.3

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
Hi guys, I'd like to dismiss, hide keyboard on every navigation state change. How do I implement behaviour?

**Comment by aksonov** [comment]
Please check latest version based on react navigation 2.x - 4.0.0-beta.40, it should hide Keyboard automatically now.

**Comment by pistonsky** [comment]
It hides, but with a significant delay, especially on iOS.

On iOS it should ideally animate keyboard hiding as user swipes back. Is there a way to implement that?
