### ISSUE TITLE
Multiple navigationBar buttons with renderRightButton

### ISSUE THREAD

**Issue by kaifaust** [aksonov/react-native-router-flux#315]
I want two buttons on the right side of the navigationBar.

I want to be able to pass an array of my buttons like this: 
`renderRightButton={[this.searchButton, this.newButton]}` 
but it gives me this error:
`this.route.props.renderRightButton.bind is not a function`.

Note: padding a single button here that isn't an array works...

**Comment by aksonov** [comment]
Check docs carefully. renderRightButton is _closure_ (function) not array.

**Comment by beebase** [comment]
So is it possible to render multiple buttons and where in the docs can I find an example?
