### ISSUE TITLE
Add a FAB that would be visible on specific scenes 

### ISSUE THREAD

**Issue by Moshikol** [aksonov/react-native-router-flux#3151]
### Version
Tell us which versions you are using: 

- react-native-router-flux": "^4.0.0-beta.31
- react-native": "0.55.4

### Expected behavior
I Want to add FAB (floating action button) that would be visible on all scenes that under my "tabs" scene parent is there a way to add the  FAB to the tab navigation bar without wrting a whole new component that would handle the animations of the changed tabs and so on? 
I don't want to add the FAB to each scene in separate because I want it to stay in an absolute position when moving between tabs 

There is my router code :

![image](https://user-images.githubusercontent.com/19548879/43396551-951e24cc-940a-11e8-92aa-05da1a83a409.png)

Thanks In Advance !

**Comment by aksonov** [comment]
Please check Example project, it has MessageBar that is very similar for your goals (i.e. global for all screens).

**Comment by Moshikol** [comment]
I did check the example project but I didn't find a way to use the overlay component only on my scenes that under the tabs parent scene
