### ISSUE TITLE
Header title not centered when there is a right/left button

### ISSUE THREAD

**Issue by mdelclaro** [aksonov/react-native-router-flux#3153]
### Version
Tell us which versions you are using: 

- react-native-router-flux@4.0.0-beta.31
- react-native@0.56.0

### Expected behaviour
Header title to be centered

### Actual behaviour
![image](https://user-images.githubusercontent.com/32961172/43414029-fbafe6b0-9407-11e8-95bc-450995328f48.png)

**Comment by aksonov** [comment]
Please check latest version based on react navigation 2.x - 4.0.0-beta.40

**Comment by aksonov** [comment]
Android maintainer is really wanted, I'm using iOS right now.

**Comment by daviscabral** [comment]
I am back on Android - most of my users are Android. Now I am with several AVDs on my mac to test - so I can help with that.

**Comment by aksonov** [comment]
@daviscabral Great. Hopefully I solved the non-trivial problem with`popTo` and also restored `reducer` support, so please check beta.40 and let's close all issues now ;)

**Comment by MattyK14** [comment]
Seems the header is no longer centered after upgrading to `react-native@0.55`. Tested with `beta.42` & `beta.31`. `beta.31` is fine on `react-native@0.54` whereas `beta.42` just doesn't run, both are off center on `react-native@0.55`.

**Comment by aksonov** [comment]
So what is expected/actual  (RN0.55)?

**Comment by MattyK14** [comment]
Expected (seen on RN 0.54 & previous versions):


![screen shot 2018-08-09 at 1 23 05 pm](https://user-images.githubusercontent.com/16196171/43910451-6cc8aa86-9bd7-11e8-8781-ce9eb39a95bb.png)

Actual (seen on RN 0.55):

![screenshot_1533829160](https://user-images.githubusercontent.com/16196171/43910471-7af438f0-9bd7-11e8-8e8a-9f0b344f7ed8.png)

**Comment by daviscabral** [comment]
Fixed on #3256. 

[![Image from Gyazo](https://i.gyazo.com/84990e04356ed387ceb50ca99d448a5a.gif)](https://gyazo.com/84990e04356ed387ceb50ca99d448a5a)
