### ISSUE TITLE
Tab navigation mounting any screens with a large delay

### ISSUE THREAD

**Issue by SourceCipher** [aksonov/react-native-router-flux#3154]
### Version
Tell us which versions you are using: 

- react-native-router-flux: ^4.0.0-beta.31
- react-native: 0.55.4
- Developing for android only for now

### Expected behaviour

Scenes should be mounted instantly once the scene is set fully to the view

### Actual behaviour

It has 1-2s delay before the screen is mounted. Have in mind I am talking about the production app so no debugging issues here. Both screens have very minimal code. In fact, there is no logic in them at all. Just to show text with some styling for now.

My router for the tabs looks like this:

```
 <Tabs key="tabbar" showLabel={false} tabs={false} hideNavBar style={{ marginTop: -50 }} type={ActionConst.RESET}>
                    <Scene key="contacts" component={Contacts} hideNavBar type={ActionConst.RESET}/>
                    <Scene key="chats" component={Chats} hideNavBar initial={true} type={ActionConst.RESET}/>
                    <Scene key="profile" component={Profile} hideNavBar type={ActionConst.RESET}/>
                </Tabs>
```

------------------------------------------------------------------------------------------------------------------

_Is that the actual behavior of this library? If not can I somehow mount them all at once on the app load as I would like to show at least the styling of the screen before applying with the data once the data is loaded, but I cant do that as it gets mounted with this long delay (yes, 2 seconds is a century here)_

**Comment by aksonov** [comment]
Please check latest version based on react navigation 2.x

**Comment by SourceCipher** [comment]
@aksonov I switched the app navigator to the React Navigation, but I will test on my backed up app to see if there are any differences in speed at all

**Comment by aksonov** [comment]
Thank you, closing it
