### ISSUE TITLE
Navbar glitch on previous scene during transition while using custom navbar

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3156]
### Version
Tell us which versions you are using: 
4.0.0-beta.28

### Expected behaviour
Custom navbar doesn't make the previous screens navbar disapear during transition which causes a jumpy glitchy issue.

Is there something I am missing here? I am using hideNavBar on my scene and then in my component I am applying the customNavBar like the example. This bug/glitch is very frustrating as the only issue is the previous scenes nav bar disappearing when it should not be. I know this has been an issue for many people but there seems to be no solution yet - hopefully I am wrong.

I appreciate any guidance or assistance.

Cheers.

**Comment by aksonov** [comment]
Please check latest beta.40

**Comment by aksonov** [comment]
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists
