### ISSUE TITLE
deep linking on android not working?

### ISSUE THREAD

**Issue by muhamad-rizki** [aksonov/react-native-router-flux#3157]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
open specific scene when opening a url

### Actual behaviour
only open initialroute

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. i see the code and linking method on componentdidmount is not executed
2.
3.

**Comment by aksonov** [comment]
Please reproduce it with Example project and latest version.

**Comment by daviscabral** [comment]
@muhamad-rizki I might help you after getting a sample code.

**Comment by muhamad-rizki** [comment]
@daviscabral well here is code I used in my App.js:

`
             <MenuProvider ref={v => this.optionsMenu = v}>
                <View style={{
                    flex: 1
                }}>
                    <StatusBar
                        translucent={true}
                        backgroundColor="rgba(0,0,0,0)"
                        barStyle="light-content" />
                    <Router uriPrefix="stiami.ac.id">
                        <Lightbox key="lightbox">
                            <Stack key="root" hideNavBar transitionConfig={() => fadeIn(500)}>
                                <Scene key="splash" component={SplashScreen} hideNavBar initial={true} />
                                <Scene key="home" hideNavBar type={ActionConst.RESET}>
                                    <Scene key="dashboard" component={HomeScreen} hideNavBar />
                                </Scene>
                                <Scene path="/info" navTransparent key="info" component={InfoScreen} />
                            </Stack>
                            <Scene navTransparent key="downloadDetail" component={DownloadDetail} />
                        </Lightbox>
                    </Router>
                </View>
            </MenuProvider>
`

then I tried access link from my phone http://stiami.ac.id/info but it's still open a web browser.
is there anything I should configure on android folder? because the documentation is not clear enough,
I read on some website about deep linking on react native and it need to configure the AndroidManifest.xml (http://ihor.burlachenko.com/deep-linking-with-react-native/) I add intent filter:
`
<intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>

        <data android:scheme="http" />
        <data android:scheme="https" />
        <data android:host="stiami.ac.id" />
        <data android:pathPrefix="/" />
</intent-filter>
`
After that I tried to open a link and the apps is shown, but not triggering the linking on rnrf, only show the home screen, on the website I found it looks like I have to use RN Linking library, but when I see the RNRF source code I see that this Linking is already there, but did nothing, is there something went wrong with my code?

**Comment by aksonov** [comment]
@muhamad-rizki Sorry, but it is not about RNRF, but generic React Native Linking setup. Please create test github repo where deep linking WORKS without RNRF, but doesn't work with RNRF.

**Comment by muhamad-rizki** [comment]
allright then
