### ISSUE TITLE
LinkingManager.getInitialURL

### ISSUE THREAD

**Issue by msabaeian** [aksonov/react-native-router-flux#3158]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

App.js
```
export default class App extends Component {
  render(){
    return (
    <Router>
          <Scene key="root">
            <Scene key="Splash" component={Splash} hideNavBar  />
          </Scene>
      </Router>
    )
  }
}
```
Splash is just a simple react component

error:
TypeError: undefined is not an object (evaluating 'LinkingManager.getInitialURL')

![error](https://i.imgur.com/Fq72BjS.png "error")

how i can fix it?
thanks all

**Comment by aksonov** [comment]
https://facebook.github.io/react-native/docs/linking
