### ISSUE TITLE
When using navTransparent on iOS, the navbar area is non-responsive

### ISSUE THREAD

**Issue by Kelby2** [aksonov/react-native-router-flux#3159]
### Version
Tell us which versions you are using: 
"react-native-router-flux": "^4.0.0-beta.31",
"react-native": "0.55.1",

### Expected behaviour
If using navTransparent, you should be able to click on the area where the navbar would have been (component beneath it). (This is the behavior on Android, where you can continue to click in the area, drag, etc).

### Actual behaviour
This area does not respond to clicks:
<img width="259" alt="screen shot 2018-08-07 at 5 59 48 pm" src="https://user-images.githubusercontent.com/26385281/43805355-72ff330e-9a6d-11e8-9d10-59709088dcda.png">
I'm using navTransparent on this scene with the map but the navbar area does not respond to any panning or clicks. Ideally, I would have the searchbar up there, but it's un-clickable. I've tried playing around with zIndex's but nothing works. This only happens on iOS.

**Comment by aksonov** [comment]
Sorry, this component is wrapper around react navigation (i.e. adds own Router syntax and some syntax sugar). Feel free to check latest version (beta.40). If it still doesn't work, check react navigation demos and try reproduce the issue there.
