### ISSUE TITLE
Actions.jump() not working as it is supposed to

### ISSUE THREAD

**Issue by pakkibokati2012** [aksonov/react-native-router-flux#3160]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
        Actions.jump('tabbar', this.props.rowData) is supposed to send props to all children of scene with key 'tabbar'

### Actual behaviour
Props is sent to first child only
below is the scene heirarchy
<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul" 
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component= 
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component= 
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>

**Comment by pakkibokati2012** [comment]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
        Actions.jump('tabbar', this.props.rowData) is supposed to send props to all children of scene with key 'tabbar'

### Actual behaviour
Props is sent to first child only
below is the scene heirarchy
<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul" 
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component= 
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component= 
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>

**Comment by pakkibokati2012** [comment]
<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul"
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component=
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component=
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>

**Comment by pakkibokati2012** [comment]
``<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul"
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component=
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component=
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>

**Comment by pakkibokati2012** [comment]
`<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul"
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component=
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component=
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>`

**Comment by pakkibokati2012** [comment]
`<Scene key="tabbar" tabs tabBarPosition='bottom'>
          <Scene key='StepList' title='Steps' icon={TabIcon} back component={StepList} iconName="list-ul"
           swipeEnabled />
            <Scene key="See Site on Map" title="See Site on Map" icon={TabIcon} back component=
           {ShowMap} iconName="map-marker" swipeEnabled />
            <Scene key='Show Documents' title="Site Documents" icon={TabIcon} back component=
            {DocumentList} iconName="file-pdf-o" swipeEnabled />
</Scene>`

**Comment by aksonov** [comment]
Sorry, this functionality is not supported (jump with params), feel free to submit PR.

**Comment by aksonov** [comment]
Please check Example project and TabView.js with `Actions.tab_5_1({ data: 'test!' })`
