### ISSUE TITLE
A new feature about pop method.

### ISSUE THREAD

**Issue by HengCC** [aksonov/react-native-router-flux#3164]
Is it possible to do a markup action before jumping the page. For example, Actions.mark(), after doing a lot of jumps, I only need to execute Actions.popToMark(). I will return directly to the mark point.

**Comment by aksonov** [comment]
Yes, it is supported already, just use `Actions.popTo('mark')`

**Comment by HengCC** [comment]
@aksonov  thanks,

But I mean, when I execute Actions.popToMark(), I don't know what the point I am marking. This point is automatically maintained in memory only when I execute Actions.mark().

For example:
```
Actions.mark(),
Actions[key1].call(),
Actions[key1].call(),....Actions[keyN].call(),
```
When Actions.popToMark() is executed again, it will return to the position of key1.
