### ISSUE TITLE
Transition history using this same scene but with other parameters

### ISSUE THREAD

**Issue by bialasik** [aksonov/react-native-router-flux#3166]
Hello,
I'm creating a shop app and I'm using react-native-router-flux as a router. 
Currently I have just few scenes like product list, product info, basket, checkout.

But I need to create a navigation. I have JSON with whole navigation structure, where ID of category is the ID for call to API when ProductList scene calls componentDidMount().

But I don't know how to 
a) use this same scene but with additional parameters and refresh it -- I suppose that I should do something like `Actions.refresh({ key: PRODUCT_LIST, params: { categoryId: 12345 } })`?
b) how to handle this same scene transitions history? I mean if I'll do some Actions.refresh() how can I go back to previous categories I refreshed before? 

As a state manager in the app, I'm using Redux. But I'm not using it for router (I had some issues to pair RNRF and Redux).

Or maybe you have other ideas how to handle this case?

Best regards,
Marcin

**Comment by aksonov** [comment]
Just do usual 'push', like Actions.productList({categoryId: 123}), you will just two components in the stack.

**Comment by aksonov** [comment]
For Redux integration, change ReduxExample

**Comment by bialasik** [comment]
And even if I'll do some pushes on this same scene but with different parameters, I can go back to old state?

**Comment by aksonov** [comment]
"<" button ? Sorry, github is for issues not for questions, please post the question to StackOverflow
