### ISSUE TITLE
Drawer panHandlers{null} doesn't work anymore

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3169]
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.43
- react-native 0.55.4

### Expected behaviour
Disable swipe back when drawer is open

### Actual behaviour
Drawer swipes back to login. I had this working before with panHandlers{null} on my drawer but after updating it broke. I have also tried gesturesEnabled={false} too but no luck still.

P.S  - This update was incredible and resolved so many previous issues I was facing. Thanks for all your hard work.

**Comment by daviscabral** [comment]
@nica0012 could you please update to the most recent version at the moment and see if is still happening? 

Also, can you provide an app using the code from `Example` folder?

**Comment by nica0012** [comment]
@daviscabral I tried updating but the issue still persists.

**Comment by NelGarbuzova** [comment]
+1

**Comment by daviscabral** [comment]
Version 4.0.3 does not work exactly the same way as the 4.0.0-beta.x. It is using a different react-navigation version. Please provide the all the information asked in the issue template instead of +1 to get help.

**Comment by aksonov** [comment]
Please create new issue for 4.x version if the issue still exists
