### ISSUE TITLE
NavBar Title

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#317]
How can I prevent the title from truncating when its too long? Can you suggest a workaround if this is not possible? I already tried maximizing the navbar width using styles

**Comment by aksonov** [comment]
3.0 release should solve this problem. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.

**Comment by marijarahman** [comment]
This is not solved and I'm using v3.39.2

**Comment by kayazinc** [comment]
I'm using v3.38.0, also having the same issue when showing on tablet.
