### ISSUE TITLE
Actions.pop(refresh:{}) does not work for me 

### ISSUE THREAD

**Issue by lynnic26** [aksonov/react-native-router-flux#3172]
### Version

- react-native-router-flux v4
- react-native v0.55.4
- react  v16.3.1

### Expected behaviour

I have screen A and Screen B 
when I redirect from A -> B,
In B screen backing to A ,  I want A screen fetch data and rerender the screen everytime entering it 

```
Actions.pop({
     refresh: {someProp: Math.random()}
})
```

### Actual behaviour

The api methions above does not work ,
so I did some workaround,

```
Actions.pop()
setTimeout(() => {
      Actions.refresh({
        someprop: Math.random() * 100
      })
}, 10)
```

this can fire **componentWillReceiveProps** lifecycle method in A screen
and I setState and rerender screen A in this way

I want to know why `Actions.pop({refresh: {}})` does nothing in my case
It can not even fire **componentWillReceiveProps**  unless move it in a setTimeout function

**Comment by dextermb** [comment]
I attempted to add a function for a Scene's `onEnter`:
```
const refresh = () => {
	Actions.refresh({
		enterTime: Math.random()
	});
};
```

```
componentDidUpdate(prev_props) {
    if (this.props.enterTime !== prev_props.enterTime) {
        this.init();
    }
}
```

But this doesn't seem to work either.

**Comment by daviscabral** [comment]
@lynnic26 what is the `react` version you are using? 

Could you check if your version is compatible?

| `react-native` | `react`         |
|----------------|-----------------
| 0.46.x         | 16.0.0-alpha.12 |
| 0.47.x         | 16.0.0-alpha.12 |
| 0.48.x         | 16.0.0-alpha.12 |
| 0.49.x         | 16.0.0-beta.5   |
| 0.50.x         | 16.0.0          |
| 0.51.x         | 16.0.0          |
| 0.52.x         | 16.2.0          |
| 0.54.x         | 16.3.0-alpha.1  |
| 0.55.x         | 16.3.1          |

**Comment by atifplus** [comment]
` "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-router-flux": "4.0.0-beta.31",`  This is working for me had the same issue with 4.0.1

**Comment by dextermb** [comment]
@atifplus Most features were broken after `4.0.0` (and I think `^4.0.0-beta.31`) as that is when it changed to react-navigation `^2.0`.

There's a pull request that is being worked on which will hopefully resolve these issues soon.
https://github.com/aksonov/react-native-router-flux/pull/3240

**Comment by daviscabral** [comment]
With `4.0.2` - you will have to provide a `key` to pop to have it refreshing.

```
  Actions.pop({ refresh: { data: 'Data after pop', title: 'title after pop' }, key: null });
```

**Comment by aksonov** [comment]
Could we preserve old API?

**Comment by daviscabral** [comment]
Yes, it should be preserved. Just wanted to show where to place it.

**Comment by aksonov** [comment]
So why we need to provide null key? As I remember it was not required before...

**Comment by daviscabral** [comment]
I've updated the example - my bad for keeping it confuse. Actually null is the default - not needed.

**Comment by daviscabral** [comment]
But it will be refactored in the #3269.

**Comment by aksonov** [comment]
Please check latest 4.0.3, reopen if bug still exists.

**Comment by gagantaneja** [comment]
> ### Version
> * react-native-router-flux v4
> * react-native v0.55.4
> * react  v16.3.1
> 
> ### Expected behaviour
> I have screen A and Screen B
> when I redirect from A -> B,
> In B screen backing to A , I want A screen fetch data and rerender the screen everytime entering it
> 
> ```
> Actions.pop({
>      refresh: {someProp: Math.random()}
> })
> ```
> ### Actual behaviour
> The api methions above does not work ,
> so I did some workaround,
> 
> ```
> Actions.pop()
> setTimeout(() => {
>       Actions.refresh({
>         someprop: Math.random() * 100
>       })
> }, 10)
> ```
> this can fire **componentWillReceiveProps** lifecycle method in A screen
> and I setState and rerender screen A in this way
> 
> I want to know why `Actions.pop({refresh: {}})` does nothing in my case
> It can not even fire **componentWillReceiveProps** unless move it in a setTimeout function

> try using `requestAnimationFrame` rather than `setTimeout`

**Comment by jiushicheng** [comment]
my Version react 16.4.1 react-native 0.56.0 react native router flux 4.0.5  the problem still exists @aksonov

**Comment by aksonov** [comment]
@jiushicheng Check examples and modify it to demonstrate your issue.

**Comment by fanzhiri** [comment]
today is 2019-08-27 , my Version react 16.8.6 react-native 0.60.5 react native router flux ^4.0.6 the problem still exists .
can not fire componentWillReceiveProps .
May need to adapt to the new life cycle "static getDerivedStateFromProps(props, state) "
@aksonov

**Comment by n3rd253** [comment]
@aksonov this will break come react native 1.17.

componentWillReceiveProps is being deprecated in favor of componentDidUpdate
