### ISSUE TITLE
android back button move the app to forground mode

### ISSUE THREAD

**Issue by roeib** [aksonov/react-native-router-flux#3173]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31
- react-native v0.55.4

### Expected behaviour
when press back button make Actions.pop()

### Actual behaviour
android back button move the app to forground mode

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
@roeib Please try the most recent version, in case that still does not work, provide an example (better if using one of the ones provided in the repository) so I can reproduce it here and help you.
