### ISSUE TITLE
How to listen onback, onpop inside screen component

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#3178]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Expected behaviour

I wanna listen, catch on navigation pop, back inside screen component

### Actual behaviour

Actions.refresh({ renderBackButton: () => ()}) in cdm, cwm seems not working

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by telmen** [comment]
In API documentation, it has `onBack` prop but there's no API in source code.

**Comment by daviscabral** [comment]
Did you meant `Scene` with `Screen`? - `onBack` is showed in the code and in the `Example` code. 

https://github.com/aksonov/react-native-router-flux/blob/cd74da5f28f3a0d3c33be781a7f07463ace6b00f/src/NavBar.js#L18
https://github.com/aksonov/react-native-router-flux/blob/e1b7cd19ad86980643ae852c2f689da4d6ec6538/Example/Example.js#L113

Please provide the information that is asked in the template, so we can help you.

**Comment by telmen** [comment]
I mean yeah, but I want to control it from either previous scene navigating to my desired scene or inside my scene. Like Actions.myscene({ onBack: () => {} }). But it doesn't work.

**Comment by daviscabral** [comment]
`onBack` is not a supported in the action param. You will have to manage that in the life cycle of your component or in the `onNavigationStateChange`.

**Comment by telmen** [comment]
Nevermind, my bad. I was rendering custom back button and didn't pass props onback on onPress prop. Closing this issue.

**Comment by daviscabral** [comment]
My bad - just confirmed that it is supported. Thanks for having the time to report it back here.  👍
