### ISSUE TITLE
Check auth onEnter

### ISSUE THREAD

**Issue by PeterKow** [aksonov/react-native-router-flux#318]
Hi,

I try to implement check authorization with a router. I can see that before there was support for `onEnter` method which we can add to route

`<Route name="main" onEnter={(route) => {console.log('check Auth - isLogin?')}}>`

The current version doesn't support this, any ideas how I can implement autch check on Router level? 

Thanks!

**Comment by eneskaya** [comment]
I was thinking about that too. Here's my idea (I'm new to react-native and to native programming, btw.)
How about setting up a view, let's call it "launch", which calls a log in view. On this view, there is a check if the token is in the storage. If true, the user is redirected to the "home" route, or whatever. On the log in view you could also, e.g., show a loading spinner before rendering the email and password form, etc. 

I'm not sure if this is the right way to do it, would be glad to hear other/better ideas.

**Comment by PeterKow** [comment]
This might work if your app requires login in for all your components, a problem is when you have routes which can be accessed without login in.

Generic solution is when:
- you have `onEntry` method which you can add to your route
- be able to create nested routes and root will check auth for you

**Comment by aksonov** [comment]
3.0 release should solve this problem using Switch renderer, check README. 
However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
