### ISSUE TITLE
drawer position right not working correctly

### ISSUE THREAD

**Issue by arbabi2010** [aksonov/react-native-router-flux#3180]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native v0.46.4

### Expected behaviour
Hi. when I open drawer with position "left" it open and move from left to right and fix in right. actually this not open from right. this is my code
`<Scene drawer key="drawer" contentComponent={buy} drawerPosition="left" drawerWidth={350}  hideNavBar hideTabBar hideDrawerButton="back" >`

### Actual behaviour

this open form right

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
Your issue description is confusing. 

But it seems this is the expected behavior.

Here is the code from Example folder using the most recent version:
[![Image from Gyazo](https://i.gyazo.com/1f37db18f03d6384a1108cc46980ecc1.gif)](https://gyazo.com/1f37db18f03d6384a1108cc46980ecc1)

Please, try it like is there and in case you are still having issues, reopen this ticket.

**Comment by arbabi2010** [comment]
@matthewkwong2 I wanted to open it from right but it had a bug when i was using from genymotion. i use from my mobile device and it's ok right now. thank you.

**Comment by tarbundiyahitesh21** [comment]
`drawerPosition='right'` not working in reactnavigation library

**Comment by tristanvandam** [comment]
@tarbundiyahitesh21  I have the exact same issue.

When using the default draw navigator, if shows from the left perfectly.
`        <Drawer.Navigator  drawerContent={props => <SideDrawerNavigator {...props} />} ></Drawer.Navigator>
`

When using drawerPostion='right' screen goes slightly dark but there is no drawer.
`       <Drawer.Navigator  drawerContent={props => <SideDrawerNavigator {...props} />} drawerPostion='right' ></Drawer.Navigator>`
