### ISSUE TITLE
Add tabStyle to active tab only

### ISSUE THREAD

**Issue by ThomasLarge** [aksonov/react-native-router-flux#3181]
Version  4.0.0-beta.31

I'm asking if there's a way to add a tabStyle to the active tab. This way you would be able to add a different style to the whole tab on the active state. I might just be missing something in the docs but I'm not able to see something to do this with

This is what I'm trying to achieve

![screen shot 2018-08-14 at 11 00 43](https://user-images.githubusercontent.com/15890942/44085392-57505b08-9fb1-11e8-867d-d8bea0911ae7.png)

I started to make a custom component but didn't want to do this as there's more configuration.

Here is the code 

```
<Scene
        key="Tabs"
        tabs={true}
	tabBarPosition="bottom"
	activeBackgroundColor="#282828"
	inactiveBackgroundColor="#282828"
	inactiveTintColor="#6E6E6E"
	activeTintColor={'white'}
	tabBarStyle={{
		backgroundColor: '#282828'
	}}
	tabStyle={{
		width: '100%',
		height: '100%',
		borderTopColor: 'grey',
		borderTopWidth: 4,
		marginTop: -1,
		paddingTop: 10
	}}
	swipeEnabled={false}
	animationEnabled={false}
	panHandlers={null}
	initial={true}
>
.... tabs content

</Scene>

**Comment by SourceCipher** [comment]
Same issue here as I want to add different width to each tab but I cant seem to find a way to do it.

I was about to add the issue that the `tabStyle` is not working at all as it says **Override the style for an individual tab of the tabbar** but having this  `tabStyle`  in each tab component which is a child of the Tabs or Scene with the `tabs={true} `will not take any custom styling whatsoever

**Comment by dextermb** [comment]
Couldn't you do this through `icon`? Or at least this is how I am doing it?

```
<Tabs>
	// ...
	<Scene
		key={'Challenges'} headerMode={'none'}
		hideNavBar={true} component={Challenges}
		onEnter={refresh}
		icon={({ focused }) => (
			<TabbarIcon
				active={focused} style={{ width: 100 }}
				text={'Challenges'} icon={'challenges'}
			/>
		)}
	/>
	// ...
</Tabs>
```

Then in `TabbarIcon`:

```
<View style={[_Tabbar.item, style]}>
	{icon &&
	 <Image
		 style={[
			 _Tabbar.item_icon,
			 active ? { opacity: 1 } : {}
		 ]}
		 source={icon}
	 />}
	<Text
		style={[
			_Tabbar.item_text,
			active ? { color: '#c8367a' } : {}
		]}
	>{text}</Text>
</View>
```

Thoughts?

**Comment by ThomasLarge** [comment]
@dextermb I did try something like that but the active state is on the issue with the icons as they have this build in. 

I want to change the borderTopColor on active state. I'm able to set the tabStyle to add the styling but can't find away to get add a styleProp for the tabStyle on active state. 

<img width="405" alt="screen shot 2018-08-18 at 16 55 24" src="https://user-images.githubusercontent.com/15890942/44300979-89fda480-a307-11e8-9a40-835d92276586.png">

This is what I have I just need to add the borderTopColor. (I also need to fix the icon colours but this isn't a problem

**Comment by daviscabral** [comment]
Have you achieved the result expected? Do you mind sharing what have you done? What is the lib missing in that case? Thank you.

**Comment by ThomasLarge** [comment]
Hi @daviscabral I haven’t yet, I don’t really want to make a custom component as I would have to route all of the push / pops. 

If the lib could have a active style prop for the container / single tab of the tab view that would be great. As you can see above I have added a border top to the whole container but I want to add it every tab and then change it to white when active. 

When I have some time I’m going to have a look though the code and see if I can work it out. If so I will make a PR.

**Comment by daviscabral** [comment]
Nice - thank you. Please, when you do, refer to this issue. I'll keep this opened and marked as `feature request`.

**Comment by ThomasLarge** [comment]
I haven't had the chance to look into this as much as I would of liked but if someone could explain how the active state works on the title colors. I'm sure we will be able to add a new prop for the activeTabStyle

**Comment by daviscabral** [comment]
Not being able to work on this lately - but I'll try to spare some time later today.

**Comment by aksonov** [comment]
@ThomasLarge beta is not supported, could you please check latest 4.0.6 version?

**Comment by ramanasak** [comment]
Is there a way to call a function when the tab is selected?
