### ISSUE TITLE
any plans to support SwitchNavigator or recommended setup

### ISSUE THREAD

**Issue by aniltirola** [aksonov/react-native-router-flux#3185]
### Version
- react-native-router-flux ^4.0.1
- react-native https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz
- react-navigation: ^2.11.2

### Expected behaviour
use the features of SwitchNavigator
https://reactnavigation.org/docs/en/switch-navigator.html

### Actual behaviour
seems not to be implemented now

### My question
Are there any plans to support SwitchNavigator?
Or are there any recommandations how to implement the behaviour of SwitchNavigator?

**Comment by matthewkwong2** [comment]
OK, from the offical doc of react navigation, the key feature of Switch Navigation is 

> to only ever show one screen at a time. By default, it does not handle back actions and it resets routes to their default state when you switch away. 

You may try to look at ```Actions.reset()``` 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions

which seems like something you are looking for. The downside though is no transition animation will be fired. If you want to keep the animation while simply prevent users going back to the previous page, try ```back={false}``` in the corresponding ```Scene``` and override the ```BackHandler``` (Android only, ios doesn't have a hardware back button) for that particular scene. https://facebook.github.io/react-native/docs/backhandler

You may call ```Actions.popTo("sceneKey")``` or ```Actions.push("sceneKey")``` in your backhandler according to your need.

**Comment by aniltirola** [comment]
ok, thanks; currently I solved everything with a customreducer;

**Comment by daviscabral** [comment]
Keeping it opened to see if someone might implement it.

**Comment by aksonov** [comment]
@aniltirola @daviscabral What is problem just to pass `SwitchNavigator` as `navigator` param to `Scene`?

**Comment by daviscabral** [comment]
Thanks - I might start a doc page project - to link API with examples.
