### ISSUE TITLE
How to control swipe and return to the specified page instead of the previous page(ios)

### ISSUE THREAD

**Issue by ljmkimqx** [aksonov/react-native-router-flux#3187]
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.32 (v3 is not supported)
- react-native v0.?.?

### Expected behaviour
How to control swipe and return to the specified page instead of the previous page(ios)

**Comment by matthewkwong2** [comment]
call 
```
Actions.push("sceneKey",  {props to pass to the scene});
```
if you want to navigate to a specific page.

Or, 
```
Actions.popTo("sceneKey", {props to pass to the scene});
```
If you want to return to a specify page.
These methods can be called in everywhere, including any kind of listeners (e.g. onPress).

take at look at here
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#actions

**Comment by ljmkimqx** [comment]
I know this, I often use these methods。But I mean when I slide back right, not when I click back。For example, A->B->C, in the C page, I hope that when I can slide right, I will return the A page instead of the B page. The reason why I have this requirement is because I don't want users to ban right slides on C pages (I don't want to use panHandlers={null}). I personally think that prohibiting right slip is not very friendly.  Is there a way to solve this problem? If there is no better way, I will use panHandlers={null}. Thanks.

**Comment by matthewkwong2** [comment]
That's the point, I'm not sure whether onBack handles the swipe gesture in iOS, but it DOES handle the back button in the nav bar AND the hardware back button in Android devices.

You may try
```
<Scene
   key="whateverKey"
   onBack={() => Actions.popTo("sceneKey")}
/>
```

**Comment by ljmkimqx** [comment]
I found that ios's right-sliding back and Android's hardware back button won't trigger the onBack method.

**Comment by matthewkwong2** [comment]
Too bad.

For android, you can implement the backhandler

For ios though, still searching

**Comment by ljmkimqx** [comment]
Yes, but thank you for answering me.

**Comment by daviscabral** [comment]
Hey guys, looking into the issue history I found out that `onBack` is really not called by hardware handlers like you can see at #2359. For now `BackHandler` still should be used, I'll check what can be done on that matter - feel free to provide PRs that help on that matter.

**Comment by daviscabral** [comment]
Sorry - I misread the issue. Maybe we could work in a new event here? Not sure yet how to fix it - I am checking other issues with the `Example` code, and might take a look into that too.

**Comment by ljmkimqx** [comment]
Is there a way to solve this problem?  thanks

**Comment by ljmkimqx** [comment]
thanks，I'll look at the use of React Native Gesture Handler, but I have an idea of ​​directly manipulating Actions.state to see if I can delete a page in state, so I don't have to modify the swipe gesture, but it feels so dangerous.
