### ISSUE TITLE
No animation when switching between routes

### ISSUE THREAD

**Issue by eneskaya** [aksonov/react-native-router-flux#319]
Hello, I have a small problem here. 

When I press on a button to switch to another Route, the animation is really fast and seems strange. I can't help it but no matter what I try it doesn't look better.

![animationless](https://cloud.githubusercontent.com/assets/964419/13793719/8e5ffa9c-eaf8-11e5-954a-b7ec0d71f975.gif)

I have a very simple setup

```javascript

      <Router>
        <Route name="launch" component={SignUpView} initial={true} wrapRouter={true} title="Einloggen"/>
        <Route name="register" component={Header} title="Register"/>
      </Router>
```

What could be the problem here?
Thanks!

**Comment by aksonov** [comment]
Why you wrapRouter here? 
Check 3.0 release, now the component uses new React Native Navigation API. However it has a little bit different API comparing with 2.x release. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.
