### ISSUE TITLE
Actions.reset: There is no route defined for Key X

### ISSUE THREAD

**Issue by asd8855** [aksonov/react-native-router-flux#3194]
### Version
- react-native-router-flux v4.0.1 
- react-native v0.56.0

<Router backAndroidHandler={backAndroidHandler}>
      <Lightbox>
      <Scene key="root">
          <Scene key="LaunchPage" component={LaunchPage} hideNavBar={true} navTransparent={false} rightTitle="" initial />
          <Scene key="LoginPage" component={LoginPage} title="登录" hideNavBar={true} navTransparent={false} hideBackImage={true} />
          <Scene key="ResetPwdOnePage" component={ResetPwdOnePage} title="找回密码" hideNavBar={true} navTransparent={false} />
          <Scene key="ResetPwdTwoPage" component={ResetPwdTwoPage} title="重置密码" hideNavBar={true} navTransparent={false} />
          <Scene key="BillDetailPage" component={BillDetailPage} title="账单详情" hideNavBar={true} navTransparent={false} />
          <Scene key="WithdrawPage" component={WithdrawPage} title="提现" hideNavBar={true} navTransparent={false} />
          <Scene key="WithdrawalRecordPage" component={WithdrawalRecordPage} title="提现记录" hideNavBar={true} navTransparent={false} />
          <Scene key="BatchManage" component={BatchManage} title="批次管理" hideNavBar={true} navTransparent={false} />
          <Scene key="BatchDetail" component={BatchDetail} title="批次详情" hideNavBar={true} navTransparent={false} />
          <Scene key="BatchStatistics" component={BatchStatistics} title="批次统计" hideNavBar={true} navTransparent={false} />
          <Scene key="BillList" component={BillList} title="账单查询" hideNavBar={true} navTransparent={false} />
          <Scene key="ChooseBankCardPage" component={ChooseBankCardPage} title="选择银行卡" hideNavBar={true} navTransparent={false} />
          <Scene key="ResetPwdThirdPage" component={ResetPwdThirdPage} title="绑定支付宝" hideNavBar={true} navTransparent={false} />
          <Scene key="UpdatePhoneNumOnePage" component={UpdatePhoneNumOnePage} title="绑定手机号" hideNavBar={true} navTransparent={false} />
          <Scene key="UpdatePhoneNumTwoPage" component={UpdatePhoneNumTwoPage} title="绑定手机号" hideNavBar={true} navTransparent={false} />
          <Scene key="FeedbackPage" component={FeedbackPage} title="意见反馈" hideNavBar={true} navTransparent={false} />
          <Scene key="FacePayCodePage" component={FacePayCodePage} title="当面付二维码" hideNavBar={true} navTransparent={false} />
          <Scene key="BillSearchListPage" component={BillSearchListPage} title="账单搜索" hideNavBar={true} navTransparent={false} />
          <Scene key="About" component={About} title="关于我们" hideNavBar={true} navTransparent={false} />
          <Scene key="WebViewPage" component={WebViewPage} title="" hideNavBar={true} navTransparent={false} />

          <Tabs key="main" tabBarPosition="bottom" swipeEnabled={false} animationEnabled={false} labelStyle={styles.tabLabelStyle} tabBarStyle={styles.tabBarStyle} tabStyle={styles.tabStyle} activeTintColor="#FF4459" leftTitle=" " onLeft={() => {
              console.log("onLeft");
            }}>
            <Scene key="HomeIndexPage" component={HomeIndexPage} tabBarLabel="首页" style={{ paddingBottom: 10 }} title="首页" hideNavBar={true} icon={state => {
                let source = state.focused ? require("../../res/tab/home-icon-active.png") : require("../../res/tab/home-icon-normal.png");
                return <TabIcon source={source} />;
              }} />
            <Scene key="MoreIndexPage" component={MoreIndexPage} tabBarLabel="工作" title="工作" hideNavBar={true} icon={state => {
                let source = state.focused ? require("../../res/tab/work-icon-active.png") : require("../../res/tab/work-icon-normal.png");
                return <TabIcon source={source} />;
              }} onEnter={() => {
                Actions.refs.MoreIndexPage.table();
              }} />
            <Scene key="MineIndexPage" component={MineIndexPage} tabBarLabel="我的" title="我的" hideNavBar={true} icon={state => {
                let source = state.focused ? require("../../res/tab/me-icon-active.png") : require("../../res/tab/me-icon-normal.png");
                return <TabIcon source={source} />;
              }} onEnter={() => {
                Actions.refs.MineIndexPage.refreshHeaderView();
              }} />
          </Tabs>
        </Scene>
        <Scene key="confirmDialog" component={ConfirmDialog} />
      </Lightbox>
    </Router>;

------

#### Steps to reproduce

- Upgrade from 4.0.0-beta.31 to 4.0.1
- Reset from a nested scene targeting a scene that is not in the first level

**Comment by asd8855** [comment]
when I use "Action.reset("xxx")",it will show

**Comment by mswokk** [comment]
Same here. 
* RN 0.54.0
* RNRF 4.0.1

Under 4.0.0-beta.31 has no problem. 
After upgrading to 4.0.1 it throws error.

Here is my hierarchy and error message

```
<Router key="root">
            <Lightbox>
                <Scene key="rootScene">
                    <Scene
                        initial
                        key="entryScreen"
                        type={ActionConst.RESET}
                        component={EntryScreen}
                    />
                    <Scene
                        key="appOnboarding"
                        component={AppOnboarding}
                    />
                  (... ommit)
               </Scene>  

                <Scene
                    hideNavBar
                    key="dialog"
                    component={YDialog}
                />

                <Scene
                    hideNavBar
                    key="bottomDrawer"
                    component={BottomDrawer}
                />

                <Scene
                    hideNavBar
                    isModal
                    key="questionnaireResultModal"
                    component={QuestionnaireResult}
                />
          </LightBox>
</Router>
```

Error says .... 
```
 Error: Error: There is no route defined for key mainTab.
 Must be one of: 'rootScene','dialog','bottomDrawer','questionnaireResultModal'

 This error is located at:
     in Navigator (at createNavigationContainer.js:376)
     in NavigationContainer (at Router.js:97)
     in App (at Router.js:122)
```

It looks doesn't recognize child  <Scene> s more then 2 depth

**Comment by daviscabral** [comment]
Nice, thanks, I'll take a look when possible and update the ticket.

**Comment by daviscabral** [comment]
Also guys, there a couple of things here that I noticed that are not supported anymore - due `react-navigation@2` breaking changes:

- `swipeEnabled={false}` and `animationEnabled={false}` will not work anymore as you can read about it here: [react-navigation/issues/4146](https://github.com/react-navigation/react-navigation/issues/4146) and [here](https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html#tab-navigator-split-into-separate-components)

I am checking the provided code now to see what is happening.

**Comment by daviscabral** [comment]
Hey guys - I was able to fix the issue - just being sure that is not going to break anything else before creating a PR for it.

Just to be clear about the fixes I am going to push:
- Reset is now going to work with the right stack/scope - respecting nested scenes;
- When using the scene aliases (Actions.[key]) for a scene that has a type `RESET`, it will also respect the scope.

Thank you for the patience and for keeping the discussion clear and objective here.

**Comment by Kiran0791** [comment]
I installed the latest package today "react-native-router-flux": "^4.0.1" but i don't find the above fix.
Can someone help me on how to pull these changes

**Comment by RodrigoCS** [comment]
@Kiran0791 
I believe the last changes are not on npm, right now you could do react-native-router-flux@https://github.com/aksonov/react-native-router-flux/

**Comment by daviscabral** [comment]
This should do the trick:
```
yarn add aksonov/react-native-router-flux
```

**Comment by Kiran0791** [comment]
> aksonov/react-native-router-flux

Even after this reset not working. Its says **There is no route defined for key signup.
Must be one of: 'lightbox'**. When lightbox is used it throws this error

**Comment by asd8855** [comment]
Did you solve this problem in version 4.0.5? I still had this problem in version 4.0.5
Error: There is no route defined for key main.
Must be one of: 'root','confirmDialog'

**Comment by aksonov** [comment]
Please try replace action

**Comment by asd8855** [comment]
@aksonov  Replace 'reset' with 'replace'?

**Comment by aksonov** [comment]
Yes, use type=replace for routes you want to use instead current one

**Comment by hsynlove** [comment]
@aksonov I have the same problem when i update my version to 4.0.5, for some reason i have to use 'reset' instead of 'replace'. What can i do?

**Comment by hsynlove** [comment]
**I find a way to avoid this problem by add a new scene 'Route'  in the first place of 'Pages'.** 

```
<Lightbox>
            <Scene initial key="Start" component={StartScreen}/>
            <Scene key="Pages">
                <Scene key="Route" component={Route}/>
                <Scene key="Login" component={Login}/>
                <Scene key="Main" component={Main}/>
            </Scene>
</Lightbox>
```
```
import {Actions} from 'react-native-router-flux';

const Route = (props) => {
    const {target, params} = props;
    Actions.replace(target, params);
    return null;
};

const {reset} = Actions;

Actions.reset = (target, params) => {
    const props = {target};
    if (params) {
        props.params = params;
    }
    reset('Pages', props);
};

export default Route;
```

then I can use Actions.reset('Login') or Actions.reset('Main') normally. I hope this can help

**Comment by asd8855** [comment]
@hsynlove the 'Root' is empty page？

**Comment by hsynlove** [comment]
@asd8855 yes, and this page can resolve this problem though it doesn't look elegant.

**Comment by afilp** [comment]
Hi, 'replace' is not 'rest' because when the user logs out we need to make sure that no history is tracked anymore (with back buttons, etc.). 

@aksonov Do you think this can be solved in a cleaner way? Thanks!

**Comment by ayushnawani** [comment]
facing the same issue here. reset not working for nested scenes inside lightbox.

**Comment by spadgeaki** [comment]
@aksonov Hi, we are still experiencing the same issue in latest version.

**Comment by acollazomayer** [comment]
@aksonov same here. Just upgrade from beta to 4.0.6 and push is not working

**Comment by manithin** [comment]
same here. Reset is not working and sometimes weirdly push too is not working

**Comment by DimForCity** [comment]
yes, reset not working for nested scenes with lightbox.

**Comment by Dineshchitta** [comment]
Hi @aksonov , Trying to update 
react-native-router-flux from 4.0.0-beta.22 to 4.0.6 
react-navigation from 1.0.0-beta.26 -> 2.18.3
React native 59.10

Still facing this issue. If I use REPLACE instead of RESET I am not getting any issue. But the app is not behaving in expected behavior.

**Comment by malithjkmt** [comment]
Not working on `react-native-router-flux` for same scenario (Lightbox, reset)
```
    "react": "16.8.6",
    "react-native": "0.60.4",
```

@aksonov @daviscabral @asd8855 any insights ?

**Comment by SanyasiraoM** [comment]
@aksonov can you please reopen the issue?

**Comment by hectorsuarezm** [comment]
Same as @malithjkmt this still not working

`    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-router-flux": "4.0.6"`

any work around that doesn't affect the app behaviour (type="replace") ?

**Comment by mylesshie** [comment]
same error, "react-native-router-flux": "^4.2.0",

**Comment by bluescorp1311** [comment]
still error, "react-native-router-flux": "4.2.0". "react-native": "0.60.4"

**Comment by worione** [comment]
Action.reset("key") the problem is fixed for me

**Comment by Nico-Guyon** [comment]
I also have the same problem with "react-native-router-flux": "^4.2.0".
Action.reset('X') gives me: There is no route defined for Key X

**Comment by yestay90** [comment]
I also face the same problem. When I add type='reset' to scene it works ok when connected to metro. But when creating build it shows error on alert that There is not route defined for Key x.

**Comment by malithjkmt** [comment]
After 2 years, upgraded to `"react-native-router-flux": "^4.3.1"`. Still facing the same issue

**Comment by telmen** [comment]
How is this closed?

**Comment by yestay90** [comment]
@telmen , I resolved this issue by resetting to Modal parent element, plus I also set initialScreen props. So, for example when you logout. Just run Actions.reset('modal'), and inside of Modal set the initialScreen.

**Comment by telmen** [comment]
@yestay90 hi, i can't seem to find `initialScreen` prop anywhere. What do you mean by that?

**Comment by yestay90** [comment]
@telmen , sorry it is just `initial`. `<Scene initial={true} key="loginScreen" component={LoginScreen} />`

**Comment by telmen** [comment]
@yestay90 no problem, dude. But how do I reset the current stack and not use a modal scene but a plain scene from the root stack?

**Comment by yestay90** [comment]
@telmen , you get this error only when you have <Lightbox> or <Modal> which wraps you stacks. So In my case, I could only reset whether to LightBox or to Modal cause they are on top of stack.

**Comment by telmen** [comment]
Decided not to use Modal :). Thank you.
