### ISSUE TITLE
Unable to transfer a state value from one scene to another via “Actions.push()” ...

### ISSUE THREAD

**Issue by keneseu** [aksonov/react-native-router-flux#3196]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1
- react-native v0.56.0

### Expected behaviour
Able to transfer a "task" state value from "tasks" scene to the "screen" scene, using “Actions.push” - where "the router and scenes" are defined  in "App".

### Actual behaviour
The "Screen" scene seemed to receive an "undefined" value instead ...

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

[Tasks.txt](https://github.com/aksonov/react-native-router-flux/files/2305658/Tasks.txt)
[Screen.txt](https://github.com/aksonov/react-native-router-flux/files/2305660/Screen.txt)
[App.txt](https://github.com/aksonov/react-native-router-flux/files/2305666/App.txt)

**Comment by daviscabral** [comment]
You should use the scene key or `jump` to make that work. You can see this working in the Tab 5 from the `Example` code.

With the example, the code would be: 
```js
  onPress = () => {
    Actions.screen({incomingTask: this.state.task})
  }
```

![2018-08-23 05 17 54](https://user-images.githubusercontent.com/4285/44513560-0be92700-a694-11e8-9f4e-be1463aba94a.gif)

In case that is still happening, please provide a failing example and reopen this ticket.

**Comment by keneseu** [comment]
Hi,

Thank you for your help! Could you provide me with the complete code for
the Tab 5 example, as I still could not get it work somehow?

Look forward.
