### ISSUE TITLE
How to override tab swipe navigation if child element is swipeable?

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#3199]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.56.0

### Expected behaviour
Override tabs swipe navigation if child element has panresponder, swipeable.

### Actual behaviour

A current Scene(Tab) is navigating between tabs while child element is working partially.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
Could you try `4.0.1`? RNRF 4.0.1 uses `react-navigation@2.0` and `4.0.0-beta.31` uses `react-navigation@1.5`. In `react-navigation@2.0` is not supported anymore.

**Comment by daviscabral** [comment]
I am closing this ticket in favour of the bugs and active issues - please, check the `Example` folder from that version you are using or try to upgrade to the most recent version.  

If you believe that this was mistakenly closed - feel free to reopen providing a way to reproduce the error (I couldn't get the problem exactly) or a https://stackoverflow.com/help/mcve.
