### ISSUE TITLE
Testing with jest breaked

### ISSUE THREAD

**Issue by Mokto** [aksonov/react-native-router-flux#32]
Hi,

I'm trying to write test in a component using this plugin.

When requiring react-native-router-flux inside a Jest Test, I got
`Error: src/actions/__tests__/router-test.js: src/actions/router.js:  node_modules/react-native-router-flux/index.js: node_modules/react-native-router-flux/__mocks__/react-native.js: Cannot find module 'react' from 'node_modules/react-native-router-flux/__mocks__/react-native.js'`

Do you have any clue ?

Thanks

**Comment by Mokto** [comment]
The only way I see is to create a __mocks__ directory at the root of your project and add a react-native-router-flux.js file :

```javascript
module.exports = {
  Actions: {
    push: function() {},
    reset: function() {},
    pop: function() {},
  }
}
```

**Comment by aksonov** [comment]
I'm going to use mocha for 1.0 release to avoid that...
