### ISSUE TITLE
Error while updating property transfrom of a view managed bt RCTView

### ISSUE THREAD

**Issue by sritharanrbt** [aksonov/react-native-router-flux#3200]
Just after installing router-flux it throws this error on android , but working fine with Ios , is there work around with this

 
<img width="1280" alt="screen shot 2018-08-22 at 4 21 18 pm" src="https://user-images.githubusercontent.com/16588387/44459631-fb9b6280-a627-11e8-8298-85fe9a6526af.png">

### Version
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-router-flux": "4.0.1"

**Comment by daviscabral** [comment]
@sritharanrbt are you using RTL? Can you provide more information about the error? Code sample? That sounds like a real bug with the way we handle the `transform` prop - but the lack of information in the issue does not help.
