### ISSUE TITLE
 How can I hear the event come back?

### ISSUE THREAD

**Issue by felipe-alecsandro** [aksonov/react-native-router-flux#3201]
Hello,

I'm trying to hear the back event I stated on the route in de module detailVisit:
`<Scene key="detailsVisit" back={true} component={DetailsVisit} title="Detalhes da visita" />`

I have tried to listen to the event as follows, and I have not been successful in the detailVisit:
`  componentDidMount() {
        BackHandler.addEventListener('backPress', () => {
            Actions.visits();
            return true;
        });
}`

Would you help me?

**Comment by daviscabral** [comment]
Have you tried `onBack`?
