### ISSUE TITLE
onEnter event supported on Drawer component ? Want to call function when user open Drawer

### ISSUE THREAD

**Issue by anishroff** [aksonov/react-native-router-flux#3204]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1 (v3 is not supported)
- react-native v0.55.1

```
                <Drawer
                  hideNavBar
                  key="drawer"
                  contentComponent={SideMenu}
                  drawerImage={MenuIcon}
                  drawerWidth={300}
                  onEnter={() => alert("in drawer")}
                >
```

### Expected behaviour
I want to call a function in component after user opens the Drawer. I tried with above code with no luck. 

### Actual behaviour

`onEnter` alert is not shown when Drawer is opened. Is it supported on `Drawer` ? How to track if event of user opened Drawer ?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
Can you try this? 

```js
                <Scene 
                  drawer
                  hideNavBar
                  key="drawer"
                  contentComponent={SideMenu}
                  drawerImage={MenuIcon}
                  drawerWidth={300}
                  onEnter={() => alert("in drawer")}
                >
```

**Comment by anishroff** [comment]
@daviscabral Apologise for delay. It doesn't work this way as well. How can I help to find the issue, please assist.

**Comment by daviscabral** [comment]
@anishroff I've added support for it in a PR.
