### ISSUE TITLE
How can I hide single tab with width 0

### ISSUE THREAD

**Issue by VishalKumar2016** [aksonov/react-native-router-flux#3205]
- react-native-router-flux: "^3.39.2",
- react-native: "^0.44.3",

### Expected behaviour
I have 6 tabs but what to show only five tabs how can I hide one tab and when I call that tab programmatically It's will show the screen but not show any tab select and even not show that tab in tab bar. I mean I need an invisible tab

### Actual behaviour
I use tab style with width: 0 but not working is there any other way to achieve this.

**Comment by daviscabral** [comment]
Sorry, unfortunately v3 is not supported anymore.  Also, this seems to be a question better suited for StackOverflow.
