### ISSUE TITLE
How to make react-native-router-flux Drawer transparent?

### ISSUE THREAD

**Issue by Hannibal2** [aksonov/react-native-router-flux#3209]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31",
- react-native v0.55.4

I need to make side menu transparent, but i dont't  lnow how, I've tried to add opacity to my MenuView component, but it makes visible white backround  of scene instead of phone screen

MyCode: 
 ```
<Drawer
            key='drawer'
            drawer
            contentComponent={MenuView}
            hideNavBar
            drawerIcon={<Icon name='menu' size={30} />}
            drawerWidth={300}
            drawerPosition='right'
        >
            <Scene .... />
            <Scene ... />
       </Drawer>
```
Does anybody know how to solve it?

**Comment by dextermb** [comment]
Do you need to make the menu transparent or the backdrop of the menu?

**Comment by Hannibal2** [comment]
@dextermb the backdrop

**Comment by daviscabral** [comment]
The opacity solution - if I am not mistaken, is for the versions using `react-navigation@2`. 

For versions before it - I am not aware how to that's could be done. I usually look into the `react-navigation` issues and StackOverflow to see if someone asked/answered it. Please reopen the issue with template information in case of a bug found.
