### ISSUE TITLE
Dynamic navigationBarStyle / sceneStyle

### ISSUE THREAD

**Issue by jcsmesquita** [aksonov/react-native-router-flux#321]
Hi,

First off, great work on this library :+1: 

My issue is that I want to update the navigationBarStyle and sceneStyle properties dynamically. Is there any way to trigger the whole navigation bar to rerender and catch those prop changes? I've looked into Actions.refresh(props) but it doesn't seem like it will help me in this case...

**Comment by aksonov** [comment]
3.0 release should solve this problem. However it has a little bit different API. Anyway I'm closing this ticket because 2.x release will not be supported except critical bugs.

**Comment by jcsmesquita** [comment]
Thanks for letting me know.

**Comment by hakkikonu** [comment]
How can I change `navigationBarStyle` dynamically. I want to use different background colors for every Scene

Currently my config is like this;

```
<Router tintColor='white' navigationBarStyle={{ backgroundColor: '#81b71a' }} >
...
 </Router>
```
