### ISSUE TITLE
Proposal: RNRF 3.5

### ISSUE THREAD

**Issue by daviscabral** [aksonov/react-native-router-flux#3213]
A lot of issues are coming from the major upgrade of `react-navigation` from `1.5.6` to `2.x`.

That is really making the work of handling issues and fixing bugs a lot more complicated that used to be.

So just to be clear: 

- RNRF `4.0.1` uses `react-navigation@2.0`;
- RNRF `4.0.0-beta.31` uses `react-navigation@1.5.6`;

What I am proposing here is to branch-out from `4.0.0-beta.31` as `v3.1` and keep the warning telling that it is not supported. 

So we can keep with the `rnrf@4.0.x` and its problems with `react-navigation@2` to be fixed as expected.

**Comment by mswokk** [comment]
Due to critical bugs in 4.0.1, I'm still in 4.0.0-beta.31. I think 4.0.0 is not stabilized yet. I agree with @daviscabral

**Comment by daviscabral** [comment]
@mswokk I believe `4.0.1` is stable - but it's not working as before for a lot of cases that I believe were not the main intent of the lib. 

But for having a `3.5` version, someone from the community also will have to step up to maintain it. That's the main purpose of this issue too. My focus is on bringing back things that people are missing from `v3` on `v4`.

**Comment by aksonov** [comment]
@daviscabral Sounds good (v3.5)

**Comment by daviscabral** [comment]
Cool. I'll fork the last beta using `react-navigation@1.5` to a branch `v3.5` and update the `package.json` to reflect it.

**Comment by daviscabral** [comment]
@aksonov that's done - could you publish it as a version please? I've already built and tagged it too over there. And also, ignore the `4.0.2` commit on `packages.json` in the history - that was really precipitated - but if would be good to release it now that we have a few fixes in place. Thanks.

**Comment by daviscabral** [comment]
Agree. I just had the idea of moving it to its own package - like `react-native-router-flux-deprecated`. But right after changing the title I was not so sure about it. Anyway, let's focus in the v4 :-)

**Comment by daviscabral** [comment]
A note for anyone that end in this thread - there is a branch for beta - and PRs are welcome. I am not interested in working on that version (too much context to load everytime I have to switch between the different versions of react-navigation).
