### ISSUE TITLE
Drawer Open detection

### ISSUE THREAD

**Issue by atrimn** [aksonov/react-native-router-flux#3215]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

I have a Custom NavBar so my drawer button doesnt work.
But on my Iphone device i can just swipe right to open the drawer which is fine.

But i cannot detect if the drawer is open using onEnter or onOpen

**Comment by aksonov** [comment]
It looks like question for stackoverflow. You can try to check `this.props.navigation.state`
