### ISSUE TITLE
How to set the gradient for the navigation bar？

### ISSUE THREAD

**Issue by asd8855** [aksonov/react-native-router-flux#3217]

**Comment by dextermb** [comment]
According to the [API Documentation](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md#scene) you can pass a custom navbar component with the prop `navBar` on a Scene or forfeit the gradient and just change the styles with the prop `navigationBarStyle`

**Comment by asd8855** [comment]
ths

**Comment by dextermb** [comment]
@asd8855 If this resolved your issue can you close this thread.
