### ISSUE TITLE
Module parse failed when using react-native-router-flux in minimal test project

### ISSUE THREAD

**Issue by Sharcoux** [aksonov/react-native-router-flux#3219]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1 (v3 is not supported)
- react-native v0.?.? -> react-native-web v0.8.9

### Expected behaviour

Just trying to make a minimal project to work

### Actual behaviour

I get this crash

Module parse failed: Unexpected token (100:6)You may need an appropriate loader to handle this file type.|   if (transitionConfigurer) {
|     return {
|       ...defaultConfig,
|       ...transitionConfigurer(transitionProps, prevTransitionProps, isModal),
|     };

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. create-react-app
2. npm install react-native-web react-art react-native-router-flux
3. Replace App.js by the following:

```
import React from 'react';

import { Scene, Actions, Router } from "react-native-router-flux";
import { Text, View } from "react-native";

const Test1 = () => (
  <View>
    <Text>test1</Text>
  </View>
);
const Test2 = () => (
  <View>
    <Text>test2</Text>
  </View>
);

function App() {
  return (<Router>
    <Scene key="root">
      <Scene key="test1" component={Test1} title='test1' initial />
      <Scene key="test2" component={Test2} title='test2'  />
    </Scene>;
  </Router>);
}

export default App;

```

For reminder, create-react-app will forward calls targeting react-native to react-native-web.

**Comment by daviscabral** [comment]
This is not related to `RNRF`. As the error message says - you will need the `babel` loader to make spread work (probably `@babel/plugin-syntax-object-rest-spread` - but I believe that's not included anymore and to customize it, you might have to `eject` your app).
