### ISSUE TITLE
pop and refresh problem in a async function

### ISSUE THREAD

**Issue by 2linziyi2** [aksonov/react-native-router-flux#3221]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.25 (v3 is not supported)
- react-native v0.53.3

### Expected behaviour
Scene A -> Scene B, Scene B pop by a function. As follows
```
test() {
  Promise.resolve(true).then(result => {
     Actions.pop();
     Actions.refresh({timestamp: new Date().getTime()})
  })
}
```

Only Scene A tigger componetWillReceiveProps

### Actual behaviour

Actions.refresh function will refresh Scene A and Scene B, and Scene A tigger componetWillReceiveProps，Scene B tigger constructor to componentWillUnmount

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Scene A -> Scene B
2. pop and refresh in a async function

**Comment by daviscabral** [comment]
Can you update to a more recent version? 

I am still waiting further discussion on #3213 - until there, I don't think `beta` version should be supported.
