### ISSUE TITLE
New scene is not visible full screen

### ISSUE THREAD

**Issue by ggunti** [aksonov/react-native-router-flux#3226]
### Version

- react-native-router-flux v4.0.1
- react-native v0.55.4

### Expected behaviour
Open the required scene full screen of course.

### Actual behaviour
The required scene is opened, but on the bottom is still visible a little portion from the previous screen (the camera).
See the video: https://vimeo.com/287135365
I called Actions.sketch(), but on the background is still alive the previous scene. On the bottom of the screen is visible a little portion of it. Why?

### Steps to reproduce

1. Use a react-native-camera-kit camera component as initial scene
2. After taking a photo, call Actions.nextScene()

I call this function when taking a picture:
![untitled](https://user-images.githubusercontent.com/26307699/44747185-3bc18000-ab15-11e8-9b46-64436acc8fa9.png)

**Comment by daviscabral** [comment]
Can you provide the route and component structure used? The way you explained here - it is really hard to reproduce from my side to try to help you.

I noticed that with the last release, a lot of issues might be happening due the wrong version match between a lot of dependencies.

Could you check if your version is compatible?

| `react-native` | `react`         |
|----------------|-----------------
| 0.46.x         | 16.0.0-alpha.12 |
| 0.47.x         | 16.0.0-alpha.12 |
| 0.48.x         | 16.0.0-alpha.12 |
| 0.49.x         | 16.0.0-beta.5   |
| 0.50.x         | 16.0.0          |
| 0.51.x         | 16.0.0          |
| 0.52.x         | 16.2.0          |
| 0.54.x         | 16.3.0-alpha.1  |
| 0.55.x         | 16.3.1          |
| 0.56.x         | 16.4.1          | 

Also, check the breaking changes related to the version you are using and the most recent - that might shed a light here:
https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md

**Comment by daviscabral** [comment]
@ggunti Cool. Thanks. I can't see anything wrong there - have you inspected the views to see from where is that coming? Also, could you try to use `yarn add aksonov/react-native-router-flux` to test if the new version of RN that was merged and the other fixes to reset and push/pop might fix that?

**Comment by aksonov** [comment]
If you don't have problem without camera then it is not problem of RNRF. Maybe react-navigation and CameraKitCamera is not compatible somehow. Please try pure react-navigation first.
