### ISSUE TITLE
<Tabs tabBarOnPress() .../>, obj.scene is undefined, obj.jumpToIndex() is not a function

### ISSUE THREAD

**Issue by EyreGe** [aksonov/react-native-router-flux#3229]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "^4.0.1",
- "react-navigation": "^2.12.1",
- "react": "16.4.1",
- "react-native": "0.56.0",

### Expected behaviour

![image](https://user-images.githubusercontent.com/19946413/44831518-7df3da00-ac59-11e8-8d14-920520a10d44.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/19946413/44831588-c612fc80-ac59-11e8-8027-9038bf3ad779.png)

![qq20180830-0](https://user-images.githubusercontent.com/19946413/44831748-7da80e80-ac5a-11e8-8cc0-2c4bdb4d406e.png)

**Comment by dextermb** [comment]
For the sake of keeping things easy to read, could you post code snippets using the `<>` icon in the editor rather than screenshots.

**Comment by daviscabral** [comment]
`jumpToIndex` was removed in the `react-navigation@2` and for this reason it's not possible to use anymore (and one of the reasons that it was not even documented as stated on #2805).

**Comment by EyreGe** [comment]
I solved the problem: 
  const routeName = obj.navigation.state.key;
  obj.navigation.navigate(obj.navigation.state.routeName);
