### ISSUE TITLE
 can i remove some scene from the navigation stack 

### ISSUE THREAD

**Issue by lvst09** [aksonov/react-native-router-flux#3231]
Version
Tell us which versions you are using:

react-native-router-flux v4.0.0-beta.31
react-native v0.55

 can i remove some scene from the navigation stack  ? when i pushed two same scene after several push actions ,like A=>B=>C=>A, then I wan't to remove the first scene A

**Comment by aksonov** [comment]
Maybe you can use custom reducer with custom action to do that. Check RNRF sources, its Reducer.js, how it works with custom POP_TO.
