### ISSUE TITLE
Cannot convert object to primitive value error in dependency

### ISSUE THREAD

**Issue by thomas-yancey** [aksonov/react-native-router-flux#3233]
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.1.0 (v3 is not supported)
- react-native v0.56.0

### Expected behaviour
Build works

### Actual behaviour

Build fails when creating static bundle for release on 

/node_modules/rx/dist/rx.all.js: Cannot convert object to primitive value
what would cause this? it seems like I have added no new routes and the error came up out of the blue. I only am posting here because rx.js is a dependency from 
react-native-router-flux#opencollective#inquirer#rx

since this only occurs on the build I am having a hard time tracking down what might cause this issue, any help appreciated. Thanks

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by daviscabral** [comment]
Are you able to reproduce it with the Example or ReduxExample code provided? It might be something else in your app affecting it. 

There is no enough information here to help you - please provide a way to reproduce the error - here, both examples are building on ios and android.

**Comment by thomas-yancey** [comment]
you were right it was unrelated to this library, my mistake and thanks for responding

**Comment by daviscabral** [comment]
No worries, glad you got it working.
