### ISSUE TITLE
There is no route defined for key when using Actions.reset();

### ISSUE THREAD

**Issue by mn7676** [aksonov/react-native-router-flux#3234]
### Version
Tell us which versions you are using: 

- react-native-router-flux "^4.0.1"
- react-native 0.56.0

### My code
```

<Router>

   <Lightbox>
        <Scene key='root' headerMode='none'>
            <Scene key='login' component={Login} initial/>
            <Scene key='main' component={Main} />
            <Scene key='page' component={Page} />


        </Scene>


    </Lightbox>

</Router>


```

in page 'main' or 'page' when using `Actions.reset("login")` get error : `There is no route defined for key login Must be one of :'root'` but `Actions.push("login") or Actions.replace("login") ` is ok!!

**Comment by daviscabral** [comment]
Thank you for reporting the issue - this one is a duplicated and was already reported on #3194. 

Closing in favour to keep all information to this bug there.
