### ISSUE TITLE
Pop not working correctly in multiple stack in tabs

### ISSUE THREAD

**Issue by alimahmoodvand** [aksonov/react-native-router-flux#3238]
### Version
"react-native-router-flux": "^4.0.0-beta.28",
 "react-native": "0.54.4",
I have 2 tabs with stack and scene

Tab1 
Stack
Scene 1-1
Scene 1-2
Tab2
Stack 
Scene 2-1
Scene 2-2

I go to scene scene 1-1 => scene 2-1 => scene 1-2
then i use pop function

### Expected behaviour
I expect go to scene 2-1

### Actual behaviour
router go to scene 1-1

because scene 1-1 & scene 1-2 is in same stack and  scene 2-1  in another stack

**Comment by daviscabral** [comment]
Please try to upgrade to `beta.31` that is the last version using the same react-navigation, and if that does not work, upgrade it to `4.0.1`.  There is a discussion about turning `beta.31` into a version on #3213 - but I don't think it will get traction - so for now, there is no support for beta versions IMO.

**Comment by alimahmoodvand** [comment]
I upgrade my router flux to 4.0.1 version but my problem yet exist in pop navigation
