### ISSUE TITLE
New 3.0 version is released with breaking API changes, check README.md

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#324]
2.x version is not supported now (except critical bug fixes).

**Comment by kristianmandrup** [comment]
Awesome! I can already see the docs are getting much better :) Cheers!

**Comment by emrosenf** [comment]
@aksonov Incredible work ... this is the declarative API everyone always wanted. Any thoughts on using Redux to store state instead of NavigationRootContainer so that all of the application state can be in one store?

**Comment by aksonov** [comment]
@emrosenf Check original navigation API github:
https://github.com/ericvicenti/navigation-rfc/issues/52
Also nice discussion here:
https://github.com/ericvicenti/navigation-rfc/issues/29

So author doesn't want to unite redux/navigation states and i'm ok with it.

**Comment by emrosenf** [comment]
I assume you've seen https://github.com/jlyman/RN-NavigationExperimental-Redux-Example ? It stores state with redux and calls the NavigationStateUtils functions directly. Seems to me like it would be better to have one store for everything, right?

**Comment by tonygriv** [comment]
I have android 4.4 genymotion emulator and after switching to 3.0 version this router my app crushes and works very slow. Any Ideas?

**Comment by aksonov** [comment]
v3.0 release is just wrapper around new Experimental Navigation API. So try that API without my component (React Native UIExplorer project) and check behaviour and report if it is slow.

**Comment by tonygriv** [comment]
I have just try Example app in this repository. The same behaviour.

**Comment by aksonov** [comment]
Please read my answer again.

**Comment by zxcpoiu** [comment]
Hi @aksonov 

When using redux, and wrap `Router` under `Provider` like
```
<Provider>
    <Router />
</Provider>
```

the router will render several times if store changed, thus causing `key xxx is already defined` due to invoke `Actions.Create(props.children)` in `Router.js` several times. described at #376 ( probably NOT caused by HMR is on )

my structure like this:

```javascript
<Provider>
    <MyLogicSmartComponent>

        constructor(props) {
            super(props);
            this.myMethod = this.myMethod.bind(this);
            this.xxxx = null;
        }

        myMethod(yyyy) {
            if (this.store.myReduxData) {
                this.xxxx = yyyy;
                this.props.dispatch(xxxx)
            }
        }

        render() {
            return (
                <Router>
                    <Scene myMethod=this.myMethod>
                </Router>
            )
        }
    </MyLogicSmartComponent>
</Provider>
```

The problem with this structure is I can NOT use:

```javascript
const scene = Actions.Create(
    <Scene />
)
<Router scene={scene}>
```

Because I needs to pass `this.myMethod` down to `Scene` from `MyLogicSmartComponent`.

After playing `Example`,
I noticed that these two components `Router` and `Example` only render at the beginning no matter I jump back and forth between different `Scene`.

1. Is that normal?
2. if so, does it makes sense or hurt if add the following in `Router.js` to prevent several `Actions.Create()` ?

```diff
--- Router.js.orig
+++ Router.js
@@ -24,10 +24,14 @@
         this.state = {};
         this._renderNavigation = this._renderNavigation.bind(this);
         this._handleProps = this._handleProps.bind(this);
+        this.scenesMap = null;
     }
 
     _handleProps(props){
-        const scenesMap = props.scenes || Actions.create(props.children);
+        const scenesMap = this.scenesMap || props.scenes || Actions.create(props.children);
+        if (!this.scenesMap) {
+            this.scenesMap = scenesMap;
+        }
         const {children, style, scenes, reducer, createReducer, ...parentProps} = props;
         scenesMap.rootProps = parentProps;
         const initialState = getInitialState(scenesMap);
```


or any idea for how to wrap redux and SmartComponent with Router?

Thanks for the great job anyway!

**Comment by agrass** [comment]
I'm still having this issue of  ```Key is already defined```. Any idea how to solve it?  before upgrading react-native to 0.22 it was ok, but now is crashing due low memory

**Comment by agrass** [comment]
I already fixed the problem ```key is already defined``` creating the scenes outside the render method. The other problem of low memory it's something related with NavigationExperimental so not too much related with this repository
