### ISSUE TITLE
Pop not working correctly in multiple stack in tabs

### ISSUE THREAD

**Issue by alimahmoodvand** [aksonov/react-native-router-flux#3243]
Version
"react-native-router-flux": "^4.0.1",
"react-native": "0.54.4",
I have 2 tabs with stack and scene

Tab1
Stack
Scene 1-1
Scene 1-2
Tab2
Stack
Scene 2-1
Scene 2-2

I go to scene scene 1-1 => scene 2-1 => scene 1-2
then i use pop function

Expected behaviour
I expect go to scene 2-1

Actual behaviour
router go to scene 1-1

because scene 1-1 & scene 1-2 is in same stack and scene 2-1 in another stack
I cant reopen [#3238](https://github.com/aksonov/react-native-router-flux/issues/3238) @daviscabral
I upgrade my router flux to 4.0.1 version but my problem yet exist in pop navigation

**Comment by aksonov** [comment]
Sorry, but your desired behavior is not supported - you are manipulating with scenes from different stacks and tabs are automatically switched.
