### ISSUE TITLE
Can't navigate to the screen with Drawer

### ISSUE THREAD

**Issue by Luckygirlllll** [aksonov/react-native-router-flux#3246]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.1
- react-native v0.55.1

### Expected behaviour

Can navigate to the screen with the drawer and see the drawer

### Actual behaviour

Can't navigate to the screen with a drawer

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
```
 render () {

    return (
      <Router createReducer={this._reducerCreate}>
      <Stack key='root'>
         <Drawer
            hideNavBar
            key="drawerMenu"
            contentComponent={NavigationDrawer}
            drawerWidth={250}
            drawerPosition="left"
        >
        <Scene
          initial={isLoggedIn &&  profile.homebase && profile.drivingSince && profile.vehicleType && profile.payRate }
          key='mapScreen'
          component={MapScreen}
          navBar={PlatformNavbar}
          logo="mf-logo"
          hideNavBar={false}
        />
        </Drawer>
 </Stack>
      </Router>
    )
  }
}
```

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by daviscabral** [comment]
Take a look in the Example code. 
https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js

`Stack` and `Drawer` are both navigators - and with this structure I believe you don't need both there. Try to remove Stack and make the Drawer your root. If that does not work, put the Stack inside.
