### ISSUE TITLE
backicon_mask.png: error: Invalid filename. Unable to add.

### ISSUE THREAD

**Issue by Luckygirlllll** [aksonov/react-native-router-flux#3248]
### Version
Tell us which versions you are using:

react-native-router-flux v4.0.1
react-native v0.55.1

### Expected behaviour

Create release apk for android 

### Actual behaviour

```
Error: Invalid file name 
/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnavigationstack_dist_views_assets_backiconmask.png 
```

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. create release apk 

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by daviscabral** [comment]
The `Example` project got all the configuration got be able to generate the APK without this issue, you might copy or check it to see what to do.

This commit shows more or less what I have done to bring it back to live: https://github.com/aksonov/react-native-router-flux/commit/cd74da5f28f3a0d3c33be781a7f07463ace6b00f

Just keep the focus in the `android/` folder and you will be fine.

Closing as this error is not related with `react-native-router-flux` - but with the upgrade of Graddle and the way that it is not being able to process this PNG file. I am trying to be available in Gitter for helping with general questions and keeping the issues to manage bugs in the lib.
