### ISSUE TITLE
Error while create release apk: backicon_mask.png: error: Invalid filename. Unable to add.

### ISSUE THREAD

**Issue by Luckygirlllll** [aksonov/react-native-router-flux#3249]
Version

Tell us which versions you are using:

react-native-router-flux v4.0.1
react-native v0.55.1

Expected behaviour

Create release apk for android

Actual behaviour

Error: Invalid file name 
/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnavigationstack_dist_views_assets_backiconmask.png 

Steps to reproduce
create release apk

@daviscabral This issue relates to react-native-router-fkux because this icon is one of the modules which are inside the react-native-router-flux. 

P.S: it's kind of bad practice just to close issues without solving them and sending link to the commit with the changes in 39 files and 2000 lines of code. 

This error happened to me and can happen to any other user of that library.

**Comment by daviscabral** [comment]
Sorry, I was really trying to help. I am focusing on bugs. I hope you get the help you need.

**Comment by js1121302139** [comment]
why？ build android apk show Error？ android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnavigationstack_dist_views_assets_backiconmask.png: error: Invalid filename.  Unable to add.
 "react": "16.4.0",
    "react-native": "0.55.4",
    "react-native-router-flux": "^4.0.1",

**Comment by js1121302139** [comment]
@Luckygirlllll   #3264

**Comment by daviscabral** [comment]
This was fixed in `react-native@0.57` as stated here https://github.com/facebook/react-native/issues/16906. 

Closing since there are two possible fixes for the issue.
