### ISSUE TITLE
v3.0.7 - action should be defined

### ISSUE THREAD

**Issue by Ksantor** [aksonov/react-native-router-flux#325]
Looks like I'm doing something wrong.

index.android.js
```
'use strict';

import React, { AppRegistry, Component } from 'react-native';
import { Router, Actions, Scene } from 'react-native-router-flux';

import Home from './src/scenes/Home';

const scenes = Actions.create(
  <Scene key='root'>
      <Scene key='home' component={ Home }/>
  </Scene>
);

class MyApp extends Component {
  render() {
    return (
      <Router scenes={ scenes }/>
    );
  }
}

AppRegistry.registerComponent(MyApp', () => MyApp);
```

`<Router scenes={ scenes }/>`  gives me `action should be defined` error pointing to `Reducer.js:123`

Using RN 0.21.0

**Comment by aksonov** [comment]
Try 0.22-rc

Pavel.

**Comment by Rmannn** [comment]
After updating, i got 
Unknown plugin "transform-class-properties" specified in "***/node_modules/react-native-router-flux/.babelrc"

**Comment by aksonov** [comment]
Try 3.0.9, removed that file.

**Comment by aksonov** [comment]
Closing it for now, feel free to create issues if any.

**Comment by Rmannn** [comment]
Thanks it's working now.
