### ISSUE TITLE
SafeAreaView not working with hideNavBar

### ISSUE THREAD

**Issue by davidwu220** [aksonov/react-native-router-flux#3253]
### Version
- react-native-router-flux v4.0.1
- react v16.4.1
- react-native v0.56.0

### Expected behaviour
Wrapping `SafeAreaView` component around `View`s should provide extra paddings (in the case of iPhone X, top and bottom).

### Actual behaviour
Bottom padding was added correctly, but the top padding was not added (see screenshot 1). An `Modal` page, however, the paddings are added correctly (see screenshot 2).

![](https://raw.githubusercontent.com/davidwu220/poolpal-react-native/rnrf-issue-SafeAreaView/app/images/rnrf-issue-images/top-not-added.png)
^ *Screenshot 1*

![](https://raw.githubusercontent.com/davidwu220/poolpal-react-native/rnrf-issue-SafeAreaView/app/images/rnrf-issue-images/top-added.png)
^ *Screenshot 2*

### Steps to reproduce
1. In a `Scene` component, wrap the `View` component with `SafeAreaView` component
2. To see the edges, consider setting border styles

### Reproducible Demo
Check out my [issue branch](https://github.com/davidwu220/poolpal-react-native/tree/rnrf-issue-SafeAreaView/) to see the bug.

**Comment by aksonov** [comment]
@daviscabral are you able to reproduce the issue? I don't think that RNRF can cause the problem, because it just wraps react-natigation.

**Comment by daviscabral** [comment]
It seems some confusion around the way react-navigation works with SafeAreaView. I am facing that sometimes too - just couldn't pin-point the exactly place where it happens.

**Comment by aksonov** [comment]
@davidwu220 It is probably react-navigation issue. Update to latest react-navigation and check. If it doesn't help, please check their demos and check your issue there

**Comment by davidwu220** [comment]
So apparently after upgrading to `react-native 0.57` fixed the issue (I also installed `react-navigation 2.16`, but I imported `SafeAreaView` from `react-native`, so I don't think this is related). Thanks for the help!

**Comment by lucasanh** [comment]
Hi, I have the same problem. Please let me know if this issue is solved
