### ISSUE TITLE
Update beta27 -> 4.0.1 bug

### ISSUE THREAD

**Issue by Komalov** [aksonov/react-native-router-flux#3255]
#### 4.0.1
Tell us which versions you are using:

- react-native-router-flux v4.0.1
- react v16.2
- react-native v0.56

### Expected behaviour

I'm trying to update from beta27 to latest 4.0.1

### Actual behaviour

__Unable to resolve module react-navigation/src/views/CardStack/CardStackStyleInterpolator__

![screen shot 2018-09-12 at 12 12 34](https://user-images.githubusercontent.com/26224268/45411517-6d922500-b685-11e8-89aa-19f979692656.png)

**Comment by daviscabral** [comment]
There is an example of how to handle transition config in the Example app inside the repo that shows the correct path to import this file.

For the most recent versions (> 4.0.1) - that's something you can use from the `react-navigation-stack` package.

For the earlier versions (<= 4.0.1) that's still part of react-navigation.

Sorry, but the error there is pretty clear, the file is not there anymore.
