### ISSUE TITLE
react-native-safe-area-view@0.9.0 issue: Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by atlkuk** [aksonov/react-native-router-flux#3257]
### Version
Tell us which versions you are using:
Version 4.0.1

-->
- react-native-router-flux v4.0.1
- react v16.4.1
- react-native v0.57.0-rc.3

### Expected behaviour

That all works fine

### Actual behaviour

When i run my application this warning appears:
```
Require cycle: node_modules\react-navigation\node_modules\react-native-safe-area-view\index.js -> node_modules\react-navigation\node_modules\react-native-safe-area-view\withSafeArea.js -> node_modules\react-navigation\node_modules\react-native-safe-area-view\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
this is because of an old react-native-safe-area-view version, if you could upgrade it to 0.10.0 it'll be great!!

Thanks

**Comment by daviscabral** [comment]
Probably this warning is because you are using a react-native in a release candidate version. `react-native-router-flux` does not directly depend on that package - that's a `react-navigation` dependency. And we depend on them to update, to also get that update. 

What you can do is to use `resolutions` from yarn to lock it in a more recent version.

```
$ yarn why react-native-safe-area-view
yarn why v1.9.4
[1/4] 🤔  Why do we have the module "react-native-safe-area-view"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-native-safe-area-view@0.9.0"
info Reasons this module exists
   - "react-navigation" depends on it
   - Hoisted from "react-navigation#react-native-safe-area-view"
```

**Comment by Echelpoel** [comment]
Updating to latest version of `react-navigation` fixed this warning.
