### ISSUE TITLE
want to disable drawer 

### ISSUE THREAD

**Issue by d12544** [aksonov/react-native-router-flux#3260]
Need to disable drawer open on swiping gesture in some screen in stack navigator
panhandlers and gestureEnabled not working

**Comment by daviscabral** [comment]
maybe a typo? `gesturesEnabled` (with an S). Can you confirm it?

**Comment by daviscabral** [comment]
Duplicate of #3169.

**Comment by d12544** [comment]
GesuturesEnabled* . It was a typo. Not working
