### ISSUE TITLE
Drawer doesn't show correctly on Actions.drawerOpen()

### ISSUE THREAD

**Issue by nickfla1** [aksonov/react-native-router-flux#3262]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.1
- react v16.5.1
- react-native v0.57.0

### Expected behaviour
Calling `Actions.drawerOpen();` opens and renders the drawer correctly.

### Actual behaviour
An overlay appears instead of the drawer; changing scene/tab and then changing back to the interested scene renders the drawer correctly

![image](https://user-images.githubusercontent.com/1572060/45436250-9f6db080-b6b2-11e8-98b3-396b7dacbbf4.png)

### Steps to reproduce
```
<Drawer
   key='userProfile'
   drawerPosition='right'
   navBar={CustomNavbar}
   contentComponent={Menu}
   hideNavBar
>
   <Scene
       key='userProfileInner'
       component={NewProfile}
       hideNavBar
       initial
   />
</Drawer>
```

```
<TouchableOpacity 
    onPress={() => {
        Actions.drawerOpen()
    }}
    hitSlop={{ left: 15, top: 15, right: 15, bottom: 15 }}
>
    <Icon name="menu" size={verticalScale(35)} color={white} />
</TouchableOpacity>
```

**Comment by aksonov** [comment]
I can't reproduce. Please check examples/react-native and its Drawer. Feel free to modify example and demonstrate this bug.

**Comment by iamsee** [comment]
same issue when set drawer below tabs like this 
![image](https://user-images.githubusercontent.com/6944557/46004533-bc0fdc80-c0e5-11e8-8cce-ad1a12ad30b3.png)
![image](https://user-images.githubusercontent.com/6944557/46004603-de095f00-c0e5-11e8-9052-fd9cdcf8e400.png)
it's broken on android

**Comment by daviscabral** [comment]
Example code is working fine on Android.

![android](https://user-images.githubusercontent.com/4285/46022111-5bb67600-c0b8-11e8-9cc9-9f7a46246e19.gif)

**Comment by iamsee** [comment]
@daviscabral 
yes,but the example code  tab scene is below the drawer
![image](https://user-images.githubusercontent.com/6944557/46054641-caf49e80-c17a-11e8-8f01-989daf5e5dc9.png)

and set drawer below the tabs 
![image](https://user-images.githubusercontent.com/6944557/46054674-f24b6b80-c17a-11e8-8b4c-2e9e79037fbf.png)

only the mask show 
![image](https://user-images.githubusercontent.com/6944557/46054696-042d0e80-c17b-11e8-8ff3-2ba7a23f548c.png)

**Comment by iamsee** [comment]
@daviscabral  
i try that
![image](https://user-images.githubusercontent.com/6944557/46055577-32ace880-c17f-11e8-9308-5d069f18a495.png)
![image](https://user-images.githubusercontent.com/6944557/46055595-46584f00-c17f-11e8-8251-f0f3c8bb0af9.png)

same result

**Comment by daviscabral** [comment]
@iamsee it seems this is the issue https://github.com/react-navigation/react-navigation/issues/2743 of `react-navigation`.

You can track it here: https://github.com/react-navigation/react-navigation/issues/4154.

**Comment by iamsee** [comment]
thx
