### ISSUE TITLE
about PopTo

### ISSUE THREAD

**Issue by SwitchDestiny** [aksonov/react-native-router-flux#3268]
### Version
Tell us which versions you are using:
- react-native-router-flux 3.43.0
- react 16.3.1
- react-native 0.55.4

Scene A => B => C =>D ,When I want to return to A from D，I use Actions。popTo（A），but，This has an animation effect。All pages will flash past.

How to solve this problem?

**Comment by aksonov** [comment]
3.43 is not supported anymore, sorry
