### ISSUE TITLE
How to call nested scenes multiple times (Child keys must be unique)

### ISSUE THREAD

**Issue by Rmannn** [aksonov/react-native-router-flux#327]
When I use nested scenes as following 
profile (currentUser) => View => profile (OtherUser) 
I get an error 
Warning: flattenChildren(...): Encountered two children with the same key, `.0:$card_profile`. Child keys must be unique; when two children share a key, only the first child will be used.

Is there a way to push a view that already exists ? When the user is different in my case.

**Comment by peterlazar1993** [comment]
@aksonov Facing the same issue, not sure what I'm doing wrong 
```
const scenes = Actions.create(
  <Scene key="root" hideNavBar>
    <Scene key="auth" component={Auth} />
    <Scene key="leaderboard" component={LeaderBoard} />
  </Scene>
```
It works if I change the scene type to ```replace``` though.

**Comment by aksonov** [comment]
@Rmannn could you create separate 'action' with separate key for  profile (OtherUser)  ?

**Comment by Rmannn** [comment]
This is what i did. but,
The navigation stack should allow us to push same scene (different instance) to the stack.
The solution works only if we plan to navigate throught those scenes only once.

if I do 
profile (currentUser) => View => user_profile (OtherUser1) => View => user_profile (OtherUser2) 
This will fail with the same error.

**Comment by chenxiaohu** [comment]
I think need dynamic scene to face this type problem, but I can't find any example..
Use case：
User_1 page open User_2, there are many different users(1,2,3....999...) , and in navigator stack more than one

**Comment by aksonov** [comment]
please check 3.0.11

**Comment by Rmannn** [comment]
Thank you, this is working now.
I was trying to do it over a PR.

Something we should do is when we Jump to the tabs (root), do not animate each children.
If the stack is really huge, we will have an animation like the end of a solitaire game. Cards are moving until Jump is done.

if I do 
user_profile (User) => user_profile (OtherUser1) => View => user_profile (OtherUser2) => JUMP to user_profile (User) 
All children OtherUser1, OtherUser2 will be animated until User.

**Comment by aksonov** [comment]
Check Example and set duration to {1} for Scene to avoid animations. Maybe you could propose PR for that. For example you could wrote own custom renderer based on TabBar without animation.

I'm closing this ticket.

**Comment by Rmannn** [comment]
Thanks, I will try to propose some PR if I modify the renderer.

**Comment by Rmannn** [comment]
For those who are searching how to override the TabView default behavior, 
You have to override the TabView Component and override the NavigationCardStack _setTiming Default function.
Because when you have scene inside tabs, we use a NavigationCardStack instead of the default NavigationAnimatedView. Changing the duration for cards inside tabs has no effect. (using duration={1}) on tab scenes.
