### ISSUE TITLE
jump to create new page is failed

### ISSUE THREAD

**Issue by EyreGe** [aksonov/react-native-router-flux#3271]
### Version
Tell us which versions you are using:

- "react-native-router-flux": "^4.0.1"
- "react": "16.4.1",
- "react-native": "0.56.0",

### Expected behaviour
HomePage --> LoginPage --> RegisterPage --> LoginPage --> RegisterPage
click login button in HomePage jump to LoginPage, then click register button in LoginPage jump to RegisterPage, then click login button in RegisterPage jump to create new LoginPage 

### Actual behaviour
Actually, when click login button in RegisterPage back to last LoginPage

App.js
   <Router>
        <Stack key="root">
          <Scene key="home" clone component={Home} />
          <Scene key="login" clone component={Login} />
          <Scene key="register" clone component={Register} />
        </Stack>
      </Router>
![image](https://user-images.githubusercontent.com/19946413/45610687-6d33c880-ba8f-11e8-819e-13610a8edcc1.png)

jump:
  onPress={() => Actions.push('register')}

I would be grateful for any help
Thanks in advance!

**Comment by aksonov** [comment]
I can't reproduce this issue. Please change any of our examples accordingly to demonstrate the issue.
