### ISSUE TITLE
Android drawer slow switching between stacks

### ISSUE THREAD

**Issue by Komalov** [aksonov/react-native-router-flux#3273]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.1
- react v16.2
- react-native v0.56

### Expected behaviour

When I am navigating between stacks on android, it should be as fast as on iOS, or close to it

### Actual behaviour
When I am navigating between stacks on my android (actually I am navigating to specific scene of different stack), it's have delays sometimes (1-2 secs, sometimes more). Navigating between scenes in the same stack is extreamly fast everywhere.

What I was worry about:
latest version - done, I updated it
remove console.logs from entire app
check gebug mode - checked, I am totally in release mode

Maybe the cause of this problem is my undertanding of on/onEnter prop, so please fix me if I am using onEnter wrong
```
<Scene
  component={Any}
  ..props
  on={() => {
     request()
     anotherRequest()
  }}
/>
```
It's the same on iOS and android, except on iOS I have ```tabs={true}``` and ```lazy={true}```. So I just replace __tabs__ to __drawer__ on android, and specify contentComponent for Drawer at upper stack which is my entire app

I have ``hideNavBar={true}`` everywhere btw

**Comment by aksonov** [comment]
Yes, it is possible that you are doing something CPU-intensive within your `onEnter`. You should use `InteractionManager.runAfterInteractions` https://facebook.github.io/react-native/docs/interactionmanager
