### ISSUE TITLE
Unable to access component instance in onRight/onLeft

### ISSUE THREAD

**Issue by thedjinn** [aksonov/react-native-router-flux#3274]
### Version

- react-native-router-flux v4.0.1
- react v16.5.1
- react-native v0.57.0

### Problem

I have a scene inside a stack and want to attach some behaviour to the right nav bar button. The router looks roughly like this (irrelevant scenes removed):

```jsx
<Router>
    <Stack>
        <Scene key="myScreen" component={MyScreen} title="My Screen" rightTitle="Add" />
    </Stack>
</Router>
```

Now, the problem is that I want to call some method on the component instance. One thing I can do is add the `onRight` prop to the `Scene`, but this does not give me access to the component instance, only the component class. Another approach is to add a `static onRight()` to the component, but once again, no access to the component instance.

Is this functionality currently missing or not working properly? Or am I missing something myself? The documentation and examples are not very clear on how to properly implement this pattern. Thanks for any assistance!

**Comment by aksonov** [comment]
You can use `Actions.refs.SCENE_KEY` to access component ref.
