### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by bm-software** [aksonov/react-native-router-flux#3276]
### Version
- react-native-router-flux v4.0.1
- react v16.4.1
- react-native v0.57.0

With [this](https://github.com/aksonov/react-native-router-flux/commit/d61960c6bf0139150a327a161b3d9374c6d6772f#diff-b52768974e6bc0faccb7d4b75b162c99) commit typings for `Reducer` and `createReducer` (`RouterProps`) have been removed. 
Could you re add them again please?

**Comment by daviscabral** [comment]
PR #3281 merged.
