### ISSUE TITLE
Modal and nested Stack routing configuration

### ISSUE THREAD

**Issue by bm-software** [aksonov/react-native-router-flux#3277]
### Version
- react-native-router-flux v4.0.1
- react v16.4.1
- react-native v0.57.0

From the example I see that structure:

    <Router createReducer={reducerCreate} onStateChange={stateHandler} getSceneStyle={getSceneStyle} uriPrefix={prefix}>
        <Overlay key="overlay">
          <Modal key="modal" hideNavBar transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forFadeFromBottomAndroid })}>
            <Lightbox key="lightbox">
              <Stack key="root" titleStyle={{ alignSelf: 'center' }}>
                <Scene key="echo" back clone component={EchoView} getTitle={({ navigation }) => navigation.state.key} />
                <Scene key="launch" component={Launch} title="Launch" initial type={ActionConst.RESET} />
    			
    			...
              </Stack>
    
              <Scene key="demo_lightbox" component={DemoLightbox} />
            </Lightbox>
            <Scene key="error" component={ErrorModal} />
            <Stack key="login" headerLayoutPreset='center' path="login/:data" titleStyle={{ alignSelf: 'center' }}>
              <Scene key="loginModal" component={Login} title="Login" onExit={() => console.log('Login: onExit')} leftTitle="Cancel" onLeft={Actions.pop} />
              <Scene key="loginModal2" component={Login2} title="Login2" onEnter={() => console.log('Login2: onEnter') } backTitle="Back" panHandlers={null} duration={1} />
              <Scene key="loginModal3" hideNavBar component={Login3} title="Login3" onEnter={() => console.log('Login3: onEnter') } onExit={() => console.log('Login3: onExit')} panHandlers={null} duration={1} />
            </Stack>
          </Modal>
    
          <Scene component={MessageBar} />
        </Overlay>
      </Router>

I'm trying to reproduce that structure and I started from `Modal` only. This is my code ( obviously inside `Router`)

    <Modal key='modal' hideNavBar transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal })}>
        <Stack key='root' navigationBarStyle={sharedStyles.header} titleStyle={{alignSelf: 'center'}}>
            <Scene key='landing' component={LandingScreen} initial
                type={SceneType.RESET as ActionConstShort}
                hideNavBar/>
            <Scene key='signIn' component={SignInScreen}
                title='Accedi'
                titleStyle={sharedStyles.headerTitle}
                type={SceneType.RESET as ActionConstShort}
                init/>
            <Scene key='home' component={HomeScreen} initial
                title={config.app.name}
                titleStyle={sharedStyles.headerTitle}
                init
                renderRightButton={() => <HomeHeaderRight onAccount={() => {Navigation.account()}} onAbout={() => {Navigation.about()}} />}/>
            <Scene key='account' component={AccountScreen}
                title='Gestione Account'
                titleStyle={sharedStyles.headerTitle}
                headerTintColor='white'/>
            <Scene key='about' component={AboutModal}
                title='Informazioni'
                titleStyle={sharedStyles.headerTitle}
                headerTintColor='white'/>
        </Stack>
        <Scene key='login' component={LoginScreen}
                title='Accedi'
                titleStyle={sharedStyles.headerTitle}
                headerTintColor='white'/>
    </Modal>

Intially the app load "landing" then if I call `Actions.signIn()` the following error is thrown:

> There is no route define for key signIn. Must be one of: 'root','login'

If I put the `signIn` scene outside from `root` at the same level of `login` scene it works fine but it is shown as Modal and I don't want that. I would like to keep it inside `root` as a normal scene. 

How can I solve this?

**Comment by aksonov** [comment]
You have to use 'replace' not reset as type
