### ISSUE TITLE
Actions.Scenename cause render multiple time and cause getWrappedInstance return undefined

### ISSUE THREAD

**Issue by timeturnback** [aksonov/react-native-router-flux#3278]
RNRF version : v4.0.1

This is my render nav button function
`renderSubjectInfoRightButton(props) {
      return (
        <NavButton onPress={()=>{Actions.refs.SubjectDoc.getWrappedInstance().onRight();}}
          name='md-options'
          type='ionicon'
          color={color.black}/>
        )
    }`
this is the scene
`<Scene key="SubjectInfo"
                                   navigationBarStyle={{backgroundColor: "#fff"}}
                                   titleStyle={navTitleStyle}
                                   component={SubjectInfo} title="Thông tin bệnh nhân"
                                   renderRightButton={this.renderSubjectInfoRightButton}
                                   renderLeftButton={this.renderCloseButton}/>`

The problems is some time I go to scene with Actions.SubjectInfo() , it cause SubjectInfo render 3 time , and when I click to the right button it return 
![screen shot 2018-09-19 at 21 23 51](https://user-images.githubusercontent.com/6651194/45765867-4f698d80-bc60-11e8-8729-66926d5f8b11.png)
The problems is sometime this bug come out . It work manytime but some time it render 3 time and throw the error

UPDATE : this prolems cause by pop the scene then go into the other sence immediately .
Ex : I'm in Subject info scene , I pop out the go to Subject scene right away (delay about <0.5 second)

**Comment by aksonov** [comment]
This use case is not supported - `Actions.refs` is not immediately available but only when screen component is created and mounted.

**Comment by timeturnback** [comment]
Ok. I understand I have my way to fix that problems . Just wanna report to dev team about the issue that when you pop and then go to the scene right away , the scene is render twice or triple with the old props , then the new props . This may cause some malfunction
