### ISSUE TITLE
Action should be defined

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#328]
`2016-03-17 10:55:19.464 [info][tid:com.facebook.React.JavaScript] 'ACTION:', null
2016-03-17 10:55:19.465 [error][tid:com.facebook.React.JavaScript] action should be defined
2016-03-17 10:55:19.467 [fatal][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: action should be defined`

I used your sample code
any solutions?

**Comment by Rmannn** [comment]
You must use 3.0.9 (Latest) 

"react": "^0.14.7",
"react-native": "0.22.0-rc4",
"react-native-router-flux": "^3.0.9",

**Comment by erikdung** [comment]
I got same error, how to fix it?

**Comment by Rmannn** [comment]
Update to the latest version using npm and packages versions

**Comment by shishircc** [comment]
I have same issue and I have the latest (^3.0.11) package form npm. The sample code does not work.

**Comment by liangmicha** [comment]
I am having the same issue     
"react-native": "^0.21.0",
  "react-native-router-flux": "^3.0.10",

**Comment by aksonov** [comment]
@liangmicha check above and README about required react-native version (0.22-rc) before posting. Hope that will upgrade to 0.22 on Monday...Closing this.

**Comment by subtirelumihail** [comment]
You should keep this open until the react native gets upgraded :)

**Comment by joshbedo** [comment]
Having the same issue

**Comment by joshbedo** [comment]
Better hope you have absolutely no dependencies if you use this plugin. All these breaking changes are killing me. Now i upgrade and i can't use my existing websocket setup >.<

**Comment by itinance** [comment]
Why is this closed? Having the same issue: https://github.com/aksonov/react-native-router-flux/issues/680
