### ISSUE TITLE
Iphone X has a line in the middle of the tabbar

### ISSUE THREAD

**Issue by yoyo0427** [aksonov/react-native-router-flux#3280]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.1
- react v16.2.0
- react-native v0.52.0

### Expected behaviour
No line

### Actual behaviour
If the tabbar has four tabs, there is a line. If it is 3 tabs, it is normal.
![1](https://user-images.githubusercontent.com/12933263/45801015-35be5980-bce5-11e8-914d-cc9ffe2126af.png)

![2](https://user-images.githubusercontent.com/12933263/45800969-145d6d80-bce5-11e8-82b3-55c3e5faa5df.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.Running on iphone x
2.the tabbar has four tabs

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
I don't see any line for example project, feel free to modify our examples to demonstrate the issue.

**Comment by yoyo0427** [comment]
@aksonov

**Comment by yoyo0427** [comment]
I revised the example project.

**Comment by yoyo0427** [comment]
I revised your example.

**Comment by aksonov** [comment]
Please check core react navigation examples
