### ISSUE TITLE
android navbar position wrong with navTransparent

### ISSUE THREAD

**Issue by wangshangming** [aksonov/react-native-router-flux#3291]
### Version
- react-native-router-flux v4.0.3
- react v16.5.1
- react-native v0.57.1

### Expected behaviour
The nav contents stay at the middle of the view in Android which was normal @4.0.0-beta.31

### Actual behaviour
![image](https://user-images.githubusercontent.com/12669392/46000023-fffce480-c0d9-11e8-81cb-3523627c0e3d.png)
stay at the bottom

### Steps to reproduce
my code:
```
<Scene
     {...configs}
     component={CommonView(component)}
     navTransparent
/>
```
common view is a HOC to hack a customized navbar like
```
({navbarStyle, fullScreen = false, barStyle, ...compProps}) => (
        <View style={{flex: 1}}>
            <StatusBar barStyle={barStyle}/>
            {!fullScreen && <View style={[styles.narbarWrapper, navbarStyle]}/>}
            <Component {...compProps}/>
        </View>
);
```
'View' is the actual area to contain the backButton and title with some customized style.The position of the nav contents went wrong even if simply use navTransparent.

**Comment by daviscabral** [comment]
Please fill the issue template properly. Without that, it's not possible to help.
