### ISSUE TITLE
Question: Is RN v0.57.1 a mandatory for RNRF v4.0.3?

### ISSUE THREAD

**Issue by oleole90** [aksonov/react-native-router-flux#3297]
### Version
- react-native-router-flux v4.0.1
- react v16.5.2
- react-native v0.56.1

I'm having issues while upgrading from v4.0.1 to v4.0.3. Initial route works, but cannot navigate anymore, using: Actions.sceneKey(); but Actions.jump('sceneKey'); works!

Anyway, I'll open a more detailed issue soon if I can reproduce this but before upgrading my RN version, I wanted to know if it's worth the risk.
Cheers!

**Comment by daviscabral** [comment]
Can you please also provide the installed version of `react-navigation`? Also - I believe that's not the recommended `react` version for this `react-native` version.

**Comment by oleole90** [comment]
react-navigation v2.16.0

If you want me to run any experiments I can do that and share here. Like set breakpoints in RNRF's code on action dispatches within my app.

Here is what my routes looks like:
https://gist.github.com/oleole90/a3f2b9acc8d7c612a3b13809d8f56b3c

Splash > Intro (fails silently)
Splash > Demo (works fine)
Both works fine on 4.0.1

![image](https://user-images.githubusercontent.com/4123376/46128910-d917ed00-c256-11e8-9857-3800af92a095.png)

Splash.js
```
import { Actions as NavigationActions } from 'react-native-router-flux';

// after login
NavigationActions.Intro();
```

**Comment by daviscabral** [comment]
Sorry - I only read right the title of the issue now - answering it: I don't think 0.57 is mandatory - examples were updated to 0.57 recently, before that, it were using 0.56 - but with previous version of react, and also with babel locked to beta-46, that were the versions they were supposed to work.

I recommend you to lock to the recommended versions - and also follow the instructions from here: https://github.com/react-native-community/react-native-releases/blob/0.57/CHANGELOG.md

**Comment by daviscabral** [comment]
@oleole90 sorry - but was that the fix for your issue? do you mind sharing what fixed it?

**Comment by oleole90** [comment]
Not fixed. Going back to digging how RNRF works on provided Example app then hopefully find out why Navigation/SET_PARAMS isn't firing in my app. (3 days and counting...I'm in deep trouble!)

Closed this issue because it was a question and you've answered it.

**Comment by aksonov** [comment]
Make sure you use the same react navigation for both cases. Then try to reproduce issue with our example
