### ISSUE TITLE
why the tabs works like this?

### ISSUE THREAD

**Issue by JinnL** [aksonov/react-native-router-flux#3298]
### Version
Tell us which versions you are using:
    "react": "16.3.1",
    "react-native": "^0.55.4",
    "react-native-router-flux": "^4.0.4",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.12.1"

Expected behaviour

the tabBar title should show normal.

![gi 5r ap q4vn9vn gnnui](https://user-images.githubusercontent.com/12424815/46185776-ff4c9400-c30d-11e8-9009-2c017b008538.png)

but when in  react-native-router-flux V3 that work normal on android devices

Reproducible `demo`

> <Router backAndroidHandler={this._backAndroidHandler}>
            <Stack  key="root" hideNavBar>
                <Scene tabs key="tabbar">
                    <Scene key="tab1" initial icon={TabIcon} tabIcon='home'  title='home' navigationBarStyle={{ backgroundColor: '#ffdb42' }}>
                        <Scene key='home' component={Login} hideNavBar />
                    </Scene>
                    <Scene key="tab2" icon={TabIcon} tabIcon="headphones"  title="music" navigationBarStyle={{ backgroundColor: '#ffdb42' }}>
                        <Scene key="music" component={Music} title="OOXX" />
                    </Scene>
                    <Scene key="tab3" title="heart" icon={TabIcon} tabIcon="heart"  navigationBarStyle={{ backgroundColor: '#ffdb42' }}>
                        <Scene key='favorite' title='where' component={Login} />
                    </Scene>
                </Scene>
            </Stack >
        </Router>

> export class TabIcon extends Component {
    render() {
        return (
            <View style={{ justifyContent: 'center', alignItems: 'center' }}>
                <Icon name={this.props.tabIcon} size={20} color={this.props.selected ? "yellow" : '#666'} />
                <Text style={{ color: this.props.selected ? 'yellow' : '#666', marginTop: 5, fontSize: 12 }}>{this.props.title}</Text>
            </View>
        )
    }
}

**Comment by daviscabral** [comment]
Remove title from your `TabIcon` and it will should work as expected.

Expo example shows something similar to your code.
https://github.com/aksonov/react-native-router-flux/blob/master/examples/expo/navigation/AppNavigator.js#L99
https://github.com/aksonov/react-native-router-flux/blob/master/examples/expo/components/TabBarIcon.js

**Comment by JinnL** [comment]
# #

**Comment by JinnL** [comment]
thanks  a lot . but how to change tabBarLabel text color?

**Comment by JinnL** [comment]
thanks again.i have find the  attribute activeTintColor  .

**Comment by daviscabral** [comment]
Glad it worked - react-navigation have changed a lot - and rnrf also due to it.
