### ISSUE TITLE
undefined is not an object(evaluating 'context._currentValue=currentValue')

### ISSUE THREAD

**Issue by RtzX** [aksonov/react-native-router-flux#3299]
Version:
"react": "^16.3.0-alpha.0",
 "react-native": "0.55.0",
 "react-native-router-flux": "^4.0.4",
QAQ:
![qq20180928-173038](https://user-images.githubusercontent.com/13709644/46200602-9c2a2400-c344-11e8-93b4-c6364e67b820.png)

**Comment by aksonov** [comment]
Not related to RNRF
