### ISSUE TITLE
Example broken with latest react-native-navbar

### ISSUE THREAD

**Issue by puzzfuzz** [aksonov/react-native-router-flux#33]
Just leaving this incase anyone else runs into it - when using the example to launch a modal using the `NavBarModal` component from this example and running against the latest stable `react-native-navbar` (1.0.4 at the time of this writing) I'm getting the following exception:

```Argument 0 (BOOL) of RCTStatusBarManager.setHidden must not be null```

A fix for this is detailed in the below issue on that project.
https://github.com/Kureev/react-native-navbar/issues/100

**Comment by lrettig** [comment]
I'm having the same problem. Thanks for reporting.

**Comment by shinework** [comment]
+1

**Comment by aksonov** [comment]
Should be fixed within latest version, i'm using standard RN NavigationBar instead now.

**Comment by niftylettuce** [comment]
+1 Still doesn't work
