### ISSUE TITLE
RCTRootView.h file not found

### ISSUE THREAD

**Issue by 5amfung** [aksonov/react-native-router-flux#330]
As soon as I open the project file in xcode, there's an error.

![image](https://cloud.githubusercontent.com/assets/371691/13839926/48d251fc-ebdc-11e5-9f71-123f619629c9.png)

**Comment by aksonov** [comment]
Have you run npm install ?

**Comment by 5amfung** [comment]
Yes.  I ran ```npm install``` in the example directory as well as the project directory.
