### ISSUE TITLE
Implementation of 3D Touch "Peek and Pop"

### ISSUE THREAD

**Issue by LeviWilliams** [aksonov/react-native-router-flux#3301]
Version 4.0.0-beta.31

React navigation has an exposed "peek and pop" method for utilizing 3d Touch in this now merged pull request [https://github.com/wix/react-native-navigation/pull/2186](here). Is there any way we can take advantage of this? I've messed around with the navigator and haven't been able to figure it out.

Expected behaviour:

![32990015-486219dc-ccef-11e7-92f3-e69735fbd6d2](https://user-images.githubusercontent.com/32551245/46224637-24dc9c00-c314-11e8-9d33-434bbb889b2b.gif)

**Comment by daviscabral** [comment]
Sorry - that's not possible. v4.0.0-beta-31 is not using react-native-navigation - it is using react-navigation 1.5. That is a different library.

**Comment by daviscabral** [comment]
I will keep this opened as a feature-request in case someone would like to work on it.
