### ISSUE TITLE
Can't push to new scene in componentDidMount

### ISSUE THREAD

**Issue by alexborton** [aksonov/react-native-router-flux#3302]
### Version
- react-native-router-flux v4.0.1
- react v16.3.1
- react-native (expo 29.0.0 - 0.55 i think!)

### Expected behaviour
Should be able to push to a new scene on a condition when a scene mounts

### Actual behaviour
Nothing seems to happen...

### Steps to reproduce
I have a scene which mounts. If there us a condition met on that scene, i want to push/pop/replace (none work) to the correct screen.

Code looks something like this;

```
  componentDidMount = () => {
    const { userProfile } = this.props
    if (!userProfile.seenIntro) this.showIntroScreen()
  }
```

```
  showIntroScreen = () => Actions.introScreens()
```

nothing seems to work with this. The only way i seem to be able to navigate to the screen is specifically though onPress functions and i can't see why - the principle should remain the same.

**Comment by aksonov** [comment]
It is normal, use `setTimeout`
