### ISSUE TITLE
While back navigation default navbar visible over custom  navebar

### ISSUE THREAD

**Issue by jariwalabhavesh** [aksonov/react-native-router-flux#3304]
### Version
- react-native-router-flux v4.0.5
- react v16.3.1
- react-native v0.55.1

### Expected behavior

**IOS**
If we had provided custom navbar component then default navbar should not be visible while back 
transition

**ANDROID**
The back button is replaced with hamburger icon before page move to the previous page.

### Actual behavior
- I have 3 pages in sample app login, home, detail.
- I had configured custom navbar in route.
- I have navbar only visible on the detail page and hidden on login and home page.

**IOS**
When I go home to detail page then no issue but when I go back from detail to home page then navbar is flickering, It is hiding custom navbar and show default navbar of RNRF while back transition.

**ANDROID**
In Android when I go back from detail to home page then navbar icon replaced with back arrow button from hamburger icon while back transition.

You will find both android and ios issue video here in the repo (It also content regenerated issue code) : [https://github.com/jariwalabhavesh/RNRF_NAVBAR_ISSUE.git](https://github.com/jariwalabhavesh/RNRF_NAVBAR_ISSUE.git)

### Steps to reproduce
I had already reproduced the issue with minimal code which is here : [https://github.com/jariwalabhavesh/RNRF_NAVBAR_ISSUE.git](https://github.com/jariwalabhavesh/RNRF_NAVBAR_ISSUE.git)

And Steps to reproduce:
1. Clone https://github.com/jariwalabhavesh/RNRF_NAVBAR_ISSUE.git
2. npm install
3. react-native run-android / react-native run-ios
4. You will see home page with GO TO DETAIL button, Click on **GO TO DETAIL** button
5. Now on detail page click on **GO BACK** and observe top navbar while a back transition and you should able to see an issue(Please run with both android and ios)

Repo also content videos(android/ios) in which you can see issue

**Comment by jariwalabhavesh** [comment]
@aksonov : any update on this issue?

**Comment by Eng-Ahmedelsayed** [comment]
any updates?

**Comment by chunkhang** [comment]
I faced a similar issue as well. Solved it by using `headerMode="screen"` for the `<Stack>`.
