### ISSUE TITLE
Drawer navbar shows even when drawer is closed

### ISSUE THREAD

**Issue by RobinJayaswal** [aksonov/react-native-router-flux#3309]
v4.0.5

I just upgraded from v4.x.x.beta to v4.0.5. I did not change any of my code (shown below), but suddenly the navigation bar on my Drawer scene always shows, not just when my drawer is open. It used to work as expected, only showing the drawer navigation bar when the drawer was open. Now I get stacked navbars when the subscenes also have a navbar.

Is this expected behavior in the latest? And if so, how would you recommend having a navbar on my drawer component that only shows when the drawer is open?

```javascript
 <Scene
              key="drawer"
              contentComponent={MyDrawerComponent}
              type="replace"
              ....
              drawerLockMode="locked-open"
              navigationBarStyle={styles.navigationBarWithBackButton} // NOTE: this navbar now shows always, even when the drawer is closed
              renderLeftButton={customLeftBackButton}
              renderRightButton={customRightSettingsButton}
              drawer
 >
    <Tabs
         key="main"
         drawerLockMode="locked-open"
          navigationBarStyle={styles.homeNavigationBar}
    >
      ....
    </Tabs>
</Scene>
```

**Comment by RobinJayaswal** [comment]
A workaround I can do is making MyDrawerComponent have a navbar directly, and just having hideNavBar on my top level drawer scene. But I am wondering if there is a more natural way to achieve my desired behavior.

**Comment by aksonov** [comment]
Your approach is correct, I'm closing this issue
