### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#332]
HI, I'm having trouble with the navBar. When I set the navbar hidden = true, The bar will be hidden when pushed but not so in tab bar scene.

**Comment by aksonov** [comment]
have you set hideNavBar for that scene?

**Comment by ajoshdee** [comment]
I have a tab scene as my initial scene. but the navbar is not visible when the container scene's navbar is not set to hidden=true. But when I set it to false, the navbar will appear. but when i press a button on my launch page, the pushed page doesn't show the navbar.

**Comment by ajoshdee** [comment]
`<Scene key="main">
    <Scene key="tab" component={TabBar} tabs={true} initial={true}>
        <Scene key="board" component={ExamBoard} title="Exam Board" initial={true} icon={TabIcon}/>
        <Scene key="profile" component={ProfileView} title="Profile" icon={TabIcon}/>
        <Scene key="setting" component={TabView} title="Settings"  icon={TabIcon}/>
        <Scene key="more" component={TabView} title="More"  icon={TabIcon}/>
    </Scene>
    <Scene key="administrative" component={Admin_Exam} title="Assessment" leftTitle=" "/>
    <Scene key="communications" component={Communications_Exam} title="Assessment" leftTitle=" "/>
    <Scene key="creativity" component={Creativity_Exam} title="Assessment" leftTitle=" " />
    <Scene key="human_relations" component={HR_Exam} title="Assessment" leftTitle=" "/>
    <Scene key="leadership" component={Leadership_Exam} title="Assessment" leftTitle=" "/>
    <Scene key="problem_solving" component={Problem_Solving_Exam} title="Assessment" leftTitle=" "/>
    <Scene key="emotional_quotient" component={EQ_Exam} title="EQ Exam" leftTitle=" "/>
    <Scene key="result" component={ResultView} title="Human Interaction Skills" leftTitle=" "/>
  </Scene>`

**Comment by aksonov** [comment]
Could you modify Example to show the problem?

**Comment by ajoshdee** [comment]
To put it simply, it acts just like a switch, if i turn the container scene off I can see the navbar of the tab scenes, but can't see the navbar of the other scenes . If I turn it on, I can't see the navbar of the tab scenes, but can see the navbar of the other scenes.

**Comment by ajoshdee** [comment]
oh I solved it, I just needed to set my tab scene's nav bar to false.
