### ISSUE TITLE
Why could only React Native 0.22-rc is supported?

### ISSUE THREAD

**Issue by KBLNY** [aksonov/react-native-router-flux#333]
Hi,
Quick question, why does the doc for 3.0.10 states "React Native 0.22-rc is supported, it could not work with earlier or later versions"?
What could break react-native-router-flux with other versions than RN 0.22-rc?
Thanks for spotting out the parts of RN 0.22-rc you use that early or late versions could not support.
Best

**Comment by peterlazar1993** [comment]
@KBLNY  It is using NavigationExperimental which is available from 0.22 only I guess

**Comment by dan-lee** [comment]
Yes, this is the reason. But React 0.22 should be released Mar 21, if you want to use a stable RN version

**Comment by aksonov** [comment]
0.22 is supported now.
