### ISSUE TITLE
Route stopped working when upgrading 4.0.1 -> 4.0.5

### ISSUE THREAD

**Issue by handoff** [aksonov/react-native-router-flux#3330]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.5
- react 16.6.0-alpha.8af6728
- react-native 0.57.3

### Expected behaviour
Tab2 is a settings view. Clicking a row should open the settings for that row.
See router below.

### Actual behaviour
When in tab2, nothing happens when pressing the row that should open tab2Scene2. This worked in version 4.0.1.

### Steps to reproduce
When in tab2, I should be able to open the scene 'tab2Scene2', and from there open the modal 'tab2Scene2Popup'.

    <Router>
    <Scene key="root" hideNavBar>
        <Tabs key="tabs" >
            <Scene 
                key="tab1" 
                component={Tab1} 
                title="tab1" 
            />
            <Stack 
                key="tab2" 
                title="tab2" 
            >
                <Modal hideNavBar>
                    <Scene
                        key="tab2Scene2" 
                        component={Tab2Scene2} 
                    />
                    <Scene 
                        key="tab2Scene2Popup"
                        component={Tab2Scene2Popup}
                    />
                </Modal>
                
                <Scene
                    key="tab2Scene3" 
                    component={Tab2Scene3} 
                    title="tab2Scene3" 
                />
            </Stack>
        </Tabs>
    </Scene>
    </Router>

**Comment by forsen** [comment]
Try to give the Modal component a `key` prop, and navigate to that one instead. Navigating to the first scene in a Stack, Modal or Tabs would (at least in earlier versions) mount the scene twice, so navigating to the Stack/Modal/Tab directly to open the first scene is a better approach.
