### ISSUE TITLE
Disable Transition(sliding) animation while navigating between Scenes

### ISSUE THREAD

**Issue by Kazn** [aksonov/react-native-router-flux#3331]
I m using react-native-router-flux v4.0.4

I m trying to disable animation while navigation between screens. Not in tabs.
I have used this one
`<Scene key="home" component={home} duration={0} hideNavBar={true}/>`

`duration={0}` and `animationEnabled={false}` are not working .Are there any solution

**Comment by marciobera** [comment]
@Kazn, it worked for me in this way:

`<Router>
	<Tabs hideTabBar key="root">
		<Scene key="loading" component={Loading} initial hideNavBar />
		<Scene key="login" component={Login} hideNavBar />
		<Scene key="loginForm" component={LoginForm} hideNavBar />
		...
	</Tabs>
</Router>`

**Comment by Kazn** [comment]
I m not using in tabs.have you checked in iphone as well

**Comment by marciobera** [comment]
> I m not using in tabs.have you checked in iphone as well

Try use this:
`<Scene key="home" component={home} hideNavBar  swipeEnabled={false} animationEnabled={false} panHandlers={null} />`

It worked on both iOS and Android for me. (I'm using the 4.0.5 react native router flux version).

**Comment by aksonov** [comment]
@marciobera is correct

**Comment by 1453alabanda** [comment]
> > I m not using in tabs.have you checked in iphone as well
> 
> Try use this: `<Scene key="home" component={home} hideNavBar swipeEnabled={false} animationEnabled={false} panHandlers={null} />`
> 
> It worked on both iOS and Android for me. (I'm using the 4.0.5 react native router flux version).

thanks
