### ISSUE TITLE
Can access screen when add Drawer

### ISSUE THREAD

**Issue by kyunkakata** [aksonov/react-native-router-flux#3332]
When i add Drawer on my code : 
``
<Drawer
                hideNavBar
                key="drawerMenu"
                contentComponent={SideMenu}
                drawerWidth={250}
                drawerPosition="right"
            >
   <Scene key="screen1" component={screen1} hideNavBar={true}
          
       />
   <Scene key="MainScreen" component={MainScreen} hideNavBar={true}
        initial
       />
</Drawer>
<Scene key="screen2" component={screen2} hideNavBar={true}
        
       />
``
I can't use Action.push("screen1") when it is in screen 2. 
I tried to use Action.screen1({type:ActionConst.RESET}) but state of screen1 cannot change. It didn't change to default value I set.
How to fix it. Thank you

**Comment by aksonov** [comment]
Sorry, not enough information. Please check provided examples with Drawer
