### ISSUE TITLE
Hide back button

### ISSUE THREAD

**Issue by HyperNovax** [aksonov/react-native-router-flux#3336]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.5
- react v16.3.1
- react-native v0.55.4

### Expected behaviour
I'm trying to hide the back button.
I read the doc and I used different properties but none works.

### Actual behaviour
The back button image is visible.

So, is it possible to hide the back button ?

**Comment by aksonov** [comment]
You should use `type='replace'` so new scene will be first within the stack.
