### ISSUE TITLE
Drawer is working weirdly.

### ISSUE THREAD

**Issue by jackychanfox** [aksonov/react-native-router-flux#3339]
I opened the drawer and clicked "Login" item on drawer
after that, when I click back button, I can see the opened drawer till now.
how can I fix this issue?

I used drawer of react-native-router-flux.

```
<Scene key="root" >
       <Scene key="Login" component={Login} hideNavBar/>
       <Scene key="SignUp" component={SignUp} hideNavBar />
       <Scene key="Drawer" 
              drawer 
              contentComponent={SideDrawer} 
              initial 
              hideNavBar 
              drawerWidth={Constants.Window.width*0.7}>
              <Scene key="Main" component={Main} hideNavBar/>
              <Scene key="Test" component={Test} hideNavBar />
       </Scene>
</Scene>
```

**Comment by aksonov** [comment]
You should manually close drawer after tap, it is intended behavior

**Comment by jackychanfox** [comment]
How to close drawer manually?
After navigation to another scene, when I close drawer, original scene is displaying again.
Could you explain in detail?

**Comment by aksonov** [comment]
Check example project
