### ISSUE TITLE
Actions.{destination-component} not working when located inside a method

### ISSUE THREAD

**Issue by DeToxer** [aksonov/react-native-router-flux#334]
Instead of having Actions.Help directly inside the onPress of the button, im calling a method like so : onPress={this.handleOnPress}. The method looks like this:

`_handleOnPress(){
    Actions.Help;
}`

This does not work, but if i have the Actions.Help directly inside the onPress it works just fine.
Is this a knows bug or am i doing something wrong?

I have this problem several places in my app.

**Comment by aksonov** [comment]
Actions.Help is Function!

**Comment by aaroncrawford** [comment]
I'm having this issue as well.  When I pull Actions.<key> out of the onPress I'm getting flooded with 

> setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

If I put back to the onPress, everything behaves normally.  And I am utilizing the correct syntax e.g. :

_handleOnPress() { Actions.register(); }

I'm utilizing ES6 classes, if that makes any difference.  Any thoughts?
