### ISSUE TITLE
Actions.pop(refresh: { }) cannot trigger componentWillReceiveProps at children scene

### ISSUE THREAD

**Issue by NelGarbuzova** [aksonov/react-native-router-flux#3344]
### Version

"react-native-router-flux": "4.0.5",
"react-native": "^0.56.0",
"react": "^16.4.1"

### Expected behaviour

Actions.pop({refresh:{}}) would trigger componentWillReceiveProps at Drawer scene
The children scene should also trigger componentWillReceiveProps.

### Actual behaviour

Actions.pop({refresh:{}}) would trigger componentWillReceiveProps at Drawer scene but not children scene.

### Steps to reproduce
1. Wrap scenes in parent scene or Drawer.
2. Use Actions.sceneKey to go from one scene to another.
3. Use Actions.pop({refresh:{}});
4. View returns to previous scene. componentWillReceiveProps() calls on Drawer, but not calls on children scene.

**Comment by yrjwcharm** [comment]
可以 加个时间戳 Actions.pop({refresh:{date:new Date()}); 就可解决。

**Comment by aksonov** [comment]
Sorry, it is not supported right now. Feel free to submit PR

**Comment by gancheng** [comment]
Actions.pop({refresh: {}, timeout: 1})

**Comment by RukaiJohn** [comment]
Actions.pop({refresh: {}, timeout: 1})

this stops the app for 1 second so you really can't click or do anything

**Comment by MiloHwb** [comment]
@RukaiJohn It appears that time unit is not second. I tried, can solve my problem, and quite quick.
