### ISSUE TITLE
problem with tabbar when drawer is child of tabbar

### ISSUE THREAD

**Issue by samandaryaei** [aksonov/react-native-router-flux#3346]
may menu app is : 

<Router>
 <Scene hideNavBar>

     <Scene key="splash" component={Splash} title="Splash" initial/> 

      <Scene key="root" hideNavBar>

        <Scene key="login"     component={Login}     title="Login" initial/>
        <Scene key="favorite"  component={Favorite}  title="favorite"/>

        <Tabs 
              key="tabbar" 
              animationEnabled={true}
              swipeEnabled={true}
              tabBarPosition="bottom"
              activeTintColor={ Common.BRAND_COLOR_1 }
              inactiveTintColor= { Common.BRAND_COLOR_2 }
        >

        <Drawer
          key="drawer"
          contentComponent ={ DrawerLayout }
          drawerPosition="right"
          drawerWidth={250}
          icon={ ({ tintColor }) => <Icon name="user" size={30} color={tintColor} /> }
          // style={{ zIndex : 0 }}
         
          titleStyle={{ fontFamily:'IRANSansMobile' }}
        >
            <Scene hideNavBar>  
              <Scene key="profile" component={Profile} initial />
              <Scene key="faq" component={FAQ} />
              <Scene key="aboutUs" component={AboutUs} />
              <Scene key="contactUs" component={ContactUs} />
            </Scene>
       </Drawer>

        <Scene key="course" icon={ ({ tintColor }) => <Icon name="graduation-cap" size={30} color={tintColor} /> } title="دوره ها" titleStyle={{ fontFamily:'IRANSansMobile' }}>
           <Scene component={Course} title="Course"/>
          </Scene>

          <Scene key="video" icon={ ({ tintColor }) => <Icon name="film" size={30} color={tintColor} /> } titleStyle={{ fontFamily:'IRANSansMobile' }}  initial >
           <Scene key="videoList" component={VideoList} hideNavBar initial />
          </Scene>

          <Scene key="event" icon={ ({ tintColor }) => <Icon name="calendar" size={30} color={tintColor} /> }  titleStyle={{ fontFamily:'IRANSansMobile' }} >
           <Scene component={Event} title="Event"/>
          </Scene>

          <Scene key="podcast" icon={ ({ tintColor }) => <Icon name="podcast" size={30} color={tintColor} /> }  titleStyle={{ fontFamily:'IRANSansMobile' }} >
           <Scene component={Podcast} title="Podcast"/>
          </Scene>

        </Tabs>

      </Scene>

    </Scene>

  </Router>

//----------------------------------------------------------------------------
my drawerlayout component is : 
export default class DrawerLayout extends Component {
    render () {
        return (
            <View style={{ flex:1,backgroundColor:Common.BRAND_COLOR_3 }}>
                <View style={{ justifyContent:'center',alignItems:'center',paddingTop:15 }}>
                <Thumbnail source={require('./../../../assets/images/OHImageLogo-min.png')} style={{ width:"45%",height:100 }}/>
                </View>

                <Item style={{ padding:10,justifyContent:"flex-end" }} onPress={()=>Actions.replace('faq')}>
                    <Text style={{ fontFamily:"IRANSansMobile",marginRight:10,color:Common.BRAND_COLOR_2 }}>...</Text>
                    <Icon name="question-circle" size={30} color={Common.BRAND_COLOR_1} />
                </Item>

                <Item style={{ padding:10,justifyContent:"flex-end" }} onPress={()=>Actions.replace('aboutUs')}>
                    <Text style={{ fontFamily:"IRANSansMobile",marginRight:10,color:Common.BRAND_COLOR_2 }}>....</Text>
                    <Icon name="info-circle" size={30} color={Common.BRAND_COLOR_1} />
                </Item>

                <Item style={{ padding:10,justifyContent:"flex-end" }} onPress={()=>Actions.replace('contactUs')}>
                    <Text style={{ fontFamily:"IRANSansMobile",marginRight:10,color:Common.BRAND_COLOR_2 }}>.....</Text>
                     <Icon name="at" size={30} color={Common.BRAND_COLOR_1} />
                </Item>

            </View>
        );
    }
}
//----------------------------------------------------------------------------

when i run app at android emulator tabbar and drawer is show and tabbar work success but when i press drawer button , drawer not show and The screen is black but when switch to another tab and go previous tab drawer menu Appears !!!!

**Comment by aksonov** [comment]
Make Drawer as parent for Tabs
