### ISSUE TITLE
componentWillMount called more than once, componentWillUnmount not called on scene change

### ISSUE THREAD

**Issue by liangmicha** [aksonov/react-native-router-flux#335]
Hi all, I am running into an issue with react-native-router-flux where componentWillMount for one of my components is being called more than once.

I am using  react-native-router-flux: "^2.3.12"

so if I switch from Component1 (Groceries) to Component 2 (Detail) and switch back to Component1, componentWillMount for Component1 is called again for that first component.

I have some important listeners that I don't want to register twice in componentWillMount

and for some reason componentWillUnmount isn't called either

I am using redux, anyone have this issue also?

Here's my code snippet of my two tabs (tabbarGrocerties and tabberDetail)
```
class Application extends Component {
  render() {
    return (
          <Router hideNavBar={true} name="root">

              <Schema name="withoutAnimation"/>

              <Route name="signin" component={SignIn} title="Register"/>
              <Route name="tabbar">
                  <Router footer={TabBar} hideNavBar={true}>
                      <Route name="tabbarGroceries" schema="tab" title="Groceries TODO" component={Groceries} hideTabBar={true}/>
                      <Route name="tabbarDetail" schema="tab" title="Detail" component={Detail} />
                  </Router>
              </Route>
          </Router>
    );
  }
}
```

Groceries render contains:
```
<Text onPress={Actions.tabbarDetail}> Click here to go to detail </Text>
```

Detail.js  render contains
```
<Text onPress={Actions.tabbarGroceries}>Click to go to groceries</Text>
```
 
Both Action is imported like this:

```
var Actions = require('react-native-router-flux').Actions;
```

**Comment by aksonov** [comment]
Are you sure that all route have 'switch' type, check Example project for details? Anyway 2.x is not supported anymore, you need to use 3.0 release
