### ISSUE TITLE
Remove icon from tabbar but still have the route inside the tabs

### ISSUE THREAD

**Issue by ThomasLarge** [aksonov/react-native-router-flux#3350]
**Version 4.0.1**

Is there a way to have a screen in a tab bar route but not display it in the tabbar? for example I have the following code;

```
<Scene
        key="Tabs"
        tabs={true}
        tabBarPosition="bottom"
        activeBackgroundColor="white"
        inactiveBackgroundColor="white" 
        inactiveTintColor="black"
        activeTintColor={'#00AF99'}
	tabBarStyle={{
		backgroundColor: 'white'
	}}
	swipeEnabled={false}
	animationEnabled={false}
	panHandlers={null}
	hideNavBar={true}
	>
	<Scene key="Welcome" component={Welcome} />
		<Scene
			key="SystemBuilder"
			backTitle=""
			component={SystemBuilder}
			icon={SystemBuilderIcon}
			rightTitle={<View />}
		/>
		........... 	
         </Scene>
 </Scene>
```
And this is what it looks like on the app 
![screenshot 2018-11-09 at 14 29 33](https://user-images.githubusercontent.com/15890942/48270672-807d6780-e432-11e8-8e1b-7a72c2f2bd69.png)

I don't want the welcome link in the tabbar

**Comment by aksonov** [comment]
You may create another tabbar (with `hideTabBar` option) with two children - Welcome and your current tabbar

**Comment by ThomasLarge** [comment]
@aksonov are you able to give me a example?
