### ISSUE TITLE
 Key xxx is already defined!(all keys)

### ISSUE THREAD

**Issue by JohnTree** [aksonov/react-native-router-flux#3351]
### Version
Tell us which versions you are using:

- react-native-router-flux v3.37.0
- react v16.0.o
- react-native v0.4.4

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
Not enough information
