### ISSUE TITLE
Actions.refresh onExit prop not being passed

### ISSUE THREAD

**Issue by ibbi** [aksonov/react-native-router-flux#3357]
### Version

- react-native-router-flux v4.0.6
- react v16.6.1
- react-native v0.57.5 (not supported?)

### Expected behaviour
onExit function should be the newly assigned one, just like title and other props change on refresh of scene.

### Actual behaviour
onExit function either remains the same if initialized, or remains null if not initialized.

### Steps to reproduce
1. Use Actions.refresh, with onExit prop passed in
2. after scene refreshes, go back/press back button. The function called isnt the new one passed. However, title has updated.

### Reproducible Demo
`Actions.refresh({
  title: 'hello',
  onExit: () => { console.log('world'); }
});`

full context at https://github.com/ibbi/simplestretch/blob/master/src/components/StretchScreen.js

**Comment by shubhang93** [comment]
Try Wrapping your Actions.refresh in a setTimeout

**Comment by aksonov** [comment]
It is not supported
