### ISSUE TITLE
Does react-native-router-flux support swipe back gesture?

### ISSUE THREAD

**Issue by lvst09** [aksonov/react-native-router-flux#3359]
My code is like this 

     <Provider store={store}>
                    <Router hideNavBar={true}>
                        <Stack key="root"  hideNavBar={true}>
                            <Scene key='RootTab'
     ...

I want to know how to enable swipe back action , like click back button , if was supported.

**Comment by adelowo** [comment]
In my experience, on iOS, the swipe back gesture is supported.
