### ISSUE TITLE
Back Button Styling

### ISSUE THREAD

**Issue by stolinski** [aksonov/react-native-router-flux#336]
Love the package so far. I'm currently re-writing my code for v3 and wondering how to change the style, (more importantly the color) of the back button. Thanks!

**Comment by aksonov** [comment]
Does backButtonStyle work?

**Comment by stolinski** [comment]
Did not work, or at least `backButtonStyle={{color:'white'}}` didn't work.

**Comment by aksonov** [comment]
@stolinski It will not work because default back button is just image with blue arrow. Just render your own button, using renderBackButton method

**Comment by stolinski** [comment]
Weird. I would have thought it to be an SVG that could be styled rather
than an actual blue image. Bummer.



SCOTT TOLINSKI
www.scotttolinski.com

**Comment by aksonov** [comment]
It is what used now in React Native NavigationHeader component. Feel free to submit PR with  better solution

**Comment by stolinski** [comment]
Will do.



SCOTT TOLINSKI
www.scotttolinski.com

**Comment by suibobuzhuliu** [comment]
I'm really need it!
