### ISSUE TITLE
Why the first scene does not response swipe back action?

### ISSUE THREAD

**Issue by lvst09** [aksonov/react-native-router-flux#3367]
<Provider store={store}>
                    <Router hideNavBar={true}>
                        <Stack key="root" hideNavBar={true} >
                            <Scene key='RootTab'
                                   component={RootTabRD}
                                   duration={1}/>
...

My code is like this , while the second and after scene can response the swipe back gesture to pop current scene ,but at the root scene , the swipe back gesture is not responsed .
The question is where is the code does the router judge if or how to responsed the swipe back guesture, i want to hack the callback to implement the function to pop out from react native root scene to native VC!

**Comment by bhaskardabhi** [comment]
@lvst09 did you find any solution for this?
