### ISSUE TITLE
Why is Overlay not documented?

### ISSUE THREAD

**Issue by telmen** [aksonov/react-native-router-flux#3369]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.6
- react v16.6.1
- react-native v0.57.7

### Expected behaviour

Either `<Overlay />` or `<Scene overlay` components should be documented.

### Actual behaviour

There is no documentation found.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
It is true. Overlay is explained via our examples but it is definitely not enough. PR is welcome.
