### ISSUE TITLE
Private scene component

### ISSUE THREAD

**Issue by mahyar33** [aksonov/react-native-router-flux#3371]
hi
I couldn't handle onEnter with [#3283 ](https://github.com/aksonov/react-native-router-flux/issues/3283)solution
I want to create PrivateSeen component if the user didn't authorize, it redirects them to login scene
can you give me an example, please?

**Comment by LeviWilliams** [comment]
Many solutions to this have been shown in this repository for auth protecting scenes. One example: #1668

**Comment by aksonov** [comment]
Thank you, @LeviWilliams
