### ISSUE TITLE
What is LegacyTabs ?

### ISSUE THREAD

**Issue by Nikosmonaut** [aksonov/react-native-router-flux#3377]
Hello,

Are legacy tabs deprecated or will be ? There is no more options "swipeEnabled" between tabs ?

**Comment by aksonov** [comment]
For some (unknown) reasons `swipeEnabled` was removed from react-navigation 2.x that is why we added 'legacy' and support for old tabs. I'm not sure what is the status of `swipeEnabled` within latest react-navigation 3.x. I will try to support it but I can't promise, need to complete migration to 3. first: https://github.com/aksonov/react-native-router-flux/issues/3393
