### ISSUE TITLE
It is possible create a drawer view with height  smaller than screen?

### ISSUE THREAD

**Issue by giovanischiar** [aksonov/react-native-router-flux#3386]
I need a drawer scene that is smaller than screen, it is possible with this library?

### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.0
- react v16.3.0
- react-native v.52.6

**Comment by aksonov** [comment]
It is not supported. Maybe with react-navigation 3.x it could be possible, but I'm not sure
