### ISSUE TITLE
Support react navigation 3.x

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#3393]
We need to support latest react-navigation (currently RNRF supports react-navigation 2.x)

**Comment by darrencruse** [comment]
I've been using react-navigation a bit but was finding it a little confusing for more complex needs.

I'd not looked at RNRF I do like the look of it - it seems to address what I wasn't liking about react-navigation which is partly that it just doesn't feel very easy doesn't feel very "react like".

I am using react-navigation v3 though on a greenfield project for a client that won't go live for almost a year so I don't see us even considering using RNRF without it supporting v3.

So two questions:
a.  How long has it typically taken RNRF to support a new version of react-navigation?

b.  (the most interesting question to me):  Has there been any discussion of the react-navigation and RNRF projects merging and making RNRF part of react-navigation?

(even if react-navigation feels their approach is super super flexible I could imagine the RNRF way being there for newbies or for simple needs and their current way being more an advanced option)

**Comment by aksonov** [comment]
a. It seems to be not difficult to migrate to v3, I will commit new 'alpha' release in following days
b. I talked with Eric Vicenti two years ago and he personally didn't like idea of JSX for routes (scenes). As I understand other members of react-navigation don't like it as well, so RNRF will live as separate component for those who likes this idea.

**Comment by aksonov** [comment]
Hi all,

4.1.0-beta.2 supports react-navigation now. Please check and create issues if any.
