### ISSUE TITLE
Can it use with react-redux/native ???

### ISSUE THREAD

**Issue by w-site** [aksonov/react-native-router-flux#34]
The problem is that if use react-redux/native and wrap Router component with connect method from  react-redux/native it will not be updated. So how I can update it ?

**Comment by aksonov** [comment]
Sorry, it doesn't support Redux at this moment

**Comment by w-site** [comment]
Yep, I look throw source and understood it. So currently I can use it if i wrap every component that pass to Route with connect method from react-redux/native. Seems it work for me ) Thanks.
