### ISSUE TITLE
How to have a transparent background?

### ISSUE THREAD

**Issue by alexmngn** [aksonov/react-native-router-flux#340]
On the v2, I was able to have a transparent background on my scene, but now with the v3 I'm not able to do this anymore.
How can I set my Router/Scene to have a transparent background?
Thanks

**Comment by aksonov** [comment]
The problem in NavigationCard of React Native package:
```
      <Animated.View
        {...panHandlers}
        style={[styles.main, animatedStyle]}>
        {this.props.renderScene(sceneProps)}
      </Animated.View>
```

So the component can't pass own style to NavigationCard and it is weird. Please create issue there if you want it to be fixed:
https://github.com/ericvicenti/navigation-rfc

**Comment by alexmngn** [comment]
The NavigationCard in the last React Native 0.22rc-4 has the following:
```
     <Animated.View
        {...panHandlers}
        style={[styles.main, style]}>
        {this.props.renderScene(sceneProps)}
      </Animated.View>
```

`style` is a prop and I'm not sure how to access it via Scene/Router @aksonov ?

**Comment by aksonov** [comment]
Looks like rc4 doesn't have this code, only latest master branch, and i was not able to run our Example with latest branch (it just shows white screen), so you have to wait. Maybe this component needs some changes like passing style to NavigationCard or AnimatedNavigationView but i can't test it now.

**Comment by aksonov** [comment]
Looks like rc4 doesn't have this change, but master does. Anyway i've added this feature to the component (once NavigationCard will have style support, it should work), release 3.0.14

**Comment by zelphir** [comment]
How to override this value here: https://github.com/aksonov/react-native-router-flux/blob/master/src/DefaultRenderer.js#L88

**Comment by aksonov** [comment]
Check code above:
```
             style={[styles.animatedView, navigationState.style]}
``

**Comment by zelphir** [comment]
@aksonov saw that, but where and how should I pass the style? in the Router? In each `Scene`? What if I want to set it globally? could you give me an example?

Thanks

**Comment by aksonov** [comment]
For each scene.  If you want to set globally you can wrap View around Router, but current Navigation API doesn't support it, you have to wait until current master  will be published as i said above.

**Comment by zelphir** [comment]
ok, which parameter should I use for each scene?

**Comment by aksonov** [comment]
Read my answer again. i said 'master', not rc-4...

**Comment by aksonov** [comment]
@zelphir You may use new feature #356 with 3.1.0 - you can pass some property to all scenes from Route. So you could pass sceneStyle, for example, and then use props.sceneStyle within your Scene...

**Comment by zelphir** [comment]
@aksonov thanks!

**Comment by 7daysofrain** [comment]
Im still having this problem, cant make the scene transparent with 3.26.1. I cant see the background Image. Please can somebody help me? Thanks

`            <View style={styles.container}>
                <Image source={require('Correos/imgs/bg-photo.jpg')} style={styles.background} />
                <Router style={styles.overbox} sceneStyle={styles.routerScene}>
                    <Scene key="home" component={LoginView} title="Home" />
                </Router>
            </View>`

`    container:{
        flex:1,
        backgroundColor: "black"
    },
    routerScene:{
        backgroundColor: "transparent"
    },
    background:{
        flex:1,
        resizeMode: 'cover',
        width: null,
    },
    overbox: {
        position: "absolute",
        left:0,
        top:40,
        backgroundColor: "transparent",
        width: width,
        height: height
    },`

**Comment by ssomnoremac** [comment]
this works but the previous scene is visible underneath. Should be an easy fix to animate it further off screen. Is there an api for that?
