### ISSUE TITLE
When pop the Scene "componentDidMount" is invoked when navigating a lightbox inside a tabbar

### ISSUE THREAD

**Issue by matteocollina** [aksonov/react-native-router-flux#3418]
### Version
- react-native-router-flux v4.0.0-beta.31
- react-native-cli: 2.0.1
- react-native: 0.55.4

### My Router
```
Router
  Stack
     Scene key="Landing"
     Tabs key="tab_root"  tabBarComponent={CustomTabBarComponent}
          #1st section
          Lightbox key="First"
             Drawer
                Scene key=A initial
                Scene key=B
        
          #2nd section
          Lightbox key="Second"
             Drawer
                Scene key=C initial
                Scene key=D
```
           
### Expected behaviour

From Scene "Landing": `Actions.reset('tab_root_logged');`
From Scene "A": Actions.B()
From Scene "B": Actions.pop()
**componentDidMount of Scene "A" should not be invoked**

### Actual behaviour

**componentDidMount of Scene "A" is invoked**

**Comment by matteocollina** [comment]
any news ?

**Comment by nevin22** [comment]
any news ?

**Comment by matteocollina** [comment]
I found a solution (the closing of the tags has been omitted):

Router
  Stack
     Scene key="Landing"
     Scene key="tab_root_logged"
     Tabs tabBarComponent={CustomTabBarComponent}
          #1st section
          Scene="section_first"
                Drawer
                   Scene
                     Scene key=A initial
                     Scene key=B

          #2nd section
          Scene="section_second"
                Drawer
                   Scene
                     Scene key=C initial
                     Scene key=D
        

From Scene "Landing": Actions.reset('tab_root_logged');
From Scene "A": Actions.B()
From Scene "B": Actions.pop()

From a tab section to another tab section use: Actions.jump("section_second")
