### ISSUE TITLE
react-native-router-flux navigates to default when a system dialog pops up in iOS

### ISSUE THREAD

**Issue by handoff** [aksonov/react-native-router-flux#3431]
### Version

- react-native-router-flux@4.0.6 
- react@16.6.3 
- react-native@0.58.3

### Expected behaviour
The user will stay on the current route (scene) when a system dialog pops up.

### Actual behaviour
When a user accesses some features for the first time, like the camera, iOS will pop up a system dialog asking for permission to use the resource. When that dialog pops up, react-native-router-flux navigates to the default route. This is, of course, not desired.

**Comment by pistonsky** [comment]
Damn... This one is dangerous!

**Comment by kashanshah** [comment]
Facing the same issue.. even when the keyboard pops up, navigated to the root scene!

**Comment by MosesEsan** [comment]
@handoff Did you find a solution for this?

**Comment by kamleshsindhal08** [comment]
Facing the same issue, any solution for both android and IOS

**Comment by handoff** [comment]
@MosesEsan No, sorry. I thought this was such a big issue that @aksonov would be able to look into it, but it has been some time now...

**Comment by handoff** [comment]
@MosesEsan @kamleshsindhal08 - I found a workaround. The problem is that the router component gets re-rendered, right? So in your router component class add this method:
```
shouldComponentUpdate() { 
    return false;
} 
```

**Comment by handoff** [comment]
@MosesEsan @kamleshsindhal08 - I found a workaround. The problem is that the router component gets re-rendered, right? So in your router component class add this method:
```
class RouterComponent extends Component {
...
shouldComponentUpdate() { 
    return false;
} 
...
render() {
        return (
            <Router>
            ...
            </Router>
...
```

**Comment by Krutarth-Dave** [comment]
> @MosesEsan @kamleshsindhal08 - I found a workaround. The problem is that the router component gets re-rendered, right? So in your router component class add this method:
> 
> ```
> class RouterComponent extends Component {
> ...
> shouldComponentUpdate() { 
>     return false;
> } 
> ...
> render() {
>         return (
>             <Router>
>             ...
>             </Router>
> ...
> ```

Many thanks. After two days of efforts, this solved the issue. Phew!
