### ISSUE TITLE
Change drawerPosition dynamically based on what you press 

### ISSUE THREAD

**Issue by ThomasLarge** [aksonov/react-native-router-flux#3432]
### Version

- react-native-router-flux v4.0.6
- react v16.5.0
- react-native v0.57.1

Hi I'm trying to find a way I can change the drawerPosition based on what the user is pressing/clicking. I have created a Drawer and I'm using redux to change the component that is displayed based on what icon the user presses. This works great but I want to be able to change it from 'left' to 'right' too.

I have tried this with Redux but it re-renders the whole router and creates a lot of issues. Is there a different way around this? Can I pass props to the "Actions.drawerOpen();"? 

Any help would be great, all I need is two drawers one to come from the left and one to come from the right. 

I have tried the following below but as the store doesn't refresh in the router then the left and right doesn't change. Also attached are the two buttons I'm pressing one on the left and one on the right

<img width="403" alt="screenshot 2019-02-22 at 07 05 27" src="https://user-images.githubusercontent.com/15890942/53226461-fb316200-3672-11e9-8107-fe863b2f37f9.png">

Router 
```
<Drawer
	hideNavBar
	key="drawer"
	drawerPosition={store.nav.drawType == 'mainNav' ? 'left' : 'right'}
	contentComponent={Menu}
>
Scenes here
</Drawer>
```
Menu
```
class Menu extends Component {
	constructor(props) {
		super();
	}
	render() {
		const { drawType } = this.props;

		if (drawType === 'mainNav') {
			return <DrawerContent />;
		} else if (drawType === 'notifications') {
			return <Notifications />;
		} else {
			return <DrawerContent />;
		}
	}
}
function mapStateToProps(store, ownProps) {
	return {
		drawType: store.nav.drawType
	};
}
export default connect(mapStateToProps)(Menu);
````

**Comment by ashar-sarwar-viabletree** [comment]
@ThomasLarge have you found any solution for changing drawer position dynamically .?

**Comment by ThomasLarge** [comment]
@ashar-sarwar-viabletree I didn't I moved to react navigation
