### ISSUE TITLE
renderNavigationBar

### ISSUE THREAD

**Issue by ylquankai** [aksonov/react-native-router-flux#344]
Hi~How to use renderNavigationBar(props) method? I implement it in my class,but it does not work. Can you give a example for it? thank you.

**Comment by ylquankai** [comment]
I found 

childrenState.component.renderNavigationBar 

is undefine

in NavBar.js

**Comment by aksonov** [comment]
Have you provided static renderNavigationBar method for your component? Then it cannot be undefined...

**Comment by ylquankai** [comment]
class Login extends React.Component {
    renderNavigationBar(props){
      return <View/>
    }

    render(){
        return (
            <View style={[styles.container, this.props.style]}>
                <Text>Login page: {this.props.data}</Text>
                <Button onPress={Actions.loginModal}>Login 2</Button>
                <Button onPress={Actions.pop}>Back</Button>
            </View>
        );
    }
}

Here is my demo code, it's not work for renderNavigationBar.

**Comment by aksonov** [comment]
Ugh, method is not static....

**Comment by ylquankai** [comment]
I see~ thank you very much.

**Comment by walidvb** [comment]
In my case, the navBar is rendered at the bottom of the page, rather than the top. tried removing all styles from the top/wrapping view of my component, without luck.

Also, I was trying to pass down my redux states, but it seems it isn't part of the `props` passed to the static method :/

**Comment by pewh** [comment]
I know this is an old issue. But I get navBar is rendered at the bottom of the page. Tested on latest version (3.36.0)

**Comment by robinschaaf** [comment]
The only way I could get the navbar to render at the top was to absolute position it like this, and set a height:
`    position: 'absolute',
    top: 0,
    left: 0,
    right: 0
`
