### ISSUE TITLE
Upgrade from 4.0.0-beta28 to 4.0.6 being unable to push screen

### ISSUE THREAD

**Issue by acollazomayer** [aksonov/react-native-router-flux#3447]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.6
- react v16.6.3
- react-native v0.58.6

### Expected behaviour

When doing `Action[key]()` pushes to the next screen

### Actual behaviour

Does nothing.

**Comment by alittletf** [comment]
its `Actions` not `Action`...

`Actions.key();` as well as `Actions[key]();` should work on v4.0.6

**Comment by acollazomayer** [comment]
@aksonov I Love how this was closed. This was not the issue though. Is still not working. Something that was working after the update everything broke. However i am switching the navigation library.

Thanks it was really good while it last
