### ISSUE TITLE
Component will Unmount

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#345]
Hi, i'm getting this warning and its slowing my app whenever i put something in ComponentWillUnmount. This does not occur in previous versions. 
 `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

**Comment by Tarkzeng** [comment]
I have this problem too. Is there any api to know if the component is already not exist in this window?

**Comment by aksonov** [comment]
This component is just wrapper around NavigationExperimental API. Just reproduce it with UIExplorer examples (without this component) and post your issues there:
https://github.com/ericvicenti/navigation-rfc
