### ISSUE TITLE
babel-plugin-lodash

### ISSUE THREAD

**Issue by astulip** [aksonov/react-native-router-flux#3452]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.1.0-beta.4
- react v16.8.1
- react-native v0.58.1

with error:(node_modules/react-native-router-flux/src/Reducer.js:  Lodash chain sequences are not supported by babel-plugin-lodash.
Consider substituting chain sequences with composition patterns.
See https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba

**Comment by aksonov** [comment]
Latest version doesn't use `chain` but only `isEqual`, please give me exact stack trace with error.

**Comment by astulip** [comment]
Sorry, I retest today and found that the problem is no longer there.

> react v16.8.5
> react-native 0.59.2
> react-navigation 3.5.1
