### ISSUE TITLE
Changing transition animations in v3

### ISSUE THREAD

**Issue by robclouth** [aksonov/react-native-router-flux#347]
Hi, how do you change the transition animations in v3?

**Comment by aksonov** [comment]
You have to implement it by yourself using React Native Animated API. Check AnimatedNavigationView. I've already posted request to add bottom to top animation there:
https://github.com/ericvicenti/navigation-rfc/issues/47

**Comment by aksonov** [comment]
Looks like documentation about custom animation is here:
https://github.com/ericvicenti/navigation-rfc/pull/53

**Comment by aksonov** [comment]
I've added support of direction, check Example for 3.0.14, Login page
