### ISSUE TITLE
scenes transitions' animation  about 3.0.11 is slower then 2.x

### ISSUE THREAD

**Issue by xushuwei202** [aksonov/react-native-router-flux#349]
scenes transitions' animation  about 3.0.11 is slower then 2.x

**Comment by aksonov** [comment]
It is fully configurable by using duration property.

**Comment by aksonov** [comment]
I'm fine to change 'default' duration if you can say exact value for native iOS animation duration. Now it is equal to 500ms.

**Comment by xushuwei202** [comment]
after test,  I think 300ms is ok
