### ISSUE TITLE
Can not navigate without {type:"reset"} - App is freezing

### ISSUE THREAD

**Issue by hakkikonu** [aksonov/react-native-router-flux#3498]
### Version
version: 4.0.6

    "@react-native-community/async-storage": "^1.4.2",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-elements": "^1.1.0",
    "react-native-facebook-account-kit": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-iap": "^2.5.5",
    "react-native-router-flux": "^4.0.6",
    "react-native-vector-icons": "^6.5.0"

### Expected behaviour

When I use `Actions.pageB()` in pageA, it should navigate without freezing.

### Actual behaviour

Currently I have two pages. Initial page is pageA, second page is pageB.

When I try to navigate from pageA to pageB with Actions.pageB() in `<Button onPress={() => Actions.pageB()} title="Go to page B" />`

It should go to pageB scene. But when i press to button app is freezing. 

pageB is empty component and only it rendering 

`<View><Text>This is page B</Text></View>`
.

When I console.log("page b loaded"), it returns page b loaded. So in background Scene is loading but, app does not show rendered page when i press button.

--

Currently I solve this issue with `Actions.pageB({type:"reset"})`.

But If use type:"reset", Router stack cleaning. So I can not use navbar back buttons.

What is the problem here?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create a button and two page. Go to pageB from pageA with `Actions.pageB()`
2. When debugged, pageB is loaded.
3. App freezing

My router is;

```
<Router>
            <Scene key="root">
                <Scene key="pageA" component={pageA} title="Page A" initial />
                <Scene key="pageB" component={pageB} title="Page B" />
            </Scene>
</Router>

```

**Comment by tinpt123** [comment]
ActionConst.RESET will block back button, it only use splash screen. check again import component.

**Comment by hakkikonu** [comment]
I solved problem. See this page: https://stackoverflow.com/questions/56752564/app-freezes-on-ios-when-navigate-to-another-screen-react-navigation
