### ISSUE TITLE
Navigating to tab's child routes

### ISSUE THREAD

**Issue by iZaL** [aksonov/react-native-router-flux#350]
currently its not possible to navigate to a tab's child routes from another tab. to make this behavior, if we insert this code
`<Button onPress={Actions.tab1_2}>Switch to tab1_2</Button>`
to **TabView** class  from the Example folder  and try to navigate to that route from any tabs except **tab1**, the router fails to navigate to the tab1_2 scene

**Comment by aksonov** [comment]
It looks like enhancement. "JUMP" action within new Navigation API just switches tab. As I see you want to do PUSH + JUMP in the same action... Have you tried to jump to tab1 and then push to tab1_2 ?

**Comment by iZaL** [comment]
Yes, Jump + Push works. would be cool to have in the one action though ..

**Comment by aksonov** [comment]
Feel free to submit PR.

**Comment by Elyx0** [comment]
Digging this, but it's really been a feature that people have asked since early days of v2. @iZaL how did you articulate the logic of jump + push ? Ho does tab1 knows he has to do the push to tab1_2 ? Is it something the switch component could handle ?

**Comment by Elyx0** [comment]
Oh okay manually with 
```javascript
Actions.callback({key:'tabbar',type:'push'});
Actions.callback({key:'tab1',type:'jump'});
```
Great work :) !

**Comment by aksonov** [comment]
Should be OK now just with one Action (v3.22.17)
