### ISSUE TITLE
react-native-router-flux updates/future?

### ISSUE THREAD

**Issue by mskarimi** [aksonov/react-native-router-flux#3501]
### Version

- react-native-router-flux v4.1.0-beta.5
- react v16.8.3
- react-native v0.59.9

@aksonov an update will happen in the future, or the package will be archived in the future?
What's you're thinking on the plan for react-native-router-flux going forward?

**Comment by CarGuo** [comment]
It hasn't been updated for four months ago . I suspect it has been abandoned ？

**Comment by mskarimi** [comment]
@aksonov are you here???

**Comment by aksonov** [comment]
@mskarimi Sorry, it was vacation time... I'm here now, but have limited availability, maintainers are actively wanted..
