### ISSUE TITLE
if go from  initial scene to previous scene, app crash after deploy on ios. (Cannot call a class as a function)

### ISSUE THREAD

**Issue by jackychanfox** [aksonov/react-native-router-flux#3503]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.6
- react v16.8.3
- react-native v0.59.8

### Expected behaviour
This is my code
```
<Scene key="Welcome" component={Welcome} hideNavBar  />
<Scene key="Login" component={Login}  hideNavBar/>
<Scene key="Register" component={Register} hideNavBar />
<Scene key="ForgotPassword" component={ForgotPassword} hideNavBar />
<Scene key="Home" component={Home} initial={isLoggedIn} />                    
...
```
After login, on Home screen 
Actions.Welcome() make a crash error (cannot call a class as a function on ios after deploy to apple store, not development mode)

it is working in development mode well. 
but when I install app from apple store. this error occurs.

my project is ejected expo project. (sdk33)

Please help me if anyone knows the solution.
Thanks
![IMG_3602](https://user-images.githubusercontent.com/25379769/60355877-1259d500-9a02-11e9-83e7-33fafedf6d6a.PNG)

**Comment by Forestchong93** [comment]
Hi, any idea to resolve this?
