### ISSUE TITLE
Custom NavBar has no ability to pass props

### ISSUE THREAD

**Issue by naji247** [aksonov/react-native-router-flux#351]
Hey guys, I really like your work on this repo.

I'm trying to pass a titleview as my navbar into my router.
```js
const scenes = Actions.create(
    <Scene key="root" navBar={TitleView}>
      <Scene key="RankScreen" initial={true} component={RankScreen} title="DogShow"/>
      <Scene key="LeaderScreen" hideNavBar={true} component={LeaderScreen} title="LeaderScreen"/>
    </Scene>
);
```

But what I need is to pass props in. 
```js
const scenes = Actions.create(
    <Scene key="root" navBar={<TitleView title="eifj"></TitleView>}>
      <Scene key="RankScreen" initial={true} component={RankScreen} title="DogShow"/>
      <Scene key="LeaderScreen" hideNavBar={true} component={LeaderScreen} title="LeaderScreen"/>
    </Scene>
);
```

Do you have any recommendations? Also, what is the specific purpose of the root scene? Is it necessary?

**Comment by aksonov** [comment]
just use 
```
navBar={Title} title="eifj"
```
title should be passed to Title automatically.

**Comment by naji247** [comment]
Using: 

```js
const scenes = Actions.create(
    <Scene key="root" >
      <Scene key="RankScreen" button="leader" navBar={TitleView} initial={true}  component={RankScreen} title="DogShow"/>
      <Scene key="LeaderScreen" hideNavBar={true} component={LeaderScreen} title="LeaderScreen"/>
    </Scene>
);
```

I still get:

<img width="330" alt="screen shot 2016-03-18 at 11 28 21 am" src="https://cloud.githubusercontent.com/assets/1920483/13888076/91d110f2-ecfc-11e5-81ee-b2b238c5b085.png">

When I want:

<img width="358" alt="screen shot 2016-03-18 at 11 29 18 am" src="https://cloud.githubusercontent.com/assets/1920483/13888093/adc2d390-ecfc-11e5-9ced-3072e02f6b64.png">

**Comment by ylquankai** [comment]
You can try to use this.props.scene.navigationState.data to get props.

**Comment by aksonov** [comment]
@naji247 I can't reproduce it. Please change Example accordingly to show the problem.

**Comment by dbsdugus00** [comment]
I think I have a same question like this.
I want to pass props to custom NavBar like
<Scene key='menu' component='menu' navBar={<Toolbar istrue={true} }/>
But It doesn't work. How can I solve it?

**Comment by dbsdugus00** [comment]
I think I have a same question like this.
I want to pass props to custom NavBar like
`<Scene key='menu' component='menu' navBar={<Toolbar istrue={true}/> }/>`
But It doesn't work. Is there any recommendations?
