### ISSUE TITLE
How to refresh/re-render previous scene after pop() the current scene.?

### ISSUE THREAD

**Issue by uplamartya** [aksonov/react-native-router-flux#3510]
# Version
Tell us which versions you are using:

- react-native-router-flux v4.?.?
- react v16.?.?
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by fanzhiri** [comment]
show which versions you are using first please 
react-native-router-flux v4.?.?
react v16.?.?
react-native v0.?.?

**Comment by uplamartya** [comment]
react-native-router-flux: v4.0.6
react-native: v0.59.9
react-native: v16.8.3

**Comment by jsina** [comment]
same issue

**Comment by jsina** [comment]
@uplamartya have you solved it?

**Comment by uplamartya** [comment]
Previously I was not using redux, so it was necessary to refresh/re-render the previous Scene on pop() of the current scene. But, later on, I achieved this with redux.
