### ISSUE TITLE
Actions.popTo not updating/passing new props

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3521]
v4.0.4

For some reason when using this code:

`                    Actions.popTo('myList', { 
                      title: item, 
                      cameFromDetails: true,
                      uri: null,
                      medical: true
                   });`

The props are not being passed back to the scene. When i use Actions.replace instead of popTo and pass the same props, it works.

What could be the problem? the docs say they work the same with the Params.

Cheers.

**Comment by nica0012** [comment]
I used jump instead of popTo and it worked just as I wanted, weird thought because I thought it was only from jumping tab to tab.

**Comment by prios-annapurna-jones** [comment]
Why is this closed? We are using 4.2.0 and PopTo with new props doesn't change the props. Just goes to the page and does not change props.

**Comment by salorsino** [comment]
> I used jump instead of popTo and it worked just as I wanted, weird thought because I thought it was only from jumping tab to tab.

Oddly worked for me too. Thanks for the suggestion
