### ISSUE TITLE
Any update for React Native 0.60.x ？

### ISSUE THREAD

**Issue by CarGuo** [aksonov/react-native-router-flux#3524]
### Version

| `react-native` | `react`         |
|----------------|-----------------
| 0.60.3         | 16.8.6 |

**Comment by rickmanelius** [comment]
This will likely become a blocking change given upcoming AndroidX and 64-bit requirements in order to deploy to Google Play starting on August 1st, 2019.

**Comment by shubhang93** [comment]
Also InteractionManager doesn't seem to be working as expected with react native 0.60.2

**Comment by belal-mazlom** [comment]
I used this library in many projects before, but seems I am forced to migrate to:
https://reactnavigation.org/
😕

**Comment by aksonov** [comment]
RNRF 4.2.x works with latest React Native. We are using RNRF in our production app
