### ISSUE TITLE
Prop `transitionConfig` no longer exists on any component; Can no longer change transition animation

### ISSUE THREAD

**Issue by nikola-kolosek** [aksonov/react-native-router-flux#3535]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.6
- react v16.8.3 
- react-native v0.59.9 

### Expected behaviour

The package should provide the user with a smooth and easy-to-use way to change the screen transitions between scenes.

### Actual behaviour

Prop `transitionConfig` no longer exists on any of the components, and right now I couldn't find a way to change the transition animation without completely migrating to `react-navigation`

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by krakz999** [comment]
```
import { StackViewStyleInterpolator } from 'react-navigation-stack';

const transitionConfig = () => ({
    screenInterpolator:
        StackViewStyleInterpolator.forFadeFromBottomAndroid,
});

<Stack key="root"
     transitionConfig={transitionConfig}
>
     {/* scenes */}
</Stack>
```

**Comment by nica0012** [comment]
@nikola-kolosek Hi, how did you manage to fix this? My transitions no longer work when upgrading to v4.3.0

**Comment by sewign** [comment]
@nikola-kolosek @nica0012 same. did you manage to fix this ?
