### ISSUE TITLE
How can I run React Native Example?

### ISSUE THREAD

**Issue by wstar89** [aksonov/react-native-router-flux#3537]
I am a software developer started React Native.
I am downloaded example in reactnativeexample.com but It isn't run.

![image](https://user-images.githubusercontent.com/54064759/63146656-44fd7280-c02e-11e9-91a7-06dfdf1eac0c.png)

The size of project that I created is 300MB, but example is 3MB.
What is it wrong?

**Comment by aksonov** [comment]
Should be solved now, please check latest master `examples/react-native` folder
