### ISSUE TITLE
ReferenceError: Can't find variable: state 

### ISSUE THREAD

**Issue by King2231** [aksonov/react-native-router-flux#3539]
The below question. I suppose it has to do something with react-native-router-flux since the issue is there only when i move from my newpassword screen to login screen.

https://stackoverflow.com/questions/57553509/referenceerror-cant-find-variable-state-in-react-native-0-60-4

Please take a look and suggest any bugs in my code or any workarounds

**Comment by aksonov** [comment]
Sorry, this error is not related to this component
