### ISSUE TITLE
renderRightButton doesn't work

### ISSUE THREAD

**Issue by alanzanattadev** [aksonov/react-native-router-flux#354]
Hi,

How am i supposed to use the prop renderRightButton on a Scene ?
I've tried with a closure : renderRightButton={() => (<Switch/>)}
And without : renderRightButton={<Switch/>}
Even with adding onRight or rightTitle (this prop overrides mine) it doesn't work, nothing appears.

I've looked source code but I don't see any mention of this.props.renderRightButton, is it normal ?
I'm using 3.x

Thank you

**Comment by aksonov** [comment]
from NavBar:
```
        if (state.renderLeftButton){
            this._renderLeftButton = state.renderLeftButton;
        }
        if (state.renderRightButton){
            this._renderRightButton = state.renderRightButton;
        }
        if (state.renderBackButton){
            this._renderBackButton = state.renderBackButton;
        }

```
Please debug and feel free to submit PR if it doesn't work properly.

**Comment by jarredwitt** [comment]
I was running into the same issue as well. Did some debugging and was able to get it working by changing up NavBar.js. Here is my complete NavBar.js. 
`/**
 * Copyright (c) 2015, Facebook, Inc.  All rights reserved.
 *
 * Facebook, Inc. ("Facebook") owns all right, title and interest, including
 * all intellectual property and other proprietary rights, in and to the React
 * Native CustomComponents software (the "Software").  Subject to your
 * compliance with these terms, you are hereby granted a non-exclusive,
 * worldwide, royalty-free copyright license to (1) use and copy the Software;
 * and (2) reproduce and distribute the Software as part of your own software
 * ("Your Software").  Facebook reserves all rights not expressly granted to
 * you in this license agreement.
 *
 * THE SOFTWARE AND DOCUMENTATION, IF ANY, ARE PROVIDED "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES (INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE) ARE DISCLAIMED.
 * IN NO EVENT SHALL FACEBOOK OR ITS AFFILIATES, OFFICERS, DIRECTORS OR
 * EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THE SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
import React, {Animated, PixelRatio, Image, StyleSheet, Text, TouchableOpacity, View, NavigationExperimental} from 'react-native';
import Actions from './Actions';
const {
    AnimatedView: NavigationAnimatedView,
    Card: NavigationCard,
    RootContainer: NavigationRootContainer,
    Header: NavigationHeader,
    } = NavigationExperimental;

export default class extends React.Component {
    componentWillMount(){
        const state = this.props.navigationState;
        this._renderRightButton = this._renderRightButton.bind(this);
        this._renderBackButton = this._renderBackButton.bind(this);
        this._renderLeftButton = this._renderLeftButton.bind(this);
        this._renderTitle = this._renderTitle.bind(this);
    }
    render() {
        const state = this.props.navigationState;
        const childrenState = this.props.navigationState.children[state.index];
        if (state.navBar || childrenState.navBar){
            const Component =  childrenState.navBar || state.navBar;
            return <Component {...this.props} {...state}/>
        }
        if (childrenState.component && childrenState.component.renderNavigationBar){
            return childrenState.component.renderNavigationBar({...this.props,...childrenState});
        }
        if (state.hideNavBar || childrenState.hideNavBar){
            return null;
        }
        return (
            <Animated.View
                style={[styles.header, state.navigationBarStyle]}>
                {state.children.map(this._renderTitle, this)}
                {this._renderBackButton()}
                {this._renderLeftButton()}
                {this._renderRightButton()}
            </Animated.View>
        );
    }

    _renderBackButton() {
        if (this.props.navigationState.index === 0) {
            return null;
        }

        const state = this.props.navigationState;
        const childState = this.props.navigationState.children[this.props.navigationState.index];

        if (childState.renderBackButton || state.renderBackButton) {
          let backButton = childState.renderBackButton || state.renderBackButton;

          return (
            <View style={styles.backButton}>
              {backButton()}
            </View>
          );
        }

        return (
            <TouchableOpacity style={[styles.backButton, this.props.navigationState.leftButtonStyle]} onPress={Actions.pop}>
                <Image source={require('./back_chevron.png')} style={[styles.backButtonImage, this.props.navigationState.barButtonIconStyle]}/>
            </TouchableOpacity>
        );
    }

    _renderRightButton() {
        const state = this.props.navigationState;
        const childState = this.props.navigationState.children[this.props.navigationState.index];

        if (childState.renderRightButton) {
          let button = childState.renderRightButton();

          return (
            <View style={styles.rightButton}>
              {button}
            </View>
          );
        }

        if (childState.onRight && childState.rightTitle){
            return (
                <TouchableOpacity style={[styles.rightButton, childState.rightButtonStyle]} onPress={childState.onRight}>
                    <Text style={[styles.barRightButtonText, childState.rightButtonTextStyle]}>{childState.rightTitle}</Text>
                </TouchableOpacity>
            );
        }
        if (state.onRight && state.rightTitle){
            return (
                <TouchableOpacity style={[styles.rightButton, state.rightButtonStyle]} onPress={state.onRight}>
                    <Text style={[styles.barRightButtonText, state.rightButtonTextStyle]}>{state.rightTitle}</Text>
                </TouchableOpacity>
            );
        }
    }

    _renderLeftButton() {
        const state = this.props.navigationState;
        const childState = this.props.navigationState.children[this.props.navigationState.index];

        if (childState.renderLeftButton) {
          let button = childState.renderLeftButton();

          return (
            <View style={styles.leftButton}>
              {button}
            </View>
          );
        }

        if (childState.onLeft && childState.leftTitle){
            return (
                <TouchableOpacity style={[styles.leftButton, childState.leftButtonStyle]} onPress={childState.onLeft}>
                    <Text style={[styles.barLeftButtonText, childState.leftButtonTextStyle]}>{childState.leftTitle}</Text>
                </TouchableOpacity>
            );
        }
        if (state.onLeft && state.leftTitle){
            return (
                <TouchableOpacity style={[styles.leftButton, state.leftButtonStyle]} onPress={state.onLeft}>
                    <Text style={[styles.barLeftButtonText, state.leftButtonTextStyle]}>{state.leftTitle}</Text>
                </TouchableOpacity>
            );
        }
    }

    _renderTitle(childState: NavigationState, index:number) {
        return (
            <Animated.Text
                key={childState.key}
                style={[
          styles.title, this.props.navigationState.titleStyle, childState.titleStyle,
          {
            opacity: this.props.position.interpolate({
              inputRange: [index - 1, index, index + 1],
              outputRange: [0, 1, 0],
            }),
            left: this.props.position.interpolate({
              inputRange: [index - 1, index + 1],
              outputRange: [200, -200],
            }),
            right: this.props.position.interpolate({
              inputRange: [index - 1, index + 1],
              outputRange: [-200, 200],
            }),
          },
        ]}>
                {this.props.getTitle ? this.props.getTitle(childState) : childState.title }
            </Animated.Text>
        );
    }

}

const styles = StyleSheet.create({
    title: {
        textAlign: 'center',
        marginTop: 10,
        fontSize: 18,
        fontWeight: '500',
        color: '#0A0A0A',
        position: 'absolute',
        top: 20,
        left: 0,
        right: 0,
    },
    header: {
        backgroundColor: '#EFEFF2',
        paddingTop: 20,
        top: 0,
        height: 64,
        right: 0,
        left: 0,
        borderBottomWidth: 0.5,
        borderBottomColor: '#828287',
        position: 'absolute',
    },
    backButton: {
        width: 50,
        height: 37,
        position: 'absolute',
        bottom: 4,
        left: 2,
        padding: 8,
    },
    rightButton: {
        width: 50,
        height: 37,
        position: 'absolute',
        bottom: 4,
        right: 2,
        padding: 8,
    },
    leftButton: {
        width: 50,
        height: 37,
        position: 'absolute',
        bottom: 4,
        left: 2,
        padding: 8,
    },
    barRightButtonText: {
        color: 'rgb(0, 122, 255)',
        textAlign:'right',
        fontSize: 17,
    },
    barLeftButtonText: {
        color: 'rgb(0, 122, 255)',
        textAlign:'left',
        fontSize: 17,
    },
    backButtonImage: {
        width: 13,
        height: 21,
    },
});
`
I'm still cleaning it up, but if it works for you as well I'll get a PR ready and submit.

**Comment by aksonov** [comment]
@jarredwitt No need to post sources here (it is for issues not for source code), just submit PR and i will review.

**Comment by jarredwitt** [comment]
Sounds good. I'll get it cleaned up and do some more testing then submit.

**Comment by aksonov** [comment]
Okey, i've found that props were not passed for nested scenes, please check 3.1.1

**Comment by jarredwitt** [comment]
It's still not working for me in 3.1.3. When I make the NavBar.js changes to what I posted earlier it begins working correctly. I'll do some more debugging.

**Comment by linyize** [comment]
renderTitle also don't work for me.

**Comment by aksonov** [comment]
@linyize Sorry, renderTitle is not supported (because of animation of titles), i've removed it from docs.

**Comment by aksonov** [comment]
@jarredwitt I've just added renderRightButton to Example for tab #5, i see it without any problem

**Comment by alanzanattadev** [comment]
I've tried with the same component and renderTo attribut of your example, copied pasted, but it doesn't work on 3.1.5, nothing is displayed

**Comment by aksonov** [comment]
Example, tab#5 contains custom right button (just unclickable text)

**Comment by SudoPlz** [comment]
I've got trouble seeing the right button in `3.2.2`. I use the code from your example but nothing appears. I'll keep on looking in case I'm missing something.

**Comment by aksonov** [comment]
Are you joking? Have you ever read answer above? tab n5 contains right button from Example project.

**Comment by SudoPlz** [comment]
Yes I understand that, I'm using that exact code but I don't see any Right button on my nav bar.. Am I missing something?

**Comment by SudoPlz** [comment]
Ok I kept researching and I found out that the button WAS indeed render but it was rendered BEHIND the nav bar.. Like so: 
![screen shot 2016-03-25 at 22 04 11](https://cloud.githubusercontent.com/assets/3070948/14052817/a0559fba-f2d5-11e5-9eb7-e77ccb0dc362.png)

Thats my code: 

      class ARightBtn extends React.Component {
          render(){
              return <Text style={{
                width: 80,
                flex:1,
                position: 'absolute',
                height: 120,
                width: 200,
                top: 50,
                right:0,
                padding: 8,
                backgroundColor: 'red',
                color: '#000000'
            }}>RightBtnTest</Text>
          }
      }
and then I use it like so:

    <Scene key="EmailSignIn" title="Sign In" type="push" hideNavBar={false} titleStyle={{color:Colors.mainTextColor}} renderRightButton={()=><ARightBtn/>} initial={true} >
        <Scene key="EmailSignIn1" component={EmailSignIn} title="Sign In" navigationBarStyle={{backgroundColor:Colors.primaryColor}} renderRightButton={()=><ARightBtn/>}  />
        <Scene key="EmailSignIn2" component={Onboarding} title="Sign In"/>
    </Scene>
