### ISSUE TITLE
there is a way  onPress drawer blank to hide?

### ISSUE THREAD

**Issue by jiangmingwen** [aksonov/react-native-router-flux#3549]
some packages version:
  "react": "16.8.6",
  "react-native": "0.60.3",
  "react-native-router-flux": "4.1.0"
  "react-navigation": "3.1.0"

code :
import {  Drawer } from 'react-native-router-flux';

  <Drawer key='drawer'
         hideNavBar={true}
         contentComponent={DrawerComponent}
         drawerWidth={ 200 }
         drawerPosition={'left'} />  

question:
  there is a way to hide drawer  when the drawer is displayed, click on the blank area on the right side of the drawer?

**Comment by aksonov** [comment]
You can do anything - just add this logic into `DrawerComponent`
