### ISSUE TITLE
What does `clone` do?

### ISSUE THREAD

**Issue by jqtruong** [aksonov/react-native-router-flux#3552]
### Version

- react-native-router-flux v4.0.6
- react v16.8.6
- react-native v0.60.5

I'm looking at the Example as instructed in the API docs, but it is not very clear. Maybe a better question is: when would i use the `clone` property?

**Comment by illuminist** [comment]
It's the same thing as React.cloneElement
https://stackoverflow.com/questions/37521798/when-should-i-be-using-react-cloneelement-vs-this-props-children
