### ISSUE TITLE
Tabs will go up when I open keyboard. Is there a way on how to fix this? Please help. 

### ISSUE THREAD

**Issue by prospkarl** [aksonov/react-native-router-flux#3554]
## Latest Version:: ^4.0.6

**Here is the Issue**

![issue](https://user-images.githubusercontent.com/54798409/64752999-35514b00-d554-11e9-88ca-c4960242bb30.PNG)

**Comment by aksonov** [comment]
Please check latest `4.2.0-beta.1`. If it doesn't help try pure `react-navigation` tabbar and report issue if it is there..
