### ISSUE TITLE
Unkown memery leak

### ISSUE THREAD

**Issue by wv1124** [aksonov/react-native-router-flux#3555]
### Version
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-router-flux": "^4.0.6"

Demo is  here : [https://github.com/wv1124/react-native-router-flux-test]( https://github.com/wv1124/react-native-router-flux-test)

**Comment by aksonov** [comment]
Please try react-navigation module itself to check this issue. This component is just wrapper around react-navigation
