### ISSUE TITLE
pass Router props to all Scenes

### ISSUE THREAD

**Issue by rgovindji** [aksonov/react-native-router-flux#356]
I am using Relay with my project but when I try render a scene that contains my News Feed I get an undefined error saying the property hasn't been set. I define the Scene's and then I wrap the Router in a relay container which has a fragment for the NewsFeed page. If I don't use the Navigator then the newsfeed renders fine. Here's what I am trying below:

```
const scenes = Actions.create(
    <Scene key="modal" component={Modal} >
      <Scene key="root" hideNavBar={true}>
        <Scene key="NewsFeed" component={NewsFeed} title="NewsFeed" />
        <Scene key="Login" component={Login} title="Login" />
      </Scene>
      <Scene key="error" component={Error}/>
    </Scene>
);

export default class SampleApp extends Component {
  render() {
    return (
       <Router scenes={scenes}/>
    );
  }
}

export default Relay.createContainer(SampleApp, {
  fragments: {
    viewer: variables => Relay.QL`
      fragment on Viewer {
        id
        ${NewsFeed.getFragment('feed')}
      }
    `,
  },
});
```

**Comment by aksonov** [comment]
Any screenshot? Looks like it is about Relay but not about this component 

Pavel.

**Comment by rgovindji** [comment]
I managed to get it to work by doing adding the "viewer" property manually to the NewsFeed scene.

 ```
render() {
    **scenes.NewsFeed.viewer = this.props.viewer;**
    return (
       <Router scenes={scenes} props={this.props}/>
    );
  }
```
Is this the proper way to do this? 

I also have an issue now with the NewsFeed scrolling performance is bad. It is a ListView and when I scroll it will lose a lot of frames. This didn't happen when I was rendering the NewsFeed as a standalone component.

**Comment by aksonov** [comment]
It is definitely not about this component. The current component is just wrapper around new nav api

Pavel.

**Comment by rgovindji** [comment]
Okay so it should work without the additional line? I must have done something wrong. Thanks

**Comment by aksonov** [comment]
Yes, if viewer is required property that set by Relay, you have to pass it manually because Router doesn’t know about it.
Maybe the component could pass all their props to all children automatically to solve this (except scenes and probably style), feel free to submit PR or i could do it when i have time…

Maybe you could rename this ticket accordingly (like "pass Router props to all Scenes") To pass style we could use sceneStyle, for example, so you could set ‘default’ scene style this way.

**Comment by rgovindji** [comment]
Okay I have re-opened the ticket and renamed it. I like the idea that would be very helpful!

**Comment by aksonov** [comment]
Should be done for 3.1.0

**Comment by rgovindji** [comment]
Thanks! I will give it a shot now :)

**Comment by rgovindji** [comment]
@aksonov How do I get switching between tabs to work. The initial tab will load correctly but if I switch to another tab and switch back I get an error saying "viewer" is undefined.

**Comment by sibeliusseraphini** [comment]
Hey @rgovindji could u share an example repo with ur solution please?

**Comment by rgovindji** [comment]
I'm still using 3.22 so I don't know if there is an issue in the latest version but in order to pass all props to all scenes I did this.

<Router {...this.props}  >
