### ISSUE TITLE
GetState 

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#357]
How do i get the state of the navigation like when it's pushed or poped? Need to implement Additional functions. Instead of just printing the log to the console. Sample Implementation would be much appreciated.

**Comment by aksonov** [comment]
Pass your function as reducer as reducer param. If may call 'default' reducer from your reducer (check how to create it from Router sources)

**Comment by ajoshdee** [comment]
How can create a switch case for the action.type?

**Comment by ajoshdee** [comment]
I just need a listener that will return the state of the navigator. Cause i needed to do additional methods using a switch case depending on the state of the navigator.

**Comment by ajoshdee** [comment]
I want to handle callbacks instead of just receiving `'ACTION:', { key: 'result', type: 'push' }` in the console

**Comment by aksonov** [comment]
Have you tried to pass own reducer as i said?

**Comment by ajoshdee** [comment]
How do you pass reducer? I did Reducer({this.State.getInitialState(), scene})
But i always get cannot evaluate undefined object error

**Comment by ajoshdee** [comment]
can you just show me an example of how to implement it in my view?

**Comment by aksonov** [comment]
what means this.State?? State is module of the component. Sorry, i'm not tutor and it is not resource to support javascript beginners.

**Comment by ajoshdee** [comment]
Oh sorry, I used State.getInitialState()

**Comment by aksonov** [comment]
Sorry, syntax is still wrong, please study javascript, check sources, i don't see any problem with it. It is not the problem of the component.

**Comment by brettpappas** [comment]
@aksonov I think you would have more people willing to contribute if you included a little commenting in your code. I looked at the Router sources and a few others (State, Reducer) and am hesitant to make improvements to it when I don't know what you expect the functions to do. Code comments also help when people don't find what they are looking for in the docs.

**Comment by aksonov** [comment]
I've put comments where it is necessary. Please check React Native sources do you see any comments there? You may also compare v2 and v3, i've fully rewritten v3 to make it as simple as possible.

**Comment by aksonov** [comment]
@ajoshdee Okey, i've added custom reducer to example, hope it will help.

**Comment by ajoshdee** [comment]
Thank you very much for the example
