### ISSUE TITLE
Error: Requiring unknown module '789' 

### ISSUE THREAD

**Issue by aowuR** [aksonov/react-native-router-flux#3590]
Error: Requiring unknown module "789". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.

yarn and npm isntall has tried; What's the reason?

**Comment by vedant-pandey** [comment]
You may have installed the dependencies while running the scripts. 

- Close the currently running expo or react-native command, and restart. 
- In case that also doesn't work, do `npm cache clean --force`
- At this point your app should start, if that also doesn't work remove the node_modules and do `yarn install` or `npm install`

**Comment by aowuR** [comment]
remove the node_modules and do yarn install or npm install is ok  !!  Thanks!!!!
