### ISSUE TITLE
Actions. refresh(); look like change parent Scene props , is not current scene

### ISSUE THREAD

**Issue by xiaoniuge** [aksonov/react-native-router-flux#3591]
"react-native-router-flux": "^4.0.6"

**Comment by DanielLe232** [comment]
Could you provide me a some code?

**Comment by xiaoniuge** [comment]
> Could you provide me a some code?

PageOne: 
import React, {Component} from 'react';
import {View, TouchableOpacity, Text} from 'react-native';
import {Actions} from 'react-native-router-flux';

class PageOne extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {}

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.push('page_two')}>
          <Text style={{color: 'blue'}}>PageOne next</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default PageOne;

PageTwo: 
import React, {Component} from 'react';
import {View, TouchableOpacity, Text} from 'react-native';
import {Actions} from 'react-native-router-flux';

class PageTwo extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    Actions.refresh({title: 'THREE'});
    alert('page_two:  ' + Actions.currentScene); // Actions.currentScene is page_one
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.pop()}>
          <Text style={{color: 'blue'}}>PageTwo pre</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default PageTwo;

router: 
import {Router, Scene, Actions} from 'react-native-router-flux';
import React from 'react';
import PageOne from './src/view/PageOne';
import PageTwo from './src/view/PageTwo';

class AppRouter extends React.Component {
  constructor(props) {
    super(props);
    this.props = props;
  }

  render() {
    return (
      <Router>
        <Scene>
          <Scene
            key="page_one"
            component={PageOne}
            title="ONE"
            initial={true}
          />
          <Scene key="page_two" component={PageTwo} title="TWO" />
        </Scene>
      </Router>
    );
  }
}

export default AppRouter;

-------

On the page_two, I output the current scene information, which should be page_two, but the output is page_one. Actions.refresh ({Title: 'the'}) is used in the componentdidmount method of the page_two, which has no effect. When the page_one is returned and counted into the page_one again, the title changes, but the page_one is changed.

**Comment by xiaoniuge** [comment]
> Could you provide me a some code?

import React, {Component} from 'react';
import {View, TouchableOpacity, Text} from 'react-native';
import {Actions} from 'react-native-router-flux';

class PageOne extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {}

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.push('page_two')}>
          <Text style={{color: 'blue'}}>PageOne next</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default PageOne;

---

import React, {Component} from 'react';
import {View, TouchableOpacity, Text} from 'react-native';
import {Actions} from 'react-native-router-flux';

class PageTwo extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    Actions.refresh({title: 'THREE'});
    alert('page_two:  ' + Actions.currentScene); // Actions.currentScene is page_one
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.pop()}>
          <Text style={{color: 'blue'}}>PageTwo pre</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default PageTwo;

----
import {Router, Scene, Actions} from 'react-native-router-flux';
import React from 'react';
import PageOne from './src/view/PageOne';
import PageTwo from './src/view/PageTwo';

class AppRouter extends React.Component {
  constructor(props) {
    super(props);
    this.props = props;
  }

  render() {
    return (
      <Router>
        <Scene>
          <Scene
            key="page_one"
            component={PageOne}
            title="ONE"
            initial={true}
          />
          <Scene key="page_two" component={PageTwo} title="TWO" />
        </Scene>
      </Router>
    );
  }
}

export default AppRouter;

----

On the page_two, I output the current scene information, which should be page_two, but the output is page_one. Actions.refresh ({Title: 'the'}) is used in the componentdidmount method of the page_two, which has no effect. When the page_one is returned and counted into the page_one again, the title changes, but the page_one is changed.

**Comment by xiaoniuge** [comment]
> Could you provide me a some code?

router: 

    <Router>
        <Scene>
          <Scene key="page_one" component={PageOne} title="ONE" initial={true} />
          <Scene key="page_two" component={PageTwo} title="TWO" />
        </Scene>
      </Router>

page_one:

    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.push('page_two')}>
          <Text style={{color: 'blue'}}>PageOne next</Text>
        </TouchableOpacity>
      </View>

page_two:

      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={() => Actions.pop()}>
          <Text style={{color: 'blue'}}>PageTwo pre</Text>
        </TouchableOpacity>
      </View>

 componentDidMount() {
    Actions.refresh({title: 'THREE'});
    alert('page_two:  ' + Actions.currentScene); // Actions.currentScene is page_one
  }

-------

On the page_two, I output the current scene information, which should be page_two, but the output is page_one. Actions.refresh ({Title: 'the'}) is used in the componentdidmount method of the page_two, which has no effect. When the page_one is returned and counted into the page_one again, the title changes, but the page_one is changed.

**Comment by DanielLe232** [comment]
@xiaoniuge I have tested your code. I realize they have delay time when change from scene to another scene (They still focus previous scene in a short time). The same with my issue when i work on Android TV.
My code:
```
componentDidMount() {
        this.props.navigation.addListener('didFocus', () => {
            alert(Actions.currentScene)
        });
        this.props.navigation.addListener('didBlur', () => {
            alert(Actions.currentScene)
        });
        // setTimeout(() => {
        //     Actions.refresh({ title: 'THREE' });
        //     alert('page_two: ' + Actions.currentScene);
        // }, 1);
    }
```

**Comment by xiaoniuge** [comment]
> this.props.navigation.addListener('didFocus', () => {
>             alert(Actions.currentScene)
>         });
>         this.props.navigation.addListener('didBlur', () => {
>             alert(Actions.currentScene)
>         });

Thank you very much! It works！

**Comment by xiaoniuge** [comment]
Thank you very much! It works！
