### ISSUE TITLE
swipeEnabled not working on last beta ?

### ISSUE THREAD

**Issue by psppro26** [aksonov/react-native-router-flux#3598]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.2.0-beta.2
- react v16.9.0
- react-native v0.61.4

### Expected behaviour
SwipeEnabled was working perfectly with version 4.0.6 but not working on last beta v4.2.0-beta.2 ? All is working except the swipe ?

### Actual behaviour
     <Router>

        <Tabs
          key="welcome"
          tabs={true}
          legacy={true}
          swipeEnabled={true}
          tabBarComponent={navigation => <BarWelcome navigation={navigation} />}
          // tabBarStyle={{ backgroundColor: 'transparent', borderTopWidth: 0, justifyContent: 'center' }}
          type="replace"
          showLabel={false}
          tabBarPosition='bottom'

        >
          <Stack key="welcome">
            <Scene
              hideNavBar
              initial={true}
              key="updateProfile"
              title="updateProfile"
              component={WelcomeContainer}

            />
          </Stack>
          <Stack key="login">

            <Modal hideNavBar>

              <Scene
                hideNavBar
                initial={true}
                key="login"
                title="LOGIN"
                // {...DefaultProps.navbarProps}
                component={LoginContainer}
                Layout={LoginComponent}

              />

              <Scene
                back={true}
                hideNavBar={false}
                navBar={() => <NavModal />}
                key="signUp"
                title="SIGN UP"
                {...DefaultProps.navbarProps}
                component={SignUpContainer}
                Layout={SignUpComponent}
              />

              <Scene
                back
                hideNavBar={false}
                navBar={() => <NavModal />}
                key="forgotPassword"
                title="FORGOT PASSWORD"
                {...DefaultProps.navbarProps}
                component={ForgotPasswordContainer}
                Layout={ForgotPasswordComponent}
              />
              <Scene
                back
                key="updateProfile"
                title="UPDATE PROFILE"
                {...DefaultProps.navbarProps}
                component={UpdateProfileContainer}
                Layout={UpdateProfileComponent}
              />
            </Modal>
          </Stack>

        </Tabs>

      </Router >

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
Yes, swipe doesn't work due deprecated modules, PR is welcome to enable it. Everything else should work

**Comment by Bang9** [comment]
use `gestureEnabled`

**Comment by Bang9** [comment]
use `gesturesEnabled={false}`
