### ISSUE TITLE
replace does not call componentWillUnmount for replaced component

### ISSUE THREAD

**Issue by lrettig** [aksonov/react-native-router-flux#36]
Hello

I'm using `type="replace"` for one of my routes. I noticed that, after I follow this route several times, I get the following warning:

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.` ([Full stack trace](http://i.imgur.com/bB7lHFw.png))

I tested some more and it appears that this is happening because, while I remove the change listener in `componentWillUnmount`, this method is not called on a component that's being replaced.

How can I handle this, and know when my component is going away due to `replace`?

Thanks!

**Comment by Mokto** [comment]
+1 :)

**Comment by aksonov** [comment]
The component just calls navigator call. I suppose RN  navigator should call it, right?

Pavel.

**Comment by lrettig** [comment]
Oddly it works fine for Actions.pop on the same component

**Comment by aksonov** [comment]
Pretty weird...I'm not sure where is the reason of such behavior

**Comment by aksonov** [comment]
Closing it for now. Looks like it is problem of navigator, please check direct call of navigator.replace
