### ISSUE TITLE
nhandled JS Exception: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by saphir100** [aksonov/react-native-router-flux#3600]
### Version
Tell us which versions you are using:

- "react-native-router-flux": "^4.0.6"
- "react": "16.9.0"
- "react-native": "0.61.5"

### Expected behaviour

load D1.js page.

### Actual behaviour
Unhandled JS Exception: SyntaxError: Invalid or unexpected token

This error is located at:
    in Router (at DrawerTest1.js:80)
    in DrawerMenu (at App.js:6)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

### Reproducible Demo
DrawerTest1.js contain below code.
``
<Router> #this line 80 
        <Lightbox>
          <Scene key="root" hideNavBar>
               <Scene key="D1" component={Shopping_Center} init />
                <Scene key="D2" component={Contact_Us} />
          </Scene>
         <Scene key="loginorregisterlightbox" component={LoginOrRegister} />
        </Lightbox>
</Router>
``

![error](https://user-images.githubusercontent.com/7803395/71446311-22473d00-2737-11ea-854e-503a949c2b4e.png)

**Comment by aksonov** [comment]
Please check with latest version and let me know results
