### ISSUE TITLE
this.props.sceneStyle of Example can't passed

### ISSUE THREAD

**Issue by xushuwei202** [aksonov/react-native-router-flux#361]
I test Example about 3.1.0,  pass Router props to all Scenes don't work.

export default class Example extends React.Component {
    render() {
        return <Router scenes={scenes} sceneStyle={{backgroundColor:'#F7F7F7'}}/>;
    }
}

**Comment by aksonov** [comment]
What is your empty example about? I've added passing of style to Example project and Launch page gets it normally.

**Comment by xushuwei202** [comment]
Sorry, it's my bad.  after update,  i forget to npm install package
