### ISSUE TITLE
How can I run React Native Example [Jan 2020]?

### ISSUE THREAD

**Issue by NorfeldtAbtion** [aksonov/react-native-router-flux#3617]
Having a lot of trouble trying out the example listed in this repo on my iOS simulator.

Steps I did:

1. Cloned the project.
2. Navigated to `.../react-native-router-flux/examples/react-native/ios`
3. `pod install`
4. `cd ..`
5. `yarn ios`
6. BAMP! Hit another wall (first was the `pod install` I was missing)

```
ooking for JS files in
   /Users/norfeldt/Desktop/react-native-router-flux/examples/react-native 

Loading dependency graph...events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat '/Users/norfeldt/Desktop/react-native-router-flux/examples/react-native/ios/build/Example/ModuleCache.noindex/1JBYRE32SJYDT/CoreText-3W9A51BO0R6G.pcm.lock'
Emitted 'error' event at:
    at Walker.emit (events.js:200:13)
    at /Users/norfeldt/Desktop/react-native-router-flux/examples/react-native/node_modules/walker/lib/walker.js:52:12
    at FSReqCallback.oncomplete (fs.js:165:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/norfeldt/Desktop/react-native-router-flux/examples/react-native/ios/build/Example/ModuleCache.noindex/1JBYRE32SJYDT/CoreText-3W9A51BO0R6G.pcm.lock'
}
Process terminated. Press <enter> to close the window
```

![Simulator Screen Shot - iPhone 11 - 2020-01-27 at 11 06 47](https://user-images.githubusercontent.com/53769763/73165939-216a4800-40f5-11ea-96b8-dc4e78b6eb8d.png)

**Comment by aksonov** [comment]
Just checked latest master. Works well, with some warning.
![Simulator Screen Shot - iPhone 8 - 2020-02-15 at 12 51 35](https://user-images.githubusercontent.com/1321329/74585794-eec7b700-4ff1-11ea-8a9a-69af9a4a25b2.png)
