### ISSUE TITLE
How to show passed props in "<Scene/>" "title" attribute in RNRF v4.0.6?

### ISSUE THREAD

**Issue by haratmalli** [aksonov/react-native-router-flux#3619]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.?.?
- react v16.?.?
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
It will be just usual component props. Like `this.props.title` for `title`

**Comment by haratmalli** [comment]
> It will be just usual component props. Like `this.props.title` for `title`

i just want to receive the passed props like Actions.key({myProp: 'exampleValue'}), in <Scene title={this.props.myProp}/> but unable to do that any suggestion or right trick to do that?

**Comment by aksonov** [comment]
Just check example project
