### ISSUE TITLE
Props should be defined for stack

### ISSUE THREAD

**Issue by megazoid84** [aksonov/react-native-router-flux#362]
Hi. Thanks for your work. I have a small trouble shortly described in subject. When I add

```
import Home from './Home'

const scenes = Actions.create(
  <Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar={true}>
      <Scene key="home" component={Home} title="Replace" type="replace"/>
    </Scene>
  </Scene>
);
```

Inserting source code above give me the next error
![Error screen](https://dl.dropboxusercontent.com/u/63830953/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202016-03-21%2019.21.17.png)

What did I do wrong?

**Comment by Froelund** [comment]
I have the same issue:
- react-native-router-flux: 3.1.3
- react-native: 0.22.2

**Comment by Froelund** [comment]
It looks like that the input for Router -> handleProps has changed.
The first element of props.children is an array. Previously I believe those were React components.

**Comment by Froelund** [comment]
In my case it was because I still used Route instead of Scenes.
https://github.com/aksonov/react-native-router-flux#important-breaking-changes-comparing-with-2x-version

**Comment by megazoid84** [comment]
@Froelund can you describe your case in details? What did you do wrong?

**Comment by timzaak** [comment]
Do you  have  write  '<Router scenes={scenes} />' ?

**Comment by megazoid84** [comment]
@timzaak yes, of course
```
import Home from './Home'

const scenes = Actions.create(
  <Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar={true}>
      <Scene key="home" component={Home} title="Replace" type="replace"/>
    </Scene>
  </Scene>
);

class App extends React.Component {
    render() {
        return <Router scenes={scenes} sceneStyle={{backgroundColor:'#F7F7F7'}}/>;
    }
}
```

This code generate the error given above.

**Comment by aksonov** [comment]
Where are Actions, Scene imports?

Pavel.

**Comment by megazoid84** [comment]
@aksonov it's a full source code of App.js that gives the error:

```
import React, { Component, PropTypes } from 'react-native'
import {Scene, Router, Switch, TabBar, Modal, Schema, Actions} from 'react-native-router-flux'
import Home from './Home'

const {
  Platform,
  StyleSheet,
  Text,
  View,
} = React

const scenes = Actions.create(
  <Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar={true}>
      <Scene key="home" component={Home} title="Replace" type="replace"/>
    </Scene>
  </Scene>
);

class App extends React.Component {
    render() {
        return <Router scenes={scenes} sceneStyle={{backgroundColor:'#F7F7F7'}}/>;
    }
}
export default App
```

And source code of Home.js

```
import React from 'react-native'
const {View, Text, StyleSheet} = React;
const Button = require('react-native-button');
const Actions = require('react-native-router-flux').Actions;

class Home extends React.Component {
    render(){
        return (
            <View style={styles.container}>
                <Text>Replace screen</Text>
                <Button onPress={Actions.pop}>Back</Button>
            </View>
        );
    }
}
module.exports = Home;
```

**Comment by aksonov** [comment]
Sorry, i can't reproduce and see Launch screen normally (after fixing missed styles where is not declared in your example). Try to add console.log(Router, Scene), something wrong with your dependencies.

**Comment by KBLNY** [comment]
For me, I didn't replace `name` property by `key` in `the variable I used in my `<Scene />` like :
```
var myRoute = {
   key: 'myRoute',
   component: MyComponent,
   title: 'My Route'
};

<Scene key={myRoute.name} title={myRoute.title} component={myRoute.component} />
```

**Comment by shivangbtech** [comment]
getting same error :
'props should be defined for stack'
while using sample:
https://github.com/efkan/rndrawer-implemented-rnrouter

**Comment by aksonov** [comment]
@shivangbtech Always write your version of RNRF. i guess that example depends from v2 version.

**Comment by shivangbtech** [comment]
I recently install :

react-native-router-flux@3.22.1 ../node_modules/react-native-router-flux
├── react-native-tabs@1.0.5
└── assert@1.3.0 (util@0.10.3)

**Comment by aksonov** [comment]
That is why you have got the error.... Are you sure that example could use this version? author said that it depends from v2.

**Comment by shivangbtech** [comment]
So how can I solve the problem, I need to develop same functionality. I have tried many solutions. One more example I am using having problem:
http://stackoverflow.com/questions/36693943/unable-to-use-drawer-method-opendrawer-in-component-react-native-android

**Comment by aksonov** [comment]
Why you can't check Example project from RN 3.22.1 ? It has Drawer for tab bar..

**Comment by aksonov** [comment]
Also this error (props should be defined for stack) could happen if you pass several scenes, without Root one to Router. Anyway, latest 3.22.5 wraps such scenes with Root one automatically now
