### ISSUE TITLE
Module `react-native-screens` does not exist in the Haste module map

### ISSUE THREAD

**Issue by duongduckien** [aksonov/react-native-router-flux#3621]
<img width="375" alt="Screen Shot 2020-02-12 at 02 29 39" src="https://user-images.githubusercontent.com/22634319/74271885-3d4e2a80-4d40-11ea-950e-1b0ddb206c0a.png">

The package.json file
    "@expo/vector-icons": "^9.0.0",
    "@types/react-native-fbsdk": "^0.6.2",
    "@types/react-native-i18n": "^2.0.0",
    "@types/react-native-loading-spinner-overlay": "^0.5.1",
    "@types/react-native-safari-view": "^2.0.4",
    "@types/react-native-vector-icons": "^4.6.4",
    "@types/react-navigation": "^3.0.1",
    "@types/react-redux": "^6.0.12",
    "@types/uuid": "^3.4.4",
    "axios": "^0.18.0",
    "babel-core": "^7.0.0-bridge",
    "native-base": "^2.12.1",
    "query-string": "^6.8.1",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-config": "^0.11.7",
    "react-native-drawer": "^2.5.1",
    "react-native-elements": "^0.19.1",
    "react-native-fbsdk": "^0.8.0",
    "react-native-flash-message": "^0.1.10",
    "react-native-google-signin": "^1.0.2",
    "react-native-i18n": "^2.0.15",
    "react-native-linkedin": "^1.3.1",
    "react-native-linkedin-signin": "^0.0.2",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-safari-view": "^2.1.0",
    "react-native-vector-icons": "^6.2.0",
    "react-native-webview": "^5.8.1",
    "react-navigation": "^3.0.9",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-saga": "^0.16.2",
    "rn-linkedin-login": "^1.0.4",
    "uuid": "^3.3.2"

Warning for installing the node_module:
warning "react-native-router-flux > react-navigation-drawer@2.3.4" has unmet peer dependency "react-native-gesture-handler@^1.0.12".
warning "react-native-router-flux > react-navigation-drawer@2.3.4" has unmet peer dependency "react-native-reanimated@^1.0.0".
warning "react-native-router-flux > react-navigation-drawer@2.3.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-native-router-flux > react-navigation-stack@1.10.3" has unmet peer dependency "react-native-gesture-handler@^1.0.0".
warning "react-native-router-flux > react-navigation-stack@1.10.3" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-native-router-flux > react-navigation-tabs@2.7.0" has unmet peer dependency "react-native-gesture-handler@^1.0.0".
warning "react-native-router-flux > react-navigation-tabs@2.7.0" has unmet peer dependency "react-native-reanimated@^1.0.0-alpha".
warning "react-native-router-flux > react-navigation-tabs@2.7.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-native-router-flux > react-navigation-tabs > react-native-tab-view@2.13.0" has unmet peer dependency "react-native-gesture-handler@*".
warning "react-native-router-flux > react-navigation-tabs > react-native-tab-view@2.13.0" has unmet peer dependency "react-native-reanimated@*".
warning "react-navigation > react-navigation-drawer@1.4.0" has unmet peer dependency "react-native-gesture-handler@^1.0.12".
warning "react-navigation > react-navigation-drawer@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.5.3" has unmet peer dependency "react-native-gesture-handler@^1.0.0".
warning "react-navigation > react-navigation-stack@1.5.3" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.2.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".

Can you help me?

**Comment by alittletf** [comment]
You figure this out?

**Comment by salgadohp** [comment]
Hey, I'm having the same problem here, tried every thing and nothing work, please some help me.

**Comment by vovkind** [comment]
+

**Comment by jessanKhan** [comment]
> Hey, I'm having the same problem here, tried every thing and nothing work, please some help me.

I am also having same problem. I am desperately searching for the solution.

**Comment by aksonov** [comment]
@salgadohp and others Check @alittletf answer. You should install them manually, as described in docs for react-navigation

**Comment by zw-zhuangwei** [comment]
固定版本  4.0.6  就没问题了
