### ISSUE TITLE
Very serious bug

### ISSUE THREAD

**Issue by livelyPeng** [aksonov/react-native-router-flux#3628]
After installation, an error is reported. Error: binding failed: error: unable to resolve module ` react native screens ` from ` node \ u modules \ react navigation stack \ lib \ module \ views \ stackview \ stackviewcard. JS `: react native screens could not be found within the project,

After the "react native screens" is installed, the simulator will flash out and cannot run

**Comment by hectorsuarezm** [comment]
Had the same issue, because I didn't fully followed the instructions on [React Navigation](https://reactnavigation.org/docs/en/getting-started.html). 
You need to make sure you follow all the steps within React Navigation, not only the 

> npm install @react-navigation/native

There are also additional lines you need to add for Android

**Comment by shiroze** [comment]
Follow React Navigation docs [Here](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project)

> if you using react < 0.59 run react-native link
