### ISSUE TITLE
Issue with assert in Actions.js

### ISSUE THREAD

**Issue by thessem** [aksonov/react-native-router-flux#363]
Currently my program will not load due to line 53 in `Actions.js`
```javascript
assert(key, "unique key should be defined " + JSON.stringify(root));
```
Due to `Unhandled JS Exception: Converting circular structure to JSON`

Removing the assert gives me expected behaviour (everything works fine), I was wondering if there was a different way to log this without relying on `JSON.stringify()`, or is my problem indicative of a deeper issue?

Thanks for the great library, btw!

**Comment by aksonov** [comment]
You must define key for each Actions.
