### ISSUE TITLE
props not passed when switching tabs

### ISSUE THREAD

**Issue by rgovindji** [aksonov/react-native-router-flux#364]
When load the initial tab the "viewer" prop is populated correctly but if I switch to another tab I get a "viewer is undefined" error.

```
const scenes = Actions.create(
<Scene key="main">
        <Scene key="tabbar" hideTabBar={false}  tabs={true}  >
          <Scene key="Profile" component={ProfilePage} initial={true} icon={TabIcon} iconLabel="ios-paper" title="Profile" />
          <Scene key="NewsFeed" component={NewsFeedPage} icon={TabIcon} iconLabel="ios-home" title="News Feed" />
        </Scene>
    </Scene>
);

export default class SampleApp extends Component {
  render() {
    return (
      <Router scenes={scenes} {...this.props} sceneStyle={styles.pageViewStyle} />
    );
  }
}

export default Relay.createContainer(SampleApp, {
  fragments: {
    viewer: variables => Relay.QL`
      fragment on Viewer {
        id
        ${NewsFeedPage.getFragment('viewer')}
        ${ProfilePage.getFragment('viewer')}
      }
    `,
  },
});
```

**Comment by aksonov** [comment]
Please check 3.1.4

**Comment by rgovindji** [comment]
@aksonov I am getting a syntax error saying unexpected character react-native-router-flux/src/back_chevron.png
<img width="371" alt="screen shot 2016-03-22 at 9 02 06 am" src="https://cloud.githubusercontent.com/assets/251495/13952491/05b502c2-f00d-11e5-9d5e-758420b9caa9.png">

**Comment by aksonov** [comment]
I can't reproduce it

**Comment by rgovindji** [comment]
Thank you this fix worked :)

**Comment by RTakes** [comment]
@rgovindji 
I'm repeatedly and randomly having this same issue.  I can't consistently reproduce it, and cleaning and rebuilding is no longer fixing the issue.  Today doing a git commit triggered the error.

Any suggestions?

![image](https://cloud.githubusercontent.com/assets/1253332/14393182/4dac20d6-fd7a-11e5-8d86-a84ddab06f9b.png)
