### ISSUE TITLE
How to refresh the tabs while switching? 

### ISSUE THREAD

**Issue by prateekchachra** [aksonov/react-native-router-flux#3648]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.2.0
- react v16.9.0
- react-native v0.61.5

I'd like to refresh the tabs when I switch them. Is there a property like 'isFocused' that I can use to refresh the current tab? I want to all the 'Actions.refresh()' action when the user switches the tab, tried that in router.js but it didn't work.

**Comment by shiroze** [comment]
Try this on other Scene

```
  componentWillMount() {
    Actions.refresh({ key: 'your_tabs_key' });
  }
```

you can try use set timeout too.
