### ISSUE TITLE
Set testID on default tabs

### ISSUE THREAD

**Issue by lucasroca** [aksonov/react-native-router-flux#3649]
Hi, I'm trying to set a testID on the default tab bar touchables, but I can't seem to find the way. I'm writing e2e tests with Detox and I'm trying to trigger a click on each tab icon. Is this possible at all? Should I instead build a customer tab bar?

----
### Version
Tell us which versions you are using:

- react-native-router-flux v4.2.0
- react v16.9.0
- react-native v0.61.5

**Comment by aksonov** [comment]
I think custom tab bar should be used

**Comment by yestay90** [comment]
@aksonov can you provide example of how to toggle drawer, and switch between tab bar using detox?

**Comment by maxlxq** [comment]
+1
