### ISSUE TITLE
how to get ios like screen transition in android in using react-native-router-flux:4.2.0

### ISSUE THREAD

**Issue by liuzhen88** [aksonov/react-native-router-flux#3650]
`###` Version
- react-native-router-flux v4.2.0
- react v16.9.0
- react-native v0.61.5
- "react-navigation": "^4.2.2"

### Expected behaviour
i expect set something , can transition like ios.
but can not found CardStackStyleInterpolator from react-navigation. 

### Actual behaviour
can not found CardStackStyleInterpolator from react-navigation

code like this:

`import {
  Router,
  Stack,
  Scene
} from "react-native-router-flux";
import { CardStackStyleInterpolator } from 'react-navigation';

`const` App = () => (
 ` <Router>`
    `<Scene key="root">`
      `<Scene key="home" component={Home} hideNavBar initial={true}/>`
     ` <Scene key="login" component={Login} hideNavBar/>`
    `</Scene>`
  `</Router>`
);`

then error:  cannot found CardStackStyleInterpolator

**Comment by aksonov** [comment]
Please check `example/native/App.js` and custom transition there (`react-native-stack` must be used)
