### ISSUE TITLE
Transition bottom to top

### ISSUE THREAD

**Issue by tonypeng** [aksonov/react-native-router-flux#3651]
Is there any way to open scenes in a bottom-to-top transition? (unlike the default sliding in from right) It seems like the old `direction="vertical"` no longer works.

### Version
Tell us which versions you are using:

- react-native-router-flux v4.2.0
- react v16.9.0
- react-native v0.61.5

**Comment by 6iix** [comment]
Running into the same issue, I have tried a few different things and had no luck. Anyone have anything to try? I have One stack with multiple scenes. I want a specific scene in the stack to come in from the bottom. 

@tonypeng any luck on this?

**Comment by tonypeng** [comment]
@6iix for the time being, I'm simply using an animated Modal component--it's suboptimal and makes the code not as clean but works for my use case as I don't have any complicated history for this particular scene. I plan on doing some more digging around later and I'll post here if I find a better solution--let me know if you figure something out as well!

**Comment by 6iix** [comment]
@tonypeng sounds good, I am trying to figure something out, but it is looking like the modal might be the way to go. It's a shame we can't animate a single scene.

**Comment by DemonRodman** [comment]
@tonypeng I found a way to do it, but it involves switching packages. I switched to @react-navigation/native which provided a lot more control.

**Comment by aksonov** [comment]
@tonypeng  Just check example in native folder, Login screen is placed under `Modal`, I think it have desired behaviour. Closing
