### ISSUE TITLE
How to update the Stack's icon?

### ISSUE THREAD

**Issue by online-lorno** [aksonov/react-native-router-flux#3658]
### Version
- react-native-router-flux v4.2.0
- react v16.13.1
- react-native v0.62.2

### Expected behaviour
Updates tabbar icons with the props `activeTintColor` and `inactiveTintColor`

### Actual behaviour
Only updates the label's tintColor
![image](https://user-images.githubusercontent.com/6301441/79945758-1aa76300-84a1-11ea-9060-380ece76e343.png)

I currently have `Stack`s in the `Tabs`, each `Stack` has it's own `Scene`(s) and has an `icon` prop.
```
<Tabs activeTintColor="blue" inactiveTintColor="grey">
    <Stack title="Title 1" icon={() => <Icon type="MaterialIcons" name="warning" />}>
        <Scene ... />
        <Scene ... />
    </Stack>
    <Stack title="Title 2" icon={() => <Icon type="MaterialIcons" name="error" />}>
        <Scene ... />
        <Scene ... />
    </Stack>
</Tabs>
```

The props `activeTintColor` and `inactiveTintColor` only updates the label and not the tabbar icons as per the docs. I only tested this on Android.

**Comment by aksonov** [comment]
They are for labels, not for icons. Try to customise your Icon component instead to display icons with desired props
