### ISSUE TITLE
Navigation from drawer to another scene

### ISSUE THREAD

**Issue by pt147** [aksonov/react-native-router-flux#3659]
### Version

- react-native-router-flux v4.2.0
- react v16.8.6
- react-native v0.60.5

here is my routes file.

```
<Router>

    <Scene key="app" hideNavBar={true} initial={this.props.isLoggedIn}>

        <Drawer key="drawer" drawer={true} contentComponent={SideMenu} initial={true}>
                 <Scene key="homeScreen" component={HomeScreen} hideNavBar={false} navBar={() => <HeaderDrawer title="Home" />} />
                 <Scene key="paymentScreen" component={PaymentScreen} hideNavBar={false} navBar={() => <HeaderDrawer title="Payment" />} />
                 <Scene key="activityScreen" component={ActivityStatement} hieNavBar={false} navBar={() => <HeaderDrawer title="Activity Statements" />} />
         </Drawer>

        <Scene key="forgotPassword" hideNavBar={false} component={ForgotPasswordScreen} navBar={() => <Header title="Forgot Password" />} />

    </Scene>

<Router>
```
Now, I can able to move from one of the drawer tab to `forgotPassword` using `Actions.forgotPassword()` but from `forgotPassword` I'm not able to come back to drawer using `Actions.pop().` Can anybody tell what's wrong here?

**Comment by shiroze** [comment]
Try this

```
<Router>
  <Overlay key="overlay">
    <Modal key="modal" transitionConfig={transitionConfig}>
      <Drawer key="drawer" drawer={true} contentComponent={SideMenu} initial={true}>
                <Scene key="homeScreen" component={HomeScreen} hideNavBar={false} navBar={() => <HeaderDrawer title="Home" />} />
                <Scene key="paymentScreen" component={PaymentScreen} hideNavBar={false} navBar={() => <HeaderDrawer title="Payment" />} />
                <Scene key="activityScreen" component={ActivityStatement} hieNavBar={false} navBar={() => <HeaderDrawer title="Activity Statements" />} />
        </Drawer>

      <Scene key="forgotPassword" hideNavBar={false} component={ForgotPasswordScreen} navBar={() => <Header title="Forgot Password" />} />
    </Modal>
  </Overlay>
<Router>
```
And button menu on press add

> onPress={() => { Actions.forgotPassword({ onBack: () => { Actions.drawer() } }); }}

For me this work fine


Also, can you provide react, react-native, RNRF version ?

**Comment by pt147** [comment]
Thank you for your solution but it didn't work for me. While pressing the default back button i kicked out from the app instead of getting back on drawer.

And yes i am using following versions.

- react-native-router-flux v4.2.0
- react v16.8.6
- react-native v0.60.5

I am new to this react world and i am really want to solve this. 

Thank you.

**Comment by pt147** [comment]
**Update:**
I'd put `type='replace` in `<Scene> ` . Now pressing the back button in android i am back at Drawer. However  how can i implement this behaviour while pressing the back button of header ?

**Comment by shiroze** [comment]
> **Update:**
> I'd put `type='replace` in `<Scene> ` I removed it. Now pressing the back button in android i am back at Drawer. However how can i implement this behaviour while pressing the back button of header ?

RNRF Back Button automatically do Actions.pop() so we don't have to add it.

also please remove

> hideNavBar={false} navBar={() => <HeaderDrawer title="Home" />}

to add title in header use this method
```
              <Scene 
                key="your_key"
                title="Your_title"
                onLeft={() => console.log("Back")}
                component={your_component}
              />
```

**Comment by pt147** [comment]
Yes. Thank you very much. This works like a charm but then again can i use my own header as `navBar` component and expects the same result as a default one? Would it be possible?

**Comment by shiroze** [comment]
> Yes. Thank you very much. This works like a charm but then again can i use my own header as `navBar` component and expects the same result as a default one? Would it be possible?

yes you can, I recommend read the react-navigation docs to customize the navbar
