### ISSUE TITLE
Drawer Menu is not showen when I drag from left to right

### ISSUE THREAD

**Issue by joerecra** [aksonov/react-native-router-flux#3668]
### Version
Tell us which versions you are using:

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-drawer": "^2.5.1",
"react-native-gesture-handler": "^1.6.1",
"react-native-reanimated": "^1.9.0",
"react-native-router-flux": "^4.2.0",
"react-native-screens": "^2.8.0"

### Expected behaviour

When I try to drag from left to right to show Drawer Menu. It is not shown. it Just Works when I click in hamburguer menu.

### Actual behaviour

Menu should be showen when I drag from left to right and hidden when I drag from right to left

### Steps to reproduce
Router:

```
<Router>
            <Scene>
              <Scene
                  key="Login"
                  component={Login}
              />
              <Drawer key="drawerMenu" hideNavBar drawer={true} contentComponent={SideBar} drawerWidth={220}>
                <Scene key="root">
                  <Scene key="home"  drawer={true} component={Home}/>
                </Scene>
              </Drawer>
            </Scene>
          </Router >
```
SideBar:

```
import React from 'react'
import { StyleSheet, View, Text } from 'react-native'

const SideBar = () => {
  return (
      <View style={styles.container}>
          <Text>menu items go here</Text>
      </View>
  );
}
export default SideBar;
```

**Comment by samagyaneshwar** [comment]
Hey @joerecra , even i face the same issue.
You can check #3666 for the solution.
