### ISSUE TITLE
Jest Test not working

### ISSUE THREAD

**Issue by kkh975** [aksonov/react-native-router-flux#3678]
### Version
- react": "16.13.1",
- react-native": "0.62.2",
- react-native-router-flux": "^4.2.0",
- @babel/core": "^7.10.2",
- @babel/runtime": "^7.10.2",
- @testing-library/react": "^10.2.1",
- @testing-library/react-hooks": "^3.3.0",
- @testing-library/react-native": "^5.0.3",
- @types/react-native-vector-icons": "^6.4.5",
- babel-jest": "^26.0.1",
- jest": "^26.0.1",
- react-native-testing-library": "^2.1.0",
- react-test-renderer": "16.13.1",

### Expected behaviour
I have simple view and try to test it. See below.
Result is not expected that I want.

### Steps to reproduce
1. SImple View
```js
import React, { useCallback } from 'react';
import { View, TouchableOpacity } from 'react-native';
import { Actions } from 'react-native-router-flux';
import Icon from 'react-native-vector-icons/AntDesign';

const MyView = ({ children }) => {
  const onPress = useCallback(() => {
    Actions.push('webview', '');
  }, []);

  return (
    <View>
        <TouchableOpacity onPress={onPress} testID="Press">
          <Icon name="right" size={30} color="#000" />
        </TouchableOpacity>
    </View>
  );
};
```
2. Jest Testring file
```js
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import MyView from '../../src/MyView';
import { Actions } from 'react-native-router-flux';

describe('UserTermAgree', () => {
  it('기본동작', async () => {
    const spy = jest.spyOn(Actions, 'push');
    const inst = render(<MyView />);
    const press = inst.getByTestId('Press');

    fireEvent.press(press);

    expect(spy).toHaveBeenCalled();
  });
});

```
3. Result:
<img width="1114" alt="스크린샷 2020-06-22 오후 5 59 09" src="https://user-images.githubusercontent.com/1680132/85268950-29ff5880-b4b2-11ea-8ebc-d657198d616a.png">

Some answer says try to below in jest.config.js.
```js
transformIgnorePatterns: ['node_modules/(?!react-native|react-navigation)'],
```

but result is:
<img width="1090" alt="스크린샷 2020-06-22 오후 6 06 00" src="https://user-images.githubusercontent.com/1680132/85269584-0d175500-b4b3-11ea-9526-d9ffb16c36a0.png">

after try to:
```js
transformIgnorePatterns: ['node_modules/(?!react-native|react-navigation|react-native-screens)'],
```

than, other export file conflict...
<img width="727" alt="스크린샷 2020-06-22 오후 6 08 04" src="https://user-images.githubusercontent.com/1680132/85269774-55367780-b4b3-11ea-9883-5542c40e4a4c.png">

**Comment by kkh975** [comment]
I figure out how solve it. 

I fixed transformIgnorePattern on jest.config.js.

I have to add not only ''react-native" but also "@react-native".

**Comment by RicardoBrito1938** [comment]
Hello @kkh975 

i am facing the same error, my config is 

  "jest": {
    "preset": "@testing-library/react-native",
    "testMatch": ["**/__tests__/**/*.test.js"],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect",
      "@testing-library/react-native/cleanup-after-each"
    ],
    "coverageDirectory": "__tests__/coverage",
    "setupFiles": ["./jest.setup.js"],

    "transformIgnorePatterns": [
      "node_modules/(?!react-native|@react-native|react-navigation|react-native-screens)"
    ]
  }

is this correct?

**Comment by RicardoBrito1938** [comment]
Hello @kkh975 

could you help me? i got the same error, when i change the config file 

```  ● Test suite failed to run

    TypeError: Cannot read property 'Direction' of undefined

      at Object.<anonymous> (node_modules/react-native-gesture-handler/Directions.js:3:39)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/GestureHandler.js:2:1)``` 


my config is 

```       "node_modules/(?!react-native|react-navigation|react-native-gesture-handler)"
```

**Comment by kkh975** [comment]
@RicardoBrito1938  
Check up like below on jest.config.js file

```js
const jestPreset = require('@testing-library/react-native/jest-preset');

module.exports = {
    // preset: 'react-native',
    preset: '@testing-library/react-native',
    ...
}
```

**Comment by RicardoBrito1938** [comment]
> @RicardoBrito1938
> Check up like below on jest.config.js file
> 
> ```js
> const jestPreset = require('@testing-library/react-native/jest-preset');
> 
> module.exports = {
>     // preset: 'react-native',
>     preset: '@testing-library/react-native',
>     ...
> 

Thank you very much, it worked!!

**Comment by RicardoBrito1938** [comment]
Hello @kkh975 , it me again, i got stucked in another issue, it would be great if just take a look on it 


I have a simple function wich i call on my button 
```  const sendUserToQuiz = () => {
    logger('GOAL', 'QUIZ', JSON.stringify({ id }), '[MAIN_SCREEN,QUIZ]');
    // eslint-disable-next-line new-cap
    Actions.Quiz({
      id,
    });
  };```

and my test is     const spy = jest.spyOn(Actions, 'Quiz');


but i got the following response


![image](https://user-images.githubusercontent.com/51454097/86957323-f1f24980-c130-11ea-8034-c895a265d578.png)

would you have any tip for that?

**Comment by RicardoBrito1938** [comment]
Hello @kkh975 , me again, if could give a tip, that would be very helpful

my test is very similar to yours, but it doesnt work 

``` const onPress = () => {   
    Actions.Quiz({
      id,
    });
  };````


is this case i go directly to "Quiz" scene, i tried to write the test like that:

    const button = getByTestId('button');

    const spy = jest.spyOn(Actions, 'push');
    fireEvent.press(button);

    expect(spy).toHaveBeenCalled();


would you have any tip, how i could adapt it?
