### ISSUE TITLE
backButtonTitle doesn't appear

### ISSUE THREAD

**Issue by AntonPuko** [aksonov/react-native-router-flux#368]
Hello. I don't see back button title not in my project, and even not in example.
![lefttitle](https://cloud.githubusercontent.com/assets/8849922/13951321/d8cedb76-f038-11e5-8d0b-e2eed2333b6e.png)
Is there something i'm missing?

**Comment by aksonov** [comment]
No, it is default behaviour of React Native NavigationHeader (NavBar is improved copy of it) component - looks like many developers prefer it without displaying of title of prev. route.

Anyway you could use renderBackButton to render text or something or submit PR to improve the component.

**Comment by AntonPuko** [comment]
Thanks, i've got it!
