### ISSUE TITLE
Usage with Redux

### ISSUE THREAD

**Issue by isikfsc** [aksonov/react-native-router-flux#37]
Can this be used with Redux instead of Facebook Flux?

**Comment by aksonov** [comment]
I'm pretty inspired with Redux and want to create next version based on it. But i don't have any Redux experience, so still don't have any idea how to make it in 'right' way. Looks like it should be top 'container' component, but it is all know at this moment :)

**Comment by Mokto** [comment]
This is my redux way to do it : 

Action
```javascript
'use strict';

import { Actions } from 'react-native-router-flux';


const actions = exports = module.exports;
exports.PUSH = 'PUSH';
exports.RESET = 'RESET';
exports.POP = 'POP';


exports.push = function push(name, data) {
  if(typeof Actions[name] == 'function') {
    Actions[name](data);
  }
  return {
    type: actions.PUSH,
    name: name,
    data: data
  }
};
exports.reset = function reset(name, data) {
  Actions.reset(name);
  return {
    type: actions.RESET,
    name: name,
    data: data
  }
};

exports.pop = function pop() {
  Actions.pop();
  return {
    type: actions.POP
  }
};
```

Reducer : 
```javascript
'use strict';

import { PUSH, RESET, POP } from '../actions/router';

var initialState = [{
  name: 'home'
}];

module.exports = function router(state = initialState, action) {
  switch (action.type) {
    case PUSH:
      return [
        ...state,
        {
          name: action.name,
          data: action.data
        }
      ];
    case RESET:
      return [{
        name: action.name,
        data: action.data
      }];
    case POP:
      var res = [...state];
      return res.filter(function (item, i) {
        return i<res.length-1
      });
    default:
      return state;
  }
};

```

**Comment by Mokto** [comment]
Also see this : https://github.com/burgalon/react-native-redux-navigator

**Comment by aksonov** [comment]
@Mokto thanks, but i want to make the component itself to use redux, without alt. i.e. replace all alt dependencies to redux ones. Looks like it should be created as 'middleware' (i'm studying redux right now)

**Comment by aksonov** [comment]
It seems not correct to add this support for this component, because it has 'flux' in its name, so i've created separate component react-native-redux-router with Redux support, all comments are welcome! Thanks for feedback and pointing me to great Redux library :)

https://github.com/aksonov/react-native-redux-router

**Comment by isikfsc** [comment]
thanks a lot. :)
I hope I will try it soon.

**Comment by isikfsc** [comment]
Hi there,
I have a question for redux version [here](https://github.com/aksonov/react-native-redux-router/issues/3)

**Comment by aksonov** [comment]
Related #44. I'm going to unite both components, simplify and make it suitable for any flux/redux implementation.

**Comment by aksonov** [comment]
It is published, looks like i have to abandon 'redux'-related version, because latest one is suitable for any flux implementation
