### ISSUE TITLE
How to disable iOS bounce effect on scene load?

### ISSUE THREAD

**Issue by bhaskardabhi** [aksonov/react-native-router-flux#3704]
My scene is bouncing whenever it is loaded. I want to disable the effect. I did many search but not able to find any solution. I am attaching gif for the animation here:

![](https://i.imgur.com/YsCxwTk.gif)

I tried searching for solution but didnt find anything. Following are my dependencies:

```
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-gesture-handler": "~1.6.0",
"react-native-reanimated": "~1.9.0",
"react-native-router-flux": "^4.2.0",

```

**Comment by daviCalavera** [comment]
I have the same problem, could you solve it @bhaskardabhi ?

**Comment by dennisbouwpas** [comment]
+1 I have the same issue

**Comment by daviCalavera** [comment]
I found a solution in my case @dennisbouwpas 
I used scrollviews on each scene and scorllview by default on iOS has the "bounces" attributes true by default (https://reactnative.dev/docs/scrollview#bounces)
I set it on false (bounces={false}) and que issue dissapeared.
