### ISSUE TITLE
Back arrow icon missing on iOS 14

### ISSUE THREAD

**Issue by lucasroca** [aksonov/react-native-router-flux#3709]
### Version
- react-native-router-flux v4.2.0
- react v16.9.0
- react-native v0.61.5

### Expected behaviour
Back arrow to be displayed on navbar

### Actual behaviour
Back arrow not being displayed on navbar

### Steps to reproduce
1. Install the react-native example from this repository
2. Run it on iOS 14
3. Click the "Go to Register page" option

### Reproducible Demo
![image](https://user-images.githubusercontent.com/29613530/94140309-56d55a00-fe6b-11ea-8e5f-de89759441ca.png)
![image](https://user-images.githubusercontent.com/29613530/94140337-605ec200-fe6b-11ea-8929-f52cc0ee21fd.png)

**Comment by jsbls** [comment]
You need to update `react-navigation` to 4.4.1

**Comment by lucasroca** [comment]
Looks like it's actually a react native bug. I've applied this patch: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428 and the arrow image is displayed now.

By the way, is it possible to pass a component in RNRF to display instead of the default image?
`backButtonImage` seems to only support images.
