### ISSUE TITLE
Pass previous route details like title as props

### ISSUE THREAD

**Issue by ponty96** [aksonov/react-native-router-flux#371]
I don't know if version 3.x passes the previous route details to the new route as props but 2.x doesn't.
When using NavigatorIOS the back button shows the title of the previous Screen | Route and it will be more efficient to programmatically get few details of the previous route passed as props to the current Screen | Route. Minimal details like the title should be passed with the route props passed down

![screen shot 2016-03-22 at 6 09 14 pm](https://cloud.githubusercontent.com/assets/11190968/13961026/11428ed6-f05b-11e5-96e0-d29c9674bfca.png)

**Comment by aksonov** [comment]
Have you tried with v3 ? Why you created issue even without checking of latest supported version??

**Comment by ponty96** [comment]
because I'm still using version 2.x and I dont know if v2 has been discontinued.... and i'm not ready to upgrade to v3 yet....

**Comment by aksonov** [comment]
v2 is not supported. NavigatorIOS is not supported by React Native and this component as well.
