### ISSUE TITLE
Each tab component is rendered even when not selected

### ISSUE THREAD

**Issue by rgovindji** [aksonov/react-native-router-flux#372]
On application start, each tab component is rendered even if it's not visible. Is this by default? Do I need to use the Switch component to stop this?

**Comment by aksonov** [comment]
It is how NavigationView works. This component is just wrapper around Navigation API:
```
      <View
        style={this.props.style}>
        {this.props.navigationState.children.map(this._renderScene)}
      </View>
```

You always could implement your custom renderer instead of TabBar to avoid this. Feel free to do it and PR would be very appreciated.
