### ISSUE TITLE
Hermes integration failed with two product flavours

### ISSUE THREAD

**Issue by naveksha-jain** [aksonov/react-native-router-flux#3728]
### Version
Tell us which versions you are using:

- react v16.11.0
- react-native v0.62.2

Product flavours 2 - uat and prod

### Expected behaviour
assembleRelease command should be successful

### Actual behaviour
FAILURE: Build failed with an exception.
Process 'command '../../node_modules/hermes-engine/osx-bin/hermes'' finished with non-zero exit value 6

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by aksonov** [comment]
Not related to RNRF (it is NOT native component)
