### ISSUE TITLE
Tab scenes are set to type="push" even tho type="jump" was initially declared

### ISSUE THREAD

**Issue by rgovindji** [aksonov/react-native-router-flux#373]
I set in my code for the tab to be type="jump" but when debugging it shows type="push"

` <Scene key="NewsFeed" component={NewsFeedPage} icon={TabIcon} initial={true} type="jump" iconLabel="ios-home" title="News Feed" />`

<img width="938" alt="screen shot 2016-03-22 at 5 34 25 pm" src="https://cloud.githubusercontent.com/assets/251495/13968670/6665ec84-f054-11e5-8b5c-d508f06cfd92.png">

**Comment by aksonov** [comment]
As you see sceneKey ends with '_'. It means that it is _inner_ scene. Each tab scene should contain inner scene with navbar, so navbar could be displayed:
```
            // wrap scene if parent is 'tabs'
            if (parentProps.tabs) {
                const innerKey = res.key + '_';
                const inner = {...res, name:key, key: innerKey, type: PUSH_ACTION, parent:res.key}
                refs[innerKey] = inner;
                res.children = [innerKey];
                delete res.component;
            }
```
