### ISSUE TITLE
libc.so crash on screen change

### ISSUE THREAD

**Issue by krunalbad** [aksonov/react-native-router-flux#3742]
### Version
Tell us which versions you are using:

- react-native-router-flux v4.0.6
- react v16.13.1
- react-native v0.63.2

### Actual behavior
![Screenshot 2021-03-23 at 12 19 04 PM](https://user-images.githubusercontent.com/45413622/112105128-0b112c80-8bd2-11eb-89fb-2d5ee2367041.png)

**Comment by aksonov** [comment]
Unrelated to RNRF (it is not native library)
