### ISSUE TITLE
Transitions between scenes in tabs scenes are slow regardless of duration

### ISSUE THREAD

**Issue by AlexDM0** [aksonov/react-native-router-flux#381]
Hi,

I've updated your Example.js like so:

```js
<Scene key="tabbar" tabs={true} default="tab2"  duration={1} >
    <Scene key="tab1"  title="Tab #1" icon={TabIcon} navigationBarStyle={{backgroundColor:'red'}} titleStyle={{color:'white'}}  duration={1} >
        <Scene key="tab1_1" component={TabView} title="Tab #1_1" onRight={()=>alert("Right button")} rightTitle="Right"  duration={1}  />
        <Scene key="tab1_2" component={TabView} title="Tab #1_2" titleStyle={{color:'black'}} duration={1} />
    </Scene>
    <Scene key="tab2" initial={true} title="Tab #2" icon={TabIcon} duration={1}>
        <Scene key="tab2_1" component={TabView} title="Tab #2_1" onLeft={()=>alert("Left button!")} leftTitle="Left" duration={1}/>
        <Scene key="tab2_2" component={TabView} title="Tab #2_2" duration={1}/>
    </Scene>
...
```

So all scenes have a duration property set to 1. If you click on "Go to TabBar page" then "next screen for tab2_1" you expect no animations. I've put a debug print in the defaultRenderer and the duration of 1 is successfully propagated (the selected is always tab2 by the way?).

The animations are also much slower than the normal 250 ms compared to the scenes outside of the tabs.

Did I miss something? (I did search the issues this time, sorry about the last one.)

Regards

**Comment by zxcpoiu** [comment]
I don't know neither.

But I've noticed slow transitions even crashed. ( Use genymotion 2.6.0 )
When I encounter this problem, one of my CPU core became 100%. 
If lucky, it continued after few seconds, otherwise it crashed.

maybe it related to RN new API.

**steps:**

click and back items from top to bottom,
it occurs usually after leave `error prompt scene` and click tap item.

**Comment by thessem** [comment]
If you're on Android the 0.22 release of React Native's experimental navigator seems to not work very well (Unusably slow transitions, eventually crashes). This gets a little better if you pull in the git version.

I think the relevant issue on RN is facebook/react-native#6474 or similar

**Comment by AlexDM0** [comment]
Hi, 

I'm using iOS at the moment. I'll give it a shot though!

Regards

**Comment by aksonov** [comment]
Please check 3.1.6
