### ISSUE TITLE
TypeError: _core.pathUtils is undefined 

### ISSUE THREAD

**Issue by vkanagarajan** [aksonov/react-native-router-flux#3823]
### Version
Tell us which versions you are using:
 "react": "16.13.1",
        "react-native": "0.63.4",
    "@react-navigation/core": "6.1.1",
        "@react-navigation/native": "6.0.8",
  "react-native-router-flux": "4.2.0",
        "react-native-screens": "3.13.1",

### Actual behaviour

![Simulator Screen Shot - iPad Air 2 - 2022-05-12 at 22 10 30](https://user-images.githubusercontent.com/53504749/168126262-abd65a6c-f1e4-4b59-9c5e-f0cf5655d88e.png)

### Steps to reproduce
After npm install given getting the below error for router flux package 
TypeError: _core.pathUtils is undefined 

### Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by xenos28** [comment]
RNRF support React Navigation v4.x

Not v6

**Comment by vkanagarajan** [comment]
@xenos28  
this package version 
"@react-navigation/native": "6.0.8",

**Comment by vkanagarajan** [comment]
After adding the below package issue fixed   
"react-navigation": "4.4.4",
