### ISSUE TITLE
Double tapping on link creates a double view

### ISSUE THREAD

**Issue by AlexDM0** [aksonov/react-native-router-flux#384]
Hi,

When using the example, if you click on a link twice quickly (so before the new view has finished the animation) it will trigger a duplicate of the required view to slide in. Is this something we need to check in our reducer implementation or is it a bug?

Very ugly workaround:
```js
let startTime = new Date().valueOf();
let lastTime = new Date().valueOf();

const reducerCreate = params=>{
    const defaultReducer = Reducer(params);
    return (state, action)=>{
        // startTime so the application has booted, 250 for animation duration.
        if (new Date().valueOf() - lastTime < 250 && new Date().valueOf() - startTime > 1000) {
            return state;
        }
        lastTime = new Date().valueOf();
        return defaultReducer(state, action);
    }
};
```

I have a few big buttons that the user can click on and if they accidentally tap twice, I dont want to load 2 cards of the next view.

Regards

**Comment by evollu** [comment]
UIExplorer example has the same issue. I'm doing the same workaround

**Comment by slamus** [comment]
You should use the reducer to store the currentRoute somewhere in your app.
Then you check if the currentRoute is already set and prevent the route to be triggered twice.

**Comment by AlexDM0** [comment]
I had that before but then the example didn't work as it is calling a reference to itself. In production that wouldn't be the case so there your solution would indeed be better.

**Comment by aksonov** [comment]
Check 3.2.2, reducer doesn't change state for push the same route again.

**Comment by wkwyatt** [comment]
This issue persist when there is an object passed to the route.  
i.e. Actions.newScene({ params: { id: 5, name: "newRoute" } })

What should be done if this is the issue?
