### ISSUE TITLE
v3 After connecting Switch to Scene gettings infinite loops

### ISSUE THREAD

**Issue by Nikamura** [aksonov/react-native-router-flux#385]
After clicking login or signup links from Launch page it throws stack exceeded error, can be seen at the bottom picture.

Trying to debug my self, but help would be awesome.

```
export default class Navigator extends React.Component {
	render() {
		return (<Router>
			<Scene
				key="root"
				hideNavBar={true}
				component={connect((state) => ({ loggedIn: state.auth.login.loggedIn}))(Switch)}
				selector={(props) => "launch"}
			>
				<Scene key="launch" component={Launch}/>
				<Scene key="login" component={Login} direction="vertical"/>
				<Scene key="signup" component={Signup} direction="vertical"/>
			</Scene>
		</Router>)
	}
}
```

![image](https://cloud.githubusercontent.com/assets/3459367/14015707/b5a226c6-f1c3-11e5-94d6-b99f681b8fab.png)

**Comment by aksonov** [comment]
Why Switch doesn't have 'tabs' property?

**Comment by Nikamura** [comment]
Hmm, I see that it requires Tabs now, but I think that should be the case.

Let's say I have pages where tabs are not used (launch,login, register)

And when authenticated tabs are used there. So I can't use Switch unless I am using it with Tabs, is that correct?

**Comment by aksonov** [comment]
Switch is analog of 'switch' operator. Tabs are 'case' conditions.

**Comment by Nikamura** [comment]
Okay, I see. Thanks

Also there seems to be a bug:
```
			<Scene
				key="root"
				hideNavBar={true}
				tabs={true}
			>
				<Scene key="launch" component={Launch}/>```

NavBar is shown, even where hideNavBar is true, when tabs true is added.

**Comment by aksonov** [comment]
You should hideNavBar also for launch too, because all tabs are wrapped by NavBar.
