### ISSUE TITLE
Persisting the state of a tab

### ISSUE THREAD

**Issue by AlexDM0** [aksonov/react-native-router-flux#386]
Hi,

When using tabs, I'd like to store the state for each tab when switching between them.

In the Example.js:
go to the tab example,
click the "next screen for tab2_1"
click tab#1 in the bottom,
click tab#2 in the bottom,
We now see a transition from 2.2 to 2.1.

I want it to stay at 2.2 unless I'm already at tab#2 and then press tab#2. This is the behaviour of the apple App store for instance, browse in one tab, click another and go back to continue where you left off.

Is this possible?

Regards

**Comment by aksonov** [comment]
@joenoon Thanks for PR! 
Please check 3.1.6
