### ISSUE TITLE
navigationState props breaks pure shouldComponentUpdate

### ISSUE THREAD

**Issue by Elyx0** [aksonov/react-native-router-flux#392]
When components are connected, given that `navigationState` is not an Immutable
the `shallowEquals` or plain equals to determine if a component should update always fails. (Thus forcing the rerendering of the component)

![screenshot 2016-03-24 16 28 34](https://cloud.githubusercontent.com/assets/706218/14030330/7813c28c-f1dd-11e5-8101-3b4e1645061d.png)

Problem is that `shallowEquals` don't deal with nested structures. So when checking keys between `this.props` and `nextProps` it throws when it gets at the `navigationState` key.

```javascript
  var objA = this.props;
  var objB = nextProps;
  var keysA = Object.keys(objA);
  var keysB = Object.keys(objB);

  if (keysA.length !== keysB.length) {
    return false;
  }

  // Test for A's keys different from B.
  var bHasOwnProperty = hasOwnProperty.bind(objB);
  for (var i = 0; i < keysA.length; i++) {
    if (!bHasOwnProperty(keysA[i]) || objA[keysA[i]] !== objB[keysA[i]]) {
      console.log(keysA[i]); // Logs "navigationState"
      return false;
    }
  }
```

But running the same code with `objA = this.props.navigationState` and `objB = nextProps.navigationState` says that these items are shallowEqual. So no change happened actually. Which should not trigger an update.

This is a causing a lot of mounted components to update for no reason when navigating.

**Comment by aksonov** [comment]
I believe it happens because currently the component copies full state using Immutable.fromJs().toJS() I know it is not effective, if you know better alternative to modify some substate only quickly, please submit PR.

**Comment by aksonov** [comment]
Another possible reason is 'current' key for scene is always changing, so root router will always re-render because it will thought that his property is changed. I'm going to remove it and use getCurrent() function instead

**Comment by aksonov** [comment]
Okey, I've done major refactoring to improve state management within reducer, now it is not fully cloned, but only partially, please check carefully 3.2.0, some bugs may occur...

**Comment by aksonov** [comment]
Closing it for now (because of silence)

**Comment by Elyx0** [comment]
Awesome work, thank you, so far so good. Will reopen if I see issues.
