### ISSUE TITLE
Calling Same Route with different props mounts it idefinitely

### ISSUE THREAD

**Issue by slamus** [aksonov/react-native-router-flux#395]
Hi,

Just upgraded to v3, and everything is working as expected even if the breaking changes were breaking a lot of things ;)
However I have one remaining issue, and I cannot find a solution to it:

I'm calling a single modal route from different places in my code, and with different props.
I change the content of the modal according to the props sent.

#### BEFORE 
The modal was updating perfectly as you expect with a single view changing its state.
#### AFTER
The modal is working good at first call.
But when I try to call the route a second time with different props, the component is mounted repeatedly like in a infinite loop...

*Edit: the `componentWillReceiveProps()` method is called repeatedly and the `render()` method too.*

#### CODE

Main Router

```jsx
<Router createReducer={params => this.routerReducerCreate(params)}>
  <Scene key="container" component={Modal}>
    <Scene key="root" hideNavBar={true} component={MainContainer}>

      <Scene
        key="Login"
        type="replace"
        component={LoginPageContainer}
        initial={true}
      />

      <Scene
        key="Platform"
        type="replace"
        component={PlatformContainer}
      >
      // .....SOME ROUTES
      </Scene>

    </Scene>

    <Scene
      key="Modal"
      component={ModalContainer}
    />

  </Scene>
</Router>
```

How I call the route

```js
    Actions.Modal({
      modal: "countryCode",
      callback: (country) => {
        if (country) {
          this.props.onSubmit({
            phone_number: country.dial_code,
          });
        }
      }
    })
```
OR

```js
     Actions.Modal({
        modal: "webView",
        callback: ()=>{
          appActions.setWebViewURL(null);
        },
        data: {
          webViewURL: this.props.app.get("webViewURL"),
        },
      })
```js

**Comment by aksonov** [comment]
Hm... I'm not sure that you are using modals correctly... Could you check Example and how 'error' popup modal works there?

**Comment by slamus** [comment]
Yes,
I will try to change my logic to match the example one.
Keep you updated

**Comment by slamus** [comment]
Well,
After thinking about it a bit: **I just want to pass new props to the current view !**
How do I do that ?

**Comment by aksonov** [comment]
Hm, Actions.refresh(props)? I've added it to Example, to login screen (it changes title)

**Comment by slamus** [comment]
Yes, but if I want to do that from outside the current mounted component ? Can I do that ?

**Comment by aksonov** [comment]
Hm, you said "pass new props the current route". Anyway you may try Actions.refresh({key:KEY, ...props}) where KEY is that component...

**Comment by slamus** [comment]
Perfect, will try that.

**Comment by aksonov** [comment]
3.2.1 should allow setting key for refresh action.

**Comment by slamus** [comment]
thanks for notifying
