### ISSUE TITLE
Navigating to a Schene if you know the schenes key as a string.

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#396]
I want to know how to navigate to a Schene , when I already have its key on a string.

    import {Actions} from 'react-native-router-flux';
    var scheneKey = "LoginSchene";
    
Apparently I can't do:
    
    Actions[scheneKey]();

nor do I want to do:
    
    Actions.LoginSchene();

I would like something like:

    Actions.navigateTo(scheneKey);

but I can't find such a method.

Thank you.

**Comment by aksonov** [comment]
Why you can't do Actions[scheneKey](); ?

**Comment by SudoPlz** [comment]
Because `_reactNativeRouterFlux.Actions[schene] is not a function` is the error I get.

**Comment by SudoPlz** [comment]
Omg it was totally my bad. `Actions[scheneKey]();` is working after all, I had a typo in the scheneKey... Sorry for wasting your time.
