### ISSUE TITLE
Breaks when minified

### ISSUE THREAD

**Issue by jacob-israel-turner** [aksonov/react-native-router-flux#4]
When I bundle/minify my app, this library breaks.  For some reason, the component names don't get added to the `Actions` object after minification.

`Object.keys(Actions)` prior to minification:

``` javascript
["push", "PUSH", "pop", "POP", "dismiss", "DISMISS", "preSplash", "splash", "login", "register", "etc."]
```

`Object.keys(Actions)` after minifcation:

``` javascript
[ 'push', 'PUSH', 'pop', 'POP', 'dismiss', 'DISMISS' ]
```

**Comment by aksonov** [comment]
Thanks, it seems to be real issue - probably because Actions are generated in runtime, not compile time and minificator brakes it somehow. But it seems to be out of my control, any idea how to make it work with minification?

**Comment by jacob-israel-turner** [comment]
I'll take a look at it this afternoon, I honestly have no idea how your library works yet. :P I'll let ya know what I find.

**Comment by aksonov** [comment]
It works in straightforward way: it just adds new functions during processing of «Route» children to alt Actions object. Maybe I need to ask within alt github how to add custom actions in runtime correctly.

**Comment by aksonov** [comment]
Please check latest version 0.1.0, this bug should be fixed.

**Comment by jacob-israel-turner** [comment]
@aksonov Thanks.  We ended up going with an unminified bundle because of time restraints.  I'll take a look at 0.1.0 for our next release.
