### ISSUE TITLE
why the animation is forbidden in Container.js

### ISSUE THREAD

**Issue by daemonchen** [aksonov/react-native-router-flux#40]
I saw in Container.js line 113:

` var sceneConfig = route.sceneConfig || schema.sceneConfig || Animations.None;` has been commented.

I used to uncomment this code and it works fine with animation such as `<Schema name="tab" navBar={NavBar} sceneConfig={Navigator.SceneConfigs.HorizontalSwipeJump} />` in `index.ios.js`.

So what's the reason that you commented this code?

**Comment by aksonov** [comment]
Okey, currently Container implementation looks a little bit 'hacky' - it uses navigator 'push' inside for new tabs, so user may see wrong 'push'-like navigation for initial rendering of tab... If you know how to deal with it, PR is welcome

**Comment by aksonov** [comment]
Check latest version that allows inner Router to define
