### ISSUE TITLE
JS frame rate goes to -2.0 on Android deployed from Windows

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#401]
Running Example project on Android deployed from Windows 10 x64
after navigating through a bit JS frame rate always goes to -2.0 and the app becomes unresponsive.
It will eventually crash (my phone possibly going out of memory)

**Comment by aksonov** [comment]
Seems duplicate of #355

**Comment by bosung90** [comment]
This bug seems to be 50% fixed in 0.23.0rc-1.
However, react-native-router-flux has a peer dependency of 0.22.
How can I use 0.23 with react-native-router-flux?
