### ISSUE TITLE
Render all tabbar sub-scenes on any tab's click

### ISSUE THREAD

**Issue by spaceoi** [aksonov/react-native-router-flux#403]
I am wondering it's a feature or a bug.

If you click any tab, like Tab#5 in the example, all of the tabviews(5 tabs in the example) will be rendered. It will be better if only render one tab instead of all of them, since the user only cares about the selected tab.

**Comment by aksonov** [comment]
Could you check UIExplorer ExperimentalNavigator tab demo (from React Native 0.22 package)?

**Comment by emrosenf** [comment]
They are aware of the issue and will refactor it soon. See https://github.com/facebook/react-native/issues/6579

**Comment by spaceoi** [comment]
Yes I have checked the code and @emrosenf figured it out! thank you @aksonov and @emrosenf !
