### ISSUE TITLE
getting an error from the chevron, any ideas to resolve?

### ISSUE THREAD

**Issue by lwhiteley** [aksonov/react-native-router-flux#405]
Error while persisting cache: SyntaxError /Users/layton/Documents/dev/app/node_modules/react-native-router-flux/src/back_chevron.png: Unexpected character '�' (1:0)

![https://i.imgur.com/Du9gotJ.png](https://i.imgur.com/Du9gotJ.png)

**Comment by lwhiteley** [comment]
may have been resolved by clearing watchman cache

**Comment by aestrro** [comment]
Actually, I'm getting the same error on the `burger menu (menu burger) <- lolz` 

![hamburgerissue](https://cloud.githubusercontent.com/assets/1408518/15334868/cd051fea-1c24-11e6-9dda-7049c3ee718c.png)

**Comment by lwhiteley** [comment]
i stopped my packager and ran `watchman --watch-del-all` and then restarted my packager and it started working for me
