### ISSUE TITLE
Upgrading to V3.1.3 has broken replace type

### ISSUE THREAD

**Issue by JamesWatling** [aksonov/react-native-router-flux#408]
Since upgrading to the latest `v3.1.3` version the replace functionality is not working correctly.

I have updated my previous code to account for the new updates in V3, but the replace type acts as a normal push state. Have I simply overlooked something, or is this a new bug.

```
  <Scene
       key={Routes.LESSONS_INDEX}
       initial={this._loggedIn()}
       component={LessonsIndexContainer}
       type="replace"
   />
```

On another note, love what you're doing here, but due to the speed of releases do you think it would be wise to have a more formal changelog that details all the changes in each release.

Also if you require any assistance for updating the documentation let me know :smile:

**Comment by marcosbeirigo** [comment]
Don't uses this terrible shit

**Comment by aksonov** [comment]
I can do change logs, but it will make all things much much slower - so far many people want to use but nobody want to help.

Always check latest npm versions from NPM, not from github (because i can't create each version there)
