### ISSUE TITLE
All TabBar views mounted on initial render

### ISSUE THREAD

**Issue by kesha-antonov** [aksonov/react-native-router-flux#409]
Hello!

In v2. TabBar scenes called componentDidMount only when the tab was focused. Now all of them gets mounted in the same time.

For example:
```
TabBar
  Tab1
  Tab2
  Tab3
```
When I go to Tab1 - Tab2 and Tab3 will mount so we have 3 calls to api at the same time.

Maybe I'm missing something? Please advise.

**Comment by aksonov** [comment]
Please always search existing issues first. Duplicate of #372

**Comment by kesha-antonov** [comment]
Thanks! @aksonov
