### ISSUE TITLE
Navbar is hidden in pages even if  hideNavBar is false

### ISSUE THREAD

**Issue by ajaybc** [aksonov/react-native-router-flux#41]
I am developing for Android.
When I am using the following router code

```
<Router>
    <Route name="launch" component={HomePage} initial={true} title="Launch"/>
    <Route name="settings" component={SettingsPage} title="Settings" />
</Router>
```
When I launch the app and is in the HomePage, everything is well and fine.

![screenshot from 2015-11-22 13 02 53](https://cloud.githubusercontent.com/assets/414383/11322586/83f4274c-9119-11e5-96a8-d2bcd1fb0ac8.png)

But when I navigate to the settings page the navbar disappears even though it is there in the code of the component.
![screenshot from 2015-11-22 13 06 16](https://cloud.githubusercontent.com/assets/414383/11322598/f0c3321e-9119-11e5-9134-2cb18bb5e2c0.png)

Here is the layout for the settings page 
```
<DrawerLayoutAndroid
          drawerWidth={300}
          drawerPosition={DrawerLayoutAndroid.positions.Left}
          renderNavigationView={() => navigationView}
          ref={'DRAWER'}>
            <View style={{flex: 1}}>
                <ToolbarAndroid
                  title="Test"
                  actions={[{title: 'Settings'}]}
                  onActionSelected={this.onActionSelected}
                  style={{backgroundColor: '#FF0000',height: 56}}
                  navIcon={require('../../assets/images/hamburger.png')}
                  titleColor='#FFF'
                  onIconClicked={this.onIconClicked}>
                </ToolbarAndroid>

                <ScrollView
                    style={styles.settingsScroller}>
                    <Text>Settings</Text>
                </ScrollView>
            </View>
        </DrawerLayoutAndroid>
```

Am I doing it wrong or is it a bug ?

**Comment by pewh** [comment]
+1 I have same issue too

**Comment by aksonov** [comment]
Current version was not tested on android devices at all. I'm preparing now 1.0 release which will work on both devices, check #44

**Comment by aksonov** [comment]
Please check now
