### ISSUE TITLE
Help with nested routing

### ISSUE THREAD

**Issue by texas697** [aksonov/react-native-router-flux#412]
Can you please take a look
 http://stackoverflow.com/questions/36156876/how-to-use-nested-routing-with-react-native

**Comment by Froelund** [comment]
Which version of react-native-router-flux are you using?

**Comment by texas697** [comment]
"react-native-router-flux": "^2.3.1"

**Comment by aksonov** [comment]
v2 is not supported now, sorry. Check v3.
