### ISSUE TITLE
Programmatically unmount previous components?

### ISSUE THREAD

**Issue by rlau1115** [aksonov/react-native-router-flux#415]
Is there any way to remove / unmount components from the navigation stack? 

I'm using Redux in my app, and there are several instances where I modify or remove certain objects in my state after navigating to a new component. However, the app crashes because components that are no longer being displayed are still depending on the non-existent state objects.

I've tried having multiple calls of Actions.pop() (one for each view that I'm trying to remove), but it isn't working. Any insight?

**Comment by rlau1115** [comment]
Actually, Actions.pop() does do the intended job of unmounting a component, but it doesn't happen immediately. I was able to test this by adding a timeout.

```
/*** This works ***/
export function handleLeaveGroup(groupInfoJson) {
  return function(dispatch) {
    // Remove two group views from stack
    RouterActions.pop();
    RouterActions.pop();

    // // route to inbox scene
    RouterActions.inbox();

    // Dispatch action to reducer
    setTimeout(() => {
      dispatch(leaveGroup(groupInfoJson));  
    }, 500)
  }
}
```

```
/*** This doesn't work ***/
export function handleLeaveGroup(groupInfoJson) {
  return function(dispatch) {
    // Remove two group views from stack
    RouterActions.pop();
    RouterActions.pop();

    // // route to inbox scene
    RouterActions.inbox();

    // Dispatch action to reducer
    dispatch(leaveGroup(groupInfoJson));  
  }
}
```

The timeout isn't ideal, so is there anyway to force an immediate unmount?

**Comment by aksonov** [comment]
v3 uses 'async' Navigator API, so it is not the problem, but the feature :)

**Comment by dabit1** [comment]
Hi! Somebody knows how can I solve this problem? If I have a list and I go to any item, and I press back button and quickly I go to another item the item component is not unmounted thus the component preserves data from last item. This is because the component is not unmounted immediately.

Many thanks
