### ISSUE TITLE
NavBar Title

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#417]
Hi, after update to 3.2.3, i'm having trouble displaying the navbar title. My initial scene is a tab view. But the title is not showing. Inside the view is a button that will push another scene, In this scene I can see the title. I already tried hiding the root scene navbar. It will make the tab view's nav title visible but will make the pushed scene's navbar invisible. Any solutions?

**Comment by philipshurpik** [comment]
I also faced with this problem and created pull request to fix it

**Comment by philipshurpik** [comment]
as I understand now it's fixed, please check

**Comment by aksonov** [comment]
Closing it for now, please report if it is not fixed in latest 3.2.4
