### ISSUE TITLE
Pop back to specific scene

### ISSUE THREAD

**Issue by cgreening** [aksonov/react-native-router-flux#419]
Anyone know how to pop back several scenes to a particular scene?

e.g.

```
<Scene key="root" hideNavBar={true}>
    <Scene key="Test1"/>
    <Scene key="Test2"/>
    <Scene key="Test3"/>
    <Scene key="Test4"/>
</Scene>
```

If I'm on `Test4` how can I pop back to `Test2`?

**Comment by aksonov** [comment]
It is not supported within v3 right now, PR will be welcome.

**Comment by aksonov** [comment]
@cgreening Have you tried Actions.pop();Actions.pop() ?

**Comment by cgreening** [comment]
We've got a workaround with a custom reducer where we modify the state to
get it back to the scene we want.

Will try and turn that into a pr.

This does look pretty horrible though as every scene is animated off in
rapid succession. I believe this might be an issue with the underlying
navigation component. I think it needs a bit more work to bring it into
line with the standard native iOS uinavigationcontroller.

**Comment by Mbompr** [comment]
Hi @cgreening apparently you did not have time to turn it into a PR. By any chance, could share with us your custom reducer, I am facing the same problem.

**Comment by cgreening** [comment]
customRouterReducer.js:

```js
import {Reducer} from 'react-native-router-flux';

const reducerCreate = params=>{
    const defaultReducer = Reducer(params);
    return (state, action)=>{
        if(action.type == 'BODGE') {
          if(state.children.length > 1) {
            state = Object.assign({}, state, {index: 0, children : state.children.slice(0,1)});
           }
        } else {
          state = defaultReducer(state, action);
        }
        return state;
    };
};

export default  reducerCreate;
```

And then in your setup do:

```js

import customRouterReducer from './customRouterReducer'
import {Actions, Scene, Modal, Router} from 'react-native-router-flux'

const ConnectedRouter = connect()(Router);

<ConnectedRouter scenes={scenes} createReducer={customRouterReducer}/>
```

Then send actions with the type "BODGE" to pop back to the first scene.

**Comment by esutton** [comment]
@cgreening Thank you!

Can you please give example on how to send action with type "BODGE" ?

**Comment by cgreening** [comment]
In a connected component you should be able to do:

```js
this.props.dispatch({type: 'BODGE'});
```

**Comment by sym900728** [comment]
I write in the my component with the 

this.props.dispatch({type: 'BODGE'})

It's not useable.

**Comment by benjamincarp** [comment]
Actions.js mentions popTo in several places, which I assume would do what we're looking for here but I didn't have any luck trying to actually use it and I find the layout of this code pretty hard to read so I didn't dig in too far.  

In my case, I need to pop to the root level so I could just use a replace action for now. I would prefer for it to be a pop to the correct level though in case we ever add a level below the current root.

**Comment by JosephDev** [comment]
same here. `Actions.ROUTE_NAME({type: ActionConst.RESET});` occur errors blow. 

<img width="487" alt="screen shot 2016-07-21 at 8 48 34 am" src="https://cloud.githubusercontent.com/assets/7818008/17031063/40c6ebfe-4f27-11e6-8b53-0c91a2e9cc23.png">

I use `ActionConst.BACK` instead. 

Please mention if I use it as wrong way. thanks,

**Comment by MattyK14** [comment]
+1

**Comment by highbass** [comment]
I get the exact same error as @JosephDev when trying to use POP_TO.

**Comment by redwind** [comment]
@cgreening: thanks for your hack
@sym900728 : if this still help for you, it work for me by call 
`Actions.callback({ type: 'BODGE' })`
