### ISSUE TITLE
Routes inside of a tab container?

### ISSUE THREAD

**Issue by crysfel** [aksonov/react-native-router-flux#42]
Is there a way to set routes inside of the tab container? I have a list inside of a tab, what I want is to show another view when the user taps on an item on the list. I tried this:

This is the index file:
           <Router>
                    <Route name="songview" component={SongView} />
                    
                    <Route name="tabbar" >
                        <Container component={Tabs.Container}>
                            <Route name="songs" component={SongRoutes} title="Songs" icon={Tabs.Icon} image={require('./icons/quaver11.png')} />
                            ...
                        </Container>
                    </Route>
                </Router>

And inside the ```SongRoutes``` component I have this:

        <View style={styles.container}>

                <Router>
                    <Schema name="default" sceneConfig={Animations.FlatFloatFromRight} />

                    <Route name="songlist" component={SongList} initial={true} />
                    <Route name="songview" component={SongView}  />
                </Router>

            </View>  

I'm getting the list of elements displayed correctly, here's the callback for when the user taps on the list.

    _onPressButton(){
        console.log(Actions.songview);
        Actions.songview({data:'This is some data!'});
    }

But when taping on an item I'm getting this error: 

    [tid:com.facebook.React.JavaScript] 'No route is defined for name: songview'

Am I doing something wrong? Any help would be appreciate.

**Comment by aksonov** [comment]
Yes, it is known issue - ‘Container’ support is experimental for now.
I’m going to fix it soon with possibility of inner Router tag, but for Redux architecture (react-native-redux-router component), because Alt is not so powerful and clear.

**Comment by crysfel** [comment]
I see, that's means I can't do it for now. I would look for another way to it then. Thanks.

**Comment by aksonov** [comment]
Check #44

**Comment by aksonov** [comment]
Should be fixed with new version

**Comment by aksonov** [comment]
As described here: https://github.com/exponentjs/ex-navigator/issues/57
you should hide root navigator (as shown in demo) and push from scene with own navigator (you may use wrapRouter attribute for it)
