### ISSUE TITLE
Example project tabbar title and rightButton now showing up

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#421]
I just cloned latest master branch at commit #d8ddf9d
I tried running this in Xcode iPhone 5 simulator.

Expected behaviour :
- Can see title `Tab #1` and `Tab #2` etc in each tabbar
- See `Right` text on the right side of navbar and clicking on it will bring alert popup `Right button`
Actual behaviour:
- Cannot see any title in any of the tabbar. 
- Cannot see right button in any of the tabbar.

**Comment by aksonov** [comment]
Looks like PR #406 brake things, i've partially reverted it (removed from Example), please check latest version (3.2.4)

**Comment by timzaak** [comment]
3.2.13 does can also see no title
