### ISSUE TITLE
How to forbid swipe back gesture in 3.x?

### ISSUE THREAD

**Issue by songyouwei** [aksonov/react-native-router-flux#422]
I'm using react-native-viewpager component in a scene, and i need to forbid swipe back gesture in this scene.
I'm using react-native-router-flux 3.1.5.

**Comment by songyouwei** [comment]
> No old navigator.sceneConfig support (instead the component uses React Native NavigationAnimatedView for better transitions)
How to use NavigationAnimatedView to forbid swipe back gesture?

**Comment by aksonov** [comment]
Please search for existing issues before creation of new one! Duplicate of #359
