### ISSUE TITLE
Actions.pop() broken in v3.2.4 

### ISSUE THREAD

**Issue by aguenther** [aksonov/react-native-router-flux#428]
Actions.pop() seems to no longer send the user back to the last scene, instead it a) selects the scene which is defined before the currently selected and b) deletes the last scene in the list. When the first element is reached, the app crashes with "undefined is not an object (evaluating 'selected.hasOwnProperty')"

My main component:
```
export default class ExampleApp extends Component {

  render() {
    var sceneDefaults={
      hideNavBar: true
    };
    return (
      <Router>
        <Scene key="tabbar" initial={true} tabs={true} default="home" style={style.tabBar} >
          <Scene
            {...sceneDefaults}
            key="chat"
            title="Chat"
            icon={TabBarIcon}
            component={ChatScreen}
            inactiveImage={require('../image/chat.png')}
            activeImage={require('../image/active_chat.png')}
          />
          <Scene
            {...sceneDefaults}
            key="favorites"
            title="Favoriten"
            icon={TabBarIcon}
            component={FavoriteScreen}
            inactiveImage={require('../image/hotel.png')}
            activeImage={require('../image/active_hotel.png')}
          />
          <Scene
            {...sceneDefaults}
            key="home"
            title="Home"
            initial={true}
            icon={TabBarIcon}

            component={HomeScreen}
            inactiveImage={require('../image/home.png')}
            activeImage={require('../image/active_home.png')}
          />
          <Scene
            {...sceneDefaults}
            key="feedback"
            title="Feedback"
            inactiveImage={require('../image/book.png')}
            activeImage={require('../image/active_book.png')}
            icon={TabBarIcon}
            component={FeedbackScreen}
          />
          <Scene
            {...sceneDefaults}
            key="info"
            title="Info"
            icon={TabBarIcon}
            component={InfoScreen}
            inactiveImage={require('../image/info.png')}
            activeImage={require('../image/active_info.png')}
          />
        </Scene>
      </Router>
    );
  }
}
```

If "Home" selected, calling Actions.pop() causes the selection to pass to "Favorites", "Info" disappears. Next call moves the selection to "Chat", and removes "Feedback". The third call then causes the aforementioned javascript error.

**Comment by aksonov** [comment]
" selects the scene which is defined before the currently selected and b) deletes the last scene in the list."  - is it not definition of pop? Please modify Example project accordingly to show the issue. It is absolutely useless to give me some scenes config from your app.

**Comment by aguenther** [comment]
Well, from your documentation I assumed pop goes back through the history, and for 2.x it indeed worked like that. Aka, if you start at Home, then go to Chat, then to Feedback, and then call pop, you are at Chat again, and after another call you are at Home. Instead, it goes back through the scenes' definition,  from bottom to top.

While I understand that it makes sense that something called "Actions.pop" pops actions off the list of defined actions, it would be nice if you mentioned this change under "breaking changes", along with instructions how to get the "back in history" behavior in the new version.

**Comment by aksonov** [comment]
Hm... Are you using pop for tabbar (tabs=true)?

**Comment by aguenther** [comment]
Yes, I do. It is in the example, too. Do I have to do it differently in that case?

**Comment by aksonov** [comment]
And what did you expect from pop for TabBar? Where is it in example? pop() for tab bar doesn't make any sense. I will add assert call to throw exception in this case.

**Comment by Quirksmode** [comment]
Sorry to bring back an old thread, but I have just come across this same issue. Is there no way to go back to a different tab? I have an app which has search as one of the tabs and I need to add a back button, it's part of the design and in this instance makes a lot of sense
