### ISSUE TITLE
It doesn't work with react-native@0.16.0

### ISSUE THREAD

**Issue by shiverysea** [aksonov/react-native-router-flux#43]
causes error like this:
[BABEL] {$PRJ_DIR}/node_modules/alt/lib/index.js: Unknown option: {$PRJ_DIR}/node_modules/alt/.babelrc.stage

**Comment by idibidiart** [comment]
Babel 6 was introduced in 0.16 and broke several things.

**Comment by plougsgaard** [comment]
Try deleting all `.babelrc` files from `node_modules` except for the packager's config.

For example:

`find node_modules -type f -name '.babelrc' | grep -v 'node_modules/react-native/packager/react-packager/.babelrc' | xargs rm`

**Comment by shiverysea** [comment]
That works for me! Thanks! @plougsgaard

**Comment by aksonov** [comment]
Looks like no other ways except this for now, thanks @plougsgaard

**Comment by aksonov** [comment]
https://github.com/facebook/react-native/issues/4062

**Comment by aksonov** [comment]
New version doesn't use alt, so issue should be solved, please check
