### ISSUE TITLE
Weird slide animation

### ISSUE THREAD

**Issue by RWOverdijk** [aksonov/react-native-router-flux#430]
When opening a new view (by calling the action) and swiping right to navigate back, the animation seems a bit off. It's seems not fluid.

Is this a known something?

**Comment by aksonov** [comment]
Please check React Native UIExplorer example, ExperimentalNavigation section and compare animation. This component is just wrapper around it, it doesn't provide 'own' animation.

**Comment by RWOverdijk** [comment]
@aksonov Will do.
