### ISSUE TITLE
Inner routes in Tabs broken since 3.2.2

### ISSUE THREAD

**Issue by Mokto** [aksonov/react-native-router-flux#431]
Hi,

When I upgrade to 3.2.2 -> 3.2.5, my tabs routes are broken. 

```javascript
<Scene key="root" tabs={true}>
    <Scene key="loading" component={Loading} />
    <Scene key="login" component={Login} />
    <Scene key="loggedIn" component={Layout}>
        <Scene key="main">
            <Scene key="menu" type="replace">
                <Scene key="category" component={Menu} />
            </Scene>
            <Scene key="settings" type="replace" component={Settings} />
        </Scene>
     </Scene>
</Scene>
```

Replace routes are working fine, but when I do Actions.menu(params), the custom Reducer receives proper actions, but routes are not visually pushed.

It is working fine in 3.2.1.

Please let me know if you need anything else.
Thanks for your work and keep going ! :)

**Comment by aksonov** [comment]
Why tab items are replace? Please try to reproduce bug on example project.

Pavel.

**Comment by Mokto** [comment]
Okey doing it now.

**Comment by Mokto** [comment]
Ok I can't reproduce in example but I went into your code and 

`if (state.children[state.index].sceneKey == action.key && !props.clone){` is triggered even if I send different parameters to the same route.

Looking into it.

**Comment by Mokto** [comment]
Closing as it was related to https://github.com/aksonov/react-native-router-flux/pull/432
