### ISSUE TITLE
Is there a way to force truncating the text in the nav bar? 

### ISSUE THREAD

**Issue by rlau1115** [aksonov/react-native-router-flux#438]
I achieved a temporary fix by changing the source code for NavBar, adding a "numberOfLines={1}" prop, along with passing in some styling into the root scene. Is there a more elegant/permanent way to do this without changing the underlying source code (since this will get erased every time I update)? 

```
/* NavBar.js */
...
_renderTitle(childState: NavigationState, index:number) {
        return (
            <Animated.Text
                key={childState.key}
                numberOfLines={1}

```

**Comment by aksonov** [comment]
We could make it configurable option, please send PR

**Comment by rlau1115** [comment]
Will look into it, thanks for the quick response :)
