### ISSUE TITLE
Beta testers for 1.0 release?

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#44]
Hi guys,

I'm going to release 1.0 version which will not depend from any flux implementation and support inner Router tag to build tab bars with nested own navigators, but i need help - testers to give me feedback.

**Comment by cnjsstong** [comment]
Here! What should I do?

**Comment by aksonov** [comment]
Will publish separate branch soon, thanks!

**Comment by aksonov** [comment]
@cnjsstong Please check branch 1.0beta and try to run Example.

**Comment by cnjsstong** [comment]
Already running. Any specific points that need attention?

**Comment by aksonov** [comment]
No. Any feedback is appreciated. 

Pavel.

**Comment by cnjsstong** [comment]
One problem first...

It seems that you have not updated `package.json` for Example. It is still using 0.3.x version of react-native-router-flux .

**Comment by aksonov** [comment]
@cnjsstong thanks, version is published.
