### ISSUE TITLE
Question: Passing parameters with the navBar onRight

### ISSUE THREAD

**Issue by AlexDM0** [aksonov/react-native-router-flux#440]
Hi, 
I'm using the text "edit" in the top right of the navBar to go to a new page using the onRight method:
```
onRight={() => Actions.roomEdit()}
```
However, what should be edited is depending on the previous page. I could of course set globals to pass this information along or add something in the reducer to propagate data from the last page to the next but these all seem like dirty solutions. Is there a better way that I'm overlooking? 

Inside a scene I can add arguments to the Action, but since the navbar is defined on the router level I don't have the arguments I want to pass yet...

Regards

**Comment by aksonov** [comment]
navigationState should be bind to onRight method, have you tried check param passed to onRight??

**Comment by AlexDM0** [comment]
Cant believe I missed that. Sorry and thanks!
