### ISSUE TITLE
Nav image flicker between scene transitions.

### ISSUE THREAD

**Issue by willmcneilly** [aksonov/react-native-router-flux#442]
Thanks for all the hard work, this is the best RN router I've come across.

I have a use-case where I need to add an image to the navbar. So I've made a copy of the default navbar component and edited the structure slightly to add the image.

Unfortunately there's a noticeable flicker in the image between scene transitions, caused by the navbar mounting on each transition. This happens both when I set the custom navbar on the root scene, and when I call it from the renderNavigationBar static method on each of the scene components.

Is there a better way of handling this or am I working against the grain?

Possibly a way to specify a custom nav that is used in defaultRenderer and mounted once?

Thanks.

**Comment by aksonov** [comment]
It is all about React Native programming, i guess. Check "<" back image, is it flickering? If no then something is wrong with your code....

**Comment by willmcneilly** [comment]
Thanks for the reply.

Yes, it flickers too.

I've copied your navbar example and added it to the root scene in the navBar prop. It seems anytime I transition to a new scene, it flickers as the navBar component is mounted.

**Comment by aksonov** [comment]
@willmcneilly Does UIExplorer project (v0.22, NavigationExperimental topic) have flickering?

**Comment by morgondag** [comment]
Im having the same flickering problem.
There seams to be a 1 pixel wide white border when navigation between views.
I recorded an example application with the problem here:
https://www.dropbox.com/s/uqs1ngy37j2ciwq/recording.mov?dl=1
If you scrub trough the video its quite clear there is a white line appearing.

Here is a picture of the visual artifact:
![image](https://cloud.githubusercontent.com/assets/4340802/14937489/03bc88e4-0f09-11e6-8975-d9a0fa733bb6.png)
_The new view have a white line that flickers as the new view animates into place._

**Comment by morgondag** [comment]
when swiping back the old view have this white line applied to the top of the view:
see the top left corner here:
![photo 30-04-16 19 29 07 1](https://cloud.githubusercontent.com/assets/4340802/14937521/1c12a6d4-0f0a-11e6-86c9-1679e770b371.png)

**Comment by cridenour** [comment]
We're still not sure if this is anything in this library or the upstream NavigationExperimental. Has anyone been able to reproduce in the UIExplorer shipped with RN?

**Comment by rturk** [comment]
@willmcneilly can you test this using the latest stable RN & RNRF? RN0.26.2 & RNRF 3.26.X?

**Comment by morgondag** [comment]
Can confirm that there is still a white line on transitions with these versions:

```
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-router-flux": "3.26.0",
```

**Comment by aksonov** [comment]
Sorry, but it is out of scope for this component, if UIExplorer RN example flickers too, raise issue for RN, not here.
