### ISSUE TITLE
NavigationBar has white borderBottom

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#444]
### Version
    "react-native": "^0.22.0",
    "react-native-router-flux": "aksonov/react-native-router-flux#dcc7558",

### Expected behaviour
No white border between navigationBar and content

### Actual behaviour
White border between navigationBar and content

### Steps to reproduce

1. Make navigationBar backgroundColor red
2. Make content dark
3. Notice there is white border between navigationBar and content.

### Temporarily fix
set navigationBarStyle to have borderBottomWidth: 0,

**Comment by aksonov** [comment]
Use your fix to remove border, it is not a bug, but behaviour of built-in NavBar. You may pass your own NavBar if you want.
