### ISSUE TITLE
Change Statusbar Color?

### ISSUE THREAD

**Issue by MovingGifts** [aksonov/react-native-router-flux#445]
I can't seem to find a way to change the very top status bar (iphone) to be dark background with white icons, since the navbar I am using is dark. Any idea how to get it to work? I looked into react native's documentation on Status Bar but can't seem to understand what is needed, or if there is a way to do it with this plugin. Any ideas?

**Comment by jeroenbourgois** [comment]
AFIKT it cannot be done on iOS. The docs are quite clear about it.

**Comment by MovingGifts** [comment]
@jeroenbourgois Hmmm.. I must have missed that, where specifically does it say it cannot be done in iOS. I am sure there has to be a way..

**Comment by lee-gray** [comment]
You can call StatusBar.setBarStyle('light-content', true); to change the status bar text to white. Remember to include StatusBar from react-native.

**Comment by MovingGifts** [comment]
@lee-gray Works great! Thanks man :)

**Comment by rochestb** [comment]
@lee-gray Thanks!
![rad-sunny-delight-d-ja8v9vQFdbCiQ](https://media2.giphy.com/media/ja8v9vQFdbCiQ/giphy.gif)

**Comment by hejiaji** [comment]
Fantastic!!

**Comment by lin493369** [comment]
Thanks!

**Comment by gungungun93** [comment]
you cannot use backgroundColor in StatusBar in IOS, it's only work in android. to fix that, you need to create View cover StatusBar and set backgroundColor in View instead. :)

**Comment by e2goon** [comment]
Use the method below if you need to. :)

```javascript
<Scene
  key="tabbar"
  tabs={true}
  onSelect={el => {
    if (typeof Actions !== 'object') return;
    const {
      sceneKey,
      statusBarStyle
    } = el.props
    if (statusBarStyle) {
      StatusBar.setBarStyle(statusBarStyle, true)
      Actions[sceneKey]()
    }
  }}>
  <Scene
    key="tab_1"
    title="home"
    component={Home}
    icon={TabIcon}
    statusBarStyle="light-content" />
.
.
.
```

**Comment by Saliheen** [comment]
Below code works for me


```
import {useEffect} from 'react';
import {StatusBar} from 'react-native';

const TranslucentStatusBar = ({isDarkSelected = false}) => {
  useEffect(() => {
    StatusBar.setBarStyle(isDarkSelected ? 'dark-content' : 'light-content');
  }, [isDarkSelected]);
  return (
    <>
      <StatusBar
        translucent={true}
        backgroundColor="transparent"
        animated={true}
      />
    </>
  );
};

export default TranslucentStatusBar;
```
