### ISSUE TITLE
renderBackButton does not take you back to previous route.

### ISSUE THREAD

**Issue by MovingGifts** [aksonov/react-native-router-flux#446]
Hello,

`<Scene key="root" renderBackButton={()=><BackButton/>} ...`

I had to customize the back button, since it is different dimensions and icon than the one provided. After following the documentation, I created a renderBackButton closure that returns the new back button, which shows up perfectly. However, when I click it, it does not take me back to the previous route. Any idea how to get it to go back to the previous route on click?

(Just for the record, backButtonImage works, in terms of swapping out the image and taking you back to the previous route, however, I am not able to add the width/height of the icon, and that is why I had to use renderBackButton, so I can add image dimensions)

Please let me know how to get this to work..

**Comment by mattfca** [comment]
did you add Actions.pop() to the onpress in <BackButton/> ?
