### ISSUE TITLE
NavBar covers part of the View

### ISSUE THREAD

**Issue by jeroenbourgois** [aksonov/react-native-router-flux#447]
### Version
- react-native-router-flux v3.2.6
- react-native v0.22.2

### Expected behaviour
The content of a view should be below the NavBar

### Actual behaviour
The content is partly hidden by the NavBar if the container is full enough.

### Steps to reproduce

1. Open `Example` project
2. On the `<Scene key="root">` remove the `hideNavBar` property
3. Inject a lot of text in the `home` view
4. Navigate to the home view, see that the text is behind the navbar

* for the example the first few textlines were numbers, starting from 1. That way it is easy to see that 1 and 2 are below the navbar
![Screenshot](https://www.dropbox.com/s/hajr5g0nz8hynj6/Screenshot%202016-04-01%2013.03.55.png?dl=1)

I am willing to investigate myself but I have no idea where to start

**Comment by aksonov** [comment]
It is not bug, it is known feature of React Native as well as native iOS nav bar (so semi-transparent navbars could be shown nicely). You need to adjust your padding by yourself.

https://github.com/facebook/react-native/issues/4264

**Comment by jeroenbourgois** [comment]
Perfect, thanks!
