### ISSUE TITLE
renderRightButton and renderLeftButton are not working

### ISSUE THREAD

**Issue by atn4z7** [aksonov/react-native-router-flux#449]
### Version
- react-native-router-flux v3.2.6
- react-native v0.22

### Expected behaviour
renderRightButton and renderLeftButton should be working for scenes that are not tabs

### Actual behaviour
renderRightButton and renderLeftButton are only working for scenes that are tabs

### Steps to reproduce

1. add renderRightButton={()=><Right/>} to loginModal scene in Example.js
```
  <Scene key="login" direction="vertical"  >
      <Scene key="loginModal" component={Login} title="Login" renderRightButton={()=><Right/>}/>
      <Scene key="loginModal2" hideNavBar={true} component={Login2} title="Login2" panHandlers={null} duration={1}/>
  </Scene>
```
2. run the example 
3. right button is not rendered

**Comment by atn4z7** [comment]
turned out I just need to specify it at the parent scene like this
```
      <Scene key="login" direction="vertical"
                  renderLeftButton={ButtonRenderer.back}>
                  <Scene key="loginModal" component={Login} schema="modal" title="Login"
                    navigationBarStyle={styles.navBar}/>
```

**Comment by SudoPlz** [comment]
I've got the exact same problem in 3.2.7 I just slightly modified the example to add a right button in the login and register screen of the example but the button is not rendered on top.. In fact during the transition I can see the button of the login screen below the main bar.

**Comment by sneerin** [comment]
what's ButtonRenderer.back?
