### ISSUE TITLE
component property not set when using Router in Clojurescript through Reagent

### ISSUE THREAD

**Issue by stepugnetti** [aksonov/react-native-router-flux#451]
### Version
- react-native-router-flux: cloned from master on Mar 30th, 12:00 CET.
- react-native : v0.22.0

I had to bundle it with WebPack 2.1.0-beta.0 through Babel 6.6.5 with presets es2015 and stage-0.

### Issue
I'm using  react-native-router-flux in Clojurescript (1.7.170), with a React wrapper called Reagent (0.5.1). My app crashes before mounting the Router component with an error message I cannot interpret: `component property is not set for key=root`. It looks like the `props` argument is not initialized properly. I added a `ref=myfun` property to the component to be able to access the actual object and to perform some inspection, but the `myfun` function never gets executed.

Any hints about what's going on?

Thanks!

**Comment by aksonov** [comment]
Are you seriously think that somebody could help you without even snippet of code? Sorry, please fill all steps or i will close the issue.

**Comment by aligenc** [comment]
it is my problem too. i am getting same error as _component property is not set for key=root_

`
import React, { Component, Image } from 'react';
import {  AppRegistry} from 'react-native';
import { Router, Scene } from 'react-native-router-flux';

export default class MyApp extends Component {
  render() {
    return (
      <Router>
        <Scene key="root">          
          <Scene hideNavBar={true} key="pageOne" component={PageOne} title="Home" initial={true} />
          <Scene  hideNavBar={false} key="pageTwo" component={PageTwo} title="Search Results" />
        </Scene>
      </Router>
    )
  }
}`

**Comment by xahon** [comment]
I have same error too. Here is my snippet of code


```
import React from 'react'
import { Scene, Actions, Router } from 'react-native-router-flux' //eslint-disable-line

import SignupScreen from './src/screens/signup' //eslint-disable-line
import LoginScreen from './src/screens/login' //eslint-disable-line

export default class App extends React.Component {
  render () {
    return (
      <Router>
        <Scene key='root'>
          <Scene key='authenticate' component={ SignupScreen } initial={ true } hideNavBar />
          <Scene key='login' component={ LoginScreen } hideNavBar />
        </Scene>
      </Router>
    )
  }
}
```

**Comment by xahon** [comment]
This issue was resolved by adding `default` keyword in `SignupScreen` and `LoginScreen`  
`export default class SignupScreen extends React.Component`  
No components needed for `root` `Scene`!  
Issue should be closed
