### ISSUE TITLE
sceneStyle ignored.

### ISSUE THREAD

**Issue by FrankSalad** [aksonov/react-native-router-flux#452]
### Version
- react-native-router-flux v3.2.6 
- react-native v0.22.2

Routes defined like this
```
      <Router>
        <Scene key="root" sceneStyle={{paddingTop: 50}}>
          <Scene key="one" component={One} />
          <Scene key="other"
                 component={Other}/>
        </Scene>
      </Router>
```
Also tried
```
      <Router sceneStyle={{paddingTop: 50}}>
        <Scene key="root"2>
          <Scene key="one" component={One} />
          <Scene key="other"
                 component={Other}/>
        </Scene>
      </Router>
```
### Expected behaviour
Padding is added to the top of both scenes.

### Actual behaviour
No padding is added to the top of either scene.

**Comment by jeroenbourgois** [comment]
I am not so sure `sceneStyle` is still used in the `3.0` Version? @aksonov

**Comment by aksonov** [comment]
It is not used in v3. You may pass any attribute but should use it inside your component accordingly. So 'style' may work.

**Comment by domchristie** [comment]
> You may pass any attribute but should use it inside your component accordingly

I feel it’d be good if `sceneStyle` was brought back. Wrapping every scene component in `<View style={props.style}>` isn’t ideal.

I could look into creating a PR if you’re interested?

**Comment by aksonov** [comment]
Yes, feel free to create PR.

**Comment by domchristie** [comment]
I had a look into this and unfortunately it’s not as easy as I had hoped.

`DefaultRenderer` can either render a `navigationState` component or an `NavigationAnimatedView`. In the case of rendering a `navigationState` component there’s no way to apply styles directly without wrapping it in another component (perhaps a `NavigationCard`?)

**Comment by aksonov** [comment]
Should be done for 3.2.7

**Comment by mmazzarolo** [comment]
Hello there, sorry but I don't get it, does `sceneStyle` work now?  
The example of the first post is still not working for me  on 3.2.7.

**Comment by aksonov** [comment]
Check latest master

**Comment by amitbobade2007** [comment]
Not working for me also in 3.2.8.

**Comment by aksonov** [comment]
@domchristie Does it work for you?

**Comment by domchristie** [comment]
@aksonov Yes, it appears to work for me:

https://github.com/domchristie/react-native-router-flux/commit/4644c59157b4ee374f2f8565aff66c9c6cc2ae9f#diff-8e927151f271a81709e2e70c2953591bL57

Results in:

![simulator screen shot 14 apr 2016 10 48 52](https://cloud.githubusercontent.com/assets/111734/14524056/80dca2f6-022e-11e6-9557-ec4a096ad376.png)
