### ISSUE TITLE
How to move scene in from left?

### ISSUE THREAD

**Issue by FrankSalad** [aksonov/react-native-router-flux#453]
react-native-router-flux@3.2.6 

Removed support for pushing things from left side?

**Comment by aksonov** [comment]
Could you clarify?

**Comment by MovingGifts** [comment]
@FrankSalad Do you mean having the new scene slide in form the left side to the right, instead from the right to the left?

@aksonov If so I have the same question(s):

1. For scene transitions ex. SlideDown, SlideUp, SlideFromRight, SlideFromLeft, how can those 4 be applied on the next/prev scene? I think by default there is only 2 that work that I've seen in the demo.
2. For other transitions, like FlipRight/FlipLeft, how can those be applied on the next/prev scene? Is it possible?

**Comment by FrankSalad** [comment]
@aksonov like Tinder - there's a center card (swiper), right card (messages) and left card (settings). When the left nav button is pressed the whole interface slides right to place the left card in the center.

**Comment by aksonov** [comment]
Maybe we should wait for RN0.25 to allow custom animations. Closing it for now.

**Comment by wrousseau** [comment]
@aksonov Is there any news regarding this ?

**Comment by cridenour** [comment]
Some work was started in #868 which has been published, looking for help with additional animations.
