### ISSUE TITLE
use pop action in initial scene will show error

### ISSUE THREAD

**Issue by winsontam** [aksonov/react-native-router-flux#455]
### Version
- react-native-router-flux v3.2.3
- react-native v0.22.2

### Expected behaviour
should be ignored without error

### Actual behaviour
hang with error.

NavBar.js (selected is undefined)
        while (selected.hasOwnProperty("children")) {

**Comment by aksonov** [comment]
Ignoring of 'wrong' actions is not good way. Why can't you disable pop action from initial scene?

**Comment by winsontam** [comment]
how about "assert" something for better debug?

**Comment by aksonov** [comment]
Latest version ignores it now.
