### ISSUE TITLE
Switch demo

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#458]
Hi, I don't see any demo for switch in the example app. Can you add sample?

**Comment by aksonov** [comment]
It is given within README.

**Comment by ajoshdee** [comment]
Your README is too abstract to follow. And it's not in the sample code either.

**Comment by aksonov** [comment]
Sorry, i can't help. You may add PR. I don't want to introduce redux or other dependency for Demo without strong need.

**Comment by ajoshdee** [comment]
Can you at least tell me how to use it without the redux?

**Comment by ajoshdee** [comment]
Like where does the selector props gets its props? I don't know where to pass the data.

**Comment by aksonov** [comment]
select gets props from the its component props.

**Comment by ajoshdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7309782/14243879/969a5aa8-fa8a-11e5-9fd5-df2503b46067.png)
How do i pass props.userInfo?

**Comment by aksonov** [comment]
Sorry, i don't know how to do it without Redux. You may write copy Switch to your component and pass userInfo somehow there.
