### ISSUE TITLE
How to change back button ? Any examples ?

### ISSUE THREAD

**Issue by melihmucuk** [aksonov/react-native-router-flux#460]
I can't change default back button on iOS. Whats the problem ? I tried `renderBackButton`, `renderLeftButton` and `backButtonImage` props, but didn't change.

```
<Scene
  key="entry"
  component={Entry}
  title="Title"
  titleStyle={styles.title}
  navigationBarStyle={styles.navBar}
  renderLeftButton={() => this._backButton.bind(this)}
  renderBackButton={() => this._backButton.bind(this)}
  backButtonImage={backButton}/>
```

`var backButton = (<Image source={this.state.backIcon} style={{width: 30, height: 30}} />);`

```
_backButton(){
    return (
      <View style={{paddingHorizontal: 5, paddingVertical: 7}}>
        <TouchableOpacity
          style={{padding: 10}}
          onPress={() => Actions.pop()}>
          <Icon
            name="arrow-left"
            size={20}
            color="#e67e22" />
        </TouchableOpacity>
      </View>);
  }
```

### Version
```
"dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.22.2",
    "react-native-router-flux": "^3.2.6",
    "react-native-vector-icons": "^1.3.3"
  }
```

**Comment by SudoPlz** [comment]
I could not get it to work either, till then I just go and tamper the `back_chevron.png` img in the `node_modules/react-native-router-flux/src` directory.

**Comment by lee-gray** [comment]
@melihmucuk try adding it to your root Scene, I don't know why but it worked for me.

<Scene key="root" backButtonImage={require('../images/back_chevron.png')}>
    <Scene key="foo" component={fooView} title="Foo" />
    <Scene key="bar" component={barView} title="Bar" />
</Scene>

**Comment by AlexDM0** [comment]
I just used the renderBackButton method:

renderBackButton={backButtonFunction}

with

```js
let backButtonFunction = function() {
  if (this.props.navigationState.index === 0) {
    return null;
  }
  return (
      <TouchableOpacity style={[{
        width: 100,
        height: 37,
        position: 'absolute',
        bottom: 4,
        left: 2,
        padding: 8,
        justifyContent:'center',
    }]} onPress={Actions.pop}>
        <View style={{flexDirection:'row', alignItems:'center'}}>
          <Icon name="ios-arrow-back" size={25} color={'#ffffff'} style={{marginTop:2,paddingRight:6}} />
          <Text style={styles.topBarLeft}>Back</Text>
        </View>
      </TouchableOpacity>
  );
};
```

Works like a charm.

**Comment by SudoPlz** [comment]
Will try that, thanks for reporting this brother.

**Comment by AlexDM0** [comment]
Keep in mind that you dont use an arrow function or bind it. It depends on the this of the environment where it is being executed. I reverse engineered it from the method implemented in the router source and hardcoded the styling into it.

Cheers

**Comment by Lida** [comment]
I think there is a bug with the current implementation that only use the renderLeft/Right/BackButton props set on the root scene. They are only bound on NavBar's componentWillMount.

I have a [local commit](https://github.com/livecirrus/react-native-router-flux/commit/d16a003f707ee931e5dd1b1a1454cc83919135a9) that fixes this in my fork.

**Comment by SudoPlz** [comment]
Can you open a pull request?

**Comment by Paul-Todd** [comment]
I second that - this fixes an issue where the first scene (master scene) has a left button for settings. The remaining scenes (detail scenes) have the standard behaviour.

**Comment by StinoDes** [comment]
Hey @AlexDM0 ,
Where did you define that function?
I can't seem to get it to work in my project.

**Comment by AlexDM0** [comment]
I defined it in my router file but it shouldn't matter where you define is since the scope will be where it is executed. In fact that is the only reason it works. Did you put it in the scene props?

**Comment by StinoDes** [comment]
Thanks for the quick response!
I did include it in the scene's props, but it somehow keeps saying that `this.props.navigationState` is undefined.
I don't think anything's off with my props though:
`<Scene key="key" component={Component} renderBackButton={backButtonFunction}/>`
I've tried defining the function inside of the render-method, outside of the class, as method of the class. None seemed to solve it though.

**Comment by AlexDM0** [comment]
Which version are you using? You didn't use arrow functions or bind?

**Comment by StinoDes** [comment]
I have used neither of those.
react-native-router-flux: 3.2.12
react-native: 0.23.1

**Comment by AlexDM0** [comment]
I'm not sure if it could be related but so far router-flux requires 0.22. I'll check my exact router flux version when I get to work. 

If it doesn't work anymore I'll make a pull req to fix it and properly pass the props instead of hoping the this is alright.

**Comment by StinoDes** [comment]
Thanks, I'll try reverting back to an older version or RN.
Perhaps that'll fix it.

**Comment by AlexDM0** [comment]
I tested it with rn 0.22 and router-flux 3.22, everything seems to work fine.

**Comment by StinoDes** [comment]
I couldn't get it to work. Started using the NavigatorExperimental now, which seems to work fine

**Comment by AlexDM0** [comment]
My bad, it doesnt work with 3.22... I'll look into it

**Comment by StinoDes** [comment]
I might just be looking over something I did wrong. No worries.
Thanks for helping out though :)

**Comment by AlexDM0** [comment]
The navbar now correctly gets the tab it should and the this is not bound anymore causing the app to crash. I'll make a pull to fix this.

**Comment by alirezavalizade** [comment]
how to change color of Backbutton in react native router flux ? 
<img width="369" alt="screen shot 2016-08-06 at 2 19 20 am" src="https://cloud.githubusercontent.com/assets/14992757/17451470/5998d4d8-5b7c-11e6-8c60-bdf719aaf5e1.png">

**Comment by crismali** [comment]
@alirezavalizade I managed to change the color by passing `leftButtonIconStyle` to the scene with a `tintColor`.
```js
const styles = StyleSheet.create({
  backButton: {
    tintColor: 'white'
  }
})

// ...later

<Scene key='foo' component={Foo} leftButtonIconStyle={styles.backButton} />
```
