### ISSUE TITLE
Nested schenes no longer working?

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#462]
Do others also fail to use nested schenes? 

Today I updated to 3.2.4 but it seems I'm can no longer navigate to any of the nested ones.

### Version
- react-native-router-flux v3.2.4
- react-native v0.22.2

**Comment by aksonov** [comment]
Please give example (by modification of this component Example)

**Comment by SudoPlz** [comment]
Ok I close the issue until I create an example of this.

**Comment by aksonov** [comment]
Could it be duplicate of #370?

**Comment by SudoPlz** [comment]
I'll check it and let you know!
