### ISSUE TITLE
Add nav buttons (and handlers) from inside component

### ISSUE THREAD

**Issue by jwohlfert23** [aksonov/react-native-router-flux#463]
Let's say I have a component and I want the right button of the navbar to be "Manage" only if the logged in User is the admin of the page. How would I go about adding that button from within the component itself (as that's where I can check if the UserStore's current user is equal to the page's admin).

I've tried setting hideNavBar={true} and adding a react-native-navbar component there, but it's just really messy/buggy.  Is there a way to add the NavBar component in this repo in there? Or perhaps a different method I'm not thinking of to get the desired result?

**Comment by jwohlfert23** [comment]
I just

**Comment by luisfuertes** [comment]
Could yo fix it? I need have a component with and without back button.
