### ISSUE TITLE
Injected props are not passed to renderNavigationBar

### ISSUE THREAD

**Issue by Kerumen** [aksonov/react-native-router-flux#466]
### Version
- react-native-router-flux v3.2.6
- react-native v0.22

### Expected behaviour

When I connect a component with `redux-form` or `connect` from `react-redux` I want to have all the injected props in the `static renderNavigationBar(props)` method.

### Actual behaviour

Instead, the injected props are not passed to the `static renderNavigationBar(props)` method. Only the props from the Scene definition.

### Steps to reproduce

1. Connect a component with `redux-form`
2. `console.log` the props in `renderNavigationBar`

It's not working either if i connect the component with the HOC form, the decorator form or when I connect it directly in the routing.

**Comment by aksonov** [comment]
PR is welcome.

**Comment by Kerumen** [comment]
I tried a lot of things in my code and in RNRF's code but I didn't manage to get this working :(

**Comment by Elyx0** [comment]
Did something like https://github.com/aksonov/react-native-router-flux/issues/468 I didn't try to mess with the code though...

**Comment by Kerumen** [comment]
I finally also did something very similar.

**Comment by aksonov** [comment]
You may now use navBar property as well as rightButton/leftButton for each scene.
