### ISSUE TITLE
How to use type='reset'?

### ISSUE THREAD

**Issue by rgovindji** [aksonov/react-native-router-flux#467]
### Version
- react-native-router-flux v3.2.3
- react-native v0.22.0

In my application I have a page camera screen that push's an edit screen on top and then navigates to a news feed tab. When I go back to the camera tab the nav state is not cleared so I am still on the EditPhoto screen. 

Here's my scene information for the camera tab:
```
<Scene key="camera_tab" initial={true} iconLabel="ios-camera">
                <Scene key="CameraPage" type='reset' component={CameraPage} ref="camera"  hideTabBar={false} icon={TabIcon}
                       title="Camera" hideNavBar={true}>
                </Scene>
<Scene key="EditPhoto" component={EditPhoto} icon={TabIcon} hideNavBar={false}
                       hideTabBar={true} onLeft={() => Actions.pop()}  leftTitle="Back" title="Edit Photo">
                </Scene>
</Scene>
```
### Expected behaviour

Setting type='reset' on tab component should reset nav state when navigating back to the tab.

### Actual behaviour
Clicking on any tab results in an infinite loop. If I set type='reset' on the Scene 'camera_tab' the tab bar removes the all of the tabs except the camera_tab.

**Comment by rgovindji** [comment]
I ended up calling reset on the first child when I navigate away from the tab. It's a hack but I guess it worked.

**Comment by nitsujri** [comment]
@rgoldiez glad you got it working, would you be willing to help out make a PR against the documentation?

**Comment by rgoldiez** [comment]
I'll try to get a PR done, but here's how I use type='reset'.  I don't configure any scenes like the original poster.  My onPush and onPop functions simply track navbar info (for my custom navbar) and always return true.

```
                  <Router hideNavBar={true} header={NavBar} onPush={hbStore.pushRoute} onPop={hbStore.popRoute}>
                     <Route name="dashboard"    component={Dashboard} type='reset'/>
                     <Route name="robot"        component={RobotView} type='reset'/>
                     <Route name="cases"        component={Cases} type='reset' />
                     <Route name="caseview"     component={CaseView} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="caseviewrepl" component={CaseView} type='replace' sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="feedcomments" component={ChatterFeedComments} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="feedcommentsrepl" component={ChatterFeedComments} type='replace' sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="ideas"        component={Ideas} type='reset' />
                     <Route name="ideaview"     component={IdeaView} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="lost"         component={CenteredSpinner} />
                     <Route name="userprofile"  component={UserProfile} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="appsettings"  component={AppSettings} type='reset'/>
                     <Route name="myprofile"    component={UserProfile} type='reset'/>
                     <Route name="group"        component={ChatterGroup} type='reset'/>
                     <Route name="chatterfeed"  component={Chatter} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                     <Route name="chatterfeedrepl"  component={Chatter} type='replace' sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                  </Router>
```

**Comment by irisSchaffer** [comment]
@rgovindji, I have exactly the same problem and can't get it to work. May I ask what you mean by "resetting on the first child when navigating away"?
And could this issue be re-opened? I don't think it is solved yet...

**Comment by rgovindji** [comment]
@irisSchaffer I'm doing this  Actions.callback({ key: 'tabbar', type: 'reset'}); which resets all the child scenes. Just do the same on the root node for your tab bar.
```
<Scene key="tabbar" initial={true} tabs={true}>
<Scene key="camera_tab" initial={true} iconLabel="ios-camera">
                <Scene key="CameraPage" type='reset' component={CameraPage} ref="camera"  hideTabBar={false} icon={TabIcon}
                       title="Camera" hideNavBar={true}>
                </Scene>
<Scene key="EditPhoto" component={EditPhoto} icon={TabIcon} hideNavBar={false}
                       hideTabBar={true} onLeft={() => Actions.pop()}  leftTitle="Back" title="Edit Photo">
                </Scene>
</Scene>
</Scene>
```

**Comment by irisSchaffer** [comment]
Thanks for the quick reply!
Ok, for me, I need to push to a scene in a different tab and not back to the root. So what I tried to do was to call `Actions.myScene({type : 'reset' })`, but although the back button disappears on the new scene, I still get the last scene I was in when going back to the old tab... See [this stackoverflow question](http://stackoverflow.com/questions/38660223/react-native-router-flux-resetting-navigation-stack-in-tab) for details

**Comment by rgovindji** [comment]
Have you tried doing what I suggested and then pushing the scene you want onto the stack?

`
Actions.callback({ key: 'tabbar', type: 'reset'}); 
Actions.yourScene;
`

**Comment by irisSchaffer** [comment]
Yeah, that is what we are currently doing, with a `setTimeout`, but it seems super hacky too...
