### ISSUE TITLE
getState warning causes app to not render properly when opening the App

### ISSUE THREAD

**Issue by rturk** [aksonov/react-native-router-flux#472]
### Version
    "react-native-router-flux": "^3.2.6",
    "react-native": "^0.22.2",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-saga": "^0.9.5",
    "redux-storage": "^4.0.0",
    "redux-storage-decorator-filter": "^1.1.3",
 

### Expected behaviour

Normal transition flow like 2.x series

### Actual behaviour

Warning erros are produced during transitions

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

I'm getting setState warnings in the simulator as well on devices. This causes the UI to partially render `zoomed out`. Given that is zoomed out my educated assumption is this is somewhat related to Animation.

### Steps to reproduce

1. Use  "react-native-router-flux": "^3.2.6",
2. Fire a transition Actions.somenthing() as soon as the App loads
3. Enable/Disable chrome debug can increase/decrease the error

**Comment by rturk** [comment]
@sibeliusseraphini FYI

**Comment by aacotroneo** [comment]
As a temporal workaround.. adding a timeout seems to help ```                setTimeout(()=> { 
                    Actions.dashboard();
                },0);```

**Comment by rturk** [comment]
@aacotroneo well it is quite a hack.. Have you tested thoroughly and do you know why it works?

**Comment by rturk** [comment]
Can someone help/point to the potential source of this issue? I'll be happy to work in a PR.

**Comment by aacotroneo** [comment]
no sorry, just worked on my code and dropped the workaround. I'll trace it
later and tell you if I find something

**Comment by rturk** [comment]
I'm still getting this. As soon as the apps loads I load the app state from the disk, if the user is already logged I'll skip login view and take him directly to the tabbar.

[info][tid:com.facebook.React.JavaScript] 'ERROR:', { [TypeError: _reactNativeRouterFlux.Actions.tabbar is not a function. (In '_reactNativeRouterFlux.Actions.tabbar()', '_reactNativeRouterFlux.Actions.tabbar' is undefined)]

**Comment by aacotroneo** [comment]
that one seems like another error. Does that redirect happen before the Router component is loaded? You need that so the Actions are generated.
I have a splash screen myself and restore everything when the splash mounts.. and there I got the warning you posted first.

**Comment by aksonov** [comment]
Probably you are trying to use Actions before it actually created. You need to create them BEFORE Router render, i.e. during compile time. Another option to use setTimeout. But compile time creation is better (however hot reload react native feature will not reload them).

**Comment by rturk** [comment]
Looks like this was closed with the latest commit (https://github.com/aksonov/react-native-router-flux/commit/5373ba2d4e653bbc9e952449a4be11573594687a). I'll run some additional tests.

**Comment by rturk** [comment]
@aksonov That's correct I'm trying to call Actions before router is created. I'm closing this since this is not related to RNRF. 

I've fixed this using F8 code as benchmark (link below as reference). This is much better design. I'm only rendering the App after redux was fully loaded. Surprisingly waiting for the redux to load during initial app setup actually makes it faster since we only need to render it once.

https://github.com/fbsamples/f8app/blob/b5df451259897d1838933f01ad4596784325c2ad/js/setup.js#L61

**Comment by epas1117** [comment]
Sorry I didn't understood, the solution is to add a timeout setTimeout(()=> { Actions.dashboard(); },0);
