### ISSUE TITLE
Implementing tabs in subcomponent

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#473]
I'm trying again to use the tab support you provide. In issues #59 and #64 I describe what I'm trying to do. In version 1 it was possible to implement part of the router heirarchy in a subcomponent by passing `navigator={this.props.navigator}` down to the subcomponent. Is something like this possible in version 3?

I have tried implementing the entire router in the subcomponent but I get the warning `Key root is already defined!` (as well as all my other keys) because the subcomponent re-renders whenever its props change. Also I get an error `Possible Unhandled Promise Rejection (id: 0):
Cannot read property '_currentElement' of null` which I assume is related.

I need to implement the tabs in the subcomponent because the scenes in the tabbar need access to props which are passed down in the hierarchy. I've been using TabBarIOS for this but would like to replace it for several reasons.

**Comment by aksonov** [comment]
It is not supported

**Comment by aksonov** [comment]
You should do it with usage of custom renderer (for TabBarIOS or whatever your like). But scenes should be defined once, at root level
