### ISSUE TITLE
Type 'replace' not replacing view

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#474]
I updated react native to v0.23. and react-native-route-fulx to the latest version. The view is not replaced but it appears behind the initial view

**Comment by codyhazelwood** [comment]
+1 I also just spent about an hour on this and reverted back to 0.22.

**Comment by codyhazelwood** [comment]
This also affects v0.24-rc2

**Comment by Mokto** [comment]
I do not know if it helps but still not working in 0.24-rc3

**Comment by joshbedo** [comment]
Noticing the same issue on iOS.

**Comment by msathis** [comment]
Doesn't work for type "reset" as well.

**Comment by jou** [comment]
Also ran into this, with 0.23.1

**Comment by aksonov** [comment]
I've asked author how to use replace now: https://github.com/ericvicenti/navigation-rfc/issues/50

**Comment by aksonov** [comment]
#489
