### ISSUE TITLE
Menu icon only works if navigation drawer component is the root element

### ISSUE THREAD

**Issue by codyhazelwood** [aksonov/react-native-router-flux#480]
### Version

- react-native-router-flux v3.2.7
- react-native v0.22.2, v0.23.0, v0.24.0-rc2
- react-native-drawer v2.0.0

### Expected behaviour

Creating a scene with a navigation drawer should create a hamburger icon for the menu.

### Actual behaviour

A hamburger icon is only created if the menu is the root element.

### Steps to reproduce

Working example:

```
<Router>
    <Scene key="main" component={NavigationDrawer} title="My Fancy App" type="replace">
        <Scene key="mainContainer">
            <Scene key="home" component={Home} />
            <Scene key="home2" component={Home2} />
        </Scene>
    </Scene>
</Router>
```

Non-working example (icon does not appear, but you can still swipe from the left to open the menu):

```
<Router>
    <Scene key="root>
        <Scene key="signIn" component={SignIn} type="replace" />
        <Scene key="main" component={NavigationDrawer} title="My Fancy App" type="replace">
            <Scene key="mainContainer">
                <Scene key="home" component={Home} />
                <Scene key="home2" component={Home2} />
            </Scene>
        </Scene>
    </Scene>
</Router>
```

**Comment by aksonov** [comment]
Please check Example, Drawer is not root there, but works, right?

**Comment by aacotroneo** [comment]
@codyhazelwood I think your problem is that you are rendering the navBar of the 'root' scene which doesn't have access to the Drawer context.
You should add `<Scene key="root" hideNavBar={true}>` and let the child render their own NavBar

**Comment by codyhazelwood** [comment]
Sorry for the late reply.  @aacotroneo Thanks a lot!  That fixes the problem.
