### ISSUE TITLE
No animations after upgrade react-native to 0.23

### ISSUE THREAD

**Issue by huston007** [aksonov/react-native-router-flux#481]
### Version
- react-native-router-flux v3.2.7
- react-native v0.23.1

### Expected behaviour

There should be animations when user navigates from one scene to another

### Actual behaviour

Animations dissapeared after upgrade react-native from 0.22.2 to 0.23.1

### Steps to reproduce

1. Upgrade react-native to 0.23.1
2. Check the animations disappeared completely

**Comment by Elyx0** [comment]
RNRF stable currently is with RN 0.22

**Comment by caledhwa** [comment]
I’m seeing animations work correctly with 0.24.0-rc2

Also, Android is not working correctly with 0.22 - as a known issue. :)

On April 8, 2016 at 7:24:39 AM, Elyx0 (notifications@github.com) wrote:

RNRF stable currently is with RN 0.22

**Comment by huston007** [comment]
Okay, I'll dive deeper into my code to find the issue then. 
By the way, 0.24.0-rc3 has no animations as well.
Here is my router
```
<Router hideNavBar={true}>
        <Scene key="root">
          <Scene key="Home"
                 component={Home}
                 initial={true}/>

          <Scene key="LogIn"
                 duration={1}
                 component={() => <LoginForm auth={this.auth} onLogIn={this.checkAuthorization.bind(this)}/>}/>

          <Scene key="IssueList"
                 direction="horizontal"
                 title="Issues"
                 type="replace"
                 component={IssueList}/>

          <Scene key="ShowImage"
                 title="Image"
                 direction="vertical"
                 component={ShowImage}/>

          <Scene key="SingleIssue"
                 title="Issue"
                 direction="horizontal"
                 component={SingleIssue}/>

          <Scene key="CreateIssue"
                 title="Create Issue"
                 component={CreateIssue}/>
        </Scene>
      </Router>
```

**Comment by sylvainbaronnet** [comment]
No animation with 0.24.0-rc3 too

**Comment by sylvainbaronnet** [comment]
#486 Fix it

**Comment by timzaak** [comment]
@sylvainbaronnet  does not fix it .
Android  with v3.2.8 and rn v0.23.1 does not work.

**Comment by sylvainbaronnet** [comment]
Works for me with RN 0.24.0-rc3 (iOS and Android)

**Comment by timzaak** [comment]
If you use type="replace" ?

**Comment by sylvainbaronnet** [comment]
see #491

**Comment by aksonov** [comment]
#489
