### ISSUE TITLE
Discuss - Replace Actions.destination({..data}); with Actions.go('destination',{...data});

### ISSUE THREAD

**Issue by rturk** [aksonov/react-native-router-flux#484]
Hopefully this proposal should be straight forward to explain:

Currently in order to trigger any change in the navigation flow one needs to call Action.destination(). I would like to ask this group if it makes sense to replace the existing logic with a unique function, let's say `go()` that will provide same functionality, however without the need to write more code.

Actions will solely a few functions. Actions.pop(), Actions.go(...), Actions.refresh().. etc..
With a new function. Actions.go('destination',{payload})

Pros:

- Makes it easy to mage view and other content generated on demand
- Consistency the between strings `destination` and the `key` used to create scenes components
- Easier to use in switch, if's statements
- Helps code maintenance when one needs to search for functions that change the navigation flow

Cons:

- This will break current design

Please include your thoughts, concerns, props, cons

**Comment by aksonov** [comment]
Actually you could use it now, with Actions,callback({key:'destination', {...}). You may submit PR to make 'go' as alias for that

**Comment by rturk** [comment]
@aksonov thank you! This is great.
