### ISSUE TITLE
otherProps in Scene does not update at all

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#485]
### Version
"react-native": "^0.22.2",
"react-native-router-flux": "aksonov/react-native-router-flux#dcc7558",

### Problem
Following code will pass isRefreshing props to WeatherContainer which works as correctly.
```
<Scene key="weatherProperty" component={WeatherContainer} title="Weather" isRefreshing={this.props.isWeatherRefreshing}/>
```
However, when this.props.isWeatherRefreshing changes props passed to WeatherContainer does not update.

### How to hack it around
Whenenever this.props.isWeatherRefreshing changes call
```
Actions.refresh({isRefreshing: this.props.isWeatherRefreshing})
```
However, this causes problem when props change while I am on a different Scene.

**Comment by aksonov** [comment]
It is not issue actually. You may use Actions.refresh({key:SCENE_KEY, props}) for this.

**Comment by bosung90** [comment]
@aksonov This is an issue. Actions.refresh only works for the currently active scene and therefore if props change while you are on a different scene, it will simply fail.

**Comment by aksonov** [comment]
Have you tried Actions.refresh({key:SCENE_KEY, props}) ? Could you modify component Example to show the issue?

**Comment by bosung90** [comment]
@aksonov Sorry I thought you were referring to my "hack it around" solution and didn't notice your key:SCENE_KEY. I will let you know once I try it, Thanks!. 
However, I still feel like otherProps should update to a new value whenever props change to a new value.

**Comment by aksonov** [comment]
I don't see how it is possible to implement (auto-update fields) - Scenes are not real components, but just syntax sugar to describe your scheme. They don't render anything.

**Comment by bosung90** [comment]
@aksonov using otherProps in Router allows you to pass to every Scene. Is there similar for Actions that allow me to pass props to all Scenes ? For example Actions.refresh({key: 'Router', props})

**Comment by bosung90** [comment]
@aksonov  I just tried Actions.refresh({key:SCENE_KEY, props}), and I am getting "missed child data for key=weatherProperty error at <unknown> Reducer.js : 123

**Comment by bosung90** [comment]
@aksonov Found out the problem is with Reducer.js line 82 it is checking rather state.key === key but it should actually be state.name === key
Also, calling Actions.refresh on key that is statically defined but has not yet been initialized will throw assertion error. Is there a way to check if element exists before calling Actions.refresh or let it fail silently?

**Comment by bosung90** [comment]
#506

**Comment by aksonov** [comment]
Should be fixed within 3.2.10

**Comment by tuneZola** [comment]
I am also seeing this issue with v3.22.15. The Scene is betting called with each Redux state change, but the value the Scene has is never updated.

**Comment by bosung90** [comment]
@tuneZola You can easily bypass this restriction by one of following ways:
1. Use `Actions.refresh({key: '<your scene key>', <customKey>: <customValue>})`
2. Put redux container in each of your Scene component and you can get your values within your container without passing it through scene.
3. Pass in function as otherprops that returns your value. This can be fetched whenever willReceiveProps gets called within Scene component that sets your state.

**Comment by tuneZola** [comment]
@bosung90 Thank you for the work around. I am not sure if I would personal want to do something like this. It seems like a work about that is fairly extensive if you have a log of scenes as we do, and the restriction seems to be a flaw. Why would you have a scene update without being passed down the old props. Whats the point in using Redux in that case. Might as well keep everything in state.
