### ISSUE TITLE
Tabs NavBar doesn't show on first reroute

### ISSUE THREAD

**Issue by MITDelian** [aksonov/react-native-router-flux#49]
I encountered this first in a project that I was working on but wanted to verify it by trying out your example app.

Basically when using the tabs, the first reroute you do away from the root doesn't have a navbar. Here is my process:

Launch Example App:

![screenshot 2015-12-09 18 30 49](https://cloud.githubusercontent.com/assets/1158032/11705191/ffe32fc4-9ea2-11e5-9f61-b8eef549f012.png)

Go to TabBar page:
![screenshot 2015-12-09 18 31 19](https://cloud.githubusercontent.com/assets/1158032/11705198/0e736e5a-9ea3-11e5-9e32-77e71b71ec3a.png)

Click on next screen for tab1_1 (this is where the issue is! Navbar no longer there):
![screenshot 2015-12-09 18 31 48](https://cloud.githubusercontent.com/assets/1158032/11705208/1ec41570-9ea3-11e5-96a5-434bb3e0b3a9.png)

Click back:
![screenshot 2015-12-09 18 32 17](https://cloud.githubusercontent.com/assets/1158032/11705222/2ebd5acc-9ea3-11e5-85bb-3f201c7c64a3.png)

Click on next screen for tab1_1 (Now the Navbar shows up just fine...):
![screenshot 2015-12-09 18 32 32](https://cloud.githubusercontent.com/assets/1158032/11705227/394e516c-9ea3-11e5-934d-9278a7fa8d6f.png)

Thanks for all of your contributions to the RN ecosystem. I'm going to dig into this myself a bit and see if I can find what is causing this.

**Comment by aksonov** [comment]
So what is error on last screen?

**Comment by aksonov** [comment]
Oh, i see, error not on last, but on third one. I will look

**Comment by aksonov** [comment]
Should be fixed with 1.0.1, please check. Thanks for reporting!

**Comment by MITDelian** [comment]
Sorry just the third screen had errors, was just showing on the last screen when you navigate back the nav bar appears

**Comment by MITDelian** [comment]
Nice! Looks great. Fixed the issue.
