### ISSUE TITLE
Passing state to Scene  through props

### ISSUE THREAD

**Issue by Emilios1995** [aksonov/react-native-router-flux#492]
### Version

- react-native-router-flux v3.2.8
- react-native v0.23.1

I don't want to use Redux as state holder, I want instead to store the state in the top level component which contains the router, then pass part of the state to the routes through the props 

### Expected behaviour
When I update the state, the scenes's component should be updated with the new state in props

### Actual behaviour
The Scene's components remains with the old version of the state

**This was already fixed in #167 but the problem appeared again in v3**

**Comment by aksonov** [comment]
How you propose to support several Scenes in stack with the same key like ProfileDetail? It is NOT suitable to change global ProfileDetail 'state' in this case. You could easily store state within this.state for the component taken from this.props.navigationState.

**Comment by Emilios1995** [comment]
@aksonov thank you for answering but I don't understand the solution you are proposing, would you mind elaborating a bit more?

**Comment by aksonov** [comment]
My fault, you cannot use this.state, because component will be created for each Scene. But again, we have two contradict requirements from component users - don't store state (because of possibility of several equal components within stack) and you want to store state....

**Comment by aksonov** [comment]
You could solve your problem with your custom reducer - just modify 'scenes' of state properly. Now it is read-only (never modified).

**Comment by Emilios1995** [comment]
@aksonov  you're right, I understand the problem. Would you please give me an example of how  I could implement that custom reducer to solve my problem? I'm not familiar enough with this library to figure it out on my own :(

**Comment by aksonov** [comment]
Sorry, i don't have time for teaching. Check readme, check example project with custom reducer, etc. And better try to use Redux, this component is about navigation, not replacing redux.
