### ISSUE TITLE
Cannot interact with NavigationCard rendered scenes

### ISSUE THREAD

**Issue by antonzy** [aksonov/react-native-router-flux#493]
Lets say I got the following setup:

```javascript
<Router>
    <Scene key="root" hideNavBar={true}>
        <Scene key="login" component={LoginScreen} type="replace"/>

        <Scene key="shell" type="replace" component={ShellScreen} tabs={true} >
            <Scene key="profile" type="jump" title="My Profile" component={ProfileScreen} initial={true}/>
        </Scene>
    </Scene>
</Router>
```

Seems like everything is rendered correctly, but I cannot interact with the rendered scene.
When opening Inspector looks like NavigationCard from NavigationExperimental is the top view and all taps are swallowed by it.

**Comment by aksonov** [comment]
I can't reproduce. Could you modify Example project and show the issue?
