### ISSUE TITLE
Back button Warning

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#494]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.2.8
- react-native v0.22.0

### Expected behaviour
No warning when onLeft is not specified

### Actual behaviour
Warning shows up when onLeft is not specified

### Steps to reproduce

1. Add a scene (without specifying onLeft closure but with leftTitle)
2. Push to the scene

**Comment by ajoshdee** [comment]
I just want the normal back button.

**Comment by aksonov** [comment]
You have to use backTitle then i guess.
