### ISSUE TITLE
tabbar doesn't work in react-native 0.24.0-rc3

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#495]
### Version
- react-native-router-flux v3.2.8
- react-native v0.24.0-rc3

### Expected behaviour
Tabbar should work

### Actual behaviour
Exception is thrown

### Steps to reproduce

1. Pull latest react-native-router-flux[#6817717](https://github.com/aksonov/react-native-router-flux/commit/68177172a2d7c68aa98503296872effc6f8dfd1d)
2. run command `npm install --save react-native@0.24.0-rc3`
3. run command `react-native upgrade` and overwrite all `a`
4. Notice app crashes with red screen 
```
undefined is not an object (evaluating navigationState.index)
render
DefaultRenderer.js @ 47:0
```

**Comment by aksonov** [comment]
#525
