### ISSUE TITLE
direction="vertical" not working

### ISSUE THREAD

**Issue by yusufseyrek** [aksonov/react-native-router-flux#499]
### Version
- react-native-router-flux v3.2.8
- react-native v0.23.1

### Expected behavior
I have a scene that needs to come from vertical direction but it is comes from right. Also i run the example. Its not working either. 

`
<Scene key="modal" component={Modal} >
                <Scene key="root">
                    <Scene key="SelectSummoner" component={SelectSummoner}  title={Strings.get("selectsummoner")} initial={true}/>
                    <Scene key="GameInfo" component={GameInfo} title={Strings.get("gameinfo")}/>
                    <Scene key="login" direction="vertical">
                        <Scene component={SummonerDetail} key="SummonerDetail" title="Test" hideNavBar={true}/>
                    </Scene>
                </Scene>
            </Scene>
`
btw sorry for code styling..

P.S: on RN v0.22 it is working perfectly.

**Comment by bosung90** [comment]
@aksonov #490 does not fix this problem. I am still getting push from right side rather than vertically.
