### ISSUE TITLE
How to hide navbar?

### ISSUE THREAD

**Issue by sslash** [aksonov/react-native-router-flux#50]
I want to remove the top navigation bar.
I have tried  to set showNavigationBar={false} on the route, but its still there.
Am I missing something obvious?

**Comment by aksonov** [comment]
Use it for 'Router', not for 'Route'. PR for documentation is welcome :)

**Comment by sslash** [comment]
I have tried that too, doesn't remove the navbar :/

**Comment by aksonov** [comment]
Let me check

**Comment by aksonov** [comment]
Are you sure you removed root navbar first?

**Comment by aksonov** [comment]
Otherwise it will be visible if you are hide child ones...

**Comment by sslash** [comment]
<img width="1344" alt="skjermbilde 2015-12-10 kl 17 05 52" src="https://cloud.githubusercontent.com/assets/1174520/11720627/5d50f9d0-9f60-11e5-9b69-4dd98761e50a.png">

Just to be sure, I add it in most possible places

**Comment by aksonov** [comment]
Android or iOS? I've just modified demo, added flag to Login and doesn't see navbar there normally:
Or you want to hide "Launch" navbar? Then probably 'wrapRouter' doesn't pass it to inner Router, i will fix it.

<Router hideNavBar={true}>
                <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
                <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                <Schema name="withoutAnimation"/>
                <Schema name="tab" type="switch" icon={TabIcon} />

                <Route name="launch" component={Launch} initial={true} wrapRouter={true} title="Launch"/>
                <Route name="register" component={Register} title="Register"/>
                <Route name="home" component={Home} title="Replace" type="replace"/>
                <Route name="login" schema="modal">
                    <Router showNavigationBar={false}>
                        <Route name="loginModal" component={Login} title="Login" schema="modal"/>
                        <Route name="loginModal2" component={Login2} title="Login2"/>
                    </Router>
                </Route>
                <Route name="register2" component={Register} title="Register2"  schema="withoutAnimation"/>
                <Route name="tabbar">
                    <Router footer={TabBar} showNavigationBar={false}>
                        <Route name="tab1" schema="tab" title="Tab #1" >
                            <Router>
                                <Route name="tab1_1" component={TabView} title="Tab #1_1" />
                                <Route name="tab1_2" component={TabView} title="Tab #1_2" />
                            </Router>
                        </Route>
                        <Route name="tab2" schema="tab" title="Tab #2" component={TabView} />
                        <Route name="tab3" schema="tab" title="Tab #3" component={TabView} />
                        <Route name="tab4" schema="tab" title="Tab #4" component={TabView} />
                        <Route name="tab5" schema="tab" title="Tab #5" component={TabView} />
                    </Router>
                </Route>
            </Router>

**Comment by aksonov** [comment]
Check 1.0.2 version, i've disabled nav bar for 'launch' screen within Example also.

**Comment by sslash** [comment]
Worked like a charm. Thanks!

**Comment by lakmalniranga** [comment]
<Scene key={'login'} component={LoginView} hideNavBar={true} />

This works to me!

**Comment by bjax13** [comment]
<Router hideNavBar={true}>

Also works.

**Comment by vvavepacket** [comment]
I tried the above code from lakmalniranga, but header still takes a spot.
[https://snag.gy/91aXTj.jpg](url)

**Comment by EmersonStark** [comment]
hideNavBar={true} :D

**Comment by lyrl** [comment]
work !!!!  thanks @lakmalniranga 

```js
                <Scene key="SplashSCreen" component={SplashSCreen}  title="splash" hideNavBar={true} initial/>

```

**Comment by sivcan** [comment]
We don't even need to assign hideNavBar a value of true.
If we mention it then it simply means we are giving it a value of true rather than being undefined.
Just adding for future users referring to this issue. 

```
<Scene 
key="SplashSCreen" 
component={SplashSCreen}  
title="splash" 
hideNavBar
 initial
/>
```

**Comment by Omarkojak** [comment]
any ideas why when using hideNavBar it still appears
<img width="1280" alt="screen shot 2017-06-09 at 1 34 44 am" src="https://user-images.githubusercontent.com/15948451/26954976-d73dcbc2-4cb3-11e7-8054-e655843e076e.png">
<img width="1280" alt="screen shot 2017-06-09 at 1 33 59 am" src="https://user-images.githubusercontent.com/15948451/26954977-d741b30e-4cb3-11e7-8612-2c0ea953e1ac.png">

**Comment by godfredcs** [comment]
@Omarkojak You gave the Router a paddingTop of 65. That means every scene gets a paddingTop of 65 whether they have titles (navbar) or not.

**Comment by Omarkojak** [comment]
ok fixed sorry for that

**Comment by rwehresmann** [comment]
There are any way to not only hide the navbar, but also remove it? Even hidden, it still taking up space on the screen.

**Comment by Icacls** [comment]
it still appears,I can not see why
![111](https://user-images.githubusercontent.com/3806467/27943013-5027e4d0-630e-11e7-82bd-32687f546cb6.jpeg)
![222](https://user-images.githubusercontent.com/3806467/27943014-503b1ee2-630e-11e7-9e3f-fc86fb19126b.jpeg)

**Comment by MehranJanfeshan** [comment]
any update on this? even if hide the nav still takes some space there

**Comment by aksonov** [comment]
@MehranJanfeshan Are you talking about v4 version?

**Comment by MehranJanfeshan** [comment]
@aksonov Thanks for the reply, I got the version 4 but I am getting this error:

`[react-native-router-flux] props should be defined`

**Comment by aksonov** [comment]
Check breaking changes first

**Comment by MehranJanfeshan** [comment]
@aksonov I found that in the old version I was able to do this: 
`<Router sceneStyle={{margin:0}} hideNavBar={true}>
      <Scene key="auth">
        <Scene key="login" component={AuthScreen}/>
      </Scene>
      <Scene key="main">
        <Scene
          onRight={() => Actions.auth()}
          rightTitle="Log out"
          key="newOrderList"
          component={EmployeeList}
          title="New Orders"
          initial
        />
        <Scene key="orderDetails" component={OrderDetails} title="Order Details"/>
      </Scene>
    </Router>` 

but after I moved to version 4 I cannot do that so I changed to this and it worked:

`<Router sceneStyle={{margin:0}} hideNavBar={true}>
      <Scene key="auth">
        <Scene key="login" component={AuthScreen}/>
        <Scene
          onRight={() => Actions.auth()}
          rightTitle="Log out"
          key="newOrderList"
          component={EmployeeList}
          title="New Orders"
          initial
        />
        <Scene key="orderDetails" component={OrderDetails} title="Order Details"/>
      </Scene>
    </Router>`


but this not what I want, I want to able to categorize the Scene, is there any other alternative?

**Comment by aksonov** [comment]
I don't understand the problem. Please check Example and try to reproduce your issue there.

**Comment by MehranJanfeshan** [comment]
here is my code that works perfectly in version 3 but when I upgraded to version 4 I got this error: 
`[react-native-router-flux] props should be defined`
so I removed the part that is surrounded by the blue line and it works fine. 
![image](https://user-images.githubusercontent.com/13583839/28177844-be5ef810-682e-11e7-8b70-cbe6528fd071.png)

**Comment by aksonov** [comment]
Wrap it with one root scene.

**Comment by MehranJanfeshan** [comment]
if I wrap it with one root scene then how I can control the back button? I do not want the user to be able to back to the login page, that' why I used to Scene.

**Comment by aksonov** [comment]
It is not question about RNRF but more about your application structure. I guess you need to use `tabs` or disable back button (mark it with 'init' attribute) or use 'replace' type. Check Example.

**Comment by aksonov** [comment]
Actually v3 just wrapped multiple scenes into one, so you will not see any back button (because you hide parent navbar)

**Comment by MehranJanfeshan** [comment]
@aksonov Thanks for the help and thanks for the great job :)

**Comment by adarshTS** [comment]
this worked for me :
<Scene key="homeScreen" component={mainScreen} hideNavBar={1} />

**Comment by aksonov** [comment]
You could just use `<Scene key="homeScreen" component={mainScreen} hideNavBar` />

**Comment by vhson0610** [comment]
@lakmalniranga this worked for me, thanks!

**Comment by ahmetilhann** [comment]
Works

```
const RouterComponent = () => (
    <Router headerMode="none">
        <Stack key="main">
            <Scene 
                key="login" 
                component={Login} 
            />
        </Stack>
    </Router>
);
```

**Comment by 0paIescent** [comment]
@ahmetilhann Thanks! Removes all headers of child Scenes in the Router, still works as of v4.0.0-beta.3.

**Comment by X9He** [comment]
@ahmetilhann thanks so much! maybe the older way only works on pre 4.0 RN? I'm on 4.0.6 and `headerMode="none"` works

**Comment by padlock98** [comment]
Upgraded my project to RN0.59.10, however still using react-native-router-flux for Router and Scene.  And having this white header bar issue.  Took me for days, all the while I suspected it was due to react-navigation and managed to turn it off but still there is another header blocking the view, then only I thought of may be due to react-native-router-flux.  @ahmetilhann method is WORKING.  Set headerMode="none" at Router, life saver!!!

**Comment by ShubhamTomar98** [comment]
> <Scene key={'login'} component={LoginView} hideNavBar={true} />
> 
> This works to me!

to the point

**Comment by ameurbilel** [comment]
Hello,
using the hideNavBar makes the hole components disappear.
Here is my code : 
<Router>
                <Stack key="root" >
                    <Scene key="login" component={Login} title="Login" initial={true} hideNavBar={true}/>
                    <Scene key="signup" component={Signup} title="Signup" />
                </Stack>
</Router>
What could be the cause?

![Screenshot_2020-05-03 elschool](https://user-images.githubusercontent.com/57261657/80896310-de67d400-8ce4-11ea-9a29-5c75e072c69b.png)

**Comment by cells800** [comment]
> Hello,
> using the hideNavBar makes the hole components disappear.
> Here is my code :
> 
> ```
> <Router>
>                 <Stack key="root" >
>                     <Scene key="login" component={Login} title="Login" initial={true} hideNavBar={true}/>
>                     <Scene key="signup" component={Signup} title="Signup" />
>                 </Stack>
> </Router>
> ```
> 
> What could be the cause?
> 
> ![Screenshot_2020-05-03 elschool](https://user-images.githubusercontent.com/57261657/80896310-de67d400-8ce4-11ea-9a29-5c75e072c69b.png)

I have the same issue as well.
