### ISSUE TITLE
Android Requiring unknown module "assert"

### ISSUE THREAD

**Issue by mobileDevNativeCross** [aksonov/react-native-router-flux#500]
### Version
- react-native-router-flux 3.2.8
- react-native 0.23.1

### Steps to reproduce

1. import {Actions} from "react-native-router-flux";

Module AppRegistry is not a registered callable module.
Requiring unknown module "assert". If you are sure the module is there, try restarting the packager or running "npm install".
Module AppRegistry is not a registered callable module.

**Comment by aksonov** [comment]
Have you read message you are posting? "Requiring unknown module "assert". If you are sure the module is there, try restarting the packager or running "npm install"."

**Comment by mobileDevNativeCross** [comment]
sorry.
