### ISSUE TITLE
Actions.refresh({key: SCENE_KEY, props}) throws assertion error

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#506]
### Version
"react-native-router-flux": "^3.2.9",
"react-native": "^0.23.1",

### Expected behaviour
Actions.refresh({key: SCENE_KEY, props}) should update the props passed into the scene component.

### Actual behaviour
Throws an assertion exception
```
missed child data for key=SCENE_KEY
<unknown>
Reducer.js:126
```

### Steps to reproduce

1. Ensure you have Scene with key=SCENE_KEY
2. Call Actions.refresh({key: SCENE_KEY, props})

### Possible Fix
Currently there doesn't seem to be a workaround unless changing Reducer.js directly.
More specifically changing line 82 
`if (type === REFRESH_ACTION ? state.key === key : state.sceneKey === key) {`
to
`if (state.sceneKey === key) {`
Seems to fix the problem, as state.key have 0_ infront of their values so it will not match.
Another way to do it is by checking if state.name === key

### More problems
Even if you change line 82 to above line, it will still fail assertion if your scene has not been loaded yet. It would be nice to allow an option to check for existing scene or fail silently.

**Comment by aksonov** [comment]
Please check 3.2.10. Sorry, but fail silently is not good idea, so you need to make sure that scene with that key is already loaded.
