### ISSUE TITLE
Schema=popup in 1.x ? 

### ISSUE THREAD

**Issue by Sh3rawi** [aksonov/react-native-router-flux#51]
Hello, Great work on the router man!
I've just updated to v1.0 and I noticed that you removed the implementation of popups. 
Would like to know if it can be re-implemented ? Or was there a specific technical issue with the new release ? 

Thanks,

**Comment by aksonov** [comment]
Yes, a little bit work is needed, i just thought feature is not used :)

**Comment by JonnyBGod** [comment]
+1

**Comment by aksonov** [comment]
Ok, will work on it.

**Comment by aksonov** [comment]
Please check type='modal' within latest 2.1.3 and Example with popup Error.
