### ISSUE TITLE
Switch from one scene in a tabbar to another scene in a other tabbar

### ISSUE THREAD

**Issue by albo1337** [aksonov/react-native-router-flux#510]
### Version
- react-native-router-flux v3.?.?
- react-native v0.24.rc-2

### Expected behaviour
Scene would be shown with an other tabbar.

### Actual behaviour
Scene is not opening.

### Steps to reproduce

1. Create one tabbar with a tab. 
2. Create there a scene with a component.
3. Create an other tabbar with a tab.
4. Create there a scene with a component.
5. Try to switch from scene in tabbar1 to scene in tabbar2.

What I'm doing wrong?

**Comment by aksonov** [comment]
Duplicate of #370 ?

**Comment by albo1337** [comment]
I get no errors. The scene is just not opening. Maybe I do an example:

`<Scene key="root" hideNavBar={true}>

                    <Scene key="firstTabbar" Component={TabBar} tabs={true} default="loginTab">
                        <Scene key="loginTab" title="Login" icon={TabIcon}>
                            <Scene key="login" component={Login} title="Login"/>
                        </Scene>
                        <Scene key="registerTab" title="Registrieren" icon={TabIcon}>
                            <Scene key="registerModal" component={Register} title="Registration"/>
                        </Scene>
                    </Scene>

                    <Scene key="secondTabbar" Component={TabBar} tabs={true} default="homeTab">
                        <Scene key="homeTab" title="Home" icon={TabIcon}>
                            <Scene key="home" component={Home} title="Home"/>
                        </Scene>
                    </Scene>
                </Scene>`

I want to open in my scene "login" the scene "home".

**Comment by aksonov** [comment]
Please modify Example project to reproduce the issue

**Comment by albo1337** [comment]
Done

**Comment by albo1337** [comment]
I found it by my own. I had to call the Scene in an other way as I thought. 

###Example.js
```
...
<Scene key="modal" component={Modal}>
    <Scene key="root" hideNavBar={true}>
        <Scene key="tabbar" Component={TabBar} tabs={true} default="loginTab">
            <Scene key="loginTab" title="Login" icon={TabIcon}>
                <Scene key="login" component={Login} title="Login"/>
            </Scene>
            <Scene key="registerTab" title="Registrieren" icon={TabIcon}>
                <Scene key="registerModal" component={Register} title="Registration"/>
            </Scene>
        </Scene>
        <Scene key="tabbarTwo" Component={TabBar} tabs={true} type="replace">
            <Scene key="homeTab" title="Home" icon={TabIcon}>
                <Scene key="home" component={Home} title="Home"/>
            </Scene>
        </Scene>
    </Scene>

</Scene>

...
```


###Login.js
```
...
Actions.tabbarTwo();
...
```
