### ISSUE TITLE
Click back button ON DEFAULT SCENE

### ISSUE THREAD

**Issue by dzmitryhil** [aksonov/react-native-router-flux#511]
### Version

- react-native-router-flux v3.8.5
- react-native v0.23.1

### Description

I'm trying add Android BACK button behaviour.

My render method:
```
 render() {
         // handle android back button action
         BackAndroid.addEventListener('hardwareBackPress', () => {
               if (Actions) {
                  Actions.pop();
                  return true;
               }
               return false;
             });

        return <my Router description>....
    }
```

**Almost everything works**, but when I call "Actions.pop();" on Default scene - got error

in file: Modal.js
at line:` <DefaultRenderer navigationState={state}  key={state.key} {...state} />`
exception:  Cannot read property 'sceneKey' of undefined

How can i check is this Scene default ? Or fix it please, if it is bug.

**Comment by bosung90** [comment]
you shouldn't call Actions.pop() on a default scene since there is nothing to pop. In default scene, you should return false in order to let Android take care of back button (in which case it will close the app)

**Comment by dzmitryhil** [comment]
But how can I check if scene Default ?

**Comment by bosung90** [comment]
#515 Use Gitter for questions
