### ISSUE TITLE
IMPORTANT: Please ask questions about usage within Gitter or stackoverflow

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#515]
... not here, with tag react-native-router-flux, react-native

**Comment by caledhwa** [comment]
Better yet Pavlo? Use the Gitter…. a pretty good group of folks trying to figure stuff out there. Learned a ton already. Thanks for a great project!



On April 12, 2016 at 7:27:53 AM, Pavlo Aksonov (notifications@github.com) wrote:

Please ask questions about usage within stackoverflow, not here, with tag react-native-router-flux, react-native

**Comment by rturk** [comment]
In case you're looking for the address https://gitter.im/aksonov/react-native-router-flux

**Comment by ndarilek** [comment]
Can anyone create the react-native-router-flux tag on SO? I can't, I need 1500 reputation. I have a question but unfortunately Gitter is inaccessible to me, and since I can't create the SO tag I don't know where to ask it.

Thanks!
