### ISSUE TITLE
Push Navigation animation doesn't work in 3.2.10, 3.2.12

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#519]
### Version
    "react-native": "^0.23.1",
    "react-native-router-flux": "3.2.12",

### Expected behaviour
When calling Actions.SCENE+KEY() it should have push animation coming from right to left.

### Actual behaviour
There is no push animation. Animation inside navigationBar works.

### Steps to reproduce

1. Run Example Project in Android or iOS, go to Tabbar
2. Press `push new scene`
3. Notice the scene changes but there is no push animation

1. Same behaviour inside Login scene

**Comment by brien-crean** [comment]
+1

**Comment by crockpotveggies** [comment]
+1

**Comment by aksonov** [comment]
#525! Duplicate of #481

**Comment by bosung90** [comment]
@aksonov This is not a duplicate of #481  because this bug was introduced starting 3.2.10
#481 Clearly states it is for 3.2.7

**Comment by angeloashmore** [comment]
#526 should fix this.

**Comment by aksonov** [comment]
@bosung90 All i see that non-supported 0.23 is used...
