### ISSUE TITLE
Crash when Back button is tapped during animation

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#520]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.2.7
- react-native v0.22.2

### Expected behaviour
Actions invoked during an animation should be ignored.

### Actual behaviour

I have a scene that is a list, and selecting an item in the list pops the scene. There is also a BACK button in the navbar that does a pop. When running on a slow device and the animation takes a long time after selecting a list item, the user is tempted to press  the Back button, which results in a Red Box error: `'undefined' is not an object (evaluating 'selected.duration')`

I can disable the back button when the action starts, but I might have to do that in many places, and I'm wondering if that shouldn't be the responsibility of this component or navigation experimental?

### Steps to reproduce

1.
2.
3.

**Comment by bosung90** [comment]
If you are talking about Android, you should upgrade RN to 0.23.1

**Comment by chetstone** [comment]
Thanks, no, this is iOS.

**Comment by aksonov** [comment]
@chetstone Looks like it is fixed within latest React native master, i don't remember number of the issue, but we can't use it because of #557

**Comment by charpeni** [comment]
I'll close this issue since 0.26 will be landed in few days.

If you still get this issue with 0.26.0 (both updated react-native and react-native-router-flux), please reopen it.

**Comment by gendeld** [comment]
I have the same problem with RN 0.37 and RNRF 3.37

**Comment by Guardiannw** [comment]
Same problem

**Comment by egunsoma** [comment]
Same problem here.
Even tried to `stop` animations onBack is clicked, but didn't help.
Any ideas?

**Comment by chetstone** [comment]
I set a state variable goingBack to disable subsequent clicks of the back button
