### ISSUE TITLE
Adding custom animations

### ISSUE THREAD

**Issue by sashafklein** [aksonov/react-native-router-flux#523]
### Expected behaviour

(Running react-native-router-flux 3.1.6, on react-native 0.22.2)

Is there any way to customize a transition animation (ie one other than 'push'/'replace'/etc)? I tried adding an `applyAnimation` function, but it seems to only allow me to control duration of animation -- and that doesn't actually work as expected; setting the duration, to whatever value, seems to slow the animation down. 

If custom animations are possible, is there an example somewhere of how to make one? I can't find one (in examples, issues, etc), and haven't been able to approximate one by using `applyAnimation` and looking around the source code.

I'm specifically looking for a swipe-style animation, where one page shifts in while the other shifts out.

Thanks!

**Comment by Iliyass** [comment]
Curious about this `applyAnimation` can you show an example of it's body, I have no clue what should it return!
I'm also looking for having a custom Animation.

**Comment by aksonov** [comment]
As I understand custom animations are introduces only within RN0.24, but that version introduce more serious bugs, see #557 
You may also check branch 3.24, but it contains bugs described within #557

**Comment by ms88privat** [comment]
Is this now possible with 0.26? Is there any example for a custom animation? Thanks!

**Comment by zelphir** [comment]
@aksonov any updates on this one?

**Comment by 7ynk3r** [comment]
updates?

**Comment by getnashty** [comment]
+1 looking for updates

**Comment by dkaushik94** [comment]
Trying out for custom animations. If I get a hang of it I might try to contribute support of different animation styles. No luck yet. Anybody with a good example of how to apply animations in between on screen transitions. @aksonov
