### ISSUE TITLE
Correct Way to Implement Drawer

### ISSUE THREAD

**Issue by babbarankit** [aksonov/react-native-router-flux#524]
I am having a  Launch Screen which redirects to Drawer by calling `Actions.drawer` if Login Credential are found.
Home Screen is appearing but with a back button instead of Drawer Button, please help!
```
const scenes = RNRF.Actions.create(
    <Scene key="root">
      <Scene key="launch" component={LaunchScreen} initial={true} hideNavBar={true} title="Launch"/>
      <Scene key="loginScreen"  component={LoginScreen} hideNavBar={true} title="Login Screen"/>
      <Scene key="otpScreen" component={OTPScreen} hideNavBar={true} title="Login Screen" />
      <Scene key="drawer" component={SideDrawer}>
        <Scene key="main">
          <Scene key="home" component={Home} type="replace"/>
          <Scene key="home1" component={Home1} type="replace"/>
        </Scene>
      </Scene>
    </Scene>
);
```

**Comment by codyhazelwood** [comment]
Add `hideNavBar="true"` to your `root` scene, and them remove it everywhere else.  You'll still get a navbar on your `main` scene which should contain the drawer.

**Comment by babbarankit** [comment]
Thanks! issue was because of using 0.23.1

**Comment by lynndylanhurley** [comment]
I must be an idiot because I've been struggling with this for several hours. What is the proper way to set up the drawer with this configuration?

~~~js
// scenes
<Scene key="Root">
  <Scene key="Auth">
    <Scene
      key="Login"
      component={Login}
      title="Login" />
  </Scene>

  <Scene key="Main">
    <Scene
      title="Dashboard"
      key="Dashboard"
      component={Dashboard}
      initial={true}>

    {/* ... more scenes */}
  </Scene>
</Scene>
~~~

~~~js
// drawer

class MainDrawer extends React.Component {
  static contextTypes = {
    drawer: PropTypes.object,
  };

  constructor (props) {
    super(props);

    this.state = {
      showDrawer: false,
    };
  }

  toggle () {
    const {drawer} = this.context;
    const showDrawer = !this.state.showDrawer;

    if (showDrawer) {
      drawer.open();
    } else {
      drawer.close();
    }

    this.setState({showDrawer});
  }

  renderNav () {
    return (
      <View>
        {/* ... menu items */}
      </View>
    )
  }

  render () {
    const children = this.props.navigationState.children;

    return (
      <Drawer
        ref={(ref) => this.drawer = ref}
        type="displace"
        content={this.renderNav()}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        negotiatePan={true}
        tweenHandler={(ratio) => ({
          main: { opacity: Math.max(0.54,1 - ratio) }
        })}>
        <DefaultRenderer navigationState={children[0]} />
      </Drawer>
    );
  }
}
~~~

Following the example, I tried this:

~~~js
// scenes
<Scene key="Root">
  <Scene key="Auth">
    <Scene
      key="Login"
      component={Login}
      title="Login" />
  </Scene>

  <Scene key="Main" component={MainDrawer}>
    <Scene
      title="Dashboard"
      key="Dashboard"
      component={Dashboard}
      initial={true}>

    {/* ... more scenes */}
  </Scene>
</Scene>
~~~

But this doesn't work. I don't get the drawer icon, and if I try to create my own drawer icon manually using the `rightTitle` and `onRight` props, I can't access the drawer from the `onRight` method's context. For example, this also doesn't work:

~~~js
    <Scene
      component={Drawer}
      rightTitle={
        <Icon name="navicon" size={26} color="#fff" />
      }
      onRight={() => {
        console.log('context', this.context); // context is undefined
      }}
      title="Dashboard"
      key="Main">

      {/* ... scenes */}
    </Scene>
~~~

I'm using react-native 0.22.

**Comment by efkan** [comment]
I had prepared an example [here](https://github.com/efkan/rndrawer-implemented-rnrouter).

**Comment by aksonov** [comment]
@efkan Great work!
Actually i don't like complexity of 'contextTypes', maybe it is possible to implement drawer without usage of context at all....

For example Actions.refresh({key:DRAWER_NAME, 'open':true}) could open drawer (Drawer renderer will open it when navigationState.open prop is changed) Maybe we could improve 'refresh' to allow 'switch' boolean values to implement switch, like passing function for values: Actions.refresh({key:DRAWER_NAME, open:value=>!value})

**Comment by efkan** [comment]
Thanks @aksonov ,

Thanks to you, I completed a month ago that example and I don't have enough time to think about it.

Yesterday I upgraded the my project. As you may guess, then some serious problems arose.
One of them is upgrading `react-native-router-flux`. It seems beautiful and it uses the original React-Native Navigator component. I think that is great. However I have to create new appropriate NavBars for Android and iOS. 

Nontheless, I think that way is the correct.

**Comment by aksonov** [comment]
@efkan You could still use v2. v3 seems more like experimental. I was wrong when thinking that when NavigationExperimental component became part of React Native it will be 'stable'.

If you choose to use v3, feel free to improve existing NavBar and submit PR.

**Comment by shivangbtech** [comment]
getting error :
'props should be defined for stack'
while using sample:
https://github.com/efkan/rndrawer-implemented-rnrouter

**Comment by mmazzarolo** [comment]
@lynndylanhurley did you find any way to handle that kind of navigation on `react-native-router-flux 3`?  
I'm working on something that in my opinion sounds really vanilla but it still seems too hard to achieve in this version: drawer on some main routes, no drawer in sub-routes.  
I'm facing a lot of issues: un-needed sub-schemes, the title sometimes doesn't work, the back button is not rendered etc... I'd love to help but unfortunately I have no time :(  

It worked perfectly on the previous version but sadly it seems to have a lot of problem now... I think I'm going to drop this router until it become more stable.  

P.S.:
**DefaultRenderer:** 
```javascript
_renderHeader(/*NavigationSceneRendererProps*/ props) {
        return <NavBar
            {...props}
            getTitle={state => state.title}
        />;
    }   
```

**NavBar:** `this.props.getTitle` can't be `null` here, am I right?
```javascript
_renderTitle(childState: NavigationState, index:number) {
        const title = childState.renderTitle ?
          childState.renderTitle():this.props.getTitle ? this.props.getTitle(childState) : childState.title;
```

**Comment by tiempham** [comment]
Use my way: `    renderRightButton={() => <SmallAvata />}
                               renderBackButton={()=> <Icon name={"nav-button"} size={16} color="#fff"/>}
                               renderLeftButton={() =>  <Icon name={"nav-button"} size={16} color="#fff"/>}
                               hideBackImage={true}`
use this in Scene options.
