### ISSUE TITLE
Please STOP creating new and new issues regarding 0.23 version, component requires 0.22 now

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#525]
README clearly states that 0.22 is required. About 10 issues are almost the same, what sense to create more? If you really do want to help, submit PR, otherwise wait until someone will fix it. 

It doesn't make to sense to fix it for 0.23, because 0.24 changes navigation staff again, so it is more question to React Native, when API will be stable.

You still can use v2 version with old navigation to avoid these things.

**Comment by cridenour** [comment]
Thanks for your hard work! I'm willing to take a stab at 0.24 integration this weekend, if there is any existing work or contributors working on this, if you're willing to help herd us so we're not doing unnecessary work, that would be helpful!

**Comment by aksonov** [comment]
Don't have free time to work on it yet, so feel free to submit PR this weekend, thanks!

**Comment by cridenour** [comment]
Will do!

**Comment by rlau1115** [comment]
Thanks for all of your hard work on this guys. Really appreciate it! Pretty swamped on my end with deadlines but will try to contribute when my time frees up.

**Comment by FearMediocrity** [comment]
I've submitted #534 to bring the Example app in to line with the currently supported version

**Comment by lelandrichardson** [comment]
FYI, support for 0.24 is blocking AIrbnb from upgrading to 0.24, and we will be preparing a PR to upgrade this lib for 0.24 support today (hopefully).

**Comment by aksonov** [comment]
@lelandrichardson Will it be different from 3.24 branch? The problem is not in absence of PR but that 0.24 contains bugs and they are confirmed by NavigationExperimental authors. The only solution i see is to move whole NavigationExperimental from latest RN master into this component (if master already contains fixes, of course)...

**Comment by lelandrichardson** [comment]
@aksonov thanks for this context. I'm just sort of jumping into this now...

Is there a discussion thread where I can understand better the bugs you are referencing in RN 0.24?  If so, I will try and get them cherry-picked into 0.25-rc (if they aren't already)

**Comment by aksonov** [comment]
It is distributed across many issues :)
Some attempts to aggregate: #489, #557

**Comment by alanzanattadev** [comment]
Am I the only one who has a problem with renderRightButton ? It worked with 0.22 but doesn't work anymore. Nothing is displayed, or maybe it's under the navbar layer.

**Comment by aksonov** [comment]
Closing it for now, but probably we will have the same story with 0.27 now :)
