### ISSUE TITLE
'Without Animation' not working

### ISSUE THREAD

**Issue by dunhuang** [aksonov/react-native-router-flux#527]
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.2.13
- react-native v0.22.2

'Go to Register page without animation' appears same effect as 'Go to Register page'
I don't know how to push scene without animation.

**Comment by aksonov** [comment]
Should work with latest version, please check. Closing it for now.
