### ISSUE TITLE
How do I get the current screen?

### ISSUE THREAD

**Issue by lynndylanhurley** [aksonov/react-native-router-flux#528]
### Version
- react-native-router-flux v3.2.11
- react-native v0.22.0

### Expected behaviour

I used to be able to track this using the `BEFORE_FOCUS` and `AFTER_FOCUS` actions.

### Actual behaviour

There are no longer any `*_FOCUS` events dispatched.

So how do I get the name of the current screen?

**Comment by yang515648779** [comment]
I also want to ask this.

**Comment by lynndylanhurley** [comment]
Just pushed a fix. See #531

**Comment by lynndylanhurley** [comment]
See also #537.

**Comment by aksonov** [comment]
#537 is much much better, thanks.
