### ISSUE TITLE
How to refresh after Actions.pop()?

### ISSUE THREAD

**Issue by helloworld123456** [aksonov/react-native-router-flux#529]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.2.2
- react-native v0.23.0

### Expected behaviour
Say there is a listview, when choose an item from the list, push the detail page, 
in the detail page use Actions.pop() back to the list page
I want the listview get refreshed right after the Actions.pop()
How can I implement this?please help me...

### Steps to reproduce

1.
2.
3.

**Comment by Elyx0** [comment]
Actions.pop();
Actions.refresh(); ?

**Comment by helloworld123456** [comment]
@Elyx0 
: ), thank you, it works!

**Comment by burgalon** [comment]
Doesn't it make sense for pop({params}) to act like pop() + refresh({params}) ?

**Comment by aksonov** [comment]
It will be good addition, PR is welcome!

**Comment by burgalon** [comment]
I'm looking at Reducer.js POP_ACTION and wanted to add `...props` similarly to refresh but it doesn't seem like it's working out

**Comment by nbkhope** [comment]
To cause the data in your list to be updated when you pop to that initial scene, you can pass back a dummy prop like `Actions.pop({ updated: true })`. Then, in your initial scene component, set up a lifecycle method componentDidUpdate to fetch the data if the `prevProps.updated != this.props.updated`. For more details, see https://stackoverflow.com/a/44360099/5326603
