### ISSUE TITLE
onPop being called?

### ISSUE THREAD

**Issue by MITDelian** [aksonov/react-native-router-flux#53]
onPop doesn't seem to be called when the back button is pressed

**Comment by aksonov** [comment]
Right, because it is out of the component control... Maybe i will remove onPop entirely in favor to onLeave function call (available within 1.0.7 as Route prop), that is called when route loses focus.

**Comment by aksonov** [comment]
Should work in 2.0.3

**Comment by michalpetrov** [comment]
Still not working in 2.0.5

**Comment by aksonov** [comment]
It works fine on my side, for example for Tab#1_2 view.
                        <Route name="tab1" schema="tab" title="Tab #1" >
                            <Router onPop={()=>{console.log("onPop is called!"); return true} }>
                                <Route name="tab1_1" component={TabView} title="Tab #1_1" />
                                <Route name="tab1_2" component={TabView} title="Tab #1_2" />
                            </Router>
                        </Route>

**Comment by Proyoyo** [comment]
Works fine for me. I'm using 2.0.5.
