### ISSUE TITLE
Adding Promise compatibility to selector function for Switch component 

### ISSUE THREAD

**Issue by Iliyass** [aksonov/react-native-router-flux#532]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.?.?
- react-native v0.?.?

First of all, thanks for this repo.
I have been looking for an authentication filter/middleware to implement in the router, so, I found out that you already have this as Switch component and a selector function, but the problem I had with it, is that I was checking the Storage for a data, based on it, I have to decide to where I should redirect him, the storage is Promise based, and selector doesn't support promises.

so, I have edited the Switch updateState function to support Promises or sync function, so my result is like the code below

```
    redirectToSelectedKey (selectedKey, props){
        const navState = props.navigationState;
        const selected = navState.children.filter(el=>el.sceneKey == selectedKey) || console.error("key=" + selectedKey + " doesn't exist");
        const navigationState = selected[0] || console.error("Cannot find scene with key=" + selectedKey);
        if (navigationState.key != navState.children[navState.index].key) {
            Actions[selectedKey]();
        }
        this.setState({navigationState});
    }
    updateState(props){
        const selector = props.selector || console.error("selector should be defined");
        const returnedValue = selector(props)
        if(returnedValue instanceof Promise) {
            return selector(props)
                    .then(selectedKey => this.redirectToSelectedKey(selectedKey, props))
                    .catch(err => console.error("selector should return key"));
        }
        const selectedKey = returnedValue
        this.redirectToSelectedKey(selectedKey, props)

    }
```

It's working fine for me, I don't know if my approach is wrong, if so, let me know, I can push a pull request if you want to.

Thanks again for this repo :+1:

**Comment by aksonov** [comment]
Looks very nice, feel free to submit PR & add docs to README.
