### ISSUE TITLE
How to get navigator object inside component?

### ISSUE THREAD

**Issue by vdrg** [aksonov/react-native-router-flux#544]
Hi!

Is there any way to get the navigator inside a component? I need it in order to use [LightBox](https://github.com/oblador/react-native-lightbox/) (it needs to get the navigator passed into it's props) 

Thanks!

**Comment by cridenour** [comment]
That component seems to be expecting an instance of https://facebook.github.io/react-native/docs/navigator.html but this library uses NavigationExperimental, which doesn't have a compatible API.

**Comment by vdrg** [comment]
oh ok :(

Thanks for your help!
