### ISSUE TITLE
Back button Style

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-router-flux#546]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.24.0
- react-native v0.24.0

### Expected behaviour
barButtonIconStyle changes backbutton icon style

### Actual behaviour
barButtonIconStyle does not change back button icon style

### Steps to reproduce

1.Add barButtonIconStyle to the main scene
2. Push to another scene
3.

**Comment by aksonov** [comment]
#525 ?
