### ISSUE TITLE
Actions.xxx no response

### ISSUE THREAD

**Issue by gerard0315** [aksonov/react-native-router-flux#548]
Hi, this may seem a bit silly but I am actully a beginner in this but it seems I can't get the routings to work.

This is my index.ios.js
`
import React, {AppRegistry, Navigator, StyleSheet, Text, View} from 'react-native'
import {Scene, Router, TabBar, Modal, Schema, Actions, Reducer} from 'react-native-router-flux';

window.React = React;

var Login = require('./components/Login1');
var MainPage = require('./components/MainPage');

const reducerCreate = params=>{
    const defaultReducer = Reducer(params);
    return (state, action)=>{
        console.log("ACTION:", action);
        return defaultReducer(state, action);
    }
};

export default class SimplyPark extends React.Component {
    render() {
        return 
        <Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'}}>
            <Scene key="modal" component={Modal}>
                <Scene key="root" hideNavBar={true}>
                   <Scene key="Login" component={Login}/>
                   <Scene key="MainPage" component={MainPage} title="SimplyPark"/>
                </Scene>
            </Scene>
        </Router>;
    }
}
`

This my part in routing:
`<TouchableHighlight style={styles.signin}
      onPress={Actions.MainPage}>
       <Text style={styles.whiteFont}> {this.state.isLogedIn ? "go": "Sign In"} </Text>
  </TouchableHighlight>`

I used my Iphone6s on iOS9.3.1 and RN version 0.24.0 to test.
Thanks !!!!

**Comment by jeroenbourgois** [comment]
Very weird, but I seem to be having the same issue. The initial page is loading just fine, any actions from there on seem to be muted.

**Comment by jeroenbourgois** [comment]
@gerard0315 what version of React are you using? Check you `package.json` please.

**Comment by gerard0315** [comment]
@jeroenbourgois I'm using React 0.14.8 and RN 0.24.0,RN is latest but React is not. However aksonov is using the same setup.

**Comment by jeroenbourgois** [comment]
Ah... but the current version of the router requires RN 0.22, or are you using the latest master version instead of the stable one?

**Comment by gerard0315** [comment]
@jeroenbourgois yes I'm using v3.24 of the router

**Comment by Iliyass** [comment]
The same error, I thought it's just me. 
RN : 0.23.1
RN router flux: 3.2.13

**Comment by gerard0315** [comment]
have you tried author's example @Iliyass ?

**Comment by gerard0315** [comment]
@jeroenbourgois oh i see, it's sort like https://github.com/aksonov/react-native-router-flux/issues/525. Author added support for RN0.24 yesterday I thought it would work

**Comment by gerard0315** [comment]
@Iliyass please see https://github.com/aksonov/react-native-router-flux/issues/525, the stable version supports only RN0.22 now i think

**Comment by aksonov** [comment]
#557
