### ISSUE TITLE
Tab bar icons support

### ISSUE THREAD

**Issue by jfsemaan** [aksonov/react-native-router-flux#55]
Hi,

Is there a way to include icons instead of text on each tab?

Thanks.

**Comment by aksonov** [comment]
Sure, just define your TabIcon which will display image and add image source attribute to route (it will be passed to your TabIcon component).

**Comment by MITDelian** [comment]
Here is an example of how I did it:
```js
            <View style={styles.tabContainer}>
              <Icon
                name={this.props.tabIcon}
                size={24}
                color={this.props.selected ? '#444' :'#AAA'}
              />
              <Text style={[{color: this.props.selected ? '#444' :'#AAA'}, styles.tabIcon]}>{this.props.title}</Text>
            </View>
```

I'm using `react-native-vector-icons` as my icon manager

**Comment by MITDelian** [comment]
@jfsemaan feel free to reopen this if you have any other questions
