### ISSUE TITLE
undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal

### ISSUE THREAD

**Issue by masterkrang** [aksonov/react-native-router-flux#552]
Just `npm install`ed today on my project, getting this error `undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal`.

- react-native-router-flux v3.22.0
- react-native v0.23.1

### Expected behaviour

Should run without errors.

### Actual behaviour

`undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal`.
![image](https://cloud.githubusercontent.com/assets/452219/14646580/d78b65a4-060e-11e6-89eb-ac61b1515682.png)

### Steps to reproduce

1. npm install
2. run project in xcode (to device or simulator, error is the same)

I feel confident that this is related to react-native-router-flux because I downgraded to v3.1.5 and everything was fine.

My package.json looks like this: `"react-native-router-flux": "^3.1.5",`

Also posted to StackOverflow:

http://stackoverflow.com/questions/36722967/react-native-navigationcardstackstyleinterpolator-forhorizontal-undefined

**Comment by aksonov** [comment]
#525 ??

**Comment by greatwitenorth** [comment]
I'm seeing a similar error:
 ```
Cannot read property 'forHorizontal' of undefined
``` 

I'm running ```react-native@0.22.2``` and ```react-native-router-flux@3.24.0```:

![image](https://cloud.githubusercontent.com/assets/547583/14647908/5f34af90-0625-11e6-9b86-c6c86dab5898.png)

not sure if this is related to @masterkrang original issue.

**Comment by lynndylanhurley** [comment]
I'm seeing this issue as well.

**Comment by lynndylanhurley** [comment]
Hi guys, please try https://github.com/aksonov/react-native-router-flux/pull/553 and let me know if it solves the issue.

**Comment by cridenour** [comment]
So I'm pretty sure this is because you're running 3.24 while running 0.22. 3.24 should be for 0.24+

**Comment by GeoffreyPlitt** [comment]
I am still getting this error, even though I seem to be using all the right versions of things:

webfreelance10@p26xx-webfree10:~/eaplay_good $ npm list | grep react
├─┬ react@0.14.8
├─┬ react-native@0.22.2
│ ├─┬ babel-preset-react-native@1.8.0
│ │ ├── babel-plugin-react-transform@2.0.2
│ │ ├── babel-plugin-transform-react-display-name@6.8.0
│ │ ├─┬ babel-plugin-transform-react-jsx@6.8.0
│ │ │ └── babel-helper-builder-react-jsx@6.9.0
│ │ ├── babel-plugin-transform-react-jsx-source@6.9.0
│ │ │ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ │ │ ├── babel-plugin-react-display-name@1.0.3
│ ├── react-timer-mixin@0.13.3
│ ├─┬ react-transform-hmr@1.0.4
│ │ └─┬ react-proxy@1.1.8
│ │   └── react-deep-force-update@1.0.1
├── react-native-button@1.6.0
├── react-native-calendar-events@0.1.4
├─┬ react-native-drawer-layout@0.5.1
│ └── react-native-dismiss-keyboard@0.0.2
├── react-native-google-analytics-bridge@2.1.0
├── react-native-htmlview@0.5.0
├─┬ react-native-router-flux@3.22.23
│ └── react-native-tabs@1.0.7
├── react-native-youtube@0.6.0
├─┬ react-redux@4.4.5
│ ├── hoist-non-react-statics@1.0.6

So I'm using react@0.14.8, react-native@0.22.2, and react-native-router-flux@3.22.23.

@cridenour I saw your comment above, but I'm not able to upgrade to 0.24. What version of react-native-router-flux works for 0.22 ?

**Comment by GeoffreyPlitt** [comment]
Also, is all of this affected by the version of Android being run in the simulator? Are my versions of node modules only expected to work up to a certain version of Android? Testing with API 23 for now.
