### ISSUE TITLE
Disable horizontal swipe to go back

### ISSUE THREAD

**Issue by agrass** [aksonov/react-native-router-flux#554]
### Version
- react-native-router-flux v3.22.0
- react-native v0.24.0-rc5

It's there a way to disable horizontal swipe to go back but only for one Scene? It's because I'm already using the swipe for other thing, so when I updated RN and react-native-router-flux this functionality is 
not working anymore.

Thanks

**Comment by agrass** [comment]
I already fixed changed that scene with type 'reset' and it worked. I don't know if it's the best solution. I tried to change the direction to 'vertical' but it didn't worked

**Comment by aksonov** [comment]
#525

**Comment by agrass** [comment]
Hi @aksonov , sorry I'm using with RN 0.24 and looks pretty stable, Navegation bugs are already solved.  Anyway I already solved this with another 'type' prop in Scene, but when I change direction from 'horizontal' to 'vertical' nothing changed.

**Comment by cridenour** [comment]
0.24 may seem stable, but the underlying navigation library that this library uses was shipped with some major bugs. If you can, stick with 0.22.
