### ISSUE TITLE
Problem with redux state and Switch after upgrading RN to v0.24

### ISSUE THREAD

**Issue by zelphir** [aksonov/react-native-router-flux#555]
- react-native-router-flux v3.24.0
- react-native v0.24.1

After upgrading to RN v0.24 and the the latest RNRF something doesn't work very well using `Switch` and Redux. Everything was working fine with RN v0.22. I'm using the built-in reducer for the router.

I have something like that
```jsx
const selectorCheck = (auth) => {
  if (auth && !auth.token) {
    return 'isGuest'
  }
  return 'isAuthenticated'
}
```
to switch from one group of scenes to the other if an `auth.token` is available.

### Expected behaviour
Using the Redux debugger or a button to reset the state it should "switch" to the guest group of scenes (like it was doing with RN v0.22)

### Actual behaviour
Doesn't switch to the guest scene, the only way to do that is reloading the app using `cmd+R`

### Steps to reproduce

1. change the state in order to load the "isAuthenticated" group of scenes
2. reset the state using the redux debugger or a button (tried both)

This is how my scenes look like:
```jsx
const scenes = Actions.create(
  <Scene key="modal" component={ Modal } >
    <Scene
      key="root"
      tabs
      component={ connect(({ auth }) => ({ auth }))(Switch) }
      selector={ ({ auth }) => selectorCheck(auth) }
    >
      <Scene key="isGuest" style={ bgColor('red', 'base') }>
        <Scene key="launch" component={ Launch } title="Launch" initial />
      </Scene>
      <Scene key="isAuthenticated">
        <Scene key="onboarding" component={ OnBoarding } title="OnBoarding" initial />
      </Scene>
    </Scene>
  </Scene>
)
```

**Comment by ms88privat** [comment]
https://github.com/aksonov/react-native-router-flux/issues/525

**Comment by Olliepop** [comment]
@ms88privat react-native-router-flux v3.24.0 was released to support RN 0.24, so this is a valid issue.

**Comment by ms88privat** [comment]
@Olliepop where do I find it? I see no tag? Which of the branch is the correct one? Thanks

**Comment by Olliepop** [comment]
@ms88privat Pavel removed 3.24 after huge issues were noticed with Navigator (NavigationExperimental) in RN 0.24 - see his comment here https://github.com/aksonov/react-native-router-flux/pull/553#issuecomment-212075299

**Comment by aksonov** [comment]
#557...
@ms88privat i've reverted changes so now master is 3.22.0, sorry for confusion

**Comment by zelphir** [comment]
Just updated to RN 0.26 and latest version of RNRF (3.26.1). The problem is still present.

**Comment by rturk** [comment]
My two cents..

@zelphir what triggers **isAuthenticated**? Looks like you're using this to change the launch screen of your app? If that's the case Keep in mind that while the app is loading you'll might hit a state where redux was not fully loaded/processed/parsed and your app already started to render.

Also RN25> apps are much faster after improvements in the code, so there is a change the apps will render much faster..

If that's the case: Check this
https://github.com/fbsamples/f8app/blob/master/js/F8App.js#L80
https://github.com/fbsamples/f8app/blob/master/js/setup.js#L61

What's interesting in the F8 App is that they only start render when they have everything in place for the app to start working.

**Comment by zelphir** [comment]
@rturk The initial state of the app is handled by `redux-persist`

```jsx
render() {
    if (!this.state.rehydrated) {
      return <Loading />
    }

    return (
      <Provider hideNavBar store={ store }>
        <Routes />
      </Provider>
    )
  }
```

I've just checked that if I don't use a wrapper for the scenes it works, for instance:

```jsx
const scenes = Actions.create(
    <Scene
      key="root"
      tabs
      component={ connect(({ auth }) => ({ auth }))(Switch) }
      selector={ ({ auth }) => selectorCheck(auth) }
    >
      <Scene key="isGuest" component={ Launch } title="Launch" initial />
      <Scene key="isAuthenticated" component={ OnBoarding } title="OnBoarding" />
    </Scene>
)
```

But I have different scenes based on the user state, that's why I was using a Scene wrapper.

**Comment by zelphir** [comment]
@aksonov any thoughts?

**Comment by aksonov** [comment]
@zelphir Add some debug into selector to check if updated property is there. Btw, i've made Switch as pure function recently and it worked well for me (yes, it doesn't generate action anymore but just show proper scene)

**Comment by zelphir** [comment]
@aksonov Everything is updated but the scene. If I use the navbar, even the navbar is updated, but the `Scene` remains the same (of course also all the props are updated)

**Comment by zelphir** [comment]
@aksonov and yes... the selector is returning the right scene

**Comment by aksonov** [comment]
@zelphir Are you still using RN 0.24?

**Comment by aksonov** [comment]
Have you upgraded to latest 3.26.5?

**Comment by zelphir** [comment]
Nope, using RN@0.26 and latest RNRF@3.26.5

**Comment by aksonov** [comment]
Probably you need to create new issue then and clone & change Example to reproduce the issue.

**Comment by zelphir** [comment]
ok

**Comment by zelphir** [comment]
@aksonov Done: #760
