### ISSUE TITLE
Discussion: RN NavigationExperimental API bugs/breaking changes, future direction of the project

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#557]
Guys, I'm seriously thinking about the project direction after RN 0.24 introduced serious bugs with new navigation api:
https://github.com/ericvicenti/navigation-rfc/issues/69
https://github.com/ericvicenti/navigation-rfc/issues/50

@ericvicenti did great new navigation ("ExperimentalNavigation"), but i believe it was mistake to join it with React Native contribution because now we have to wait RN0.25 or even RN0.26 to fix it instead of quickly get fixes from 'navigation-rfc'...

Any thoughts about it? Maybe maintain own forked separated ExperimentalNavigation to avoid such bugs coming with new React Native version and do regular replacements from new react native once they are really tested? This way RNRF will be much more safe to use, i think...

**Comment by joenoon** [comment]
I did notice the "switching tab re-mounts" problem return last week.  Hopefully I'll get some time this week to try and figure out what happened.

Maybe `master` should be bleeding edge without concern for RN release versions.  So branches are cut for every RN release as they come out with a confirmed working commit for that version.  And branches could be cut for rc's as well - so maybe not even have a `master` branch.  Backporting would be rare since the goal is to keep moving forward while having branches that work with various RN versions as we go.

I think maintaining a fork would be a lot of work.  It doesn't make much sense to me to preserve and continue to use stuff they are intentionally changing upstream.  

I guess the way I see it is since its clearly marked experimental, whoever wants to use it (and by association this repo), should understand its closely tied to upstream changes, and can easily break.  I think the best we could do is let people use working combinations.  So if they want to use RN 0.24 they should use it in combination with `aksonov/react-native-router-flux#0.24-stable`.  And if that branch doesn't exist yet, they are on their own or should wait.

**Comment by aksonov** [comment]
@joenoon Thanks for the feedback. The problem that everybody wants to use latest stable React Native (because it fixes a lot of issues usually) and also wants to use latest RNRF (because it fixes a lot of issues as well). Problems begin when such combination have bugs, like we have with RN 0.24 => a lot of issues are created recently and we cannot do anything with it.

If we would use master for latest changes, it would be difficult to improve older forks then (like current most stable 3.22). So I'm still thinking to have most stable version as master and some 'experimental' versions (like 3.24) as forks which should be merged to master when all issues will be fixed.

**Comment by satya164** [comment]
@aksonov Why not copy the files into the project until the API becomes stable?

**Comment by aksonov** [comment]
@satya164 You may try to do it. The problem that the ExperimentalNavigation component uses require of internal React native libraries directly, so we have to change all 'require' calls. And do it every time for each new API change, it is what @joenoon explained above.

**Comment by satya164** [comment]
I really don't see any alternative right now. Moving NavigationExperimental into separate repo is much more difficult rather than just changing the require calls. We've to set up the Facebook infra for the separate repo, which is not simple.

**Comment by aksonov** [comment]
Could you submit PR? Maybe some shell script which will change require calls automatically...

**Comment by sarovin** [comment]
There are news for react-native 0.25 support??

**Comment by caledhwa** [comment]
In my opinion, the issues with ExperimentalNavigation will eventually get resolved. While some can't wait for that, I could. So, I'm hoping that we can get it all smoothed out again by 0.25-0.26. Since they are working on 2 week releases, I'm hoping that we're really only looking at a month at most of waiting for issues to be resolved. I like RNRF and I'd love to see it move forward with RN. While ExperimentalNavigation was a mess of bugs, I'd guess that once it gets smoothed out, it won't happen like that again for awhile. Anyhow, my two bits!

**Comment by joenoon** [comment]
FWIW I've been using this combination successfully:

```
    "react-native": "0.24.1",
    "react-native-router-flux": "aksonov/react-native-router-flux#3.24"
```

I'll probably start looking at 0.25 this week.

**Comment by sarovin** [comment]
There isn't bug with rn 0.24.1?

**Comment by farwayer** [comment]
@sarovin there are bugs with `replace` type still :(

**Comment by ndarilek** [comment]
Just found this project today. Honestly, I think the fact that we can build native mobile apps cross-platform is pretty awesome in and of itself. I'd be happy to remain a RN version or so behind if it means I can use someone else's great module to ease app development, and routing/navigation is enough of an RN pain point that I'm happy to be a bit more conservative with upgrades if it means someone does the hard work of building a good router for me.

It might be enough to simply update the README.md with the latest working, stable combinations. If that means this only works with RN 0.23, then that's just a price people pay to have a decent routing solution. It seems a bit unrealistic for folks to expect you to keep up with RN when it is a rapidly-evolving project and you presumably have your own work and projects to maintain a living.

That said, what are the most recent known working combinations? I'm attempting to integrate this and am wondering if anything works with 0.24 or if I need to wait for 0.25. Unfortunately I've already updated my project and don't want to roll it back, but in the future I can hold off on upgrades if it means working with good third-party modules.

Thanks.

**Comment by joenoon** [comment]
@ndarilek you can try this combination with 0.24: https://github.com/aksonov/react-native-router-flux/issues/557#issuecomment-215235588

I've seen comments where others have run into an issue with 'replace' route types, but my app doesn't use that functionality so I haven't run into it myself.  I'm also using a custom NavBar, so its possible there are other issues I'm unaware of.

**Comment by spaceoi** [comment]
@joenoon The title didn't display in tabbar sub-scenes, and buttons didn't display correctly either for rn0.24 + rnrf#3.24 in iOS. Do you have a solution for this?

**Comment by joenoon** [comment]
@spaceoi I dont use the default NavBar, but I did stumble onto the title issue by accident.  If I remember correctly it was related to this change: https://github.com/aksonov/react-native-router-flux/commit/fe5da322d392117e7d51a382ae8584c2d7f45936

@philipshurpik do you remember the reason for that change?  

Just glancing it looks like `child` and `selected` both point to the same thing.  Maybe `state` was removed accidentally instead of one of the duplicates?

**Comment by spaceoi** [comment]
@joenoon Actually I think this is a different bug. The _renderTitle method runs several times and the last run will show as the title in the NavBar. For example the click of 'Switch to tab1' shows runs 3 times _renderTitle method: tab1_1, launch and tabbar, and the title displays tabbar's title, which is undefined, instead of tab1_1's title, which is the correct result 'tab1_1'.

**Comment by ptomasroos** [comment]
react-native has 0.26 has now a rc released since 5 days ago.

**Comment by Olliepop** [comment]
Fixes didn't make it into 0.26. Holding out for 0.26.1.

**Comment by ptomasroos** [comment]
@Olliepop what fixes are you referring to?

**Comment by aksonov** [comment]
@joenoon 0.26 is out, should we merge wip-0.26 to master?

**Comment by aksonov** [comment]
0.27, 0.28-rc all they have breaking changes. Maybe it is really worth checking to copy NavigationExperimental sources into this component, so it will work with any RN version? And merge them from time to time to improve things...

**Comment by farwayer** [comment]
I don't think it is good idea to have separate copy of NavigationExperimental. It can become very different from original source very soon. imho it is better to wait API stabilization. The presence of the version matrix and supporting 0.28 will be enough.

**Comment by joonhocho** [comment]
Maybe ask React Native team to have a separate repo for NavigationExperimental ?

**Comment by satya164** [comment]
This has come up a lot in the past. I think you'll find this discussion useful - https://github.com/facebook/react-native/issues/6184

**Comment by jmurzy** [comment]
@joenoon 

I've experienced similar [issues](https://github.com/jmurzy/react-router-native/issues/2) in my own project. 🤕

To answer your question:

> does this solve the problem with RN versions? Or are the copied sources still possibly dependent on certain RN features with the version it was released in?

I believe it should solve your problems with React Native versions, and no, ``NavigationalExperimental`` isn't currently dependent on specific versions of React Native. I'm still not sure if I'd recommend forking as ``NavigationalExperimental`` is still a moving target and the new ``NavigationTransitioner`` comes with its own set of [issues](https://github.com/jmurzy/react-router-native/issues/3) that need to be addressed before it can replace ``NavigationAnimatedView``, &c. 

But given the current state of this project it might be worth a try, and as I also mentioned in ericvicenti/navigation-rfc#81, [here](https://github.com/ericvicenti/rn-sample/tree/master/react-navigation )'s how you'd do it. 

As for your proposed alternative approach:

I've been making some exciting progress on this front, [react-router-native](https://github.com/jmurzy/react-router-native). [shameless plug] 

And for those of you who are interested, here's the pitch:

> React Router community decided that a [reducer-based paradigm](https://github.com/reactjs/react-router/issues/743) similar to that of **NavigationExperimental** is better suited to native navigation. Transition to a reducer-based paradigm is also being [discussed](https://github.com/reactjs/react-router/issues/3190) for the web. On the other hand, NavigationExperimental [has no intention to support ](https://github.com/ericvicenti/navigation-rfc/issues/64#issuecomment-209001717) a React Router-like interface and leaves the navigation state up to the developer to maintain.

> A declarative API removes the need to write [boilerplate code](https://github.com/facebook/react-native/commit/1dc33b5f23640a60682ac879b9a3e94a4aa519d9) and speeds up development. React Router Native follows React's __Learn Once, Write Anywhere__ principle by providing **a superset of React Router's API that marries _React Router_ to _NavigationExperimental_**.

Feedback is greatly appreciated. 😅

**Comment by aksonov** [comment]
@jmurzy Looks like your wrote your router **once**, but selling it **anywhere** :) Okey, if seriously, here is my feedback - but please don't start discuss it here (you may use your topic jmurzy/react-router-native#7 for that, you could quote my feedback there if you want), because it is really offtopic here and i don't know why i didn't remove your post (probably because first half is quite useful, thanks! :)

I don't think that url-based navigation works well for native, but probably it is very subjective. For example for me it is much easier to use `Actions.user(123)` not `dispatch("/user/123")` or even better: `Actions.post({user, post})` instead of something like `dispatch("/user/123/post/1234")` where user and post are well defined domain objects (it could be observable model from MobX).

It is very easy to add deep linking to this component as described here #704, but looks like our community doesn't need it much. URL is boilerplate _itself_ and it is popular because it is needed for web. URL is form of serialization of an user request and RNRF just uses original user request because it is not necessary to serialize/deserialize data to/from URL for native apps. However you could do deep linking with RNRF easily if needed.

**Comment by aksonov** [comment]
Okey, 3.30.0 version doesn't depend from 0.26 anymore (i've forked NavigationExperimental API to separate package). We will update fork (react-native-experimental-navigation) when new changes within Experimental Navigation API will be made (we could clone even latest master fixes now!). Also we will update this component to work with latest version API but it is not so critical now (now component still depends from 0.26 API, but not from React Native 0.26)

Feedback is welcome.

**Comment by aksonov** [comment]
When ExperimentalNavigation API will be stabilized AND our Router will be changed to use it, we will switch from fork to RN again. I'm glad that ExperimentalNavigation 0.26 doesn't depend from core, so fork was not difficult to do (mostly just replace import paths), i'm closing this issue for now.
