### ISSUE TITLE
Discussion: the component usage within real apps

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-router-flux#558]
Please post your apps here and submit PR to add it to special section to README.

**Comment by sibeliusseraphini** [comment]
This is not a complete app, but it is a good start point

https://github.com/sibeliusseraphini/react-native-redux

It has a login screen, and it uses redux, redux-saga, redux-storage and this package to manage the routes

It uses the 2.x api, but I will update it when I have time

**Comment by donnguyen** [comment]
@aksonov I have created a PR to add my recent published app that using this plugin here, please have a look https://github.com/aksonov/react-native-router-flux/pull/712
