### ISSUE TITLE
Documentation example on how to integrate with a redux/flux architecture

### ISSUE THREAD

**Issue by jmacedoit** [aksonov/react-native-router-flux#56]
"The component doesn't depend from any Flux implementation and allows to intercept all route actions by adding Actions.onPush/onReplace/onPop handlers from your store(s)"

I think an example on how to accomplish this would be very valuable. From inspecting the code, I have an idea on how I could do it, but I'm not sure if it's the proper way.

**Comment by aksonov** [comment]
The problem that for now i don't see use cases to use onPush/onReplace/onPop, maybe you could provide some use cases when it is needed?

**Comment by jmacedoit** [comment]
Perhaps a "log out" case where you need to manipulate some data and pop?

**Comment by aksonov** [comment]
Again, i don't see how onPop could be used here. You just executes two actions, one - logical, 'logout' for your flux/redux which will manipulate all needed data and doing pop at the same time...

<Button onPress={()=>{Actions.pop(),this.dispatch(logout())} }>Logout</Button>

**Comment by herby** [comment]
Yeah. just some hint, please. I just don't know how to combine that with a state.

**Comment by aksonov** [comment]
I believe info passed via react context. Check it http://rackt.org/redux/docs/basics/UsageWithReact.html
I'm just using these two steps and everything works well (root Provider, then connect each screen).
Maybe you could do redux demo, it would be really great.

**Comment by herby** [comment]
I have read though the that page already, thanks. I understood how to connect things there, but there, root (in App.js) was connected, and it was passed state to `select` function, where it selected relevant subsets and used then directly in the render JSX in the components.

But here, those components are not specified at all. There are only routes. I do not understand how the data gets passed to the 'screen' components themselves (or do I add it to the `Route` and it gets passed down to the component?)

**Comment by aksonov** [comment]
For Route you define 'component' class, that class should be 'connected'. Data passed via inner context, as i understand.

**Comment by herby** [comment]
Ok, I probably understand now. I use `Provider` to specify store for an app, and then I need to connect every single 'visual' component, adding specific select function for each of it (so every one select its own relevant subset), and if I have hierarachy of visual components, then I connect the roots of the trees in the visual forest (and passing the rest down via props as shown in other redux-react tutorials). Am I right @aksonov?

**Comment by aksonov** [comment]
Right

**Comment by herby** [comment]
Thanks. ;-)

**Comment by jmacedoit** [comment]
You are right, and I agree with you. I just lacked a better example - The thing is I'm coming from your other implementation using redux and I have a mix of questions that I'm not sure are related...I'm starting to think that my true question is related to custom actions.  In redux router, your reducer returned a state which was used by the router component to know how it should render itself. I could, however,  create my own reducer to process custom actions that were  supposed to change  the route stack in a way different than the simple push /pop /replace primitives. What is the way to accomplish that here ?  Is it related to onPop, onReplace, etc...?

**Comment by aksonov** [comment]
Please give me real use case, I will think about it

Pavel.

**Comment by jmacedoit** [comment]
Please let me know if this should be in a different issue:

Imagine there's  **Login**, **MembersArea** and **EditProfile** scenes/routes. And that after the user logs in, I want him to go to **EditProfile**, but with **MembersArea** also in the stack, and not **LogIn**.

So this is the route stack evolution I want:
```
[Login]----logs in---->[MembersArea,EditProfile]----back (pop)--->[MembersArea]
```
How am supposed to do the log in step in terms of Action calls?

**Comment by drojas** [comment]
Hi, thanks for sharing this, it's very valuable. This is what I'm doing, please correct me if there is a more "idiomatic" way to do it.

Logic that I want `attached` to a specific routing event (like navigate from here to there implies that ...) is being dispatched as plain actions alongside the routing action. But, logic that should be `attached` to every routing event (like serialising, remote controlling, automatic fetching) is embedded in some "higher order action" that manages routing actions.

PS: However, as the routing actions are abstracted away, it's not 100% clear how to achieve what @jmacedoit is trying to do with the stack. Perhaps a public api for action creators might be a good approach.

**Comment by mangogogos** [comment]
So Im gathering that route components MUST be connected? The design I had in mind is a container which is connected and passes those props down to purely visual scenes, chosen by the current route. Is there a way I can get this type of behaviour without having to connect too many components? I really don't need to have any components but the container be connected

**Comment by jmacedoit** [comment]
With the redux specific implementation version -  https://github.com/aksonov/react-native-redux-router -  it was possible to create custom actions... This is precisely what I would like to do with this implementation (since the other is being discontinued) ...

**Comment by aksonov** [comment]
@mangogogos Do you want Router will pass all own props to children? Looks good idea, please confirm.

**Comment by aksonov** [comment]
@jmacedoit Why you  need 'custom' actions, please describe user case here

**Comment by aksonov** [comment]
@jmacedoit [Login]----logs in---->[MembersArea,EditProfile]----back (pop)--->[MembersArea] - I'm going to add 'initial' action which will setup given navigation stack, will it work for you?

**Comment by jmacedoit** [comment]
I'm not sure I understand... You will create an action where it is possible to specify the stack?

**Comment by aksonov** [comment]
@jmacedoit Yes. Something like Actions.reset([stack])

**Comment by aksonov** [comment]
@drojas I'm still don't understand clearly about custom actions/action creators, etc. For example for some your redux action you need to pop/push or reset stack or something. Why you can't just declare that action and call Actions.ACTION inside your Redux action ?

**Comment by mangogogos** [comment]
I had more in mind that having a connected component contain the router would cause state changes to propagate to the current scene. I have a container which is subscribed to a redux store that has inside it a router. The container takes its props and delegates them to the routes but even though the container was updating with state changes, it didn't seem like the routes were updating to receive the new values

**Comment by aksonov** [comment]
@mangogogos Yes, routes are not updating corresponding component currenty, because they don't render nothing and use just to give values for parent Router. As I said above i need clear use cases to understand the problem.

**Comment by mangogogos** [comment]
Would you suggest just connecting all subcomponents then? To me that seems to go against redux but you would consider every route to be a container?

**Comment by herby** [comment]
I was asking my original question exactly because I had similar feeling. I got the answer that, yes, the each "root" visual component (the first the is visual in the tree, IOW its parent is route) should be connected. That shouldn't be that much components, and I see added value in the fact that each connect call will use its own select function.

But yes, I had the impression that actually, the root router is connected and data is somehow passed down.

The problem I see here is, that unnecessary data may be computed / processed - the whole route tree must process the whole store (as the whole store will be undoubtedly connect to the root router) and subsets selected on the way down. As I am new in flux-like thing and react as well, in fact, I don't know if this case can be optimized good enough (while the connect(selectFn) probably can, as it is the core redux principle).

Jacob Patenaude wrote:
> Would you suggest just connecting all subcomponents then? To me that 
> seems 
to go against redux but you would consider every route to be a

**Comment by aksonov** [comment]
It is quite easy to pass all Router's props to Route's components, but I'm concerned a little that some/major unnecessary props will be passed if Redux state is large, and screens will need only some small sub-set of it.  Also props like style, hideNavBar could be a problem.

**Comment by mangogogos** [comment]
This seems fair! I will redesign my selectors and give it another go, thanks!

**Comment by aksonov** [comment]
Both points (connect once or connect 'each') have own props/cons, check nice discussion here https://github.com/rackt/redux/issues/419

**Comment by aksonov** [comment]
Maybe I could introduce 'connect' Route property where you could list all defined props to pass to this route from parent Router? Does it sound good?

**Comment by mangogogos** [comment]
That would be a great compromise! Allows scene components to be oblivious to redux but still adds selective behaviour
+1

**Comment by herby** [comment]
I am still afraid if ir does not mean too much processing and if some wrapper which is `connect`ed should not pass these to the visual component (which can be its required child). Something like <Redux select={state => ({foo: state.foo, bar: state.baz.bar})}><VisualComponent quux="moox">...</VisualComponent></Redux>, which would pass foo and bar to VisualComponent props in addition to quux specified explicitly and renders the connected version of itself using the injected select function.

But maybe connect itself is not very magical and passing down substate in props just does the same... I don't know.

Jacob Patenaude wrote:

**Comment by herby** [comment]
Oh wait, I happened to come up with interesting idea. Maybe even brilliant one ;-).
What if instead `component={Foo}` I used `component={connect(selectFnForFoo)(Foo)}`. Isn't it all that's needed?

**Comment by aksonov** [comment]
Yes, it should work! :)

**Comment by aksonov** [comment]
But syntax is more complex comparing with connect="foo"

**Comment by herby** [comment]
But it does what @mangogogos wants, in the sense, the visual components can stay oblivious to Redux, as `connect` call is done externally, in the router, not in component definition.

From my PoV the syntax is only just an bit more complicated. Hm. I'll try that (I even do not fear to put select functions inline - I will see what is selected directly at the right place).

**Comment by aksonov** [comment]
Ok, i don't want to make component more complex too, so let's use inline connect.

**Comment by mangogogos** [comment]
yeah inlining like that should work! thanks @herby looks like everything I needed was there all along!

**Comment by drojas** [comment]
@aksonov I wasn't aware of the possibility to alter the stack directly via actions. Thanks!.

**Comment by Everhusk** [comment]
@herby Brilliant idea indeed :+1: Just a question about how you structure your RN app, do you keep your entire router defined in one file, or do you split it up?

**Comment by Everhusk** [comment]
Also, do you nest your components under the container they should be a part of? For example
<Route name="container1">
<Router>
<Route name="component1a"/>
<Route name="component1b"/>
</Router>
</Route>
<Route name="container2">
<Router>
<Route name="component2a"/>
<Route name="component2b"/>
</Router>
</Route>

**Comment by herby** [comment]
I personally do it in one file, I did not use nesting yet. To keep components decoupled, I also tend to add `next={foo => Actions.bar({foo:foo})}` like props to the route that gets propagated to the component, so I can easily rewire the order in which components are, if the component is "UNIXy" or "middlewarey" enough, so the "next screen" is not hardwired.

**Comment by thngdude** [comment]
@herby, I'm trying to figure out how to implement your solution. Where and how would you define the selectFnForFoo function?

Also, I'm assuming you would also have to define something like the following in the component?
`export default connect(state => ({
    state: state.counter
  }),
  (dispatch) => ({
    actions: bindActionCreators(counterActions, dispatch)
  })
)(CounterApp);`

Thanks

**Comment by herby** [comment]
Contrary to tutorials, there isn't connect call in export clause of a component. Bare class is exported. The connect call is in Route itself, like `component={connect(state => ({...subset of state...})(ComponentClass)}`. And it is juat mattwr of style if you inline the function as above, or declare it first and juat reference it by name.

**Comment by thngdude** [comment]
@herby I got it working. Thank you!

**Comment by aksonov** [comment]
I'm thinking about possibility to set global handler for Actions, it will simplify things much. Maybe someone can suggest PR for that? You may create even ReduxHandler which will be set once and send redux actions to dispatcher.

**Comment by herby** [comment]
@aksonov I don't understand what you want to do from your description... I can just point on two things, from the partial try to understand:
 1. You are redux/flux agnostic now, which is nice thing; is the thing you are thinking of gonna break it?
 2. I use es6 `import` / `export` (with help of RN built-in babel), which is (syntactically) static and does not allow to monkeypatch what is exported. Won't your approach rely on that?

**Comment by aksonov** [comment]
Actually this component is exNavigator agnostic as well, but have kind of 'plugin', ExRouter to connect with ExNavigator UI. Another plugin could be implemented for Native iOS Navigator or for navbar component from 0.3 version. The same concept could be used for handlers. Actions.handler could be set to some handler and be called before any action. This handler could be 'redux' aware, i.e. call something like route.props.dispatch(PushReduxAction(name, props)), so you could subscribe to PushReduxAction and other redux actions from your store.

**Comment by aksonov** [comment]
Please check latest demo for 2.2.0 release.

**Comment by jonlong** [comment]
@Everhusk did you end up connecting a nested route structure like the one you referenced [here](https://github.com/aksonov/react-native-router-flux/issues/56#issuecomment-173820238)?

I'm trying to do exactly the same thing, but having a tough time figuring out how the props would get from `container2` to `component2a` in your example.

**Comment by aksonov** [comment]
3.0 is released with improved docs. Closing it for now, because it is for outdated version (2.x)

**Comment by matt-d-rat** [comment]
@aksonov I am also getting the ```console.error: "selector should be defined"``` error:

__scenes.js__
```js
import React from 'react';
import { Actions, Scene, Switch } from 'react-native-router-flux';
import { connect } from 'react-redux';

import Login from './containers/Login';
import Home from './containers/Home';

export default scenes = Actions.create(
    <Scene key="root"
           component={connect( state => ({user:state.user}) )(Switch)}
           tabs={true}
           selector={props => props.user.accessToken ? 'home' : 'login'}>
        <Scene key="login" component={Login} title="Login"></Scene>
        <Scene key="home" component={Home} title="Replace"></Scene>
    </Scene>
);
```

__main.js__
```js
import React, { Component } from 'react-native';
import { Router } from 'react-native-router-flux';
import { Provider } from 'react-redux';
import configureStore from './store/configureStore';
import scenes from './scenes';

const store = configureStore({});

export default class Main extends Component {
    render() {
        return (
            <Provider store={store}>
                <Router scenes={scenes} />
            </Provider>
        );
    }
}
```

My project has the following dependencies at these versions:

```json
{
    "react-native": "0.22.0-rc",
    "react-native-flip-view": "1.0.4",
    "react-native-google-signin": "0.4.3",
    "react-native-router-flux": "3.0.15",
    "react-native-vector-icons": "1.3.2",
    "redux": "3.3.1",
    "react-redux": "4.4.1",
    "redux-logger": "2.6.1",
    "redux-thunk": "2.0.1"
  }
```
