### ISSUE TITLE
How to get the navigation bar Dimensions from within a Schene?

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#561]
For example lets say I'm within my Login schene. How can I access the navigation bar and get for example its height?

Thank you..!

**Comment by aksonov** [comment]
Sorry, it is out of scope of this component, it is about react native programming. I guess you should use onLayout handler

**Comment by SudoPlz** [comment]
Could this perhaps be a future feature or should I just close the issue?

**Comment by aksonov** [comment]
It is not planned, but you may submit PR.

**Comment by SudoPlz** [comment]
On which file should I look for the Navigation bar component and its styles?

**Comment by aksonov** [comment]
NavBar.js

**Comment by SudoPlz** [comment]
Ok thanks!

**Comment by SudoPlz** [comment]
Hey @aksonov , I found a way to get the dimensions of my NavBar, but I'm currently trying to figure out a way to pass that object with the width and height back to the user. If your project was using redux, I would dispatch an action to save it to the current state, but I'm so confused on how to pass that object to the end user with your library. Any suggestions please?

**Comment by aksonov** [comment]
Use Actions.refresh(data). You may specify key of scene where you want to pass that data.

**Comment by SudoPlz** [comment]
Ok so since my pull request was not accepted, here is how to set your View to render below the nav bar in both iOS and Android: 

`paddingTop:Platform.OS === 'ios' || Platform.Version > 19 ? 64 : 44,  //nav bar height`

**Comment by af7** [comment]
@SudoPlz Is this a cross-device solution?
I find that on my Samsng Android I need to use "53", so how can we be sure of the values?

**Comment by SudoPlz** [comment]
@af7 The code is no more valid. I got this code from https://github.com/aksonov/react-native-router-flux/blob/0.26-stable/src/NavBar.js#L58 but apparently this has changed in the latest version. 

Now the code has changed to :

```js

**Comment by af7** [comment]
@SudoPlz Thanks, may I assume that this is regardless of pixelRatio and same for all models of Android and iOs?

**Comment by SudoPlz** [comment]
@af7 Yes!
