### ISSUE TITLE
tab routes does not get params

### ISSUE THREAD

**Issue by ivpusic** [aksonov/react-native-router-flux#563]
- react-native-router-flux v3.22.0
- react-native v0.24.0

currently when I try to get injected params by Actions.myRoute(/.. injected params  ../) it only works if route is not tab route.

Example:

``` jsx
<Scene key="tabbar" tabs={true} >
     <Scene key="tab5" component={TabView} title="Tab #5" icon={TabIcon} />
 </Scene>
```

and now if I do `Actions.tab5({myProp: 'prop'})` I am not able to get `myProp` from TabView.

If `tab5` is not inside tab scene, then it works.

**Comment by ivpusic** [comment]
the issue is inside `case JUMP_ACTION:` in Reducer. 

Currently params are not injected into child. I did this, but still there is a problem that params cannot be removed if you call `Actions. tab5()` => in this case all params set by `Actions.tab5({myProp: 'prop'})` should be removed. Reason why this is not easy right now is because currently lib is injecting received params directly into scene, not into some dedicated scene property.

So probably we would have to introduce scene.params property, and inject/remove params passed to Actions.NAME.

**Comment by aksonov** [comment]
Why just don't pass {myProp:undefined}  to 'remove' that value?

**Comment by ivpusic** [comment]
it could be an option, but doesn't sound convenient. Also in case when we have Tabs and we use built in TabBar for navigation `<Scene key="tab5" component={TabView} title="Tab #5" icon={TabIcon} />`, then when we click on tab for this scene, action will be called (internally) as `Actions.tab5()`, so there is no way to pass additional (reset) arguments. Even if there is a way, you have to keep track of your previous params, and be careful when doing reset, which sounds, yeah...not the best solution

**Comment by aksonov** [comment]
Ok, i see. You may submit PR if you want to add this feature to component.

**Comment by aksonov** [comment]
It could be quite simple to implement, i guess. All 'core' props are stores within state.scenes, so all you need is just 'reset' them for some special key, like Actions.tab5({reset:true})

**Comment by aksonov** [comment]
Okey, i've added new feature ("scene sub-state"), maybe it could be useful for you (v3.22.15) You need to define 'special' scene (check README) and call it when you need to 'restore' your scene. It doesn't support 'containers' now (i.e. scene is restored to initial params, with no children/index), but you may submit PR to improve it.

**Comment by pampang** [comment]
@ivpusic Sorry to bother you. Like calling Actions.tab5({myProp: 'prop'}), where can I get 'myProp'?

**Comment by ivpusic** [comment]
if you are using tabs right now you cannot. my workaround was to connect router with my local redux setup. that way you will get action jump/focus and it will contain route params. then you save param to your state and you can use it. How to do that is explained here https://github.com/aksonov/react-native-router-flux#reduxflux.

**Comment by aksonov** [comment]
As I said before it should not be difficult to improve this part - i.e. interpret 'jump' also as 'refresh', i just don't have enough time to do it.
