### ISSUE TITLE
Code style linter and CI

### ISSUE THREAD

**Issue by charpeni** [aksonov/react-native-router-flux#567]
Hi there,

I'm just wondering, should we add a linter in this repo ? For the sake of consistency between multiple contributors.

I suggest the [Airbnb React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react) and it can be setup with [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), I can do that if you want to.

Furthermore, I think this repo should use a CI like [CircleCI](https://circleci.com/) it could automatically run eslinter and unit tests on each pull requests.

______

- [x] Implement eslint with [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) - (PR #574)
- [x] Fix eslint issues - #600 #601 #602 #603 #604 #605 #606 #609 #614 #625 
- [x] Add [mention-bot](https://github.com/facebook/mention-bot) to WebHooks
- [x] Add CI tests with eslint and mocha
- [x] Link with [CircleCI](https://circleci.com/)

**Comment by aksonov** [comment]
Please do, thanks.

**Comment by charpeni** [comment]
@aksonov  In addition, to improve the pull requests reviewing, i'm thinking about using the [mention-bot](https://github.com/facebook/mention-bot). Thoughts?

**Comment by aksonov** [comment]
Looks interesting!

**Comment by cridenour** [comment]
@charpeni You might want to watch out for doing both at once or every pull request is going to have you mentioned if you commit the new linted code :)

**Comment by charpeni** [comment]
Oh, you're totally right.

The linking with [mention-bot](https://github.com/facebook/mention-bot) and [CircleCI](https://circleci.com/) will needs the interaction of a collaborator with access to the WebHooks.

**Comment by cridenour** [comment]
True. I'd say, submit a PR with the new .eslintrc and such (which I agree would be an awesome addition), but let @aksonov do the big "reformat" commit.

**Comment by charpeni** [comment]
I will do the fix to the eslint problems as mentioned in #574.

@aksonov Any reason why the tabulation is not consistent ?

**Comment by aksonov** [comment]
No reason. Unfortunately webstorm sometimes doesn't do formatting

Pavel.

**Comment by aksonov** [comment]
I've fixed some problems using --fix, but there is still many. Btw, strange that 'codacy' didn't found any, and requires usage of ", but aslant requires ' ;)

**Comment by r0b1n** [comment]
Guys, I am ready to help you with fixing issues.
@charpeni any help needed?

P.S.
@aksonov Will it work wrong when `lastAction` contain property which is not exists in `action`?

https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L16-L22

**Comment by aksonov** [comment]
@r0b1n Yes, it could be, you may improve it and submit PR. Also unit tests are necessary, so you are welcome to submit unit tests.

**Comment by charpeni** [comment]
@r0b1n Sorry I missed the notification, yes you can help with the few remaining eslint errors if you want to.

@aksonov Can you add [mention-bot](https://github.com/facebook/mention-bot) to the repo WebHooks?

**Comment by aksonov** [comment]
Yes, what should i do?

**Comment by charpeni** [comment]
@aksonov Pretty simple in fact, just follow these steps : https://github.com/facebook/mention-bot#how-to-use :)

**Comment by aksonov** [comment]
Sorry, have pretty limited time, could you submit PR with needed .mention-bot ?

**Comment by cridenour** [comment]
@aksonov Looks like the configuration is optional, just need to add the webhook in settings. 

`https://mention-bot.herokuapp.com/` under Settings > Webhooks & services > Add Webhook

**Comment by aksonov** [comment]
ok, done.

btw, i will be unavailable during next week.

**Comment by charpeni** [comment]
@aksonov Thank you.

We will take care of this repo, good week!

**Comment by charpeni** [comment]
@aksonov Before leaving can you give authorization to CircleCI for this repo ? https://circleci.com

I will do the config soon with eslint and unit tests.

**Comment by aksonov** [comment]
Circle should be authorized already.

**Comment by charpeni** [comment]
@aksonov Welcome back!

You should setup your Git with your real git address, some commits are linked to aksonov@gmail.com and you don't get mentioned by the bot.

I added a circle.yml, but CircleCI doesn't get triggered, can you try to manually start a build and verify the link with this repo?

**Comment by aksonov** [comment]
@charpeni  please check now.
I'm getting this:
```
eslint index.js src/ test/ -o $CIRCLE_TEST_REPORTS/eslint/eslint.xml -f junit
bash: line 1: eslint: command not found
bash: line 1: eslint: command not found
bash: line 1: eslint: command not found

eslint index.js src/ test/ -o $CIRCLE_TEST_REPORTS/eslint/eslint.xml -f junit returned exit code 127
eslint index.js src/ test/ -o $CIRCLE_TEST_REPORTS/eslint/eslint.xml -f junit returned exit code 127
eslint index.js src/ test/ -o $CIRCLE_TEST_REPORTS/eslint/eslint.xml -f junit returned exit code 127
```

**Comment by charpeni** [comment]
@aksonov Fixed and merged into master.

1 eslint error remaining (except Example folder), I will fix it.

**Comment by charpeni** [comment]
@aksonov What happened with the mention-bot ?

**Comment by aksonov** [comment]
I don't know, i didn't change anything.

**Comment by charpeni** [comment]
>Hi Nicolas!
>
>Thanks for reaching out to us. As long as your project is public, you will have access to a total of 4 free >containers for that project to build on our Linux based platform. As for OS X, we have enabled OSS for >your org aksonov.
>
>Please let me know if you need anything else!
>Chloé

**Comment by charpeni** [comment]
cc @aksonov @joenoon @cridenour @rturk @lynndylanhurley

**Comment by aksonov** [comment]
@charpeni great, what should i do?

**Comment by charpeni** [comment]
@aksonov Nothing, it should be already activated. I'll look to do some e2e tests.
