### ISSUE TITLE
Implied Routes

### ISSUE THREAD

**Issue by skrigs** [aksonov/react-native-router-flux#571]
This is more a feature suggestion for version 3 of the router.

I have a requirement to display a list of notifications to a user on a tab. When the user selects a notification the application needs to switch to a different tab immediately resetting the stack used by the tab and build up the depth of navigation the user would have followed to arrived at this scene.

e.g.
- The user is currently visiting "Profile->Photos ->Album 1" on "Tab 1"
- The user selects a notification being displayed on "Tab 2" to view a friends profile
- The application switches to "Tab 1"
- Unmounts all the previous scenes on "Tab 1"
- Builds up the stack "Profile->Friends->Friend 1" 
- Finally displaying scene "Friend 1"

Within my applications configuration I currently defines the route hierarchy similar to how this library defines it. However I also have the ability to define an extra data structure I call impliedRoutes that has the following structure:

impliedRoutes = {
   friends ['friends', 'profile']
   friend: ['friend', '@friends']
}

The keys can be referred to in what I call a pushDeep action. The values in the array either refer to the key in your router or another key within the impliedRoutes. Therefore when visiting friend, the router stack is populated with the routes matched by friend, friends and profile.

I hope you find this helpful and look forward to the next steps this library takes in a hope to replace my implementation sometime with it in the not too distant future (when NavigatorExperimental has a more stable API).

**Comment by aksonov** [comment]
I don't quite understand what do you need. Could you implement needed functionality with custom reducer (check Example project how to use own reducer)? You may intercept all nav actions and do whatever you want with them and with navigation state.

**Comment by skrigs** [comment]
Ahhh yes.... Still getting use to the concept of the navigation state finally being fully represented within the store. My implementation is a bit like your v2 where I'm using the old Navigator. I will see how I go at implementing all my existing functionality (thinking it through I can't think of anything I couldn't achieve)
