### ISSUE TITLE
Replace Scenes with custom components not working.

### ISSUE THREAD

**Issue by philolo1** [aksonov/react-native-router-flux#573]
Hi i am using  react-native-router-flux v3.2.6 with react-native v0.22.2 and i would like to split my scenes into smaller components, but its not working. Like this:

instead of 
```
<Router>
                   <Scene key="tab0" component={ FeedView } navBar={ FeedNavBar } titleStyle={ { color: "white" } } />
</Router>
```

I would like to create my own class Tab0

```
class Tab0 extends React.Component {
  render() {
    return ( 
              <Scene key="tab0" component={ FeedView } navBar={ FeedNavBar } titleStyle={ { color: "white" } } />
    );
  }
};
```

and then just use

```
<Routerr>
                   <Scene key="tab0" component={ FeedView } navBar={ FeedNavBar } titleStyle={ { color: "white" } } />
</Router>
```

I am getting the error "Component property is not set for key=root. Is there a way to do that?

**Comment by aksonov** [comment]
Good question, maybe we need to add this topic to README!
You can split your scenes using NodeJS require calls:
```
            <Router>
                    {require("./scenesForTabBar")}
                    {require("./scenesForAnotherPart")}
            </Router>
```

scenesForTabBar.js:
```
import React from 'react-native';
import {Scene} from 'react-native-router-flux';

module.exports = <Scene key="tabbar" tabs={true}>
   // scenes here
</Scene>;
```

**Comment by philolo1** [comment]
@aksonov thanks, yeah it would be useful to add it to the readme. I see that the way i would like to do it its not easily possible without changing the interface, so your solution is fine, thanks!

**Comment by aksonov** [comment]
I believe this method is better than any possible additional interface, because it requires zero knowledge about that additional interface from code reader...

**Comment by philolo1** [comment]
i mean generally it should be possible to group any another component to a new component without breaking the code, but i understand that this might be hard to implement with the current Scenes etc. anyway i am ok with that and thanks for the fast response.

**Comment by aksonov** [comment]
Honestly i just don't see how to traverse children of component children defined in their render method, maybe you know the way? So if you define some custom component 'Scenes', the component will be not able to iterate Scenes children...

**Comment by aksonov** [comment]
So I would like to implement this possibility however i don't see how to do it with React Native....

**Comment by philolo1** [comment]
Well you can do something like shallowRendering https://facebook.github.io/react/docs/test-utils.html, but I am not sure that is really efficient and the way to go. I don't think that feature is that urgent, as long as there is a workaround.

**Comment by tuneZola** [comment]
You should just be able to import the Scene as a component. This is a feature we would really like. Can this issue be reopened?

**Comment by aksonov** [comment]
PR is welcome. I've show a way to accomplish it for current version
