### ISSUE TITLE
Navbar Icon to trigger method on scene?

### ISSUE THREAD

**Issue by MovingGifts** [aksonov/react-native-router-flux#575]
On a movies scene, I have a listview with 10 movies. In the navbar assigned to the scene, I have an "a-z" as the right icon to sort the movies alphabetically. I am having a very hard time getting the button in the navbar, to do the sorting of the movies. However, if I add the "a-z" icon in the movies scene itself, without the navbar, it sorts them perfectly via a method called by onPress, but the icon needs to be in the navbar. I assume I have to use redux with the navbar icon as an onPress action, but I am not 100% sure how to do this.

I am fairly new to this package and the Redux/Flux part to me is very confusing in the documentation. I learn better with videos showing how things are done. I already watched the Redux videos by Dan Abramov but not sure how to implement them with the router.

Can someone with more knowledge shed some light on the steps to take to accomplish this simple task?

**Comment by rturk** [comment]
https://github.com/aksonov/react-native-router-flux/issues/515

**Comment by sf577** [comment]
This question was asked in the gitter however there was no answer as to how to achieve it. Has anybody worked out something close to best practice on this?

**Comment by MovingGifts** [comment]
@st577 Agreed, I am still stuck on this one with no response from gitter. I am sure others will benefit from how to accomplish this as well. Anyone?

**Comment by sf577** [comment]
I've finally hacked it together by hiding the navbar in the router, and putting the custom NavBar in the scene component. It looks fine and I can pass a function callback in fairly easily however in general im not happy with the solution.

**Comment by MovingGifts** [comment]
I agree, would be better to have all the navbars in a single file, but know how to reach in and call the a method from the corresponding scene..
