### ISSUE TITLE
Customize <Tab>

### ISSUE THREAD

**Issue by evollu** [aksonov/react-native-router-flux#576]
Do you think it is a good idea to add renderTab prop to allow custom Tab bar?
I can make a pull

**Comment by cridenour** [comment]
You can already customize every component in the TabBar. 

```
<Scene key="main" tabs={true} component={TabBar}>
  <Scene key="showings" component={ShowingsList} title="Showings" icon={TabIcon} iconName="calendar" />
</Scene>
```

**Comment by evollu** [comment]
I want to custom tabbar itself not tabIcon because I want to use TouchNativeFeedback instead of TouchOpacity in react-native-tab.

**Comment by cridenour** [comment]
Please see the first line, you can pass a component to the scene with tabs={true}. I would suggest using the TabBar in this component as a start, and edit from there.

**Comment by evollu** [comment]
yeah I tried and it works for most cases, but just not mine. Just want to add an option to not depend on another library.

**Comment by cridenour** [comment]
Well, to be fair the tab library is the same maintainer as this library. 

But if you don't want to use it you won't need to. You have full control over that component as it just reads the navigation state to decide what to do. I personally overwrote mine to hide it when the user is logged out.

**Comment by evollu** [comment]
I will change it in my fork then.
Thanks 😄

**Comment by manideepcs024** [comment]
how can the tab text (which is key by default) can be changed or removed.
