### ISSUE TITLE
Toggle burger button for V3

### ISSUE THREAD

**Issue by kevinvn1709** [aksonov/react-native-router-flux#578]
I got some problem with RNRF V3 when implement with react-native-drawer

// NavigationDrawer

    class NavigationDrawer extends Component {
		render() {
	        return (
	            <Drawer
	                type="overlay"
	                content={<.... />}
	                styles={{....}}>
	                // View...
	            </Drawer>
	        );
	    }
	}

// RootApp

    export default class App extends Component {
	    render() {
	        return (
	         <Router>
	             <Scene key="root">
	                 <Scene key="drawer"
	                        type="reset"
	                        renderLeftButton={this.renderBurger()}
	                        component={NavigationDrawer}>
	                 </Scene>
	             </Scene>
	         </Router>
	        )
	    }
	    
	    renderBurger(){
			return (
	            <TouchableOpacity
	                style={...}
	                onPress={ ()=>/* I WANT TO TOGGLE DRAWER HERE */}
	            >
	                <Image
	                    source={require('./btn-menu.jpg')}
	                />
	            </TouchableOpacity>
	        )
	    }
    }

In the RootApp file. I want to close drawer when user tap on burger button. I can not use contextTypes in this case. Please help me to do it

Thanks.

**Comment by aksonov** [comment]
You should place renderLeftButton for children of Drawer, check Example project.
