### ISSUE TITLE
Cannot find scene with key=xxxx and Switch

### ISSUE THREAD

**Issue by emroot** [aksonov/react-native-router-flux#579]
### Version
- react-native-router-flux v3.22.8
- react-native v0.22.0

I'm trying to use `Switch` but I keep getting the following error: 
![image](https://cloud.githubusercontent.com/assets/110190/14765471/e2db798a-0997-11e6-879b-2f929353ea2c.png)

Code looks like this:
```
<Router>
  <Scene
    component={connect(state => ({
      authorized: state.authentication.authorized,
    }))(Switch)}
    hideNavBar
    key="root"
    selector={props => (props.authorized ? 'dashboard' : 'login')}
  >
    <Scene key="login" hideNavBar>
      <Scene key="main" component={Login} />
      <Scene key="email" component={LoginEmail} />
    </Scene>
    <Scene key="dashboard" tabs tabBarStyle={styles.tabBar}>
      <Scene key="availability" icon={TabIcon} tabIcon="calendar" hideNavBar>
        <Scene key="schedule" component={AvailabilityContainer} />
      </Scene>
    </Scene>
  </Scene>
</Router>
```

When I dig deeper in code, I notice that `navigationState.children` has only one children probably because of this? https://github.com/aksonov/react-native-router-flux/blob/master/src/State.js#L52

Error is triggered here: 
https://github.com/aksonov/react-native-router-flux/blob/master/src/Switch.js#L16-L17

**Comment by aksonov** [comment]
Check README. "New feature for 3.x release is custom scene renderer that should be used together with tabs={true} property."

**Comment by emroot** [comment]
gotcha, makes sense. thanks!

**Comment by mmelchio** [comment]
@emroot Could you explain how you got it to work?
How do your Login components look like?
In my case it couldn't fine the variable: connect.
