### ISSUE TITLE
Android hardware back button, and styling

### ISSUE THREAD

**Issue by andreialecu** [aksonov/react-native-router-flux#581]
It doesn't look like the back button on android is supported out of the box. 

Any guidance into how an implementation with tabs would work? Only the active tab should be navigated back.

Also, how could the UI be styled for Android in this case? Any hints about how to move the tab bar to be un top (below the navigation bar) and style it to a native android look would be appreciated. 

Pointers on integrating something like https://github.com/brentvatne/react-native-scrollable-tab-view or `ViewPagerAndroid` with RNRF would be great.

**Comment by aksonov** [comment]
#515
