### ISSUE TITLE
"direction" no long works

### ISSUE THREAD

**Issue by evollu** [aksonov/react-native-router-flux#584]
Seems 2.4 removed direction prop in NavigationCard and relies on panHandler and style to handle vertical. Should we add the feature back? (As NavigationCardStack did)

**Comment by cridenour** [comment]
This work has already been complete in the unreleased 3.24 branch but we are waiting on upstream changes for a complete working solution for 0.24.

Thanks!

**Comment by mikefowler** [comment]
Any word on those upstream changes holding that branch back, @cridenour?

**Comment by cridenour** [comment]
We're hoping they hit in 0.25, and we just merged a type=replace fix. I might try and upgrade to latest react native master later this week to see if they do.

**Comment by mikefowler** [comment]
Neat. @lelandrichardson, do you know if this is on the radar for 0.25? If not, maybe we can sneak it in. What are the specific changes you're waiting for, @cridenour? Link to SHA?

**Comment by cridenour** [comment]
We have support for direction in the 0.24 branch, but the two issues are linked to in #489 I believe.
