### ISSUE TITLE
NavBar's height should not be 64pt in Android

### ISSUE THREAD

**Issue by chzhuo** [aksonov/react-native-router-flux#586]
### Version
react-native-router-flux v3.22
react-native v0.23.1

### Expected behaviour
NavBar's height should be 64pt in IOS, but should be 44pt in Android. Because we can't code Android's status bar.

### Actual behaviour
The screenshot show that NavBar is higher. The title is not vertical center. 
![screenshot_2016-04-25-10-43-23_com shop_app](https://cloud.githubusercontent.com/assets/10919124/14772585/b4b08d5c-0ad2-11e6-97f6-0ebe0ba69746.png)

### Steps to reproduce

1.Add a NavBar to a scene
2.Execute 'react-native run-android'
3.You will see the NavBar's height more than 44pt.

**Comment by vermiculite** [comment]
Thanks I had never noticed. I made a work around as follows.
```<Router
            navigationBarStyle={navigationBarStyle}
            titleStyle={titleStyle}
        >```
Assuming you want to apply for all scenes.

Style definitions are

```
const navigationBarStyle = {
    paddingTop: 0,
    height: 44
};

const titleStyle = {
    marginTop: 0,
    top: 10
};
```

**Comment by ms88privat** [comment]
In my `style.js` file, I handle all the logic between Android and iOS like:

```js
export function getHeaderHeight() {
  if(Platform.OS === 'ios') {
    return HEADER_HEIGHT_IOS;
  } else {
    return HEADER_HEIGHT_ANDROID;
  }
}
```

This is also useful to have:

```js
if(Platform.OS === 'ios') {
  DEVICE_HEIGHT = Dimensions.get('window').height;
} else {
  var ExtraDimensions = require('react-native-extra-dimensions-android');
  // REAL_WINDOW_HEIGHT - Actual height of screen including system decor elements
  // REAL_WINDOW_WIDTH - Actual width of screen including system decor elements
  // STATUS_BAR_HEIGHT - Height of the status bar
  // SOFT_MENU_BAR_HEIGHT - Height of the soft menu bar (supported on most new Android devices)
  // SMART_BAR_HEIGHT - Height of the MeiZu's device smart bar

  DEVICE_HEIGHT =
    ExtraDimensions.get('REAL_WINDOW_HEIGHT') -
    ExtraDimensions.get('STATUS_BAR_HEIGHT') -
    ExtraDimensions.get('SOFT_MENU_BAR_HEIGHT');
}
```

**Comment by charpeni** [comment]
Fixed by #596.

**Comment by chzhuo** [comment]
When android.version >= 21 we can set component [StatusBar](https://facebook.github.io/react-native/docs/statusbar.html)'s translucent to true. When translucent is set to true, the app will draw under the status bar. This is useful when using a semi transparent status bar color.  When android.version < 21 we can do like @vermiculite 's comment.

**Comment by aksonov** [comment]
Sorry it doesn't work (for iOS), i've partially reverted #596

**Comment by explorigin** [comment]
This is still an issue for me with 3.26.5 on RN 0.26.

**Comment by sarovin** [comment]
@explorigin Can you post a screenshot and your code?

**Comment by explorigin** [comment]
Screenshot is no different from the first post.  We might leave this one closed.  I was able to work around it by setting `<StatusBar translucent />` inside my scene.  Kinda a bummer to have to do that in each scene but it works.

**Comment by sarovin** [comment]
You can use this in index.android.js:

```
StatusBar.setBackgroundColor('transparent');
StatusBar.setTranslucent(true);
```

**Comment by explorigin** [comment]
Thanks, that's really helpful!

**Comment by charpeni** [comment]
>It is however not recommended to use the static API and the component for the same prop because any value set by the static API will get overriden by the one set by the component in the next render. [StatusBar documentation.](https://facebook.github.io/react-native/docs/statusbar.html#content)

**Comment by Yangzhilang** [comment]
@vermiculite it worked.Good job.

**Comment by anray** [comment]
@vermiculite 
"react-native": "^0.39.2",
"react-native-router-flux": "^3.37.0",

This workaround doesn't work. There are no such props for Router: navigationBarStyle, titleStyle

**Comment by anray** [comment]
In my case Android actionBar was created with Views. So I need to fix sizes of those views
