### ISSUE TITLE
undefined is not an object (evaluating 'child.type.prototype')

### ISSUE THREAD

**Issue by shivangbtech** [aksonov/react-native-router-flux#587]
I am getting error message :

"undefined is not an object (evaluating 'child.type.prototype')", while trying to run this Example code for android. Here is Example URL: "https://github.com/aksonov/react-native-router-flux"

I have installed:
 sudo npm install react-native-router-flux@2.3.9
 sudo npm install react-native-drawer --save
 sudo npm install react-native-button

**Comment by cridenour** [comment]
The example code is for v3 of the library. If you're wanting to stick with v2, you will need something like https://github.com/aksonov/react-native-router-flux/tree/752dde2f236d1404d3a09beb1c3229597b7db3b4
