### ISSUE TITLE
Can not route back to a scene which type is 'reset' or 'replace'

### ISSUE THREAD

**Issue by helloworld123456** [aksonov/react-native-router-flux#588]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.22.0
- react-native v0.24.0

### Expected behaviour
My route configure like this:
`<Provider store={store}>
                <Router createReducer={reducerCreate}>
                    <Scene key="root" hideNavBar={true} hideTabBar={true}>
                        <Scene key="TestScene1" component={TestScene1} initial={true} type="replace"/>
                        <Scene key="TestScene2" component={TestScene2} type="replace"/>
                    </Scene>
                </Router>
</Provider>`

TestScene1 and TestScene2 are just ordinary RN components,:

`
class TestScene1 extends Component {
    render() {
        return (
            <View style={{flex:1,flexDirection: 'column',paddingTop:100, alignItems:'center'}}>
                <Text>1</Text>
                <Button onPress={()=>Actions.TestScene2()}>go to 2</Button>
            </View>
        )
    }

class TestScene2 extends Component {
    render() {
        return (
            <View style={{flex:1,flexDirection: 'column',paddingTop:100, alignItems:'center'}}>
                <Text>2</Text>
                <Button onPress={()=>Actions.TestScene1()}>go to 1</Button>
            </View>
        )
    }
`
When I route to TestScene2 from TestScene1, it's ok, but when I back to TestScene1 from TestScene2, it doesn't work, the UI still display the TestScene2 after Actions.TestScene1() send out.
And this problem just happen when the type of TestScene1 and TestScene2 are  both 'replace' or 'reset'.

**Comment by aksonov** [comment]
#525 !
