### ISSUE TITLE
Issues implementing tabs in subcomponent

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#59]
Thanks for your work on the new version. It looks promising. 

I need to have my tabs down a ways in the component hierarchy. I'm experimenting with your Example to see if that can work. 

First, I replaced all the tab stuff in the Example class with just this:

```
<Route name="tabbar" component={TabContainer} />
```
Then I moved all the rest of the tab stuff to TabContainer:

```
        return (
          <Router footer={TabBar} showNavigationBar={false}>
              <Route name="tab1" type="switch" icon={TabIcon} title="Tab #1" >
                  <Router>
                      <Route name="tab1_1" component={TabView} title="Tab #1_1" />
                      <Route name="tab1_2" component={TabView} title="Tab #1_2" />
                  </Router>
              </Route>
              <Route name="tab2" type="switch" icon={TabIcon} title="Tab #2" hideTabBar={true} component={TabView} />
              <Route name="tab3" type="switch" icon={TabIcon} title="Tab #3" component={TabView}  />
              <Route name="tab4" type="switch" icon={TabIcon} title="Tab #4" component={TabView} />
              <Route name="tab5" type="switch" icon={TabIcon} title="Tab #5" component={TabView} />
          </Router>
        );
```
The first problem was I couldn't get Schema to work so in the above code, I have worked around that by expanding the tab schema out in each tab. I first tried just `schema="tab"` and got the error `No schema=tab is defined for route=tab`.
Then I tried defining the schema in TabContainer as the first child of \<Router\>. Then I get a `console.error: No icon class is defined for undefined.`

Problem 2: The above code mostly works but if I wrap it all in a \<View\> nothing renders. EDIT: `<View style={{flex: 1}}>` works.

Problem 3: The `Back` button in the TabView screen only works if you're on Tab 1. Once you switch to a different tab, clicking Back triggers the error: `Cannot pop navigator with less than 1 screens`

Problem 4: When I set `initial={true}` on Tab 3, the view initially is set to Tab 3, but the TabBar icon still shows Tab 1 is selected.

**Comment by aksonov** [comment]
Thanks for great feedback. Could you please give me sample github repo with all issues above. Also it will be useful to create separate issues (not this one) for each problem...
And PR will be welcome for some/all of them would be helpful.

P.S. Problem 2 is not problem, i believe.

**Comment by chetstone** [comment]
Thanks for the response. I have created new issues for problems [1](https://github.com/aksonov/react-native-router-flux/issues/63),[3](https://github.com/aksonov/react-native-router-flux/issues/64), and [4](https://github.com/aksonov/react-native-router-flux/issues/62). Agreed, I don't believe problem 2 is a problem at the moment.

I have rethought my approach and for my app it may make more sense to implement the entire router in the subcomponent. In that case issue #62 would be the highest priority for me.
