### ISSUE TITLE
hideNavBar is not working on the last version

### ISSUE THREAD

**Issue by mywaystar** [aksonov/react-native-router-flux#590]
With the last react-native-router-flux version, hideNavBar has this behavior both on iOS and Android:

![Bug](http://img15.hostingpics.net/pics/636854screen.jpg)

I downgraded back to the 3.22.4 and it's works fine

**Comment by aksonov** [comment]
Have you tried master branch?

**Comment by mywaystar** [comment]
Nope, i'm using npm so I did'n tried

**Comment by ms88privat** [comment]
@mywaystar try this "react-native-router-flux": "github:aksonov/react-native-router-flux#master"

**Comment by aksonov** [comment]
@mywaystar Please try 3.22.10. There were huge changes for nav bar, hope i didn't broke anything.

**Comment by mywaystar** [comment]
True, with master, it's working :)
