### ISSUE TITLE
Force component to render before switching to it.

### ISSUE THREAD

**Issue by xvalentino** [aksonov/react-native-router-flux#599]
Is there any way to render a scene/route before you switch to the route?

I am loading images and videos in a scene, and they take time to load. There is an unpleasant initial flicker when I move to these scenes. I'd like to force my component to update, THEN within the component I have an 'onLoadFinish' callback where I'd like to call Actions.foo().

Does anyone have any idea if this is capable now, or point me into the direction of where I could make a PR to make this possible?

I'm on 2.x but I'd upgrade if I had to.

Thank you!

**Comment by aksonov** [comment]
Just use Actions.refresh to change state of current scene (i don't remember if v2 has 'refresh' action)

**Comment by xvalentino** [comment]
I believe it is in 2.x, but I thought Actions.refresh would only refresh the current scene. I want to refresh a scene that isn't in focus yet. Does this mean a custom render function would be what I need?

**Comment by aksonov** [comment]
so refresh it before pushing

**Comment by xvalentino** [comment]
"`Actions.refresh(PARAMS)` will update the properties of the current screen."
Does this mean the current screen that's in focus, or the scene this function is called in?

Sorry but it's not exactly clear to me how I specify which component I want to refresh.

**Comment by xvalentino** [comment]
The problem I was running into is in the 2.x implementation of tabs, render was only called when a route was rendered.

Upgrading to v3 has fixed this.

Thank you!

**Comment by xvalentino** [comment]
@aksonov My app was crashing because I was on React Native 0.22. But when I update to 0.24 anything besides the current scene is not rendered/updated (just like in 2.x)

Is there a stable 3.x release that will have the functionality I'm looking for? (updating component that aren't the current scene)

**Comment by aksonov** [comment]
pop & refresh cause crash?

**Comment by xvalentino** [comment]
I ended up removing pop in several places and replaces them to just pointing to another tabbed route. But my app began crashing after updating to 3.x, and I read in some of the other issues that there were problems with RN 0.22. The app would crash after ~5 minutes of use. I couldn't track down what exactly was causing it. Should I go back and debug? After reading issues I assumed using the latest router version with RN 0.22 was unstable.

What I'm going for is tabbed functionality so all of my components are always mounted, and being updated (not only when I make a component the current scene).

**Comment by aksonov** [comment]
Is it Android?

**Comment by xvalentino** [comment]
Yes

**Comment by aksonov** [comment]
Then, yes, it is not stable with Android. However it is pretty stable with iOS.

**Comment by aksonov** [comment]
0.24 improves android support, but introduces other bugs :) So we are waiting for RN0.25 probably....

**Comment by xvalentino** [comment]
Do you know of any 3.x version that works with any RN version on Android? Or any combinations of version that could accomplish this?

Thank you for replying so quickly! Glad I can get this sorted out so fast.

**Comment by aksonov** [comment]
Sorry, no. v3 depends from new navigation api and it doesn't work good on android (v0.22)
