### ISSUE TITLE
Key is already defined!

### ISSUE THREAD

**Issue by cmouysset** [aksonov/react-native-router-flux#607]
### Version
    "color": "^0.10.1",
    "react-native": "^0.24",
    "react-native-android-statusbar": "^0.1.2",
    "react-native-drawer": "^2.0.0",
    "react-native-navbar": "^1.1.4",
    "react-native-router-flux": "^3.22.15",
    "react-native-selectme": "^1.0.0",
    "react-native-tableview-simple": "^0.8.0"

### Expected behaviour

When clicking a link in the drawer menu it should take me to the page instead nothing happens.

### Code being used

/// RootRouter 

const reducerCreate = params=>{
    const defaultReducer = Reducer(params);
    return (state, action)=>{
        console.log("ACTION:", action);
        return defaultReducer(state, action);
    }
};

export default class RootRouter extends Component {

    constructor(props) {
        super(props);
        this.state = {
            token: ''
        };
		this.loginFunction = this.loginFunction.bind(this);
    }

	loginFunction(token) {
		this.setState({ "token": token });
		console.log('RootRouter Token: ' + this.state.token);
	}

    render() {
        return(<Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'}}>
			<Scene key="drawer" component={Modal}>
				<Scene key="home" component={Home} title="Home" />
				<Scene key="login" component={Login} initial={true} loginFunction={this.loginFunction}/>
				<Scene key="account" component={Account} title="Account" />
				<Scene key="social" component={Social} title="Social" />
				<Scene key="sales" component={Sales} title="Sales" />
			</Scene>
		</Router>);

/// CP_Function:

export default class CP_Function extends Component {
	componentDidMount() {
		console.log("componentDidMount - hamburger listening")
		AppEventEmitter.addListener('hamburger.click', this.openControlPanel.bind(this));
    }

    componentWillUnMount() {
		console.log("componentWillUnMount - hamburger listening removal")
    	AppEventEmitter.removeListener('hamburger.click');
    }

	closeControlPanel(navigation) {
		if(navigation.type == 'AFTER_ROUTER_ROUTE') {
			this.refs.navigation.close();
			Actions.refresh({ "token": this.state.token });
		}
	}

	closeControlPanel = () => {
		this._drawer.close()
	};

	openControlPanel() {
		console.log("Hamburger clicked!");
		this._drawer.open();
	}

	render(){
		return (
            <Drawer
                ref={(ref) => this._drawer = ref}
                type="overlay"
                content={<ControlPanel />}
                tapToClose={true}
                openDrawerOffset={0.2}
                panCloseMask={0.2}
                negotiatePan={true}
                tweenHandler={(ratio) => ({
                 main: { opacity:Math.max(0.54,1-ratio) }
            })}>
				<RootRouter />
            </Drawer>
        );
    }
}

**Comment by cridenour** [comment]
Please see #525

**Comment by r0b1n** [comment]
@cmouysset 
About `Key is already defined!`:
I see what you use custom `RootRouter ` component which encapsulates the render of `Route` and `Scene`s. Also I see `RootRouter ` state changing while login, this forces to re-render.
But you shouldn't re-render `Route` > `Scene`s. I suggest you to rework your `RootRouter` to make it render only once. Make it `state`-less and `props`-less. 

P.S. You may store token in flux implementation of your app.

**Comment by cmouysset** [comment]
@r0b1n thanks! I'm not sure where to store the token if I don't store it in RootRouter. What do you mean by the in flux implementation?

**Comment by r0b1n** [comment]
@cmouysset [flux](http://facebook.github.io/flux/docs/overview.html) and [many implementations of it](https://github.com/voronianski/flux-comparison)?

**Comment by cmouysset** [comment]
Thanks @r0b1n.

So I've changed the RootRouter to:
export default class RootRouter extends Component {

    render() {
        return(
        <Router>
			<Scene key="drawer" component={CP_Function}>
                <Scene key="main" >
                    <Scene key="home" component={Home} title="Home" hideNavBar />
                    <Scene key="login" component={Login} initial={true} hideNavBar />
                    <Scene key="account" component={Account} title="Account" hideNavBar />
                    <Scene key="social" component={Social} title="Social" hideNavBar />
                    <Scene key="sales" component={Sales} title="Sales" hideNavBar />
                </Scene>
			</Scene>
		</Router>);
    }
}

And put the loginFunction and the token state in CP_Function (see below). Is this how you'd recommend I do this? My concern is how can I get the token from Login.js to CP_Function so that I can change the state so that it's accessing on other pages?

export default class CP_Function extends Component {
    constructor(props) {
        super(props);
        this.state = {
            token: ''
        };
		this.loginFunction = this.loginFunction.bind(this);
    }

	loginFunction(token) {
		this.setState({ "token": token });
		console.log('RootRouter Token: ' + this.state.token);
	}

	componentDidMount() {
		console.log("componentDidMount - hamburger listening")
		AppEventEmitter.addListener('hamburger.click', this.openControlPanel.bind(this));
    }

    componentWillUnMount() {
		console.log("componentWillUnMount - hamburger listening removal")
    	AppEventEmitter.removeListener('hamburger.click');
    }

	closeControlPanel(navigation) {
		if(navigation.type == 'AFTER_ROUTER_ROUTE') {
			this.refs.navigation.close();
			Actions.refresh({ "token": this.state.token });
		}
	}

	closeControlPanel = () => {
		this._drawer.close()
	};

	openControlPanel() {
		console.log("Hamburger clicked!");
		this._drawer.open();
	}

	render(){
		const children = this.props.navigationState.children;
		return (
            <Drawer
                ref={(ref) => this._drawer = ref}
                type="overlay"
                content={<ControlPanel closeFunc={this.closeControlPanel}/>}
                tapToClose={true}
                openDrawerOffset={0.2}
                panCloseMask={0.2}
                negotiatePan={true}
                tweenHandler={(ratio) => ({
                 main: { opacity:Math.max(0.54,1-ratio) }
            })}>
				<DefaultRenderer navigationState={children[0]} />
            </Drawer>
        );
    }

**Comment by r0b1n** [comment]
@cmouysset learn about flux, `redux` implementation, for example. It will answer your question.

**Comment by mckn** [comment]
I got this issue when I was running a version of react newer then the 0.22.*. So it might be the issue?

**Comment by seanfuture** [comment]
Running 0.22.2 of React Native resulted in same console log so in Actions.js the following change solved it for myself for now:

**Before**
```
    iterate(root: Scene, parentProps = {}, refs = {}) {
        assert(root.props, "props should be defined for stack");
        const key = root.key || 'root';
        assert(key, "unique key should be defined ",root);
```
**After**
```
    iterate(root: Scene, parentProps = {}, refs = {}) {
        assert(root.props, "props should be defined for stack");
        const key = root.key || 'root';
        if (this[key]){
            return refs[key]
        }
        assert(key, "unique key should be defined ",root);
```
.. where the `console.log("Key " + root.key + " is already defined!");` statement appears below this.

Hope this helps

**Comment by rturk** [comment]
@cmouysset can you try again using the latest master? FYI (https://github.com/aksonov/react-native-router-flux/commit/900ba4299faff2099b91e8002bf2256892cee652)
