### ISSUE TITLE
renderBackButton or renderLeftButton?

### ISSUE THREAD

**Issue by chrissm79** [aksonov/react-native-router-flux#61]
Is there a way to customize the left button with either renderBackButton or renderLeftButton? I tried by adding to the Route,Router and Schema but couldn't get it to work. Thanks!

**Comment by aksonov** [comment]
I will definitely add it, thanks!

**Comment by aksonov** [comment]
Should be available within 1.0.7

**Comment by chrissm79** [comment]
Awesome, thank you!!

**Comment by aksonov** [comment]
renderRightButton will customize right button. also there rightButtonStyle for styling.

**Comment by chetstone** [comment]
Thanks for this. Can we also have a renderTitle? My app has a drop-down menu from the title button.

**Comment by MITDelian** [comment]
Addressed in #70

**Comment by lrettig** [comment]
If anyone else is as stuck on this as I was--until the docs are updated--this appears to work with the latest version of the code (2.0.5):

```javascript
class MyApp extends React.Component {
  render() {
    return (
      <Router>
        <Route
          name="home" component={HomeScreen} initial={true} title="Home"
          onRight={function(){
            console.log("Right button pressed")
          }}
          rightTitle="Testing"
        />
      </Router>
    );
  }

}

```

**Comment by gr4yscale** [comment]
Thanks @lrettig, I searched through the code for a while and discovered this, too - too late before reading this issue. =\ There are so many layers between RN, Exponent, and this component that it's rather confusing. Still very useful. I would be happy to help with documentation if I understood it all a bit better.

**Comment by lrettig** [comment]
I think adding a couple of simple examples like this to the existing README file might go a long way!
