### ISSUE TITLE
Re-mount tab component when navigating from the same component

### ISSUE THREAD

**Issue by Proyoyo** [aksonov/react-native-router-flux#617]
Hi there,
I'm wondering if there is a way to re-mount tab component when navigating from the same component.

e.g. When a user on "Feeds" component, clicking "Feeds" tab icon will unmount the current "Feeds" component and mount a new "Feeds" component.

I'm using:
- react-native-router-flux v3.22.15
- react-native v0.24.1

**Comment by aksonov** [comment]
#525

**Comment by diogoviannaaraujo** [comment]
Im still trying to figure a way of doing this correctly.. My only solution right now is to conect router to my reducer, keep track of each change, and when its focus on the same tab i remount the component.
Really thought that it would be awesome if scene called a onFocus propriety on the component everytime the reducer calls focus on that scene
