### ISSUE TITLE
Is it possible to have a dropdown when clicking on a button in the navbar?

### ISSUE THREAD

**Issue by hyperh** [aksonov/react-native-router-flux#626]
Is it possible to have a dropdown when clicking on a button in the navbar?  This would be similar to native Android behaviour, like this: http://i.stack.imgur.com/tIO9E.png

I haven't seen anything in the docs that tells me you can do it. It says you can submit a custom NavBar component, is that the standard way to go about doing this?

**Comment by cridenour** [comment]
Yes, I would suggest you use a custom NavBar.

**Comment by hyperh** [comment]
Are there any resources I should be reading as a starting point?

**Comment by adrianmc** [comment]
@hyperh it looks like you'll probably have to implement a static method `renderNavigationBar(props)` in your scene component class. See here: https://github.com/aksonov/react-native-router-flux#custom-nav-bar-for-individual-scene-or-even-different-state-of-scene-new-feature

**Comment by MovingGifts** [comment]
@adrianmc @cridenour I've seen this part of the docs, but there is no code example to see how it works anywhere. For beginners, it's really hard to use this plugin IMHO. Can you post an example of how the renderNavigationBar(props) should be used with a custom navbar?

**Comment by cridenour** [comment]
I've not done it myself unfortunately, so I don't have a example on hand. If you do get it working, please submit a PR to add it to the docs though!

**Comment by Elyx0** [comment]
I've done it and it required a custom `renderNavigationBar`. Besides that you're building a dropdown like you would normally in React using state and `Actions`
