### ISSUE TITLE
Having component on root Scene stops transition animations on underlying transitions

### ISSUE THREAD

**Issue by swemail** [aksonov/react-native-router-flux#627]
### Version

- react-native-router-flux v3.22.0
- react-native v0.24.1

### Expected behaviour

I'm using code like in the Drawer Integration and have a drawer like component as component on the top Scene. The sub Scenes have in turn navigation. When clicking those I expect the default transition animations.

### Actual behaviour

There are no animations.

**Comment by rturk** [comment]
https://github.com/aksonov/react-native-router-flux/issues/525
