### ISSUE TITLE
Direction attribute no longer working

### ISSUE THREAD

**Issue by ajwhite** [aksonov/react-native-router-flux#629]
### Version

- react-native-router-flux v3.22.23
- react-native v0.24.1

### Expected behaviour
When providing `direction="vertical"` - it is expected the scene comes in vertically

### Actual behaviour
The scenes only come in horizontally, from right to left.

### Steps to reproduce

1. Create a basic `Scene`
2. Add `direction="vertical"` to any `Scene`
3. Navigate to a `Scene` with the vertical direction

**Comment by cridenour** [comment]
#525 (aka please stick with 0.22 until further notice)

**Comment by alvarowolfx** [comment]
Just for the record, @ajwhite  you can force the scene to animate vertically using NavigationCardStackStyleInterpolator and getSceneStyle prop.

`
import NavigationCardStackStyleInterpolator from 'NavigationCardStackStyleInterpolator';

<Scene key="login" getSceneStyle={NavigationCardStackStyleInterpolator.forVertical}>
    <Scene key="loginScreen" component={LoginScreen} title="Login"/>
</Scene>
`

**Comment by jasongaare** [comment]
@alvarowolfx thanks for this! Is there a way to get it to come in from the top rather than the bottom with this?
