### ISSUE TITLE
Schema doesn't work when implementing tabs in a subcomponent

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#63]
When tabs are in a subcomponent of the main router, schema doesn't work. Trying to inherit a schema defined in the main router gives the error: `No schema=tab is defined for route=tab`.
Example code is [here](https://github.com/chetstone/react-native-router-flux/blob/d177cde5a9adcd10adcced6f0856b785b1d369c1/Example/components/TabContainer.js#L26).

If instead I try to insert the schema in the tab component's own router I get the error: `console.error: No icon class is defined for undefined`. Example code is [here](https://github.com/chetstone/react-native-router-flux/blob/0fabbed0dd537551c2548ecd24bff7124cd666d6/Example/components/TabContainer.js#L26).

**Comment by aksonov** [comment]
You must pass 'schemas' prop to Router to make it work:
```xml
          <Router footer={TabBar} showNavigationBar={false} navigator={this.props.navigator} schemas={this.props.schemas}>
```
