### ISSUE TITLE
How to update Tabbar ?

### ISSUE THREAD

**Issue by reddingit** [aksonov/react-native-router-flux#630]
I add a red dot on Tabbar to indicate has new message, blew is the code,

![qq20160504-0](https://cloud.githubusercontent.com/assets/5533582/15005274/0cb36e1a-11f5-11e6-9826-2f2bbe489074.png)

![qq20160504-2](https://cloud.githubusercontent.com/assets/5533582/15005320/bbc32a12-11f5-11e6-9d98-8f2df30d1caf.png)

The red dot default is hide, I don't know how to update Tabbar make it display , can any body help me?

**Comment by cridenour** [comment]
I see you have `showDot={false}` and one without showDot - in both cases, `this.props.showDot` will be false-y.

**Comment by reddingit** [comment]
@cridenour Yes, I only want the Message scene have dot.

**Comment by cridenour** [comment]
Then you'll need to change `showDot` to `{true}` for one of them

**Comment by reddingit** [comment]
Already tried Actions.refresh({showDot: true}) 、Actions.Tabbar({showDot: true}) 、Actions.Message({showDot: true}) ，nothing happen...

**Comment by sarovin** [comment]
The props showDot is undefined in the TabIcon, no? It is defined in the component 'MessageConintainer'...not?
Can you use console.log to display the status of this.props.showDot?

**Comment by reddingit** [comment]
showDot will pass to TabIcon.
The problem is I cann't find a way to reload TabBar after it rendered.

**Comment by sarovin** [comment]
You are looking for this https://facebook.github.io/react/docs/component-specs.html

**Comment by reddingit** [comment]
@sarovin Thanks.
Need find a way in these `Router,Scene,Actions` pattern...

**Comment by cridenour** [comment]
I don't think you should be using this library to pass that information down. You should still use a custom TabIcon but you should be using a Flux implementation like Redux or Alt to actually store the information of whether to show the dot - and have the TabIcon have a property of whether to connect to the store or not. 

So I would use `showDot={true}` and in your componentDidMount of TabIcon, `if (this.props.showDot) DotStore.listen(this._handleDot)` ... etc.

**Comment by reddingit** [comment]
Thanks @cridenour 
Finally, I solve this problem as you say. 
Declare a new TabIcon component, map `dot` state as its props.
