### ISSUE TITLE
Drawer hamburger icon replaced by back button

### ISSUE THREAD

**Issue by cjmarkham** [aksonov/react-native-router-flux#632]
- react-native-router-flux v3.22.23
- react-native v0.24.1

When implementing `react-native-drawer` the hamburger menu is replaced by the back button. Any way to get the hamburger menu on the right?

```
render() {
  return (
    <Provider store={store}>
      <Drawer
        tapToClose={true}
        content={<Sidebar />}
        openDrawerOffset={0.3}
        negotiatePan={true} >
        <RouterWithRedux>
          { Scenes.map(this.renderScene) }
        </RouterWithRedux>
      </Drawer>
    </Provider>
  );
}
```

**Comment by cjmarkham** [comment]
I got around this by using `renderRightButton` and `this.refs.drawer.toggle.bind(this)` and `renderBackButton` but is there a better option?

**Comment by cridenour** [comment]
I'm not sure if this is caused by #525 or not - so I'll keep it open. But if you can show that this is happening on 0.22 that would help narrow this down.  0.24 introduced tons of navigation bugs.

**Comment by davidfloegel** [comment]
Has there been any solution to this yet? Or any more ideas?

**Comment by cridenour** [comment]
Still waiting to see if this is an issue with the library or mis-matched versions. Can anyone try this on 0.26-rc with the 0.26-wip branch here?

**Comment by davidfloegel** [comment]
Ok thanks!
I will see if I have some spare time tonight then I can try it!

**Comment by rturk** [comment]
Not sure if I understand your question. My two cents...
I can't understand your code above. Why you're wrapping the drawer menu within the navigation logic? 

This is what works for me
  <Scene key="asda" component={DrawerMenu} type="reset" duration={1} initial={true} >

Also check this
https://github.com/aksonov/react-native-router-flux/blob/cad94673dd872669d49ec95895bd775592a13dec/Example/components/NavigationDrawer.js
