### ISSUE TITLE
Action.reset()

### ISSUE THREAD

**Issue by sce9sc** [aksonov/react-native-router-flux#633]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.22.23
- react-native v0.24.1

### Expected behaviour
Reset the scenes

### Actual behaviour
function undefined

### Steps to reproduce

1.
2.
3.

**Comment by cridenour** [comment]
So I wrote this into my branch, but recently stopped using it in favor of `Actions.scene({type: 'reset'})` - would that work for you? If not, I can submit a PR.

**Comment by cridenour** [comment]
Also, reset will not work for 0.24 (see #525)

**Comment by charpeni** [comment]
I'll close this issue since 0.26 will be landed in few days.

If you still get this issue with 0.26.0 (both updated react-native and react-native-router-flux), please reopen it.
