### ISSUE TITLE
Babel Plugin

### ISSUE THREAD

**Issue by sarovin** [aksonov/react-native-router-flux#635]
The Babel plugin:
 ```
    "babel-cli": "^6.6.5",
    "babel-core": "^6.7.6",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-native": "^1.5.6",
    "babel-preset-stage-0": "^6.5.0",

```
are all necessary for the component?

**Comment by cridenour** [comment]
I imagine this is related to #628 - I'm not sure of the deployment process used for the project, yes it does seem to be a hidden requirement given the latest push to npm.

**Comment by charpeni** [comment]
Thank you, I'll do some cleaning with babel soon.
