### ISSUE TITLE
Requiring React API in React Native version >= 25.1 is being deprecated.

### ISSUE THREAD

**Issue by isaiahgrey93** [aksonov/react-native-router-flux#638]
Using:
- react-native-router-flux v3.22.23
- react-native v0.25.1

### Actual behaviour

Importing any module that uses the `react-native` `Reactjs` API throws an exception and deprecation warning. importing `React` from `react-native` is being deprecated.

https://github.com/facebook/react-native/releases/tag/v0.25.1

### Expected behaviour

Be able to import modules that use the `react` Reactjs API.

### Steps to reproduce

1. install `react-native@v0.25.1`, `react-native-router-flux@v3.22.23`
2. `import { Actions, Scene, Router } from react-native-router-flux`

**Comment by sarovin** [comment]
#637

**Comment by cridenour** [comment]
Fixed by #637
