### ISSUE TITLE
how to jump into a child page?

### ISSUE THREAD

**Issue by nemosdo** [aksonov/react-native-router-flux#645]
### Version
- react-native-router-flux v3.22.23
- react-native v0.24.1

### Expected behaviour
1. index.js
`<Scene key="account" component={Account} icon={TabIcon} title="Account">
    <Scene key="register" component={Register} icon={TabIcon} title="Register"/>
    </Scene>
<Scene key="helpCenter" component={HelpCenter} icon={TabIcon} title="Help"/>`

2. account.js
`<TouchableHighlight underlayColor="#ddd" onPress={Actions.register}>`
nothing happens when i click the button,
but it works with 
`<TouchableHighlight underlayColor="#ddd" onPress={Actions.helpCenter}>`

so how should i do to make the 'account' page  jump into the child page 'register'  ?

**Comment by cridenour** [comment]
I know as part of 3.22.17, something was implemented for child routes of tabs, in #350 I think. I guess this didn't apply to other scenes.

Wonder if you can use 3.22.17 as a base and get it to work. If so, let us know!

**Comment by nemosdo** [comment]
Thanks for replay  , still not work with v3.22.17

**Comment by nemosdo** [comment]
it works when using like this, 

https://github.com/aksonov/react-native-router-flux#sub-scenes-support
