### ISSUE TITLE
Any way to use react-native-navbar with this?

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#65]
I like that your new version makes tabs a lot more useful (once the bugs are worked out), but your previous version used react-native-navbar, which made it fairly easy to create custom navigation bars. It seems like a lot work to try to figure out how to replicate this with ex-navigator. 

I need to pass custom components for left button, right button, and title (and also [style the navbar](https://github.com/aksonov/react-native-router-flux/issues/47)), and I don't have a clue how to do this.

You refer to the ex-navigator docs, and they refer to the [React Navigator](https://facebook.github.io/react-native/docs/navigator.html#content) docs, which are horrible. The reason I found your project in the first place was because I couldn't understand the React Navigator docs. Back to square one.

**Comment by aksonov** [comment]
React-native-navbar is ios-only and doesn't look good - i noticed some weird behavior with showing 'Back' button during transition for initial routes, nothing like that with built-in RN navbar.
It is easy to customize built-in RN navbar, i will add proper props to do it soon.

**Comment by aksonov** [comment]
Does navigationBarStyle work for you to style nav bar?

**Comment by chetstone** [comment]
Yes that does seem to work. Thanks.

**Comment by aksonov** [comment]
Closing it now, to customize buttons, refer to #61
