### ISSUE TITLE
Memory leak and there are alot of setState warning when rotate screen after calling screen transition

### ISSUE THREAD

**Issue by tinygipxy** [aksonov/react-native-router-flux#657]
I'm using: 
- react-native-router-flux v3.2.8
- react-native v0.22.0

### Expected behaviour
App work fine when rotate screen many times 
### Actual behaviour
Memory leak issue after 10-20 times rotate screen and there are alot of setState warning:
![image](https://cloud.githubusercontent.com/assets/7077139/15167388/1700ba92-175b-11e6-9dc5-f170829f1e93.png)

### Steps to reproduce

1. Download React-native-router-flux, open and run Example in XCode
2. Click "Go to login page", click "Back" to "Home" 
3. Rotate screen about 10 times 
4. Got the above error

### More infor:
I tried sample Navigation from React Navative's UIExplorer, don't have this issue
![image](https://cloud.githubusercontent.com/assets/7077139/15167281/4a73d9b4-175a-11e6-85b7-ffc1c546c725.png)

Thanks

**Comment by bosung90** [comment]
Have you tried adding
shouldComponentUpdate(){
return false
}
??

**Comment by tinygipxy** [comment]
Good suggest :-), why don't you tell me use static html instead of React

**Comment by aksonov** [comment]
@tinygipxy I suggest you to try experimental 0.26-wip branch with react native 0.26.0-rc. Looks like it is RN issue, not this component.

**Comment by bosung90** [comment]
@tinygipxy That's what you say to someone who is trying to help you out?

**Comment by tinygipxy** [comment]
@bosung90 Nothing serious here, thank you anyway
@aksonov you tried to use this component (3.22.23) with react-native 0.26.0-rc, but got issue "Super expression must either be null or a function, not undefined" that caused by : 
`import {Scene} from 'react-native-router-flux'` command

**Comment by cridenour** [comment]
@tinygipxy You also need to use the 0.26-wip branch..

**Comment by tinygipxy** [comment]
@cridenour Can you help to explain it more ? what is 0.26-wip and where can I get it ?

**Comment by cridenour** [comment]
It's a branch on this project. 

In your package.json, update this library to read 
`"react-native-router-flux": "aksonov/react-native-router-flux#0.26-wip",`

Then run `npm install` again.

**Comment by tinygipxy** [comment]
Yes, branch 0.26-wip with react 0.26.0-rc don't have this issue

**Comment by charpeni** [comment]
I'll close this issue since it's resolved by 0.26.

Thank you @tinygipxy.
