### ISSUE TITLE
Remove shadow on DefaultRenderer

### ISSUE THREAD

**Issue by Mokto** [aksonov/react-native-router-flux#658]
Hi,

I do not know if this is RNRF or [navigation-rfc](https://github.com/ericvicenti/navigation-rfc) related, but is there any way to remove shadow generated by RNRF on Scenes/DefaultRenderer ?

Thanks !

**Comment by aksonov** [comment]
Could you show screenshot? Also could you check 0.26-wip to see if it is fixed there (then it means that it was bug of navigation-rfc)

**Comment by Mokto** [comment]
![img_0113](https://cloud.githubusercontent.com/assets/5103928/15251169/1cabff82-18f6-11e6-8a9e-1ba426b39dec.PNG)

I hope you see it clearly but everything around a Scene container has a black shadow.

I even had to set my custom navbar to position: 'absolute' to hide this shadow.

This behaviour exists since 3.0.

**Comment by joenoon** [comment]
@Mokto I just updated the 0.26-wip branch to allow overriding the NavigationCard's default shadows.  Check the Example project on that branch and specifically `getSceneStyle`.

**Comment by Mokto** [comment]
Ok thanks man !
