### ISSUE TITLE
Setting Action.x({type: 'replace'}) does nothing

### ISSUE THREAD

**Issue by CoericK** [aksonov/react-native-router-flux#659]
- react-native-router-flux v3.22.23
- react-native v0.25.1
- react v0.14.8

When calling Action.x({type: 'replace'}) to replace the current scene for a new one, it does nothing, not errors, or warnings (besides deprecated React.createElement)

**Comment by sylvainbaronnet** [comment]
This is a known bug (from RN) and 0.25 is not officially supported, See #525

**Comment by CoericK** [comment]
@sylvainbaronnet @cridenour So what should i do? Lower my RN Version ?

**Comment by cridenour** [comment]
Most people are sticking with 0.22 for the time being. You're welcome to try the beta branch `0.26-wip` on this project and use the `0.26-rc` version of react-native. Or as others have pointed out, try using the 2.x branch of this project. 

I realize none are ideal, but most of the bugs are upstream in react-native.
