### ISSUE TITLE
Why does it create new instances of component every tab switch?

### ISSUE THREAD

**Issue by SunnyGurnani** [aksonov/react-native-router-flux#660]
We found that this router is creating new objects and calling constructor() of component on Tab Switch.

This make it really slow and un useful. Are we first to find this out ? 
Is there a workaround ?

**Comment by aksonov** [comment]
#525 ?

**Comment by SunnyGurnani** [comment]
You are right that was the issue we thought any version greater then 0.22 will work with the router.
Thanks for quick response.

**Comment by joenoon** [comment]
@SunnyGurnani ive added a 0.26-wip branch: https://github.com/aksonov/react-native-router-flux/tree/0.26-wip

It brings back the old behavior where all tabs are loaded, however there is a bug I haven't been able to figure out yet related to the "selected" tab changing on load.  But if you are trying to get things working with > 0.22 then it might make sense to check that branch out.

**Comment by SunnyGurnani** [comment]
Just to add one more thing when we used >0.22 transitions were always horizontal even when we set it as vertical. But when we downgraded to RN 0.22 it worked fine.
