### ISSUE TITLE
Scene preloading

### ISSUE THREAD

**Issue by kitolog** [aksonov/react-native-router-flux#662]
Hi, I'm using v3 and I need to preload some scene before it using. Scene contains video and I want to do something like:
1. On scene1 we do nothing
2. On scene2 we preload sceneVideo.  Preloading needed for video caching.
3. When user goes out somewhere from scene2 (to scene3, scene4,... etc) we show preloaded sceneVideo
4. return back to needed scene (scene3, scene4,... etc)

So, my question is: how can I create scene, keep it in memory and show only when it needed?

**Comment by rturk** [comment]
My two cents: RNRF manages the App navigation stack, just like any other framework it will not help with when and how you'll render and show stuff . For your use case you could use a app state (via redux for example) to decide when to show or not the Video.

My question is: Do you really need to preload a video? If you need to preload a VIdeo you shouldn't be using it in a MobileApp.. Think about Facebook. FB App shows millions of videos per hour, none of them is pre-loaded.

**Comment by bosung90** [comment]
You can try using tabbar without showing tabbar icons. 
After showing Scene 1, you can push tabbar
Tabbar has 2 tabs:
Tab1 has Scene 2 3 4 ... etc
Tab2 shows preloaded scene Video.
You can fire off loading the video at the same time you push the tabbar scene

**Comment by xvalentino** [comment]
I need to do this exact thing. On android there was a bug with using the tabbed views. Because the component wouldn't render the tab or update it if it was not in focus. Let me know if you figure this out, I'm still working on this.

https://github.com/aksonov/react-native-router-flux/issues/599

**Comment by ms88privat** [comment]
Creating a view (and destroying a view) before pushing them would be very cool. Would like to see an example of how to do it.

**Comment by aksonov** [comment]
Seems this more question to RN new Navigation API, not for this component, because this component is just wrapper.

**Comment by xvalentino** [comment]
Anyone figure this out? Or does anyone have an idea to where in the new Navigation API this functionality is at? What I'd like is to basically have all of my tabs be able to be updated, even if they aren't in focus.

**Comment by xvalentino** [comment]
Here's a branch where this is possible within tabbed Scenes. 

https://github.com/xvalentino/react-native-router-flux/commit/30fc19b65c99f869b6025f5d89014ab47eeef9f8.

You can call `Actions.scene` within `componentDidMount` or in an Image/Video's `onLoad`

@ms88privat @kitolog

**Comment by aksonov** [comment]
@xvalentino could you submit PR to make it configurable option (like preloadScenes, false by default) ?

**Comment by xvalentino** [comment]
@aksonov yeah sure thing.

I'm pretty sure this.props.navigationState is where the props would be for this component in TabbedView, I'm just going to have to make sure TabBar passes its props to it.

**Comment by xvalentino** [comment]
Can anyone find a way to test this in the example, I think I'd need a little help putting this into a PR

(or if someone can point me into the right direction that'd be great)

**Comment by Mohamed-Abo-El-Soud** [comment]
@xvalentino The best way to test this is to transition between two gifs (two scenes, each containing a gif).

So scene 1 has a gif,
and scene 2 has another gif

What you will notice is that the way it is right now, pushing a new scene while two gifs are running simultaneously (one in scene 1 and the other in scene 2, and you are transitioning from scene 1 to scene 2) is causing a lot of dropped frames in the transition animation.

HOWEVER, while you are on scene 2, popping the navigation stack will go back to scene 1. But what you will notice is that while popping, there doesn't seem to be a performance lag, even though it's still switching between two gifs.

I think the reason for this is that while it is popping, both scene 1 and scene 2 were already preloaded and the phone did not have to re-render the components. however in the first scenario, when you are pushing a new scene, the component is being re-rendered while the scene transition is happening, hence the performance lag.

( I came across a similar scenario to the one I'm describing to you).

**Comment by Mohamed-Abo-El-Soud** [comment]
BTW @aksonov can we reopen this issue until someone submits a PR for the preloading of tabs?

**Comment by markdaws** [comment]
Any update on this?  I want to preload a WebView inside a stack navigator so when the user clicks on an item in a list the view is already loaded as it transitions in. Is it possible to do this now with RNRF?
