### ISSUE TITLE
From within a scene, put an icon in the navbar

### ISSUE THREAD

**Issue by anthonywebb** [aksonov/react-native-router-flux#663]
I have a scene/component that has a form, once the form is complete I would like to put a save button up on the right side of the navbar.  Can the navbar be manipulate by code inside a scene?  Or is it only possible to add/remove navbar buttons when you initially set up your router and scenes?

Thanks!

**Comment by wireblue** [comment]
Hi @anthonywebb,

I believe this is one way of doing it.
https://github.com/aksonov/react-native-router-flux#sub-scenes-support

I've not used this feature before, but I would imagine you'd setup a "save" sub-scene (with a key of "form_save" for example) and run `Actions.form_save()` when you want the save button shown.

I'm sure there are other ways of achieving a similar result also.

**Comment by anthonywebb** [comment]
I'll have to give that a try.  

I am also wondering if maybe this can be done via Actions.refresh() ?

**Comment by bosung90** [comment]
yes you can do it with Actions.refresh({})
just override rightButtonImage and onRight or use other props if you want only text.

**Comment by ms88privat** [comment]
@anthonywebb I tried the sub-scenes thing @wireblue mentioned and it did work for me.

**Comment by joenoon** [comment]
@anthonywebb Actions.refresh or sub-scenes should do the trick here.  Please re-open if there are any issues.
