### ISSUE TITLE
Process 'command 'node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by devux** [aksonov/react-native-router-flux#666]
Hello all,
I'm getting these error while building APK using this https://facebook.github.io/react-native/docs/signed-apk-android.html

Error:
uncaught error Error: TypeError: /home/devux/Desktop/events-photo-react/node_modules/react-native-router-flux/src/NavBar.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
    at Object.validate (/home/devux/Desktop/events-photo-react/node_modules/babel-types/lib/definitions/index.js:115:13)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

Version using:
react-native: 0.24.0
react-native-router-flux: 3.22.0

**Comment by aksonov** [comment]
#525 ??

**Comment by aksonov** [comment]
666 issue should be like this ;)

**Comment by charpeni** [comment]
I'll close this issue since 0.26 will be landed in few days.

If you still get this issue with 0.26.0 (both updated react-native and react-native-router-flux), please reopen it.

**Comment by devux** [comment]
I've modified my babelrc file now its working

**Comment by rodan-lewarx** [comment]
@devux Hi, I have the same issue. What have you modified in your babelrc? Thanks

**Comment by jssisodiyaPG** [comment]
@devux what changes you made in your babelrc file

**Comment by abhishkekalia** [comment]
TransformError: /home/reactjs/refrence/ProjectTest/node_modules/react-native/Libraries/react-native/react-native-implementation.js: EISDIR: illegal operation on a directory, read

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.887 secs

**Comment by pottercomuneo** [comment]
Could someone please explain which was the solution? It's not clear to me even after reading #525.
Thanks!

**Comment by OrangeFlavoredColdCoffee** [comment]
i solved  this  ,by run react-native run-android   and error msg will show clearly , but when you build in  AndroidStudio, can not locate error msg .
for me ,just because one comma 



![wechatimg197](https://user-images.githubusercontent.com/15223345/45815650-e3dcfa00-bd0b-11e8-82c4-de9d33d5a740.jpeg)

**Comment by patel-harshal** [comment]
how to i solve this problem! am try to build my react native .abb file for my application. 
![1](https://user-images.githubusercontent.com/42863078/122666111-0821da00-d1c9-11eb-93e4-8cb3770fa5d7.png)
