### ISSUE TITLE
Image Flickering when navigating to another View

### ISSUE THREAD

**Issue by Evinon** [aksonov/react-native-router-flux#675]
### Version
- react-native-router-flux v3.22.23
- react-native v0.24.1
- react v0.14.8

### Expected behaviour
I do expect that the Images ( does not matter where they are ) do not get re-rendered when I move to another View. 

### Actual behaviour
I do have two Screens which both use the same NavBar as defined in the Root-Scene.
When I Navigate from one View to another then the Image which is placed at the NavBar flicker's.
It disappears for a short time and then it comes back. 

### Steps to reproduce

1. Create a Component which returns the follwing: <View> <Image /></View>
2. Pass this Component as the navBar parameter in the Root Scene.
3. Navigate to an other View and you will notice that the Image will get re-rendered.

**Comment by aksonov** [comment]
#525

**Comment by Evinon** [comment]
@aksonov -.- Sorry, my fault.
