### ISSUE TITLE
Actions aren't fired within react-native-side-menu based components

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#676]
### Version
- react-native-router-flux v3.22.23
- react-native v0.25.1

Can you give some hints about correct usage of react-native-router-flux together with react-antive-side-menu?

Following the docs is the most outer element a < SideMenu >, encapsulating the < Router >-Component, like so:

```
export default class Application extends React.Component {
	render() {
		const menu = <MySideMenu navigator={navigator}/>;

		return (
			<SideMenu menu={menu}>
				<Router createReducer={reducerCreate}>

					<Scene key="root" hideNavBar={true}>
						<Scene key="home" component={HomeScreen} title="Home" initial={true}/>
						<Scene key="login" hideNavBar={true} component={LoginScreen} title="Login" panHandlers={null}
							   duration={1}/>
					</Scene>

				</Router>;
			</SideMenu>
		);
	}
}

```

Doing this everything works fine, but when i place some buttons with actions inside the side menu, no action will be taken. Nothing happens, while placing the buttons on home-screen and other components are working fine.

I've read the section "Drawer (side menu) integration" in your README.md, but can't apply this on this case.

Thank you!

**Comment by cridenour** [comment]
This sounds like #525. Feel free to re-open if you find this with 0.22.

**Comment by itinance** [comment]
Don't know what you mean. None of the listed issues in #525 are related to this issue. Also i use react-native 0.25 and not 0.22.
Please correct me if i misunderstood you
