### ISSUE TITLE
Using redux fails

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#680]
I tried to use this router component with redux passing state and actions and ran into several issues.
Thus i tried to fill up an already existing redux example application with this routing-approach.

However, it doesn't work and produce an error "Action should be defined".

I published an example project "Counter" on github for reproducing: https://github.com/itinance/example-react-native-redux-with-router
and extended with this router-stuff. It is the Counter-Directory.

How is it possible to combine this router-implementation with Redux?

**Comment by danawoodman** [comment]
What is the full stack trace?

Why are you passing in actions like you did? Why not instead use the `Actions` method?

```js
import { Actions } from 'react-native-router-flux'

// elsewhere pass in `Actions.yourRoute()`...
```

Also, did you follow [this guide](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md)?

**Comment by itinance** [comment]
@danawoodman for registered routes is Actions the right choice as you wrote. But those route-Actions are pretty working. My issue is, that my own actions aren't working that way and they have nothing to do with the route-actions in "Actions" from react-native-router-flux. Anyway, i've got the solution, will share it in a new comment

**Comment by itinance** [comment]
To make custom actions work, every component needs apparently to be connected with redux' "connect" method. This commit will solve my issue: https://github.com/itinance/react-native-router-flux/commit/65db001441406878a56b4ee8215825ae44ad4626

But i'm wondering about. In another project i switched to "react-native-router-redux", which works pretty well with connecting the actions only once in the root application component.
