### ISSUE TITLE
Using redux: passing state to a scene won't update on state modifications

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#681]
**Versions**:
    "react-native": "0.22.2"
    "react-native-router-flux": "3.22.23"

**The issue:**

Building a react native app using redux and this router library will not work together as expected.
Reducers are working fine, but the state will not being updated in nested components.

Won't work:

```
		const { state, actions } = this.props;
        return <Router createReducer={reducerCreate}>

			<Scene key="root" hideNavBar={true}>
				<Scene key="home" component={HomeScreen} title="Home" state={state} {...actions} />
			</Scene>

        </Router>;

```

HomeScreen:

```
render(){
		const { state, decrement, increment } = this.props;

        return (
            <View {...this.props}  style={styles.container}>

				<Text>{state.userId}</Text>

				<Button onPress={increment}>Increment</Button>
                <Button onPress={Actions.login}>Login</Button>
				<Button onPress={Actions.launch}>Intro</Button>
            </View>
        );
    }
```

Using no router this will work fine on state updates:

```
        return (
            <View {...this.props}  style={styles.container}>
				<Text>{state.userId}</Text>
				<Button onPress={increment}>Increment</Button>
                <Button onPress={Actions.login}>Login</Button>
				<Button onPress={Actions.launch}>Intro</Button>
            </View>
        );

```

**Comment by itinance** [comment]
I published an [example application](https://github.com/itinance/react-native-router-flux/tree/master/ExampleRedux) as an entire copy of the original example application, which demonstrates this issue. In the launch screen i placed a simple counter with "increment" button. The counter is being incremented well in state, but not the view:

**Comment by aksonov** [comment]
@itinance What scene should be updated? Have you connected your scene to Redux? As I see you connected container but not particular scene.

**Comment by itinance** [comment]
Ah yes, that was the right hint. This was a misunderstanding on my site. Thank you very much. For the sake of completeness and if others run into this issue too, i updated the Example to work.
