### ISSUE TITLE
How to Force Navigation Bar to re-render

### ISSUE THREAD

**Issue by andyshuxin** [aksonov/react-native-router-flux#683]
Update: I found a work around, by calling `Actions.refresh({leftButtonImage: null})` in `clickTrash`

### Version
"react-native-router-flux": "3.22.23",
"react-native": "0.24.1",

### Expected behaviour
<img width="487" alt="screen shot 2016-05-16 at 16 19 24" src="https://cloud.githubusercontent.com/assets/233354/15284151/38d81252-1b82-11e6-82f6-d563ec014503.png">
I have a UI like this. I like that when I click the trash bin button on top-left, it'll be hidden. (This is the thing that I can't achieve.)

Essentially, the code is
```
<Scene key="
       component={EditorView}
       title="Editor"
       leftButtonImage={
              this.props.isDeleting
              ? ''
              : require('./shared/assets/trash.png')
      }
      onLeft={this.props.clickTrash}
/>

And `this.props.clickTrash` will change internal state `isDeleting`.

Changing UI according to `isDeleting` works for content in the main view (below navigation), but doesn't for the navigation bar.
```

### Actual behaviour
The navigation bar remains the same. I put `console.log(this.props.isDeleting)` in `render()` of `Router` and `isDeleting` changed from `false` to `true`, but the UI of the navigation icon doesn't change.

I don't think this is related to image, as changing the text on right button doesn't work either.
I tried `this.forceUpdate()` in onLeft, and it doesn't work either.

Where should I be looking? Thank you very much!

**Comment by joenoon** [comment]
Looks like you solved it with Actions.refresh which is correct, so I'll close.

**Comment by symmetriccurve** [comment]
leftButtonImage does not work! How did you get it to work. It  works on right though

**Comment by andyshuxin** [comment]
@symmetriccurve We didn't. We just wrote a custom `NavigationBar`.

**Comment by aksonov** [comment]
@symmetriccurve If this is not top-level element in the current stack, backButtonImage will be displayed (that is more logical).
