### ISSUE TITLE
Is it possible to have a fixed view of fixed width/height outside a router?

### ISSUE THREAD

**Issue by shraddha1704** [aksonov/react-native-router-flux#684]
### Version
react native 0.22.2
- react-native-router-flux v3.x

### Expected behaviour
A small fixed view should be present on top of each scene.

### Actual behaviour
View outside Router tag does not work.

`<View style={{flex:1}}>
<Provider store = {store}>
            <Router hideNavBar={true}>
                <Route name="s1" component={s1} initial={true}/>
                <Route name="s2" component={s2} type="replace"/>
                <Route name="s3" component={s3} type="replace"/>
                <Route name="s4" component={s4} type="replace"/>
                <Route name="s5" component={s5} />
              </Router>  
</Provider>
<View style={{position:'absolute', top:0, left:0, width: 100, height: 100}}>
             <Text>Hi</Text>
</View>
</View>
`

**Comment by 009dollar** [comment]
I am facing a similar issue. has anyone found a solution?

**Comment by cridenour** [comment]
You could use `src/TabBar.js` as inspiration for rendering a child scene with a "static" component.
