### ISSUE TITLE
Adding styles to a tab bar causes poor performance

### ISSUE THREAD

**Issue by greatwitenorth** [aksonov/react-native-router-flux#687]
### Version
- react-native-router-flux v3.22.23
- react-native v0.22.2

### Expected behaviour
When I add a style to a tab bar I expect the style to show and the application to retain the same level of performance (memory, cpu usage etc) before the style was applied

### Actual behaviour
The style is displayed correctly, but as I navigate to several screens the ram and CPU usage climb rapidly until the entire app crashes. The moment I remove the style the app functions as normal.

### Steps to reproduce

1. add the following style to a tabbar:
```
style={{borderTopWidth: 1, borderTopColor: '#f2f2f2', backgroundColor: '#fff'}}
```
2. Start to navigate between several screens (part of the tabbar or not)
3. After about 5 screens the entire app will crash.

**Comment by charpeni** [comment]
On iOS, Android or both?

**Comment by greatwitenorth** [comment]
I've only tested on iOS. It happens on both the simulator and an actual device.

**Comment by ptomasroos** [comment]
Can you create a repo with the code @greatwitenorth ?

**Comment by joenoon** [comment]
@greatwitenorth if possible you might want to try with the 0.26-wip branch.  RN 0.26 stable is right around the corner and the react-native-router-flux 0.26-wip branch has quite a few changes - especially dealing with the TabBar.

**Comment by aksonov** [comment]
Check latest 3.26.0 and re-open this ticket if issue remains.
