### ISSUE TITLE
Use tabbar,Click the tab item,the page will render again.

### ISSUE THREAD

**Issue by yanghuxiao** [aksonov/react-native-router-flux#690]
### Version
- react-native-router-flux v3.24.1
- react-native v0.24.1

### Expected behaviour
when i go to the listview page,the listview's data loaded,then i scroll to the end,now I click the tab item to change the page.but i click the tab to go to listview,the data loaded again,and it scroll to the top.
i want to keep the listview state.don't want to reload the data and scroll to top.

### Actual behaviour
list view data reload and scroll to top,may be the page reload.not go back.

### Steps to reproduce

1.create the listview page,and load data.
2.click the tabbar item to go to another page
3.click listview item to go back.

**Comment by ptomasroos** [comment]
See #525

**Comment by joenoon** [comment]
@yanghuxiao  if possible you might want to try with the 0.26-wip branch. RN 0.26 stable is right around the corner and the react-native-router-flux 0.26-wip branch has quite a few changes - especially dealing with the TabBar.

**Comment by yanghuxiao** [comment]
@joenoon thank you
