### ISSUE TITLE
RCTRootView.h' file not found

### ISSUE THREAD

**Issue by ismeteor** [aksonov/react-native-router-flux#691]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Steps to reproduce

1.
2.
3.

**Comment by cridenour** [comment]
This is a problem with your react-native installation, not this library. Feel free to jump in the Gitter to ask for more general help though!
