### ISSUE TITLE
Issue Causing ReactNative.createElement

### ISSUE THREAD

**Issue by DavidBrear** [aksonov/react-native-router-flux#693]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.22.23
- react-native v0.25.1

### Expected behavior

Source code on github for version 3.22.23 has

```
import React from 'react';
```
inside of `Scene.js` (there are other files but this has been my litmus test) but when I do `npm install --save react-native-router-flux` it pulls down version 3.22.23 but in `Scene.js` it has:

```
import React from 'react-native';
```
Other files throw the the warning `ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead.`

<img width="377" alt="screen shot 2016-05-17 at 8 45 17 am" src="https://cloud.githubusercontent.com/assets/1081640/15322650/02acc7ec-1c0c-11e6-8e63-ae9e8c32f129.png">
<img width="1393" alt="screen shot 2016-05-17 at 8 45 40 am" src="https://cloud.githubusercontent.com/assets/1081640/15322656/07c5cc88-1c0c-11e6-8a44-b4b154e14d18.png">
<img width="765" alt="screen shot 2016-05-17 at 8 46 02 am" src="https://cloud.githubusercontent.com/assets/1081640/15322657/099056a0-1c0c-11e6-944f-dd1af624e06b.png">
<img width="943" alt="screen shot 2016-05-17 at 8 46 21 am" src="https://cloud.githubusercontent.com/assets/1081640/15322660/0cf0dbf8-1c0c-11e6-80c1-07a3f8169414.png">

package.json:
```
{
  "name": "testProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "flow": "flow; test $? -eq 0 -o $? -eq 2"
  },
  "dependencies": {
    "key-mirror": "^1.0.1",
    "lodash": "^4.12.0",
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-keyboard-spacer": "^0.2.0",
    "react-native-router-flux": "^3.22.23",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "flow-bin": "^0.24.2"
  }
}
```

### Steps to reproduce

1. cleared my cache with `npm cache clear react-native-router-flux`
2. Verified there was no `react-native-router-flux` inside my ~/.npm directory
3. Started a new react native project `react-native init testProject`
4. Added react-native-router-flux to the project `npm install --save react-native-router-flux`
5. Start App up and observe issue.

**Comment by charpeni** [comment]
@aksonov didn't publish `react-native-router-flux` to npm since 3 weeks, I guess a new release will be published when 0.26 will land.

**Comment by cridenour** [comment]
For the time being, I suggest you change your package.json to use `askonov/react-native-router-flux#0.26-wip` if you really need to use anything beyond 0.22.

**Comment by DavidBrear** [comment]
Sounds good. I just wasn't sure since it says it's version 3.22.23 via NPM but the code is slightly different from what's available from master branch. I honestly just went into each of the files and manually changed it to use `react` which solved the warning problem. Not my finest moment but it worked.
