### ISSUE TITLE
"replace" and "reset" not working?

### ISSUE THREAD

**Issue by danawoodman** [aksonov/react-native-router-flux#695]
### Version
v3 is SLOW for Android right now (because React Native ExperimentalNavigation is slow), see #355, no need to create new issue!
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.22.22
- react-native v0.24.1 (react 0.14.8)
- redux 3.5.2

### Expected behaviour

Calling `Actions.someAction({ type: 'replace' })` (or `reset`) should change the current route/component to `someAction`.

### Actual behaviour

The route changes but does not cause the view to re-render, leaving part of the UI from the previous route visible. 

It appears that the menu changes but the underlying component does not re-render for some reason.

I have attempted to call this action in my container component, an action and a `Scene`'s `onLeft`/`onRight` all with the same effects. Navigation seems to work otherwise if I use the default `push` type.

### Steps to reproduce

1. Create two routes (`myFirstRoute`, `mySecondRoute`)
2. Navigate to `mySecondRoute` route from `myFirstRoute`, have an action that calls `Actions.myFirstRoute({ type: 'reset' })`
3. The route changes but part of the `mySecondRoute` still displays on the screen

**Comment by sunnyyants** [comment]
Yes, I have the same situation when I try to use reset after authentication...

**Comment by cridenour** [comment]
#525 !

**Comment by danawoodman** [comment]
@cridenour I see that now but please realize the current readme does not say this anywhere. Until that changes, I imagine a lot more similar issues are created unfortunately. 

That said, it looks like v0.26.0 was just released so I imagine this won't be an issue soon.

Cheers 🍻
