### ISSUE TITLE
Unable to resolve module buffer

### ISSUE THREAD

**Issue by joenoon** [aksonov/react-native-router-flux#697]
@ronak301 ran into this on gitter and I tracked it down to a recent release of "assert".  I've created an issue over there: https://github.com/defunctzombie/commonjs-assert/issues/20

For now, I've updated the 0.26-wip branch to lock "assert" @ 1.3.0 : https://github.com/aksonov/react-native-router-flux/commit/15696515400126b74ce8ff93ca42ec558be58d44

Any ideas how to address it in the existing versions?

The hotfix is for the user to manually force their own dependency:

```
npm install --save assert@1.3.0
```

So maybe that needs to go in the README on master?  Its unclear if this is just a temp bug upstream and if they plan on yanking 1.4.0 or if we need to plan around this.

**Comment by ronak301** [comment]
Ya this have solved my problem for the time being. Thanks to @joenoon for quick reply.

**Comment by JimmyStavros** [comment]
I'm still having the same issue even after manually installing the dependency, anything else I can try?

**Comment by joenoon** [comment]
@JimmyStavros try a thorough reset:

```
(set -ex; rm -rf node_modules/ && npm cache clear && npm install && (watchman watch-del-all || true) && rm -fr $TMPDIR/react-* && node_modules/react-native/packager/packager.sh --reset-cache true)
```

**Comment by aksonov** [comment]
@joenoon what about removing this dependency at all and replace to own function to check condition and raise exception if it is not true?

**Comment by joenoon** [comment]
@aksonov that sounds great!

**Comment by calvinmetcalf** [comment]
FYI this exists https://github.com/calvinmetcalf/minimalistic-assert

**Comment by aksonov** [comment]
@calvinmetcalf Let's don't repeat the same error - avoid dependency if possible. Because author of minimalist-assert could publish new version that brake build again... It is definitely weak side of NPM.

**Comment by calvinmetcalf** [comment]
I'm the author of minimalistic-assert fyi but it would probably make sense to just require a specific version

**Comment by cridenour** [comment]
I think @joenoon pushed a version to our new Utils file. But let's all remember the left-pad insanity before we introduce dependencies for 3 lines :)

**Comment by lwansbrough** [comment]
Libraries should version lock their dependencies. Using the carat is dangerous.

**Comment by calvinmetcalf** [comment]
in fairness it's especially dangerous for a situation like react-native
where you are consuming libraries from a different ecosystem meaning things
that are not a breaking change in node/browserify/webpack are breaking for
you guys
