### ISSUE TITLE
Is there a way to hide status bar?

### ISSUE THREAD

**Issue by zccan** [aksonov/react-native-router-flux#699]
### Version 3.1.5
Is there a way to hide status bar?
Like [this](https://facebook.github.io/react-native/docs/statusbar.html)?
<Navigator
     initialRoute={{statusBarHidden: true}}
...

**Comment by Kerumen** [comment]
You can do it in the `componentWillMount` hook of your initial `Scene` with the static API of `StatusBar`:
```
componentWillMount() {
  StatusBar.setHidden(true);
}
```

**Comment by timzaak** [comment]
I change the status bar by native code.

**Comment by jeroenbourgois** [comment]
Does this work for you @zccan ?

**Comment by zccan** [comment]
@jeroenbourgois yes this helps. thank you @Kerumen

**Comment by dann1609** [comment]
this is not hidden status bar. Only hide text but bar still present

Captura de pantalla 2017-09-03 a la(s) 12.35.44 p.m.

**Comment by Biplovkumar** [comment]
this is not hidden status bar. Only hide text but bar still present

**Comment by daviscabral** [comment]
That's not related with `rnrf`. 

Use just `react-native` to do it. https://facebook.github.io/react-native/docs/statusbar.html.
