### ISSUE TITLE
version 0,.26 showing error

### ISSUE THREAD

**Issue by gmchaturvedi1** [aksonov/react-native-router-flux#700]
i have just upgraded to 0.26 react-native but showing error.Can u help me on this 

![image](https://cloud.githubusercontent.com/assets/10846505/15391469/f0bbab0a-1dde-11e6-9872-74b1a49ff461.png)

**Comment by xotahal** [comment]
I think, [update to 0.26-wip](https://github.com/aksonov/react-native-router-flux/issues/636#issuecomment-220253826) could help for now

**Comment by gmchaturvedi1** [comment]
how to do that can u suggest?

**Comment by xotahal** [comment]
npm i react-native-router-flux@aksonov/react-native-router-flux#0.26-wip

**Comment by rturk** [comment]
@gmchaturvedi1 
In General  ...super expression must be either null.. means that one ore more of your external dependencies are using legacy React import due to breaking changes in RN0.26

**Comment by joenoon** [comment]
Agree with @rturk this is usually because a dependency does `import Foo from 'react-native'`, and then extends `Foo.Component`, which no longer exists since RN 0.26.

Also things may have stabilized since two days ago, so give the upgrade another try.
