### ISSUE TITLE
How to reset?

### ISSUE THREAD

**Issue by anthonywebb** [aksonov/react-native-router-flux#702]
On the README it mentions

> Reset History Stack - The new reset Action for clearing the history stack and eliminates the navbar back button.

Exactly what I am looking for, but I dont know how to use the new reset action.  I couldnt find any info in the documentation or examples.  Can someone help?

**Comment by cridenour** [comment]
Your best bet is to use type="reset" when defining scenes or when using `Actions.scene()` instead do `Actions.scene({type: "reset"})`.

I had a branch where I created a Actions.reset() but it felt like overkill vs. passing in the type.

**Comment by anthonywebb** [comment]
@cridenour that worked great, thank you!
