### ISSUE TITLE
Error with menu_burger.png

### ISSUE THREAD

**Issue by jneumann** [aksonov/react-native-router-flux#703]
### Version
- react-native-router-flux v3.22.23
- react-native v0.26.0

### Expected behaviour

This is with a new React Native project. The first time I run the app, without editing anything except adding react-native-router-flux

### Actual behaviour
"/Users/jneumann/Projects/portfolio/node_modules/react-native-router-flux/src/menu_burger.png: Unexpected Character '?' (1:0) at menu_burger.png:1:0
<img width="571" alt="screen shot 2016-05-19 at 8 50 03 pm" src="https://cloud.githubusercontent.com/assets/4145595/15414788/6ffeb0aa-1e03-11e6-8f2b-a3ced06bfd3f.png">

**Comment by cridenour** [comment]
We haven't pushed a version compatible 0.26 to NPM yet. Go ahead and change your package.json to `"react-native-router-flux": "aksonov/react-native-router-flux#0.26-wip",`

**Comment by jneumann** [comment]
Jawesome! That works now.

**Comment by DominicTobias** [comment]
I have the same error with the latest version and latest react/react-native on an empty project

**Comment by DominicTobias** [comment]
The solution was to quit the emulator *and* the packager terminal and restart

**Comment by xRapidDavex** [comment]
my package.json is pointing to `"react-native-router-flux": "^3.33.2"` and @DominicTobias 's suggestion worked for me.

**Comment by nalwayaabhishek** [comment]
I am getting same error, while running the test with mocha. I also tried to use "react-native-router-flux": "aksonov/react-native-router-flux#0.26-wip" but no luck.

**Comment by casenjo** [comment]
@nalwayaabhishek have you found a solution to your mocha tests? The suggestion by @hellogerard in #628 fixes my tests, but I don't know what (if any) negative effects it could have to silence the mockery warnings

**Comment by j-wang** [comment]
For posterity, since I almost missed it scrolling through after being brought here on Google by this error message:

@DominicTobias's solution worked for me. 
RN v0.33.0 and react-native-router-flux v3.35.0.

**Comment by Baskerville42** [comment]
[This comment is helpful, thanks!](https://github.com/aksonov/react-native-router-flux/issues/703#issuecomment-236175231)

**Comment by luisfrocha** [comment]
@DominicTobias 's solution worked for me.
