### ISSUE TITLE
Warning due to a upgrade react-native to 0.26 [using key props]

### ISSUE THREAD

**Issue by oziks** [aksonov/react-native-router-flux#705]
I explain you my workflow :
* react-native-router-flux #master
* react-native v0.26.0
* react v15.0.2

I just created an issue on https://github.com/exponentjs/react-native-tab-navigator/issues/75 repository. According to React warning message, using `key` props is not recommended. 

You'll make a way to fix this message?

**Comment by cridenour** [comment]
You can always use `console.ignoredYellowBox` until they fix it upstream.
