### ISSUE TITLE
Implementing Actions.xxx in function

### ISSUE THREAD

**Issue by gerard0315** [aksonov/react-native-router-flux#707]
Hi, I'm using RN0.24 and flux3.26. RN version may be out-dated but the Actions.xxx works fine when I'm using `onPress={Actions.xxx}`
However once I put it into functions like `onPress=this.function` and in function i do 
`function(event){ Actions.xxx; }` then it's not working
can anyone help with this? thank you!!

**Comment by msathis** [comment]
Shoudn't you call Actions.xxx() inside your custom onPress handler?

**Comment by gerard0315** [comment]
@msathis lol thanks just realized it
