### ISSUE TITLE
Passing data to nested routers

### ISSUE THREAD

**Issue by emrosenf** [aksonov/react-native-router-flux#71]
I have this part of my router, pretty much straight out of the example. There are three levels of routers: the tab bar itself, the first tab, "discover", has it' own tab history, and then the modal tab, "artist".

                <Route name="tabbar">
                    <Router footer={TabBar} showNavigationBar={false}>
                        <Route name="discover" schema="tab" title="Discover" >
                            <Router>
                                <Route name="discoverMain" component={DiscoverPage} title="Discover Page" />
                                <Route name="artist" schema="modal">
                                    <Router hideTabBar={true}>
                                        <Route name="artistMain" component={ArtistPage} title="Artist" schema="modal"/>
                                    </Router>
                                </Route>
                            </Router>
                        </Route>
                        <Route name="tab4" schema="tab" title="Tab #2" component={TabView} />
                        <Route name="tab5" schema="tab" title="Tab #3" component={TabView} />
                    </Router>
               </Route>

Suppose I'm on the `DiscoverPage`, and I want to get to `ArtistPage`. I will call `Action.artist({data: obj})`, passing in some data. The Router's `push` function will be called twice: first for the "artist" route, and then for the "artistMain" route.

The problem is that the `data` will be attached to the props of the first route, and not the second. The result is that the `data` object is not attached to the `ArtistPage` component.

**Comment by aksonov** [comment]
Good catch, looks like we need to pass all data from Route to inner Router and from Router to inner Routes.

**Comment by andreasbhansen** [comment]
Any news on this, @aksonov ?

**Comment by aksonov** [comment]
@andreasbhansen Just released 2.0, it should work there - 'data' prop is passed to children routes, please check

**Comment by joshloo** [comment]
Hi everyone, 
Suppose I have a page before tabbar. Something like this:

<Router createReducer={reducerCreate} getSceneStyle={getSceneStyle}>
                <Scene key="modal" component={Modal} >
                    <Scene key="root" hideNavBar hideTabBar>
                        <Scene key="LoginPage" component={LoginPage} initial/>
                        <Scene key="tabbar" component={NavigationDrawer}>
                            <Scene key="main" tabs tabBarStyle={styles.tabBarStyle}
                                tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle}>
                                <Scene key="tab1" initial title="Dashboard" icon={TabIcon}>

How should I pass data from Login Page to tab1?
