### ISSUE TITLE
Drawer icon size is much bigger than it should be

### ISSUE THREAD

**Issue by codyhazelwood** [aksonov/react-native-router-flux#713]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.0 (issue was present in latest v3.22.x as well)
- react-native v0.26.1 (issue was was present in v0.24.x)

### Expected behaviour

Hamburger icon should be normal size

### Actual behaviour

Hamburger icon is double size.  I know it's not just me, as nearly all of the screenshots I've seen show the hamburger icon being pixelated and the full height of the navbar instead of the previous normal size.

### Steps to reproduce

1. Upgrade from RNRF v3.2.0 to v3.26.0

**Comment by codyhazelwood** [comment]
Worked around it for now by doing:
```
<Router leftButtonIconStyle={{height: 24, resizeMode: 'contain'}}>
    ...
</Router>
```

But I'd still say it's a bug since it changed between versions of RNRF.

**Comment by aksonov** [comment]
@codyhazelwood Could you submit PR, thanks!
