### ISSUE TITLE
RNRF v3.26.1 / RN 0.26.1 Error: "navigationState and onNavigate property should be not null"

### ISSUE THREAD

**Issue by sylvainbaronnet** [aksonov/react-native-router-flux#715]
### Version

- react-native-router-flux v3.26.1
- react-native v0.26.1

Got error  on launch : 
![screen shot 2016-05-22 at 10 43 25](https://cloud.githubusercontent.com/assets/1569516/15453155/93df4d96-200a-11e6-8e26-3aef876d0edf.png)

@joenoon Code must be updated for 0.26 ?

**Comment by xotahal** [comment]
It's just a guess. If you use side menu, you will have to add `onNavigate` prop to `DefaultRenderer`. In  [side menu integration](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration) example is same issue - there is not `onNavigate` prop.

```js
<DefaultRenderer navigationState={children[0]} />
```
vs.
```js
<DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
```

And also, if you use `DefaultRenderer` somewhere, you should pass `onNavigate` prop now

**Comment by sylvainbaronnet** [comment]
Good guess, it fixes the error, thanks !

Now my custom navbar doesn't appear anymore and the side menu is not accessible

**Comment by sylvainbaronnet** [comment]
It's ok, I had just to remove `hideNavBar={true}`
