### ISSUE TITLE
Tapping a tab should navigate to the default scene for that scene group

### ISSUE THREAD

**Issue by Olliepop** [aksonov/react-native-router-flux#717]
### Version
- react-native-router-flux v3.26.1
- react-native v0.26.0 & v0.26.1

I am using the Example app.
### Expected behaviour

In the Example, when I go to the "TabBar page" then "push new scene" then tap the tab i'm currently in ("Tab #2" for example) i expect my current scene to pop so that i'm back at the default scene for that tab.

Because the action type `jump` with key `tab2` is dispatched, i expect to be taken to the default scene for that tab (tab2_1)

This is the group I am talking about:

`<Scene key="tab2" initial={true} title="Tab #2" icon={TabIcon}>
    <Scene key="tab2_1" component={TabView} title="Tab #2_1" renderRightButton={()=><Right/>} />
    <Scene key="tab2_2" component={TabView} title="Tab #2_2" onLeft={()=>alert("Left button!")} leftTitle="Left" duration={1} panHandlers={null}/>
</Scene>`
### Actual behaviour

3 actions are dispatched: 
- Jump (key: tab2)
- Push (scene.key: 0_modal)
- Push (scene.key: 1_tabbar)

Despite these actions, no actual navigation is performed and the user remains on the same child scene of a tab that they were on. 
### Steps to reproduce
1. Open the RNRF `Example` app
2. Tap "Go to TabBar page"
3. Tap "push new scene"
4. Tap "Tab # 2" in the tab bar

I expect that # 4 takes us back to scene `tab2_1` instead of staying on the current scene.

**Comment by cridenour** [comment]
I think this is a good idea, would love to see a PR with it if you're up to it!

**Comment by Olliepop** [comment]
@cridenour Cool - i thought this was a bug with intended functionality because of the actions dispatched when you click a tab. But if it's an enhancement i'd definitely be happy to work on it.

**Comment by cridenour** [comment]
I believe those actions are only dispatched because we send them regardless of whether the tab is selected.

**Comment by joenoon** [comment]
Agree this would be nice - just checked the Facebook and Twitter apps and they behave as described above

**Comment by Olliepop** [comment]
Question related to solving this issue:

I had this solved in 3.22.23 by chaining `Actions.pop()` to the number of children in the tab scene navigationState. 

In the latest implementation of TabBar within the `onSelect` method we're unable to execute multiple Actions i.e:
```
Actions.scene_1();
Actions.scene_2();
Actions.scene_3();
```

In the above example only the last action, `Actions.scene_3()` will be performed. Does anybody know we can perform all 3 within onSelect in TabBar? 

Link for convenience: https://github.com/aksonov/react-native-router-flux/blob/master/src/TabBar.js#L22

**Comment by Olliepop** [comment]
This is worth a seperate issue, as this issue (#717) is related to TabBar behaviour.

**Comment by Elyx0** [comment]
This can be handled with a custom rnrf reducer. I implemented something along these lines back in v.22

```javascript
import { Reducer } from 'react-native-router-flux';

const inTabMenu = (state) => {
  if (state && state.children && state.children.length > 0) {
    return state.children[0].name = "tabbar";
  }
  return false;
};

const getActiveTabName = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    if (parent && parent.children.length) {
       //console.log('activeTabName',parent.name,'[[<<<   >>>]]');
       return parent.name;
    }
  }
  return undefined;
};

const getTabTreeIndex = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    return parent.index;
  }
  return undefined;
};

const getTabRootName = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    return parent.children[0].name;
  }
  return undefined;
};

export const reducerCreate = params=> {
  const defaultReducer = Reducer(params);
  return (state, action)=> {
    // this part makes sure that when a menuIcon is pressed AND you are already in that menu tree,
    // it goes back to the root of that tree
    if (action.type === 'jump' && inTabMenu(state)) {
      console.log('JUMP IN TAB MENU')
      let activeTabName = getActiveTabName(state);
      // We only want to reset if the icon is tapped when we're already in the view
      //debugger;
      if (activeTabName === action.key) {
        // if we're already at root, do not do anything.
        if (getTabTreeIndex(state) === 0) {
          console.log('Already in root');
          return state;
        }
        // snap to root.
        //debugger;
        let rootName = getTabRootName(state);
        if (rootName) {
          console.log("ACTION ROOT", {key:rootName, type:'reset'});
          return defaultReducer(state, {key:rootName, type:'reset'});
        }
      }
    }
    console.log("ACTION", action);
    return defaultReducer(state, action);
  }
};
```

**Comment by nbolender** [comment]
If anyone is stumbling upon @Elyx0's reducer above, here is a version that works with the latest. Namely the changes are using ``ActionConst.JUMP`` instead of ``"jump"``, and using ``sceneKey`` instead of ``name`` when getting the tab root key.

```javascript
import { Reducer, ActionConst } from 'react-native-router-flux';

const inTabMenu = (state) => {
  if (state && state.children && state.children.length > 0) {
    return state.children[0].name = "tabbar";
  }
  return false;
};

const getActiveTabName = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    if (parent && parent.children.length) {
       //console.log('activeTabName',parent.name,'[[<<<   >>>]]');
       return parent.name;
    }
  }
  return undefined;
};

const getTabTreeIndex = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    return parent.index;
  }
  return undefined;
};

const getTabRootName = (state) => {
  if (state && state.children && state.children.length > 0) {
    let cbase, parent = null, base = state;
    while(cbase = base.children) { parent = base; base = cbase[base.index];  }
    return parent.children[0].sceneKey;
  }
  return undefined;
};

export const reducerCreate = params=> {
  const defaultReducer = Reducer(params);
  return (state, action)=> {
    // this part makes sure that when a menuIcon is pressed AND you are already in that menu tree,
    // it goes back to the root of that tree
    if (action.type === ActionConst.JUMP && inTabMenu(state)) {
      console.log('JUMP IN TAB MENU')
      let activeTabName = getActiveTabName(state);
      // We only want to reset if the icon is tapped when we're already in the view
      //debugger;
      if (activeTabName === action.key) {
        // if we're already at root, do not do anything.
        if (getTabTreeIndex(state) === 0) {
          console.log('Already in root');
          return state;
        }
        // snap to root.
        //debugger;
        let rootName = getTabRootName(state);
        if (rootName) {
          console.log("ACTION ROOT", {key:rootName, type:'reset'});
          return defaultReducer(state, {key:rootName, type:'reset'});
        }
      }
    }
    console.log("ACTION", action);
    return defaultReducer(state, action);
  }
};
```

**Comment by itelo** [comment]
@nbolender, can you post a full example or a link?

**Comment by nbolender** [comment]
@itelo You can take that entire example and put it in its own file, then import it to your root component (where your Router component lives). Just set it up like so:

```javascript
import React, { Component } from 'react';
import { Router, Scene } from 'react-native-router-flux';

import myReducerCreate from 'my-reducer-example';

class MyApp extends Component {
    render() {
        return (
            <Router createReducer={myReducerCreate}>
                <Scene />
                ...
            </Router>
        );
    }
}
```

**Comment by itelo** [comment]
Hey @nbolender, i'm getting `no reducer provided for key routes`, seems to be a problem in my redux config

**Comment by nbolender** [comment]
@itelo You probably need to combine it with any reducers used by Redux. Try checking the Redux docs and your code for combineReducers().

**Comment by AnsalAli-mudano** [comment]
Is there any other solution than implementing custom reducer for routing? I think this is a general scenario and every one who uses tabview needs this behaviour. If someone has any idea about this, please discuss it here.

**Comment by arnsa** [comment]
@nbolender for some reason inTabMenu returns me false :( I suppose it's not working anymore?

**Comment by nbolender** [comment]
@arnsa I am working off of this version of this library. Maybe something has changed recently that affects this: https://github.com/aksonov/react-native-router-flux/commit/2b09f47740bb0f5829e8419d9ba6622aef20c42c

In any case, I expect to be switching to a different library for navigation the next time I upgrade my app.

**Comment by adriandiaz** [comment]
Has anyone figured a work around for this or has it been resolved? It seems like this issue still persists in v4

**Comment by MartinCamen** [comment]
It's working for me in an older version (`3.38.0`) but not in a newer project with a newer version (`^4.0.0-beta.22`)... Does anyone have any solution for this for v4?

**Comment by lateau** [comment]
Here's my solution on >=4.0.0-beta.

I suppose that we have three children on a tab and want to see default scene always when it's tapped.

* Profile Menu
  * Profile summary(default scene)
  * Change your name
  * Change password

```jsx
<Scene
  key="profile_tab"
  tabBarOnPress={(scene, jumpToIndex) => {
    const { route, focused } = scene;
    if (focused) return; // Skip transition when if a tab is already focused to prevent unwanted hard refresh.
    const { key } = route; // This is a key of a scene has been tapped.
    if (key === 'profile_summary' && route.routes.length > 1) { // You've leave a child scene before, excepts default.
      Actions.replace('profile_summary'); // This might be what you want to do. It will show you default scene with fresh state.
      return;
    }

   // Otherwise, jump to a scene with previous index
   jumpToIndex(scene.index);
  }}
>
  <Scene key="profile_summary" ... />
  <Scene key="change_name" ... />
  <Scene key="change_password" ... />
</Scene>
<Scene
  key="another_tab"
>
  ...
</Scene>
```

Notice that `route.routes` will always include default scene whether it is previously stacked or not. While `Actions.replace(...)` gives you fresh default scene(re-mounted), you might try  `jumpToIndex(route.routes[0].index)` to display default screen you've seen little bit before.

**Comment by aaron25mt** [comment]
@lateau Solution looks good, I want to try it out but my tabBarOnPress function isn't getting called. Any suggestions?

**Comment by lateau** [comment]
Hello @aaron25mt 

That's weird. Did you try a Example project on this repository?
I don't try it but it might work. Add `tabBarOnPress` property into this Tabs:  https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L140

**Comment by aaron25mt** [comment]
@lateau Yes, I tried with an existing problem. Found my issue was that you cannot specify both tabBarOnPress and backToInitial as props to Tabs, but I found a fix. Thanks though!
