### ISSUE TITLE
How to intercept loading scene to check authentication first ? 

### ISSUE THREAD

**Issue by tinygipxy** [aksonov/react-native-router-flux#719]
### Version
- react-native-router-flux v3.26.1
- react-native v0.26.1

### Expected behaviour
I want to check authen before loading the scene, I tried to use componentWillMount, but it's only called one time:
```

export default class Inbox extends Component {
	componentWillMount() {
		this.checkAuth();
	}
	checkAuth() {
		if( this.props.global.loggedIn) {
			console.log( 'loggedIn ' );
			return
		}
		console.log('Need login...');
		Actions.LoginRegister();
	}

```

**Comment by rturk** [comment]
@tinygipxy I guess that your question is beyond the scope of this framework. Looks like you want to increase the control of your app state based on certain conditions, in your example authentication.

You can achieve this using redux. For example only a certain redux state will render a particular view. Check the example folder.
 
Also this can help you
https://github.com/aksonov/react-native-router-flux/issues/555
https://github.com/fbsamples/f8app/blob/master/js/F8App.js#L80
https://github.com/fbsamples/f8app/blob/master/js/setup.js#L61

**Comment by cridenour** [comment]
Yea unfortunately we don't have the web's react-router control of "preTransition" in this library. Highly suggest you move that stuff into a Flux implementation though anyways.

**Comment by tinygipxy** [comment]
Thank you all, I'll try to use state to control it

**Comment by rturk** [comment]
@tinygipxy can you please close this?

**Comment by aksonov** [comment]
@rturk i've added you as collaborator, so you could close issues now. Thanks for your help!
