### ISSUE TITLE
tabs scene not rendering anymore => hideTabBar not working

### ISSUE THREAD

**Issue by ivpusic** [aksonov/react-native-router-flux#722]
### Version
- react-native-router-flux v3.26.1
- react-native v0.26.1

I did upgrade to latest versions of RN and RNRF, and I have hard time doing all fixes. There should be some migration or something, which explains what should we do to support 0.26 RN when used with latest RNRF. Previously I used RN0.25 and previous version of RNRF and everything was working like a charm.

So,  back to my problem.

```
<Scene key="authenticated" initial={this.state.authenticated} hideTabBar={true} tabs={true}>
            <Scene key="feed" hideNavBar={true} initial={true} component={Feed}/>
            <Scene key="profile" hideNavBar={true} component={Profile}/>
            <Scene key="search" hideNavBar={true} component={Search}/>
            <Scene key="notifications" hideNavBar={true} component={Notifications}/>
            <Scene key="explore" hideNavBar={true} component={Explore}/>
</Scene>
```

with this I get warning
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `TabNavigator`.`

I have custom tabBar component, which I render on my own. I don't want to use built in component. To support that, I added `hideTabBar={false}`, which was working in previous version. Now, it doesn't work anymore. If I add `icon={something}` to my `Scene`s, then app renders again.

My questions is, what happened with `hideTabBar`? how can I turn it off? are there any other changes since last version I should know about?

Thanks

**Comment by cridenour** [comment]
Version 3.22 is not compatible with 0.26. However, 3.26.1 is! Feel free to re-open if this is still happening after you upgrade.

**Comment by ivpusic** [comment]
sorry, version is `3.26.1`, it is my mistake

**Comment by joenoon** [comment]
@ivpusic to use your own tab bar component you would need to add `component={MyTabBar}` to the `tabs={true}` scene.  If you intend to use your own tab bar component and see an error about TabNavigator, the rnrf implementation is being used.

**Comment by joenoon** [comment]
Also to add more background, there were lots of changes, especially to the tab component, to get everything working with NavigationExperimental in RN upstream.  react-native-tabs was previously used but I switched the project to react-native-tab-navigator.  react-native-tabs' focus is on the actual tab bar.  react-native-tab-navigator handles the tab bar and the tab's child content, making sure that the tab children don't load all at once.  That became a big selling point and noticeable improvement when I was working on getting everything compatible with 0.26.  The result is some changes might be required during the upgrade, and there are possibly some things that could be better out of the box, but the Example app provides a pretty good outline and should help quite a bit.

**Comment by ivpusic** [comment]
@joenoon tnx for help. Is there any example of `component={MyTabBar}`? if not, are there any specific requirements which component should have in order to work correctly?

**Comment by cridenour** [comment]
You should use src/TabBar.js in this project as a starting point for `MyTabBar`. Just change as necessary!

**Comment by ivpusic** [comment]
is there a way to disable requirement for tabbar completely? if I pass option hideTabBar={true}, then I expect that I don't need to think about it at all, and this was working in previous version.

**Comment by cridenour** [comment]
Don't use `tabs={true}`? 

I am using a custom tab bar based on src/TabBar.js that I hide using a flux state. I had to update my component with 0.26, but other than that, it works fine.

**Comment by ivpusic** [comment]
without tabs=true you get push actions when doing navigation, instead of jump which is desired in my case...the workaround would be to use replace instead of push

**Comment by joenoon** [comment]
If you are using `tabs={true}` you need something to render the child scenes: feed, profile, etc.  If you don't use the default TabBar, you need a component that will take its place and render those children for you - keep only the active screen visible, the rest hidden, etc.

I'm still not sure though that you need to do anything other than `hideTabBar={true}` like you intended.  The error you mentioned: `Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of TabNavigator.` seems to be saying one of the tabs has a null child.  You might need to do some debugging and try to figure out where things are going wrong.  One thought would be:

```
<Scene key="feed" hideNavBar={true} initial={true} component={(props) => {
  console.log('feed', props, 'Feed', Feed);
  return <Feed {...props} />;
}}/>
```

etc...

So its possible if you just track down that, then everything else will be fine.

**Comment by cridenour** [comment]
Yes, if needed, you can just use `type="jump"` on all the sub-scenes. Definitely take a look at Joe's comments above though!

**Comment by joenoon** [comment]
Also check your imports vs requires, exports etc...  see this: https://github.com/reactjs/react-router/issues/2220#issuecomment-220573173

**Comment by joenoon** [comment]
And maybe this https://codereviewvideos.com/blog/warning-react-createelement/

**Comment by ivpusic** [comment]
@joenoon that wont work until you provide Icon=something. the reason is because hidetabbar is ignored, so default tab bar will still try to render and fail, becuase not all parameters are specified...I saw that this was changed recently, and now hidetabbar option only affects style, not rendering of default component

**Comment by joenoon** [comment]
@ivpusic ok so the problem is you are not passing an icon to the tab bar?  Can you simply pass something for now to see if it gets you working? `icon={() => <View/>}` or something.  If thats the only problem then we might need a better error message.

**Comment by joenoon** [comment]
about hideTabBar... it is not ignored.  it is used by the default tab bar component to set its styling to hidden, and it can be used by getSceneStyle to account for its state.  I think what you might be referring to is previously the whole tab bar component would be skipped entirely if hideTabBar was true.  That does not happen any more since the scenes are children of the tab bar component now.  Previously they were siblings.  Now if we didn't render the tab component, then none of its tabbed scenes would get rendered either.

**Comment by ivpusic** [comment]
thanks for explanation...but, when I set hideTabBar to false and render my component on top of it, then if I click somewhere on the bottom of screen, I get redirected to some other page...on android this is even more visible...my workaround for now is to put width and height to 0, using custom scene style property.

As you can see this is pretty big discussion and thing are unclear. I had no idea what new version bring and how to use it until I start reading code -> which most people does not want to do, because they want to save time by using library, not spend it. 

My suggestion is to make docs update about things you told me here, so other people can know it as well. also better error message if Icon is missing would be good.

**Comment by joenoon** [comment]
@ivpusic agreed and the points you bring up are very valid.   NavigationExperimental is still a moving target - things change rapidly there and as a result here - for example tabs became non-functional due to a change in NavigationExperimental's NavigationView a few versions back.  The hidden tab bar catching clicks is one I haven't heard about until just now.  PRs either addressing docs, adding examples of broken use-cases, or fixing these issues would be very appreciated.  I'll try to make time to do another round of updates later this week as well.

**Comment by aksonov** [comment]
@joenoon Just got these exceptions too - i'm not using built-in TabBar either... I think it is VERY critical issue, too pity that i didn't mention it during 3.26.0-rc testing...
I still believe we must separate tabbar to different component completely to avoid coupling....

**Comment by joenoon** [comment]
@aksonov maybe a combination of the react-native-tabs with some of the smart logic around how the children are rendered like react-native-tab-navigator does?  I'm all for it if it pleases more people.  In hindsight the release for .26 probably should have been a major version bump + contain release notes saying something like check your usage against the Example app.  There is just too much changing here and upstream to be one of those libraries anyone can use without having to dig into the source.  Maybe one day when NavigationExperimental stabilizes...

To confirm, which is the critical issue(s) out of this?  Are you experiencing the bug where the hidden tab bar is catching clicks?  Or the null issue? Or both?

**Comment by aksonov** [comment]
We could publish docs about breaking changes for 3.27 to use separate TabBar (tabs or tab-navigator,etc.).

>To confirm, which is the critical issue(s) out of this? Are you experiencing the bug where the hidden tab >bar is catching clicks? Or the null issue? Or both?
Both. As I understand i have to pass icons for hidden tabbar to resolve it and it is quite weird :)

**Comment by aksonov** [comment]
Feel free to reopen if you still have issue with latest version.
