### ISSUE TITLE
How to auto-transition Scenes based on state

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [aksonov/react-native-router-flux#724]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.1
- react-native v0.26.0

## Requirement

This is more a "how to" question rather than an issue.
My requirement is that Scene transition should be based on the availability of a state. For e.g, On startup, I would like to transition a user to a `Search` scene when a state `location` is not available or transition to a `List` scene when it is available. And I obviously will like for the Title to be different for each Scene, So an if condition in a common Scene may not be an option.

**Comment by cridenour** [comment]
Where is the transition started from? A button press? App load? 

Either way, it will come down to custom code in your component and using `Actions.search()` or `Actions.list()` as necessary.

**Comment by sathyakumarseshachalam** [comment]
Want to do it in AppLoad. So question : I can only call `Actions.*` when I have registered my scenes with Provider in my render method. That being the case, whats the recommended pattern/place to call `Actions.search` or `Actions.list` like calls on AppLoad.

**Comment by cridenour** [comment]
Check out everything under `Alternatively` here: https://github.com/aksonov/react-native-router-flux#usage

After that, I would try using `Actions.search` in componentWillMount of your app.

**Comment by jhen0409** [comment]
I also have similar question but different purposes, if it doesn't auto-transition depends on the state, it will be unable to use `remote-redux-devtools` instrument functions. (e.g. skip action)

Finally I directly used NavigationExperimental, [the RootContainer must get the same state](https://github.com/jhen0409/react-native-boilerplate/blob/master/src/containers/App.js#L46), the `skip action` is works very well.

**Comment by sathyakumarseshachalam** [comment]
@cridenour : I tried and your solution worked. Thanks

**Comment by BerndWessels** [comment]
@jhen0409 did you get `remote-redux-devtools` time travel to work with `react-native-router-flux` ?

**Comment by jhen0409** [comment]
@BerndWessels Unfortunately, `react-native-router-flux` doesn't provide a way to set `navigationState` for `Router`, it has its own state, so it doesn't to do time travel.

I don't know if it have any change, I haven't tried it for a long time.

Currently I'm considering to use [`react-navigation`](https://github.com/react-community/react-navigation) instead of `NavigationExperimental`.
