### ISSUE TITLE
 expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `TabNavigator`.

### ISSUE THREAD

**Issue by yuyixg** [aksonov/react-native-router-flux#725]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.1
- react-native v0.26.0

ExceptionsManager.js:61 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `TabNavigator`.

   <Scene key="main" tabs={true} >   

tabs ={true}  is not work

**Comment by cridenour** [comment]
Can you reproduce in the Example app? Or paste your <Router> config.

**Comment by yuyixg** [comment]
@cridenour  thank you ,demo is not issue ,my project is upgrade

**Comment by ssomnoremac** [comment]
Just a note on this error, I got it when I didn't define and include an Icon for tabs. Might be worth investigating a clearer error message.
to reproduce:
```
  <Scene key="books" tabs={true}>  
    <Scene key='catalog' component={Catalog} title="Catalog" />
        ...
```
to fix:
```
<Scene key='catalog' component={Catalog} title="Catalog" icon={TabIcon}/>
```

**Comment by Elyx0** [comment]
Opened https://github.com/aksonov/react-native-router-flux/issues/736 as it was previously working

**Comment by Hu4F00d** [comment]
Can confirm what @ssomnoremac said. The error seems to happen when you don't include an Icon for the tabs.

**Comment by jnbt** [comment]
I've also encountered the same problem
