### ISSUE TITLE
[HELP] Drawer integration issue.

### ISSUE THREAD

**Issue by yorzi** [aksonov/react-native-router-flux#726]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.22.23
- react-native v0.24.1

### Expected behaviour

I hope to trigger Drawer's open and close in my custom NavBar component, I have some config like this:

```
        <Scene key="drawer" component={Drawer} type='reset' >
          <Scene key="main" navBar={HeaderBar} drawerImage={require('./assets/menu.png')}>
            <Scene key="mine" component={Mine} title="my setting" iconName="settings" sceneStyle={styles.movieDetails} icon={TabIcon} navLeftButton='back' />
          </Scene>
        </Scene>
```

### Actual behaviour

I have no idea how I can open or close Drawer in `HeaderBar` component, is there a way to get Drawer in other scene component? (Sorry if I ask something stupid.)

Or, does anyone have an detailed document or sample for Drawer integration? I've spent a day to struggle with different configs.

Thanks.

**Comment by jeroenbourgois** [comment]
There is an example with the Drawer, it can be found here:

https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration

In your header bar the Drawer should be available through the context afik, have you tried debugging the context?

**Comment by yorzi** [comment]
@jeroenbourgois thanks for your quick reply, I did follow your like. Hmm, I thought Drawer is available in context, but `this.context` in HeaderBar is blank.

**Comment by yorzi** [comment]
@jeroenbourgois according to your update, Yeah, `SideMenuContent` in you case is child component of Drawer, so you can get `const { drawer } = this.context`. but in my case, `HeaderBar` is a custom NavBar for Scene where I want to have a complex and flexible top nav bar. I might need to trigger the menu icon in HeaderBar to open or close Drawer.

**Comment by cridenour** [comment]
Just a heads up you are using an unsupported pair of RNRF + RN. The only known working configurations are RN 0.22 + RNRF 3.22.x and RN 0.26 and RNRF 3.26.x.

**Comment by yorzi** [comment]
@cridenour Oh, thank you, I know the version relation now. Let me try to adjust versions first.

**Comment by luisfuertes** [comment]
"react-native": "^0.28.0" + "react-native-router-flux": "^3.30.2" arent working yet?

**Comment by andrispraulitis** [comment]
Works for me

**Comment by luisfuertes** [comment]
Can you post a example of your code?

**Comment by andrispraulitis** [comment]
https://github.com/andrispraulitis/tournament

**Comment by luisfuertes** [comment]
Thanks for your example!
Im trying it but dont work. What im doing wrong?

My index: 
```
			<Provider store={store}>
				<Router key="root"
				 sceneStyle={{backgroundColor:'white'}}
				 navigationBarStyle={Styles.navBar}
				 titleStyle={Styles.navTitle}
				 backButtonTextStyle={Styles.navTitleButtonStyle}
				 backButtonImage={this.backImage}
				 rightButtonTextStyle={Styles.navTitleButtonStyle}
				 leftButtonTextStyle={Styles.navTitleButtonStyle}
				>
					<Scene key="root" >


						<Scene key="Splash" initial={true} component={Splash} hideNavBar={true} type='replace' />
						<Scene key="Login" component={Login} hideNavBar={true} type='replace'  />

						<Scene key='SideDrawer' component={SideDrawer} type='replace'>

									<Scene key='Screen1' component={Screen1} />
									<Scene key='Screen2' component={Screen2} />

						</Scene>
					</Scene>
				</Router>
			</Provider>
```

My SideDrawer: 
```
import {PropTypes, StyleSheet, } from 'react-native'
import React, {Component} from 'react'

// Router Flux
import {Actions, DefaultRenderer} from 'react-native-router-flux';

// Redux
import { connect } from 'react-redux';

// Drawer
import Drawer from 'react-native-drawer'
import SideDrawerContent from './SideDrawerContent'

export default class SideDrawer extends Component {
	render() {
		console.log()
		const navigation = this.props.navigationState;
		if (!navigation.children) {
			return null;
		}

		return (
			<Drawer
				ref="navigation"
			  type="overlay"
			  content={<SideDrawerContent />}
			  tapToClose={true}
			  openDrawerOffset={0.2} // 20% gap on the right side of drawer
			  panCloseMask={0.2}
			  closedDrawerOffset={-3}
			  styles={drawerStyles}
			  tweenHandler={(ratio) => ({
			    main: { opacity:(2-ratio)/2 }
			  })}
			  >
			    <DefaultRenderer navigationState={navigation.children[0]} onNavigate={this.props.onNavigate} />
			</Drawer>
    )
	}
}

const drawerStyles = StyleSheet.create({
	drawer: { shadowColor: '#000000', shadowOpacity: 0.8, shadowRadius: 3},
	main: {paddingLeft: 3},
})
```

When i do "Actions.SideDrawer":
`In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.`

My "navigation.children[0]" object:
![captura de pantalla 2016-06-28 a las 15 22 45](https://cloud.githubusercontent.com/assets/18212615/16416793/3286dff8-3d44-11e6-94b9-83da31459937.png)

**Comment by andrispraulitis** [comment]
Looks like you need to wrap your drawer scenes with a scene.

**Comment by luisfuertes** [comment]
Now: 
```
			<Provider store={store}>
				<Router key="root"
				 sceneStyle={{backgroundColor:'white'}}
				 navigationBarStyle={Styles.navBar}
				 titleStyle={Styles.navTitle}
				 backButtonTextStyle={Styles.navTitleButtonStyle}
				 backButtonImage={this.backImage}
				 rightButtonTextStyle={Styles.navTitleButtonStyle}
				 leftButtonTextStyle={Styles.navTitleButtonStyle}
				>
					<Scene key="root" >


						<Scene key="Splash" initial={true} component={Splash} hideNavBar={true} type='replace' />
						<Scene key="Login" component={Login} hideNavBar={true} type='replace'  />

						<Scene key='SideDrawer' component={SideDrawer} type='replace'>
								<Scene key="main" tabs={true} hideTabBar={true}>
									<Scene key='Screen1' component={Screen1} />
									<Scene key='Screen2' component={Screen2} />
								</Scene>
						</Scene>
					</Scene>
				</Router>
			</Provider>
```

But same error
