### ISSUE TITLE
`Router` is undefined on RN 0.26.1

### ISSUE THREAD

**Issue by jaimeagudo** [aksonov/react-native-router-flux#727]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.1
- react-native v0.26.1

### Expected behaviour

`Router` is not undefined

### Actual behaviour

`Router` is undefined

![image](https://cloud.githubusercontent.com/assets/4053914/15499732/fe8593e8-21a5-11e6-8081-0b2121cd6eb8.png)

### Steps to reproduce

1. `git clone https://github.com/jaimeagudo/snowflake`
2. `cd snowflake`  
3. `npm install`
4. `react-native run-ios`

The cause seems to be this change on RN, `RootContainer: NavigationRootContainer` is deprecated
 https://github.com/facebook/react-native/commit/14eb427a8061e0c904ace022535070150c6872d4

**Comment by rturk** [comment]
Kill NavigationExperimental Containers is only applicable to RN0.27-rc, are you sure you're using RNv0.26.1?

**Comment by sharq1** [comment]
@jaimeagudo try following changes to snowflake.js:
![image](https://cloud.githubusercontent.com/assets/1241239/15528786/9a5a9b78-2247-11e6-950c-71d8400cc627.png)

**Comment by OFranke** [comment]
Changing this did not work for me. I still have the same error as described above.

**Comment by wzywno** [comment]
Hi,
@sharq1 I made changes as you wrote in previous comment.
Now I have other error, Did you have it also?
![img_2926](https://cloud.githubusercontent.com/assets/1249754/15536327/2f107318-2271-11e6-84f7-3deb14530baf.jpg)

**Comment by wzywno** [comment]
This is related with react-native-drawer 
```
const children = this.props.navigationState.children;
...

<DefaultRenderer navigationState={children[0]} />
```

**Comment by jaimeagudo** [comment]
thanks @sharq1 , that pass the error but afaik won't bind the Router component to the store which I think it's wrong https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options 

![image](https://cloud.githubusercontent.com/assets/4053914/15536043/11452e88-2270-11e6-8ef9-a5653ecc3ee2.png)

Honestly I am just starting with RN and I have serious doubts if all this troubleshooting and breaking changes worth, I am considering swift which curiously has some tools inspired by React architecture

https://reswift.github.io/ReSwift/master/
https://github.com/alexdrone/Render

**Comment by jeroenbourgois** [comment]
@jaimeagudo is the `ItemCheckbox` a component of yours? If so, are you exporting it correctly?

**Comment by wzywno** [comment]
@jaimeagudo  I had the same error message. I changed my components declarations.
I added  ```default ```, so
```
export class MyButton extends Component {
```
I changed to 
```
export default class MyButton extends Component {
```

**Comment by sharq1** [comment]
@jaimeagudo you are right, it should be connected to the store, which should be done this way `const RouterWithRedux = connect()(Router)`, so the difference is that we import `Router` and use it instead of `RNRF.Router` - it works for me.

**Comment by aksonov** [comment]
It is definitely not issue of this component.
