### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by ramigb** [aksonov/react-native-router-flux#728]
- react-native-router-flux v3.26.1
- react-native v0.27.0-rc

### Expected behaviour
The example provided on the github page should work fine, I've made sure the scenes have valid components etc. 

### Actual behaviour
Element type is invalid: expected a string (for built-in components) or class/function (for composite components) but got: undefined, check the render method of 'Router'.

**Comment by cridenour** [comment]
Possibly related to https://github.com/facebook/react-native/commit/14eb427a8061e0c904ace022535070150c6872d4?

**Comment by cridenour** [comment]
@ramigb In the mean time, I would stick with 0.26.

**Comment by ramigb** [comment]
@cridenour thank you, that's what I will do for now.

**Comment by aksonov** [comment]
Please, please don't use unsupported versions.

**Comment by stereodenis** [comment]
react-native@0.37.0
react-native-router-flux@3.26.0 

@ramigb @cridenour what should I do to fix it?

**Comment by cridenour** [comment]
React Native and this library have had many, many updates since the
versions you're using. I'd update to the latest.
