### ISSUE TITLE
How can Example component TabView listen for onRight and onLeft button ?

### ISSUE THREAD

**Issue by esutton** [aksonov/react-native-router-flux#731]
For example, I would like to display "Done" for the rightTitle and commit to database when user presses right button. Currently the Example's "Tab #1" displays an alert with text "Right Button".

Can anyone advise on how to modify the Example TabView component to intercept the onRight event?

Scene declaration in Example.js:
```
                    <Scene key="tabbar" component={NavigationDrawer}>
                        <Scene key="main" tabs={true} >
                            <Scene key="tab1"  title="Tab #1" icon={TabIcon} navigationBarStyle={{backgroundColor:"red"}} titleStyle={{color:"white"}}>
                                <Scene key="tab1_1" component={TabView} title="Tab #1_1" onRight={()=>alert("Right button")} rightTitle="Right" />
                                <Scene key="tab1_2" component={TabView} title="Tab #1_2" titleStyle={{color:"black"}}/>
                            </Scene>
```

- react-native v0.26.0

React and js newbie.

-Ed

**Comment by rturk** [comment]
Hi @esutton If I've understood correctly you've kind of already answered your own question. You need to connect `onRight` to a function or callback that will handle your `save` to database logic. You probably need another framework like Redux to handle your overall App State.

**Comment by samdturner** [comment]
+ 1

@esutton you have the same use case as me.  I am discussing it in issue #747

**Comment by esutton** [comment]
@rturk Maybe my problem is I am not experienced in javascript.  ( However, I am using redux. )

How can I connect the Scene onRight function, to the Scene component?  

When user presses the right "Done" button I want to commit the edited object to the database.

**Comment by aksonov** [comment]
@esutton You definitely need to re-think this and follow flux/redux principles. MySceneComponent should not have any logic except publishing redux/flux events, so onRight could do the same

**Comment by yberstad** [comment]
@aksonov, I'm sorry, but I do not know the custom when having questions on a closed issues, should I create a new and reference the old, or could I try to use the same issue? I'll try using this issue/thread, please correct me if I'm doing it wrong.

So my main question is, how can I publishing a redux event with payload, when the basis for this payload is in a "SceneComponent"? 
An example would be a form, and when the user has filled in all input fields and pressed "Done" triggering the "onRight()", I would like to publish an redux event with the form data. Do I need to create my own NavBar as suggested in #747 ? Is there a better way, or have I misunderstood something?
