### ISSUE TITLE
After upgrade version to 3.22, renderRightButton is not correctly displayed.

### ISSUE THREAD

**Issue by RooneyLeeSJ** [aksonov/react-native-router-flux#738]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.22.0
- react-native v0.23.1

### Expected behaviour
What I want to is to show two image icons left and right both side.
When I used 2.x version, renderRightButton was completely perfect, but after update version to 3.22,  right image is not displayed well.
what should i do? this is my code.. and view,,, 

![2016-05-26 6 45 55](https://cloud.githubusercontent.com/assets/15812687/15570653/1f1bf5ac-2372-11e6-9491-e971479ab384.png)

![2016-05-26 6 41 37](https://cloud.githubusercontent.com/assets/15812687/15570548/94fc3940-2371-11e6-8c8a-0abbb4f868c4.png)
![2016-05-26 6 41 50](https://cloud.githubusercontent.com/assets/15812687/15570552/9b9325b6-2371-11e6-8328-24be328f387d.png)

and this is my previous view before upgrade version.
<img width="345" alt="2016-05-26 6 44 25" src="https://cloud.githubusercontent.com/assets/15812687/15570611/f2ea32f0-2371-11e6-87d6-fe1b55c711aa.png">

### Steps to reproduce

1.
2.
3.

**Comment by cridenour** [comment]
You need to use RN 0.22 with 3.22.x or RN 0.26 with 3.26.x. If the problem persists after you upgrade, let me know and I'll re-open.
