### ISSUE TITLE
Storing current Scene

### ISSUE THREAD

**Issue by demiro** [aksonov/react-native-router-flux#745]
So imagine this scenario

 - scene 1
 - scene 2
 - scene 3
  - scene 3a 
  - scene 3b
  - scene 3c
 - scene 4

Scene 3 will be USER DETAILS page and you can come to this page from different pages

What I want to do is that when I am on Scene 3 the Navigation Bar Close button leads ALWAYS to the previous SCENE...

Hardware back button though it depends... if no tabs were tapped (sub scene), than goes to the previous scene... if not, than it goes to the previous SUB scene.

Clicking on a TAB triggers Actions[selected tab] <- which are linked to sub scenes

Android backbutton uses normal Actions.pop()

How to set the Close button to go to the correct Scene?

What I tried was 

```
    componentDidMount(){
    	this.setState({cameFrom: Actions.pop});
    }
```

and then

```
	close(){
		this.state.cameFrom();
	}
```

which obviously doesn't work since it is just triggering the same Actions.pop() function instead of transitioning to the appropriate screen

**Comment by vonovak** [comment]
Just looking at it, I'd try this: you can transition to your scene 3 like `Actions.Scene(custom props here)`. In custom props, you can pass the original scene that the user came from and then pass that even to the subscenes and then you'll know where the user came from and use that I formation to go back.

**Comment by aksonov** [comment]
It seems good solution, so i'm closing this.
