### ISSUE TITLE
hideNavBar does not work on scene 

### ISSUE THREAD

**Issue by eranbes** [aksonov/react-native-router-flux#746]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.2
- react-native v0.26

### Expected behaviour
hideNavBar={true} should hide the NavBar

### Actual behaviour
NavBar is still shown for the scene

### Steps to reproduce

1.  < Scene key="startup" initial={true} hideNavBar={true} / >

**Comment by rturk** [comment]
@eranbes can you please include more details of your code? The "startup" scene has nested Scenes?

**Comment by eranbes** [comment]
One router and a few siblings (scenes), nothing nested.  here is another one (attaching image too):
![screenshot_2016-05-27-20-12-55](https://cloud.githubusercontent.com/assets/342114/15618742/b0027eda-2447-11e6-92ba-f4d8a985fa97.png)

<Scene key="tandcPage" hideNavBar={true} component={TandcScreen} title={strings.tandc}
                   sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>

**Comment by boulajp** [comment]
I have this issue as well with:

react-native-router-flux v3.26.5
react-native v0.26

**Comment by boulajp** [comment]
Could you include your entire router tree? I was having this issue, and I managed to fix it by moving the hideNavBar up to the root component

**Comment by rturk** [comment]
HI @eranbes pasting just snippets of code don't help. Can you please provide more details of your code? Please feel free to use a GIST.

**Comment by eranbes** [comment]
it seems like it was a styling error after all.

**Comment by bendellarocco** [comment]
@eranbes what was the styling issue?  I am seeing this same issue on android only

**Comment by eranbes** [comment]
We just reserved top margin and forgot to remove it.

**Comment by bendellarocco** [comment]
Darn, nothing that helps my issue.  Thank you for your response
