### ISSUE TITLE
How to style Modal to have a transparent background, like an overlay?

### ISSUE THREAD

**Issue by sibelius** [aksonov/react-native-router-flux#749]
### Version
- react-native-router-flux latest
- react-native 26.0.1

**Comment by mnadbader** [comment]
backgroundColor:'rgba(255,255,255,0.5'

**Comment by aksonov** [comment]
I believe it is out of scope of this component. Example project has modal popup with usage of 3rd party component.

**Comment by y2k-shubham** [comment]
I achieved this by the combination of following:
- in your render method where you are rendering Modal, pass a prop transparent={true}
- add a single View child to your modal (put all other things inside this View) and apply style to it with backgroundColor = 'rgba(r, g, b, a)' as described above

**Comment by Anuskhan** [comment]
backgroundColor:'rgba(255,255,255,0.5')
