### ISSUE TITLE
Possible to go to specific tabbar tab using Actions?

### ISSUE THREAD

**Issue by leovanhaaren** [aksonov/react-native-router-flux#75]
I know the package is lacking some documentation, but I can't figure out how to call a specific tab page with extra data;

```Actions.tab3({ data: 'somedata' });```

results in: 
_reactNativeRouterFlux.Actions.tab3 is not a function.

Am I missing something?

**Comment by aksonov** [comment]
Don't forget that router Actions are created in _run-time_, so you may should wrap such calls into functions to avoid being checking during compile-time. Check Example project.

**Comment by corbt** [comment]
I have this same question: is there a way to navigate directly to a specific route in a sub-router? I can only seem to navigate to routes at the same level as the currently active route.

**Comment by aksonov** [comment]
Please post example here and check it with latest version. Maybe 2.0 version could do it (navigate to other route)
