### ISSUE TITLE
Assistance with custom navbar

### ISSUE THREAD

**Issue by lwhiteley** [aksonov/react-native-router-flux#751]
### Version
- react-native-router-flux v3.26.1
- react-native v0.26.1

### Expected behaviour

I want to render a custom navbar but im afraid i may be doing something wrong

```js
static renderNavigationBar(props){
      return <CommonHeader/>
    }
```

This doesnt render anything, when i remove it the default navbar is rendered

Any advice would be helpful

**Comment by lwhiteley** [comment]
fixed, header styling was the issue

**Comment by pewh** [comment]
Hello @lwhiteley.

I know this is an old issue, but I'm curious how you styling header. I get blank navbar too. Thanks! :beers:

**Comment by jeannei** [comment]
@pewh I'm not sure if you solved this, but as reference for anyone that needs help in the future, here is an example:

``` 
 // Default styles from inspecting default nav bar
  const navigationBar = {
    backgroundColor: <Your color>,
    position: "absolute",
    paddingTop: 0,
    top: 0,
    height: 64,
    right: 0,
    left: 0,
    bottomBorderWidth: 0.5,
    borderBottomColor: <Your color>
  } 

 // custom component
  static renderNavigationBar(props) {
    return (
      <View style={navigationBar}>
        <Text>{props.title}</Text>
      </View>
    );
  } 
```

**Comment by travisday** [comment]
@jeannei I am having trouble implementing this I have a page that loads a list view do I put this code in there?

**Comment by jeannei** [comment]
@travisday is your `scene` rendering that component?

**Comment by travisday** [comment]
@jeannei Yes, I got it sort of working, my custom nav shows up but gets rid of the back button
