### ISSUE TITLE
custom navBar being rendered twice and to the bottom of the scene

### ISSUE THREAD

**Issue by lwhiteley** [aksonov/react-native-router-flux#752]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.?
- react-native v0.26.2

### Expected behaviour

```js
<Scene key="drawer" component={SideDrawer} tabs={false}>
     <Scene component={Home} key='home' title='Home' navBar={CommonHeader} hideNavBar={false}/>
     ...
</Scene>
```

I expected this to be placed first in the scene above the content. However it is being rendered twice
where one has the drawer context and the other doesnt

### Actual behaviour

Once styled absolutely, when the drawer is open it is displayed under the navbar also it is not pushing it
to the side as expected 

Note: 
- the header without the drawer context is displayed above when positioned absolutely, so i cant use my drawer button

### Steps to reproduce

1. create a drawer with `type="static"`
2. add a custom navBar without adding position styling

**Comment by AkiraXue** [comment]
i got  the same  problem  when i  want  to  renderTitle  and  renderLeftButton with  two different  components  which render twice 
navBar={ ()=>{ return this.renderNavBar(); } }

...
<NavLeftButton btnText={btnText} style={style} btnIcon={btnIcon}/>
<NavTitle title={'title'} style={style} />
...

**Comment by reddingit** [comment]
I solve this problem by add some code at render() function in NavBar.js, see below:
![qq20160531-0](https://cloud.githubusercontent.com/assets/5533582/15662730/2e126fd4-2726-11e6-880b-4b9469d21dfd.png)

**Comment by lwhiteley** [comment]
thanks for the update.

but does it solve the header being displayed at the bottom?
seems like it would only solve it being displayed twice; a step forward nonetheless 👍

**Comment by reddingit** [comment]
If you want to use both drawer and tabbar, maybe you should do this:
`
<Scene key="drawer" component={SideDrawer} >
							 	<Scene key="tabbar" component={TabBar} tabs={true}>
								      <Scene component={Home} key='home' title='Home' navBar={CommonHeader} hideNavBar={false}/>
								      ...
							    </Scene>
							</Scene>
`

**Comment by lwhiteley** [comment]
i chose to turn off tabbar actually so maybe should edit post.. but when i do, it still displays to the bottom

**Comment by momo-Flanny** [comment]
if you want to use the component in navBar, you should let the component in position absolute like this:

![image](https://cloud.githubusercontent.com/assets/13936769/15698348/3bb6d94c-27f6-11e6-8bcc-3e3a3bacde64.png)

**Comment by lwhiteley** [comment]
please read the issue again. that is the problem

**Comment by momo-Flanny** [comment]
well, but i think if you want to use the component in navBar, it means you should recover the style by your self

**Comment by lwhiteley** [comment]
the default style of the navbar is what you just showed me, that adds the weird behaviour of not being fluid when the drawer is open. as i said before, thats not what i want

**Comment by Roilan** [comment]
Is there any update on this beside having it `absolute`? 

@lwhiteley Have an example of what you did?

**Comment by lwhiteley** [comment]
was this fixed or a solution provided?

**Comment by lwhiteley** [comment]
@Rollan its as i said before,

in order to get away from the absolute style and had to put the header component at the top of the components I use for the Scenes. which is not preferable i guess

**Comment by lwhiteley** [comment]
and when the drawer is open, how do i get it to move to the side with the rest of the scene?
 that is my intended use case

**Comment by tuckerchapin** [comment]
This is mildly off topic, but since the people in this issue seem to have it squared away, I thought I'd ask:

I have a custom navBar component that loads correctly when I comment out my drawer and the drawer works fine, but the navBar does not load at all when the drawer is in the app (open or closed). I've tried rearranging `hideNavBar` and `navBar` onto different scenes, but no combination thereof seems to allow the drawer to appear and still have the navBar behind it.

```
<Router navBar={AppBar}>
...
    <Scene key="drawer" component={MaterialDrawer} initial={true} tabs={false}>
    <Scene key="loggedIn" component={LoggedIn} title="FitMango" hideNavBar={false} initial={true} type="replace"/>
```

The drawer and navbar all load correctly, so I have a feeling it's something to do with this chunk in my index file.
