### ISSUE TITLE
How could I make custom navBar fixed on the top ?

### ISSUE THREAD

**Issue by kdchang** [aksonov/react-native-router-flux#755]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.5
- react-native v0.25.1

### Expected
I want to use my custom navBar (NavBar) on the top of every scene. 
Here is the sample code:
```
      <Provider store={store}>
        <RouterWithRedux>
          <Scene key="root" navBar={NavBar}>
            <Scene key="main" component={Main} title="Main" initial={true}/>
            <Scene key="list" component={List} title="List"　/>
          </Scene>
        </RouterWithRedux>
      </Provider>
```

### Actual
Actually, the custom navBar is showing on the bottom of the scene. 
How could I make it fixed on the top ? Thanks :)

**Comment by rafaelcorreiapoli** [comment]
Apply this style to the a View wrapping your navbar
  <View style={{position: 'absolute', top: 0, flex: 1, alignSelf: 'stretch', right: 0, left: 0}}>

**Comment by kdchang** [comment]
@rafaelcorreiapoli 
Cool. It works! Thanks a lot :)

**Comment by kdchang** [comment]
@rafaelcorreiapoli 
Excuse me, the navBar is fixed on the top now. But it would overlap the main content every page(due to position absolute), how could I fix this issue ? thanks :)

**Comment by xvalentino** [comment]
@kdchang did you find a clean solution?

**Comment by AlessandroCorradini** [comment]
@xvalentino @kdchang 
I've used the same solution. A container component like this:

```
import React from 'react';
import { ScrollView, StatusBar, View} from 'react-native';



class Container extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            unScrollable: this.props.unScrollable || false
        }
    }

    render() {
        return (
            <View style={{flex: 1, marginTop: 45}}>
                <StatusBar
                    backgroundColor="#2085A8"
                    barStyle="light-content"
                />
                {(!this.state.unScrollable) ? <ScrollView>{this.props.children}</ScrollView> : <View>{this.props.children}</View>}
            </View>
        );
    }
}

export default Container;
```
