### ISSUE TITLE
routing using keys in props 

### ISSUE THREAD

**Issue by sandeepgujela** [aksonov/react-native-router-flux#757]
var menuItems : [  {name:'Dashboard',redirectkey:'DashboardPageKey'},
                              {name:'Orders',redirectkey:'OrdersPageKey'},
                              {name:'Member Orders', redirectkey:'MemberPageKey'},
                              {name:'Catalog',redirectkey:'CatalogPageKey'} ]  

var menuItemsList = this.state.menuItems.map(function(menuItem){
      return(< MenuItem key={menuItem.key} menuItem={menuItem}/ >);
    }) 

Component MenuItem:

export default class MenuItem extends Component{

		render(){
		return(
                    <View onPress={}>  //what should i write here. 
	                           <TouchableOpacity >
 						<Text>100</Text>
						<Text>{this.props.menuItem.name}</Text>
				    </TouchableOpacity>
                    </View> );
	}
}

what should i write on press  in order to redirect it to respective key passed as props .
Example <View onPress={Action.this.props.redirectUrl} or some thing else.

Thanks

**Comment by rafaelcorreiapoli** [comment]
import { Actions } from 'react-native-router-flux'

onPress={Actions.myPageKey}
