### ISSUE TITLE
ExNavigator – Unexpected token?

### ISSUE THREAD

**Issue by andreasbhansen** [aksonov/react-native-router-flux#76]
Hey,

I'm having some problems using this library – or perhaps its ExNavigator dependency.
After installing it and following the Getting Started guide, the simulator shows the Red Screen (of Death) stating that

> SyntaxError /[...]/node_modules/react-native-router-flux/node_modules/@exponent/react-native-navigator/ExNavigator.js: Unexpected token (24:16)

I've tried removing and re-installing react-native-router-flux, but to no success.

Any ideas what might be causing this?

**Comment by andreasbhansen** [comment]
Well, I should of course have checked the ExNavigator repo before asking here. 

Here's the same issue:
https://github.com/exponentjs/ex-navigator/issues/60

**Comment by thomasjonas** [comment]
Did you fix it? I had to update my React and all other packages to the latest version... which was kind of a hell. In the end I just started from scratch again.

**Comment by andreasbhansen** [comment]
Hm, I'm not sure what might have fixed this. So many errors occurred throughout today, ended up updating OS X Yosemite, then upgraded to OS X El Capitan, downloaded a few xGB large Xcode updates, cleaned and reinstalled the entire node_modules folder, removed some .babelrc files that caused problems, and just five minutes ago I was able to get everything up running again. That took an entire day.

**Comment by robtg4** [comment]
why was this closed? the error hasn't been solved

**Comment by aksonov** [comment]
1. I can't reproduce problem
2. You noticed that "Well, I should of course have checked the ExNavigator repo before asking here." - does it mean the case not in this component?

**Comment by derese** [comment]
Can any body please tell us how they solved it ?

**Comment by joshbedo** [comment]
Having same issue and with ExNavigator i can't even use this library.

**Comment by andreasbhansen** [comment]
Sorry, I'm not able to say what actually fixed it. As previously posted, I spent a day updating and reinstalling everything from OS to Node. For some reason, it worked.

**Comment by anupkale1984** [comment]
I was able to resolve it with. Development server restart as mention on this post
https://www.npmjs.com/package/babel-preset-react-native-stage-0
