### ISSUE TITLE
Hidden TabBar still clickable when hideTabBar={true}

### ISSUE THREAD

**Issue by q6112345** [aksonov/react-native-router-flux#763]
### Version

Tell us which versions you are using (react native 0.26 is required for v3): 
- react-native-router-flux v3.26.0
- react-native v0.26.0
### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/6049450/15661952/fcee12fc-271e-11e6-96fa-e34406146397.png)
### Steps to reproduce

In the example, as screencast below:

![hidetabbar](https://cloud.githubusercontent.com/assets/6049450/15661803/ae42a65a-271d-11e6-8ca3-1a514c0a9190.gif)
### Solution:
#758

**Comment by aksonov** [comment]
Please check with latest version.

**Comment by gijoehosaphat** [comment]
I get this with the currently latest commit to master #b58d21c492838fe16315948ed1695d6b4ca915a8

**Comment by aksonov** [comment]
@joenoon could you look at it?
