### ISSUE TITLE
Jump action is no longer called when Switch route changes.

### ISSUE THREAD

**Issue by willmcneilly** [aksonov/react-native-router-flux#766]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.8 and above
- react-native v0.26.0 and above

### Expected behaviour
When switch state changes and a new route is switched to the jump action should be called.

### Actual behaviour
jump action is not called.

This started happening today after the changes made in 3.26.8. I'm wondering if this is a bug or an intentional change.

thanks.

**Comment by aksonov** [comment]
Please check latest 3.26.13

**Comment by aksonov** [comment]
Jump action is not called currently for simplicity, however everything should work (i.e. correct scene should be rendered)

**Comment by willmcneilly** [comment]
Ah ok. We have been using jump in our reducer. I should be able to find a work around. Thanks.
