### ISSUE TITLE
Switching between tabs does not trigger 'focus' action

### ISSUE THREAD

**Issue by antonzy** [aksonov/react-native-router-flux#769]
### Version

Tell us which versions you are using (react native 0.26 is required for v3): 
- react-native-router-flux v3.26.12
- react-native v0.26.3
### Expected behaviour

Given using Redux integration and a <... tabs={true}> scene with <... type='jump'> children scenes, 
I expect that when switching between tabs,
a 'focus' action will be dispatched with the current scene.
### Actual behaviour

'focus' action is not being dispatched, except for when then initial scene of the tab bar is displayed.

**Comment by aksonov** [comment]
@antonzy It could be a bug, could you provide repo based on our Example project to reproduce it?

**Comment by andrispraulitis** [comment]
same as #785 ?
