### ISSUE TITLE
How to change Animation for tabs

### ISSUE THREAD

**Issue by vnovick** [aksonov/react-native-router-flux#770]
### Version

Tell us which versions you are using (react native 0.26 is required for v3): 
"react-native": "^0.26.2",
"react-native-router-flux": "^3.26.5"

There is no description in docs how to use Animation.

Specifically I want to change Animation on tab change. How can I implement this?

**Comment by xvalentino** [comment]
I'd like to disable animations. Anyone know if there is an easy way to implement this yet?

**Comment by zxcpoiu** [comment]
Try

https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L105

and see if it works

**Comment by Anthonyzou** [comment]
This seems to work. The only issue I cant figure out is when to reset `bounceValue` in the state when navigating away.

```javascript
import React, { Component } from 'react';

import {
  Animated,
  Dimensions,
  NativeModules,
  View,
} from 'react-native';
const {UIManager} = NativeModules;
const WIDTH = Dimensions.get('window').width;

class SitesPage extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      bounceValue: new Animated.Value(WIDTH),
    };
  }

  componentWillReceiveProps(){
    this.state.bounceValue.setValue(-WIDTH)
  }

  componentDidMount() {
    UIManager.setLayoutAnimationEnabledExperimental &&
    UIManager.setLayoutAnimationEnabledExperimental(true);
    Animated.spring(                          // Base: spring, decay, timing
      this.state.bounceValue,                 // Animate `bounceValue`
      {
        toValue: 0,                         // Animate to smaller size
        velocity: 10,
        deceleration: 2
      },
    ).start();                                // Start the animation
  }

  render() {
    return (
      <Animated.View style={{flex:1, transform: [{translateX: this.state.bounceValue},]}}>
        <View>...</View>
      </Animated.View>
    );
  }
}
```

**Comment by xvalentino** [comment]
@Anthonyzou depending on what kind of scene it is, maybe you could reset the state in componentWillUnmount.

**Comment by Anthonyzou** [comment]
@xvalentino It doesn't seem to work. This is a scene in parent with the attribute `tabs={true}`

**Comment by xvalentino** [comment]
Hmm, how about adding a listener?

https://facebook.github.io/react-native/docs/animated.html#addlistener

Once the value hits 0, call https://facebook.github.io/react-native/docs/animated.html#stopanimation and set the state back to whatever you need it to be.

Let me know, as I haven't needed to do this yet, but could end up using this in the future.

Hope this helps! @Anthonyzou

**Comment by keeleycarrigan** [comment]
@Anthonyzou I think the reason it's not working totally is the Animation start call should be pulled out into it's own function that can be called whenever and it needs to be called again on `componentWillReceiveProps` after resetting the width. Doing that makes my scenes animate in every time they are called.

@xvalentino thanks so much for this solution. I think I may try to add some logic in there to animate in left or right based on the situation.

**Comment by electricfeel1979** [comment]
with the version 4.0.0-beta.21 to disable the animation its animationEnabled={false}

i really had to dig around the plugin to find this, it was on the node_modules, hopefully this could have been included on the api reference.

**Comment by tranlehaiquan** [comment]
animationEnabled={false} work only with IOS? Any idea?
