### ISSUE TITLE
Routing from inside a tab scene to outside it breaks the navbar

### ISSUE THREAD

**Issue by diogoviannaaraujo** [aksonov/react-native-router-flux#773]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.0
- react-native v0.26.3

### Expected behaviour

Im using a structure like this

```
<Scence 'Login' />
<Scene 'Dashboard' tabs=true />
   <Scene 'Home' />
   <Scene 'Fav' />
<Scene 'ItemProfile' />
```

I did that so when routing to Item profile it would not show the tabBar, and would keep the tabs position the same and so
In 3.22, i was able to push from Home to ItemProfile without problems

### Actual behaviour

Now i get ItemProfile without the navbar junt a empty space for it

### Steps to reproduce

1. create a structure like that
2. push from a scene inside a tab to one outside
3. watch tabas disapear

**Comment by rturk** [comment]
@diogoviannaaraujo can you elaborate? Can you please paste all your code or link to a gist. Snipets of code don't help much.

**Comment by Elyx0** [comment]
I've experimented the same.

When navigating from down to top
`static renderNavigationBar(props) {` is never called.

In his example
```js
<Scence 'Login' />
<Scene 'Dashboard' tabs=true />
   <Scene 'Home' />
   <Scene 'Fav' />
<Scene 'ItemProfile' />
```
Calling `Actions.Login()` from the Scene `Fav` would render the Login Scene without calling `renderNavigationBar` hence having the top bar empty.

```js
'use strict';
import React, {Component} from 'react';
import {ScrollView, Text, View} from 'react-native';

export default class LoginView extends Component {
  constructor(props) {
    super(props);
  }

  static renderNavigationBar(props) {
    console.log(props,this.props,this);
    return (
      <View><Text>HELLO></Text></View>
    );
 }

  render() {
    return (
      <ScrollView style={{
          flex: 1,
          position:'relative',
          marginTop:cssConfig.header.height,
        }}>
        <Text>My nav bar is gone if Action.Login() called me from a tabbar child route !</Text>
    </ScrollView>);
}
}

**Comment by diogoviannaaraujo** [comment]
Yeah, thats exaclty it!

**Comment by rturk** [comment]
Please check example
You're not calling renderNavigationBar anywhere in your code, what I'm missing something?

Also you can always include customized NavBar in your render code
 
```
  render() {
    return (
    <View><Text>HELLO></Text></View>
      <ScrollView style={{
          flex: 1,
          position:'relative',
          marginTop:cssConfig.header.height,
        }}>
        <Text>My nav bar is gone if Action.Login() called me from a tabbar child route !</Text>
    </ScrollView>);
}
}
```

**Comment by rturk** [comment]
What happens if you go Login from 'ItemProfile' ?

**Comment by diogoviannaaraujo** [comment]
If I open the app on Login and go to Itemprofile the navbar is there, but if I go from Home to Login and the navbar is alreadly gone it does not come back.

**Comment by diogoviannaaraujo** [comment]
Someone could find any workaround this? Is forcing me to stay with RN 0.22 😢

**Comment by rturk** [comment]
@diogoviannaaraujo I can't reproduce this. You can always re-create your own navbar and implement it inside the scene view
https://gist.github.com/rturk/a52321593dd9264ddd2ccbd43eb489b7

**Comment by aksonov** [comment]
@diogoviannaaraujo Please provide github repo with our Example project modification to reproduce the issue.

**Comment by cridenour** [comment]
I'm going to close this due to inactivity. If this continues to be a problem, please let us know and we will re-open the issue. If this is a question about using the library, head over to the [Gitter Chat](https://gitter.im/aksonov/react-native-router-flux) for live help!

**Comment by blackxored** [comment]
I'm experiencing this as well.
