### ISSUE TITLE
Actions.callback is not defined

### ISSUE THREAD

**Issue by babbarankit** [aksonov/react-native-router-flux#775]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.2
- react-native v0.26.2

### Expected behaviour
I am calling the second screen using Actions.second() It should redirect to new screen

### Actual behaviour
Instead it is saying Actions.callback() is not defined

### Steps to reproduce

1. Install React-native with react-native-router-flux with redux (3.5.2)
2. Follow the Redux Guide and create two scenes
3. From First Scene Create a button to redirect to second screen
4. See the Error

**Comment by babbarankit** [comment]
This seems to be working. I will need to improve my library design.

**Comment by rturk** [comment]
@babbarankit Fantastic! Gitter is also a great place to ask questions.
 https://gitter.im/aksonov/react-native-router-flux

**Comment by babbarankit** [comment]
Thanks @rturk for this info 👍
