### ISSUE TITLE
Unable to get TabBar working

### ISSUE THREAD

**Issue by sammkj** [aksonov/react-native-router-flux#776]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.16
- react-native v0.26.3

## Problem

When I go to `tabbar`, I don't see the tab bar. Did I do something wrong?

```
    <Router>
      <Scene key="root">
        <Scene
          key="pageOne"
          initial
          component={PageOne}
          title="PageOne"
        />
        <Scene key="tabbar">
          <Scene
            key="main"
            tabs
            title="Tabs"
          >
            <Scene
              key="tab1"
              initial
              component={TabView}
              title="Tab 1"
            />
            <Scene
              key="tab2"
              component={TabView}
              title="Tab 2"
            />
          </Scene>
        </Scene>
      </Scene>
    </Router>
```

**Comment by cridenour** [comment]
The `tabbar` Scene should be the one with tabs={true}, not it's first child. Basically remove the whole `tabbar` scene and rename `main` to `tabbar`.

**Comment by sammkj** [comment]
@cridenour , thank you for your response. I tried your suggestion. But still can't get it work. Here a screenshot:


![deded](https://cloud.githubusercontent.com/assets/9153498/15787016/5d0fc708-2985-11e6-9b82-cc8e14575c44.gif)

**Comment by aksonov** [comment]
Please check our Example project with tab bar

**Comment by shaxbee** [comment]
@sammkj You need to specify icon property (it must be a component which defines look of a tab) for each sub-scene which has to show as a tab.

**Comment by cridenour** [comment]
I'm going to close this due to inactivity. If this continues to be a problem, please let us know and we will re-open the issue. If this is a question about using the library, head over to the [Gitter Chat](https://gitter.im/aksonov/react-native-router-flux) for live help!
