### ISSUE TITLE
[Question] Best way to Synch state across scenes using Default Reducer.

### ISSUE THREAD

**Issue by shiv86** [aksonov/react-native-router-flux#777]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

    "react-native": "^0.26.3",
    "react-native-router-flux": "^3.26.16"

### Question

What is the best way to change the props of another scene such that it is consistent with another scene using the DefaultReducer:

Say for example I have 3 scenes: **MainContainer** > **FirstContainer**  > **SecondContainer**. 

The FirstContainer has a props attribute called volume e.g.: this.props.volume. When a button is clicked on FirstContainer the following action is called:

`Actions.secondContainer({volume: this.props.volume});`
 
The SecondContainer loads with this.props.volume = 1. The SecondContainer also has button when click the following action is called:

`Actions.refresh({volume: 0});`

Which changes the.props.volume = 0 for the SecondContainer. When the button on the SecondContainer is clicked how can I ensure that this.props.volume for the FirstContainer also changes its prop.volume = 0, such that the volume prop is consistent for both First and Second Container:

I have created an example to demo this use case: https://github.com/shiv86/SnchComponentStateTest/

```
Also these are all the scenes:

class SynchComponentState extends Component {
    render() {
        return <Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'} }>
            <Scene key="main" >
              <Scene key="mainContainer" component={MainContainer} />
              <Scene key="firstContainer" component={FirstContainer} />
              <Scene key="secondContainer" component={SecondContainer} />
            </Scene>  
     
        </Router>;
    }
}

```

**Comment by aksonov** [comment]
Sorry, but it is only navigation router, not framework for syncing your app state. I'd recommend to look at MobX & react-native-mobx or Redux.

**Comment by shiv86** [comment]
ah ok. I misunderstood the scope of RNRF. Thanks
