### ISSUE TITLE
Actions.[SCENE_NAME] is not working.

### ISSUE THREAD

**Issue by lexfernandez** [aksonov/react-native-router-flux#780]
### Version

Tell us which versions you are using (react native 0.26 is required for v3): 

"react-native": "^0.26.2",
"react-native-button": "^1.6.0",
"react-native-drawer": "^2.2.3",
"react-native-router-flux": "^3.26.16",
"react-redux": "^4.4.5"
### Expected behaviour

I implemented the drawer in my react-native application, I am using redux as well, I expect the side menu show up with the buttons to go to other scenes and when I click those buttons they will take me to another scene.
### Actual behaviour

I click the side menu button and the buttons do nothing, I do click on them and the scene I was trying to go never show up.

This is my code:

app.js

``` javascript
      <Provider store={this.state.store}>
        <RouterWithRedux>
          <Scene key="drawer" component={NavigationDrawer}>
            <Scene key="root"
            tabs={true}
            component={connect(state => ({auth: state.auth}))(Switch)}
            selector={(props)=> props.auth.token !=='' ? "map" : "login"}>
              <Scene key="login" hideNavBar={true} component={Login} />
              <Scene key="map"  component={Map} title="Google Map" initial={true}/>
              <Scene key="todoApp" hideNavBar={true} component={TodoApp} title="Todos"   />
            </Scene>
          </Scene>
        </RouterWithRedux>
      </Provider>
```

Navigator

``` javascript

import React,{ Component} from 'react'
import Launch from './Launch'
import Drawer from 'react-native-drawer'
import {DefaultRenderer} from 'react-native-router-flux';

export default class Navigation extends Component {
    constructor(props){
        super(props);
    }
  render(){
    console.log(this.context);
    const navigationState = this.props.navigationState;
    let selected = navigationState.children[navigationState.index];
    // var activeScene = (selected.name == "root" : selected[0] ? selected);
        const children = this.props.navigationState.children;
    return (

        <Drawer
            ref="navigation"
            type="displace"
            content={<Launch />}
            tapToClose={true}
            openDrawerOffset={0.2}
            panCloseMask={0.2}
            negotiatePan={true}
            tweenHandler={(ratio) => ({
                 main: { opacity:Math.max(0.54,1-ratio) }
            })}>
              <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate}  key={selected.key} {...selected} />
        </Drawer>
    );
  }
}

```

Launch.js

``` javascript
import React, {Component} from 'react'
import {View, Text, StyleSheet, TouchableHighlight} from 'react-native'
import Button from 'react-native-button'
var Actions = require('react-native-router-flux').Actions;

export default class Launch extends Component {
    constructor(props){
      super(props);
    }
    render(){
        return (
            <View {...this.props}  style={[styles.container, this.props.sceneStyle]}>
                <Text>Launch page</Text>
                <Button onPress={Actions.todoApp}>Todo App</Button>
                <Button onPress={Actions.map}>Map</Button>
            </View>
        );
    }
}

var styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
    }
});

```

**Comment by lexfernandez** [comment]
I figure out that my problem is the Switch component because it is redirecting me to the map even if I try to push another view, is there a way to avoid this behaviour.

I remove this from my root component and everithing else start working as expected.
```javascript

component={connect(state => ({auth: state.auth}))(Switch)}
selector={(props)=> props.auth.token !=='' ? "map" : "login"}
```

**Comment by aksonov** [comment]
Could you clarify? Switch switches to map because probably your token is not empty. It should not be re-rendered unless your redux state auth is changed.

**Comment by lexfernandez** [comment]
@aksonov it switch to map but when I try to call another scene using Action.scene() it doesn't work, I think it is because of the Switch component because when I remove it the Action.scene() works great. How can avoid this conflict?

**Comment by aksonov** [comment]
Then it could be the bug. Could you make some example based on this project example and publish it to github?

**Comment by lexfernandez** [comment]
Sure, I will try to create an example as soon as I can, I will let you know.

**Comment by lexfernandez** [comment]
Hi @aksonov at the end I just needed to add type="replace" to my scenes in order to see the changes. I'm not sure why only type="replace" is working, can you please explain how do I have to use the other types. 'push', 'jump' and 'reset'

**Comment by aksonov** [comment]
@lexfernandez I'm waiting for examples, as i said it is probably a bug.

**Comment by adrienthiery** [comment]
I think I got in a similar situation, the idea being that the switch "Restricts" you to only one Scene, but in my case, I just created 2 "subroot" scenes for the switch : 
```
<Provider store={Store}>
    <Router
        sceneStyle={styles.routerStyle}
        hideNavBar={true}
    >
        <Scene
            key="root"
            component={connectedSwitch}
            tabs={true}
            selector={selectScene}
        >
            <Scene
                key={"anonymous"}
             >
                <Scene
                    key="index"
                    component={WelcomeView}
                    initial={true}
                />
            </Scene>
            <Scene
                key={"authenticated"}
            >
                <Scene
                    key="otherIndex"
                    component={AuthenticateView}
                    initial={true}
                />
            </Scene>
        </Scene>
    </Router>
</Provider>
```

And then my switch is : 
```
const connectedSwitch = connect(
    (state) => ({
        profile: state.Auth.profile,
    })
)(Switch);
const selectScene = (props) => (
    props.profile.id
        ? 'authenticated'
        : 'anonymous'
);
```

So only my Scenes children to "anonymous" are available if my user is not logged in, and only my Scenes under "authenticated" are available if my user is logged in.

Is it not the expected behaviour ?

Does it help @lexfernandez ?

**Comment by lexfernandez** [comment]
Thanks @adrienthiery, I remove the drawer and follow your example and it works like a charm. 

Do you have any idea how to implement a drawer(side-menu), I follow the example but I can't make it work correctly.

**Comment by lexfernandez** [comment]
@aksonov here is the example of the drawer + switch, please check it out and let me know what is the problem.

https://github.com/lexfernandez/goGreen/tree/drawer

**Comment by frangeris** [comment]
Same issue here using `"react-native-router-flux": "^3.30.0"`

I have the same situation of @adrienthiery 

> switch "Restricts" you to only one Scene

Exactly, for now the workaround is using 2 main `Scene`, authenticated and anonymous.

@aksonov Are you planning to improve this or just stay using the above?

**Comment by luisfuertes** [comment]
with "react-native-router-flux": "^3.30.2", if i set "type" to my scenes, Actions dont work.

And in Drawer if i set `tabs={true}`, `Actions.pop()` dont work. 
If i set `tabs={false}`, `Actions.pop()` works, renderLeftButton dont work, but renderBackButton work. 
And set  `type="reset"` dont work and i can go to Login with back button :s

```
			<Provider store={store}>
				<Router
				 sceneStyle={{backgroundColor:'white'}}
				 navigationBarStyle={Styles.navBar}
				 titleStyle={Styles.navTitle}
				 backButtonTextStyle={Styles.navTitleButtonStyle}
				 backButtonImage={this.backImage}
				 rightButtonTextStyle={Styles.navTitleButtonStyle}
				 leftButtonTextStyle={Styles.navTitleButtonStyle}
				>
					<Scene key="root" >
						<Scene key="Splash" initial={true} component={Splash} hideNavBar={true} />
						<Scene key="Login" component={Login} hideNavBar={true} />

						<Scene key='drawer' component={SideDrawer} open={false}>
								<Scene key="main" tabs={false} hideTabBar={false}>

									<Scene key='Home' component={Home} renderBackButton={this.renderMenuButton} renderRightButton={this.renderNotificationButton} sceneStyle={{paddingTop: this.getNavBarOffset(), paddingLeft: 3}} navigationBarStyle={[Styles.navBar, {backgroundColor: Commons.Colors.purple}]} type={'reset'}/>

									<Scene key='Screen1' component={Screen1} renderBackButton={this.renderMenuButton} sceneStyle={{paddingTop: this.getNavBarOffset(), paddingLeft: 3}} />
									<Scene key='Screen2' component={Screen2} renderBackButton={this.renderMenuButton} sceneStyle={{paddingTop: this.getNavBarOffset(), paddingLeft: 3}} />


								</Scene>
						</Scene>
					</Scene>
				</Router>
			</Provider>
```

**Comment by keeleycarrigan** [comment]
I'm experiencing this as well. I pretty much just have to 'fake' tabs. And the back button in the title doesn't render at all, but if I put a button in the view and `onPress` call `Actions.pop()` everything works. Seems like I should just build my own top nav bar and write all the logic myself.
