### ISSUE TITLE
[NavBar] wrong style 

### ISSUE THREAD

**Issue by Beingbook** [aksonov/react-native-router-flux#781]
### Version

Tell us which versions you are using (react native 0.26 is required for v3): 
- react-native-router-flux v3.26.16
- react-native v0.26.3
### Expected behaviour

<img width="487" alt="2016-06-05 6 57 07" src="https://cloud.githubusercontent.com/assets/2682865/15804774/5b3fd186-2b4f-11e6-8e72-93bbf2ec8bb4.png">
`<NavBar />` renders correctly iOS
### Actual behaviour

![kakaotalk_photo_2016-06-05-18-57-19](https://cloud.githubusercontent.com/assets/2682865/15804775/5f6ac644-2b4f-11e6-9878-6edb3318da08.jpeg)
`<NavBar />` renders incorrectly Samsung Galaxy Note 4.
And `Platform.Version` is 22.

So https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js#L50 should be fixed.
Android greater than 19 needs margin? I guess not... Why `<NavBar />` needs Platform checking?

**Comment by aksonov** [comment]
Feel free to submit PR to fix that, we can't check all android devices...

**Comment by AkaOne** [comment]
@Beingbook are you going to submit a PR to fix this ?

**Comment by Beingbook** [comment]
@AkaOne Oh, I can submit PR but I don't know it's general problem.

**Comment by AkaOne** [comment]
I've just check with react-native-router-flux v3.30.0 and it's not fixed
This not a bug though, if you take a look at NavBar.js you'll see that the styling isn't quite done to get the android's style, so platform checking and tunning the style should do
