### ISSUE TITLE
Actions error and navigationState.children conflicts with another child!

### ISSUE THREAD

**Issue by xrjxs** [aksonov/react-native-router-flux#782]
### Version
- react-native-router-flux v3.26.16
- react-native v0.25.1

### Expected behaviour
Actions.[SCENE_NAME] work correctly.

### Actual behaviour
Actions.[SCENE_NAME] jump to another scene 

### Steps to reproduce

1. scene config

        reducerCreate(params) {
             const defaultReducer = Reducer(params);
             return (state, action)=>{
                return defaultReducer(state, action);
            }
        }

        <Router
            createReducer={reducerCreate()}
            >
          <Scene key="modal" component={Modal}>
            <Scene key="root" hideNavBar={false} >
              <Scene key="product" component={Product} title="Item" />
              <Scene key="newsItem" component={NewsItem} title="News Item" />
              <Scene key="tabbar" tabs={true} initial={true} >
                <Scene key="main" title="Main" component={ProductList} />
                <Scene key="news" title="News" component={News} />
                <Scene key="order" title="Order" component={Order} />
              </Scene>
            </Scene>
          </Scene>
        </Router>

2.
* from the main page, is a product listview, click on the item will jump to product scene

* on the product page, click a button jump to order scene by Actions.order( {title: 'order'} ); this stey can by done in the componentDidMount() { Actions.order( {title: 'order'} ); }

* now the current page is the order scene.
  if you click on the tabbar News, then click on the News listview, normally it will jump to the newsItem scene, but it jump to product scene.
  if you click on the tabbar Main, then click on the ProductList listview, normally it will jump to the product scene, but it shows the red screen with the message: navigationState.clilcren[2].key"scene_1_product" conflicts with another child!

**Comment by 281330** [comment]
```
i think you're doing nesting wrong.  check out this code snippet from the Example:

<Scene key="tabbar" component={NavigationDrawer}>
                        <Scene key="main" tabs={true} >
                            <Scene key="tab1"  title="Tab #1" icon={TabIcon} navigationBarStyle={{backgroundColor:"red"}} titleStyle={{color:"white"}}>
                                <Scene key="tab1_1" component={TabView} title="Tab #1_1" onRight={()=>alert("Right button")} rightTitle="Right" />
                                <Scene key="tab1_2" component={TabView} title="Tab #1_2" titleStyle={{color:"black"}}/>
                            </Scene>
                            <Scene key="tab2" initial={true} title="Tab #2" icon={TabIcon}>
                                <Scene key="tab2_1" component={TabView} title="Tab #2_1" renderRightButton={()=><Right/>} />
                                <Scene key="tab2_2" component={TabView} title="Tab #2_2" onLeft={()=>alert("Left button!")} leftTitle="Left" duration={1} panHandlers={null}/>
                            </Scene>
                            <Scene key="tab3" component={TabView} title="Tab #3" hideTabBar={true} icon={TabIcon}/>
                            <Scene key="tab4" component={TabView} title="Tab #4" hideNavBar={true} icon={TabIcon}/>
                            <Scene key="tab5" component={TabView} title="Tab #5" hideTabBar={true} hideNavBar={true} icon={TabIcon}/>
                        </Scene>
                    </Scene>
```

**Comment by aksonov** [comment]
@xrjxs @281330  is right, also you could use 'clone' attribute to push 'cloned' scene from anywhere.

**Comment by AndrewHenderson** [comment]
I'm running into this same issue using the following code:
```jsx
export default Actions.create(
  <Scene key="root">
    <Scene key="login" component={Login} initial hideBackImage />
    <Scene key="app"
           tabs
           tabBarStyle={styles.tabBarStyle}
           tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle}
    >
      <Scene
        initial
        key="tab1"
        title="Events"
        component={EventsFeed}
        icon={TabIcon}
        iconName="home"
        hideBackImage
      />
      <Scene
        key="tab2"
        title="Create Event"
        component={EventForm}
        icon={TabIcon}
        iconName="event"
        hideBackImage
      />
      <Scene
        key="tab3"
        title="Profile"
        component={Profile}
        icon={TabIcon}
        iconName="person"
        hideBackImage
      />
    </Scene>
  </Scene>
);
```
Once the user has authenticated, I direct him to the `app` scene. Within app, is a tab `profile` which has a logout button. When the user clicks that I direct him to the `login` scene. When the user logs back in and goes to `profile` and logs out again I get the following error screen:

<img width="301" alt="screen shot 2016-11-26 at 1 47 57 pm" src="https://cloud.githubusercontent.com/assets/1031565/20644121/079d94d2-b3df-11e6-9e51-397536247d24.png">

**Comment by Ross-Landry** [comment]
@AndrewHenderson -I'm having the same exact problem. Did you find a solution?

**Comment by AndrewHenderson** [comment]
@Ross-Landry No. It's still happening for me. I've put resolving this issue on the back burner for now.

The message makes me think the router is trying to navigate from the same page "login" to itself.

**Comment by Ross-Landry** [comment]
Try adding:

 type={ActionConst.RESET} 

as a prop to your 'Login' scene. You may also have to add the prop to the parent scene, if that's what you navigate to. For example, when I logout I navigate to Actions.auth(), which starts at my login scene. So I had to add type={ActionConst.RESET}  to the Auth scene as well. 

Example:

                <Scene key="auth" barButtonIconStyle={{ tintColor:'black' }} type={ActionConst.RESET}  >
                  <Scene key="login" 
                                        component={LoginForm} 
                                        title="Login" 
                                        type={ActionConst.RESET} />
                  <Scene key="register" 
                                        component={RegisterForm} 
                                        title="Register" 
                                        onBack={() => this.onBackToLogin() }  />
                </Scene>

This worked for me, good luck!

**Comment by AndrewHenderson** [comment]
@Ross-Landry That worked! Thanks for posting!

**Comment by JeroenNelen** [comment]
@Ross-Landry  @AndrewHenderson 
I understand this works for the log-out case, in which you indeed would want to reset the navigation stack. But I have the following scenario:
1. user is on scene A and clicks a browse button which redirects to scene B
2. user navigates further, from B to C, from C to D (amount of browsing can differ)
3. at scene C, user does an action and now I want him to be redirected to scene A, currently scene A has type PUSH because you arrive, in the beginning at scene A via scene Z and you have to be able to use the back-button.... so I try to Actions.sceneA(); but this throws the navigationState.children issue, because it is trying to add the scene again to the stack, is there a way for me to redirect to scene A without using REPLACE for example?  Any suggestion?

**Comment by Ross-Landry** [comment]
@JeroenNelen 

Does Scene A always go back to Scene Z when you click the 'back' button on the nav bar? If that's the case then I could suggest a workaround.

**Comment by JeroenNelen** [comment]
@Ross-Landry that's a scenario we can consider yes, to always have sceneA's back button to redirect to sceneZ.
RESET to sceneA is not an option, because then we can not go back to sceneZ from sceneA as the stack was cleared.

**Comment by Ross-Landry** [comment]
@JeroenNelen you can define the scene that the back button navigates to using the 'onBack' prop of the Scene component. 

So for sceneA set:
onBack={()=> Actions.sceneZ() } 

Once you've done this then you can make sceneA type RESET.

**Comment by AndrewHenderson** [comment]
I've run into this issue again: https://github.com/aksonov/react-native-router-flux/issues/1526

**Comment by AndrewHenderson** [comment]
Resolved using `Actions.pop`.

**Comment by Dictory** [comment]
Use `NavigationActions.pop()` before push fix it for me, example:
```javascript
   NavigationActions.pop();
   setTimeout(()=> NavigationActions[to](options));
```

**Comment by razvan-tudosa** [comment]
Isn't there a cleaner solution? I have to do this in several places in order to avoid the crashes, it's insane!

**Comment by aksonov** [comment]
Unfortunately ExperimentalNavigation API is very buggy and already deprecated by React Native team.
I'm working now on v4 version now that uses new http://reactnavigation.org and actively looking for contributors:
 #1595

**Comment by Dictory** [comment]
@aksonov it is brilliant news! Good luck!
