### ISSUE TITLE
Search field in navbar loses focus after animation

### ISSUE THREAD

**Issue by vonovak** [aksonov/react-native-router-flux#783]
### Version

- react-native-router-flux v3.26.16
- react-native v0.26.3

My problem is this - I'm using RNRF in an android app and I have a search `<TextInput>` in the navbar, which has autofocus set, so that after transitioning to the Scene, user can enter query right away. The problem is, the focus is lost upon the end of animation.

### Expected behaviour
As the scene transitions, I'd like the keyboard appear and stay there.

### Actual behaviour
While transitioning to the scene, keyboard goes up but upon the ed of animation, `<TextInput>` loses focus and keyboard gets hidden again. :/

Turning the animation off doesn't help.

### Steps to reproduce

1. use a custom navbar through `static renderNavigationBar(props)` 
2. put a textinput with autofocus in the navbar
3. call Actions.searchScene()

I would welcome any thoughts on how to solve this in a nicer way if possible, thanks.
Note I cannot easily access the component through this.refs because the navbar is rendered ins static context. Hm maybe not doing it static will help

**Comment by vonovak** [comment]
solved by not using the static renderNavigationBar and focusing the field upon the end of animation

**Comment by ajoshdee** [comment]
Hi what did you use instead of the static renderNavigationBar?

**Comment by vonovak** [comment]
I just rendered the search field as part of the content.

**Comment by MirGhojam** [comment]
Hi, my whole android app's TextInput has the same phenomenon, I would be very grateful if you'd elaborate me on this solution.  Thank You @vonovak

**Comment by vonovak** [comment]
@MirGhojam I honestly don't remember. I switched to ex-navigation soon after trying out RNRF. The next, hopefully final switch, will be to react-navigation :)

**Comment by MirGhojam** [comment]
@vonovak oh I see, Thanks anyway :)
