### ISSUE TITLE
Swipe back moves multiple scenes

### ISSUE THREAD

**Issue by Andreyco** [aksonov/react-native-router-flux#784]
### Setup

"react-native-router-flux": "^3.26.16"
"react-native": "0.26.2"  
### Expected behaviour

On swipe back gesture, I expect to animate single scene only and go back by that scene.
### Actual behaviour

From time to time (+- 50%), swipe back gesture animates 1 or multiple scenes. Despite it animates multiple scenes while swipe back is in progress, it goes back by single scene in every situation.
See attachment
![swipeback](https://cloud.githubusercontent.com/assets/829963/15815948/6ad2c6cc-2bd0-11e6-903b-91ae8c398ddc.gif)
### Steps to reproduce

Give following scene hierarchy, do swipe back gesture

``` javascript
<Router createReducer={createNavigationReducer}>
      <Scene key="auth" component={RootScene} hideNavBar initial={true} />
      <Scene key="sceneLogin">
        <Scene key="sceneLogin1" component={LoginScene} title="Login" renderLeftButton={renderLeftButton} />
      </Scene>
      <Scene key="sceneRegister">
        <Scene key="sceneRegister1"
          component={RegistrationScene} title="New User" renderLeftButton={renderLeftButton} />
        <Scene key="sceneRegister2"
          component={RegistrationScene2} title="New User2" />
      </Scene>
    </Router>
```

Reducer (basic)

``` javascript
export const createNavigationReducer = (params) => {
  const defaultReducer = Reducer(params);
  return (state, action) => {
    if (__DEV__) {
      /* eslint-disable no-console */
      if (console.group) console.group('Navigation:');
      console.log('ACTION:', action);
      if (console.groupEnd) console.groupEnd();
      /* eslint-enable no-console */
    }

    console.log(defaultReducer(state, action));
    return defaultReducer(state, action);
  };
};
```

Navigation actions

```
// Root view (with "New User" button)
New user -> Actions.sceneRegister

// New User scene
go next -> Actions.sceneRegister2

```

**Comment by aksonov** [comment]
Please check this on UIExplorer react native example with ExperimentalNavigation, it could be RN issue.

**Comment by Andreyco** [comment]
This is related to scene nesting - which is unique to RNRF as far as I know.
Having different hierarchy, it works as expected. Except navbar does not slide with Scene

**Comment by aksonov** [comment]
Could you add more scenes with "plain" implementation?
Why did you close this?

**Comment by Andreyco** [comment]
> Could you add nested scenes with "plain" implementation?
No, I did not attempt to do so.

**Comment by aksonov** [comment]
@Andreyco Please try, because it may be not RNRF issue. RNRF just constructs navigationState and passes it to RN NavigationExperimental API.

**Comment by tsyirvo** [comment]
Hey,
I'm having the same issue when swiping back when the scenes are wrapped inside a tabbar…
I'm using RNRF v3.22.23 & RN v0.24.1

**Comment by ms88privat** [comment]
👍

**Comment by abumostafa** [comment]
+1

**Comment by MihaiDamian** [comment]
Having the same issue. Swiping randomly navigates to the previous scene in the stack or to the previous scene in the parent stack.

**Comment by arunkumarrmrj** [comment]
Use below code on router init

`<Router createReducer={createNavigationReducer}>
<Scene key="auth" component={RootScene} hideNavBar initial={true} renderBackButton={null} panHandlers={null} />
  <Scene key="sceneLogin">
    <Scene key="sceneLogin1" component={LoginScene} title="Login" renderLeftButton={renderLeftButton} renderBackButton={null} panHandlers={null} />
  </Scene>
  <Scene key="sceneRegister">
    <Scene key="sceneRegister1"
      component={RegistrationScene} title="New User" renderLeftButton={renderLeftButton} renderBackButton={null} panHandlers={null} />
    <Scene key="sceneRegister2"
      component={RegistrationScene2} title="New User2" renderBackButton={null} panHandlers={null} />
  </Scene>
</Router>
`

**Comment by DjangoGG** [comment]
having the same issue
