### ISSUE TITLE
React native 27 is out 3 hours ago. Any plans for 3.27.0?

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#786]
[Here](https://github.com/facebook/react-native/releases)!

**Comment by rturk** [comment]
Acording to release notes Lot's of breaking changes

Breaking changes related to Navigation

- Kill NavigationLegacyNavigator (ef44781) - @hedgerwang
- Kill NavigationExperimental Containers (14eb427) - @ericvicenti
- Kill NavigationView (c3714d7) - @hedgerwang

New features
- Animated: Implement toJSON method of Animated (17f0807) - @wusuopu
- Expose a new prop transition for scene renderer. (55c3086) - @hedgerwang

**Comment by jpapillon** [comment]
+1

**Comment by Andreyco** [comment]
As stated in release notes _NavigationRootContainer_ is removed. Assuming that, RNRF is completely broken, since _Scene_ makes use of _NavigationRootContainer_. Or am I wrong?

**Comment by joenoon** [comment]
@Andreyco RNRF is locked to 0.26.x, so RNRF should be perfectly fine.  I'm sure there will be a lot of work to make RNRF work with 0.27.x given some of the changes upstream.  So RNRF will hold people back to 0.26.x for now.  I will try to allocate some time this week to look at the 0.27.x path.

**Comment by Andreyco** [comment]
@joenoon oops, it sounded differently as I mentioned that. RNRF works just great as is, with RN 0.26. I meant it's not in shape ready for RN 0.27, which has introduced several breaking changes.

**Comment by joewood** [comment]
Maybe worth testing with the release candidate of 0.28 - which has just been [labeled](https://github.com/facebook/react-native/releases/tag/v0.28.0-rc.0). This is due to be final on [June 20th](https://github.com/facebook/react-native/blob/master/Releases.md)

**Comment by cridenour** [comment]
Which as I'm sure we're all aware is my birthday. 🎉

**Comment by aksonov** [comment]
Looks like no sense to work on 0.27, because 0.28 breaks things again, please check my latest post for #557

**Comment by mvaivre** [comment]
@aksonov Agreed. And 0.28 will add important fixes like this one: https://github.com/ericvicenti/navigation-rfc/issues/61

**Comment by rturk** [comment]
@aksonov agreed. I've spent a few hours reading v0.27 and v0.28 navigator code. There are several breaking changes related to the same components. Makes no sense to invest time for two consecutive breaking changes that are only a few weeks apart. Also v0.28 it's already in RC so we can already start coding for it.

**Comment by aksonov** [comment]
Okey, 3.30.0 version doesn't depend from 0.26 anymore (i've forked NavigationExperimental API to separate package). We will update fork (react-native-experimental-navigation) when new changes within Experimental Navigation API will be made (we could clone even latest master fixes now!). Also we will update this component to work with latest version API but it is not so critical now (now component still depends from 0.26 API, but not from React Native 0.26)

Feedback is welcome.

**Comment by aksonov** [comment]
@joenoon other others, if you want to adopt RNRF to latest 0.28 (or even master) API, let me know. I've published latest master as react-native-experimental-navigation, 0.29.0-alpha, so you could play it with RNRF right now.

**Comment by aksonov** [comment]
Closing it for now. If someone wish to upgrade RNRF to latest API, let me know, PR is welcome.
