### ISSUE TITLE
Prop for drawerImage placement on `left` and `right` of navigationBar

### ISSUE THREAD

**Issue by aestrro** [aksonov/react-native-router-flux#794]
### Version
- react-native-router-flux v3.26.5
- react-native v0.26.2

### Expected behaviour
Adding a prop on **Scene** when desiring to place the drawerImage on the `right` or the `left` of the navigationbar.

### Actual behaviour
Currently on a `Scene` we are able to overwrite the `hamburger` drawerImage with our own image, which displays the drawerImage on the left side of the navigationBar by default

**Comment by aksonov** [comment]
With 3.26.20 Drawer's support is simplified - so now you could defined own leftButton/rightButton and use Actions.refresh({key:DRAWER_KEY,  open: value=>!value}) within onPress method.

Check updated docs for more details.

**Comment by aestrro** [comment]
Must I set the tabs={true} prop in the child Scene to get this working? Currently my application is not using tabs, so I feel this is why it doesn't work right now.

```
<Scene key="drawer" component={Drawer} open={false} >
  <Scene key="main" **tabs={true}** >
    ....
  </Scene>
</Scene>
```

**Comment by aksonov** [comment]
It is not required to have tabs, it should be just one child, but usually it is tabs. I don't know how it is possible to use drawer but not use tabs (tabs is NOT tab bar, it is 'tabs' structure, like tabs in browser) - your drawer scenes are usually tabs.

**Comment by aestrro** [comment]
Just to let you know:
```
onPress={() => Actions.refresh({key: 'drawer', open: value => !value }) }
```
Does not work because the open value is a function in this state, (I was getting a YellowBox error), but:

```
onPress={() => Actions.refresh({key: 'drawer', open: true }) }
```
Does work because when the drawer is open I can dismiss by other means...

**Comment by aksonov** [comment]
You need to set initial value open so refresh could determine modifier 

Pavel.
