### ISSUE TITLE
Disable "swipe to go back" for modal

### ISSUE THREAD

**Issue by axelander** [aksonov/react-native-router-flux#796]
### Version
- react-native-router-flux v3.26.1
- react-native v0.26.0

Is there a way to disable "swipe to go back" for modals?
In the app I'm currently working on we open a WebView in a modal and when trying to scroll up in the WebView the modal captures the gesture and starts the back-animation. Like this:
![](http://g.recordit.co/lDpVhSIbpG.gif)

**Comment by willmcneilly** [comment]
Possibly related to this issue https://github.com/facebook/react-native/issues/7450

**Comment by cridenour** [comment]
Have you tried `panHandlers={null}` on the Scene?

**Comment by axelander** [comment]
@cridenour Thank you! 👍

**Comment by Shinichi52** [comment]
@cridenour  Thank you

**Comment by mazenchami** [comment]
> Have you tried `panHandlers={null}` on the Scene?

@cridenour, yes that helps but is there a way to programmatically enable/disable it dependent on the modal visibility. i.e. keep panHandlers when modal is closed and set panHandlers to null when modal is open?
