### ISSUE TITLE
If you are passing component={Drawer} to show your DrawerLayout, how are you opening/closing it using the navbar burger button?

### ISSUE THREAD

**Issue by 281330** [aksonov/react-native-router-flux#799]
This is just a general question in terms of approach.

I was reading the API documentation and have decided to do the following:

```
<Router getSceneStyle={getSceneStyle} navigationBarStyle={styles.navigationBarStyle} titleStyle={styles.titleStyle}>
  <Scene key='root'>
    <Scene key='drawer' component={DrawerLayout}>
       <Scene key='main' tabs={true}>
          <Scene key='search' component={Search} title='search'/>
          <Scene key='results' component={Results} title='results'/>
       </Scene>
    </Scene>
  </Scene>
</Router>
```

I have a DrawerLayout component that uses DrawerLayoutAndroid, and I am also using the RNRF built-in nav bar with a burger button.  In the code above, I do not have the renderLeftButton() because I couldn't get it to work, but that's what I plan on using.

Using that functionality and structuring the code as done so above, how do you access the openDrawer() and closeDrawer() methods when clicking on the burger button?  How can I access those methods, which exist in the DrawerLayout component?  Should I be using redux?  

Thanks!

**Comment by aksonov** [comment]
You will access it via navigation state! Check #797 and https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#drawer-side-menu-integration

**Comment by 281330** [comment]
@aksonov thanks!  i am wondering if I am using DrawerLayoutAndroid, should I be using the drawer methods for open and close?  I am not sure how the Drawer library you are using works, I am just trying to use what react-native provides out of the box.  Please let me know if you have any suggestions.  Thanks!

**Comment by suibobuzhuliu** [comment]
`Actions.refresh({status:"open"});`

**Comment by ctrlaltdylan** [comment]
Thank you, the documentation answers my question as well. How awesome!

**Comment by Nethracs** [comment]
Can anyone please give me some hint on how to use DrawerLayoutAndroid with redux?
