### ISSUE TITLE
God it would be nice if...

### ISSUE THREAD

**Issue by duro** [aksonov/react-native-router-flux#8]
...this was built with Redux. Just saying. Love the implementation, but with everyone jumping on the Redux band wagon, including myself, I'm not sure about mixing Flux implementations.

**Comment by aksonov** [comment]
I don't see anything wrong with mixing implementation, if you would use this component only for nav transitions. However i agree that mixing could be issue. It is possible to add abstraction layer and use different flux implementation, but it is not trivial, so PR is welcome.

**Comment by Mokto** [comment]
+1

I forked [react-native-counter-ios-android](https://github.com/chentsulin/react-native-counter-ios-android)

I tried to pass props to route like this :

```javascript
var RouterModule = React.createClass({
    render: function() {
        console.log('FROM ROUTER  : ',this.props.counter);
        return (
          <Router>
            <Schema name="default" sceneConfig={Animations.FlatFloatFromRight} />
            <Route {...this.props} name="launch" component={Counter} initial={true} hideNavBar={false} title="Launch"/>
          </Router>
        );
    }
});
```

When I increment the counter:
* `console.log('FROM ROUTER  : ',this.props.counter);` is rightly updated
* but the subcomponent Counter) rerender with not updated counter value.

Please let me know if I am not clear.

**Comment by aksonov** [comment]
Please provide your code as github repo.

Pavel.

**Comment by Mokto** [comment]
Thanks for your quick answer.

[My forked repo](https://github.com/Mokto/react-native-counter-ios-android/blob/master/src/containers/Router.js)

The console.log in ./src/components/Counter.js and ./src/containers/Router.js show the issue.

Please let me know if you need anything else.

**Comment by aksonov** [comment]
Sorry, but it is not intended usage of this component. Router should be high-level app component, not internal one, so it doesn't change his props during app work. As I see Redux provides own router so looks like they are not compatible to each other.

**Comment by Mokto** [comment]
Ok, thank you anyway, I found a workaround. (connect every subcomponent with redux)
