### ISSUE TITLE
NavBars won't "easily show/hide" (iOS 9.2)

### ISSUE THREAD

**Issue by andreasbhansen** [aksonov/react-native-router-flux#80]
Hey,

I cannot get the NavBars to show/hide on only some specific views.

An example where I would assume that the *"launchpage"* view would have its navbar hidden (because the Router says so), but the *"loginpage"* view navbar would be visible, because it says so. However, the navbar is hidden on all views when the ```hideNavBar={true}``` is set on the Router:

```javascript
<Router hideNavBar={true} initialRoutes={['launchpage']}>
  <Route name="launchpage" component={LaunchPage} type="reset"/>
  <Route name="loginpage" component={LoginPage} hideNavBar={false} title="Login" schema="default"/>
</Router>
```

So I tried to remove ```hideNavBar={true}``` from the router, and set place ```hideNavBar={false}``` on the *"loginpage"* view, but then the navbar is shown on all pages, not only the *"loginpage"*:

```javascript
<Router initialRoutes={['launchpage']}>
  <Route name="launchpage" component={LaunchPage} type="reset"/>
  <Route name="loginpage" component={LoginPage} hideNavBar={false} title="Login" schema="default"/>
</Router>
```

I've also tried the ```showNavigationBar={true}```, but it doesn't help solving this either. Any ideas here?

**Comment by aksonov** [comment]
It is known problem, see #72. Btw, you always could use own custom navbar and set it as header/footer for Route, and hide it when necessary.

**Comment by andreasbhansen** [comment]
I'll definitely look into that!
And thanks for this contribution, makes life easier.

**Comment by andreasbhansen** [comment]
@aksonov I'm having some really weird issues with the navigation bar. I can't really implement a custom one, because for some reason, with the following code, a navigation bar is present all the time within the **"loggedinLayout"** route group, even though ```hideNavBar={true}```:

```javascript
    <Router hideNavBar={true} initialRoutes={['loggedinLayout']}>
        <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
        <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        <Schema name="tab" type="switch" icon={TabIcon}/>

        <Route name="launchLayout" type="replace">
          <Router hideNavBar={true}>
            <Route name="launchview" component={LaunchView} type="replace" />
            <Route name="onboardingemail" component={OnboardingEmail} title="Email" schema="default"/>
            <Route name="onboardingname" component={OnboardingName} title="Name" schema="default"/>
            <Route name="onboardingphonenumber" component={OnboardingPhoneNumber} title="Phone Number" schema="default"/>
            <Route name="onboardingpassword" component={OnboardingPassword} title="Password" schema="default"/>
            <Route name="onboardingregistrationcomplete" component={OnboardingRegistrationComplete} title="Welcome!" schema="default"/>
          </Router>
        </Route>

        <Route name="loggedinLayout" type="replace">
          <Router footer={TabBar} hideNavBar={true}>
            <Route name="mainview"  key="1" component={MainView} title="Main" schema="tab" />
            <Route name="myorders" key="2" component={MainView} title="My Orders" schema="tab" />
            <Route name="logoutview" key="4" component={LogoutView} title="Profile" schema="tab" />
          </Router>
        </Route>
      </Router>
```

When it's set to hidden, the navigation bar is showing with the route name as title, and there is no back button when navigating the tabs (which is great!). However, if i set ```hideNavBar={false}``` on the **"loggedinLayout"**, I'm able to style it the way I want, but then there's a backbutton (when navigating between tabs) I can't get rid of, I've tried the newer props like ```renderLeftButton``` and ```backButtonStyle``` but they have no effect.

**Comment by aksonov** [comment]
hideNavBar now is supported for Route
