### ISSUE TITLE
Cannot pop twice

### ISSUE THREAD

**Issue by Swordsman-Inaction** [aksonov/react-native-router-flux#803]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.16
- react-native v0.26.3

### Expected behaviour
I want to go back twice. I got the stack A -> B -> C, now I want go back to A without reload or reset it from C.
```
Actions.pop()
Actions.pop()
```
or 
```
Actions.pop(2)
```
doesn't work

### Actual behaviour
Just go back(pop) once

### Steps to reproduce

1.create 3 scenes, A, B, C
2.from A to B, then to C
3.try to go back to A from C

#39

**Comment by aksonov** [comment]
Yes, looks like this problem started from React Native 0.26, probably NavigationExperimental API has changed something. As workaround you may use setTimeout(()=>Actions.pop) for 'additional' actions, it should work.

**Comment by Swordsman-Inaction** [comment]
@aksonov thanks, man

**Comment by esutton** [comment]
How would I pop twice?

I am no JS expert.  I literally tried this syntax without achieving two pops:
`setTimeout(()=>Actions.pop);`

Did I read there support for a **Actions.pop(2)** enhancement coming?  

Is it available today somewhere?  I cannot seem to find where I read the issue.

**Comment by Swordsman-Inaction** [comment]
@esutton 
you can use the PR in #806 
or you can just use
```
Actions.pop()
setTimeout(() => {Actions.pop()}, 100)
```
to pop twice

**Comment by xvalentino** [comment]
To add onto what was said before, you probably want to use this.setTimeout, so you don't end up running into errors if the component unmounts before the function is called.

https://facebook.github.io/react-native/docs/timers.html

**Comment by esutton** [comment]
@xvalentino thank you.

I was using the syntax @Swordsman-Inaction kindly suggested.  However, I was getting crashes on cheap Samsung Galaxy S4 tablets on Android that I suspect *could* be related.  I do not know for sure.  Anyway, I went back to single-pops temporarily.

I understand a new RFRF API is coming for multiple pops.  I will wait until this API is documented in the README.ms and  a new RN release comes out that seems to play well with my other packages.

**Comment by xvalentino** [comment]
No problem. Let me know how it goes @esutton !

**Comment by nguyenvanphuc2203** [comment]
use Actions.popTo() instead
