### ISSUE TITLE
BackAction not dispatched when I swipe a Schene.

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#807]
This is the declaration of my Schene:
`<Scene key="VOTE" {...defaultProps} component={Vote} title="Vote" direction="vertical" hideNavBar={true}/>`

I use redux. Now when I swipe down, I pop to the previous parent, but (unlike from when I Actions.pop()) I get neither a `back` nor a `BackAction` action dispatched. I only get a `focus` action dispatch.

Why?

I'm using 
`React Native 0.26.3`
and 
`RNRF 3.26.16`

Thank you.

**Comment by aksonov** [comment]
@SudoPlz I can't reproduce it with our Example project, could you? I see BackAction property within logs.

**Comment by andrispraulitis** [comment]
RNRF Example:

Swipe back action type is "back", but Actions.pop() action type is "BackAction"

**Comment by SudoPlz** [comment]
@andrispraulitis I know that I have reducer code for both.
@aksonov I don't have time to create a project to reproduce this, I disabled swiping and just called Actions.pop() manually to solve this for now.

**Comment by chapati23** [comment]
this should be re-opened. have the exact same problem. only actions that's being dispatched by swipeBack is FOCUS
