### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by mbecker** [aksonov/react-native-router-flux#809]
### Version
- react-native-router-flux v3.26.24
- react-native v0.26.2
### Feature

Hi,

I know from reading the issues here that you could configure the animation for navigation from one to another scene as follows:

```
<Scene key="page" navBar={NavBarPage} component={Page} title="Page" getSceneStyle={NavigationCardStackStyleInterpolator.forVertical}/>
```

(You could use 'forHorizontal' as well)

Are any other animations are possible?

So from the normal [react native Navigator.NavigatorSceneConfigs](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js) the following animations are possible:

```
PushFromRight
FloatFromRight
FloatFromLeft
FloatFromBottom
FloatFromBottomAndroid
FadeAndroid
HorizontalSwipeJump
HorizontalSwipeJumpFromRight
VerticalUpSwipeJump
VerticalDownSwipeJump
```

How could I use these animations? How could I write a custom animation (for example material style animation)?

Thank you very much for the excellent library and for your work!

**Comment by aksonov** [comment]
@mbecker As I see ExperimentalNavigation has quite limited support of animations now, you may ask this questions at navigation-rfc github or React Native github because this component is just wrapper around it. If you really need it you could use RNRF v2 version (based on exNavigator)

**Comment by sbycrosz** [comment]
But then RNRF v2 breaks on the latest version of React Native because of what I believe to be the `split React and React Native import` introduced in RN 0.25.x
Would you still accept a PR for 2.x?

**Comment by aksonov** [comment]
@sbycrosz yes, why not. use https://github.com/aksonov/react-native-router-flux/tree/2.x branch and submit PR.

**Comment by sibelius** [comment]
@aksonov what is the progress on this?

can u use `FloatFromBottom` on Scene of RNRF?

**Comment by sibelius** [comment]
@mbecker did u find a solution?

**Comment by kenma9123** [comment]
He simple ignore things, if he can't really find a solution :D
