### ISSUE TITLE
BACK button on Android exits the app

### ISSUE THREAD

**Issue by alexander-ignatow** [aksonov/react-native-router-flux#81]
Back button on android exits the my react-native app. I am not sure if it is an expected behavior, but if so I suggest to add notice of this to the docs.

I fixed it with adding following handler to my project:

    BackAndroid.addEventListener('hardwareBackPress', () => {
      try {
        Actions.pop();
        return true;
      }
      catch(err)  {
        console.log("Cannot pop. Exiting the app...")
        return false;
      }
    });

**Comment by aksonov** [comment]
The component is just wrapper around exNavigator. Could you check if it works the same with pure exNavigator?
