### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by itcurves** [aksonov/react-native-router-flux#810]
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.16
- react-native v0.26.3

### Expected behaviour

Back button in navigation bar

### Actual behaviour

I installed the example app as shown in gif, but I never get Back button in Navigation bar on iOS.

What I have to do to add that button?

### Steps to reproduce

1.
2.
3.

**Comment by aksonov** [comment]
Enter tabbar, go to tab2_2 or anywhere where is more than one scene within the stack.

**Comment by itcurves** [comment]
ok I got it thank you. Is there a simple way to use Tabs? I am trying but bit new thing for me.

**Comment by aksonov** [comment]
Check Example

**Comment by itcurves** [comment]
That what I am following:
please check what is wrong:

<Scene key="root">
    <Scene key="tabbar" tabs={true} >
        <Scene key="tab1"  title="Tab #1"  >

        </Scene>
        <Scene key="tab2"  title="Tab #2" >
        </Scene>
    </Scene>
    <Scene key="home" component={Home} title="My Title" hideNavBar={false}/>

  </Scene>

gives me error below:
[react-native-router-flux] component property is not set for key=tabbar

sorry really new to these things just trying to learn.

Thank you

**Comment by aksonov** [comment]
Please go to gitter chat and ask for help.
