### ISSUE TITLE
Version 3.30.0 on npm causes errors with npm start

### ISSUE THREAD

**Issue by cgreening** [aksonov/react-native-router-flux#814]
### Version

- react-native-router-flux v3.30.0 from npm

### Expected behaviour

Can install version from NPM without any issues. Version on npm should match release tags in github.

### Actual behaviour

Version on npm does not work, version on npm is 3.30.0 which does not seem to match any tagged version in github.

Error on `npm start`

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: validateDOMNesting

node_modules/react-native-experimental-navigation/node_modules/react/lib
/validateDOMNesting.js collides with node_modules/react/lib/validateDOMNesting.js
```

### Steps to reproduce

1. Install latest version from npm
2. npm start
3. Error message about naming collisions.

**Comment by abelcha** [comment]
@cgreening What version of RN are you using ?

**Comment by tuckerchapin** [comment]
Just encountered a similar issue:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ReactNativeTextComponent
  Paths: ~/Development/PROJECT/native/node_modules/react-native/Libraries/ReactNative/ReactNativeTextComponent.js collides with ~/Development/PROJECT/native/node_modules/react-native-experimental-navigation/node_modules/react/lib/ReactNativeTextComponent.js
```

**Comment by aksonov** [comment]
Have you tried to remove node_modules and run install again? I can't reproduce this error both Example and my own app.

**Comment by Proyoyo** [comment]
I had the same issue. I fixed it by using npm 3 instead of npm 2.

**Comment by MillerDix** [comment]
Guess he`s using RN:0.25.x
Same here, ExperimentalNavigation caused naming collision
RN:0.25.1 （3.30README says RN0.26+ supported, but is there any way i can keep my RN 0.25.1 ? ）
npm: 3.7.3
Remove node_modules and install again doesn`t work.

**Comment by MillerDix** [comment]
Guess he`s using RN:0.25.x  

Same here, ExperimentalNavigation caused naming collision  
RN:0.25.1 ( 3.30README says RN0.26+ supported, but is there any way i can keep my RN 0.25.1? )  
npm: 3.7.3  
Remove node_modules and install again doesn`t work.

**Comment by aksonov** [comment]
Hm, maybe i need to remove "react" as dependency from react-native-experimental-navigation. Please try now (0.26.1)

**Comment by hellogerard** [comment]
I encountered the same error (with a different conflicting module name). Removing `node_modules` and re-installing all npm modules worked for me.

react: 15.1.0
react-native: 0.27.2
react-native-router-flux: 3.30.0

**Comment by DClark5218** [comment]
still an open issue for me. I removed node modules and did the same as @hellogerard recommended. Still not working :(

**Comment by aksonov** [comment]
@DClark5218 could you make sure that 0.26.1 is used for react-native-experimental-navigation ?

**Comment by cridenour** [comment]
I'm going to close this due to inactivity. If this continues to be a problem, please let us know and we will re-open the issue. If this is a question about using the library, head over to the [Gitter Chat](https://gitter.im/aksonov/react-native-router-flux) for live help!
