### ISSUE TITLE
Custom Tab Bar

### ISSUE THREAD

**Issue by vinceprofeta** [aksonov/react-native-router-flux#816]
In the latest build I cant figure out how to render a custom tab bar component? Does anyone have an example?

**Comment by 281330** [comment]
do you have some example code?  Just asking, that way if there is something obvious.  :)

**Comment by aksonov** [comment]
@vinceprofeta Just check built-in TabBar and implement yours one in the same way.

**Comment by vinceprofeta** [comment]
@aksonov would my custom tabsBar be passed into the parent scene as a footer prop?
```
<Scene key="home" footer={CustomFooter} tabs={true} >
```

**Comment by cridenour** [comment]
After forking src/TabBar.js to a component, just pass that in as `component={CustomTabBar}`.
