### ISSUE TITLE
Redirecting actions based on if/else generates error

### ISSUE THREAD

**Issue by jw84** [aksonov/react-native-router-flux#82]
I gitcloned and modified the Example app to check the state if the user is logged in or not.

If !this.state.loggedIn then redirect to the login route. However this generates a "Cannot read property 'getCurrentRoutes' of undefined" error

![image](https://cloud.githubusercontent.com/assets/48764/11867364/7a279118-a465-11e5-9325-f410834daf88.png)

![image](https://cloud.githubusercontent.com/assets/48764/11867922/3b708e1c-a469-11e5-8133-a37bbf114f97.png)

But if I remove the !this.state.loggedIn and simply check for this.state.loggedIn === true then the operation works and the Action is kicked off

Weird, can someone help?

Code here: https://github.com/jw84/routerDemo

**Comment by andreasbhansen** [comment]
Well, I don't think you're supposed to call the route name as a function like you're doing here:
```javascript
if (!this.state.loggedIn) {
  Actions.login();
}
```

... but rather like this:
```javascript
if (!this.state.loggedIn) {
  Actions.login;
}
```

No idea if that'll work, but you'll get rid of the error message.

**Comment by aksonov** [comment]
@andreasbhansen , not Actions.login is function, so you need to call that function with data passed to next scene. I will look at this issue when i will have time.

**Comment by andreasbhansen** [comment]
@aksonov Ah - ok, thanks!

**Comment by aksonov** [comment]
@jw84 Could you check with latest version?

**Comment by aksonov** [comment]
Closing for now
