### ISSUE TITLE
Unmet Peer Dependency from latest version of this library

### ISSUE THREAD

**Issue by KishPatel1996** [aksonov/react-native-router-flux#822]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.26.16
- react-native v15.0.2

UNMET PEER DEPENDENCY react@^15.1.0

Upgrading react breaks react-native as well.

**Comment by xvalentino** [comment]
I upgraded to react-native@0.27.0 after upgrading react and things work now.

**Comment by KishPatel1996** [comment]
That seemed to fix things.  Thanks!
