### ISSUE TITLE
document action types (pop,jump,refresh etc)

### ISSUE THREAD

**Issue by talarari** [aksonov/react-native-router-flux#829]
popTo
  pop
  jump
  refresh
  focus

couldn't find any doc to explain the behavior of these actions, could you please add a doc or answer here?

**Comment by rturk** [comment]
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md

**Comment by manask88** [comment]
I don't think the link helps too much. Some actions like pop or push may be obvious. But I am having a hard time trying to differentiate jump vs replace for example. What about back vs backaction?. Would be nice to document how each of these actions make a change in the navigation stack

**Comment by huchenme** [comment]
@rturk there is no documentation of `pop` in the link, and I have seem some examples using `popTo` but not in the link as well. In addition, it is really confusing of how to use, and what are the differences between different actions,

for example, what is the difference between `Actions.pop({ type: ActionConst.RESET })` and `Actions.popTo('home')`?  is `Actions.popTo('home')` and `Actions.home({ type: 'pop' })` the same thing?
