### ISSUE TITLE
Overlaying the nav bar

### ISSUE THREAD

**Issue by TangRufus** [aksonov/react-native-router-flux#83]
I am using ~~[react native drawer](https://github.com/root-two/react-native-drawer)~~ [react native side menu](https://github.com/react-native-fellowship/react-native-side-menu) to make a side menu.
The nav bar is always on top, covering the menu view.

Is there any way to: 
 - move nav bar aside (along with the main content view), or
 - let side menu rendered on top of nav bar (seems react native doesn't support z-index)?

Thanks!

**Comment by TangRufus** [comment]
To clarify, i am facing the same issue as react-native-fellowship/react-native-side-menu#72

**Comment by aksonov** [comment]
So it seems to be not issue of this component?
