### ISSUE TITLE
typescript definitions broken?

### ISSUE THREAD

**Issue by AlmaasAre** [aksonov/react-native-router-flux#830]
### Version
- react-native-router-flux v3.26.24
- react-native v0.26.3
- react v15.0.2

type definitions:
- registry:dt/react#0.14.0+20160602151522

### Expected behaviour

Typescript definitions should work

### Actual behaviour

.. doesn't work. The type definitions tries to use properties on React that aren't defined in the react-definition as far as i can see.

![image](https://cloud.githubusercontent.com/assets/1777366/16110776/be47e7d8-33af-11e6-8068-87e1b4d166d0.png)

**Comment by charpeni** [comment]
Will be fixed by #831.

**Comment by xirc** [comment]
I had same problem.
Versions:
* react-native-router-flux v3.30.0
* typing: "react-native": "registry:dt/react-native#0.19.0+20160501140141"

I've fixed the problem by #831.
@AlmaasAre Could you try using it?

**Comment by charpeni** [comment]
I'll close this issue since it should be fixed now, let me know if it's not.
