### ISSUE TITLE
set Icons in tabbar 

### ISSUE THREAD

**Issue by gmchaturvedi1** [aksonov/react-native-router-flux#832]
Dear Friends,

how to set Icon in tab and  set tabbar to just after navbar.

thanks & Regards
G M chaturvedi

**Comment by cridenour** [comment]
Hey @gmchaturvedi1, your best bet for support like this is in the [Gitter Chatroom](https://gitter.im/aksonov/react-native-router-flux). Feel free to open a new issue if you find a bug in the library.

**Comment by EngineerDiab** [comment]
@gmchaturvedi1 Did you figure out how to do it?

**Comment by infacq** [comment]
@gmchaturvedi1 yeah figure it already?
