### ISSUE TITLE
How to get length of router?

### ISSUE THREAD

**Issue by JosephkimOS** [aksonov/react-native-router-flux#833]
### Version

"dependencies": {
    "react": "^15.1.0",
    "react-native": "^0.27.2",
    "react-native-drawer": "^2.2.2",
    "react-native-router-flux": "^3.30.0",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "react-native-button": "github:ide/react-native-button"
  }
### Expected behaviour

I tried current path and length with "currentRouter" but, got "undefined"

here is capture of "Actions" in my component
![screen shot 2016-06-16 at 6 24 08 pm](https://cloud.githubusercontent.com/assets/13225072/16138175/b5cab88e-33ef-11e6-8622-c9a2f701de87.png)

**Comment by xvalentino** [comment]
What exactly do you expect to get? The number of routes you have?

One idea I have for this is maybe keep track of the stack in redux?

**Comment by JosephkimOS** [comment]
I expect get size of routes or list of routes.

Do I have to stack or track by myself?

**Comment by robotomeister** [comment]
I have a tangentially related question, is there a way to get the size of the stack before we do an Actions.pop()?

**Comment by guilhermebruzzi** [comment]
In my case i want the type PUSH_OR_POP on transitions. And i need to know the size of the stack to know if the action was a pop (and how many scenes it poped) or a push of a new scene.

**Comment by walkertong** [comment]
Same question

**Comment by duzliang** [comment]
+1
