### ISSUE TITLE
The nav bar and the tab bar block my scene

### ISSUE THREAD

**Issue by mickeyinfoshan** [aksonov/react-native-router-flux#836]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.0
- react-native v0.25.1
### Expected behaviour

My scene shouldn't be blocked by the `navbar` and the `tabbar` when no `sceneStyle` is specified.
### Actual behaviour

My scene is blocked so I have to specify the `sceneStyle`.
### Steps to reproduce
1. Just use the example and change the style a little

**Comment by KishPatel1996** [comment]
A cheap hack I use is to pad the view by `Navigator.NavigationBar.Styles.General.TotalNavHeight`.

**Comment by 281330** [comment]
There is a small snippet in the example app that handles this.

**Comment by 281330** [comment]
```
if (computedProps.isActive) {
    style.marginTop = computedProps.hideNavBar ? 0 : 64;
    style.marginBottom = computedProps.hideTabBar ? 0 : 50;
  }
```

**Comment by rturk** [comment]
Hi @mickeyinfoshan please be more specific. Ideally share a screenshot. Overall please explain what do you mean by `block`?

**Comment by charpeni** [comment]
I confirm this issue, I just ran on it. 

I'll give more details soon.

**Comment by charpeni** [comment]
I don't know if it what's @mickeyinfoshan means.

If you remove `hideNavBar` from the Example ([here](https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L96)), you won't be able to swipe back with Android because the scene will be blocked in transition.

Any ideas?

cc @aksonov @rturk @sarovin

**Comment by leoi11** [comment]
@charpeni I ran into the problem @mickeyinfoshan is having, and it's different from what you're describing here:
> If you remove hideNavBar from the Example (here), you won't be able to swipe back with Android because the scene will be blocked in transition.

The problem I run into is that the navbar seems to be overlaid on the scene so if I display something at the top of the view it will potentially be covered by the navbar.
