### ISSUE TITLE
Back button color 

### ISSUE THREAD

**Issue by Shakarang** [aksonov/react-native-router-flux#840]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.0
- react-native v0.27.2

### Expected behaviour

I'm trying to change the arrow color like the screenshot below. However, I can't set a color on each scene. I can only do it on the root Scene. Am I missing something or it is a bug ?

![Img](http://i.imgur.com/VIfuSRO.png)

It works with this code when I'm setting it to the root scene. 
```
<Router >
   <Scene key="root" titleStyle={{ color: 'red' }} barButtonIconStyle={{ tintColor: 'green' }}>
      <Scene key="connexion" component={Connexion}
         hideNavBar={false} title="Connexion" initial={true}/>
      <Scene key="signup" component={Signup} hideNavBar={false}
         title="PageOne" navigationBarStyle={NavBarStyle.bar.darkNavigationBar}
      />
   </Scene>
</Router>
```

I would like to set each scene style separately (like this code). Is it even possible
```
<Router >
   <Scene key="root" titleStyle={{ color: 'red' }}>
     <Scene key="connexion" component={Connexion}
       hideNavBar={false} title="Connexion" initial={true}/>
     <Scene key="signup" component={Signup} hideNavBar={false}
       title="PageOne" navigationBarStyle={NavBarStyle.bar.darkNavigationBar}
       barButtonIconStyle={{ tintColor: 'green' }}
      />
    </Scene>
</Router>
```

**Comment by 281330** [comment]
In each Scene, you can give `backButtonTextStyle={{ ... }}`

**Comment by Shakarang** [comment]
I've tried to add it in the scene with these properties : 

- color
- backgroundColor
- tintColor

But it doesn't work..

**Comment by sercanov** [comment]
Would you try the following @Shakarang 

`leftButtonIconStyle = {{ tintColor:'red'}}`

**Comment by JaiNatha** [comment]
You can always drill down into:
node_modules/react-native-router-flux/src/back_chevron.png

and edit "back_chevron.png" however you'd like.

**Comment by JaiNatha** [comment]
Oh sorry, I misread your initial comment, just realized you're trying to set it for each scene.

leftButtonIconStyle={{ tintColor: 'green' }} is indeed the way to go

**Comment by crazy9code** [comment]
This is not working in my project.    
 <Scene ... leftButtonIconStyle = {{ tintColor:'red'}} />
Version 
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.3",
    "react-native-router-flux": "^4.0.0-beta.12"

need to update back Icon color.

**Comment by jaimecorrea** [comment]
Same issue, on RNRF 4.0.0-beta.15 is not working leftButtonIconStyle, neither barButtonIconStyle

**Comment by jordenchang55** [comment]
```html
<Scene
    key="root"
    headerTintColor="#000"
>
```
This works for me on RNRF@4.0.0-beta.16

**Comment by Frexuz** [comment]
`headerTintColor` seems correct, but what about size? or, if we want a different back-icon?

**Comment by jordenchang55** [comment]
Check [here](https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options) for styling your nav bar.
If you want to change icon, you can use ```leftButtonImage``` prop in scene.

**Comment by Frexuz** [comment]
```
                      <Scene
                        key='HomePage'
                        component={HomePage}
                        renderBackButton={<Icon name='chevron-left' />}
                      />
```

like this?

> `renderBackButton` is not a function

**Comment by SSTPIERRE2** [comment]
@Frexuz This is an issue I'm wrestling with now as well. All I want is to use something like a package icon for the navigation buttons, rather than an image or text, but it seems we have to re-implement the on-touch functionality (most likely routing) ourselves for each scene (i.e. onRight/onLeft doesn't do anything if you choose to use renderBackButton/renderRightButton).

**Comment by kallayyash** [comment]
> headerTintColor="#000"

its worked me too

**Comment by pietropr** [comment]
> ```
> <Scene
>     key="root"
>     headerTintColor="#000"
> >
> ```
> 
> This works for me on RNRF@4.0.0-beta.16

Its worked for me too. RN 0.59
