### ISSUE TITLE
Transitions problem

### ISSUE THREAD

**Issue by Shakarang** [aksonov/react-native-router-flux#842]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.0
- react-native v0.27.0
### Expected behaviour

In your example, when going to tab bar, we can see the navigation drawer during the transition, is it normal? Is there a way to hide it?

Second, when I swift left to toggle the navigation drawer, it goes back to the previous view. Is there a props to handle it?

![Imgur](http://i.imgur.com/qIujuor.gif?1)

**Comment by agumack** [comment]
I test on IOS and android. Transitions slow :(

**Comment by sarovin** [comment]
I have a problem with transition on Android.
RN@0.28
RNRF@3.20.2

![transition android](https://cloud.githubusercontent.com/assets/5980398/16298601/8b8c3fc4-3936-11e6-929b-19ce8ea81e7d.gif)

**Comment by andrispraulitis** [comment]
@sarovin @Shakarang I have both of these issues too..

RN@0.28
RNRF@3.30.0

**Comment by heat** [comment]
react native 0.28 rename the experimental Navigator name, so is RNRF already adapt that ?

**Comment by sarovin** [comment]
RNRF@3.30.0 use a fork of experimental navigator from RN@0.26

**Comment by ajoshdee** [comment]
I'm getting Native Module cannot be null on RN0.28. Help needed.

**Comment by srdjan-kolosek** [comment]
@sarovin Have you maybe solved the transition problem on android somehow?

**Comment by blackxored** [comment]
Transitions are notably slow on my end too (iOS). On device, not simulator.

**Comment by rturk** [comment]
@ajoshdee This package uses a fork for Nagiator Experimental, please check docs.

**Comment by tquiroga** [comment]
Same problem.
It's still happening to me 2 years later with RN 0.56 and RNRF@4.0.0-beta.27.
