### ISSUE TITLE
Possible to define Navigator Stack 'type' in Action call?

### ISSUE THREAD

**Issue by praveenperera** [aksonov/react-native-router-flux#844]
- react-native-router-flux v3.26
- react-native v0.26

Is it possible to pass in the way I want the navigator to handle the stack in the Action call?

For example calling `Action.index({  type: 'push' })` would render the welcome component by pushing it to the stack. However calling `Action.index( type: 'replace' })` would render the welcome component but would replace instead of pushing.

Basically I would like to control how the Navigator stack is controlled on the link level instead of the scene level.

**Comment by cridenour** [comment]
That's exactly how it currently works - have you tried it and it's not working?

**Comment by praveenperera** [comment]
I tried it put then it seems to call the action, so if I pass it with 'push' you can see the stack animation for push and then it replaces it. I will try again and post a GIF. Thanks
