### ISSUE TITLE
Can't implement react-native-drawer : 'unique key should be defined'

### ISSUE THREAD

**Issue by Krestone** [aksonov/react-native-router-flux#845]
### Version
"react-native": "^0.26.2",
 "react-native-router-flux": "^3.26.5"

Hi! I am trying to combine the router with react-native-drawer, following in the footsteps of Issue #92 and #242 . However even though I am trying to implement the same method of nested routes I am getting this error   
![error](https://cloud.githubusercontent.com/assets/14961405/16267601/4ccb9274-3893-11e6-9055-a67172714952.jpg)

At this point Im completely lost and would appreciate any guidance, Thanks!

 Here is my code 

`
   ```
  render() {
    
		return (
			<Router name='root' >
         <Route component={LoginView} key='login' name='Login' initial={true} title="Welcome"   hideNavBar={true} />
          <Route component={SecureView} key='secureview' name='SecureView'  />

          <Route component={Dashboard} key='dashboard' name='main' hideNavBar={false} type='reset' >
             <SideDrawer>
                <Router sceneStyle={styles.routerScene} navigationBarStyle={styles.navBar} titleStyle={styles.navTitle} renderLeftButton={this.renderMenuButton}>
                  <Route component={ReservationList} key="reservationlist" name='ReservationList'>  </Route>
                </Router>
             </SideDrawer>
          </Route>

    </Router>
		)
	}`
```

In which dashboard is the page with the side menu, and reservationlist is the Action which I want to take from within the drawer

**SideDrawer.js:**

```
import React, { Component, PropTypes } from 'react'
import Drawer from 'react-native-drawer'
import SideDrawerContent from './SideDrawerContent'



export default class SideDrawer extends React.Component {
	constructor(props){
		super(props);

		this.ReservationList=HotelAdminService.ReservationList.bind(this);
	}
  render() {
    return (
      <Drawer
        type="overlay"

        content={<SideDrawerContent />}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
				open={true}
        closedDrawerOffset={-3}
        styles={{ drawer: {backgroundColor: '#ffffff'} ,main: { paddingLeft: 3 }}}
        tweenHandler={(ratio) => ({ main: { opacity: (2 - ratio) / 2 } })}
      >
        {React.Children.map(this.props.children, c => React.cloneElement(c, {
          route: this.props.route
        }))}
      </Drawer>
    )
  }
}


SideDrawer.propTypes = {
	children: PropTypes.node,
	route: PropTypes.object,
}.

```

**SideDrawerContent.js:**

```
import React, { View, Component, PropTypes, Text, TouchableHighlight } from 'react'
import { Actions } from 'react-native-router-flux'

import SideDrawer from './SideDrawer.js'
var HotelAdminService = require('./services.js');

export default class SideDrawerContent extends Component {


	constructor(props){
		super(props);
		this.ReservationList=HotelAdminService.ReservationList.bind(this);


	}

	static contextTypes = {
		drawer: PropTypes.object.isRequired,
	};

	render() {
		const { drawer } = this.context
		return (
			<View>
			<Text style={styles.title}>{this.props.hotel} Dashboard</Text>
			<TouchableHighlight onPress={()=>HotelAdminService.ReservationList(this.props.hotel)} style={styles.button}>
					<Text style={styles.buttonText}>Reservations</Text>
			</TouchableHighlight>
			</View>
		)
	}
}

SideDrawerContent.propTypes = {
	drawer: PropTypes.object
}

const styles ={
  container: {
      flex:1,
      padding: 30,
      marginTop: 65,
      alignItems: "stretch"
  },
  title:{
    fontSize:20,
    textAlign: 'center',
  },
  button: {
      height: 36,
      flex: 1,
      backgroundColor: "#555555",
      borderColor: "#555555",
      borderWidth: 1,
      borderRadius: 8,
      marginTop: 10,
      justifyContent: "center"
  },
  buttonText: {
      fontSize: 18,
      color: "#ffffff",
      alignSelf: "center"
  },
}

```

**Comment by cridenour** [comment]
That code is from version 2.x of the library. Please see the Example project, specifically https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js and https://github.com/aksonov/react-native-router-flux/blob/master/Example/components/NavigationDrawer.js on how to do this with 3.x.

**Comment by manishk-sdei** [comment]
![untitled-1](https://user-images.githubusercontent.com/29279133/27220759-e8d30280-52a3-11e7-8e17-376474f91c51.png)

my router is working but i want it come from second page home but when i added code for this its shows error


here my router code:

import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, Image, TextInput, Button, Navigator, TouchableOpacity} from 'react-native';
import { Router, Route, Schema, Actions, Scene} from 'react-native-router-flux';
import login from './main/login';
import home from './main/home';
import flexcontent from './main/flexcontent';
import SideDrawer from './main/SideDrawer';
import Screen1 from './main/Screen1';
import Screen2 from './main/Screen2';


export default class AwesomeProject extends Component {
renderMenuButton = () => {
		return (
			<TouchableOpacity
				style={styles.leftButtonContainer}
				onPress={() => this.drawer.open()}
			>
				<Image source={require('./main/images/menu.png')} style={{height: 24, width: 24}} />
				
			</TouchableOpacity>
		)
	};

	renderBackButton = () => {
		return (
			<TouchableOpacity
				style={styles.leftButtonContainer}
				onPress={Actions.pop}
			>
				<Image
					source={require('./main/images/back.png')}
					style={{height: 24, width: 24}}
				/>
			</TouchableOpacity>
		)
	};
  render() {
    return (
	<Router name='root'>

		<Schema
		 name='boot'
		 sceneConfig={Navigator.SceneConfigs.FloatFromRight}
		 hideNavBar
		 type='replace' // When type='replace' is existing Actions.pop never work
		/>

		<Route name='Login' key='login' component={login} schema='boot' initial title="Welcome" />
		

    	<Route name='Drawer' hideNavBar type='reset'>
    		<SideDrawer ref={c => { c ? this.drawer = c.drawer : this.drawer }}>
			 {
			  /*Nested Routes are used for to manage the navbar cases (Route[Home] \ Router \ Route[Home_] )
			  React-Native-Reouter-Flux actions use the route names.*/
			 }

			  <Router name='drawerRoot'
			   sceneStyle={styles.routerScene}
			   navigationBarStyle={styles.navBar}
			   titleStyle={styles.navTitle}
			  >
			   <Schema
				name='home'
				sceneConfig={Navigator.SceneConfigs.FloatFromRight}
				hideNavBar={false}
				renderLeftButton={this.renderMenuButton}
			   />
			   <Schema
				name='interior'
				sceneConfig={Navigator.SceneConfigs.FloatFromRight}
				hideNavBar={false}
				renderLeftButton={this.renderBackButton}
			   />

			   <Route name='home' key='home' component={home} schema='home' title='Home' />
			   <Route name='Screen1' key='Screen1' component={Screen1} schema='interior' title='Screen1' />
			   <Route name='Screen2' key='Screen2' component={Screen2} schema='interior' title='Screen2' />

      </Router>
     </SideDrawer>
    </Route>
</Router>
	
    );
  }
}

const styles = StyleSheet.create({
	
	leftButtonContainer: {
		paddingLeft: 15,
		paddingRight: 20,
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
	},
})
