### ISSUE TITLE
Jump to an existing route?

### ISSUE THREAD

**Issue by jamesfzhang** [aksonov/react-native-router-flux#85]
Hey @aksonov thanks for creating this router. I've tried Navigator, react-native-router, gb-native-router, and this is definitely the best! Is there a `jumpTo` functionality like Navigator does? It would transition to an existing scene without unmounting or pushing a new version of the scene onto the route stack. Thanks.

**Comment by MITDelian** [comment]
Hey @jamesfzhang this is what the type of 'switch' is used for. You can check out in the example how we use it for tabs, however this can be used for any route really. Just define a route as so:

`<Route name="foo" type="switch"/>`

**Comment by MITDelian** [comment]
Feel free to reopen if you have further questions

**Comment by jamesfzhang** [comment]
@MITDelian Thanks, didn't realize that's what "tab" meant!

**Comment by MITDelian** [comment]
Yes! It's referencing the schema defined up above. If you are having a bunch of routes that have this witching behavior I recommend a schema so you can define other global attributes on said routes if needed

**Comment by jamesfzhang** [comment]
@MITDelian I tried using type "switch" but I don't want the navbar to appear. I set `hideNavBar` but it still appears?

```js
<Router hideNavBar={true} style={styles.container}>
  <Schema name='default' sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
  <Route name='home' component={HomeScreen} initial={true} title='Home' type='replace'/>
  <Route name='tracks' component={TracksScreen} title='Tracks' type='switch'/>
  <Route name='artists' component={ArtistsScreen} title='Artists' type='switch'/>
  <Route name='albums' component={AlbumsScreen} title='Albums' type='switch'/>
</Router>
```

<img width="371" alt="screen shot 2015-12-21 at 10 00 21 am" src="https://cloud.githubusercontent.com/assets/2057670/11937533/b22f52c8-a7c9-11e5-95f5-aa8d92ddfa19.png">

**Comment by aksonov** [comment]
Does parent router hide navbar as well?

**Comment by jamesfzhang** [comment]
@aksonov That is the top level Router.

**Comment by jamesfzhang** [comment]
@aksonov @MITDelian I added some logging to this library's `render` method to log the value of `hideNavBar` in between scene transitions. As you can see the value is `true` after a push route, which is expected but becomes `undefined` after a switch route.

<img width="137" alt="screen shot 2015-12-22 at 5 06 45 pm" src="https://cloud.githubusercontent.com/assets/2057670/11969449/72b890b8-a8ce-11e5-94cb-bcba69089365.png">

**Comment by vitalets** [comment]
+1 having trouble with unneeded navbar when switch is enabled.
