### ISSUE TITLE
APK building fails with 3.30.0 on windows

### ISSUE THREAD

**Issue by asafratzon** [aksonov/react-native-router-flux#852]
### Version
- react-native-router-flux v3.30.0
- react-native v0.28.0

Developing on windows, not sure if this happens on mac.

Before upgrading to the version above, I was using 3.26.0 and 0.26.2 and my apk was built just fine.
Whenever I try to build an APK by running 'cd android && ./gradlew assembleRelease' (see [react-native docs](https://facebook.github.io/react-native/docs/signed-apk-android.html#generating-the-release-apk)), build fails with the following message:

> * What went wrong:
> Execution failed for task ':app:processReleaseResources'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:/../AppData/Local/Android/sdk/build/tools/23.0.1/aapt.exe'' finished with non-zero exit value 1

When I build it with '--info' flag the bug becomes clearer:

> Unknown source file : E:/.../android/app/build/intermediates/res/merged/release/drawable-mdpi/**node_modules_reactnativerouterflux_node_modules_reactnativeexperimentalnavigation_assets_backicon.png: error: Invalid filename**.  Unable to add.

My guess is that once react-native-router-flux is using the cloned experimental navigator, the directories hierarchy becomes too deep, and this creates this monstrous file name that is seemingly invalid to the aapt.exe.
 
Still If I run the app in GenyMotion ('react-native run-android'), build succeeds and the app works as expected.
For now I went back to previous versions (3.26.0 and 0.26.2).
In two weeks I should have a macbook pro so I will check how it goes over there and update here.

**UPDATE**: this issue doesn't reproduce on Macbook Pro (OSX) and APK is built just fine.

**Comment by Lukkub** [comment]
I'm trying currently to build app and have exactly the same Error.

> :app:processReleaseResources
Unknown source file : /Users/lukaszkubica/Desktop/pplTests/ppltestsnative/android/app/build/intermediates/res/merged/release/drawable-mdpi/node_modules_reactnativerouterflux_node_modules_reactnativeexperimentalnavigation_assets_backicon.png: error: Invalid filename.  Unable to add.
:app:processReleaseResources FAILED

I'm using:
- react-native-router-flux v3.30.0
- react-native v0.27.2

I didn't use any previous versions and in general this is my first try to build an App with ReactNative so I can not compare this fail.

**Comment by rturk** [comment]
@asafratzon Can you initiate the packager with `nmp start` also can you run this app in the simulator?

**Comment by asafratzon** [comment]
@rturk all 'npm start' does is it runs the React Packager, which is already taken care of by 'react-native run-android' in react-native 0.26.2 and 0.28.
In any case I just tried the whole setup again and this time I faced no slow transition in the simulator but still building the APK fails with the same error I mentioned.

**Comment by cridenour** [comment]
What if you install the react-native-experimental-navgation library directly so it's not as nested? If it truly is a filename length issue, that might help.

**Comment by asafratzon** [comment]
@cridenour I just now moved to MacBook Pro (which is awesome btw) so I can confirm that this issue doesn't occur on OSX.
What you offer might help for those on Windows but wouldn't it require to modify also react-native-router-flux so it wouldn't keep cloning react-native-experimental-navigation?
Thanks for your comment.

**Comment by cridenour** [comment]
@asafratzon As long as you install the same version, npm won't re-install it as a submodule.

I'm going to close for now - if you are having this issue on windows, please see my suggestion above!

**Comment by asafratzon** [comment]
@cridenour cool, thanks!

**Comment by DVassilev** [comment]
@cridenour I have this issue on OS X and attempted to as suggested above but it has not changed the filename and fails to fix this issue. Any work around?

**Comment by joelcloralt** [comment]
@DVassilev I was having the same issue but I was able to assemble the release by deleting the `/android/app/build` directory and letting it create the whole thing again. 

I also changed the line that calls that icon here: https://github.com/aksonov/react-native-experimental-navigation/issues/1#issuecomment-235678427

**Comment by Luckygirlllll** [comment]
I have the same error. deleting /android/app/build didn't help
