### ISSUE TITLE
Component Props are not passed to renderNavigationBar method

### ISSUE THREAD

**Issue by willmcclellan** [aksonov/react-native-router-flux#853]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.26.24
- react-native v0.26
### Expected behaviour

the `renderNavigationBar` static method on a scene component should receive the props of the component instance. E.g, the component is connected to redux store and you have access to the props of that component inside `renderNavigationBar` to affect the display of the NavBar
### Actual behaviour

Only scene props are passed to `renderNavigationBar`
### Steps to reproduce
1. Create scene and give it a component which is connected to redux state
2. Add `renderNavigationBar` static to the component with `props` argument
3. Log out `props` in `renderNavigationBar` - No custom component props are available

**Comment by yutingjin** [comment]
i met the same situation of this method, i cannot dispatch action or update state, due to it is only a static method of component...

**Comment by AlexeyToksarov** [comment]
@willmcclellan @yutingjin  I'm not sure whether this is a correct solution, but you could pass necessary props with `Actions.refresh` method:

```
static renderNavigationBar(props) {
  props.propName
}

componentWillMount() {
  Actions.refresh({propName: this.propName});
}
```

**Comment by trongan** [comment]
Hi,
Let assign YourComponent.renderNavigationBar = YourComponent.renderNavigationBar bellow component class. It work ok.
