### ISSUE TITLE
_reactNative.Platform.select is not a function<unknown NavBar.js>

### ISSUE THREAD

**Issue by AshokICreate** [aksonov/react-native-router-flux#854]
### Version
Tell us which versions you are using: 
- react-native-router-flux v3.?.?
"react-native-router-flux": "^3.22.23"

- react-native v0.?.?
react-native-cli: 0.2.0
react-native: 0.25.1

### Expected behaviour
I should be able to run my project.

### Steps to reproduce
1. npm install
2. cmd + r from your xcode or react-native run-ios
3. result => _reactNative.Platfrom.select is not a function._

**Comment by nemosdo** [comment]
your react-native-router-flux's version is not '3.22.23', may be '3.30', you can see it in 'node_modules/react-native-router-flux/package.json'

**Comment by Roconda** [comment]
I agree to @nemosdo. I think your react-native-router-flux version is too new for RN 0.25.1

**Comment by cridenour** [comment]
0.25 was never officially supported, but the latest versions of RNRF provide the navigation code inline.

**Comment by rturk** [comment]
Hi @AshokICreate your project should work if you upgrade RN. If you don't have any further questions please close this.

**Comment by masterkrang** [comment]
@AshokICreate same problem here. started yesterday.

RN 0.25.1

I'm trying to upgrade to RN 0.28 will let you know how it goes

**Comment by whitmanc** [comment]
@AshokICreate I haven't tried upgrading react-native, but I am using RN `0.25.1` and using react-native-router-flux `3.3.0` fixes it for me

**Comment by whitmanc** [comment]
@cridenour @aksonov How can we find RN version compatibility in this project? I feel like this problem is related to the fact that compatibility isn't clear. I tried looking in the package.json, but that doesn't show RN `0.28.0`: https://github.com/aksonov/react-native-router-flux/blob/master/package.json#L66

Excuse if the answer is obvious, still becoming versed with npm

**Comment by cridenour** [comment]
@whitmanc The previous versions of this project relied on specific versions of RN (3.26 with 0.26, etc). Since 3.30, it works with all versions of RN. 

Moving forward, we just ask everyone work with the latest code :)

**Comment by whitmanc** [comment]
@cridenour tx for the reply & got it. Keep up the good work!

**Comment by AshokICreate** [comment]
@nemosdo @Roconda yes you both are right it is "version": "3.30.2". i ll update my RN to 0.28 and let you know.

**Comment by cridenour** [comment]
@AshokICreate Did upgrading end up fixing your issue?

**Comment by tsyirvo** [comment]
@AshokICreate It's because the `Platform.select` API is only available on RN since 0.26 and you're using 0.25.1.
