### ISSUE TITLE
Navigation Bar titleStyle doesn't override fontFamily on Android

### ISSUE THREAD

**Issue by andrispraulitis** [aksonov/react-native-router-flux#855]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.0
- react-native v0.28.0

<img width="824" alt="screen shot 2016-06-24 at 19 41 49" src="https://cloud.githubusercontent.com/assets/8721800/16347313/eecf5072-3a43-11e6-8694-30bab46dea40.png">

As you can see that the custom font works on both iOS and Android on title "London Summer Party", but in NavBar only iOS works.

**Comment by rturk** [comment]
Is your font installed in Android? (including all formats Bold/Italic) I had a similar issue with android. For example IOS will default to the same family font if *bold* or *italic* are not installed, however Android will default to a System font.

**Comment by mrnahidtalukder** [comment]
I'm having the same issue right now

**Comment by mrnahidtalukder** [comment]
I just figured it out, you have to include a fontWeight with it as well, if you set it to fontWeight: 'normal' along with fontWeight: 'YOUR FONT', that worked for me.

**Comment by Cadiac** [comment]
+1 Having the same issue, but workaround provided  by mrnahidtalukder solved the issue for now.

**Comment by rturk** [comment]
@andrispraulitis do you have any further comments? can you please close this?
