### ISSUE TITLE
How to reset every Scene?

### ISSUE THREAD

**Issue by ms88privat** [aksonov/react-native-router-flux#857]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.0
- react-native v0.26.2

Is it possible to reset the complete state of the router?
I want that my components of the scenes are mounting again.

The use case is, that I want to reset it after a user is logging out.

**Comment by ms88privat** [comment]
I often do things like "if componentDidMount and data is not available, load something". But this doesn't work anymore, because I reset my Redux-Store (so no data available) but the components are not going to mount again because the Router still exist.

Maybe there should be an option on the new switch component if it should unmount the other case

**Comment by cridenour** [comment]
When you're calling the page after logging out use `Actions.KEY({type: "reset"})`. We use this for logging out without issue.

**Comment by ms88privat** [comment]
@cridenour Thanks, but this doesn't work for me. Tried to reset every scene I got, but my last selected Tab is still active and will not mount again.

**Comment by rturk** [comment]
@cridenour I have a global wrapper that completely un-mounts my hole app when the user logs out, including redux state cleanup.
I like it since its a simple and elegant solution, with extra benefit that its smart to release used resources. 

The F8 App was my inspiration:
https://github.com/fbsamples/f8app/blob/master/js/F8App.js#L80

**Comment by ms88privat** [comment]
@rturk Thanks for the hint again. Now I gave this solution a second thought and it should work with two Routers too.

Because in my case a simple Login Screen isn't good enough, I need routing there too. That's why it is integrated in the current Router setup.

**Comment by rturk** [comment]
@ms88privat in this case I recommend you to use redux (or other state management framework of your preference). 
What I don't recommend is use two (or more!) routers.. this can be inefficient (from a memory and CPU perspective)..

**Comment by ms88privat** [comment]
@rturk I'm using redux. But this is not the problem. What I need is something like this:

```jsx

render() {
  return this.props.authenticated ? this.renderHome() : this.renderLogin();
}

renderHome() {
 return <Router1 />;
}

renderLogin() {
  return <Router2 />;
}
```

I can't use the Switch Component of Router because it will keep both Scenes in Memory (which will prevent the componentDidMount Events from happening again also)

Any solution for this Problem? I think I have to use the pure Navigator for the second Router instead of the Router from Router-Flux.

**Comment by cridenour** [comment]
AFAIK, if you navigate to a page via `type=reset`, then any component added to the stack after that will have its componentDidMount action called.

**Comment by ms88privat** [comment]
@cridenour let me try that again. Maybe I run into the naming conflict with the new Action Names

**Comment by ms88privat** [comment]
@cridenour thanks. Looks like it is working. I think I also did not use type=reset correctly the last time. Now I put it directly on my HomeView and LoginView as prop with the Action constant

**Comment by ms88privat** [comment]
@cridenour But its still not perfect. If you could have two Routers it would be better. Right now the View is in memory and still rendered in the Background! It's not good for older devices and the other aspect is, that the Scroll Position is preserved (even after RESET). And the scroll position is really far on the bottom because of the login button :(

**Comment by ms88privat** [comment]
@cridenour this solution doesn't work. The View itself will mount again. But not my Components inside the View. Because it is still rendered.

**Comment by ms88privat** [comment]
Ok, I got it to work! I will create the pull request now :)

**Comment by joenoon** [comment]
@ms88privat I did this for login and getting a full router reset.  I wonder if this would work for your case?

```
<Router key={`${user_id_or_session_key_or_auth_key_or_anon}_route`} ...>{...}</Router>
```

By having a key that changes when the logged in user changes... ie. anonymous to user1 to anonymous to user2, the whole component and children will be unmounted and re-created when that key changes.

**Comment by ms88privat** [comment]
@joenoon omg, didn't know about the key thing. With this it should be possible to render two Routers (like I mentioned above).

But my PR for the Switch component is still usefully. So you can have only one Router and have the benefit of unmounted Scenes while switching.
