### ISSUE TITLE
assemble cannot package backicon.png.  Looks like file name is wrong, missing delimiters.

### ISSUE THREAD

**Issue by cyphire** [aksonov/react-native-router-flux#859]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.2
- react-native v0.28.0

### Expected behaviour

Assembled a release: gradlew assembleRelease
Expected it to build my .apk for testing.

### Actual behaviour
Build failed:

[C:\Users\bcanin01\workspace\react\bs1\android]gradlew assembleRelease > out.txt
Unknown source file : C:\Users\bcanin01\workspace\react\bs1\android\app\build\intermediates\res\merged\release\drawable-mdpi\node_modules_reactnativerouterflux_node_module
s_reactnativeexperimentalnavigation_assets_backicon.png: error: Invalid filename.  Unable to add.

Did it lose some backslashes somewhere????

### Steps to reproduce

1. Just run my assembleRelease.  No problem in debug mode (as assets are not packaged...)
2.
3.

**Comment by asafratzon** [comment]
@cyphire I encountered the same issue, already reported in issue named "[APK building fails with 3.30.0 on windows](https://github.com/aksonov/react-native-router-flux/issues/852)". if you encountered this on Mac please add a comment there.

**Comment by cyphire** [comment]
Closing issue for asafratzon having same issue, please follow the thread above for this current issue...
