### ISSUE TITLE
Loading state

### ISSUE THREAD

**Issue by zelphir** [aksonov/react-native-router-flux#860]
### Version

- react-native-router-flux v3.30
- react-native v0.28

Is possible to create a loading state in overlay (with semi-transparent background, so it's possible to see the scene that triggered the loading)?

I'm playing with the modal but even if I add a transparent background I can't see the scene behind it. Am I doing something wrong?

Thanks

**Comment by zelphir** [comment]
Figured it out.... just follow the Example!

**Comment by believer** [comment]
@zelphir How did you go about this? I'm trying to get a transparent background as well, but can't seem to get it. I've managed getting my Scene like a modal but not the transparent part. Please share! 😄

**Comment by Daniellt1** [comment]
Same issue.
@zelphir, please share your code.
@believer, have you solved that?

**Comment by tioback** [comment]
@believer and @Daniellt1 , as @zelphir mentioned, just follow the [Example](https://github.com/aksonov/react-native-router-flux/tree/master/Example)
