### ISSUE TITLE
Pass state/props to onRight or onLeft (navbar)

### ISSUE THREAD

**Issue by zelphir** [aksonov/react-native-router-flux#864]
### Version
- react-native-router-flux v3.30
- react-native v0.28

Is it possible? how to do that?

for instance if I want to save a form using the navbar right button...

**Comment by jeroenbourgois** [comment]
I think this can be done, but not sure how. Right now I see that the `Connect` function is passed in...

**Comment by jeroenbourgois** [comment]
Any ideas on this?

**Comment by cridenour** [comment]
I think this is a great reason to use flux. React shouldn't be trying to share state or props when you can have a higher level store keep this information for multiple components to connect to and use.

**Comment by jeroenbourgois** [comment]
Exactly. I am using redux but i find no way to access or pass the store
there :(

**Comment by irisSchaffer** [comment]
Is there a way to access the store from within `onRight` / `onLeft`? We are looking into performing a `logout` and would need access to `dispatch`.

Another use case we've encountered is uploading a collection of files `onRight`. Since we don't have access to the props or the store though, we can't even check if we should already display the button or not. At the moment we simply added this functionality at the entry point of the next scene and redirect back if there are no files.

**Comment by ofermalbin** [comment]
Try this trick:

**Scene:**
<Scene key="members" component={Members} title="Members" onRight={(props) => props.onAdd && props.onAdd()} rightTitle="Add" />

**component:**
class Members extends React.Component {

  componentDidMount() {
    Actions.refresh({ onAdd: this.addMember.bind(this) });
  }

  addMember() {
    const { project_id } = this.props.params;
    Actions.memberadd( {params: {project_id: project_id}} );
  }

  render() {

    const { project_id } = this.props.params;
    
    return (
      <MembersList params={{project_id: project_id}} />
    );
  }
}

export default Members;

**Comment by ofermalbin** [comment]
try this trick:

**## Scene:**

```
<Scene key="members" component={Members} title="Members" onRight={(props) => props.onAdd && props.onAdd()} rightTitle="Add" />
```

**## Component:**

```
class Members extends React.Component {
    componentDidMount() {
        Actions.refresh({ onAdd: this.addMember.bind(this) });
    }

  addMember() {
    const { project_id } = this.props.params;
    Actions.memberadd( {params: {project_id: project_id}} );
  }

  render() {
    const { project_id } = this.props.params;
     return (
      <MembersList params={{project_id: project_id}} />
    );
  }
}

export default Members;
```

**Comment by cridenour** [comment]
I don't see why you can't access the store via `onRight` or `onLeft`. Since it's just a JavaScript function, everything available should be there - maybe there's a scoping problem in your case. If you post code we can try and help.
