### ISSUE TITLE
'RCTTextField not a descendant of RCTShadowView' crash when TextInput is focused

### ISSUE THREAD

**Issue by vugman** [aksonov/react-native-router-flux#865]
**Not sure this is related to RNRF but changing one of the props of the scene seems to affect**

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.0
- react-native v0.28.0

### Steps to reproduce

1. Have a main screen (with tabs in my case)
2. Navigate to a different screen, outside of the tabs scene
3. Navigate to another screen that has a TextInput and focus on the input

**If I set type="replace" (instead of 'push') this does not happen**

Here's what I get:
<img width="373" alt="screen shot 2016-06-27 at 11 29 55" src="https://cloud.githubusercontent.com/assets/11426508/16373416/d1e667ac-3c5a-11e6-97f8-f1d8af69477c.png">

**Comment by cridenour** [comment]
Do you have any other libraries in this app? I've seen this with the keyboard aware scroll view. https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/33

**Comment by vugman** [comment]
No I don't, I think this happens when there are multiple screens in the stack that listen to keyboard events (i.e. TextInput component)

**Comment by JosephDev** [comment]
@vugman Apply this [PR](https://github.com/facebook/react-native/pull/7876) and [this](https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/41) into your app.
I have no problems with react-native-router-flux v3.30.0 and react-native v0.28.0

**Comment by aksonov** [comment]
I'm closing it because it is not RNRF issue.
