### ISSUE TITLE
Fade from one scene to another?

### ISSUE THREAD

**Issue by andyschwob** [aksonov/react-native-router-flux#867]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.2
- react-native v0.27.0

Is it possible to have one scene fade into the next?  (Instead of the normal horizontal/vertical swipe)

**Comment by sheparddw** [comment]
Looks like you created a way: https://github.com/aksonov/react-native-router-flux/pull/868
I added it here for reference.

**Comment by andyschwob** [comment]
thanks, my fault i should have linked it

**Comment by cridenour** [comment]
Closing in favor of the pull request.
