### ISSUE TITLE
Run two actions on Sidebar onPress function

### ISSUE THREAD

**Issue by MovingGifts** [aksonov/react-native-router-flux#869]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.3.0
- react-native v0.27.0

### Expected behaviour
With an open sidebar, when clicking the aboutUs link, the onPress calls the following function.
Expected behaviour is sidebar should close, and navigate to aboutUs.
`onPressAboutUs = () => {
      Actions.refresh({key: 'sideBar', open: false });
      Actions.aboutUs();
    }`

### Actual behaviour
Sidebar remains open, and only aboutUs gets navigated to. Upon closing aboutUs, sidebar is still open. If I use a single action by itself, the single action works, but I need both of them to work as a combination to hide the sidebar and load the scene.

### Steps to reproduce

1. Include an onPress which runs the above 2 actions.
2. Only the last action is run.

Any idea how to get it to work?

**Comment by aksonov** [comment]
Add second action within setTimeout
