### ISSUE TITLE
routeReducer not working properly

### ISSUE THREAD

**Issue by lesniakania** [aksonov/react-native-router-flux#87]
I'm using `react-native-router-flux` with `redux`.
I try to implement simple route change - from the list to the specific view of the list item.
I've already did similar thing using `react` (not `native` one) and I learned than that every route change is done dispatching the action. Selecting the state is done in `select` method which selects particular item from general state.
But if you don't have params in state it's impossible to choose particular item in detailed container.
That's why I think something is wrong in `routeReducer` or dispatching routing actions in `react-native-router-flux`, cause there is no params in state.

I'm dispatching route change according to the documentation:

```
<TouchableHighlight onPress={() => Actions.edit_question({id: question.id })}>
// ...
</TouchableHighlight>
```

But nothing changes in state:
```
{ routing: { changeId: 1, path: undefined, state: undefined, replace: false } }
```

Here is working component using not native `react` and `redux`:
https://github.com/lesniakania/oceny-frontend/blob/master/src/components/SubmissionPage.js

My `package.json` for this project:
```
{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "0.17.0",
    "react-native-router-flux": "^1.0.9",
    "react-redux": "3.0.0",
    "redux": "3.0.3",
    "redux-simple-router": "^1.0.1",
    "redux-thunk": "1.0.0"
  }
}
```

Can you help me : ]?

**Comment by aksonov** [comment]
This component doesn't provide routerReducer (maybe you meant react-native-redux-router)?

**Comment by lesniakania** [comment]
Hm, actually I should have phrase this issue in other way.
I'm using `routeReducer` from `redux-simple-route`. But from what I understand, it's not the reducers fault, but it just doesn't get proper state to reduce from.
I mean, as far as I know redux, all reducers gets every action, and they just choose to which action they want to respond.
But I can't see in state in my custom reducer nothing about params. But I see all the arguments I pass to the `Action.name(args)` methods in the props of the component. The thing is that, I think, it should be in state first.

**Comment by aksonov** [comment]
redux-simple-router is not connected with this component (and it is not declared anywhere, right?), so i  still don't understand the issue

**Comment by lesniakania** [comment]
Ok, maybe my assumptions are wrong then.
I thought it should work like this:

Your component implements routing with ability to connect your library to either `flux` or `redux`.
In `redux` it would mean that routing change is done by dispatching action.
But it would mean that I can see state change in any reducer (particularly `routeReducer` from `redux-simple-router`.
But I'm not seeing state change, so my assumption something is wrong while changing the route with your component. Or maybe I should set your component up in other way, but I already did everything from the `README`. 

The example I've shown you is from the non native one, it's just for illustration how I think it should work.

**Comment by aksonov** [comment]
You should manage state on your own (flux or redux) by using Actions.onPush/Actions.onPop - fire there needed redux actions and manage your state.

**Comment by lesniakania** [comment]
Hm, ok, I can do this, but it's not a matter of executing callback, but the fact that route itself should be changed by dispatching action. I understand I can use it regardless of the architecture choice, I'm just saing it's a pitty you don't want to support redux way no more.

**Comment by aksonov** [comment]
Maybe it will be later, when i've found what is desired use case. For a while nobody didn't tell me how it should be supported - you are using redux-simple-router, but somebody else will use own way of redux, so it is not clear how to support all possible scenarios.

**Comment by lesniakania** [comment]
Ok, I understand now. For me It would be just more consistent with non-native react world.
I started with using https://github.com/acdlite/redux-router, because their `why` section convinced me that changing a route is a state change so should be treated the same way as any state change in `redux`.
Now they recommend using `redux-simple-router` (because it's more official).
I can't wait when there will be more official libraries in this world ; ] I mean more knolegde about how it should be done, less chaos.

Anyway thanks for conversation.

**Comment by aksonov** [comment]
Okey, now with 2.0, you could implement your own Router delegate to manage state/UI - check ExRouter for reference - it uses simple onPush/onPop props with exNavigator UI. You may use your own UI that fires own Redux push/pop/replace actions - and you could check current router/route using Actions.currentRouter and Actions.currentRouter.currentRoute

**Comment by lesniakania** [comment]
@aksonov thanks for letting me know. I don't have time to check this now, but I will remember definitely for future.
