### ISSUE TITLE
Swipe gesture not working to dismiss scene

### ISSUE THREAD

**Issue by chadwilken** [aksonov/react-native-router-flux#872]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.26.16
- react-native v0.27.2
- react-native-drawer v2.0.0
### Expected behaviour

Before we could swipe from anywhere on the screen to pop back to the previous screen. Now it is similar to the default iOS behavior on a `UINavigationViewController` where you can swipe from a small portion of the screen.

**Comment by cridenour** [comment]
I believe the default for this library should mirror the default iOS behavior. However, if you want to override that, you can always set your own panHandlers on the scene, but I don't have any examples of the functionality you're looking for.

**Comment by jasongaare** [comment]
Adding panHandlers works, in a way. I can set it to call Actions.pop() after the user has moved their touch a certain distance, however it would be really nice if the parent view rendered underneath the view as it is getting dragged off the screen. Is there a way to pull that off?

**Comment by enapupe** [comment]
I have that behaviour but it only triggers from the very left edge.. Like, 1px or so.. it should be a little bit wider though
