### ISSUE TITLE
Actions.KEY_NAME doesn't do anything. 

### ISSUE THREAD

**Issue by zsawaf** [aksonov/react-native-router-flux#876]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.2
- react-native v0.28.0

### Expected behaviour

I expect scenes to transition after I call Actions.KEY_NAME

### Actual behaviour

Nothing happens.. I read the documentation carefully several times, and I realize it's probably something to do with my code. If anyone can catch what I'm doing wrong, I'd greatly appreciate it. 

### My Setup / How to reproduce

 in index.js

    const scenes = Actions.create(
      <Scene key="root"
             navigationBarStyle={{ backgroundColor: '#fff' }}
             titleStyle={{ fontSize: 15 }}
        >
        <Scene
          key="restaurants"
          component={Restaurants}
          initial={true}
          title="Restaurants"
          />
        <Scene
          key="menus"
          component={Menus}
          title="Menus"
        />
      </Scene>
    );
then in my render function:

    return (
      <Router scenes={scenes}/>
    )

Then in restaurants.js, I have a listview, and the renderRow is as following: 

    return(
      <TouchableOpacity onPress={Actions.menus(restaurants)} style={styles.listContainer}>
        <View style={styles.listImage}>
          <Image source={{uri: restaurant.logo}} style={styles.backgroundImage} />
        </View>
        <View style={styles.textContainer}>
          <View style={styles.leftColumn}>
            <Text style={styles.mainFont}>{restaurant.name}</Text>
            <Text style={styles.smallerFont}>{restaurant.type}, {restaurant.price}</Text>
          </View>
          <View style={{flex:1}}></View>
          <Text style={styles.estFont}>{restaurant.est}</Text>
        </View>

      </TouchableOpacity>
    );

but when I press the touchableOpacity, nothing happens. 

I tried adding a random button on a screen that has calls Actions.menus, but that also does nothing.

Do I need to add a custom switch statement or something? 

Any tips would be appreciated. Thank you

**Comment by MovingGifts** [comment]
@zsawaf Try `() => Actions.menus(restaurants)`

**Comment by zsawaf** [comment]
Thanks a lot! 

   Actions.menus() wasn't working, but wrapping it in a function works. Thanks a lot!

**Comment by tuckerchapin** [comment]
Hmm. I have the same issue, but several variants have not solved my problem.

Call location:
```
...
<CreateSessionButton onPress={() => Actions.createSession()}>
    <Icon name="add" size={scaleFont(30)} color="#FFF"/>
</CreateSessionButton>
...
```

Router layout in `index.js`:
```
render() {
    return (
        <Router>
            <Scene key="root">
                <Scene key="landing" hideNavBar={true} component={Landing} title="Loading..." type="replace"/>
                <Scene key="loggedOut" hideNavBar={true} component={LoggedOut} title="Sign in/up" type="replace"/>
                <Scene key="enterCCInfo" hideNavBar={true} direction="vertical">
                    <Scene key="getCC" component={CreditCardEntry} title="Enter your card info"/>
                </Scene>
                <Scene key="drawer" component={MaterialDrawer}>
                    <Scene key="loggedIn" component={LoggedIn} title="Logged in" hideNavBar={true} initial={true} type="replace"/>
                    <Scene key="createSession" direction="vertical" hideNavBar={true}>
                        <Scene key="sessionDetailSelector" component={SessionDetailSelector} initial={true} title="Schedule a session"/>
                        <Scene key="sessionConfirm" component={SessionConfirm} title="Everything look right?"/>
                        <Scene key="sessionReciept" component={SessionReceipt} title="We'll see you then"/>
                    </Scene>
                </Scene>
            </Scene>
        </Router>
    );
}
...
```

I've tried a variety of things:

* The call is wrapped in an anonymous function
* I've tried calling other scenes: real scenes throw no errors, but do not render into the view, while fake, non-existent scenes like `Actions.fooBar();` throw an error. So clearly something is being actually called.
* I've tried moving the scene outside of the wrapping scene that has the `direction="vertical"` tag.
* I've tried having other buttons or UI components trigger this `Actions` call. 

Nothing seems to work. Any ideas?

**Comment by tuckerchapin** [comment]
Alright, so drawer seems SUPER broken right now.

Simply by commenting out the "drawer" container around my code I was able to launch the vertical scene with no other modification.

**Comment by zsawaf** [comment]
Yeah, tbh I couldn't get drawer working with the flux navigation. 

I just left it out for now until there's better integration :)

**Comment by tuckerchapin** [comment]
Glad to know I'm not going crazy. Looks like that's what I'm gonna have to do.

**Comment by aksonov** [comment]
Does example drawer work for you?

Pavel.

**Comment by tuckerchapin** [comment]
If you're referring to the example drawer found [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md) then yes and no. 

It "works" in that the drawer functions 100% as to be expected. However, its inclusion causes other things to break. It breaks `Actions.KEY_NAME()` calls and also breaks the custom `navBar` functionality, causing no navBar to render at all.

**Comment by aksonov** [comment]
Do Example’s Actions.KEY_NAME() work within Example?

Are you sure that Actions.KEY_NAME is not null when you are call them? Note, that you should not call them during mounting phase, because they may be null at this time.

About navBar - please create repo with Example and custom NavBar and show broken functionality. I’m using custom nav bar and drawer without any problem within my app

This component is used within production apps, so i don’t think it contains such big bugs.

**Comment by aksonov** [comment]
And Example Drawer contains exactly ONE scene, your example contains many..

**Comment by tuckerchapin** [comment]
OH. Wow. Yeah, I'm a complete idiot, sorry for wasting your time. Reorganized the scenes and having one scene inside the drawer fixes ALL of my problems. 😬
