### ISSUE TITLE
initial router not rendered in Android(while fine in iOS)

### ISSUE THREAD

**Issue by jiyinyiyong** [aksonov/react-native-router-flux#878]
### Version

```
  "dependencies": {
    "react": "15.1.0",
    "react-native": "0.28.0",
    "react-native-router-flux": "^3.30.3",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2"
  }
```
### Expected behaviour

From iOS simulator 

![image](https://cloud.githubusercontent.com/assets/449224/16445051/7d1f09b2-3e13-11e6-9774-9d14351dca03.png)
### Actual behaviour

In Android: content not rendered(only text "app" left)
iOS: fine.
### Steps to reproduce

Clone this repo, install dependencies, run `react-native run-android`:

https://github.com/ElemeFE/template-redux-rn/blob/master/app/containers/app.js#L13

**Comment by cridenour** [comment]
There is only one "Router". You're already defining it in your index.ios.js and index.android.js. I highly suggest you use the Example as a starting spot.

https://github.com/aksonov/react-native-router-flux/tree/master/Example

**Comment by jiyinyiyong** [comment]
You mean `<Router>` has to be the root component?

**Comment by cridenour** [comment]
Yes, and there can only be one per project. You can't have it in both app.js AND index.android.js.

**Comment by jiyinyiyong** [comment]
`index.android.js`? https://github.com/ElemeFE/template-redux-rn/blob/master/index.android.js
I don't understand...

**Comment by cridenour** [comment]
Ah so sorry - I read `Provider` as `Router` when I first looked. 

I would still place your Router as the first element after the redux provider - following this guide. https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

**Comment by jiyinyiyong** [comment]
Oh, no, initial router is still not rendered in Android after moving `Router` to `Provider`.
