### ISSUE TITLE
Example Launch.js action cannot go to tabbar specific tab page

### ISSUE THREAD

**Issue by MovingGifts** [aksonov/react-native-router-flux#884]
Using: 
- react-native-router-flux v3.30.3
- react-native v0.27.0

Using the latest Example in Launch.js - I try to navigate to a specific tab in a tabbar by adding an Button onPress action, console shows a jump action, but the scene never loads.

In Launch.js:
`<Button onPress={Actions.tabbar}>Go to TabBar page</Button>`

I add this under it:
`<Button onPress={()=>Actions.tab2()}>CUSTOM Go to TabBar SPECIFIC Tab page</Button>`

I also tried this:
`<Button onPress={()=>Actions.tab2_1()}>CUSTOM Go to TabBar SPECIFIC Tab page</Button>`

Both don't work. Any idea how to get it to work?

**Comment by MovingGifts** [comment]
Hello anyone?

**Comment by cridenour** [comment]
It's not something that is supported AFAIK. There are some hacks you can do with a custom TabBar, but I was hoping someone had a more clever answer for you.

**Comment by MovingGifts** [comment]
@cridenour Thank you for responding. I feel like the Tabs are the most lacking feature at the moment. Something like [RN Scrollable Tab View](https://github.com/skv-headless/react-native-scrollable-tab-view) integration would be amazing in my opinion, and they're almost as popular just in tabs (can disable the scroll effect to match this rn tabs), as this repo is just in routing. Unfortunately, I don't have enough knowledge/skills to make an integration [see talk about integration here](https://github.com/skv-headless/react-native-scrollable-tab-view/issues/155), or to get the tabs in this component and it's action to work as they should. I would imagine it's pretty simple for the experts in this repo to do either.

Can someone with more knowledge please chime in? @joenoon @aksonov

**Comment by MovingGifts** [comment]
bump

**Comment by joenoon** [comment]
@MovingGifts I tried your example and was a little surprised it doesn't work.  But I've never needed to do anything like that so I've never run into the issue before.  I think you'll need to look into a custom reducer or adjusting the default reducer to handle jumping/pushing to nested scenes.

**Comment by MovingGifts** [comment]
@joenoon Thank you for your reply and direction. I have no clue how to do that, but appreciate your answer!

**Comment by sham3k** [comment]
Calling Actions.ROUTE_KEY({ type: 'jump' }) from inside one of the tabs can switch tabs.
So maybe you need to pass the tab to switch to, as a prop to the initial tab page, and call Actions.ROUTE_KEY({ type: 'jump' }) from there.

Let me know if thats what you need. :)
