### ISSUE TITLE
Custom NavBar with custom TabBar

### ISSUE THREAD

**Issue by lifehackett** [aksonov/react-native-router-flux#885]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.3
- react-native v0.28.0
### Expected behaviour

Displays my custom navBar
### Actual behaviour

Displays the default navBar
### Steps to reproduce

I am going through the process of upgrading RN from 22-28.  First, thanks for all your hard work around their moving target of a Navigation API.  Using your TabView and TabBar as a template I have gotten the tab bar working again, but my custom NavBar has been replaced with the default one.  I have tried applying `hideNavBar={ true }` at the tab bar level (nothing happens) and at the individual tab level (tab bar is hidden).  I have also tried applying the navBar again at these same levels and the correct one gets displayed, but it doesn't have the correct navigation state presumably because it is a separate instance.

```
export default class App extends Component {
  render() {
    return (
      <Provider store={ store }>
        <Router>
          <Scene key="root" hideNavBar={ true } >
            <Scene key="login" component={ Login } />
            <Scene key="drawer" component={ Menu }>
              <Scene key="nav" navBar={ NavBar }>
                <Scene key="projects" title="Projects" component={ ProjectPicker } />
                <Scene key="collections" component={ CollectionPicker } getTitle={ () => currentProject(store.getState()).name } />
                <Scene key="moderation" tabs={ true } component={ ModerationTabs } getTitle={ () => activeCollection(store.getState()).name } >
                  <Scene key={ DENIED.toLowerCase() } component={ ModerationList } getTitle={ () => activeCollection(store.getState()).name }  />
                  <Scene key={ UNMODERATED.toLowerCase() } initial={ true } component={ ModerationList } getTitle={ () => activeCollection(store.getState()).name } />
                  <Scene key={ APPROVED.toLowerCase() } component={ ModerationList } getTitle={ () => activeCollection(store.getState()).name } />
                  <Scene key="filters" title="Filters" component={ Filters } />
                </Scene>
                <Scene key="moderation_detail" getTitle={ () => activeCollection(store.getState()).name } component={ ModerationDetail } />
              </Scene>

            </Scene>
          </Scene>
        </Router>
      </Provider>
    )
  }
}
```

UPDATE: NavBar implementation

```
export default create({
  displayName: 'NavBar',
  contextTypes: {
    drawer: PropTypes.object,
  },
  render(p, s, c) {
    const { drawer } = c;
    const { height, width } = Dimensions.get('window');

    return (
      <View style={ styles.container }>
        <StatusBar barStyle="light-content" />
        <TouchableOpacity onPress={ Actions.pop }>
          <View style={ styles.backButton }>
            <If condition={ p.navigationState.index > 0 }>
              <MDIcon name="arrow-back" size={ 20 } color={ colors.gray.one } />
            </If>
          </View>
        </TouchableOpacity>
        <View>
          <Text style={[ styles.title ]} numberOfLines={ 1 }>{ p.getTitle(p) }</Text>
        </View>
        <TouchableOpacity onPress={ drawer.open }>
          <View style={ styles.menuButton }>
            <If condition={ !!drawer }>
              <MDIcon name="menu" size={ 20 } color={ colors.gray.one } />
            </If>
          </View>
        </TouchableOpacity>
      </View>
    )
  }
})
```

**Comment by cridenour** [comment]
What does your NavBar code look like?

**Comment by lifehackett** [comment]
Original post updated with NavBar

**Comment by cridenour** [comment]
Hm, even if your navbars are separate instances, they should have the correct state. 

Make sure you're reading the navigationState correctly, maybe compare to the original one and see how they are reading the new state. 

https://github.com/aksonov/react-native-router-flux/blob/master/src/NavBar.js

**Comment by lifehackett** [comment]
Ok, so I went ahead and tried to use the provided prop interface supplied by RNRF and am getting the same result.  It doesn't seem to matter whether I remove `tabs={ true } component={ ModerationTabs }` or not.

To recap my question:
1) Why is it necessary to redefine my navbar styles in the 3 scenes (Denied, Unmoderated, Approved) nested under the tabbar? 
2) Why in the scenes nested under the tab bar is the back button not rendering?  The issue seems to be that the navigationState is being reset to 0 when passed in to those scenes, but I don't understand why.

Here is the updated navigation

```
export default class App extends Component {
  render() {
    return (
      <Provider store={ store }>
        <Router>
          <Scene key="root" hideNavBar={ true } panHandlers={ null }>
            <Scene key="login" component={ Login } panHandlers={ null }/>
            <Scene key="drawer" component={ Menu } panHandlers={ null }>
              <Scene key="nav" { ...navBar } panHandlers={ null }>
                <Scene key="projects" title="Projects" component={ ProjectPicker } sceneStyle={{ marginTop: NAV_BAR_HEIGHT }} panHandlers={ null } { ...navBarButtons }/>
                <Scene key="collections" component={ CollectionPicker } getTitle={ () => ProjectSelectors.activeProject(store.getState()).name } sceneStyle={{ marginTop: NAV_BAR_HEIGHT }} panHandlers={ null } { ...navBarButtons }/>
                <Scene key="moderation" tabs={ true } component={ ModerationTabs } getTitle={ () => CollectionSelectors.activeCollection(store.getState()).name } panHandlers={ null } >
                  <Scene key={ DENIED.toLowerCase() } component={ ModerationList } getTitle={ () => CollectionSelectors.activeCollection(store.getState()).name } sceneStyle={{ marginTop: 100 }} { ...navBarButtons } { ...navBar }/>
                  <Scene key={ UNMODERATED.toLowerCase() } initial={ true } component={ ModerationList } getTitle={ () => CollectionSelectors.activeCollection(store.getState()).name } sceneStyle={{ marginTop: 100 }} { ...navBarButtons } { ...navBar }/>
                  <Scene key={ APPROVED.toLowerCase() } component={ ModerationList } getTitle={ () => CollectionSelectors.activeCollection(store.getState()).name } sceneStyle={{ marginTop: 100 }} { ...navBarButtons } { ...navBar }/>
                </Scene>
                <Scene key="filters" title="Filters" component={ Filters } panHandlers={ null }/>
                <Scene key="moderation_detail" getTitle={ () => CollectionSelectors.activeCollection(store.getState()).name } component={ ModerationDetail } panHandlers={ null }/>
              </Scene>

            </Scene>
          </Scene>
        </Router>
      </Provider>
    )
  }
}

const navBar = {
  navigationBarStyle: styles.container,
  titleStyle: styles.title,
}

const navBarButtons = {
  renderBackButton(p) {
    return (
      <TouchableOpacity onPress={ Actions.pop }>
        <View style={ styles.backButton }>
          <If condition={ p.navigationState.index > 0 }>
            <MDIcon name="arrow-back" size={ 20 } color={ colors.gray.one } />
          </If>
        </View>
      </TouchableOpacity>
    )
  },
  renderRightButton(p) {
    return (
      <View style={ styles.menuButton }>
        <MDIcon name="menu" size={ 20 } color={ colors.gray.one } />
      </View>
    )
  },
}
```

**Comment by cridenour** [comment]
I would believe that you wouldn't want a back button on a child tab scene. Navigation at that point should be between tabs. If you navigate to a scene from a tab, you will then want to go back - but only as far as the tabs. 

This is a "sane" default as most tab based navigators are root scenes - but obviously you have a use case for otherwise. I'll have to take a deeper dive or get @joenoon in here to find a next step.

**Comment by joenoon** [comment]
@lifehackett in my app I use a custom navBar and I set it in the jsx on every immediate child of a `tabs={true}` scene, as well as the top root.  So it looks sort of close to what you are doing, except I don't know that `{...navBar}` is correct.  I think you need `navBar={navBar}`.

And since these are the tab root scenes (index: 0), it makes sense to me that no back button is appearing... but you are using a custom NavBar that doesn't handle `renderRightButton` or `renderBackButton` from your `navBarButtons`, so I'm really not sure what is going on there?  By the logic in your custom NavBar the back button would only be displayed if `index > 0`, and none of denied, unmoderated, or approved would meet that criteria.

**Comment by lifehackett** [comment]
Thank you for the responses.  Prior to upgrading RN and then RNRF my custom nav bar worked as I've described I would like it to work, so either it seems like a bug that it changed or there was a conscious decision to "re-root" navigation when tabs are introduced.

@joenoon the `{...navBar}` in my third post was a refactored attempt to use the provided NavBar API as opposed to a custom NavBar (which is the first example I provided).  The `{...navBar}` is just destructuring the props (included it the snippet) to interact with the provided NavBar.

IMO it would make sense that tabs occupy a place in the state stack similar to any other scene.  So in my case if you navigated `projects > collections > moderation > filters` then `{index: 0 } = projects`, `{ index: 1 } = collections`, and `{ index: 2 } = moderation[denied, unmoderated, approved]` and `{ index: 3 } = filters`.  Clicking a tab would replace the state at index 2 with the tab you selected.  As you navigate the tabs it does not add and index, but replaces the existing one.

**Comment by lifehackett** [comment]
@joenoon Sorry about that sort of being buried.  I was trying out the approach to see if it would work and didn't put enough effort into readability.  Admittedly, I don't have a great grasp on the RN navigation stuff yet so really appreciate your time and effort; the diagram is most helpful.

I am heading out of town shortly, but will do this exercise Tuesday and if everything seems to check out will close this thread then it if you don't mind waiting until then.

**Comment by rohitgoyal** [comment]
Has there been any solution to this? 
I am using a drawer and under that i have multiple scenes. I need back button even on the first scene of that drawer's child scenes.

**Comment by satishmane** [comment]
Hi,
Can you please share working example of custom navigation bar? Currently I am using drawer integrated with router-flu. And I want to add few more button on navigation bar. Hence I want to create custom navigation bar with drawer menu icon on left and other buttons on right side of bar. One of the button is refresh to reload same scene again
thanks
Satish
