### ISSUE TITLE
Dynamic TabIcon by access context/redux?

### ISSUE THREAD

**Issue by pewh** [aksonov/react-native-router-flux#887]
Hello, this is a question rather than an issue.

I already see Example, and I'm just curious how to set dynamic TabIcon (something like badge number on Cart Icon). How to do it? React context? or redux? Thanks

### Version
Tell us which versions you are using: 

- react-native-router-flux v3.3.2
- react-native v0.28

**Comment by diogoviannaaraujo** [comment]
You sure could connect your Icon to a redux state and show something for there.
But maybe there is a way to pass a prop to tab throu the router

**Comment by rturk** [comment]
@pewh this is a little old but should give you an ideia how to implement a custom Icon. In my case I'm simply changing colors, but you should be able to `connect` icons to your favor redux tool.

https://gist.github.com/rturk/69568c504583439a1f5e39b0f87fc81d

**Comment by pewh** [comment]
Hey, thanks all men for the solutions. My case is changing icon or add number beside icon if product is added to cart. So I think access redux state or `connect` are make sense. Actually I have migrate from redux to mobx. I also use React native mobx as a RNRF wrapper. I am on vacation now, so I'll try it again after a few days.
