### ISSUE TITLE
Is this how hidenavbar should work?

### ISSUE THREAD

**Issue by julipur** [aksonov/react-native-router-flux#89]
if I have 

Router hideNavBar={true} I get a screen like this (with the little '<' on the top). Also it shows the title from that Route.

http://screencast.com/t/ugUrtfCcW

if I have  Router hideNavBar={false}, it does not show the '<' and shows the title of the first route. 

http://screencast.com/t/2T7Bpj04W8

Is this the correct behaviour?

**Comment by aksonov** [comment]
No, "<" is not displayed when current route (scene) if first within navigation stack (i.e. have 'switch' type or have wrapRouter function or inner Router)

**Comment by julipur** [comment]
the behaviour I described is in the second route (scene) of the application. hidenavbar(true) shows the < and false hides it.

**Comment by aksonov** [comment]
Post your full routes here.

**Comment by julipur** [comment]
<Router hideNavBar={true}>
              <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
              <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
              <Schema name="withoutAnimation"/>
              <Schema name="tab" type="switch" icon={TabIcon} />

              <Route name="location" component={Location} title="Property Location" initial={true} wrapRouter={true} />
              <Route name="quote" component={Quote} title="Quote"/>
          </Router>

**Comment by aksonov** [comment]
As you can see "location" has wrapRouter which means it runs under his own navigator (that is why you don't see "<")

**Comment by julipur** [comment]
Thanks much!
