### ISSUE TITLE
How can i add gradient in background color of navbar?

### ISSUE THREAD

**Issue by kishanj918** [aksonov/react-native-router-flux#890]
### Version
- react-native-router-flux v3.30.2
- react-native v0.28.0

**Comment by cridenour** [comment]
Check out the API docs here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#navigation-bar 

You can pass in a `navigationBarStyle` - if that doesn't get it perfect, you can create your own NavBar by copying src/NavBar.js to your own file and using `navBar={MyNavBarComponent}`.

**Comment by kishanj918** [comment]
@cridenour thanks :+1:
