### ISSUE TITLE
Improve documentation about how to implement modals

### ISSUE THREAD

**Issue by kennethlynne** [aksonov/react-native-router-flux#893]
The current documentation is kinda "go fuck your self" for newbies just exploring this great router.

**Comment by kennethlynne** [comment]
Just to be clear: I'm a newbie, or else I would send a PR 👍

**Comment by JimmyStavros** [comment]
Agree. It also seems like the example is pretty outdated compared to the current API.

**Comment by sondremare** [comment]
Trying to use modals as the example code shows. And it crashes the entire app when used with a view with https://github.com/FaridSafi/react-native-gifted-messenger

**Comment by aksonov** [comment]
@sondremare Check Example project, does modal work for you?

**Comment by brien-crean** [comment]
Agree, also a bit confused about Modal usage.
If using a Modal as a way of reporting App status to the user e.g. "Network connection failed" etc. 
displaying the Modal works fine I can show it on each screen as the user navigates. 
However as Actions.pop() (or maybe ActionConst.BACK in latest version) is used to dismiss the Modal, if I push another route to the stack and then try to dismiss the Modal it instead pops the most recently added route from the stack and the Modal is stuck there

Is there a better way to implement or is it possible to override onNavigate on the Modal component for example? I tried adding it as a prop to the Scene but it prevented the component from rendering
E.g.
```
      <Router createReducer={this.reducerCreate.bind(this)} >
        <Scene key="modal" component={Modal} >
          <Scene key="root">
            <Scene key="loginScreen" hideNavBar={true} initial={this.state.needSignIn} component={LoginScreen} type="reset" duration={200} />

          </Scene>
            <Scene key="statusModal" component={ErrorModal} onNavigate={ ()=> Actions.loginScreen()}/>
        </Scene>
      </Router>
```

**Comment by heat** [comment]
I have some trouble with Actions.pop() when switch tabs while modal is open.

Is there a action to close modal or what @charpeni is the best way

**Comment by brien-crean** [comment]
@heat @cridenour I tried to submit a pull request, but got permission denied. Here is the example of Modal usage I was trying to submit:

```jsx
import StatusModal from './components/StatusModal'

<Router>
  <Scene key="modal" component={Modal} >
    <Scene key="root">
      <Scene key="screen1" initial={true} component={Screen1} />
      <Scene key="screen2" component={Screen2} />
    </Scene>
      <Scene key="statusModal" component={StatusModal} />
  </Scene>
</Router>
```

Then in the StatusModal Component we can define what we want it to look like and what props can be passed to it:

```jsx
class StatusModal extends Component {

  constructor(props) {
    super(props)
    // set state with passed in props
    this.state = {
      message: props.error,
      hide: props.hide,
    }
    // bind functions
    this.dismissModal = this.dismissModal.bind(this)
  }

  dismissModal() {
    this.setState({hide: true})
  }

  // show or hide Modal based on 'hide' prop
  render() {
    if(this.state.hide){
      return (
        <View>
        </View>
      )
    } else {
        return (
          <TouchableHighlight style={styles.mainContainer} onPress={this.dismissModal}>
            <Text style={styles.text}>{this.state.message}</Text>
          </TouchableHighlight>
        )
      }
  }
}
```

Lastly when calling the Modal pass the props defined in the component, for example an error message and a 'hide' prop of false to display the Modal:

`Actions.statusModal({error: "Network failed...", hide: false})`

When the Modal is pressed it will set hide to true and return an empty view.

**Comment by Daniellt1** [comment]
Hi,

I have exactly the same code as @brien-crean, but I am getting this kind of error: [screenshot](https://s32.postimg.org/doyiq7639/Capture.png).

What I am doing wrong?

Thanks,
Daniel

**Comment by heat** [comment]
I'll try stack it again before pop.  `Actions.modalApp(); Actions.pop()`

**Comment by omeid** [comment]
I have the same problem. The hiding technique in ed28f7f  works but it breaks the `Action.pop` behaviour, at least for the first call after presenting the modal anyways.

**Comment by omeid** [comment]
One solution for this would be for `Actions.ACTION_NAME` to return a reference that can be passed on to `Actions.pop($REF)`. Thoughts?

**Comment by flare216** [comment]
@brien-crean  , i try to hide the modal by Actions. statusModal({hide: true}) but failed, the render of StatusModal indeed returns an empty view, but the modal still on the screen, so weired.

**Comment by brien-crean** [comment]
@omeid @flare216 yes, unfortunately there is a flaw with my solution, the Modal never gets popped from the stack so will only appear once, other pushes of the Modal will result in error. 

I have been trying to create another solution but have been unsuccessful so far. 

Potential solutions could be the ability to remove a Scene from the stack by name, (after checking that it exists on the stack), as @aksonov proposed e.g. removeScene(ACTION_NAME) or the solution that @omeid proposed above, either would work. Unfortunately I don't know if I would be able to figure it out myself

**Comment by aksonov** [comment]
I've added Actions.get(ACTION_NAME) to receive scene with ACTION_NAME. This way you could store everything during displaying of that scene including refs using Actions.refresh({key:ACTION_NAME, ref:this.refs.REF_NAME}) then use Actions.get(ACTION_NAME).ref from any other action

**Comment by brien-crean** [comment]
Thanks @aksonov, I'll give that a shot and see if I can submit another PR for the docs

**Comment by sibelius** [comment]
How can I have a transparent background on my Modal?

Should I use `Modal` from `react-native` ?

**Comment by danmatthews** [comment]
I'm still completely confused by modals with this Router.

The detailed example in the documentation shows modals acting like the `Modal` component of React Native - this is what i want. When i call `Actions.login` to open my login screen, i want it to pop up over the content of the current page - this means i can check if a user is authenticated, and if not, pop up the login screen to authenticate them in situ.

Is this possible? It looks easy in the example, but i can't get modals to be anything more than a little chunk of `<View>` that just appears at the bottom of the screen when triggered.

What am i missing? I would love to know so i can help contribute to the documentation.

**Comment by cridenour** [comment]
If the view is showing up then the router is doing its job, and that view just needs styling.  Position absolute, top, left, right, bottom all at 0.

**Comment by sibelius** [comment]
@cridenour position absolute shouldn't be the default?

what about transparent background, is it possible without using `<Modal>` from `react-native`?

**Comment by danmatthews** [comment]
@cridenour the detailed example shows it appearing using a slide-in-from-bottom animation, and i can't see anything in the example that effects that transition - therefore i assumed that it was part of the router?

**Comment by cridenour** [comment]
I believe a transparent background is possible, as I've done it accidentally. However I'm on mobile and can't provide an example. But regarding positioning, the default is fluxbox, but you can manually set it to absolute.

With the direction, on the modal view in your scene config, just set `direction="vertical"` and it should do the trick.

**Comment by danmatthews** [comment]
Beautiful, thank you :) i'll give that a try after i've walked the 🐶

**Comment by gkrinc** [comment]
I tried adding the **getSceneStyle** prop to my RouterWithRedux, but I get the same problem that @Daniellt1 was getting: "Objects are not valid as a React child (found: object with keys {..."

So brutal that it's this difficult to get a Modal working :s

Here's the render method of my index.ios.js file

```
render() {
        return (
            <Provider store={store}>
                <AppDrawersContainer>
                    <RouterWithRedux hideNavBar={true} getSceneStyle={getSceneStyle}>
                        <Scene key="modal" component={Modal}>
                            <Scene key="root" renderTitle={() => { return <AppLogo /> }}>
                              ... other scenes ...
                            </Scene>
                            <Scene key="statusModal" component={StatusModal} />
                        </Scene>
                    </RouterWithRedux>
                </AppDrawersContainer>
            </Provider>);
}
```

The StatusModal is a direct copy of the one provided in the example.

If I take this scene out, I don't get the error, but of course the modal won't load

`<Scene key="modal" component={Modal}>`

**Versions:**
react-native: v0.34.0-rc.0
react-native-router-flux: v3.34.0 (downgraded from 3.35.0 because of another issue)

**Comment by cridenour** [comment]
Wait why do you have `getSceneStyle` on your router? I don't think it's valid on a router, only scenes.

**Comment by gkrinc** [comment]
https://github.com/aksonov/react-native-router-flux/blob/822e83f08f5063cd33bc0c92030311c9acafb2af/Example/Example.js#L107

**Comment by cridenour** [comment]
Ah, you're right - sorry. Maybe instead of nesting the scenes under the Router object, pass them using the `scenes` prop and `Actions.create`

**Comment by gkrinc** [comment]
I ended up going with react-native-simple-modal. I liked how easy it was to implement and it handles a queue of modals quite effectively and doesn't cause any weird routing issues that people seem to have come across.

**Comment by robinweston** [comment]
I had the same issues, but realised I was importing Modal from react-native instead of react-native-router-flux

**Comment by liamfd** [comment]
@robinweston that was the issue for me as well, thank you for posting that.

I attempted to make a PR to update the docs to be a bit more informative, not sure if I did it right but I didn't seem to have permission. I suggested that the first code block in [the modal example](https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#modals) be changed to the following:

```jsx
import React, { Component } from 'react';
import { Text, View, TouchableHighlight } from 'react-native';
import {
  Actions,
  Router,
  Scene,
  Modal // Note that this needs to be our implementation of modal, not React-Native's
} from 'react-native-router-flux';
import StatusModal from './components/StatusModal'

export default class App extends Component {
  render() {
    return (
      <Router>
        <Scene key="modal" component={Modal} >
          <Scene key="root">
            <Scene key="screen1" initial={true} component={Screen1} />
            <Scene key="screen2" component={Screen2} />
          </Scene>
          <Scene key="statusModal" component={StatusModal} />
        </Scene>
      </Router>
    );
  }
}

class Screen1 extends Component {
  render() {
    return (
      <View style={{margin: 128}}>
        <Text onPress={() => Actions.statusModal({error: "Network failed...", hide: false})}>This is Screen1!</Text>
      </View>
    )
  }
}

class Screen2 extends Component {
  render() {
    return (
      <View style={{margin: 128}}>
        <Text onPress={() => Actions.statusModal({error: "Network failed...", hide: false})}>This is Screen2!</Text>
      </View>
    )
  }
}
```

That file should be good for a user to copy paste, as long as `StatusModal` is present and valid. If that is too verbose I think even something as simple as the following would be a big improvement, because I didn't know that this project had a Modal component until I got to this thread.

```jsx
import { Modal } from 'react-native-router-flux';
import StatusModal from './components/StatusModal'

export default class App extends Component {
  render() {
    return (
      <Router>
        <Scene key="modal" component={Modal} >
          <Scene key="root">
            <Scene key="screen1" initial={true} component={Screen1} />
            <Scene key="screen2" component={Screen2} />
          </Scene>
          <Scene key="statusModal" component={StatusModal} />
        </Scene>
      </Router>
    );
  }
}
```

By the way, I couldn't find the styles that are referenced in the `StatusModal` component, it might be nice to either remove the references to them or define them in the example, as right now it crashes.

**Comment by DiegoGallegos4** [comment]
@sibelius Did you find a way to style a transparent background?

**Comment by sibelius** [comment]
I'm using `Modal` component from react-native core

**Comment by fostertime** [comment]
Based on this note from @aksonov from July:

> I've added Actions.get(ACTION_NAME) to receive scene props with ACTION_NAME. This way you could store everything during displaying of that scene including refs using Actions.refresh({key:ACTION_NAME, ref:this.refs.REF_NAME}) then use Actions.get(ACTION_NAME).ref from any other action

Is this a solution to resolve the issue of not being able to pop() the modal? I am having the same issue as described above, where the first view of the modal works, but another others cause a duplicate key error. Trying to figure out how to pop the modal, when hiding it.

**Comment by ryancoughlin** [comment]
Is the goal of this modal to be treated like a native modal respective to the device it's running on? I can't seem to get anything more than a view talking up 50% of it's container view. Is that accurate out of the box functionality?

@danmatthews Were you able to get past that?

**Comment by ryancoughlin** [comment]
>If the view is showing up then the router is doing its job, and that view just needs styling. Position absolute, top, left, right, bottom all at 0.

@cridenour If that applies styling, could that be proposed to default functionality since that is how modals behave natively? Including a navigation bar.

**Comment by ryancoughlin** [comment]
>If the view is showing up then the router is doing its job, and that view just needs styling. Position absolute, top, left, right, bottom all at 0.

@cridenour If that applies styling, could that be proposed to default functionality since that is how modals behave natively? Including a navigation bar.

**Comment by cridenour** [comment]
@ryancoughlin That suggestion was for their particular case. If you check out the Example app, the modal example (Login) does not require such styling.

**Comment by ryancoughlin** [comment]
Oh great, that was super helpful. Seemed like the trick was nesting it within another scene.

**Comment by highbass** [comment]
@ryancoughlin i am going through figuring out the exact same problem... could you kindly provide how you went about solving it.

**Comment by highbass** [comment]
ok I seem to figured it out also.... basically modified styling to be something as such...

```
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0)',
  },
```

which (from the example) is attached to TouchableHighlight

      ```
<TouchableHighlight style={styles.container} onPress={this.dismissModal}>
        <Text style={styles.text}>{this.state.message}</Text>
</TouchableHighlight>
```

I also modified the dismissModal to have an Action.pop() .. since after hiding it doesn't come back up.
