### ISSUE TITLE
Scene {type:'reset'} or type="reset" is not working in 3.30.4 version.

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [aksonov/react-native-router-flux#894]
### Version
Tell us which versions you are using: 
Recently I migrated to react-native-router-flux v3.30.4 version from react-native-router-flux v3.30.3.
Scene which has  prop '**type**' is not navigating. 

- react-native-router-flux v3.30.4
- react-native v0.28.0

### Expected behaviour
Scene with **type** prop is working fine.

### Actual behaviour
Not able to navigate to scene which has prop **type**

**Comment by cridenour** [comment]
Is this something you're also seeing in the Example app?

**Comment by Durgaprasad-Budhwani** [comment]
@cridenour Yes same thing is also reproducible in Example app and to reproduce there, go to register page in example app and click on replace page or go to switch page and click on exit, it will not work.

**Comment by felipemartim** [comment]
also happening here

**Comment by iWinkey** [comment]
Same issue with type="replace"

**Comment by iWinkey** [comment]
2fff2c9efd410bde2839c894f5e91f2f3b7ae8c6 See this commit and #843 this discussion!
Now the type string is prefixed to namespace them, so the type="reset" now is type="REACT_NATIVE_ROUTER_FLUX_RESET" and type="replace" now is type="REACT_NATIVE_ROUTER_FLUX_REPLACE"

**Comment by ElvisChiang** [comment]
FYI,

change from 
```JavaScript```
import { Scene, Reducer, Router } from 'react-native-router-flux';

<Scene key={deviceConfg} type="replace' >
```
to 
```JavaScript
import { Scene, Reducer, Router, Actions } from 'react-native-router-flux';
const { PUSH_ACTION, REPLACE_ACTION } = Actions;

<Scene key={deviceConfg} type={REPLACE_ACTION} >
```

**Comment by cridenour** [comment]
Thank you @iWinkey. This is an unfortunate and unintentional change of a merge request aimed at better redux integration. It might be worth rolling back, but I'll wait for others to chime in.

**Comment by Durgaprasad-Budhwani** [comment]
Thank you @iWinkey. It is working like a charm. Closing this issue.
