### ISSUE TITLE
drawerImage size

### ISSUE THREAD

**Issue by phidomo** [aksonov/react-native-router-flux#895]
I want to override the drawer image in the navBar.
### Expected behaviour

An image gets automatically resized.
### Actual behaviour

The image does not render if the image is larger than the default image, which is very small.
When using a small image, the icon is shown correctly.
### Steps to reproduce
1. Use an image of 700x700 pixels.
2. `<Scene key='main' drawerImage={require('../images/menu-icon.png')} />`
3. Drawer image is not rendered

**Comment by mrnahidtalukder** [comment]
I'm having the same issue

**Comment by Keksike** [comment]
I can't get this reproduced. Can you give me an example of your full root component?

**Comment by vsrinivas150283** [comment]
I have the same issue when trying to change the drawerImage

**Comment by DiegoGallegos4** [comment]
Do it like this: 

`drawerImage={{uri: 'menu', height: 20, width: 20, resizeMode:'stretch', color: 'white'}}`

**Comment by vsrinivas150283** [comment]
Probably its not working in my case.
