### ISSUE TITLE
Components lifecycle

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [aksonov/react-native-router-flux#896]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.?.?
- react-native v0.28

### Expected behaviour
Should call componentWillUnmount wheb changing route

### Actual behaviour
Does not call it, therefore I can't handle things like stopping timers (setInterval) and other cleanups

### Steps to reproduce

1. Create a component that has a timer
2. Try to stop the timer on componentWillUnmount
3. The method is never called and the timer keeps running after I change the route

**Comment by aksonov** [comment]
This component is just wrapper around React Native navigation. RN Navigation doesn't call componentWillUnmount, please check React Native docs.
