### ISSUE TITLE
Cannot find module buildStyleInterpolator

### ISSUE THREAD

**Issue by saidimu** [aksonov/react-native-router-flux#9]
On Android, the following error occurs:

`undefined is not a function (evaluating 'buildStyleInterpolator(FlatFadeToTheUp)')`

It appears the `buildStyleInterpolator` module cannot be found: [line 4](https://github.com/aksonov/react-native-router-flux/blob/master/Animations.js#L4) & [line 5](https://github.com/aksonov/react-native-router-flux/blob/master/Animations.js#L5) in `Animations.js`

**Comment by aksonov** [comment]
Please latest version 0.1.9 with Android, i've made fix for the path, hope path is the same for Android as for iOS.

**Comment by saidimu** [comment]
The path fix works now. Thanks!
