### ISSUE TITLE
TabBar speed...

### ISSUE THREAD

**Issue by LeBlaaanc** [aksonov/react-native-router-flux#90]
I'm looking at switching to this component from the TabBarIOS component since I can more easily program routes.

It seems to work almost out of the box but the biggest problem I have so far is the tabbar seems to wait for the component to load/render fully before switching the tabbaritem/button/icon's state.

Is there a way to cache or differ the loading of the component once I click the tabbar icon?

**Comment by LeBlaaanc** [comment]
It's also kind of janky, often white screen is all I get... any thoughts on what to look for? :\

**Comment by LeBlaaanc** [comment]
It's also eating up memory like a bosssss haha. Eeeeee.

**Comment by LeBlaaanc** [comment]
Sorry for the hasty reply... On further inspection this is caused by not using `"type='switch'"`, presumably because it is continually pushing each tab onto the view stack? Anyhoo, next problem is figuring out how to get rid of the NavigationBar with `type='switch'` is on, the two methods `hideNavBar={true}` and `showNavigationBar={false}` don't seem to work.

**Comment by aksonov** [comment]
Thanks for the feedback. You may implement your own tab bar for desired functionality. This component provides just simplest tab bar mostly to demonstrate navigation, but you could pass own one.
