### ISSUE TITLE
How to catch tabbar onclick event ? 

### ISSUE THREAD

**Issue by tinygipxy** [aksonov/react-native-router-flux#903]
My application is using tabbar, when user click to switch tabbar I want to refresh data, can you help on to do it ?

**Comment by cridenour** [comment]
You should look at using a reducer to catch these actions. 

See the example here https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L55 and here https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L106

**Comment by tinygipxy** [comment]
Thank you @cridenour, but I'm connecting it to Redux state, so I don't have this reducer anymore. Anyway, I managed to use onPress action of tabbar scene to handle  it after look into source code of tabbar: 
https://github.com/aksonov/react-native-router-flux/blob/f9081b8cce8281ca845aa377fca552087d844de4/src/TabBar.js#L28

**Comment by sibelius** [comment]
@tinygipxy could u post a gist or a repo with the code that u used?

can i define a function inside my component to handle this `onPress` event?

**Comment by tinygipxy** [comment]
@sibelius I didn't use it anymore in my project, but the code look like this:
  <Scene key="Main" onPress={() => {console.log("On Press")}} .../>
