### ISSUE TITLE
Can't put custom left icon on scenes wrapped inside a tabbar

### ISSUE THREAD

**Issue by tsyirvo** [aksonov/react-native-router-flux#904]
### Version
- react-native-router-flux v3.26.0
- react-native v0.24.1

I'm using a tabBar in my app but I can't manage to put a custom icon or title on the left button (nor can I put a custom action on press)… The scene title is not getting displayed either. 
On the other hand, I can customize the right button without problems.

On my scenes which aren't wrapped in a tabBar, everything is working fine, left/right icons and actions.

Do you have any idea where this might be coming from ?

Cheers,

**Comment by aksonov** [comment]
it could be the reason that Back button displayed when stack length is greater than 1.

**Comment by tsyirvo** [comment]
So there is no way to get a custom left button while using a tabbar ?
Even when putting an `onBack` action, I can't modify the default behavior of the left button…

**Comment by aksonov** [comment]
Have you tried to change backButton ?

**Comment by tsyirvo** [comment]
After testing something else, I realized that nowhere in my app, I can put a custom left button... I might be doing something wrong :/

`<Scene key='searchResults' component={SearchResults} title='Résultats' titleStyle={{ color: '#7A7A7F' }} leftButtonImage={settingsIcon} onLeft={() => { Actions.filters(); }} rightButtonImage={mapIcon} onRight={() => { Actions.filters(); }} panHandlers={null}/>`

This is what I'm using inside my tabbar. I'm doing the same for right and left but only right button is working.

**Comment by K-Leon** [comment]
I noticed same thing and could isolate it, but i have no idea how to fix:

Naviging from one tabbed  component **to another tabbed or nested scene** => No Left Button => Route Stack is 0

Navigating from one tabbed  component **to another Scene which is NOT nested** => Back Button Visible => Stack Size 1 - Everything works like expected

**Comment by tsyirvo** [comment]
After upgrading to the latest version of RNRF and RN, I don't seem to have any problems with my navbar.

**Comment by tsyirvo** [comment]
I don't have any problems with the navbar styling but when doing routing from a scene from inside the tabbar to a scene which is outside of the tabbar (a regular scene), the navbar is not displayed a the scene to which i'm routing the user…
Do I need something specific to jump from the tabbar to a scene outside of it ?
