### ISSUE TITLE
peerDependencies issue with react 15.2.0

### ISSUE THREAD

**Issue by andyschwob** [aksonov/react-native-router-flux#905]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.30.6
- react-native v0.27.2

Everything installs fine when i do it one step at a time: ex ```npm i react-native-router-flux --save```, but if i remove my node_modules and ```npm install``` im getting peerDependencies issues.

in my package.json i have 
```
  "dependencies": {
    "react": "15.1.0",
    "react-native": "0.27.0",
    "react-native-router-flux": "^3.30.6"
  }
```
but when i npm install, no matter what i do it installs react 15.2.0 and then at the end of the install I get this error:
```
npm ERR! peerinvalid The package react@15.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.27.2 wants react@15.1.0
```

Any ideas?

**Comment by andyschwob** [comment]
during the npm install process this is where it's getting installed:
```
└── react-native-experimental-navigation@0.26.1 (clamp@1.0.1, **react@15.2.0**, react-addons-pure-render-mixin@15.2.0, fbjs@0.8.3, babel-plugin-syntax-flow@6.8.0, babel-plugin-transform-flow-strip-types@6.8.0, babel-cli@6.10.1, babel-preset-react-native@1.9.0)
```

**Comment by rturk** [comment]
@andyschwob can you simply migrate to the latest stable react 15.2?

**Comment by andyschwob** [comment]
we can close this, i updated to a newer version of node and did a npm clean and project clean and it's working now.  thanks @rturk
