### ISSUE TITLE
add authrization to flux

### ISSUE THREAD

**Issue by charlesluo2014** [aksonov/react-native-router-flux#909]
hi,this framework is good!
how can i add the authorization with few code！

 <Scene key="contacts" auth={true} component={ContactListView} title="contacts" ></Scene>

add the auth properties

**Comment by rturk** [comment]
Hi @charlesluo2014 not sure what do you mean. In order to implement Authorization in any App you need to build your own custom logic, handle user input, serverside integration, etc.

**Comment by charlesluo2014** [comment]
hi,@rturk 
the case is,when some page dose not need to Authorization and others need,the normal way to Authorization is
```
 if(isLogin()){
    Actions.login();
}else{
    ....//render
}

```
so it has many page,this code will appear many times.
is That any way to make it configable?

**Comment by rturk** [comment]
Hi @charlesluo2014 I don't see any problem on the code above, it's simple, clean and clearly states that only if some is logged a particular scene will be rendered..  I have multiple `auth` blocks like the one you described above in my apps.

As always PR's are always welcome.

If you don't have any further questions, can you please close this?

**Comment by cridenour** [comment]
I'm going to close as this has nothing to do with this library and is more of an architecture question. Feel free to re-open if I'm misunderstanding!
