### ISSUE TITLE
componentWillUnmount not called when I go to new route

### ISSUE THREAD

**Issue by sslash** [aksonov/react-native-router-flux#91]
componentWillUnmount dosnt trigger when I go to a new route that is part of a tabBar router.
It happens when I to Action.toMyOtherRoute(), and when I press on one of the other buttons in the tabBar. 
The problem with this is that if a reducer updates the store that the "Old-route" listens to, the old-route will re-render.

**Comment by aksonov** [comment]
But 'old-route' still in the nav stack (that is why it will not be unmounted), right? Looks like it is not connected with this component, but general redux/flux question. I'm solving it by checking if route is "current route" then update, otherwise don't update.

**Comment by sslash** [comment]
how do you check if the component is "current route"? I can't see any such property on the route component

**Comment by Durgaprasad-Budhwani** [comment]
@aksonov  Have you found any solution for this fix ?

**Comment by aksonov** [comment]
Please check latest 2.0 version. There is Actions.currentRouter property and Router has currentRoute property as well, so you could use Actions.currentRouter.currentRoute

**Comment by michalpetrov** [comment]
I'm not sure if this is the same problem, but when I have tabbar router with tree routes in it and I click on the tab button, then Tabs component is rerendered four times. The view seems to be switched immediately but applying the "selected" style on the new selected tab button is lagging cca 1 second.

**Comment by aksonov** [comment]
@sslash check Actions.currentRouter.currentRoute

**Comment by aksonov** [comment]
@michalpetrov i saw such behavior as well, it seems not connected with this issue. You may create new ticket, PR is welcome!

**Comment by sslash** [comment]
@aksonov the problem with Actions.currentRouter.currentRoute is that if your current route is inside a tabBar, its name resolves to the tabBar route, not the current (nested) child route. Say I have
```
<Route name="tabbar">
                    <Router footer={TabBar} hideNavBar>
                    <Route name="home" schema="tab" component={Home} />
</Route>
```
And I am currently on "home", Actions.currentRouter.currentRoute.name = tabbar and not home

**Comment by aksonov** [comment]
Strange, with 2.0.9 I've fixed that - it should deep into child route after Actions.route method:

```
            // deep into child router
            while (router.currentRoute.childRouter){
                router = router.currentRoute.childRouter;
                debug("Switching to child router="+router.name);
            }


```

**Comment by tonyneel923** [comment]
@aksonov Is Actions.currentRouter.currentRoute still the recommended way to do this? I cannot seem to get this to work in 3.32.0

**Comment by pewh** [comment]
+1 latest version doesn't have `Actions.currentRouter` anymore. So how to access `currentRoute`?

**Comment by bulkyracehorse512** [comment]
@pewh have you found a solution for this?

**Comment by pewh** [comment]
create `_createReducer` function:
```
  _createReducer = (params) => {
    const { dispatch } = this.props
    const defaultReducer = Reducer(params)

    return (state, action) => {
      if (action.type === ActionConst.FOCUS) {
        dispatch(updateScene(action.scene.name))
      }

      return defaultReducer(state, action) 
    }
  }
```

then in render, 
```
return (
      <Router
        scenes={routes}
        createReducer={this._createReducer}
     ...
      />
    )
```

`updateScene` is just a redux action. Here is my `updateScene` function:
```
export function updateScene(sceneName) {
  return (dispatch, state) => {
    dispatch(createAction('SET_ROUTE')(sceneName))
  }
}
```

then in reducer:
```
export const routeReducer = handleActions({
  SET_ROUTE: (state, action) => ({
    ...state,
    currentScene: action.payload,
  }),
}, { currentScene: '' })
```

What I've done is simulate `Actions.currentRouter` function by create own reducer. Hope it solve your problem.
