### ISSUE TITLE
0.29 support?

### ISSUE THREAD

**Issue by ivpusic** [aksonov/react-native-router-flux#910]
is it coming soon? I see inactive branch related to 0.29 but no release so far

**Comment by aksonov** [comment]
Check Readme, current version of RNRF doesn't depend from RN version anymore.

**Comment by gregorpilz** [comment]
i get 'Check the render method of Router' on 0.29

**Comment by danieldunderfelt** [comment]
Weird... 0.29 & RNRF user here, works well!

**Comment by cridenour** [comment]
@gregorpilz Any more details on the error with 0.29? Can you run the Example app and provide a screenshot?

**Comment by lifehackett** [comment]
Is there a timeline to upgrade the fork that RNRF depends on?  I am experiencing a bug that in looking through the `react-native@0.30.0-rc` release notes it may address the issue.  Just want to evaluate my options.

**Comment by rturk** [comment]
@danieldunderfelt please note that RNRF don't use React Native core navigation anymore. Due to the increasing number of breaking changes. RNRF use a form https://github.com/aksonov/react-native-experimental-navigation please look at package.json

**Comment by rturk** [comment]
@lifehackett RNRF already works with RN29 (please check comment above), well at least my app works.

**Comment by lifehackett** [comment]
The package.json indicates version 26 https://github.com/aksonov/react-native-router-flux/blob/master/package.json

So your app may work because the things you are using didn't break between 26 to 29, but others could be using things that changed and broke or in my case there seems to be a bug in 26 that is addressed in 30.

**Comment by danieldunderfelt** [comment]
@rturk I am aware, yes. I was simply confirming that it works as @gregorpilz experienced some issues.

**Comment by gregorpilz** [comment]
hi guys i have forget to update the package.json :)
thx

**Comment by luhui** [comment]
Got `native module cannot be null ` error with 0.29 on iOS, any ideals?

**Comment by GantMan** [comment]
this is working for me in 0.29, is this ticket still live?

**Comment by lifehackett** [comment]
There is a difference between working with 0.29 and supporting 0.29.  This DOES work side by side with 0.29, but DOES NOT support 0.29 since the package.json still specifies 0.26
