### ISSUE TITLE
How to set initial route

### ISSUE THREAD

**Issue by haabnaseem** [aksonov/react-native-router-flux#913]
How to set initial route based on state ? let's say if user is logged in select another route, how to switch between them, i have seen a switch feature but it is using with tabs ? anyone can show example code.

**Comment by kaenry** [comment]
need too.

**Comment by sithobog** [comment]
Hi!:P
I have needed the same feature. So i did something:P
 I'm using 'loading' in state because in other way component will be rendered twice (because i have async action in componentWillMount).
I have authentication by token, so if i have token in storage so user can be logged and MainVIew is initial scene. If i don't have token LoginView is initial scene.

You can use any condition to check if user 'logged in' or whatever you want. You can change ugly loading for some epic animation:D
```
  constructor(props, context) {
    super(props, context);
    this.state = {
      logged: false,
      loading: true,
    };
  };

  componentWillMount(){
    self = this;
    AsyncStorage.getItem('token')
    .then( (value) =>{
        if (value != null){
          this.setState({
            logged: true,
            loading: false,
          });
        } else{
          this.setState({
            loading: false,
          })
        }
      }
    );
  };

  render() {
    if (this.state.loading) {
      return <View><Text>Loading...</Text></View>;
    }
    return (
      <Router>
        <Scene key='root'>
          <Scene key='login' component={LoginView} title='Login' initial={!this.state.logged} />
          <Scene key='main' component={MainView} title='Main' initial={this.state.logged} />
        </Scene>
      </Router>
    )
  }
```

**Comment by rturk** [comment]
@haabnaseem @kaenry @sithobog Check this code. It's from Facebook code. It's a simple elegant approach. If the user is not logged it will show login screen, otherwise when authorized the full app. Works really well.

https://github.com/fbsamples/f8app/blob/master/js/F8App.js#L80

**Comment by haabnaseem** [comment]
@rturk Thanks will check it out too!, @sithobog 👍 the code you shared
works well, thank you very much

**Comment by cridenour** [comment]
Another approach is to have the initial screen be the login screen as it checks for the AsyncStorage token and on finding that token, calling `Actions.main` or whatever your other screen should be.

**Comment by shenders13** [comment]
Hi there, I initially tried @sithobog's approach and that worked fine until I had to nest my "root" Scenes inside a "modal" scene. Applying my situation to @sithobog's example, the code would be:

```
constructor(props, context) {
    super(props, context);
    this.state = {
      logged: false,
      loading: true,
    };
  };

  componentWillMount(){
    self = this;
    AsyncStorage.getItem('token')
    .then( (value) =>{
        if (value != null){
          this.setState({
            logged: true,
            loading: false,
          });
        } else{
          this.setState({
            loading: false,
          })
        }
      }
    );
  };

  render() {
    if (this.state.loading) {
      return <View><Text>Loading...</Text></View>;
    }
    return (
      <Router>
        <Scene key="modal" component={Modal}>
          <Scene key="root">
            <Scene key='login' component={LoginView} title='Login' initial={!this.state.logged} />
            <Scene key='main' component={MainView} title='Main' initial={this.state.logged} />
          </Scene>
          <Scene key='alert' component={Alert} hideNavBar/>
        </Scene>
      </Router>
    )
  }
```

In this circumstance, which ever Scene is placed first in the "root" container is set as the initial scene i.e. the "initial" prop is no longer respected once the "modal" Scene is added to the equation. So LoginView would always be rendered initially even if `this.state.logged` was `true`.

Thanks very much in advance :)

Sam

**Comment by ZainabShakeel** [comment]
Using React-native-router-flux.... i initialized my initial scenes with the access of user login...
import React, {Component} from 'react';
import {AsyncStorage } from 'react-native';
import {Platform,Router, Stack, Scene} from 'react-native-router-flux';
import firebase from 'react-native-firebase'
import Login from './Login';
import Signup from './Signup';
import Home from './Home';
import Record from './Record';
export default class Routes extends Component{
  constructor(props, context) {
    super(props, context);
    this.state = {
      logged: false,
      loading: true,
    };
  };

  componentWillMount(){
  
    var user = firebase.auth().currentUser;
    console.log(user);
    if(user!=null)
    {
      this.setState({
        logged: true,
        loading: false,
      });
    }
   
  };

  render() {
    return (
        <Router>
        <Stack key="root" hideNavBar={true}>
        <Scene key="signup" component={Signup} title="Signup"/>
          <Scene key="login" component={Login} title="Login" initial={!this.state.logged} />
          <Scene key="home" component={Home} title="Home" initial={this.state.logged}/>
          <Scene key="record" component={Record} title="Record"/>
        </Stack>
     </Router>
            );
  }
}

**Comment by ZainabShakeel** [comment]
Using React-native-router-flux.... i initialized my initial scenes with the access of user login...

import React, {Component} from 'react';
import {AsyncStorage } from 'react-native';
import {Platform,Router, Stack, Scene} from 'react-native-router-flux';
import firebase from 'react-native-firebase'
import Login from './Login';
import Signup from './Signup';
import Home from './Home';
import Record from './Record';
export default class Routes extends Component{
  constructor(props, context) {
    super(props, context);
    this.state = {
      logged: false,
      loading: true,
    };
  };

  componentWillMount(){
  
    var user = firebase.auth().currentUser;
    console.log(user);
    if(user!=null)
    {
      this.setState({
        logged: true,
        loading: false,
      });
    }
   
  };

  render() {
    return (
        <Router>
        <Stack key="root" hideNavBar={true}>
        <Scene key="signup" component={Signup} title="Signup"/>
          <Scene key="login" component={Login} title="Login" initial={!this.state.logged} />
          <Scene key="home" component={Home} title="Home" initial={this.state.logged}/>
          <Scene key="record" component={Record} title="Record"/>
        </Stack>
     </Router>
            );
  }
}

**Comment by Moji0098** [comment]
dear @sithobog , this post is for 2016 , did we have any resolve for this now ? for example how to we implement this with **switch** in RNRF ?
