### ISSUE TITLE
Respond to the START of a Scene transition from within a Scene's child component

### ISSUE THREAD

**Issue by dmwallace** [aksonov/react-native-router-flux#917]
Is there a way to respond to the START of a Scene transition from within a Scene's child component?

I have audio playing which I stop within componentWillUnmount.  componentWillUnmount is only triggered at the completion of a scene transition (and only when popping a scene, not pushing).

I'd like to be able to stop the audio as soon as the transition is triggered while keeping that logic encapsulated within the relevant component. (i.e. without creating global audio control logic)

**Comment by cridenour** [comment]
You can listen to the reducer - check the Example app for a way to do this.
