### ISSUE TITLE
Actions.pop to transfer state

### ISSUE THREAD

**Issue by afilp** [aksonov/react-native-router-flux#918]
Latest version>

I could not find how the POP can transfer state so that the targeted component starts with that instead.

**Comment by cridenour** [comment]
You can do 

```js
Actions.pop();
Actions.refresh(newProps);
```

**Comment by af7** [comment]
Thank you, what happens in the meantime? Does the component receive the old props? Does it render without any? Or is this immediate?

**Comment by momo-Flanny** [comment]
I think no api can support, and I've resolved the by sendding  an  event

**Comment by af7** [comment]
@momo-Flanny Thanks, can you please explain a little how you did this?

**Comment by cridenour** [comment]
@af7 I also believe you can do `Actions.refresh({key: 'sceneKey', ...newProps})` followed by pop - but I have not tested that.
