### ISSUE TITLE
Spread operator support

### ISSUE THREAD

**Issue by helsont** [aksonov/react-native-router-flux#919]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.22.23
- react-native v0.?.?

### Expected behaviour
See https://facebook.github.io/react/docs/jsx-spread.html

**Comment by charpeni** [comment]
Spread operator should be already supported, what are you trying to achieve?

**Comment by helsont** [comment]
Sure, here's my code:
```
const getSettingsTab = (topPadding) => {
  const opts = {
    key: 'settings',
    title: 'More',
    icon: { TabIcon }
  };
  return (
    <Scene {...opts}>
      <Scene
        key="tab2_1"
        title="Settings"
        component={SettingsContainer}
        sceneStyle={{ paddingTop: topPadding }}/>
    </Scene>
  );
};
//...
render() {
    const topPadding = Platform.OS === 'ios' ? IOS_TOP_PADDING : ANDROID_TOP_PADDING;
    const settingsTab = getSettingsTab(topPadding);
    // abbreviated scene initialization
    return (
      <RouterWithRedux>
        <Scene key="tabbar"
          tabs={true}
          type="reset">
          { settingsTab }
        </Scene>
      </RouterWithRedux>
    );
  }
```
![simulator screen shot jul 11 2016 11 52 51 am](https://cloud.githubusercontent.com/assets/1709344/16737164/10ffd956-475e-11e6-9ca6-9fd26f8f444f.png)

If I use the key value pairs in `opts` directly in the JSX, it works as expected.

**Comment by AntonNiklasson** [comment]
You should probably change your options from this:
```
const opts = {
  key: 'settings',
  title: 'More',
  icon: { TabIcon }
};
```
To this:
```
const opts = {
  key: 'settings',
  title: 'More',
  icon: TabIcon
};
```

**Comment by cridenour** [comment]
@AntonNiklasson is correct. Using `{}` is necessary in JSX but when you use it in the JS object, it creates a child object holding the TabIcon and not just the TabIcon as expected.

**Comment by helsont** [comment]
Didn't catch that. Thanks!
