### ISSUE TITLE
The style of navigation bar in the scene which is poping changed to white background

### ISSUE THREAD

**Issue by imWildCat** [aksonov/react-native-router-flux#922]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.x
- react-native v0.29.0
### Expected behaviour

The style of navigation bar in the scene which is poping does not change.
### Actual behaviour

The style of navigation bar in the scene which is poping changed to white background.

Screenshot:

![qq20160713-2](https://cloud.githubusercontent.com/assets/2396817/16797377/d1ba36ca-4919-11e6-86ee-645939177f59.png)

GIF:
![bug_2](https://cloud.githubusercontent.com/assets/2396817/16797335/a7b94faa-4919-11e6-9cfb-60c9009ce3bf.gif)
### Steps to reproduce

``` js
...
      <Provider store={store}>
        <RouterWithRedux backButtonImage={require('../components/assets/back_icon.png')}>
          <Scene
            key="root"
            titleStyle={styles.titleStyle}
            navigationBarStyle={styles.navigationBarStyle}>
            <Scene key="tabbar" tabs={true} tabBarStyle={styles.tabBar}>
              <Scene key="discovery"
                     component={DiscoveryTabPageContainer}
                     titleStyle={styles.titleStyle}
                     navigationBarStyle={styles.navigationBarStyle}
                     icon={TabIcon}
                     initial={true}
                     title="Wetoo"/>
...
```

**Comment by cridenour** [comment]
@imWildCat Thanks for the detailed report. This definitely seems like a bug on our end - but I'll have to play with the Example app to make sure. 

In the mean time, can you try adding `navigationBarStyle={styles.navigationBarStyle}` to your `tabbar

**Comment by imWildCat** [comment]
![nav](https://cloud.githubusercontent.com/assets/2396817/16828142/bec13f86-49bf-11e6-9197-1766a6b2554e.gif)
Thanks for your respond. 
I added `navigationBarStyle={styles.navigationBarStyle}` for `tabbar`, but I seemed not working too.

**Comment by vinayr** [comment]
I am having same issue. I use dark background for my navigation bar and whenever I hit back button the background changes to white before scene transition. @imWildCat did you find any workaround?

**Comment by vinayr** [comment]
Changing the `backgroundColor` of `sceneStyle` to the same color as navigation bar's background color fixes for me.
```
<Router sceneStyle={{ backgroundColor: 'black' }}>
</Router>
````

**Comment by waqas19921** [comment]
Having same issue

**Comment by cridenour** [comment]
@waqas19921 Does the solution posted by @vinayr work for you?

**Comment by waqas19921** [comment]
No this problem lies with `tabbar` changing `router sceneStyle` changes the background of every scene.

**Comment by ryanoboril** [comment]
Overriding getSceneStyle() worked for me.

```
<Router
    getSceneStyle={() => {
        return {backgroundColor: sceneBackgroundColor};
    }}>
```

**Comment by mklb** [comment]
For everyone still having the same issue in late 2018 with V4.
It happened to me when transitioning from a view with a navigation bar (and a navigationBarStyle obviously) to a scene which had `hideNavBar={true}`. Setting a `navigationBarStyle` with backgroundColor transparent for the scene without a nav bar solved it for me.
