### ISSUE TITLE
How to detect Scene change/tab change? 

### ISSUE THREAD

**Issue by josh-deprogram** [aksonov/react-native-router-flux#925]
How do I detect when the current scene is in focus when changing routes?
The first time around componentDidMount is called but the components are not unMounted on scene change or additional route updates so there a method of knowing?

**Comment by cridenour** [comment]
Please see the Example app here: https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L56

If you're using redux, you can follow this guide: https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

**Comment by brien-crean** [comment]
@designbuildplay Further to what @cridenour suggested If you are using something like redux this is how I am detecting a tab change:

Listen for a "jump" action, and then change state in order to hook into one of the React lifecycle hooks like componentDidUpdate or componentWillReceiveProps.

```javascript
// listen in reducer for tab1 selected
// Note: jump action is fired by defaultReducer attached to main Router (see example project)
case "jump":
      if(action.key=="tab1") {
        return {
          ...state,
          tab1: true
        }
      }

// reset tab1 to false (triggered by action call in component)
case TAB_ONE:
      return {
        ...state,
        tab1: false,
      }
```

```javascript
// Tab 1 Component
  componentDidUpdate(prevProps) {
    // on tab1 press
    if(this.props.tab1) {
      console.log("Tab 1 Pressed")
      // fires TAB_ONE action
      this.props.resetTab()
    }
  }
```

**Comment by irisSchaffer** [comment]
One problem with this approach is that you need to add a new variable for every new tab you introduce. Furthermore, this only applies for tabs.
The question was

> How do I detect when the current scene is in focus when changing routes?

While it is possible to listen for `JUMP` on a switch of tabs, listening to `FOCUS` won't do the trick, because the focused scene after a jump seems to be the parent tabs scene.

**Comment by asrytis** [comment]
The lack of onEnter/onLeave support is very inconvenient. Say I need some data refreshed whenever user gets to the Home screen. I can't think of a better way than doing the following:

```
componentWillReceiveProps(nextProps) {
    const scene = this.props.router.scene.key;
    const nextScene = nextProps.router.scene.key;
    
    if (scene !== nextScene && nextScene === this.props.sceneKey) {
        // This component is getting focused
        this.props.refreshData();
    }
}
```
This is ugly and I don't want to see this code in every component that needs to act on something when the scene gets focused. Few solutions come to my mind neither of which I am happy with:

1. capture & act upon router actions in custom middleware
2. create a base class that will run automatically run the check and call componentDidFocus()

Any thoughts on this anyone?

**Comment by cridenour** [comment]
@asrytis Are you leveraging the reducer in your app? This type of logic shouldn't be something that lives on your component. If there are issues with the reducer stopping you from using it, I think that would be the best place for us to start.

**Comment by asrytis** [comment]
@cridenour I do have reducers but those aren't meant for API calls. The way I'd do this in a web app is either use onEnter hook in a Route definition:

`<Route path="home" component={Home} onEnter={doWhateverAPICallsINeed} />`

or leverage one of component lifecycle methods, such as
```
componentWillMount() {
    callWhateverApiINeed();
}
```
The problem with react native router is I don't have neither of these options. Scenes never get unmounted and there is no alternative to onEnter other than performing the checks I posted above. I went with custom middleware for now but I'd love to hear how others tackle this issue.

**Comment by designbuildplay** [comment]
@aksonov It would be a great feature if Scenes where destroyed (Unmounted) on scene change, even if this was not default but a Prop option. Having a lot of scenes constantly mounted also can easily hit performance issues once navigating round an app if you aren't careful with shouldComponentUpdate()

**Comment by cridenour** [comment]
I believe that would have to be something built into react-native. This library lives on top of NavigationExperimental.

**Comment by tonyneel923** [comment]
@cridenour for the reducer I am correct in understanding it is possible to use altjs for this? If so how would I learn to do this? I do not have any experience with redux so I am having issues understanding how to use alt.

**Comment by cridenour** [comment]
@tonyneel923 Definitely. In your custom reducer function like https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L59 then you can call AltJS actions to save the current scene. 

Your stores can listen for these actions and act appropriately.

**Comment by tonyneel923** [comment]
```
    const reducerCreate = params=>{
      const defaultReducer = Reducer(params);
      console.log(params)
      return (state, action)=>{
          ConfigActions.setCurrentRoute(action.scene.name);
          return defaultReducer(state, action);
        }
    }
```
@cridenour  Something like this? Thanks for the help.

**Comment by cridenour** [comment]
@tonyneel923 Yup! Then in your various stores that your components listen to, bind to the ConfigActions.SET_CURRENT_ROUTE action and determine if you care about that scene. So if you have a "News" component and store, and you want to refresh every time they enter, then the NewsStore would bind to that action and determine whether to refresh when receiving that action.

**Comment by cridenour** [comment]
Also, for Alt specifically, if you already have the updated data but want to just have the component refresh, you can use `this.emitChange()`

**Comment by parkerdan** [comment]
@designbuildplay   The answer to your actual question is quite easy and provided by RN Navigator.

onDidFocus will tell you when a scene is "focused"
It's called with the route.

`<Navigator 
onDidFocus={ (route) => {console.log(route), doStuff() } }
renderScene={ renderScene }
configureScene={ configureScene }
/>`

**Comment by designbuildplay** [comment]
@parkerdan the focus method is not reliable if you have sub set Scene such as scenes within a tabs, then it is the tab scene container that gets focused

**Comment by stereodenis** [comment]
```
componentDidMount() {
  InteractionManager.runAfterInteractions(() => {
    this.setState({ ready: true })
  })
}
```

**Comment by af7** [comment]
I get `undefined is not an object` when evaluating `action.scene.name`. What is wrong?

**Comment by monumentyusuf** [comment]
@afilp Because it fires two different object as you can see below;
```
Object {key: "AlbumsTab", type: "REACT_NATIVE_ROUTER_FLUX_JUMP"}
Object {scene: [Object], type: "REACT_NATIVE_ROUTER_FLUX_FOCUS"}
```
You have to check `scene` object first like;
```
if(action.scene){
  console.log(action.scene.name);
}
```
`RNRF v3.37.0`

**Comment by AndrewHenderson** [comment]
I'm working on this issue at the moment. Has anyone made any progress on it?

**Comment by bulkyracehorse512** [comment]
@designbuildplay did you figure out how to ensure that components unmount on scene transitions?

**Comment by AndrewHenderson** [comment]
@bulkyracehorse512 Scenes within your root never unmount. For instance, if you're using tabs at the foundation of your application, those scenes will live with the lifecycle of the application itself.

**Comment by afilp** [comment]
@designbuildplay What do you mean " if you aren't careful with shouldComponentUpdate()"?

I am also worried of tens of screens remaining on the memory just for being available for a POP action. What is the best practice for this? Do you use shouldComponentUpdate() extensibly on every component, if yes how? Thanks!

**Comment by booboothefool** [comment]
I think this would help me: https://github.com/aksonov/react-native-router-flux/issues/1659

**Comment by booboothefool** [comment]
I think this would help my performance issues: https://github.com/aksonov/react-native-router-flux/issues/1659

UPDATE:
Holy crap @josh-deprogram, thanks for the tip. My app has a ton of tabs with long lists in each, and thanks to what you said, I just discovered they are all being re-rendered no matter which tab you go to. 

For example, 
[Tab 1][Tab 2][Tab 3][ Tab 4][Tab 5][Tab 6]

1) Go to Tab 4
2) Go to Tab 2
=> Tab 4 gets `componentWillReceiveProps()` and `render()`

so that means if you:
1) Go to Tab 1, 2, 3, 4, 5, 6
2) Go to Tab 3
=> Tab 1, 2, 4, 5, 6 gets 'componentWillReceiveProps()` and `render()` !!!

I think that would help explain why when you load all of the tabs in my app, it explodes? It's because when you click on a different tab... it re-renders all tabs that were previously mounted.

**Comment by roots-ai** [comment]
> Please see the Example app here: https://github.com/aksonov/react-native-router-flux/blob/master/Example/Example.js#L56
> 
> If you're using redux, you can follow this guide: https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

Links are broken.

**Comment by Samykills** [comment]
A simple solution to this is using the attribute onEnter of the <Scene> in router

For eg: `<Tabs
        key="mainTabScreen"
        hideNavBar
        hideTabBar
        lazy
        swipeEnabled={true}
        tabBarComponent={() => null}
        tabBarPosition="top"
      >
        <Scene
          key="profileScreen"
          component={ProfileScreen}
          hideNavBar
          onEnter={() => {
            console.warn("profile");
          }}
        />
        <Scene
          key="homeScreen"
          component={HomeScreen}
          hideNavBar
          onEnter={() => {
            console.warn("profile");
          }}
        />
      </Tabs>`

This will always trigger when u swipe for tab change
