### ISSUE TITLE
Requesting code sample for a "Float from bottom" transition

### ISSUE THREAD

**Issue by nlively** [aksonov/react-native-router-flux#926]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.0
- react-native v0.29.0

### Question

Certain scenes in my app need to slide up from the bottom when they are pushed onto the route stack and slide down when they are popped off the stack.

Prior to migrating my app to `react-native-router-flux`, I was able to specify a scene config using RN's Navigator.  The config I used is `Navigator.SceneConfigs.FloatFromBottom`.

Can someone please provide a code sample for how I could accomplish the same thing using the latest version of `react-native-router-flux`?

Thanks

**Comment by brien-crean** [comment]
The default transition animation is horizontal, just needs to be changed to 'vertical' in the Scene declaration, e.g.
```
<Scene key="Scene1" hideNavBar={true} component={Scene1} type="push" duration={200} direction='vertical' />
```
More info here:
https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#animation

**Comment by enapupe** [comment]
It is a shame that the docs are poorly organized and the source code for `<Scene>` has no `directio` proptype. I had no idea that the Animation section in the docs were to be applied  in the scene component.

**Comment by rturk** [comment]
Hi @enapupe PRs are always welcomed. This is a public project and as such you can help the team with new improved docs.

**Comment by enapupe** [comment]
@rturk I understand, but first I must understand the code/docs to be able to improve it..
