### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by Roilan** [aksonov/react-native-router-flux#927]
- react-native-router-flux v3.30.1
- react-native v0.29.0

I was looking over https://github.com/aksonov/react-native-router-flux/issues/205 and tried replicating what he did on the latest API and no luck getting a shared background image to render. Wondering if anyone has come across this or found a good way to do. I've provided my example Router component below.

https://gist.github.com/Roilan/c0058cd424389b9887483de5ca613255

The `Background` component, just has a `Image` with `children` being rendered inside of it.

Thanks!

**Comment by cridenour** [comment]
Why not just render the router inside a view with a background image?

**Comment by Roilan** [comment]
Thanks for your response @cridenour. Great suggestion and not sure why I didn't think of that before. So, I tried what you suggested and still having some issues with the transparent background. I provided a gist of how it looks now.

https://gist.github.com/Roilan/4e0942dceab4fd84897384729bffb40d

Seems like even with a transparent background it's still overlaying on top of the image.

**Comment by cridenour** [comment]
Does your home component have a transparent background set as well? I believe most react-native components default to non-transparent.

**Comment by Roilan** [comment]
Yeah, I've tried setting the `home` component background to `transparent`. No luck either. If I set it to another color, it takes over the whole background, it makes me believe that `Background` is just laying behind everything even when we set the background. Thoughts?

**Comment by brien-crean** [comment]
@Roilan I tried something similar and could see that the `Background` component was there in the component tree, by using the Nuclide React Native Inspector but I could not get it to render. I tried playing around with the new zIndex for iOS also but nothing I did seemed to help

**Comment by Roilan** [comment]
@brien-crean Thanks for looking into it. I'm having the exact same issue. Not sure what else to try. Maybe it's worth looking into add the option for a background component.

**Comment by Roilan** [comment]
Found the issue. So, it's related to this https://github.com/aksonov/react-native-router-flux/issues/448 the `backgroundColor: transparent` was removed. Manually setting the background to transparent in the `NavigationCard` works but throws errors due to shadows. @cridenour @aksonov any thoughts on if it's even possible to do this?

**Comment by Roilan** [comment]
Quick update, I found the issue. The deep inside the `NavigationCard` component, it has a `shadowColor` and `backgroundColor`. Setting both to `transparent` fixes it. I'll be making a PR shortly for optional style in the `NavigationCard` to override this.

**Comment by Roilan** [comment]
Solved using `getSceneStyle` more info on https://github.com/aksonov/react-native-router-flux/pull/931#issuecomment-233105349

**Comment by Jlexyc** [comment]
ComponentWrapper put new background for new scene, so transition effect (like changing only content) is not achieved.

Idea is to leave the same image on the same place, but change scenes with transparent background in foreground. But i've got that old scene doesn't disappear. So maybe some solution how to make old scene disappear?

**Comment by matAlmeida** [comment]
i'm having the same problem @Jlexyc . Did you figured out how to solve?
