### ISSUE TITLE
question about stack(history)

### ISSUE THREAD

**Issue by ReneMarquez** [aksonov/react-native-router-flux#930]
Hello everyone, so I have a question regarding the stack(history) of the router; is there a way to delete a route from the stack, so if at some point I go back (pop), that scene/route that I deleted does not show?

Right now what I'm doing is detecting if the route has a specific prop (using currentRouter.previousRoute) and then replacing with the scene that the user had visited before going to the scene I want to delete; the negative to this is if I press back again, the same scene is displayed again (due to being 2 times in the stack)

**Comment by cridenour** [comment]
The only way I can think to do this would hook up your own reducer and put the logic there, so you can affect the actual navigation state. 

I would check the current implementation of reset for changing the underlying navigation state.
