### ISSUE TITLE
Add ability to customize TabBar

### ISSUE THREAD

**Issue by LeBlaaanc** [aksonov/react-native-router-flux#933]
From what I can tell it doesn't seem it's possible to replace the TabBar similar to NavBar.

I get that I can change the icon but I'd like to change the press feedback away from TouchableOpacity. 

At the point is my only choice to connect redux and fire actions? Where do I put the TabBar component to allow for hiding in the event I'm showin a modal?

**Comment by cridenour** [comment]
In the scene where you set `tabs={true}` you can set the component like `component={MyTabBar}`. I suggest you copy src/TabBar.js as a starting point.

**Comment by LeBlaaanc** [comment]
@cridenour thanks so much this works awesome!
