### ISSUE TITLE
Action type replace has no animation

### ISSUE THREAD

**Issue by bunea** [aksonov/react-native-router-flux#939]
### Version
- react-native-router-flux v3.31.1
- react-native v0.28.0

I guess this is more of a question rather than a bug report but there doesn't seem to be any animation running when replacing a scene.

I couldn't find anything related to it in the documentation.

Is there any way to configure this behaviour?

**Comment by enapupe** [comment]
To me, it feels natural to just replace, not transition to it.. Why can't you use a regular push?

Regardless, I'm also looking for some information about animations and there is almost none, not even in the source code :/

**Comment by bunea** [comment]
There's a bug when using TextInputs and ScrollViews to scroll to the inputs when the keyboard opens ([facebook/react-native/pull/7876](https://github.com/facebook/react-native/pull/7876)).

We have an auth flow that goes from a sign in scene to a sign up one and it crashes on iOS. Using replace to navigate to the scene unmounts the previous component and unsubscribes from keyboard events so it doesn't crash any more but there are no animations which is a bummer.

**Comment by cridenour** [comment]
Yea unfortunately this is probably not something we'll add as the whole idea of replace is to change the component inline. 

That said, if you need to force unmount the previous scenes, there was work in #932 that should interest you. Not sure if it will fix this particular workaround.

**Comment by bunea** [comment]
Thanks for the response.

I understand why replace is implemented as it is. This was more of a
question as I could not find too much documentation on transition
animations so I thought it was worth a shot.

I've seen the merge regarding unmounting scenes in a switch component but
I'd rather not change anything in the library itself to avoid conflicts on
future updates.

In the mean time I've found a workaround by tracking router actions and
states but thanks for the clarification regarding replace behaviour.
