### ISSUE TITLE
Add styles to Tabbar

### ISSUE THREAD

**Issue by thachp** [aksonov/react-native-router-flux#94]
Tabbar at the moment is static defined to style={{backgroundColor:'white'}}

See https://github.com/aksonov/react-native-router-flux/blob/master/index.js#L447

            return (
            <Tabs style={{backgroundColor:'white'}} onSelect={this.onSelect.bind(this)} {...this.props}>
                {this.state.children}
            </Tabs>
        );

Can we pass in style instead?

**Comment by joshuarotenberg** [comment]
You can pass style into the router component:

```<Router footer={TabBar} showNavigationBar={false} style={{backgroundColor:'#cccccc', borderTopWidth:1, borderTopColor: '#cccccc'}} >```

**Comment by MITDelian** [comment]
@joshuarotenberg is correct. passing in your own style will override the default style

**Comment by rturk** [comment]
If I add a style as suggested above the top of screen will also show a border

    <Router footer={TabBar} showNavigationBar={false} style={{backgroundColor:'white', borderTopWidth:1, borderTopColor: '#00bb00'}} >

![simulator screen shot jan 21 2016 10 37 56 am](https://cloud.githubusercontent.com/assets/2236950/12480731/a3678cc2-c02b-11e5-965b-51eca2596492.png)

**Comment by aksonov** [comment]
Because style param is passed to component as well. You have to pass something like tabStyle and change TabBar to accept tabStyle as property.

**Comment by rturk** [comment]
@aksonov thanks. That's my guess. As @thachp commented style is fixed to 'white. I think we need a more robust way to augment style the tabbar using props. Similar to your code in the react-native-tabs.

**Comment by iclems** [comment]
Any update on a better way to do this?
