### ISSUE TITLE
Prevent Swipe gesture in 2.3.1

### ISSUE THREAD

**Issue by anton6** [aksonov/react-native-router-flux#942]
- react-native-router-flux v2.3.1
- react-native v0.24.1

Hi. 

I'm using an old version of react-native-router-flux.
I need to prevent swipe back gesture.

Is this possible in version 2.3.1?

I know about panHandlers={null}, however I don't think this is supported in v2.3.1.

Thanks.

**Comment by brien-crean** [comment]
@anton6 Try adding this to a Schema:
`<Schema name="noSwipe" sceneConfig={Navigator.SceneConfigs.HorizontalSwipeJump.gestures = null}/>`

Then add the schema to the Route like this

`<Route name="scene1" schema="noSwipe" component={Scene1} />`

Note that this will also disable transition animations. I could not find another way to disable gestures without disabling animations when I was running v2

**Comment by anton6** [comment]
@brien-crean 

Hi, yes I was actually doing that already, but thanks anyway.
