### ISSUE TITLE
Trying to work from the example app..

### ISSUE THREAD

**Issue by CrashyBang** [aksonov/react-native-router-flux#945]
### Version

Tell us which versions you are using: 

Sorry I know this issue is not super relative here but it is driving me nuts.

- react-native-router-flux v3.31.1
- react-native v0.27.0

### Expected behaviour

Want to be able to rename the app from `Example` in the code to `App`
I have posted about it here in detail: http://stackoverflow.com/questions/38477020/renaming-react-native-example-app/38477223#38477223

### Actual behaviour

When I try to update from `Example` to `App` it errors during the build and is still somehow referencing `Example`.

### Steps to reproduce

1. Rename `Example` everywhere to `App`
2. Try to compiler the `App`
3. It errors

**Comment by cridenour** [comment]
Maybe there are changes that need to be made in the Xcode project? I've never re-named a project before.

**Comment by CrashyBang** [comment]
@cridenour hmmmm I see okay I will keep digging and will post a solution here when I find one :).

**Comment by CrashyBang** [comment]
After running through this tutorial: http://blog.tylerbuchea.com/renaming-a-react-native-project/

I found the best way to handle this was to just remove the ios and android folders and run `react-native upgrade`

Cheers.
