### ISSUE TITLE
Is it possible to fire action when clicking on the title of the navbar

### ISSUE THREAD

**Issue by tsyirvo** [aksonov/react-native-router-flux#949]
### Version

- react-native-router-flux v3.31.1
- react-native v0.24.1

---

Hi,

I just wanted to know if it was possible to fire an action when the user click on the title of the page, such as what is implemented for the left or right buttons.

Cheers,

**Comment by cridenour** [comment]
For that, I would suggest forking the NavBar and passing it in as your own using `navBar` described here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#navigation-bar

**Comment by tsyirvo** [comment]
Thanks for putting me in the right direction :)  I managed to do what I needed! 
When i'll have time, I'll clean my code and submit a PR for this.
