### ISSUE TITLE
How to only show Navbar Title?

### ISSUE THREAD

**Issue by thachp** [aksonov/react-native-router-flux#95]
I want to remove the <Back> feature in the Navbar.  When tab1 first activate, I see "Tab 1" in the navbar, that I would like to keep.  When Tab2 is consequentially pressed, I see "Tab 2" in the navbar, but on the left of that, there is a "Tab 1" with the left arrow.    How do I remove it?

![screen shot 2015-12-26 at 6 09 05 pm](https://cloud.githubusercontent.com/assets/1495371/12008614/d1d7d8f8-abfb-11e5-90e5-975145481b70.png)
Below is a snippet from my sample app.  

    <Router hideNavBar={true}>
        <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
        <Schema name="modal" icon={TabIcon} sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
        <Route name="initial" component={Initial} initial={true} wrapRouter={true} title="Sign In"/>
        <Route name="register" title="Register" schema="default" component={Register}/>
        <Route name="tabbar" schema="modal">
            <Router footer={TabBar} showNavigationBar={true}>
                <Route name="tab1" schema="modal" title="Tab 1" component={TabView}/>
                <Route name="modal" schema="modal" title="X" component={TabView}/>
                <Route name="tab2" schema="modal" title="Tab 2" component={TabView}/>
            </Router>
        </Route>
    </Router>

**Comment by aksonov** [comment]
You should hide TabBar nav bar as well and add type='switch' for each Route (so nested nav bar will be generated for each tab), check Example.
