### ISSUE TITLE
Scene leaks through, and props question

### ISSUE THREAD

**Issue by richyzhu** [aksonov/react-native-router-flux#950]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.2
- react-native v0.27.1
### Expected behaviour

I followed the example from https://github.com/aksonov/react-native-router-flux/blob/master/docs/MINI_TUTORIAL.md.
### Actual behaviour

![page1](https://cloud.githubusercontent.com/assets/6087736/17027382/454f7374-4f29-11e6-8402-4541bc88af52.png)
![page2](https://cloud.githubusercontent.com/assets/6087736/17027383/46ae4876-4f29-11e6-8f06-ad96f538bd9f.png)

after the scene transition, the previous scene leaks through. What can I do change the opacity
### Steps to reproduce

this is my code for the root scene:

``` javascript
            <Router>
                <Scene key="root">
                    <Scene key="pageOne"  component={PageOne} opacity={0} title="PageOne" getInitialState={() => ({... this.props})} initial={true} />
                    <Scene key="pageTwo" component={PageTwo} opacity={0} hideNavBar={false} getInitialState={() => ({... this.props})} title="PageTwo" />
                </Scene>
             </Router>
```

also, is there any other way to pass all my props? currently I'm passing them to the scene using getInitialState, but if my props changes, the scenes would not get the updated props. Thanks for all the help.

**Comment by aksonov** [comment]
see #948

**Comment by richyzhu** [comment]
thanks for the prompt response!
also, is there any other way to pass all my props? currently I'm passing them to the scene using getInitialState, but if my props changes, the scenes would not get the updated props.

**Comment by kanekotic** [comment]
so i dont know if you solved @richyzhu , but as also it was difficult for me to find the solution to this second question you had you have to pass `{... this.props}` to the router not to the scene

```
<Router {...this.props} >
     //your scenes ....
</Router>
```

**Comment by dcolin** [comment]
I have the same problem, did someone find a solution to fade out opacity to zero?

**Comment by pr-rojan** [comment]
Hi @richyzhu 
Did you find answer to your second question?
I am too struggling with that.
Thank you
