### ISSUE TITLE
RN 0.30 Incompatibility

### ISSUE THREAD

**Issue by chadwilken** [aksonov/react-native-router-flux#954]
Just opening this up to see if there are plans to support the newest version (0.30) of RN since then killed `NavigationAnimatedView`?

**Comment by cridenour** [comment]
We forked NavigationExperimental to avoid conflicts like this. It should work fine, but let us know if that isn't the case!

**Comment by Durgaprasad-Budhwani** [comment]
I have migrated to RN0.30 version and my application is compatible with react-native-router-flux@3.31.2 version. @chadwilken you can close this issue.
