### ISSUE TITLE
Unmounting Scenes

### ISSUE THREAD

**Issue by hybrisCole** [aksonov/react-native-router-flux#955]
how do I unmount scenes? I'm concerned about not having memory leaks.

Regards,

**Comment by cridenour** [comment]
You can try out the new unmount prop as described in #932 - I haven't had a chance myself. In areas where we need memory, I usually use `type="reset"`

**Comment by ajoshdee** [comment]
Hi when i set unmountscenes to true, my app goes to the first scene before going to the second scene on the switch scene. this doesn't happen with the unmountscene prop and immediately goes to its specific scene

**Comment by ajoshdee** [comment]
It has something to do with the order which the scenes are placed,

**Comment by cridenour** [comment]
@ajoshdee Go ahead and open a new issue - don't believe it fits with this. Thanks!

**Comment by labtorie** [comment]
I had to use a wrapper around the component 
```
const ChatKiller = (props) => { // workaround to unmount chat when its tab is not active
    const [active, setActive] = useState(true)
    const scene = Actions.currentScene
    const sceneNames = [
        '_SupportChat',
        'SupportChat',
        'CourierChat',
        '_CourierChat',
    ]

    useEffect(()=>{
        setActive(sceneNames.includes(scene))
    }, [scene])

    if (!active) return null
    return <Chat {...props}/>
}
```
