### ISSUE TITLE
Possible To Use Existing Routes & Components?

### ISSUE THREAD

**Issue by flyingace** [aksonov/react-native-router-flux#96]
Is there any way to configure the router so that if a route or component that has already been called is called again it re-uses the route/component rather than adding another to the stack?

Is there a way to search the stack to see if the same route is already in the stack and then return it to the top of the stack?

Is there a way to determine what the current route is so that it can be checked against the Action that is being called?

**Comment by aksonov** [comment]
please check 'jump' type for newly released 2.0 version. It is actually the same as 'switch', but without inserting nested nav bar inside (which is useful for tab bars)
