### ISSUE TITLE
Failed to build DependencyGraph: @providesModule naming collision:

### ISSUE THREAD

**Issue by sugeivan** [aksonov/react-native-router-flux#960]
Duplicate module name: AutoFocusUtils
  Paths: /home/sugeivan/react/SampleAppMovies/node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react/lib/AutoFocusUtils.js collides with /home/sugeivan/react/SampleAppMovies/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /home/sugeivan/react/SampleAppMovies/node_modules/react-native-router-flux/node_modules/react-native-experimental-navigation/node_modules/react/lib/AutoFocusUtils.js collides with /home/sugeivan/react/SampleAppMovies/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/home/sugeivan/react/SampleAppMovies/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /home/sugeivan/react/SampleAppMovies/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25

**Comment by aksonov** [comment]
Remove node-modules and run install again.

**Comment by TheoGit** [comment]
Any fixes for this?  I didn't get this error until installing xCode 8 - that's when everything went bad

**Comment by jcollum** [comment]
This happened to me when I installed with Yarn but not with NPM.

**Comment by Antonhansel** [comment]
Same when using Yarn, works fine with npm

**Comment by gritzko** [comment]
Occurs randomly in my case, npm, Xcode 8.

**Comment by ndbroadbent** [comment]
@aksonov this is happening because your npm package accidentally includes it's own internal `node_modules` directory. I ran into this problem when I was trying to fork `react-native-experimental-navigation` and use my own version.

Can you please setup the `files` directive in your `package.json` to only include the necessary files, and then push a new package to npm? Thanks!

**Comment by aksonov** [comment]
Could you submit PR?

**Comment by ndbroadbent** [comment]
@aksonov Sorry ignore me! The npm packages are fine, I think I was just running into a weird bug with `yarn`. You're right, you just need to remove `node_modules` and reinstall.

**Comment by vongohren** [comment]
I had this problem today, and I downgraded react-native-router-flux one version. Then it suddenly worked. But I believe that its not the router flux library that is the problem, but some NPM stuff. But you could try to downgrade that, or some random library to see if my thoughts are correct.

**Comment by clevertree** [comment]
To solve this problem I had to explicitly state the version
    "react-native-router-flux": "3.38.0",

If you do:
    "react-native-router-flux": "^3.38.0",
Then the later version with the 127 phantomChildren libraries will be used instead and break building. Corporate sabotage?

**Comment by daviscabral** [comment]
Corporate sabotage? It sounds more like the regular "copy and paste without knowing what I am doing" as usual stuff instead of locking versions in the right way. ;-)

**Comment by clevertree** [comment]
@daviscabral I disagree. Plus I have evidence to show the package.json files of older versions of npm libraries may have been modified in such a way that they break continuous integrations like appcenter. You don't seem to be actually debating me, or you seem to be confused, so I suggest you ask me for clarification, if that's what you need. Bad attitude isn't going to help this current widespread problem.

**Comment by daviscabral** [comment]
Alright - show me both things - where my joke shows bad attitude and where is our sabotage here. Thank you.

**Comment by aksonov** [comment]
@clevertree Why do you spam closed issues? It is open source project, your 'corporation' didn't do anything to help. Why you can't just create detailed ticket with exact errors you got instead of spamming several tickets with the same 'corporate sabotage' abuse.

**Comment by clevertree** [comment]
@aksonov I posted a solution to an actual problem that has not been solved, even if the thread is closed. Instead of helping @daviscabral attack me, you could point me at an already open ticket which suggests this solution, as I have found none. If there is none, then I would suggest you leave my solution here, so that other people who found this problem and can't upgrade to @4 can use it. Is that not protocol?
