### ISSUE TITLE
Margin top mandatory on each scenes ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [aksonov/react-native-router-flux#962]
### Version

- react-native-router-flux v3.31.2
- react-native v0.29.2

### Expected behaviour

When making a Scene, the Component given in props is displayed above the navigation bar

### Actual behaviour

I have to add a top margin of at least 70 to have my component rendered above the navigation bar. Is it normal ? Is their a way to apply a margin to all the scenes ?

### Steps to reproduce

```es6
const Home1 = () => (
	<View style={{margin: 70}}>
		<Text>Welcome to the Home page 1</Text>
	</View>
)

const Home2 = () => (
	<View style={{margin: 50}}>
		<Text>Welcome to the Home page 1</Text>
	</View>
)

const App = () => (
	<Router>
		<Scene key="root">
			<Scene key="home1" component={Home1} title="Home1" initial />
			<Scene key="home2" component={Home2} title="Home2"/>
		</Scene>
	</Router>
)

AppRegistry.registerComponent('App', () => App);
```

<img width="200" alt="home1" src="https://cloud.githubusercontent.com/assets/3855602/17057774/3b6c8608-5014-11e6-966c-897b58c0564c.png">

<img width="200" alt="home2" src="https://cloud.githubusercontent.com/assets/3855602/17057777/4042c944-5014-11e6-9c78-234388c281c9.png">

**Comment by cridenour** [comment]
Since the navBar is absolutely positioned, this is normal AFAIK. However, since some of us don't use the navBar or have a transparent background, adding this margin automatically wouldn't be ideal.

**Comment by EmrysMyrddin** [comment]
Ok, thank you for your answer. In fact, after a little thinking, I just have to make a component to do that... Sorry for the obvious question !
