### ISSUE TITLE
Redundant UI didn't get cleared by `Switch`

### ISSUE THREAD

**Issue by Arthraim** [aksonov/react-native-router-flux#965]
I'm using the `Switch` which shows UI by state, but if both state got triggered, both UI would be in ram (in View hierarchy).

Let's say I have a UI `A` for user who didn't login, `B` for a user who logged in. 
1. When user first came, `A` presents, and after he logged in, switch to `B`. Now, both `A` and `B` are in ram, which is not a good idea.
2. When user loggedin last time and come again, `B` presents. Then if he logged out, switch to `A`.  both `A` and `B` are in ram as well.
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.31.0
- react-native v0.29
### Expected behaviour

The UI got switched off will get removed from hierarchy and cleared from ram.
### Actual behaviour

Both of them (on or off) are in ram and hierarchy.
### Steps to reproduce
1. create something like following

```
<Scene key="main"
               component={connect(state => ({login: state.getIn(['auth', 'login'])}))(Switch)}
               tabs={true}
               selector={(props: {login}) => {return (props.login ? 'dashboard' : 'welcome')}}>
    <Scene key="dashboard" />
    <Scene key="welcome" />
</Scene>
```
1. add `login` info to state
2. both `dashboard` and `welcome` would be in hierarchy

**Comment by sarovin** [comment]
See this #932 and this #958

**Comment by ms88privat** [comment]
@Arthraim please try the newest version of router-flux and then add the prop "unmountScenes" to your Switch component. E.g.:

```jsx
<Scene key="main"
               component={connect(state => ({login: state.getIn(['auth', 'login'])}))(Switch)}
               tabs={true}
               unmountScenes
               selector={(props: {login}) => {return (props.login ? 'dashboard' : 'welcome')}}>
    <Scene key="dashboard" />
    <Scene key="welcome" />
</Scene>
```
