### ISSUE TITLE
How is the header implemented in the Example app

### ISSUE THREAD

**Issue by CrashyBang** [aksonov/react-native-router-flux#967]
### Version
Tell us which versions you are using: 

- "react-native-router-flux": "^3.31.2"
- "react-native": "^0.27.0"

Sorry I have spent hours trying to figure this one out but it is still stumping me.

Where on earth does this header come from:

<img width="624" alt="screen shot 2016-07-24 at 7 10 23 pm" src="https://cloud.githubusercontent.com/assets/2978850/17082452/1b476396-51d3-11e6-8008-947a2da8aec1.png">

I think it probably comes from a module as I could not find any reference what so ever in the default code.

Cheers.

**Comment by CrashyBang** [comment]
Shoot sorry, figured out it comes from this package, what would be the best way to disable this?

**Comment by cridenour** [comment]
Add `hideNavBar={true}` to your root Scene.
