### ISSUE TITLE
How to reset tabs?

### ISSUE THREAD

**Issue by nlively** [aksonov/react-native-router-flux#970]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.0
- react-native v0.29.0

### Request

My app uses Redux + the tabs feature to switch between tabs based on state.  Our app also implements the concept of logging in and logging out.  When a user logs out, we'd like to reset all tabs to their original state (i.e. pop everything off each stack) so that a new user can log in without the previous user's windows open.

What's the best way to do this?

Thanks

**Comment by cridenour** [comment]
Have you tried navigating to a tab with `Actions.sceneKey({type: 'reset'})`?

**Comment by cridenour** [comment]
Actually, this sounds exactly like what #932 was introduced to solve.

**Comment by nlively** [comment]
@cridenour you are correct.  I was able to add `unmountScenes={true}` to my root scene after this pull request was merged and it all works now.
