### ISSUE TITLE
How to keep the navbar displayed and fixed ? (w/ GiftedMessenger)

### ISSUE THREAD

**Issue by Brokray** [aksonov/react-native-router-flux#972]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.31.2
- react-native v0.28.0
- [react-native-gifted-messenger v0.1.4](https://github.com/FaridSafi/react-native-gifted-messenger)

### Expected behaviour

Hi everyone,

I apologize if the question have already been asked, but I couldn't find a thread specifically about this.
I've integrated GiftedMessenger to my application and when I start writing a message the all view goes up in order to give some space to the keyboard. The problem is that my navigation bar goes up too.

Does anyone have found a way to keep it at it's place whatever is going on around it ? 
I tried with absolute style positionning but doesn't seem to work. Also tried to contain my <GiftedMessenger />component in a <ScrollView />, unsuccessful.

I'm a bit of a newbie in react-native : maybe I'm missing something obvious. I apologize for my bad english.
Thanks you all.

**Comment by cridenour** [comment]
I have to think this is more of a question for their library than ours - I've never had the NavBar disappear when showing the keyboard.

**Comment by aksonov** [comment]
@Brokray I agree with @cridenour, it looks not our component failure. Personally i've been using gifted messenger at the past, but migrated to  own solution for better keyboard handling and better auto-scroll to bottom using inverted scrollview (because scrollTo will not work good for large datasets). You may check example for react-native-xmpp component.

**Comment by Brokray** [comment]
@cridenour Yeah... That's what I thought but I needed to be sure. I posted the exact same question on their library : will see. Thanks anyway !

@aksonov Thank you for your answer, I will check this example. I may migrate to my own solution as well for the exact same reason, that could be really helpful.
