### ISSUE TITLE
Is Switch the only way to restore navigation state?

### ISSUE THREAD

**Issue by ronaldheft** [aksonov/react-native-router-flux#973]
What is the recommended way to restore the navigation state from a store?

I've played with the `Switch` component and I'm able to restore my tabs views using the component. How do I restore non-tabbed views?

For example, if I push a scene onto a tab, how do I restore to that the scene in the tab? I assume I'll need logic for the scene to know the proper onBack / onLeft functionality after a restore, but I haven't made it to that point yet.
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.30.1
- react-native v0.30

**Comment by sckoh** [comment]
have you found the answer? I'm trying to do the same thing
