### ISSUE TITLE
[Question] Equivalent of configureScene

### ISSUE THREAD

**Issue by rclai** [aksonov/react-native-router-flux#977]
I know that `configureScene` has been deprecated, but how would you go about doing it using the new API? I also saw that the RN team has just killed `NavigationAnimatedView` according to [this](https://github.com/facebook/react-native/releases/tag/v0.30.0), so what now?

**Comment by sibelius** [comment]
@aksonov what is the equivalent of configureScene on the newest version?

**Comment by sibelius** [comment]
@rclai u can try to use https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#animation

**Comment by rclai** [comment]
Thanks.
