### ISSUE TITLE
Navigation Titile on Android is in additional View instead of just being Text

### ISSUE THREAD

**Issue by lesniakania** [aksonov/react-native-router-flux#98]
Because of that, I'm not able to center navigation title properly on Android.
See the pictures.

iOS (good):
![ios-title](https://cloud.githubusercontent.com/assets/193863/12049266/57a96d84-aee5-11e5-8621-06887ddecdf6.png)

![ios](https://cloud.githubusercontent.com/assets/193863/12049216/c56ddcac-aee4-11e5-8ca1-cb36a9251b18.png)

Android (bad)
![android-title](https://cloud.githubusercontent.com/assets/193863/12049259/3e95f358-aee5-11e5-9866-9a1386d05e43.png)

![android](https://cloud.githubusercontent.com/assets/193863/12049217/c5728dd8-aee4-11e5-8dfb-bfc8a95cf7c8.png)

My code:
```
<Router navigationBarStyle={styles.navBar}
// ...
</Router>
```

```
let styles = StyleSheet.create({
  navBar: {
    backgroundColor: colors.green,
    borderBottomColor: '#2ECBC7',
    borderBottomWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  }
});
```

**Comment by aksonov** [comment]
It seems exNavigator issue, they promise to finish it soon...
https://github.com/exponentjs/ex-navigator/issues/24

**Comment by delta1** [comment]
hi @lesniakania see the PR above for a workaround

**Comment by lesniakania** [comment]
@aksonov Thanks for pinging me. Although I'm a little big confused, I see you merged it to your master, but I can't see these changes in the `ExRouter`.

When I apply these changes manually in my local copy of your library, it works for me, so nice to have this workaround :]

**Comment by delta1** [comment]
@lesniakania Looks like a regression from this recent commit: https://github.com/aksonov/react-native-router-flux/commit/3025c02a341d7e09f8c35ac929d4a343302d63fe 

@aksonov did you commit from an old version?

**Comment by aksonov** [comment]
@delta1 fixed. Strange, i always try to pull before commit...

**Comment by delta1** [comment]
Confirming it's fixed, was just about to send a PR. Thanks @aksonov !
