### ISSUE TITLE
Interpolators are off

### ISSUE THREAD

**Issue by blackxored** [aksonov/react-native-router-flux#981]
There are some issues with transitions on this project, as well as with NavigationExperimental, interpolators seem "wrong" on iOS.

Here are my findings:
1. On this project's NavBar. Setting `direction=vertical` or (as of recently) `animation=fade` for a scene still triggers an horizontal interpolator for the navbar title (the one where the title fades and slides horizontally). It should either by a fade, or stay in place, but definitely completing a non-horizontal transition for the view with an horizontal transition for the navbar title shouldn't be by design.
2. NavigationExperimental's fault (BTW props for letting us set `animationStyle` so we don't have to monkey-patch all the way down) on horizontal transitions. On iOS there should not be any scaling (I've removed this) and no opacity transitions (I left them on since they seemed cool, but it's not default iOS behavior).
3. I can't even start with vertical transitions, see any native iOS apps for details.

**Comment by cridenour** [comment]
Hey @blackxored - thanks for the feedback. The few "design" elements of this library could definitely use a closer look. I wonder if there are things we can do to hide the inaccuracies of NavigationExperimental in either this library or our branch of NE - https://github.com/aksonov/react-native-experimental-navigation

**Comment by mastermoo** [comment]
Hey I would really like to see more "native" transitions by default.

I tried to animate the Push-Transition like in iOS, see below:
![](http://i.giphy.com/l46CbnSGxcMvNI2BO.gif)
The scaling and opacity transitions are gone, only translateX stayed and the NavigationCard got a shadow which fades out on swipe-end.

There are still a few issues, however:
- The Back Button stays in place (it should slide horizontally like the title of navbar)
- Vertical Transitions triggers the same transition as the horizontal one, see below gif.

![](http://i.giphy.com/3o6ZsXupLLLHyrh8fm.gif)

Am I missing something with the vertical transitions?

**Comment by blackxored** [comment]
@mastermoo Sign me when we both have some free time, as I've also worked on this area.

**Comment by slyfox4** [comment]
@mastermoo Hi! Can you share your code for Push-Transition like in iOS?

**Comment by luco** [comment]
@mastermoo It seems that react native reads scenes from top to bottom, so in this case, the `direction="vertical"` is on bottom, and the code never goes thru horizontal animation.

I'm trying to figure it out.
