### ISSUE TITLE
props disapear when changing scene using redux store

### ISSUE THREAD

**Issue by radosch** [aksonov/react-native-router-flux#983]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v0.31.0-rc.0
  "redux": "^3.5.2"
### Expected behaviour

following this example
https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md

I would expect that props / scene information will be show, when I switch scenes.
### Actual behaviour

On first call dashboard route, I can use {this.props.routes.scene.title},
after navigating to ProfileScreen scene, and back, it wont show up anymore.
### Steps to reproduce

```
              <Scene key='main'
                tabs='true'
                tabBarStyle={styles.tabBarStyle}
                tabBarSelectedItemStyle={styles.tabBarSelectedItemStyle} >
                <Scene
                  key='dashboard'
                  hideNavBar={true}
                  component={DashboardScreen}
                  title='Dashboard' icon={TabIcon} hideStatusBar={true}
                />
                <Scene
                  key='profile'
                  component={ProfileScreen}
                  title='Profile'
                  icon={TabIcon} />
              </Scene>
```

**Comment by neeboo** [comment]
Same problem to me... Did some work on reducer.js and Router.js though... Somehow with ActionsConst.BACKACTION, it will calculate the parent sceneKey, then use the Actions.callback method to dispatch actions.type only... No routes related props will be sent over to redux store...
