### ISSUE TITLE
Example of a simple TabBar

### ISSUE THREAD

**Issue by DominicTobias** [aksonov/react-native-router-flux#988]
Hi, thanks for this project I've found the API on the whole intuitive and sensible. I see there's a `TabBar` but I can't find a description of what it is, or how to use it.

I want to have a global bar at the bottom of my app with some buttons which navigate to top level scenes (like https://facebook.github.io/react-native/docs/tabbarios.html)

I haven't ran "Examples" but it looks like there is a custom NavigationBar which loads in a slidey side drawer? It also doesn't appear to use `TabBar`. I find it confusing how a `tabbar` scene is put adjacent to the other scenes - am I supposed to somehow do this to have a bottom tab bar?

I could just make my own component and use `Actions` to navigate to pages, but I think there must be a recommended way of doing it using `TabBar`? Thanks.

**Comment by cridenour** [comment]
While we don't have anything simple regarding the tab bar, check out the detailed example as a starting point. 

PRs welcome once you figure it out ;) 

https://github.com/aksonov/react-native-router-flux/blob/master/docs/DETAILED_EXAMPLE.md

**Comment by sbourlon** [comment]
I am interested in that example too!
