### ISSUE TITLE
Navigation retains previous view on top of another (Map)

### ISSUE THREAD

**Issue by jeveloper** [aksonov/react-native-router-flux#989]
### Version

Tell us which versions you are using: 

Android ONLY
- react-native-router-flux v3.32
- react-native v0.30.0
- react-native-maps v0.7.1
### Expected behaviour

View A
contains a mapview 

View B 
contains a mapview

View A button takes to view B (Actions.viewb) and View A is fully hidden
### Actual behaviour

View A's mapview appears on TOP of View B
### Steps to reproduce

View A

```
render() {

   return (
     <View style={styles.container}>
       <MapView
         key="viewa"
         cacheEnabled={false}
            style={styles.map}
            initialRegion={this.state.region}
          >
            <MapView.Marker coordinate={this.state.coordinate}>
               <Text style={{color: 'red'}}>Test</Text>
            </MapView.Marker>
          </MapView>
       <View style={styles.buttonContainer}>
         <TouchableOpacity onPress={()=> {  Actions.viewb({type: 'push'}) } } style={[styles.bubble, styles.button]}>
           <Text style={{ fontSize: 20, fontWeight: 'bold' }}>-</Text>
         </TouchableOpacity>
         <TouchableOpacity  style={[styles.bubble, styles.button]}>
           <Text style={{ fontSize: 20, fontWeight: 'bold' }}>+</Text>
         </TouchableOpacity>
       </View>
     </View>
   );
 }
```

View B

```

render() {


   return (
     <View style={styles.container}>

         <MapView
           key={this.state.rkey}
            style={styles.map}
            initialRegion={this.state.region}
            cacheEnabled={false}
          >
            <MapView.Marker coordinate={this.state.coordinate}>
               <Text style={{color: 'red'}}>Test BBB</Text>
            </MapView.Marker>
          </MapView>
       <View style={styles.buttonContainer}>
         <TouchableOpacity onPress={Actions.viewa } style={[styles.bubble, styles.button]}>
           <Text style={{ fontSize: 20, fontWeight: 'bold' }}>-</Text>
         </TouchableOpacity>
         <TouchableOpacity  style={[styles.bubble, styles.button]}>
           <Text style={{ fontSize: 20, fontWeight: 'bold' }}>+</Text>
         </TouchableOpacity>
       </View>
     </View>
   );
 }

 }
```

navigation is 

```
          <Scene
                key="viewa"
                component={viewa}
                initial={true}
                />

                <Scene
                  key="viewb"
                  component={viewb}
                  />
```

Can someone suggest , either modify the state of view A BEFORE it focuses on View B or finding a way that during the PUSH , a component such as mapview is somehow demounted or at least not dispalyed.
I believe this may be related to RN 29/30 changes.

Thank you

**Comment by danscan** [comment]
@jeveloper Have you attempted to reproduce this issue using plan `NavigationExperimental` (without `react-native-router-flux`).  Any results?

If not, I may try it so to hone in on the real problem.

**Comment by danscan** [comment]
@jeveloper: So I just tested this with `NavigationExperimental.CardStack` and `react-native@0.31` (**without** `react-native-router-flux`).  The issue still occurs.

Example component: 
```javascript
import { NavigationExperimental } from 'react-native';
import MapView from 'react-native-maps';

export default () => (
  <NavigationExperimental.CardStack
    navigationState={{
      index: 0,
      routes: [
        { key: 'MAP_1' },
        { key: 'MAP_2' },
        { key: 'MAP_3' },
      ],
    }}
    renderScene={() => (
      <MapView style={{ flex: 1 }} />
    )}
  />
);
```

When the `index` (in the `navigationState` object) is `0` (i.e. the root route is the current route, and the only route rendered), the map works fine:
![reactnativemapsnavigationexperimentaltestindex0](https://cloud.githubusercontent.com/assets/1638987/17720447/fc54b2d4-63ef-11e6-9d45-4dcaec526d5d.gif)

When the `index` is `1` (i.e., a second route was pushed, and is now the current route (and the previous route is rendered behind it), the issue occurs:
![reactnativemapsnavigationexperimentaltestindex1](https://cloud.githubusercontent.com/assets/1638987/17720442/ed8c5e96-63ef-11e6-8ee9-268472f2674e.gif)

**Comment by jeveloper** [comment]
Whoa, thank you @danscan , that is pretty serious issue, i can see that RN is tweaking Nav constantly through commits, can i assume that the map lib is at fault of not detecting unmounting or a different type of change?

**Comment by danscan** [comment]
@jeveloper It appears to be the Android implementation of MapView only.  It doesn't appear that anything on the JS side is directly at fault... on iOS this behaves as expected.

**Comment by danscan** [comment]
@jeveloper Drilling down even further, it seems like if you have many map view's rendered, and you set their `style`s to something including `position: 'absolute'` this issue occurs.

I imagine something related to drawing the frame contents is at fault.

**Comment by danscan** [comment]
@iiitmahesh In the app that I used `react-native-maps` in, I had to modify its navigation stack such that nothing would render underneath a map.  This issue turned out to have nothing to do with `react-native-router-flux` (though I think any user implementing navigation these days should use `react-navigation` or `react-router` instead, as they have much cleaner APIs and sources!)
