### ISSUE TITLE
Passing the Navigation title in Action

### ISSUE THREAD

**Issue by iZaL** [aksonov/react-native-router-flux#99]
I know you are working on the V2 of this great lib. so I thought in case you haven't thought about this feature where we can pass the route's title as a prop while navigating 
ex:
    Actions.mediaEntityScene({
      title:'title for the scene'
      data: media
    });

**Comment by aksonov** [comment]
It should work out of the box now, isn't? 

Pavel.

**Comment by iZaL** [comment]
you are right ! it is working !
