### ISSUE TITLE
UNMET PEER DEPENDENCY react@^15.3.0

### ISSUE THREAD

**Issue by afilp** [aksonov/react-native-router-flux#991]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v.0.30.0
### Actual behaviour

We get UNMET PEER DEPENDENCY react@^15.3.0

Why?

Because "react-native": "0.30.0" requires "react v15.2.1" and not higher.
### Steps to reproduce

1.
2.
3.

**Comment by adbl** [comment]
Hit this aswell, `react-native-experimental-navigation` v0... has a dependency on `react-addons-pure-render-mixin` `^15.1.0` which currently resolves to version `15.3.0` which depends on react with same version. Should react-native-experimental-navigation dependency version get locked to `15.1.0` ?

Interim solution do `npm install react-addons-pure-render-mixin@15.1.0` after install react-native-router-flux.

**Comment by jeveloper** [comment]
guys, its just a warning , it shouldn't break anything. You'll notice a lot of components for RN have this issue due to enormously quick release cycle of RN.

Don't forge to enjoy the summer :)

**Comment by af7** [comment]
@jeveloper It hurts to know that friends are now on sunny beaches and I am still struggling with what is warning or not and what breaks or not on the npm world! (struggling to develop in sunny and hot Athens...)

**Comment by jeveloper** [comment]
Ahhh Greece ! i've been to cyprus a long time ago, still havent been to Greece.

RN is sometimes very painful even though it exists for way of a year.
its tangled with watchman, npm (sometimes caching happens) and don't get me started developing for android.

**Comment by af7** [comment]
I develop for Android... (for start, then for iOS)

**Comment by aksonov** [comment]
Should be solved now with latest react-native-experimental-navigation

**Comment by agnaf** [comment]
This issue can be closed now
