### ISSUE TITLE
Why Actions.push() will make the left button hide?

### ISSUE THREAD

**Issue by jingpeng** [aksonov/react-native-router-flux#992]
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.32.0
- react-native v0.26.3

**Comment by jingpeng** [comment]
When I use Actions.push, the left button will be replaced by back button

**Comment by mattvot** [comment]
Try adding the renderLeftPutton prop to all the scenes you want the button to appear.

**Comment by lukabers** [comment]
Any solution?
