### ISSUE TITLE
How to navigate to a new scene with onRight

### ISSUE THREAD

**Issue by abhisuri97** [aksonov/react-native-router-flux#993]
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.32.0
- react-native v0.26.3

I am relatively new to redux so please bear with me here:

I have an action defined in `actions/index.js` called `changeScene`. The intended behavior is that when this action is called, then the scene will change to the scene defined to the one with a key matching `scene`. It is defined as follows:

```javascript
export const changeScene = (scene) => {
  return {
    type: 'CHANGE_SCENE',
    scene: scene
  }
}
```

In my reducer, I have the following lines of code:

```javascript
export default function reducer(state = initialState, action={}) {
  switch (action.type) {
    case ActionConst.FOCUS:
      return {
        ...state,
        scene: action.scene
      }
    case 'CHANGE_SCENE':
      return {
        ...state,
        scene: action.scene
      }
    default:
      return state;
  }
}
```

My routes have roughly this structure:

```javascript
<Provider store={store}>
    <RouterWithRedux>
        <Scene key="root">
        <Scene key="intro" component={Intro} initial={true} hideNavBar={true} title="Intro"/>
        <Scene 
           key="eligibility" 
           component={Eligibility}
           title="Eligibility"
           rightTitle="Next"
           onRight={()=>store.dispatch(changeScene('intro'))}
        />
       ...
```

However this is not working. Could someone give some insight as to why? I cannot seem to do console.log on the reducer with react native.

**Comment by irisSchaffer** [comment]
Any reason why you are not using `Actions.sceneName()` for the navigation?

```
import { Actions, Scene } from 'react-native-router-flux'

//...

<Scene
	key="myScene"
	title="My Scene"
	component={MyScene}
	rightTitle="Next"
	onRight={() => {
		Actions.myOtherScene()
	}}
/>
```
